### ISSUE TITLE
Fonts Selection missing in Hydrogen

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#10]
The Font Picker is not present in the Gantry Admin.

**Comment by w00fz** [comment]
The field is in gantry5 we just don't have any use for it. We are planning to have it implemented for hydrogen.
Thanks for opening an issue about it so we don't forget :)

**Comment by mahagr** [comment]
I'm going to close this one as #13 has better description of the issue. Thanks for the reminder!
