### ISSUE TITLE
Responsive Menu issues

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#100]
It will take too much time (and writing) to explain it, so please watch the video below:

http://youtu.be/hPs4ZBou7hA

Basically, the HTML element are still being shown where they shouldn't be so the :hover effect is applied on them. It also shows the "active" menu item even though it is on the previous "page".

The second issue, which is really not that important, is reproducible in Firefox only. I know that the users are not supposed to resize their browser but still, it's a bit annoying. The hamburger icon does not disappear when you resize the browser back. In Chrome it disappears.

*I put these two problems in one issue as they are a bit related. Sorry if I'm wrong*

**Comment by w00fz** [comment]
For the sake of convenience I'm going to add tasks out of the two issues just so it's more clear.

- [ ] In offcanvas menu, if a sublevel is shorter than the parent, the parent elements bleed through
- [ ] In firefox, the matchMedia is not working properly for hiding/showing the hamburger icon.


Good catches by the way. Thanks for the video and detailed explanation. I'll look into those.

**Comment by JoomFX** [comment]
Thanks @w00fz :)
