### ISSUE TITLE
menue item on a single row

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1000]
Hello
my menu has 16 items. On my computer they are on a single row on others on two rows. The last version of this site was on gantry 4, menu behaviour was uniform everywhere, all in a row.
How can obtain the same using Gantry5?

**Comment by w00fz** [comment]
This is mostly a CSS issue, we do have support for dropdowns in case they fall into multiple rows, so it is still usable, but it is your job to ensure they fit in the view and if not make the proper adjustments, like perhaps reduce the font size and padding or regroup in a different way the menu items. 16 menu items is quite a lot of items. 

I don't consider this an issue with Gantry nor Hydrogen.
