### ISSUE TITLE
404 page title in English

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1001]
The browser title for the 404 error page always seems to be in English.

I did a search on this in Gantry 5 and it appears that are a lot of places where this literal "Page not found" is hardcoded in english (presumably one of these ends up in the browser title) - see screenshot.
![2015-11-12_10-26-48](https://cloud.githubusercontent.com/assets/11683218/11116177/b60c42e4-8928-11e5-9927-00aa7376b264.png)

I have a member who's site is correctly set up in Spanish language yet the browser page title shows english on the 404 page when the main message in the body of the page is correctly in Spanish.

![2015-11-12_10-27-17](https://cloud.githubusercontent.com/assets/11683218/11116210/ff0c0380-8928-11e5-8044-827e985803d8.png)

Link to forum topic:http://www.rockettheme.com/forum/joomla-template-ambrosia/250491-changing-404-page-not-found?start=0#1249956

.

**Comment by marktaylor46** [comment]
Specifically line 34 of /components/com_gantry5/gantry5.php line 34 is hardcoded in english language.

**Comment by marktaylor46** [comment]
Another member with same issue here:
http://www.rockettheme.com/forum/joomla-template-antares/256654-404-page-system-message-error-translate?start=0#1281642

**Comment by mahagr** [comment]
Yeah, the error is hard coded into English as it comes from an exception. Generally I do not want to translate our error messages, but I think this one might be exception as its not really an internal error where we want to be able to understand the error message.

**Comment by marktaylor46** [comment]
Also the hardcode reference that needs to be changed is  /components/com_gantry5/router.php 'Page not found' line 24 :
