### ISSUE TITLE
Not needed "Available Themes" in WordPress

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1004]
When you click on the Gantry Logo in the top bar of admin it takes you to not needed page "Available Themes" with unclickable "Configure" button.

https://monosnap.com/file/mnmptk4slBLa7WiahyddPFM2d4cxU0.png

**Comment by mahagr** [comment]
I have plans for this page in the future as our theme installer, where you can not only view installed themes but also install (and update) new ones.

**Comment by newkind** [comment]
Ok, then let's fix at least the "Configure" button :)

**Comment by mahagr** [comment]
Yes, that we need to fix. We also need to find a way to go to (preview or edit) other themes than default.

**Comment by newkind** [comment]
We can try to hook into the WordPress preview mode for unactivated themes.

**Comment by mahagr** [comment]
I added preview links to all Gantry themes and fixed the Configure button (for now its only available for currently selected theme).

I will add the missing `Configure` links later when we implement the installer stuff.
