### ISSUE TITLE
fresh wp & gantry5 with none home outline

### ISSUE THREAD

**Issue by rootcrop** [gantry/gantry5#1007]
Another fresh install of WordPress 4.3.1, 
Gantry 5.2.2, Timber 0.22.1 and fresh gantry_g5_hydrogen theme
and the same story 

![hydrogentheme0](https://cloud.githubusercontent.com/assets/15847603/11164348/16d1c126-8aff-11e5-8d62-b8a5341075d3.jpg)

In this dashboard / hydrogen theme there are outline:
none selected (in gray): global defaults, system defaults
item with options selected (in black): base outline, body only, error, offline
Options HOME is missing.

Is that bug or feature?
Or is there any simple explanation  i don't get?

**Comment by newkind** [comment]
Hi,

The Home outline is currently missing but we'll add it in next couple days. Right now all you need to do is to :
1. Create new "Home" outline
2. Assign it to Front Page
3. In Layout Manager use "Load" button to load the Home layout
4. Save changes

Thanks,

**Comment by rootcrop** [comment]
Noted, thanks a lot!
