### ISSUE TITLE
Iphone5 and Safari doesn't "resize" according to responsive settings.

### ISSUE THREAD

**Issue by artisanwebandprint** [gantry/gantry5#1008]
Hello,

We're testing the newly launched Gantry 5, custom designed website http://jimwan.com and it's looking great across all browsers and devices except Safari (under 1200 pixels, doesn't resize) and Iphone 5. Since it's working on all other devices, I wonder if something in the framework itself is not playing well with Apple software. Please take a look here at this short video:

http://screencast.com/t/p4c2iHyYb

Please advise.

Warm Regards,

Dawn

**Comment by artisanwebandprint** [comment]
Also, Dropdown menus do not show up in Safari.

Thanks,

Dawn

**Comment by w00fz** [comment]
Hi there!
I just tried your site on the Apple Simulator, since I have an iPhone 6, and I see no issues with your site:

![ios 9 1 13b137 2015-11-14 15-28-29](https://cloud.githubusercontent.com/assets/11734/11166350/990f9bd8-8ae4-11e5-880d-a9b89b5b5444.jpg)

I have a feeling that the website simulator you are using might be throwing a false positive representation of the site in the actual device.
If you have an iPhone 5 laying around or someone that does have one, I'd suggest you to test with that.

**Comment by w00fz** [comment]
Hi, were you able to verify this?

**Comment by artisanwebandprint** [comment]
I checked on Iphone 5 and it does not work. Also in Safari, the dropdown menus do not work.

Warm Regards,

Dawn

**Comment by Bokelmann** [comment]
wonder wich version of Safari is that exactly?

**Comment by mahagr** [comment]
I agree. It sounds like an old version of Safari that doesn't properly support flexbox in CSS.

**Comment by artisanwebandprint** [comment]
Hello,

The version of Safari is up to date and the newest available for a PC (5.1.7). I discovered that the issue is that hover does not work. You must click on the small arrow to see the dropdown menu. This is the only browser in which that is happening. Is there a way for hover to show in Safari with Gantry?

Best,

Dawn

**Comment by w00fz** [comment]
Hello, that explains it.
Unfortunately Safari for windows has been discontinued long time ago, version 5 is very old (we are currently at version 9) and we do not support it.

http://docs.gantry.org/gantry5/basics/system-requirements#browser-requirements

**Comment by artisanwebandprint** [comment]
Thanks for all of the responses. I'll see if I can find a simulator for Safari 9. 

PS. I loved working with Gantry 5. Thank you for such a wonderful templating system. It has opened up designing from scratch again for me.

Warm Regards,

Dawn
