### ISSUE TITLE
Suggestions for UI

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#1010]
1- We often need to enable/disable particles in a layout. To do this we must edit the particle to toggle on/off.
Can't we have this toggle on the particle box we place on a section?
2- Currently we need 1 outline for home and 1 for the rest for the sake of module assignments. In order to use use a unique layout for the whole site can't we have another toggle on the particles to "enable/disable on home"?
.

**Comment by w00fz** [comment]
Sorry this got unanswered.

The first question is not something we can manage to do, not now and not with the current UI. There is just no room for it. My advice is to just edit the files manually if you need to quickly disable a big amount of particles. Even if we had an UI for it, manual edit could hardly be beatable in terms of speed.

Regarding point 2, I believe this is something that's going to be resolved by itself with the inheritance implementation. You will be able to inherit any section or particle from Home but most importantly, we are reintroducing the Layout in the Base Outline, so you can now manage things differently.
