### ISSUE TITLE
Clearing the outline causes the flexslider not to function properly

### ISSUE THREAD

**Issue by coolman01** [gantry/gantry5#1011]
So, I started again, and created a blank joomla site.
I uploaded gantry 5.2.3 and isotope
I set up the base outline and removed the demo css
As a multilingual site I created the defaults for each language (german and english) and left the original for All languages
In the german default I cleared the layout
I added some basic stuff - logo, social, language changer, page content, copyright, branding, to-top
I then followed the steps to recreate the "Above" item in the demo using the flexslider in "showcase" mode using the expanded section
Adding everything in terms of content worked fine BUT
Only the first item shows up, no thumbnails and no slider

I then tried to create the same thing using the english template but without clearing it and the same thing happened - the first item shows, no thumbnails, no slider

Something isn't working right.
I'm happy to provide access to the site you can see here : http://dearmaharaji.website/again/index.php/de/

**Comment by arifinrt** [comment]
Hi @coolman01 I have replied your post here http://www.rockettheme.com/forum/joomla-template-isotope/250919-no-animation-in-flexslider-thumbnails-not-showing?start=0#1251328
