### ISSUE TITLE
<div class="g-menu-overlay"> leaving large empty space Safari and mobile

### ISSUE THREAD

**Issue by JeyjooMilano** [gantry/gantry5#1012]
We developed a new website and find a large empty space at top of page caused by #g-page-surround { min-height: 100vh;}.
This is particularly evident on mobile and iMac.

**Comment by w00fz** [comment]
That overlay is generated automatically for the Offcanvas and Menu. I think while developing your theme you might have removed extra SCSS that were needed.
Please have a look at Hydrogen to see how it is styled. You can also reference https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/scss/nucleus/_nav.scss#L256-L266
