### ISSUE TITLE
Menu order changes

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1016]
Using Wordpress, editing the menu under Appearance > Menu changes the order of menu items.

**Comment by mahagr** [comment]
It should be changing the order of menu items; both WP and Gantry should have the same ordering.

**Comment by dudewithamood** [comment]
When I change the Navigation Label in Appearance > Menus the item changed becomes the last item in the g5 Menu Editor resulting in the order being different between WP ang g5.

**Comment by mahagr** [comment]
@newkind Are you able to reproduce this issue?

**Comment by dudewithamood** [comment]
This is happening for me using Wordpress 4.3.1, Gantry 5.2.3 and Hydrogen 5.1.6.

**Comment by newkind** [comment]
Personally can't replicate it. Tried renaming item labels and moving the root level items (with child items) and the changes were reflected both in the Gantry 5 Menu page and front end.

**Comment by dudewithamood** [comment]
@newkind I'm putting up a test site so you can see it in action... how do I share login details with you?

**Comment by newkind** [comment]
You can PM me on Gitter - the same nickname as here on github.

**Comment by newkind** [comment]
Legit issue, needs to be fixed.
