### ISSUE TITLE
Saving menu fails if menu items have been checked out

### ISSUE THREAD

**Issue by procc1** [gantry/gantry5#1019]
I'm having this message when I try to save anything in Menu, why?

> 400 Bad Request
> Oops, Saving menu failed: JTableMenuType: :store failed<br />The user checking out does not match the user who checked out this menu and/or its linked menu module..

**Comment by procc1** [comment]
All ready found problem :) 
These "Check-in" lock's on menu items, in joomla menu editing, was not allowing gantry5 menu editor to make any changes.

**Comment by mahagr** [comment]
I'm going to reopen this one as we need to deal with this...

**Comment by sidorovanthon** [comment]
So do somebody have any kind of manual salvation for this issue?

**Comment by mahagr** [comment]
Do a global check in for menu items and it should be fine.

**Comment by mahagr** [comment]
There's not much that I can do if someone has checked out a menu item or assigned module, so I fixed this by disabling saving and displaying an alert message that explains why you cannot change the menu.

**Comment by kat05** [comment]
This is working fine for me in latest CI.
