### ISSUE TITLE
Suggestion request: turn menu items on/off

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1020]
Just like how a particle can be turned on and off in an outline, it would be useful to be able to do the same with menu items in the g5 Menu Editor.

Use case: Set up entire menu structure of a new site however when the site goes live some pages are not ready and so it would be useful to turn the menu item off until the page is ready (rather than deleting it or hiding it with CSS).

**Comment by newkind** [comment]
Hi,

That won't be possible because Menus don't have support for outline instances - you can just create a separate menu and in layout manager assign it to the ceratin page.

Jakub

**Comment by mahagr** [comment]
Actually the support for hiding individual menu items is already there; it just needs to be enabled.

**Comment by newkind** [comment]
Well yah, but this isn't about disabling menu items only - it's about selective disabling menu items per outline/assignment. Like a menu variant per outline/assignment.

**Comment by dudewithamood** [comment]
To clarify, my use case only requires disabling menu items in the Menu Editor, not selectively disabling per outline/assignment.

**Comment by w00fz** [comment]
I think this could be a nice enhancement for the Menu Editor.
If I understand correctly you are suggesting to have an enable/disable toggle for each Menu Item, like we do for Particle in the Layout, and be able to easily turn that on or off without having to pass through the platform.

This would literally change nothing on the platform side or on gantry, except that when we are processing the menu items to render on front-end, we would just skip the disabled menu items.

If the menu item that getting disabled was a Parent then, of course, no children would render as well.

I think this could be a nice feature :)

**Comment by mahagr** [comment]
I agree on this being a nice feature to have.

**Comment by sural98** [comment]
Toggle should not be in the modal, just on the menu item itself. It should be a 1-click operation.

**Comment by newkind** [comment]
That would bloat the UI

**Comment by dudewithamood** [comment]
This is what I'm thinking, in line with elsewhere:
![image](https://cloud.githubusercontent.com/assets/15866807/11343314/22a993ae-9214-11e5-9119-43808b304870.png)

**Comment by w00fz** [comment]
Yeah I think how you are suggesting @sural98 would just make it extremely confusing. Besides, the enabling / disabling action is not very common, it doesn't really require immediate access from the menu item level.

I do like @dudewithamood suggestion, it's more in line and consistent with the rest of admin.

**Comment by w00fz** [comment]
This is now implemented:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11734/15232559/fda684c6-1856-11e6-86bf-33f7fc36f33d.gif)

**Comment by JoomFX** [comment]
Very nice :wink: 
Thanks Djamil!

**Comment by dudewithamood** [comment]
Awesome everyone - many thanks.
