### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1023]
When g5 is used to upload an image, such as when adding an image to Logo / Image under Particle Settings, the image is not uploaded in a way that is accessible via the Media Library (in Wordpress).

Is this a feature or behaviour-by-design? I would have assumed it would upload into /wp-content/uploads

I'm using the Logo / Image particle to place images in various places but if I want to access these images when editing content I must rather upload in the Media Library and then edit the particle settings.

**Comment by w00fz** [comment]
The Gantry File Picker works with the same paradigm of any other overrides and streams.
When you use `gantry-media://` stream to reference a file, you are, behind the scenes, targeting in cascade different folders. In wordpress case this means you are targeting:

1. The `gantry-theme://images` stream (wp-content/themes/yourtheme/images)
2. `/wp-content/uploads` folder (where all wordpress media uploads go)
3.  `/wp-content/plugins/gantry` (root of the gantry plugin)

This means that the specified file will be looked for, in order, top to bottom, until found (or not found).
So if you reference `gantry-media://logo.png` and it does exist in the theme **images/** folder, it will be used, if it doesn't exist but exist in `wp-content/uploads/` then it will use that, etc, etc.

Now the same goes similarly for uploading. When you open the File Picker you are presented with the Stream paths, folders and files of all the 3 lookup directories are merged together in this virtual directory you have access to.
When you upload, the file will always end up in a the custom folder of your theme `wp-content/themes/yourtheme/custom/images/` and its folder structure as well as files, will follow this virtual directory that you've been presented with. This allow to easily upload an image named exactly the same as another found in wordpress uploads, without touching the original one.

Try this, find any image and call it **example.png**, upload it with wordpress media. Head back to Gantry and use the image as logo.
Now find another image, call it also **example.png**, head back to the G5 File Picker and upload it in the same location you see your original one.

You will notice that it looks like you just overwritten the original one, as only the new one shows up in the File Picker and if you refresh the front-end, the logo now uses this new example.png as expected.
Although if you dig into the wordpress media, the original file is still there. And also if from the File Picker you trash the image, the original one will come back.

The whole point of this mechanism is to interface with the platform with safety guards and keep everything that is Gantry related as much contained as possible. Every platform implements their own media manager in different ways and they should still be used to manage your global medias. A showcase image, a logo, a background. Gantry offers just a way to overwrite those global images without being intrusive nor destructive.

If you are facing yourself needing to access media files from outside Gantry, like a new article in wordpress or a 3rd party plugin, the media manager of your platform of choice should be used. Anything uploaded via the media manager of your platform will be always available from Gantry AND safely-overridable like explained above.

I know this is a long reply and I'm sorry to have bothered, I really wanted to make clear how this concept  works and why.  We will also look into possibilities to integrate with the platform media manager but it's not going to be anytime soon. We have experiences with this and with both Joomla and Wordpress, it has never been easy and always very limiting. For Gantry uploading a file means just pure-upload and storage. For the platforms this has may other aspects, like Wordpress that automatically create various sizes for it.

**Comment by dudewithamood** [comment]
Thank you, I appreciate the explanation and it answers my question as I was looking to understand the thinking behind it. Your answer explains this perfectly.
