### ISSUE TITLE
Menu for mobile

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1024]
Is it possible to specify which menu is used as the Mobile Menu? It seems to default to the first menu in a layout however the first menu is not always the main menu.

**Comment by w00fz** [comment]
Yes, in the Layout open the settings for the Menu you want to become the Mobile Menu and select **Mobile Target**.

![mobile-target](https://cloud.githubusercontent.com/assets/11734/11349048/effe83ea-91de-11e5-8f70-eac155d5f57f.png)

**Comment by dudewithamood** [comment]
Oh wow, thank you - can't believe I missed this!

I tried it out and how it works is exactly how it should however the results are unexpected. I'll explain... if you look at the image below, this is a secondary menu where I override the Menu as set under Particle Settings in the Base Outline. But you'll notice it also carries through Mobile Target as True, which is exactly intended behaviour but results in this secondary menu being set as the Mobile Target (based on appearing prior the primary default menu in the layout).

![image](https://cloud.githubusercontent.com/assets/15866807/11359493/5009cf6e-9285-11e5-99e1-9606866577ee.png)

To get it to work the Mobile Target must also be overridden and set to False.

An even better way would be to have the default as False and override for the primary menu only.

Hope this helps someone.

**Comment by mahagr** [comment]
I would change mobile target in base settings as false and then set it to true in all layouts for the particle you would like to be the mobile menu, just as you said above.

I'm not sure if we can easily change the default value, though, as it will affect on some existing sites as well as we would need to release update for the templates.

**Comment by dudewithamood** [comment]
I suggest to adjust in the documentation rather than make any changes. It's simple enough.

**Comment by w00fz** [comment]
Maybe @FrugalGeek can make this more explicit in the docs?

**Comment by FrugalGeek** [comment]
On it!

**Comment by dudewithamood** [comment]
Thank you - you guys are awesome!

**Comment by FrugalGeek** [comment]
Added a section here:
http://docs.gantry.org/gantry5/particles/mobile-menu#mobile-menu-targeting

Hope it helps!
