### ISSUE TITLE
Dont work with WP Super Cache PlugIn

### ISSUE THREAD

**Issue by 84ck80n3** [gantry/gantry5#1029]
Gantry dont work with the WP Super Cache PlugIn:
https://wordpress.org/plugins/wp-super-cache/
If i use this PlugIn, i have a white Page with the content on the left side. No Warning-Messages. Just a blank page.
But for me ist not important, because Gantry is very very quick. Thanks for your Work!

**Comment by mahagr** [comment]
@jakub ?

**Comment by 84ck80n3** [comment]
Hello mahagr!
What is jakub?

**Comment by newkind** [comment]
Jakub is me - at least that's my name ;) So I just tried the WP Super Cache on my local G5 install and works fine. Caching seems to be working, no errors or blank pages.

Can you tell me what configuration did you used ? Can you enable WP_Debug in wp-config.php and in Theme settings > Extras (top right corner) > Platform Settings > Debug > Enabled ?

Thanks!

**Comment by 84ck80n3** [comment]
Hello Jakub!
I enabled wp_debug in wp-config and Theme settings.
Now its ... ähhh.... hmmm..... completely strange ;-)
In the Admin-Area i got follow message:
Warning: include(/opt/users/www/muckel50web47/html/wordpress/wp-content/advanced-cache.php): failed to open stream: No such file or directory in /opt/users/www/muckel50web47/html/wordpress/wp-settings.php on line 65

and

Warning: include(): Failed opening '/opt/users/www/muckel50web47/html/wordpress/wp-content/advanced-cache.php' for inclusion (include_path='.:/opt/php-5.6/lib/php') in /opt/users/www/muckel50web47/html/wordpress/wp-settings.php on line 65

and the Homepage looks very strange:

http://muckelfloh.com/wordpress/

Do you need the keyword? Ist just a playground, you can do what you want!

**Comment by newkind** [comment]
The homepage is a whoops error page.

The errors you see in the admin is not a Gantry 5 error and has something ot do with advanced cache.
```
Warning: include(/opt/users/www/muckel50web47/html/wordpress/wp-content/advanced-cache.php): failed to open stream: No such file or directory in /opt/users/www/muckel50web47/html/wordpress/wp-settings.php on line 65

Warning: include(): Failed opening '/opt/users/www/muckel50web47/html/wordpress/wp-content/advanced-cache.php' for inclusion (include_path='.:/opt/php-5.6/lib/php') in /opt/users/www/muckel50web47/html/wordpress/wp-settings.php on line 65
```
To get rid of the error on the front end can you please go to Theme Settings > Settings and in the Menu particle card select any of the existing menus, save changes and clear cache. This should solve the issue. Once this is done we can fight with WP Super Cache.

**Comment by 84ck80n3** [comment]
This Problem was just after i changed to the debug-mode. Before was ist ok. The Message is now away.
So, now WP Super Cache is activated and you see nothing on the Homepage, just the menu and a little bit Text.

**Comment by newkind** [comment]
Must be a conflict with AutoOptimize plugin because it's cached css file returns 500 Internal Server Error : 
http://muckelfloh.com/wordpress/wp-content/cache/autoptimize/css/autoptimize_f395436701b06f71b6c6264710b4c719.css

**Comment by 84ck80n3** [comment]
No, i deactivate Autoptimize and Wp Super Cache ist still activated, and the same Problem is on the Homepage.

**Comment by newkind** [comment]
Can you please clear the WP Super Cache cache as it still tries to load the mentioned above css file from Autoptimize ?

**Comment by 84ck80n3** [comment]
Ok, and we can see the Gantry Homepage ;-) So, ist a Problem with Autoptimize?

**Comment by 84ck80n3** [comment]
It works with Cache OR Optimize but dont with both. I prefer Optimize because on the Google SpeedTest has the Page now just 58 Points. Thats nothing.

**Comment by newkind** [comment]
Well there's definitely something wrong but not with Gantry. You need to check PHP error logs on your server - this might be something with server configuration ie. PHP memory limit or anything like that. If you don't know how to do it, you can ask you hosting provider to investigate that.

**Comment by 84ck80n3** [comment]
Ok, no Problem!
I will use it with Autoptize and then its PERFECT!
Thanks a lot for your help!!!!!

**Comment by newkind** [comment]
no problem :)
