### ISSUE TITLE
layout of items in "sample content" particle

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#103]
I have two requests; first: in "sample content" particle it could be possible to resize the height of the row? Second: in this kind of particle I can sort the order of the various items, but the layout is anyway displayed in a row ( A, B, C or B, A, C or C, A, B )... and what if I need a vertical layout, such as
A
B
C
I think that something like the choice of layout in sub -menu (vertical or in a row) inside this kind of particles could be a nice addition.

**Comment by w00fz** [comment]
You can click the [ + ] to add a new row and put a particle in there. That would make the particle render one on top of the other.

**Comment by beamaria** [comment]
Thanks Djamil, if I did that procedure,  the result is to have all my four items in a single row, like this
![senza titolo](https://cloud.githubusercontent.com/assets/11693902/7281233/840b9132-e928-11e4-9299-ef05b8fe7683.jpg)
I would rather have the items in a list 
name: pinco pallo
address: atlantic way
phone: 353 0001 22334455
email: info@pincopallo.com
I can't figure out how to put a particle inside the "new item" field

**Comment by kevlardev** [comment]
Ive added a new block variation, full-width, which you can place on blocks to force them to be 100% width and stack vertically. In the case of particles (like this sample content particle) it will also force all the child g-blocks inside to be vertical as well. So if you select this variation in the block tab when configuring the particle and apply, it should give you the intended effect.

**Comment by w00fz** [comment]
Also a temporary workaround for you is to create a custom CSS and add the following code:

```
.sample-content .g-block {
  flex: 100%;
}
```

**Comment by beamaria** [comment]
Thanks Djamil and Kevin; @w00fz :I tried your code in my custom scss and then recompiled the scss, but it doesn't work, the four items are still on the same row; anyway, since Kevin added this new block variation I think I can wait till it will be inside beta4 version ;-)
