### ISSUE TITLE
Strings in YAML files are not translated

### ISSUE THREAD

**Issue by baijianpeng** [gantry/gantry5#1030]
I had reported and reminded the RT team many times that they should care more about the language files. But it seems that you just don't know where is the problem.

Ok, today I made a screenshot to show you how bad the language files of Gantry 5 are.

Note: this screenshot is only one Tab of that settings page. In fact, every Tab has the same problem: only very few strings can be translated via the language files, many others were NOT included in the language files!!!

![gantry-language-file-sucks](https://cloud.githubusercontent.com/assets/1249063/11387133/afb48fb6-9362-11e5-8ca5-c2e423bc7973.png)

**Comment by adi8i** [comment]
Actually you write section and fields name in yaml file, it has nothing to do with language files.

**Comment by baijianpeng** [comment]
If you developers write  section and fields name in yaml files, how to
translate them?

If those  section and fields names can not be translated, how to
persuade people speaking non-English languages to use Gantry 5
Framework and Templates based on Gantry 5?

2015-11-25 13:55 GMT+08:00 Adrian <notifications@github.com>:

**Comment by w00fz** [comment]
This is known and something we have in our [Agenda](https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel).

A long and detailed discussion with propositions and plans for the future can be found in #84.
So there is no language file for YAML files, but you can still use foreign languages as labels in them.

I'm marking this as duplicate.

**Comment by alangarcia88** [comment]
2020 and still the same...

**Comment by mahagr** [comment]
Actually they can be translated now, there is just no script that gathers the translations together.
