### ISSUE TITLE
WordPress Base Item in Menu particle card doesn't have any menu items to choose from

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1033]
WordPress Base Item in Menu particle card doesn't have any menu items to choose from, thus it's not possible to create a splitmenu.

https://monosnap.com/file/RSo44lnoRsDfQIK7rPDzUBAjjSIz4d.png

**Comment by mahagr** [comment]
It looks like that [embed] is not handled as a shortcode (shortcode just gets removed), but its a filter in `the_content`.

See https://core.trac.wordpress.org/browser/tags/4.4/src/wp-includes/class-wp-embed.php
