### ISSUE TITLE
501 error when deleting custom outline

### ISSUE THREAD

**Issue by GeGeek** [gantry/gantry5#1035]
Hello,

i am on litespeed and i have a 501 error message when i want to delete a custom outline, previously created.
![capture](https://cloud.githubusercontent.com/assets/5159674/11465236/4507a508-9737-11e5-86c3-557dacf73cb6.PNG)

And this error message is not correctly formated :)

Thank you !

**Comment by mahagr** [comment]
Which platform are you in?

**Comment by GeGeek** [comment]
I'm on WordPress

**Comment by mahagr** [comment]
@GeGeek Do you still have the issue in latest version? Because of I remember fixing something like this.

**Comment by GeGeek** [comment]
@mahagr i didn't try it again, i'll try soon and tell you ;)

**Comment by GeGeek** [comment]
Hi @mahagr it's working now :)
Thanks !
