### ISSUE TITLE
Loading of Jquery as asset needs addtional support adding to Gantry 5

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1036]
I am raising this following a discussion about Isotope template (but it will apply to others too).

I have noticed that in Isotope multiple copies of JQuery are being loaded (and different versions). It transpires that JQuery is being loaded as an asset on the page settings but we really need a mechanism to tell Joomla to load JQuery so only one copy is loaded to:
1. avoid potential conflicts between multiple and different versions
2. improve efficiency by not downloading additional copies that are not required.

![2015-12-04_08-20-05](https://cloud.githubusercontent.com/assets/11683218/11584962/469535d0-9a60-11e5-879d-c912f8bd6916.png)

**Comment by mahagr** [comment]
@marktaylor46 This issue should be moved to Isotope template. G 5.2.6 adds support to work around this.

**Comment by marktaylor46** [comment]
Thank you - I have raised a JIRA to update all G5 templates to use this.
