### ISSUE TITLE
Help with the Twig syntax

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1038]
@w00fz @mahagr Hey guys,

I'd like to ask you for little help with the particle I'm developing :smile: 

Basically, I'd like to achieve the following layout (it is from my SativaFX G4 template):

![alt](http://i.imgur.com/7cHCIzE.png)

So, I have a `collection.list` and the user adds 9 items. What would be the Twig syntax so these 3 items are shown 3 in a row (3x3)?

I suppose it will be done with a `for` loop, but I'm not sure what the exact syntax should be. Here's the markup I'm trying to achieve:

```
<div class="g-grid">
	<div class="g-block">
		<div class="g-content">
			Item 1
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 2
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 3
		</div>
	</div>
</div>
<div class="g-grid">
	<div class="g-block">
		<div class="g-content">
			Item 4
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 5
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 6
		</div>
	</div>
</div>
<div class="g-grid">
	<div class="g-block">
		<div class="g-content">
			Item 7
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 8
		</div>
	</div>
	<div class="g-block">
		<div class="g-content">
			Item 9
		</div>
	</div>
</div>
```

Thanks a lot ;)

**Comment by JoomFX** [comment]
Alright, so I should use [Twig Batch](http://twig.sensiolabs.org/doc/filters/batch.html) but I still can't figure it out. Continue playing :smile:

**Comment by JoomFX** [comment]
Wow :smile: 

Here it is:

```
{% for row in particle.items|batch(3) %}
	<div class="g-grid">
		{% for item in row %}
			<div class="g-block">
				Item #
			</div>
		{% endfor %}
	</div>
{% endfor %}
```

I think I'm addicted to G5 and Twig :smile: 
Thanks guys ;)

**Comment by w00fz** [comment]
Pretty cool :+1:

**Comment by JoomFX** [comment]
Thanks @w00fz :100: :smile:

**Comment by mahagr** [comment]
I love twig too!

**Comment by adi8i** [comment]
@JoomFX Have you tried to replace `batch(3)` with something like `batch(particle.col)` ?

**Comment by JoomFX** [comment]
Hey Adi,

Yep, this is how I'm doing it, so I give the user an option to choose the number of columns ;)

```
{% for row in particle.items|batch(particle.columns|default('3')|e) %}
```

**Comment by adi8i** [comment]
Eh, thanks. I have an `input.number` then `|batch(particle.nr)` but it didn't worked. i lost about 1 hour to realize that was needed to resave the particle, the input was stored empty.

**Comment by JoomFX** [comment]
Ah... yah, these things can be very annoying!
That's why I always put `|default('...')`, just in case ;)
