### ISSUE TITLE
Can't delete widget from Menu Editor

### ISSUE THREAD

**Issue by olmostblue** [gantry/gantry5#1039]
Hi, on Wordpress in Gantry 5.2.4 I can't delete widget in the Menu Editor, if I drag it to the top don't appear the delete area. I've tried with different browser on Mac and Windows
![schermata 2015-12-04 alle 17 05 43](https://cloud.githubusercontent.com/assets/10565487/11594326/a3f33378-9aa9-11e5-89fe-054a1476e965.png)

**Comment by newkind** [comment]
Works fine for me. Can you do a hard refresh on your browser ? Do you have any JS errors on the menu page ?

**Comment by w00fz** [comment]
This seems to be working fine for me too.

**Comment by olmostblue** [comment]
I've tried to clean cache and cookies but nothing change, on the page I don't have JS errors... Now I will try to delete and reinstall Gantry

**Comment by olmostblue** [comment]
It's strange but if I a new widget in the menu I can delete the new one but not this in the screenshot

**Comment by w00fz** [comment]
Are you able to delete the old one after you dragged in a new one?

**Comment by olmostblue** [comment]
no, the old one continues to be non-removable... I've to delete and reinstall gantry but persist... In frontend i've hidden the widget with css but if i can delete it is better

**Comment by w00fz** [comment]
Could you inspect via dev tools and paste back the HTML for that widget you cannot delete?
Also am I understanding right that this widget is the only one you cannot properly delete?

**Comment by w00fz** [comment]
Is this still an issue? I think somehow your widget got stuck in the menu. All that gantry saves is in yaml files so you should be able to delete this manually from `wp-content/themes/<your-theme>/custom/config/menu/`.

Edit the `yaml` of the menu that has the issue and you should see the widget in question, remove it and you should be good.

Feel free to reopen with additional details/ways to reproduce this, if the problem persists.

Thank you!
