### ISSUE TITLE
Drag & Drop zones for widgets in menu aren't working properly

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1040]
There's something wrong with drop zone for widgets in menu. To make it work you have to drag it in a way where a menu item on the side turns blue and you have a black indicator visible otherwise it won't work.

Video : https://cloudup.com/c39lTUBQSJU

**Comment by w00fz** [comment]
This is known and it's technically right. You can drop only an item only before or after another item, when you are hovering over the container or in between the gaps of two items (which is still the container), you are not targeting an item which in return makes the drop area false.

Always drag and then hover over the item. Left to Half of the item means left of the item, Half to Right means right of it.

More infos #108

**Comment by newkind** [comment]
Then maybe we shouldn't display the vertical black line until the side menu item is hovered ?
