### ISSUE TITLE
Rounded Corner Turns Squared in Particle Settings Popups

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#1041]
If you click the Block tab then go back to the Particle tab in a particle's Settings popup, the corner goes from rounded to squared.

![screen shot 2015-12-04 at 11 33 06 am](https://cloud.githubusercontent.com/assets/4026828/11596506/fbb1c202-9a7a-11e5-8ead-027a7fbd3b18.png)

![screen shot 2015-12-04 at 11 33 02 am](https://cloud.githubusercontent.com/assets/4026828/11596507/fbb3b13e-9a7a-11e5-82c0-0f93c1fe20cf.png)

**Comment by mahagr** [comment]
Not sure if this is a bug as selected tab has different styling.

@w00fz what do you think?
