### ISSUE TITLE
Question: How can I set a background pattern in gantry5 / hydrogen template?

### ISSUE THREAD

**Issue by Attis35** [gantry/gantry5#1042]
Hello Dev Team,
I tried to modify the scss files to set a background pattern image for the entire website without success.
Could you please help me where to modify what?

Thank you in advance!

**Comment by adi8i** [comment]
Navigate to `template-name/custom/scss/custom.scss` and add
```
#g-page-surround {
    background-image: ......
}
```

Note that the background is behind the `section` and every section have a background color, so your image will be masked, set `section`'s background color to transparent.

**Comment by Attis35** [comment]
Hello Adrian,

thank you very much, it works :) I really like this framework and the template, because I can easily make cool sites.
