### ISSUE TITLE
Cannot use object of type Closure as array 

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1046]
This came up as an issue with BuddyPress but can be also an issue with other 3rd party plugins.

The original issue from BuddyPress :
`( ! ) Fatal error: Cannot use object of type Closure as array in /Users/xxx/Sites/wp/wp-content/plugins/buddypress/bp-core/bp-core-filters.php on line 1104`

@mahagr : "we might need to change our logic so it calls function, but its really hacky way"

**Comment by mahagr** [comment]
I've added simple Rendered class, which basically does the same as closure, but should fix the issue.

**Comment by mahagr** [comment]
Had to revert the change as it was causing even more issues than closure.

We just need to ask plugin authors to fix their plugins and not assume that the callback of the widget display is an array of widget object and function.

**Comment by DamirPecnik** [comment]
Getting the same error if i use Gantry 5 Particle in Widgets, with this plugin:
https://wordpress.org/plugins/advanced-access-manager/

**Comment by mahagr** [comment]
Yes

> We just need to ask plugin authors to fix their plugins and not assume that the callback of the widget display is an array of widget object and function.
