### ISSUE TITLE
Grav: Menu Icons

### ISSUE THREAD

**Issue by grangeway** [gantry/gantry5#1048]
Adding a icon to a level 1 menu in grav adds the following to the mainmenu.yaml file:

items:
  foo/bar:
    hash: ''
    dropdown_hide: ''
    width: auto
    class: ''
    icon: 'fa-area-chart'

in the xdebug stack traces, this appears to get processed as:

,"layout":"list","target":"_self","dropdown":"","icon":["","fa fa-area-chart"]

which ends up in twig as being:

(array (0 => '', 1 => 'fa fa-area-chart')) 

leading to the following twig exception:

An exception has been thrown during the rendering of a template ("Array to string conversion") in "menu/item.html.twig" at line 20.'

When running under IIS, this exception never reaches the end user (pretty sure this isn't normally the case), and instead you received standard IIS 500 error page.

**Comment by w00fz** [comment]
Reference about `array_merge_recursive` collision.

[`array_merge_recursive` vs `array_replace_recursive`](http://jontai.me/blog/2011/12/array_merge_recursive-vs-array_replace_recursive/)

**Comment by mahagr** [comment]
Was left there by overlook; logic was originally copied from WP which didn't use keys.
