### ISSUE TITLE
Production / Development Mode Error

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#1051]
I am using Joomla 3.4.5 + Gantry5 Latest + Hydrogen 5.2.4 version

Whenever I enable Production mode and save. Then when I open again from Template manager, it automatically goes to Development mode.

There is also problem in switching from Production to Development Mode. Please check

**Comment by w00fz** [comment]
I am unable to reproduce this issue, where are you toggling Prod / Dev? From the system plugin or from G5 Admin?
If you do via G5 Admin you don't need to save, it saves automatically as the toggle turns red/green.

For me the behavior is working fine though. Can you check the Network panel in the Chrome inspector on the ajax response, to see if there's something odd in there?

Also are you able to try on a different Joomla instance, perhaps locally, to make sure it's not an issue restricted to that one site?

**Comment by rgblogs** [comment]
I am toggling from G5 admin. I am facing similar problem on multiple sites.
![prod-red](https://cloud.githubusercontent.com/assets/1318090/11739147/3d20831a-a00f-11e5-9ff7-21c0c8e9a515.png)

See picture, production mode is red color. Toggling again and again says Production Enabled Production Enabled (not development).

When I visit again through template manager, development is enabled.

**Comment by rgblogs** [comment]
How to enable / disable compression??

**Comment by w00fz** [comment]
Are you able to toggle prod and dev from the gantry5 system plugin?

**Comment by rgblogs** [comment]
Yes, g5 system plugin is working. But it is not in sync with template admin.

Google Page Speed Insight giving speed of 54. No extra extension / module used.

**Comment by w00fz** [comment]
That really depends on your server. I get 91% of PageSpeed with GTMetrix with a default Gantry and not even in Production mode.

![page-speed](https://cloud.githubusercontent.com/assets/11734/11759916/59f2b2ac-a03b-11e5-8ddd-1fcf94d389c9.png)

Regarding the sync, like said earlier I can't reproduce it, there might be some server configuration on your end that blocks it. Try looking for `mod_security`.

I also asked you earlier to check on the Network panel, did you do? Are you getting anything that's not JSON in the response? Have you tried enabling debug? 

This really seems just an isolated issue on your end.

**Comment by rgblogs** [comment]
Network Panel is fine.

You are correct. This issue is related to server configuration as this is happening after I migrated to VPS server from shared hosting. On shared, it is working fine.

But, now I don't have clue how / what to fix?

**Comment by w00fz** [comment]
I am not entirely sure, this looks ok on my local. I take you tried clearing out all cache?

**Comment by mahagr** [comment]
Fixed toggle if caching is turned on.

For the other questions, please open a new issue if you still have something to ask.
