### ISSUE TITLE
Grav: Particles configuration URI isn't properly parsed for XHR

### ISSUE THREAD

**Issue by grangeway** [gantry/gantry5#1054]
Clicking on a gantry particle, then trying to confgure the particle currently tries to open whole of grav within a popup window:

![capture](https://cloud.githubusercontent.com/assets/434241/11743555/5b0df7a4-a000-11e5-85a4-16aaecd51d92.PNG)

**Comment by w00fz** [comment]
There's an issue right now that prevent's me from using the admin. As soon as we get that sorted I'll fix this.

Cheers.

**Comment by w00fz** [comment]
Try with the latest update because this is now working fine for me.

**Comment by mahagr** [comment]
Works for me too. I think there was earlier bug that caused this. Closing the issue.
