### ISSUE TITLE
Positions Manager: Implementation for a new view for managing Positions.

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#1059]
Joomla has this concept already where modules can be assigned to the same position, resulting in modules stacked up on top of each other.
The idea is great and works nicely but, managing it, has always been a problem due to the UI limitation that Joomla offers.

It is quite convoluted to know what a position is containing. To do so one has to enter the Modules Manager and filter by said position. If the author desires to rearrange what's in a Position container, a one-by-one module operation will be required by constantly: entering, changing, saving and moving to the next one module, individually.

Gantry's main idea is to keep things simple and have a simplistic way for approaching things and we feel this is something we can improve.

A Positions Manager that is reachable right within the Gantry Admin will allow the author to list all positions in the same view, granting abilities to reorder within the same position or across different ones, adding and removing Modules / Particles, understanding right away the Assignment status of each item and finally to quickly and simply enable or disable each item.

A Position Group generated from the Positions Manager will then become available from the Layout Manager as any other Particle, allowing for greater support for inheritance, since it will be all manageable through the same global Position Manager view.

This will also satisfy the need for allowing Platforms where a positions system is missing or it's not quite as flexible as what Joomla offers, like in Grav where a positions system doesn't exist or like Wordpress, where the concept of widgets locations is similar but not quite as powerful as Joomla's.

---

Development for this has already begun with 84234041315993f and for this initial implementation it looks like this:

![positions-manager](https://cloud.githubusercontent.com/assets/11734/11770291/445f8792-a1af-11e5-855e-3d8e3727dbc6.png)

**Comment by JoomFX** [comment]
It look's great guys :smile: 

What I'm really missing in G5 is the inheritance of the Layout Manager. I mean, to have a single point for managing the layout - to have the Layout Manager tab re-enabled in the "Base" outline and then all other outlines to inherit the layout from "Base", and have it greyed-out by default (the same as "Styles" for example). And if the user wants to have a different layout for the different outlines, he just overrides it by clicking a checkbox (again, the same as "Styles").

**Comment by w00fz** [comment]
Yes, we will get there. Inheritance is still our number 1 source of discussion. We know what we need and it will require the LM to be reworked quite a bit in order to make it more flexible and to accommodate inheritance.
LM Inheritance is quite complex we are cautiously taking baby steps towards it because we want to make it right: the Positions Manager is a little part of it.
We also discussed a concept of mirroring to go along with LM inheritance (more details in #1018).

Since LM is such a delicate beast, we are trying to ensure we have everything around it covered so that we can then tackle it. Given the importance of the LM and because we don't want to lose any of the current capabilities we have with it, it will require extensive work on it. 

We initially wanted it to go with 5.3.0 but given the amount of work and considering Grav's integration deserved priority over it, we decided to postpone it for later. 

You can rest assured though, LM inheritance is constantly in our thoughts, dreams and nightmares: we'll get there :smile_cat:

**Comment by JoomFX** [comment]
> LM inheritance is constantly in our thoughts, dreams and nightmares

Hehehe :smile: 

Thanks Djamil. Keep up the great work guys!

**Comment by cworf** [comment]
"You can rest assured though, LM inheritance is constantly in our thoughts, dreams and nightmares: we'll get there"

Yay! I'm really excited to have the inheritance feature, its been the single biggest reason I have stayed clear of gantry 5 when building larger, more detailed client sites. Actually tho the mirroring concept would take my vote over the gantry 4 style inheritance any day. the ability to mirror either whole sections or just individual particles would be amazing.

Good luck!

**Comment by robben111** [comment]
Being able to assign a particle to a specific page/article would be a very powerful feature.   

For example, if I want to add a right banner to a series of widget pages.  Each widget page would have a different right side banner.  Not a rotating banner, but a specific area of content(particle) that is variable dependent on the assignment to a specific article. 

Right now it seems I'll need to create/manage a bunch of themes to do this, which seems to have its own duplicative style issues.

**Comment by mahagr** [comment]
Yes, its exactly what this feature is doing.
