### ISSUE TITLE
Grav: Page in Normal Mode Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1062]
When page is in Normal mode i can't save it and the UI is broken a little see screens
![2015-12-15 00 58 57](https://cloud.githubusercontent.com/assets/10489911/11798524/e0359bd0-a2cb-11e5-8c9e-a2448623fff9.jpg)
![2015-12-15 00 58 41](https://cloud.githubusercontent.com/assets/10489911/11798526/e40dc8cc-a2cb-11e5-8029-2e8a51c8659a.jpg)

**Comment by mahagr** [comment]
Does this happen only when Gantry is installed? Because of I cannot see this being Gantry issue as it doesn't run on this particular page.
