### ISSUE TITLE
Gantry in Grav - add new page

### ISSUE THREAD

**Issue by paulhibbitts** [gantry/gantry5#1063]
Grav + Admin 1.04 core downloaded and Gantry is then installed all works fine.When a new Page is added via Admin the site preview shows the new menubar item, but clicking on it produces the following error:

Template "widgets/menu.html.twig" is not defined in "partials/base.html.twig" at line 16.

Screenshot attached.
![crikey there was an error](https://cloud.githubusercontent.com/assets/1812771/11798534/904f1f9c-a280-11e5-9f2b-ae032b9cad63.png)

Thanks for looking into this,
Paul

**Comment by DamirPecnik** [comment]
This is because the system set the Display Template to Error #1061 can you confirm this?

**Comment by paulhibbitts** [comment]
Yes, it does seem that "Error" is set as the default page file. Changing it to "Page" and adding the new page produces this:

![add page grav](https://cloud.githubusercontent.com/assets/1812771/11798697/163feb8a-a282-11e5-87fd-d14512ad3151.png)
