### ISSUE TITLE
XFN (rel) from WP Menu doesn't get passed to HTML output

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1064]
XFN (rel) from WP Menu doesn't get passed to HTML output

https://wordpress.org/support/topic/scroll-animation-not-working?replies=7#post-7781796

**Comment by mahagr** [comment]
@newkind I've added the XFN output, but class is still only in the parent `<li>` and not inside the `<a>` tag. Not sure if it matters, tho?

**Comment by newkind** [comment]
That should be fine ;)
