### ISSUE TITLE
Background image like Ganty 5 website

### ISSUE THREAD

**Issue by mark118** [gantry/gantry5#1065]
How did you implement the rocket background image in the http://gantry.org/ website. It also has a different scrollspeed? I like that!!

**Comment by mahagr** [comment]
@rhukster Something for you to answer?

**Comment by rhukster** [comment]
Take a look at this: http://pixelcog.github.io/parallax.js/

**Comment by mark118** [comment]
Thank you, that's it!! Is #g-page-surround the right place for the backgound?

**Comment by mark118** [comment]
How/where do I add this code?
<div class="parallax-window" data-parallax="scroll" data-image-src="/path/to/image.jpg"></div>

**Comment by mark118** [comment]
How/where do I add this code?
class="parallax-window" data-parallax="scroll" data-image-src="/path/to/image.jpg"

**Comment by w00fz** [comment]
You can add datasets to your particle block via Tag Attributes (http://docs.gantry.org/gantry5/tutorials/using-block-settings#tag-attributes) or you can use Custom HTML particle to output the whole html structure or, if you are in Joomla, you can use Joomla's Custom HTML module, write the output and then use the Particle Module Instance to render it.

**Comment by mark118** [comment]
Thank you, good to know. I'll try these options.
