### ISSUE TITLE
Atoms with "body_top/body_bottom" features

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#1069]
Hello,

i have an atom, and want to load some simple HTML after ```<body>``` tag, can you please add the feature, something like this:

```{% block body_top %} <h1>foobar</h1> {% endblock %}```
```{% block body_bottom %} <h1>foobar</h1> {% endblock %}```

Thank you so much,
Federico

**Comment by w00fz** [comment]
Closing this as duplicate of #1161, even tho this came up earlier there's been a discussion going on in the other issue.
