### ISSUE TITLE
Menu problems

### ISSUE THREAD

**Issue by ramon12** [gantry/gantry5#1071]
Note: This bug can be recreated, i lost production site with this bug, losing all the data.
Also menu direction in last build, the center value dont work/show properly making the menu invisible if set,and left setting making overlay.

If you add new rows and then remove them
![Menu](http://i63.tinypic.com/smbx8l.png)
It shows blank on frontend and unused html tags, even clearing site/browser cache
![Blankmenutags](http://i66.tinypic.com/l8r6b.png)
Recreated:
![Recreated](http://i66.tinypic.com/2lk2t1w.png)
If i want to add new row again it shows under having 100% and under 50% result in breaking the layout
![Recreated](http://i67.tinypic.com/msnol4.png)
Recreated shows 50% - 50% but the bug under shows again
![Recreated2](http://i66.tinypic.com/20tosw8.jpg)
After menu crash
![Crash](http://i64.tinypic.com/1zf1zpj.png)
Losing all the data
![Empty](http://i64.tinypic.com/otgdqf.png)
And blank frontend 
![Empty2](http://i65.tinypic.com/2u8dvu9.png)

**Comment by mahagr** [comment]
As a quick fix, can you try to remove directory called `templates/g5_hydrogen/custom/menu`. It should make the menu visible again.

**Comment by ramon12** [comment]
I don't have anything in custom as you said. And a sugestion to fix this is to limit creating new row to 1 like you did on layout tab as last my issue reported.

**Comment by mahagr** [comment]
I believe this is still an issue even if we haven't been able to reproduce it locally.

Send me a note in gitter chat and I will take a look on it for you.

**Comment by newkind** [comment]
@mahagr yesterday, this once happened to me :
```
500 Internal Server Error

Oops, An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()") in "forms/fields/menu/item.html.twig" at line 6..
```
Not sure if that's connected but @w00fz said that it might

**Comment by mahagr** [comment]
I did find some issues with menu columns:

* You can create over 20 columns making CSS sizes to fail as 5% is the smallest supported size
* Resizing column rounds only the next column, making sum of the sizes < 100%

**Comment by w00fz** [comment]
I am not entirely sure what your original issue was about but I found something that might be similar or related. Would have been useful a better description on how to reproduce all this, rather than just dumping a few screenshots.

Anyway, all I could figure out/understand is now fixed and should be available in the next CI Build.

Thank you,
