### ISSUE TITLE
the hydrogen theme is missing the default "home" outline.. did I missing something?

### ISSUE THREAD

**Issue by joshmans** [gantry/gantry5#1072]

**Comment by w00fz** [comment]
Hello there, the Home outline only appears in Joomla, in Wordpress and Grav it isn't needed and you get a Default Outline. You can create a new outline very easily through the Outlines tab and then assign it to Home. That would be identical to what you see in the video.

**Comment by joshmans** [comment]
I do not have a default outline in my wordpress+gantry+hydrogen install
besides the poor one that is in the start of the video until its changed to
the home outline.. It'd be nice to have one to better understand how things
work

**Comment by mahagr** [comment]
Default outline = Base outline. You can create home outline yourself:

* Go to `Outlines` tab (on top row)
* Create new outline and rename it to `Home`
* `Edit` outline
* In `Layout` tab `Load` preset named `Home`, but first uncheck the checkbox on the modal. Then `Save`
* In `Assigments` tab check `Page Context > Front Page` and hit `Save`

After this your home page will be using the Home outline.

**Comment by newkind** [comment]
I'll add one today.

**Comment by mahagr** [comment]
There is already issue on missing home outline in WP: #895

**Comment by mahagr** [comment]
Closing issue as duplicate.
