### ISSUE TITLE
Joomla cache issue after Gantry update

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1074]
System info:
* Joomla v3.4.6
* PHP 5.5.19
* MySQL 5.6.21

Scenario:
1. Upload the the content of the joomla-pkg_gantry5_v5.2.5.zip on the TMP joomla folder.
2. Extension > Manage > Install from Folder. (Install OK)
3. Upload Package File > Browse > joomla-tpl_g5_hydrogen_v5.2.5.zip > Upload & Install (Install OK).
4. Extension > Templates > Hydrogen - Home (The Styles tab is showing correct).
5. Click on "Layout" tab. It open an empty modal window (see the screenshot1)
6. Click on some other tab like "Page Settings". It shows a modal window (screenshot2)
7. System > Clear Cache > Check the "gantry5" cache group and hit Delete
8. Now, Extension > Templates > Hydrogen - Home (The Styles tab is showing correct).
9. Click on "Layout" tab -> Correct!
10. Click on "Page Settings" tab -> Correct! 

Conclusion:
The issue has gone.

Screenshot1
![g525-cache1](https://cloud.githubusercontent.com/assets/3976174/11893416/bd36ec72-a570-11e5-9bf2-131152153672.png)

Screenshot2
![g525-cache2](https://cloud.githubusercontent.com/assets/3976174/11893430/cf4a3bbc-a570-11e5-9606-837f3cccf3c7.png)

**Comment by nicutor** [comment]
I had the same issue on gantry 5.2.6 too.

**Comment by mahagr** [comment]
I'm wondering if this was another bug: #1076. Can you try with latest CI build if its still happening?

**Comment by mahagr** [comment]
@mariantanase @nicutor Is this still an issue on later releases?

**Comment by mariantanase** [comment]
hi @mahagr 
it's not more an issue from my side.

**Comment by mahagr** [comment]
Closing the issue as not being an issue anymore.
