### ISSUE TITLE
Joomla Overrides not working in G5_Hydrogen

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#1075]
According to the docs from Joomla this needs to be possible:
TEMPLATE_NAME/html/com_content/article/default.php

Translated to Gantry I got it now:
g5_hydrogen/html/com_content/article/default.php

I added into the page header `HELLO` but it is not showing on the websites. I have also tried:
g5_hydrogen/custom/html/com_content/article/default.php

Which has the same result. Would love to receive feedback from anyone who got this working.

Tested this on 3 different websites with all latest Joomla and Gantry 5.2.4. I am sure it is not `fixed` at 5.2.5. as I tested this on 1 website with the same result.

**Comment by mahagr** [comment]
Joomla takes care of its overrides and Gantry has no control over them.

**Comment by hennysmafter** [comment]
@mahagr Could you try the above override please because it is not working at my test sites. And we really need it for some of the projects.

**Comment by w00fz** [comment]
I tried and it works for me @hennysmafter 

![override](https://cloud.githubusercontent.com/assets/11734/11903870/22b03f4a-a571-11e5-8314-6d41f5ef853a.png)

![override-2](https://cloud.githubusercontent.com/assets/11734/11903881/37ee2d7c-a571-11e5-8222-b7e364e579aa.png)

![override-3](https://cloud.githubusercontent.com/assets/11734/11903906/6f1f4e2a-a571-11e5-9ad0-c9dc54a54182.png)

**Comment by hennysmafter** [comment]
@w00fz Thank you for trying it out and indeed adding the H1 element is working strangely when adding an ID to an element it is not? Not sure if this is because of Gantry or Joomla.

![2015-12-18 19 40 44](https://cloud.githubusercontent.com/assets/4426337/11904315/910c35b8-a5bf-11e5-8b1e-ef9163fc6715.png)
![2015-12-18 19 41 34](https://cloud.githubusercontent.com/assets/4426337/11904317/94e54648-a5bf-11e5-8cd1-bfca7d5097fc.png)

**Comment by w00fz** [comment]
There are two `class="page-header"` in the php, if you notice there is an if statement wrapping around it.  You might be adding the `id` on the wrong one. Scroll down to line 48, you will see it.

![foobar](https://cloud.githubusercontent.com/assets/11734/11904376/96abb71e-a574-11e5-970e-39f6b0ae8dd4.png)

**Comment by hennysmafter** [comment]
Yes. I replied it above. Thank you very much for the help it is appreciated.
