### ISSUE TITLE
Bug with Timbers render_string and compile_string 

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1077]
When using 
`{{ gantry.platform.call( 'Timber::render_string', 'hi') }}`
in Twig files you'll get :
```
An exception has been thrown during the rendering of a template ("Argument 1 passed to Gantry\Framework\Theme::setTwigLoaderPaths() must be an instance of Twig_Loader_Filesystem, instance of Twig_Loader_String given, called in /Users/XXX/Gantry5/Framework/src/classes/Gantry/Component/Theme/AbstractTheme.php on line 96 and defined")
```

Is this caused because we're already in Twig files and we shouldn't call Timber::render_string or Timber::compile_string?

https://github.com/jarednova/timber/wiki/Timber-docs#render_string

**Comment by mahagr** [comment]
Correct call is, BTW:

    {% do gantry.platform.call( 'Timber::render_string', 'hi') %}

As the function already outputs data.

**Comment by dudewithamood** [comment]
Thank you - will test and see if it resolves my issue.

**Comment by dudewithamood** [comment]
Doesn't solve the issue I'm having. Timber bug logged here (as I assume it's a Timber issue?): https://github.com/jarednova/timber/issues/798

More accurately, my particle code is as follows (although the simplified 'hi' version generates the same error):
```PHP
{% set post = (particle.post ? do gantry.platform.call( 'Timber::get_post', particle.post ) : do gantry.platform.call( 'Timber::get_post' )) %}
{% do gantry.platform.filter( do gantry.platform.call( 'Timber::compile_string', particle.twig, { 'post' : post } ) )|html|raw %}
```

An example of particle.twig is "<h2>{{ post.title }}</h2>"

**Comment by newkind** [comment]
If I remember correctly when we talked about this issue with @mahagr he said that `compile_string` doesn't support loading files and you're trying to load `particle.twig` file. 

Timber docs seem to confirm this as they say that compile_string and render_string should be used with snippets - not files : https://github.com/jarednova/timber/wiki/Timber-docs#compile_string

**Comment by dudewithamood** [comment]
Yes, particle.twig is a snippet, a string. Like this (simplified):
```PHP
{% do gantry.platform.call( 'Timber::compile_string', '<h2>{{ post.title }}</h2>', { 'post' : post } ) %}
```
