### ISSUE TITLE
Improve google analytics atom tooltip and placeholder

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1079]
This is a very trivial little matter but it does keep coming up in the forum...

For the Google Analytics atom I wonder whether we can:
1. change the tooltip message for UA Code to say "Enter the Google UA tracking code for analytics (e.g. UA-XXXXXXXX-X)".
2. Add a placeholder in the empty field "UA-XXXXXXXX-X"
3. Add validation to the field to a) check format b) prevent code being added in field.

Why? because users keep pasting the whole Google Analytics script into this field.

![2015-12-21_10-24-35](https://cloud.githubusercontent.com/assets/11683218/11928786/20ef2630-a7ce-11e5-98be-ba6c41f28c98.png)

**Comment by mahagr** [comment]
LOL

**Comment by marktaylor46** [comment]
Yeh I know it's funny but it's true :)

Thanks!
