### ISSUE TITLE
Cannot activate hydrogen theme on fresh wordpress install

### ISSUE THREAD

**Issue by tompopovic** [gantry/gantry5#1083]
I've been attempting to install Gantry 5 on a fresh Wordpress installation.  When activating the Hydrogen theme, the server starts generating 500 Internal Server errors, with the following in the apache error_log:

Premature end of script headers: plugins.php, referer: http://shimanamischool.com/wp2/wp-admin/themes.php

I'm also seeing the following error messages to the browser:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in wp2/wp-includes/plugin.php on line 525

Installation details are as follows:
Gantry Framework 5.2.5
Timber 0.22.4
Hydrogen Theme 5.2.5
Wordpress 4.4
PHP 5.4.45 on CentOS 6.7 x86_64 
Apache/2.2.31

The errors come up about 50% of the time while the theme is activated, on both front end and wp-admin.  I do not see the Gantry Theme in the admin sidebar.

**Comment by mahagr** [comment]
https://github.com/WordPress/WordPress/blob/master/wp-includes/plugin.php#L525

We aren't touching the 'function' of the plugin. The error has nothing to do with Gantry, but something else goes wrong. I have no idea what is causing this to happen, though...

@newkind Do you have any ideas?

**Comment by tompopovic** [comment]
The error message is generated from
```php
add_action('admin_notices', function () use ($e) {
    echo '<div class="error"><p>Failed to load theme: ' . $e->getMessage() . '</p></div>';
});
```
in https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/wordpress/includes/gantry.php#L41

The error message it's trying to display is:
Service definition is not a Closure or invokable object.

I've traced the errors back to Pimple, and found out that this is being caused by PHP eaccelerator.

Disabling this resolved my problem:

php.ini:
eaccelerator.enable 0
eaccelerator.optimizer 0

**Comment by mahagr** [comment]
This is starting to look like a bug in eAccelerator, which hasn't been maintained for over 3 years. I remember having issues with it before I decided to use APC which was better maintained at that point. Both projects are now officially dead and you should soon start using PHP 5.6 with Opcache. Later versions of PHP are much faster and have many bug fixes over the one you have.

If you cannot yet move to PHP 5.6, consider at least using APC instead of eAccelerator.
