### ISSUE TITLE
Error on Recompile CSS

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1087]
On a live site, I did e few changes on my custom.scss file. After that when I tried to hit Recompile CSS I receive an error (see the screenshot).
Joomla 3.4.7
Gantry 5.2.6
PHP 5.4.42
![error-g5](https://cloud.githubusercontent.com/assets/3976174/11991634/c86687e6-aa1c-11e5-9098-c0b9696d9a90.png)

![error2-g5](https://cloud.githubusercontent.com/assets/3976174/11991737/21946da0-aa1e-11e5-9dcd-882e8c3092e9.png)
I cannot use now the "Recompile CSS" !

**Comment by w00fz** [comment]
Can you try increasing the memory? I have mine set to 256M and hasn't been an issue so far.
```
memory_limit = 256M
```

Also I highly suggest changing PHP from 5.4 to 5.6, a lot faster and 5.4 is already in EOL, 5.5 following soon.

http://php.net/supported-versions.php

**Comment by mariantanase** [comment]
Thanks @w00fz ,
Unfortunately, the hosting provider have no immediate plans to upgrade.
This is the hosting answer : *Right now, there won't be an upgrade. But, next year, we will introduce a new control panel. That control panel will include php 5.5 and 5.6. Unfortunately, we can't tell you precisely when the new control panel will go online. We hope it will be in the first quarter of the next year.*

How can I increase the memory ?

**Comment by mariantanase** [comment]
ok, resolved !
I added this line `ini_set('memory_limit','256M');` into index.php and now the "Recompile CSS" is working fine.

**Comment by mahagr** [comment]
I've kept the limit at 96M, which seems to be enough for CSS compiler.
