### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1088]
On a few installations (Joomla 3.4.7 + Gantry 5.2.6) I noticed a "not found" error when tried to click on the wheel, every wheel on layout manager.
![servage-err](https://cloud.githubusercontent.com/assets/3976174/11991701/93b37990-aa1d-11e5-8c41-e76a41969251.png)

**Comment by w00fz** [comment]
Can you try replacing the js in `administrator/components/com_gantry/js/` with the one attached?

[main.js.zip](https://github.com/gantry/gantry5/files/71574/main.js.zip)

**Comment by mariantanase** [comment]
Now this error has gone. I noticed a faster response when open a modal window from the wheel

**Comment by jasonc13** [comment]
@w00fz - I don't know how to replace the js in administrator/components/com_gantry/js/.  How do I do that?  - I am new to this gantry thing.

**Comment by jasonc13** [comment]
I figured it out.  For me I had to go out to my hosting service, get on the sever, and then go into the file directory and then change the code in the main for the code that @w00fz gave in his post above.  There is probably a better way but that fixed it for me.
