### ISSUE TITLE
Can't drag existing Particles of Modules from top-level menu to submenu

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#109]
It should be possible to click and drag non-menu items such as particles and modules to submenus. It doesn't seem to be possible at this time.

See linked video for examples.

https://www.dropbox.com/s/69kj0j13u6l68hw/ScreenFlow.mp4?dl=0

**Comment by w00fz** [comment]
Yes this is an issue. You can drag modules and particles if you just created them. The issue is once you saved and reloaded the page, the capability is rearranging modules/particles is lost.
I'll look into it thanks.

Good catch.
