### ISSUE TITLE
5.2.6 - Admin page - modul position settings - ERROR

### ISSUE THREAD

**Issue by verasztos** [gantry/gantry5#1090]
Not Found

The requested URL /administrator/&format=json was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by verasztos** [comment]
possible solution:

1. Clear Cache
2. logout - login

I worked

**Comment by w00fz** [comment]
Yeah there seems to be a problem which I already patched but won't be available until next release. Have a look at #1088 for the fix.
