### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Neugls** [gantry/gantry5#1093]
![image](https://cloud.githubusercontent.com/assets/1432749/12091328/36d1267e-b331-11e5-9209-7574d0825c45.png)

Joomla 3.4.8
Windows 10
Xampp 
php version: 5.5.6

I am viewing the index page, here is the calling stack
![image](https://cloud.githubusercontent.com/assets/1432749/12091364/880c7a02-b331-11e5-96ff-3c89df537717.png)

**Comment by w00fz** [comment]
Have you tried increasing the maximum execution time? It's a PHP setting.

**Comment by mahagr** [comment]
Compiling SCSS can be really slow, but it is a one time task after changing Styles or after upgrading Gantry or template.
