### ISSUE TITLE
 Subject: joomla default header (with js and css files) are not loaded in the "Error" system outline in Gantry v5.2.4

### ISSUE THREAD

**Issue by sahil-github** [gantry/gantry5#1096]
Hello Gantry Team
Some modules like Ajax Login/Register module, language switcher module, news highlighter module, vertical menu module  etc are not working on gantry5 Error Page as js/css files related to those modules are not loaded in the Error system outline page of Gantry5 v5.2.4 Hydrogen template which breaks the whole layout of the website. Please give some solution for this issue.

**Comment by JoomFX** [comment]
Hey @sahil-github 

Many assets are not being loaded on the Error Page, for example jQuery.
This is not a G5 related thing, this is how Joomla is designed. You are not supposed to have anything on the Error Page. Have a look at this issue for more details:

https://github.com/gantry/gantry5/issues/918

You might try to load jQuery (and other assets) manually in the "Error" outline, using the options under "Page Settings".
