### ISSUE TITLE
Hebrew article layout broken

### ISSUE THREAD

**Issue by mirono** [gantry/gantry5#1097]
![joomla1](https://cloud.githubusercontent.com/assets/6016445/12142750/472ec320-b483-11e5-97aa-2fa461910a3c.PNG)
![joomla2](https://cloud.githubusercontent.com/assets/6016445/12142753/49e70c26-b483-11e5-9fba-0876ffd6f35f.PNG)

In the old Joomla (2.5.11) it was like in joomla1.png
With the new Joomla (3.4.8) and Gantry5 with Hydrogen template, the layout is broken, like in joomla2.png

**Comment by adi8i** [comment]
Can you change the template to `protostar` please, and see if it's working fine, not sure if it's a gantry issue.

**Comment by mirono** [comment]
With protostar it's even worse:
![joomla3](https://cloud.githubusercontent.com/assets/6016445/12152262/49ccac3a-b4bc-11e5-80a9-163f966f5df6.PNG)

**Comment by mirono** [comment]
Old Joomla: http://ophir.org.il/index.php/he/
New Goomla: http://ophirnew.org.il/index.php/he/

**Comment by adi8i** [comment]
If you have the same issue with protostart, the issue is not caused by Gantry. Your new website url is not accessible.

**Comment by mirono** [comment]
Joomla caused my bug report as template issue. What do you suggest?

**Comment by w00fz** [comment]
This is not Gantry related. 

You should have a look at your content and fix classnames to match the new Joomla 3 way. I think you have HTML in the articles that use classes that are just not available anymore.
