### ISSUE TITLE
Script added in page settings - custom content works, but it doesn't if loaded in atom

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1098]
Hello.

If i load a script like the following from `page settings -> head properties - > custom content` works fine.
Instead if i create an atom and add the same script in `block javascript` or `block javascript_footer` will throw an error, `cannot read property dataset of null` .  What's the difference ?

`<script data-trab="an id" async="async" defer="defer" src="https://my.trab.io/trab.js"></script>`

**Comment by mahagr** [comment]
Can you copy the whole atom here.

**Comment by adi8i** [comment]
```
{% block javascript_footer %}
    {% if particle.enabled %}
        <script data-trab="640045600b6438b962c2cdf24d643ec9" async="async" defer="defer" src="https://my.trab.io/trab.js"></script>
    {% endif %}
{% endblock %}
```

data-trab is generated for each project, if it will load fine you should get a non authorized error.

**Comment by mahagr** [comment]
Proper code would be:
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block javascript_footer %}
    <script data-trab="640045600b6438b962c2cdf24d643ec9" async="async" defer="defer" src="https://my.trab.io/trab.js"></script>
{% endblock %}
```

The issue here is that Joomla and WP doesn't support `data-` attributes, so they are dropped.

**Comment by mahagr** [comment]
Cleaner(?) way to do the same:

```
{% scripts in 'footer' %}
    <script data-trab="640045600b6438b962c2cdf24d643ec9" async="async" defer="defer" src="https://my.trab.io/trab.js"></script>
{% endscripts %}
```

**Comment by adi8i** [comment]
If you add the code using `{% scripts in 'footer' %}`
```
A template that extends another one cannot have a body in "@particles/trab.html.twig" at line 3.
```

I'll add the code in `custom content` there works fine. Thanks.

**Comment by mahagr** [comment]
Second example is without `extend` (first line).
