### ISSUE TITLE
"Woops. Looks like this page doesn't exist." after saving a style in Grav

### ISSUE THREAD

**Issue by ghost** [gantry/gantry5#1104]
Hello,

I changed the navigation-background-color, saved and got "Woops. Looks like this page doesn't exist.".

Olli

**Comment by mahagr** [comment]
This is known issue; you need to click on "Styles" tab to make the path correct.

**Comment by Tyrion2737** [comment]
Got it 😀

**Comment by w00fz** [comment]
Actually I fixed this now with ac4577b39
