### ISSUE TITLE
WP: Theme does not have Base Outline

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1107]
Sorry for opening a new issue, we discussed this on chat, i have troubles accessing it. 

This issue will occur if you don't have `default` folder in `config folder` , not sure if is an issue or not, anyway you will not ship a template with `config folder` empty. 

To reproduce it, remove the content of `config` and `custom/config` folders. It happens in wp only.

**Comment by mahagr** [comment]
Its not really an issue -- Gantry cannot work without default folder. It contains the default settings for the current theme.

**Comment by newkind** [comment]
Maybe we should create more accurate warning?

**Comment by adi8i** [comment]
Or create an empty folder on first hit, if it doesn't exist ?

**Comment by mahagr** [comment]
Yeah, creating empty folder could do it.
