### ISSUE TITLE
Use of getAttributeNode() is deprecated. Use getAttribute() instead.

### ISSUE THREAD

**Issue by mark118** [gantry/gantry5#1108]
Is this a real issue in main.js?

**Comment by mahagr** [comment]
No, its not a real issue. Its just recommendation to change the code at some point in the future. Most likely needed by some older version of IE.

**Comment by w00fz** [comment]
No need to worry about it, it's just a warning thrown by one of our dependencies (and only in Firefox). Will be likely be dealt with soon enough or eventually we will take care of it.

**Comment by mark118** [comment]
Ok thank you!
