### ISSUE TITLE
Second scss not working

### ISSUE THREAD

**Issue by mark118** [gantry/gantry5#1110]
Can I add a second scss file? I use custom.scss and want to use particles.scss also. Custom.scss is loading fine but particles.scss not?

Regards,
Mark

**Comment by adi8i** [comment]
In `custom.scss`, at top add `@import particles;`

**Comment by mahagr** [comment]
Method recommended above is the best one; include extra files from the main custom file.

**Comment by mark118** [comment]
Ok thank you!!
