### ISSUE TITLE
Question or bug "Menu Item Type/Link" in Grav

### ISSUE THREAD

**Issue by Tyrion2737** [gantry/gantry5#1111]
Hello,

one of my menu items should not be clickable (only for opening the dropdown).

So first I tried the following:

![ohne titel](https://cloud.githubusercontent.com/assets/14146656/12299281/5077501c-ba16-11e5-826d-4a9553be41ce.png)

But none combination of "Menu Item Type/Link" does work.

Or how would you do this?

Olli

**Comment by mahagr** [comment]
Gantry should automatically detect the menu item from Grav; create directory without page.md file and it should automatically do this for you.

**Comment by Tyrion2737** [comment]
And only deleting page.md and leaving the 2 fields as they were when the page was created in admin is not enough, is it?

**Comment by Tyrion2737** [comment]
I can not help myself, but sometimes it works but sometimes not. I do more testing tomorrow.

**Comment by mahagr** [comment]
I'm not sure if it is possible in admin. Have never tried to create page in that way. If it isn't; create a but into grav admin on it.

**Comment by mahagr** [comment]
I made the three first fields read only as they aren't supposed to be changed from Gantry.
