### ISSUE TITLE
{% scripts in 'footer' %} broken in CI, 5.2.7 and 5.2.6

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1113]
`{% scripts in 'footer' %}` is broken in CI, 5.2.7 and 5.2.6

`{% block javascript_footer %}` works fine

**Comment by mahagr** [comment]
Its odd as:

```
{% assets in 'footer' %}
    {% block javascript_footer %}
    {% endblock %}
{% endassets -%}
```

Basically `scripts` is just an alias for `assets`.

**Comment by newkind** [comment]
Your sample shows `assets` not `scripts` - is it the same ?

**Comment by mahagr** [comment]
Its identical to `scripts` and `styles`. Just added those two as they are easier to memorize. :)

**Comment by mahagr** [comment]
OK, the issue was that we are doing footer scripts in

    add_action('wp_enqueue_scripts', ...);
