### ISSUE TITLE
"Back" words in my keywords cloud

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#1114]
If I use a complex menu structure, than the "back" words are appear in my keyword cloud. I think this one is no good for the SEO.

For example: class=g-menu-item-container href=# data-g-menuparent="" title=Back><span>Back</span>

![image](https://cloud.githubusercontent.com/assets/1657924/12371878/52e083f8-bc43-11e5-8ad5-d2e066b84cbf.png)
![image](https://cloud.githubusercontent.com/assets/1657924/12371920/cc4e12e0-bc44-11e5-92ad-0153f76e107a.png)

**Comment by w00fz** [comment]
Can't you ignore 'back' from the keywords?

**Comment by w00fz** [comment]
Also what are you using for that keywords cloud? Is that a plugin?

**Comment by w00fz** [comment]
Any input on this @csbalazs ? 😃

**Comment by csbalazs** [comment]
I use a simple website analyser: woorank.com. This one has a keywords cloud. My site (joomlacms.hu) has a complex menu structure, and the "back" keyword often occurs.

**Comment by w00fz** [comment]
I see, I think that being an analyzer it just tells you the most common keywords. Unfortunately I don't see a way to have words getting ignored by such tools, however in the woorank site, at the keywords section it mentions this:

> This Keyword Cloud provides an insight into the frequency of keyword usage within the page.
> 
> It's important to carry out keyword research to get an understanding of the keywords that your audience is using. There are a number of [keyword research tools](http://blog.woorank.com/2012/10/16-free-keyword-research-tools-seo/) available online to help you choose which keywords to target.

Which explains how you can target determined keywords, which will also allow you to exclude back from the list.

Sorry I don't think there's anything else we can really do about that. I did search for ways to exclude words from being indexed and it's not possible, has to be done at the SEO tool level.
