### ISSUE TITLE
Ability to apply outline/layout to dynamically created pages

### ISSUE THREAD

**Issue by jasonday** [gantry/gantry5#1115]
I'm using a plugin (WP Listings) that creates a custom post type, and I want a specific outline/layout assigned to the single posts of the CPT. 

Within Hydrogen, the only way to assign this new layout is to assign it to a specific post of that CPT. I am unable to assign the outline to all current and FUTURE single CPT posts. 

A couple of options:

* allow for assignments to CPT singulars or archives
* allow for option for assignments (when assigned to a menu item) to cascade to sub pages
* allow for option to turn on assignment for all current & future items within that grouping under the assignments page in Hydrogen

**Comment by w00fz** [comment]
Related to #928 and #771 and #1298

**Comment by w00fz** [comment]
This should be implemented now and will be available with 5.3.0.
