### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by RogerSteve** [gantry/gantry5#1118]
Selecting other template than gantry5 eg. protostar will show: COM_GANTRY5_PARTICLE_NOT_INITIALIZED

**Comment by mahagr** [comment]
Looks like the language file won't get loaded in that case.

**Comment by mahagr** [comment]
I've tried to reproduce this with 2 different languages and I always see:

```
Warning
Gantry 5 Particle: Cannot display content; not in Gantry 5 template!
```

Where the first word is translated. Can you enable translations debug and look if `en-GB.mod_gantry5_particle.ini` has been loaded or not?

**Comment by RogerSteve** [comment]
Not seen that file, here a screen on debug:
![US](https://s21.postimg.org/6yrhgu3k7/us.png)
Recreated:
Install G5 + Hydrogen -> Remove Home Overlay -> Switch to other template than G5

**Comment by mahagr** [comment]
Thanks for the instructions, I finally found the issue. :)
