### ISSUE TITLE
Nucleus core doesn't respect themes $core-font-size and $core-line-height

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1122]
Nucleus core doesn't respect themes $core-font-size and $core-line-height

**Comment by mahagr** [comment]
This one is really odd; I have no idea why it doesn't work.

**Comment by adi8i** [comment]
@newkind do you mean that you can't adjust `$core-font-size` in template's typography page ? If so it works fine for me. Was an older "issue" about this, make sure `@import "configuration/base";` is loaded before `@import "configuration/nucleus/base";`

**Comment by mahagr** [comment]
I take what I said back; I was in production mode and didn't recompile the CSS. It seems to work just fine for me, too. Was using hydrogen.

**Comment by newkind** [comment]
@adi8i you were right man! the order was wrong as i took it from a different template! thanks! :)
