### ISSUE TITLE
Can't Delete Outline

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1124]
I am getting this when trying to delete Outline.

/Method Not Implemented

GET to /~xxxxxx/administrator/index.php not supported.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

@kat05 also had the same error ....

/Method Not Implemented

GET to /gantry5/boilerplate/joomla/administrator/index.php not supported.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by w00fz** [comment]
The issue is we are using the `DELETE` request method which is not always enabled, in our sandbox it isn't for instance.

We should probably move it to `POST` and `/*/delete`.

@mahagr ?

**Comment by w00fz** [comment]
Seems sorted with the `POST` approach.

**Comment by DamirPecnik** [comment]
Works!
