### ISSUE TITLE
404 Outline not found

### ISSUE THREAD

**Issue by unlmtd** [gantry/gantry5#1125]
Hello,

This new version (5.2.8) breaks "infolist" particle ability to add links to each item. I was modifying the footer in the RocketLauncher of Requiem (the "Useful links" part) and when I changed the link it said "404 Outline not found". I reverted temporarily to 5.2.7 and it worked fine.

**Comment by kat05** [comment]
Hi,

I just tried this on a Requiem Joomla RocketLauncher install and changed a link in the Info List particle (module ID 295) and the changes saved fine for me.

This is using Gantry 5.2.8 and Joomla 3.5.0 beta, running MAMP on php 5.5.26 at the moment.

**Comment by kat05** [comment]
Just tried this in WordPress as well, in the Home outline -> Useful Links (in Footer-a) I removed the link from the 2nd item and saving worked fine for me.

**Comment by w00fz** [comment]
@unlmtd Could you try with the [CI Build](http://gantry.org/downloads#ci-builds) and see if this is still an issue?

**Comment by unlmtd** [comment]
@w00fz I will try in a moment.

**Comment by unlmtd** [comment]
Checking from my WordPress plugin page:
- Version 5.2.7: Works fine. Applied changes and saved successfully.
- Version 5.2.8 (from update button): Bug there. It doesn't even retrieve the link it had.
- CI Build (commit: 8803f8dd8): Bug still there.
- Reverted to 5.2.7: Worked fine again. Purple message on top of "Update to 5.2.8".
It is worth noting that I attempted to change the name of the outline from "Home" to "Inicio" (for the sake of having it translated to spanish) and my Layout modifications work was gone (it became the default for the RocketLauncher), so I reverted back the name of the Outline to "Home" and my modifications came back. Perhaps the real issue is on the renaming of the Outline?

**Comment by kat05** [comment]
Hi again,

I've just renamed my Home outline to Inicio and saw the error "404 Outline not found".
I renamed it back to Home.
Then I updated Gantry to latest CI.
Then I tried renaming the Home outline to Inicio again and this time I did not get any error anymore.

**Comment by kat05** [comment]
There is something wrong with renaming the outlines, also with latest CI build.
I could rename it once, then tried to rename to something else (a name I had not used before at all) and then I received

`403 Forbidden
Oops, Forbidden.`

**Comment by mahagr** [comment]
@unlmtd I fould out the issue: clearing cache from Gantry will fix the issue for you. I just need to find out why cache wasn't properly cleared up on upgrade.

**Comment by mahagr** [comment]
@kat05 The issue you are seeing isn't related to the one @unlmtd is having. They are two completely different issues, at least according to my testing.

**Comment by unlmtd** [comment]
Well, for now, I have not had the issue anymore (updated to Gantry 5.2.9), but I did not try to rename again the Home outline which was the one troublesome.
