### ISSUE TITLE
404 not found when adding an asset on page settings

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1126]
On Gantry 5.2.8 (5.2.7 doesn't have the issue) if you add a JS asset on the page settings tab, pick a JS asset and then click save you get a 404 not found.

![2016-01-29_08-39-53](https://cloud.githubusercontent.com/assets/11683218/12670954/4bb7afe0-c664-11e5-9c58-0dd15f2f2e42.png)

**Comment by kat05** [comment]
The same is happening when adding a CSS asset too. Gantry 5.2.8 and Joomla 3.5.0 beta. (3.4.8 too)

**Comment by kat05** [comment]
Just tested on WordPress 4.4.1, same issue there too.

**Comment by newkind** [comment]
Confirmed.

**Comment by kat05** [comment]
Fix confirmed in both Joomla and WP. :)

**Comment by marktaylor46** [comment]
yup confirmed on joomla for me too
