### ISSUE TITLE
Module List in Menu Editor Can Be Too Tall for Window

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#113]
If you're on a smaller screen with less resolution or working in a non full-height window, the menu list is a bit too tall so you can't reach the select button unless you scroll the page.

See linked video for example (20 seconds in).

https://www.dropbox.com/s/69kj0j13u6l68hw/ScreenFlow.mp4?dl=0

**Comment by w00fz** [comment]
That's what the scroll is for though :D

**Comment by w00fz** [comment]
Ok I reduced from 500px to 400px :+1:
