### ISSUE TITLE
Implement an universal method to call jQuery from Twig on all platforms

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1132]
@mahagr Hey Matias,

I was thinking about opening this issue for a week now and I just noticed that you actually [asked me to do so](https://github.com/gantry/gantry5/issues/1057) back in December :smile: 

So, could you please implement this "unique API" to load jQuery on all platforms? As we discussed in the other issue, it will check the platform you are on and then load the jQuery library that comes from the platform. 
For example, if you are on Joomla, you will call the new method/API, let's say: 

```
{{ gantry.load('jquery.framework') }}
```

which will then see that you are on Joomla and will call:

```
 {{ joomla.html('jquery.framework') }}
```

Something like that ;)

**Comment by JoomFX** [comment]
@mahagr Hey Matias,

Do you think this can be implemented until 1st of April?
There's no rush, I just need to decide how to proceed with my particles...
I want to make all my particles truly platform independent, so if this will not be implemented soon, can I use the following:

```
{% if gantry.platform.getName() == 'joomla' %}
	{{ joomla.html('jquery.framework') }}
{% endif %}

{% if gantry.platform.getName() == 'wordpress' %}
	{{ wordpress.call('wp_enqueue_script', 'jquery') }}
{% endif %}
```

I think it will do the job just fine :wink: 
What do you think?

**Comment by mahagr** [comment]
Yeah, I guess it can be done. Remind me if it hasn't been done within a week; I'm currently on a larger feature, and I'd like to get it done first.

**Comment by JoomFX** [comment]
Great! Thanks Matias :wink:

**Comment by mahagr** [comment]
Kept the syntax the same:

    {{ gantry.load('jquery') }}

Possible variations are atm:
- jquery
- jquery.ui.core
- jquery.ui.sortable
- bootstrap.2
- bootstrap.3 (only in WP)
- mootools
- nootools.more

If option is available in the platform, function returns `true`, otherwise `false`.

**Comment by JoomFX** [comment]
I love you xoxoxo :smile:
