### ISSUE TITLE
Error while saving layouts in outlines using Hydrogen theme 5.2.9 with gantry 5.2.9

### ISSUE THREAD

**Issue by bilalbutt** [gantry/gantry5#1135]
When ever I try to save/update layout in the outlines it shows a popup and says 

> 404 View not found [name, type, prefix]: category, json, contentView

Please help as I love gantry and would love to use the theme.
Attach is the screen shot of the error I get.

![layout-gantry](https://cloud.githubusercontent.com/assets/11819707/12853298/3338becc-cc55-11e5-9f6d-08ea5c03df4f.png)

**Comment by FrugalGeek** [comment]
Having the same problem when I edit particles with collections in them. 

Problem occurring in Xenon with latest Gantry.

![2016-02-06 22_09_16-window](https://cloud.githubusercontent.com/assets/4026828/12870874/c72a9a64-cd1e-11e5-8a3d-e51cd9c70ce7.png)

**Comment by kat05** [comment]
seems related to https://github.com/gantry/gantry5/issues/1125

**Comment by mahagr** [comment]
I don't think these two issues relate; one is in Joomla and another in WP.

@bilalbutt In your case, it looks like the response comes from the frontend, not from the backend, which really confuses me as it shouldn't happen. Can you join to our chat https://gitter.im/gantry/gantry5 and ping me in there so I can take a look into your site?

@FrugalGeek I tracked down your issue and it was related to caching the twig files. Clearing cache from Gantry fixed the issues in your site but I'm still looking why cache wasn't cleared up on upgrade.

**Comment by mahagr** [comment]
Update: It looks like there are some mod_security(?) rules that prevent AJAX responses from being loaded if they have JSON encoded attributes in them.

**Comment by mahagr** [comment]
It was mod_security issue. Closing.

**Comment by gaassis** [comment]
what do you mean!! i have a some problem error 404 categorie not found
