### ISSUE TITLE
Smart search not working on home page (Joomla)

### ISSUE THREAD

**Issue by anatamambo** [gantry/gantry5#1138]
Good day, after creating a smart search module and mapping to the header for Gantry5 Joomla ... It works just fine on all pages except for the home page ... On the home page it simply redirects onto itself on submitting a search ... The only difference was that the get variable itemid was set to 103 on the home page and to 107 for all other pages that work ... Is there a fix for this?

**Comment by mahagr** [comment]
Have you tried to create own hidden menu item for smart search?

**Comment by mariantanase** [comment]
Did you placed a **Page Content** on Hydrogen-Home Layout ?

**Comment by mahagr** [comment]
Well, usually the idea is not to use front page layout for search by specifying special menu item, which ensures that the search page always looks the same. In Joomla this can be done by creating menu item in a hidden menu for the search.

**Comment by mahagr** [comment]
BTW, you may also be able to fix the issue by adding Page Content particle into Home layout.

Is this still an issue or can I close the issue?

**Comment by mahagr** [comment]
Closing issue after month of inactivity from @anatamambo . We can reopen this issue if there will be new comments on the issue.
