### ISSUE TITLE
hydrogen missing some language strings when using joomla discover install

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#114]
i've done a discover install for hydrogen on j3.4.1 and there seem to be some language strings missing, namely:
TPL_G5_HYDROGEN_DESC
TPL_G5_HYDROGEN_HOME_STYLE
![g5_discover2](https://cloud.githubusercontent.com/assets/5719486/7305134/5e67259c-e9c1-11e4-8bde-fbc1b3a98745.jpg)
![g5_discover1](https://cloud.githubusercontent.com/assets/5719486/7305133/5e66ffea-e9c1-11e4-955e-172eaf2bc989.jpg)

**Comment by mahagr** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/6835

Please download patchtester from https://github.com/joomla-extensions/patchtester/releases in order to test it.

**Comment by kat05** [comment]
the patch works for me, no more missing language strings when using the discover install method.
