### ISSUE TITLE
RuntimeException on Cache File

### ISSUE THREAD

**Issue by egscentral** [gantry/gantry5#1140]
Hello. My site suddenly started returning a RuntimeException that seems to be a problem within gantry as far as I can tell. Here is the error log:

> PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Opening file for writing failed on error fopen(/nas/content/live/testzozoi/wp-content/cache/gantry5/g5_hydrogen/compiled/yaml/97fc94fb63983ca7cb44cbe1f6f8eac0.yaml.php): failed to open stream: Permission denied' in /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/File/src/File.php:202\nStack trace:\n#0 /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/File/src/File.php(316): RocketTheme\\Toolbox\\File\\File->lock()\n#1 /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\\Toolbox\\File\\File->save(Array)\n#2 /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/classes/Gantry/Component/File/CompiledFile.php(105): RocketTheme\\Toolbox\\File\\PhpFile->save(Array)\n#3 /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/classes/Gantry/Component/Layout/Layout.php(615): Gantry\\Component\\File\\CompiledYamlFile->content()\n#4 /n in /nas/content/live/testzozoi/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/File/src/File.php on line 202

Is there a way to fix this?
Thanks,
Kyle

**Comment by mahagr** [comment]
You have wrong permissions in that file. Cache folder should be writeable by Apache.

Easiest way to fix this is to remove all files under `/nas/content/live/testzozoi/wp-content/cache/gantry5` and make sure it has proper permissions.

**Comment by w00fz** [comment]
Did you manage to solve this @egscentral ? If so please feel free to close the issue.

Thanks.

**Comment by mahagr** [comment]
Closing the issue due to inactivity. It can always be reopened if its still an issue.
