### ISSUE TITLE
Imagepicker -section.html.twig file changes

### ISSUE THREAD

**Issue by ki0kk** [gantry/gantry5#1141]
I am trying to follow the gantry documentation to insert the imagepicker for the header.  I have the first file modifications complete but the documentation is missing the text for the section.html.twig file changes?

**Comment by w00fz** [comment]
Sorry about that, something odd with the site. We are looking into it.

**Comment by FrugalGeek** [comment]
Hello there,

My fault. We changed our documentation site around this week and it was my job to go through and turn off twig processing in the documentation. This page slipped through the cracks. It's fixed now. Thanks for bringing to our attention.

**Comment by ki0kk** [comment]
TNX, see the text now.

Greg
