### ISSUE TITLE
Error After Updateing To 5.2.10 Version

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#1142]
Error displaying the error page: An exception has been thrown during the rendering of a template ("Creating directory 'public_html/templates/g5_hydrogen/custom/css-compiled' failed on error mkdir(): File exists") in "@nucleus/page_head.html.twig" at line 6.: An exception has been thrown during the rendering of a template ("Creating directory '/public_html/templates/g5_hydrogen/custom/css-compiled' failed on error mkdir(): File exists") in "@nucleus/page_head.html.twig" at line 6.

**Comment by mahagr** [comment]
Upgrading theme deletes the given folder `public_html/templates/g5_hydrogen/custom/css-compiled` so check out if it still exists. You are safe to remove `css-compiled` if it exists.

I don't know what causes the error; did you move the site? Are the file permissions ok?

**Comment by rgblogs** [comment]
Updating from 5.2.9 works.

Earlier I was upgrading from 5.2.4 version.

**Comment by mahagr** [comment]
Glad you have solved the issue. I don't think there is anything we can fix on this what isn't already been fixed, so I'm closing this issue.
