### ISSUE TITLE
Add title field to the Custom HTML particle

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1143]
Add title field to the Custom HTML particle

**Comment by w00fz** [comment]
Wouldn't this be redundant? Being a Custom HTML field, you can just add the title (no string attached!) in the content itself, ie:

```
<h1>My Title</h1>
<p>Content</p>
```

**Comment by newkind** [comment]
I agree with @w00fz, besides if there would be a title field there would have to be a specified place to render it and that's not the point of the Custom HTML particle. This would be very limiting.

**Comment by mahagr** [comment]
I agree. Additionally at least Joomla has its own title for modules, so this particle would end up having two titles.
