### ISSUE TITLE
js error randomly happening in admin which causes certain issues

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1145]
I've seen it in Joomla with 5.2.8, 9, 10 and also in latest CI, but can not pinpoint exactly when it starts.

The js error is

Timestamp: 12/02/16 11:53:12
Error: TypeError: body is null
Source File: .../administrator/components/com_gantry5/js/main.js?56bdb99e line 28146 > Function
Line: 194

It can cause all sorts of issues, like saving not working, popups not opening or opening empty, etc.
Usually a refresh will fix it, but if you don't know that and don't realize there is an actual js error, then that's pretty annoying.

**Comment by mahagr** [comment]
If possible, can you keep inspector open to see what is there in the response? I'm suspecting this may be the same Apache crashes on PHP segmentation fault which have been seen by some our users in PHP 5.5 with Opcache PHP module turned on.

**Comment by kat05** [comment]
i see this error locally on 5.6.10 and also on our sandbox, if you wanna take a look yourself.

**Comment by w00fz** [comment]
Hey @kat05 is this still an issue? Been a while! Wonder if you ever got this error again. There have been some defer issues in the previous versions that would have caused this kind of error but they seem to have been resolved already.

**Comment by mahagr** [comment]
I've not seen or heard of this issue anymore, maybe @hexplor can tell me if he has seen those anymore.

**Comment by hexplor** [comment]
Yeah. I didn't experience it either for some time.

**Comment by mahagr** [comment]
I'm closing this issue as its likely been fixed along with the defer issues @w00fz mentioned above.
