### ISSUE TITLE
Removed last instances of prefixed box-sizing (deprecated) 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1148]
As mentioned on chat, there seem to be more instances of @include box-sizing that need to be removed.

../gantry5/engines/joomla/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss
../gantry5/platforms/common/scss/admin/particles/_colorpicker.scss
../gantry5/platforms/common/scss/admin/_core.scss
../gantry5/engines/common/nucleus/scss/nucleus/_core.scss
../gantry5/engines/joomla/nucleus/scss/joomla/_forms.scss
../gantry5/platforms/common/scss/admin/_modal.scss
../gantry5/platforms/common/scss/admin/_selectize.scss
../gantry5/platforms/common/scss/admin/_toastr.scss
../gantry5/engines/joomla/nucleus/scss/joomla/_utilities.scss

**Comment by w00fz** [comment]
They are removed, you need to look in the proper branch

**Comment by w00fz** [comment]
https://github.com/gantry/gantry5/commit/afa705e8b4c26ef54847303785f6e72d75e77e08 
Branch scss34

**Comment by kat05** [comment]
got it, thanks! :)
