### ISSUE TITLE
Layout manager: add support for fixed width sections

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#115]
As an example we have three column layout with 40% main content and 30% sidebars in both sides:

xxx  | yyyy | zzz
---- | ------- | ------

When the left size collapses, both remaining columns get multiplied by 0.7/1 = 1.43:

yyyyyy | zzzz
------ | -----

Instead of resizing the remaining sidebar, we need an option to lock both sidebars to 30% allowing main content to fill up the space and become 70%.

yyyyyyyy | zzz
------ | -----

Easiest way to do it is to add a new option to the sections to lock/unlock the size.

**Comment by nicutor** [comment]
+1 on this. I am using this on a template and the layout is broken when a sidebar content is missing.
