### ISSUE TITLE
Gantry5 woo-commerce assignment issue!

### ISSUE THREAD

**Issue by yone920** [gantry/gantry5#1150]
I am building a woo-commerce online store with gantry5. I want to create an outline for single product page but there is option to do that. All I can do is assign to already added products to the specific outline. This way however I have to do this every time I added new product!!!

**Comment by w00fz** [comment]
Related to #928 and #1115

**Comment by adi8i** [comment]
ust to complete, there's an issue for pages also, you can assign an outline for first page but not for others e.g. `.../shop/page/2/`

**Comment by freddie79** [comment]
I am also having issues assigning an outline to the WooCommerce Shop page. I have selected Shop from the Menu and Pages lists but it is still just using the default outline. I assume this is related to the above issues unless I'm doing something wrong. Worked fine in Gantry 4. Thanks.

**Comment by newkind** [comment]
Closing! :) Please test and re-open in case of issues.
