### ISSUE TITLE
Cache Errors

### ISSUE THREAD

**Issue by egscentral** [gantry/gantry5#1155]
Hello. I am using Gantry 5 on a site hosted by WP Engine. If visitors to the site are not logged in as an admin they will get 500 errors on some pages because Gantry tries to save a cache file and is unable to for permissions reasons. When it is unable to save the file it throws and uncaught exception in php and exits rendering the page inaccessible. I found a documentation page on a similar issue that recommends setting the affected files' permissions to 755, however my files are already all set to 775 so this should not be an issue. To be honest, it would be ideal for me to just disable Gantry's caching because WP Engine has this built in, but at this point I will take anything that makes the site functional.

Thanks
Kyle

**Comment by newkind** [comment]
Hi Kyle,

We actually have a workaround for caching in WPEngine. WPEngine doesn't allow compiled PHP files in the wp-content/cache/ directory so you need to go to the Plugins > Gantry 5 Framework > Settings (right below the plugin name) and change the custom location to :

`/tmp/<some random characters>/cache/gantry5/`

ie.

`/tmp/dasd878asd980asd98das/cache/gantry5/`

This should make Gantry 5 cache work just fine with WPEngine.

Thanks,
Jakub

**Comment by newkind** [comment]
This has been officially documented now ;)

[Workaround for Issues with Cache Directory Restrictions](http://docs.gantry.org/gantry5/troubleshooting/permissions-error#workaround-for-issues-with-cache-directory-restrictions)

**Comment by jamgit** [comment]
Anyone reading this now might have gotten same experience for me where this workaround is not always successful. After performing this on wpengine I am still getting some 500 errors. So am looking to root out why. See below a file still not writing to this created directory:
Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/nas/content/live/silostaging/tmp/qetuol49bei873lkkj/cache/gantry5/rt_gemini/twig/c7/c7199fc856cfe0f4d20f8ff34ecb012fe76d5826e73e3f8e0b05645c253617b8.php

**Comment by mahagr** [comment]
`Failed to write cache file` should tell everything -- it looks like PHP doesn't have rights to write the file. Make sure you configure Gantry to use cache folder where it has rights to write PHP files.

Those files are written by Twig templating engine and they contain compiled PHP versions of all the twig files.

**Comment by jamgit** [comment]
Just for other peoples reference for WPEngine, it looks like we found a solution that works. It is to do a proxy pass of the entire site directly to apache. Putting in location ~* ^/ { proxy_pass http://localhost:6788; } to nginx seems to have worked. I have not done this before so not sure if there will any negatives to doing this, but it is working so far.
