### ISSUE TITLE
Issue with the "Page Content" particle and the "Sourcerer" extension by NoNumber

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1157]
@mahagr Hey Matias,

I believe this is for you.
There seems to be a little issue when using [NoNumber's Soucerer](https://www.nonumber.nl/extensions/sourcerer) with Gantry5.

So, when you have a page (menu item) of type `Gantry 5 Theme -> Custom Page` the "Page Content" particle is not supposed to be rendered on the frontend because there is actually no content.
But as soon as you install NoNumber's Soucerer, Gantry 5 assumes that there is content and renders the empty particle.

This issue/change in behavior was introduced in Gantry 5.2.8. If you install Gantry 5.2.7 the issue is no longer reproducible.

I will contact Peter from NoNumber but before that I wanted to see what you think about it, since everything works as expected in all versions prior to 5.2.8. What has changed in 5.2.8?

I'm not sure if I explained the issue properly so I recorded [a short video](https://youtu.be/Cc59WSl98qE) showing everything ;)

**Comment by mahagr** [comment]
`Compatibility fix for some plugins which require non-empty component output to work properly` was the fix and it was to make some other NoNumber extension to work properly.

**Comment by mahagr** [comment]
BTW: For some reason inspector isn't showing <script> tag, so you'd better to look into source code, I think it shows a script in the component output..?

**Comment by JoomFX** [comment]
Yes, this is the commit responsible for the different behavior, thanks Matias.

Alright, two more question:

1. Is this the permanent solution from G5 site? Can it be done in a different way so "Page Content" particle is not loaded when Sourcerer is enabled? I'm talking about the `echo "\n";` code.

2. Do you think that something can be done/improved on the Sourcerer side so it does not cause this issue in G5? If you have time you can have a look at `helper.php` in Sourcerer.

Or should I just live with it ? :smile:

**Comment by w00fz** [comment]
I think the issue Matias is bringing up is that the previous fix he mentioned was to allow other NoNumber extensions to function when the content was empty. Now this other NoNumber extension behaves exactly the opposite.

Sounds to me like this is an inconsistency in the way some extensions work and while I'm sure we could technically fix this for Sorcerer specifically, I don't like the idea of hardcoded exceptions for 3rd parties in Gantry itself.

**Comment by JoomFX** [comment]
Thanks for your input Djamil.

Yes, I also do not think that adding exceptions for 3rd party extensions is a good idea - once you start doing it the list might never end :wink: 

Alright, I'll write to Peter from NoNumber tomorrow and see what he says. I might also ask him to comment here :wink:

**Comment by JoomFX** [comment]
Alright guys, here's the answer I got from Peter:

> Like stated in that issue discussion:
> "I also do not think that adding exceptions for 3rd party extensions is a good idea"
> 
> The same reasoning here.
> 
> The Gantry framework overrides core Joomla behaviour and causes issues with other extensions that rely on that core behaviour.
> I can only do so much to work around issues Gantry throws at me.
> 
> You'll just have to accept that Sourcerer and Gantry seems incompatible in this case.

I was wondering, is the "Compatibility fix" needed? I mean should this be included in Gantry? I suppose yes, since the component output is always available in Joomla, but I'm just asking.

**Comment by JoomFX** [comment]
If it helps, the following code from line 137 in `helper.php` in Sourcerer triggers the component output:

```
$buffer = JFactory::getDocument()->getBuffer('component');
```

**Comment by mahagr** [comment]
Well, basically Gantry has no component output in one of the menu items, allowing you to create a page that has been built from modules only. There is no special output or logic, just empty buffer. It also works with other Joomla templates, though some CSS tricks may be needed to remove empty space.

What I changed was to add `\n` to the output to make it not empty as some other extensions were requiring component output or they were turned off from the whole page. Easiest way to add the compatibility fix would be make a small change into sourcerer helper.php line 137:

    $buffer = trim(JFactory::getDocument()->getBuffer('component'));

**Comment by JoomFX** [comment]
Thanks Matias!

I forwarded your suggestion to Peter and here's what he said:

> Can't do that as the JFactory::getDocument()->getBuffer('component') can potentially return an array.
> But changed the check to see if it is empty or not.
> 
> I changed this check in all my extensions that do frontend stuff.

I just tested the development version of Sourcerer and it works just fine with Gantry 5, the "Page Content" particle is no longer triggered.

You can close the issue now :wink:

**Comment by mahagr** [comment]
Oh, I forgot the array output, but the idea for the array is the same.

I'm just a bit worried that Peter has accidentally broken the another extension which we originally fixed... I think it was NoNumber Modals which stopped loading scripts if component buffer was either empty or an array. So basically all pages with no content had broken modals in all module positions.

**Comment by JoomFX** [comment]
Alright, do you mean that the other extension (NoNumber Modals) will be accidentally broken in G5 only, or it will be broken in general?

What Peter did in Sourcerer is this... he replaced this code:

```
		$buffer = JFactory::getDocument()->getBuffer('component');

		if (empty($buffer) || is_array($buffer))
		{
			return;
		}
```

with this one:

```
		$buffer = JFactory::getDocument()->getBuffer('component');

		if (empty($buffer) || !is_string($buffer))
		{
			return;
		}

		$buffer = trim($buffer);

		if (empty($buffer))
		{
			return;
		}
```

Should I just tell him to double check the Modals extensions?

**Comment by mahagr** [comment]
Modals is already broken with empty component output, which is why I created the workaround for Gantry to make output to be always non-empty. Basically if he replaces the code with the new one also in Modals, it would break the plugin again.

I have no idea why empty buffer test is needed (I can think of having empty output if there is an uncaught exception..?), but in the case of NoNumber Modals, the logic should be different to cope with pages without component output but with a lot of modules.

**Comment by JoomFX** [comment]
This is the update I got from Peter:

> Please try the latest development version of Modals from:
> www.nonumber.nl/development-releases
> 
> This should probably fix the issue you had (making the work-around in Gantry no longer necessary).

So I tested NoNumber Modals with and without the "Compatibility fix" (I deleted `echo "\n";` from `gantry5.php`) and it works just fine.

Should we remove the "Compatibility fix" now? It is up to you, my issue is resolved anyway, so it is just up to you to decide if `echo "\n";` should be there or not :wink:

**Comment by JoomFX** [comment]
There's also the following message in the changelog of both Sourcerer and Modals:

` # Fixes incompatibility with Gantry templates that do not load a component area`

**Comment by mahagr** [comment]
I'm tempted to remove the workaround in Gantry, which would also allow Peter to remove workaround for the workaround.

**Comment by mahagr** [comment]
@JoomFX @nonumber

After some thinking I have decided to remove the original workaround. I still think that the real issue was rather unexpected behaviour of Gantry component and not a bug in NoNumber products, but I also think that just removing the workaround in both ends would be the best solution.

Peter, thanks for your efforts to fix the issue. I didn't originally contact you on Modals issue as I was thinking that Gantry was the one to blame. Now I regret my decision as your fix in Modals looks much cleaner fix.

The reason why Gantry 5 isn't outputting component at all is that it allows you to build pages which consist of modules only. Gantry 4 also had the same feature in home page, but it was hardcoded just not to render the articles component, which was both inefficient and caused other issues.

**Comment by JoomFX** [comment]
Great! Thanks Matias.

I just pinged Peter to make sure he sees your comment.
