### ISSUE TITLE
Gantry 5 template - jomsocial - video not playing

### ISSUE THREAD

**Issue by avn12** [gantry/gantry5#1158]
We have an issue with gantry 5 template that does not allow to play videos on Jomsocial http://zdorovio.com/video/1110-andy/video/1983-o-tomatnoj-paste-i-ketchupe  Video is not played - just show the link "javascript".  We checked with Jomsocial and they said the problem is with gantry template (latest version).  Video works when gantry template is switched off. (Jomsocial installed on the site is  the latest version 4.1.6.)

**Comment by w00fz** [comment]
The issue is that you have a `<noscript>` tag injected in the `<head>` element. `<noscript>` is a DOM element and is not allowed in the head, it should go in the body.
This seems caused by googlemanager, how are you using this code? Are you using an Atom for it?

**Comment by avn12** [comment]
Thanks! Fantastic! Case sovled!

**Comment by w00fz** [comment]
:+1:

**Comment by AANNQ** [comment]
@avn12 could you please share with me how to fit this? Tks!
