### ISSUE TITLE
Joomla content support in particles

### ISSUE THREAD

**Issue by iliali16** [gantry/gantry5#1160]
Hi guys,

I have this problem, I have a link to an article in hydrogen template but I have no idea how and where to outputi it. Can you please help me?

**Comment by mahagr** [comment]
Sorry, but I cannot understand what you are trying to ask.

Are you trying to add a link to an article? In Joomla you create a (custom html) module which you assign to proper position, where you would like to show it. In Hydrogen you can do the same, but you are not restricted just on existing module positions; you can also create your own in Layout Manager, or you can use a particle to do the same.

**Comment by iliali16** [comment]
Ok, so basicly, I have an article in joomla.
I have created a module that lists the category of articles and have placed it in the hydrogen template in a layout I want to see it.
Now I have this problem where when I click the link in this module it takes me to the home page but I don't want it there.
I want to create a layout which will display the articles from this category.
Any help will be appreciated.

**Comment by mahagr** [comment]
Joomla is very limited on this; basically it either uses the current menu item or picks up the first menu item with Articles component in it. The solution is not to use Articles as your home page (you can use `Gantry / Custom` instead) and by creating own menu item for articles entry point.
