### ISSUE TITLE
Adding stuff after <body> and before </body> from an Atom

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1161]
Hey guys,

I'm looking for exactly the same options as the ones under "Page Settings" - `After <body>` and `Before </body>` but for Atoms. I mean, a syntax that will add an element immediately after `<body>`. Is that possible? If not, can it be added in a future release?

This will be a really nice addition. Here's an example...
I'm currently working on a "Page Preloader" Atom. It needs an HTML element immediately after `<body>` in order to work properly. I can add the HTML element from "Page Settings" but imagine how much easier and user-friendly it will be if I can do everything from the Atom. Then the user will just drag & drop the Atom and everything will be working out-of-the-box :wink:

**Comment by JoomFX** [comment]
I tried adding the HTML element with JS but it doesn't work in this case, I mean the element is added but too late as it takes time for the JS to load. The HTML element should be part of the markup by default and therefore I need to add it somehow from the Atom.

If this is not currently possible in G5, can we just add a new "placeholder" in `page.html.twig` similar to `{{ gantry.config.page.body.body_top|raw }}` where we can inject stuff directly from Atoms? Like we can currently add JS and CSS but for HTML elements as well :wink:

**Comment by mahagr** [comment]
I thought we already had issue on this, but... I guess not or it was closed.

**Comment by JoomFX** [comment]
Hey Matias,

Do you think that this can be implemented for the next release? :wink:

**Comment by mahagr** [comment]
I was thinking it already for the yesterdays release, but didn't have time to do it. We'll see. :)

**Comment by JoomFX** [comment]
Thanks Matias :)

**Comment by JoomFX** [comment]
Matias, since you just said in the Gitter chat, that the next G5 release is soon, it is time for me to bug you about this :smile: 

Any chance that this feature can be ready for the next G5 release? I really need to use it for our April's template. Thanks :wink:

**Comment by JoomFX** [comment]
@mahagr @w00fz guys, I know that you are just about to release, but do you think this enhancement can make it for this release or there will be no time for it?

**Comment by mahagr** [comment]
I don't think its going to make it because of I still need to look into some bugs.

**Comment by JoomFX** [comment]
Ok, thanks Matias.
I'll wait for it in some of the future releases :wink:

**Comment by mahagr** [comment]
New tag can be used from anywhere:

```twig
{% pageblock top %}
    -PAGE TOP-
{% endpageblock %}

{% pageblock bottom %}
    -PAGE BOTTOM-
{% endpageblock %}

{% pageblock body_top %}
    -BODY TOP-
{% endpageblock %}

{% pageblock body_bottom %}
    -BODY BOTTOM-
{% endpageblock %}
```

It works like a block, but you don't need to define it in parent template file. Also accepts `with {priority: 0}` just like javascript and style blocks.

**Comment by mahagr** [comment]
Also documented.

**Comment by JoomFX** [comment]
Hey Matias,

Thank a lot for that!
It is a really nice addition 😉
