### ISSUE TITLE
Loading assets from Atoms with "Priority"

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1164]
@w00fz @mahagr Guys, how can I load assets from Atoms with "Priority"?

It doesn't seem to be possible. The only blocks that actually work in Atoms are:

```
{% block stylesheets %}
    {{ parent() }}
    {# any stylesheet you would like to render in <head> #}
{% endblock %}

{% block javascript %}
    {{ parent() }}
    {# any javascript you would like to render in <head> #}
{% endblock %}

{% block javascript_footer %}
    {{ parent() }}
    {# any javascript you would like to render before </body> #}
{% endblock %}
```

But I cannot use the following, it doesn't work from Atoms:

```
{% assets in 'head' with { priority: 10 } %}
    {# any assets you would like to render before <head> #}
{% endassets -%}
```

And I really do need to set a priority :wink:

**Comment by JoomFX** [comment]
UPDATE :smile: 

Well, it seems that I can use `{% assets in 'head' with { priority: 10 } %}` from an Atom but it needs to be inside `{% block particle %}`. Here's the working code:

```
{% block particle %}
    {% assets in 'head' with { priority: 10 } %}
        {# any assets you would like to render before <head> #}
    {% endassets -%}
{% endblock %}
```

But here comes another confusion - is it ok to use `{% block particle %}` in **Atoms**? Isn't `{% block particle %}` meant for **Particles** only, for visible elements?

**Comment by JoomFX** [comment]
Another update...

It seems that the following codes do absolutely the same job, they put the asset (in my case CSS) in absolutely the same place:

```
{% block stylesheets %}
    {{ parent() }}
    {# any stylesheet you would like to render in <head> #}
{% endblock %}
```

Does the same as:

```
{% block particle %}
    {% assets in 'head' with { priority: 10 } %}
        {# any assets you would like to render before <head> #}
    {% endassets -%}
{% endblock %}
```

What I'm trying to accomplish is to load a CSS file before the the theme files, from an Atom. Any way to do that?

We need to be able to do that (load CSS files before the theme files) so we can easily override the CSS rules, without CSS specificity. Don't ask me "why without CSS specificity" :smile:

**Comment by JoomFX** [comment]
Alright guys, I found a better solutions for my particular case so I'll just close this issue.

Can you just comment if it is possible to load CSS assets from an Atom before the theme CSS files and if it is possible, what is the exact syntax? I just want to know, it might be helpful.

If it is not possible, I'm still fine :wink:

**Comment by mahagr** [comment]
You should use `{% assets in 'head' with { priority: 11 } %}` inside block to insert the files before the theme. By default theme uses priority 10 where atoms and particles use priority 0.

**Comment by JoomFX** [comment]
Thanks Matias.
I didn't know I can use `{ priority: 11 }` - I thought I can only use from `-10` to `10` :wink:
