### ISSUE TITLE
WordPress theme updater

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1165]
Would be awesome if we could enhance WordPress exprience with auto updater or something that would make the theme updating process much easier.

**Comment by DamirPecnik** [comment]
Yep awesome idea!

**Comment by mahagr** [comment]
I did some research on this. The following may or may not work:

* Hook to `upgrader_package_options` filter and make `abort_if_destination_exists` field to reference a new field in `hook_extra`.
* Hook to `upgrader_source_selection`, it will allow you to check what is being installed and change `abort_if_destination_exists` to false.

**Comment by mahagr** [comment]
Small test:

```
$array = ['ref' => ['a' => 'foo']];
$array['a'] =& $array['ref']['a'];
function test($ref) { $ref['a'] = 'bar';}
test($array['ref']);
print_r($array);
```

Result:

```
Array
(
    [ref] => Array
        (
            [a] => bar
        )
    [a] => bar
)
```

**Comment by mahagr** [comment]
Bah, it won't work. There's one extra function call that instead of using the array, copies the value of abort into a parameter. :(

**Comment by mahagr** [comment]
A true hack to workaround the issue. :)

```
class Truthy extends SimpleXmlElement { }
$array = ['ref' => ['a' => new Truthy('<bool><true></true></bool>')]];
$array['a'] = $array['ref']['a'];
function toFalse($ref) { if ($ref instanceof Truthy) unset($ref->true);}

echo $array['a'] ? 'true' : 'false'; // true
toFalse($array['ref']['a']);
echo $array['a'] ? 'true' : 'false'; // false
```

**Comment by mahagr** [comment]
The only downside is that only tests like $a and !$a are allowed...
