### ISSUE TITLE
Cannot save offline outline layout - get whoops error

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1167]
If you go to "offline" outline and then to layout tab and just press the "save layout" button then you get a "whoops" error "try to get property of non-object in templateinstaller.php.

I tried this in several template and they all do the same so my guess is that this is Gantry 5 rather than any template. It happens in both G5.2.11 and G5.2.12.

![2016-02-29_07-52-32](https://cloud.githubusercontent.com/assets/11683218/13388660/c1c321b6-deb9-11e5-9988-c0fca7158a8c.png)

**Comment by kat05** [comment]
I've tried in Galatea and Kraken and on both it works fine for me.
This might be a setup specific issue, my tests were done on MAMP.

**Comment by marktaylor46** [comment]
I am on windows 10 64 bit with WAMP.

I regressed top G5.2.10 and then I could save the offline outline layout without issue.

Then I installed 5.2.11 and it then broke. So it appears the issue is in 5.2.11.

**Comment by marktaylor46** [comment]
member with issue in RT forum here:
http://www.rockettheme.com/forum/joomla-template-galatea/255713-new-install-error-on-template-offline-layout?start=0#1275972

**Comment by marktaylor46** [comment]
confirmed fix
