### ISSUE TITLE
Hydrogen child theme

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1169]
Hello
for sure I'm a dummy but please someone can explain me how make a child theme assuming that I use the last version native Hydrogen5 template. I've read the doc but I always have some errors, this was the last one
** RuntimeException (404)

Theme g5_hydrogen-child not found **

Should be nice to have a native Hydrogen-child.zip added on G5 official site

**Comment by newkind** [comment]
There is a sample hydrogen-child theme in the git here : https://github.com/gantry/gantry5/tree/develop/themes Just download the zip and you can use it as a sample ;)

**Comment by prankyboy** [comment]
well... thx newkind...
uhmmmm... folder filename.... g5_hydrogen-child? 
I read for example rt_hydrogen but the parent template name is g5_hydrogen right?

**Comment by newkind** [comment]
Child theme in git is set to have parent theme under dir `rt_hydrogen` and child theme ie. `rt_hydrogen_child`. You can change these dirs to whatever fits you.

**Comment by prankyboy** [comment]
mumble mumble... ok... let me see...

**Comment by newkind** [comment]
Ok, the updated files are in git. Child theme should be now properly referencing `g5_hydrogen` parent theme instead of `rt_hydrogen`

**Comment by prankyboy** [comment]
thx again... maybe i made something wrong but it's a mess...
`            $gantry = Gantry::instance();
     
            /** @var UniformResourceLocator $locator */
            $locator = $gantry['locator'];
     
            $filename = $locator->findResource("gantry-themes://{$theme}/gantry/theme.yaml");
            if (!$filename) {
                throw new \RuntimeException(sprintf('Theme %s not found', $theme), 404);
            }
     `

**Comment by newkind** [comment]
Do you have 2 directories under you wp-content/themes/ :
- g5_hydrogen
- g5_hydrogen_child ?

**Comment by prankyboy** [comment]
yep I got them

**Comment by newkind** [comment]
Are your files updated ? Is your Hydrogen and Hydrogen Child updated to the latest changes in git or the hydrogen has been there for a while ?

**Comment by prankyboy** [comment]
YESSSSSSsssssss.......  great man! I got it. 
Ehm... I think I'll never tell someone what was my fault.
Newkind your help was really precious. 
I dont' know if I can make an answer about custom.scss
at this point I've to use style.css file in child theme to override some css and not custom.scss as in joomla, right?

**Comment by newkind** [comment]
Nope, you can use custom.css just fine ;)

**Comment by prankyboy** [comment]
we are talkin about the same file
custom.scss right?

**Comment by newkind** [comment]
Yes, custom.scss - if you want the css stuff to be only in the child theme - create it in the child theme. If you want it to be in both, create it in parent.

**Comment by prankyboy** [comment]
Thank you again man, now it's up to me and I dont' wanna bother u anymore. 
take care! ;-)

**Comment by newkind** [comment]
No worries. I'm closing this issue ;)

**Comment by matias-tecnosoul** [comment]
Hi, sorry to bring this back, but we're having questions about the **location of the custom.scss** file (_using WP v4.6.1, Hydrogen v5.3.6 and Gantry v5.3.6_). We've placed it inside a couple of folders to try to make it work:
**themes/child-folder/custom/custom.scss
themes/child-folder/custom/scss/custom.scss
and even in themes/child-folder/custom.scss**
none of them worked. Finally we tried inside:
**themes/child-folder/custom/blog-16** and it seems to be working in there. Is that correct?
thanks in advance!

**Comment by mahagr** [comment]
The proper location is `themes/child/custom/scss/custom.scss`, though it will not get picked up unless you're running on development mode (switch inside Gantry). Try recompiling CSS just in case.

**Comment by matias-tecnosoul** [comment]
Hi, indeed we are running on "development mode", however it didn't seem to work inside that location `themes/child/custom/scss/custom.scss`. 
Something similar it happening with some particles (Tabs Particle) I'm trying to add, I'm following the docs in [http://www.inspiretheme.com/documentation/gantry5-particles/tabs]. With the particle issue I'm in the parent theme, not the child.
I don't know if that's related and can help finding the issue.
Another possible related thing is that I had problems with the permissions of the folders. Since I'm using a local testing server I even tried setting 777 permissions.
Thanks again

**Comment by mahagr** [comment]
Apache does need read permissions to access the file, but basically having 0777 permissions will allow anyone to read the file, so it shouldn't be the issue. 

I do have debugging tool available for WP, which allows us to see what the search locations for the files are. PM me in gitter chat (https://gitter.im/gantry/gantry5) if you want to get the tool.

Also have you tried to do this without child theme as Gantry has custom folder to avoid child theme creation altogether..?

**Comment by matias-tecnosoul** [comment]
ok thanks, I'm going to gitter to get that tool cheers!
also wanted to ask u what do u mean by 

> Also have you tried to do this without child theme as Gantry has custom folder to avoid child theme creation altogether

That is not necessary to create child themes in Gantry??

**Comment by mahagr** [comment]
Gantry supports theme customizations out of box by allowing you to override most files in `custom/` folder under the theme. So if you just want to change files, just copy them over into `custom/` with the identical path. Gantry also allows files outside of theme (eg. in Gantry itself) to be overridden.

**Comment by matias-tecnosoul** [comment]
nice, so just to clear up, child themes would be unnecessary? or are there any other benefits?

**Comment by mahagr** [comment]
It depends on what you want to do. If you just want to override/change some files, no child theme is needed.

**Comment by matias-tecnosoul** [comment]
ok, thanks.
Back to the particles issue, I remembered that the only way to make the Ulkit Atom appear was to add it to the root particles folder (not custom/particles), I know its not correct but in that moment I needed to make it work and let it that way. 
I'm trying now on another server and I'm seem to be having the same issue installing the Ulkit atom. I'm using a multisite wp installation in both locations in case that matters.
Btw, let me know if we should open another issue.
thanks again!!

**Comment by matias-tecnosoul** [comment]
Having same results on our online server :(
Also I'm trying to install the Ulkit atom in Helium theme and same results.
Thanks for any hints!

**Comment by matias-tecnosoul** [comment]
If I move the uikit.html.twig, uikit.yaml and tabs.html.twig and tabs.yaml files to the root particles folder I can see them.
The Ulkit atom shows up in the "page settings"
![screenshot from 2016-11-07 19-00-02](https://cloud.githubusercontent.com/assets/19720454/20077769/87b2f3a0-a51c-11e6-93cd-a15cdd983398.png)
but when I go to configure the Tabs particle in the Layout home section I see this message 

> This Particle requires the "UIkit for Gantry5" Atom to be loaded.

is that right? (I see the same on our local server as on our production server and with the parent and child themes) cheers

**Comment by JoomFX** [comment]
Hey @matias-tecnosoul ,

I recorded few videos for you.

[This video](https://youtu.be/1BKKWxBh5GI) shows that the `custom.scss` file in the CHILD theme (Helium) works just fine.

[This video](https://youtu.be/wVfnTIwU9Rw) shows that the "UIkit for Gantry5" atom works just fine in both the main theme's `custom/particles` directory as well as in the child theme's `custom/particles` directory. What you should have in mind is that if you are using a CHILD theme you must add the particle there (not in the parent).

And finally, [this video](https://youtu.be/C-klgRojbOo) shows that the "Tabs" particle works just fine in both the parent and the child themes. And yes, the `This Particle requires the "UIkit for Gantry5" Atom to be loaded` notice will always be there, no matter if the "UIkit for Gantry5" atom is loaded or not. It is just a notice that informs the user that the "Tabs" particle will not work if the "UIkit for Gantry5" atom is not loaded.

**Comment by matias-tecnosoul** [comment]
for sure they work fine!! I'm not suggesting they dont, I'm trying to find out why they don't in my servers.
Thanks a lot for your time!! I'll check the videos and keep trying out...

**Comment by matias-tecnosoul** [comment]
really nice!! :D I really appreciate your help! (sorry if my english is not too clear).
I'll keep working tomorrow!
thanks again!!

**Comment by matias-tecnosoul** [comment]
I'm not seeing in your videos the `blogID` folders inside the `custom` folder. Maybe that's the thing!! since I'm using a **multisite WP** installation (as I mentioned previously) I have to do all the job planned for the `custom` folder in each of the `blogID` folders!?

**Comment by matias-tecnosoul** [comment]
It seems that was the issue!! if you're **using a multisite installation of WP** you have to create all the files and folders planned for the `custom` folder inside the `custom/blogID` subfolder. The `blogID` folder is automatically created by gantry for every site using the theme. I enclose a screenshot of the folder structure.
![screenshot-filezilla-gantry-wp-multisite](https://cloud.githubusercontent.com/assets/19720454/20115002/5f71243e-a5d5-11e6-9434-819a71d0a700.png)

 Thanks a lot for everyone's help!! :+1:

**Comment by mahagr** [comment]
I had totally forgot this, we need to add it to the documentation. @FrugalGeek @newkind
