### ISSUE TITLE
custom.scss in wp

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1170]
The custom.scss in wp can be managed in backend as in joomla installation? If yes which is the path for this file?

**Comment by newkind** [comment]
I'm not sure if I know what you have on your mind. But all Gantry functionallity should the same (or almost the same) in all platforms.

**Comment by prankyboy** [comment]
Oooops good mornin newkind
I think the same but seems to me there are little differences. In joomla I put the custom.scss in theme-directory/custom/scss and after this i can manage the file in the backend editor.
On wp I made the same putting the file in child-theme-directory/custom/scss but I don't see the custom.scss in editor

**Comment by newkind** [comment]
Morning ;) That's not Gantrys fault but WordPress'es. WordPress file editor is very basic and poor. I'd suggest you to install any CSS/SCSS editing WP plugin. I'll investigate if we can add some more paths to the WP core file editor so there wouldn't be need of plugins to do basic editing.

**Comment by prankyboy** [comment]
Auff great! I'm happy to not have made another silly question ;-)
