### ISSUE TITLE
Set gantry5 frontpage as home in wp

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1171]
I missed the hydrogen frontpage as home. On Home page the system returns 
No menu selected
Record not found

And what about Seo on this page? I mean I can set description for articles and pages but not for the front page whitout page content

**Comment by newkind** [comment]
Sorry, but I have no idea what you're talking about ? Assigning an outline to be used as the front page ?

**Comment by mahagr** [comment]
On `No menu selected`, you need to create a menu in WP or disable menu particle in Settings tab.
Not sure about `Record not found`, never seen it before.

On SEO, you can change the layout of the front page to include page content (WP output), though there should be a way to set description, keywords etc for the page, too.

**Comment by prankyboy** [comment]
Thank you guys! Everything's works!
