### ISSUE TITLE
Trying to call just a certain post for a particle

### ISSUE THREAD

**Issue by chaladm** [gantry/gantry5#1173]
Hi all,
So yesterday newkind helped me out by setting the post type for the particle. But I didn't realise that I should just be calling 1 post at a time and using the layout manager already in gantry.

I tried to put some sort of array but its not working. Would appreciate if someone knew what i was doing wrong.

attempt 1: 
{% set posts = wordpress.call('Timber::get_posts', {post_type: 'detachedhome', ID: '1'}) %}
<h1>{{ post.title }}</h1>

**Comment by chaladm** [comment]
did it a non-elegant way like this:

{% block particle %}

  {% set id = particle.id %}
  {% set post_type = particle.post_type %}
  
  {% set posts = wordpress.call('Timber::get_posts', {post_type: post_type }) %}
  {% for post in posts %}
   {% if (post.id) == id %}
    <div class="title"> {{ post.id }}</div>
    <div class="title"> {{ post.title }}</div>
   {% endif %} 
  {% endfor %}
  
{% endblock %}


I got particles to call the id and type. Would love to see if anyone got a more elegant way of doing this.

**Comment by newkind** [comment]
Should be : ` {% set posts = wordpress.call('Timber::get_posts', {post_type: 'detachedhome', p: '1'}) %}`

Timber get_posts accepts the same parameters as wp_query

https://github.com/jarednova/timber/wiki/Timber-docs#get_posts

**Comment by chaladm** [comment]
thanks newkind. How do we do it for a page?

I have used ACF for pages too. Not sure how to echo the fields from that.

**Comment by newkind** [comment]
Timber get_posts will accept all arguments from [WP_Query](http://codex.wordpress.org/Class_Reference/WP_Query) so just use them to get what you need.

**Comment by chaladm** [comment]
I used this : 
{% set posts = wordpress.call('Timber::get_posts', {page_id: '21'}) %}

worked fine. Thanks again newkind

**Comment by chaladm** [comment]
Just one last question if you are able to help me out. How do I set it for current page?

**Comment by chaladm** [comment]
Will start a new question about this
