### ISSUE TITLE
Set header height now menu doesn't work right (Hydrogen)

### ISSUE THREAD

**Issue by elleonblanco** [gantry/gantry5#1175]
Hello all:
Been away from web work for a couple years but am loving Gantry5 and Hydrogen. Nice work! I am having a small issue however after I set up an override and adjust the header height in the default template. If I set it anything below 90 PX then the menu becomes unusable. As in you can not select any of the menu entries. It acts as if the menu moves up but the hot spots do not. I would like to actually shrink the header down to about 60PX but don't know what to look for to compensate for teh menu shift.
I am sure it isn't that difficult I just don't know where to look. Hope one of you can help shed some light on this.

**Comment by w00fz** [comment]
Any way you can attach a screenshot or a URL to look at it?

**Comment by elleonblanco** [comment]
Sure... http://net4ia.com/index.php
I have it set at 90 now.. I'll lower it to 80

**Comment by elleonblanco** [comment]
set to 80 PX and css recompiled

**Comment by w00fz** [comment]
What you probably want to do is to set the Header section to Flushed. By default non flushed sections include a margin / padding dictated by the theme. Those margin / padding prevent you to lower than a certain amount, by flushing the section you remove it although you will still always reach a limit driven by the height of your content.

Another solution is to simply customize your CSS to deal with this particular case, for example in your `custom.scss`:

```sass
#g-header {
    max-height: 50px;
    .g-content {
        padding: 0;
        margin: 0;
    }
}
```

More details about `custom.scss`: http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

**Comment by elleonblanco** [comment]
I set it to flushed and solved the menu problem. I'll have to figure out how to position the logo and text now. Perhaps I should just adjust it in the custom.scss override. 

Thanks for the help. Glad you all are here and don't mind helping folks out.

**Comment by w00fz** [comment]
Not a problem, happy to help :+1:
