### ISSUE TITLE
Menu title

### ISSUE THREAD

**Issue by amorz** [gantry/gantry5#1176]
Hi,

I found a little bug, 

When you add a title attribute (menu-anchor_title) to a Joomla menu item. It also  add's a subtitle to the gantry menu. 

Kind regards,

Stephan

**Comment by w00fz** [comment]
Good catch, fixed now.

Thank you!

**Comment by mahagr** [comment]
There's still issue when saving, I'll fix it in a bit.

**Comment by mahagr** [comment]
BTW, this change may break our RLs if we ever used subtitles anywhere. It also breaks user sites if they did the same.

So the change isn't backwards compatible.

**Comment by mahagr** [comment]
Yes, it was broken in the first place, not sure why I used title, maybe I misunderstood its meaning.

I think we should just fix RL for the Ambrosia and inform users about the incompatible change..?

**Comment by w00fz** [comment]
Agreed, it's not such a bad breaking change though, worst can happen is you just don't get subtitles which can be easily get fixed passing through the G5 Menu.
I am also not entirely sure people uses that for the subtitles anyway, i think it's the norm for people to use Menu Editor.

**Comment by amorz** [comment]
Thank you for fixing this issue.
