### ISSUE TITLE
How to debug twig?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1178]
I am trying to make some custom particle, during witch I need to see the value of some variables to better understand what is what. I searched the twig website, it says to use "dump()" I need to enable debug somewhere when the twig environment is created. Where is it? Or does gantry provide some wa to debug twig?

**Comment by w00fz** [comment]
If you are in Joomla, enable debug mode of Joomla. If you are in Wordpress, go in the Gantry plugin settings and enable debug there.

`dump()` is the proper way to debug twig

**Comment by newkind** [comment]
Also in WP to make `dump()` work you need to set `WP_Debug` to `true` in `wp-config.php`

**Comment by newjie** [comment]
Thanks. I am using Joomla and it works. Is there any other method available? How can I invoke other PHP function from inside of a twig template? Some says an extension of twig is needed, but how do I install that extension?

**Comment by w00fz** [comment]
Check this documentation out: http://docs.gantry.org/gantry5/advanced/php-functions
Think it's what you are looking for.

**Comment by w00fz** [comment]
Closing the issue. Hope you got the answers you were looking for. Feel free to reopen otherwise.

Thanks.
