### ISSUE TITLE
Offcanvas Module Position

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#1179]
I added module position in offcanvas where mobile menu is located. It was working fine with desktop version.

But after updating (Joomla + Hydrogen) latest version, module position offcanvas sidebar is not showing on desktop. It is showing only in mobile.

**Comment by mahagr** [comment]
Yeah, we did add a new option for this which defaults to false. 

Go to `Styles` and look for `Offcanvas` settings. Last setting (`Toggle Visibility: Always`) will fix your issue.

**Comment by rgblogs** [comment]
Thanks, problem solved. :)

I saw this update in change log but couldn't find more information on this.
