### ISSUE TITLE
Using get_post function for particles and want to return fields from the current page

### ISSUE THREAD

**Issue by chaladm** [gantry/gantry5#1180]
I have made custom fields for a page and want to put each field as a particle to fill in my page.
I'm having trouble making the particle only echo content for that certain page.

With this function, it echos all the content from all the pages:
{% set posts = wordpress.call('Timber::get_posts', {post_type: 'page'}) %}

**Comment by newkind** [comment]
Just put the post/page id in the array after `post_type` to narrow down the query.

**Comment by chaladm** [comment]
I am going to use the same layout for 3 different pages and I wanted this twig particle to echo the custom field of only the page I open.

If i cannot do this way, I will have to make layouts for each page.

**Comment by chaladm** [comment]
I've tried a different way and it doesnt' work either.
What I did was use the custom html particle and put the twig line {{ post.title_room }} and clicked the process twig

this didn't work however . Hope someone can shed some light into this issue

**Comment by chaladm** [comment]
Found the answer:
{% set posts = wordpress.call('Timber::get_posts') %}

I read in the documentation that if you do not put any query then it will render the current page. 

Thanks again all.
