### ISSUE TITLE
Shortcode for twig in particles

### ISSUE THREAD

**Issue by chaladm** [gantry/gantry5#1181]
Hi,
I'm having an issue with shortcodes in particles. I am getting the text from a custom field in a page.
The echo is coming out with the code rather than processing the html.

I use this code:
{{ post.gallery|shortcodes }}

**Comment by chaladm** [comment]
no worries got it work

Used the code:
{{ post.gallery|shortcodes|raw }}

**Comment by mahagr** [comment]
Yeah, by default twig escapes all input and you need to tell it not to do that.

Great for fighting against XSS vulnerabilities as most of the time you just forget to escape..
