### ISSUE TITLE
Issue with changing Style Preset when Jetpack is activated

### ISSUE THREAD

**Issue by ChrystalSolutions** [gantry/gantry5#1184]
I'm running Gantry5, Hydrogen theme, Wordpress.

When Jetpack is enabled, and I select on a Style Preset, nothing happens.  The graphic for the preset gets highlights, but the star doesn't move to the preset, the colors don't change below, and the save button doesn't change.  Basically nothing happens.

Disabling Jetpack resolves the issue and it works normally.

**Comment by w00fz** [comment]
Thanks for opening the issue.
On RT forums I also spotted that Jetpack causes some issues on G5 front-end, we need to investigate what's conflicting with Gantry.

/cc @newkind, @mahagr

**Comment by w00fz** [comment]
I fixed this now, it wasn't specifically incompatible with Jetpack only but potentially other plugins as well.
