### ISSUE TITLE
Clicking multiple times on save button results in multiple records

### ISSUE THREAD

**Issue by RogerSteve** [gantry/gantry5#1185]
When i saved the settings, the saving action got stuck on the background loop making server load, at that time i didn't see the problem.
So i started to debug and here i found:
![Saving loop](http://oi67.tinypic.com/2d10cjr.jpg)
You can press multiple times both blue buttons.
![Saving popup](http://oi63.tinypic.com/2zf97jk.jpg)
"Save layout' button don't make any loading circle but the loop exist:
![Saving popup](http://oi66.tinypic.com/219s1z5.jpg)

I saw you have a check to show you where changes was made, can you make a check to not save when is nothing to save and limit save buttons to one instance or something?

**Comment by w00fz** [comment]
We can look at disabling the save until a request is done, in fact, that should be already working like that, not sure what happened. In the meantime, you coule stop clicking so many times so close to each other since you know the issue, just wait for it to finish?
I'm sure your hosting provider would appreciate it ;)

**Comment by RogerSteve** [comment]
The problem is happens on background, that was one method to replicate, check timeline on console and you will see the loop.
If it was by me sure, but it happens on background, thank you for your concern anyway :)

**Comment by w00fz** [comment]
Then this sounds like a different issue, not client side related. Perhaps has to do with the server setup, that's preventing the save to happen.
@mahagr any idea?

**Comment by w00fz** [comment]
I believe some comments have been deleted in here, it looks like i'm babbling to myself above :smile_cat: 

Anyway I'm going to close this as we don't think it's Gantry related, feel free to reopen if you have more informations to provide.

Thanks.

**Comment by RogerSteve** [comment]
Not sure what you talking about, maybe git bots block something, happen before to me.
And the issue was to block multiple save action, you can save multiple times without finish the current action, like i request in main post. :)

**Comment by w00fz** [comment]
I'm talking about the 2 messages that were deleted in between my two ones above, they were the same message from you from 2 accounts :smiley: 

Anyway I'm reopening the issue to look further but I still think this is a server issue on your end.
