### ISSUE TITLE
Cannot render select.selectize value in scss

### ISSUE THREAD

**Issue by Flowman** [gantry/gantry5#1186]
Trying to create a dropdown selection for background repeat with different options.

Selection code in the styles file
    background-repeat:
      type: select.selectize
      label: Background Repeat
      default: no-repeat
      options:
        no-repeat: no-repeat
        repeat: repeat
        repeat-x: repeat-x
        repeat-y: repeat-y

Scss file:
    @if variable-exists(section-background-repeat) {
        background-repeat: $section-background-repeat;
    }

Result 
background-repeat: 'no-repeat';

The issue is it adds quotes around the value and it throws an error in the web browser.

**Comment by w00fz** [comment]
You can use sass function `unquote()` around the variable.

**Comment by Flowman** [comment]
@w00fz unquote() worked like a charm.

Cheers
