### ISSUE TITLE
Menu Issue on Hydrogen theme - Gantry

### ISSUE THREAD

**Issue by gamolo** [gantry/gantry5#1187]
I hope someone can fix this. It seems the menu's layer module is behind showcase module, so that the menu items are not shown. 
![Uploading Captura de pantalla 2016-03-10 a las 10.52.13 p.m..png…]()

![captura de pantalla 2016-03-10 a las 10 52 19 p m](https://cloud.githubusercontent.com/assets/17776963/13693660/f26b89a0-e712-11e5-9d4d-f5d1d43a229f.png)

**Comment by Bokelmann** [comment]
hmmm I can't really see an issue on that screenshot?
Do you have a link to the issue? The url in screenshot didn't seem to work for me?

**Comment by hexplor** [comment]
Yeah.. I visited your website and didn't see an issue either..

**Comment by N8Solutions** [comment]
I took a look at the site as well, http://gerardoangeles.com, and the only thing I saw was that the dropdown menu's would disappear briefly if you were hovering over them when the slides changed in RokGallery.  However, keeping the mouse hovered over the menu item during the change the dropdown menu's reappeared immediately.

**Comment by Bokelmann** [comment]
adding

```
.rokgallery-wrapper {
 	z-index: 0;
 	position: relative;
 }
```

will solve that I guess

**Comment by gamolo** [comment]
I've tried with different modules. The roksproket module had troubles.

**Comment by Bokelmann** [comment]
so try

```
 section#g-showcase {
 	z-index: 0;
 	position: relative;
 }
```
 
the module on the frontage is a RokGallery-module.
Try to add whaI suggested an see if it helps.

**Comment by gamolo** [comment]
Ok. Thanks.

**Comment by gamolo** [comment]
I've added the line at "/scss/hydrogen/_showcase.scss" in template "g5_hydrogen", Nothing changed at all
![captura de pantalla 2016-03-11 a las 11 29 29 a m](https://cloud.githubusercontent.com/assets/17776963/13710041/b13cc330-e77c-11e5-8755-6aea92b9bc33.png)

**Comment by Bokelmann** [comment]
add it to a custom scss file like it's explained here:
http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
an recompile the css from the settings in Gantry

**Comment by gamolo** [comment]
Thanks a lot, it works... I was missing the "recompile" step.

**Comment by mahagr** [comment]
I'm assuming that the issue has been fully fixed, @gamolo just say if it isn't.

**Comment by gamolo** [comment]
Fully fixed
