### ISSUE TITLE
Gantry5 and WPML

### ISSUE THREAD

**Issue by chaladm** [gantry/gantry5#1190]
Hi,

I was wondering if anyone has experience with Gantry and WPML?

I'm trying to create a twig query so it will echo the post of the language whenever I switch languages.
Is there a way to do this?

Thanks.

**Comment by chaladm** [comment]
I've tried to use this function 

{% if ICL_LANGUAGE_CODE == 'en' %}
English
{% elseif ICL_LANGUAGE_CODE == 'th' %}
Thailand
{% endif %}

It's not picking it up ICL_LANGUAGE_CODE

Any ideas anyone?

**Comment by mahagr** [comment]
Twig has function for constants:

    {% if constant('ICL_LANGUAGE_CODE') == 'en' %}

**Comment by chaladm** [comment]
thank you works perfect!
