### ISSUE TITLE
Timber (echo post type categories)

### ISSUE THREAD

**Issue by chaladm** [gantry/gantry5#1191]
Hi,
I'm looking how to echo all the categories for a post type.
Is there a way to do this?

Thanks.

**Comment by mahagr** [comment]
WP related functions are all handled by Timber. They have very good documentation in https://github.com/timber/timber/wiki which can be referred if you need to fetch any data from Timber.

Github issues are meant to report bugs on the software, its not meant to be a support channel. If you want to talk with us, please join our chat in https://gitter.im/gantry/gantry5
