### ISSUE TITLE
Slideshow particle

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1192]
After new template creation when I save after every change of style I've this:

500 Internal Server Error
Oops, Undefined mixin breakpoint: failed at `} ` /web/htdocs/www.mydomain.biz/home/templates/g5_hydrogen/custom/scss/_slideshow.scss on line 18.

**Comment by JoomFX** [comment]
Mate, we spoke about it, didn't we? https://github.com/gantry/gantry5/issues/1177

Just make sure you have `@import "dependencies";` at the very top of your "custom.scss" file.

Also, the Slideshow particle is not a core Gantry 5 particle and therefore this is not the write place to ask for assistance. Just write a comment on the Blog Post where you downloaded the particle from.

**Comment by prankyboy** [comment]
Oi, glad to read u. Everything's ok with u?
uhm, right this is not the right place. Anyway yes I've @import at the top oc custom.scss.
I continue on the blog.

**Comment by mahagr** [comment]
No problems on my side. I am just cleaning up old issues and fixing some bugs, so closed this as being not part of Gantry.
