### ISSUE TITLE
Cannot upgrade from 5.2.3 to 5.2.13

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1196]
Hi,

I have gantry 5.2.3 installed and I want to upgrade it. This is the error I get:

```
Error

Unable to write entry
Warning

Update path does not exist.

Package Update: There was an error installing an extension: com_gantry5_v5.2.13.zip
Message

Error updating package.
```

What should I do?

Thank you.

**Comment by mariantanase** [comment]
Try to upload the content of the package (_joomla-pkg_gantry5_v5.2.13.zip_) to **TMP** folder and then use the **Install from Folder** option.

**Comment by nicutor** [comment]
This worked. Thank you!
