### ISSUE TITLE
Grav + Gantry + Hydrogen error

### ISSUE THREAD

**Issue by hamishmacdonald** [gantry/gantry5#1198]
I've added the Gantry plug-in and Hydrogen theme to my Grav install, and both appear in their respective places, but when I choose "Configure" from the Gantry page, I'm taken to the "Crikey!" error page.

This message appears in the top-left purple sidebar:
```
Whoops\Exception\ErrorException thrown with message "Call to undefined method RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator::resetScheme()"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home/comixwor/public_html/user/plugins/gantry5/gantry5.php:159
```

And line 159 in the code is highlighted:
```
Whoops\Exception\ErrorException thrown with message "Call to undefined method RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator::resetScheme()"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home/comixwor/public_html/user/plugins/gantry5/gantry5.php:159
```

Attached are the contents of the "Environments & Details" log.
[Environment_details.txt](https://github.com/gantry/gantry5/files/178368/Environment_details.txt)

**Comment by mahagr** [comment]
Right now Gantry needs Grav 1.1 (CI build) as well as development build from admin and form plugins to work properly.

**Comment by hamishmacdonald** [comment]
Ah. Thank you!
