### ISSUE TITLE
Adding ID & Class field to Sample Content Particle Items.

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#1199]
I would like to give one more suggestion for a change in the standard particle Sample Content it is a great particle and especially the part where you can add multiple sample items. I am only missing an ID & Class field in those multiple sample items. The reason I am asking because I am really missing this function and yes I can create a particle that has it but I would rather have it build into Hydrogen as it can then benefit everyone.

![google-chrome](https://cloud.githubusercontent.com/assets/4426337/13856998/28cd7cb4-ec78-11e5-9daa-6dc6124e9cd1.png)

**Comment by hexplor** [comment]
Hello hennysmafter,
I think it's mostly possible right now. In variations field just put your own class name and it should work (correct me if I'm wrong)
Regarding ID, you can easy implement it automatically. Open particles/sample.html.twig and find this line:

```
{% for sample in particle.samples %}
				<div class="g-block {{ sample.class }}">
```

then make it:

```
{% for sample in particle.samples %}
				<div id="{{ id }}-item-{{ loop.index }}" class="g-block {{ sample.class }}">
```

This will give you following id: **module-sample-XXX-item-X** 
You can assign that to various js scripts.

**Comment by mahagr** [comment]
Good idea for handling Id, though it looks like while sample.class is defined in twig, its missing from YAML.

**Comment by hexplor** [comment]
Oh.. i thought it's a "Variation" field in the particles.. hmm

**Comment by mahagr** [comment]
Actually variations are our predefined classes, you cannot enter your own, it seems.

**Comment by hexplor** [comment]
Yeah, you are right. I was sure i actually did that :) My bad

**Comment by w00fz** [comment]
Has this been implemented yet?

**Comment by w00fz** [comment]
Nevermind, I implemented it myself.
