### ISSUE TITLE
Styles Preset Alignment Issue

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#12]
There is a alignment issue with Presets image and title in Styles, see screenshot.
![2015-03-28 23 42 56al](https://cloud.githubusercontent.com/assets/10489911/6883234/6d05786e-d5a4-11e4-86ad-261668926244.jpg)

**Comment by w00fz** [comment]
What browser and os is that?

**Comment by DamirPecnik** [comment]
Window 8.1 and Chrome Latest Version!

**Comment by DamirPecnik** [comment]
Confirmed fix in Latest Build!
