### ISSUE TITLE
WordPress - Gantry Save causes 404 popup

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1203]
Hey @newkind for some reason when i try and save anything on any outline i get a popup with a 404 page on it, no idea why. Have you come across this before?

I have Jetpack which i deactivated but the issue still happens. It was working and then all of a sudden it stopped randomly. I haven't installed any new plugins since it did work, all i have done is change css.

I have deleted and re-installed Gantry too but the issue still happens. Happy to share logins with you via PM if you like.

**Comment by mahagr** [comment]
What is the error you are getting?

**Comment by igor-gp** [comment]
Hey @mahagr i don't see any traditional error message, it literally just pops up with a 404 error page inside a popup.

The issue has since resolved itself somehow but i have just been able to replicate it. It happens when i duplicate an outline, then go into the new outline or any for that matter and try and save something in the layout or styles etc, it then that i get this error/glitch. 

The on-flow effect seems to also affect the wp-admin login page. When i log out and try to log back in it takes me to a 404 page. 

The interesting thing is, when i then reload the wp-admin page and login, it all goes back to normal, i.e. save in gantry works. 

So it seems to happen only once after duplicating an outline that save is erroring out, but once i log out and try again (which fails), then try again, it then works fine. 

Interesting to see if it happens on your end too or just mine. 

Thanks

**Comment by mahagr** [comment]
Might be somehow related to #1137

**Comment by igor-gp** [comment]
Yeah very well could be, sounds the same! Sorry i didn't see there was an existing issue for it, i did check first hehe.
