### ISSUE TITLE
The joomla-pkg_gantry5_v5.2.13 Update cache issue

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1204]
Some users are having the same issue as myself with this update. Once you've updated via the Extensions Manager screen the purple Update message still appears when you open an Outline. Previous updates never did this.
My purple message removal process is to Login -> clear the cache -> immediately Logout and then on the next Login the message is removed.

**Comment by mahagr** [comment]
The code hasn't been changed since August 2015 (when we attempted to fix #631), so the issue has been there forever.

I guess that Joomla doesn't clean up #__updates table and while the fix was added for templates (or Hydrogen), it wasn't applied to Gantry itself.

**Comment by DanGthatRokGallery** [comment]
Hi Matias, 
I have now all installs of Callisto to Photon on my local server and have various versions of Gantry 5 up to 5.2.12 and have never seen this issue.
Something new has cropped with 5.2.13 in that my "fix" of clicking the "X" to close the message and then clearing the cache and then logging out and logging back in ONLY works for that specific Outline.
If I login and choose a different Outline than the one I applied the "fix" to I see the Update message again in this Outline. It's VERY bothersome. Also when you click the Update button and are redirected to the Extensions Manager, J348 requires a Clear Cache and then Find Updates just to see the Gantry 5.2.13.

I have to update this issue as I've reinstalled 5.2.12 into Photon and then did the update and NONE of this issues occurs with J35.

Also users in the forums are starting to mention this as the believe there is something wrong with the update.

**Comment by mahagr** [comment]
Update message may also have something to do with Joomla update because of this is really a bug in Joomla which we tried to create workaround for. I will look into fixing it, though.

Am I right that Hydrogen update will not show up? That part should be working properly, its just Gantry update.. Right?

**Comment by DanGthatRokGallery** [comment]
Hydrogen - even stranger than my Salient.
To confirm mahagr I uninstalled G5.2.13 and installed G5.2.13.
![g5_hydrogen-extensions_manage---gantry](https://cloud.githubusercontent.com/assets/3792467/14113186/d847e9ec-f59f-11e5-8714-5bb6135e978d.jpg)

Cleared my caches
Logged out and logged back in again and now see this
![g5_hydrogen_home-layout_manager](https://cloud.githubusercontent.com/assets/3792467/14113175/ca2ee748-f59f-11e5-946f-bf17ee1891a7.jpg)

Getting back to my Salient, every time I access an Outline I get the purple update notice even though I've installed and re-installed G5.2.13 about 6 times.
I checked my DB and tables "plg_system_gantry5", "plg_quickicon_gantry5", "plg_gantry5_preset", "mod_gantry5_particle",  "gantry5_nucleus", "com_gantry5" and Gantry 5 Framework are all showing G5.2.13 so I don't know where else to look.

Of all the G5 templates so far these have this issue on my MAMP for WINDOWS - all J3.5.0 - templates updated to versions online as of today.
Infinite PURPLE notice:
Callisto, Isotope, Xenon, Galatea, Photon - Ethereal: J3.5.0

Normal Gantry update:
Ambrosia, Requiem, Kraken, Antares - Ethereal: J3.4.8

**Comment by mahagr** [comment]
I found a minor bug in our end for Gantry itself, but otherwise the code looks good to me.

BTW, you didn't downgrade hydrogen, so its version is higher.

**Comment by mahagr** [comment]
I'm not able to reproduce this issue with or without Joomla caching.

* Installed 5.1.12
* went to cpanel to see that there are updates
* checked that the purple bar was showing in gantry
* updated
* gantry was not showing updates anymore
* repeated 3 times

**Comment by mahagr** [comment]
This may be some kind of Joomla caching issue as it caches extension entries in order to avoid database lookup. In that case there's not much I can do to fix the issue as the data returned by Joomla is out of date.

**Comment by DanGthatRokGallery** [comment]
Closed. For some reason all those templates with the issue didn't have the Gantry 5-Package file installed. Once I re-installed 5.2.13 the issue disappeared.
