### ISSUE TITLE
Custom assets (CSS & js) issue

### ISSUE THREAD

**Issue by jasonday** [gantry/gantry5#1205]
Adding files to either CSS or js in "Custom CSS/JS" under Settings has no effect. Files are not loaded.

I have tried the full path, in addition the selected path "gantry-assets://", with no effect. 

Gantry 5.2.13
Hyrdrogen 5.2.10

**Comment by newkind** [comment]
Under "Settings" or "Page Settings" ?

**Comment by jasonday** [comment]
Settings

**Comment by newkind** [comment]
Settings tab is used to set "defaults" for particles and atoms, but these defaults aren't used until you actually use the particle or atom. You still need to drag them either in Page Settings (Atoms) or in Layout Manager (particles). Does it make sense ?

If you want to add the JS/CSS without particles you need to use "Page Settings" not "Settings" tab.

**Comment by jasonday** [comment]
Thanks, and I figured that out, however from a usability perspective this interaction feels like a friction point. It's not very intuitive.

**Comment by mahagr** [comment]
Yeah, unintuitive at best. We were supposed to remove atoms from the settings page altogether (after they were moved to page settings), but we somehow forgot to do that.
