### ISSUE TITLE
issue with color of "strong"

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1206]
Hi,
How can I override the following line from **_core.scss** ?
```
h1, h2, h3, h4, h5, h6, strong {
	color: darken($base-text-color, 10%);
}
```
I need to use **strong** tag on white text. On every part of the site when I use **strong** attribute I expect to have the bold font not darken, regardless of the font color.
On my scenario to fix this thing, I have to remember to comment that line after every Gantry update.
Can be another way to override this ?

![screenshot-localhost 2016-03-21 09-18-31](https://cloud.githubusercontent.com/assets/3976174/13913398/7df257b6-ef46-11e5-82a9-399b02c204fc.png)

**Comment by newkind** [comment]
You need to make your CSS higher priority ie. by adding extra parent tag :
```
body strong {font-weight: bold;}
```
or 
```
#g-page-surround strong {font-weight: bold;}
```

This should help ;)

**Comment by mariantanase** [comment]
No, it didn't work. The color remain the same, e.g darken from $base-text-color.
I don't want this!
If I comment the line like this:
```
h1, h2, h3, h4, h5, h6, strong {
	/* color: darken($base-text-color, 10%); */
}
```
This is the desired result like in the screenshot attached.

![screenshot-ok](https://cloud.githubusercontent.com/assets/3976174/13915175/4ed52776-ef53-11e5-923d-72e451c7b3dd.png)

**Comment by newkind** [comment]
Any url to your site ?

**Comment by mariantanase** [comment]
unfortunately is on localhost

**Comment by newkind** [comment]
Have you tried using `color: inherit;` ?

**Comment by mariantanase** [comment]
Perfect !
I've added 
`strong {color: inherit;}`
on my **custom.scss**
This is the fix. Thank you !

**Comment by newkind** [comment]
Great!
