### ISSUE TITLE
Expand port filter to include 443 for SSL connections

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1208]
@newkind as discussed:

Please amend
`if ($_SERVER["SERVER_PORT"] != "80") {`

To this
`if ($_SERVER["SERVER_PORT"] != "80" && $_SERVER["SERVER_PORT"] != "443") {`

Thanks.

**Comment by newkind** [comment]
Actually that was just a workaround, so I need to do some testing with SSL and then make a proper solution ;)

**Comment by mahagr** [comment]
Where do we have this code?

**Comment by igor-gp** [comment]
@mahagr from what i see it's this path

`/wp-content/plugins/gantry5/src/classes/Gantry/WordPress/Assignments/AssignmentsMenu.php`

**Comment by mahagr** [comment]
Oh, I can see it now. I agree that the code in there is a bit hacky, cleaner solution would be better. Doesn't WP have a function which you can use for this?

**Comment by igor-gp** [comment]
You mean something like this? https://developer.wordpress.org/reference/functions/is_ssl/

**Comment by mahagr** [comment]
Looks much better. @newkind ?

**Comment by newkind** [comment]
Not really - the issue isn't with detection of SSL but with url comparison. I need to test it.

**Comment by w00fz** [comment]
Can we please address this? Looks very ugly as it is 😸

**Comment by newkind** [comment]
Replaced old function with the new one with two additional WP filters that allow you to set custom ports (regular and ssl).

@igor-gp @adi8i would be awesome if you could test it guys!

**Comment by igor-gp** [comment]
Hey @newkind i have tested the CI and all the SSL pages which were not working before do work now, so that's good. You seem to be indicating that we can set ports somewhere, if so, where is that?

**Comment by newkind** [comment]
Awesome!

There are two filters that you can add to your theme : `gantry5_current_url_server_port` and `gantry5_current_url_server_ssl_port`

For example in your functions.php you could do :
```
add_filter('gantry5_current_url_server_port', function() {
    // If 8080 is your custom port
    return '8080';
});
```

**Comment by igor-gp** [comment]
Ok cool will that be added to the Gantry docs please? 

Also no way to somehow Gantrify that hehe, and add some sort of option in the platform settings page?

**Comment by newkind** [comment]
@FrugalGeek - docs request for you here

To be honest I think that this is too advanced to be modified somewhere from the WP admin. I think it should stay the way it is, especially that it's gonna be used very sporadically - thoughts @mahagr ?

**Comment by w00fz** [comment]
I fully agree with @newkind. I think we should document this but it's not something that many would benefit from if it had an UI in admin, in fact, I fear most people would actually just get confused by the settings.

**Comment by mahagr** [comment]
I also agree with above comments.
