### ISSUE TITLE
Logo particle link going to "current" page rather than home page on J3.5

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1210]
Further to the request by @mahagr I have raised this new issue regarding the url on th elogo particle going to the "current" page rather than the site home page - the issue seems to be related to J3.5.

I have today had another example of this issue in the RT forums. I had to add "/" in the url for the logo particle (in base outline) to fix this. So I think this ticket should be reopended as the issue does seem to exist still. This is the forum topic (admin details therein):

http://www.rockettheme.com/forum/gantry5-for-joomla/256727-link-homepage-on-logo?start=0#1281701

Member is using G5.2.13 and Joomla 3.5.0

**Comment by mahagr** [comment]
It seems to be a bug happening only in Jooma! 3.5, I was able to verify it myself.
