### ISSUE TITLE
Custom section attributes not copied on layout switch

### ISSUE THREAD

**Issue by ghost** [gantry/gantry5#1213]
If you add custom settings to section( by creating file YOUR_THEME\custom\admin\blueprints\layout\section.yaml), after layout switch and save, values of custom attributes are lost.

**Comment by mahagr** [comment]
There is a reason why section attributes aren't copied over -- some layout presets have their custom attributes for some custom CSS (or looks). By copying attributes, those custom features would stop working.

**Comment by mmckp** [comment]
I don't exactly understand, you say that in layout preset yaml you can define section attributes? I didn't find such possibility in documentation. Maybe code that loads new layout should copy only custom section attributes defined in YOUR_THEME\custom\admin\blueprints\layout\section.yaml ?

**Comment by mahagr** [comment]
Well, layout preset file is identical to any layout file; it can have all the properties + even some more, which cannot be changed from admin.

Its possibility to copy only section attributes when they haven't been set in preset, but that brings another problem as you cannot beforehand know what gets copied and what is already defined in preset. Its more logical either to skip or copy all the attributes...

**Comment by mmckp** [comment]
Hmm I don't know gantry that well, so I can't say if I agree or not with what you are saying, but I have been using Gantry for a while, and such behavior seems like an obvious bug.

**Comment by mmckp** [comment]
Consider scenario, where I add new section "map" in my "Contact" layout. I go to admin panel > Layout, and it displays my old "contact" sections. I want to load my new layout structure, so i click Load>Contact. It reloads my layout, and new "map" section is visible, but all my custom attributes from sections are lost.

**Comment by mmckp** [comment]
Maybe if user selects the same layout from Load dropdown, it should ask whether to reset or copy section attributes value? But it may seem confusing for user, if he doesn't know framework and terminology very well...

**Comment by mahagr** [comment]
I tend to agree, but I also need to keep backwards compatibility with our own themes.

Simplest solution would be to copy attributes only if they had been specified in the current outline. If not, default ones from the new preset/outline would be used. That would allow presets to have their own attributes while still using the ones which user specified.

The issue that comes into my mind is: what if you circle through all the presets before deciding which one to use..?

**Comment by w00fz** [comment]
I believe none of this will matter anymore once 5.3 is released. With the Inheritance in place you can now decide to inherit only the attributes of the section from another outline which means Loading won't override them anymore.

**Comment by mahagr** [comment]
I agree that having inheritance will mostly fix this issue as there will be no reason to copy section settings anymore - those can be inherited. We will probably also have to look into how preset/outline loading works; it may be the best to inherit everything by default and then let user to choose which parts to override.

**Comment by w00fz** [comment]
I was thinking that the current behavior we have for Load is very valuable. What we need is an extra option in the Load popover to allow flagging the loading as a full inheritance action or not. The same way we have the option to preserve or discard the current particles.

**Comment by w00fz** [comment]
This is now implemented with our Inheritance effort.
