### ISSUE TITLE
Mobile Menu Swipe Feature Problem

### ISSUE THREAD

**Issue by WebTread** [gantry/gantry5#1216]
Here is how I came about this issue...

Working with Isotope template, didn't want overlay because of issues on some tablet, loved mobile menu and decided to use it in all views by setting the breakpoint very high. But mobile menu wouldn't sit inside the body and instead hugged the outside. So I hid it using the display: none; CSS and then borrowed the code data-offcanvas-toggle in my own div. Added the cursor: pointer; CSS and man this looks perfect and works as expected.

Until I get on my iPad and start scrolling down the page and it accidentally opens the freaking mobile menu on the right anytime my fingers slightly bend to the right as I flick down the page instead of just when I click on the menu button.

Now I added the sticky Nav / Header particle Headroom.js Particle found here http://www.inspiretheme.com/blog/freebies/42-fixed-sticky-header-atoms-for-gantry-5-freebies which is awesome. But I've tested everything and it has nothing to do with the menu or the sticky nav / header or anything else.

It is simply that there is a swipe feature turned on and no way I know of to turn it off for those of us who love the idea of using the mobile menu at all times for a clean looking menu but don't want people on mobile devices accidentally opening that menu at every flick of the finger that goes a little sideways. It's kind of the same thing with the new iOS where my right side panel is often opening and loading the news app when I don't want it to.

So please can we allow for turning this feature off somewhere? No reason to loose the feature as it may be great on just a phone but it is not great on the iPad and should be something we can access to turn off in a place that would make sense. Maybe in the BreakPoint section have a tick box that has Swipe for Tablet and another for Swipe for Phone and allow them to be turned on off individually. Or wherever else it makes sense to have some control over this feature.

Again not bagging on the feature, just saying try moving around this site http://webtread.com/sites/new-mpc/ using an iPad or other tablet and be on any page and accidentally swipe a bit to the right as you're scrolling down and it pops out the mobile menu. I've got a sticky nav bar so they can click on menu if they want it to pop out. I don't want that to happen as the scroll down on accident. And it happens to me a lot as I test.

Thanks,

Grant

**Comment by marktaylor46** [comment]
Perhaps i've misunderstood your long comment but you can disable the swipe event for the offcanvas section on the offcanvas section settings. is that what you mean?

![2016-03-29_16-30-15](https://cloud.githubusercontent.com/assets/11683218/14113632/b73a1f5a-f5cb-11e5-9a80-fb6e57a69af5.png)

**Comment by WebTread** [comment]
lol... Thank you Mark for the short, concise and problem solving answer. It was late in my day. Not sure how I missed that feature but it definitely solves what I thought was an issue. Thanks again and we can close this erroneous issue.

**Comment by mahagr** [comment]
Thanks @marktaylor46
