### ISSUE TITLE
*transparent* as an option in the colorpicker coding issue

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1217]
This references https://github.com/gantry/gantry5/issues/334

In Antares and Photon when I click the TRANSPARENT button in the color picker this is the color code generated:
rgba(255, 255, 255, -0.00)

On trying to SAVE I get this error message:
INVALID FIELDS
Please review the fields in the page and ensure you correct any invalid one.

If I manually change the code to 
rgba(255, 255, 255, 0.0)

it SAVES.

**Comment by mahagr** [comment]
@w00fz can you check this one when you get back to home? Adding something like `max(val, 0)` might help?

**Comment by w00fz** [comment]
I couldn't really replicate the issue at all but I applied Matias' suggestion which i think should do just fine.
