### ISSUE TITLE
Can't add a row or alter sections settings on a tablet

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1218]
A member reported this in the RT forum and I have confirmed the issue on my own Ipad Pro.

It appears to apply in any theme so that's why I believe it is a Gantry 5 issue.

On the layout of an outline your cannot click on either the "+" or setting cog on mainfeature or sidefeature sections (i.e. sections that appear side by side) You can click on the those icons for other sections that span the full width of the template (e..g. navigation).

What happens is the icons does change color but does not do anything.

![img_0013](https://cloud.githubusercontent.com/assets/11683218/14148877/6b03bb72-f699-11e5-8a25-216d1fc46966.PNG)

link to forum issue: http://www.rockettheme.com/forum/gantry5-for-joomla/251371-cant-add-row-in-section-using-ipad?start=0#1283156

**Comment by charleshowell** [comment]
Thanks, guys! I can't tell you how much I appreciate all the hard work you do to make Gantry 5 great! I brought this issue to Mark, and I am happy to provide any assistance that I can.

**Comment by mahagr** [comment]
I'm having the same issue with my Android tablets; sometimes the touch actions work just fine, most of the time not at all. The same issue exists in Chrome, Firefox, Opera and Android browsers (didn't test anything else) and in all the devices I tested.

**Comment by charleshowell** [comment]
As a somewhat separate yet related issue, try and click on the gear icons and back arrows "<" when working in the Menu Settings page. The same kind of thing is going on here.

**Comment by w00fz** [comment]
Thank you @charleshowell , would you mind opening this as a new issue since this one is closed and although similar still different?

I'll take a look at it tomorrow. Cheers.
