### ISSUE TITLE
Add shortcut button for duplicating collection items

### ISSUE THREAD

**Issue by hexplor** [gantry/gantry5#1220]
Hey folks,
When i was creating a lot of content i came up with following idea. It would so super awesome and cool to add ability to duplicate elements :) See: 

![Image](https://dl.dropbox.com/s/dzy9txrchh1hwy7/Monosnap_2016-04-01_13-37-11.png)

What do you think ?

**Comment by DamirPecnik** [comment]
+1 for this i like the idea!

**Comment by nicutor** [comment]
+1 for this. I was thinking to add an issue like this on the last couple of weeks.

**Comment by w00fz** [comment]
Done :dancers:

**Comment by nicutor** [comment]
Thank you @w00fz Can't wait to test it :)
