### ISSUE TITLE
Zend opcache without file checks causes issues in admin

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#1222]
Following PHP settings cause issues in admin:

```
opcache.revalidate_freq>0
```

```
opcache.validate_timestamps=0
```

We need to reset opcache for all modified PHP files.

**Comment by mahagr** [comment]
@1webmaster4you Can you test your original opcache settings with the latest CI build?

**Comment by 1webmaster4you** [comment]
I Matias,
I upgraded to the latest CI Build (commit: 38ccdbcf6)
It break WOW and ANIMATE .js (they were not working anymore).
I did erase all cache and rebuild GANTRY CSS.
Error came from [JCH optimise pro] : It was resolved by using (**Use try-catch** [**ON**]) in setup.

My latest OPcache setting are on RT forum: [ZEND OPcache - Server CONFIG for Gantry5](http://www.rockettheme.com/forum/gantry5-for-joomla/257143-zend-opcache-server-config-for-gantry5
)

Website Ref.: [MOISSON LAVAL](http://moisson.designserv.net/)

**Comment by mahagr** [comment]
The build shouldn't break javascript, the only changes are small change in css and some php7/opcache fixes.

**Comment by mahagr** [comment]
Most likely a javascript error has occurred on that page. Try enabling 'Use try catch' setting in Advanced Options and see if that helps. If not you will need to exclude the file(s) that are causing the conflict. This tutorial describes how to find the files to exclude:

https://www.jch-optimize.net/documentation/resolving-conflicts-by-excluding-offending-files.html

I don't think that is Gantry issue; though you may want to find out which JS files cause the issue.
