### ISSUE TITLE
Collection List items are not shown when number of variables reach the php `max_input_vars` value

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1226]
Hi guys,

I wanted to add this issue from some time and only now I find some free time.

The issue is that, if you will add many collection lists and/or particle variables, at some point they will not be showed correctly. After I've made a research I find out that the PHP variable max_input_var is set to 1000 by default and when that limit is reached, the particles blow away and are not correctly loaded from database.

The fix is simple. Increase the max_input_var value and restart apache.

I've added this issue for Matias too as a reminder. @mahagr you told me that you know a way to detect this and alert the user or such.

Thanks.

**Comment by mahagr** [comment]
Yes, we should be able to detect if PHP got all the data it needed instead of accidentally truncating data.

**Comment by mahagr** [comment]
@nicutor I'm not 100% sure if I fixed all the cases when this can happen; can you test it out?

Basically I've fixed the issue in assignments and settings tabs, but I haven't touched individual particles (in layout and menu managers).

**Comment by nicutor** [comment]
Great job @mahagr . Thank you.

I will test it out once the new version will be ready and let you know if works for me.
