### ISSUE TITLE
Prevent accidential loss of entered data when editing nested collections

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1227]
Hi,

After a lot of usage on particles by me and my clients I was needed to suggest this.

When there are many nested collection.items and I am needed to enter on those to modify things, the biggest issue is that, if I am not very careful, I can click outside of particle window (on the grey side of popup) and everything I've modified is lost.

Of course, when no nested collections lists, this is not a problem, but when this is happening, I can say that is very very annoying. Not only for me, but when I am asking my clients about, they tell me only 1 reason that they don't like gantry. And this is that, all their modifications are lost sometimes because of this mistake.

Now, If there can be added an option to enable/disable this, will be really great and will improve the entire gantry experience. If not, this is it :) I just got too pissed off about this and I was needed to let you know about.

Thanks.

**Comment by mahagr** [comment]
I'm going to call this a bug because of "it is very annoying". I think we should display similar warning as when leaving a page with unmodified content.

**Comment by w00fz** [comment]
This is now fixed for collection lists as well as for Particles settings (in LM) and Menu Item settings.

**Comment by nicutor** [comment]
Thank you @w00fz :)

**Comment by nicutor** [comment]
Hi @w00fz ,

This work perfect. However, when there are collection lists on a particle, the same accidental click can happen on particle top level too. So, I think that this must be enabled on top level of particle as well and not only on collections.

Should I open a new issue of this or this one can be re-opened?

Thank you.

**Comment by mahagr** [comment]
Open a new issue as the earlier fix was already released.

**Comment by nicutor** [comment]
Done
