### ISSUE TITLE
BUG? Drag-and-drop vs sub-menu items

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#123]
Create a sub-menu item under home menu item, for example, in Joomla menu manager
Go to G5 menu editor and click Hydrogen Home menu item to expand it. Sub-menu item covers 100% of the box.
Drag module/particle onto the sub-menu item of greyed box
- They both will cover the whole box unless module/particle is inserted by creating a 50%-column via + button.
![capture](https://cloud.githubusercontent.com/assets/1849490/7333462/38428d66-eb79-11e4-80fb-149438a2700b.JPG)
- If you go to Menu editor from Layout window, for example and go "Back to configuration" from there you will be directed to Styles not to where you left off.

**Comment by w00fz** [comment]
I'm not sure I understand. What is the issue?

**Comment by adi8i** [comment]
Well is not any issues. First thing you said. 
> They both will cover the whole box unless module/particle is inserted by creating a 50%-column via + button. 
By defautl submenu items will be arranged in a column, if you want them to show on 2 columns just click + button and add one more.

**Comment by w00fz** [comment]
The point 1 is not an issue as it's been explained by @adi8i. 
For point 2 I enhanced this so now it keep tracks of the last tab you were in and going Back will take you there.

**Comment by adi8i** [comment]
Actually you can set a custom size for dropdown, from `Style` - `configuration styles` - `menu` .... i  just said something wrong above :dancers:
