### ISSUE TITLE
Cannot override platform-content

### ISSUE THREAD

**Issue by HarryBosh** [gantry/gantry5#1231]
Why is `<div class="platform-content">` in the framework? Doesnt this make it impossible to override?

**Comment by mahagr** [comment]
It is used to separate our own Nucleus layout system from the platform one (like Bootstrap 2.0) as they may be using different CSS resets. Basically without that the platform content may look broken.

**Comment by HarryBosh** [comment]
What i do is create a design, build static html/css, then wrap it around joomla, gantry5, or any other cms / template engine. I am using bootstrap4 etc.. and have stripped out all joomla and gantry css and js and replaced it from the static build.

Whatever the reason Nucleus needs it, it is not required for developers like myself, and if i update gantry framework, it could now interfere with my html/css unless i refactor my code. From what i understand from using gantry5 you all have gone to great lengths to make this awesome and flexible. which it totally is, except that line of code.

**Comment by mahagr** [comment]
Well, if you want to replace nucleus with Bootstrap 4, you should also replace/update the template files that nucleus comes with. Which platform you are on?

**Comment by HarryBosh** [comment]
How would i find which platform i'm on?

I am just overriding all instances of html/css with my own. is that what you mean by 
> replace/update the template files 

`templates/g5_interludic2/custom/engine/templates/etc..`

**Comment by mahagr** [comment]
I would say you're using Joomla. :)

Yes, I was meaning that you should override all the files in the engine. The original engine files are located in `media/gantry5/engines/nucleus/templates` and you can copy them into the folder you pointed above in your message. 

PS: I'm very interested to see what you come up with as Gantry is supposed to have support for multiple rendering engines, but I've never had change to test them (and I think they're not fully working either). So if you succeed in your changes, I would like to see them, even in private, in order to finish and document this feature.

You can join us in Gitter chat https://gitter.im/gantry/gantry5 if you want to.

**Comment by HarryBosh** [comment]
I will post back a link to the repo when i am done.



On Wed, Apr 13, 2016 at 3:50 PM, Matias Griese <notifications@github.com>
wrote:

> I would say you're using Joomla. :)
>
> Yes, I was meaning that you should override all the files in the engine.
> The original engine files are located in
> media/gantry5/engines/nucleus/templates and you can copy them into the
> folder you pointed above in your message.
>
> PS: I'm very interested to see what you come up with as Gantry is supposed
> to have support for multiple rendering engines, but I've never had change
> to test them (and I think they're not fully working either). So if you
> succeed in your changes, I would like to see them, even in private, in
> order to finish and document this feature.
>
> You can join us in Gitter chat https://gitter.im/gantry/gantry5 if you
> want to.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/1231#issuecomment-209239469>
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by w00fz** [comment]
Any news on this?

**Comment by HarryBosh** [comment]
If i upgrade gantry5 then it will undo the changes made to the core.

On Thu, Apr 21, 2016 at 1:05 PM, Djamil Legato <notifications@github.com>
wrote:

> Any news on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/1231#issuecomment-212710472>
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by mahagr** [comment]
Yeah, well, there's a way in Gantry to use override files for everything instead of changing the core files. Just copy all the modified nucleus files into `templates/your_template/custom/engine` and you can safely update Gantry.

**Comment by HarryBosh** [comment]
The override would conflict with future updated versions,

never mind i have updated to 5.2.14

as long as that particular div doesnt get styled it should be fine.

Thanks

On Thu, Apr 21, 2016 at 3:15 PM, Matias Griese <notifications@github.com>
wrote:

> Yeah, well, there's a way in Gantry to use override files for everything
> instead of changing the core files. Just copy all the modified nucleus
> files into templates/your_template/custom/engine and you can safely
> update Gantry.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/1231#issuecomment-212748444>
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by w00fz** [comment]
Nothing in `custom/` folder gets ever overwritten by updates. It's the whole point of that folder, we created so that users can add their tweaks and overrides and never have to worry about losing them.

Anyway I don't foresee us ever changing that div so you should be good!

**Comment by mahagr** [comment]
BTW, I would still love seeing your BS4 implementation. :)

**Comment by HarryBosh** [comment]
Yeah but the overrides are overriding any updates to those files...
negating the update/security fixes to that file.


Frontend WIP
http://interludic.com.au/projects/barrasteel/staging/





On Thu, Apr 21, 2016 at 3:25 PM, Matias Griese <notifications@github.com>
wrote:

> BTW, I would still love seeing your BS4 implementation. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/1231#issuecomment-212750218>
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by mahagr** [comment]
There shouldn't be any security fixes in template files, just maybe some new functionality.
