### ISSUE TITLE
Two update sites for Gantry ?

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1232]
Hi,
I have a question. On **Extension > Manage > Update Sites** there are 2 entries for Gantry 5.
It's normal ?

![update-sites](https://cloud.githubusercontent.com/assets/3976174/14420079/41511b78-ffca-11e5-80d4-0e95c6f890de.jpg)

**Comment by mahagr** [comment]
Yeah, one if for Hydrogen (and other free official themes) and another for gantry 5 itself.

**Comment by mariantanase** [comment]
ok thanks
