### ISSUE TITLE
Image Picker causes 500 Error

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1233]
When i click on the image picker (in any particle that has one) i get the popup as per the attached image. 

This is the first time this has happened, and i'm not sure what has caused it.

![2016-04-11_170734](https://cloud.githubusercontent.com/assets/12219933/14426359/fb314404-0020-11e6-8b3f-5d65df504b5e.jpg)

This happens with or without any image in the field.

**Comment by mahagr** [comment]
Which template are you using? I've tried to reproduce this in Hydrogen trying all kinds of things, but no avail.

**Comment by igor-gp** [comment]
@mahagr i'm using one of our own, i'll install a new instance of WP with hydrogen on it to see what happens on the same server. 

BTW, i am using a CI build Version: dev-7019d0259 / Released: March 21, 2016 so unless its something with that CI, not sure.

I will get back to you with results soon

**Comment by igor-gp** [comment]
Ok well the new install with hydrogen works fine and i used a CI. 

I have tried disabling all plugins except Gantry and Timber and still the issue is there.

Any ideas?

**Comment by igor-gp** [comment]
I have just reinstalled WordPress and that did nothing either. :(

**Comment by mahagr** [comment]
I may have to take a look into your site in order to figure out what might go wrong.

Can you contact me via Gitter?

**Comment by igor-gp** [comment]
Sure

**Comment by mahagr** [comment]
wp_upload_dir() returns

```
Array
(
    [path] => /home/matias/www/wordpress/gospel/wp-content/uploads/2016/04
    [url] => http://wordpress.local/gospel/wp-content/uploads/2016/04
    [subdir] => /2016/04
    [basedir] => /home/matias/www/wordpress/gospel/wp-content/uploads
    [baseurl] => http://wordpress.local/gospel/wp-content/uploads
    [error] => 
    [relative] => http://wordpress.local/gospel/wp-content/uploads
)
```

Last path is clearly wrong.

**Comment by igor-gp** [comment]
I can confirm the fix works, thanks!
