### ISSUE TITLE
Gantry-media paths/folders

### ISSUE THREAD

**Issue by Trust7** [gantry/gantry5#1237]
What are the default paths of folders that are included in "gantry-media://" for example when using the "Pickers"? How to change/add paths/folders to "gantry-media://"?

For example I want to create a particle with a filepicker where later I would like to choose a PDF file. I found out that one of the folders included in "gantry-media://" is "media/gantry5" but what if I would like to store my files (for filepicker) in "custom" folder? At the moment I only know that the "custom/images" folder is included in "gantry-media://" but storing for example PDFs in "images" folder doesn't sound right.

**Comment by w00fz** [comment]
You can use the `root` parameter to specify a different folder, so if you have a `custom/pdf` folder in your theme, you could say:

```
root: 'gantry-theme://custom/pdf'
```

**Comment by Trust7** [comment]
It works perfectly! Thank You! It is really amazing how powerful Gantry5 is and at the same time how easy it is to use.

**Comment by davezelenka** [comment]
Where is the yaml file that needs to have root: /custom/folder added? Thanks.

**Comment by mahagr** [comment]
Not yaml file but a filepicker form field inside your particle blueprints.

**Comment by davezelenka** [comment]
Nice. Thank you.
/templates/g5_helium/particles/owlcarousel.yaml
