### ISSUE TITLE
Editing article / category page_layout

### ISSUE THREAD

**Issue by HarryBosh** [gantry/gantry5#1239]
How do you isolate the article elements?
`eg: <h1 class="title">{{ article.title|e }}</h1>`

body, fulltext, parameters, etc.. how do we access these?

at the moment all we have is html|raw

**Comment by HarryBosh** [comment]
Never mind i will just override the article content, would be nice to able to do the mentioned though?

**Comment by mahagr** [comment]
Component layouts can be overridden just like in all Joomla templates by copying the layout file into `html` folder and using php in those files.

**Comment by w00fz** [comment]
Marking this as resolved, looks like you got the answers you were looking for. Feel free to reopen otherwise.
