### ISSUE TITLE
Creating new layout does not work

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#124]
I just follow the steps in the [Documentation](http://docs.gantry.org/gantry5/advanced/creating-layout-presets) in order to create a new layout but it does not work. I want to mention that it worked fine in Beta 1 and 2 where I also tried it.

Have a look at the video below:

https://youtu.be/KyLffS_HsHo

**Comment by adi8i** [comment]
Yes, i've tried that too :).

**Comment by adi8i** [comment]
Change the name of yaml file, will not work because you already have a `test.yaml` layout in `g5_hydrogen/layouts`

**Comment by adi8i** [comment]
Check the file type :P, in your folder it say is a text document, so the extension may be `test.yaml.txt` 
![capture](https://cloud.githubusercontent.com/assets/9744973/7334908/84fa67ba-ebaa-11e4-81d8-4827d75acde7.PNG)

**Comment by JoomFX** [comment]
@adi8i thanks a lot Adi :)
yes, that was it. such a stupid thing. I shouldn't be testing when I'm so tired.
it explains why it was working before :D
