### ISSUE TITLE
site root in menu.html.twig partial?

### ISSUE THREAD

**Issue by HarryBosh** [gantry/gantry5#1242]
Hi,

How do i get the joomla dir / root
**within ROOT/templates/wasHydrogen/particles/menu.html.twig**

I have tried the following.
```{{ gantry.platform.root() }} {{ joomla.call('JUri::root') }}```

**Comment by mahagr** [comment]
I believe that second one should work. If it doesn't, try something like:

    {{ joomla.call(['JUri', 'root']) }}

**Comment by HarryBosh** [comment]
Niether are working inside the particle

**Comment by mahagr** [comment]
I just tested and both `{{ joomla.call(['JUri', 'root']) }}` and `{{ joomla.call('JUri::root') }}` return `http://joomla.local/` in my test site.

**Comment by HarryBosh** [comment]
in a particle?

On Tue, Apr 19, 2016 at 3:54 PM, Matias Griese <notifications@github.com>
wrote:

> I just tested and both {{ joomla.call(['JUri', 'root']) }} and {{
> joomla.call('JUri::root') }} return http://joomla.local/ in my test site.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/1242#issuecomment-211740647>
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by mahagr** [comment]
Yes, I edited logo particle and just added all of the examples into there. That said, there's yet another way to do the same; just look into logo particle how it points to home page:

`{{ gantry.siteUrl() }}` gives relative path to the home page.

**Comment by HarryBosh** [comment]
Problem was that it didnt work in the marco scope

so i had to pass it through all the macros that required it, starting with
```{{ _self.displayItems(menu.root, menu, _context, '', gantry.siteUrl()) }}```

**Comment by mahagr** [comment]
Yeah, macros are problematic as they do not have global scope.
