### ISSUE TITLE
Moving Particles / Modules in sublevels in the Menu Settings doesn't preserve the settings

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1243]
Hey guys,

I have picked up on an issue, it happens when you create a custom html menu particle and drag and drop it into an existing menu as a drop down. The observations:

1. The settings don't want to open once in the drop down spot
2. The actual item doesn't show in the spot you put it in on the front end. 

I have done a quick video showing this. Is it just on my end or?

[custom html particle in dropdown menu.zip](https://github.com/gantry/gantry5/files/223738/custom.html.particle.in.dropdown.menu.zip)

**Comment by w00fz** [comment]
Thanks Igor, this is now fixed.

Good catch!

**Comment by igor-gp** [comment]
@w00fz Great thanks!
