### ISSUE TITLE
Particle content inhertance (feature)

### ISSUE THREAD

**Issue by HarryBosh** [gantry/gantry5#1244]
Would be great to be able to inherit content from another page layout,
Is this possible?

Where the same content that get's used on the home page can be inherted on the sub page layout. at the moment i am duplicating the footer and header content which is unlikley to be different.

![image](https://cloud.githubusercontent.com/assets/6327261/14694055/358d3c82-07a8-11e6-9ca4-bec9e70696ed.png)

perhaps a "inherit from" drop down list?

**Comment by w00fz** [comment]
Hi, this is actually planned as our next focus for 5.3. There will be inheritance for both sections and individual particles, that you can inherit from other outlines.

**Comment by HarryBosh** [comment]
Great, will this just be an update to the framework or do i need to update my template as well?

**Comment by w00fz** [comment]
It will just be a Gantry release, all templates will be able to use it without any change.
