### ISSUE TITLE
Image Picker (-) collapse button doesn't work

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1246]
The collapse button doesn't work in the image picker.

![interstellar theme gantry5 dev wordpress 2016-04-21 12-09-51](https://cloud.githubusercontent.com/assets/1641534/14705552/6726c774-07ba-11e6-8788-1b9f44b95ab6.jpg)

**Comment by w00fz** [comment]
Works for me on both platforms (tested with chrome), which browser are you using?

**Comment by newkind** [comment]
Firefox

**Comment by w00fz** [comment]
Thanks, could reproduce and fixed.
