### ISSUE TITLE
Prevent accidential loss of entered data when editing particles

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1247]
Hi @w00fz ,

This issue is related to https://github.com/gantry/gantry5/issues/1227

The last comment from there is:

> This work perfect. However, when there are collection lists on a particle, the same accidental click can happen on particle top level too. So, I think that this must be enabled on top level of particle as well and not only on collections.
> 
> Should I open a new issue of this or this one can be re-opened?
>
>Thank you.

**Comment by w00fz** [comment]
Are you sure you are up to date? With that fix in #1227 I also made sure that Particle Settings cannot get closed when in Layout Manager, to avoid the same problem you raised regarding collections.

I am trying now on my local and it seems to work as expected.

Do I understand right that you are referring to Layout Manager and a Particle such as Social that contains a Collection list, and that when you open the Particle Setting you can still click on the overlay to get it closed?

Perhaps I need a screenshot 😃

**Comment by nicutor** [comment]
Yes, you understand right. When you click on Edit Particle button on modules (not on template > particle defaults), you can still click on the first overlay to close it. So this is on Extensions > Modules > Gantry 5 Particle Module.

On collection lists is working fine. However, even if somebody enter their data on collection lists, they can press on the last overlay of particle (top level one and they can still lose everything).

I think the best way is to disable the click on overlay on the entire particle and not on the collection lists only.

**Comment by w00fz** [comment]
Ahhhh, I don't think you mentioned you were in the Gantry 5 Particle Module! I assumed you were in the Layout Manager / Menu Editor as those are the only other places where you can edit a particle in a modal, and that was working for me.

I see what you mean now and I can reproduce the issue. Fixing :)

**Comment by nicutor** [comment]
Thank you @w00fz :)
