### ISSUE TITLE
HTML entities not encoded properly in menu item titles

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1248]
Noticed in the drop down menu that the HTML entities are not encoded properly, for example `&` is coming through as `&#038;`. So a title like **Mission & Vision** is showing up as `Mission &#038; Vision` 

Unless its something on my end.

**Comment by w00fz** [comment]
It does render properly for me with Hydrogen

**Comment by w00fz** [comment]
Note: I tested on Joomla, what platforms are you on?

**Comment by adi8i** [comment]
Hey @w00fz , that's on WordPress.

**Comment by adi8i** [comment]
And it's a child item, if this helps.

**Comment by w00fz** [comment]
Thanks. I tested in WordPress too and changed the child but it still seems to work fine for me.

![gantry 5 dev just another wordpress site 2016-04-21 11-44-45](https://cloud.githubusercontent.com/assets/11734/14720474/7a7cae14-07b6-11e6-9e88-0f2b04459c57.png)

**Comment by mahagr** [comment]
Look into the database and check how the `&` is stored in there. I believe that the entry looks like `Mission &#038; Vision`. I'm not sure why your site stores the character in different way to @w00fz 's site, but this might be something I'm able to fix if I know more about the issue.

**Comment by DamirPecnik** [comment]
Same was for this person http://www.rockettheme.com/forum/gantry-for-wordpress/257623-latest-gantry-5-update-messing-with-menus i add the html character in and it worked ...

**Comment by newkind** [comment]
Hmm I was having the same issue when I was developing Topaz. We need to take care of it ASAP.

**Comment by adi8i** [comment]
I seen on some forums other WP users reporting this, not sure if it's gantry related.

**Comment by mahagr** [comment]
It was Gantry related, though this seems to be happening only the first time you save menu. Second time it will convert the entities into characters, which work just fine.
