### ISSUE TITLE
Disabling "compile yaml" and "compile twig" writes lots of directories to Windows hard drive root

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1250]
Windows system.

In "system - Gantry 5" plugin if you disable the "compile yaml" and "compile twig" options then the next recompile of CSS from base outline or automatic recompile dumps loads of folders into the root of your hard drive.

![2016-04-22_14-12-00](https://cloud.githubusercontent.com/assets/11683218/14742469/4cee129c-0894-11e6-857f-928a597ff029.png)

These directories contain log encoded files names with a .php extension.

http://www.rockettheme.com/forum/gantry5-for-joomla/257976-in-photon-project-twig-save-caching-files-in-hard-drive-root?start=10#1288121

**Comment by mahagr** [comment]
Must be fixed before new release gets out.
