### ISSUE TITLE
Expand left on parent menu item for dropdown doesn't work if "extended" dropdown

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1252]
If you change the dropdown options on a parent menu item in Gantry 5 menu editor to "expand-left" then it does not work on "extended" dropdown style - it only works on "simple" dropdown style. I test this on intersteller "pages" menu item. 

I'm not sure if this is intentional behaviour but even if it is I think we could improve it to work with "extended" too.

![2016-04-25_17-04-20](https://cloud.githubusercontent.com/assets/11683218/14790144/e9a4e4f6-0b07-11e6-931f-dc244df4edc4.png)

![2016-04-25_17-04-52](https://cloud.githubusercontent.com/assets/11683218/14790148/ee71a0aa-0b07-11e6-9395-2c268e6f469e.png)

http://www.rockettheme.com/forum/gantry5-for-joomla/258098-wrong-expand-left-dropdown-direction-when-2-levels-item-menus?start=0#1288666

**Comment by w00fz** [comment]
This is now implemented for Extended menus who define a fixed size.

**Comment by marktaylor46** [comment]
This does not appear to work unless I misunderstanding it. I tested this on interstellar with G5.2.15 with the settings as per my screenshots above - the dropdown type is "extended" and the dropdown width is set to 320px and the direction is set to "expand left" yet it still opens to the right?

**Comment by mahagr** [comment]
Its not in 5.2.15, see the milestone on the right side. :)

**Comment by marktaylor46** [comment]
Ooops - sorry. As it was fixed before 5.2.15 came out I made the wrong assumption that it was in 5.2.15. I have now downloaded and installed the CI build and it is indeed fixed in that version :+1:

**Comment by w00fz** [comment]
I actually implemented it right after 5.2.15 release so it didn't make it through. It required a bit more time developing and we wanted to ensure it went through a test pass first.

**Comment by marktaylor46** [comment]
Ok - I tried it and it seems to work fine for me - so thanks :+1:
