### ISSUE TITLE
"The menu selected is empty!" error in Menu editor when PHP default_charset is not "UTF-8"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1257]
A member initially reported this and I have now been able to reproduce the error.

If in php.ini the default_charset is set to anything other than "UTF-8" then when you go into Gantry 5 menu editor you will get an error "The menu selected is empty!". Changing the default_charset back to "UTF-8" restores normal working function. Also, when you get the error you can enable "debug mode" in Joomla Global configuration and this makes the menu editor work again too strangely.

I think we should either copy with the charset change or displayt a better error message.

![2016-04-27_11-46-41](https://cloud.githubusercontent.com/assets/11683218/14851991/a35625f8-0c7b-11e6-8a64-ab7a990fcb4f.png)

![2016-04-27_13-26-43](https://cloud.githubusercontent.com/assets/11683218/14852024/c9579fac-0c7b-11e6-96ac-2acad494efbd.png)

**Comment by mahagr** [comment]
Warning: htmlspecialchars(): charset `latin1' not supported, assuming utf-8 in …/­classes/­Gantry/­Framework/­Menu.php362

**Comment by mahagr** [comment]
Fixes the issue with the menu, but just a warning: Joomla still doesn't work properly if default charset is anything else than UTF-8.
