### ISSUE TITLE
Option image fulltext in the Particle Joomla Article

### ISSUE THREAD

**Issue by lauroguedes** [gantry/gantry5#1258]
I will like to leave a sugestion to the particle Joomla Articles.
To implement the possible to put the option to article full image
and yet to allow the two options

**Comment by mahagr** [comment]
I'm not sure what you mean, can you describe it better with an example?

**Comment by nikola3244** [comment]
@mahagr Fix is in pending #1261

**Comment by w00fz** [comment]
The PR @nikola3244 proposed (#1261) has been merged in and solves this issue as well.

Cheers
