### ISSUE TITLE
Atoms not deleting in Chrome on Android

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1259]
Dragging the Atoms to the "trash can" on the top of the screen is possible, but upon releasing the finger, nothing happens. 
Particle deleting is working.

Chrome 49.0.2623.105; Android 5.1.1

**Comment by w00fz** [comment]
This was a tough one! 

Good catch, thank you.

**Comment by kashifu72** [comment]
I'm having this issue with Chrome and Firefox on Android.

**Comment by mahagr** [comment]
Can you also specify the versions you were using?
