### ISSUE TITLE
Gantry5 Admin language override - 5.2.15

### ISSUE THREAD

**Issue by Trust7** [gantry/gantry5#1263]
Today I made an language override in custom folder of the en-GB.com_gantry5.ini file and it worked great. Then I made a Gantry5 5.2.15 update and all the translation disappeared - it seems that it is getting the language strings from "administrator\components\com_gantry5\language\en-GB" folder only (when I make changes in this folder then the translation shows up). I just checked again and indeed it happens when I make update from 5.2.14 to 5.2.15.

**Comment by sanek4life** [comment]
Gantry 5 have many, many settings.

this is really what everybody want, translation into other languages.

**Comment by mahagr** [comment]
The main translation files (`en-GB.com_gantry5.ini` etc) are loaded by Joomla itself, so you can put the files into the usual locations, eg. `languages/xx-XX` and `administrator/languages/xx-XX`).

**Comment by Trust7** [comment]
Yes, I know I can put the files there but wouldn't they get overwritten with an update? I wanted to use the "custom" folder to just override the language files (that worked in 5.2.14). My question is why it doesn't work after 5.2.15 update?

**Comment by mahagr** [comment]
Nothing has changed. Main language files should always be in Joomla default locations -- custom is for automatically generated language files (positions mostly). In Joomla you can store language files into 2 locations: inside component/extension (automatically updated) and main language folder (usually 3rd party translations). If you put the file into later one, it will not be overridden.

**Comment by mahagr** [comment]
@Trust7 Has this issue been solved for you?

**Comment by Trust7** [comment]
Yes, it is solved. Thanks
