### ISSUE TITLE
Gantry 5 + hydrogen

### ISSUE THREAD

**Issue by Cremasterau** [gantry/gantry5#1267]
I have a fairly basic site that presents as fully responsive when resizing a desktop window or even when 'toggling device mode' in Chrome but when I check it on my phone it is not responsive at all.

Any thoughts would be appreciated.

Cheers

**Comment by mahagr** [comment]
Responsiveness is working only in Android 5+ phones as Android 4.4 comes with a custom browser that hasn't been updated for 3 years. I recommend using Chrome instead.

**Comment by Cremasterau** [comment]
Thanks for the reply mahagr, 

The phone I was using was a iphone 3, retro I know but hey.

Is this still the same issue?

**Comment by w00fz** [comment]
Yes, I believe the iPhone 3 iOS cannot be upgraded so you are stuck with a very old Safari which does not support a lot of the features required for responsive to work, like Flexbox. Unfortunately this does fall into our unsupported browsers.

You could try downloading Chrome for iOS, if they support your iOS version, it might work with that.
