### ISSUE TITLE
Coming soon page

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#127]
A request: beyond the "error page", it could be possible adding a "coming soon" page, maybe with a counter and an email address? I suppose it's not so hard to create it using a particle, but put the counter inside the particle could be a bit tricky (from a coding point of view...)
Also it could be nice to have the same opportunity for the whole site ...

**Comment by mahagr** [comment]
@kevlardev @w00fz 

What did we decide on this one?

**Comment by kevlardev** [comment]
We were not going to have a page dedicated to coming soon, as there really is no difference between it and a normal page from a layout manager point of view (error is unique as its tied to a specific event). Really any page can be a 'coming soon' page, we do however plan to add a coming soon particle that would include the counter and email similar to our previous g4 coming soon page. This would allow it to be more universal (you could have multiple coming soon pages for different sections of a site, or coming soon portions of a particular page, etc).

**Comment by beamaria** [comment]
This "coming soon " particle will be really cool... and flexible too! Brilliant idea Kevin :-)
As usual, the Gantry team solution are always many steps beyond!

**Comment by beamaria** [comment]
This "coming soon " particle will be really cool... and flexible too! Brilliant idea Kevin :-)
As usual, the Gantry team solution are always many steps beyond!

**Comment by beamaria** [comment]
This "coming soon " particle will be really cool... and flexible too! Brilliant idea Kevin :-)
As usual, the Gantry team solution are always many steps beyond!

**Comment by w00fz** [comment]
We are going to have this particle provided by the themes for now, eventually in the future this might become a core Gantry particle but not for now.
