### ISSUE TITLE
Using variables, outline name, etc. in styles -> Background image field?

### ISSUE THREAD

**Issue by n8115** [gantry/gantry5#1270]
[Wordpress]  Is there any way to use some type of variable to auto-populate the background image for a section?

i.e.  gantry-media://banners/team/ ** outline, page featured image, or page name here**  .jpg

I'm setting up a very large "Team" section where each profile needs it's own background image in Showcase, and without being able to do this, it looks like I'll need to manually set up dozens of outlines which is going to be a pain to maintain..

Any ideas?

**Comment by w00fz** [comment]
Have you considered creating a Particle with a collection list? Each item could be a Team member and from the particle you would be able to have unique and per member backgrounds

**Comment by w00fz** [comment]
Any update on this? 😄

**Comment by n8115** [comment]
Thanks for the reply!

I just looked into collection lists, all I found was
http://docs.gantry.org/gantry5/advanced/particle-yaml-field-types

I'm not really seeing how these would solve this problem..

**Comment by w00fz** [comment]
Look at the Social particle, it's very similar in a sense. You can pick different social media, assign an unique icon, text and link for each one.

The same way would be for your team list, each member of the team will have unique name, banner, text, etc.

Seems exactly what you are looking for.

**Comment by n8115** [comment]
OK I see what you mean, so I'd set up a collection list with an item per team member, but then I'd still have to set up an outline for each team member, and select only their item in the collection list... Is that right?

What I'm trying to avoid is having multiple particles, and hopefully have my client not have to go into the gantry5 outlines to swap out images (be able to update page content AND banner image from the "Page" - with the Gantry outline being used to pull in custom fields, a link back to the main "staff" page etc.. something the client would never need to touch.

**Comment by w00fz** [comment]
I am not entirely sure why you need an outline for each member, is that the details page? That would be a different thing.

The collection list allows to list items in an outline, so if you wanted the same but with only one item in a different outline, you would probably need another particle for that.

The good thing about this is that when you add the image field in the collection list items, you can then specify that once for each member (ie, `gantry-media://team/joe.jpg`, `gantry-media://team/kate.jpg`), then all anyone will have to do to update those images is to just replace them via FTP.

**Comment by n8115** [comment]
I think what I'm struggling to understand is how to tell each page which
image should show up.

So I have dozens of staff profile pages, all assigned to my "Team Profiles"
outline.

On the team profiles outline, I have this collection list particle, with
items for each staff member.


Where do I tell this particle which item should show up on which page?

**Comment by w00fz** [comment]
Ok I'm sorry, I misunderstood, I thought you wanted to list all the staff profiles in one page only, which is why I was suggesting the collections list particle.

Have you checked the body class names? We do populate it with a lot of useful names based on menu, page, outline, etc.

Example:
```html
<body class="gantry g-offcanvas-left g-home-particles g-style-preset3 home page page-id-31 page-template-default site outline-home_-_particles dir-ltr">
```

Although this is also probably not what you were looking for. There really isn't a variable that you can use in SCSS, nor any easy way to accomplish this other than overriding the `section.html.twig` so that it automatically renders with the page-name background in place.

**Comment by mahagr** [comment]
Which component are you using in those team profile pages? If you do not need any Joomla component output, you can also use Gantry component and render a particle as main content.

**Comment by n8115** [comment]
I ended up figuring out a decent solution outside of Gantry.. Set up a custom plugin that grabs the content from a custom field on each page (set to an image url), then applies <style>#g-header{background-image:url($banner) }</style>

Looks like I probably could have done something similar with a modified particle.


Down from 30'ish outlines to 1 :D

**Comment by mahagr** [comment]
Sounds like a good way of doing it. I'm going to close the issue as being solved. If you have further questions, just go ahead. :)
