### ISSUE TITLE
Joomal Gantry5 sidebar

### ISSUE THREAD

**Issue by omaralsoudani** [gantry/gantry5#1272]
Hi All,
Please advice me , How can I create a sidebar in Joomla gantry5 by easy way ??
And if I create a sidebar , How can I assign this sidebar in just a few menu not all??

Thanks a lot,
Enana
pro@enana.com

**Comment by nikola3244** [comment]
@omaralsoudani Something like [this](http://docs.gantry.org/gantry5/advanced/creating-layout-presets#how-to-create-a-sidebar-section)?

By the way, you can also ask questions like this in [Gantry 5 Gitter chat](https://gitter.im/gantry/gantry5). :smile:
