### ISSUE TITLE
Copyright not Displaying Correctly

### ISSUE THREAD

**Issue by TGoodrich** [gantry/gantry5#1273]
I'm not sure when this issue started but I noticed today that the copyright  "© 2016" now displays after the copyright text instead of before.

**Comment by w00fz** [comment]
This has been changed with 5.2.15, have a look at https://github.com/gantry/gantry5/issues/950#issuecomment-155911536.

**Comment by mahagr** [comment]
@w00fz Should we add placeholder for `Copyright` and display it if there's nothing given in the field?
