### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by Frenkie64** [gantry/gantry5#1276]
ello people, small question. I have a site, that works fine on a computer. however, on a mobile device, I have two issues. 
1. The top bar (header, navigation, logo) is only the width of the device. when I show a larger picture and scroll to the right, the top part stays white on the mobile page (it should be dark grey). On the regular page I have no scroll, so no issues 
![image](https://cloud.githubusercontent.com/assets/17751433/15123370/ba577188-1623-11e6-9d42-140939a94c6a.png)

2. On some device browsers, the full menu is shown in stead of the mobile menu. is there a known issue? Can I resolve that? I noticed this to be happening on the default browser in my Galaxy Tab 3 (7"), while Chrome on the same device shows the mobile menu. On my girlfriends LG G3 default browser, same issue, chrome on the same device works perfect. On my Galaxy S6, both browsers work normally.

**Comment by alisamii** [comment]
Default Android Browser is not fully responsive except in the more recent OSs.

**Comment by w00fz** [comment]
Correct, the default Android browser is not supported by Gantry because uses old engines that are not capable of rendering flexbox or CSS3.

http://docs.gantry.org/gantry5/basics/system-requirements#browser-requirements

**Comment by mahagr** [comment]
LG G3 can be upgraded to Android 5.0 (and depending on your carrier to 5.1 or even 6.0). Upgrading away from Android 4.4 will fix most of the rendering issues with the default Android browser.

Cheap devices like Galaxy Tab 3 seem to always be running with outdated version of Android with no updates available. I think its very bad policy from any company, but I guess they just want to maximize income and do not care about their low and mid range customers.
