### ISSUE TITLE
page title, breadcrumbs (widget particle)?

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1280]
I am creating my first project for a client (this serving as learning), I noticed several exemblos with some good layout options, but when it was put into practice customizing a design, I found these options in the documentation and also not found in any preset, is there any ready particle breadcrumbs? or I have to create? or I use a plugin and put the reference it inside a widget particle? I look for something that shows in row 1 of the title page and in line 2 the bredacrumbs even like to be able to do everything within the grantry, but if it is not possible will use third-party resources, which indicate to me?

**Comment by mahagr** [comment]
You can use plugin (I bet PW has one) and either use widget instance or normal position/sidebar and put it into there.

**Comment by astenio** [comment]
tnks!
