### ISSUE TITLE
error message/ version v5.2.15 / g5_hydrogen

### ISSUE THREAD

**Issue by samiradz** [gantry/gantry5#1281]
Hello,

I have installed the latest version of gantry 5 and since this update I can't save a changes into hydrogen theme.

I use Joomla 3.5.1. Here are the error message.
-----------------------------------------------------------------------------
Whoops\Exception\ErrorException thrown with message "PHP Startup: imagick: Unable to initialize module
Module compiled with module API=20121212
PHP    compiled with module API=20131226
These options need to match
"
Stacktrace:
#0 Whoops\Exception\ErrorException in Unknown:0

-------------------------------------------------------------------------------
Could you help me please ?

ps: excuse my English.

Best regards.

**Comment by mahagr** [comment]
Yeah, not related to Gantry but a badly configured PHP.
