### ISSUE TITLE
custom particle 'content'

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1282]
hello,
I had a small idea for two particles, like to customize the particle 'content', this particle displays the current page, made as indicated in the documentation, I searched the folder 'wp-content \ plugins \ gantry5 \ engines \ nucleus \ particles' but, just I found the 'content.yaml' file not found 'content.html.twig' file, where I find the file to be able to do this?

**Comment by newkind** [comment]
Are you talking about "WordPress Posts" particle ? If yes, then the file is named `contentarray.html.twig`

**Comment by astenio** [comment]
no, no, i talking about "Wordpress Page".

**Comment by astenio** [comment]
![cscitc3 1](https://cloud.githubusercontent.com/assets/7676600/15270665/c41843a4-19fd-11e6-8239-41284bb0bbd8.png)

**Comment by mahagr** [comment]
The template file for page content can be found from the plugin itself; `wp-content/plugins/gantry5/engines/nucleus/templates/content/system.html.twig`. It also drives system messages, so be careful when changing it.
