### ISSUE TITLE
"Gantry 5 - Presets" plugin

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1285]
@w00fz @mahagr Guys, isn't it better to have this plugin disabled by default?

[As we discussed before](https://github.com/gantry/gantry5/issues/1068), this plugin should be used for the Template Demo only. Therefore it is disabled in the Quickstart package (Rocketlauncher) of all our templates and all RT templates. But as soon as you update the Gantry Framework in the Quickstart/Rocketlauncher the plugin gets enabled again and it is very easy to forget about it and release a Quickstart/Rocketlauncher with enabled "Gantry 5 - Presets" plugin.

**Comment by w00fz** [comment]
It looks like a bug, it is disabled by default but for some reasons after update it gets reset to enabled, not sure why.

**Comment by JoomFX** [comment]
Yay! Thanks Matias :wink:

**Comment by mahagr** [comment]
Can you test it out? It seems to work, but more CI build tests would be cool. :)

**Comment by JoomFX** [comment]
Yep, it works just fine with the latest CI (commit: `04acf6c34`) :wink:

**Comment by mahagr** [comment]
Cool, we will get the fix out tomorrow.

**Comment by JoomFX** [comment]
Great!
So, just out of curiosity, are you going to release 5.2.18 tomorrow?
I'm asking because I'm currently updating the Quickstart (Rocketlauncher) packages of our templates so I'm wondering if I should wait for 5.2.18 (I do not want to release the updates with 5.2.17 because of the `row-fluid` thing) :wink:

**Comment by mahagr** [comment]
If you are very busy on testing latest CI build, I can even release 5.2.18 later today. :)

**Comment by JoomFX** [comment]
No, I already tested the CI build but I do not want to release an update of our templates, where the Quickstart comes with a CI build :wink: 
Thanks Matias, I really appreciate that, but do not push the release just for me. I know you have much more important things to do, so I'll just wait :wink:

**Comment by mahagr** [comment]
No, we have planned to release the new version either today or tomorrow depending on how much testing it gets. So its all up to testing at this point -- no more changes are coming.
