### ISSUE TITLE
Icon Selector Bug and Layout Issue

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1290]
I noticed when i am trying to edit the icons and i only want to change the icon size that select button is not working i need to select the icon again ... also the icon size is not well align in the layout see screenshot...

![2016-05-17 23 16 38](https://cloud.githubusercontent.com/assets/10489911/15339662/c6312a40-1c85-11e6-88cf-f355ee8b0773.jpg)

**Comment by w00fz** [comment]
The dropdown has been fixed in the `53_goodies` branch, the alignment was already fixed in there.
Also the size will never affect the button icon in the field (your right most arrow in the screenshot), otherwise the UI will get messy.
