### ISSUE TITLE
JSN Uniform doesn't load after update Gantry

### ISSUE THREAD

**Issue by ComunicaViVe** [gantry/gantry5#1291]
Hello there, after the update my form doesn't load, only the wheel loading, but if I change the template to Protostar works nice

![screen shot 2016-05-17 at 6 36 36 am](https://cloud.githubusercontent.com/assets/11687106/15342916/9cd3804e-1c62-11e6-8feb-fa35842de2b9.png)

**Comment by mahagr** [comment]
I need a bit more information in order to track down this issue.

Did it work before updating Gantry to the latest, have it never worked in Gantry?

Also try latest CI build from the Gantry download page, it may already fix the issue.

**Comment by ComunicaViVe** [comment]
Thanks for you reply,

Actually I have 2 site running with JSN Uniform, one with Gantry 5.2.15 (Works fine and not updated) and the other with Gantry 5.2.16 (JSN Doesn't work). 

I have a open ticket in JoomlaShine too and told me: 

_The incompatibility comes from this template like js conflict, or something running in that template prevents the Uniform loading._

**Comment by mahagr** [comment]
@w00fz Maybe you can take a look on it?

**Comment by JoomFX** [comment]
@mahagr If this is a G5 issue at all, it might be related to the exposed `G5.$` and `G5.ready` JavaScript utils that @w00fz implemented in 5.2.16

EDIT: You were faster :wink:

**Comment by mahagr** [comment]
The software seems to require login to access it. Join our gitter chat in https://gitter.im/gantry/gantry5 and PM me.

**Comment by ComunicaViVe** [comment]
How can I do to give you access on it? I have a open ticket in Rockettheme Forum but here I don't have a secure tab

**Comment by ComunicaViVe** [comment]
Ok ok sorry

**Comment by mahagr** [comment]
I'm getting:

    TypeError: $(...).select2 is not a function

On line:

    $("select.jsn-uf-select2-dropdown").select2();

The odd thing in the site I'm seeing is that all JavaScript gets loaded in the footer.

**Comment by mahagr** [comment]
It looks like downgrading Gantry has no effect, but it surely looks like some kind of js issue which only happens with Gantry template.

**Comment by w00fz** [comment]
The exposed $ and ready are namespaced so I doubt they are the caused. In fact, the whole main js from g5 is namespaced. The error above means you aren't loading the select2 plugin, or if you are it's too early, or your site is loading two versions of jQuery.
View the page source of the page, maybe paste the head if all is in there.

Kinda hard without a link to understand what's the issue.

// Djamil Legato // From iPhone //

**Comment by ComunicaViVe** [comment]
I sent you the URL

**Comment by w00fz** [comment]
This doesn't look like a Gantry issue but an ordering issue in the way the JS scripts order is been added.
Not quite sure what we can do there.

**Comment by ComunicaViVe** [comment]
But the problem with the Framework or Gantry Template because if I change to Protostar Template works fine

**Comment by w00fz** [comment]
I am not aware of anything with loading the JS frameworks that has changed in 5.2.16, are you using the same tempalte in 5.2.15 and 5.2.16?

What's happening is that the select2 plugin that JSN includes is not attaching to jQuery, this is probably because of the wrong ordering. So perhaps it is Gantry loading wrongly the js but this is not a JS conflict per se.

@mahagr ?

**Comment by ComunicaViVe** [comment]
Yes It is and I have another sites with JSN Uniform too

**Comment by w00fz** [comment]
Also for the records, that `$` error has nothing to do with Gantry and its exposed dollar, if you look at the file where the error is happening, it is an anonymous function:

```js
(function ($) {
...
$("select.jsn-uf-select2-dropdown").select2();
...
})(jQuery);
```

So, jQuery is still what's been called, we don't use jQuery in Gantry core

**Comment by mahagr** [comment]
Gantry isn't loading any JS, joomla is. Gantry does use Joomla to load some extra js files, depending on the template and particles you're using.

**Comment by ComunicaViVe** [comment]
Oh I see the issue

**Comment by ComunicaViVe** [comment]
the real problem is the Dropdown

**Comment by ComunicaViVe** [comment]
If I disable this, load the form

**Comment by w00fz** [comment]
Also your site is loading all the JS assets at the bottom of the page, that is not default Joomla behavior. Are you using some plugin to do that? It could be related.

**Comment by ComunicaViVe** [comment]
No just JSN Uniform

**Comment by ComunicaViVe** [comment]
![screen shot 2016-05-18 at 2 51 59 pm](https://cloud.githubusercontent.com/assets/11687106/15372021/2a103006-1d08-11e6-8a61-380a09bf57cd.png)

This is the $ in the dropdown

**Comment by w00fz** [comment]
I'm not too sure @ComunicaViVe, if you compare the page source between your Home page and the link you gave me, you can see that all the JS scripts are moved from the `<head></head>` (in Home), to the bottom of `<body></body>` (in the link you sent).

This is what I suspect being the issue, I am not sure what's doing it, it's not Gantry, and it's not Joomla default behavior, where everything renders in the `<head>`. Perhaps it's JSN doing so and somehow the order of the scripts gets messed up, causing the error.

Maybe try looking if there is a setting to avoid doing that.

Hope it helps.

**Comment by hennysmafter** [comment]
I have had this same problem having all js in body and by me it was because of wrong setup of JCH_Optimize.

**Comment by mahagr** [comment]
Looks like the issue has been solved in the site? What was it?

**Comment by ComunicaViVe** [comment]
Not solved, I just remove the dropdown

**Comment by w00fz** [comment]
What is this Dropdown? Is it part of JSN?
It does seem that removing it fixed also the ordering issue of your assets, they now load in proper order and at the top of the page, which makes the whole thing work as expected.

**Comment by ComunicaViVe** [comment]
Yes I a function in the form

![screen shot 2016-05-18 at 3 33 26 pm](https://cloud.githubusercontent.com/assets/11687106/15373147/e9edead0-1d0d-11e6-8152-02eee0b351e4.png)

**Comment by ComunicaViVe** [comment]
This dropdown is the problem or any dropdown in the form

**Comment by ComunicaViVe** [comment]
with RT template because in protostar load fine

**Comment by w00fz** [comment]
Well something in that is changing completely how the assets load in the page, it might be that you can only see this in RT templates but it could also be the same for other template clubs.

I would contact the JSN Uniform authors and point them out about the behavior of the assets loading at the bottom of the page when you use the dropdown, as opposed to regularly load at the top in the had when you do not use the dropdown.

This to me seems an issue with that extension and not Gantry related. We aren't really doing anything with loading assets except calling core Joomla methods to load them, we do not any manipulation to move them between head and body and just let Joomla handle it.

As I said above, it seems to me that whatever triggers that Dropdown also causes rendering the assets in a different way than the default joomla behavior.

Hope it helps.

**Comment by ComunicaViVe** [comment]
Thanks a lot guys for ur timely response, I summit another ticket to JoomlaShine again and I will give u the feedback

**Comment by w00fz** [comment]
@ComunicaViVe confirmed on Gitter that he was able to resolve the issue and it is related to the dropdown utility of JSN. 
I am now going to mark this issue as resolved.

Cheers
