### ISSUE TITLE
Feature: Publish / Un-publish block/section

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1294]
I think it would be nice if there was a button to quickly publish/unpublish a section or block, instead of having to remove the block completely from the layout. Unless if there is already this feature somewhere and I am missing it.

**Comment by w00fz** [comment]
If you disable the particle, through the toggle, it won't show up, and you wouldn't need to remove it 

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
Did that help?

**Comment by joomlabeat** [comment]
since my post here, I haven't work with it at, but I guess it will work... me silly didn't think of the particle's toggle...
thanks
