### ISSUE TITLE
Wordpress, title and content

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1296]
Well I'm with a certain difficulty, let's see if I can say what I want to do
I would like to display the title of the current page in a section, and the content of that page in another section.
So I have to handle both completely independently.
the particle (Page Content) displays the two things together, I want to have the two separated.
this is of great help and interest of many I think!

**Comment by w00fz** [comment]
I don't think we have an easy way to grab the title of the page, however this should be achievable by creating a customized particle, then you could use the regular Page Content particle for the body with some CSS to hide the title.

This is a bit beyond the scope of Github issues, you will probably have better luck on the Gitter chat.

**Comment by newkind** [comment]
Hi,
You can try something like :

```
{% set posts = wordpress.call('Timber::get_posts') %}
{{ post.title }}
```
Haven't tested it but might work as `Timber::get_posts` should call the current query.

**Comment by astenio** [comment]
Congratulations, and thank you very much!
His solution was flawless, it was through posivel better customization of the project, and also discover things that are not found in the gantry 5 documentation about the wonderful particles, but I will leave here the final result to someone you need to use.

1. file particle title.html.twig

![](http://img.prntscr.com/img?url=http://i.imgur.com/K0i5cHL.png)

2. file particle title.yaml

![](http://img.prntscr.com/img?url=http://i.imgur.com/EJi34z4.png)

I did a test, in line 3 of the second file, altered "type: particle" to "type: system", it continued working, but when trying to apply the formatting of the "Block" tab block, even the tab options accepting these formats are not rendered so by changing back to particle, everything worked perfectly.

**Comment by newkind** [comment]
Glad it works :)

**Comment by mahagr** [comment]
System type is reserved, which is why it might not have worked properly.
