### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by frontado** [gantry/gantry5#1297]
Please help. I am having this error:  **Call to a member function isCompatible() on a non-object in /home/servisoft1/public_html/wp-content/themes/1g5_hydrogen/functions.php on line 21**

That was after trying to modify logo image.

Please help. How can I fix it. I have no access to wordpress and website.

**Comment by w00fz** [comment]
Sounds like you are using a modified version of hydrogen that is not synced with the current hydrogen.

**Comment by frontado** [comment]
And how can I fix it?

**Comment by frontado** [comment]
I cannot even enter to wordpress

**Comment by frontado** [comment]
This is my URL: http://servicargamiami.com/

**Comment by w00fz** [comment]
Did you modify the Hydrogen template yourself? Best way is to grab the latest version from gantry.org and do a comparison between the one you have installed and the one you downloaded.

**Comment by frontado** [comment]
I fixed it. I renamed theme folder name and I got access to dashboard again. Thanks anyway!

**Comment by w00fz** [comment]
👍
