### ISSUE TITLE
Styling of the default Joomla Menu module

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#130]
It is really not a big deal and probably you've done this intentionally but anyway...

Currently, you cannot make a difference between the Top Level Menu items and their children. Probably it will be better if you put some margin-left to the `ul.nav-child` element or to the `ul.unstyled` element as it was in G4:

```
ul.menu ul.unstyled {
    margin-left: 25px;
}
```

Here's a [screenshot](http://i.imgur.com/AV7iGsD.png)

**Comment by kevlardev** [comment]
Fixed in fef71efde8510d941dae891278492bbae74d1b37
