### ISSUE TITLE
Hydrogen issue with Timber, Wordpress, Virtual Local Debian Jessie 

### ISSUE THREAD

**Issue by Cicorione** [gantry/gantry5#1300]
Hi to all, I am not a dev and this is my first time on Github so I don't know if I am doing well or not.

I am trying to learn your amazing framework on a Virtual Debian Lamp Stack, has been a little bit difficult for me set up the LAMP stack and Wordpress (in network mode) to work in local, when I finished I installed in order: Gantry 5, Timber plugins and the Hydrogen theme.

When I active the these plugins and assign the Hydrogen Theme on a test blog I am unable to go to the Dashboard, I get a weird screen  with this issue:

```
RuntimeException (500)
UniformResourceLocator: Absolute stream path with relative lookup not allowed () 
```
And other information like these:
```
Environment & details:
GET Data
activated 	true
POST Data empty
Files empty
Cookies
wordpress_test_cookie 	WP Cookie check
wp-settings-time-1 	1463761748
wordpress_dd7191e221d399a557f5030d2498328f 	Debian|1463933326|d3SDYRnHWJIsPLXRDr3jyqwdoRU7VQyQqKZEmbgthjd|4f63157f40f3cdfb75f84fce1e9ac8118a026044aa0ed6d86af1f34a085632a7
wordpress_logged_in_dd7191e221d399a557f5030d2498328f 	Debian|1463933326|d3SDYRnHWJIsPLXRDr3jyqwdoRU7VQyQqKZEmbgthjd|8104f36748c450d2ef73a985e0bfe75fe69a4806228628710d0eb47404707af3
Session empty
Server/Request Data
SERVER_SOFTWARE 	Apache/2.4.10 (Debian)
REQUEST_URI 	/wp/blog02/wp-admin/themes.php?activated=true
REDIRECT_STATUS 	200
HTTP_HOST 	192.168.56.101
HTTP_USER_AGENT 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0
HTTP_ACCEPT 	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE 	en-US,en;q=0.5
HTTP_ACCEPT_ENCODING 	gzip, deflate
HTTP_REFERER 	http://192.168.56.101/wp/blog02/wp-admin/themes.php
HTTP_COOKIE 	wordpress_test_cookie=WP+Cookie+check; wp-settings-time-1=1463761748; wordpress_dd7191e221d399a557f5030d2498328f=Debian%7C1463933326%7Cd3SDYRnHWJIsPLXRDr3jyqwdoRU7VQyQqKZEmbgthjd%7C4f63157f40f3cdfb75f84fce1e9ac8118a026044aa0ed6d86af1f34a085632a7; wordpress_logged_in_dd7191e221d399a557f5030d2498328f=Debian%7C1463933326%7Cd3SDYRnHWJIsPLXRDr3jyqwdoRU7VQyQqKZEmbgthjd%7C8104f36748c450d2ef73a985e0bfe75fe69a4806228628710d0eb47404707af3
HTTP_CONNECTION 	keep-alive
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_SIGNATURE 	
Apache/2.4.10 (Debian) Server at 192.168.56.101 Port 80
SERVER_NAME 	192.168.56.101
SERVER_ADDR 	192.168.56.101
SERVER_PORT 	80
REMOTE_ADDR 	192.168.56.1
DOCUMENT_ROOT 	/var/www/html
REQUEST_SCHEME 	http
CONTEXT_PREFIX 	/wp
CONTEXT_DOCUMENT_ROOT 	/usr/share/wordpress
SERVER_ADMIN 	webmaster@localhost
SCRIPT_FILENAME 	/usr/share/wordpress/wp-admin/themes.php
REMOTE_PORT 	51741
REDIRECT_QUERY_STRING 	activated=true
REDIRECT_URL 	/wp/blog02/wp-admin/themes.php
GATEWAY_INTERFACE 	CGI/1.1
SERVER_PROTOCOL 	HTTP/1.1
REQUEST_METHOD 	GET
QUERY_STRING 	activated=true
SCRIPT_NAME 	/wp/wp-admin/themes.php
PHP_SELF 	/wp/wp-admin/themes.php
REQUEST_TIME_FLOAT 	1463763019.986
REQUEST_TIME 	1463763019
Environment Variables empty
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
```

I got there are some issues with the path of Wordpress, to create this Wordpress site I had to create the domain site in fallback as suggested by the Debian wiki:
```
/etc/wordpress/config-default.php (this is used as a fallback if no other file matches your domain name) 
```

Probably this is connected with the issue however I don't have idea how fixing it.
I hope you can help me, many thanks in advance.

This is the screenshot:
![screen shot 2016-05-20 at 12 52 06 pm](https://cloud.githubusercontent.com/assets/19494201/15435576/19414a38-1e8b-11e6-9b2c-0114db4ddbdf.png)

**Comment by mahagr** [comment]
The issue comes probably from configuration like you thought, or maybe if you have part of the site outside of the document root. Gantry uses streams to allow file overrides, but the streams general need to have relative paths in order to allow it to create URLs from those.

I've never tried to have global instance of WP; usually you just install it to your web root. For now I recommend you not to use globally installed WP, but install it like most people are doing.

**Comment by Cicorione** [comment]
Thanks for your reply, actually I am creating a new virtual debian lamp stack to install Wordpress manually to verify if the problem still persists.

**Comment by Cicorione** [comment]
I installed locally Wordpress without using the Debian Package and I was able to install Gantry plugins and the hydrogen theme. Thanks.
