### ISSUE TITLE
Issue when submitting a BreezingForm

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1303]
@mahagr Hey Matias,

One of our customers reported an issue when using [BreezingForms](https://crosstec.org/en/downloads/breezingforms-for-joomla.html) with Gantry 5.

As soon as the user tries to submit the form, the whole module position the form is published to gets corrupted and the following error message is shown:

```
Error while rendering position.
```

The issue is reproducible with Hydrogen as well.
Have a look at [this video](https://youtu.be/asq2Ml9EPUk), it shows everything.

What could be causing the issue? I guess the action that BreezingForms perform when submitting the form is in conflict with the way Gantry 5 renders the module positions.
Currently, because of that issue, BreezingForms cannot be used with Gantry 5.

Thanks for looking it this ;)

**Comment by mahagr** [comment]
Duplicate of #1301
