### ISSUE TITLE
Button.html.twig bugs

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1308]
`gantry5/platforms/common/templates/forms/fields/button/button.html.twig`
Bug 1: line 8
Endif, but no starting if. **Fatal Error**
Maybe there was an intention to put something like this? `{% if field.type is defined %}`

Bug 2: line 13
Unneeded closing curly bracket.
currently: `{% if field.icon is defined %} }`
should be: `{% if field.icon is defined %}`

**Comment by marktaylor46** [comment]
It doesn't look right to me either...
I think the path in full is:
/administrator/components/com_gantry5/templates/forms/fields/button/button.html.twig

**Comment by nikola3244** [comment]
This is the full path in the repo - on GitHub.  :-)

**Comment by nikola3244** [comment]
This code fixes those two bugs and improves icon and it also adds check for button text.
```{% extends 'forms/' ~ layout|default('field') ~ '.html.twig' %}

{% block input %}
    <button
            {# required attribute structures #}
            name="{{ (scope ~ name)|fieldName|e }}"
            {# non-gloval attribute structures #}
            type="{{ field.type|e }}"
            {# global attribute structures #}
            {{ block('global_attributes') }}
            >
        {% if value is defined and value != "" %} {{ value|e }} {% else %} {{ field.value|e }} {% endif %}
        {% if field.icon is defined %}<i class="{{ field.icon|e }}" aria-hidden="true"></i> {% endif %}
    </button>
{% endblock %}

**Comment by mahagr** [comment]
Looks like we're not using button anywhere. Should be really easy to fix, though! Thanks!

**Comment by w00fz** [comment]
@nikola3244 could you make a PR for it?
