### ISSUE TITLE
input.imagepicker failed to open dir

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1311]
CI Build/ Version: dev-774abcc56 / Released: May 25, 2016
`Oops, DirectoryIterator::__construct(/home/ubuntu/workspace/gantry-media:/): failed to open dir: No such file or directory.`

**Comment by newkind** [comment]
@w00fz same stuff @hexplor had

**Comment by newkind** [comment]
@adi8i how do you exactly reproduce it

**Comment by adi8i** [comment]
Just add `input.imagepicker', I encountered this in a particle, I haven't tested in admin, but I guess is the same.

**Comment by adi8i** [comment]
Almost there ;).

`The filename, directory name, or volume label syntax is incorrect. (code: 123).`

Now the modal is opening but you get `500 Internal Server Error` when you click a folder.

**Comment by w00fz** [comment]
Can you give it a try now @adi8i ? It should be fully working again.

**Comment by adi8i** [comment]
Cool, works fine now.

**Comment by w00fz** [comment]
Thanks
