### ISSUE TITLE
Suggestion: add warning message to Gantry 5 admin when there is no default template set

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1316]
I've seeen many times in Gantry 5 based sites that somehow users get themselves into a position where there is no "default" (starred) template in Joomla template manager. Once in this state it can cause errors in many places such as:

1. Roksprocket fails to find correct layout (e.g. strips layout pagination to pages other than first stops rokbox working).
2. 404 not found when opening Gantry 5 particle module (where particle exists in what should be default template).
3. adding a new Gantry 5 particle module only see particles that are in core Gantry 5.

Suggested warning message:
"Warning: You do not appear to have a default template(starred) set in Template Manager"

Example screenshot:
![2016-05-28_10-06-01](https://cloud.githubusercontent.com/assets/11683218/15626454/2bea30a4-24bd-11e6-80e3-5556c492acb6.png)

**Comment by mahagr** [comment]
Yes, this seems to be common in multi-lingual Joomla sites.
