### ISSUE TITLE
[Wordpress] Custom post type / Advanced Custom fields -  Assignments

### ISSUE THREAD

**Issue by n8115** [gantry/gantry5#1317]
I'm having an issue attaching a "custom post type" to an assignment.

I created a new custom post type (using the CPT UI plugin), and now  have a "Publications" post type in my admin left sidebar, everything is working great except that I can't assign paginated pages to the Outline, only the archive page. 

Under assignments, I see no option to assign to the post type, I just get a list of all of the individual "Publications" posts.

I'm assuming if I turn categories on in the post type I can attach each post to a category and assign the section to that category, but I'm looking for a way to have them automatically attach as I don't want to have to worry about my client and their staff forgetting about that step. 

I also noticed there's a spot in assignments that was created after I installed Advanced Custom Fields called "Field&nbsp;Groups" - but selecting any of those options doesn't actually connect to the pages those custom fields are attached to. I'm assuming gantry just isn't compatible with ACF?

**Comment by mahagr** [comment]
Looks like you already found #1298.
