### ISSUE TITLE
Page Settings > Tooltip / Notes

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1318]
5.2.18, PHP 7

2 minor issues:

## 1)

The Tooltip on the Head Properties > Custom Content lacks the word "<head>" -- its in the code, but it doesn't render.

`<span data-tip="Anything in this field will be appended to the <head>" data-tip-place="top-right" aria-label="Anything in this field will be appended to the <head>" data-title="Anything in this field will be appended to the <head>">`

![image](https://cloud.githubusercontent.com/assets/8940155/15654016/006f5ea8-264e-11e6-91b9-87cc1d17fd6f.png)

## 2)

Grammar/confusion on the New Item Notes that seem to be shared by both Assets and the Custom CSS/JS Atom

JS

Please note that inline JavaScript code should be stripped out of <script></script> tags as Atom is automatically adding them.

CSS

Please note that inline CSS code should be stripped out of <style></style> tags as Atom is automatically adding them.

Proposed changes:

**Assets > CSS > New Item**

Please note that inline CSS code should be stripped out of `<style></style>` tags as Assets will automatically add them.

**Assets > JS > New Item**

Please note that inline JavaScript code should be stripped out of `<script></script>` tags as Assets will automatically add them.

---

**Atom > CSS > New Item**

Please note that inline CSS code should be stripped out of `<style></style>` tags as the Atom will automatically add them.

**Atom > JS > New Item**

Please note that inline JavaScript code should be stripped out of `<script></script>` tags as the Atom will automatically add them.

**Comment by w00fz** [comment]
Thanks!
