### ISSUE TITLE
Missing pre-defined layout denies access to WP admin

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1319]
When one of the pre-defined layouts are missing ie. `_body_only` Whoops throws an exception locking out both WP admin and frontend, making it hard to switch theme or do anything in the admin without manually changing current theme.

`RuntimeException (404)
Preset '_body_only' not found`

Replicate steps :
Make sure your theme is linked and then just move `common` out of theme directory to some other place and try to access WP admin.

**Comment by nikola3244** [comment]
Something like this? :smile:

**Comment by mahagr** [comment]
Well, no, I wouldn't do it in there as the code isn't WP specific. Besides the same issue seems to be in Joomla and others.

This issue happens because of broken installation and there are a few other things that can be broken as well. So the fix has to be a bit different than this.

**Comment by nikola3244** [comment]
I know that it's not WP specific, that's why I have put `function_exists()`.
You are right, and you know Gantry core better than me. :)
