### ISSUE TITLE
can't drag more than 1 menu item into newly added menu columns

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#132]
i've added a 2nd and 3rd menu column and was able to drag and drop one menu item into each one.
trying to drag and drop further menu items into those though, does not seem to work.

![g5_menucolumns](https://cloud.githubusercontent.com/assets/5719486/7359658/75722e10-ed06-11e4-83db-6b0066911902.jpg)

**Comment by w00fz** [comment]
You can but you have to hover over the text `Contacts` or `Coming Soon`, by just dragging over the gray area won't work. This is a known issue like explained in #108

**Comment by kat05** [comment]
ah right, feel free to close this one then. :)

**Comment by w00fz** [comment]
I'll keep it open as a reminder for when I figure out how to best handle this :+1:

**Comment by mahagr** [comment]
Just an idea: could we target to the flex box instead of the inner div/list of items?

**Comment by w00fz** [comment]
5 months later... this should be now fixed :dancer:
