### ISSUE TITLE
Outline assignments page has too many fields in it

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#1320]
See #1279 for earlier discussion.

Outline assignments page grows really huge, especially in WordPress where each post and page have their own toggle. In Joomla large multi-language sites on the other hand have a lot of menu items.

We must radically reduce the amount of data in this page by introducing pagination and filtering.

**Comment by w00fz** [comment]
I'd rather keep that other issue reopened since all the discussion is in there.
