### ISSUE TITLE
Add priority field for JS Assets and custom CSS/JS atom JS.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1321]
Although you can set priority of JS loaded in TWIG files there is currently no way of specifying this for JS loaded as an Asset on the "page settings" tab of an outline OR the custom CSS/JS atom.

I suggest we add a new field to both of these to allow priority to be specified with a default value pre-filled.

**Comment by marktaylor46** [comment]
Ok I can see this is added for the atom - but what about the page settings js asset??? can't we do the same there too?

**Comment by mahagr** [comment]
There.

**Comment by marktaylor46** [comment]
super :)
