### ISSUE TITLE
Widgets::listWidgets error

### ISSUE THREAD

**Issue by horch004** [gantry/gantry5#1323]
Hi,

When a widget does not provide a description (like a Download Manager category widget) and I turn on the PHP error_reporting the function Widgets::listWidgets fails and the widgets get a message 'Error while rendering widget'.

When error_reporting is off, the widgets are displayed fine. So, its not a very big deal.

I solved it for now by changing the code to: 'description' => (isset($widget->widget_options['description']) ? $widget->widget_options['description'] : '')

File: gantry5/src/classes/Gantry/WordPress/Widgets.php

**Comment by w00fz** [comment]
Thanks, your fix is what I also applied.
