### ISSUE TITLE
"About" not working in WordPress (404)

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1324]
How to reproduce:
Open any Gantry template in WordPress, click on About
![screenshot_2016-05-31_22-02-14](https://cloud.githubusercontent.com/assets/15911110/15711035/a6e73250-280c-11e6-8f47-606285481e8e.png)
And you will get this:
![screenshot_2016-06-01_15-13-22](https://cloud.githubusercontent.com/assets/15911110/15711039/acd1f0f6-280c-11e6-8424-525ed5478786.png)

No error in Joomla.

Line that is returning the 404:
https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Admin/Controller/Html/About.php#L24

**Comment by w00fz** [comment]
This seems to work fine for me on my local development (CI Build)

**Comment by nikola3244** [comment]
@w00fz Very strange.
I just downloaded fresh WP (4.5.2) and latest CI build (dev-2a6e65ddf).
It is not working.

**Comment by w00fz** [comment]
Ok I get it too with the latest 5.2.18 and CI Build, it works in my local because I have a symbolically linked setup.

**Comment by w00fz** [comment]
Ok fixed now 😃

**Comment by nikola3244** [comment]
I think I have a better solution :wink:

**Comment by w00fz** [comment]
The parent reference was wrong though. We used to have `hydrogen` in Wordpress but then the folder was renamed to `g5_hydrogen`.

**Comment by w00fz** [comment]
That actually is better. Can you PR?
