### ISSUE TITLE
Ethereal won't show Gantry update

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1327]
Running Ethereal 1.2.4 on J351 at Gantry 5.2.13 and the 5.2.18 refuses to show. I've repeatedly Cleared Cache -> Find Updates and it still doesn't see the 5.2.18 update.

**Comment by w00fz** [comment]
Didn't you have the same issue in #1241 ?

**Comment by w00fz** [comment]
This seems just to be a Joomla issue and nothing much we can do about it.
