### ISSUE TITLE
Bootstrap: Table has always a border

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#1330]
When I recompile a theme,  there is always an border around a table

```
table{border:1px solid}
```
The table should have no borders, if you want to use a border, then you need to use table-bordered like bootstrap.

**Comment by w00fz** [comment]
Are you sure that's Gantry and not your CSS?
This is all I could find in nucleus about table: https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/scss/nucleus/_core.scss#L212-216

No borders specified

**Comment by w00fz** [comment]
Ok seems like you are referring to Hydrogen theme specifically and not Gantry Core (https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/common/scss/hydrogen/_tables.scss).

I disagree that we should remove the border, it's a theme design decision, any template can be handling tables however they like, with border, with no border, with 3px border, really this is beyond Gantry's scope.
It so happen that Hydrogen ships with 1px border based on `$base-border-color`, if you don't like that you can always tweak it via `custom.scss`.

**Comment by 810** [comment]
yes referring to Hydrogen theme, 

I just suggest to rename the class, like bootstrap is doing.

**Comment by w00fz** [comment]
Care to explain why this should be needed?

**Comment by 810** [comment]
Example, i added an option to our Kunena templates. 
To show or hide the table borders. But on Hydrogen its now always displayed. So the users need to add custom css to hide the lines.

**Comment by w00fz** [comment]
I think this should be handled by the Kunena templates. So if the option is enabled, the Kunena templates forces a border, otherwise removes it.
Changing this in Hydrogen is not guarantee the Kunena templates to always works, it would just make it work for Hydrogen and we would have a breaking change.
Like I said earlier, this is not Gantry core but a template specific style. Some other templates might always force a no-border table, in which case your option to show it wouldn't work either.

See what I mean?

**Comment by mahagr** [comment]
I agree on @w00fz when it comes to our layout, but in Joomla we have 2 modes: Nucleus and Bootstrap 2.3. I think that we should add a rule into our `bootstrap-gantry.css` file to not to add borders while we are displaying a Joomla component or module.

**Comment by w00fz** [comment]
The problem is you cannot do this from bootstrap-gantry, the border comes from the Hydrogen theme.

![contacts 2016-06-06 11-19-56](https://cloud.githubusercontent.com/assets/11734/15832785/a0dfaf52-2bd8-11e6-97fc-d969d5f0276c.png)

**Comment by mahagr** [comment]
Is it possible to easily override that border rule in `bootstrap-gantry.css` without messing up bootstraps table classes?

```html
<table class="table table-striped">
```

Bootstrap always require you to use `.table`, so we could just override border in that rule?

**Comment by w00fz** [comment]
Any update on this?

**Comment by mahagr** [comment]
I have an idea how to fix this, so setting it to the milestone.
