### ISSUE TITLE
Fonts: Failed to load resources 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1331]
WordPress
Gantry: Version: dev-94549727c / Released: June 3, 2016

Fonts are loaded but I get lot of errors in console.

On localhost
![local](https://cloud.githubusercontent.com/assets/9744973/15799107/b8dcdfdc-2a5a-11e6-9eba-48cab9b8d1cd.PNG)

On C9 - Https
![c9-https](https://cloud.githubusercontent.com/assets/9744973/15799111/c1b37d96-2a5a-11e6-8d71-6b77fe83e345.PNG)

**Comment by w00fz** [comment]
Woff2 is new in the latest scss we are now using. You quite likely don't have the files. Should probably silently fail though, if the resource is not found.

// Djamil Legato // From iPhone //

**Comment by adi8i** [comment]
I added woff2 files and it works fine, thanks :D

**Comment by w00fz** [comment]
:+1:

**Comment by w00fz** [comment]
Actually, looking at the code, that error is on purpose to let the user identify the missing font file format. When using local fonts it's now required with bourbon to also provide the woff2 version.

**Comment by adi8i** [comment]
I got the error form first image, even if woff2 is added on php 5.6, sounds like an issue or ?

**Comment by w00fz** [comment]
What is the path exactly that errors out? You sure you have the woff2 in that folder?
And also, did you recompiled CSS in Base?
This should definitely work

**Comment by adi8i** [comment]
`Mixed Content: The page at ... was loaded over HTTPS, but requested an insecure font 'gantry-theme://fonts/roboto/roboto_medium_macroman/Roboto-Medium-webfont.woff2'. This request has been blocked; the content must be served over HTTPS`

Note `'gantry-theme://`.

Gantry: Version: dev-b67903a3f / Released: June 4, 2016

**Comment by w00fz** [comment]
Yah when it's `gantry-theme://` it means the file (`roboto/roboto_medium_macroman/Roboto-Medium-webfont.woff2`) in `../theme/custom/fonts` or `../theme/fonts/` doesn't exist.
Which is weird if you say it's there.

**Comment by adi8i** [comment]
![capture](https://cloud.githubusercontent.com/assets/9744973/15868602/3aa2ca66-2cf1-11e6-812a-d7a140b9f6e4.PNG)

**Comment by w00fz** [comment]
👍
