### ISSUE TITLE
Creating new outline throw "500 Internal Server Error"

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1334]
Gantry: Version: dev-b67903a3f / Released: June 4, 2016

When you try to create a new outline is created only the `folder` and `index.yaml`, `layout.yaml` is missing.

https://github.com/gantry/gantry5/blob/develop/platforms/common/templates/layouts/outline.html.twig

**Comment by JoomFX** [comment]
Adi, is that in WP?
I cannot reproduce it in Joomla (with the CI build)

**Comment by adi8i** [comment]
Hey, yes it's on WordPress, I haven't tried on Joomla.

**Comment by MisterAttrition** [comment]
Hello. I am also having this problem on wordpress. Is there an easy fix here?

**Comment by mahagr** [comment]
This issue was fixed back in 2016 so yours must be something else. Please make sure you have the latest version of both Gantry and the theme and report a new issue if the issue still persists after upgrading.
