### ISSUE TITLE
Home layout problem - slideshow and menu not working

### ISSUE THREAD

**Issue by skatercorpse** [gantry/gantry5#1335]
Hi there,

I am facing a problem with gantry5, Hydrogen template.

Using the Home layout on the home menu item the slideshow module does not show up (I am using the SimpleResponsive Slideshow. But I also copied the Slideshow particle from Ethereal template and it does not show up as well).
No matter in which module position and section I place it.

I have also installed a particle and atom for a sticky menu and it also does not work with the Home layout.

Everything work fine with the Hydrogen Default layout in the other pages (slideshow, sticky menu).
I also tried to apply the Hydrogen Home layout to another menu item, and it works!

"home" menu item is a "Gantry5 themes custom page" type.
The other menu items are articles.

I have no clue what it could be the problem.

Anybody can help me?

Thank you!

**Comment by mahagr** [comment]
Maybe the slideshow is assuming that some JS/CSS is loaded even if its not. In page settings of Home outline, try if adding `JavaScript Frameworks` atom and selecting jQuery + Bootstrap helps.

**Comment by mahagr** [comment]
Another way to make it to work is just to do what I said above, though the real issue is in the module which doesn't properly tell that it needs jQuery/Bootstrap. Its the modules responsibility to do that, even if Protostar happens to do that out of box.

I'm closing the issue as solved.
