### ISSUE TITLE
Gantry update notice on CI build in WP admin

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1338]
When theme is set to require a newer (unreleased version) of Gantry ie. 5.3 and we use CI build the error message still appears in the WP admin.

![helium theme helium wordpress sandbox wordpress 2016-06-06 21-28-41](https://cloud.githubusercontent.com/assets/1641534/15834890/e11eef2e-2c2d-11e6-9407-5f164df4bedb.jpg)

**Comment by mahagr** [comment]
Was just temporal clitch (opcache?)
