### ISSUE TITLE
Accessing current article from a particle

### ISSUE THREAD

**Issue by AdamWarnock** [gantry/gantry5#1339]
Not sure if this is a bug or not, but I didn't see anything about it not supposed to work in particles while browsing the docs.

I'm trying to render the title of the article the page is in a Custom HTML particle. Form the looks of it, it should just need to have the Process Twig and have  {{ article.title }} in the markup. If this isn't how it's supposed to work, then I need another way to add the article title to the particle.

**Comment by mahagr** [comment]
In Joomla modules and particles are not aware of the main content of the page, which means that there's really no reliable way to display title in a particle (or Joomla module).

You can try to load article manually, but its quite tricky as there are many variables in a play (menu item, request variables etc) which can alter the behaviour of the component.

**Comment by AdamWarnock** [comment]
So, there's not a way to just grab the article ID? Can you give an example of how to do this if the Menu Item ID is the same for several articles? Sorry, I'm trying to find a way to do this reliably since the alternative for how we have things set up is to do an outline for every single page, and that is obviously a major maintenance headache.

**Comment by mahagr** [comment]
You may want to check if someone has done a content aware module for this use from Joomla Extensions Directory.

In principle you can check if content comes from Joomla, view is for single article and grab the id, after which you load the article and display title. I'm not sure if its that simple or if you still need to take account the current menu item as well.

I have absolutely no idea if this works at all:

```twig
{% set request = gantry.request.request %}
{% if request['option'] == 'com_content' and request['view'] == 'article' and request['id'] %}
    {% article = joomla.finder('article').id(request['id']).language().find()|first %}
    {% article.title %}
{% endif %}
```

http://docs.gantry.org/gantry5/advanced/content-in-particles

PS. This issue is really out of scope of Gantry 5 support.

**Comment by AdamWarnock** [comment]
Sorry about that, still thanks for your help. I tried the code above and got an error, which is more than I was getting before.

Like I said, thanks for the help, and sorry about pestering you guys about this. :)

**Comment by mahagr** [comment]
Maybe @JoomFX would be interesting from a particle like this?

Yeah, I'm sorry that I cannot just use more time for this as I have new release (5.3) to make and still too much work to do.

**Comment by JoomFX** [comment]
Hey @AdamWarnock 

I'm not quite sure what you want to do.
Can you please give me some more details?

I do read all comments above and I read your first comment several times but I'm not exactly sure what you want to do. I understand that you want to show the article title, but when, where? Do you want to show the Article Title when you are on the article page/view ("Single Article" menu item)?
Just explain everything with as much details as possible :wink:

**Comment by mahagr** [comment]
Basically the idea is to have a particle that displays some of the data from the current article, like title, in another location (outside of the component). This has actually been already requested a few times for WP and @newkind has kindly instructed people how to do it (in WP this information is already available).

**Comment by JoomFX** [comment]
So it should take the current view, figure out what the article ID is and show it in a particle?

Of course, this is expected to work only on the Article Page, right?

**Comment by mahagr** [comment]
Yes, the above code displays nothing if you're not in article page... Well it would, if it worked. I just wrote it from my memory without any testing or looking into docs. So it may need some work, but is probably a particle a few people would appreciate. :)

**Comment by JoomFX** [comment]
Alright, I'm lost :smile: 

So, the following code works perfectly fine, it shows the Article ID when you are on the article page:

```
    {% set request = gantry.request.request %}
    {% if request['option'] == 'com_content' and request['view'] == 'article' and request['id'] %}
        {{ request['id'] }}
    {% endif %}
```

So I thought that it will be very easy to take the Article Title once I have the ID, but I was wrong. I tried everything I could think of, but nothing worked. In my opinion the following should work but it doesn't:

```
    {% set request = gantry.request.request %}
    {% if request['option'] == 'com_content' and request['view'] == 'article' and request['id'] %}

        {% set options = {id: [[request['id']]]} %}
        {% set article = joomla.finder('content', options).language().find() %}

        {{ article.title }}

    {% endif %}
```

Matias, can you have a look at it when you have time as I'm really interested in why we cannot take the article title (or anything else) once we have the ID. Most probably I'm just doing something wrong :smile:

**Comment by mahagr** [comment]
Finder always returns a list, so you need to grab the first article from that list. See my example from above.

**Comment by JoomFX** [comment]
Ha!
That's it! I was looking the the `|first` filter in your code many times but I thought that it is really not important since we are working with just one article, but obviously I was wrong. Now it works :smile: 

Let me review clean up my code a bit and I'll post it here together with the whole "Article Title" particle :wink:

**Comment by JoomFX** [comment]
@AdamWarnock Here you go. This is basically the code that Matias gave you, I just fixed some typos :wink: 

### Option 1
Use the following code in the "Custom HTML" particle (make sure you check "Process Twig" option):

```
{% set request = gantry.request.request %}
{% if request['option'] == 'com_content' and request['view'] == 'article' and request['id'] %}

    {% set article = joomla.finder('content').id([request['id']]).language().find()|first %}
    {{ article.title }}

{% endif %}
```

You can style the article title as you wish. For example, you can add H# tag to it - `<h2>{{ article.title }}</h2>`

### Option 2
Download the attached `article-title.zip` file and UNZIP it on your computer.
Copy the `article-title.yaml` and `article-title.html.twig` to `ROOT/templates/g5_hydrogen/custom/particles/`
The "Article Title" particle will now be available in the Admin.

[article-title.zip](https://github.com/gantry/gantry5/files/307416/article-title.zip)

**Comment by mahagr** [comment]
Thanks @JoomFX as I was too busy to take a look into it. I will keep this issue open as it may be handy to have imperoved version (with title/intro/images) of this particle available for users to play with it.

**Comment by AdamWarnock** [comment]
Thanks for the help. I wasn't expecting this and am really grateful that you did this.

**Comment by JoomFX** [comment]
@mahagr No problem at all, Matias!
You actually did everything, without your code I wouldn't be able to do it :wink: 

@AdamWarnock You are welcome mate :+1:

**Comment by mahagr** [comment]
Here is the same for WordPress:

https://github.com/GospelPowered/Gantry5/tree/master/Particles/WordPress%20Title

**Comment by mahagr** [comment]
Documented

**Comment by ShibumiDesign** [comment]
It is still beyond me that Gantry 5 has all these awesome particles that display manually entered content in a beautiful fashion, but no option to pull Joomla content and display it the same if it was manually entered into the particle.

I am using the RocketTheme Kraken template, and love the layout of the gridcontent particle, but I want to set it up to actually pull and display Latest Articles content from Joomla... [http://docs.gantry.org/gantry5/advanced/content-in-particles](url) says it's possible to pull joomla content into particles, but does not give clear direction on how to implement

**Comment by w00fz** [comment]
Check out the contentarray (Joomla Content) particle, that is a core particle that pulls content from the platform, joomla in your case.

You can apply the same logic to the grid content particle and create your own mix of the two.

**Comment by ShibumiDesign** [comment]
I have used that one, but I want to use the styling from the gridcontent particle like this:
![capture](https://cloud.githubusercontent.com/assets/2746226/17537369/0eb90802-5e6a-11e6-838f-df65b4423890.jpg)

But the particle cant pull joomla content, only manually configure it:
![capture2](https://cloud.githubusercontent.com/assets/2746226/17537371/0eb9aa64-5e6a-11e6-94d8-c3d4916872e2.png)

Default Joomla Articles (contentarray) particle
![capture3](https://cloud.githubusercontent.com/assets/2746226/17537370/0eb92f30-5e6a-11e6-8de5-7f83e22746bb.png)

As you can see, the gridcontent particle displays the content in a much nicer format, but having to manually update the particle each time the client adds new content is not going to work very well...

**Comment by w00fz** [comment]
My suggestion was for you to create your own particle where you get inspiration and context from both the Joomla Articles (contentarray particle) and the gridcontent particle.

This is not an issue, you are just wanting 2 different particles to do one thing. It is possible to do so but you need to create your own.

**Comment by ShibumiDesign** [comment]
I've been using Joomla for years, but I am relatively new to Twig and YAML processing... still, I'll read through the documentation for Gantry some more.

I guess I just was hoping for a system more like the RokSproket module that allows you to pick a content provider to do either manual input (Simple Provider) or pull content articles (Joomla Provider)

**Comment by w00fz** [comment]
Gantry has the capability to access the platform content data, just like RokSprocket and as you have seen in the Joomla Content particle.

The thing is that each Particle is its own independent entity, so if a Particle doesn't come with the ability to access the platform content because uses other means (like gridcontent that uses text and textarea fields), then the only solution to this is to create your own particle.

It's not that complicated, especially given that you have 2 particles that do exactly what you are looking for and you just want them merged into one.

Hope this helps!
