### ISSUE TITLE
Homepage reverted to default when changing PHP version

### ISSUE THREAD

**Issue by GeGeek** [gantry/gantry5#1340]
Platefrom: WordPress

Hello,

i am using cPanel with CloudLinux and PHPSelector.

I selected php7 and began working with Gantry.
For another reason, i tried to change the PHP version from 7.0 to 5.6.
After this, my homepage reverted to the default layout.
I checked the layout in admin, all is correct, like assignements too etc..

But other pages are showing the correct layout and content.

Do you have any idea ?

Thanks

Best regards

PS: If i revert to PHP7.0, all is working again :)

**Comment by w00fz** [comment]
This is known, every time you switch PHP version you also need to clear Gantry's cache, because the twig files needs to be regenerated.

**Comment by GeGeek** [comment]
Hello, thanks for the comment but after deleting cache from admin or ftp, the problem persist.

**Comment by w00fz** [comment]
I am a bit baffled by this one, it shouldn't cause these issues.
Any idea @mahagr ?

**Comment by mahagr** [comment]
We discussed about this issue a bit in Gitter chat and in the end I just had to raise my hands up: I have absolutely no idea what could cause this to happen.

In Joomla I would say that there is a plugin that overrides assignment, but in WordPress its all our own logic and there should be nothing that interferes with it.

@GeGeek Contact me again in Gitter, I think we may have a way to track this down.

**Comment by mahagr** [comment]
We solved the issue, but it seems to be a bug.

Front page had two outlines matching to it:

Home Outline:
* Front Page

New Outline:
* Front Page
* Home Page
* Pages / Home

In PHP5.6 the first outline got assigned where in PHP7 the second was assigned to the home page.

**Comment by mahagr** [comment]
cc @newkind

**Comment by GeGeek** [comment]
Thanks again :)
