### ISSUE TITLE
Hydrogen-Home template layout does not seem to match it's outline image

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#1343]
In Outlines, the outline image (id 10) of Hydrogen-Home template is slightly different than all the other Hydrogen outline images in that the Hydrogen-Home outline image seems to show a Nav section above the header, instead of under the header. Thus, the actual layout of Hydrogen-Home does not match it's outline image (id 10) as shown in Outlines.

**Comment by mahagr** [comment]
There are just a limited amount of images, which aren't meant to match the actual layout, but just give hints if it has sidebars available.
