### ISSUE TITLE
nucleus.css file is overriding media query classes?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1344]
![media](https://cloud.githubusercontent.com/assets/12814040/15880227/644f3ef0-2cf9-11e6-9ce4-58da29bd717a.png)

.visible-desktop class is not working due to this issue

```
.visible-desktop {
  	display: inherit !important;
}

.g-block.visible-desktop {
    display: block !important;
}
```
I don't understand the rationale for  above CSS. I am adding 'visible-desktop' class to a position particle, and it doesn't get hidden on mobile because of this.

A side question: I editted "media/gantry5/engines/nucleus/scss/nucleus/_utilities.scss" and remove that "!important", but the compiled nucleus.css doesn't get it even though I have "developement" on. And I tried "save styles" and "recompile css", it still doesn't get it. So how do I make change to these scss files under media/gantry5 folder?

**Comment by w00fz** [comment]
That change has been made over a year a go for #722 but I am not quite sure if this has changed during this time and with later versions of Joomla. I am a bit hesitant about just removing it. Will need some testing.

Regarding the overrides, check out the [override docs](http://docs.gantry.org/gantry5/advanced/file-overrides#gantry-directory-structure), what you want to do is create a custom file in `TEMPLATE_DIR/custom/engine`.

**Comment by newjie** [comment]
I have copied the whole nucleus to custom/engine, from the front-en, I can see the webpages are using nucleus.css file under custom folder, so I guess the override part is done correctly. However, although I editted the _utilities.scss file, the compiled css file still doesn't get the newly made modification. What is wrong?

**Comment by mahagr** [comment]
There is no automatic recompile for nucleus; you need to compile it manually by using the instructions provided in the Github readme.

**Comment by newjie** [comment]
I think this is definitely a bug. I set the .visible-desktop class on layout setting page for a particle, but the particle doesn't get hidden on mobile devices. Because it is ".g-block.visible-desktop"

**Comment by newjie** [comment]
By the way, since it doesn't get recompiled automatically, I am directly editting custom/.../css-compiled/nucleus.css, will this create problem in the future?

**Comment by w00fz** [comment]
Definitely, every Gantry update will override that. I would suggest creating a `custom.scss` file and just override the portions of CSS you want to be different.

http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

**Comment by newjie** [comment]
Don't you think this is too counter-intuitive for normal users who are used to how bootstrap worked in gantry4?

**Comment by w00fz** [comment]
We are trying to determine why this is a bug now, you are the first one who reported the issue so far and after over a year this was implemented. It is definitely an issue and we are looking at the best way to resolve it.

Overriding via `custom.scss` is not counter-intuitive, it's the way to go for customizing any CSS without the worry of losing your changes after a theme or gantry update.

**Comment by newjie** [comment]
About counter-intuitive, I mean adding "visible-desktop" class and expecting the element to be hidden but it doesn't.

**Comment by w00fz** [comment]
Yes like i said, this is an issue, we are trying to fix it.

**Comment by blizam** [comment]
I would think it would be fine/safe to change it in nucleus.css to:

@media (min-width: 980px) { 
.visible-desktop {
    display: inherit !important;
}

.g-block.visible-desktop {
    display: block !important;
}
}

which will keep it inline with how Bootstrap 2/Joomla might use it and won't override G5 template default settings for breakpoints... if breakpoints are changed in G5 though it could still conflict... maybe the responsive utility classes should be renamed?

**Comment by w00fz** [comment]
Add that to your `custom.scss` and you should be good.

**Comment by mahagr** [comment]
Well, I think the main reason for this change in the first place was to match Bootstrap responsive classes so that fields wouldn't disappear inside a single size range. This means that we should override all the breakpoints of Bootstrap or you will get a lot of issues if the breakpoints have been changed.

Obviously something must have gone wrong when these classes were added. One way to fix this is to remove the rules from Bootstrap file in Joomla, but in that case adding Bootstrap to WP would have miss-match on responsive ranges.

I guess that in Joomla it wouldn't hurt to get rid of Bootstrap CSS where it is same as in Nucleus.

**Comment by w00fz** [comment]
After some testing, I have decided to remove that extra `.g-block.visible-desktop {}` rule that seems to do nothing but just cause issues.

Thanks for reporting the issue.
