### ISSUE TITLE
No content on startpage

### ISSUE THREAD

**Issue by karbal1** [gantry/gantry5#1345]
Hello,
We made a new website using Gantry5 
When we go to the website the content of the homepage is invisible (category blog)
http://bit.ly/28jF9uy
Once you click on home everything seems to be oké...
http://bit.ly/25HZs2B
What could be the problem and how can we solve this?
Thanks!
Kind regards

**Comment by mahagr** [comment]
There seems to be 2 different home pages. Make sure that you set your `startpagina` menu item as the default one.

**Comment by karbal1** [comment]
Hello,
Thank you!!!
I have 2 different menu's... so I had to copie all the menu-items to a 3th, off-canvas menu to show as mobile-menu on phone...
that 's where it went wrong... stupid
:-)
Kind regards

**Comment by w00fz** [comment]
Glad it's resolved!

Very nice, clean and fresh mod of Hydrogen by the way!
