### ISSUE TITLE
Suggestion: Add padding space to alert messages

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1347]
On `scss\hydrogen-joomla\_utilities.scss`
I think it's a good ideea to add: `padding: $content-padding;` to the **.alert** class (line 20).
The final code would be:
```
.alert {
   background-color: lighten($warning-color, 41%);
   border-color: lighten($warning-color, 34%);
   padding: $content-padding;
   ......
}
```
What do you think ?

**Comment by adi8i** [comment]
![capture](https://cloud.githubusercontent.com/assets/9744973/15891588/ffcdd010-2d7d-11e6-970c-3b1193b34a91.PNG)

Alert looks fine. You posed on chat too something about alerts, still an issue? If so add a screenshot please :).

**Comment by mariantanase** [comment]
Yes, is still an issue.
Take a look on theese screenshots:

Without padding

​
With padding

​
I used the DIV tag, not the P

*************************************************************************************
Ing. Marian TANASE

*> web: http://www.tanase.it <http://www.tanase.it>*
*> google+: https://plus.google.com/+MarianTanase
<https://plus.google.com/+MarianTanase>> email: marian.tanase@gmail.com
<marian.tanase@gmail.com>*

* <http://it.linkedin.com/in/tanasemarian>*

2016-06-08 12:37 GMT+02:00 Adrian <notifications@github.com>:

**Comment by adi8i** [comment]
Yes, sorry I see it now, I tested on WordPress there works fine, on Joomla is a bug, I removed my previous comment.

**Comment by newkind** [comment]
Hmmm it's odd but it looks like Joomla version has the alerts styling set in `_utilities.scss` file inside of theme, where WP loads the alerts from the nucelus - not sure why it was made like that.

Can you try editing the `hydrogen-joomla.scss` file and replace this code :

```
// Load Theme Variable Driven Nucleus Elements
@import "joomla/theme/base";
```

with this :
```
// Load Optional Nucleus Assets
@import "nucleus/theme/alerts";

// Load Theme Variable Driven Nucleus Elements
@import "joomla/theme/base";
```

Please recompile the CSS after and see if they'll start to look properly. We might need to remove the alerts code from `_utilities.scss` and load them the same way we do in WP.

**Comment by mariantanase** [comment]
Perfect ! Thanks @newkind

**Comment by newkind** [comment]
Can you please post your results ? Does this solve it :)

**Comment by mariantanase** [comment]
Yes that solve it! 
![paddingok](https://cloud.githubusercontent.com/assets/3976174/15893888/deb0d7ce-2d82-11e6-9d59-d4a44296dce5.png)

**Comment by newkind** [comment]
Great, I'll compare the code and add the fix to Hydrogen.
