### ISSUE TITLE
Inherit vs Inheritance

### ISSUE THREAD

**Issue by gyvermac** [gantry/gantry5#1349]
I think that to be less confusing (with the new "inheritance") the word "inherit" in the section parameters should be change to something like " inherit from page settings"...

![capture d ecran 2016-06-08 a 18 42 40](https://cloud.githubusercontent.com/assets/11781634/15903228/e2ea3474-2dab-11e6-8c67-078b80fed355.png)

**Comment by w00fz** [comment]
Agreed, I like the idea of a more explanatory wording.
