### ISSUE TITLE
suggetion: display menu icon preview in popup dropdown at default size 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#135]
please see pic, i was wondering if the icon should be shown with a default size on the dropdown, otherwise it looks a little weird.
![g5_icondropdown](https://cloud.githubusercontent.com/assets/5719486/7361576/97963ecc-ed20-11e4-8876-ccc62c58e9cb.jpg)

**Comment by w00fz** [comment]
It really is meant to be previewing the way it's going to be displayed on front-end. The same goes for the Spinner, if you enable that option it will start rotating, exactly like it would on front-end.
I know it doesn't look good but it might help preventing the use of such large icons :)
