### ISSUE TITLE
Rename Base Outline

### ISSUE THREAD

**Issue by gyvermac** [gantry/gantry5#1350]
Joomla/ G5
A cosmetic bug.
It is possible to rename all outlines except "base outline" : that's OK.

But the edition icon is visible on "base outline" and if you try to edit the name you get a "403 forbidden" error.
I think it should be better to remove the edition button and prevent any change.

![capture d ecran 2016-06-09 a 08 46 16](https://cloud.githubusercontent.com/assets/11781634/15921026/dea18836-2e1e-11e6-9047-293bf140aee2.png)

**Comment by mahagr** [comment]
@w00fz @newkind Should we enable renaming base outline (title only) or just disable the editing?

**Comment by newkind** [comment]
Renaming could help with translating stuff but can also lead to confusion. What I'd actually do is to allow renaming but mark the Base Outline with asteriks or something so it would stand out.

**Comment by mahagr** [comment]
I think that base outline can already be translated (at least in most places). Maybe we should not only prevent renaming but add that asterisk into the name, though.

**Comment by w00fz** [comment]
This is purely a cosmetic issue that really nobody ever noticed until now, but still an issue.
We should just remove the edit icon and that's it. To keep it consistent with the Outlines page.
