### ISSUE TITLE
Can't make Slideshow particle work on WP

### ISSUE THREAD

**Issue by esencial** [gantry/gantry5#1351]
Hi there.

This is my first question here, so I apologize in advance if I'm not following some etiquette rule over here.

My question is addressed to @JoomFX, since he is the developer of the particle.

I'm trying Gantry 5 and I've installed the Slideshow particle and Ulkit successfully. Both @import are in place, I've added the particle to my Navigation area and loaded 3 items into it. The slideshow won't display properly. I can see the images, but they are shown one above the other, in a static manner.

I'm still using the defaults and think everything seems to be in place. I'm using WordPress 4.5.2.

Any clue?

Thanks in advance.

**Comment by JoomFX** [comment]
Hey @esencial 

According to the problem description (images loaded one above the other) I'm 99% sure that the "UIkit for Gantry5" atom was not loaded properly.

Watch [this video](https://youtu.be/dgJe06yCNeM) and make sure the "UIkit for Gantry5" atom is added (and enabled) in your "Base" outline :wink:

**Comment by gyvermac** [comment]
Seems that uikit-min.css is not load.

**Comment by esencial** [comment]
@JoomFX, it's solved. I just skipped the drag-and-drop step shown in the video; the atom was installed but not applied to the layout.

Thanks!

**Comment by JoomFX** [comment]
Great! I'm glad you figured it out :wink:
