### ISSUE TITLE
Adding items inside particles settings

### ISSUE THREAD

**Issue by Trust7** [gantry/gantry5#1354]
Is it possible to make a particle where You can add multiple items? Similary to "Custom CSS/JS Atom" or "Social Particle".

![customcssjs](https://cloud.githubusercontent.com/assets/17771389/15985950/d6d64134-2ffc-11e6-90c9-77fc37944b5e.jpg)
![social](https://cloud.githubusercontent.com/assets/17771389/15985951/d6d67686-2ffc-11e6-9f33-18d431fdf93c.jpg)

For example I would like to make a slider where the client could add images on his own. I would make a particle that would contain the slider code and in the settings (admin panel) there would be a possibility to add new items which would contain the image path and maybe some other information. By adding an item inside the particle it would for example create a DIV and IMG. That way I could have a particle which would contain DIVs needed for the slider to work and the images wouldn't be hard coded.

**Comment by gyvermac** [comment]
Yes it's ! You can even find a good free example here : http://www.inspiretheme.com/documentation/gantry5-particles/slideshow

**Comment by Trust7** [comment]
That's great! Thanks :-)
