### ISSUE TITLE
Joomla Articles Particle inherited properties

### ISSUE THREAD

**Issue by ajduke2** [gantry/gantry5#1355]
If I open the configuration window for the Joomla Articles particle then several of the properties are always showing the override field checkbox ticked, even if I untick them and save then when I open again they become ticked again. This makes it difficult to pick-up settings from the particle defaults. Is it a bug?

**Comment by mahagr** [comment]
Gantry unsets the settings if they are identical to the default settings. So you need to change the settings in order to get them saved.

**Comment by ajduke2** [comment]
I have changed the settings in the Particle Defaults of the Base Outline, so I shouldn't need to also make the same changes in the particle itself should I? At the moment several of my settings are overridden if I go into the particle and just click save, surely if a setting is changed at a lower level then the particle should pick those settings up unless they were specifically overridden.

Particle Defaults of the Base Outline:
![screen1](https://cloud.githubusercontent.com/assets/19416678/16019414/cacca676-31a0-11e6-9846-b78b608a59fd.png)

Particle settings:
![screen2](https://cloud.githubusercontent.com/assets/19416678/16019427/d69fdea0-31a0-11e6-9ee4-805c5720ca2d.png)
(override checkbox is ticked even if I unticked it last time)

Result:
![screen3](https://cloud.githubusercontent.com/assets/19416678/16019553/80a391da-31a1-11e6-967c-cb7b3810d438.png)

**Comment by w00fz** [comment]
You shouldn't be needing to manually update particles that are inheriting the settings from Base.
Are you running 5.2.18 or are you testing this on 5.3.0 CI Build?

**Comment by ajduke2** [comment]
I'm running 5.2.18

**Comment by w00fz** [comment]
I believe this should be sorted in 5.3 (check latest CI Build).
I tested and I could tick and unticked at my discretion, keeping its state from the last change even after save and after reload.

Please feel free to reopen if the issue persists, perhaps by providing a step-by-step way of reproducing the issue.
