### ISSUE TITLE
need more control on ".platform-content"

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1357]
In my experience, very often I need control over a "line" in a section instead of the particle(s) within the "line".
For example, I have 3 "lines" in "#g-above" section, I want the first line to hide on mobile view, I click the little cog and add "hidden-phone" class to the particle within the line, however, there will still be a blank space in the page. Why? Although the particle is hidden, but its container - the first line - is still there. In detail, the ".g-content" still have 3 ".platform-content"s, and the  margin and padding of '.platform-content'  is making the space. To hide it, I will have to do '.platform-content:nthchild(1){display:none}' in custom.css. I don't feel comfortable doing this, what if there are many "lines" in the section and I want to hide one of them? I think this is not very friendly to regular users.

So I think it will be wonderful if we can have a little cog for the "lines" too.

**Comment by blizam** [comment]
Grids are what they're called

http://docs.gantry.org/gantry5/configure/layout-manager#grids

I'd agree that it'd be nice to have some limited Settings on Grids... at least to add a CSS Class, maybe a tag attribute as well.

On the flip side, it's very easy to create Sections as well which give you all those features... you can duplicate your current layout's YAML file, add in a bunch of new Sections and load your new Layout, preserving your Particles... 

I'm not sure which (if either) would be more intensive on rendering on the front end... if there's anything that makes a Section more optimal than a Grid or vice versa.

**Comment by w00fz** [comment]
The grid (or row) can be styled via YAML file like @blizam said. We do not have any UI for it because it's a very rare use-case. We might consider expanding this when we are going to revamp our Layout Manager but for the moment you have to do it via YAML.
