### ISSUE TITLE
Buen día me salio el siguiente ERROR

### ISSUE THREAD

**Issue by topmentos** [gantry/gantry5#1358]
Warning: Invalid argument supplied for foreach() in /home/qj000044/public_html/wp-includes/plugin.php on line 678
Warning: Invalid argument supplied for foreach() in /home/qj000044/public_html/wp-includes/plugin.php on line 678
Fatal error: Call to undefined method Composer\\Autoload\\ClassLoader::setPsr4() in /home/qj000044/public_html/wp-content/plugins/timber-library/vendor/composer/autoload_real.php on line 33

ayudenme si a alguien le paso lo mismo, que pasos deberia hacer para poder solucionarlo.
por otro lado estoy utilizando wordpress

**Comment by mahagr** [comment]
Not a bug in Gantry; the error happens in Timber plugin. Though its not a bug in Timber either.

You have installed some very old plugin which uses old version of composer.
