### ISSUE TITLE
smart warning about pending changes will sometimes be replaced with the regular browser warning

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#136]
when changes are pending (have not been saved yet) the smart warnings are great to prevent users from browsing away from the page without prior saving. when clicking certain links though, for example any of the joomla admin menu links or 'platform settings' etc, then the smart warning will not show, instead the regular browser warning will be displayed, please see pics
![g5_smartmessage](https://cloud.githubusercontent.com/assets/5719486/7361750/dd749594-ed23-11e4-9cf9-86ee96f5647f.jpg)
![g5_notsmartmessage](https://cloud.githubusercontent.com/assets/5719486/7361751/dd74a2be-ed23-11e4-800d-f61437dc9445.jpg)

**Comment by w00fz** [comment]
Yes that is intentional. When you reload the browser or click links that take you away from the G5 admin I can only prevent the page from loosing changes through the *onbeforeunload* event which brings up that pop-up.

**Comment by w00fz** [comment]
As a side note, chrome handles this  better, looks much nicer there :)
