### ISSUE TITLE
Add new section to template

### ISSUE THREAD

**Issue by karbal1** [gantry/gantry5#1361]
Hello,
Is there a way to add an extra section to my template?
I have:
1. My navigation (full width flushed)
2. My content (full width boxed, white background)
And
3. A footer (full width flushed)
http://bit.ly/1UsuFmF
I would like to have my contact form full width (boxed) on a blue background.  Now I have it in the flushed  footer section and on 80%width but it doesn't align the same with the main content, that doesn't look very nice...
So, I think I need an extra section in between main content and footer?
Or is there an other solution to solve this?
Kind regards

**Comment by w00fz** [comment]
Other than styling via CSS with the limits that comes with, I'd just create an extra section and this is how you do it: http://docs.gantry.org/gantry5/advanced/creating-layout-presets#adding-a-section-to-an-existing-layout-preset

**Comment by karbal1** [comment]
Thank you very much!!!
Perfect!
