### ISSUE TITLE
Edit font of the menu

### ISSUE THREAD

**Issue by karbal1** [gantry/gantry5#1364]
Hello,

Is there a way to change the color from the fonts of the active menu without using css?
I can do that by changing the main font color but I want those to stay in a grey color and the active menu should become blue like the logo used for the website...

Thanks!

**Comment by JoomFX** [comment]
Hi @karbal1 

There is no such option in Hydrogen by default (and there really shouldn't be).

Changing the text color of the active menu and all other similar things are a design decision and should be handled by the user. You can easily do that by adding the following code in your [custom.scss](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) file:

```
#g-page-surround {
	.g-main-nav {
		.g-toplevel {
			> li {
				&.active {
					&:not(.g-menu-item-type-particle) {
						&:not(.g-menu-item-type-module) {
							> .g-menu-item-container {
								color: red;
							}
						}
					}
				}
			}
		}
	}
}
```

Make sure you "Recompile CSS" under the "Styles" tab in the "Base" outline so your `custom.scss` is picked up.

You can of course achieve the same by using a much simpler code, that does not take care of all the posibilities (having a particle or module published in the top level of the Main Menu). Just inspect the menu with Firebug or Chrome Inspect Element and you will figure it out. You can use this code for example:

```
.g-main-nav .g-toplevel > li.active .g-menu-item-container {
	color: blue !important;
}
```

**Comment by karbal1** [comment]
Thank you! Works perfect!
