### ISSUE TITLE
New outline card appears in wrong order

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1369]
When you create a new outline in the Outline admin page, no matter what name you type for it - it always appears next to the "Base Outline", so you need to refresh the page for it to appear in the proper place according to the alphabetic order.

**Comment by w00fz** [comment]
This is known and a change in 5.3. New cards always get added at the top now, we aren't refreshing the whole Outline page anymore. In future versions we are planning to add filters like Search and Sorting. But this is the behavior for now.

**Comment by mahagr** [comment]
It was changed because of previously when you added a new outline, you had to scroll down and find the outline before you could edit it. It is much easier to edit the new outline if its added to the top.
