### ISSUE TITLE
CIBuild: inheritance: Forever spinner when saving section settings.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1370]
I used Sienna for testing of Inheritance.

Steps to recreate this issue.
1. create two outline based upon "home positions" preset called "test1" and "test2" ensure both layouts are cleared.
2. Add a module position particle to the layout of "test1" outline in the "Top main" section and save the layout
3. Go to "test2" outline and on the "top main" section settings go to the inheritance tab. Choose "test1" outline to inherit and check all three include options and APPLY and SAVE
4. Again in "test2" outline layout open the "Top main" section setting and then uncheck the "section children" box and APPLY and SAVE
5. Drag the module position particle from the "top main" section to the "navigation main" section below and SAVE the layout.
6. now open the "top main" section settings again and recheck the "section children" checkbox and APPLY and SAVE - you then get a forever spinner and nothing happens.

![2016-06-18_17-27-39](https://cloud.githubusercontent.com/assets/11683218/16172202/1a9aad00-357b-11e6-81d4-696343227bf4.png)

**Comment by w00fz** [comment]
I cannot reproduce this one. For me when I finally recheck the children and Apply and Save, I end up with 2 Module Positions that look the same, as expected, and I could save it without infinite spin.

![edit test1 2016-06-19 23-30-18](https://cloud.githubusercontent.com/assets/11734/16185054/f4a0cc14-3675-11e6-8987-e7b8c126f71a.png)

**Comment by marktaylor46** [comment]
Here's a video of the issue I reported - I can reproduce this issue over and over. http://screencast.com/t/ADFAjjXvltat

**Comment by marktaylor46** [comment]
Ok Sorry I have now tried CI build and it seems fine... I didn't notice the commit before just saw the comment about not being able to reproduce... 

All good now :)
