### ISSUE TITLE
CIBuild: inheritance - module position key gets renamed without asking

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1371]
I used Sienna for testing of Inheritance.

Steps to recreate this issue.
1. create two outline based upon "home positions" preset called "test1" and "test2" ensure both layouts are cleared.
2. Add a module position particle to the layout of "test1" outline in the "Top main" section and save the layout
3. Go to "test2" outline and on the "top main" section settings go to the inheritance tab. Choose "test1" outline to inherit and check all three include options and APPLY and SAVE
4. Again in "test2" outline layout open the "Top main" section setting and then uncheck the "section children" box and APPLY and SAVE
5. Drag the module position particle from the "top main" section to the "navigation main" section below and SAVE the layout.
6. refresh the page.
7. now open the "top main" section settings again and recheck the "section children" checkbox and APPLY and SAVE. Now you will have the inherited module position in "top main" with it's original name and also the one we moved out to "navigation main" with the same name (which is as expected).
8. now just refresh the page - notice how the module position in "navigation main" get's it's ket changed to "positions-9999" without asking. It's fine to have the same module position key used multiple times on the page?

![2016-06-18_17-44-07](https://cloud.githubusercontent.com/assets/11683218/16172270/19c3e976-357d-11e6-924e-512f3043ca49.png)

**Comment by w00fz** [comment]
Yes you should be able to use the same position key multiple times in the same layout. This sounds like  a bug. Can you take a look @mahagr ?

**Comment by w00fz** [comment]
Also if after all the steps you then Drag and Drop a Module Position in Navigation and make it inherit from Test 1, it will properly inherit the position key `possy1` as expected from the one that instead gets a random key.

**Comment by mahagr** [comment]
This is actually a limitation of layout needing unique ids and our latest file format oversimplifying modules id. The issue happens also without inheritance, but inheritance does make the issue worse than it was before.

**Comment by mahagr** [comment]
Please test everything possible again as my change may have some side effects if I missed something.

**Comment by marktaylor46** [comment]
I just tried latest CI Build and this is not fixed for me? It still does exactly the same thing?

![2016-06-22_09-42-28](https://cloud.githubusercontent.com/assets/11683218/16260095/af410fa0-385d-11e6-8396-70ccbe77d21e.png)

**Comment by mahagr** [comment]
It may not break already broken layout (and I have no intention of doing that). 

But just in case I'm going to reopen it to have another round of tests. Maybe I missed some use case.

**Comment by marktaylor46** [comment]
Here's a video of what I am doing on latest build to show you the error: http://screencast.com/t/o7puknBsuR9

**Comment by marktaylor46** [comment]
notice also that although the key of the lower module position was changed that it is also still "striped" (i.e. apparently inheriting ????)

**Comment by w00fz** [comment]
Looking at your video, the key changing is still an issue, it shouldn't randomly change like that.
As for the Inheritance kept on the particle, that is correct. You never removed inheritance from that particle, you just moved it to a different location in the Layout.

**Comment by marktaylor46** [comment]
confirmed fix :)
