### ISSUE TITLE
Add warning to inheritance tab

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1374]
I used Sienna for testing of Inheritance.

Steps to recreate this issue.
1. create two outline based upon "home positions" preset called "test1" and "test2" ensure both layouts are cleared.
2. Add a module position particle to the layout of "test1" outline in the "Top main" section and save the layout
3. Add a module position particle to the layout of "test2" outline in the "Top main" section and save the layout
4. In "test2" outline "top main" section settings - inheritance. Change the setting to inheirt from "test1" outline and check all three boxes (so that children are inherited).

Notice how the module position that you created in step 3 has been deleted without any warning. I would have expected it to still be present but on a second row in that section? Or at the very least get a warning that I was about to wipe out my pre-existing particles in the section?

**Comment by JoomFX** [comment]
I think that this is normal, the expected behavior.
Since you are inheriting the whole section, I would expect that my section in "Test2" will be absolutely the same as the one in "Test1" (the one you are inheriting from).

But I agree that there should be a warning message that you will lose the existing particles.

**Comment by w00fz** [comment]
This is the intended behavior and the reason we have no warning is because you don't really lose your Particles, since you can always use the History (`Undo`, `Redo`) to revert the change if it was a mistake. Otherwise it would become a constant and rather annoying notice.

**Comment by marktaylor46** [comment]
Well I think an error message is warranted. If you check the "inherit child" (only when changing to this state) and there are already pre-existing particles in the section then I think there should be an error message "You already have other particles present in this section. By inheriting children you will lose these particles if your continue. Are you sure ?  YES NO". Otherwise the expectation would be that inherited particles would be added to the pre-existing particles in the section and this is not what happens.

**Comment by mahagr** [comment]
In that case I would just have short warning in the tab visible all the time, mostly because of any action you do in inheritance tab will kill the data you have entered before.

**Comment by marktaylor46** [comment]
Yeh I could live with that as we do that in other places too. :+1:

**Comment by marktaylor46** [comment]
if we could have that message only be visible if the "inherit children" box is check that would be cool too
