### ISSUE TITLE
All WordPress post are showing up in Assignments tab

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1375]
Like title says, when you go to Assignments tab, all posts show and that is a big problem on 3500+ posts site. 
I get page freeze and then crash.

It would be better if there is some sort of pagination.

I needed a temporary fix so I just modified this to 100.
https://github.com/gantry/gantry5/blob/develop/src/platforms/wordpress/WordPress/Assignments/AssignmentsPost.php#L119

**Comment by JoomFX** [comment]
@nikola3244 Hey Nikola,

Have a look at [this issue](https://github.com/gantry/gantry5/issues/1279).
I know that you are around lately so you might have already seen it :wink:

**Comment by nikola3244** [comment]
Thanks Ivo!
Closing this one.

**Comment by nikola3244** [comment]
Just found this one too #1320.
I really need to use search better... :sweat_smile:
