### ISSUE TITLE
AJAX for particles

### ISSUE THREAD

**Issue by MadaSociety** [gantry/gantry5#1376]
Hello,

After set posts page in the settings and assign outline to the page, I don't see the pagination at the top or bottom.
I use "**WordPress Posts**" particle for posts page and different category.

How add pagination for "Wordpress Posts" ? Thank you.

Best regards,

**Comment by newkind** [comment]
@w00fz @mahagr we would need to have an universal ajax solution to paginate the posts inside of the particle both for WP and Joomla, can we do something about it ?

**Comment by w00fz** [comment]
Yeah I think we need a solution like  we have in backend, so that also particles can benefit from this. Like being able to paginate a collection as needed.

**Comment by A-Kasaaian** [comment]
Hi, is pagination added to "WordPress Posts"?? I think it is essential.
