### ISSUE TITLE
Switching presets from the frontend doesn't recompile particle added styling

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1377]
When you add a CSS code from the particles twig file and you switch presets from the front end using `?presets=presetX` this piece of code doesn't get recompiled. Because of that it looks like theme is using two different presets at the same time. 

Would be awesome to fix this for Helium ;)

Sample code :
```
{% if particle.imageOverlay == 'enable' %}
        {% styles with { priority: -10 } %}
        <style type="text/css">
            #g-owlcarousel-{{ id }} .g-owlcarousel-item-img:after {
                background-image: linear-gradient(40deg, {{ gantry.config.get('styles.accent.color-1') }}, {{ gantry.config.get('styles.accent.color-2') }});
                opacity: 0.9;
            }
        </style>
        {% endstyles -%}
    {% endif %}
```

**Comment by mahagr** [comment]
This issue requires me to finish `feature/blueprints` branch first.

**Comment by mahagr** [comment]
```twig
{{  gantry.theme.presets[gantry.theme.preset].styles.accent['color-1'] }}
```

**Comment by w00fz** [comment]
Marking this as resolved since it was internally resolved in a different way, leaving the original request unneeded.
