### ISSUE TITLE
Inheritance: Do not allow outline to inherit sections from itself

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1379]
I've created a new outline in Hydrogen called Hydrogen - Test 2.

In the Layout manager I went to > Load > Outlines and selected the very same outline to inherit from and I could save the changes just fine.

Now my outline Hydrogen - Test 2 is actually inheriting from itself which should be prevented from happening.

Please see pics

![ci_inheritself1](https://cloud.githubusercontent.com/assets/5719486/16193826/7c77eade-36f1-11e6-8e7d-f142546dce57.png)

![ci_inheritself2](https://cloud.githubusercontent.com/assets/5719486/16193830/829992a0-36f1-11e6-8675-2a33d0026a36.png)

**Comment by w00fz** [comment]
We should probably just remove completely the same Outline. Even the copy + keep particles doesn't make much sense, one can simply reload.
