### ISSUE TITLE
Inheritance: Add option to clear inherited sections in layout

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1380]
In the layout tab, there is the 'Clear' button.

However, it will only clear out all sections that have their own settings and do not inherit.

It would be great to somehow also allow the clearance of anything that's inherited, possibly as an alternative option to the existing Clear function.

**Comment by w00fz** [comment]
This is now a dropdown where you can pick either or. 

![gantry 5 dev - administration 2016-06-21 17-19-14](https://cloud.githubusercontent.com/assets/11734/16250697/524d196c-37d4-11e6-912e-3fb5972a6a86.png)
