### ISSUE TITLE
Inheritance should be possible to set directly when creating new outline

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1386]
You should be able to select an Outline and select inheritance checkboxes in the "Create new Outline" popup. That way it's easier to set it up and we get rid of extra unnecessary step.

So these checkboxes and outline chooser :
![z6sibalclfgubvo7adqyp3ghbknwer](https://cloud.githubusercontent.com/assets/1641534/16235375/eff4a5ea-37d4-11e6-89fb-859d8ccc40b7.png)

Should be available also from this popup :
![uv3tdzfj692zr8qgjxqyxnrfb5cp2x](https://cloud.githubusercontent.com/assets/1641534/16235399/0f23a934-37d5-11e6-8408-b9d7abec6410.png)

**Comment by w00fz** [comment]
All the UI is implemented

**Comment by mahagr** [comment]
@w00fz I simplified UI for duplicate button, but it needs some changes in JS in order to work.

Also please send `1` and `0` instead of `true` and `false` as those are seen as strings by PHP.

**Comment by w00fz** [comment]
So needy 😃

**Comment by w00fz** [comment]
We should be all good here now.
