### ISSUE TITLE
CIBuild: inheritance: can't change inheritance when two particles of same type on layout

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1387]
This is really hard to explain in words... But basically this is the setup:
1. Create two outline "test1" and "test2" with completely empty layouts and have "test2" inherit the whole outline of "test1"
2. now in "test1" outline drag a "logo/image" particle onto the layout and save. you will see it is correctly inherited onto "test2" layout
3. Now go back to "test1" layout and edit the particle settings for that "logo/image" particle and you will see that you can still alter the inheritance for that particle (say to inherit from base outline) But don't make any changes.
4. Now add a second "logo/image" particle to any section on the layout".  DON'T SAVE
5. Now go back to the particle settings for the original "logo/image" particle and go to inheritance tab... Note that you can still change inheritance details
6. Now SAVE the layout
7. Now go back to the particle settings for the original "logo/image" particle and go to inheritance tab... Note that you are now prevented from changing the inheritance for this particle - this must be incorrect?

Here's a video:
http://screencast.com/t/QAiii6jJp

**Comment by mahagr** [comment]
It should prevent it right away...

**Comment by marktaylor46** [comment]
confirmed fix :)
