### ISSUE TITLE
Set layout of page

### ISSUE THREAD

**Issue by Mike00798** [gantry/gantry5#1388]
Hey,

I am searching whole day for the option to set my custom layout of some pages.
Layout ID is sidebar_right, But I got no idea where I have to write it down.

Best regards
Mike

**Comment by mahagr** [comment]
Start by telling which CMS you're using?

Layout is used inside an outline, which has assignments. To use outline in your page you need to assign it to that page.

**Comment by w00fz** [comment]
You should consider joining our [Gitter Chat](https://gitter.im/gantry/gantry5), these kind of questions are more suited in there. Lot of people in the room, including us from the Gantry Team (@gantry/developers), are constantly trying to help when and where we can.

Also the instant messaging works a lot better than the Github Issues, where we are trying to keep track of actual issues related to the framework.

Thanks.
