### ISSUE TITLE
Save as option for layouts

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#139]
I don't know if it has been discussed already but I think a "Save as" option for a layout in a multi-language Joomla installation would extremely be useful for non-programmers/coders.

**Comment by mahagr** [comment]
I'm adding this to beta5 as we are going to start looking into translations in there.

**Comment by sural98** [comment]
Thanks.

**Comment by mahagr** [comment]
This was already implemented in Configurations page for RC1.
