### ISSUE TITLE
removing override on atoms "section" doesn't remove inherited atoms

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1390]
If you override the atoms "section" (wrong term I know) and then add an atom that inherits from another outline and then remove the override on the atoms "section" and save the layout then it does not remove the inherited atom (until you refresh the page).

Here's a video: http://screencast.com/t/fh23eMEyay

I also think there should be a warning message if you do that as you may unintentionally lose a lot

**Comment by w00fz** [comment]
This is the correct behavior, based on how the implementation is across the whole admin. It might look more obvious with Atoms but this applies to any other field in Styles, Page Settings, Particles Defaults. Your overridden value, when the override is removed, is kept (which means you are now handing it to the Base Outline value).
At this point If you save and refresh it's just loading visually what value is being used.

We do not have any logic in place in admin to make this dynamically refreshing, and probably something we should look into but for a later release.

I'm going to close this as we are aware of it and it just hasn't been our intention to change it at the moment.
