### ISSUE TITLE
Section titles overflowing on layout

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1392]
A trivial point I know but it make the beautiful layout ugly when the section names overflow.

I fixed it with this CSS:
```.section-header > h4 {
    max-width: 100% !important;
    overflow: hidden;
}```

![2016-06-22_17-04-20](https://cloud.githubusercontent.com/assets/11683218/16274123/2ee12dec-389c-11e6-9815-72478fb4b60e.png)


![2016-06-22_17-06-24](https://cloud.githubusercontent.com/assets/11683218/16274077/fb3b323a-389b-11e6-9591-77f3369e8bf8.png)

Better still would be to also add a tooltip over the section name that gave the section name in full.

**Comment by adi8i** [comment]
In that example `text-overflow: ellipsis` could make it look better.

**Comment by w00fz** [comment]
Thanks for the suggestions guys. I now added ellipsis and also a title so when the title is truncated you can still get the full title when hovering.
