### ISSUE TITLE
wp error root with gantry5 / hydrogen

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1394]
First thank you all for the latest help and clarification.

Well, I started a second project using the gantry 5, and as I like to test everything that is possible, I ended up finding a problem.

I got a situation where the theme is not applied in any way, but, no way even in my home or front page, and how to achieve this fact?

The error is the following:
If the wordpress installation is in a sub-directory, and load directory or root directory is another will happen this error / bug (the theme will never be applied to the site entrance page)

![settings 1](https://cloud.githubusercontent.com/assets/7676600/16294170/8b8e4fe4-38f5-11e6-9c28-459c8377a8b1.png)

ps: if there is a solution or it is not an error, please who know the fix, let me know!

**Comment by newkind** [comment]
I'm not sure what you mean - are you talking about this https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory ?

**Comment by astenio** [comment]
yes or good url: http://www.websitedesignerinseattle.com/2012/01/making-wordpress-blog-root-directory-keeping-directory/

**Comment by newkind** [comment]
Ok, thanks for the info. I'll test it today.

**Comment by newkind** [comment]
I just tested this and works fine for me. I can have WP in a subdirectory and still everything works fine - theme styles change etc.
