### ISSUE TITLE
Outline as WP page

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1396]
It could be useful that we have some option to mark an outline to be standalone/to get a permalink to the outline. 

This feature would make Assignments tab on that outline not required and WP Pages would not have to be used at all. 

An idea that I got at 3am, so it might be stupid/not useful :smile:

**Comment by mahagr** [comment]
In Joomla we have our own "page type" or menu item type as joomla calls it. Its different to outline, though, and works just any other "page type" except of you can set a particle as the main content.

I think the first step would be to implement similar solution to WP.

**Comment by mahagr** [comment]
Related to #1013.

After a thought, I would do this in the opposite way by having option inside page to use specific outline to display it.
