### ISSUE TITLE
Create responsive font using Flowtype.js (from Github) in Gantry 5

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#1397]
Flowtype.js has a project at https://github.com/simplefocus/FlowType.JS?files=1
which makes font responsive to screen width without using breakpoints.
I'm a beginner, and I could not make this work in Gantry 5.  Maybe you guys can. Thx.

**Comment by mahagr** [comment]
You can just enter the Javascript code in `Page Settings` tab. There's `Assets` box with `Javasctipt` in it.

**Comment by pintobuck** [comment]
Thank you for the info.  I still have been unable to make flowtype.js work.  It would be very helpful if I knew all the steps that I need to make Flowtype.js work in Gantry 5, Rockettheme's Hydrogen template, and Joomla 3.51.

This is what I have done so far.

(1)Per mahagr’s comment at https://github.com/simplefocus/FlowType.JS;
Flowtype.js was made ready for Joomla.
In flowtype.js, I replaced $(   with  jquery(

(2) Per mahagr’s comment at https://github.com/simplefocus/FlowType.JS;
In the Hydrogen template, Page Settings, Assets, I put the flowtype.js file.
Also, I titled the Asset item: flowtype.js
See Item #6 below for the file content. 
  

(3) Per: https://github.com/simplefocus/FlowType.JS  Step #1.
In Gantry 5, Hydrogen template, Custom HTML particle, I put: 
     <script src="//code.jquery.com/jquery-latest.min.js"></script>
    <script src=" flowtype.js"></script>
 Followed by HTML for my logo text.

(4) Per: https://github.com/simplefocus/FlowType.JS  Step #2
In Gantry 5, Hydrogen temple, Custom.scss file, I put the following. 
Note that I did not put periods in front of these particular class names.  Is that correct?

body
{
   font-size: 18px;
}

h1,h2,h3,h4,h5,h6,p
{
   line-height: 1.45;
}

H1 {font-size:2em}        /* displayed at 24px */
H2 {font-size:1.5em}     /* displayed at 18px */
H3 {font-size:1.25em}   /* displayed at 15px */
H4 {font-size:1em}         /* displayed at 12px */
h5 { font-size: .83em; }
h6 { font-size: .75em; }



(5) Per: https://github.com/simplefocus/FlowType.JS, Step #3.
I tried to call flowtype with this: this in the Hydrogen template Atom CSS/JS:
	  jquery(‘body’).flowtype(); 

Per my guess, I put the it in the Hydrogen template Atom CSS/JS, and, I checked the Before </body>  box.

(6)  Per: https://github.com/simplefocus/FlowType.JS,  Step #4
I established  default settings/variables.

      var settings = $.extend({
         maximum   : 9999,    /* UNITS ARE PIXELS */
         minimum   : 1,       /* UNITS ARE PIXELS */
         maxFont   : 40,	  /* FONT SIZE */
         minFont   : 8,       /* FONT SIZE */
         fontRatio : 30,	  /* RECOMMENDED RATION TO TEST RESULTS */
      }, options),


(6)  The flowtype.js file that I used in Item #2 above is:

/* *** Begin Flowtype.js file content ********************** */
/*
* FlowType.JS v1.1
* Copyright 2013-2014, Simple Focus http://simplefocus.com/
*
* FlowType.JS by Simple Focus (http://simplefocus.com/)
* is licensed under the MIT License. Read a copy of the
* license in the LICENSE.txt file or at
* http://choosealicense.com/licenses/mit
*
* Thanks to Giovanni Difeterici (http://www.gdifeterici.com/)
*/

(function($) {
   $.fn.flowtype = function(options) {

// Establish default settings/variables
// ====================================
      var settings = $.extend({
         maximum   : 9999,    /* UNITS ARE PIXELS */
         minimum   : 1,       /* UNITS ARE PIXELS */
         maxFont   : 40,	  /* FONT SIZE */
         minFont   : 8,       /* FONT SIZE */
         fontRatio : 30,	  /* RECOMMENDED RATION TO TEST RESULTS */
      }, options),

// Do the magic math
// =================
      changes = function(el) {
         var $el = jQuery(el),
            elw = $el.width(),
            width = elw > settings.maximum ? settings.maximum : elw < settings.minimum ? settings.minimum : elw,
            fontBase = width / settings.fontRatio,
            fontSize = fontBase > settings.maxFont ? settings.maxFont : fontBase < settings.minFont ? settings.minFont : fontBase;
         $el.css('font-size', fontSize + 'px');
      };

// Make the magic visible
// ======================
      return this.each(function() {
      // Context for resize callback
         var that = this;
      // Make changes upon resize
         jQuery(window).resize(function(){changes(that);});
      // Set changes on load
         changes(this);
      });
   };
}(jQuery));

/* ***** End Flowtype.js file content ****************** */

**Comment by mahagr** [comment]
Off the hand do not load jQuery yourself, let Gantry/Joomla to load it (there's `Javascript Frameworks` atom for that). Loading jQuery more than once will break the page.

Where did you put the new js file? You need to get the URL for it right.

**Comment by pintobuck** [comment]
Thank you for your reply.
1. I now have deleted `<script src="//code.jquery.com/jquery-latest.min.js"></script>` from the Custom HTML particle that contains my logo text.
2.  I added the code from flowtype.js as an asset on the page settings of the Hydrogen template. It's a javascript item which I titled flowtype.js. Per [MrT's suggestion](url=http://www.rockettheme.com/forum/gantry5-for-joomla/260353-can-flowtype-js-responsive-font-work-in-gantry-5#1300894), I put the asset in the Base Outline of the Hydrogen Template.

I'm working on a test site. I can give you super user access if it would help.

**Comment by marktaylor46** [comment]
You don't want to load jquery like that. Use the javascript frameworks atom and tick the "jQuery" toggle. Let Joomla load jQuery for you via the Javascript frameworks atom.

**Comment by pintobuck** [comment]
Status Update - Flowtype was working fine last night in the body div. This morning I had Flowtype working in the body and logo-text divs. Then, I started to fine tune it, and Flowtype stopped working. So far, I have been unable to get Flowtype working again, even when I started over using my own instructions posted above.

**Comment by mahagr** [comment]
BTW, you shouldn't be using backslashes `\` in URL but normal ones `/`.

There's also better way to point to files in the template: `templates\g5_hydrogen\custom\custom\js\flowtype.js` would become `{{ url('gantry-theme://custom/js/flowtype.js') }}`

**Comment by pintobuck** [comment]
Thanks for the followup. I'm such a beginner, I pretty much need a cookbook recipe to understand things. 

Question #1:
(a)  I did not know if I include the quotation marks like this 
`<script src="{{ url('gantry-theme://custom/js/flowtype.js') }}"></script>` 

(b) would gantry-theme be replaced by g_hydrogen  or stay the same?

In the interim, I wound up using 
`<script src="//fraudstoppers.com/templates/g5_hydrogen/custom/custom/js/flowtype.js"></script>`

Question #2:
Regarding Step #3 in the Flowtype [readme.md](https://github.com/simplefocus/FlowType.JS/blob/master/README.md): 
Step 3: Call FlowType.JS
To begin the magic, simply call FlowType.JS before the close of your body tag:
`$('body').flowtype();`

Do I replace  `$( ` with  `jquery(`  for Joomla in this Step 3? 
 I have been putting `jquery('body').flowtype();` into a Custom CSS/JS Atom in the Base Outline.

Question/Info #3:
  I wonder if the word "body" is a div ID? The one time that I had flowtype working on my logo text,  I had replaced 'body' with my div ID 'logo-text'

I'm running this on a test site. If it would be helpful, I could give you a super user ID and pw.

**Comment by mahagr** [comment]
Q1
a) That looks correct
b) Yes, its using streams which automatically attempts to find the file from the proper location

Q2
Use `jQuery('body').flowtype()`, placing seems to be correct.

Q3
Body is a tag in the beginning of HTML body.

Please join gitter chat at https://gitter.im/gantry/gantry5 as there are a few helpful users.

**Comment by pintobuck** [comment]
**FlowType.js Responsive Web Font Typography** 
Adapted for use in the Gantry 5 Template Framework

**FlowType.JS**
Responsive web typography at its finest. Font-size based on element width.
Check out the [demo site](http://simplefocus.com/flowtype).

**What does FlowType.JS do?**
Ideally, the most legible body typography contains [between 45 and 75 characters per line](http://webtypography.net/2.1.2). This is difficult to accomplish for all screen widths with only CSS media-queries. FlowType.JS eases this difficulty by changing the font-size based on a specific element's width. This allows for a perfect character count per line at any screen width.  FlowType can also be used on other elements of varying length, such as logo text.
Installation in a Gantry 5 Template

1.	Download the flowtype.js file. [Download the latest release](https://github.com/simplefocus/FlowType.JS/archive/v1.1.0.zip).
      a.	Replace  $(  with  jquery(
                When I did it, there were only two replacements.

2.	Put the revised flowtype.js file on your server.

3.	In Gantry 5, put a Custom HTML particle in your template header.

4.	In the Custom HTML particle paste the flowtype call script, for example:

<script src="your-path-to-this-file/flowtype.js"></script>

<script type="text/javascript"> 
        jquery = jQuery.noConflict();
        jquery(document).ready(function() {
            /*jquery('body').flowtype({
                minimum   : 500,             pixel units. You set min and max width of browser window for FlowType action. 
                maximum   : 1200,
                minFont   : 12,                  pixel units. You set min and max font size for FlowType action. 
                maxFont   : 20,
                fontRatio: 35                     ratio of character string width / line height.  Make visual adjustments. 
              });
              */
            jquery("body").flowtype({                  /* Example: body is an element tag that you might choose */
                minFont: 12,
                maxFont: 30,                                      /* Notice there is a comma after maxFont: 30,  */
                fontRatio: 35                                      /* Notice there is NO comma after fontRation: 35  */
            });
            jquery("#logo-text").flowtype({               /* Example: #logo-text is a div ID that I used. */
                minFont: 8,
                maxFont : 40,
                fontRatio: 30
            });
        });
    </script>


5.	In your CSS style sheet or in your [Custom.scss](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet),  font-size should be in em units for FlowType to affect text size.

	Body
	{
	   font-size: 1em;	/* example */
	}

	h1,h2,h3,h4,h5,h6,p
	{
	   line-height: 1.45;	/* recommended */
	}

	H1 {font-size: 2em;}      /* examples */
	H2 {font-size: 1.5em;}    
	H3 {font-size: 1.25em;}   
	H4 {font-size: 1em;}      
	H5 {font-size: .83em; }
	H6 {font-size: .75em; }

	#logo-text
	{
 	   font-size: 1.75em;    /* example */
	}

6.	In Gantry 5 / your template name / Base Outline / Page Settings / Atoms / JavaScript Frameworks / JQuery, tick Framework over to green. Apply and save. That activates jQuery as a resource.

7.	Narrow or widen your browser window and watch the font size change.  Adjust Items #4 and #5, above, as needed.


Brought to you by...
This wonderful piece of magic has been brought to you by the team at [Simple Focus](http://simplefocus.com/). Follow Simple Focus on Twitter: [@simplefocus](http://twitter.com/simplefocus).

FlowType.JS is licensed under the MIT License. See the LICENSE.txt file for copy permission.

This procedure and Readme was adapted for Gantry 5 by Pintobuck.
Expert advice was received from:
    @mahagr , Gantry 5 development project at Github.com; and forum development at Kunena.org
   [ MrT](http://www.rockettheme.com/), Gantry 4 & Gantry 5 template development and expert support at Rockettheme.com

**Comment by pintobuck** [comment]
Flowtype.js as downloaded on ``7/03/2016:/*
* FlowType.JS v1.1
* Copyright 2013-2014, Simple Focus http://simplefocus.com/
*
* FlowType.JS by Simple Focus (http://simplefocus.com/)
* is licensed under the MIT License. Read a copy of the
* license in the LICENSE.txt file or at
* http://choosealicense.com/licenses/mit
*
* Thanks to Giovanni Difeterici (http://www.gdifeterici.com/)
*/

(function($) {
   $.fn.flowtype = function(options) {

// Establish default settings/variables
// ====================================
      var settings = $.extend({
         maximum   : 9999,
         minimum   : 1,
         maxFont   : 9999,
         minFont   : 1,
         fontRatio : 35
      }, options),

// Do the magic math
// =================
      changes = function(el) {
         var $el = $(el),
            elw = $el.width(),
            width = elw > settings.maximum ? settings.maximum : elw < settings.minimum ? settings.minimum : elw,
            fontBase = width / settings.fontRatio,
            fontSize = fontBase > settings.maxFont ? settings.maxFont : fontBase < settings.minFont ? settings.minFont : fontBase;
         $el.css('font-size', fontSize + 'px');
      };

// Make the magic visible
// ======================
      return this.each(function() {
      // Context for resize callback
         var that = this;
      // Make changes upon resize
         $(window).resize(function(){changes(that);});
      // Set changes on load
         changes(this);
      });
   };
}(jQuery));`

**Comment by mahagr** [comment]
I'm glad that you found answer for your problem.

I don't think that adding something like this into Gantry is a good idea as we want to keep the framework as light as possible. Not a bad idea for an atom, though!

I'm going to close this issue as being answered and out of scope for Gantry itself.
