### ISSUE TITLE
CIBuild: Inheritance: Section lock icon background color

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1398]
Just a minor suggestion... it would be better if the section lock background had more transparency rather than being solid white as it can completely obscure the section widths at smaller viewports.

I also think it would benefit from being a little smaller that it currently is (say 0px 18px padding instead of 8px 16px padding).

![2016-06-27_16-29-01](https://cloud.githubusercontent.com/assets/11683218/16385508/09575f14-3c85-11e6-91db-fdf22a5de3f8.png)

**Comment by w00fz** [comment]
It was more transparent and it was requested to make it more opaque :)

What should I do here? I can add a little bit more opacity to make everyone happy?

**Comment by marktaylor46** [comment]
50% opacity seems to look ok to me?

**Comment by w00fz** [comment]
@newkind can you see if 50% satisfies your like as well?

**Comment by newkind** [comment]
@w00fz I'm just not sure what about text read-ability when there's more than icon only. If you think that it would be better - go for it.

**Comment by gyvermac** [comment]
Prefer icon only

**Comment by w00fz** [comment]
I've set it to 70% opacity, think it's a good compromise for both point of views.

Cheers.
