### ISSUE TITLE
Mobile Menu Behavior for in-page anchors is different for Chrome than IE Edge or Mozilla

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1399]
From JIRA: GANTRYFIVE-187

Installed Isotope RocketLauncher 

Built new Menu entirely of System Links > External Links 

5 items: 

#g-showcase 
#g-above 
#g-utility 
#g-feature 
#g-expanded 

In Chrome the mobile menu stays open as you navigate from item to item, clicking outside of the mobile menu closes the menu and removes the overlay, which all seems fine 

In Mozilla and IE Edge clicking a menu item will jump to that anchor, close the menu, but leave the overlay in place... you then need to click anywhere to remove the overlay. 

So the overlay being there still is weird but primarily you've now lost you ability to navigate elsewhere because the menu is collapsed... so you have to scroll all the way to the top to click the toggle again

Second to that bug: 

There should really be an option for on-page/one-page menus like this where the mobile toggle stays fixed as you navigate so it's available wherever on the page you might be

**Comment by w00fz** [comment]
I tried Firefox, Chrome, IE11 and all of them keep the menu open and the overlay in place when clicking them.
Same behavior as you are describing in Chrome. I cannot reproduce the other behavior you are describing in Firefox / IE.

**Comment by blizam** [comment]
Maybe it's restricted to Isotope... I will test with Hydrogen
[Recording #1.zip](https://github.com/gantry/gantry5/files/341979/Recording.1.zip)

**Comment by w00fz** [comment]
Can you try the CI Build? Maybe I fixed this already and I don't recall it.

**Comment by w00fz** [comment]
Any more info about this one? I tried also with IE10 and still I cannot reproduce the issue.

**Comment by blizam** [comment]
I installed the CI build on Isotope and the behavior did not change. I'll test with Hydrogen now

**Comment by blizam** [comment]
The issue is also present with Hydrogen, both G5 stable and the latest CI. I can make another vid if that's at all helpful but the issue is for in-page anchors the mobile menu collapses and the overlay remains in place (until clicked) upon navigating in Mozilla and IE Edge. In Chrome the menu stays open until clicked outside of.

Windows 10 Pro OS Build 10586.420
Mozilla Firefox 48.0b5
Microsoft Edge 25.10586.0.0

PHP 7.0.6
Joomla 3.5.1

**Comment by w00fz** [comment]
I finally managed to reproduce and fix! 👍

**Comment by blizam** [comment]
Because you're the patron saint of G5 who graciously walks among mere mortals

7xGoldStars
:star2::star2::star2::star2::star2::star2::star2:
