### ISSUE TITLE
Font Chooser Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#14]
The check box for selecting font don't work in Chrome, when you click to the right it will select it see screenshot!

![2015-03-28 22 56 52](https://cloud.githubusercontent.com/assets/10489911/6883241/a873b32a-d5a4-11e4-8ecf-89f951726a07.jpg)

**Comment by w00fz** [comment]
Cheers!

**Comment by DamirPecnik** [comment]
Confirmed fix, working!
