### ISSUE TITLE
Content array particle - alias in link duplicating

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1400]
Creating an issue here based on [discussion](https://gitter.im/gantry/gantry5?at=5773f803971717155489a312) in Gitter chat.

Basically, `{{ article.route }}` is doubling the alias in Content Array particle (and probably everywhere else where it is used). 
So, instead of: `ID-alias`, we get `ID-alias-alias`.

Confirmed on Joomla 3.5.1 and CI build dev-23db22646 (28-06-2016).
It works properly on same CI on WP 4.5.3.

cc @dieter05 so he can follow progress as he originally found the bug.

**Comment by mahagr** [comment]
The code was copied from Joomla; not sure what has been changed since the initial commit. Maybe they changed something which means we would need to handle also older versions.

**Comment by nikola3244** [comment]
I can write a line or two to support older versions too.

**Comment by mahagr** [comment]
Lets figure out why this is happening first. :) I'll join to gitter in a second.

**Comment by mahagr** [comment]
OK, so as you noticed, Joomla uses `:` to separate slug from the id where Gantry code has `-`. Do you want to make a pull request?

**Comment by mahagr** [comment]
Can you verify that the issue is fixed? I noticed that we had the same issue in category.

**Comment by nikola3244** [comment]
Confirmed fix for both.

**Comment by JoomFX** [comment]
Thanks guys!
Tested it and I also confirm it's fixed :wink:
