### ISSUE TITLE
Latest CI Build Brakes Local Fonts and Local Style image

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1401]
The Latest CI Build Version: dev-23db22646 / Released: June 28, 2016 is braking the Local Fonts and Local Style image...

**Comment by w00fz** [comment]
How is it breaking exactly? Seems to be fine for me in my local tests.

**Comment by DamirPecnik** [comment]
The local fonts are not loading ...

**Comment by adi8i** [comment]
Is this the issue? https://github.com/gantry/gantry5/issues/1384

**Comment by mahagr** [comment]
Rebuild CSS to see fix in effect.
