### ISSUE TITLE
CIBuild : Inheritance: Suggestion add info message to base outline > layout

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1406]
Because the layout tab is now reinstated in Joomla for the base outline. I suggested that an information box be added to the top of the layout

```"This layout is only used for inheritance in other outlines. Changes herein will only be reflected in outlines that inherit from the base outline."```

Or something to that effect... I think this is important since I believe it will confuse Joomla users otherwise (I know it's different in Wordpress).

If possible it would also be nice to add a further info message if nothing is inheriting at all from the base outline:
```"There are no outlines that currently inherit anything from the base outline layout"```

**Comment by JoomFX** [comment]
:+1:

**Comment by mahagr** [comment]
Your comments @w00fz @newkind ?

**Comment by newkind** [comment]
If you need this kind of message, it has to be Joomla only. Other platforms don't need it and well it wouldn't be true ;)

**Comment by w00fz** [comment]
We can add a notice about Base Layout only being there to be inherited, but I personally dislike this tendency we are getting into where everything has to have a notice.
We have documentation and that's there for answering questions. I don't want us to build this wonderful playground and start filling it with signs that tell kids what to play with and how to. Most things get figured out, everything else can be found in the docs.

**Comment by gyvermac** [comment]
As it can't be assigned to any menu, it can't be used wrongly... 
But I think usage of a "base-outline (id default)" vs "template-default (id 9)" can be very confusing for a user. It should be at least renamed more consistently : template-base-outline (id 0) template-defaul-outline (id 9) 
Anyway, must be very clear in the docs !

**Comment by mahagr** [comment]
It cannot be renamed without breaking all existing templates or having a mismatch on directory vs text. The issue also only exists in Joomla -- in all other platforms it works as you'd imagine it would.

**Comment by mahagr** [comment]
I disagree with adding a message as base outline isn't being used in anywhere else either.
