### ISSUE TITLE
G-grid sizing bug IE

### ISSUE THREAD

**Issue by Rdechamps** [gantry/gantry5#1407]
The g-grid flexbox use with the class .size-X need a fix on IE if you want to use the grid outside the layout manager. For example, re-use the grid system inside an article and adding padding to it break the grid system since IE does not perform well on flexbox and box-sizing combination.

A quick fix would be to add the following code to the nucleus.css file : 
`@for $i from 1 through 100 {
    .size-#{$i} {
        max-width: $i + '%';
    }
}`

Note : you then need to make it 100% on mobile targeted device.

**Comment by mahagr** [comment]
Which version of IE you're refering to?

**Comment by Rdechamps** [comment]
Hello,

I'm refering to IE 11 and IE 10.

Romain.


Le 30/06/2016 à 15:36, Matias Griese a écrit :
>
> Which version of IE you're refering to?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/gantry/gantry5/issues/1407#issuecomment-229660038>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AKQwZUX7Z0yolgPcPD0Y63v8QwjS4hy-ks5qQ8Z6gaJpZM4JCJeL>.
>

-- 
Romain Dechamps.
logo

4, Allée Pin de Saint-Clair 38130 ÉCHIROLLES
Tél. 04 38 49 05 05 - Ligne directe : 04 38 21 09 13*
**www.elan-creatif.com* <http://www.elan-creatif.com/>

**Comment by mahagr** [comment]
Oh, and I was hoping to get rid of widths soon because of they prevent us from really taking advantage from flexbox... :(

Do you have example where the grids break?

**Comment by Rdechamps** [comment]
Hopefully somedays we will all have good browsers!

Below is an example I made so you will see it action. Note that I had to 
reset the max-width property that I add in my custom style so you can 
see the default settings. The first row is a basic gantry install, the 
second include the max-width property : 
http://inedits.com/dev/thr-saunier/site/test/


Le 30/06/2016 à 15:51, Matias Griese a écrit :
>
> Oh, and I was hoping to get rid of widths soon because of they prevent 
> us from really taking advantage from flexbox... :(
>
> Do you have example where the grids break?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/gantry/gantry5/issues/1407#issuecomment-229664220>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AKQwZUNRpJlhqUqZX3r10hiJLdzLmz8Eks5qQ8nrgaJpZM4JCJeL>.
>

-- 
Romain Dechamps.
logo

4, Allée Pin de Saint-Clair 38130 ÉCHIROLLES
Tél. 04 38 49 05 05 - Ligne directe : 04 38 21 09 13*
**www.elan-creatif.com* <http://www.elan-creatif.com/>

**Comment by w00fz** [comment]
Thank you @Rdechamps for the suggested fix which I like a lot and for the test site you put together for me to better see the problem.

Really appreciate it, wish all issues where made like this one! 👍 

This is now fixed.
