### ISSUE TITLE
Changing  Showcase Background

### ISSUE THREAD

**Issue by ulyssedoris** [gantry/gantry5#1408]
how to change the showcase background image from repeating? 
![screen shot 2016-06-30 at 8 19 59 pm](https://cloud.githubusercontent.com/assets/13663636/16508385/6b9e6dfc-3f00-11e6-8b01-456c239b43c5.png)

**Comment by newkind** [comment]
Just use this CSS rule :
`background-repeat: no-repeat;`

**Comment by ulyssedoris** [comment]
It worked thank You! One more question should I use a style sheet to prevent the change when gantry5 gets updated? Which file should i add this css rule into?

**Comment by newkind** [comment]
Please read this : http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

**Comment by JoomFX** [comment]
Hey @ulyssedoris 

Yes, you should put all your custom CSS code in the [custom.scss](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) file (notice that the file extension is SCSS, not CSS - everything is explained in the official Gantry5 documentation) :wink:

**Comment by JoomFX** [comment]
@newkind you were 1 second faster, damn :smile:

**Comment by newkind** [comment]
;)
