### ISSUE TITLE
Gantry Joomla & Wordpress on the same domain.

### ISSUE THREAD

**Issue by marcinNS** [gantry/gantry5#1409]
I have two installations with Gantry libraries. 
First installation is Joomla CMS on root domain eg. www.example.com
The second installation is Wordpress CMS on subdirectory: www.example.com/blog
After I upgraded Gantry to 5.2.18 I can't run joomla and wordpress on the same time.

If I first run Joomla in browser, I have error on Wordpress site
 _mod_fcgid: stderr: PHP Fatal error:  Class 'JFactory' not found in /web/libraries/gantry5/classes/Gantry/Framework/Platform.php on line 37,_

If I first run Wordpress in browser, I have error on Joomla site
 _mod_fcgid: stderr: PHP Fatal error:  Call to undefined function Gantry\\Framework\\wp_nonce_url() in /web/blog/wp-content/plugins/gantry5/src/classes/Gantry/Framework/Gantry.php on line 59_

When I disable **opcache** the problem is gone.
It looks like it depends which Library is first cached (from Joomla or from Wordpress).

Any suggestions what can I do excluding disable opcache?

**Comment by mahagr** [comment]
Might be happening because of this setting being off:

*opcache.use_cwd*

    If enabled, OPcache appends the current working directory to the script key, thereby eliminating possible collisions between files with the same base name. Disabling this directive improves performance, but may break existing applications.

**Comment by marcinNS** [comment]
Thanks for reply. This setting is ON (master and local value). It must be anything else.

**Comment by mahagr** [comment]
Then honestly I'm not sure what else it could be. Check if you have any values that aren't the default ones (from php documentation) as I'm running Gantry in multiple sites using 4 platforms and all of them work just fine.

**Comment by w00fz** [comment]
Have you tried excluding the sub-folder in the `.htaccess`?

Something like:
```htaccess
RewriteCond %{REQUEST_URI} !^blog
```

**Comment by marcinNS** [comment]
Yes, I excluding the sub-folder. I have in root .htaccess (example.com is sample only).
```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
RewriteCond %{REQUEST_URI} !^/blog/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /blog/$1
RewriteCond %{HTTP_HOST} ^example\.com$ [NC]
RewriteRule ^(.*)$ http://www.example.com/$1 [R=301,L]
```
I think I must search answer in opcache settings, as suggested @mahagr

**Comment by mahagr** [comment]
I think the easiest way would be to change settings one by one and restart apache. What are the settings now?

**Comment by w00fz** [comment]
Were you able to solve this issue? Can I close it?

**Comment by w00fz** [comment]
Marking this as resolved but feel free to reopen if you have additional info to provide that we can help you with.
