### ISSUE TITLE
/

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#1410]
Please see the 3rd comment, below.  (This comment was blank, when woofz replied, so I edited this post to explain.)

**Comment by pintobuck** [comment]
Thx for replying instantly woofz. I solved an issue that might be worthy of a Gantry 5 enhancement and pull request. I'm new to Github, and I was experimenting on how to do that. 

Gantry 5 makes responsive web pages, but the font, itself, is not responsive. Please see a solution in [Create responsive font using Flowtype.js (from Github) in Gantry 5 #1397](https://github.com/gantry/gantry5/issues/1397) .

**Comment by mahagr** [comment]
Please do not add a new issue if there's already existing issua opened.
