### ISSUE TITLE
Crikey when changing tab from "Layout" to "Page Settings"

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1412]
https://drive.google.com/file/d/0B8fB_QtQf14TSXR0eVJMMDFQUmM/view?usp=sharing
https://drive.google.com/file/d/0B8fB_QtQf14TZWxTVzl4XzFqOGs/view?usp=sharing
Gantry and Hydrogen version: dev-cde99afd0 (07/07/2016)
WP 4.5.3

As you can see on the video, if we are in "Layout" tab on "Home" outline and save the layout and then click on "Page Settings tab", we get Crikey.

It's not happening on Base.
Tested on WP only.

EDIT:
I was wrong. You don't even need to save the layout. Just click on "Layout" tab and then on "Page Settings".

EDIT2:
Actual error message:
```
Argument 1 passed to Gantry\Framework\Atoms::__construct() must be of the type array, 
null given, called in /home/nikola/public_html/wphelium/wp-
content/plugins/gantry5/src/classes/Gantry/Admin/Controller/Html/Configurations/Page.ph
p on line 81
```

**Comment by nikola3244** [comment]
Also, maybe not related to exact this issue, while you are on "Page Settings" tab on "Base Outline" and change outline to "Body Only" without changing the tab, spinner on "Page Settings" tab will spin forever or display a Crikey.

**Comment by w00fz** [comment]
What's in your Atoms field in Base -> Page Settings?

**Comment by nikola3244** [comment]
Nothing, it's empty.

**Comment by w00fz** [comment]
Check `custom/config/default/page/head.yaml` and `custom/config/_body_only/page/head.yaml`

**Comment by nikola3244** [comment]
I don't have a `page` directory in `custom/config/default` or `custom/config/_body_only`

**Comment by nikola3244** [comment]
Only `index.yaml` and `layout.yaml` in every subdirectory of `custom/config`

**Comment by w00fz** [comment]
Ok weird, because I don't get that error. It's like there's some setting stored wrong.

**Comment by nikola3244** [comment]
So weird. This is a clean installation from yesterday when I tried Helium.

**Comment by nikola3244** [comment]
If needed, I can provide a URL to my environment with SSH access, so you guys can check what's wrong.

**Comment by mahagr** [comment]
:+1:
