### ISSUE TITLE
PHP 5.4: Can't use method return value in write context

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#1413]
![error gantry 5 v-5 3 0](https://cloud.githubusercontent.com/assets/11734/16699885/b96aea68-450b-11e6-926b-35f342302c5f.PNG)

**Comment by mariantanase** [comment]
I've tried to update but I received the same error. Fortunately I've tested the update on a localhost. The fix is on the CI build ? or should I wait the 5.3.1 ?

**Comment by mariantanase** [comment]
Ok, I modified the Particles.php with your fix and it's ok.
Thanks @w00fz !

**Comment by w00fz** [comment]
You should definitely upgrade php if you can. 5.4 is old and reached end of life a year ago. Security issues will not get fixed anymore. Not to mention that 5.6 and even better 7.0, are incredibly faster!

**Comment by mahagr** [comment]
Please install CI build from http://gantry.org/downloads#ci-builds to fix this issue in PHP 5.4.

**Comment by mariantanase** [comment]
Ok. Even the minimum server requirements on the docs.gantry.org should be updated.

**Comment by RonBuitendijk** [comment]
I see CI build on http://gantry.org/downloads#ci-builds, but how can i download it?
