### ISSUE TITLE
Just uploaded Gantry 5.3.0 and getting this error

### ISSUE THREAD

**Issue by pambesteder** [gantry/gantry5#1415]
Just uploaded Gantry 5.3.0 and when I went to make a change to my template's layout, got this error:

I used the auto update when it alerted me there was an update....so what can I do to fix it?

Thanks
Pam

![gantryerr94](https://cloud.githubusercontent.com/assets/12632086/16705536/62a0a4ec-4552-11e6-835f-744fad88c14f.png)

**Comment by w00fz** [comment]
See https://github.com/gantry/gantry5/issues/1413
