### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by GeGeek** [gantry/gantry5#1416]
Hello,

if i do exactly that (following), i get this error: Invalid argument supplied for foreach() (see the attached image).

1. Go in outlines list
2. Duplicate an outline with **inherit option enabled**.

If i try this without the inherit option, it works.

![image 1](https://cloud.githubusercontent.com/assets/5159674/16707431/4d5ace70-45cd-11e6-8652-7b082e484984.png)

I'm on WordPress, with PHP 5.6 / 7.0, LiteSpeed

Thank you

**Comment by w00fz** [comment]
I can't seem to be able to reproduce this.
Which Outline are you trying to duplicate? Could you zip the `custom/config/<id>` folder and pass it here?

**Comment by mahagr** [comment]
I'll look if I can prevent this from happening.

**Comment by GeGeek** [comment]
Hi,

i tried with the default outline "home" and it's working, but with all my other custom outlines, i get this error.

Thank you

**Comment by mahagr** [comment]
In the mean time you can install previous stable release form https://github.com/gantry/gantry5/releases

**Comment by mahagr** [comment]
@w00fz I think we need a link to older releases in our downloads page.

**Comment by mahagr** [comment]
@GeGeek Test if CI build has still any issues..?
