### ISSUE TITLE
Error After Upgrading to 5.3.0

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#1419]
I am using Gantry with Hydrogen (Joomla). Update was successful. But when I open template, error is coming:

Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
Can't use method return value in write context

Stack frames (1):
0 Whoops\Exception\ErrorException 
…/­classes/­Gantry/­Admin/­Particles.php42

On right side, some code is displayed.

**Comment by w00fz** [comment]
See https://github.com/gantry/gantry5/issues/1413

Although the issue is fixed and you can use CI Build to get around it, you are still using PHP 5.4, it's not secure, you should upgrade to a more recent version.

**Comment by rgblogs** [comment]
I upgraded to 5.6 (5.4 was default option) version through cPanel and error gone! Thank you...

I hope other problems in Joomla do not occur because of this upgrading.

**Comment by mahagr** [comment]
PHP 5.5 and 5.6 do not really have backward incompatibilities so as long as you had at least PHP 5.4, you should be fine.
