### ISSUE TITLE
Authorization menu items

### ISSUE THREAD

**Issue by mark118** [gantry/gantry5#142]
I have an issue with the menu in this situation:
parent -> special with a child -> registered
Registered users get an error. I know this is not very well configured ;-)
It may not be a bug but it probably will give issues.

**Comment by adi8i** [comment]
@mahagr  What's the issue? I am curious, this one was over me  :D

**Comment by mahagr** [comment]
It's a known issue; I need to fix it. Basically items below the special shouldn't show up at all.

**Comment by mahagr** [comment]
Seems to be fixed by other changes.
