### ISSUE TITLE
Gantry 5.3.0 gives odd error message in Joomla create NEW module screen

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1420]
Installed 5.3.0 into Ambrosia 1.1.3. Then tried creating a new Module -> Type -> Gantry 5 Particle 
and got this error warning:
![new - modules_gantry 5 particle](https://cloud.githubusercontent.com/assets/3792467/16711811/f39d2340-463c-11e6-8498-394522d61c3a.jpg)

Checking my Template Manager it appears that Ambrosia-Default is set as the Default Gantry 5 template.
![templates_styles](https://cloud.githubusercontent.com/assets/3792467/16711810/f39ce9f2-463c-11e6-87c5-fc4012015936.jpg)

**Comment by mahagr** [comment]
Thanks @w00fz, missed that one.
