### ISSUE TITLE
error 405 with G5.3.0 and CI-18b2463ac

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1422]
In an Outline when clicking the pen to edit the Outline name the current name is erased. I type in my name.
![click_pen-type_new_name](https://cloud.githubusercontent.com/assets/3792467/16715179/3f7c5da2-46a7-11e6-817b-55aa885c40fc.jpg)

Then I click off or press enter and the entry box shrinks and I get a 405 error
![error-after-typing](https://cloud.githubusercontent.com/assets/3792467/16715178/3f7c37f0-46a7-11e6-8710-010c8f6032f6.jpg)

Using J351 and PHP 5.6 in both Chrome and Firefox browsers.

**Comment by w00fz** [comment]
Good catch!
