### ISSUE TITLE
Gantry 5.3.0 and latest CI kills the functioning of enellax.js

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1424]
In the latest G5.3.0 and latest CI build they prevent the enellax.js from properly functioning so there is NO parallax effect happening.

**Comment by w00fz** [comment]
Need more details. What's not functioning? Is it loading on frontend? How did you set it up in admin?

**Comment by w00fz** [comment]
Hello? 😄

**Comment by DanGthatRokGallery** [comment]
Hi Djamil
Sorry for the late reply but I wanted to wait for 5.3.1. It's weird - enllax.js loads properly and is present but when viewing a proper enllax you can see the targeted container change the background-position setting as you scroll. In Chrome Dev Tool you can see the JS acting as the element gains a pink background while the JS is doing its thing.

Like in Sienna, I'll use my Isotope RocketLauncher to describe this.
With Gantry 5.2.18 the Extension section uses a Block Content particle with enllax setup in the Tag Attributes. This is the HTML output from Chrome:
`<section id="g-extension" data-enllax-ratio="0.9" data-enllax-type="background" style="position: relative; left: 0px; right: 0px; background-position: center -194px;">`

Here everything works as it should. Now when I install 5.3.0 or 5.3.1 this is the output from the same section:
`<section id="g-extension" data-enllax-ratio="0.9" data-enllax-type="background">`
So when you scroll - nothing happens - the background image moves exactly with the content - NO parallax.

**Comment by marsivo** [comment]
$ bower install animate.css --save

**Comment by w00fz** [comment]
@marsivo that's irrelevant.

@DanGthatRokGallery I tried replicating but works fine for me:

![home 2016-07-11 22-53-32](https://cloud.githubusercontent.com/assets/11734/16756516/8ba2619a-47ba-11e6-8a3f-11a2ae5bf1f2.png)

**Comment by DanGthatRokGallery** [comment]
Thanks Djamil - must be my PHP version as I'm using RocketLauncher's.

**Comment by mahagr** [comment]
PHP version shouldn't affect on this issue.Check if you have javascript error.

**Comment by kat05** [comment]
I've tested this locally on an Isotope RocketLauncher install, after updating Gantry to latest CI dev-1391b91b3, the Parallax Effect on the frontpage keeps working as expected.

**Comment by w00fz** [comment]
Sorry Dan, I think this is something on your instance.
Feel free to reopen if you get more clues and it's something on Gantry that needs to be fixed.

Thanks!

**Comment by DanGthatRokGallery** [comment]
Thanks peeps. It's something on mine then but both instances are clean RocketLauncher's so I'm not sure where to look. I think your Matias it has to be something else other than PHP as I tried a LIVE clean RocketLauncher on 5.6 and it worked fine - ARGGHHH!!!!!!

You can CLOSE this if you haven't already.
