### ISSUE TITLE
Gantry 5.3 and Php 5.4.12 not work

### ISSUE THREAD

**Issue by marcs84** [gantry/gantry5#1426]
Whoops\Exception\ErrorException thrown with message "Can't use method return value in write context"

Open: \wp-content\plugins\gantry5\src\classes\Gantry\Admin\Particles.php 

        if ($particle) {
            return !empty($locator->findResources("gantry-theme://config/{$outline}/particles/{$particle}.yaml"));
        }

I assume that the latest version is not compatible with PHP 5.4. Confirm?
The system requirements are php 5.5+?

**Comment by marktaylor46** [comment]
Fixed in #1413 CI build = please use CI build.

**Comment by mahagr** [comment]
We will release update today which fixes the issues.
