### ISSUE TITLE
Crikey error after upgrade to  gantry version 5.3

### ISSUE THREAD

**Issue by Go2Sicily** [gantry/gantry5#1428]
hi there, since  i have update to v5.3.0 i got this error! I already installed PHP 5.6 but nothing is changed.
![schermata 2016-07-11 alle 12 41 20](https://cloud.githubusercontent.com/assets/16309800/16728122/e1c626c0-4764-11e6-817b-2f79f225746e.png)

**Comment by mahagr** [comment]
SCSS compilation takes too long, try enabling Opcache extension in PHP to speed up the page load.

You may also try increasing `max_execution_time = 60` in your `php.ini` or by going into admin and compile CSS manually.

**Comment by Go2Sicily** [comment]
@mahagr  Solved! Thank you so much
