### ISSUE TITLE
add x button to easily reset menu icon and menu image path

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#143]
it seems after selecting a menu icon or image, the icon or image path needs to be manually removed in order to remove the icon or image. adding an x button or similar to easily reset to an empty field would be helpful, me thinks.
![g5_iconimg_x](https://cloud.githubusercontent.com/assets/5719486/7375999/216a8d20-eda2-11e4-823d-41ccb100fbb2.jpg)

**Comment by DamirPecnik** [comment]
+1 on this.

**Comment by w00fz** [comment]
Ok this is now implemented. It only shows on hover which means it's mostly desktop friendly and that is ok, we don't want to clutter the touch devices with smaller screen.

It is also smart enough to automatically hide or show when needed. If you just cleared out a field or if you manually `backspaced` the content of a field, the reset icon goes away.

Also worth mentioning, it is implemented only for those fields where it makes sense. There won't be a reset icon for `checkbox`, `radio`, `collections`, `select`.

![gantry 5 - administration 2015-04-29 16-13-45](https://cloud.githubusercontent.com/assets/11734/7403449/bc38a15a-ee8a-11e4-8b74-10804c1f5bb1.jpg)
