### ISSUE TITLE
Undefined property after removing layout.yaml

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1431]
Not sure how to replicate it but in my instance of Joomla, after making some changes to layout and deleting layout.yaml file I started to get `Undefined property` error on reload and save.

https://monosnap.com/file/DFmh7uKGBU893ntY3NMMPxuxvbHgp6.png

**Comment by mahagr** [comment]
Do not delete layout.yaml file, its not really supported anymore. Nevertheless I'll try to fix this issue.
