### ISSUE TITLE
Error after Installing 5.3.1

### ISSUE THREAD

**Issue by dancatt** [gantry/gantry5#1433]
Hi,

after Installing the Update 5.3.1 in Worpress, I become the following Error:

`Fatal error: Uncaught Twig_Error_Loader: There are no registered paths for namespace "gantry-admin" in "@nucleus/page.html.twig" at line 79. in <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:196 Stack trace: #0 <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('@gantry-admin/p...') #1 <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('@gantry-admin/p...') #2 <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php(378): Twig_Environment->getTemplateClass('@gantry-admin/p...', NULL) #3 <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php(286): Twig_Environment->loadTemplate('@gantry-admin/p...', NULL) #4 <PFAD>/htm in <PFAD>/wordpress/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 196`

Can somebody help?

Thank You.

**Comment by w00fz** [comment]
Please download and install Gantry 5 Plugin again. It's been hot fixed.

**Comment by dancatt** [comment]
Thank You. It works
