### ISSUE TITLE
Backend breaking with missing js-translations.html.twig

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1434]
If someone is overriding `/admin/templates/partials/base.html.twig` and is missing 
`{% include "@gantry-admin/partials/js-translations.html.twig" %}`, admin area won't work.
What won't work?
Layout tab contents would be missing, Extras button won't work...

The exact error message would be:
`Uncaught TypeError: n.G5T is not a function`

On G5.3.1 (second release) and WP 4.5.3

**Comment by mahagr** [comment]
Backwards compatibility issue; existing themes modifying admin will break.

**Comment by nikola3244** [comment]
By the way, `php_unsupported.html.twig` also needs `ignore missing`.

**Comment by mahagr** [comment]
That will only fix backwards compatibility allowing theme to work in older version of Gantry. I can also see another issue when you have new Gantry with older version of theme -- it will break the admin.

**Comment by w00fz** [comment]
You are definitely the only person I know who overrode admin `base.html.twig` 😄 
Also this shouldn't be an issue with older templates, the two twig files are specifically for admin only, shouldn't affect front end at all.

**Comment by nikola3244** [comment]
This was the only way to put a custom JS in administration area. 😄

Djamil, Matias, @adi8i and me talked about this in Gitter. 
Problem was that I overroded this file in some previous Gantry version and you guys updated it recently. 
Without JS translations on 5.3.1, admin area is almost unusable. 
But frontend is completely fine.

**Comment by w00fz** [comment]
If I add the `ignore missing`, that solves the problem with backward compatibility right?

**Comment by nikola3244** [comment]
Not really. If you put it now, it won't make a difference because file is already overridden.

**Comment by w00fz** [comment]
Actually it will probably still fail because you would be missing the G5T function

**Comment by w00fz** [comment]
I'll handle it via JS, making sure G5T is always available.

**Comment by nikola3244** [comment]
What if it's not?

**Comment by w00fz** [comment]
You will get untranslated strings

**Comment by w00fz** [comment]
Unfortunately this had to be done, I needed translated strings in JS and the only way to pass them is via twig as inline JS.

**Comment by nikola3244** [comment]
Doesn't matter if it's not translated. Better to have couple untranslated strings than broken admin. 😜

**Comment by nikola3244** [comment]
If not undefined won't work?

**Comment by nikola3244** [comment]
Oops, accidentally commented. (I deleted one comment)

**Comment by w00fz** [comment]
Can you try with the latest CI Build if this is better now?
Once it finished building 😄

**Comment by nikola3244** [comment]
Probably tomorrow. Too much coding today. 😄

**Comment by nikola3244** [comment]
Sorry it got me so long to test, confirming that it's working now.

**Comment by mahagr** [comment]
Cool, release will likely happen tomorrow -- I still have some tasks to do on installer.

**Comment by nikola3244** [comment]
Sounds good, thank you both for all your hard work.
