### ISSUE TITLE
All sections get wiped out when trying to uninherit a section and leaving checkboxes active

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1435]
Not sure if the title is correct or if this bug also appears under different circumstances.
In an Isotope RocketLauncher using latest CI dev-1391b91b3 and Joomla 3.5.1 I went to the Default outline's Header section and inherited from the Home outline which has an empty Header section.

After that I uninherited again which worked fine at first, but then I repeated the step and checked the checkboxes for - Replace Section Attributes and - Replace Particles within Section and all of a sudden my whole layout was wiped out.

Please see the attached screencast.
https://www.dropbox.com/s/sl3inzrwdfjn9zc/Firefox%20-%20Isotope%20-%20Administration.mov?dl=0

**Comment by kat05** [comment]
I can also replicate with the latest Helium CI build, screencast can be seen here:
https://www.dropbox.com/s/1c4yc0lspxy11tu/Firefox%20-%20Isotope%20-%20Administration2.mov?dl=0

**Comment by kat05** [comment]
This seems to happen only if the section you inherited from is an EMPTY section containing no particles.

**Comment by kat05** [comment]
This same issue is present in WordPress.

**Comment by w00fz** [comment]
Good catch! Nasty one.
