### ISSUE TITLE
Problem after update to  (hydrogen v5.3.1 / g5_hydrogen) using Joomla 3.5.1

### ISSUE THREAD

**Issue by sirmagic** [gantry/gantry5#1436]
IMPORTANT URGENT !!!!
Problems after update to v5.3.1 hydrogen / gantry5!
Website uses Community Builder and after updating displayed some fields are not correct and prevent users to update their user profile. A very important feature is thus saqt out of service on a website with more than 6,000 daily visitors.

contact me for any further information (screenshots)
Can I download hydrogen/gantry5 v 5.3.0 some where ???

**Comment by mahagr** [comment]
Can you attach a screenshot highlighting the issue and maybe an address to the site?

**Comment by sirmagic** [comment]
![userdetails](https://cloud.githubusercontent.com/assets/3233528/16767300/0401872c-483f-11e6-92d9-b9194a6a5661.jpg)
![userdetails 1](https://cloud.githubusercontent.com/assets/3233528/16767309/0c20988a-483f-11e6-994c-4795f8559f63.jpg)

**Comment by mahagr** [comment]
And installing older version did fix the issue?

**Comment by sirmagic** [comment]
have not done that - where do I get  hydrogen/gantry5  v5.3.0 ?

**Comment by sirmagic** [comment]
have download v 5.3.0 be back

**Comment by sirmagic** [comment]
what should I try first hydrogen v5.3.0 or gangry5 5.3.0?

**Comment by sirmagic** [comment]
installing gantry5 / hydrogen v 5.3.0  It did not fix the problem !!!

**Comment by sirmagic** [comment]
I have a copy site that run v 5.2.18 gantry5 and hydrogen ok
Can going bag to v 5.3.0 give problems??

**Comment by sirmagic** [comment]
I've tried to install all the way back to version v5.2.18 and I can not correct the error - what has gone wrong. Since there was oprateret to version 5.3.0 disappeared all template menu subtitles - might have occurred corresponding unrecoverable error on community builder fields for the update to 5.3.1?

**Comment by sirmagic** [comment]
no vith v 5.2.18 the probmel still there

**Comment by sirmagic** [comment]
I have not changed anything in the Community Builder extension

**Comment by sirmagic** [comment]
the problem is also here!
![userdetails 2](https://cloud.githubusercontent.com/assets/3233528/16768938/bbf29f36-4846-11e6-9440-1f2116522284.jpg)

**Comment by mahagr** [comment]
Is that also  from the frontend? Try is recompiling CSS from Gantry helps..?

**Comment by sirmagic** [comment]
yes all picture are frontend

**Comment by sirmagic** [comment]
How do I do that???

**Comment by sirmagic** [comment]
do just press recompile in hydrogen theme?

**Comment by sirmagic** [comment]
Recompile CSS did not help - byt the frame changed a little in the way that the field scroll bar can be open, but stille no fiels 
![userdetails](https://cloud.githubusercontent.com/assets/3233528/16769691/060b24f0-484a-11e6-8948-8ecc8fcc298f.jpg)

**Comment by sirmagic** [comment]
From here it seems it is fields in Community Builder and UddlM extension that makes a posting to a table that has problems.
What is the time horizon for the error is corrected in a new gantry5 / Hydrigen update?

**Comment by w00fz** [comment]
Did you recompile CSS from Base Outline? You need to do it there. Also i cannot see any of those dropdowns you mention in your screenshot in your site.
Please point to a link where we can inspect them.

**Comment by sirmagic** [comment]
This screenshot is from a website that runs Gantry 5 / Hydrogen v5.2.18

![korrekt felt 2](https://cloud.githubusercontent.com/assets/3233528/16781696/af279398-487c-11e6-8e90-abff7c7414ce.jpg)
![korrekt felt](https://cloud.githubusercontent.com/assets/3233528/16781703/b7b106f2-487c-11e6-8653-84652325de7f.jpg)

**Comment by w00fz** [comment]
Yah I can see the screenshot but I can't see it online. Perhaps there is some CSS conflict happening, it's hard to know without actually seeing it live.

**Comment by sirmagic** [comment]
it requires you to be a registered user to view user profile page and that part at the moment only run danish

**Comment by w00fz** [comment]
Can you inspect the field with Chrome?? Maybe you can figure out where is the issue?

**Comment by sirmagic** [comment]
do not know - but it comes on over a field in both Community Builder extension and UddeIM extension and nothing has changed besides updating to Gantry5 / Hydrogen v5.3.1

**Comment by sirmagic** [comment]
if you have an email I can use, to registration for you as admin on a test site, with the same problem?

**Comment by w00fz** [comment]
You can PM me in our Gitter chat (https://gitter.im/gantry/gantry5) can find me as w00fz (https://gitter.im/w00fz)

**Comment by sirmagic** [comment]
can you see me in the private talk

**Comment by w00fz** [comment]
This was resolved in private. It was just a CSS issue on the site.
