### ISSUE TITLE
"GANTRY5_PLATFORM_JS_LOADING" language constant missing?

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1437]
I have noticed that when editing particles (in modules) in Joomla Module manager that whilst the particle is loading there is (what I presume to be) a language constant shown that appears to be missing?

GANTRY5_PLATFORM_JS_LOADING

![2016-07-12_15-06-49](https://cloud.githubusercontent.com/assets/11683218/16770000/d4ecf314-4842-11e6-80fb-4b38ffda236c.png)

**Comment by kat05** [comment]
I just saw this too, but was unable to get a screenshot of it. :)

**Comment by kat05** [comment]
Here is another one.

![gantry_js](https://cloud.githubusercontent.com/assets/5719486/16771960/a25ce5c0-4852-11e6-8e23-b253b05aab86.png)

**Comment by w00fz** [comment]
Ah I didn't catch this is only happening in the Module.
