### ISSUE TITLE
Level 0 Menu subtitles get wiped out from all menu items after updating one at level 1.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1438]
It's easier to explain by steps:

I used Galatea for testing:
1. Go to menu editor "mainmenu"
2. edit home menu item settings and add a subtitle - APPLY & SAVE
3. click on "features" menu item
4. edit a child menu item and add a subtitle - APPLY & SAVE
5. change menu to "galatea menu" and then back to "mainmenu" again - note that the subtitles on the level 0 menu item that you added have now been wiped out.

![2016-07-12_16-11-56](https://cloud.githubusercontent.com/assets/11683218/16772373/ee9da34a-484b-11e6-9d27-6ded225f591c.png)
![2016-07-12_16-12-33](https://cloud.githubusercontent.com/assets/11683218/16772377/f3320360-484b-11e6-8770-36b09c0a46e5.png)

forum topic: http://www.rockettheme.com/forum/joomla-template-galatea/260889-template-menu-editor-malfunction-in-the-subtitle-field?start=0#1303725

**Comment by mahagr** [comment]
Try CI.

**Comment by marktaylor46** [comment]
fix looks good :)
