### ISSUE TITLE
Menu editor's on/off toggle not working

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1439]
Using Gantry CI dev-1391b91b3 on Joomla 3.5.1, when using the on/off toggle on a menu item inside the menu editor, setting it to off does not seem to do anything, on frontend the menu item keeps showing just as if the toggle was set to on.

Please see pic.
![gantry_menutoggle](https://cloud.githubusercontent.com/assets/5719486/16772386/6416a0b0-4854-11e6-8461-e9629560e002.png)

**Comment by kat05** [comment]
Actually, when leaving the Menu editor for example by using the Joomla menu to go to the extensions manager and then returning to the menu editor, then the toggle is set back to ON for some reason.

**Comment by mahagr** [comment]
Might be issue in Joomla 3.5.1+ only.

**Comment by kat05** [comment]
I can confirm that this works just fine in an older version of WordPress as well as in latest 4.5.3.

**Comment by w00fz** [comment]
I can confirm this is broken in Joomla

**Comment by w00fz** [comment]
It appears that during validation some fields, including `ID` are lost. This causes issues with the `onMenuSave` event that skips the item since `$id` is 0.

Not sure what changed, I can't find anything in our commits that affected this.

**Comment by mahagr** [comment]
The issue was much worse than described here -- menu items were not really saved at all.
