### ISSUE TITLE
Override modules.php

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#144]
Guys, I wanted to modify the markup of the Module Titles and add additional `span` which I need in order to style the Titles in specific way.

In Gantry 4 there was a `modules.php` file by default in `root/templates/gantry/html` but there is no such override in `hydrogen` by default.

So here's what I did:

1. Copied the `modules.php` file from `root/templates/system/html`
2. Created the `root/templates/g5_hydrogen/html` folder and pasted the `modules.php` file there
3. Refreshed the website and I got the following:

![Alt Text](http://i.imgur.com/CGVsXSB.png)

I do understand that you want to stay away from any overrides and stuff but can you please include an override only for the `modules.php` file? It will be really helpful (ever for your template developers) :)

If you do not want to include an override for the `modules.php` file, can you please let me know how to override it properly :) Yah, the error message is quite self-explanatory but I cannot figure it out at the moment :)

```
Cannot redeclare modChrome_none() (previously declared in C:\wamp\www\gantry5\templates\system\html\modules.php:15
```

**Comment by adi8i** [comment]
#129  https://github.com/gantry/gantry5/tree/develop/themes/hydrogen/joomla/html

**Comment by JoomFX** [comment]
I'm not sure I understand what you mean @adi8i  :)
I cannot find the answer of my questions in the issue you pasted above :)

**Comment by adi8i** [comment]
You can try that module.php, has been updated and will be in the next beta in `g5_hydrogen/html`

**Comment by JoomFX** [comment]
oh, i see it now :)
thanks Adi, I will test it after 15mins :)

**Comment by adi8i** [comment]
```
<?php
/**
 * @package     Joomla.Site
 * @subpackage  Template.system
 *
 * @copyright   Copyright (C) 2005 - 2015 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;
// Gantry Specific Module Chrome
function modChrome_gantry($module, &$params, &$attribs)
{
	$moduleTag      = $params->get('module_tag', 'div');
	$headerTag      = htmlspecialchars($params->get('header_tag', 'h3'));
	$bootstrapSize  = (int) $params->get('bootstrap_size', 0);
	$moduleClass    = $bootstrapSize != 0 ? ' span' . $bootstrapSize : '';
	// Temporarily store header class in variable
	$headerClass    = $params->get('header_class');
	$headerClass    = ($headerClass) ? ' class="' . htmlspecialchars($headerClass) . '"' : '';
	if (!empty ($module->content)) : ?>
		<<?php echo $moduleTag; ?> class="moduletable<?php echo htmlspecialchars($params->get('moduleclass_sfx')) . $moduleClass; ?>">
			<?php if ((bool) $module->showtitle) : ?>
				<<?php echo $headerTag . $headerClass . '>' . $module->title; ?></<?php echo $headerTag; ?>>
			<?php endif; ?>
			<?php echo $module->content; ?>
		</<?php echo $moduleTag; ?>>
	<?php endif;
}
?>
```

**Comment by JoomFX** [comment]
@adi8i does this `modules.php` file work for you?
I mean, I do not get any errors, the website loads fine, but it seems that it does not override the default one.

Can you add additional class on line 25, just after the `moduletable` class and let me know if it is rendered on the frontend for you :)

**Comment by adi8i** [comment]
i will try in 5 - 10 mins :)

**Comment by JoomFX** [comment]
thanks ;)

**Comment by adi8i** [comment]
Look the same for me, i will play a bit around

**Comment by adi8i** [comment]
@JoomFX i working fine, just add the class where you would like, for example
```
<<?php echo $moduleTag; ?> class="mycustomclass moduletable<?php echo htmlspecialchars($params->get('moduleclass_sfx')) . $moduleClass; ?>">
```

Then go to `module manager`, edit the module you want to display, go to `advanced` tab and from `module style` chose `gantry`

**Comment by JoomFX** [comment]
thanks @adi8i :)

@w00fz @mahagr but guys, are you going to leave it like this? I mean in G4 the user didn't have to select a special "Module Style" in order for the template override to be loaded.

The idea behind a Template override is to override the default behavior/layout. The user really shouldn't have to perform this additional step (selecting a "Module Style").

The Module Titles style (modules.php) are template specific. The user should not need to change the settings in the backend.

Please let me know what you think about this.

**Comment by adi8i** [comment]
This should take inherit from template :)

**Comment by kevlardev** [comment]
In the upcoming beta, the new modules.php override will be included with the gantry chrome. The defaults for the layouts will also be set to use the gantry chrome automatically so it will not have to be manually configured. The option is still there for you to manually override it to be some other chrome name should you wish.

**Comment by JoomFX** [comment]
@kevlardev thanks mate :)

*The defaults for the layouts will also be set to use the gantry chrome automatically so it will not have to be manually configured.*

This is how it should be :)

**Comment by mahagr** [comment]
Just a note on having custom ```html/modules.php``` in your theme:

This file is part of Joomla every Joomla template and really has nothing to do with Gantry. So it follows rules specified in Joomla.

You cannot just copy ```templates/system/html/modules.php``` into your template, as Joomla doesn't allow you doing that. Basically Joomla doesn't allow templates to override system chromes, which is a shame.

I'm finding this a bit confusing on a template as there are files that follow Joomla rules and then there are files that follow our rules. We have no control on the files that Joomla requires us to have.

**Comment by JoomFX** [comment]
thanks for the information @mahagr :)
