### ISSUE TITLE
How To Remove Lines and Boxes Offcanvas

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#1442]
First of all, thanks for Helium template :)

Working on Joomla, everything latest version.

I have offcanvas enabled Always to show in desktop also. There is a module for Menu in offcanvas.

However, there is one border line around all menu items; and a line each below every menu item. How can I remove these?

**Comment by w00fz** [comment]
Hey @rgblogs could you upload a screenshot pointing out to which lines exactly you are referring to?

**Comment by w00fz** [comment]
@rgblogs any more details you can provide?

**Comment by w00fz** [comment]
Ok I see what you meant. Fixed, will be available in next update.
