### ISSUE TITLE
WOFF2 font issue with Gantry 5.3.1

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1443]
Dealing with a clients site I discovered this a font load error. So I did a CLEAN install of Photon RocketLauncher on my LIVE server and updated from 5.2.18 to 5.3.1.
At 5.2.18 I had no font errors. At 5.3.1 I get this:
`Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
gantry-theme://fonts/sourcesanspro/sourcesanspro-regular/sourcesanspro-regular-webfont.woff2
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
gantry-theme://fonts/sourcesanspro/sourcesanspro-black/sourcesanspro-black-webfont.woff2
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
gantry-theme://fonts/goudybookletter1911/goudybookletter1911-regular/goudybookletter1911-regular-webfont.woff2
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
http://gantry5.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Article not found)`

You can see at [Font Issue](http://gantry5.com/parallaxtest/)

**Comment by w00fz** [comment]
Yes with 5.3.0 we updated Bourbon to latest and woff2 fonts need to exist.
We haven't updated the templates yet but you can go look for the woff2 file on the internet and upload it at the location it says, it will fix the problem.

**Comment by DanGthatRokGallery** [comment]
Thanks Djamil.

**Comment by w00fz** [comment]
👍
