### ISSUE TITLE
Grav - Unexpected characters near "_blank" href: "http://gantry.org/blog/php54-end-of-support

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1444]
Using Grav RC 1.1.0-rc.3 with Admin plugin and Gantry CI dev-d79c75a5d on MAMP running PHP 5.6.10, I am getting the following error when trying to view /admin/gantry. Please see pic.

```
Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Unexpected characters near "_blank" href: "http://gantry.org/blog/php54-end-of-support">More Details.</a>"" at line 238 (near "GANTRY5_PLATFORM_PHP54_WARNING: "You are currently running PHP <strong>%s</strong> which will soon no longer be supported by Gantry. Please upgrade as soon as possible. <a target: "_blank" href: "http://gantry.org/blog/php54-end-of-support">More Details.</a>"").") in "@gantry-admin/partials/js-translations.html.twig" at line 4."

Stacktrace:
#45 Twig_Error_Runtime in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:402
#44 Symfony\Component\Yaml\Exception\ParseException in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Inline.php:76
#43 Symfony\Component\Yaml\Inline:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Parser.php:513
#42 Symfony\Component\Yaml\Parser:parseValue in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Parser.php:240
#41 Symfony\Component\Yaml\Parser:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Yaml.php:65
#40 Symfony\Component\Yaml\Yaml:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/File/src/YamlFile.php:82
#39 RocketTheme\Toolbox\File\YamlFile:decode in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/File/src/File.php:296
#38 RocketTheme\Toolbox\File\File:content in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/File/CompiledFile.php:122
#37 Gantry\Component\File\CompiledYamlFile:content in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:96
#36 Gantry\Component\Translator\Translator:load in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:65
#35 Gantry\Component\Translator\Translator:find in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:32
#34 Gantry\Component\Translator\Translator:translate in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Twig/TwigExtension.php:124
#33 call_user_func_array in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Twig/TwigExtension.php:124
#32 Gantry\Component\Twig\TwigExtension:transFilter in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#31 __TwigTemplate_e76d19b9d2baad966d605c79686f145654e69ef1e6b53aac6f212b9f45943c30:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#30 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#29 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#28 __TwigTemplate_5489cce56ac8b799228732c8a31ed463ee1949789caf0621a1f619e5bf223f4c:block_javascript in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:167
#27 Twig_Template:displayBlock in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#26 __TwigTemplate_c3445a173186d3c1c83011044c80f2d4e5de21e2f64f24c5395bd838b366b801:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#25 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#24 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#23 __TwigTemplate_5489cce56ac8b799228732c8a31ed463ee1949789caf0621a1f619e5bf223f4c:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#22 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#21 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#20 __TwigTemplate_c6d7a6e065e1f382c0613fc8aec163a0a625ee781142f88be128b4813fe68d4c:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#19 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#18 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:366
#17 Twig_Template:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:347
#16 Twig_Environment:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Theme/AbstractTheme.php:162
#15 Gantry\Component\Theme\AbstractTheme:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php:162
#14 Gantry\Component\Router\Router:getErrorResponse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php:62
#13 Gantry\Component\Router\Router:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/gantry5.php:221
#12 Grav\Plugin\Gantry5Plugin:onAdminPagesInitialized in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#11 call_user_func in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#10 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:46
#9 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#8 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:299
#7 Grav\Common\Grav:fireEvent in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Processors/PagesProcessor.php:11
#6 Grav\Common\Processors\PagesProcessor:process in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:123
#5 Grav\Common\Grav:Grav\Common\{closure} in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:385
#4 Grav\Common\Grav:Grav\Common\{closure} in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:361
#3 call_user_func_array in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:361
#2 Grav\Common\Grav:__call in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:124
#1 Grav\Common\Grav:measureTime in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:124
#0 Grav\Common\Grav:process in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/index.php:38
```

![gantry_grav](https://cloud.githubusercontent.com/assets/5719486/16794346/9717f454-48d7-11e6-80b5-2693f2b6c313.png)

**Comment by w00fz** [comment]
Yah the lang is quite out of sync in grav, I'll add all the missing ones tomorrow 
// Djamil Legato
On Jul 12, 2016 23:56, kat05 <notifications@github.com> wrote:Using Grav RC 1.1.0-rc.3 with Admin plugin and Gantry CI dev-d79c75a5d on MAMP running PHP 5.6.10, I am getting the following error when trying to view Gantry via the Admin, please see pic.

Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Unexpected characters near "_blank" href: "http://gantry.org/blog/php54-end-of-support">More Details.</a>"" at line 238 (near "GANTRY5_PLATFORM_PHP54_WARNING: "You are currently running PHP <strong>%s</strong> which will soon no longer be supported by Gantry. Please upgrade as soon as possible. <a target: "_blank" href: "http://gantry.org/blog/php54-end-of-support">More Details.</a>"").") in "@gantry-admin/partials/js-translations.html.twig" at line 4."

Stacktrace:
#45 Twig_Error_Runtime in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:402
#44 Symfony\Component\Yaml\Exception\ParseException in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Inline.php:76
#43 Symfony\Component\Yaml\Inline:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Parser.php:513
#42 Symfony\Component\Yaml\Parser:parseValue in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Parser.php:240
#41 Symfony\Component\Yaml\Parser:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/symfony/yaml/Yaml.php:65
#40 Symfony\Component\Yaml\Yaml:parse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/File/src/YamlFile.php:82
#39 RocketTheme\Toolbox\File\YamlFile:decode in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/File/src/File.php:296
#38 RocketTheme\Toolbox\File\File:content in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/File/CompiledFile.php:122
#37 Gantry\Component\File\CompiledYamlFile:content in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:96
#36 Gantry\Component\Translator\Translator:load in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:65
#35 Gantry\Component\Translator\Translator:find in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Translator/Translator.php:32
#34 Gantry\Component\Translator\Translator:translate in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Twig/TwigExtension.php:124
#33 call_user_func_array in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Twig/TwigExtension.php:124
#32 Gantry\Component\Twig\TwigExtension:transFilter in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#31 __TwigTemplate_e76d19b9d2baad966d605c79686f145654e69ef1e6b53aac6f212b9f45943c30:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#30 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#29 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#28 __TwigTemplate_5489cce56ac8b799228732c8a31ed463ee1949789caf0621a1f619e5bf223f4c:block_javascript in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:167
#27 Twig_Template:displayBlock in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#26 __TwigTemplate_c3445a173186d3c1c83011044c80f2d4e5de21e2f64f24c5395bd838b366b801:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#25 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#24 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#23 __TwigTemplate_5489cce56ac8b799228732c8a31ed463ee1949789caf0621a1f619e5bf223f4c:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#22 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#21 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:403
#20 __TwigTemplate_c6d7a6e065e1f382c0613fc8aec163a0a625ee781142f88be128b4813fe68d4c:doDisplay in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:387
#19 Twig_Template:displayWithErrorHandling in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:355
#18 Twig_Template:display in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php:366
#17 Twig_Template:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Environment.php:347
#16 Twig_Environment:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Theme/AbstractTheme.php:162
#15 Gantry\Component\Theme\AbstractTheme:render in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php:162
#14 Gantry\Component\Router\Router:getErrorResponse in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/src/classes/Gantry/Component/Router/Router.php:62
#13 Gantry\Component\Router\Router:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/user/plugins/gantry5/gantry5.php:221
#12 Grav\Plugin\Gantry5Plugin:onAdminPagesInitialized in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#11 call_user_func in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#10 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/symfony/event-dispatcher/EventDispatcher.php:46
#9 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#8 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:299
#7 Grav\Common\Grav:fireEvent in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Processors/PagesProcessor.php:11
#6 Grav\Common\Processors\PagesProcessor:process in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:123
#5 Grav\Common\Grav:Grav\Common\{closure} in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:385
#4 Grav\Common\Grav:Grav\Common\{closure} in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:361
#3 call_user_func_array in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:361
#2 Grav\Common\Grav:__call in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:124
#1 Grav\Common\Grav:measureTime in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/system/src/Grav/Common/Grav.php:124
#0 Grav\Common\Grav:process in /Applications/MAMP/htdocs/grav_1.1.0-rc.3_ap/index.php:38

**Comment by mahagr** [comment]
Let's not forget Prime either.

**Comment by tcicit** [comment]
Have the same rerror! GRAV Version 1.0.10

**Comment by spacetook** [comment]
Same error here. Using Grav version 1.1.0-rc.3.

**Comment by w00fz** [comment]
This has been fixed now, try latest CI Build!

Thanks

**Comment by tcicit** [comment]
Whoops\Exception\ErrorException thrown with message "Call to undefined method RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator::resetScheme()"

Stacktrace:
#0 Whoops\Exception\ErrorException in D:\xampp\htdocs\grav-admin\user\plugins\gantry5\gantry5.php:159

Next Error after upgrad.

**Comment by kat05** [comment]
For me the latest CI build seems to have fixed the issue, I am no longer seeing any errors, but will keep digging.

**Comment by kat05** [comment]
@tcicit Make sure to go to the Grav Dashboard and clear all caches, that should resolve your issue.

**Comment by mahagr** [comment]
@tcicit Gantry doesn't run in Grav 1.0. Upgrade...

**Comment by tcicit** [comment]
Ok I'll try it. Thanks

**Comment by tcicit** [comment]
now it works :+1:
