### ISSUE TITLE
Particle Loading text is not loaded from language 

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1446]
Hi guys,

After updating to 5.3.1 the variable name GANTRY5_PLATFORM_JS_LOADING is showing instead of its text:

![gantry5-1](https://cloud.githubusercontent.com/assets/12487089/16802332/e3b439fe-4908-11e6-9f5b-c5fd937d9eb8.jpg)

**Comment by kat05** [comment]
Hi,

please see https://github.com/gantry/gantry5/issues/1437
The issue should be fixed in latest CI build.

**Comment by nicutor** [comment]
Thank you.
