### ISSUE TITLE
Hydrogen Mobile Menu Closing

### ISSUE THREAD

**Issue by francopa12** [gantry/gantry5#1447]
I have a site with a large mega menu and mobile menu.  If you are using mobile menu on a phone and you try to scroll up or down, it responds by closing the menu.  It is not going to the page so it is not responding as a click. Its is just closing the menu.  It only seems to happen in mobile browsers.  If you can grab an area without a link, it works fine.  But anywhere with a link is not working.  Is there a work around?
http://rksolutions.patrickfranco.com
I am just lost on this one.
Any help would be greatly appreciated.

**Comment by w00fz** [comment]
Thanks, nice catch.
This is an issue I actually introduced after fixing #1399 😞 

I'll sort it out.

**Comment by w00fz** [comment]
This is fixed now @francopa12.

**Comment by francopa12** [comment]
Hello,
I have updated the site and it has repaired this issue on mobile devices.  However, it is appearing in ie11.  If you open the menu, then move the cursor it immediately closes the menu.
Please advise.
Thanks for your help and awesome framework.
Patrick
