### ISSUE TITLE
Grav - Gantry updates on production sites need manual cache clear to prevent errors

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1449]
As discussed with @w00fz earlier, a manual cache clear via the Grav dashboard is necessary after a Gantry update, otherwise lots of issues/errors can arise.

**Comment by mahagr** [comment]
Yeah, update logic hasn't been implemented in Grav. I'll keep this open to allow us to deal with it.

**Comment by w00fz** [comment]
The issue is that Gantry in Grav installs in Production mode on. That's the bug.

**Comment by mahagr** [comment]
The issue exists also after user sets production mode on. So we need to fix this in the installer.

**Comment by mahagr** [comment]
@kat05 Can you test this please?
