### ISSUE TITLE
Trackpad issue when tapping on particles in Layout Manager

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#145]
Added a social Particle to the right of the mobile menu particle in the Offcanvas section, saved, created a new row and dragged the social particle there, saved, then hit undo and everything went crazy. :dancer: 

![screen shot 2015-04-28 at 1 36 06 pm](https://cloud.githubusercontent.com/assets/4026828/7377422/de5eec38-edab-11e4-8e54-6dc63e8b36b3.png)

**Comment by adi8i** [comment]
You must click something wrong, i did the same as you said and look well, nothing wrong :)

**Comment by FrugalGeek** [comment]
Added spacers on either side of a particle, then hit the undo button twice.

![screen shot 2015-04-28 at 1 56 27 pm](https://cloud.githubusercontent.com/assets/4026828/7377810/6bd1add8-edae-11e4-9257-4877d39cdead.png)

**Comment by adi8i** [comment]
I've played around with this, and don't get any issue, is working fine for me on win 8.1 + google chrome. Maybe you are using another browser or OS. :)

**Comment by kat05** [comment]
i can confirm this issue. i did not get it at first when trying to follow ryan's steps, but played some more with adding, moving, deleting particles as well as saving and undoing every now and then.

**Comment by kat05** [comment]
i have also had issues with particles duplicating themselves, for example i added just one spacer but at one point i suddenly had a 2nd one appear. the one that was added is greyed out and i am unable to edit or delete it. 
there are also issues with the grid percentages not adding up to 100%, please see pic as an example.
![g5_layoutmanagerissues](https://cloud.githubusercontent.com/assets/5719486/7379257/474bf04e-edb9-11e4-9ba0-8338677c6bc1.jpg)

**Comment by kat05** [comment]
![g5_layoutmanager2](https://cloud.githubusercontent.com/assets/5719486/7379483/dcae7d22-edba-11e4-9dab-93b50a2c5db0.jpg)

**Comment by kat05** [comment]
it seems once this happens, there is no way to fix things again. i've tried deleting all particles, when i tried to delete the last one, all settings froze with the 'drop here to delete' button stuck at the top and not going away anymore.
![g5_layoutmanager3](https://cloud.githubusercontent.com/assets/5719486/7379731/85950fc2-edbc-11e4-9994-aefa6aef920a.jpg)

**Comment by kat05** [comment]
![g5_layoutmanager3-1](https://cloud.githubusercontent.com/assets/5719486/7379762/b1a04ab4-edbc-11e4-98e1-3c9f3aa37eda.jpg)

**Comment by w00fz** [comment]
Anyway you guys can reproduce this in a consistent way? I'm having a hell of a time trying to reproduce this at all.
