### ISSUE TITLE
Outlines can't be unassigned from assignments tab on Joomla

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1451]
Outlines can't be unassigned from assignments tab, the outline it's reassigned after page refresh.

**Comment by mahagr** [comment]
This happens only if you unset all the items. It won't save.

**Comment by Danxetc** [comment]
Is there easy fix to this please? my client keeps forgetting to not assign

**Comment by mahagr** [comment]
Should be fixed now. :)
