### ISSUE TITLE
Joomla error page has malformed <head> section

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1452]
For some reason Gantry wrongly outputs the `<head>` section in Joomla error page. Some stylesheets are being loaded even before the `<head>` tag.

https://monosnap.com/file/eSVSwE1CCUR12PVhZjCg2LrOKNHnTy.png

**Comment by newkind** [comment]
Looks like it was caused by Error page not wanting to load jQuery.

**Comment by mahagr** [comment]
I think I want to fix it anyway...

**Comment by w00fz** [comment]
I can't reproduce this.

**Comment by newkind** [comment]
there was inline JS script coming from Atom that required jQuery and caused this

**Comment by w00fz** [comment]
Ok so not really a Gantry issue, nothing really to fix.
