### ISSUE TITLE
Grav - Invalid security token (edit)

### ISSUE THREAD

**Issue by spacetook** [gantry/gantry5#1453]
Hi,

I am using Grav version 1.1.0-RC.3 and the newest Gantry CI Builds (commit: 68d644745) for Grav.
However if I want to save my changes inside the Gantry menu, then it they won't get saved and I get the message:

**403 Forbidden
Oops, Invalid security token; please reload the page and try again..**

![grav-gantry3](https://cloud.githubusercontent.com/assets/20362400/16841685/a3a52332-49da-11e6-8041-ab5a2f28f5b7.jpg)

Tried it with firefox and chrome.

Edit: Fixed the scroll problem with "clear all caches"

**Comment by mahagr** [comment]
I think it can also be fixed by just reloading the page?

**Comment by spacetook** [comment]
Nope, won't work even after multiple refreshs using F5.
After a refresh, I type in my changes again an after clicking "Save styles" I get the same message again.
I have also tried to install a new and fresh install of gantry and updated everything of Grav, but without success.

**Comment by w00fz** [comment]
Can you please try updating Grav and Grav Admin to latest, as well as installing the new Gantry CI Build? I cannot reproduce this issue.

From your screenshot it also looks like you have some styling issues (no padding inside the grey container), which I don't get on my local.

**Comment by spacetook** [comment]
No, didn't worked.
Did a fresh install of everything.
Installed the newest Grav + Admin from the website (Grav v1.1.0 - Admin v1.1.1).
Update button of the admin plugin says "everything up to date".

Gantry CI Builds are the newest, downloaded them from the website.
(Last build was generated 5 hours ago (commit: 0b63f6274))

I have also deleted all caches.

Maybe I have to change something inside the plugin menu?

![gantry-plugin-menu](https://cloud.githubusercontent.com/assets/20362400/16894686/40e34258-4b5e-11e6-9112-df43571ddd6e.jpg)

**Comment by w00fz** [comment]
Uh, try disabling production. That really should be off by default.

**Comment by spacetook** [comment]
Tried if without success.

**Comment by w00fz** [comment]
hey @spacetook , can you send me your `user` folder so i can try to reproduce on my local?

**Comment by w00fz** [comment]
Any word on this? 😃 

Still waiting on the user folder, that would really help me debug the problem since I still cannot reproduce this issue at all.

Please drop the zip in PM on Gitter if you get the chance.

**Comment by spacetook** [comment]
Sorry for the delay. Was ill and had less time. Send you the files through Gitter :)

**Comment by w00fz** [comment]
Np, thanks for that! Appreciate it.
I'll look asap at the issue and hopefully I'll be able to reproduce.

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
Sorry to say @spacetook but I was never able to reproduce this issue. Have you tried the latest CI Builds recently?

**Comment by spacetook** [comment]
Yeah, it works now xD
No idea why I had so much trouble, I also tried hosting on Windows without success, but now it works on Windows therefore it should also work on Linux^^
Huge thanks anyway :)

**Comment by IrealiTY** [comment]
Sorry but how did you fix that issue? - did you install a new CI build? Did you just re-install gantry?

**Comment by mahagr** [comment]
There should be no need for CI builds as the issue is months old and there have been new releases.

**Comment by IrealiTY** [comment]
Well I was getting this particular issue on a fresh installation yesterday.

**Comment by mahagr** [comment]
Did reloading page help to fix the issue? Or is it still continuing?

**Comment by IrealiTY** [comment]
Didn't help, no. I'll try to setup a fresh setup later. (my 1st test was on a  fresh digitalocean vps)

**Comment by patrickbolle** [comment]
Same problem here. Fresh Digital Ocean VPS.

**Comment by mahagr** [comment]
Please see:

https://github.com/getgrav/grav/issues/1245

Fixed all `$_GET` parameters missing in Nginx (please update your nginx.conf)

**Comment by OleVik** [comment]
For anyone with the same problem using Caddy as the server, try the latest [configuration-example](https://github.com/getgrav/grav/blob/develop/webserver-configs/Caddyfile) in /grav/webserver-configs.

**Comment by ITSecMedia** [comment]
@OleVik Thank you!!!
