### ISSUE TITLE
Infamous `woff2` and missing fonts.

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#1457]
As we all know, when a font is missing, it will error out with the stream path `gantry-theme://fonts/..`. This is extremely useful and valuable from a developer stand point, because it triggers immediate intervention in adding the missing font.

However, ever since we upgraded Bourbon with G5.3, this has become especially common. The new Bourbon version requires a `woff2` font to be added and nobody (us included) ever did that before.

We need to suppress the stream at least when in PROD mode.

--
/cc #1331 - #1443

**Comment by mahagr** [comment]
I agree, lets get rid of it and just use the location where the file would be saved if user added it.

**Comment by nikola3244** [comment]
Nice fix! 
I was also thinking about almost same thing, with one addition: you guys could also put couple "if" statements in Bourbon scss file, and not load font file if it doesn't exist.

**Comment by w00fz** [comment]
The only problem is that once the file is compiled, it's done. Won't be able to ever catch missing files again.

**Comment by nikola3244** [comment]
Hm, I'm not quite sure that I understand.
CSS can always be recompiled again.
Even currently you have to recompile CSS again if you didn't had woff2 on
first compile.

**Comment by w00fz** [comment]
There is a new option in Bourbon's `font-face` mixin, `$file-formats`, which I think at some point we should hook up into.

/ ref: http://bourbon.io/docs/#font-face

**Comment by nikola3244** [comment]
Actually, I think I have a simpler fix. 😉
Will show you tomorrow, it's late here

**Comment by nikola3244** [comment]
I don't think that I like this solution (well, at least not the PHP part).
Anyway, take a look.

**Comment by w00fz** [comment]
I don't think it's a good idea to override bourbon core files. I see what you are looking for though.
My idea here is that the error on frontend about the missing font is good, not bad. Usually  this is going to be a problem only for developers and only at the beginning of development. Once sealed you won't really have to worry.

What I mentioned above with the `file-formats` it's still something additional I would like to address in the future. Right now you have to provide all the default file formats from Bourbon without exception, I'd like to have this declarable in the local font definition in yaml (`file-formats: [ttf woff svg]`) because there may be times where not all formats are available or simply they are not desired.

**Comment by nikola3244** [comment]
Yeah, `file-formats` addition sounds good.
So, yeah, good thinking.
