### ISSUE TITLE
Trans filter in WP has 'gantry5' textdomain hardcoded

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1459]
Right now when we want to use `|trans` filter in WP in themes we are limited to the hardcoded `gantry5` textdomain. We should change this to be dynamic with fallback to `gantry5`, so devs could pass the param with their custom textdomain name.

https://monosnap.com/file/uVEtJmH5P5Hw5EUN0nbR8FPIF5f8BD.png

**Comment by mahagr** [comment]
Because of `|trans` filter already takes parameters, I cannot add yet another one to pass custom textdomain. Instead I'm using the textdomain from the theme. For WP specific translations use the function provided by Timber.

@newkind Can you test this out?

**Comment by newkind** [comment]
Seems that it works fine :) Closing!
