### ISSUE TITLE
Mobile Menu Particle Takes Up Space on Desktop

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#146]
If you place a particle next to the mobile menu particle whatever pace (default 50%) the mobile menu particle takes up is left blank on the front end, squishing the other particle to the remaining 50% of the space.

Stacking vertically using rows works but creates a gap at the top.

**Comment by adi8i** [comment]
![capture](https://cloud.githubusercontent.com/assets/9744973/7377738/0e99c130-edf1-11e4-86c1-7d4f389506cb.PNG)

This is how it look like on full desktop, for this configuration, so menu particle and another one on the same row

![2](https://cloud.githubusercontent.com/assets/9744973/7377752/24350e14-edf1-11e4-8d63-fc8cda8a4fcc.PNG)

On mobile will look just fine:
![3](https://cloud.githubusercontent.com/assets/9744973/7377787/53cc8b66-edf1-11e4-9425-93c7e7acba8d.PNG)

Anyway i think you should not place anything on the same row with mobile menu, may be this is how it was designed to work, and is off cananvas, has  a limited width. 

A workaround would be to restrict this, so you can't place another module or particle on the same row with mobile menu, or add a tooltip somewhere to inform this. 
@w00fz  @mahagr

**Comment by FrugalGeek** [comment]
I spoke with @kevlardev about this issue when the offcanvas section was added and the intention was to have things stack vertically despite being in the same row. This seemed like a bug to me, rather than user error as any particle that does not render should not take up space as if it did.

**Comment by adi8i** [comment]
i haven't looked at code, but i think the menu render all the time so it take the space, but there is some css to hide it, and yes you are right, look like a bug

**Comment by w00fz** [comment]
I don't think this is an issue. You can place particles next to each other, yes, but in the ends it's up to end-user ensuring this is going to look good.
There's also an option in the Styles panel to increase the size of the offcanvas, in case 2 particles next to each other is the desired effect but it feels too narrow.

Anyway I assigned @kevlardev to the issue, maybe he has a better explanation for this and it is actually an issue that needs to be resolved.

**Comment by kevlardev** [comment]
Yes, we originally looked at forcing everything in the offcanvas panel to be vertically stacked regardless. However, the offcanvas position is not a 'mobile only' position, and with the addition of user configurable size, it allows users to create an offcanvas panel that could be much larger, even the size of the full page (for a sliding page effect) in which case it would be useful to have side by side layout.

We felt it best not to restrict people in how they use the panel and leave it up to their own discretion. In mobile breakpoints the items will all stack vertically using the same behavior as the rest of the layout.
