### ISSUE TITLE
An extra outline is added in the Italian Joomla package

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1461]
Hi,
I notice a small difference between two fresh installations. An extra **Hydrogen - Predefinito** outline is present there.
1. **Italian** Joomla package + Gantry 5.3.2
![gantry-on-joomla-it](https://cloud.githubusercontent.com/assets/3976174/17020140/5315e184-4f40-11e6-93e5-ed9d5e5157e7.png)

2. **English** Joomla package + Gantry 5.3.2
![gantry-on-joomla-en](https://cloud.githubusercontent.com/assets/3976174/17020154/65eeb8a8-4f40-11e6-8518-90a79b74a8f5.png)

It's normal ? What do you think @w00fz ?

**Comment by mahagr** [comment]
This is interesting.. Joomla installer uses `JText::sprintf('JLIB_INSTALLER_DEFAULT_STYLE', JText::_($this->extension->name))` to create the layout title and we do the same. That means that both Joomla and Gantry should end up using translated name.

I need to check if I have accidentally hardcoded the title...

**Comment by mahagr** [comment]
Yeah, I need to improve the logic slightly...

**Comment by mahagr** [comment]
Can you test if CI fixes the issue for you?

**Comment by mariantanase** [comment]
Here is the result on a new Italian Joomla installation with the latest CI .
![gantry-dev-on-joomla-it](https://cloud.githubusercontent.com/assets/3976174/17022408/11fc11ba-4f4e-11e6-89d6-7c13639164c2.png)
Great @mahagr !
