### ISSUE TITLE
New tabbed Particle UI like "Joomla Article" broken

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#1463]
I tested the new Particle "Joomla Article" with the new tabbed dialog (known as contentarray) and place this particle in the Layoutmanager. After open the modal settings and click on the tab "Block" i saw this:
![tabbed-particle1](https://cloud.githubusercontent.com/assets/20481746/17045551/893c4a70-4fca-11e6-938e-ea023875deea.jpg)
Then i click on the tab "Particle" and saw this:
![tabbed-particle2](https://cloud.githubusercontent.com/assets/20481746/17045562/a3e9e6e8-4fca-11e6-9f87-9457b2c4adb2.jpg)

Please checked this new function for the new tabbed content for particle and fixed asap. Thanks

**Comment by w00fz** [comment]
Thanks! I completely missed this one.
You can install the latest [CI Build](http://gantry.org/downloads#ci-builds) that comes with the fix in it.
