### ISSUE TITLE
"Save Assignments" not working, stays assigned to menus

### ISSUE THREAD

**Issue by Danxetc** [gantry/gantry5#1468]
I'm new to Gantry and testing with Hydrogen template.

I assigned "Hydrogen - Home" outline to "Home" menu, then saved the assignment. When I tried to "unassign", it stayed assigned, even though it said "Assignments Saved".

I've tried to reinstall the template and the Gantry 5 Component and started a new Joomla! site, but still wouldn't save and stayed assigned.

**Comment by nikola3244** [comment]
Confirming. J3.6.0 and G5.3.2
"Hydrogen Theme" menu, "Home" menu item can't be unassigned from "Hydrogen - Home" outline.

**Comment by w00fz** [comment]
I believe this is the same issue as #1451 so I'm marking it as duplicate and closing it for organizational purposes, you can subscribe to the other one.

Feel free to reopen if that's not the case!
