### ISSUE TITLE
Navigation position

### ISSUE THREAD

**Issue by samiradz** [gantry/gantry5#1470]
Hello,

I would like to use aikon Menu but I can't found the navigation position?
I don't understand how to use another Menu than Default menu from Hydrogen theme

Could you help me please.

I use joomla 3.6 and v5.3.1 / g5_hydrogen

Best regards

Sam

**Comment by w00fz** [comment]
With Gantry all you have to do is go in the Layout and create your own Position. Then you can assign the Joomla module to the position you just created.

Gantry uses the default Menu from Hydrogen only if you use the Menu Particle.

**Comment by JoomFX** [comment]
> Gantry uses the default Menu from Hydrogen only if you use the Menu Particle.

And you can change that by editing the "Menu" particle. By doing so, you can choose any of your Menus to be rendered by the "Menu" particle.
