### ISSUE TITLE
Duplication of "system outlines" does nothing

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1473]
I know that you should not be attempting to duplicate "system outlines" such as "error outline" but outline manager has a button has a "duplicate" button against these outlines and some members have used this only to find that nothing happens and no new outline is created at all? Maybe the button should be removed from system outlines or a message displayed?

**Comment by w00fz** [comment]
The Outline is actually getting duplicated but in the Users list, not the System one.
Check at the top of the list, you will see it there. System outlines cannot be duplicated in the system category, nor they can be deleted, this is because they are tied to the platform.

**Comment by marktaylor46** [comment]
Yes I see - But does it still make sense to allow duplicate of a system outline since it won't work as a system outline having been duplicated? Personally I think the duplicate option should be removed as I can't think of a practical use of it?

**Comment by w00fz** [comment]
It can be useful because a template might provide specific details about a system outlines that you might want to duplicate for other purposes.
This is different than using a Preset, because that would only give you the structure of the Layout. Duplicating an actual Outline gives you all the settings that come with it, Styles, Page Settings, Layout.
I think it makes sense to allow to duplicate a System outline.

**Comment by marktaylor46** [comment]
ok - I raised it because member was trying to create and "error" outline for a multilingual site (i.e. expecting to use an error page for each language rather than just making the content of that one outline have different language content. That's why I thought allowing this was confusing - but ok I can live with it.

**Comment by w00fz** [comment]
That's a good question actually, I'm not sure if joomla actually allows multi language for error pages. 
Might need to see if @mahagr has any idea about it.

**Comment by w00fz** [comment]
I reopened until we get more details about it

**Comment by marktaylor46** [comment]
The only issue is that the error outline has a particle directly on the layout with a specific language content... my solution was to change this to a module position instead, then assign modules to that positions but mark each one with the appropriate langauge in module manager - then the correct one gets loaded ok... So, I got around the issue, I just found myself questioning the merits of being able to duplicate a "system" outline that then turned into a "user" outline?

**Comment by mahagr** [comment]
System outlines aren't handled by Joomla but by Gantry. Right now they are hardcoded to use a single outline for all the languages. To be honest I don't think we should be changing that as we will soon(ish) be implementing language support for particles.

In the mean time user can use module positions to put translated particles into it. Its not perfect, but should work.

**Comment by mahagr** [comment]
Generally I agree with @w00fz here; its useful to be able to duplicate system outline as a normal one.
