### ISSUE TITLE
Gantry 5 admin panel not working - joomla

### ISSUE THREAD

**Issue by hryx82** [gantry/gantry5#1474]
Hello. When I try to access the component Gantry 5 displays a 2 errors and nothing else. Please help diagnose and fix my problem.

![problem](https://cloud.githubusercontent.com/assets/20682175/17174798/4ceca4e6-5404-11e6-8738-d45ba36086eb.png)

**Comment by w00fz** [comment]
That looks like a weird error, you should try reinstalling Gantry again. Seems like something is missing.

**Comment by hryx82** [comment]
Reinstall did not fix. Next the same mistakes.

**Comment by mahagr** [comment]
It looks like it tries to load whoops.css from wrong location.

I'm assuming you're using Joomla? Do you have another component that uses whoops?

**Comment by hryx82** [comment]
The problem already fixed. The reason was the location of the entire installation in the root folder instead of in a subdirectory. Thank for help.
