### ISSUE TITLE
Missing Translation in message required field

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#1477]
I have made an atom with required fields and test it in the modal. As i save with an empty filed this message appears like to see in screenshot (right bottom corner)
Can this be checked?

![g5-translate-error](https://cloud.githubusercontent.com/assets/20481746/17294571/01216040-57f8-11e6-8627-014a139eaf8a.jpg)

**Comment by hacki65** [comment]
Seems to be a cache problems. At a second test all is good ;)

**Comment by w00fz** [comment]
:+1:
