### ISSUE TITLE
Sorting of filenames in filepicker and imagepicker

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#1478]
As to see in the screen the filenames in the list of the imagepicker are always unsorted. Is it possible for a first improvement the set the sort order by names? It would be better to a file in the list.

Another improvement as see on the screen i have changed the text-alignment for the row "size" to the right and give a padding to the right of 20px.

![g5-filepicker](https://cloud.githubusercontent.com/assets/20481746/17294843/74c13362-57f9-11e6-8e5c-d5cd1504fee9.jpg)

**Comment by w00fz** [comment]
Done. Cheers!
