### ISSUE TITLE
TEXT not appearing in header 

### ISSUE THREAD

**Issue by ulyssedoris** [gantry/gantry5#1479]
Hello Team,

May be I am doing something wrong here, I am trying to include text in the header of the website. Every time I unselect image and type text e.g. ULYSSE DORIS, it goes back to the logo gantry 5 . I am looking for the same option that used to be in gantry 4. 

Thank You for taking the time to explain
![screen shot 2016-08-01 at 1 49 49 pm](https://cloud.githubusercontent.com/assets/13663636/17303489/f11062e0-57ee-11e6-9401-8f57da0b3465.png)
![screen shot 2016-08-01 at 1 43 17 pm](https://cloud.githubusercontent.com/assets/13663636/17303490/f111fea2-57ee-11e6-80ed-0e44fee753e6.png)
![screen shot 2016-08-01 at 1 42 55 pm](https://cloud.githubusercontent.com/assets/13663636/17303491/f115be5c-57ee-11e6-97de-ea9ef6d80a7f.png)
![screen shot 2016-08-01 at 1 42 12 pm](https://cloud.githubusercontent.com/assets/13663636/17303519/1b6db27c-57ef-11e6-9328-259000214697.png)

**Comment by w00fz** [comment]
Try overriding the Image and set it to empty.

**Comment by ulyssedoris** [comment]
Tried it this way and no changes. any other suggestions that I can possibly try?
![screen shot 2016-08-01 at 2 56 37 pm](https://cloud.githubusercontent.com/assets/13663636/17305464/7503b436-57f8-11e6-884f-c866e722ab95.png)

**Comment by w00fz** [comment]
This seems to work fine for me:

![gantry 5 dev - administration 2016-08-01 12-20-40](https://cloud.githubusercontent.com/assets/11734/17305993/66ec2196-57e2-11e6-87e1-cb494d907f51.png)

![home 2016-08-01 12-21-27](https://cloud.githubusercontent.com/assets/11734/17306007/7c2b3b6e-57e2-11e6-9dc0-3cb7854d6f52.png)

**Comment by w00fz** [comment]
One thing you could do is to use the `Custom HTML` particle instead, and write your link/text there. Although this should be working just fine.

Are you sure you don't have any `logo.html.twig` particle override in your `custom/` folder?

**Comment by ulyssedoris** [comment]
I followed the your screen shot and now it works fine! Thank You !

**Comment by w00fz** [comment]
You are welcome! 👍
