### ISSUE TITLE
How to use CMS contents other than com_content?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1480]
I've read this "http://docs.gantry.org/gantry5/advanced/content-in-particles". It seems to me this documentation is only talking about how to use Joomla contents. Is it possible for gantry to get contents from other components? Like k2, or community builder?

**Comment by mahagr** [comment]
Because of how Joomla works its not possible to get content from other components without writing a bunch of code to support them. Right now we do not have short term plans to add support to other than core Joomla functionality.

That said, if those components have a proper API to fetch content from them, its already supported as you can make function calls from twig files.

**Comment by newjie** [comment]
I am using Easyblog I really want to integrate its content with Gantry particles. Their content can be retrieved like this:
```
<?php
// Include the engine
include_once(JPATH_ADMINISTRATOR . '/components/com_easyblog/includes/easyblog.php');

// Only fetch 10 posts
$limit = 10;

// Category id's (one or more)
$options = array(1);

$model = EB::model('Category');
$posts = $model->getPosts($options, $limit);
```

I think what I need to do is modify some PHP files so I can do something like `easyblog.finder('category', options)`. But I have very limited knowledge about twig even PHP, so where should I start? Can you point me to some doc?

**Comment by mahagr** [comment]
You could create a simple class and register it to gantry from a plugin event, something like this:

```php
class Easyblog { ... }

class plgGantryEasyblog extends CMSPlugin 
{
    public function onGantry5ThemeInit($theme)
    {
        if ($this->app->isClient('site')) 
        {
            $gantry = \Gantry\Framework\Gantry::instance();
            $gantry['easyblog'] = new Easyblog();
        }
    }
}
```
