### ISSUE TITLE
New outline has all checkboxes in Content tab selected

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1482]
When you create a new Outline and go to the Content tab in WP, you can see that all checkboxes for fields are selected even though there were no modifications made to them. This causes YAML file to have unnecessary overriden values.

Screenshot : https://monosnap.com/file/BygG6YQXcoSsiM6PuqhSvxS9RcUjWF.png

**Comment by kat05** [comment]
I've just tried this on a Requiem Launcher running latest WP and Gantry CI build Version: dev-f5c21a302 / Released: August 4, 2016 and I am not seeing this issue.

**Comment by kat05** [comment]
I now installed Helium CI build Version: dev-f5c21a302 / Released: August 4, 2016 to that same installation and with Helium I can confirm the issue.

**Comment by mahagr** [comment]
@newkind Can you check what's different between Requiem and Helium? It might be using different values in content blueprints... Nevertheless, it sounds like a bug.

**Comment by newkind** [comment]
Content blueprints in Requiem and Helium are exactly the same, no changes.
