### ISSUE TITLE
Helium template: Base Outline->Particle Default->Logo/Image->SVG code invisible

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1483]
Took me a while to figure out there is some invisible codes in the textarea. This causes confusion.

**Comment by w00fz** [comment]
Can you elaborate? I see SVG code in the SVG content area.
What do you mean invisible?

**Comment by newjie** [comment]
![screen shot 2016-08-04 at 16 22 49](https://cloud.githubusercontent.com/assets/12814040/17417160/e4d5bb74-5a5f-11e6-8213-a1d82ec8ca8d.png)

This is what I see in my chrome. I have multiple helium installation, they are have this issue.

**Comment by newjie** [comment]
Happens in chrome, in firefox I can see it.

**Comment by w00fz** [comment]
This is mine in Chrome, seems fine. Perhaps you have an outdated version?

![gantry 5 dev - administration 2016-08-04 13-27-13](https://cloud.githubusercontent.com/assets/11734/17417239/2eb22ca0-5a47-11e6-8be8-65ddfcff91e2.png)

**Comment by newjie** [comment]
Using iMac, happens in safari too. Just updated chrome to latest 52.0.xxxx version, still happens. Strange.

**Comment by mahagr** [comment]
Could there be some SVG code in another outline, which then gets used?

**Comment by kat05** [comment]
I have just checked on Joomla 3.6.2 and Chrome Version 52.0.2743.116 (64-bit) on Mac 
and I can see the svg code just fine in the Base outline with Gantry and Helium CI build dev-f5c21a302.

![heli_svgchrome](https://cloud.githubusercontent.com/assets/5719486/17430620/8090ce24-5af5-11e6-8cf5-875b173d9e53.png)

**Comment by kat05** [comment]
Just checked Safari as well and I have no issue there either.

![heli_svgsafari](https://cloud.githubusercontent.com/assets/5719486/17430687/0c4ca8b6-5af6-11e6-9d22-1c42d4e944a0.png)

**Comment by w00fz** [comment]
@newjie: did you ever sort this out?

**Comment by newjie** [comment]
It seems good now. I can't reproduce the problem.

**Comment by w00fz** [comment]
Cool! 👍
