### ISSUE TITLE
add section into areas

### ISSUE THREAD

**Issue by ulyssedoris** [gantry/gantry5#1484]
Trying to add a background image into feature area. 
I followed the instructions in 
http://docs.gantry.org/gantry5/advanced/customizing-theme-files
 so far it has not worked  for me. Should the files be named custom.yaml and custom.twig.html ? 
![screen shot 2016-08-05 at 1 07 08 pm](https://cloud.githubusercontent.com/assets/13663636/17444400/c097bf24-5b0d-11e6-8069-12c7d60bd98d.png)
![screen shot 2016-08-05 at 1 07 27 pm](https://cloud.githubusercontent.com/assets/13663636/17444411/ccb91302-5b0d-11e6-81c2-427f2950ae89.png)
![screen shot 2016-08-05 at 1 07 40 pm](https://cloud.githubusercontent.com/assets/13663636/17444410/cc188338-5b0d-11e6-8e01-1ba55822a06e.png)

**Comment by mahagr** [comment]
Code should be looking except that by looking the content in second screenshot, you do not have variable called attr_background defined. I think the correct one would be: `segment.attributes.background` instead.
