### ISSUE TITLE
Helium Template: Updateserver not implemented in templateDetails.xml

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#1488]
Hello,

there is currently no link in the section "<updateserver>" in file templateDetails.xml so Joomla! did not know about any updates for the template. The download source is available.
Can this please fixed? I have also checked the CI Build with same result.

![helium-updateserver](https://cloud.githubusercontent.com/assets/20481746/17478497/797965c8-5d6c-11e6-968f-b7f57869c906.jpg)

**Comment by mahagr** [comment]
Will be there in the next Helium release.
