### ISSUE TITLE
Where are outline specific information stored?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1489]
I've read the docs but couldn't find the answer to this question. 
I am asking this for two reasons:
1) I want to find out how to assign a *.scss (other than custom.scss) file to a specific outline. The Doc says in order to have it automatically compiled, I need to insert some codes to a twig file - I know how to do it if I want to attach a scss file to a certain particle, but not a certain outline.

2) I noticed that in Helium theme, the "home-particles" outline is getting a class "home-particles" for its body element. I couldn't find where this is set in the GUI, so I guess it must be some twig file related to the outline? Or, is there any twig file related with a certain outline? - If yes, then question  1) is answered too.

**Comment by mahagr** [comment]
1) To add scss file from a particle: http://docs.gantry.org/gantry5/advanced/css-js-twig#compiling-custom-scss-files

2) Body class `g-home-particles` gets added by core Gantry and its named by the outline preset which was used to create the layout in the outline.
