### ISSUE TITLE
Same Menu, 2 Particles, 'active' class only present in 1 Menu

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1492]
if you have a 2 menu Particles pointed at the same Joomla menu only the menu particle which loads first on the page will get the "active" class added to the current menu item.

As a practical example you may want to have a menu set only to display submenu items within a single parent menu item while the user is on parent menu page or one of the sub menu pages... like a split menu. However, this secondary menu will not show which page is active currently.

http://www.rockettheme.com/forum/joomla-template-interstellar/261797-both-active-menu-and-sidebar-highlighed

**Comment by w00fz** [comment]
This is working fine for me. Tested with Hydrogen, same setup: Menu in navbar, new Menu particle in the sidebar (pointing to same menu) with Starting level 2. The active class is added in both.

I believe the user is using an old version of Gantry 5.

**Comment by blizam** [comment]
In Requiem with the standard top horizontal and a menu particle in the FixedSide Section the latter doesn't get the active class... I'm not sure what to look for that might be Requiem specific in that but I'll try and dig into it.

Gantry 5.3.5

**Comment by blizam** [comment]
I take it all back! Every word! Seems fine (blush)

**Comment by w00fz** [comment]
Can you try with hydrogen? One possible cause might be that Requiem uses a custom implementation of the menu particle, you should check the custom folder for that.

Other than that the menu logic is handled the same for all templates internally by gantry and it shouldn't make a difference.

Also you able to reproduce this on a local installation of Requiem or only on the user site?

If you see this is specific to Requiem please open an internal issue there.
