### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sooryakalai** [gantry/gantry5#1493]
Hello!!!
First is first I am using 
Wordpress
Theme: Helium (v5.3.2 / g5_helium)
Gantry Version 5.3.2
Timber Version 1.1.2

I am using the new 'Helium theme' and I am facing this error when I try to assign a menu to the menu particle.
![500 int error](https://cloud.githubusercontent.com/assets/20853406/17519088/0e26a130-5e68-11e6-83d3-3865d416cf99.PNG)

The code from item.html.twig 

```twig
{% extends 'forms/fields/select/selectize.html.twig' %}

{% block options %}
    {{ parent() }}
    {% if gantry.menu is not null %}
        {% for group, items in gantry.menu.getGroupedItems() %}
            {% if items|length %}
            <optgroup label="{{ group|capitalize }}">
            {% for key, item in items %}
            <option
                    {# required attribute structures #}
                    {% if key == value %}selected="selected"{% endif %}
                    value="{{ key }}"
                    {# non-gloval attribute structures #}
                    {% if field.options.disabled in ['on', 'true', 1] %}disabled="disabled"{% endif %}
                    >{{ item.spacing|raw }}{{ item.label }}</option>
            {% endfor %}
            </optgroup>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}
```

PS: I am not a pro-web developer / programmer.  I have been looking for a solution online, and am very desperate to get over with this issue. Any kind of help is highly appreciated.

Regards,
Soorya Kalaiselvan

**Comment by mahagr** [comment]
I believe its a bug; will investigate it more.

**Comment by mahagr** [comment]
@sooryakalai 

I was not able to reproduce the bug so please check if its fixed for you by installing latest CI build!

Please report back if the issue was fixed.

**Comment by sooryakalai** [comment]
I am installing the latest CI build. Please give me some time.

Thanks,
Soorya Kalaiselvan

**Comment by sooryakalai** [comment]
Hello!!!
I checked with the latest CI build, but the problem still persists 
![500 int error2](https://cloud.githubusercontent.com/assets/20853406/17560403/90b1c436-5f3f-11e6-824b-c46e0f780243.PNG)
NOTE: you can see the latest build version on the background.

Regards,
Soorya Kalaiselvan

**Comment by mahagr** [comment]
Can you enable debug mode from Gantry to see if there's anything else it reveals?

**Comment by sooryakalai** [comment]
I am afraid, it is already in development mode. I checked with production mode never the less but it still throws out the same error.

**Comment by sooryakalai** [comment]
Same thing in the debug mode as well.

**Comment by mahagr** [comment]
Just fixed admin to show more information if debug mode has been enabled from the plugin. Can you try with new CI build?

**Comment by sooryakalai** [comment]
Should I install "wordpress-tpl_g5_helium_develop.zip" again? or is it " wordpress-pkg_gantry5_develop.zip"

**Comment by mahagr** [comment]
its the later file, first one is the theme which doesn't have the bug. :)

**Comment by sooryakalai** [comment]
Sorry about my "lack of knowledge on this subject ;) I am a Mechanical Engineer by profession. I am just loving web development specially because of Gantry framework. I am both grateful and exited about my amateur web dev skills. :)

**Comment by sooryakalai** [comment]
![500 int error resolved](https://cloud.githubusercontent.com/assets/20853406/17561515/0717ca68-5f44-11e6-8e2f-8e1be8b28b8d.PNG)

You have no idea how my face looks right now. :smile: :laughing: 

With lots of thanks,
Soorya Kalaiselvan

**Comment by mahagr** [comment]
Cool so it was indeed fixed. :)

**Comment by igor-gp** [comment]
phew! we had the same error popping up and the latest CI fixed it, thanks @mahagr

**Comment by antonbw** [comment]
Hi I am a newb but I am having this same issue with a clean install of gantry 5 and Helium hatried both the latest versions 5.4.12 and latest CI but still unable to get menu ?
