### ISSUE TITLE
No Block or Inheritance fields for contentarray particle

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1497]
Wordpress 4.5.3, Gantry and Hydrogen 5.3.2

No block or Inheritance fields are available for the Wordpress Posts particle (connect array). Possible issue with any particle using tabs?

Furthermore, clicking the Inheritance tab and then clicking back to the Particle tab removes tab fields - if not all in one go then progressively with repeated clicking between Inheritance and Particle.

**Comment by mahagr** [comment]
Can you show us a screen shot; for me the particle works as expected.

**Comment by dudewithamood** [comment]
Now you see it...

![image](https://cloud.githubusercontent.com/assets/15866807/17588647/b5d60fba-5fd0-11e6-859a-5bf411d97658.png)

Except that...

![image](https://cloud.githubusercontent.com/assets/15866807/17588656/c4c7a9de-5fd0-11e6-8cd1-adc635fbdf6e.png)

...and...

![image](https://cloud.githubusercontent.com/assets/15866807/17588667/cfe5dee4-5fd0-11e6-8706-4b68b37b5a2c.png)

:-(

Click back to Particle and then to Inheritance... and then do it again...

![image](https://cloud.githubusercontent.com/assets/15866807/17588699/ef84238c-5fd0-11e6-985a-8345a2d56cbe.png)

...going, going...

![image](https://cloud.githubusercontent.com/assets/15866807/17588707/fb11d21c-5fd0-11e6-9035-99df933457b1.png)

**Comment by mahagr** [comment]
Which browser are you using? Does it work better on Chrome/FF? I'm not having any issues in my tests.

**Comment by dudewithamood** [comment]
Same in all browsers.

Inspecting the html it's all there but when the tab is clicked the related pane does not receive the 'active' class, which is why they do not display.

Then when clicking back to Particle the active class is being removed the secondary tabs underneath Particle, which is why things start disappearing.

There are no JavaScript errors.

I've deactivated all plugins other than Gantry and Timber, and cleared the custom directory.

It's happening on my localhost as well as live hosted server.

Not sure what else could be affecting - will try a fresh install next...

**Comment by mahagr** [comment]
@w00fz Do you have any idea what may cause this?

**Comment by w00fz** [comment]
It's already fixed in CI

**Comment by dudewithamood** [comment]
Awesome. Thank you.

**Comment by mahagr** [comment]
@dudewithamood Can you try CI build and confirm if the issue has been fixed for you?

**Comment by dudewithamood** [comment]
Confirmed. Thank you.

**Comment by dudewithamood** [comment]
@mahagr Now that this is working in the latest release I have a question... why has CSS Class and Tag Attributes been included outside of the tabs when these are already part of the block fields?

**Comment by mahagr** [comment]
I don't know :) @w00fz @newkind ?

**Comment by mahagr** [comment]
Thanks @JoomFX. And yeah, I did miss your name. :)

**Comment by JoomFX** [comment]
No problem at all Matias.
I created the particle but you polished and changed many things so it is as good as it is :wink:

**Comment by dudewithamood** [comment]
Thanks @JoomFX - appreciating this particle greatly. I haven't played in Joomla for some time now so am a little out of touch with what's happening there. No worries, was simply curious.

FYI I replicated it for a version that would allow single post/article selection (#1503) and the feeling seems to be that this variation should happen within the contentarray particle.
