### ISSUE TITLE
Field type input.imagepicker and input.filepicker bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#15]
When trying to use the input.imagepicker or input.filepicker in Styles i was trying to set background image for header area i was getting this when i hit save.

500 Internal Server Error
Oops, failed to parse passed in variable header-image: /Joomla_3.4.1/templates/g5_hydrogen/images/macbook.png.

![2015-03-28 23 28 18](https://cloud.githubusercontent.com/assets/10489911/6883243/d67e15da-d5a4-11e4-9461-e325821e7fab.jpg)

**Comment by w00fz** [comment]
How are you setting up the SCSS for that field?

**Comment by w00fz** [comment]
Also can you share your setup for the field in Styles?

**Comment by DamirPecnik** [comment]
For styles field i was using this:

    file:
      type: input.videopicker
      label: Header Image
      default: ""

i was trying to get a value in scss with this $header-image to see what will get parsed but i didn't get to that step because when i added the input field to gantry settings and tried to save it i got that error.

**Comment by mahagr** [comment]
I think we need to wrap it inside url() for the styles. I will mark this a bug.

**Comment by w00fz** [comment]
Yah I guess before triggering the SCSS compilation the Styles should be normalized, like if it's a path or a URI we wrap it inside a `url()`. 

It is kind of annoying though because if I put `background-image: url($header-bg-image);` in the  `_header.scss`, it is totally valid and should be all the Compiler cares about. 

Instead, the variables are parsed before compilation. Is it us or the leafo compiler parsing these vars?

**Comment by mahagr** [comment]
It is leafo. Variable needs to be always defined and set, otherwise the compiler will fail to compile it.

**Comment by w00fz** [comment]
We need to add the `url()` before passing it to the compiler as we discussed.

**Comment by w00fz** [comment]
Actually quoting with `"` does the trick as well.

**Comment by mahagr** [comment]
Might be a bit trickier than I thought as the variable handling is pretty darn complicated in scss, it seems. I think we need to explicitly tell in our blueprints what we would like to do with the value.
