### ISSUE TITLE
hydrogen - centered inline images not displaying centered

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#150]
for inline images (added in the article editor), when using float left or right, the images display correctly either left or right.

however, centered images are not aligned correctly, please see pic.
![g5_hydrimgcenter](https://cloud.githubusercontent.com/assets/5719486/7384145/741b253e-edf2-11e4-991b-ea0999aea9c9.jpg)

**Comment by adi8i** [comment]
Confirmed, but is not related to Gantry5, this is a joomla bug. :)

**Comment by kat05** [comment]
i see it working fine in both protostar and beez and we have addressed it some time ago in our pre-gantry and gantry4 templates too. :)

![g5_center_beez](https://cloud.githubusercontent.com/assets/5719486/7384999/c6b627e8-ee02-11e4-8409-8616e1838663.jpg)
![g5_center_protostar](https://cloud.githubusercontent.com/assets/5719486/7385000/c6b8253e-ee02-11e4-950a-93e94c08a89f.jpg)

**Comment by adi8i** [comment]
weird, i've tried with protostart, i will try one more time

**Comment by adi8i** [comment]
You can see this too, as i understand is not a bug, but the template should support that feature. :) 
https://github.com/joomla/joomla-cms/issues/6862#issuecomment-97316734

**Comment by kevlardev** [comment]
We actually do have this css from protostar already in the joomla.css that is part of nucleus. Ill take a closer look and see whats causing it to not work properly

**Comment by kevlardev** [comment]
Ive fixed this for for both regular images being centered as well as images containing captions (figure) being centered. Was due to some rules in nucleus overriding the joomla ones.
