### ISSUE TITLE
Existing assignments get removed when assigning new items

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1501]
If you have existing layout assignments and then go and add new assignments, all existing assignments are lost.

**Comment by caleb** [comment]
I thought I was going crazy, or that I was selecting mutually exclusive assignments…

**Comment by dudewithamood** [comment]
Yes, I noticed it a few weeks ago but thought it was part of another issue I was having with assignments on one particular site. It does cause one to question ones sanity for a brief moment :-D

**Comment by mahagr** [comment]
Sounds like the same issue as in: #1451

**Comment by dudewithamood** [comment]
Not sure if it's the same but it certainly sounds related - one fix to solve them all?

**Comment by mahagr** [comment]
I removed duplicate tag for now; I also think they may be related. I also need to check if I can reproduce this exact issue. Which platform are you on? Joomla or WP?

**Comment by caleb** [comment]
I am on Wordpress (version 4.5.3).

**Comment by mahagr** [comment]
@w00fz This seems to be issue in javascript when sending data back on save. It only sends data from changed values, not the ones that were already set.

**Comment by mahagr** [comment]
Not sure why this only works in Joomla.

**Comment by w00fz** [comment]
It's not the JavaScript, it's the twig rendering the items that are on as `disabled`, when the page loads.

**Comment by dudewithamood** [comment]
Wonderful, thank you.
