### ISSUE TITLE
"joomla article" particle "block" and "inheritance" tabs are blank

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1504]
I just tested this in Citadel and G5.3.2. I dragged a "joomla article" particle on to a section in the base outline - both the "block" and "inheritance" tabs of the particle settings are completely blank? Furthermore if you then return to the "particle" tab the subsection buttons no longer function and you get a JS error in the console:

TypeError: i.find(...) is null main.js (line 2, col 25818)

![2016-08-15_09-54-41](https://cloud.githubusercontent.com/assets/11683218/17660076/de1c2382-62ce-11e6-918c-4ddc6562f0da.png)
![2016-08-15_09-54-30](https://cloud.githubusercontent.com/assets/11683218/17660079/dfccf92c-62ce-11e6-8fa1-44ee1f193e35.png)
![2016-08-15_09-54-11](https://cloud.githubusercontent.com/assets/11683218/17660081/e1f378ca-62ce-11e6-958a-02b97edb24ca.png)

RT Forum report here http://www.rockettheme.com/forum/joomla-template-kraken/262054-bug-in-joomla-articles-contentarray-particle

**Comment by mahagr** [comment]
This issue exists also in WP for some users. I'm not able to reproduce this either in Joomla or WP.

**Comment by marktaylor46** [comment]
Here's a video of it in Citadel RL and G5.3.2.

http://screencast.com/t/dQhA4wEm

**Comment by dudewithamood** [comment]
This looks like the same as #1497 which appears fixed in CI build.

**Comment by marktaylor46** [comment]
i confirm that I just tried CI build and it is indeed now fixed :)
