### ISSUE TITLE
RTL collapse icon has a problem.

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1507]
The icon for collapse in category menu don't obedience from gantry's bootstrap.the icon that show in the movie must placed on the right of web page. look at the movie in below link please:
http://screencast.com/t/i706FDyhS
I use joomla

**Comment by w00fz** [comment]
This is not an issue in Gantry. 
In your video the `bootstrap-gantry.css` has `float: right;` which I assume is the expected behavior, however `bootstrap-rtl` comes from Joomla itself.

**Comment by mahagr** [comment]
I bet you have the same issue in all Joomla templates, including default ones. The content which you had in screencast doesn't come from Gantry, but from Joomla. Please verify the issue with Protostar and report the bug to Joomla issues.
