### ISSUE TITLE
Wordpress Post Format Request

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1510]
There have been many request for the Posts Format feature in WordPress on RT Forum maybe to add that in Gantry 5?
https://codex.wordpress.org/Post_Formats

**Comment by mahagr** [comment]
@newkind What do you think?

**Comment by newkind** [comment]
This is not a Gantry 5 thing - it's a theme thing. Post formats are defined in theme and used by theme and Gantry 5 doesn't prevent it in any way. If someone wants post formats in their theme he should add them by himself.

We can have a discussion about this when it comes to our premium themes but this is not a place to discuss it.

**Comment by DamirPecnik** [comment]
OK Noted ...
