### ISSUE TITLE
submenu text, is not rtl in rtl language

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1511]
In the level1 , 2 ,3 ... of menu,when i use rtl language,the title of submenu is not rtl.I set that with custom CSS but i think it must by default is ok.

**Comment by newkind** [comment]
Which theme do you use ?

**Comment by saman222** [comment]
Hydrogen

**Comment by saman222** [comment]
hi
i see this problem is occur again.look at this:
http://www.screencast.com/t/qL9P09ogYR

**Comment by mahagr** [comment]
@saman222 Can you create a new issue from this?
