### ISSUE TITLE
CSS style stay in mobile view but menu hidden

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1513]
If i set for the menu block custom css class,when front end switch to mobile view,class stay but menu hidden and go to offconvas.for example i set custom background color and shadow for menu with use css class; then if switch to mobile view,menu go to offconvas and the shadow or background color not hidden.i solve that with css selector but that's not right way.

**Comment by w00fz** [comment]
Can you upload a screenshot or video of the issue? I'm not quite understanding what you mean.

**Comment by adi8i** [comment]
When menu is moved to offcanvas `hidden` class is automatically assigned to menu block, it works fine with latest CI.

![capture](https://cloud.githubusercontent.com/assets/9744973/17938798/2f2dbcb4-6a30-11e6-8eae-10331c52e449.PNG)

**Comment by w00fz** [comment]
So this is a non-issue?

**Comment by saman222** [comment]
http://screencast.com/t/w5oKXRFrE8

**Comment by w00fz** [comment]
This doesn't look like an issue to me. What you want to do is style the `.shmenu` class to remove shadows / borders / backgrounds when in mobile mediaquery:

http://docs.gantry.org/gantry5/tutorials/media-queries#using-media-queries-on-your-site
