### ISSUE TITLE
"Fullwidth (Boxed Content)" always shows as default in the Layout Manager

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1515]
Hey guys,

It seems that the default setting for the "Layout" option for each section in the Layout Manager is always "Fullwidth (Boxed Content)". So, whenever you save the settings, this value is applied.
Can this be improved as it looks like a bug?

Here, [this video](https://youtu.be/IpABIPQJk1c) shows what I mean :wink:

**Comment by mahagr** [comment]
You could have shown this in 10 second video, lol.

**Comment by JoomFX** [comment]
Come on Matias, I'm just trying to entertain you with longer videos :smile: 

You know me, sometimes I go in unnecessary details :wink:

**Comment by mahagr** [comment]
Nevertheless, the issue is that `0 == '' = true`. I think I need to cast the integer to a string...

**Comment by mahagr** [comment]
That was a fun one (NOT!)
