### ISSUE TITLE
How to remove new row?

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1516]
I add new row and i want to delete it.
Tip: My row is empty and i don't use any particle or position.
How to remove empty row in any section?

**Comment by JoomFX** [comment]
The new row will disappear automatically if empty. Watch [this video](https://youtu.be/i_ztI-NNQCE).

If you speak about sections - you cannot remove them from the admin. You need to edit the layout YAML file. Have look at [this section](http://docs.gantry.org/gantry5/advanced/creating-layout-presets) in the Gantry 5 documentation.

**Comment by saman222** [comment]
OK,tnx a lot
