### ISSUE TITLE
Particles are displayed randomly in layout manager

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1517]
Wordpress, dev-1c8e4560a3, no idea how to reproduce it's really randomly.

Usually only one particle is displayed in another section.

**Comment by w00fz** [comment]
Could it be you have a corrupted `layout.yaml`?

**Comment by adi8i** [comment]
Ok, let's me check.

**Comment by adi8i** [comment]
```
version: 2
preset:
  image: ''
  name: default
layout:
  /top/: {  }
  /navigation/: {  }
  /header/: {  }
  /showcase/: {  }
  /feature/: {  }
  /container-main/:
    -
      - /main/ 75: { }
      - /aside/ 25: { }
  /subfeature/: {  }
  /addons/: {  }
  /bottom/: {  }
  /footer/: {  }
  /copyright/: {  }
  /offcanvas/: {  }
```

**Comment by w00fz** [comment]
```
/container-main/:
    -
      - /main/ 75: { }
      - /aside/ 25: { }
```

Try changing main and aside to `'main 75':` and  `'sidebar 25':`

**Comment by adi8i** [comment]
Looks fine now, thanks.

**Comment by alisamii** [comment]
I have actually seen this happen often.

Even on a clean install, in the layout manager, for example, above-a, above-b and above-c which are supposed to be in main show up in feature. The particles are still in main, but they also appear in feature.

I have also seen that a single particle, for example, footer-a which has a width of 25% is also in extension, and there it says it has a size of 100, but it displays oddly. Next time I see it, I will take a screenshot.

But for now, look at this text-based replication

```
extension
|--  extension-a 33.3% --|--  extension-b 33.3% --|--  extension-c 33.3%  --|
—————————————————————————————————————————————————————————————————————————————
footer
                                                  |--    footer-a 100%    --|
|-- footer-a 25% --|-- footer-b 25% --|-- footer-c 25% --|-- footer-d 25% --|
—————————————————————————————————————————————————————————————————————————————
```

**Comment by gaelicwinter** [comment]
I found this inside my layout.yaml for just one section.  Showing the section above and below for completeness:

`  /container-header/:
    -
      -
        'headerleft 10': {  }
      -
        'headermain 80': {  }
      -
        'headerright 10': {  }
  /container-showcase/:
    -
      -
        'showcasemain 50':
          -
            - position-module-9189
      - 'position-module-9592 50'
  /container-slideshow/:
    -
      -
        'slideshowleft 10': {  }
      -
        'slideshowmain 80': {  }
      -
        'slideshowright 10': {  }`

Also attaching a screenshot of what that looks like in layout manager for that outline.  This is using gantry 5.3.6 and Sienna 1.0.1 on Joomla 3.6.4.

![sienna2](https://cloud.githubusercontent.com/assets/6510266/19840733/61b129a0-9eba-11e6-8860-b0a5d311373c.PNG)

I also occasionally get corruption like this:

![sienna](https://cloud.githubusercontent.com/assets/6510266/19840738/8135dcda-9eba-11e6-8a9b-7d598a09c734.PNG)

Now that I know how to fix it...

**Comment by kat05** [comment]
Sounds very much like this issue: https://github.com/gantry/gantry5/issues/1460

**Comment by mahagr** [comment]
@gaelicwinter 

Looks like the yaml out there has been corrupted or was broken in the first place.

Try manually removing this from yaml: `- 'position-module-9592 50'` and redo it.

**Comment by marktaylor46** [comment]
Just a note here - I see this often in the forum but have never been able to recreate it. But, the "fix" is quite straightforward. Look at the preset that your outline is using (show at the top of the page next to the word "LAYOUT". Then use the "LOAD" button on the outline and load that exact same preset again. This will repair the layout.
