### ISSUE TITLE
Outline names should use capital letters

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1520]
This was first mentioned during Remnant pre-release testing and has been reported in the internal bugtracker under REMNANT-86.

According to @w00fz  this seems to be a Gantry issue and it has been mentioned by Reggie that it's also present in other themes such as Salient and Antares.

Please see pic, the outlines should use Capital names.

![remn_outlinescapitals](https://cloud.githubusercontent.com/assets/5719486/17965481/21f71148-6abd-11e6-9f48-c13a3d3a01f8.jpg)

**Comment by w00fz** [comment]
It's weird though, because in Hydrogen this is fine:

![gantry 5 dev - administration 2016-08-25 10-32-06](https://cloud.githubusercontent.com/assets/11734/17979403/374b2682-6aaf-11e6-9ec1-41a55d6ab302.png)

**Comment by w00fz** [comment]
Never mind my last comment, it's fine only in the Presets tab but not Outlines.

**Comment by w00fz** [comment]
Fixed
