### ISSUE TITLE
Assignments global filter box doesn't work

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1521]
Just noticed that the global filter input box in Assignments page doesn't work in 5.3.4.

**EDIT** : it works, but it doesn't refresh the page. When you type something into the input, check the "Hide unassigned items" and uncheck it again, you'll see the filtered content.

https://monosnap.com/file/EZwsVTPiNGnZMHfNVMm6ufxgnaXqNH.png

**Comment by w00fz** [comment]
Fixed, btw you are on an old version, those toggles have changed in the latest version, they are now labels "All" and "None"

**Comment by newkind** [comment]
Yep, that was for the Remnant sample content where I work on stable ;)
