### ISSUE TITLE
input.number not accepting floats

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1524]
Gantry shows a warning to check fields if there is a dot in number input. 
Any other integer works.

W3C allows floats in this type of input. (https://www.w3.org/TR/html-markup/input.number.html#input.number.attrs.value)

**Comment by w00fz** [comment]
That's probably the browser, we are not doing anything with input number, other than just loading the HTML5 field of it [see here](https://github.com/gantry/gantry5/blob/develop/platforms/common/templates/forms/fields/input/number.html.twig). Are you passing in any `pattern` ?

**Comment by mahagr** [comment]
Yes, looks like a limitation in the browser; its just plain number field. In generally those HTML5 fields seem not to work that well in most browsers.

**Comment by nikola3244** [comment]
@w00fz Nope, no patterns, just a simple input. 
And I did checked that file, nothing seemed strange to me. So, I thought there might be some JS that can be improved.

 
Anyway, it seems like I will have to file a bug to Chromium.
Can be closed if it's not a Gantry's fault.

**Comment by nikola3244** [comment]
If someone encounters this bug in future: https://bugs.chromium.org/p/chromium/issues/detail?id=79732
