### ISSUE TITLE
Exclamation icon adding infinitely

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1526]
If a field has an invalid value and one clicks multiple times on "Apply and Save", warning icon (`fa-exclamation-triangle`) gets added on and on.

![screenshot_2016-08-25_15-54-31](https://cloud.githubusercontent.com/assets/15911110/17971705/3ce0fa2c-6adc-11e6-964b-aa9c35e4b9b3.png)

**Comment by nikola3244** [comment]
It happens in Chromium 52.0.2743.116 (64-bit), but not in Firefox 48.0.2

**Comment by w00fz** [comment]
Thanks, fixed now
