### ISSUE TITLE
Showcase Section bug

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1527]
If i set my showcase background color option to #ffffff then my link in this area is white that means not can see that.look this code in this file and imagine i want use white color for showcase background:
https://github.com/gantry/gantry5/blob/7019d025972463cf11e82aa22aba065fe70e5896/themes/hydrogen/common/scss/hydrogen/_showcase.scss#L10

**Comment by JoomFX** [comment]
This is a theme decision.
Hydrogen is designed to have a solid background color for the Showcase section.
You can easily modify the link color in the Showcase section by adding the following code to your [custom.scss](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) file:

```
#g-showcase {
	a {
		color: #555555;
		&:hover {
			color: #000000
		}
	}
}
```

"Recompile CSS" under the "Base" outline and refresh.

**Comment by saman222** [comment]
OK tnx. I was added something like your code to my custom.scss . I think this is a bug but if you say this is a theme decision i don't have any talk. :blush:
