### ISSUE TITLE
gantry-media:// protocol not being recognised in custom.scss

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1530]
Copied from bitter chat:

In the citadel theme, the file `/site/templates/rt_citadel/scss/citadel/particles/_video.scss` uses this rule syntax a few times:

`background: url('gantry-media://owlcarousel/play.svg') no-repeat;`

I tried using this same rule syntax in another template (requiem) using the `gantry-media://` protocol to link to an image in my custom.scss file.

Gantry was unable to resolve the url to the actual file, and I had to revert to using this syntax:

`background: url(‘/images/owlcarousel/play.svg') no-repeat;`

I had this problem with 5.3.2, and still have it with 5.3.4 and latest CI build.

Seems to work in core scss files but not in custom scss files

FYI, when inspecting the element with the inspector, the rule shown is exactly what is in the custom.scss file:

`background: url('gantry-media://owlcarousel/play.svg') no-repeat;`

**Comment by JoomFX** [comment]
Did you try to `@import "dependencies";` ?
If it works in the theme's core SCSS files, but not in `custom.scss`, then `@import "dependencies";` should fix it.

**Comment by JoomFX** [comment]
Sorry, disregard my previous comment - I don't think that `@import "dependencies";` has anything to do with the Streams.

By the way, I just tested it and the following code works just fine in G5.3.4 (without `@import "dependencies";`)

```
#g-feature {
	background: url('gantry-media://bgshowcase.png') repeat;
}
```

**Comment by alisamii** [comment]
Hi Ivo,

Of course the first thing I do when I set up a template is I add my default custom scss directory which has the @import "dependencies"; statement plus other imports that I usually use.

I tried this using requiem, topaz and hydrogen and got the same problem.

I created a file called _video.scss in the custom/scss/partials directory and then imported it into custom.scss. On compile, the compiled CSS file referenced the image using the gantry-media:// protocol.

I moved it into the default scss directory (not custom) and recompiled and this time it worked.

**Comment by alisamii** [comment]
I wonder if the streams that parse this protocol have a problem parsing it when it is in a nested custom structure???

**Comment by w00fz** [comment]
Copy the file `play.svg` into `custom/owlcarousel/play.svg` and it should work.
What happens is that the stream is failing to find that file.

**Comment by alisamii** [comment]
@w00fz why would `owlcarousel` need to be directly in `/custom/`? Should the stream not be able to find it in `/images` in the site root?

`/site/images/owlcarousel/`

**Comment by mahagr** [comment]
BTW, there's a fix related on this in latest CI. While it shouldn't fix the issue, it should at least point to a directory which could contain the file. What is the resolved path for the file when using CI build?

**Comment by w00fz** [comment]
Have you tried with the latest CI Build?

**Comment by mahagr** [comment]
I'm closing this issue as I'm assuming its solved.
