### ISSUE TITLE
Menu Option

### ISSUE THREAD

**Issue by francopa12** [gantry/gantry5#1533]
I am using the Helium Theme.  Is it possible to shut off the dropdowns?  I am want the sub items to show, I just don't want them to dropdown.  I just want them visible.  It would just help to keep the url structure consistent.  I basically just want to use the menu item as a heading.  I am just not seeing the setting to make this work.  Or maybe it is just not possible.  
Any help would be greatly appreciated. 
Thanks
Patrick

**Comment by w00fz** [comment]
I'm not quite sure what you are trying to do, perhaps you have an example you can share?
Please note also that the menu is a particle, so you can override it or create your own custom one.

**Comment by mahagr** [comment]
Maybe @francopa12 wants split menu functionality, where first level is always there and second level shows up with the current submenu..?

**Comment by francopa12** [comment]
I figured out that I could just create a module to display links using the proper menu structure.  It works fine.  However, the most recent upgrade will not allow the menu items to be shut off.

**Comment by JoomFX** [comment]
@francopa12 This was a bug which is now fixed. You can read more about it in [this issue](https://github.com/gantry/gantry5/issues/1532).

You can either install the latest [CI Build](http://gantry.org/downloads#ci-builds) (which contains the fix) or just wait for the next release.

**Comment by w00fz** [comment]
Try the CI Build, I fixed that!
