### ISSUE TITLE
Layout Manager - inherit text not shown when the section are wrapped in a container

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1537]
Hey Djamil,

Is it by design that the "Inheriting from Base Outline" text is not shown on layouts where the sections are wrapped in a container?

Here, [this video](https://youtu.be/_n5O-hna1dU) shows everything.

**Comment by w00fz** [comment]
Yes that's on purpose. When you have a container you can have side by side section and it can take too much room to display the whole label on top, I can't control that via css so for consistency it's always displaying it below in the lock to save room.
When it's a simple section than its always alone so I know there is room to display it fully.

**Comment by JoomFX** [comment]
I see.
Thanks Djamil.
