### ISSUE TITLE
Typo in nucleus.css

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1538]
Found a typo in CSS

/plugins/gantry5/engines/nucleus/css-compiled/nucleus.css?ver=57bee9c3

```
img {
    width: auto\9;
    max-width: 100%;
    display: inline-block;
    vertical-align: middle;
    border: 0;
    -ms-interpolation-mode: bicubic;
}
```

**Comment by w00fz** [comment]
That is not a typo, it's a CSS hack for IE 7, 8 and 9 (we only care about 9). Only IE9 is able to read that line so only IE9 will set the width to auto.

If you had:

```css
.my-div {
    width: 50px;
    width: 200px\9;
}
```

That would mean that every browser will set the `my-div` width to 50px, however IE 7, 8 and 9 will set it to 200px.

**Comment by mr910** [comment]
Learned something new today! w00t w00t

**Comment by essiele** [comment]
I'll remember that!

Thank you.

QLS
