### ISSUE TITLE
Simple Counter particle stops counting

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1539]
There was a XENON forum post about the counter stopping once the Seconds reached 00. So I tested with v1.2.1 - J362 and Gantry 5.3.4 and the user was correct. Once seconds reach 00 the entire countdown stops.

**Comment by w00fz** [comment]
This is really not a Gantry issue but a template specific Particle problem. I also know this was intentionally set like this for the template but it's an option in the SimpleCounter JS plugin. You can change the `continue` option to continue past 0.

https://github.com/arieh/SimpleCounter/
