### ISSUE TITLE
some disabled particles do not get 'greyed out' in the layout manager

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#154]
i've disabled everything in the 'settings' panel, then went to check the layout manager.
on the left side where you can create new particles etc, everything is correctly being 'greyed out'. however, on the right side in the actual layouts, only some of them get 'greyed out' which appears to be inconsistent and a bug of some sort. please see pics for an example.

![g5_particlesgrey](https://cloud.githubusercontent.com/assets/5719486/7401411/676e44be-ee89-11e4-98e6-79b9d549738c.jpg)

**Comment by w00fz** [comment]
Is this intentional @mahagr ? I know we talked about this but I can't remember if we left them enabled on purpose or not

**Comment by mahagr** [comment]
No, they should be all greyed out.

**Comment by w00fz** [comment]
Ok, see also #117 it is somehow related

// Djamil Legato // From iPhone //
