### ISSUE TITLE
slideshow particle not working

### ISSUE THREAD

**Issue by matt87vl** [gantry/gantry5#1549]
Hi, 
I have read old posts regarding this problem, but I did not find a solution :'(

I tried to install UIkit and Slideshows following video instructions from website. My Slideshow particle shows up in particle list and I try to add it to my Navigation area, but it says me "this particle needs UIkit installed" and slideshow images are shown one above other, without animation..

I checked webpage sourcecode and I noticed there is not link to UIkit stylesheets, even if I put both @import in place. Seems like a mistery..

I use WordPress.

**Comment by w00fz** [comment]
I don't think we have any particle that requires UIkit, perhaps you are using a third party particle? If that's the case you should contact them as this is for gantry5 issues only.

**Comment by JoomFX** [comment]
Hi @matt87vl,

The "Slideshow" particle will always show the UIkit notice, nomatter if it is already loaded or not.

From what you wrote in your comment, it seems that the "UIkit for Gantry5" atom is not properly installed and therefore it is not loaded.

Just go to the same website you downloaded the "Slideshow" particle from, find the "UIkit for Gantry5" atom there, read the documentation and make sure you follow all the steps in the installation instructions - make sure you place the "uikit" folder in the correct location.

If you are still not able to make it work then, as Djamil said, contact the developers of those particles - there is a "Contact us" link in the footer on their website.

**Comment by w00fz** [comment]
Thanks @JoomFX
