### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#155]
in the 'settings' panel, when toggling any of the settings on or off, a js error pops up

Uncaught TypeError: Cannot read property 'find' of null - main.js?55417fd8:1

![g5_findofnull](https://cloud.githubusercontent.com/assets/5719486/7404765/f8e04748-eead-11e4-9d07-1e3fe9d3b1ea.jpg)

**Comment by w00fz** [comment]
Good catch.
