### ISSUE TITLE
Editing NEW Outline title from Outlines Manager doesn't persist

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1555]
If you edit an Outline title on a NEWLY created Outline from the Outline Manager it doesn't save

Outline Manager
Create a New Outline
Afterwards, click pencil icon to edit title, hit enter... no spinny loader indicating save and it does in fact not save

Editing titles on existing Outlines from within the Outline manager works fine

**Comment by blizam** [comment]
quick note... the reason for doing this is because the Outline name you set when creating a new outline gets the Theme name prepended to it ... and I always want to delete that after creating a new Otuline

**Comment by w00fz** [comment]
Fixed, however in Joomla it is advised to keep those template prefixes because when you have more than one Gantry5 theme, it will get confusing in the Joomla Templates list.

**Comment by blizam** [comment]
makes sense :) ty ty

**Comment by kat05** [comment]
This is working fine now in latest CI
