### ISSUE TITLE
Language String Update

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1557]
Looks like there are a couple areas that need some Language string updates. Please see attached images:

GANTRY5_PLATFORM_SAVED
GANTRY5_PLATFORM_JS_SAVE_SUCCESS
GANTRY5_PLATFORM_LAST_SAVED

![screen shot 2016-09-06 at 4 59 44 pm](https://cloud.githubusercontent.com/assets/5002814/18292549/7a065908-7453-11e6-97e1-4959c1e84f18.jpg)
![screen shot 2016-09-06 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/5002814/18292550/7a102370-7453-11e6-8ad8-cda339770ac0.jpg)

**Comment by w00fz** [comment]
Are you sure you are all up to date? This is looking good to me with latest Gantry and latest Helium

**Comment by mahagr** [comment]
Also make sure you have reloaded JS files. It works for me, but I remember I had to hard reload page to get the strings to show up the first time.

**Comment by simmonsr** [comment]
re-upload of gantry 5 framework solved this issue. thanks @w00fz
