### ISSUE TITLE
WordPress: Assign particle to page

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1560]
What do you think? I know it have been requested, I wish I had it too, few times. I tried and it works pretty well, with my code you can select only a page for now but it could be extended.

PS: I wanted to send a PR, but no idea where, i modified `block` files and you have them under `common` this changes are needed on wp only.

**Comment by mahagr** [comment]
There's existing implementation for assigning widgets/modules/particles to pages, but it only exists on Grav/Prime right now. The implementation uses the same code as outlines. But I have not yet thought how to implement this in WP.

You can also PM me for faster discussion.

**Comment by mahagr** [comment]
Closing as duplicate for #1059
