### ISSUE TITLE
Padding & Margin Adjustments

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1561]
Just wondering, why aren't there any classes for left and right??

**Comment by newkind** [comment]
You mean `nopaddingleft` and `nopaddingright` ?

**Comment by mr910** [comment]
@newkind - yeah. I didn't notice at first, but someone was looking to remove it for some of their content.

**Comment by mr910** [comment]
Just for clarity - Do they exist and they're just missing from documentation or they don't exist and will be included in the next release?

**Comment by w00fz** [comment]
Oh actually I'm not sure, I thought you guys figured out they existed already.

**Comment by mariantanase** [comment]
Exists only nopaddingtop and nopaddingbottom classes. But I think will work fine if you add two more classes: **nopaddingleft** and **nopaddingright** on **_utilities.scss** :
```
.nopaddingleft {
	padding-left: 0 !important;
	.g-content {
		padding-left: 0 !important;
	}
}
.nopaddingright {
	padding-right: 0 !important;
	.g-content {
		padding-right: 0 !important;
	}
}
```

**Comment by w00fz** [comment]
Thank @mariantanase , we will get to this soon.

Can you have a look at it @newkind / @hexplor ?

**Comment by mr910** [comment]
@mariantanase - good look on this one! Looking forward to seeing this updated in docs once it's taken care of.

**Comment by newkind** [comment]
I'll add it once I'm done with my coffee ;)

**Comment by w00fz** [comment]
Thanks Jakub, should we add them in the themes variations also?

**Comment by newkind** [comment]
Not sure about that. I checked it when I was pushing this commit and looks like we only have `nomarginall` and `nopaddingall` in our variations. I think we added only these two to not clutter it too much. I can add it if you want me to though.

**Comment by w00fz** [comment]
No i think it's fine. They aren't common usages .

**Comment by w00fz** [comment]
Although we might need to document them.

**Comment by newkind** [comment]
@FrugalGeek ? :)
