### ISSUE TITLE
Save instances of Particles for later use

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1564]
Hello,
it would be nice if we could drag an instance of a particle (e.g. custom html) to the sidebar of particles, so they can be used easily multiple times. 

Is this already possible?

**Comment by mahagr** [comment]
It kind of is. To do this you need to create an unused outline and clone particle to there. Maybe not the fastest way to do it, but at least it works.

**Comment by joomlabeat** [comment]
Hey @mahagr , can you elaborate a bit on how to clone a created instance of a particle that I have on one of my outlines, to that new outline?

**Comment by mahagr** [comment]
I'm assuming that you are on the latest version and have an outline with the particle you want to save for later use.

Just go on and create a new outline like "Particle collection" and go into it. Drag the particle which you want to clone from the list and edit it. When you have particle open, click on **Inheritance** tab and select clone. Locate the particle, check the checkboxes and save.

Or if you are using particle in multiple places, just inherit it. In that way any changes you make to the particle will be reflected to all outlines.

**Comment by joomlabeat** [comment]
I thought I had updated Gantry to its latest, after I found the update notification message some days ago. Persisting asking for fetching new update information in the updates manager, it didn't show anything. Then I checked my gantry version and it was 5.2.xxsomething version. I had to manually get the last version and update it. Now I see the inheritance tab. 

Thanks for the information.

**Comment by mahagr** [comment]
Yeah, there's something going on with Joomla updates, usually it works, sometimes those just stop working.. I think that Joomla disables updates if it for any reason fails to fetch the data and doesn't restore updates until you have manually fetched the updates.
