### ISSUE TITLE
Social particle could use an 'icon only' option

### ISSUE THREAD

**Issue by DjSlash** [gantry/gantry5#1565]
For easy usage, the social particle could use an 'icon only' option, so that one still can have a "title" tag. It allows for an accessibility improvement.

(of course, this can also be achieved by overruling the particle code, but that's not everyone's cup-of-tea)

**Comment by w00fz** [comment]
Implemented:

![gantry 5 dev - administration 2016-09-09 15-06-31](https://cloud.githubusercontent.com/assets/11734/18404407/237f132e-769f-11e6-98b8-f84b1eedb8e6.png)

**Comment by kat05** [comment]
Works great with latest CI, tested with Remnant.
