### ISSUE TITLE
NextGen-Gallery Conflict

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1568]
**Running WordPress 4.6.1**

Got this ErrorException after attempting to set a 'favicon' and 'touchicon'.

**Cannot modify header information - headers already sent by (output started at /home/jvionnesnh/public_html/wp-content/plugins/nextgen-gallery/non_pope/class.photocrati_resource_manager.php:54)**

`Warning: preg_match() expects parameter 2 to be string, array given in /home/jvionnesnh/public_html/wp-content/plugins/nextgen-gallery/non_pope/class.photocrati_resource_manager.php on line 54`

Disabling 'NextGen-Gallery' allowed things to work as expected.

**Comment by mahagr** [comment]
Nothing to do with Gantry. You can get rid of the error by reporting the bug to the author of the plugin or disabling `display_errors` in php.ini (must for production sites).

**Comment by mahagr** [comment]
```php
if (isset($_REQUEST['page']) && !preg_match("#^(ngg|nextgen)#", $_REQUEST['page'])) $retval = FALSE;
```

This is the bad code. Never trust the value coming from user, especially if page comes from another plugin.
