### ISSUE TITLE
Joomla Module Styling not working on Error Outline!

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#1569]
Like the title says when you have Joomla Modules that allow to set styling elements within the module so not with the custom.scss then all these styling elements are not loaded on the Error Outline.

So basically every plugin, module or component that uses Joomla's build in add styling to head function are removed on error page. This results into a lot of extra work to have to manually add all these items to a custom.scss file. 

Now for a designer/developer this ain't a big deal. But for the average Joe this is impossible. As I said in previous questions and stuff I can't ask my customers to be fiddling with CSS or any other coding language as that is my Job that is why they hire our company to deal with stuff like that.

PS: Tested on latest Joomla/Gantry and with 5 different modules / 2 plugins. Haven't tested with a component but assumed that it would do the same thing.

**Comment by w00fz** [comment]
Thus is Joomla behavior, not Gantry. Joomla purposely prevents you to call certain methods to keep the error lean. 

If you think about it makes sense, you have an error and it needs to be displayed with the least possible way of causing additional errors, like for instance adding extra stuff in the head that might not be working etc..

// Djamil Legato // From iPhone //

**Comment by hennysmafter** [comment]
I agree partially that it could result into more errors but I also think that this should be a option. As Hydrogen and Helium are both templates that are developed for both end users and developers to be used we need to create it so that the end user won't have to code or modify but can simply do it by a on/off switch. 

I want to propose to build one option into the `Page Settings` of the `Error Outline` the option could be called `Enable Modules & Styling` this can then give a warning that if there are problems within a module it can create unexpected outcomes. 

When the option is on the error.php file loads all the styling and other elements.

**Comment by JoomFX** [comment]
@hennysmafter An year ago I was fighting with this too :smile: 
I don't think that it can be implemented in a nice way, it needs to be kind of a hack/workaround.
Have a look at Matias's comments in [this issue](https://github.com/gantry/gantry5/issues/918). They explain everything.

So probably it will be best to just leave it as it is :wink:

**Comment by mahagr** [comment]
The best thing to do would be to report a bug into Joomla issues and let them to fix this... No need to mention Gantry there, just point out that modules with CSS/JS do not work...
