### ISSUE TITLE
404 Not Found when trying to edit existing configuration

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#157]
trying to edit some of the existing configurations throws a 

404 Not Found
Oops, Configuration not found.

![g5_editconfig](https://cloud.githubusercontent.com/assets/5719486/7404939/786b5fb4-eeb0-11e4-83f9-eb4d526e8a86.jpg)

**Comment by w00fz** [comment]
See #118

// Djamil Legato // From iPhone //

**Comment by adi8i** [comment]
You manually added that?  i don't see that page in beta

**Comment by w00fz** [comment]
It's in the `develop` branch, she is testing the `current` status to filter out bugs before we release a beta :)
