### ISSUE TITLE
Default Outline, Enable Particle Twig Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1570]
There is a bug with the Enable Field for the Particle its not ticked.

So in Base outline its Enabled:
![2016-09-08 19 52 55](https://cloud.githubusercontent.com/assets/10489911/18362077/b6da09d0-7604-11e6-82f7-93758c7abc55.jpg)

But in the Default Outline its not ticked that its disabled:
![2016-09-08 20 04 37](https://cloud.githubusercontent.com/assets/10489911/18362117/db1e8460-7604-11e6-8a07-c230eb269ad7.jpg)

**Comment by mahagr** [comment]
Note to myself: Logo Toggle has different value but it still appears to be unchecked.
