### ISSUE TITLE
Layout Bug with Enabled Field  

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1571]
Particle is Enabled but in the layout its showing Grey....

![2016-09-08 19 54 34](https://cloud.githubusercontent.com/assets/10489911/18362176/0ffada30-7605-11e6-8058-1d7a1ab10d64.jpg)

**Comment by mahagr** [comment]
The behavior is correct but very confusing. When you save the particle, enabled=1 (or 0 if its unchecked) should be sent to the server, but at the same time there should be at least an indication that the particle has been disabled in particle defaults, thus not showing up in frontend no matter what the value is in here. 

Personally I think we should still allow admin to change all settings for globally disabled particles to allow him to configure all the particle instances before turning it back on.
