### ISSUE TITLE
Tag Attributes in the Layout Manager no longer work

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1577]
Hey guys,

Since 5.3.3, the Tag Attribute field in the LM does not work. The value is not rendered on the frontend.
The last working version is 5.3.2.

![tag-attr](https://cloud.githubusercontent.com/assets/7753940/18441003/e8edde44-7913-11e6-9db9-f368ca430e0d.png)

**Comment by mahagr** [comment]
It does work for me. Tested both Joomla and WP.

**Comment by JoomFX** [comment]
Hey Matias,

It works in the "Home" outline, but not in Default/Base.

Have a look at [this video](https://youtu.be/kdPHcSxGi0o).
Then, if you install 5.3.2, it starts working again.
Something in 5.3.3 broke it.

**Comment by w00fz** [comment]
This might be related to #1580

**Comment by w00fz** [comment]
This is solved now, please see #1580 for more details.
