### ISSUE TITLE
"Gantry 5 Particle" module in the latest CI

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1578]
Hey guys,

There seems to be something different in the latest CI build that changes the "Gantry 5 Particle" module in Joomla's Module Manager.

In the CI build, the particle fields get the override checkbox which, in my opinion, should not be there. This checkbox should only be visible in the Gantry5 Admin (Template Manager).

Have a look at [this video](https://youtu.be/uTzm44m6Mg0).

**Comment by w00fz** [comment]
Related: #1552

**Comment by mahagr** [comment]
I'm only seeing checkboxes inside tabs (article particle), can you verify that the issue is the same for you? @JoomFX

**Comment by JoomFX** [comment]
@mahagr Yes Matias, the issue affects only particles with Tabs (good spot).

**Comment by JoomFX** [comment]
Thanks 😉
