### ISSUE TITLE
Collapse/Expand Collection List items

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1579]
I have been thinking about this for a while, and I think I may have mentioned t in Gitter once, but I think the ability to collapse and expand the items in a collection list (inside a particle) is really very valuable.

I have a Gallery particle where in some cases I have 40+ images in the gallery. The collection list items have a lot of input options. Even on a 27" screen, I can only see 2 full item panes and part of the next 3 items below it.

If I need to change an item, let's say **Item 24** I have to scroll down a long way to find the item. If the items were collapsed, I could quickly find the one item I need to modify. Adding a filter would make that even faster.

Additionally, when setting up lots of collection list items, it would be helpful from a development standpoint to be able to follow a workflow such as:

1. Start with all items expanded
2. Fill in/populate item 1
3. Collapse Item 1
4. Fill in item 2
5. Collapse Item 2
6. Etc

This way, as I complete all the items, I will only have collapsed items listed, and I will be able to quickly verify that I have completed all the items properly.

See this mockup of what I think this could look like:

![module__schools_-_au_-_city_-_gold_coast_-_image_gallery_-_en__mod_gantry5_particle__-_the_language_house_-_administration](https://cloud.githubusercontent.com/assets/1498512/18481213/b3ce6c2e-79db-11e6-9bad-e3116524c076.jpg)

**Comment by hennysmafter** [comment]
:+1:

**Comment by w00fz** [comment]
It's a good idea 👍

**Comment by alisamii** [comment]
I don't know if it is possible, but it would be nice to have the ability, when using the single-item edit pane, to have a **Apply and Next** button next to the **Apply** button. This way, you can work with single items in sequence without opening the fill multi-item pane.

The reason I am asking for this enhancement is because I have come across a major slow-down while trying to edit a collection list with 90 items in it. I clicked **Apply** on the multi-item edit pane more than 30 minutes ago, and I am still waiting for it to close.

I cancelled the **Apply** process on a previous attempt at editing the 90-item pane, and I lost partial content in the items (item names disappeared and some items where randomly deleted from the list).

Clicking on each item successively, then applying, then clicking on the next item is not very efficient. But, if I could click on **Item 1**, edit it, then click on a button **Apply and Next** to move to **Item 2**, I would save a lot of time.

**Comment by w00fz** [comment]
This is now implemented. Note that I didn't add an Apply and Next because I think that's overkill, you can just edit in multi mode for that.
Also the filtering works like in the other sections but is a bit different, instead of filtering by title of the card, it filters by field label, which i think is a lot more useful.
For instance in Social Particle, you can filter by `icon` and get at a glance all the icons fields alone.
You are also able to collapse all and expand all or just individual ones.

Thanks for the suggestion!
  
![oct-06-2016 10-57-01](https://cloud.githubusercontent.com/assets/11734/19164242/ff37bae6-8bb3-11e6-93af-7f77557369e0.gif)

**Comment by alisamii** [comment]
Hi Djamil,

This looks and works great...except for one small usability issue (IMHO)

If you have 40 items in the collection list, it used to sort the list across then down.

So, you used to see something like this:

```
Item 1                  Item 2
Item 3                  Item 4
Item 5                  Item 6
```

Now, it is sorting down then across:

```
Item 1                  Item 21
Item 2                  Item 22
Item 3                  Item 23
```

The tab order is correct, but the display is less friendly.

Was this done by choice or by accident (because the particle settings, etc are down then across) and is it possible to revert to an across then down layout)?

![module__schools_-_au_-_city_-_adelaide_-_image_gallery_-_en__mod_gantry5_particle__-_the_language_house_-_administration](https://cloud.githubusercontent.com/assets/1498512/19166949/fa0daaac-8c09-11e6-9155-bbc1da4e95f2.jpg)

**Comment by w00fz** [comment]
I had to treat those cards as columns (like in Styles and Settings and Assignments). This was necessary because otherwise collapsing would keep the card blank occupying the same height of the sibling (before they were flex).
I don't know how this can be workarounded.

**Comment by alisamii** [comment]
OK, so it was on purpose.

If a solution is found, great. But this is a major improvement as is, so kudos for a great implementation.

**Comment by w00fz** [comment]
Yeah apparently the css3 columns specification doesn't implement any option for a left-to-right order.
At some point I want to rework these cards across the whole admin and find a better solution than CSS3 columns since they have proven quite unreliable for many different cases.

For the moment though, have to leave with this!

**Comment by alisamii** [comment]
@w00fz would flex box not help? Flexbox may have a better way of addressing these things.

**Comment by w00fz** [comment]
No won't help, flex box is how it was, but it won't allow to fully collapse a card, by principle flex box preserves the siblings at same height. Result is you will have the cars hrader and the rest of the card blank.
