### ISSUE TITLE
Particle Block Tag Attributes Inheriting issue

### ISSUE THREAD

**Issue by MaksymJ** [gantry/gantry5#1580]
Hi,

have a small issue ... 
in "Base Outline" -> in "Header" section added "Custom HTML" particle and applied in "Blocks" tab simple data attributes:

![1](https://cloud.githubusercontent.com/assets/16582788/18489733/ecdfc830-7a0f-11e6-8d8f-1bcd3dcfe8a8.png)

so, "Hydrogen - Default" as usual shows that "Header" is inheriting from "Base Outline".

![2](https://cloud.githubusercontent.com/assets/16582788/18489774/11fc7942-7a10-11e6-91bc-a03b1f41c347.png)

so, i am expecting that it will also show those applied block tag attributes to that particle ...

but it dont ...

![3](https://cloud.githubusercontent.com/assets/16582788/18489873/94495910-7a10-11e6-8b1d-b911997002a4.png)

am i missing something? or it works like that?

Best Regards,
Maksym.

**Comment by w00fz** [comment]
Can you show a screenshot for the Inheritance settings of that inherited Custom HTML?

**Comment by MaksymJ** [comment]
sure, here is "Custom HTML" particle options in "Base Outline":

![1](https://cloud.githubusercontent.com/assets/16582788/18492668/8734dee0-7a1d-11e6-8fe5-bcfdde6f0edd.gif)

and here it is Section Inheritance in "Hydrogen - Default":
![2](https://cloud.githubusercontent.com/assets/16582788/18492696/b75dd428-7a1d-11e6-8964-ea4328a3eaf5.gif)

i have also tested inheritance between different outlines (not from "Base Outline"), but result is same ... tag attributes dont shows ..

Best Regards,
Maksym.

**Comment by w00fz** [comment]
I can confirm this is an issue when inheriting a whole Section. Particle's Blocks inherited properties are not passed through.
However, this is not the case when inheriting a single Particle with its Block.

Any idea @mahagr ?

**Comment by w00fz** [comment]
Ok I solved this. Looks like there is some inconsistency in the way some properties get stored as when they come from inheritance. For instance the Extras in Block has always been arrays, but now when it comes from inheritance it's an object causing the twig to fail to iterate over it and go silent.

I am now force casting array for it but this might require some additional core cleanup as it's definitely not the right behavior.

**Comment by mahagr** [comment]
I think the cause of this is `json_decode(json_encode(...)` used in the `Layout::initInheritance()` function. The purpose of this was to clone all objects in the children instead of just referencing them, but it looks like its converting all associative arrays into objects... I'll create a new issue out of this.

**Comment by MaksymJ** [comment]
thank you very much
