### ISSUE TITLE
Targetting `g-grid` and `g-block`.

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#1581]
Dear Gantry Users & Developers,

I posted this in the chat but I thought it might be better to make it into a issue.

For as far as I know it is not possible to add our own classes at the moment to either a `g-grid` or `g-block`. Therefore I want to propose the following addition but let's first start with explaining how it now goes.

So in G5 Admin we create a container or section.
![loginsecure ug - administration - google chrome 2016-09-14 14 32 46](https://cloud.githubusercontent.com/assets/4426337/18512853/3d2c1462-7a8b-11e6-906f-eab3854817c6.jpg)

Then we add a particle or module position etc.
![loginsecure ug - administration - google chrome 2016-09-14 14 33 01](https://cloud.githubusercontent.com/assets/4426337/18512869/598bbc16-7a8b-11e6-84f4-d35bad804c88.jpg)

Now when we look at the source this all works fine but the `g-grid` and `g-block` does not have a custom class. Which is obvious as we can't add those at the moment.
![developer tools - http___research loginsecuretest eu_loginsecure eu_en_forum_index 2016-09-14 14 33 47](https://cloud.githubusercontent.com/assets/4426337/18512900/74ab37ec-7a8b-11e6-987f-86fc2251d45d.jpg)

Now my suggestion is to add on a Container/Section level 2 more cogs to the list like this:
![loginsecure ug - administration - google chrome 2016-09-14 14 38 34](https://cloud.githubusercontent.com/assets/4426337/18512919/886c6832-7a8b-11e6-9a6d-fa055bf92ff6.jpg)

One of the cogs will be to set the Grid and the other to set the Block.
![loginsecure ug - administration - google chrome 2016-09-14 14 38 16](https://cloud.githubusercontent.com/assets/4426337/18512935/9638f73c-7a8b-11e6-931c-7ec3eb7e676b.jpg)
![loginsecure ug - administration - google chrome 2016-09-14 14 38 25](https://cloud.githubusercontent.com/assets/4426337/18512937/97c12d04-7a8b-11e6-9a57-39d3c60f82f2.jpg)

In both cases this would open a screen like this:
![loginsecure ug - administration - google chrome 2016-09-14 14 40 50](https://cloud.githubusercontent.com/assets/4426337/18512947/a361f260-7a8b-11e6-9fe1-4c23b38f5f1e.jpg)

The classes we then assign in here are the one's mentioned in the source. While writing this I come to the conclusion that the `cogs for the blocks` should not be at the container but next to section settings.

There might be some issues with nested `g-blocks` & `g-grids` but I think this can be solved by adding a option that when enabled make all nested `g-blocks` inherit the inserted class. If the option is disabled the class will only be assigned to the first `g-block`. PS same goes for the `g-grid`.

Looking forward to hear if this is a good idea or if there are already ways to do this within Gantry. At the moment I am using jQuery to assign a class to the parent.

**Comment by alisamii** [comment]
I think this will be confusing to users. Three cogs next to one another is not intuitive, and having different icons (for example, if we used `fa-square` for `g-block` and `fa-th` for `g-grid`) doesn't really solve the confusion.

I am not certain that we want to mess with these two elements. However, if this is something that consensus says is valuable, then I think the best and only solution would be to just have one cog icon, and add tabs within the modal for the block and the grid.

**Comment by hennysmafter** [comment]
I agree that the 3 cogs might not have been the best idea. In my defense I came up with it in under 2 minutes. So it might need some more thinking over. 

But still going to stick with it that it would be great if we could give our own classes to `g-grid` & `g-block` because when we can add our own classes we can do more stuff with animations and other items that require a class name.

**Comment by mahagr** [comment]
You can set classes and ids for all the levels, just not from the admin. So as the developer of the template you can modify yaml file and add all the missing bits as you wish. Just remember that everything that comes after section (eg grids, blocks and particles) can be removed by user, thus not worth to use for setting custom classes etc. But if you want to target the upper block from a section, its fully possible already.

**Comment by hennysmafter** [comment]
@mahagr Could you give a example please how that would look into a .yaml. 

But the thing while this is super great to be changed on a .yaml level it does not allow a noob to do it. As they need to use FTP and then edit something they don't know a thing about. While just typing a class would be much easier in G5 Admin.

**Comment by mahagr** [comment]
Its all documented in http://docs.gantry.org/gantry5/advanced/creating-layout-presets#structure

**Comment by alisamii** [comment]
Idiot-proofing can be useful or harmful. In this case, my tendency is to err on the side of caution and not allow so called *noobs* to make this sort of change to a template through the admin, but encourage the client to seek out his template developer to implement this level of modification.

**Comment by w00fz** [comment]
I totally agree with this, one of the main reasons why we don't have those settings available there in the first place. We wanted to keep it developer friendly so that you can extend and change as much as you want while preserving developers sanity through limitation of what users can actually change in the admin.

There's also another aspect to this, specifically with grids. Grids are the most volatile element in the layout they can constantly get removed and added as new and they don't carry any special identification. Their purpose is purely to wrap more important elements like blocks and particles. If there was the ability to change settings via admin it would very hard for an user to keep up with porting those changes across grids as they could go away anytime a grid is empty.

**Comment by alisamii** [comment]
@hennysmafter when you develop your templates, from the very get-go, you can already add a class to each `g-container` that you feel might benefit from an additional class. But I am not certain that is even necessary. In the generated code, these 1st level container are wrapped in their relevant `#g-section` so you can target them with proper specificity if you need to.
