### ISSUE TITLE
Creating color presets

### ISSUE THREAD

**Issue by One041** [gantry/gantry5#1582]
Hello everyone here. Im front end dev and I started working with Gantry 5. I started learn Gantry not so long time ago and not all features of framework know good. Im will be very glad if someone can give me advice how to work with color presets because I dont found  necessary information in Gantry documentaition. I have 5 color presets and in each I want to have various color logo. I added new field for logo in blueprints yaml file and added values for this field in each preset (presets.yaml). But it not works. I think it is because values must be assigned with template. Can someone tell me how to assign value from color preset for logo particle? Thank You.

**Comment by mahagr** [comment]
Style presets only affect css, so you need to use those variables in your css files to make them to work.

**Comment by One041** [comment]
Can You show a some sample please, using yaml variables in css? Thank You

**Comment by newkind** [comment]
Hi,

The field names in blueprints are diretcly tied to the SCSS variables that you can use ie. if you check out in Helium `accent.yaml` blueprint : https://monosnap.com/file/fKwh6dRQXfzqAAKSrB2roiYcVhTAEV.png

Gantry takes the name of the yaml file, combines it with the field name and then you can use it in SCSS ie. `$accent-color-1`

If you have a blueprint called `logo.yaml` and in that blueprint you have a field named `color` this means that in your SCSS files you can use `$logo-color` to load the value of that field in your stylesheet.

**Comment by One041** [comment]
Oh Jesus. Thank You very much! It was very important and useful information for me. Im vary happy that I found someone like you. Thank You so much and have a good day.
