### ISSUE TITLE
Storing of Saving Particles for Later

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1583]
Has there been any discussion or suggestions for saving/storing a current or recently use particle?

Imagine having content/information in your particle and wanting to temporarily remove it and having the option to re-add it later. It would be similar to how the `Widget` section works for WordPress.

I recently ran into a situation where I lost some particles on a page and ended up having to re-add them again. Takes a considerable amount of time if you have a lot of classes, variations, and other items applied.

**Comment by blizam** [comment]
Your Particle data/settings/positioning is all stored in YAML files... check your template/custom/config/ -- back it up as you deem fit ;)

**Comment by mahagr** [comment]
You can store particles into a specific outline with the particle cloning feature.
