### ISSUE TITLE
Custom twig filter in Joomla Gantry 5

### ISSUE THREAD

**Issue by Vanguger** [gantry/gantry5#1584]
Tell me how to add your twig filter?
I want to add {{ 'text'|customfilter }}

**Comment by mahagr** [comment]
```php
$theme = \Gantry\Framework\Gantry::instance()['theme'];
$twig = $theme->renderer();
$twig->addFilter(new \Twig_SimpleFilter('xxx', 'myFilter'));
```

Parameters to Twig_SimpleFilter are filter name and function (can be callable). See twig docs for more info.

**Comment by Vanguger** [comment]
I can not find the entrance to the plugin:
**Fatal error: Class 'Gantry\Framework\Gantry' not found**
```
...
	public function  onAfterRoute () {
	
		$theme = \Gantry\Framework\Gantry::instance()['theme'];
		$twig = $theme->renderer();
		$twig->addFilter(new \Twig_SimpleFilter('customfilter', 'myCustomFilter'));
		
	}
...
```

The plugin How can I connect it? Or where to connect properly?

**Comment by mahagr** [comment]
Make sure that your plugin is ordered after `System - Gantry 5` plugin. Also make sure you detect if Gantry 5 has been initialized (its only being initialized `onAfterRoute` event if you're currently using Gantry 5 theme).

Easiest way to detect Gantry 5 theme is to look if the above class exists.

**Comment by Vanguger** [comment]
I have to use a bad method, TwigExtension.php overwrite the file that works, because I still can not find a good working method - (I'm writing a message via Google Translate)

```
// Bad method that works		
public function  onAfterRoute () {				
	$twig_file_path = JPATH_ROOT.'/libraries/gantry5/classes/Gantry/Component/Twig/TwigExtension.php';
				
	if (JFile::exists($twig_file_path)){
		$str_twig 	= file_get_contents($twig_file_path);
		if (strpos($str_twig, 'myCustomFilter') === false) {
			$str_search = "Twig_SimpleFilter('trans', [\$this, 'transFilter']),"; 
			$str_add1	= "\r\n			new \Twig_SimpleFilter('customfilter', [\$this, 'myCustomFilter']),";
			$text_function	= "\r\n}".'public function myCustomFilter($text){return "OkTestCustomFilter";}';
						
			$new_twig	= str_replace($str_search,$str_search.$str_add1,$str_twig);					
			$new_ext_text = preg_replace('/\}$/', $text_function."\r\n}", $new_twig);
						
			JFile::write($twig_file_path, $new_ext_text);	
						
		}
	}		
}
```

Please give a complete example that works ???

**Comment by mahagr** [comment]
Something like this should work (as long as your plugin is after Gantry one):

```php
    public function  onAfterRoute () 
    {
        if (JFactory::getApplication()->isSite() && class_exists('Gantry\Framework\Gantry')) {
            $theme = \Gantry\Framework\Gantry::instance()['theme'];
            $twig = $theme->renderer();
            $twig->addFilter(new \Twig_SimpleFilter('customfilter', 'myCustomFilter'));
        }
    }
```

**Comment by Vanguger** [comment]
It works in the frontend (... isSite () ...)
What do I need to backend (... isAdmin () ...) - does not work

Error: **Oops, Unknown "customfilter" filter in "@ gantry-admin / pages / configurations / styles / styles.html.twig" at line 9 ..**

**Comment by mahagr** [comment]
Just leave the site detection off then. Why do you need a filter in admin?

**Comment by Vanguger** [comment]
Мне удобно видеть админ панель на моём родном языке. Новый фильтр, помогает мне делать авто перевод на мой язык в админ панели.

![scrtr](https://cloud.githubusercontent.com/assets/22159120/18668562/d8ab91d0-7f3e-11e6-822e-10167d1bc8ff.jpg)

**Comment by mahagr** [comment]
Any news on getting this issue solved in your end?

**Comment by Vanguger** [comment]
Hi!
Not working, can't find the right entrance. Error:
Oops, " unknown "customfilter" filter "@ Gantry-admin / pages / configuration / styles / styles.HTML.twig"

```
    public function  onAfterRoute () //???
    {
        if (JFactory::getApplication()->isAdmin() && class_exists('Gantry\Framework\Gantry')) {//???
            $theme = \Gantry\Framework\Gantry::instance()['theme'];
            $twig = $theme->renderer();
            $twig->addFilter(new \Twig_SimpleFilter('customfilter', 'myCustomFilter'));
        }
    }
```

**Comment by mahagr** [comment]
did you create a function for the filter?

```php
function myCustomFilter() {...}
```

If you added the function inside the class, you'd need to pass the class as well:

```php
$twig->addFilter(new \Twig_SimpleFilter('customfilter', [$this, 'myCustomFilter']));
```
```

**Comment by Vanguger** [comment]
In the admin panel is Not working. Error:

_**0 Identifier "theme" is not defined.**

_I think it is in the line:_ $theme = \Gantry\Framework\Gantry::instance()['theme'];_

Call stack
     Function							Location
_1 JApplicationCms->execute()			\administrator\index.php:51
2 JApplicationAdministrator->doExecute()	\libraries\cms\application\cms.php:257
3 JApplicationAdministrator->route()		\libraries\cms\application\administrator.php:137
4 JApplicationBase->triggerEvent()			\libraries\cms\application\administrator.php:461
5 JEventDispatcher->trigger()				\libraries\joomla\application\base.php:106
6 JEvent->update()						\libraries\joomla\event\dispatcher.php:159
7 PlgSystemg5customfilter->onAfterRoute()	\libraries\joomla\event\event.php:69
8 Pimple\Container->offsetGet()			\plugins\system\g5customfilter\g5customfilter.php:39_

Used the code:

```
	public function  onAfterRoute () {
		function myCustomFilter($text){return "OkTestCustomFilter";}
		Gantry5\Loader::setup();		
        if (JFactory::getApplication()->isAdmin() && class_exists('Gantry\Framework\Gantry')) {
            $theme = \Gantry\Framework\Gantry::instance()['theme'];
            $twig = $theme->renderer();
            $twig->addFilter(new \Twig_SimpleFilter('customfilter', [$this, 'myCustomFilter']));		
	}
```
	
Well, how do I do that, I can not find a way?

**Comment by mahagr** [comment]
You are calling Gantry before it gets initialized (later during the same event). You need to have your plugin ordered after Gantry system plugin.

**Comment by mahagr** [comment]
Ping me in https://gitter.im/gantry/gantry5 , it might be better to solve this in real time chat.

**Comment by mahagr** [comment]
```php
<?php
defined('_JEXEC') or die;

class PlgGantry5TwigFilter extends JPlugin
{
    public function construct(&$subject, $config = array())
    {
        parent::construct($subject, $config);
    }

    public function onGantry5AdminInit($theme)
    {
        $twig = $theme->renderer();
        $twig->addFilter(new \Twig_SimpleFilter('xxx', [$this, 'myCustomFilter']));
    }

    public function onGantry5ThemeInit($theme)
    {
        $twig = $theme->renderer();
        $twig->addFilter(new \Twig_SimpleFilter('xxx', [$this, 'myCustomFilter']));
    }

    public function myCustomFilter($text)
    {
        return "OkCustomFilter";
    }
}
```

**Comment by mahagr** [comment]
Available in 5.3.6+ (or in the mean time CI builds).

**Comment by mahagr** [comment]
See related fix to add translation keys for form fields:

https://github.com/gantry/gantry5/issues/84#issuecomment-252000817

**Comment by w00fz** [comment]
You should document this @mahagr , stuff like this is worth having set in stone for others to find.

Cheers.

**Comment by Vanguger** [comment]
Great! This is a big step! Now I have everything working!
