### ISSUE TITLE
Joomla Article particle number of articles ?

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1587]
Scenario: 
I have a **Joomla Articles** particle as a menu item. Over the maximum number of articles to display, I'd like to have the possibility to show at the end a list with the next "x" articles with some kind of pagination.
It's possible ?

**Comment by mahagr** [comment]
Its possible if you do it by yourself, meaning updating particle to take account of url variables. There's example on how to do context dependent particle in the docs (http://docs.gantry.org/gantry5/advanced/content-in-particles#accessing-current-article). Idea should be the same.

**Comment by mariantanase** [comment]
ok thanks. I'll try

**Comment by mahagr** [comment]
@mariantanase Were you able to solve your issue?

**Comment by mariantanase** [comment]
unfortunately, is too difficult for me

**Comment by mahagr** [comment]
I think that the easiest way to do this would point the link to a blog page and forget about handling it inside the particle.

**Comment by mahagr** [comment]
I'm going to close this issue as not being a bug but a question which couldn't be fully answered.

We have some plans to add AJAX support to fetch more data and to make pagination (for the things that Gantry supports) more feasible to implement in some point of future. In the mean time pagination only fully works from a component itself, where the component has full control of query parameters and how they are interpreted.
