### ISSUE TITLE
gantry 5 uncompiled custom css

### ISSUE THREAD

**Issue by Mardulia** [gantry/gantry5#1590]
is there a way to create an old fashioned uncompiled css file in Gantry 5 that'll just work without having to compile it every time I edit it? I'm wasting a heap load of time here! Am I missing something? 

Seems like the only way I can apply my custom css styles to the site I'm working on is to compile it. Editing the compiled file is hopeless.

Call me old and crotchety- but all I want is a css file I can get to, stays the way I put it so I can mark and find the rules I write - and a folder for images that I can reference in it.  I can work fast and efficiently that way.

**Comment by LukeDouglas2** [comment]
Nope.  If you edit the custom css file, you will have to recompile.  If you directly edit any template CSS files (DEFINITELY NOT RECOMMENDED), then you will still have to recompile the CSS.  It adds about 15-20 seconds additional time for me to test changes but I can live with it.

**Comment by w00fz** [comment]
You should be able to create a `custom/css/custom.css` and that should be picked up. However, I can't remember if this is still the case, it used to.

One way to approach this is to create the `custom.scss` file and put in it just a:

```css
@import url('custom.css');
```

Then in your `custom.css` file you can write all your CSS and it shouldn't be requiring any compilation. The only compilation will be the first time.

**Comment by LukeDouglas2** [comment]
I can confirm that what w00fz states can be done as I have tested this procedure and it works.  However, I would 'highly' recommend not to go this route as it will impact page load times.  Just a suggestion.

**Comment by Mardulia** [comment]
Thank you both for responding. Very grateful! I am going to try w00fz's suggestion. Can't imagine that a such a file would have that much impact on load times. By the time I'm finished it may have hundreds of lines - certainly not thousands and don't know how else to have complete unremitting control of my css without a css file I can edit! Thank you again!

**Comment by mahagr** [comment]
There is automatic CSS recompile if you turn Production mode off (or Development mode on).

**Comment by mahagr** [comment]
Update: It looks like there's issue on compiling custom.css file the first time its added. After that the recompile seems to work just fine, at least to me.
