### ISSUE TITLE
Old preset backwards compatibility issue

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1593]
I discovered this in the Salient template. Here are the steps to recreate the issue...

1. Clearn Salient rocketlauncher installation
2. goto "home positions" outline > layout
3. press "load" button and selected preset "2 column - left" preset 
4. you get a warning about "offcanvas" section being missing from preset (which is wrong) - but continue anyway and SAVE
5. Your particles that were in offcanvas have now been wiped out.
6. repeat from step 3 again and you get the same error about offcanvas again!

@mahagr says this is a backwards compatibility issue and he knows how to correct this.

**Comment by mahagr** [comment]
This is not an issue with latest Salient versions; offcanvas is there and nothing gets wiped out. Actually older versions of the layout file adds offcanvas section automatically -- its the new version of the file which doesn't do it automatically (which is a design decision as I wanted to remove hardcoded section). 

@marktaylor46 I'm not able to reproduce your issue.

**Comment by marktaylor46** [comment]
http://screencast.com/t/MtbNhBkVIn

video above of issue

**Comment by mahagr** [comment]
I was finally able to reproduce the issue. Looking..
