### ISSUE TITLE
Force relative urls to compile using https://

### ISSUE THREAD

**Issue by horch004** [gantry/gantry5#1594]
I have some images in the custom scss file using the syntax url("gantry-theme://custom/images/.....").
When someone navigates to the website using http:// the scss file gets compiled with the images using the http:// protocol. Now, when someone navigates to the website using https:// the browser reports mixed content.

When the first hit (after clearing the cache) on the website uses https:// the scss gets compiled with https://.

It would be great to have the option to enforce the scss to get compiled using the https:// protocol for relative urls.
Now I have to use the complete url path to the image file to enforce https://

**Comment by mahagr** [comment]
You're in wordpress?

**Comment by horch004** [comment]
Yep

**Comment by mahagr** [comment]
Yeah... WordPress has a bad habit of adding protocol and domain to all urls. 

Note to myself: Fix it by replacing protocol by `//`, thus making assets to use the same protocol as the page is.

**Comment by horch004** [comment]
Thnx for the future fix
