### ISSUE TITLE
Cant create new outlines?

### ISSUE THREAD

**Issue by v2fi** [gantry/gantry5#1596]
Big trouble and the website needs to be done soon :( For some reason when I try to duplicate or create a new outline, this weird SUCCESS box appears in right bottom corner (mostly empty, with some colored boxes in it) and disappears - but no new outlines appear.

![image](https://cloud.githubusercontent.com/assets/7578369/18985636/7b2a2498-8701-11e6-9756-2a7fb9d9ee65.png)

What could be wrong?

**Comment by mahagr** [comment]
Ping me in Gitter chat https://gitter.im/gantry/gantry5

**Comment by mahagr** [comment]
I can verify the issue. It looks like that there's something weird going on with JS. Ajax works just fine, but there are some other issues as well, like `Extras` dropdown not working etc..

**Comment by w00fz** [comment]
That looks like the response not being served as json but plain HTML. Server settings?

**Comment by v2fi** [comment]
Where would I go about to figure that out / change it? I don't think I have that kind of power over the server as it's just a web hotel. Is there some kind of simple script I could try to confirm the diagnosis?

**Comment by v2fi** [comment]
I installed a fresh WP with Gantry and Hydrogen on the same server and adding the outlines works. Also the Extras work. So I guess I'm moving my stuff there.

**Comment by v2fi** [comment]
Hmm.. when I installed the new one, it asked me to update the PHP. I did and now the old installation seems to work too.

**Comment by w00fz** [comment]
Cool looks like something was messed up in your other instance. I take it's all good now and closing the issue.

**Comment by mahagr** [comment]
Good that you got your issue fixed. There are some known issues with PHP 5.4 and Gantry5 which happen only in some configurations (notably in WP if you have APC installed), which is one of the reason why we added message to upgrade PHP.
