### ISSUE TITLE
main.js.map 404 (Not Found)

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#16]
Getting this error in console?
GET http://testing.dev/Joomla_3.4.1/media/gantry5/assets/js/main.js.map 404 (Not Found)

**Comment by w00fz** [comment]
This is normal. We use sourcemaps for developing but we don't provide them as they are too big. You can disable the sourcemaps from the inspector settings (in Chrome is a cog icon).
These warnings are harmless and they only activate if you have the inspector open.

**Comment by mahagr** [comment]
Though, we will look into this and disable map files while compiling the final build.

**Comment by uglyeoin** [comment]
I'm seeing this as an error again, has something crept back into the builds?
