### ISSUE TITLE
Assign particles in positions to specific pages

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#160]
Hi @mahagr , as discussed in hipchat, we need a better solution for different layout/particles for different page without needed to create lot of config and layout files

**Comment by arifinrt** [comment]
Some notes we disccussed:
- one idea is to have particles as joomla modules where you can pick up particle and configure it
- easily generate modules from installer etc, too. For example based on existing files in the filesystem

**Comment by mahagr** [comment]
Above commits are unrelated to this issue.

**Comment by mahagr** [comment]
This has been implemented in Joomla, but missing in Prime and WP.

**Comment by mahagr** [comment]
It was decided that this feature isn't as much required as some other improvements which have been assigned into 5.2.0. Nevertheless, I'm going to move this one into 5.2 milestone to keep myself reminded on this one.

**Comment by w00fz** [comment]
Is this still relevant @mahagr ? Especially now we are going to have Inheritance?

**Comment by mahagr** [comment]
We have already solved this issue in Joomla by using module positions and particle module.

This is really the same issue as #1059. Layout inheritance will fix some special cases, but it doesn't fix the issue where you need to create different named positions to every single page where you need some custom widgets.

I'm closing this issue as duplicate to #1059 as we now understand the problem better than before.
