### ISSUE TITLE
Two files in the gantry 5, a text: con_gantry5

### ISSUE THREAD

**Issue by Vanguger** [gantry/gantry5#1600]
Hi! There are two files in the gantry 5(Joomla), a text: con_gantry5. Is this correct?

_File 1:_
     components/com_gantry5/fields/particle.php
_Line 38:_
     Lang->$load('**con_gantry5**', JPATH_ADMINISTRATOR) | | language->$load('com_gantry5', GANTRYADMIN_PATH);

_File 2:_
     components/com_gantry5/gantry5.php
_Line 15:_
     Lang->$load('**con_gantry5**', JPATH_ADMINISTRATOR) | | language->$load('com_gantry5', JPATH_ADMINISTRATOR . '/components/com_gantry5');

**Comment by mahagr** [comment]
Thanks, fixed!
