### ISSUE TITLE
Need social share buttons to work in Custom HTML particle or embed shortcodes

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#1601]
I'm using Joomla 3.62, Gantry 5, Hassium Template from JVGtheme.com.

I'm trying to put some social share buttons on my website by using Joomla plugins like Jssocials or BTshortcodes Ultimate.   When I put snippets in the custom HTML module, it just displays the snippets or a blank. For example: for Jssocial snippet {jssocials},  or for BTshortcodes Ultimate snippet [social_share linkedin="yes" pinterest="yes" tumblr="yes" pocket="yes"].

Note that BTshortcodes will appear properly if I put the snippet into an actual Joomla article.  

Note that social share buttons are different than Gantry's social particle which provides a link to the website owner's own facebook page, google+, etc.

I see this subject was addressed to some extent in previous Github posts:
Embed shortcode doesn't work in Custom HTML particle #905
 gantry5/engines/common/nucleus/particles/social.yaml

I guess an alternative would be to try to find social share buttons in a Joomla module, and put the module in a Gantry 5 module position particle.

**Comment by mahagr** [comment]
Try if the shortcodes work in Custom HTML module. I think they do not, which would mean that the plugin only supports shortcodes inside articles.

**Comment by pintobuck** [comment]
Thank you for the reply.

The social share plugin snippets do work in articles, but there are other places that I (and other people) would like to place social share buttons.

I did find ITP Social Buttons, which is a Joomla module instead of a plugin, which means that I can locate the social buttons in my Gantry 5 template using a module position particle.  I think the issue is that a social share particle would be nice to have in addition to the social connect particle that comes in Gantry 5.

**Comment by mahagr** [comment]
Well, the thing is that the plugin decides when it works and when not. We do not have that control in Gantry. Basically any plugin that would work in custom html module, should work with particles that support shortcodes (eg. run joomla event to modify content).

**Comment by pintobuck** [comment]
Yep.  I think the two Joomla short code plugins do not work in Gantry 5 Custom HTML particles. They seem to be designed for Joomla articles.  One of the plugins claims it can be auto inserted into Joomla categories.  Anyway, I think it goes back to: 1) I'm ok with the Social Share module that I found, which I put into a Gantry 5 module position particle.  2) A social share particle would be up to the experts, which I am not, if they think it is worthwhile, but I'm good for now.

**Comment by mahagr** [comment]
Alright, I'm closing this issue as solved then. :)
