### ISSUE TITLE
Assignments for Custom Post Types don't work - Wordpress  5.3.5v

### ISSUE THREAD

**Issue by lukujiAdmin** [gantry/gantry5#1602]
Hi, im just trying apply a custom outline for a custom post type, but any change I made seems to have  any effect. I read the #1298 issue, but the code there don't work anymore, i suppose is because the new version of gantry. The assigments work with the  others post, but with custom post type the settings are not reflected in the front end and  don't show me any error.

Anyone have this problem? someone can guide me to fix this?

**Comment by newkind** [comment]
The code is already merged into Gantry core and doesn't need to be added manually anymore. Can you please show me your current setup of assignments and post contents of `assignments.yaml` file from the `<your-theme>/custom/config/<outline-name>/` directory ?

**Comment by lukujiAdmin** [comment]
Hi newKind, ok. here is my assignment file

context: {  }
menu: {  }
post:
  empresa:
    0: true
    is_singular: true
    is_archive: true
    11: true
taxonomy: {  }
archive: {  }


if i set to a normal page it work, but for this post type don't.

thanks in advance

**Comment by mahagr** [comment]
Ping me in https://gitter.im/gantry/gantry5 and I will give you a debug tool that helps finding out what happens.

**Comment by pateljj04** [comment]
I am having the same issue or similar issue. I am using advance custom fields and I have the fields assigned but the content is not showing up. It just shows the field key ie: field_57e1462ba619c

**Comment by pateljj04** [comment]
Any thoughts on how to solve this? I have posted on Gitter multiple times without any response. Any guidance/help would be appreciated!
