### ISSUE TITLE
helium theme - joomla - article title font family won't change

### ISSUE THREAD

**Issue by exponentus** [gantry/gantry5#1603]
Although I've changed the font family in the Font Families core style, the font family set by default keeps showing. 
This happens whether I set the new values in the Base Outline or in the overriding outlines.

Development mode is turned on, therefore recompiling CSS should not be required.
But even after recompilations, changes do not take effect.

<img width="634" alt="screenshot 2016-10-05 13 06 39" src="https://cloud.githubusercontent.com/assets/17674908/19109106/99da3406-8afc-11e6-9165-08ef49097509.png">

**Comment by kat05** [comment]
I gave this a try and it seems the Joomla article titles are tied to the setting for "Body Font" instead of "Title Font". Not sure what the desired behaviour is.

**Comment by w00fz** [comment]
I think it should be tied to the Title Font.

/cc @newkind

**Comment by newkind** [comment]
Should be fixed in latest CI. Please test.

**Comment by binaryglyph** [comment]
Curiously the same behavior exists in 5.4.32. Titles are still tied to "Body Font" instead of "Title Font."
