### ISSUE TITLE
Status 404: Adding custom fonts

### ISSUE THREAD

**Issue by alebak** [gantry/gantry5#1604]
Hello, 

I could add a custom font but when I reload the browser I get this error:

![gantry5-errorfont](https://cloud.githubusercontent.com/assets/6515879/19141465/4ef83546-8b5b-11e6-965c-0eab22d78c2a.png)

The problem is with jQuery? How to fix it?

**Comment by w00fz** [comment]
The issue is not with jQuery, the problem is that url is a 404, doesn't exist.
What exactly are you trying to do and how did you do it?
Where did you add custom fonts? In the theme? How did you load it in the .scss? Why is there something pointing to `/custom/fonts` ?

**Comment by alebak** [comment]
I added a local font following the steps this video:

https://www.youtube.com/watch?v=qNX6ULi9Mec

But when I reload the browser I get the error mentioned. I cleaned cache and recompiled CSS also and Gantry try to load this resource: [URL_TEMPLATE]/custom/fonts.

Do I did bad?

**Comment by w00fz** [comment]
That video should be still actual. Have you tried also following the guide from http://docs.gantry.org/gantry5/tutorials/fonts to see if you missed some steps?

**Comment by alebak** [comment]
But the problem is not when loading the font. The font load correctly but when the browser load the page the console show this error. Could it be that Gantry is generating something that is not?

**Comment by w00fz** [comment]
Look at the generated CSS code and see if there's something odd in there where the font rule is.

**Comment by alebak** [comment]
I check the .css generate file and I can see this:

url('../fonts')

Why?

**Comment by w00fz** [comment]
Yah that's the issue. I think something hasn't be set properly. I do need more informations.
Care to share your `theme.yaml` font section, a screenshot of your Styles panel where you selected the font and the SCSS where you added this?

**Comment by alebak** [comment]
This my theme.yaml:

[theme.txt](https://github.com/gantry/gantry5/files/512975/theme.txt)

Styles panel:

![panel style font](https://cloud.githubusercontent.com/assets/6515879/19141979/8e61388c-8b5f-11e6-9c05-1deaf5030f54.png)

The SCSS file:

[ximware.txt](https://github.com/gantry/gantry5/files/512981/ximware.txt)

I don't understand the error :(

**Comment by w00fz** [comment]
It might be because you have the key defined with a space. Try changing it to `weblysleek_ui`

**Comment by alebak** [comment]
Doesn't works, the error is same.

This css compiled file:

[ximware.css.txt](https://github.com/gantry/gantry5/files/512995/ximware.css.txt)

**Comment by w00fz** [comment]
You sure you have the fonts file properly located and named accordingly to `gantry-theme://fonts/weblysleekui_light/ws-ui-light` ?

**Comment by alebak** [comment]
Yes, I'm sure.

![2016-10-06](https://cloud.githubusercontent.com/assets/6515879/19142280/e2737582-8b61-11e6-9a78-ad7524b7d54a.png)

**Comment by w00fz** [comment]
You are missing all the formats, `woff` is not enough.

![roboto_bold_macroman 2016-10-05 23-16-12](https://cloud.githubusercontent.com/assets/11734/19142364/c16ff5aa-8b51-11e6-9884-6d0fd1173fed.png)

**Comment by alebak** [comment]
Then I think that Gantry 5 framework should be change or add a new feature because the others formats are not required for load the font correctly, the other formats are optional.

I will try to find the .eot font file and generate webfont using fontsquirrel.com (https://www.fontsquirrel.com/tools/webfont-generator) if that works, I close the issue and I cry "eureka!"

**Comment by alebak** [comment]
Doesn't works!

I tried with other font with all formats and I get the same error. With the custom fonts Gantry try to get /custom/fonts resource (error status 404) but with roboto font does works!

I'm not understanding nothing. Is it a bug of Gantry?

**Comment by w00fz** [comment]
I don't think it is, we use this every time and never had issues so I still think something is not right on your side. Follow the official guide please: http://docs.gantry.org/gantry5/tutorials/fonts

Also have you added this like explained in the docs??

```sass
@import "vendor/bourbon/bourbon";
@import "nucleus/theme/mixins/typography";
@include import-font('roboto’); 
```

Where 'roboto' would be 'weblysleek_ui'.

**Comment by alebak** [comment]
But in the last version of the Hydrogen template does not include `import-font('roboto’);` into the SCSS files and the directory structure of Hydrogen template is not the same of tutorial.

The focus of the tutorial is [TEMPLATE_URL]/custom/fonts/roboto while Hydrogen template last version is [TEMPLATE_URL]/fonts/roboto

I maked a search using "roboto" word and not found this line: `@include import-font('roboto’); `

I don't understand. Check my custom template: 
[tpl_ximware.zip](https://github.com/gantry/gantry5/files/513055/tpl_ximware.zip)

Thanks if you help me!

**Comment by mahagr** [comment]
Tried your theme and I'm getting 404 on files:

    templates/ximware/fonts/weblysleekui_normal/ws-ui.woff2
    templates/ximware/fonts/segoeui/segoeuil.woff2
    templates/ximware/fonts/weblysleekui_semibold/ws-ui-semibold.woff2

Latest browsers prefer a format that you're missing there.

BTW, those font files are added by Bourbon mixin, which is external scss library we are using. I think there was a parameter that can be used to only selectgiven file formats, but that's something you need to decide and implement in your own there scss.

**Comment by alebak** [comment]
Thank you @mahagr for your answer with that I could solve it. You had reason the .woff2 files are required in Gantry 5.

I have an question: How could you check that these files were missing? Do you used the browser console for this?

**Comment by mahagr** [comment]
I just used latest CI build which actually tries to load those files. Will release it today as 5.3.6.
