### ISSUE TITLE
"Thank you for creating with WordPress." partly hidden in Layout Manager

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1605]
Please see pic.

![g5_wp_thanks](https://cloud.githubusercontent.com/assets/5719486/19145588/e85155d4-8baf-11e6-975f-90fbc641b1a9.jpg)

**Comment by mahagr** [comment]
Looks like a small CSS issue; @w00fz you know LM the best, so I'll throw this to you.

**Comment by w00fz** [comment]
This will go away once #1499 gets addressed. Closing for now as it is related to the other issue.
