### ISSUE TITLE
Switch from G4 to G5

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1606]
Hi,
I would like to know which are the correct steps to change from a Joomla G4-based site to G5.
And is worth to do this ? Advantages/Disadvantages ?
Thanks

**Comment by mahagr** [comment]
As long as you are fine with changing the template, there shouldn't be too many issues on changing over -- as long as you setup the particles that replace G4 configuration and set up the layout (you can use Gantry 4 preset to start with) that has the same positions as you use in older template.

The largest difference is probably that we do not provide custom styling for roksprocket or rokgallery, so if you are using those, you may need to tweak some css to get them to look good.

**Comment by mariantanase** [comment]
ok, thanks @mahagr
