### ISSUE TITLE
logo/image particle logo.html.twig always adds a link

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1607]
Suggested improvement:

Add an checkbox option to say "no link" in the particle 

If you are using this particle to just display an image then it is often the case that you won't want a link at all. Note that it would not be sufficient to check for a link value as (correctly) the particle default to the "home" link if no value is entered. 

As a "logo" particle the functionality would be fine as it is but the actual description of the particle is logo/image particle.

**Comment by hacki65** [comment]
Good idea 👍

**Comment by w00fz** [comment]
PR welcome for this.

**Comment by dudewithamood** [comment]
@marktaylor46 you can override the particle by editing logo.yaml and logo.html.yaml, and saving them under <your theme>/custom/particles - read http://docs.gantry.org/gantry5/advanced/creating-a-new-particle and http://docs.gantry.org/gantry5/advanced/particle-yaml-field-types, bearing in mind it doesn't need to be a new particle as it will override the particle when you keep the file names the same as the existing one.

This is what I've done to meet my own requirements for this particle.

I'm wondering if it would be useful to have an entirely separate project for user contributed particles and particle changes that aren't necessarily part of Gantry. That way people can pick and choose the ones they want, and contribute changes without it being tied into the Gantry framework as such.

**Comment by marktaylor46** [comment]
@dudewithamood Thank you, yes, I am fully aware how to create overrides for particles (I am MrT moderator on the RT forums) but I believe this change would benefit many people and that's why I raised the issue so that Gantry 5 could be changed. I'll get around to the PR in the next few days.

**Comment by dudewithamood** [comment]
Ah, okay, fair enough - I don't really know who's who...

I have also used this particle for placing images so in that sense, yes I agree.
