### ISSUE TITLE
submenu is not working in gantry when component is jdowload

### ISSUE THREAD

**Issue by web54** [gantry/gantry5#1609]
on https://www.web54.fr/telechargements
the issue appears only on the page loading jdownload component.

thanks.

**Comment by adi8i** [comment]
I see two issues on your website.

1. jQuery is loaded over Http, try to load it using Https.
2. JCEMediaBox is not defined, probably because jQuery is not properly loaded.

**Comment by web54** [comment]
first issue : when disabling https it is the same
second issue : when disabling  jce mediabox the same.
I found it :  it was the plugin script merge !!

**Comment by w00fz** [comment]
Assuming it is all resolved now?
