### ISSUE TITLE
Menu manager selecting image for menu item result in broken image link in admin

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#161]
Windows 8.1 64 bit

In menu manager I added an image to a menu item. It showed as a broken link in admin yet works fine in frontend
![2015-04-30_20-44-22](https://cloud.githubusercontent.com/assets/11683218/7421160/4f186290-ef7a-11e4-9af9-53532f994576.png)

**Comment by mahagr** [comment]
Might be related to your Joomla path, is it in html root or in a subdirectory?

**Comment by marktaylor46** [comment]
I added more screenshots for you. It's in a subdirectory.
![2015-05-01_09-53-11](https://cloud.githubusercontent.com/assets/11683218/7428422/3e277480-efe8-11e4-8982-49c198eac834.png)
![2015-05-01_09-53-29](https://cloud.githubusercontent.com/assets/11683218/7428423/4020078e-efe8-11e4-9645-9ed5404322f0.png)
![Uploading 2015-05-01_09-54-20.png…]()

**Comment by marktaylor46** [comment]
![2015-05-01_10-03-03](https://cloud.githubusercontent.com/assets/11683218/7428494/53541948-efe9-11e4-91dd-462a0c346f61.png)

**Comment by mahagr** [comment]
That will help a lot. Thanks.

**Comment by mahagr** [comment]
Fixed in 4c2a5a4 (accidentally picked up wrong issue for it).
