### ISSUE TITLE
Nested collection-lists and opening the multi-view of 2nd level collection list plus collapse/expand all issue

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1612]
There seems to be a new bug, probably somehow related to the way that collection list multi-view panes can now be collapsed/expanded.

If you have a nested collection list (in the particle, you have a collection list, and each item in that list can also have a collection list), trying to view open the 2nd level collection list multi-view from a first-level multi-view window doesn't work. Instead, it opens the single-view window of the first item in the first-level collection list.

See this gif.

![nested-collection-list](https://cloud.githubusercontent.com/assets/1498512/19222627/8fb1d0c4-8e5d-11e6-855a-a37dd2c5fe21.gif)

The second problem I have noticed is that if you collapse a card/pane manually (one by one) then you cannot expand it again, and the expand-all button doesn't work. If you click "collapse all" and then "expand all" the cards all collapse, but when they expand, the individually collapsed cards don't expand.

See this gif.

![collapse-expand-problem](https://cloud.githubusercontent.com/assets/1498512/19222644/df79a3a2-8e5d-11e6-8251-5aedb85d39f5.gif)

**Comment by alisamii** [comment]
@w00fz can you please look into this and confirm that you can replicate?

**Comment by mahagr** [comment]
See above link for another example of the same issue.

**Comment by alisamii** [comment]
@mahagr I noticed that #1644 which you closed was added to the 5.3.7 Milestone, but this issue, which predates that, and is the same, still have no target milestone. Any chance it will actually make it into 5.3.7?

**Comment by mahagr** [comment]
We add milestone when question gets closed regardless if it was fixed or not. Think it as an activity log of what was happening during that release.

As you probably have noticed, there are few bugs that have been lurking there for some time and just moving from release to another. To prevent that we decided not to assign issues into milestones unless we also fix them in those.

**Comment by w00fz** [comment]
The nested multi list edit never worked apparently. I can see this is a bug in the code that has been there for quite a while.

**Comment by w00fz** [comment]
Ok I fixed the toggles getting stuck closed.
Can you look at why the prefix goes out of whack in nested multi edit lists @mahagr ?

**Comment by mahagr** [comment]
@alisamii Should be fixed now. There was conflict on twig variable names that caused the issue.

**Comment by marktaylor46** [comment]
Fix works for me 👍
