### ISSUE TITLE
Grav - admin language strings for settings seem missing

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1613]
Please see pic, shows in 
- Styles
- Particle Defaults
- Page Settings
tabs.

Seeing this in Helium and other RT G5 themes.

![g5_grav_langstrings](https://cloud.githubusercontent.com/assets/5719486/19234908/cd114f76-8eee-11e6-882f-bae59dd1dd14.jpg)

**Comment by mahagr** [comment]
You're right, there are no translations and the fields should default on the text that's provided inside the yaml file.
