### ISSUE TITLE
Grav - tooltip background too short  

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1614]
Please see pic, seeing this in Helium and other RT G5 themes.

![g5_grav_tooltip](https://cloud.githubusercontent.com/assets/5719486/19237130/607dffb4-8efb-11e6-9673-c9ef15c437be.jpg)

**Comment by w00fz** [comment]
That's only because it's 1 huge long string without spaces. If you had spaces (or it translated), it would properly wrap.
