### ISSUE TITLE
Joomla Articles particle - exclude articles from current Category View

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1615]
Hey guys,

Maybe this is something for Matias (when he comes back from vacation 😉 ) but if you, Djamil, can advise that would be great!

Basically, I'm trying to add a new option to the "Joomla Articles" particle to exclude the articles from the current category. I managed to get the current category ID but I'm not sure how to remove it from the array. The problem seems to be that I cannot pass a Twig variable to a filter.

Here's my approach:

```
{% set request = gantry.request.request %}
{% if request['option'] == 'com_content' and request['view'] == 'category' and request['id'] %}
	{% set catid = request['id'] %}
{% endif %}

{% set category_options = filter.categories ? {id: [filter.categories|replace({catid:''})|split(','), 0]} : {} %}
{% set categories = joomla.finder('category', category_options).published(1).language().limit(0).find() %}
```

The `|replace` filter works just fine if I type in the category ID manually, for example `8`, but it does not work with a Twig variable - `|replace({catid:''})`.

Do you know how the above can be done?
Or if you have another idea for excluding the articles from the current category that would be even better 😉

**Comment by w00fz** [comment]
You want to use parenthesis to cast the variable: `|replace({ (catid):'' })`

**Comment by JoomFX** [comment]
Awesome! That worked! Thanks 😉 
Djamil, I decided to leave this feature and I will not be implementing it in our Joomla particles (for now). The reason is that this feature will work on "Category Blog" pages only.
Let me know if you want me to submit a PR for the "Joomla Articles" particle (I guess you don't 😉 ).

**Comment by w00fz** [comment]
Yah unless this is a requested feature by many people and more flexible than that, I don't think we should be including it.
If we see in the future this is something we want then we can always add it later. 👍
