### ISSUE TITLE
Modify CSS in a particle

### ISSUE THREAD

**Issue by aschiewe1966** [gantry/gantry5#1616]
Hello,
Can you tell me how to modify the CSS in  a particle. i am aware that if you create a file called customs.scss in THEME>CUSTOM>SCSS ou can modify some stuff but when i try to modify particles using that file it does not work. I would like to modify the content cube particle in the helium template for example.

i am not sure i should post things like this here by the way.
many thanks for your help

**Comment by blizam** [comment]
Typically, your custom.scss is for truly new custom styling or for overriding existing CSS... so if there's CSS in a particle that you want to change you may find it easiest to simply override it with more specific styling in your custom.scss file.

**Comment by aschiewe1966** [comment]
Thank you for your reply...Myabe i can explain further what i am after ..

When i inspect the page and select the area that i want i have the following css
g-contentcubes .cube-items-wrapper .cube-content-wrapper {
    max-width: 22.5rem;
    padding: 6.5rem 0;
    margin: 0 auto;
}
which comes from a file called helium_15.css in the css-compiled directory. 
Let's say i want to just modify the padding to say 4.5 rem
where would i need to modify this so that any gantry update would not overwrite my css change.

As i said in the previous post adding this change in the THEME>CUSTOM>SCSS>custom.scss 
so should i create another custom file somewhere else ? I do not want to modify YAM files and stuff like that just simple CSS...

am i any clearer ?

thanks again.

**Comment by JoomFX** [comment]
Hi @aschiewe1966 

As explained in the [Gantry 5 documentation](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet), any custom CSS/SCSS should be placed in the `custom.scss` file.

What @blizam said is basically all you need - you just need to be more specific in your CSS/SCSS.
Here's what you need to do:

1. Add the following code in your `custom.scss` file (notice the `body` that we add for specificity):

```
body {
	.g-contentcubes .cube-items-wrapper .cube-content-wrapper {
		padding: 4.5rem 0;
	}
}
```

2. "Recompile CSS" under the **Base** outline (you do need to recompile CSS the first time you create your `custom.scss` file).

Another thing that I noticed is that your CSS code is not correct - you are missing the dot (.) in front of `g-contentcubes`. So you might not even need to add `body` for specificity, adding the missing dot and re-compiling CSS under the **Base** outline might do the job.
