### ISSUE TITLE
Inheritance and the base outline - major issue

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1617]
I had a member site in the forum that had an issue with inheritance and now i've been able to recreate the scenarios that cause the issues.

When in the base outline it is possible to load another outline (via the load button) that already has inheritance. IMHO this should not be allowed since the base outline should not be able to inherit anything. The thing that go wrong are:
1. the outline copied could already have been inheriting from base outline and you effectively then create a base oulitne that is inheriting from itself and it all goes horribly wrong and destroys the base outline and the other outlines that try to inherit it.
2. even if the outline was not inheriting from base outline but rather from another outline (for say a particle) then you can end up with an inherited particle on the base outline (which should not be allowed).

I think load button from an outline should be disabled on base outline - to avoid the huge mess it creates if used on the base outline.

**Comment by gotham2042** [comment]
Thanks so much for this. My layout was completely broken as I was setting to 2-column prefix in the base outline. I had no idea that was a bad thing. I switched to editing the layout on Hydrogen - Default and now my layout works.

**Comment by mahagr** [comment]
@marktaylor46 I've not yet fully decided should loading another outline be fully blocked, but at least now the real issue has been fixed. It had to be fixed regardless if we allow load or not.

I'm going to keep the issue open until we release.

**Comment by marktaylor46** [comment]
Ok - I am still of the opinion thought that we should block all load of other outlines into the base outline - I can't see why you would want this and dealing with the complexities of "does the outline layout you're loading contain any inheritance" just seems too complex to bother with to me?

**Comment by mahagr** [comment]
I decided to keep the current behaviour; if more people complain about the change, then maybe I can look it again.
