### ISSUE TITLE
Have a bit of problem on Gantry5

### ISSUE THREAD

**Issue by gdskvorc** [gantry/gantry5#1618]
have reports of site not being responsive on some devices.
samsung galaxy s3, vivax tablet.
![14606480_1142061659221545_3251347120583358265_n](https://cloud.githubusercontent.com/assets/22826677/19370486/5b66c08e-91ac-11e6-935a-445c6dd75e6e.jpg)

Think it has something to do with flexbox but not sure.
site in question is biovrt.com
built on gantry5 custom template built on helium theme.

**Comment by w00fz** [comment]
We do not support non standard touch devices browsers as well as old devices. These do not support Flexbox which is at the core of Gantry for making themes responsive. Using Chrome instead might fix the issue.

> Due to the wide range of variances between default browsers on the Android platform, we are unable to accurately test and list all of the possible regional, carrier, and manufacturer software variables. We recommend an updated Chrome browser for Android as it provides a more consistent experience. Support for flex is the most likely sign of whether or not a browser will work with Gantry 5.

Please see our requirements: http://docs.gantry.org/gantry5/basics/system-requirements#browser-requirements

**Comment by gdskvorc** [comment]
So on new standard devices in the future flexbox will be supported?
this will persist only on older models?
Thanks

**Comment by w00fz** [comment]
Afaik all modern phones support Flexbox already because for a while now Chrome is the default browser for Android. Before every brand was shipping with their own browser and never updated during firmware upgrades. This is the only reason we don't support them, they are just too old.

**Comment by mahagr** [comment]
Its not true that Chrome is the default browser -- I have Samsung and LG phones and neither of them use Chrome by default (both are on Android 6). The issue is that Android devices before 5.0 were using older specification of flex, which we do not support.

I think there are workarounds available to get the flex to properly work on these older browsers, but I've not looked into it.
