### ISSUE TITLE
Config folder is not being picked on first install

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1619]
Wordpress, v5.3.6. Should be the same on joomla.

**Comment by adi8i** [comment]
Hey @kat05. Have you experienced this issue, can you confirm or infirm it?

**Comment by mahagr** [comment]
Please open up the issue a bit.

**Comment by adi8i** [comment]
The outlines added in `config` folder are not created when you install the theme, is a bug or the future have been disabled?

![capture](https://cloud.githubusercontent.com/assets/9744973/19557592/2ba37f9a-96cf-11e6-8624-de4fe793ff90.PNG)

**Comment by mahagr** [comment]
The logic only adds outlines which are in `install/outlines` folder and even then you need to define them in a common yaml file.

**Comment by adi8i** [comment]
Right. I missed that part, thank you.

**Comment by mahagr** [comment]
In fact, do not put those into `config` folder at all. Just allow installer to do it for you.
