### ISSUE TITLE
renaming menu item in joomla not reflected in menu manager

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#162]
Windows 8.1 64bit
I created a menu item called "test2" and moved it around a bit in menu manager
I then went back to joomla and changed the title to something much longer, saved it and then went back in to menu manager.
The title change was not reflected in menu manager nor in frontend - despite clearing cache and recompiling and clearing browser cache.
![2015-04-30_21-03-15](https://cloud.githubusercontent.com/assets/11683218/7421456/6a44b904-ef7c-11e4-9f81-e304a68b0f88.png)
![2015-04-30_21-03-37](https://cloud.githubusercontent.com/assets/11683218/7421457/6c8251fe-ef7c-11e4-9cf8-764d312485f2.png)
![2015-04-30_21-04-46](https://cloud.githubusercontent.com/assets/11683218/7421496/ae7e682c-ef7c-11e4-8ebe-968c0a59fa56.png)

**Comment by kat05** [comment]
i can confirm this issue, changes in the joomla menu item settings are not being picked up.

**Comment by mahagr** [comment]
Yes, this is a known bug. I need to think a way to fix it.

**Comment by mahagr** [comment]
Bah, wrong issue..

**Comment by mahagr** [comment]
Related to #122

**Comment by adi8i** [comment]
You need to change alias too, after that will take the name :)

**Comment by kat05** [comment]
is this still an issue? i just checked on the released callisto launcher and newly added items and renamed items update just fine in the menu editor. has this been resolved?

**Comment by marktaylor46** [comment]
I just tried it too and it does indeed appear to have been fixed now.

Closing issue.

**Comment by marktaylor46** [comment]
This issue is back again! Same process - just changing the menu item text (or changing the alias as well) does  not get reflected in the frontend (cleared browser and server cache too - no effect). I tested this in Callisto.

**Comment by marktaylor46** [comment]
I still think thjis issue is happening - I had another member site with same issue and even on latest CI build it was still not being update. I manually fixed the issue by creating a new menu item and deleting the errorneous one.

http://www.rockettheme.com/forum/joomla-template-callisto/244571-cant-make-menu-title-changes?start=0#1217093

**Comment by mahagr** [comment]
There's a new issue #552 related on this..

**Comment by marktaylor46** [comment]
There is - but that's title "menu reordering" and this is about "menu renaming" not reordering.
