### ISSUE TITLE
Posts at Gantry 5 Helium home page

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1623]
I need to publish wordpress post to home page. 

1) How to use tag More? I need to limit characters?
2) How possible to show just few posts and use pagination on bottom of block?

Thanks

**Comment by mahagr** [comment]
Just make sure that the outline that you assigned to your home page (`Home Outline`?) has `Page Content` particle in it. After this it will include the content from your menu item just like for any other page in WP.

**Comment by pobo3** [comment]
I used the "WordPress posts" to place the last three posts on the home page.
It looks good, but I need to limit the number of characters in the announcements of posts before the end of sentences. Now I can choose for example 120 characters and the offer is not completed. I installed the plug-in Advanced Expert - it allows you to post announcements finish to end of sentence. How can  the template and Advanced Expert work together?

**Comment by newkind** [comment]
Best way to do it is to use Timbers function [`get_preview()`](https://github.com/timber/timber/wiki/TimberPost#get_preview).

Simply edit the `wp-content/themes/g5_helium/views/partials/content.html.twig` and replace :
`{{ post.content|raw }}`
with:
`{{ post.get_preview(55) }}`
where `55` is "the number of words that WP should use to make the tease".
