### ISSUE TITLE
"joomla.categories" YAML field type shows Trashed categories

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1625]
Hey Matias,

I don't know if this is the intended behavior, but in my opinion, the `joomla.categories` field should not show Trashed categories.

Have a look at [this video](https://youtu.be/Ra7KjJspZEE) 😉

**Comment by mahagr** [comment]
I agree, it should act like Joomla field type.

**Comment by mahagr** [comment]
Looks like joomla admin only displays unpublished and published categories, so added proper filtering to do the same.
