### ISSUE TITLE
Homepage outline not loading, default  outline loaded instead

### ISSUE THREAD

**Issue by anxillo** [gantry/gantry5#1627]
Hi, 

I just installed gantry5 and helium template, then modified Home menu item to load custom page, and did the correct assignments, but at homepage it refuses to load the correct outline and load the default one instead (i verified by the classes on body tag).

Error persist also with template installation with example content (and separate template menu).

**Comment by mahagr** [comment]
Are you on Joomla 3.6.3?

**Comment by anxillo** [comment]
yes.	Joomla! 3.6.3 Stable [ Noether ] 17-October-2016 13:35 GMT

**Comment by mahagr** [comment]
Are you on a new empty installation? We are currently looking into this exact issue as a few people have been reporting about it appearing after upgrade to J! 3.6.3, but so far nobody in our team has been able to reproduce the issue for ourselves.

**Comment by anxillo** [comment]
no. but the installation had no categories and a few pages of content. Was almost "clean".

**Comment by mahagr** [comment]
Had you any extensions installed?

**Comment by anxillo** [comment]
That was the problem: probably a conflict with Helix3 plugins. I disabled them, now it seems to work.
