### ISSUE TITLE
Incompatibility with WooCommerce Payu Latam plugin

### ISSUE THREAD

**Issue by sergiobernal89** [gantry/gantry5#1628]
Hi, I have a wordpress website in gantry 5 Hydrogen + woocomerce but this error appears

"An exception has been thrown during the rendering of a template ("Gantry: Please set current configuration before using $gantry["config"]") in "@nucleus/page_head.html.twig" at line 8."

http://agamiguitas.com/wp-content/plugins/woocommerce-payu-latam/response.php

This is a pay confirmation page

May you help me?

Thank a lot

**Comment by mahagr** [comment]
It looks like the plugin doesn't call `template_redirect` action, where we setup the layout. Will investigate this further...

**Comment by mahagr** [comment]
@sergiobernal89 I cannot find the woocommerce plugin from anywhere, the one I found looks very different to what you have installed.

**Comment by mahagr** [comment]
Should be working with the latest CI build (loading default outline).
