### ISSUE TITLE
"Gantry5 Particle" module

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#163]
As per our conversation with @w00fz in the Gitter chat, I'm opening this as a reminder.

*A "Gantry5 Particle" module available in the Module Manager, and in this Module you will have a drop-down listing all available Particles. Then you just select the Particle and publish it in a position and assign it to a Menu Item you want.*

**Comment by mahagr** [comment]
This is something that was already mentioned in #160 and really something that is needed to prevent users from making a configuration (or template style) per page.

**Comment by JoomFX** [comment]
Yes @mahagr , exactly :)

This was my original concern - that if the template relies on Particles (as it should be and I already love them) the user will need to have quite some Configurations, which is a bit confusing and a bit different than the way Joomla originally works (assigning Modules to Menu Items). I mentioned that in the chat couple weeks ago.

In my opinion it is a quite important functionality and it should be available in the first stable release, but I do understand that there are more important things for you and you have different priorities :)

Anyway, I'm glad you see how important it is. Thanks!

**Comment by mahagr** [comment]
Well, the main question here is do we want to have something out next week or after a few months. :)

There are so many cool ideas and things we could do, but right now even the limited functionality will be much better than nothing.

**Comment by JoomFX** [comment]
yep, you are right @mahagr :)

**Comment by mahagr** [comment]
Module has been implemented.
