### ISSUE TITLE
Focus is lost in inheritance's outline dropbox

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#1632]
This is tested in MS Edge and Chrome. Joomla 3.6.3 with G5 5.3.6
Go to a layout page
Click "Section settings" of a section
Click Inheritance tab
Click Outline dropbox and push Backspace on the keyboard
Focus is lost
In order to write (for available layout names) you have to click again.
Another issue related to outline dropbox in MS Edge is that scrollbar in this window won't respond to mouse click. It will disappear upon clicking.

**Comment by mahagr** [comment]
@w00fz Can you check this one?
