### ISSUE TITLE
Content tabs rendering issue on narrow window

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1635]
If I have 6 tabs on the "Content tabs" they are not placed on the mobile version of site.
How possible to fix it?

**Comment by mahagr** [comment]
Screenshot?

**Comment by pobo3** [comment]
![2016-10-24_12-39-19](https://cloud.githubusercontent.com/assets/22922112/19642764/036f147e-99e7-11e6-984c-2b1270b8088b.png)

**Comment by mahagr** [comment]
Sorry, I missed your reply somehow.

You mean the issue happens when text in tab extends to a second row. Are you using Helium template?

**Comment by pobo3** [comment]
No, problemthe issue happens when I add  5 or more tab extends.  It no fit to mobile version. Yes, I use Helium.

Thanks
