### ISSUE TITLE
content in layout preset

### ISSUE THREAD

**Issue by One041** [gantry/gantry5#1636]
Gantry have useful doc about creating loyout presets. But what if I want to add in this preset some content? How I can do it? In gantry doc said how contet of particle represented in yaml file, but not said how add content in layout. For example I have 404.yaml layout:

layout:
  main:
    - custom

and I want to add some content in custom html particle. How I can do it?

I have several outlines with various type of particles and adding content for each particle takes some time. I suppose if I will add necessary content in layout preset, it will reduce time of set up for me and my customers. I will be glad if someone can give me advice or link with solution of this issue. Thank You.

**Comment by mahagr** [comment]
Easiest way to properly add the content is to save the layout in admin and just copy the file over as a preset. This is because of its usually pretty hard to remember all the fields of the particles.

**Comment by One041** [comment]
Thank You very much for this useful and detailed answer.
