### ISSUE TITLE
The percentages of mainbar and sidebar can't be inherited?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1639]
Pretty much as the title says, in base outline, I change the percentage of mainbar/sidebar from 75/25 to 70/30, but the outlines that inherits base outlines won't get this change in its layout.

**Comment by mahagr** [comment]
Yes, sizes are never inherited. If we inherited sizes, it would break layout when you have more than two sections in a row. same is true with particle inheritance.
