### ISSUE TITLE
sidebar menu items wrapping issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#164]
i am using the gantry 4 layout and have a roknavmenu in the sidebar.
some of the menu items have a bit of an alignment issue, please see pic.

![g5_menusidebar](https://cloud.githubusercontent.com/assets/5719486/7425490/4a6a176e-ef77-11e4-8d18-89c95897bf89.jpg)

**Comment by mahagr** [comment]
@kevlardev Any idea on this one?

**Comment by w00fz** [comment]
The theme doesn't provide any style for RokNavMenu so that implies the user will have to implement some css on his own.
This doesn't seem to be an issue of Gantry.

**Comment by w00fz** [comment]
Also as a side note for future references, we are purposely not going to provide any style for RokNavMenu going forward since we went through the whole process of creating a Menu system built-in into Gantry 5.
