### ISSUE TITLE
Menu not showing up in hydrogen

### ISSUE THREAD

**Issue by MidiHipi** [gantry/gantry5#1641]
I have a fresh install of WordPress 4.6.1 running Hydrogen theme.
I have a default new install with one post, "hello world" and I created a menu item in wordpress called "mainmenu". I then added that post list item to it and one for the sample page. The gantry framework and the hydrogen theme were installed when i did this but I made no changes. 

In the configuration for hydrogen I navigated to the menu control panel located at the top of the page and clicked on menu and in the menu editor I dragged a new particle into and added the new menu saving it and exiting the menu editor. I browsed to the blog and saw that the message in the navigation block had changed and now said "no menu selected" 

I went into navigation block in the layout page and clicked on the gear icon and verified that main menu is selected and closed it again refreshing my page in another browser with the same result. No change in configuration and the message stating that no menu selected. I checked in two places to see that it was with no result. Any ideas here? Can I provide any more information or is this just really simple?

TIA
Midi

**Comment by MidiHipi** [comment]
Oh for $%|^'$ sake, I just figured out that I have to do that to the front page outline not the main one. Please close this a chalk up to newbie! ;)
Thnx,
Midi

**Comment by timbocf** [comment]
You're a genius. Thanks!
