### ISSUE TITLE
.size-33 and .size-33-3

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1642]
I find this strange problem when I was trying to tweak the layout of particles. 
I have a section that has 2 rows, and each row has 3 particles. All 6 particles' block size are set to 33.3%. But on front-end, one of them's class is .size-33 instead of .size-33-3, which the other 5 all have. Thus, this particle only gets {flex-basis:33%} instead of {flex-basis:33.3333%}, and is a little dispositioned.

Live page: http://www.peaceevertvimg.org/index.php

**Comment by mahagr** [comment]
Try resetting the widths in Layout Manager. If the layout looks correct in admin (you can check the widths by editing the items and looking into block tab), we may need to investigate this further.

**Comment by newjie** [comment]
Indeed, the width of the block in question is 33%, however, I overlooked this because previously I set it to 33.3%, but when I adjust the others to 33.3, this one automatically went back to 33%. In sum, I have 3 blocks and no matter how I set the block size to be 33.3%, one of them always goes back to 33%.

**Comment by w00fz** [comment]
Hover over the row and click on the right icon to equalize the sizes then you can save.

![gantry 5 dev - administration 2016-10-26 10-45-08](https://cloud.githubusercontent.com/assets/11734/19737784/b1a097a6-9b69-11e6-81db-2bc8ff8997fa.png)

**Comment by newjie** [comment]
Thanks. It works.
