### ISSUE TITLE
Joomla article does not include article images

### ISSUE THREAD

**Issue by minils** [gantry/gantry5#1643]
The Joomla articles that are displayed in the page content do not include neither the intro-imgage nor the full-image.
This should be changed.

**Comment by mahagr** [comment]
Are you talking about the output from our Joomla Article particle or the component output from Joomla? The second one has nothing to do with Gantry as the rendering happens fully in Joomla.

**Comment by mahagr** [comment]
@minils More information is needed in order to solve this issue.

**Comment by minils** [comment]
I was talking about the component output from Joomla. So how can I enable this output then?

**Comment by mahagr** [comment]
From what I can see by reading Joomla code, Joomla should display fulltext image out of the box when in article view and intro image from blog view.
