### ISSUE TITLE
"edit all items" not working for collection.list within a collection.list

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1644]
Again then is more clearly explained through example.

Protean template
Base outline > layout
scroll down to the "simple menu" particle in the copyright section and open it's settings
Click on "edit all items" to edit the three top level menu items.
Now click on "edit all items" in the first menu item panel.
You should see the children for each menu item but it doesn't work. The same is true if you just edit one menu item too... 
![2016-10-29_09-45-07](https://cloud.githubusercontent.com/assets/11683218/19828436/7a42d840-9dbd-11e6-81d4-303ef75d4224.png)
![2016-10-29_09-45-34](https://cloud.githubusercontent.com/assets/11683218/19828438/7e9afd6e-9dbd-11e6-93d0-8993b5b92ca3.png)
![2016-10-29_09-47-56](https://cloud.githubusercontent.com/assets/11683218/19828439/808b6d2a-9dbd-11e6-946a-1f308ff2eddc.png)
![2016-10-29_09-49-10](https://cloud.githubusercontent.com/assets/11683218/19828440/82665790-9dbd-11e6-85fd-39f3ae283439.png)

You have to edit a single menu item at each level to get this to work.

It seems that "edit all item" for collection.list within collection.list does not work.

I believe this is a Gantry 5 bug rather than a template issue.

**Comment by alisamii** [comment]
Hi Mark,

I already reported this issue #1612

**Comment by marktaylor46** [comment]
Ok - hopefully my screenshots also add a little value to help @w00fz fix this.

**Comment by mahagr** [comment]
Duplicate for #1612, will close this one.
