### ISSUE TITLE
I think users should be able to choose whether to enable offcanvas on Tablet view

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1647]
By default, offcanvas will only show on small mobiles. In my practice, on tablet, with the window width being only 768 or less,  often times menu or even logo are folded to two lines. And I think this must be a common issue to many users. Thus, instead of having to edit CSS, why not allow us to enable offcanvas on tablet view from backend UI?
Besides, sometimes I feel on tablet, a non-responsive layout would be even better, just saying.

**Comment by DamirPecnik** [comment]
You can alter the brakepoint for the mobile menu and show it sooner here:
![2016-10-30 23 43 39](https://cloud.githubusercontent.com/assets/10489911/19840633/b72e89be-9efa-11e6-905d-fa3c66bc3de5.jpg)

**Comment by newjie** [comment]
I thought of this way but I am afraid it is going to affect other settings

**Comment by DamirPecnik** [comment]
Like what?

**Comment by newjie** [comment]
I did a lot of media queries in my custom.scss using the breakpoint mixin,something like 

```
@import "dependencies";

// typically max 47.938 rem
@include breakpoint(mobile-only) {}
// typically min 48rem
@include breakpoint(no-mobile
) {}
```
and much more. 

I am afraid if I change the breakpoints settings, it will have an impact on these CSS styles

**Comment by DamirPecnik** [comment]
Mobile Menu is only setting when the offcanvas will be enabled and mobile button shown, nothing else...

**Comment by w00fz** [comment]
Yah mobile menu is reserved for offcanvas only, your other media queries won't be affected.

**Comment by mahagr** [comment]
I'm closing this issue as being answered.
