### ISSUE TITLE
Missing features in Grav implementation

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#1648]
* [x] Styling for alerts is missing
* [x] Positions have both title and alias, edit missing from alias
* [x] Positions: Assign to all pages missing (instead of checking all individual pages)

**Comment by w00fz** [comment]
Reminders:

#2 Switch between `title` and `key` so both Title and Position name can be edited

**Comment by w00fz** [comment]
Also 455af2ecb317d
