### ISSUE TITLE
Grav - remove admin padding 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1650]
This is just a suggestion for a minor visible change which would make the Gantry admin in Grav look more like it is in Joomla and WP. 
```

#admin-main .content-padding {
    padding: 2.5rem;
}
```
could be removed to make it flush, please see pic.

![g5_grav_adminpadding](https://cloud.githubusercontent.com/assets/5719486/19891362/0be8ffac-a040-11e6-9948-2c9d3f90479b.jpg)

**Comment by w00fz** [comment]
I don't think it will look good with G5 being flushed and all other Grav's pages not. Switching between Configurations will look somewhat odd.
