### ISSUE TITLE
WordPress: multiple default outlines like in Joomla?

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#1651]
In Joomla, one sets the default outline in the Joomla Template manager (only way I know). When you do that, the outline is labeled in G5 Outlines as Default. (I don't think this is in the documentation. It should be.)

However, in Wordpress, I guess the way to set the default outline is to click All for the outline in assignments. New posts, even though they are not checked in Assignments seem to inherit the default outline. There is no indication in the Outline manager that any outline is default. If one, then assigns the new post to a different outline, it remains with the default outline. 

If there is another way of setting a default outline in WP, please enlighten me. I see nothing in the documentation. If this is the way to set default, you should label the outline as default in the outline manager. If page is not checked for the default outline, it should revert back to the base outline. If the unchecked page is assigned to another outline, it should use that outline, but it doesn't.

It seems as a lot of things aren't working properly with WP default outlines or I'm missing something. This testing was all done with the current WP Interstellar Rocket Launcher.

**Comment by newkind** [comment]
Base outline = Default outline in WordPress. All pages that aren't assigned anywhere will load everything that's set in base.

**Comment by mahagr** [comment]
Just a side note, I'm currently working on assignments in Grav positions/modules and I'm just adding a feature that makes the modules to appear in every page, kind of making them as default. We will likely do something similar with WP widgets (allowing assignments)..

But back to the question: what is the reason why you would like to default on other than base outline? In Joomla we kind of have to do that because of Joomla allows default to change, but I'm not sure benefits of doing the same in WP.

**Comment by topwebs** [comment]
1. Base outline does not work properly as default. Let me repeat. I go to another outline and assign it to all menu items. I uncheck one post, save, clear cache. I look at the post and it did not revert to base outline, it is using the outline that I unchecked it from. Not correct.
2. Why a different default? It gets very complicated when I am using different utility classes to essentially serve different outlines to mobile. Maybe I could do it all with base outline, but I would prefer not to. Also, in base outline, you can't inherit from other outlines. This also makes what I am trying to do with mobile difficult. The whole concept of having an outline for mobile, I think needs to be considered. It would be very helpful.

**Comment by mahagr** [comment]
1. It should revert back to using default. I remember fixing a bug on unassigning outlines; I'll contact you in gitter and send you a debug tool to help out tracking down this issue.
2. Good answer. I just wanted to find out your use case to justify why we need this.

As I happen to work on this right now, I'm going to talk with @w00fz and @newkind about this.

**Comment by mahagr** [comment]
One use case that comes into my mind is to be able to assign default outline by language.

**Comment by mahagr** [comment]
Applies to Grav as well.

**Comment by dudewithamood** [comment]
Yes, I second this, as per use case outlined in #1703...

**Comment by mahagr** [comment]
Support added to Grav via language support. Though if languages are disabled, selecting default will not be possible.

**Comment by mahagr** [comment]
WordPress part of this issue is duplicate to #634

**Comment by mahagr** [comment]
If this feature will be implemented like in Grav, it'll allow assignments by default. For mobile, though, there is a need to add an assignment type, so if that's what is needed, please add a new issue for it.
