### ISSUE TITLE
demo site and demo content for Gantry 5

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1653]
I think it would great if there was a demo at demo.gantry.org showing of Typography, module styles (the many variations) different particles and other general stuff like a template producer does so the end user can see what the template/framework can do, what these items are called and what they need to do to enable these feature.

If you do a typography page you can instantly show of what can be styled in the backend and show how flexible gantry is (to the unconverted).

Currently there is no demo site. Gantry does ship with 2 default outlines, a basic page and one that shows off some particles.

You could put all of this knowledge in a single outline and include it within the gantry package or make a demo site at gantry.org but the descriptions and text within the elements of the page would be descriptive about the feature and how to use it.

You could call the outline 'Showcase'

an example
http://demos.jvgtheme.pl/hassium/index.php/pages/typography

**Comment by jh96** [comment]
I always use this page for reminding myself about typography
http://demo.gantry-framework.org/typography

**Comment by shoulders** [comment]
is this still valid for gantry 5 as this is for the old Gantry 4 framework

**Comment by mahagr** [comment]
Demos for helium are almost ready and just waiting for finishing touch. They will also be available for users to download.

**Comment by mahagr** [comment]
I'm closing this question as we are already in progress of adding demo for Helium together with installable demo content.
