### ISSUE TITLE
Multiple problems with iPads and Helium template

### ISSUE THREAD

**Issue by jh96** [gantry/gantry5#1654]
Tested on iPad mini and iPad2 and in the Safari responsive design mode.

- Carousel section: The hamburger doesn't appear in portrait or landscape mode so the long menu scrunches up and wrecks the formatting of the area.
- Expanded section: The scss is out by a few pixels on the on the rt hand side, but in portrait mode you lose a few letters from each line.

![img_0363](https://cloud.githubusercontent.com/assets/14791142/19963275/8d68de2a-a1b3-11e6-86a8-d33696da0064.PNG)
![img_0364](https://cloud.githubusercontent.com/assets/14791142/19963276/8d958466-a1b3-11e6-999d-b5f2c3a835b9.PNG)

**Comment by newkind** [comment]
Second issue has been already fixed in b6833c3a925da23be3d6fb8426d446833decc77e

**Comment by newkind** [comment]
Tablets shouldn't have hamburger menu, although I had to remove the menu overlay to make buttons clickable in 88854cd375729a943661ddbefbacfc894fb73d86

This issue is now all fixed :)
