### ISSUE TITLE
Translating Gantry 5 Hydrogen theme (Wordpress) with poedit errors

### ISSUE THREAD

**Issue by HenriKorhola** [gantry/gantry5#1655]
I was trying to create a translation to Hydrogen theme using poedit and the g5_hydrogen/languages/g5_hydrogen.pot file provided with Hydrogen theme. I opened up the file in Poedit program and got the following error:

![2016-10-31_14-31-16](https://cloud.githubusercontent.com/assets/4116332/19964809/8d070484-a1cc-11e6-9cfb-77a7553b679d.png)

And when I try to make PO file of this POT file I get this error:

![2016-11-03_13-54-40](https://cloud.githubusercontent.com/assets/4116332/19964927/26088c20-a1cd-11e6-9686-1c115804a15f.png)

**Comment by newkind** [comment]
Are you sure you are using latest version of Hydrogen? I just checked the pot file and there are no duplicated strings in the latest version.

**Comment by HenriKorhola** [comment]
You are right, I had an older version of the theme. It works just fine now after update, thank you!

**Comment by newkind** [comment]
No problem :) Closing!

**Comment by mahagr** [comment]
Not really invalid, but... already fixed.
