### ISSUE TITLE
Gantry 5 Hydrogen (Wordpress) Password form missing translation

### ISSUE THREAD

**Issue by HenriKorhola** [gantry/gantry5#1657]
Password form seems to be missing translation for one field:
![2016-11-03_14-39-26](https://cloud.githubusercontent.com/assets/4116332/19966182/5a33f088-a1d3-11e6-9a55-5fa3671601cd.png)

In the password-form.html.twig there is "Password:" (note the : in the word) translatable item but this is not found in the g5_hydrogen.pot file, there is only "Password".

**Comment by w00fz** [comment]
Thanks, this was also Helium. Fixed now.
