### ISSUE TITLE
Dude about "Toggle Visibility"  in Gantry

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#1658]
Hello,
I've been around for hours on a topic.
For what is the "Toggle Visibility" option in the "Offcanvas Section" on Google searched and analyzed the source code Gantry, but I can not usefully give this option.

I changed the values of the option of "Mobile menu" to "Always" but I see the effects.
https://s13.postimg.org/4ld6ozpk7/Fire_Shot_Screen_Capture_107_Veterinaria_Mast.png
Could someone guide me about it?
Thank you

**Comment by lavert** [comment]
Are you trying to make your mobile menu visible on desktop sites? The easiest way to do this is the increase the screen size at which it's visible in the backend of gantry on the Styles tab at the bottom, you'll see the breakpoints. The mobile menu has default I think of 48rem as the setting, this means at that screen size and under the mobile menu will be visible. Just increase that to whatever you want.

**Comment by Mineslu** [comment]
Great Lavert, just what I needed.
but then this option is not useful?
![fire_shot_screen_capture_107_veterinaria_mast](https://cloud.githubusercontent.com/assets/9434043/20020555/d2ffdc12-a29f-11e6-9b74-9ab7f385c60a.png)
Thanks

**Comment by w00fz** [comment]
This was an issue that's now fixed in #1630
