### ISSUE TITLE
Joomla Menu Alias are presented by dates and not their name in mainmenu.yaml

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1659]
Joomla menu items are referenced in the mainmenu.yaml.

I am running joomla 3.6 and have the forum menu item in my **'main menu**' as a **'Menu Item Alias'** which show an alias of **'2016-09-30-14-14-00'** and this is what is then shown in the mainmenu.yaml.

The problem is that if you have many menu items as alias then you will not be able to work out which item is what easily when looking at or editing the maninmenu.yaml

This might be more an issue with joomla but is there anyway you can pull the 'Menu Title' when a 'Menu Item Alias' is detected.

**My Example Menu**

![menu](https://cloud.githubusercontent.com/assets/319997/20004561/fc260b7c-a284-11e6-87a8-7a52fa3fcc7a.jpg)

**Menu Items**

![menu items](https://cloud.githubusercontent.com/assets/319997/20004566/0001789e-a285-11e6-86ac-a4857b6cc0c0.png)

**Forum Menu Item**

![forum menu item](https://cloud.githubusercontent.com/assets/319997/20004576/164270d6-a285-11e6-98c4-406ad5cb7047.png)

**mainmenu.yaml**

With Icon code
ordering:
home: ''
blog: ''
software: ''
2016-09-30-17-17-00: ''
kb:
articles: ''
links: ''
videos: ''
stuff:
links: ''
videos: ''
search: ''
items:
2016-09-30-17-17-00:
id: 745
dropdown_dir: right
dropdown_hide: '0'
width: auto
icon: 'fa fa-anchor'

**Comment by mahagr** [comment]
Its not a bug as title is not unique identifier for menu item aliases. Joomla only has two ways to identify menu items, one being id and another alias (or path including alias).
