### ISSUE TITLE
Alignment in gantry5/hydrogen

### ISSUE THREAD

**Issue by cryptex86** [gantry/gantry5#1660]
Hi All,

I don't know if this is the right place, but I couldn't find another place to ask my question.

I'm currently building a new website using the Gantry5 framework in combination with g5_hydrogen theme and Wordpress, and I am finding some issues with the alignment of text and images in particles.

They are aligned perfectly from left to right, but I also would like to align them from top to bottom. Is there anybody who can help me with this? 

Examples can be found at this url: https://beta.hilfertheem.nl (username: gantry password: thanks!)

Thanks in advance
Tim

**Comment by w00fz** [comment]
Hi,
this is purely CSS not really Gantry related but a quick way to handle this is as follow:

```css
.g-particle center {
	top: 50%;
	position: relative;
	transform: translateY(-50%);
}
```

You can read more about how to include that custom css via our documentation http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

Hope that helps!
