### ISSUE TITLE
Grav - Color Field Double Click Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1661]
When i try to doubleclick to select the color code on the Color Field in Gantry on Grav the text is not selected also if i try to click and drag also doesn't work.

Video here ...
http://share.webthemer-it.hr/Screencast_10-36_05-11-2016.mp4

**Comment by w00fz** [comment]
This is mostly an issue in the Grav's admin plugin which i fixed in here https://github.com/getgrav/grav-plugin-admin/commit/0757d49d9f637cc58ab57064b6bde5f5168cb76b
