### ISSUE TITLE
Grav - Positions Particle Assignments Filter

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1662]
In the Assignments the All and None filter does not work.
![2016-11-07 01 44 15](https://cloud.githubusercontent.com/assets/10489911/20043335/ff7d40d4-a48b-11e6-84e7-17caf145711a.jpg)

**Comment by w00fz** [comment]
This is still a work in progress Matias is looking at.

**Comment by w00fz** [comment]
Nevermind, I misread the issue. Fixed now.
