### ISSUE TITLE
Joomla Articles particle settings in cloned outline have no check boxes

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1665]
I am using a new outline with no inheritance (made it via a clone at some point) and i have enabled particles on the template.

The reason i am doing this is to design a template which i can then move to default to use it as a base outline at some point for my own designs.

On  **"My new outline --> particles page -->'Joomla Articles' particle --> 'Articles' tab"** there are no check boxes next to any of the items on the first tab.

![joomla articles no inheritance check boxes](https://cloud.githubusercontent.com/assets/319997/20052898/f4b8c21c-a4cd-11e6-9426-a1feab3d25f0.png)

This causes these settings to be overridden and saved in g5_helium/custom/config/18/particles/contentarray.yaml when i make any changes to any particle setting. I would rather not override these unless i have to.

I think this is a bug and that there should be text boxes next to the values.

Thanks

**Comment by JoomFX** [comment]
This seems to be cause by https://github.com/gantry/gantry5/commit/c2e5b527881176a697fea496331c8078d044d4b7

I'm not sure how it should really be...

**Comment by shoulders** [comment]
reference #1578 thanks JoomFX

**Comment by mahagr** [comment]
Those settings shouldn't be there at all IMHO. They have been set to exist only as overrides (meaning that the fields should only exist inside layout, not here).

**Comment by mahagr** [comment]
I'm now hiding those fields as they will not get used regardless if you have them set or not -- all of those fields get overridden in the particle instance.
