### ISSUE TITLE
Google Analytics atom is not working

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1666]
I post this issue because I think it could be an UI issue that affects other atoms.

Previously I set GA atom with correct tracking ID in Base Outline, it WAS working, every other outlines get it and I can easily find the script tag with $('script'), also I can see traffic from GA's admin page.
Later I tried to use google tag manager to host the GA script, so I disable the  GA atom from Base Outline. Ever since then, I can never get GA atom to work. I re-enable it, delete GTM item from the "Custom CSS/JS" collections, I even try creating new GA (instead of inheriting it from Base Outline) atom in a specific outline and re-enter the tracking ID, nothing works. By not working I mean I can't see the GA script from $('script'), and on GA's amin page, I send test traffic but don't get any active user report, which indicates the GA script is not properly loaded.

**Comment by mahagr** [comment]
Can you write simple instructions to test this out?
