### ISSUE TITLE
Hydrogen - errors during recompile (tested on grav)

### ISSUE THREAD

**Issue by bomkallo** [gantry/gantry5#1667]
Recompile css throws a long column with these:
Undefined variable $header-text: line: 15
Undefined variable $header-text: line: 29
Undefined variable $header-text: line: 45
Undefined variable $header-text: line: 49
Undefined variable $border-radius: line: 50
...

**Comment by JoomFX** [comment]
You need to set the variable `!default`.
Every SCSS variable must have a `!default` value set.

It seems that the `$header-text` and `$border-radius` variables are custom ones, variables that you have created.
It depends where you are using them. The variable `!default` must be set before the SCSS compiler tries to compile the code:

1. If you are using them in the core template SCSS files, then set the `!default` in the `_colors.scss` file.
2. If you are using them in the `custom.scss` file, then set the `!default` at the top of the `custom.scss` file:

```
// Set the variable defaults in case they are missing in the template
$header-text: #000000 !default;
$border-radius: 2px !default;
```

**Comment by JoomFX** [comment]
Hmm, sorry, just noticed that it is about Grav and noticed the "bug" label that Matias has added 😉

**Comment by mahagr** [comment]
Its likely related to the new code we've added few days ago.

CC @hexplor
