### ISSUE TITLE
hydrogen - joomla blog layout - multi-column issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#167]
it seems that the number of blog columns does not reduce when minimizing browser size, which causes some layout issues, please see pic.

![g5_bloglayout](https://cloud.githubusercontent.com/assets/5719486/7436374/c1ebb9d2-f012-11e4-87ec-917749cd4122.jpg)

**Comment by kevlardev** [comment]
We are missing some responsive rules from bootstrap, im getting those added soon

**Comment by adi8i** [comment]
@kevlardev would be great if you could add some media, so on mobile will be only one column.
