### ISSUE TITLE
Post pagination 

### ISSUE THREAD

**Issue by team187** [gantry/gantry5#1670]
Hello

Is there by any chance a possibility to enable previous and next post pagination in wordpress?

I tried in several gantry framework sites and this option is not in the code for posts as I saw, only for pages.

I am using hydrogen theme if it matters.

Thanks

**Comment by team187** [comment]
I need the function like it is on the image.

Please tell me if this is possible or not I don't want to waste anyone's time.

Thank you in advance!

![posts](https://cloud.githubusercontent.com/assets/9374495/20330129/e76d1e48-ab9c-11e6-9959-c0180428f227.png)

**Comment by newkind** [comment]
You can edit the `views/partials/content-single.html.twig` and place this snippet wherever you need it :

```
{% if post.prev.link %}
        <a href="{{ post.prev.link }}">&larr; {{ post.prev.title }}</a>
    {% endif %}

    {% if post.next.link %}
        <a href="{{ post.next.link }}">{{ post.next.title }} &rarr;</a>
    {% endif %}
```
