### ISSUE TITLE
Disabled atoms are still being rendered

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1671]
I always feel like there is some problem with the inheriting system. I say "feel" because sometimes it works as expected but sometimes not. This time I think I've successfully seized a reproducable malfunction, please watch the 2 mins long video:

http://peaceevertvimg.org/1.php

**Comment by mahagr** [comment]
Yes, it does look like a bug. Thanks for reporting it.

**Comment by newjie** [comment]
By the way, another minor issue: you can see how "difficult" it is to drag a new Atom into creation in the video. :)

**Comment by mahagr** [comment]
We are aware of the drag issues. Its just not as easy to fix as you would think because of how HTML works.

**Comment by hacki65** [comment]
For GA i can confirm this, BUT other atoms seems to be working OK. I think it's a bug in GA Particle itself so the switch toogle dont has effect.

**Comment by mahagr** [comment]
Disabled atoms should not be called in the first place, so I don't think there's anything wrong in the GA atom itself.
