### ISSUE TITLE
Gantry5: unable to see particle configuration/options on layout

### ISSUE THREAD

**Issue by samwenger** [gantry/gantry5#1673]
Hello,

I actually have a problem with Gantry 5 on my Joomla 3.6.4 website. Since some weeks, when I clic to open the parameters of any particle nothing is displayed, only an empty white block pop-up instead of the parameters.

An idea of what is clashing? 

Any help would be really appriciated

![problem](https://cloud.githubusercontent.com/assets/23389575/20196949/57addc00-a79d-11e6-97fe-5dbe1c7054a4.png)

**Comment by mahagr** [comment]
Usually issues like this are caused by bad response from the server. If you can contact me in gitter chat, I can take a look what's going on in there.

**Comment by mahagr** [comment]
@samwenger As there has been no follow-up for this issue, I'm assuming that it has been solved. Please re-open the issue if this is not the case.
