### ISSUE TITLE
fopen error with Gantry 5.3.8

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1676]
I now have three templates Xenon, Topaz and Sienna that I updated to 5.3.8 on my MAMP for WINDOWS and I now get this CRIKEY error only on the front end:
An exception has been thrown during the rendering of a template ("fopen(php://stderr): failed to open stream: operation failed") in "@nucleus/page_head.html.twig" at line 8.

Open: C:\MAMP\htdocs\Topaz\libraries\gantry5\vendor\twig\twig\lib\Twig\Template.php
```
                // this is mostly useful for Twig_Error_Loader exceptions
                // see Twig_Error_Loader
                if (false === $e->getTemplateLine()) {
                    $e->setTemplateLine(-1);
                    $e->guess();
                }
 
                throw $e;
            } catch (Exception $e) {
                throw new Twig_Error_Runtime(sprintf('An exception has been thrown during the rendering of a template ("%s").', $e->getMessage()), -1, $template->getTemplateName(), $e);
            }
        } elseif (false !== $parent = $this->getParent($context)) {
            $parent->displayBlock($name, $context, array_merge($this->blocks, $blocks), false);
        }
    }
```

**Comment by mahagr** [comment]
@DanGthatRokGallery The real error doesn't happen in above location; it just gets caught in there.If you scroll down on the erorrs, you should see like with `fopen('php://stderr', 'w')` in it. Its likely line 183 in `vendor/leafo/scssphp/src/Compiler.php`..?

For some reason your apache error.log file cannot be written.

**Comment by mahagr** [comment]
Quick question: What happens if you replace above line with constant STDERR?

    $this->stderr         = STDERR;

**Comment by DanGthatRokGallery** [comment]
Hi Matias
For three days I've watched my Gantry 5 templates succumb to this error and tonight it's working fine again - so I guess I have to chalk it up to the Weird World of Windows 🎱 

Thanks for looking Matias

**Comment by mahagr** [comment]
It has to be permissions issue on log files... If you get the same issue again, please consider above code change to test if it fixes the issue.
