### ISSUE TITLE
Joomla breadcrumbs seperator icon placement issue

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1678]
This is a minor issue but I thought I would mention it.

When using breadcrumbs in helium on the home page the initial separator icon is vertically aligned to the top and on my links sub-page the initial breadcrumb separator icon is vertically aligned to the top but not as much and you can see another icon or element in the same space.

**Homepage**
https://quantumwarp.com/
![homepage breadcrumb](https://cloud.githubusercontent.com/assets/319997/20299932/d203e6aa-ab14-11e6-8838-0f006ed5710b.png)

**sub page**
https://quantumwarp.com/kb/links/list-alpha/j
![links directory breadcrumbs](https://cloud.githubusercontent.com/assets/319997/20299974/e8ee5cb0-ab14-11e6-9409-0c7647322141.png)

**sub page css rules from firefox**
![firefox css rules](https://cloud.githubusercontent.com/assets/319997/20300131/976214d0-ab15-11e6-9ff1-6aeeb71c0380.jpg)

**What I tried**
I tried the following code to fix the issue which works for the home page icon but not for the sub page

```
/*-- Fix breadcrumb arrow going to the top - only second identifier might be needed--*/
.breadcrumb [class^="icon-"], .breadcrumb [class*=" icon-"] {
    line-height: 2;
}
```

I think i have narrowed it down to the divider wrapper and in particular the icon-location class and how that is applied with the various rules applied from helium.

`<span class="divider icon-location"</span>`

Thanks for any help and I do appreciate this is a minor issue

**Comment by mahagr** [comment]
Template is modified Helium.

**Comment by newkind** [comment]
I tested two different Joomla versions and all is fine for me :
!https://monosnap.com/file/qcEeAyozSmEnilmDBVbAulFbhgrqbQ.png!

There's an extra class on your breadcrumbs `icon-location` which is not in my installations and it's that extra class that's breaking things. Any ideas where it comes from?

**Comment by shoulders** [comment]
I think it might be k2. I am just away from my of so I can not double check

On 25 January 2017 16:07:51 GMT+00:00, NewKind <notifications@github.com> wrote:
>I tested two different Joomla versions and all is fine for me :
>!https://monosnap.com/file/qcEeAyozSmEnilmDBVbAulFbhgrqbQ.png!
>
>There's an extra class on your breadcrumbs `icon-location` which is not
>in my installations and it's that extra class that's breaking things.
>Any ideas where it comes from?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gantry/gantry5/issues/1678#issuecomment-275150319

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mahagr** [comment]
Class `icon-location` is there in Joomla 3.6 and it is always set.

**Comment by newkind** [comment]
@mahagr my screenshot comes from brand new installation of 3.6.5 and I didn't have that class in it

**Comment by shoulders** [comment]
My Joomla is 3.5.1

in the file modules/mod_breadcrumbs/tmpl/default.php   line 22

````
<ul itemscope itemtype="https://schema.org/BreadcrumbList" class="breadcrumb<?php echo $moduleclass_sfx; ?>">
	<?php if ($params->get('showHere', 1)) : ?>
		<li>
			<?php echo JText::_('MOD_BREADCRUMBS_HERE'); ?>&#160;
		</li>
	<?php else : ?>
		<li class="active">
			<span class="divider icon-location"></span>
		</li>
	<?php endif; ?>
````

This is the template for breadcrumbs I think. Thius matches with the icon-location class

**Comment by newkind** [comment]
Fixed :)
