### ISSUE TITLE
Offcanvas menu, disable left gesture

### ISSUE THREAD

**Issue by linkinformatica** [gantry/gantry5#1680]
Hi. 
The problem is: 
on mobile/tablet when you scroll down (slightly to the left), sometimes it accidentally activates the offcanvas menu. Is it possibile to disable this left gesture, and activate the offcanvas menu only touching the three bars menu icon?

It's really annoying for the users

Thanks

**Comment by marktaylor46** [comment]
Turn it off in the offcanvas section settings.

![2016-11-16_09-28-41](https://cloud.githubusercontent.com/assets/11683218/20341686/277703d6-abdf-11e6-91c0-d080fb19a15e.png)

**Comment by linkinformatica** [comment]
I really miss that option! LOL

Thanks a lot ;)
