### ISSUE TITLE
Wordpress/Timber function breaks the particle in Joomla

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1681]
@mahagr @w00fz @newkind I know guys, I can imagine what your first reaction was when you read the Title 😄 

Let me explain what I'm trying to do...
I have a "Modal Search" particle and I want to make it platform independent. I want to have just a single particle for all platforms instead of having "Modal Search (Joomla)", "Modal Search (Wordpress)" and "Modal Search (Grav)".
Here is the Twig code that I have:

```
{% if gantry.platform.getName() == 'joomla' %}
	{{ gantry.platform.filter("{loadposition modal-search}")|html|raw }}
{% endif %}

{% if gantry.platform.getName() == 'wordpress' %}
	{{ function('get_search_form') }}
{% endif %}
```

The particle works perfectly fine in Wordpress, but the `{{ function('get_search_form') }}` code breaks the particle in Joomla.
I know that there is no Timber in Joomla and that this function is undefined, but I was hoping that everything that is inside the `{% if gantry.platform.getName() == 'wordpress' %}` condition will not be processed if you are in Joomla.

Can you please let me know if there is a solution for my issue (a different way to write the code perhaps) or if you are willing to implement something that will prevent the Wordpress/Timber specific code from breaking the particles in Joomla/Grav?

I do believe that being able to write Wordpress/Timber specific code in the platform independent particles is vital for Gantry 5 and especially for the moment when there will be a Particle Marketplace.

**Comment by newkind** [comment]
It's a known issue. Just replace the `function` with `gantry.platform.call` and you should be fine ;)

**Comment by JoomFX** [comment]
Awesome! Simply awesome!
Replacing `function` with `gantry.platform.call` did the job.
Thanks a million @newkind 😉

**Comment by JoomFX** [comment]
Sorry for bothering you again @newkind 😉 

I'm trying to modify and re-write the "Login Form" particle so I can add the functionality to another (platform independent) Login particle that I have.
I replaced all `function` with `gantry.platform.call` but there is another code that also breaks the particle in Joomla. It is the translatable code:

```
<label for="username">{{ __('User Name', 'gantry5') }}</label>
```

How should I re-write `{{ __('User Name', 'gantry5') }}` so it does not break the particle in Joomla?
Thanks 😉

**Comment by JoomFX** [comment]
@newkind Apart from the above, could you please tell me where the language strings from the "Login Form" particles are stored. I couldn't find them in any PO/POT files.

I'm wondering if I need to declare those translatable strings in a PO/POT file... it seems that they are not declared in the G5 core (where the "Login Form" particles comes from).

**Comment by mahagr** [comment]
@JoomFX You could use `|trans` filter and do the translation in Gantry specific way. This is really an area where I could use some help as we really need to start figuring out a workflow and implementation for stuff like this. Next version will be focusing on languages and frontend editing and its really the best time to tackle on this. :)

**Comment by JoomFX** [comment]
@mahagr Thanks Matias!

By the way, could you please give me some more details about the way I should use the `|trans` filter and how all this actually works.

Should I just replace this:

```
{{ __('User Name', 'gantry5') }}
```

with this:

```
{{ 'Username'|trans }}
```

And if I use `{{ 'Username'|trans }}` how would the user translate the "Username" word? I'm just not sure how it all works.

Apart from my questions, you said "_This is really an area where I could use some help_" - let me know how I can help 😉

**Comment by mahagr** [comment]
`|trans` filter uses language keys like Joomla does.

What comes for helping us, like I said, we really need a good plan on translations are supposed to work. :) I'll get back to it.

**Comment by JoomFX** [comment]
Thanks Matias, but here comes another issue that you (the Rockettheme guys) might not agree with...

I'm trying to have all our particles "template-independent". The idea is to allow the users to use the particles in whatever G5 template they want.
If I hardcode `{{ 'G5_LOGIN_PARTICLE_USERNAME'|trans }}` in the Twig, then I will also have to include the `G5_LOGIN_PARTICLE_USERNAME` language key in the template's language file which no longer allows this particle to be "template-independent".

For this exact particle it will be best if there is a replacement (another syntax) for the `{{ __('User Name', 'gantry5') }}` code which will not break the particle in Joomla and Grav.
Also, maybe @newkind can answer this, if I use `{{ __('User Name', 'gantry5') }}` should I declare it in a POT file in order for the user to be able to translate the `User Name` text? I'm just too new to Wordpress and I'm not quite sure how all this works. I do not see the `gantry5` text domain nor the `User Name` text declared anywhere in G5.

Regarding the translation implementation in G5 - I'll think about it 😉

**Comment by mahagr** [comment]
Ideally each particle should have its own language file, but while we're waiting that to happen, there's another way, which I'm already using in admin.

```twig
    {{ 'Here is my English string'|trans_key('MY_ENGLISH_STRING') }}
```

Basically that will allow you to write English into the particle twig file while at the same time defining the translation key for it. If the key exists in your language file its translation will be used instead the text you wrote in English.

PS: This works only from the current CI build and later.

**Comment by JoomFX** [comment]
Thanks a lot Matias!
Yep, I will go with the `|trans_key` option for now 😉 

Regarding a particle specific language file (when needed) - yes, I'm all in for that! As Djamil said in [this](http://www.rockettheme.com/blog/team/218-rockettheme-update-a-focus-on-innovation#comment-2686701915) and [this](https://github.com/gantry/gantry5/issues/680#issuecomment-236000154) comments, one day each particle will have its own folder so all assets, language file, and so on can go there (as it currently is with the Joomla modules and Wordpress widgets).
