### ISSUE TITLE
Positions keys break in Grav

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#1682]
When I create a new position, I get untitled in both the title and key area with little pencils. When I title the position the key changes to position-untitled, the pencil disappears, and I can't edit it.

When I refresh the page the key changes to position-header, but I still can't edit the key. The key is editable on the original two.

Saving gives me a 404 error.

<img width="1012" alt="screen shot 2016-11-16 at 7 12 35 pm" src="https://cloud.githubusercontent.com/assets/4026828/20372446/f1c00132-ac30-11e6-8b65-04b5b3bd06b9.png">

<img width="268" alt="screen shot 2016-11-16 at 7 12 41 pm" src="https://cloud.githubusercontent.com/assets/4026828/20372448/f1cc7606-ac30-11e6-8452-21b85ff7b078.png">

**Comment by mahagr** [comment]
@w00fz I've fixed the broken HTML on AJAX response; there's no need change the contents of the block from JS anymore (in fact it uses wrong link).

**Comment by w00fz** [comment]
This is fixed but changing position is not really doing anything. Ajax goes trough and comes back with the new value but on refresh is not preserved.

**Comment by mahagr** [comment]
I'm reopening this to get the rest of it fixed.

**Comment by mahagr** [comment]
Issue from the first message should be fixed now.

There is still issue with renaming position with unsaved items in it.
