### ISSUE TITLE
slideshow particle not displaying image

### ISSUE THREAD

**Issue by huda6491** [gantry/gantry5#1683]
the slideshow particle is not displaying the image and is only showing the title and image description.

before discovering this issue i hadn't installed the UIkit properly so it displayed the images statically but once i completed all the installation steps the slideshow animation started but there are no images displaying just the description box.

how do i fix this so the images will display?
@JoomFX  maybe you can advise.

TIA

**Comment by JoomFX** [comment]
Hey @huda6491 ,

The "Slideshow" particle should be working just fine.
Anyway, please have in mind that the issues on Github are meant for core Gantry 5 issues/question only.
Please contact me by using the "Contact Us" link in the footer of our website and I'll look at your issue 😉

**Comment by mahagr** [comment]
Closing as 3rd party issue.
