### ISSUE TITLE
Custom Menu item type throw 404 error

### ISSUE THREAD

**Issue by Danultimate** [gantry/gantry5#1684]
When I link a a custom gantry page to a menu item it gives me a 404 error.

![1](https://cloud.githubusercontent.com/assets/19416742/20392642/c0916986-aca6-11e6-9184-f25095513149.png)

![2](https://cloud.githubusercontent.com/assets/19416742/20392645/c5693e16-aca6-11e6-9566-6b67dc22c4f6.png)

**Comment by mahagr** [comment]
Did you rename `htaccess.txt` into `.htaccess`? That is the most common reason why SEF URLs aren't working.

**Comment by Danultimate** [comment]
@mahagr Thanks for the answer,  I enable the SEF urls and it is working now.
