### ISSUE TITLE
Lock overflow-y when dragging particles to the delete zone

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#169]
When you drag particles in Layout Manager to delete zone, overflow-y should get locked on drag so the whole page with layout manager wouldn't scroll up when you geat near top border of browser window.

**Comment by w00fz** [comment]
This is how it works right now I'm not sure i'm following?
When you start dragging up/down there are zones at the top and bottom of the viewport that trigger the page to scroll up down. If you are hovering over the trash zone, the scroll is interrupted.

![gantry 5 - administration 2015-05-02 19-11-44](https://cloud.githubusercontent.com/assets/11734/7443455/af082c2c-f0ff-11e4-8cfb-b7ae00d3aef4.jpg)

**Comment by newkind** [comment]
Hmm yah, I guess it needs to be that way as when the dragging starts this can be either for deleting or just moving around. Sorry about that. I'm gonna close that one ;)
