### ISSUE TITLE
Logo Image and text only go behind the hamburger icon

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1691]
when using either an image or just text in the logo/image particle these go behind the hamburger icon. When using SVG this works correctly.

My website currently has the image installed https://quantumwarp.com/

I am using joomla 3.5.1 and Gantry 5.3.8

**text only**
![text only](https://cloud.githubusercontent.com/assets/319997/20456259/22011016-ae6b-11e6-9949-c3d717b23c7a.png)

**Image**
![logo under hamburger](https://cloud.githubusercontent.com/assets/319997/20456260/2abc40d6-ae6b-11e6-8566-260ab9c6af8f.png)

**SVG**
![svg hamburger](https://cloud.githubusercontent.com/assets/319997/20456262/388f8d08-ae6b-11e6-8690-1038f3e96d82.png)

**Comment by mahagr** [comment]
Looks like an issue in helium. Can you take a look @newkind ?
