### ISSUE TITLE
show wrong module's assignments 

### ISSUE THREAD

**Issue by jwfrancesca** [gantry/gantry5#1694]
Hi, I have issue with gantry backend modules. On all module's options/assignments my page are half wrong, the list of voice menu is not only in one column but it is irregular on more columnsand  Itsn't possible to selecte or unselect the wrong voices. All wrong voice are selected and I cannot change the option. You can see issue on attachment. Can you help me? 

![schermata 2016-11-19 alle 08 52 25](https://cloud.githubusercontent.com/assets/17391986/20463971/d27ebb2c-af3e-11e6-9e72-9245aae9dc46.png)

**Comment by shoulders** [comment]
Quick idea: Clear Joomla cache and browser cache. Make sure you also restart your browser.

**Comment by mahagr** [comment]
Do you have a custom admin theme or some component that changes modules or their assignments? Also where in the admin you're in?

I've never seen issue like this (my admin looks good) and Gantry shouldn't really affect module assignment tab in any way.

**Comment by shoulders** [comment]
After a recent joomla upgrade a couple of my module admin pages were all messed up and clearing all my caches fixed it.

**Comment by jwfrancesca** [comment]
Hi, I resolved issue. Cause was a mistake on some menu. Thank all for help.
Francesca
