### ISSUE TITLE
Plugin inserting button in Joomla editor

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#1698]
Just an idea (for lazy people...) could it be possible to have a plugin inserting a button in Joomla editor?
By clicking it one can insert any desired particle directly in an article, avoiding the use of {load position xxx}

**Comment by mahagr** [comment]
Instead of loadposition, did you try:

    {loadmodule mod_gantry5_particle, Particle Title}

The last parameter is the title of the module as you wrote it in module manager.

**Comment by beamaria** [comment]
Hi Matias, I know there is the possibility to use also the loadmodule nameofmodule} and I have no issue at all using {load position xxx}, but my question (asking for a new feature) is a bit different: I wonder if it could be possible to built an editor button inserting any kind of particle in a Joomla article..
Have a look at the screenshot: maybe beside "ReadMore, Article, Module, Image and Pagebreak" button there could be a way to add a "GantryParticle" button...

![shot](https://cloud.githubusercontent.com/assets/11693902/20485184/5757bfa2-aff2-11e6-802f-4f6c40c9383b.jpg)

**Comment by mahagr** [comment]
I'm not seeing any reason why we should do that as there's already button for adding a module. It works just great for particles and stores the parameters into database instead of trying to inject them to the article.

**Comment by beamaria** [comment]
Ok, it was just an idea, maybe not a good one ;) Thanks!

**Comment by mahagr** [comment]
The issue I had with the idea is that we already have module button (and shortcodes for it) and its working well. Adding same to particles wouldn't really give any benefit except maybe filtering...
