### ISSUE TITLE
Section Classes and HTML Attributes don't work!

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#17]
When trying to add class or attribute to the section it does not work!

![2015-03-29 00 03 45](https://cloud.githubusercontent.com/assets/10489911/6883293/3530411e-d5a7-11e4-86db-8b5e8653fd07.jpg)

**Comment by mahagr** [comment]
A few people reported about this on gitter chat. I need to check why they aren't working anymore (or in Joomla)

**Comment by mahagr** [comment]
Nice catch, copy paste error it seems.

**Comment by DamirPecnik** [comment]
CSS class is working now, but HTML Attributes still dont not getting any result in code.

**Comment by w00fz** [comment]
Yah that attributes I don't think us hooked up. Should be a collection or perhaps we need a simplified version of it for just key/value.

I'll reopen this so we don't forget

**Comment by w00fz** [comment]
We need a new `key-value` field for handling this kind of attributes
