### ISSUE TITLE
Remove enforced styling

### ISSUE THREAD

**Issue by bevels** [gantry/gantry5#1702]
_This is a request._

I'd really appreciate the ability to turn off all the default element styling. **(not override)**

For example: `p { margin: 1.5rem; }`

Padding, margins, colours, borders, even breakpoints.

Essentially a barebones mode that allows us to leverage the grid, particles, atoms, assignments, inheritance etc but doesn't impose stylistic rules.

Perhaps a toggle to switch out the default instance of nucleus for a stripped back version?

I know I can override the default styles with a custom css file (it's what I'm doing), but I'm sure many developers that appreciate well formatted code will agree, that looking at a bunch of crossed out styles in inspector is a coders equivalent to running your nails down a blackboard.

I understand the need to cater to a wide audience (including DIY'ers) but there are plenty of "entry level" tools like Beaver Builder, Divi etc.. that meet the needs of non-coders. Gantry is unique in that it offers professional developers the ability to rapidly create sites with a greater level of control than most (probably all) "drag and drop" frameworks. As it stands you've managed to strike a pretty good balance, but I'd love to see more emphasis placed on efficiency for front-end developers who are proficient in html/css/js.

Additional developer features might include:

- Easier white labeling of a default theme. Currently I rename files/folders and instances of the word 'hydrogen' within all files to a custom name. Not difficult, but it takes time.

- A code editor for html particles. Ace would be fantastic, it's easy to integrate and features very good syntax highlighting, (almost as good as a code editor). https://ace.c9.io/

**Comment by shoulders** [comment]
override helium.css with an empty file or the skeleton styling you want. should have the same effect.

**Comment by w00fz** [comment]
It kinda sounds like you are looking for a boilerplate theme to get you started. For us that was Hydrogen, have you considered creating a new theme based on Hydrogen that has all the unnecessary margins and paddings you don't like?

Both Hydrogen and Helium rely on our [Nucleus CSS framework](https://github.com/gantry/gantry5/tree/develop/engines/common/nucleus/scss) which is a very opinionated and streamlined CSS framework we feel fits most of the use cases. 

That said, you could create your own theme using your own framework (or even a variation of nucleus) to match all the needs you like.

Regarding the code editor for particles, I agree. We actually have a ticket already open about it and it's something we will eventually address!

Cheers
