### ISSUE TITLE
Conflict creating a new module.

### ISSUE THREAD

**Issue by Danultimate** [gantry/gantry5#1704]
When I try to create a new custom joomla module I get a black page with a gantry particle box.

![issue](https://cloud.githubusercontent.com/assets/19416742/20630522/479d6c82-b2ff-11e6-9ff4-4c3e23c977a3.png)

**Comment by marktaylor46** [comment]
Clear you browser cache - that's caused by an update to J3.6.3 or J3.6.4

**Comment by Danultimate** [comment]
Thank you so much for your help. @marktaylor46

**Comment by marktaylor46** [comment]
You're very welcome. :)

**Comment by shoulders** [comment]
@Danultimate 

if fixed, you should close this issue to keep things neat
