### ISSUE TITLE
Helium Gradient Overlay header section

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1706]
In Helium, the header section has a gradient overlay that has an option of "Enabled" and "Disabled"

The css that controls that is in the file `sections/_header.scss`

```
    @if $header-background-image {
        background: url($header-background-image) center center no-repeat;
        background-size: cover;

        @if $header-background-overlay == 'enabled' {
            &:before {
                position: absolute;
                width: 100%;
                height: 100%;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0;
                content: "";
                z-index: -1;
                opacity: 0.85;

                @include linear-gradient(40deg, $accent-color-1, $accent-color-2);
            }
        }
    }
```

However, **disabling** the overlay seems to have no effect.

I have tried to disable it in the `Base Outline`, `Helium - Defaults` and `Helium - Home - Particles` outlines, but no matter what, the overlay still shows.

I have recompiled the css successfully but the overlay still shows.

Any ideas on how to solve this?

**Comment by hacki65** [comment]
Seems to be its the OWL Carousel. If in this particle the option "Image Overlay" is enabled the overlay from section "Navigation" is used.

**Comment by newkind** [comment]
That's right, OwlCarousel can override this. This setting in Header style is mostly for cases when you don't have Owl in this section and still want to have a nice looking Overlay with different particle ;)

**Comment by chatman1974** [comment]
How to enable background image with overlay options for every sections in Helium theme?
i am talking about gantry 5 helium theme for joomla 3x
its enabled for Header and Testimonials sections as default. I want to enable those options for every sections as well

**Comment by chatman1974** [comment]
> 
> 
> How to enable background image with overlay options for every sections in Helium theme?
> i am talking about gantry 5 helium theme for joomla 3x
> its enabled for Header and Testimonials sections as default. I want to enable those options for every sections as well

Nevermind. I did it. 
I was edited "root/templates/g5_helium/blueprints/styles" every sectionname.yaml files . And i added background image and overlay opitons in "root/templates/g5_helium/scss/helium/sections" every _sectionname.scss files. woilaaa! Thats works!
