### ISSUE TITLE
Horizontal Joomla Module stacking

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1708]
Currently a module position particle that is added to gantry will allow you to add multiple modules into that position and they will stack vertically.

Is it possible to add an option to a module position particle to allow for horizontal stacking of modules.

**Comment by mahagr** [comment]
@shoulders Sorry for the delay in my reply. 

It is possible to stack modules horizontally by changing the used Module Chrome. It may also be possible to do this with CSS rules by applying a custom CSS class.

**Comment by shoulders** [comment]
I will have a play with the chrome and see if i can get it to work. it is not urgent so i might not do it for a while.  Don't worry about delays, i just finished a 5 minute programming job in 4 weeks.

**Comment by mahagr** [comment]
I'm going to close this issue. If in doubt, please ask how to do it in gitter chat.
