### ISSUE TITLE
Fixed Width and max-width option

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1709]
The Joomlashine template framework has this option where you can make the website a fixed width. This feature could be useful for some website designs where mobile is not an issue (or developing). You would also be able to set the width of the site within the Gantry admin.

This is probably related but perhaps being able to set the max-width within Gantry to allow people to basically change the desktop version of their site. This would also be set within the Gantry admin.

I am aware of the settings, this settings I am guessing have fixed values which cannot be changed although you can change this setting per section.

- Fullwidth (Boxed Content) [Default]
- Fullwidth (Flushed Content)
- Boxed

http://docs.gantry.org/gantry5/configure/page-settings

thanks

**Comment by adi8i** [comment]
Well, I think this was discussed before, nowadays responsive website is a must and I don't think an option like this makes sense. 

Instead you can adjust breakpoints breakpoints to get a min and mix width.

**Comment by mahagr** [comment]
I agree. If you are developing you can just use whatever window size you want -- and some browsers (like Chrome) even support modes to emulate different devices and screen sizes.

**Comment by mahagr** [comment]
I'm not going to add this feature to Gantry, though its possible to already set the max-width of the site by just some lines of CSS.
