### ISSUE TITLE
Multiple modules and titles in Development mode

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#1710]
Multiple modules and titles appears in Hydrogen theme frontend (5.3.9) if I change the status to Development mode in the Extras. (Joomla! 3.6.4)

Step by step

Problem No.1

1. Change the status to Development.
2. Load 3 culomn preset in Layout.
3. Add a module position to the Aside.
4. Add a modul to the new position.
5. Check the module title in the frontend.

![image](https://cloud.githubusercontent.com/assets/1657924/20720468/8bbf08cc-b65f-11e6-8637-efc255506afd.png)

Problem No.2

1. Change the status to Development.
2. Load 3 culomn preset in Layout.
3. Add a module position to the Sidebar/Aside.
4. Add a modul to the new position.
5. The moduls are duplicated after the main in phone view.

![1611291](https://cloud.githubusercontent.com/assets/1657924/20720583/0982864e-b660-11e6-8b17-ff8a61104cd3.png)

**Comment by mahagr** [comment]
I cannot reproduce either of the issues. Not even if I use the same position key for both positions. In that case, the module does show up 2 times, but that is expected as it is showing up once in both sides.

**Comment by w00fz** [comment]
@csbalazs Please feel free to reopen and let us know how to reproduce if this is still an issue.

Cheers!

**Comment by mahagr** [comment]
Looks like the issue #1721
