### ISSUE TITLE
"The menu selected is empty!" 

### ISSUE THREAD

**Issue by alec6** [gantry/gantry5#1711]
Hello, 
On joomla 3.6.4 + Gantry  5.3.9 with a multi languages site, in the template - style - hydrogen - menu.  you'll have the message "The menu selected is empty!" 
I think it's a bug.
I found a solution but it's not the good way to fix it.
My language's menu was on "french", i put it to "all" (*) with phpmyadmin.
On the previous version, everything worked fine. 
Hope, you'll fix the bug.
Regards.
Alexis

**Comment by mahagr** [comment]
Previous version of Gantry or Joomla?

**Comment by mahagr** [comment]
I am not able to reproduce the issue (either in admin or in the site).

@alec6 Is this still an issue for you?

**Comment by alec6** [comment]
Now, it's no more an issue. 
My website is no more multi languages. So there's no problem for manage my menu.
I'm on Gantry 5.4.4 + Jooma 3.6.5 now, maybe this issue's fixed. I hadn't tested.

**Comment by Futurindus** [comment]
Hello,
I encountered the same issue, with Joomla 3.6.5 and Gantry 5.4.8.
I was not able to test the workaround proposed by alec6.
Was there a corrective action on this case?
Regards
Philippe

**Comment by mahagr** [comment]
I still cannot reproduce the issue locally, how is the menu(s) set up?

**Comment by Futurindus** [comment]
I have this issue with all the menus. Here is one of them.
[image: Images intégrées 1]

Très cordialement,

*Philippe Allot*

*ORDINAL Software*
*SCADA & MES Software*
Tel : +33 6 78 09 83 37  Fax : +33 1 46 74 01 25
*8 rue de la Renaissance*
*Batiment D - 6ème Etage*
*92160 ANTONY*
*www.ordinal.fr <http://www.ordinal.fr/>*

2017-02-23 9:23 GMT+01:00 Matias Griese <notifications@github.com>:

**Comment by mahagr** [comment]
I'm sorry, but the image isn't shown. You need to upload it from github site, not from email.

**Comment by Futurindus** [comment]
Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/25961241/23250890/3f72a23c-f9ab-11e6-91a2-9238e99fdc14.png)

**Comment by mahagr** [comment]
So the menu consists of menu item aliases, not real menu items.

**Comment by Futurindus** [comment]
It's true for this one, but I have the same issue with MainMenu, with real menu items (see screenshot).
![image](https://cloud.githubusercontent.com/assets/25961241/23251068/192d50c6-f9ac-11e6-84c3-1f0aeac64921.png)

**Comment by mahagr** [comment]
So the menu only shows up if you're using English?

Have you tried to do this in Joomla way, where you create module position `menu` instead of the menu particle and then assign menu particle for each language into that position?

**Comment by Futurindus** [comment]
a) Right.
b) I'm not sure to understand your suggestion of test. Actually I try to enhance an existing Joomla site using  Gantry and Helium template, and evaluating potential issues. So if your question is "Is the menu operational in classical Joomla with a menu position" the answer is yes.

**Comment by mahagr** [comment]
The way Gantry works right now is to do things in Joomla way. That means duplicating particles for each language, just like you would do with module positions. So either you do outline (or template style) for every language or you use module position instead of adding particles directly to the outline.

**Comment by Futurindus** [comment]
Thanks. I will try this.
Best regards
Philippe

2017-02-24 9:41 GMT+01:00 Matias Griese <notifications@github.com>:
