### ISSUE TITLE
Grav - PLUGIN_LOGIN.USERNAME_EMAIL 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1712]
Please see pic from Helium, also seen in other themes.
This can be seen when setting the site to Offline.

![g5_grav_pluginlogin](https://cloud.githubusercontent.com/assets/5719486/20752241/889b9272-b700-11e6-8531-4b340f37e043.jpg)

**Comment by OptikWebCreative** [comment]
@kat05 are you using the maintenance plugin? - this is what I'm seeing? (ver 1.2.1 of plugin)
![screen shot 2016-12-02 at 01 08 20](https://cloud.githubusercontent.com/assets/13849595/20819395/eb63aed6-b82b-11e6-8b78-4aae46d3aeef.png)

**Comment by OptikWebCreative** [comment]
I've just set the site to offline in G5 Plugin, and i'm getting the same as @kat05 :(

**Comment by simmonsr** [comment]
If you modify this as seen here, all will be ok:

https://github.com/gantry/gantry5/pull/1718

**Comment by mahagr** [comment]
Merged.
