### ISSUE TITLE
Grav - 404 Not Found - Oops, Menu item not found.

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1714]
Getting this error in several Grav demo/skeleton installs (Bamboo), can also reproduce in our Sandboxes for G5 themes.

Please see pic.

It happens when going to the Menu Editor and clicking for example on the 'Features' Menu item.

![g5_grav_404menuitem](https://cloud.githubusercontent.com/assets/5719486/20753809/77fc1a38-b708-11e6-977f-ccd4ef2d6415.jpg)

**Comment by OptikWebCreative** [comment]
I'm getting the same ... @mahagr and I are investigating

**Comment by w00fz** [comment]
This looks like an issue for you @mahagr . I dont see any JS issue here regarding the ajax.
