### ISSUE TITLE
The problem with the template Helium

### ISSUE THREAD

**Issue by plpaw** [gantry/gantry5#1716]
Hello,
I have the template Helium and Gantry Framework 5.3.9. I would like to set the field of copyright from the right rather than the left. My side: http://serwer1645460.home.pl/gan.

Regards
Paweł

**Comment by shoulders** [comment]
like this

![right](https://cloud.githubusercontent.com/assets/319997/20793872/1bfdf382-b7c1-11e6-9749-7b38eb048906.png)

then create a custom.scss and add the following css rule

```
#g-footer .g-copyright {
    text-align: right;
}
```

**Comment by mariantanase** [comment]
You should use **float** instead of text-align, like this:
```
#g-footer .g-copyright {
    float: right;
}
```

**Comment by N8Solutions** [comment]
I'd second what @mariantanase suggested and would like to add that you should also remove the padding you added and replace it with this code:
```css
#g-footer .g-copyright {
    float: right;
    padding-right: 1rem;
}
```
This way you won't have the text butted right up next to the edge.

**Comment by plpaw** [comment]
thanks for your help
