### ISSUE TITLE
A problem with the menu item. Helium

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1717]
Helium template. Version: 5.3.9
A problem with the menu item - changes are not saved.
I can not move the new menu item. changes are not saved in the settings menu Gantry
In the settings menu, wordpress - correctly.

What could be the reason?

Thanks

**Comment by DamirPecnik** [comment]
Yeah i know it happened to me also, like if you add sub-items to parent and then that parent add under other parent, then they don't show on the Gantry 5 Menu and on the Site? I think we have a bug on this

**Comment by OptikWebCreative** [comment]
Hi @pobo3 & @DamirPecnik did you get any error messages or modal boxes when saving the menu in the G5 menu editor?

**Comment by DamirPecnik** [comment]
Nope nothing, will see what the Devs will say ...

**Comment by OptikWebCreative** [comment]
wonder if this is related to #1715

**Comment by DamirPecnik** [comment]
I think this #726 Synchronize particle menu items with WP core menu...

**Comment by mahagr** [comment]
I think its likely the synchronization issue where moving menu item from WP doesn't change the location in Gantry.

**Comment by Dizolivemint** [comment]
Having the same issue with WP Helium v5.4.6. Change a parent menu item and the sub menu item disappears for good.

**Comment by bevels** [comment]
+1 Hydrogen for WP

**Comment by milothecat** [comment]
The problem is still there (Hydrogen 5.4.19 on Joomla 3.8.1), can someone tell me if any patch is available for this menu ordering issue ?

**Comment by LMKWeb** [comment]
Also having this problem with Hydrogen on WP, latest builds of each.

**Comment by linbaird** [comment]
Having this problem too, arrange order of menu items in Gantry and order does not change in front end?

**Comment by Winand** [comment]
As soon as I set custom title to menu item Gantry puts it to the right end of menu
