### ISSUE TITLE
Outline duplication copies assignments

### ISSUE THREAD

**Issue by OptikWebCreative** [gantry/gantry5#1719]
When duplicating outlines in GRAV (helium based template) the page assignments are also duplicated leaving a fight between outlines when trying to render a page.

**Comment by dudewithamood** [comment]
Thanks @OptikWebCreative 

This is happening in WordPress also.

I'm not sure of the value of (having a feature request for) a checkbox to transfer/duplicate or assignments - what would the use case for this be? In my own workflow I create the duplicate, make changes and then assign.

**Comment by OptikWebCreative** [comment]
@mahagr this may also be the case for joomla - dont know as haven't tried it

**Comment by mahagr** [comment]
It doesn't affect Joomla as it saves assignments to DB. Should be fixed now.
