### ISSUE TITLE
Duplicate module position (same key) on same layout renders title twice

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1721]
This is perhaps not such a common practice but it seems a legitate requirement to me.

If on your layout you have two "module position" particles with the same key on the layout (perhaps you want to render the content in different places dependent upon the viewport size and have given one a class of "visible-phone" and the other a class of "hidden-phone"). 

In this case the second occurrence of the module renders it's title twice.

Steps to reproduce.
1. create two module position particles on the layout (preferably in same section for purpose of test) and give both a key of "test-position"
2. Create a custom html module with a title of "test title" and content of "test content" 
3. the output rendered on the page will be:

test title
test content
test title
test title
test content

(note how the title is duplicated on the second occurrence).

forum link: http://www.rockettheme.com/forum/gantry5-for-joomla/265128-gantry-5-visible-phone-bug

**Comment by mahagr** [comment]
To me this really looks like "bug" in Joomla itself, but I'll work it around.

**Comment by marktaylor46** [comment]
I guess Gantry 5 might be revealing that issue since AFAIK you couldn't have the same module position name in any other template other than one based upon Gantry 5.

**Comment by mahagr** [comment]
You can add duplicate module positions and modules in Joomla (by changing index.php file of the template), but it doesn't work properly in there either. Joomla will not have duplicate title, but it won't obey module chrome settings either resulting to identical content where it shouldn't be.

You can get duplicate title though by injecting module directly into the page.
