### ISSUE TITLE
trojan gantry5

### ISSUE THREAD

**Issue by Remi007** [gantry/gantry5#1723]
i downloaded the file  https://github.com/gantry/gantry5/releases/download/5.3.9/joomla-pkg_gantry5_v5.3.9.zip and and security app found inside **trojan**: Win32/Peals.A!cl  👎

**Comment by w00fz** [comment]
There is no trojan in the package, it might just be your computer. 😉

<img width="926" alt="kaspersky online scanner 2016-12-06 15-30-47" src="https://cloud.githubusercontent.com/assets/11734/20948448/0fdc7f54-bbc9-11e6-99d8-030b541dcccb.png">

https://scan.kaspersky.com

**Comment by Remi007** [comment]
Windows 10 Defender  -  blocks the infected file joomla-pkg_gantry5_v5.3.9.zip  immediately after downloading. This is only the one infected file

**Comment by newkind** [comment]
Must be Windows Defender false-positive. No Virus scanner detects issues with our file : https://monosnap.com/file/qdslVRPZW2G7L0UNDhvivQJ8NGZKez.png

**Comment by mahagr** [comment]
Quick question: what happens if you download 5.3.8? Would be nice to know if the issue exists only for this single package or not. Also is there any information which file inside the package is detected?

I agree it has to be false positive -- nobody of us are even using windows.

**Comment by mahagr** [comment]
Just found this in MicroSoft site:

> NOTE: On December 6, 2016, an incorrect detection for our cloud-based protection for Trojan:Win32/Peals.A!cl was identified and immediately fixed. To ensure that this issue is remediated, you can do a forced daily update to download your Microsoft antimalware and antispyware software. For details, see Updating your Microsoft antimalware and antispyware software.

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=Trojan%3AWin32%2FPeals.A!plock&ThreatID=-2147276824

**Comment by Remi007** [comment]
The was Windows Defender false-positive.
