### ISSUE TITLE
Grav - mention of 'Modules'

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1725]
I am not sure about these instances of the word 'module'.

Please see pics.

![g5_grav_module2](https://cloud.githubusercontent.com/assets/5719486/20975842/fdeb358c-bca0-11e6-85db-4652fbc0df51.jpg)

![g5_grav_module1](https://cloud.githubusercontent.com/assets/5719486/20975843/fdef0cd4-bca0-11e6-8f99-761b1bd17437.jpg)

**Comment by mahagr** [comment]
First part has been fixed. @w00fz has the second part, maybe he just forgot to commit it?
