### ISSUE TITLE
WordPress "add_theme_support('admin-bar')"

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1730]
Hey, it's just me or `add_theme_support('admin-bar')` is no more working, i can't see the inline css?

**Comment by adi8i** [comment]
Actually `wordpress-g-admin` is not loaded in this case.

**Comment by mahagr** [comment]
@adi8i Why was this closed?

**Comment by adi8i** [comment]
After I updated wordpress to 4.7 that file was not loaded, I recently installed wordpress on docker and on C9 ide, so clean install and everything looks fine. I assume was something wrong with my configuration.

**Comment by mahagr** [comment]
@adi8i So this is still an issue? I'm confused :)

**Comment by adi8i** [comment]
I think, I am confused too, after a period of time `admin bar` doesn't show up on front end, and `wordpress-g-admin.css` is not loaded. Is 3rd time when it happens, each time on different environment (bitnami wamp, docker, c9), clean installation without other plugins.

**Comment by mahagr** [comment]
For me its working just fine, not sure what's going on there...

**Comment by newkind** [comment]
Are you sure that the admin bar is enabled in the user settings in WP? Why the file `wordpress-g-admin.css` should be autoloaded ?

**Comment by adi8i** [comment]
Admin bar is enabled. 
In admin the following is not applied.
```
body.gantry5.auto-fold #wpcontent {
    padding-left: 0;
}
```
![capture](https://cloud.githubusercontent.com/assets/9744973/21590185/23573666-d102-11e6-9005-998a8664f7d7.PNG)

It happened few times, really random, as I don't modify anything, if it's something. Maybe leave the issue open and see if others report it too.

**Comment by mahagr** [comment]
It looks like that the call for `add_theme_support('admin-bar')` is only needed if you want to customize css etc.

Closing the issue as non-issue.

**Comment by adi8i** [comment]
In fact... `auto-fold` is missing from body, in my case.
