### ISSUE TITLE
FontAwesome updates

### ISSUE THREAD

**Issue by OptikWebCreative** [gantry/gantry5#1731]
Hi Team

This issue has 2 parts one relating to FA4.x and the other part relates to FA5 which is to be released in Basic and Pro Versions.

1. FA4.x
I think the current implementation on FA is problematic, it is currently set so that we have to wait for the RT team to update al the templates and G5 to the latest version and when you over-ride with the CDN it often fails due to conflict - there must be an easier way to allow people to use the CDN CSS import of FA method? if its not possible, it would be useful if we can have a toggle to disable the built in FA calls

2. FA5 is coming soon and will have 2 versions, like many, I have helped via the Kickstarter (now closed) and have access to the Pro version, It would be great if G5 on all 3 platforms can somehow support both the free and Pro versions of FA5

**Comment by N8Solutions** [comment]
I would be interested in this functionality as well. I was also a backer of FA5 on Kickstarter. Of course until FA5 is released we just need to wait.

**Comment by w00fz** [comment]
We don't update all templates for fontawesome comes built in with gantry, so we only update that and we are pretty quick in doing so. Once gantry is updated it is available for all themes that support it.

FA5 pro cannot be used for themes without a license so it will be the end developer concern to do that, we will only be allowed to ship gantry with the free version.

**Comment by N8Solutions** [comment]
> FA5 pro cannot be used for themes without a license so it will be the end developer concern to do that

@w00fz 
Djamil, Any chance a tutorial will be provided on how best to accomplish the integration of the pro version once it's released?

**Comment by OptikWebCreative** [comment]
> FA5 pro cannot be used for themes without a license so it will be the end developer concern to do that, we will only be allowed to ship gantry with the free version.

Yes thats understandable that the pro version won't be usable for themes by default, but can't an option to "switch off" the built in FA, and a box to put the relevant CDN url in, wether its Free or Pro for those who would prefer to use the CDN anyway rather than built-in FA fonts

**Comment by mahagr** [comment]
It's a bit more "complex" than that as icons need to be listed in admin as well.

**Comment by mahagr** [comment]
Let's get back to this once FA5 has been released.
