### ISSUE TITLE
Menu Editor Login particle not rendering on frontend

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1733]
In the Menu Editor, I am adding a Login particle, however using Grav it won't render on frontend.
Checked the Menu Editor in Joomla and there is no Login particle available at all. Not sure what is expected.

**Comment by mahagr** [comment]
Seems to be caused by the same bug as #1715; already fixed.

**Comment by kat05** [comment]
I've just tested a fresh Remnant demo build with Gantry dev-40c20fc9d  and the Login is still not visible on frontend.

**Comment by kat05** [comment]
Seeing the same issue with WordPress. Login particle won't show. For example Date particle shows just fine.

**Comment by mahagr** [comment]
They both work for me. I added login particle to the menu in both Grav and WP Remnant.

**Comment by kat05** [comment]
Thanks Matias, I retested with latest CI and also with Grav's login plugin setup properly and it works fine for me now. Closing this. :)
