### ISSUE TITLE
Grav - Grav fontawesome icon is not loading

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1734]
Please see pics. All the other icons that were added with FA 4.7 load fine.

![g5_grav_faicon](https://cloud.githubusercontent.com/assets/5719486/21046592/b24ab68c-be05-11e6-8e0c-ba3812e00f1c.jpg)

![g5_grav_platformicon](https://cloud.githubusercontent.com/assets/5719486/21046593/b24bcd88-be05-11e6-808e-d6a59181afd6.jpg)

**Comment by mahagr** [comment]
We are loading FA 2 times in Grav admin (once by Gantry, another time by Grav).

**Comment by mahagr** [comment]
@w00fz Looks like Grav is missing the icon.
