### ISSUE TITLE
gantry content shrink

### ISSUE THREAD

**Issue by dmachado48** [gantry/gantry5#1737]
Hello,

I would  like to get some help. I believe this might be easy but i dont know how to solve this problem.

After installation some componentes / modules they dont brake in mobile they just shrink the content.

Im using hydrogen.

![screen shot 2016-12-10 at 06 55 07](https://cloud.githubusercontent.com/assets/5700787/21071823/a2809654-bea5-11e6-9d68-b8bc896607eb.png)
![screen shot 2016-12-10 at 06 53 58](https://cloud.githubusercontent.com/assets/5700787/21071824/a282857c-bea5-11e6-9417-4239614bf6eb.png)

Many thanks

**Comment by w00fz** [comment]
What components are you using? Hydrogen is responsive but if you use components / modules that are not responsive there's nothing Gantry can do.

**Comment by dmachado48** [comment]
Hello,

Thanks for you quick reply :D 

This is the module. As you can see its responsive. http://demo.joomlaux.com/#jux-timeline

Very strange I had to use for the form the grid class to make it resposive but for this module i cant solve that way...

Thanks a lot

**Comment by mahagr** [comment]
@dmachado48 Is this still an issue?

HTML doesn't wrap long words by default, so it might be a good idea to use smaller font and margin or just redesign the page so that there's more space to fit the content.

**Comment by w00fz** [comment]
Closing, let us know if you solved or if you have anything else to add feel free to reopen.
