### ISSUE TITLE
grav: dependency on snipcart plugin

### ISSUE THREAD

**Issue by bauer01** [gantry/gantry5#1740]
I think that dependency on 3rd part plugins should be removed.

If I use Gantry Helium theme without Grav Snipcart plugin installed, it screams an error with missing snipcart_base.html.twig

![snipcart](https://cloud.githubusercontent.com/assets/551000/21156092/d8d16c2a-c174-11e6-89c7-bd3f5942a4c9.jpg)

I'm using Gantry develop branch till commit 90fde0e7d3519f121a0c111f220fb546498c7fcf

Maybe problem is here https://github.com/gantry/gantry5/blob/develop/engines/grav/nucleus/templates/snipcart.html.twig

**Comment by bauer01** [comment]
Ohh, my mistake, I forgot to delete old pages using some stuff from grav shop skeleton :-)

**Comment by w00fz** [comment]
Got us scared there for a moment :)
Glad you solved.
