### ISSUE TITLE
ampersand in Menu Editor / Particle title

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#1742]
In Joomla...

a Menu Item title such as:

`Hours & Directions` as configured in the Menu Editor (or passed through from Joomla)

renders as:

`Hours &amp; Directions`

on the frontend

I have tried the inverse of actually specifying `&amp;` as well as `&#38;` but those render through as plain text, exactly as entered

**Comment by hacki65** [comment]
Can not confirm. Which template & fonts is used?

**Comment by blizam** [comment]
Protean... font-family: "Raleway" .... and I should note I only tested it in the OffCanvas position/mobile menu ... this is related to a rockettheme.com forum post

-Matt

**Comment by mahagr** [comment]
I am not able to reproduce this either, not in Helium or Protean. It also works in OffCanvas.

**Comment by blizam** [comment]
I'll move this to an RT internal ticket for Protean only

**Comment by mahagr** [comment]
Are still you able to reproduce this, @blizam, as I could not with the latest version.

**Comment by mahagr** [comment]
@blizam sent me a message that he's not able to reproduce this anymore. Closing.

**Comment by blizam** [comment]
I am no longer able to reproduce this
