### ISSUE TITLE
Responsive Classes seems to be broken

### ISSUE THREAD

**Issue by ka3media** [gantry/gantry5#1745]
after the update to gantry 5.4.1 on Joomla the responsive classes seems to be broken.

Moduls with suffix "visible-phone" are now visible on desktop. That don't correspond with the overview here -> http://docs.gantry.org/gantry5/tutorials/utility-classes

**Comment by hacki65** [comment]
I can not confirm that. I have tested it with possible combinations in Helium and all works as expected.
Have you clear your Jooma! Cache and try to recompile the css in Gantry?

**Comment by simmonsr** [comment]
Yes, try recompiling CSS in Base Outline of Gantry admin > Styles

**Comment by mahagr** [comment]
Caused by #1752
