### ISSUE TITLE
Framework Grav Install Runtime Exception

### ISSUE THREAD

**Issue by elproducto** [gantry/gantry5#1747]
I am attempting to install Gantry 5 framework via Grav console and via GPM command but get RuntimeException error.   Error provide below.

`[RuntimeException]                                                           
  rename(/srv/users/myuser/apps/myapp/public/tmp/Grav-5851603ccd219/gan  
  try5/./,/srv/users/myuser/apps/myapp/public/user/plugins/gantry5): De  
  vice or resource busy`

**Comment by w00fz** [comment]
Yes this is a known issue we discovered yesterday. It's a grav issue and we already have a patch for it. Next release will fix it. For the time being you should install it manually, download the plugin and unzip in user/plugins as gantry5.

**Comment by elproducto** [comment]
Thanks
