### ISSUE TITLE
Grav in Nginx: 403 Forbidden, Oops invalid security token

### ISSUE THREAD

**Issue by Sqoon** [gantry/gantry5#1748]
Hello, I recently manually installed Gantry onto Grav, Gantry themes work fine, although changing anything within the Appearance admin tabs yields a "403 Forbidden, Oops invalid security token".

I am not sure if I am overlooking something simple. 
Any help would be much appreciated, thank you.

**Comment by w00fz** [comment]
Are you running the latest grav and grav admin?

**Comment by Sqoon** [comment]
Yes, freshly installed.

**Comment by w00fz** [comment]
Hmmm, I cannot reproduce this issue. Have you tried  clearing all cache and logging out and in again?

**Comment by kat05** [comment]
I am also not able to replicate the issue.

**Comment by hexplor** [comment]
been testing grav a lot recently, never experienced this issue :(

**Comment by Sqoon** [comment]
Still occurs.

It might have something to do with firewall or htaccess but I'm still super lost.
I'm using Ubuntu 16.

Maybe I need to set permissions somewhere, but again I'm still lost.

**Comment by w00fz** [comment]
Can you let us know the steps you perform to get to the issue?

I'm assuming you go in admin, have Helium/Hydrogen enabled as themes, go in Appearance, make some changes like background colors and such, click Save and get the error. Is that correct?

**Comment by Sqoon** [comment]
That's correct. Anything I want to save or change in the appearance tab, just gives me a 403 error. So I basically can't change anything with the theme. It also gives me this error with other Gantry related themes.

**Comment by w00fz** [comment]
Which other Gantry related themes?
Perhaps you can send me your site and admin account in private on https://gitter.im/w00fz

**Comment by mahagr** [comment]
I've seen this issue happening many, many times before. Try disabling mod_security if it helps. Later you can re-enable it, but there are some rules (which I need to dig up) which need to be disabled.

**Comment by mahagr** [comment]
Actually.. What does the error look like? Might be something else.

**Comment by Sqoon** [comment]
Well, W00fz helped me a bit, and I figured out that I might have Nginx configured incorrectly.

I'm going to take a day to reconfigure it, and I will report back tomorrow to see if everything was fixed correctly. Thank you all for the help.

I'll be back tomorrow and let everyone know if it gets fixed.

**Comment by mahagr** [comment]
@Sqoon Did you manage to fix your issue?

**Comment by mahagr** [comment]
We are not yet sure why this happens for some users. If possible, please join us in https://gitter.im/gantry/gantry5 so that I can look into your site.

**Comment by flaviocopes** [comment]
Related: https://github.com/getgrav/grav-plugin-admin/issues/893#issuecomment-270792990

**Comment by mahagr** [comment]
@Sqoon Above link may help you to fix the issue ^

**Comment by mahagr** [comment]
Please update nginx.conf: 

```
    location / {
        try_files $uri $uri/ /index.php?_url=$uri&$query_string;
    }
```

**Comment by beedzei** [comment]
I have updated nginx.conf with suggested location fix but still same 403 error - on the latest Grav  + admin, Gantry 5 and Helium and all on 16.04

**Comment by beedzei** [comment]
PS. Solved - needed to be edited in sites-available/grav, not in main nginx.conf.

**Comment by samwalls** [comment]
And, in case you're using Caddy, the equivalent rewrite rule:

```
rewrite
    to  {path} {path}/ /index.php?_url={uri}&{query}
}
```
