### ISSUE TITLE
Grav Modular Page with Gantry 5

### ISSUE THREAD

**Issue by dnestorov** [gantry/gantry5#1749]
Hi all, 

I am new to Grav/Gantry 5 and I am trying to build a website using the Helium theme but I cannot create a modular page that is rendered in a Gantry layout. Is there any chance that Gantry 5 supports Grav modular pages?

Thank you.

Regards,
Delyan

**Comment by dnestorov** [comment]
Ok, so it works but I had to copy the templates from engines/nucleus in the plugin folder to the themes directory.

**Comment by mahagr** [comment]
At least in the past modular page types have appeared in admin so you've been able to use them. Isn't that true anymore?

**Comment by dnestorov** [comment]
The modular page type wasn't showing in the admin panel. When I tried to create a page it was created with "default" template even if I chose modular. I tried renaming default.md to modular.md and it worked. Then I had to copy the templates so the modular type shows in the admin panel.

**Comment by mahagr** [comment]
Confirmed a bug.
