### ISSUE TITLE
submenu text, is not rtl in rtl language again

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1753]
in this issue : 
https://github.com/gantry/gantry5/issues/1511

i explain a problem about incorrect sub-menu text align.i am using RTL language in my joomla website but Hydrogen show it as LTR. this problem already solved but now, when i upgrade Gantry&Hydrogen pkg , the problem occur again.
look at this film for clear about the problem:
http://www.screencast.com/t/zXgTQELNWM8f

**Comment by mahagr** [comment]
Thanks for creating the new issue for this.
