### ISSUE TITLE
Calling "getdisplayItems" deprecated

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1755]
PHP Unknown: Calling "getdisplayItems" on template "@particles/menu.html.twig" from template "@particles/menu.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0. in /home/xxxxx/public_html/xxxxxxxxxxxx/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php on line 690

This ticket it just a note that this need to be corrected before updating to TWIG 2.0

As discussed with @mahagr

**Comment by mahagr** [comment]
Caused by new version of Twig.

**Comment by mahagr** [comment]
There's no such function call anywhere in Gantry, so the call must come from cached twig file.
