### ISSUE TITLE
Gantry 5/sellacious shop issue joomla

### ISSUE THREAD

**Issue by ahutchings81** [gantry/gantry5#1757]
Dont know if im posting in proper place for this but ive installed gantry 5 on my site no issues at all everything looks and feels exactly how i want it. Recently come across a bug with sellacious shop. I can implement the shop no problem on site only problem i have is with the cart i get to stage were need to select address so i do then click next but nothing happens. I get no errors or anything the button just doesnt work at all. I changed template to protostar to see if it would work and worked fine just issue with gantry. Does anyone knwo what could cause this at all ? Any help would be amazing thank you in advance.

**Comment by mahagr** [comment]
Talking in gitter..

**Comment by mahagr** [comment]
Solved with a workaround. I think the main cause of the issue was jquery been loaded twice in the page.
