### ISSUE TITLE
Grav - not able to install a G5 theme from Grav Admin

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1761]
Hi guys,

I'm not sure if you are aware of the issue so I decided to just open a new issue for it.
I'm not able to install neither Helium nor Hydrogen from the Grav Admin.
[This video](https://youtu.be/KMArslhVz6E) shows the issue.

Manual installation by coping the files works fine.

**Comment by kat05** [comment]
I just successfully installed both Helium and Hydrogen, but they show version 5.4.1 instead of 5.4.2 and for some reason I am not able to activate them.

**Comment by JoomFX** [comment]
I just updated to Grav 1.1.11 (from 1.1.9) and to Admin Panel 1.2.7 (from 1.2.5) and now I can install the G5 themes successfully.

I'm not closing the issue as you might want to look at Kat's issue.

**Comment by w00fz** [comment]
This has been resolved via Grav and Gantry both.
