### ISSUE TITLE
Wordpress assignments priorities

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1762]
I think we've discussed this before.

To me assignments priorities looks wrong. I have `home` outline assigned to `front page`, then `inner` outline assigned to `single page`. `Inner` outline is used for front page too. Front page should have priority over single page, looks like gantry treats it like any other page.

**Comment by mahagr** [comment]
The assignments are set to work in the same way as with Gantry 4, more specific rules overriding the more general ones. All the rules inside the same "block" are considered to be equal.

See #1112, I think its the same issue..?

**Comment by adi8i** [comment]
Yes, I think is the same I forgot about that one, here's Front Page vs Single Page, where Front Page should have priority.

**Comment by mahagr** [comment]
Alright, then the issue is slightly different. Right now there's no way to have different priority within the same group of assignment options.

**Comment by mahagr** [comment]
@adi8i Try with the latest CI.

**Comment by adi8i** [comment]
This is still an issue in my opinion, as a reminder, I am talking about `is_front_page` and `is_page`.

In my scenario I have an outline assigned to `Front Page`, because I use a Page Builder plugin I need to create another outline and assign it to all other pages. 

And I have 2 options. Assign it to `page context -> single page` or `pages -> mark each page`. Ofc I'd go with first one.

What do you think?

![capture](https://user-images.githubusercontent.com/9744973/27486710-1ff7b21a-583a-11e7-903e-11873c6b256b.PNG)

**Comment by mahagr** [comment]
All of the options have the same priority, which may cause some prioritizing issues here. Maybe create a new issue?
