### ISSUE TITLE
403 Error in GRAV Appearance

### ISSUE THREAD

**Issue by Wferr** [gantry/gantry5#1763]
Running latest Grav v1.1.10 and Admin v1.2.6 aswell as Gantry 5 Framework 5.4.2 and Helium 5.4.2

I cannot change any of the parameters within the appearance tab. Errors out and gives a 403 to refresh for invalid security token. Restarted server, emptier cache and hard reloaded, logged in and out. Server running on debian 8 with nginx and php7.

Also posted in grav-admins issues https://github.com/getgrav/grav-plugin-admin/issues/899

Video: https://f.wferr.com/ea5_1482368751_%25pn.mp4

**Comment by mahagr** [comment]
Looks like to be the same issue as in #1748. We are not yet sure why this happens for some users. If possible, please join us in https://gitter.im/gantry/gantry5 so that I can look into your site.

**Comment by mahagr** [comment]
I'm closing this issue as duplicate, let's continue in issue mentioned in my previous comment.
