### ISSUE TITLE
Joomla components > Gantry 5 themes no longer shows all installed themes

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1764]
In joomla, Gantry 5.3.9, if you went to components > Gantry 5 themes it would show a page showing all installed themes and you could then choose the theme to work on. As of Gantry 5.4.2 this screen no longer appears at all and instead you are taken directly to the "default" theme that is installed. 
i.e. this page no longer shows.
![2016-12-22_13-57-47](https://cloud.githubusercontent.com/assets/11683218/21428334/6e0a93a6-c851-11e6-8543-f794c6045f2e.png)

**Comment by marktaylor46** [comment]
This is new functionality and now you have to click on Gantry logo top right to get to that screen.

**Comment by mariantanase** [comment]
I notice this issue too. 
@marktaylor46  I don't understand what you mean with "new functionality" ?

**Comment by marktaylor46** [comment]
Click on the "GANTRY" logo in the top right of G5 admin and you will get back to the "themes" page.

**Comment by mariantanase** [comment]
I see now, and I agree with the idea to add a tooltip on mouseover.

**Comment by mahagr** [comment]
The default landing page was changed to match the other 2 platforms. Though it could be a good idea to land into the original page if you have more than one gantry themes installed.

I also agree with the tooltip.

**Comment by mahagr** [comment]
Regarding to this issue, maybe I should add submenu to admin..?

Gantry 5 Themes
  * Available Themes
  * Default Theme

**Comment by marktaylor46** [comment]
Yeh that would be good too as long as "g5 themes" does what it does now (the new way) then it's kind like other joomla menu items (e.g. template manager).

**Comment by N8Solutions** [comment]
@marktaylor46 Thank  you for bringing this up. I wouldn't have found where to click had you not. A tooltip is definitely needed of the Gantry Logo otherwise who would know what to do?

@mahagr I also really like your idea of the dropdown menu.

Thank you for continuing to improve Gantry!
