### ISSUE TITLE
Functionality Query

### ISSUE THREAD

**Issue by OptikWebCreative** [gantry/gantry5#1766]
Hi Guys,

System Details : GRAV, Helium Template
Particle : Owl Carousel

Problem : Need multiple outlines, to have different particle dependant on page.

Currently I have 15 outlines on my new GRAV site, because I want to have different text on the Owl Carousel

Is there a way in GRAV to associate either a specific set of text to be in the fields of the particle, dependant on the page?

**Comment by mahagr** [comment]
Use positions just like you would in Joomla. :)

**Comment by mahagr** [comment]
I'm assuming that the question has been answered. Closing the issue.
