### ISSUE TITLE
Blank Page when editing an article with flexicontent since G5.4.0

### ISSUE THREAD

**Issue by charlynancy54** [gantry/gantry5#1767]
Hi,
I find an issue with Gantry 5.4.0 with Flexicontent.
When you edit a flexicontent article in frontpage, you obtain a blank page.
It's verry difficult for me to find the reason of this, because "Blank Page of Death in Joomla" is verry difficult to analyse.
Could you simply install Flexicontent on a test site and try to edit an article in frontpage to see this issue.

I fix this with the reinstall of Gantry 5.3.9

**Comment by charlynancy54** [comment]
All the releases of gantry after 5.4.0 have the same issue

**Comment by mahagr** [comment]
I just installed latest Flexicontent and created menu item pointing to its item.

I'm getting a lot of errors into my log when I try to use Flexicontent:

    PHP Warning:  Invalid argument supplied for foreach() in [various locations]

Author of the software should really check his code when installing to a clean Joomla site with sample content in it.

I'm getting the white page, too, when editing an item. I'm not sure what could cause it yet as there's no error in the logs.

**Comment by ggppdk** [comment]
> Author of the software should really check his code when installing to a clean Joomla site with sample content in it.
> I just installed latest Flexicontent and created menu item pointing to its item.

@mahagr 
thanks for looking into this,
but there is propably no bug related to the warnings that you report,

there should be no errors, and neither any warnings in PHP7
you need to visit flexicontent backend 
- in dashboard click to complete post-installation tasks
- in items manager, clck "bind" to bind FLEXIcontent items to Joomla articles

I will add a message and link to FLEXIcontent backend page so that a hasty user can not miss them, 

These are done seperately so that you can install FLEXIcontent even on a web-site with 200,000 articles

About the error when editing an item, 
- it occurs after FLEXIcontent component finishes execution
so it must be in some system plugin code

I will find where it occurs,
regardless if it is inside FLEXIcontent code

**Comment by mahagr** [comment]
@ggppdk Thanks for responding to me. I visited backend and did the post-installation tasks and binding Joomla articles before I started my testing. It was pretty clear once you got into the admin, but yes, installation could have link too.

The warnings I'm getting in admin are coming from `global $globalcats;` variable not being an array.

Here's one example:

    Warning: Invalid argument supplied for foreach() in /home/matias/www/joomla/components/com_flexicontent/helpers/permission.php on line 260

Thanks for pointing when the issue happens -- I will run some extra tests based on that information.

**Comment by mahagr** [comment]
I was able to find the function what causes the white page.

**Comment by ggppdk** [comment]
Yes, it is **cache issue**

if you visit frontend and then do the post-installation tasks of FLEXIcontent
-- then some cached data are not cleared,
**Thanks for bring this up, i will check and fix cache clearing**

I just want to note, that the above is not related to the issue of blank page

The blank page happens in any component 
-- that tries to render ACL rules in frontend forms then with Gantry G5.4.0+ see this new issue:

https://github.com/gantry/gantry5/issues/1775


@charlynancy54 
edit file:
components/com_flexicontent/views/item/tmpl/form.php

And remove
<?php echo $this->form->getInput('rules'); ?>
you will rarely want to change article ACL in frontend, and removing it , just keeps the current ACL
- the bad is that we render ACL HTML but not show it even if you disable permissions editting in frontend, we will fix this

**Comment by mahagr** [comment]
I found the offending call that causes the white page. Its `preg_replace_callback` in our stream handling function. I will fix it shortly.

@ggppdk Thanks for your help on this one, your comment really saved me hours of work.

**Comment by mahagr** [comment]
Should be fixed in the latest CI build (down in our downloads page).
