### ISSUE TITLE
Assigning/Deassigning 200+ menu items in Gantry 5 assignments takes a long time

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1768]
A member had rasied a topic in the forum here:
http://www.rockettheme.com/forum/joomla-template-interstellar/265856-mass-changing-menu-assignments-browser-hangs

Basically they wish to assign/deassign 200+ menu items in Gantry 5 admin on the assignments tab and the main.js is taking a very long execution time. In fact, in Firefox, you get a popup every minute or so saying that the script may have stopped responding and you have to press the "continue" button.

After many times of pressing "continue", or checking "do not tell me again" eventually the script will complete successfully and the assignments/deassignments will work correctly.

**Comment by w00fz** [comment]
There's already an issue open about this, it was fixed in portion and we said the only way to fix this other one was through pagination and Ajax. It's a big rewrite for the future.

**Comment by mahagr** [comment]
Closing as duplicate.
