### ISSUE TITLE
Edit, Duplicate and Remove are not enabled in Configurations screen

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#177]
As you could see on this screenshot, when I click on one of these buttons (Edit, Duplicate, Remove), nothing happens.
Are not enabled on this stage ?
![gantry5b5-duplicate](https://cloud.githubusercontent.com/assets/3976174/7449977/c91d1fdc-f23f-11e4-8659-0f3734bc4825.png)
I'm on a fresh Joomla 3.4.1 installation with Gantry5 beta5.
If I click on the plus icon on the right side of the screen, a message appear:
"**Configurations are still WIP!**"

**Comment by mariantanase** [comment]
I see now on rockettheme blog that it is a work in progress.
Sorry for open this issue.

**Comment by mahagr** [comment]
Well, now we do have issue number to refer into!

**Comment by mahagr** [comment]
Part of #118
