### ISSUE TITLE
Grav Positions Particle Icons

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1771]
Can we show particle Icons here maybe?

![2016-12-27 23 01 12](https://cloud.githubusercontent.com/assets/10489911/21509370/9767704e-cc88-11e6-8286-679efbd77af4.jpg)

**Comment by newkind** [comment]
I don't think so, these icons aren't there by accident. They were supposed to display current assignments. Some legend for the icons would be good though.

**Comment by w00fz** [comment]
There's a tooltip, is there not?

**Comment by DamirPecnik** [comment]
Yeah it says "Type:" and nothing more ...
