### ISSUE TITLE
Rendering ACL rules in frontend Joomla forms, causes blank page in G5.4.0+

### ISSUE THREAD

**Issue by ggppdk** [gantry/gantry5#1775]
It seems to happen with any component that renders ACL rules , to replicate it with **com_content**:

1. **Edit file**:  _components/com_content/models/forms/article.xml_

and add inside the **first fieldset**  (e.g. add after "featured" field)
```xml
		<field name="rules" type="rules" label="JFIELD_RULES_LABEL"
			translate_label="false" filter="rules"
			component="com_content" section="article" validate="rules"
		/>
```

2. **Edit file** :  _components/com_content/views/form/tmpl/edit.php_

and at bottom of it add
```php
<?php echo $this->form->getInput('rules'); ?>
````

3. **Edit a Joomla article in frontend and you get blank page**

**Comment by ggppdk** [comment]
I think the rendering ACL rules just triggers some bug,
-- that it may be possible to trigger **in a different way**,

without taking more time, i could not say where the issue is

**Comment by ggppdk** [comment]
I tested it seems to be fixed by this commit: https://github.com/gantry/gantry5/commit/ecbff695f7c265bd1b193b156fa6e91246c06a33

**Comment by mahagr** [comment]
Better changelog entry :)
