### ISSUE TITLE
"popupmodule" particles does not expand on "particle defaults" tab

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1776]
The "popupmodule" particles does not expand on "particle defaults" tab of the base outlines in Joomla so you can't set any default settings at all. I checked this in Versla, and Remnant.

![2017-01-03_09-37-54](https://cloud.githubusercontent.com/assets/11683218/21604122/4f8a122a-d199-11e6-86ee-d2d87c145030.png)

**Comment by mahagr** [comment]
Looks like its by purpose. There's no defaults in the particle.

Not a Gantry bug, its a decision made in the particle.
