### ISSUE TITLE
"Custom Page" menu item type loads all elements

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#178]
The "Custom Page" menu item still loads all elements ( `g-main` , `g-content` and `platform-content` ). These elements ( `g-main` and `g-content` in particular) have some `padding` and `margin` and this leaves an empty block in the page which is really not nice when you want to implement a particular design. In Gantry4 you were able to overcome this "empty block" by disabling the "Display Component"

http://i.imgur.com/n63PpvI.png

**Comment by mahagr** [comment]
Right now Joomla content also includes system messages and it seems to add div even if its empty.

**Comment by mahagr** [comment]
Also need to replace these:

    <jdoc:include type="message" />
    <jdoc:include type="component" />

with direct calls to JDocument as those includes will not get parsed in time to do the choice of hiding the section.

**Comment by JoomFX** [comment]
Perfect!
I'm glad it is assigned to Beta6 ;)
