### ISSUE TITLE
In G5, dollar sign followed by a number needs to be escaped

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1782]
Hi guys,

In G5, in order to show the dollar sign followed by a number ( `$1` ) we need to escape it first, like this - `\$1`
While it does not need to be escaped in Protostar.
Here, have a look at [this video](https://youtu.be/rfmtY98Rqp4).

I was wondering what's causing this behavior and if it can be changed?
It might sound as a minor/cosmetic thing, but for existing websites that have hundreds of articles with the above code, it actually turns into an issue.

EDIT: Sorry, forgot to say that it is about the `<pre>` tag. Here's an example code:

```
<pre>
$
$TEST
$1
\$1
</pre>
```

**Comment by mahagr** [comment]
I was able to find the issue.

**Comment by JoomFX** [comment]
Thanks Matias 😉
