### ISSUE TITLE
Helium - Font color setting for Navigation section in Styles tab has no effect on front end

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#1783]
I'm opening this ticket for @kamaleshdubey & @austre who have both experienced a problem with the Helium template. Changing the **Font Color** in the styles tab in the administrative section has no effect on the font color on the front end of the website for the **Navigation** section. I helped @austre with his issue and @OptikWebCreative has helped @kamaleshdubey. I have not tried to check whether or not the issue is isolated to the Navigation section or if other sections are also experiencing issues.

@mahagr & @w00fz 
Here are the links to them discussing the issue on Gitter
👉 : [December 28, 2016 1:02 PM](https://gitter.im/gantry/gantry5?at=58639bbd7a3f79ef5dacf5f7)

👉 : [January 7, 2017 1:40 AM](https://gitter.im/gantry/gantry5?at=58702aecda229f8d5bf2beea)

**Comment by newkind** [comment]
Works fine for me : https://monosnap.com/file/TmoVFkTGqVsk0AZTWv6NxyB4jWEiyQ.png https://monosnap.com/file/rVrxzB7rF1HydPk8p9OOwLcgSJRb1t.png

Maybe you're talking about Home outline which is forcing white font color on menu if `g-helium-style` body class is present?

**Comment by kamaleshdubey** [comment]
I am using a replication of the Helium - Particles Outline: http://nishtha.biz/. I have used the following styles in both the Navigation & Footer areas:

- Background: #ffffff

- Text: #0033cc

While this works for the Footer, it does not work for the Navigation. I have tried to apply the same style to the Header section, but this does not help either.

By the way, I have now switched to Grav from Joomla, but the problem still persists.

**Comment by newkind** [comment]
I can see that your theme is Antimatter not Helium. Can you switch to Helium?

**Comment by kamaleshdubey** [comment]
Yes, I have had to switch to Antimatter in the interim as we are now working on a slightly different idea. But the issue does persist. Although you have referenced the Home Outline earlier, this does not exist in Grav at all.

**Comment by N8Solutions** [comment]
@newkind I'd also like to add that the issue I was helping @austre with was on Joomla.

**Comment by newkind** [comment]
@N8Solutions this shouldn't matter, this code should be common for all platforms.

**Comment by kamaleshdubey** [comment]
I believe that the issues are similar only that I have suffered this on both Joomla and Grav!

**Comment by N8Solutions** [comment]
@newkind You said this above.
>Maybe you're talking about Home outline which is forcing white font color on menu if `g-helium-style` body class is present?

I have never developed a site with Helium so I was unaware of this. I just installed it as a test and chose to install the `Sample Data`. The class you are referring to, `g-helium-style` , is added to the `Base Outline` and is inherited by the others. Removing it does in fact allow the font in the navigation to be changed via the styles tab in the admin section.

I do feel it's necessary though to point out that it is a bad idea. How is anyone supposed to know that specific class forces a white font color on the menu?
Why not just set a white font color on the menu in the styles tab?

**Comment by kamaleshdubey** [comment]
@newkind expanding on the point made by @N8Solutions , if the `g-helium-style` body class is removed, it pushed the Owl Carousel below the Navigation section instead of overlaying it, thereby removing one of the better features of the template. Are we close to a solution?

**Comment by newkind** [comment]
Ok `g-helium-style` class was added there so that you'd be able to easily remove the custom styling applied to the Home outline like negative margins, spacing solutions, big paddings etc. Basically the things that make theme more generic and universal and specifc to Home only.

Moving some of these things might be doable with adding extra configuration fields but some that utilise breakpoints can be harder to do ie. different logo color on home only for devices that aren't mobile.

Also `g-helium-style` keeps the CSS for all Custom HTML particles that are present in Home, so it also was made that way for ease of removal of them from your site (if you don't need them).

There are couple things to consider here.

**Comment by newkind** [comment]
Ok, I removed the font color styling from `g-helium-style` body class, however I kept the `#g-navigation` section background to be transparent in there.

Can you guys please test the CI build (please remember to recompile CSS)?

@kamaleshdubey Regarding OwlCarousel to be pushed below I want to keep it that way as I made it like that on purpose so you could remove the `g-helium-style` body class on subpages and just have a regular looking slider for your needs.

Any other suggestions or anything that we should discuss? :)

**Comment by N8Solutions** [comment]
@newkind Thank you for working on this! I'll test it out first chance I get.

**Comment by hexplor** [comment]
I assume this can be closed ? Please confirm.

**Comment by austre** [comment]
For me it's closed. Now i can change Navigation Section color with no
problems.

Em 15 de mar de 2017 09:53, "Karol Orzeł" <notifications@github.com>
escreveu:

**Comment by kamaleshdubey** [comment]
Yes, this can be closed. It is working for me as well.
