### ISSUE TITLE
Hydrogen/Helium: Deleted or renamed Home outline reverting back to its original state

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1785]
Outline installer keep adding outlines back.

1. Install Helium
2. Remove Home - Particles Outline
3. Refresh Front Page
4. Check the outlines :)

**Comment by ardkevin84** [comment]
I've seen a possibly related issue. Slightly different, though. I still have the home-particles outline in place, but my home page uses a custom outline. I use a git-based worklow and anytime i merge dev branch (local docker) with design branch (vps dev subdomain), the home page outline reverts to home-particles. 

The CONFIG doesn't revert, but the rendering does. 

Observations:
When trying to resolve it, in one step (on the vos end) i turned off yaml compilation and toggled the wp homepage option to a different page and back. Now my outline is correct. 
Sorry, wish i would have isolated these two steps

**Comment by mahagr** [comment]
I have fixed the issue for new installations of both Hydrogen and Helium.

If you have an existing installation, please remove the following folder (depending on the theme):

```
wp-content/themes/g5_helium/config/home
wp-content/themes/g5_hydrogen/config/home_-_particles
```
