### ISSUE TITLE
Breadcrumbs with Grav1.1.12 & Gantry5.4.2(Helium)

### ISSUE THREAD

**Issue by JakeBluez** [gantry/gantry5#1786]
Hi,
i installed the breadcrumbs-pluginc via admin backend, but now i don't find how to use it.

I assumed it would appear under partials in the layout tab, but it dosen't.

Could somebody please point me in the right direction or tell me if this is yet possible?

Thanks

**Comment by mahagr** [comment]
I think I need to take a look into it for myself.

**Comment by OptikWebCreative** [comment]
@mahagr and I talked about this the other day, before this ticket - i'm trying to work out how to do this as a g5 particle, which once I have completed, I will be making available - although i may be beaten to it if @mahagr is on the case already.

@mahagr it may be useful to find a way to make all GRAV plugins available as atoms in G5?

**Comment by mahagr** [comment]
I added breadcrumbs particle.

I also added support for checking if the plugin needed by the particle is installed so I can hide particles that depend on uninstalled plugins in admin.

@OptikWebCreative There is no universal way to create particles for the plugins -- they are all different and usually need to be supported by the theme.

**Comment by JakeBluez** [comment]
Wow, just updating and it works :-)

Thank you very much, this is great!
