### ISSUE TITLE
Missing Link in Online-Doc

### ISSUE THREAD

**Issue by max123kl** [gantry/gantry5#1788]
In page
http://docs.gantry.org/gantry5/basics/introduction
at
<p>There are several ways to access the Gantry 5 administrator, depending on which CMS you are using. We have a
<a href="/gantry5/basics/configure/gantry-admin">full guide here</a>
to help you find the way that's best for you.</p>

the containing link does not work

**Comment by Quy** [comment]
This [pull request](https://github.com/gantry/docs/pull/127) to fix the link is pending to be merged.

**Comment by mahagr** [comment]
Good catch. I will close this issue now as there's pull request to fix it.
