### ISSUE TITLE
GRAV: Particles not being saved on positions page

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1790]
Please see video below.

Steps to reproduce:

1. in an empty positions add a "block content" particle and APPLY
2. add another to the same position and APPLY
3. note there are now two particle in that position - now SAVE POSITIONS
4. leave positions page and return - Note how only one particle has been saved.

https://www.screencast.com/t/uRUwWMMv

**Comment by w00fz** [comment]
I can reproduce this issue.
