### ISSUE TITLE
Grav and Gantry 5.4.3 Update

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1792]
Server Error
Sorry, something went terribly wrong!

E_COMPILE_ERROR - Cannot use Grav\Common\Page\Page as Page because the name is already in use

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

**Comment by w00fz** [comment]
This seems to be a PHP < 7 issue

**Comment by DamirPecnik** [comment]
Latest CI fixes the Issue...

**Comment by w00fz** [comment]
Fixed in 71fe40c
