### ISSUE TITLE
RokSprocket and RokGallery broken in Gantry 5.4.3

### ISSUE THREAD

**Issue by thiagocapuano** [gantry/gantry5#1794]
Error thrown with message "Call to a member function addScript() on null"

Stacktrace:
#19 Error in /home/psdb-passofundo/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Content/Document/HtmlDocument.php:129
#18 Gantry\Component\Content\Document\HtmlDocument:addScript in /home/psdb-passofundo/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Content/Document/HtmlDocument.php:168
#17 Gantry\Component\Content\Document\HtmlDocument:addHeaderTag in /home/psdb-passofundo/www/wp-content/plugins/wp_rokcommon/RokCommon/Header/Wordpress.php:55
#16 RokCommon_Header_Wordpress:addScript in /home/psdb-passofundo/www/wp-content/plugins/wp_rokcommon/RokCommon/Header.php:33
#15 RokCommon_Header:addScript in /home/psdb-passofundo/www/wp-content/plugins/wp_roksprocket/lib/RokSprocket.php:171
#14 RokSprocket:renderGlobalHeaders in /home/psdb-passofundo/www/wp-content/plugins/wp_roksprocket/wordpress.php:41
#13 RokSprocket_Wordpress:renderGlobalHeaders in /home/psdb-passofundo/www/wp-content/plugins/wp_roksprocket/widgets/roksprocket.php:293
#12 RokSprocket_Widgets_RokSprocket:prepare_sprocket_items in /home/psdb-passofundo/www/wp-content/plugins/wp_roksprocket/widgets/roksprocket.php:107
#11 RokSprocket_Widgets_RokSprocket:roksprocket_init in /home/psdb-passofundo/www/wp-includes/class-wp-hook.php:298
#10 WP_Hook:apply_filters in /home/psdb-passofundo/www/wp-includes/class-wp-hook.php:323
#9 WP_Hook:do_action in /home/psdb-passofundo/www/wp-includes/plugin.php:453
#8 do_action in /home/psdb-passofundo/www/wp-includes/widgets.php:1474
#7 wp_widgets_init in /home/psdb-passofundo/www/wp-includes/class-wp-hook.php:298
#6 WP_Hook:apply_filters in /home/psdb-passofundo/www/wp-includes/class-wp-hook.php:323
#5 WP_Hook:do_action in /home/psdb-passofundo/www/wp-includes/plugin.php:453
#4 do_action in /home/psdb-passofundo/www/wp-settings.php:449
#3 require_once in /home/psdb-passofundo/www/wp-config.php:95
#2 require_once in /home/psdb-passofundo/www/wp-load.php:37
#1 require_once in /home/psdb-passofundo/www/wp-blog-header.php:13
#0 require in /home/psdb-passofundo/www/index.php:17

**Comment by mahagr** [comment]
Please install the previous version back from WP admin (like you would install new plugin) while I'm looking into this issue. You can find the old version from https://github.com/gantry/gantry5/releases

**Comment by mahagr** [comment]
Fixed. Please try out latest Gantry CI build for WordPress from http://gantry.org/downloads#ci-builds, it should fix your issue. Also please report back if there are any other issues remaining after the update.

Also, please don't forget to update RokSprocket (and RokGallery if you have it) on your site. There are no automatic updates to either of them, so they need to be updated manually.

**Comment by thiagocapuano** [comment]
Sorry my late. Worked Fine, both version of Roksproket x.17 and x.18 with Gantry 5.4.5
