### ISSUE TITLE
Inline JavaScript duplication in 5.4.3 (WordPress)

### ISSUE THREAD

**Issue by igor-gp** [gantry/gantry5#1795]
With the latest update 5.4.3, we're noticing our scrollreveal.js particle has stopped working (WordPress). Looking at the source code of the page, we see the particle code output 3 times, which is causing the issue. 

When we roll back to 5.4.2, the particle works fine and outputs the code only once in the source code.

**Comment by mahagr** [comment]
@igor-gp Contact me in gitter to help the to set up testing for this issue.
