### ISSUE TITLE
Dropdown arrows not consistent in styling

### ISSUE THREAD

**Issue by Quy** [gantry/gantry5#1799]
![dropdownarrows](https://cloud.githubusercontent.com/assets/368084/21959007/b966004e-da6f-11e6-872b-54f4e445f037.jpg)

**Comment by mahagr** [comment]
Styling depends on if dropdown is selectize or plain select.

@w00fz : Should we make them to look the same?

**Comment by w00fz** [comment]
The dropdowns that are not selectize inherit the look of the OS and browser that runs on. I don't think it's worth adding extra CSS just to style those arrows, it requires hiding the dropdown, wrapping the select in a div, getting the style to match selectize and it doesn't really add much.
