### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#18]
- **Theme: Hydrogen/Layout**
  - Clicking Header (for example) settings opens a pop-up for additional "CSS Classes"
  - This box can be a drop-down showing all basic G5 classes like nomarginbottom, rt-center etc so that end user can select from as in layout particle block variations
  -  Layout particle block variations are having nomarginall, nopaddingall for margin/padding. It could have other variations: top, bottom, left, right
  - Gantry allows visible/invisible classes for viewports. Instead of inputting them can you add toggles (FA icons) that would make particles/sections visible-invisible for desktop/tablet/phone? This makes G5 UI more intuitive for average end-users.
- **Menu editor**
  - Clicking any menu item opens a pop-up
  - Although many will use FA icons for menu items one can prefer a link image. So we should be able to choose an image as it is in Logo particle
- **Settings**
  - Can all boxes be tabbed for easy navigation in desktop viewport?
- **Style/Configuration Styles**
  - The terms/units can be end-user-friendly. You can even add FA icons/drop-down select boxes for simplicity.

**Comment by mahagr** [comment]
Thank you for your suggestions. Some of them we have already planned, but they haven't been implemented yet. We provided early beta access just because of this; there are some very good ideas you have there!

**Comment by thelaughingstockman** [comment]
Just a thought (and one you might already have planned) but are the themes going to follow the periodic table?  (i.e. Hydrogen, Helium, Lithium...) - that would be so cool.  It would also allow one to perhaps know the order of templates a little too.

**Comment by mahagr** [comment]
Hydrogen is just the default and free theme for Gantry 5, which may then be used as a base on other themes. They may be other example themes -- or not. :)

**Comment by thelaughingstockman** [comment]
Thanks.
Just another thought - maybe for the future but it would be great if gradient styles were supported so you could have gradients across a
1) Row
2) Page
3) Group of adjacent rows

**Comment by sural98** [comment]
**NEW REQUEST**
The name change for a menu item in Menu Editor needs 2 clicks: 1st for opening modal, 2nd clicking the name.
It can be a 1-click operation.

**Comment by w00fz** [comment]
Most of these have been implemented already with a few exceptions regarding the Layout for the reasons explained in #119. Also regarding the viewports icons that could be a good new field, we will consider that one, thanks!
