### ISSUE TITLE
module title should use same font as regular menu item titles when displayed in the menu

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#180]
i've placed a few modules into my menu and it appears that those module titles use a different font than regular menu item titles. please see pic

![g5_moduleinmenu](https://cloud.githubusercontent.com/assets/5719486/7465474/61e301b8-f296-11e4-8fb3-f1643f4663bd.jpg)

**Comment by kevlardev** [comment]
Im not sure i understand the issue here. Basically the font family assignment is divided up into two things, header font, body font. Header controls all headers, body controls everything else. Im not sure it would make sense to start arbitrarily forcing fonts in particular sections (header font gives you a special header font everywhere.... except here, and here, and oh here too).

I mean i can force override it for just output from the menu itself, but what if people want to have their custom header font theyve chosen in the admin appear there as well. I guess what im getting at is, do we want to force certain configs to not function in certain places without any indication that it wont work there?

**Comment by adi8i** [comment]
that looks weird, for me works well. Maybe you've added font picker to other sections, and there are different config. dunno or overrides ? :)

**Comment by kat05** [comment]
i've not added any fontpickers anywhere, all i did is change the font settings under 
> styles > core styles:
body font = family=Prosto+One
heading font = family=Akronim

all i am saying is that when a module is being loaded into the menu (through the gantry 5 menu manager), it's title styling does not match the title styling for regular menu item titles and that makes it look weird.

**Comment by adi8i** [comment]
That means, modules load `body font` and won't change when you place them inside menu, that load `heading` . @kevlardev  could even add `h3` from modules to take `heading font`, or control module font from a separate field.

**Comment by kevlardev** [comment]
Ya right now all h1-6 headers are hooked up to the heading font family selection, regardless of where they appear. I can easily override this by forcing h1-6 tags to inherit the font family assigned to menu item text, i was just asking if it is something we feel should be forced. As a heading is different than a menu item title, and when creating a megamenu implementation you can have lots of modules with various content and might work well from a design perspective (depending on the font of course) to have variation between the header and the text.

**Comment by adi8i** [comment]
@kevlardev Would be better to control modules `h` tags from a separate field :D

**Comment by kat05** [comment]
it's fine with me that module titles anywhere on the site use the 'heading font', like they currently do.
BUT, if they are loaded into the menu via the gantry 5 menu manager, i believe that should be overriden, so that the module titles inside the menu use the 'body font', just like regular menu item titles, who also use the 'body font'.

**Comment by kevlardev** [comment]
@adi8i they already are controlled from a separate field globally. Do you mean a separate field just for modules inside a menu? That seems like it would be a bit overkill.

@kat05 Thats fine Kat, i wasnt really arguing one way or the other, ive just been trying to limit the amount of "override" behavior when possible, so wanted to get a bit of discussion about what most felt would be the preferred behavior. I can set those to use body font selection same as the menu titles for now. This can always be changed in future themes if needed, as well as customized by users/developers easily (its just a single css rule).

**Comment by adi8i** [comment]
Yes @kevlardev, but you are right, will be a overkill :)) . Too many settings and la la la

**Comment by w00fz** [comment]
I am with @kevlardev on this one. Even though you edit the menu through the Editor, it's still the theme that dictates how it should look like. If a theme calls for specific heading in the Menu then we will add a Styles entry for that but in Hydrogen it will just inherit the section styles.

I don't think this behavior should be changed.

**Comment by mahagr** [comment]
@kat05 just hide title or change its markup by using another module chrome and the issue should be fixed :)
