### ISSUE TITLE
Owl Carousel with only 1 item

### ISSUE THREAD

**Issue by billbring** [gantry/gantry5#1801]
Owl carousel disappears completely if it only has 1 item. works fine with any more than 1.

**Comment by newkind** [comment]
Which template are you using?

**Comment by billbring** [comment]
Helium on Grav

**Comment by mahagr** [comment]
I am sure that someone else was complaining the same earlier.

**Comment by newkind** [comment]
Looks like it's a bug in OwlCarousel. Let me try to update the JS file.

**Comment by newkind** [comment]
Fixed
