### ISSUE TITLE
Mosets Tree Image Navigation Missing in Gantry Templates 

### ISSUE THREAD

**Issue by Garry-Purcell** [gantry/gantry5#1802]
Joomla 3.6.5  Mostets Tree 3.9.4 Gantry 5.4.4
Generic Prostar Template Tested: (Works Correctly)
Gantry Templates Tested: Xenon 1.2.2, Helium 5.4.4, Hydrogen 5.4.4 (No Navigation Buttons Sgoeing)

The image navigation buttons in Mosets Tree are missing when using gantry templates.
Mosets Tree works correctly in using the generic Joomla Prostar template

**Xenon 1.2.2 with images not clicked on**

![xenon 1 2 2 template](https://cloud.githubusercontent.com/assets/25141779/21969583/7d38286a-dbf3-11e6-8943-1cbe74bd6369.JPG)

**Xenon 1.2.2 expanded image navigation missing**

![xenon 1 2 2 template image no navigation](https://cloud.githubusercontent.com/assets/25141779/21969620/b94c5344-dbf3-11e6-832f-6ee40001c285.JPG)

**Standard Joomla Prostar template showing navigion buttons.**

![prostar template](https://cloud.githubusercontent.com/assets/25141779/21969647/db1cd994-dbf3-11e6-8ae3-3098c9510603.JPG)

**Comment by Garry-Purcell** [comment]
Proble fixed with ne release of Mostets Tree 3.9.5 today

**Comment by mahagr** [comment]
Do you know what the issue was and what caused it?

**Comment by mahagr** [comment]
Marked as invalid as it was fixed in another product.
