### ISSUE TITLE
Skeleton download link broken on getgrav.com

### ISSUE THREAD

**Issue by salgua** [gantry/gantry5#1804]
On https://getgrav.org/downloads/skeletons, if I click on the "download" link of the helium skeleton, it try to open the page "https://github.com/gantry/gantry5/releases/download/@version@/grav-skeleton-helium-site-@version@.zip" returning a 404 error.

**Comment by mahagr** [comment]
I can reproduce the issue, link seems to be wrong.

**Comment by w00fz** [comment]
Thanks this is fixed now.
