### ISSUE TITLE
Content Cubes are using Utility Section Background

### ISSUE THREAD

**Issue by User123698745** [gantry/gantry5#1809]
**Description:**
The Content Cube Particles are using the Utility Section Background. 

**Environment:**
Grav v1.1.12 based on grav-skeleton-helium-site-5.4.4.zip and updated to v5.4.5

**Steps to Reproduce:**
1. Navigate to the Styles Configuration
2. Change Background of Utility Styles to any other color
![styles](https://cloud.githubusercontent.com/assets/1911682/22040307/bbbb1524-dd02-11e6-992d-bf2768f83cf8.png)
3. Click on Save Styles
4. Navigate to Home
5. The background of the Utility section and of all Content Cube Particles have changed 
**Before**
![home2](https://cloud.githubusercontent.com/assets/1911682/22040454/250d102c-dd03-11e6-844d-ea8983291a8e.png)
**After**
![home](https://cloud.githubusercontent.com/assets/1911682/22040458/28c06606-dd03-11e6-9061-ab0fc78314b6.png)

**Expected result:**
Only the Utility Section background should have changed. The background of the Utility Section and the Content Cube Particles should be configurable separately.

**Comment by newkind** [comment]
To be honest, I don't like too much the idea of having color pickers in the particle settings. Personally I think that maybe we should keep it the way it is right now but just set the background color to be more opaque or lightened/darkened ?

**Comment by User123698745** [comment]
I also do not think, that a new setting is needed.

It is just quite unexpected, that changing the background of some random section is influencing a particle. For example, I wanted all section backgrounds to be white, but that is currently not possible.

How do you think about using the accent color as the background (like it is done with the Tab-Headers)?

**Current**
![old](https://cloud.githubusercontent.com/assets/1911682/22265365/166e2028-e27c-11e6-9358-606fb7669629.png)

**New**
![new](https://cloud.githubusercontent.com/assets/1911682/22265364/165bb168-e27c-11e6-8102-c467d1930aac.png)

**New (White Background)**
![new white](https://cloud.githubusercontent.com/assets/1911682/22265363/1644b18e-e27c-11e6-9d70-965e199b1621.png)

**Comment by newkind** [comment]
I've decided to settle now for linear gradient made out of accent colors. We can tweak it later if it's needed.

**Comment by mahagr** [comment]
Just a small note -- this may change looks of the existing installs.
