### ISSUE TITLE
How to change width to full width boxed content

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1811]
How to change width to full width boxed content

By default it 1150px. Can I use custom width?  % or px?
How I can change it?

Thanks

**Comment by mahagr** [comment]
I think this is controlled with a combination of breakpoints and some padding and margin.

@newkind ?

**Comment by newkind** [comment]
Depends. In Helium it's controlled by breakpoints in Styles tab. This can be very different depending on theme. Try modifying Desktop and Large Desktop breakpoints in the Styles tab of your theme.

**Comment by mahagr** [comment]
@pobo3 Did we answer to your question?
