### ISSUE TITLE
Grav: little styling issue on Forgot password form

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1812]
Please see pic using Hydrogen. Same with Gemini.

![grav_g5_forgot](https://cloud.githubusercontent.com/assets/5719486/22103807/dea3b164-de3c-11e6-96c1-95cc5a25bddf.jpg)

**Comment by hexplor** [comment]
Like we discussed before, I'm not able to reproduce screen above. Tried really hard but no way. Anyone to provide needed steps to Reach recover password screen with button above ?

**Comment by mahagr** [comment]
Looks the same also in Helium. Just go to Grav admin and edit Login plugin settings to add forgot password page and you should be able to see it.

**Comment by mahagr** [comment]
@hexplor Install Helium skeleton and go to `/login` and `/forgot_password` page.
