### ISSUE TITLE
An error in uikit.js on mobile view

### ISSUE THREAD

**Issue by Osmyakov** [gantry/gantry5#1814]
Each time you click on the link in the mobile version I have an error about trigger in uikit.js. Have the latest Gantry and Hydrogen (v5.4.5) version.
`Uncaught TypeError: Cannot read property 'trigger' of undefined
    at uikit-.js:2`

**Comment by mahagr** [comment]
@Osmyakov How are you loading uikit?

**Comment by Osmyakov** [comment]
@mahagr Sorry, I checked: an error occurs in another component.
