### ISSUE TITLE
Hydrogen Theme and GRAV: CSS Problem of columns in Safari?

### ISSUE THREAD

**Issue by oscon** [gantry/gantry5#1816]
If I configure 2 columns in a blog-list, they are displayed in Firefox but not in Safari: Is this a display problem in Safari or a CSS problem within the Gantry / Hydrogen theme?
Firefox:
![screenshotfirefox](https://cloud.githubusercontent.com/assets/478932/22173664/50b349e8-dfca-11e6-81eb-7f0ed9b1acdc.png)
Safari:
![screenshotsafari](https://cloud.githubusercontent.com/assets/478932/22173665/50da8792-dfca-11e6-8a47-dbe725147afb.png)

**Comment by w00fz** [comment]
What version of Safari is it?

**Comment by oscon** [comment]
Safari 10.0 (macOSX 10.12)

**Comment by newkind** [comment]
What platform is it? Is this a platform content or particle display?

**Comment by mahagr** [comment]
I'm going to close this one. If Safari still has issues, new issue can be created.
