### ISSUE TITLE
No object_id when saving menus

### ISSUE THREAD

**Issue by AmibeWebsites** [gantry/gantry5#1819]
On WordPress I'm no longer able to save menus. It seems to loose the object_id of whatever menu item was edited. This is what is in the post value for the edited item:

`items	
"{\"home\":{\"enabled\":\"1\",\"id\":\"94\",\"hash\":\"\",\"target\":\"_self\",\"dropdown\":\"standard\",\"dropdown_dir\":\"right\",\"dropdown_hide\":\"0\",\"width\":\"auto\",\"class\":\"\",\"icon\":\"\",\"image\":\"\",\"icon_only\":\"0\",\"subtitle\":\"\",\"title\":\"Home\"},`

**Comment by w00fz** [comment]
This I think was fixed already, can you try latest CI?

**Comment by AmibeWebsites** [comment]
Great, will do. Thank you.

**Comment by AmibeWebsites** [comment]
Perfect, working - what a relief!
