### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1820]
Wordpress, Helium template
Question about translation
Problem is -  haven't translations for text of form comments on post page.
Checked with Poedit   po file- have translation.
Used loco translate plugin for translate - nothing change

How to translate form?

Thanks

**Comment by newkind** [comment]
After you translate the `.po` file with POEdit it should generate an encoded `.mo` file. Please make sure that this `.mo` file has a proper filename ie. `helium-fr_FR.mo`

**Comment by pobo3** [comment]
ok, please tell me which file to edit with Poedit?

**Comment by newkind** [comment]
`wp-content/themes/g5_helium/languages/helium.pot`

**Comment by pobo3** [comment]
Yes, I edited the file. After I save it as helium-fr_FR.mo and helium-fr_FR.po, but there is no change in the translation

**Comment by newkind** [comment]
`fr_FR` is the WP locale code that you need to adjust for yourself. `fr_FR` is for French and I gave it as example. Please use the country code that represents the language that you have set for your WP ie. `pl_PL`, `de_DE`

Here's the list of the WordPress locale : https://wpcentral.io/internationalization/

**Comment by pobo3** [comment]
Thank you, I understand how to use the WP locale code. I use my, of course. After editing pod-file, save new po and mo files in the same directory, right?

**Comment by newkind** [comment]
Yes, please note that WP won't load it until you change your language in WP admin to the same one (or modify the wp-config.php)

**Comment by pobo3** [comment]
All checked. In the settings selected the correct  language. Po-file was translated. Files are saved as helium-ru_RU.po and helium-ru_RU.mo in same directory.
But no changes in the translation of the site. What else do I check?

**Comment by newkind** [comment]
Can you try editing wp-config.php and changing :

`define ('WPLANG', '');`
to: 

`define ('WPLANG', 'ru_RU');`

**Comment by pobo3** [comment]
Very strange, but I do not find  - define ( 'WPLANG', ''); in the wp-config.php file
I tried to add define ( 'WPLANG', 'ru_RU'); - does not work
WP 4.7.1 version

**Comment by newkind** [comment]
Can you send me your .mo file?

**Comment by pobo3** [comment]
of couse
https://yadi.sk/d/WcYGzcr93AdwyS

**Comment by newkind** [comment]
Can I also get the `.po` file so I'd know which strings are translated?

**Comment by pobo3** [comment]
https://yadi.sk/d/yzqESEeL3Ae8ug

**Comment by newkind** [comment]
Sorry my bad, forgot that the domain name in plugin is only required for plugins. The proper filename should be `ru_RU.mo`. I'll change the filename to be en_US.pot to be more clear.

**Comment by pobo3** [comment]
it 's works

Thanks a lot
