### ISSUE TITLE
Hydrogen Theme and GRAV: Rendering problem login particle

### ISSUE THREAD

**Issue by oscon** [gantry/gantry5#1823]
When placing the loginParticle, the error "error rendering login particle" is displayed. An extended configuration does not seem to be possible: What am I doing wrong (specific CSS class)?
![login_02](https://cloud.githubusercontent.com/assets/478932/22251934/cd3b164c-e24c-11e6-8df7-fb161daac893.jpg)
![login_01](https://cloud.githubusercontent.com/assets/478932/22251935/cd3ec8be-e24c-11e6-94c0-46fe24c0aeb0.jpg)

**Comment by mahagr** [comment]
Already fixed in latest CI builds (release will come soon).
