### ISSUE TITLE
Hydrogen Theme and GRAV: Pulldown menu problem

### ISSUE THREAD

**Issue by oscon** [gantry/gantry5#1824]
There is a main menu: MAINMENU *, which includes various sub-pages that are redirected to external URLs. The main menu item is displayed with an arrow pointing down, but nothing happens when you click the arrow: No submenu is displayed? What am I doing wrong?
![menu_04](https://cloud.githubusercontent.com/assets/478932/22256254/87fa30fa-e25a-11e6-8de9-b6b48ab90e15.jpg)
![menu_03](https://cloud.githubusercontent.com/assets/478932/22256255/87fb5584-e25a-11e6-8f5e-1f7940d61072.jpg)
![menu_02](https://cloud.githubusercontent.com/assets/478932/22256256/87fc7860-e25a-11e6-99e4-c42cc40eeac3.jpg)
![menu_01](https://cloud.githubusercontent.com/assets/478932/22256257/8801c2f2-e25a-11e6-91e9-382c86c3bc67.jpg)

**Comment by mahagr** [comment]
Please start by checking if it is z-index issue on your site. It can also be javascript issue, but it is less likely.

**Comment by oscon** [comment]
Sorry, but I thought Z-index problem only occurs in Safari, or am I wrong? But I tested this problem within Firefox and MSIE. How can I check z-index with Firefox? Javascript seems to work as well. At least the pulldown menu in the GRAV Theme Pinpress for example seems to work correctly (with JS).

**Comment by w00fz** [comment]
This works fine in my test, please post a link where we can look at the issue.

**Comment by oscon** [comment]
Hi Djamel,
unfortunately, it's a local installation on XAMPP 3.2.2, GRAV 1.1.11, GANTRY 5.4.5 and HYDROGEN theme 5.4.2.

**Comment by mahagr** [comment]
You can check if the state of the dropdown changes by finding it from the inspector and selecting it. Then just hover over the menu and look if the dropdown html changes its visibility.

**Comment by oscon** [comment]
I installed the HELIUM skeleton for GRAV from the GANTRY site today and all the pulldown menus seem to be working. So I think, my old configuration is somewhat buggy. Therefore, my GRAV / GANTRY installation will be completely redone again. This issue can be closed.

**Comment by mahagr** [comment]
I believe that there may have been some small changes/fixes in the skeleton itself, but those shouldn't really affect menu. I believe that there's some tiny detail that you missed in your site -- maybe in your custom CSS -- which caused the issue.

**Comment by oscon** [comment]
Nun habe ich doch noch das Problem analysieren können: es handelt sich um die Einbindung des Dienstes https://feed.mikle.com. Dabei wird ein RSS-Feed in Form eines Javascripts moduliert, welches dazu führt, dass das Pulldown Modul nicht mehr korrekt funktioniert.

**Comment by mahagr** [comment]
Have you any idea why the javascript from RSS integration interferes with the menu?

**Comment by oscon** [comment]
As it seems, it is embedding through IFRAME tag
e.g. <iframe src="https://feed.mikle.com/widget/v2/7542/" /> 
I have tried it now with pure HTML code and this does not seem to have any effect on the menu anymore
  <script type="text/javascript" src="https://feed.mikle.com/js/fw-loader.js" data-fw-param="7542/"></script>
