### ISSUE TITLE
The menu items horizontally

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1826]
How can I arrange the menu items horizontally.
I tried using "display: inline-block;" for "li" but this does not work.
Maybe there is such a possibility in the settings
Need some thing like this pictures
![menu](https://cloud.githubusercontent.com/assets/22922112/22286731/d6374502-e2f8-11e6-93d2-d1ebb6af9037.jpg)

**Comment by mahagr** [comment]
You can do it by adding columns from Gantry menu manager.

**Comment by pobo3** [comment]
One more question. If i change menu sizes in css, it have change in mobile version too. How possible to change size of menu without mobile menu changes?
Also I no need to show images from menu to mobile menu.

Thanks

**Comment by w00fz** [comment]
You can target the section id. When the menu is in mobile view it's under `#offcanvas` as well as `#g-mobilemenu-container` divs. When it's not in mobile, it's in whatever section you have put it in your Layout Manager (ie, `#header`)

**Comment by mahagr** [comment]
I'm assuming all questions have been answered. Closing the issue.
