### ISSUE TITLE
Layout Doesn't Load Template Config Yaml Layout

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#183]
Hi @mahagr , As we discussed in HipChat, the layout doesn't load template config Yaml layout files, but instead it loads the custom yaml files which is only for local dev

http://pleaselook.at/Gantry_Admin_2015-05-05_19-56-55.jpg
It doesn't load the stuff from here:
http://pleaselook.at/gantry-theme-callisto_2015-05-05_19-56-13.jpg

**Comment by mahagr** [comment]
Symlink pointing to wrong directory, closing.
