### ISSUE TITLE
New Joomla Menu Cache Problem

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#1833]
Hi, an error occured if i clear the cache (i use cachecleaner from Regular Labs) and then want to go to gantry via the new menu. CacheCleaner clears the cache after any save action. In this case i.e. i edit a module and save it, it is impossible to run gantry over the menu in Joomla!.

Can this be checked?

![menu-error1](https://cloud.githubusercontent.com/assets/20481746/22377217/489c57a4-e4b1-11e6-9abb-ab9fd0a2e646.jpg)

The RuntimeException:
`RuntimeException thrown with message "mkdir(): File exists"

Stacktrace:
#14 RuntimeException in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Component/Filesystem/Folder.php:325
#13 Gantry\Component\Filesystem\Folder:create in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Component/Theme/AbstractTheme.php:199
#12 Gantry\Component\Theme\AbstractTheme:init in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Framework/Theme.php:89
#11 Gantry\Framework\Theme:init in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Component/Theme/AbstractTheme.php:67
#10 Gantry\Component\Theme\AbstractTheme:__construct in /var/www/vhosts/maler-ffo.de/httpdocs/templates/rt_isotope/includes/theme.php:28
#9 Gantry\Component\Router\Router:{closure} in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/vendor/pimple/pimple/src/Pimple/Container.php:113
#8 Pimple\Container:offsetGet in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Component/Router/Router.php:129
#7 Gantry\Component\Router\Router:load in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/gantry5/classes/Gantry/Component/Router/Router.php:51
#6 Gantry\Component\Router\Router:dispatch in /var/www/vhosts/maler-ffo.de/httpdocs/administrator/components/com_gantry5/gantry5.php:57
#5 require_once in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/cms/component/helper.php:405
#4 JComponentHelper:executeComponent in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/cms/component/helper.php:380
#3 JComponentHelper:renderComponent in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/cms/application/administrator.php:98
#2 JApplicationAdministrator:dispatch in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/cms/application/administrator.php:152
#1 JApplicationAdministrator:doExecute in /var/www/vhosts/maler-ffo.de/httpdocs/libraries/cms/application/cms.php:261
#0 JApplicationCms:execute in /var/www/vhosts/maler-ffo.de/httpdocs/administrator/index.php:51
`

**Comment by mahagr** [comment]
@hacki65 Unfortunately I don't have access for the PRO version of the plugin.

**Comment by hacki65** [comment]
You can test it with the free version too. Open a module or a component or anything else like an article, save and use the normal "Clear cache" button and then try to open gantry via the menu.

BTW: the problem occure not every time.

**Comment by mahagr** [comment]
Can you check the parameters for the exception (click on the second call for Folder::create() and make screenshot from it or paste the variables passed to the function.

To me it looks like the folder not existing gets somehow cached even if the folder has been later created.

**Comment by mahagr** [comment]
@hacki65 I'm still unable to test this out because of the feature exists only in paid version of the plugin. I attempted to fix the issue, but as I cannot test it out, I don't know if the issue was fixed.
