### ISSUE TITLE
I want to insert a block of html code after the opening tag the BODY

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#1834]
{% pageblock body_top %}
    -BODY TOP-
{% endpageblock %}

I am creating an atom and I want to insert a block of html code after the opening tag the BODY, for this I am using this documentation:

My code in atom:
`{% pageblock body_top %}
    -BODY TOP-
{% endpageblock %}`

But the code is not inserted, I do not know if that function you are not available in the latest version or I'm just doing it wrong.
Thank you.

**Comment by mahagr** [comment]
Feature is only available in version 5.4.6 or later and requires that you haven't overridden `page.html.twig` file (or that you update your version).

**Comment by mahagr** [comment]
@Mineslu Did you get the feature to work?

**Comment by sifur** [comment]
I have same problem, I have **gantry 5.4.7**, **Helium 5.4.7** and not overridden **page.html.twig** It's working from page settings but can't load content using Atom.

**Comment by JoomFX** [comment]
@sifur This is now fixed - https://github.com/gantry/gantry5/commit/a450698e753399d31084e6cc9c83ff04e4614416

You can either wait for 5.4.9 to be released or install the latest CI build.

**Comment by mahagr** [comment]
Except that there seems to be issue related to this fix. Looking into it.

**Comment by mahagr** [comment]
Issue has been fixed.
