### ISSUE TITLE
Overriding settings in the admin on Gantry Templates

### ISSUE THREAD

**Issue by AdamWarnock** [gantry/gantry5#1835]
Sorry if the title is a little enigmatic, but I was trying to keep it short.

I'm working on the template for a site we are doing for a new client and I was wondering if it was possible to override the files in `TEMPLATE/blueprints/styles` with files that live in the `custom` directory like you can with the nucleus layout files. In a similar vein, is there a way to to override the partials in the `TEMPLARE/scss/TEMPLATE` directory? The reason I am asking is so that my coworker can switch out background images for the client without needing me to pop in and edit SCSS files. I can edit the files directly, but I'd rather do the overrides so that updates to the template or Gantry don't cause things to break.

Thanks for providing this amazing framework free of charge. I'm looking forward to digging a little more into it.

**Comment by mahagr** [comment]
Most of the files can be overridden in `custom` folder by using an identical path to the file under it. It includes blueprints and scss.

**Comment by AdamWarnock** [comment]
okay, thanks. :)
