### ISSUE TITLE
Add Collapse/Expand All in Layout Manager

### ISSUE THREAD

**Issue by Quy** [gantry/gantry5#1837]
On layout that is long, the Particles section is not visible in order to drag and drop particles. 

![layoutmanager](https://cloud.githubusercontent.com/assets/368084/22394166/2dcac7be-e4cd-11e6-8e58-f33b3dccfaea.jpg)

You have to drag and drop to a temporary section, scroll down the page, and then move the particle from the temporary section to the desire section.
OR
Drag a particle with one hand and press the down arrow key with the other hand to scroll the page to the desired section that the Particles section is not visible, and then drop the particle.

Maybe adding a Collapse/Expand All buttons in the Layout Manager be a solution.

**Comment by w00fz** [comment]
There is already a lengthy discussion you can see in #1499 and some initial work that I made in the [feature/drawer_particles_picker](https://github.com/gantry/gantry5/tree/feature/drawer_particles_picker) branch.

We are aware of the limitation a long layout present with the particles picker and we'll definitely address this at some point.

Cheers.
