### ISSUE TITLE
Grav: Adding New PHP Functions

### ISSUE THREAD

**Issue by Quy** [gantry/gantry5#1838]
I followed the instructions to [Adding New PHP Functions](http://docs.gantry.org/gantry5/advanced/php-functions) and got the following error.

```
Server Error
Sorry, something went terribly wrong!
0 - Class 'Gantry\Theme\Mobile_Detect' not found
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

Log:
> [2017-01-28 16:32:25] grav.CRITICAL: Class 'Gantry\Theme\Mobile_Detect' not found - Trace: #0 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/user/themes/g5_helium/theme.php(60): require() #1 [internal function]: Grav\Theme\G5_Helium->onThemeInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onThemeInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onThemeInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onThemeInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #4 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onThemeInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #5 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Grav.php(273): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onThemeInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Themes.php(72): Grav\Common\Grav->fireEvent('onThemeInitiali...') #7 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Themes.php(49): Grav\Common\Themes->initTheme() #8 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Processors/ThemesProcessor.php(17): Grav\Common\Themes->init() #9 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Grav.php(122): Grav\Common\Processors\ThemesProcessor->process() #10 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Grav.php(364): Grav\Common\Grav->Grav\Common\{closure}() #11 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('themes', 'Themes', Object(Closure)) #12 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Grav.php(340): call_user_func_array(Object(Closure), Array) #13 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/system/src/Grav/Common/Grav.php(123): Grav\Common\Grav->__call('measureTime', Array) #14 /var/www/vhosts/httpdocs/grav-skeleton-helium-site/index.php(51): Grav\Common\Grav->process() #15 {main}

includes/theme.php:
```
<?php
namespace Gantry\Theme;

use Gantry\Framework\Theme;

class G5_Helium extends Theme {}

// Require the Mobile Detect library
include_once dirname(__FILE__).'/../custom/includes/Mobile_Detect.php';

// Dependency Injection of Mobile Detect
$gantry['mobile_detect'] = new Mobile_Detect();
```

**Comment by mahagr** [comment]
As Grav is namespaced, you're missing backslash on the last line:

```php
$gantry['mobile_detect'] = new \Mobile_Detect();
```

**Comment by mahagr** [comment]
@ScribeRyan you may want to add the backslash in order to make the example to work in all platforms.

**Comment by Quy** [comment]
Fixed in https://github.com/gantry/docs/pull/139. Thanks.
