### ISSUE TITLE
404 upon entering the gantry admin panel

### ISSUE THREAD

**Issue by samwalls** [gantry/gantry5#1839]
After installing the gantry framework + the helium theme I can't access the gantry admin panel. It tries to access the URL: `/admin/gantry/configurations/default/styles?nonce=xxxxxx...` ...and produces a 404 error.

Running PHP 7.0.3 on [Caddy](https://caddyserver.com) and using a set of Caddyfile configurations, one of which I can identify _might_ cause issues.

```
gzip
fastcgi / 127.0.0.1:9000 php

#define site rewriting rules

#IMPORTANT FOR SECURITY
# forbid access to any of these
status 403 {
        /.feische
        /.ssh
        /.git
        /.gitignore
        /README.md
        /cache
        /bin
        /logs
        /backups
        /tests
        /composer.lock
        /composer.json
        /nginx.conf
        /web.config
        /htaccess.txt
        /.htaccess
}
# END SECURITY STUFF

# global php rewrite
rewrite {
        to {path} {path}/ /index.php?_url={uri}
}
```

Does anyone have any idea as to why this is?

**Comment by mahagr** [comment]
@samwalls Which CMS you're on?

**Comment by samwalls** [comment]
@mahagr _grav_, forgot to say!

**Comment by samwalls** [comment]
More info, this is Grav v1.1.14 - with the Admin plugin v1.2.9

**Comment by rhukster** [comment]
Have you looked at this: http://learn.getgrav.org/troubleshooting/page-not-found ???

**Comment by samwalls** [comment]
@rhukster I did, but I see that the advice speaks of Apache and Nginx only (e.g. `.htaccess` files), no word of Caddy. The only rewrite rules I have in my Caddy config are shown in the OP.

**Comment by rhukster** [comment]
Did you look in the `webserver-configs/Caddyfile` for a sample config file with rewrite support ?

**Comment by samwalls** [comment]
Looking at my server directory `/admin/gantry/configurations/default/styles?nonce=[my-nonce]` where should that URI point to? I don't see a `user/plugins/admin/gantry` folder in the grav root - I do see `user/plugins/gantry5`, but even then it contains no `/configurations...` etc..

I've tried reinstalling the grav framework, also blasting the whole server's perms (something keeps creating files under root, probably unrelated anyway) - still same outcome.

**Comment by rhukster** [comment]
Hmm. maybe try to get Grav working properly first? Then add Gantry?  It's a bit hard to debug when there's a lot of moving parts :)

**Comment by flaviocopes** [comment]
@samwalls can you try editing your Caddyfile like this?

```
# global php rewrite
rewrite {
      to  {path} {path}/ /index.php?_url={uri}&{query}
}
```

https://github.com/getgrav/grav/commit/a4c5d570aedcb4830ce2584d18b255a20751b5ca

**Comment by samwalls** [comment]
@flaviocopes thanks, but that didn't do anything, the query part `?nonce=...` is actually part of the `{uri}` itself I believe - so that should include the full path needed.

I'll try reinstalling grav in the meantime.

**Comment by flaviocopes** [comment]
I replicated 403 issues in Caddy this morning, and this code fixed it. Was the same fix we discovered in Nginx a couple weeks ago https://github.com/getgrav/grav/commit/9b5ef4c263f40cb45d36541e18d52a531d74f6ef

The problem only happens when saving the configuration in Gantry.

**Comment by samwalls** [comment]
@flaviocopes Ah right, I'll include that in my new install anyhow!
