### ISSUE TITLE
Layout name as title of Layout page

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#184]
Assume we will have a lot of configurations for a multi-lang installation and assign different layouts to them.
In that case we need to know which layout has been assigned for each config visually.
Therefore the title Layout on layouts page may have the layout name as a suffix.
For example,
**Layout (3 column - Right)**
I had pointed to this issue at https://github.com/gantry/gantry5/issues/79

**Comment by mahagr** [comment]
Not sure if it makes to beta 6, but we cannot really do this before another change for #91

**Comment by w00fz** [comment]
This was implemented with #91
