### ISSUE TITLE
The "Gantry 5" menu item in the Grav Admin Panel is not being displayed as selected

### ISSUE THREAD

**Issue by User123698745** [gantry/gantry5#1840]
**How it curently looks like**
![image 003](https://cloud.githubusercontent.com/assets/1911682/22406971/9380cb44-e65d-11e6-87c8-a83061081041.png)

**How it schould look like**
![image 004](https://cloud.githubusercontent.com/assets/1911682/22406974/98a695e0-e65d-11e6-8d96-eda9af15bb12.png)

**Notes**
- Tested with grav-skeleton-helium-site-5.4.5.zip and grav-skeleton-helium-site-5.4.6.zip
- The menu item is just missing the "selected" class
- It's probably not a bug of the Grav Admin Panel, because other plugin, that add there own menu items (e.g. [Grav Admin Styles Plugin](https://github.com/OleVik/grav-plugin-adminstyles)), do not have this problem

**Comment by mahagr** [comment]
Requires Admin plugin v1.2.11
