### ISSUE TITLE
Importing partials from /custom subdirectories

### ISSUE THREAD

**Issue by AdamWarnock** [gantry/gantry5#1841]
I've looked and I can't seem to find the information I need to answer this myself. I have a `/custom/scss/custom.scss` file that I'm wanting to import a `/custom/scss/TEMPLATE/_partial.scss` file into. The problem I've run into is that no one, not even the official SASS documentation, seems to know/say how `@import` figures out what files to import. If I have something like below:

/TEMPLATE
|-- /custom
|--|-- /scss
|--|--|-- custom.scss
|--|--|-- /TEMPLATE
|--|--|--|-- _partial.scss
|-- /scss
|--|-- TEMPLATE.scss
|--|-- /TEMPLATE
|--|--|-- _partial.scss

then have `@import TEMPLATE/partial` in the `/custom/scss/custom.scss` file, is it relative to the directory that the file is located in or is it relative to the root directory that SASS is watching?

I ask because I've overridden the `/blueprints/styles/partial.yaml` file to add an image picker for the background and I'm now trying to get the image to show up in the background by overriding the scss for the section that the partial is for.

**EDIT:** Figured it out. as it happens, scsss is not the same as scss. Oops. I'm still running into issues though. I have a background image in the yaml file I overrode for the section whose partial I was trying to override.  When I compile the scss, I get an error saying that $section-background-image is not defined. How do I go about defining it? I thought this was one of the things that Gantry did automatically, but it is apparently not the case.

**Comment by newkind** [comment]
Which theme are you using?

**Comment by AdamWarnock** [comment]
Requiem, but I had thought that this was more of a general gantry issue than theme specific.

**Comment by newkind** [comment]
To get rid of this error you need to declare the default value of this variable to false.

Please check the screenshot below:
[Image](https://monosnap.com/file/hmUU6vn59JGlX6s9TNBmTJyOQLbGcX.png)

**Comment by AdamWarnock** [comment]
Ah, thanks!

**Comment by newkind** [comment]
Can we close it?

**Comment by AdamWarnock** [comment]
I haven't had a chance to try it, but I think so, yeah.

**Comment by AdamWarnock** [comment]
Figure I should let you know this worked. Thank you for the help. :)
