### ISSUE TITLE
Grav Theme Update Does Not Recompile CSS

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1847]
When updating Helium 5.4.5 theme to Helium 5.4.6, CSS is conflicted (navigation should not display as shown). Recompiling fixes the issue, but it would be nice to see recompile happen automatically upon update if possible:

![screen shot 2017-02-03 at 11 03 52 am](https://cloud.githubusercontent.com/assets/5002814/22604125/bbf178a2-ea0f-11e6-8364-bba7504e34f2.jpg)

**Comment by mahagr** [comment]
This is related to #1752, though a different issue.

**Comment by simmonsr** [comment]
fixed confirmed after installing latest gantry ci
