### ISSUE TITLE
Helium Theme | HOME Navigation menu always white 

### ISSUE THREAD

**Issue by derCarlo** [gantry/gantry5#1850]
JOOMLA 3.6.5:  i need help to change the navigation style / color at home button, it is always white i can change in template settings for navigation in helium - home - particles section ... and its always white only at home button at helium theme, i go crazy. please i need help to find out why only the start page menu i cant change from white to other colour ???

**Comment by newkind** [comment]
This is a specific style for the Home page only. You can change the color in the `_helium-style.scss`

**Comment by derCarlo** [comment]
many thx ... but there are so many files in the file system from helium i would never find the helium-style.scss ;) i read the othe post from you even and i remove the g-helium-style body style class
but as said in post you remove also the overlapping owl carousel is also removed ;(

**Comment by newkind** [comment]
Yah, I'll try to move this to the outline config.

**Comment by N8Solutions** [comment]
@derCarlo I tagged you in the chat about this here [February 4, 2017 4:20 PM](https://gitter.im/gantry/gantry5?at=5895e3179eb1bd81481b879d) :point_left:

I opened an issue about this around a month ago #1783

As I stated there, having the nav color added like that is a bad idea in my opinion. Not only that, there are a lot of new guys coming in who won't catch where it is and removing that class to be able to change the text color via the styles tab also removes a lot of other styling and forces the developer to change the font color via the `custom.scss` file.

**Comment by mahagr** [comment]
This is actually duplicate of #1783
