### ISSUE TITLE
Grav Particle based cache 

### ISSUE THREAD

**Issue by hugoaf** [gantry/gantry5#1851]
Hi,

I've created some particles that gets and shows content from Grav page header (frontmatter). However I need to keep Gantry cache disabled (Development Mode) in order to reflect changes done in admin. Otherwise a nice HTML is saved on cache and my changes are not taken unless I go to Gantry and clear cache.

I've noticed that the Content particle does not cache even if Production Mode is enabled. Is there a way to make my own particles to behave like Content particle, I mean to prevent being cached?

If not, maybe this question can be turned to a feature request.

Regards.

**Comment by mahagr** [comment]
Just remove caching (or change it to dynamic) from the particle you're created. Static caching should only be used for particles which will always have identical output regardless of the context. This means that their output only changes if you change the particle settings.

**Comment by hugoaf** [comment]
thanks @mahagr, could you please give me an example on how to remove caching from my particles?

**Comment by mahagr** [comment]
Just make sure you don't have this in your yaml file:

```yaml
configuration:
  caching:
    type: static
```

**Comment by hugoaf** [comment]
It is fixed now, thanks.

This was my issue: my yaml file actually did not have the configuration variable, but I forgot to mention that I was overriding the Owl Carousel Particle, which indeed has the ´static´ caching. I did override with:
```
configuration:
  caching:
    type: dynamic
```
Thank you again @mahagr

**Comment by mahagr** [comment]
Sorry if I was not specific enough as I meant the blueprint file.
