### ISSUE TITLE
visible-tablet / hidden-tablet is still issue

### ISSUE THREAD

**Issue by mediaDESIGN-SK** [gantry/gantry5#1853]
This does not work in Gantry 5.4.6:
`<span class="visible-tablet">Kommunikations-<br />mittel</span><span class="hidden-tablet">Kommunikationsmittel</span>`
The issue is known but i think not realy solved. See threat [(https://github.com/gantry/gantry5/issues/1705)]
Here you can see: http://www.einkonzept.de/ (middle of page by block WebDesign (sorry page is very slowly).

**Comment by marktaylor46** [comment]
Clear server and browser cache and recompile your CSS from the base outline.

Then it should work.

**Comment by mediaDESIGN-SK** [comment]
Thank You Mark! recompiling base outline, japp, this was the right solution. You are my hero.

**Comment by mahagr** [comment]
Duplicate to #1752
