### ISSUE TITLE
highlighted (hover) social icons have an underlined character

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1854]
Joomla 2.5.1
Gantry 5.4.6
Modified Helium 5.4.6
Kunena Blue Eagle 5 theme

only on the pagehttps://quantumwarp.com/forum

When you hover over a social icon (top-left) to the right there is a white underline.

![underline](https://cloud.githubusercontent.com/assets/319997/22660175/72671b3e-ec98-11e6-8745-32cd5bd5fbda.png)

This issue also affects the footer menus as you can see below. 
![footer-menu](https://cloud.githubusercontent.com/assets/319997/22662175/0452b02e-eca0-11e6-93a4-1fea358f1af9.png)

If this is an issue with kunena can you let me know and I will chase them over there.

Thanks

**Comment by mahagr** [comment]
Looks like links have underline on hover. Maybe you should add custom.scss to remove it from `.g-social a:hover` rule.

**Comment by newkind** [comment]
This is added by bootstrap, not Helium.

**Comment by shoulders** [comment]
newkind is right this is being added by bootstrap. Gantry uses its own modified bootstrap and this overrides it giving the didgy look.

after investigation it looks like the kunena forum blue eagle template still loads bootstrap after being turned off. I will pass this on to kunena guys but leave this issue open just for now if that is ok.

**Comment by shoulders** [comment]
I have logged this at kunena as it is a problem with the new template.

**Comment by shoulders** [comment]
I have logged this at kunena as it is a problem with the new template.

https://www.kunena.org/forum/blue-eagle-5/139734-bootstrap-will-not-disable

**Comment by 810** [comment]
@shoulders do you have a link for me, then i will do a pr on helium template. I think the best option is to adding the correct parameter, else other components have the same issue

**Comment by shoulders** [comment]
I think this is the link you want.

https://quantumwarp.com/forum

But I am pretty sure it is because the disable bootstrap option in blue eagle does not work.

**Comment by 810** [comment]
see pr

**Comment by shoulders** [comment]
it is also the footer menus that are affected

**Comment by newkind** [comment]
Sucks that this needs to get overwritten because of the bootstrap but well... ;)

**Comment by Quy** [comment]
Or the social particle markup needs to be updated to not include spaces in the `a` tag.
```
    <div         
         class="g-block g-social-header size-20">
                                                <div class="g-content g-particle">
                                    <div class="g-social ">
                    <a target="_blank" href="http://www.twitter.com/rockettheme" title="">
                <span class="fa fa-twitter fa-fw"></span>                <span class="g-social-text"></span>            </a>
                    <a target="_blank" href="http://www.facebook.com/RocketTheme" title="">
                <span class="fa fa-facebook fa-fw"></span>                <span class="g-social-text"></span>            </a>
                    <a target="_blank" href="https://plus.google.com/+rockettheme" title="">
                <span class="fa fa-google-plus fa-fw"></span>                <span class="g-social-text"></span>            </a>
            </div>
            
    </div>
```

**Comment by newkind** [comment]
Ok, I merged the #1862 PR, but for the next time please remember that such SCSS changes that affect *only Joomla* should be under `joomla` scss only and not `common` as right now for WP, Grav and Prime this will reset nothing ;)

**Comment by hacki65** [comment]
At RocketTheme: should be a good idea to check out your payable themes for this issue.

I have the same issue with the theme "Isotope" in combination with the pagebuilder "Quix" from ThemeXpert. I had to make an override for quix in custom.scss for quix in this case.

**Comment by mahagr** [comment]
Maybe we should fix this in joomla overrides for nucleus instead?
