### ISSUE TITLE
“search icon clickable” in menu bar

### ISSUE THREAD

**Issue by renishguru99** [gantry/gantry5#1856]
Hi,

Step 1) I have create custom code for search icon clickable. Please check - www.screencast.com/t/tT0Q8GXh 

Step 2) I have insert the code for articles. please Check. Site Link - www.test7.guru99.com/introduction-node-js.html 

Step 3) How to insert code, for “search icon clickable” in menu bar?. - www.screencast.com/t/ALx2y4FtdEdW 

I have try for created module and set Module Positions in the menu items. But it’s not working. please check - www.screencast.com/t/vYcaGElGm 

Please help Me.

**Comment by mahagr** [comment]
To me it looks like that the module is badly coded, but I also cannot really see why it wouldn't work as long as you have only single instance of the module per page. Multiple module instances will break -- as I said, it is badly coded.

Not Gantry issue, closing.

**Comment by mahagr** [comment]
BTW, if the search module is yours, it is much easier to create a particle from it and make it to work.
