### ISSUE TITLE
logo getting cut off at the top

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1858]
joomla 3.5.1
Gantry 5.4.6
Modified Helium
Firefox and Chrome
https://quantumwarp.com/

This is a minor issue

I have made some adjustments to the CSS code to reduce the gap between the content. 

````
.g-content {
	margin: 0.625rem;
	padding: 0.938rem;
}
````
to
````
.g-content {
	margin: 0.3rem;
	padding: 0.45rem;
}
````
and now the logo is slightly cut off at the top (a couple of pixels). I would of expected that even though I have reduced the gap that the logo would not get cut of at the top.

![logo-chopped](https://cloud.githubusercontent.com/assets/319997/22700227/cc47a038-ed51-11e6-9eed-6b2edfcaebcc.jpg)

It looks fine on a mobile.

Is this a bug or intentional because of other elements at play? If there is a reason for this i will do a bit of CSS code to fix it.

Thansk as always

**Comment by newkind** [comment]
It doesn't look fine on mobile - this is what your screenshot presents.

There's a negative margin on logo in mobile view to make it look nice.

```
@include breakpoint(mobile-only) {
    display: block;
    text-align: center;
    margin: -0.85rem 0;
    padding-left: $content-padding;

    img, svg {
        margin: 0 auto;
    }
}
```

If you are modifying margins and paddings on container you should modify/remove that too.

**Comment by shoulders** [comment]
for reference
````
/* content - reduce the margins of content (helium_13.css:16) */
.g-content {
    margin: 0.3rem;
    padding: 0.45rem;
}

/* after the fix above - correct the logo's top getting cut off in mobile view (templates/g5_helium/scss/helium/particles/_logo.scss)*/
@media only all and (max-width: 47.938rem) {
    .g-logo {        
        margin: -0.4rem 0;        
    }
}
````
