### ISSUE TITLE
Section tag attribute values not save on "ENTER" - only on "APPLY" or "APPLY & SAVE"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1860]
Please see this video - section tag attribute values are not being saved on pressing of just the "ENTER" key (the attribute is actually being saved - just not the value).

https://www.screencast.com/t/TwYoK4GqHo

Tested in Joomla and GRAV

**Comment by mahagr** [comment]
Looks like that if you have a focused field, enter will do a different thing depending on which field you're in. Most fields cause the form to be submitted, selectize does not. In this case, the entered value gets lost.

Should we just disable submit on enter as this I think that the current behavior is just too confusing?

**Comment by marktaylor46** [comment]
I could live with that though I think pressing enter should use the "default" button on the form and that should be "APPLY".
