### ISSUE TITLE
Problems with Particles 

### ISSUE THREAD

**Issue by romulorcar** [gantry/gantry5#1865]
The buttons for executing the functions are gone and an error appears when I click on block, inherit also does not appear.
![sem titulo](https://cloud.githubusercontent.com/assets/21232048/22836659/7a0ab53a-efa4-11e6-820e-e0f0070ac70e.png)
![sem titulo2](https://cloud.githubusercontent.com/assets/21232048/22836709/a9b9eb66-efa4-11e6-8d53-9131dc74b423.png)

**Comment by mahagr** [comment]
You have xdebug turned on with bad (and old) default settings.

```
[XDebug]
xdebug.max_nesting_level = 1000
```

**Comment by romulorcar** [comment]
Thanks! It´s working!
