### ISSUE TITLE
Borken "Apply" in collection.list

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1866]
In a collection:
  - create multiple items (on my test works fine when there's only one item)
  - fill a field, then hit `apply` -> `apply` (DON'T use `apply and save`)
  - without saving the layout, open the collection item again

**Comment by mahagr** [comment]
Is this issue the same as #1869? As I am not sure if you are editing single item or all items.

**Comment by adi8i** [comment]
I don't know what to say..., I was editing single item.

**Comment by mahagr** [comment]
Can you test if latest CI build fixes your issues?

**Comment by adi8i** [comment]
It's fixed !
