### ISSUE TITLE
"Edit All Items" removes the field values in 5.4.7

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1869]
Hey Matias,

This is the same issue as the one @adi8i reported [here](https://github.com/gantry/gantry5/issues/1817).

The issue is reproducible with the "Social" particle in a default Gantry 5.4.7 + Hydrogen installation.
Have a look at [this video](https://youtu.be/hyB_NW8X2X0). It shows everything.

I cannot reproduce the issue in G5.4.6

**Comment by adi8i** [comment]
ref. 1866

**Comment by alisamii** [comment]
I can confirm that this issue also exists in CI build dev-0adcbc0c4.

Please see this screencast:

https://www.screencast.com/t/DEqVgXKB1

**Comment by alisamii** [comment]
Fixing this issue is really very important. I have gantry modules with particles that have collection items that have 50, 100 and in some cases 200 items in them. Although still unwieldy using the multi-item interface to edit each of those items, it works. If I have to open each item one by one, it makes managing the site impossible.

I would love if there was a way to have a text document which could be read on load to create an array of some sort that would also me to just upload 100 images, and then have a text document that I point to that contains the necessary fields that generate a collection.items list. Something like this, but that's another issue I will open later.

```
[
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_01.jpg",
    title: "Koala Bears",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_02.jpg",
    title: "#Kangaroos",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_03.jpg",
    title: "#Blue Mountains",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_04.jpg",
    title: "Royal Botanical Gardens",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_05.jpg",
    title: "Sydney Harbour Bridge",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_06.jpg",
    title: "Sydney Opera House",
    category: "Destination"
  },
  {
    url: "gantry-media://destinations/ie/cork/destination/destination_07.jpg",
    title: "Ferry to Manly",
    category: "Destination"
  }
]
```

**Comment by w00fz** [comment]
I'll look into this, when did this stop working by the way? It's not something I recall has changed in a while. Also do you get any js errors? What's the Ajax response you get back?

Also @alisamii, you can always edit the yaml files manually, no need to rely 100% on the admin, especially if you are dealing with 200 items. I myself would rather manage that through file system over ui.  I don't think having a parser to import data from a document would make much sense, it would just add an extra layer of complexity for something you can already do by simply editing the file directly.

**Comment by mahagr** [comment]
Thank you for showing how to reproduce the issue. The issue was introduced with my blueprint code change 31st of January, the code came from a branch that was older than the fix, so it seems that the old bug was reintroduced accidentally.

**Comment by mahagr** [comment]
This one should be fixed now in latest CI build. Please test it out.

**Comment by JoomFX** [comment]
Yep, just tested it with the latest CI and the issue is fixed.
Thanks Matias 😉
