### ISSUE TITLE
Add Media Button not working - Gantry 5.4.7, WP 4.7.2

### ISSUE THREAD

**Issue by simoncramer** [gantry/gantry5#1870]
After Updating to Gantry 5.4.7 using Wordpress 4.7.2 the "Add Media" Button is not working any more. No images are displayed and uploaded images are not inserted into the post.

Any ideas?

**Comment by newkind** [comment]
Are you talking about "Add Media" button on post/page edit page?

**Comment by simoncramer** [comment]
Yes! The button on the post/page edit page!

I would guess it's a javascript problem, since Wordpress upgraded to a new version in 4.7 . When I deactivate the gantry plugin my backend works normally.

**Comment by newkind** [comment]
Well that's definitely not Gantry. We don't load any JS code on post/page edit pages. Must be something else. I also just tested my local installs and all seems to be fine for me.

**Comment by mahagr** [comment]
@simmonsr What was it?

**Comment by simoncramer** [comment]
It was the helium theme. I switched to hydrogen, since it has a lot less stuff that I don't need anyway

**Comment by mahagr** [comment]
Reopened to allow us to do some additional testing.

**Comment by mahagr** [comment]
I have WordPress 4.7.5 running Helium theme. I went to `Posts` and edited one. `Add Media` button works just fine (I can upload and see the images in the media library).
