### ISSUE TITLE
Modal window in owl gallery link

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1871]
Is there a way to put a link to modal window in owl gallery?

Thanks

**Comment by pobo3** [comment]
as a result, owl gallery button link must open a form

use Grav

**Comment by mahagr** [comment]
I'm not sure how this issue got missed. I'm sorry about that.

You should read Owl Carousel documentation, it should list all the supported features and provide some documentation how to use those.

As this question is out of scope from Gantry itself and I don't know the answer, I'm closing the issue.
