### ISSUE TITLE
Add Accessibility support for Font Awesome icons

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#1873]
Currently the way Font Awesome icons are implemented does not allow for `aria-label` or `aria-hidden` to be used.

I'd like to request Accessibility support be added for Font Awesome in Gantry 5.

Accessibility documentation for Font Awesome.
http://fontawesome.io/accessibility/
As discussed here
https://github.com/FortAwesome/Font-Awesome/issues/6133
here
https://github.com/FortAwesome/Font-Awesome/issues/9566
and here
https://github.com/FortAwesome/Font-Awesome/pull/9586

>Any cases where an interactive element was being described, we've moved to using the following syntax and recommendation of using an `aria-label` on the interactive element itself (vs. the `title` or `.sr-only` approach).
**Note:** For **non-interactive** elements, we continue to recommend the `.sr-only` approach.

**Example of new syntax**
```html
<a href="path/to/shopping/cart" class="btn btn-primary" aria-label="View 3 items in your shopping cart"
  <i class="fa fa-shopping-cart" aria-hidden="true"></i>
</a>
```

**Comment by mahagr** [comment]
Feel free to find all fa usages and fix those. :)

**Comment by N8Solutions** [comment]
I have completed adding `aria-hidden="true"` to all the mentions of the font awesome icons in the files. I believe I found them all and have created a pull request for it, #1875.

However I believe something still needs to be done with the Menu and the social media particle's so that if you choose **icon only** it is not recognized as a bad link with no text. Please correct me if I'm wrong but I believe in those instances we could add `aria-label` have the label come from the Title or name of the menu item even though it's not shown.

**Comment by mahagr** [comment]
@N8Solutions Create a new issue if you want to fix the particle labels.

**Comment by N8Solutions** [comment]
@mahagr 
Thank you for merging that pull request. It included a fix for the **social** particle.
I'll open a new one for the **menu**.
