### ISSUE TITLE
Layout Manager - Issue when wrapping sections in a container

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1874]
Hey guys,

When you wrap some sections in a container and you then add a "Tag Attribute" to the container, the inner sections get kind of broken. I mean, the "Block" tab appears in the settings of the inner sections while it shouldn't.
This "Block" tab causes issues because the user can no longer save the settings for the inner sections.

Here, have a look at [this video](https://youtu.be/bZPaBQXlIMU). It shows everything.

**Comment by WebAtelier47** [comment]
Hi, i still have this issue, any solutions ?
Thanks.
