### ISSUE TITLE
Text Values Same Color As Placeholder WordPress

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1876]
This drives me a little crazy. Both Text input values and Placeholder text are the same color in WordPress G5 Admin. Hard to tell which is a real value and which is placeholder (see screenshot top is field is value / bottom is placeholder).

Joomla and Grav use #111111 for values, not sure why WP does not.

![screen shot 2017-02-15 at 4 11 17 pm](https://cloud.githubusercontent.com/assets/5002814/22997817/96765104-f399-11e6-8f09-daaa5e5cc5b5.jpg)

**Comment by simmonsr** [comment]
This is Joomla:

![screen shot 2017-02-15 at 4 20 37 pm](https://cloud.githubusercontent.com/assets/5002814/22998043/b4354f50-f39a-11e6-831f-71b2e832fd77.jpg)

**Comment by newkind** [comment]
While I of course agree with you, I don't have this issue in my WP: 

![Issue](https://monosnap.com/file/PwrCLR1ay2p3LApCrSeR1wovMKX2yM.png)
