### ISSUE TITLE
mobile-menu-breakpoint couldn't greater then 48rem

### ISSUE THREAD

**Issue by kennste-eh-nich** [gantry/gantry5#1878]
Hi,
i added different values for the mobile-menu-breakpoint, which are greater than 48rem / 768px, but nothing changed. If i uses values which are greater than 48rem, the mobile-menu where visible at the default breaktpoint (48rem).
If i use values which a lower than 48rem, then is everything fine and the mobile menu is display at correct breakpoint.

Please solve this problem. Thanks alot!

I use:
Wordpress 4.7.2
Gantry + Hydrogen Theme in newest Version

**Comment by kennste-eh-nich** [comment]
Hi,
i've checked my site again. I think the problem is only on the "HOME"-outline. If i change the breakpoints in other outlines -> everthing works perfect.

**Comment by newkind** [comment]
Home outline is no different than other outlines in this case. Can you post a link to your site?

**Comment by cegascam** [comment]
I'm having the same problem with a joomla website, i set the mobile menu to 3000rem but it works like the original 48rem didn't change at all.

**Comment by cegascam** [comment]
I solved the problem, it was the site caché, maybe that's why kennste-eh-nich had the problem only at some outlines.
