### ISSUE TITLE
Mobile-menu particle prevent opening the offcanvas on desktop without adding an particle to offcanvas section

### ISSUE THREAD

**Issue by MarcosRakesh** [gantry/gantry5#1879]
Selecting Always in offcanvas settings is just showing the toggle icon but ~~menu~~ the offcanvas won't open.
Ref: #1630

**Comment by kat05** [comment]
Correct, the MOBILE menu will only show on MOBILE and not on desktop.

If you want anything to render on desktop when toggling the Offcanvas toggle, then you should add an actual menu particle to the Offcanvas section in the Layout.

**Comment by MarcosRakesh** [comment]
> @kat05 
I was talking about **offcanvas section**, not "mobile menu" (if you read the title, i changed the misleading description). Also if you place menu particle in offcanvas section won't work because is unstyled, since only work on mobile only.

> @mahagr
I made an statement not an interrogative question about the issue

I said what setting need to replicate, but here how to reproduce (for noobs):
Install G5 + Hydrogen/Helium -> Go to to admin -> Particle default tab -> Select a menu (if isn't selected any) -> Go to styles tab -> Offcanvas Styles: Set Toggle Visibility from Mobile to Always -> Save -> Go to site and if you click offcanvas toggle won't open the offcanvas, if you resize browser the offcanvas will open with mobile menu. 
I found the issue: Mobile-menu particle prevent opening the offcavas since it makes require to add one particle to the offcanvas section in layout to open (without one particle the offcanvas won't open) if you add another mobile-menu particle it will open the offcanvas blank (which is normal because no other content was add to it). So mobile-particle should open the offcanvas without second particle because the toggle icon is useless since it won't open the offcanvas

**Comment by mahagr** [comment]
This is kind of bug as the style setting forces the icon to show up, but it doesn't change the behaviour, just the style, which can be confusing. I don't remember why the setting was added originally, but I believe it was supposed to be used together with something else.
