### ISSUE TITLE
Redirect loop if session times out in admin

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#188]
as discussed on hipchat
\JHtml::_('behavior.keepalive'); doesn't seem to work

**Comment by mahagr** [comment]
Did you leave your laptop sleeping overnight? I think it's when I get the issue.

**Comment by kat05** [comment]
i had the gantry 5 admin open in one of my browser tabs, then cleared firefox cache and cookies, then went back to that tab where i had the admin open and tried to click around between the different gantry 5 admin panels i believe.

**Comment by w00fz** [comment]
I fixed this and forgot we had a ticket about it
