### ISSUE TITLE
Gantry and Grav modular pages

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1880]
I try to use the Gantry and Grav.
How to use the modular pages, if the outlines of the Gantry (helium) already contains a  position. For example, I need to insert a feedback form in a particular part of a page in a layout position. How?
Grav content has setting only for articles

Thanks

**Comment by mahagr** [comment]
Modular content is considered to be part of the main page content, just like in Grav. You cannot add it into any positions because of it will be rendered by the page type twig.

However you are able to skip modular rendering in twig and create a particle to render it.
