### ISSUE TITLE
Is there anyway for a particle to know its position?

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1881]
Is there anyway for a particle to know its position?

I am loading the same particle - that I have positioned it as a g5 particle module - in 2 positions.
I want to be able to find out from inside particle's twig, the position.
Is this possible?

**Comment by mahagr** [comment]
I don't think it is possible, or at least it depends on the CMS and how its positions work.

I will get back after reading the code.

**Comment by mahagr** [comment]
Right now there's no way particle to know its position.
