### ISSUE TITLE
Topaz in WordPress Acting Up with Latest Gantry CI

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1883]
Please see screenshot. When you install latest Gantry 5 CI using our premium theme, Topaz, several sections are missing from the FP:

![screencapture-localhost-8888-wordpress-topaz-1487365214451_720](https://cloud.githubusercontent.com/assets/5002814/23136314/ca0d346c-f761-11e6-9102-6e32edb26c15.jpg)

Not sure if this is an issue with our theme or Gantry, but I am creating an issue. One of these files seems to have caused the issue:

![screen_shot_2017-02-17_at_4 33 42_pm_360](https://cloud.githubusercontent.com/assets/5002814/23136310/c6975e48-f761-11e6-94c1-9cd3ee084256.jpg)

**Comment by mahagr** [comment]
Change in #1834 breaks this.

**Comment by kat05** [comment]
Fix confirmed in latest CI
