### ISSUE TITLE
Tag attributes should output raw

### ISSUE THREAD

**Issue by Quy** [gantry/gantry5#1886]
Here is the output of tag attributes. It should be raw.
In Blocks section:
`style` `color:red`
output:
`style="color&#x3A;red"`

**Comment by mahagr** [comment]
That wouldn't work for JSON encoded data-* attributes.

**Comment by w00fz** [comment]
This was actually raw and one could render the `style` tag attribute. Has it changed?

**Comment by mahagr** [comment]
```
{% set attr_extra = attr_extra ~ ' ' ~ key|e ~ '="' ~ value|e('html_attr') ~ '"' %}
```
Looks like it's been like this from 2015.

**Comment by w00fz** [comment]
Seems to be working as expected here.

![home grav 2017-06-28 10-01-00](https://user-images.githubusercontent.com/11734/27650127-c51d4b40-5be8-11e7-9097-541f81041fc2.png)

Feel free to reopen with more details if this is still an issue.

Thanks.
