### ISSUE TITLE
Target option for Logo / Image particle

### ISSUE THREAD

**Issue by pdowse** [gantry/gantry5#1887]
Hi Guys,

Would be great if there was a targeting option for the Logo / Image particle. For example if you use this particle to add a suppliers logo to a page. it makes sense that the image link opens in a new window. 

Having a target="_blank" or 'open in a new window' option at the particle level (instead of having to hard code it into the particle as an override) makes sense as then you can use this particle for a combination of internal and external links on multiple pages.

**Comment by vmamet** [comment]
I went thru the same issue : 
my solution if it can help is to use custom html instead of logo/image
<a href="https://www.link.com" target="_blank">
<img border="0" alt="" src="images/test.jpg"> 
</a>
It worked for me ;)
