### ISSUE TITLE
Add aria-label to the Menu items for better Accessibility support

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#1888]
@w00fz 
I would like to add `aria-label` to the menu particle so that when **icon only** is used for a menu item screen readers won't detect it as a bad link with no text.

I believe **line 49** of the **menu.html.twig** file is where `aria-label` needs to go I'm just not sure how to implement it properly.
This is how **line 49** is in the file.
```twig
<a class="g-menu-item-container{{ item.anchor_class ? ' ' ~ item.anchor_class }}" href="{{ item.url }}{{ item.hash }}"{{ (title ~ target ~ rel)|raw }}>
```
would I add `{{ (aria-label ~ target ~ rel)|raw }}` at the end before the closing `>`?

What I'm trying to accomplish is to pass the name of the menu item on to the Icon so this way it doesn't need it's own field for text input. 

cc: @mahagr @newkind

**Comment by N8Solutions** [comment]
@w00fz 
I tried what you suggested, you said:
>no
you have to create it first
they are defined above
see https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/particles/menu.html.twig#L39-L44
you want to have a `{% set arialabel = title %}` after line 44 and then in line 49 you change `{{ (title ~ target ~ rel)|raw }}` to `{{ (title ~ arialabel ~ target ~ rel)|raw }}`

I did what you suggested and it didn't pass the `aria-label` to the fa icon.
I tried changing it to aria-label but that just broke the menu and it didn't display.

Any other suggestions on how to accomplish this?

**Comment by mahagr** [comment]
Should you pass the whole attribute:  `{% set arialabel = 'aria-label="' ~ title|e ~ "¨ %}`

**Comment by mahagr** [comment]
@N8Solutions ping ^

**Comment by N8Solutions** [comment]
@mahagr  I missed you mentioning me in the comment. Better late than never. Thanks to you and the G5 Team for getting this taken care of!

**Comment by dgrimey** [comment]
I am after adding aria-labels to the menu and submenu items. I added the following lines 
`{% set arialabel = ' aria-label=' ~ item.link_title|default(item.title)|e ~ '' %}` 
around line 44 and 
` <li {{ arialabel }} ...` 
to line 81 and it works great however if the **title has a space** the label gets **broken up** to i**ndividual words**.  in the following example "**technical architecture**" title becomes the following: 
`<li aria-label="technical" architecture="" ... `
Any suggestions to how to get this to work?

**Comment by dgrimey** [comment]
I solved my issue and see Gantry had already thought this one through. I was trying to add it automatically, but I see adding a "List Tag Attributes" item was way easier and better. I hope this helps someone else out there. I wrote a blog post on the steps. 
[](https://blog.grimeymedia.com/gantry-adding-aria-labels/)
