### ISSUE TITLE
"enable.enable" inside "container.set" broken in 5.4.9

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1889]
Hey guys,

There seems to be an issue with the `enable.enable` YAML fields which are inside a `container.set`.
If the `enable.enable` field in not in a `container.set` it will work fine.
The issue is reproducible in 5.4.9 only.

Here, have a look at [this video](https://youtu.be/3Ej4_9ixoCM).

**Comment by mahagr** [comment]
Has to do with the fixes I made for the containers. Looks like I missed something.

**Comment by hacki65** [comment]
When will this be fixed? 11 days ago nothing happend. ITS A BUG!!!!

**Comment by mahagr** [comment]
Sorry about the delay on fixing this issue; I've been both super busy elsewhere and got sick.
