### ISSUE TITLE
JavaScript Frameworks Revert To Default State On Save [Wordpress]

### ISSUE THREAD

**Issue by brandonchance** [gantry/gantry5#1890]
The inner parameters inside of the "JavaScript Frameworks" atom revert to their default state on save.

Activating/Deactivating Frameworks
![gantry](https://cloud.githubusercontent.com/assets/15754732/23323786/290319ba-fab8-11e6-8b32-afd4f96b9e0a.png)

System said it saved
![gantry1](https://cloud.githubusercontent.com/assets/15754732/23323747/f8cbacf8-fab7-11e6-9146-8b3f1d963c66.png)

Opened it back up, Frameworks reverted to natural state
![gantry2](https://cloud.githubusercontent.com/assets/15754732/23323746/f8c927bc-fab7-11e6-875c-73cc8051bd77.png)

- Wordpress 4.7.2 (w/Helium Template)
- Gantry 5.4.9

**Comment by brandonchance** [comment]
Just tried this on another one of my sites and the issue was reproducible.

**Comment by JoomFX** [comment]
It is a bug in 5.4.9 which will be fixed in the next release.
For more details, have a look at [this issue](https://github.com/gantry/gantry5/issues/1889).

For now you can just downgrade to 5.4.8. You can download all versions from [here](https://github.com/gantry/gantry5/releases).

**Comment by brandonchance** [comment]
Ah, thank you and glad to hear this is already being addressed!
