### ISSUE TITLE
grav helium vs hydrogen theme....

### ISSUE THREAD

**Issue by 4evermaat** [gantry/gantry5#1894]
I was trying to ascertain the difference between these 2 themes.  any links to demos or documentation discussing this?

I'm using grav 1.1.17.

**Comment by mahagr** [comment]
The main difference between the themes is that Hydrogen is a real, fully styled theme, where Helium has just minimum styling to make it look "nice". If you want to do all your styling yourself, start with Hydrogen, otherwise Helium is a better choice.

**Comment by andrempeixoto** [comment]
Here are some diferences too:
![image](https://user-images.githubusercontent.com/35813862/47015099-7bbedf80-d122-11e8-844f-e93d87c8ccc0.png)
