### ISSUE TITLE
How to add a new font to the font picker?

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#1895]
Hi,
I've tried to add a new font to the font picker and I've followed this guide : http://docs.gantry.org/gantry5/tutorials/fonts
The font name is appearing on the picker but I cannot select one specific variation style of this font.
![font-picker](https://cloud.githubusercontent.com/assets/3976174/23459911/b8ae8bb2-fe82-11e6-9d59-116f0873981a.png)
It doesn't shown below the list of all variations.

**Comment by mariantanase** [comment]
Is any chance to have an answer ? Thanks

**Comment by mahagr** [comment]
@w00fz should know more about this subject.

**Comment by mariantanase** [comment]
I suggest that the topic should be moved to the docs github.
Anyway, in my opinion, the page http://docs.gantry.org/gantry5/tutorials/fonts should be reviewed because of two issues:
First: The **Roboto** font is already included into the Hydrogen template.
Second: It's not a good ideea to use a premium **Calisto** template as example.
Thank you

**Comment by ScribeRyan** [comment]
Hello,

I rewrote the part of the guide you're referring to with a new font and the default Helium theme as the example, tested, and committed. Hope this helps. :)

**Comment by mariantanase** [comment]
Sorry Ryan, but it still the same issue.
I attach these two screenshots where I'll try to explain the following steps:
1. write some sample text on the upper left field;
2. search for the name of the font on the upper right field; Now, you should see all variations of this font.
3. now I want to select **a particular variation** for that font.

![ok-roboto](https://cloud.githubusercontent.com/assets/3976174/24247150/d08a4678-0fca-11e7-9e0a-d2345eb392ef.png)
Ok variations with ROBOTO !

![no-caviardreams](https://cloud.githubusercontent.com/assets/3976174/24247164/e0f94964-0fca-11e7-8c42-78fc7c926854.png)
No variations with CAVIARDREAMS !

**Comment by ScribeRyan** [comment]
Hello again.

Here's the deal. We don't have the ability to preview local fonts the way we do remote ones. So, you won't see a list of variants here with previews.

If your goal is to only select certain variants to be loaded, you can either limit the styles you insert into the fonts directory or limit the variants you choose use in CSS. 

Selecting the variants in the picker only means you are loading the font with support for those variants. The actual use of these variants is determined in the CSS.

**Comment by mariantanase** [comment]
Now is clear. Thank you
