### ISSUE TITLE
Fixed Menu in Helium or Hydrogen?

### ISSUE THREAD

**Issue by axel-rank** [gantry/gantry5#1898]
Can't find an option for fixed Menu/Nav in Hydrogen or Helium? Did I miss some setting?

**Comment by N8Solutions** [comment]
@axel-rank @MarcosRakesh is correct however a much easier solution would be  using one of the 2 Atoms (free) that Inspire Theme has put together that accomplishes this. You can find them here
http://www.inspiretheme.com/gantry5-particles 
Click on **Atoms** at the top to filter the page. Look for  **Headroom.js** and **Fixed Header**.

**Comment by axel-rank** [comment]
Great, thank you for the links. Thought it has already been integrated in gantry core.
@N8Solutions Super!

**Comment by mahagr** [comment]
It is not considered a base feature of Gantry, mostly because of there are multiple different versions of Headroom and it may require some support (mostly styling) from the theme, thus, needs to be supported by the theme itself.

**Comment by bascherz** [comment]
My only issue with these solutions is that on a mobile device, the navigation "hamburger" that appears in the top-left corner doesn't stick with the header. I tried adding multiple classes to the Fixed Header atom, but no joy. Is it possible with this atom? Headroom seems to work the same, just with different effects.
