### ISSUE TITLE
Gantry G-Page-Surround

### ISSUE THREAD

**Issue by brigitte123** [gantry/gantry5#1899]
Hi,
Is there any way I can specify the **#g-page-surround div. or the #g-menu** in order to place different backgrounds to the menu pages. I am currently using Gantry Hydrogen. I used the Helium template to post a background pic and it was successful. Unfortunately, Gantry only has two templates. How can I place a background image to another menu page? 

Thanks in advance!

**Comment by N8Solutions** [comment]
@brigitte123 What CMS are you using, Joomla!, WP, or Grav?
There are several ways you can accomplish what you want. First though, are you trying to add a background picture to a particular section or do you want to have a background picture that covers the whole site? Please be as specific as possible with what it is you are trying to accomplish so others can help you.

**Comment by mahagr** [comment]
Hydrogen is meant to be used by those who want to create their own themes, not for those who just want to slightly customize it. Adding the background image to Hydrogen requires some CSS skills at least, though it shouldn't be too hard to do.
