### ISSUE TITLE
Can't change animation speed in Owl Caroussel

### ISSUE THREAD

**Issue by Peeripapo** [gantry/gantry5#1901]
There should be a configuration to set in the owl Carousel that would allow us to change the speed at which the transition occurs, not only the frequency.

**Comment by Peeripapo** [comment]
Well, found a fix for my own issue.

Added a custom particles folder cloned the owlcaurousel.html.twig and added 

                smartSpeed: 1000,

in the jquery owlcarousel parameters.

**Comment by triloger** [comment]
exxcellllent

**Comment by vineetkashyap1991** [comment]
Thankyou So much..
