### ISSUE TITLE
Top level Menu Items with spaces

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#1902]
When you have a top level menu item, `Main Projects`, clicking on it sets the URL to `Main+Projects` causing it a 404. It should instead be `Main Projects` or `Main%20Projects`.

**Comment by w00fz** [comment]
This isn't actually related to top level items but any item.

**Comment by mahagr** [comment]
Looks like we are using wrong `urlencode()` variant.. Might need to use `rawurlencode()` instead.
