### ISSUE TITLE
grav gantry5 He footer logo not changing....

### ISSUE THREAD

**Issue by 4evermaat** [gantry/gantry5#1903]
Although I uploaded my own logo, the header logo changed, but the footer logo remained `He`.  I double-checked the layout manager panel and it shows that it should be my logo credentials.  But gantry is on its own program apparently :(   See the screenshot for yourself:

![gantry5 grav helium logo still in page](https://cloud.githubusercontent.com/assets/830306/23584156/14c1995c-018b-11e7-82b6-687c1f7f1baa.jpg)

**Comment by JoomFX** [comment]
You have changed your logo under "Particle Defaults" tab, I guess.
The logo in the Header uses the default "Logo" particle settings so your logo in the Header got changed.
But there is another instance of the "Logo" particle in your Layout (see [this screenshot](http://i.imgur.com/W7VBkrI.png), it is from a WP installation but it should be the same in Grav).
Just make sure you modify the second instance of the "Logo" particle in the Layout of all Outlines.

**Comment by 4evermaat** [comment]
@JoomFX that's the thing.  When I viewed that particular footer, it had the same content copied from the particle defaults tab.  In other words, the particle default logo widget is supposed to be default.

![gantry5 grav helium particle default has sitewide logo info](https://cloud.githubusercontent.com/assets/830306/23586622/48f73b92-01cb-11e7-8431-098003426e05.jpg)

When I opened the Footer logo widget (block) options menu, I can see my default info pasted there.

**Comment by JoomFX** [comment]
@4evermaat Have a look at [this video](https://youtu.be/s3yt7dKfll8) that I recorded for you (watch it in Fullscreen and FullHD so you can actually see what I'm writing). It shows everything in details.

**Comment by 4evermaat** [comment]
I checked the video.  I was using my own SVG code in addition to png, so I was ok with my custom svg showing (header was fine, footer was the problem).  I went ahead and **re-copied my svg code** from the `particle defaults` logo to the `layouts` `footer block` in `base outline` global defaults. 

I did not need to change it in `home particles` .  In fact, I was blocked from changing it, as it was already inherited from global defaults.

![gantry5 grav helium home particles inherited from global base outline](https://cloud.githubusercontent.com/assets/830306/23587466/35cab8a0-01df-11e7-82f9-d4281b5ed58f.jpg)

That is actually correct behavior to lock fields that are inherited.  I do not know why gantry ask for default logo info in particles default for logo, and then again separately in the footer, unless it is intentional

So the confusion was that there were multiple logo places that are not necessarily inherited [properly]; so make sure if it is not showing correctly to manually copy again.

And yes, you are also correct that if `SVG` and other image format is selected, SVG will take precedence.

**Comment by mahagr** [comment]
Particle defaults tab defines the "global settings" for all particles and in the base layout you can override those settings per particle instance. Usually you want to use the global defaults for the main logo, but it also allows you to have more than one logo.

So the behavior is correct, but I find that the UI for the global defaults is not optimal and does not nessessary make any sense anymore as Gantry has changed a lot since the tab was originally added.

**Comment by mahagr** [comment]
I'm assuming that the question has been answered.
