### ISSUE TITLE
Grav - Gantry Compiler Issues in Production Mode (Safari Only)

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1907]
See Jakub's comments below

**Comment by newkind** [comment]
Looks like this is a bug in compiler which adds extra spaces to the file in packed mode. Other browsers are smart enough to ignore it, Safari not necessarily.

Dev :
[Dev]!https://monosnap.com/file/Z7sdpG01P3bIUa7Do4dLJKJDGR2AQB.png!

**Comment by mahagr** [comment]
I think this has been fixed in later versions of the compiler.
