### ISSUE TITLE
Customizing Child theme (helium)

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#1908]
Hello freind.
I created a child theme (WP), as written in the manual [http://docs.gantry.org/gantry5/theme-development/create-child-theme-wordpress](url).
After activating theme i cant enter into its settings over Left Menu.
If Actived Helium (default heme)
In Menu i see item **Helium Theme**
If Actived Child helium theme
In Menu i see item **Theme**. After clicking in menu - i see just blank screen.
How Add functional to admin panel to customizing child theme?
Bestr regards

P.S. Sorry for my english ;)

**Comment by newkind** [comment]
Does the front end load on Child theme? Can you enable `WP_Debug` in wp-config.php and also Debug in Gantry 5 settings and see if there are any errors on the admin page?

**Comment by lexa45ru** [comment]
Front end is working - i see dfault setting for helium theme.
WP_Debug and Debug Mode in gantry 5 plugin enabled, but nothing has changed.

**Comment by mahagr** [comment]
Has this issue been solved or is it still an issue?
