### ISSUE TITLE
No "Browser Unsupported" page?

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#191]
There doesn't yet seem to be any "browser unsupported" page implemented? E.g I just tried IE7, IE8, IE9 and just got messed up pages instead of a nice "unsupported browser" page.

**Comment by Omegatcu** [comment]
if you do add such page - please be Mindfull of Translation or create an ability to change what is shown.

We have this problem also with 404 Messages - I would really like that we can put in our own text instead of using the one the theme defines.

**Comment by w00fz** [comment]
We are going to turn this into a Tutorial for docs, in Gantry 5 we do not have an unsupported page anymore but it can be easily created between Particles and Configurations.
Stay tuned for the docs tutorial!
