### ISSUE TITLE
Hydrogen - Login module styling issues

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1911]
Please see pic, needs some love overall.
You need to enable the two factor authentication plugin in order to see the secret key option.

This has been reported internally a long time ago. :)

![g5_hydrogen_login](https://cloud.githubusercontent.com/assets/5719486/23651645/65703c68-0326-11e7-8814-3c225124be8e.jpg)

**Comment by mariantanase** [comment]
Weird...
With Firefox 52 (x64) and Chrome 56, I see a different padding.
![input-padding](https://cloud.githubusercontent.com/assets/3976174/23744719/a471383c-04b5-11e7-9e53-b62722311889.png)

And I've fixed this by adding this lines on my custom.scss
```
input[type="text"] {
    padding: 0.35rem!important;
}
```

**Comment by mariantanase** [comment]
Hi @hexplor ,
After your commit, the styling on Chrome is fixed but on Firefox not quite. Take a look
![firefox-padding](https://cloud.githubusercontent.com/assets/3976174/23752372/54ad01da-04d5-11e7-98d1-c192974bed80.png)

**Comment by hexplor** [comment]
I'm sorry but i can't confirm this. This is ff and chrome (text color is from section): 
![image](https://monosnap.com/file/226tDqDQMeFI0o1QsNv92AspU7YLTY.png)

**Comment by hexplor** [comment]
![windows](https://monosnap.com/file/7H0wXtwbRPg1oIW5NaxHSot7lomCZX.png) 
Fine on windows as well.
