### ISSUE TITLE
Helium and Hydrogen - Frontend calendar icon size

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1914]
Please see pics, the frontend calendar can be seen for example when editing a module from frontend.

![g5_helium_calendaricon](https://cloud.githubusercontent.com/assets/5719486/23652626/f42639d2-0329-11e7-88e5-1078000afc41.jpg)
![g5_hydrogen_calendaricon](https://cloud.githubusercontent.com/assets/5719486/23652627/f4301600-0329-11e7-8306-6d747f44f53b.jpg)

**Comment by kat05** [comment]
Hydrogen is fine in Chrome, in FF it's still a px off.

Helium is not fixed for me.

**Comment by hexplor** [comment]
Ok. Now should be fine.
