### ISSUE TITLE
Joomla menu -  Link Rel Attribute - not passed

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1915]
Joomla 3.5.1
Gantry 5.4.9

While trying to trigger Bootstrap modals from the Joomla Menu I came across this issue.

**Link Rel Attribute** is not rendered in Gantry when set in the Joomla Menu item
![link-rel-attribute](https://cloud.githubusercontent.com/assets/319997/23660929/eca46e9a-0342-11e7-9987-4bb96e526143.jpg)

**As a followup:**    I wanted to add  **data-target="#myModal" data-toggle="modal"** into the Joomla menu item so i could trigger a bootstrap modal from it. Currently I tried adding this into the menu item phpMyadmin but these were not passed either, i suspect because there are not picked up for the same reason as **Link Rel Attribute**

I think there might be an option to add this attributes coming in 3.7 into a joomla menu item. Could you add this feature aswell so that all attributes are picked up not just selected ones.

If not being able to add custom link attributes could be quite useful

**Comment by mahagr** [comment]
This is likely a new feature in Joomla as I cannot remember seeing this when I did the implementation for J! 3.4.

**Comment by erekhshe** [comment]
With Beez3 or other template it works but with gantry 5 helium it does not work!

**Comment by mahagr** [comment]
I'm not seeing an option for `Link Rel Attribute` in Joomla 3.7. Maybe it is coming from a plugin you installed?

**Comment by shoulders** [comment]
I will have a look what is going on and post my results

**Comment by mahagr** [comment]
I'm closing the issue as it is not part of core Joomla. As I said, it's likely a plugin that you installed.
