### ISSUE TITLE
add code and scripts via a joomla module  without gantry wrapping

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1916]
Joomla 3.5.1
Gantry 5.4.9

I have some modal code I want to add to my page but when i add the code to a module position all of the Gantry wrappers surround it making an area of nothing because my code is not for display, nothing is shown except a blank space..

I am sure there are other people who want to add scripts and thing like me that do not need displaying.

The Custom CSS/JS Atom does not do HTML or a combination of them like I have done in my module

The Custom HTML particle would suffer the same effect.

**Suggestion:**
1) a special section that will never add wrappers called: Hidden , similiar to offcanvas where scripts can be added
2) a setting for sections to prevent wrappers being added, a 

**My bodge for now**
Create a section called Hidden and then set its height to 0px; using
````
#g-hidden {
    height: 0px;
}
`````

**Comment by mahagr** [comment]
I've just added support for Atoms to add html into a few locations of the page:

```twig
{% pageblock bottom %}
    My HTML goes here..
{% endpageblock %}
```
You can use one of: `body_top` | `top` | `bottom` | `body_bottom`

**Comment by newkind** [comment]
@ScribeRyan docs docs docs :)

**Comment by mahagr** [comment]
http://docs.gantry.org/gantry5/advanced/css-js-twig#add-html-into-body-in-gantry-546
