### ISSUE TITLE
Helium template - unify section styles

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1920]
Joomla 3.5.1
Gantry 5.4.9

Hi

Helium is used as a template for people to build on rather than be a complete template so with that said in section styles the 'Header Styles' and 'Testimonial Styles' config panels have more options that the rest.

**Full**
![header-style](https://cloud.githubusercontent.com/assets/319997/23797055/ec5cabfa-0595-11e7-8dd7-938774c4ae08.JPG)

**Less**
![intro-style](https://cloud.githubusercontent.com/assets/319997/23797062/f3a922bc-0595-11e7-8abf-735c0df4d3d9.JPG)

Would it be possible to have the rest of the sections to have the same functionality. the individual options do not need to be enables by default, i.e. you do not need to have a background image set on every section etc....

This is my OCD coming out to play.  :)

thanks

**Comment by newkind** [comment]
This is purely by design decision. We didn't want to bloat template and it was supposed to be a starting point showing some of the Gantry 5 possibilities. If you require more options in the sections please feel free to modify the YAML and SCSS files under your `custom` directory.
