### ISSUE TITLE
Joomla - The "Body Only" outline does not seem to work

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1921]
Hey Matias,

As far as I understand, the "Body Only" outline is the one used in the Joomla Print window.
But when I modify the "Body Only" outline nothing changes.

Here, have a look at [this video](https://youtu.be/YdXtvyDZcGY) for more details.

Am I missing something or is this a bug?

**Comment by mahagr** [comment]
Body only is used on all modals in Joomla. There are two modes: html and raw mode (`?type=raw`), where both of them have static layout, which cannot be changed.

I think this was changes at some point as modals were totally broken unless static layout was used.

**Comment by JoomFX** [comment]
Alright, so there is no way to add/remove elements (particles) from the "Body Only" outline?
If so, why don't you just remove it from the G5 Admin? There's no point for it to be there if it is a static outline.
Or am I misunderstanding your comment?

**Comment by pscharfg** [comment]
I found that by overriding /media/gantry5/engines/nucleus/twig/component.html.twig, I can add a logo or anything ele I need to in the print window.   If I do this, will it also change modal windows?  Anything else?

**Comment by mahagr** [comment]
@JoomFX Body only still can be fully configured, just not the layout part of it.

@pscharfg Yes, changes will affect modals and ajax calls, as Joomla uses the layout for multiple different purposes, not just for printing.

The easiest way to change this would likely to change component.php from the theme and add some logic there to detect printing and choosing a different layout if so..

**Comment by LukeDouglas2** [comment]
Or better yet.  Just duplicate the default template and remove all particles except the two on the 'Body Only' layout.  Then you can assign away!
