### ISSUE TITLE
Apply  Button Bug

### ISSUE THREAD

**Issue by ilkayivrendi** [gantry/gantry5#1922]
Hello Guys.
When I am clicking apply button at my collection.list input.number
after I click for apply this code writes at console as error.

```
Uncaught TypeError: n.data(...).text is not a function
at main.js?ver=4.7.3:5
at i (main.js?ver=4.7.3:10)
at constructor.forEach (main.js?ver=4.7.3:12)
at main.js?ver=4.7.3:5
at XMLHttpRequest.l.onreadystatechange (main.js?ver=4.7.3:10)
(anonymous) @ main.js?ver=4.7.3:5
i @ main.js?ver=4.7.3:10
forEach @ main.js?ver=4.7.3:12
(anonymous) @ main.js?ver=4.7.3:5
l.onreadystatechange @ main.js?ver=4.7.3:10
```
Do anyone know why this fired ?
Values holdes the numbers. So in my interface I can see it. But at admin side I have to click cancel button for modal to dissapear

**Comment by mahagr** [comment]
@newkind Can you test this out?

**Comment by w00fz** [comment]
I cannot reproduce this issue.

**Comment by newkind** [comment]
@ilkayivrendi do you still have this issue? Can you post your YAML so I could test it?

**Comment by mahagr** [comment]
Closing as we cannot reproduce the issue and there's not been any activity on it.
