### ISSUE TITLE
[question] MultiLang site on grav

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#1923]
Hello.
I have simple question.
How create simple multilingual site based on gantry5 template, without creating pages, only gantry framework and particles.
What method of translate **default particles**, like "_HorizontalMenu_", "_Content Tabs_", "_Custom HTML_" etc, or **user created particles**, example, jquery carousel adaped to gantry particle (yaml and twig files).
Thanks, and best regards.

P.S. sorry for my english.

**Comment by mahagr** [comment]
Do you mean translating the admin or the site?

**Comment by lexa45ru** [comment]
I need translate frontend, i.e. site.
In this moment i use method multisite for eng/rus content, But if grav allows you to make multilingual content, then it would be easier.
Thanks.

**Comment by mahagr** [comment]
You can translate frontend just like you would without Gantry. Read Grav docs on how to do it.
