### ISSUE TITLE
Nested collection list multi-item edit not functioning.

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1924]
If you try to edit a 2nd-level collection list which has multiple items in it.

Use case:

1st level collection list has 4 items in it.
You open the collection list in the multi-item edit mode.
In each element, you add another collection list, each with between 5 and 7 items in it.
You open the 2nd level collection list in multi-edit mode and you get a simple item (which corresponds to nothing in the 2nd level collection list.

Workaround to edit multiple items at the 2nd level, Open each first level elect separately, then the 2nd-level will open in multi-item edit mode.

This seems like a regression as I think this is similar to #1877 which had been fixed before but is now broken again.

(e.g. using the RocketTheme Pricing Table)

**Comment by alisamii** [comment]
Any update on this issue?

**Comment by mahagr** [comment]
@alisamii Please test the bug fix, also with the containers. It was really hard to track down and I'm not 100% sure if I didn't break anything else.

**Comment by mahagr** [comment]
Ok, it does break nested sets with containers...

**Comment by mahagr** [comment]
Should be fixed with `container.tabs`.
