### ISSUE TITLE
Newly-created outlines give custom.scss twig related error. 

### ISSUE THREAD

**Issue by tushantin** [gantry/gantry5#1926]
I'm running the latest Wordpress, Gantry and Helium v5.4.10. 

I thought I'd update my website by recreating a theme with Gantry (this is the first time I'm working with a framework). But upon creating a new outline, whichever page I'm applying it to, once I preview that page in a new tab it gives me the following error. 

` Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("CSS Compilation on file 'custom.scss' failed on error: Undefined mixin transition: line: 17").`

` Open: /customers/e/b/4/(website)/httpd.www/wp-content/plugins/gantry5/engines/nucleus/views/partials/page.html.twig`

```
 {% extends "@nucleus/page.html.twig" %}
     
    {% block page_head -%}
        {% if page_head %}
            {{ page_head|raw }}
        {% else %}
            {{ parent() }}
        {% endif %}
    {%- endblock %}
     
    {% block page_footer %}
        {% do gantry.platform.finalize() %}
        {{ wp_footer|raw }}
    {% endblock %}
```

The problem seems to go away once I either unassign that outline from that page, or simply delete that outline altogether, but I have no idea on how to even fix this issue (I'm not a programmer, so I have no idea what this error means). 

I'd really appreciate the help. 

EDIT: I also got this error when saving a style in a new outline, even if it wasn't assigned anywhere. 

```
} catch (\Exception $e) {
            // Another process has locked the file; we will check this in a bit.
        }
 
        if ($file->locked() === false) {
            // File was already locked by another process, lets avoid compiling the same file twice.
            return false;
        }
 
        // Set the lookup paths.
        $this->compiler->setBasePath($path);
        $this->compiler->setImportPaths([[$this, 'findImport']]);
 
        // Run the compiler.
        $this->compiler->setVariables($this->getVariables());
        $scss = '@import "' . $in . '.scss"';
        try {
            $css = $this->compiler->compile($scss);
        } catch (CompilerException $e) {
            throw new \RuntimeException("CSS Compilation on file '{$in}.scss' failed on error: {$e->getMessage()}", 500, $e);
        }
        if (strpos($css, $scss) === 0) {
            $css = '/* ' . $scss . ' */';
        }
 
        $warnings = trim(ob_get_clean());
        if ($warnings) {
            $this->warnings[$in] = explode("\n", $warnings);
        }
 
        if (!$this->production) {
            $warning = <<<WARN
/* GANTRY5 DEVELOPMENT MODE ENABLED.
 
   WARNING: This file is automatically generated by Gantry5. Any modifications to this file will be lost!
 
   For more information on modifying CSS, please read:
 
   http://docs.gantry.org/gantry5/configure/styles
   http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
```

**Comment by JoomFX** [comment]
Make sure you have the following line at the very top of your `custom.scss` file:

```
@import "dependencies";
```

For more details, have a look at the [Adding a Custom Style Sheet](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) section in the docs.

**Comment by tushantin** [comment]
It works! Thank you. 

Yeah, I binged through the entire documentation in a day and also tried to get the sticky header to work via InspireTheme's particles. I actually thought "dependencies" was a placeholder for a given "_something" scss files. Whoops...
