### ISSUE TITLE
Helium > Testimonial section Background color picker doesn't change color

### ISSUE THREAD

**Issue by ScribeRyan** [gantry/gantry5#1928]
Looks like the color overlay in the testimonial section of the Helium theme is set by the theme's accent rather than the color field in that section's settings.

**Comment by vengatowen** [comment]
Hi, issue is somewhat related to this. 

I'm using RT theme Sienna wordpress using gantry frame.  I would like to have background img for a particular sections. how to do this? 

I can see background color pickers, but not as image.  How to add this.?

**Comment by mahagr** [comment]
@vengatowen Please use Rockettheme support forums for their paid themes.

**Comment by vengatowen** [comment]
Thanks.  @mahagr  and thanks for reminding this. I found a way myself spending time on it. 

For who those needed to change this, go to sections CSC file
Path:  **".../Themefolder/Custom/Complied-CSS/Particle-name"**

Where particle name as goes depends on your file name you wanted to edit. 

Just remove the `background: #fff;`   and insert  `background:URL("imagepath");`


Hope this helps others.  And thanks for your awesome framework.
