### ISSUE TITLE
Atom is not working!

### ISSUE THREAD

**Issue by alaahariri** [gantry/gantry5#1929]
Hello, 

The custom CSS files that I am linking in Atom are not loading on the site. I was working well before until updating to the latest version.

**Comment by igor-gp** [comment]
Not sure if its related, but i notice the Google Analytics atom is not working for us on a client site, i have tried as an atom or custom css/js or in the body code and none of it loads Google Analytics, really strange.

**Comment by mahagr** [comment]
Please try to revert to an older version if it fixes the issue. There have been a few changes on this after Gantry 5.4.3.

**Comment by alaahariri** [comment]
I linked the required CSS files manually in Page Settings (in the Header section). Thank you!

**Comment by mahagr** [comment]
I just tested adding both Google Analytics and CSS file from the atom and both works for me. Used base outline. Please make sure you're not overriding atoms in specific outlines.

**Comment by mahagr** [comment]
@alaahariri @igor-gp Is this still an issue?

**Comment by alaahariri** [comment]
Unfortunately, the issue in my site still exists. CSS files in Atoms are not loading on the pages. I am using the Base Outline Atom section and all other pages are inheriting from it. But CSS files are not loading on any page. 

I tried to use the Atoms section directly on the pages (not inheritance method), not working either.

**Comment by mahagr** [comment]
@alaahariri Which theme and CMS you're on? Have you modified/overridden any of the twig files?

**Comment by alaahariri** [comment]
@mahagr I am using WordPress. I did play around with twig files and other files during the development of the website. Anyway, I will try to figure it out. Thank you very much.

**Comment by mahagr** [comment]
Make sure you've not modified page and page_head files.
