### ISSUE TITLE
p margins

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#193]
@kevlardev many people use bootstrap alerts and other bootstrap components, 'p' margin top and bottom will get too high values, like 24 px on hydrogen. 

A custom rule to limit this may be added, something like:
```
.alert p {
margin-top: 10px;
margin-bottom: 10px;
}
```

Actually this may happen not just to p, is more a custom work and should be styled individually but... .:D

**Comment by w00fz** [comment]
This is really something that's driven by the theme, I dont think we want to change it for Hydrogen. Right now we are using padding in a very consistent way across the whole theme, if we change that padding it would look silly.
