### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1935]
I am facing 2 issues:

1. I had set my breakpoints in base outline config page. Those are inherited by all other outlines. Initially it took it some time after clearing caches, recompiling etc a few times till it started using my custom breakpoints values. During my first attempt I noticed that my saved breakpoints were reverted back to the default values in config and when I re-typed my custom ones cleared caches etc it finally worked. But today and out of sudden - all my media queries where I am using `@include breakpoint ` have reverted back to the default values. Same time my custom configured values are still in both the backend and in the custom config layout files. 
I am trying clearing caches, recompiling and everything I can think but all media queries are returning the default g5 values.

2. It looks like the `mobile-only` breakpoint isn't the typically max 47.938 rem - or whatever the this set to serve mobile-only devices - it actually gets triggered at the same time with the `no-desktop` breakpoint. 

So while I am trying to create styles for tablet/mobiles, the `mobile-only` rules appears when on tablet size and are overriding any styles I am setting on the `tablet-range`.

**Comment by joomlabeat** [comment]
i realized that there were mixed metrics in the breakpoints configuration - both rem and px - which seemed to cause those breakpoint issues.

**Comment by joomlabeat** [comment]
actually again - I am having issues with the breakpoints. I set all breakpoints to certain px - but in the front-end media queries I am not getting the exact values - so instead of the 1025px breakpoint the media query value becomes 1019.048px in front-end.
Why is this happening?

**Comment by mahagr** [comment]
Can you just use REM instead of px.. The conversion goes 16px=1rem. So the calculation in the scss file reduces 1px from the previous size.

**Comment by newkind** [comment]
Mark from our forums :

```
For those of you thinking "what are those weird rem values"... 0.062rem = 1px. As ranges can't overlap they need to be 1px different - hence why the typical rem values have three decimal places :)
```

**Comment by mahagr** [comment]
I'm assuming that the issue got resolved.
