### ISSUE TITLE
Content markdown gets autoescaped.

### ISSUE THREAD

**Issue by smxmn** [gantry/gantry5#1936]
I was trying to add custom html in the editor via the grav admin pages.
I used the owlcarousel shortcode plugin to insert pictures, but it requires to format the list of images in html. The shortcode gets evaluated, but the html list is shown as an escaped paragraph.

I'm using the default template, and my current markdown gets correctly evaluated using Antimatter theme, but not in Helium. I am trying to make a custom template to implement the carousel, but I think I was using the shortcodes and the grav page editor as intended.

Where can I tell gantry to use the content as raw?

**Comment by mahagr** [comment]
Gantry forces autoescaping on, so the best way is to fix the template file from shortcode plugin to use `|raw` filter on the html output.

**Comment by smxmn** [comment]
Thank you very much.
The 3rd line of plugin partial template 'owl-carousel.html.twig' can be modified like this:
`{{ owl_items|regex_replace('(^\n?<p>|<\/p>$)','') }}`
to
`{{ owl_items|regex_replace('(^\n?<p>|<\/p>$)','')|raw }}`

The generated layout of the carousel is a bit messy, but it works!

**Comment by mahagr** [comment]
@smxmn Can you report this issue with the solution to the Grav plugin, please? :)

**Comment by smxmn** [comment]
Yes, of course.
Also I found, that Hydrogen does not mess up CSS button sizes and locations like Helium.
It renders perfectly.
Do you have a similar tip where should I look for a solution? Giving all plugin stylesheets important seems hacky.

**Comment by mahagr** [comment]
Helium may have some extra styling in it, @hexplor ?

**Comment by newkind** [comment]
Nope, shouldn't have any extra stuff in there afaik.

**Comment by smxmn** [comment]
Removed lines 123-125 from `helium.scss` inside Heliums `scss` folder.

```
// Owl Carousel
@import "helium/particles/owlcarousel";
```
Now it behaves just like in Hydrogen.

**Comment by newkind** [comment]
What exactly is wrong with Helium buttons behavior? They are different, because it's a different theme.
