### ISSUE TITLE
Custom PHP function in TWIG

### ISSUE THREAD

**Issue by WebWikom** [gantry/gantry5#1937]
Hi,

I've just wrote a php function which allow me to retrieve images from a specific folder, generate a thumbnail and classify them under specific condition.
However, i dont know where to put my function in order to use it from ANY twig particle.

Thanks.

**Comment by mahagr** [comment]
There are two options how to include the function. First way is to add the function into Gantry CI, though in that case you should make an class/object, which contains the function calls you need (you can put this into the theme or a plugin):

```php
$gantry = Gantry/Framework/Gantry::instance();
$gantry['my_images'] = function () {
    return new MyImages();
};
```

Second way is to create a twig function, but it is a bit more involved than the above one.

**Comment by WebWikom** [comment]
Ah i tried to do it by including the function, however i didn't make it an object, that's why it wasn't working !
Thanks, will try it like that !

**Comment by mahagr** [comment]
You can also add functions, but those need to be wrapped as otherwise it gets only be run at once.

I'm assuming I have solved your issue.

**Comment by Mineslu** [comment]
Hello,
mmm  What is Gantry CI?
Thank

**Comment by mahagr** [comment]
CI = Continous Integration, meaning internal builds which get updated right after the change has been made.
