### ISSUE TITLE
Width of the site gets narrower when using Bootstrap CSS

### ISSUE THREAD

**Issue by pedrohsouza1** [gantry/gantry5#1938]
I'm trying to implement CSS and JS of Bootstrap on my site. The problem is, when I install it, using "Global page settings > assets" it makes the entire content fits on a narrower width as in the picture. Is there something I can do to avoid it? 
![bootstrap css](https://cloud.githubusercontent.com/assets/10166321/24153108/4fc9425e-0e2c-11e7-82d3-93c6eaf32320.jpg)

**Comment by mahagr** [comment]
Which CMS you're using?

**Comment by pedrohsouza1** [comment]
Hello, Matias, I'm using Wordpress 4.5.

**Comment by mahagr** [comment]
In Joomla we have custom overrides for Bootstrap, which is why CSS is not included in WP either.

**Comment by newkind** [comment]
Just gonna leave a message that it's most likely the same thing as here https://github.com/gantry/gantry5/issues/1998#issuecomment-303300626
