### ISSUE TITLE
Icon Only Menu Items, OffCanvas Toggle Hides

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#1939]
When using a Icon Only Menu:

![screen shot 2017-03-21 at 1 33 23 pm](https://cloud.githubusercontent.com/assets/5002814/24164259/18af1f32-0e3b-11e7-9f9a-b9c16dd507f9.jpg)

![screen shot 2017-03-21 at 1 34 59 pm](https://cloud.githubusercontent.com/assets/5002814/24164301/32a9545c-0e3b-11e7-95f7-83f7cb1cb12c.jpg)

The Offcanvas Toggle Hides

![screen shot 2017-03-21 at 1 33 44 pm](https://cloud.githubusercontent.com/assets/5002814/24164282/23024c52-0e3b-11e7-9558-aca15bd9b4b2.jpg)

**Comment by mahagr** [comment]
I am able to reproduce the issue.
