### ISSUE TITLE
Remove Redundant Links

### ISSUE THREAD

**Issue by slava05** [gantry/gantry5#1940]
Hello.
The problem of Redundant (cyclic) links in the menu.
For WordPress there is a plugin "Remove Redundant Links".
What you need to do for Joomla with Gantry5?
Help me please.

**Comment by mahagr** [comment]
I'm not sure what you mean. Cyclic links?

**Comment by slava05** [comment]
Cyclic Link This page refers to itself. For example, on the home page of the site in the menu there is an active link to the home page (to yourself). It's very bad for search engine optimization.

**Comment by mahagr** [comment]
There may be plugins for this, not sure. I've never thought that a few links pointing to the page itself are a bad thing -- those links are very easy to detect and cause no harm.

**Comment by slava05** [comment]
There are no plugins to solve this problem for joomla.

**Comment by mahagr** [comment]
IMHO not really a Gantry issue, closing.
