### ISSUE TITLE
Helium brakes with CSS Pipeline

### ISSUE THREAD

**Issue by simoncramer** [gantry/gantry5#1941]
When I enable the CSS Pipeline in GravCMS the Helium theme is not displayed correctly. Most of the CSS is missing in the generated css file.

**Comment by fenichelar** [comment]
I have the same issue. Most of the CSS is just gone.

**Comment by lexa45ru** [comment]
I join the problem

**Comment by SamAleev** [comment]
The problem occurs when changing the base outline. Return the default settings and disable assets timestamp in the gantry plugin settings. It helped me

проблема возникает при изменении base outline. верните стандартные настройки и отключите assets timestamp в настройках gantry plugin. мне это помогло.

**Comment by mahagr** [comment]
I'm able to reproduce the issue. Fixing it now.
