### ISSUE TITLE
Templates not really responsive

### ISSUE THREAD

**Issue by brugino** [gantry/gantry5#1948]
There are problems with some devices, such as tablet 10" goes off the screen, templates

**Comment by mahagr** [comment]
Older tablets (for example Android 4 ones) do not support flexbox in CSS, so Gantry themes will not be responsive because of this. Also if your content inside the theme is not responsive, the layout cannot fit into the given area and goes off-screen.

**Comment by mahagr** [comment]
Older tablets and phones (including all Android 4 ones) do not support flexbox in CSS which is what Gantry 5 uses to become responsive. Also if your page content is not responsive it will overflow outside of the screen.

In the first case you could use Chrome browser as latest version of it is available for most tablets. For the later issue, there's really no other way than to make your page content responsive as well.

**Comment by brugino** [comment]
Thanks mahagr!
I confirm what you said above.
I tested with chrome and firefox, works great with both 👍
