### ISSUE TITLE
Empty space and useless scrollbar when is low content on page

### ISSUE THREAD

**Issue by MarcosRakesh** [gantry/gantry5#1949]
>// Modify the default Admin Bar margins to render properly in the mobile mode
```html {margin-top: 32px !important;}```

On wordpress, when is low content the 32px from admin bar margins make the layout scroll and have empty space when shouldn't because there is not so much content. This is breaking the error/offline layout. The scroll and empty space is on both desktop and mobile.

**Comment by newkind** [comment]
This isn't something that I'd say is a bug. If the Admin bar is enabled - the code needs to be there. If it bugs you that these two pages have the scroll bar - either add more content to them or modify the section heights. Removing CSS for admin bar for these pages is not a proper solution.
