### ISSUE TITLE
ReferenceError: GANTRY_AJAX_URL is not defined

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#195]
with the upcoming template's rocketlauncher, latest gantry rc dev1 build and the template-demo installed, we're getting the following error randomly in the admin.

ReferenceError: GANTRY_AJAX_URL is not defined

![g5_gantry_ajax_url](https://cloud.githubusercontent.com/assets/5719486/7517882/3ca37802-f49d-11e4-9a60-8f7c84227a1c.jpg)

arifin and matias saw it too. :)

**Comment by w00fz** [comment]
Ok this should be sorted now please keep an eye on it.
