### ISSUE TITLE
Joomla backend problem in Safari 10.1

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#1950]
I have a problem with the Content pro particle (Inspire Theme developer): if I try to change the order of items (for instance moving the last item of the list to the top) the page is reloaded because of a not better identified problem  and my changes aren't saved. I was working with Safari 10.1 and Joomla/Gantry 5 updated to the last available version. Even if I cleaned the cache of Joomla, of Gantry and of the browser the problem persisted.
I switched to Chrome and hadn't any trouble at all in putting the newly added item at the top of the list.
It looked like a JS problem, I have JCH optimize installed, but even if I totally disabled it the problem wasn't solved..

**Comment by JoomFX** [comment]
Hey guys,

I asked Elisabetta to open this issue.
It seems to be an issue with G5 on Safari 10.1 when you try to re-order the `collection.list` items.
This seems to be an issue in Safari 10.1 only, the re-ordering works fine in Chrome, Firefox and IE.

@beamaria Elisabetta, would you please give us some more details please?
Where are you trying to re-order the items? I mean, is it in a "Gantry 5 Particle" module in the Module Manager, is it under the "Layout" tab in G5 Admin or is it under the "Particle Defaults" tab in the G5 Admin?
Also, could you please do the same test with the "Social" particle which is a core G5 particle? Just create some items in the "Social" particle and try to re-order them in Safari 10.1

**Comment by beamaria** [comment]
More details: the re-order trouble  is in a Gantry5 particle(Content Pro) in Module Manager, and it happens also in Socials particle. I tried this with these settings:

Joomla cache: "conservative" and “off"
JCH Optimize: enabled or disabled, when enabled also cleaning the cache
Joomla/browser and Gantry cache all cleaned
Session time: 15 and 30



Elisabetta

**Comment by beamaria** [comment]
Hi again, any solution to the problem? I suppose it could be related to the update of Safari 2017-0001 of El Capitan and Safari, which I did on 29 March. I could attach the log of error displayed , if it can help to sort out the issue..
Thanks!

**Comment by mahagr** [comment]
Unfortunately, I don't have Safari browser. Passing this one to @w00fz.

**Comment by beamaria** [comment]
Ok, thanks Mathias!

Elisabetta

**Comment by beamaria** [comment]
UPDATE: the bug is NOTin Gantry 5, but in the latest update to Safari 10.1; the workaround is the following one:
1) change the Display-->Color settings, switching from" IMac default" to sRGB IEC61966-2.1 
2) lower the display brightness of a couple of notches to better match this colour profile with the default one
Automagically you can sort your list and drag and drop without any problem :) 
I think Djamil can close this issue
