### ISSUE TITLE
SplFileInfo

### ISSUE THREAD

**Issue by pedgsilva** [gantry/gantry5#1951]
My gantry theme is giving this error : SplFileInfo::isFile(): open_basedir restriction in effect. File(gantry-themes:/\App_Data) is not within the allowed path(s): (C:/Inetpub/vhosts/iafe.pt\;C:\Windows\Temp\)

I've already reinstaled the framewok, and nothing.

if i try to entry the gantry themes in the control panel it give this error :
Session
joomla	TzoyNDoiSm9vbWxhXFJlZ2lzdHJ5XFJlZ2lzdHJ5IjozOntzOjc6IgAqAGRhdGEiO086ODoic3RkQ2xhc3MiOjE6e3M6OToiX19kZWZhdWx0IjtPOjg6InN0ZENsYXNzIjo0OntzOjc6InNlc3Npb24iO086ODoic3RkQ2xhc3MiOjM6e3M6NzoiY291bnRlciI7aToyMDtzOjU6InRpbWVyIjtPOjg6InN0ZENsYXNzIjozOntzOjU6InN0YXJ0IjtpOjE0OTEyMzg4NDY7czo0OiJsYXN0IjtpOjE0OTEyMzk5MDI7czozOiJub3ciO2k6MTQ5MTIzOTkwNTt9czo1OiJ0b2tlbiI7czozMjoiV1BaWGM3UEQ1cDE4SzJJUlR3dXNoV3l1UjhySVQxMFgiO31zOjg6InJlZ2lzdHJ5IjtPOjI0OiJKb29tbGFcUmVnaXN0cnlcUmVnaXN0cnkiOjM6e3M6NzoiACoAZGF0YSI7Tzo4OiJzdGRDbGFzcyI6Mjp7czoxMzoiY29tX2luc3RhbGxlciI7Tzo4OiJzdGRDbGFzcyI6Mzp7czo3OiJtZXNzYWdlIjtzOjA6IiI7czoxNzoiZXh0ZW5zaW9uX21lc3NhZ2UiO3M6MDoiIjtzOjEyOiJyZWRpcmVjdF91cmwiO047fXM6MTA6ImNvbV9nYW50cnkiO086ODoic3RkQ2xhc3MiOjE6e3M6NDoiZWRpdCI7Tzo4OiJzdGRDbGFzcyI6MTp7czo4OiJ0ZW1wbGF0ZSI7Tzo4OiJzdGRDbGFzcyI6Mjp7czoyOiJpZCI7YTowOnt9czo0OiJkYXRhIjtOO319fX1zOjE0OiIAKgBpbml0aWFsaXplZCI7YjoxO3M6OToic2VwYXJhdG9yIjtzOjE6Ii4iO31zOjQ6InVzZXIiO086NToiSlVzZXIiOjE6e3M6MjoiaWQiO3M6MjoiNjIiO31zOjExOiJhcHBsaWNhdGlvbiI7Tzo4OiJzdGRDbGFzcyI6MTp7czo1OiJxdWV1ZSI7Tjt9fX1zOjE0OiIAKgBpbml0aWFsaXplZCI7YjowO3M6OToic2VwYXJhdG9yIjtzOjE6Ii4iO30=
Server/Request Data
_FCGI_X_PIPE_	\\.\pipe\IISFCGI-5a823d3e-2122-4113-8c42-1d8a60e83528
ALLUSERSPROFILE	C:\ProgramData
APPDATA	C:\Windows\system32\config\systemprofile\AppData\Roaming
APP_POOL_CONFIG	C:\inetpub\temp\apppools\plesk(default)(4.0)(pool)\plesk(default)(4.0)(pool).config
APP_POOL_ID	plesk(default)(4.0)(pool)
CommonProgramFiles	C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)	C:\Program Files (x86)\Common Files
CommonProgramW6432	C:\Program Files\Common Files
COMPUTERNAME	IBERWEB20A
ComSpec	C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK	NO
LOCALAPPDATA	C:\Windows\system32\config\systemprofile\AppData\Local
MAILENABLE_PATH	C:\PROGRA~2\PARALL~1\Plesk\MAILSE~1\MAILEN~1
NUMBER_OF_PROCESSORS	12
OS	Windows_NT
Path	C:\PROGRA~2\PARALL~1\Plesk\MAILSE~1\MAILEN~1\BIN;C:\Program Files (x86)\Parallels\Plesk\Additional\Python\Scripts;C:\Program Files (x86)\Parallels\Plesk\Additional\Python\;C:\Program Files (x86)\Parallels\Plesk\Mail Servers\Mail Enable\BIN;C:\PROGRA~2\PARALL~1\Plesk\ADDITI~1\Perl\site\bin;C:\PROGRA~2\PARALL~1\Plesk\ADDITI~1\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Parallels\Plesk\Mail Servers\Mail Enable\BIN64;C:\PROGRA~2\PARALL~1\Plesk\MAILSE~1\MAILEN~1\BIN64;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Parallels\Plesk\ctl;
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.py;.pyw
plesk_bin	C:\Program Files (x86)\Parallels\Plesk\admin\bin
plesk_bin64	C:\Program Files (x86)\Parallels\Plesk\admin\bin64
plesk_cli	C:\Program Files (x86)\Parallels\Plesk\bin
plesk_dir	C:\Program Files (x86)\Parallels\Plesk\
plesk_vhosts	C:\Inetpub\vhosts\
PROCESSOR_ARCHITECTURE	x86
PROCESSOR_ARCHITEW6432	AMD64
PROCESSOR_IDENTIFIER	Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL	6
PROCESSOR_REVISION	2d07
ProgramData	C:\ProgramData
ProgramFiles	C:\Program Files (x86)
ProgramFiles(x86)	C:\Program Files (x86)
ProgramW6432	C:\Program Files
PSModulePath	C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC	C:\Users\Public
SystemDrive	C:
SystemRoot	C:\Windows
TEMP	C:\Windows\TEMP
TMP	C:\Windows\TEMP
USERDOMAIN	WORKGROUP
USERNAME	IBERWEB20A$
USERPROFILE	C:\Windows\system32\config\systemprofile
VS100COMNTOOLS	C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
windir	C:\Windows
ORIG_PATH_INFO	/administrator/index.php
URL	/administrator/index.php
SERVER_SOFTWARE	Microsoft-IIS/8.5
SERVER_PROTOCOL	HTTP/1.1
SERVER_PORT_SECURE	0
SERVER_PORT	80
SERVER_NAME	www.iafe.pt
SCRIPT_NAME	/administrator/index.php
SCRIPT_FILENAME	C:\Inetpub\vhosts\iafe.pt\httpdocs\administrator\index.php
REQUEST_URI	/administrator/index.php?option=com_gantry5
REQUEST_METHOD	GET
REMOTE_USER	
REMOTE_PORT	38248
REMOTE_HOST	195.245.147.102
REMOTE_ADDR	195.245.147.102
QUERY_STRING	option=com_gantry5
PATH_TRANSLATED	C:\Inetpub\vhosts\iafe.pt\httpdocs\administrator\index.php
LOGON_USER	
LOCAL_ADDR	188.93.231.4
INSTANCE_META_PATH	/LM/W3SVC/214
INSTANCE_NAME	IAFE.PT
INSTANCE_ID	214
HTTPS_SERVER_SUBJECT	
HTTPS_SERVER_ISSUER	
HTTPS_SECRETKEYSIZE	
HTTPS_KEYSIZE	
HTTPS	off
GATEWAY_INTERFACE	CGI/1.1
DOCUMENT_ROOT	C:\Inetpub\vhosts\iafe.pt\httpdocs
CONTENT_TYPE	
CONTENT_LENGTH	0
CERT_SUBJECT	
CERT_SERIALNUMBER	
CERT_ISSUER	
CERT_FLAGS	
CERT_COOKIE	
AUTH_USER	
AUTH_PASSWORD	
AUTH_TYPE	
APPL_PHYSICAL_PATH	C:\Inetpub\vhosts\iafe.pt\httpdocs\administrator\
APPL_MD_PATH	/LM/W3SVC/214/ROOT/administrator
IIS_UrlRewriteModule	7.1.1952.0
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.41 Safari/537.36
HTTP_REFERER	http://www.iafe.pt/administrator/
HTTP_HOST	www.iafe.pt
HTTP_COOKIE	wf_imgmanager_dir=imgiafe; e95b499cd7f5e9933075fa4a6ee345bf=ngtv4q3vvq0qjgmp4ao3fruih6; 9578e4604423860d44d4adcda32bd3df=gsqvk34vva6bshng9vab3kitv1
HTTP_ACCEPT_LANGUAGE	pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2,zh-CN;q=0.2,zh;q=0.2
HTTP_ACCEPT_ENCODING	gzip, deflate, sdch
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_CONNECTION	keep-alive
FCGI_ROLE	RESPONDER
PHP_SELF	/administrator/index.php
REQUEST_TIME_FLOAT	1491239982.1016
REQUEST_TIME	1491239982
Environment Variables empty
Registered Handlers

**Comment by mahagr** [comment]
Can you enable debug and check where the error happens? Or just send private message to me in Gitter chat and I can take a look on this.

**Comment by pedgsilva** [comment]
Thank you for the response, i've solved the error, it was php.ini, the tmp variable was wrong.

Thank you.
