### ISSUE TITLE
How can i use {% include 'my_custom.html.twig' %} in Particles or Atoms?

### ISSUE THREAD

**Issue by MaksymJ** [gantry/gantry5#1952]
Hi Folks,

How can i use `{% include 'my_custom.html.twig' %}` in Particles or Atoms?

for example, i have particle:
```
theme/particles/my_new_logo.html.twig
theme/particles/my_new_logo.yaml
```
in same directory i have created another twig file named **my_custom.html.twig** (in that twig file is simple HTML code) .. so i want to import that file in particle ... this do not work (**my_new_logo.html.twig** source code):
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
	{% include 'my_custom.html.twig' %}
{% endblock %}
```

do i need to have different **name** for **my_custom.html.twig**?
or do i need to apply special code also for that file ... i have there simple HTML ...

thank you very much,
Maksym

**Comment by mahagr** [comment]
Include always works by using relative path from the templates folder. Additionally there are a few namespaces like `@particles/filename.html.twig`.

**Comment by mahagr** [comment]
I'm assuming that the question got answered.
