### ISSUE TITLE
Can not access gantry5.4.11 with Grav admin panel 1.3.1 

### ISSUE THREAD

**Issue by pinohans** [gantry/gantry5#1953]

**Comment by pinohans** [comment]
There is no tab "gantry" in the sidebar. :(

**Comment by nattanyz** [comment]
hi there, I'm new here. I'm facing the same issue - gantry does not appear in the sidebar of my grav admin panel. does anyone know what the problem is? :(

**Comment by kat05** [comment]
Hi, have you also installed a Gantry 5 theme?
