### ISSUE TITLE
Loading jQuery 3 in head page_head.html.twig

### ISSUE THREAD

**Issue by drjjw** [gantry/gantry5#1956]
Hello,

On one particular Joomla page I need to include jQuery3. If I load it using an Atom or in the <head> configuration in the template admin, it still loads after boodtrap.js which creates problems. The only way I could get it to load before was to place it before the entire block of:

`{% block head_application -%}`

in 

media/gantry5/engines/nucleus/templates/page_head.html.twig

So it looks like:

```
<script src="//code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
    {% block head_application -%}
        
        {{ gantry.styles('head')|join("\n")|raw }}
        
        {{ gantry.scripts('head')|join("\n")|raw }}
    {%- endblock %}
```

But this loads it before the meta tags and style sheets.

Is there a way I can load jQuery3 before bootstrap.js preferably on just one page rather than globally on the site?

Jordan

**Comment by mahagr** [comment]
Hmm, this is a tough one as Joomla has special logic to load jQuery and Bootstrap. This is why it doesn't work from Gantry configuration and you need to change the file you mentioned.

Try to put the script just before `{{ gantry.scripts('head')|join("\n")|raw }}` and it might work. Just be sure that jQuery isn't loaded twice (it likely is).

**Comment by mahagr** [comment]
I'm assuming that this issue has been solved.
