### ISSUE TITLE
Tab disappears in MS Edge

### ISSUE THREAD

**Issue by humblehumanbeing** [gantry/gantry5#1957]
Main Gantry tab disappears in Microsoft Edge 40.15063.0.0 after selecting any of the tabs

<img width="965" alt="sketch" src="https://cloud.githubusercontent.com/assets/1849490/24831374/5815cb92-1c66-11e7-88fa-59262d019a03.png">
<img width="963" alt="sketch-1" src="https://cloud.githubusercontent.com/assets/1849490/24831377/5a28f6ac-1c66-11e7-8add-fd4944c0f1f9.png">

**Comment by 3cellhosting** [comment]
Problem with Edge and missing tabs is confirmed

<section id="navbar" aria-hidden="false" style="top: -50000px; width: auto; height: 53px; overflow: inherit; visibility: visible; position: relative;">
 
If I remove position:relative; it displays as expected.

**Comment by newkind** [comment]
Issue confirmed. Removing position relative is not a solution in this case. Besides this styling comes from the JS and I think that something with detection got messed up. @w00fz something for you :)

**Comment by mahagr** [comment]
Edge is old news, MS already replaced this product with a better one.
