### ISSUE TITLE
Question: Gantry function to call a layout and return resulting HTML

### ISSUE THREAD

**Issue by AmibeWebsites** [gantry/gantry5#1958]
What I'd like to do is fetch the resulting HTML when a layout (Body only) is applied, called from a PHP function in WordPress.

What Gantry function do I call and what do I need to pass it?

It doesn't require any context other than whatever's available with get_query_var, which is used by the particle in the layout applied.

Does this make sense. I can explain further if needed.

**Comment by newkind** [comment]
So you want to get query of the overbuffered html before it gets rendered?

**Comment by mahagr** [comment]
Normal WP and Timber filters should work, look if any of those meets your needs.

**Comment by AmibeWebsites** [comment]
I'll try explain a bit more... my idea is to duplicate the Body Only outline and add 'my version of' the content_array particle. This outline is not assigned to anything.

Then, I have a separate php script that I use to generate an RSS feed and want the output of  'my version of' the content_array particle, as set up in the duplicated Body Only outline, to return the XML/HTML that will populate the RSS feed.

What I'm hoping is that there's a Gantry method I can call, passing the outline required as a parameter, that will generate the XML/HTML.

**Comment by newkind** [comment]
so you basically want gantry to render html layout/outline only for the rss feed ?

**Comment by AmibeWebsites** [comment]
Yes, in this instance, although I'm also imagining using it to return HTML on an AJAX call that can then be dynamically rendered into an already loaded page.

**Comment by newkind** [comment]
You can manually call Layout in PHP by using such code:

```
$gantry = Gantry\Framework\Gantry::instance();
$theme  = $gantry['theme'];
$theme->setLayout('home', true);
```

Replace `home` with you layout name.
Rest should be done like @mahagr said - using WP and Timber filters and core solutions etc.

**Comment by AmibeWebsites** [comment]
Thank you, I'm making some progress with that.
