### ISSUE TITLE
Error  Compilation in custom.scss

### ISSUE THREAD

**Issue by fernandopro** [gantry/gantry5#196]
Sorry for my English, I use google translate.

in custom.scss...
if I create a map in SCSS gives me an error the compilation.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps

thanks

**Comment by w00fz** [comment]
Unfortunately we are restricted with the [leafo compiler](https://github.com/leafo/scssphp) for compiling the Styles panel and the custom.scss and they do not support SASS 3.3/3.4 which is a bummer as we also would of liked to use maps and lists big time!
Hopefully they will add support for the latest SASS versions so we can all use it, in the meantime I'm afraid you either compile your SCSS locally, store it into theme `css-compiled` folder and load it from the theme. Or you have to do without maps :disappointed:
