### ISSUE TITLE
Wordpress: Particle WordPress Posts: add previous/next button?

### ISSUE THREAD

**Issue by EnricoSx** [gantry/gantry5#1961]
hello, how can i add previous/next button in wordpress posts particle? thanks
or page n° like this?
![pagination](https://cloud.githubusercontent.com/assets/16323227/24965093/5a4cbd2c-1fa3-11e7-9c46-de2219742483.JPG)

**Comment by newkind** [comment]
That's not possible right now. WordPress Posts/Joomla Articles/Grav Posts particles don't support pagination right now as it would require AJAX for paginating pages. We have an enhancement ticket about it here (#1376) but no ETA.
