### ISSUE TITLE
Lot's of errors with Grav+Grantry

### ISSUE THREAD

**Issue by kkemila** [gantry/gantry5#1964]
I'm getting lot's of errors in Gantry admin. Using the latest Grav & Gantry.

I'm unable to open modals in Gantry admin, so it's impossible to do almost anything.

![errors](https://cloud.githubusercontent.com/assets/13020135/25222419/13c45b16-25c1-11e7-85c2-9b313cd19c67.jpg)

**Comment by newkind** [comment]
This is not issue with Grav/Gantry. Either you don't have these files on your server or something is preventing from accessing them - security rules, .htaccess, permissions etc.

If you are sure that files are there in proper locations, please contact your hosting provider and ask them to check what could prevent them from being accessed.

**Comment by mahagr** [comment]
I tend to agree with @newkind , your issues seems to come from `verkkoyhteys katkesi`.

Toisin sanoen jokin esti sivun lataamisen, todennäköisesti joko mod_security tai apachen kaatuminen.

Sorry about my language!

**Comment by kkemila** [comment]
Thank you! Works now. Opcache was causing the errors and I managed to solve it by adding a line to .htaccess:

php_flag opcache.enable Off

**Comment by mahagr** [comment]
Ole hyvä! Molemmat on kehitetty opcache päällä, eli ehkä kannattaa vielä katsoa, voisiko syy olla jossain muualla.

Opcache shouldn't cause any issues, in fact, Grav and Gantry should work very well with opcache. Please check your opcache settings, maybe something in there is causing your issues.
