### ISSUE TITLE
cyrillic in block javascript_footer

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#1966]
Hello
 I need use cyrillic characters in javascript_footer block, but after compiling HTML page i see in footer "abracadabra", i.e. text in wrong code pages, but this text in basic body compiling right.

Example output:
var pricelist = {"goods00" : {"id":"4603720738381, "subid" : {}, "name": "ÐÐ¾Ð´Ð³ÑÐ·Ð½Ð¸Ðº &#039;ÐÐ¾Ð»Ð¸Ð±ÑÐ°Ñ-Ð Ð°Ð´ÑÐ³Ð°&#039; Ñ Ð¾Ð´Ð½Ð¸Ð¼ Ð²ÐºÐ»Ð°Ð´ÑÑÐµÐ¼ Ð¸Ð· Ð¼Ð¸ÐºÑÐ¾ÑÐ¸Ð±ÑÑ", "price": "460" },

```
{% block javascript_footer %}
{% do gantry.load('jquery') %}
    <script>
      var pricelist = {
         {% set _counter = 0 %}
         {% for item in particle.items %}
            "goods0{{ _counter }}" : {"id":"{{ item.goodsid }}, "subid" : {}, "name": "{{ item.name }} {{ item.description }}", "price": "{{ item.price }}" },
            {% set _counter = _counter + 1 %}
         {% endfor %}
         /*Тут типа русский текст*/
      }
    </script>
{% endblock %}
```

**Comment by newkind** [comment]
Depends how you set your name - is it a Twig var or anything else? Try echoing it for JS - `{{ your_twig_var|e('js') }}`

**Comment by lexa45ru** [comment]
The data in these variables assigned from the settings of the particle.
I try this code {{ your_twig_var|e('js') }}
On output i get

`"goods00" : {"id":"4603720738381, "subid" : {}, "name": "\u041F\u043E\u0434\u0433\u0443\u0437\u043D\u0438\u043A\x20\x27\u041F\u043E\u043B\u0438\u0431\u0440\u0430\u0448\x2D\u0420\u0430\u0434\u0443\u0433\u0430\x27 \u0441\x20\u043E\u0434\u043D\u0438\u043C\x20\u0432\u043A\u043B\u0430\u0434\u044B\u0448\u0435\u043C\x20\u0438\u0437\x20\u043C\u0438\u043A\u0440\u043E\u0444\u0438\u0431\u0440\u044B", "price": "460" },`

**Comment by newkind** [comment]
That's good, you get the Unicode chars which browser should interpret properly.

**Comment by lexa45ru** [comment]
Why except the tag <script> this var output normal

**Comment by newkind** [comment]
I'm not sure what you mean. Are you asking if why you need to add this `|e('js')` in `<script>` tag in particle and you don't have to in other places?

**Comment by lexa45ru** [comment]
This variable is normally displayed inside the page, but when it is added between the tags of the script, it is transformed into an abracadabra.

**Comment by newkind** [comment]
I think it's because default escaping set in Gantry for all particles. That's why you need to escape it for the `'js'` case, but I might be wrong here. @mahagr am I? ;)

**Comment by mahagr** [comment]
Default escaping is for HTML and everything inside Javascript should really be either js escaped of json_encode'd (quotes are automatically added for strings in that case). I am not sure, though, why encoding would be wrong, as HTML document should be in UTF-8.. Maybe the font used to show the source code doesn't support Cyrillic alphabets.

**Comment by lexa45ru** [comment]
> Maybe the font used to show the source code doesn't support Cyrillic alphabets.
Why outside of tag "script" all displayed normally?

**Comment by mahagr** [comment]
I don't know. Maybe your browser detects javascript and parses it in a different way. As long as everything works in the real page, I wouldn't worry too much. I don't think that the issue is in Gantry.

**Comment by lexa45ru** [comment]
Hello again my trouble is still here, but now with missing **tags**
In twig file i write:
```
{% block javascript_footer %}
   <script type="text/javascript">
... some code here ...
          content: "<h3>Title</h3><p>Hello world</p>"
... some code here ...
   </script>
{% endblock %}
```

on output i get
```
<script type="text/javascript">
...some code here ...
        infoWindow: {
          content: "<h3>Title<p>Hello world"
...some code here ...
</script>
```
Question: where html tags?

**Comment by mahagr** [comment]
Yeah, it's a bug in PHP DOM parser (or libxml). Use following instead:

```twig
{% do gantry.document.addInlineScript(js_goes_here, 0, 'footer') %}
```

See: http://docs.gantry.org/gantry5/advanced/css-js-twig

**Comment by lexa45ru** [comment]
or, as write @JoomFX in this [post](https://github.com/gantry/gantry5/issues/2000) use `You need to escape the / in your code.`
