### ISSUE TITLE
Drag/Drop Atom doesn't work 

### ISSUE THREAD

**Issue by szavaij** [gantry/gantry5#1969]
Atom Drag/Drop doesn't work on Page settings. I put down UIKit for Gantry 5 to its place, but now the Drag/Drop for the other Atoms it's not possible.
Gantry/Template: 5.4.11/g5_helium
Joomla: 3.6.5

**Comment by szavaij** [comment]
When I remove UIKit, everything works...

**Comment by JoomFX** [comment]
Hello @szavaij 

I'm the develop of the "UIkit for Gantry5" atom.
It is just a normal atom and it couldn't be responsible for your issue.

In my opinion there is no issue at all.
You just need to be more precise when you drag and drop the atoms.
Have a look at [this video](https://youtu.be/f7_BvYP5gdo) that I recorded for you. It shows everything in details.

**Comment by szavaij** [comment]
At the end I found the solution. You are right, no issue! Your video was a great help!
Thank you,
SzJ
