### ISSUE TITLE
Joomla 3.7: Invalid extension update

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1971]
Joomla 3.7 - Gantry 5.4.10 

Can't be updated to Gantry 5.4.11

Error  Invalid extension update

**Comment by mahagr** [comment]
I've learned in the past to always update Joomla extensions before upgrading Joomla.

Support for Joomla 3.7 has already been added, but I wanted to wait for the actual release to avoid surprises. Stay tuned, the update will be there shortly.

**Comment by joomlabeat** [comment]
I too usually update extensions first. But I was working on a dev project days ago on the 3.7 rc versions - then I just tried to update gantry and noticed the error - so I thought to report it here.

**Comment by mahagr** [comment]
I was replying in general, there have been other people with the same issue after Joomla update. But new Gantry release will be out in few hours, so the issue will be fixed fairly soon. I just need to be sure that I don't need to do a second release right after.
