### ISSUE TITLE
[WordPress] - Google Maps script broken when added via G5 (both from particle and from G5 Admin)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1975]
Hey guys,

There is something strange (wrong) that happens with the Google Maps script when added from G5.
WordPress adds a version number (`?ver=x.x.x`) to all assets automatically.
But this version number is added in the wrong place in the Google Maps script and therefore it breaks it.

The correct code that should be rendered is this:

```
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&ver=4.7.4"></script>
```

And currently what's being rendered is this:

```
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?ver=key=YOUR_API_KEY">
```

Notice how the `?ver` code is being added in the wrong place.

If we load the same code from **functions.php** by using the following code, everything works fine, the `?ver` code is added at the end of the URL as it should be:

```
function my_assets() {
    wp_enqueue_script( 'gmap-scripts', 'https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY', '', '', true );
}

add_action( 'wp_enqueue_scripts', 'my_assets' );
```

Here, have a look at [this video](https://youtu.be/iHwhmL_FZoY) that I recorded. It shows everything in great details (sorry Matias, the video is a bit long, about 10mins 😉 )

So my questions is - is there something that we can add/specify in the Twig so the `?ver` code is added in the correct place (at the end of the URL)?
I tried to load the script by using all possible ways ([Particle Blocks](http://docs.gantry.org/gantry5/tutorials/particle-blocks) as well as [assets, scripts, etc](http://docs.gantry.org/gantry5/advanced/css-js-twig)) but the `?ver` code is always added in the wrong place.

Or if this is a bug, or if the currently way that G5 adds the scripts can be improved, can you please implement it? Because currently our "Google Map" particle seems to be useless/broken in WordPress 😢 

Can G5 be made to add the script as if they've been added with `wp_enqueue_script` via **functions.php**? The issue I describe above is about the Google Maps script, but it will most definitely affect/break other scripts that contain parameters in the URL.

Thank you in advance 😉

**Comment by adi8i** [comment]
When you add a key you add it like this: `https://maps.googleapis.com/maps/api/js?key=1234"`, note the `?key=1234`.

`$array = explode('?', $script['src']);` breaks the string in an array, where `?` is the separator
`$version = array_shift($array) ?: false;` adds the version number, in this case it adds `array_shift($array)` is equal to `key=1234`, so the result is `ver=key=1234`

This way you can't add any `?...`

**Comment by JoomFX** [comment]
A quick update...

@adi8i suggested a workaround that solves the issue in our "Google Map" particle.
He suggested to add `&` in the script URL so the `key` parameter is considered as a second parameter.
This is what we have in the Twig:

```
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js{% if particle.apikey %}?&key={{ particle.apikey|e|trim }}{% endif %}"></script>
```

Which renders this on the frontend:

```
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?ver&key=YOUR_API_KEY">
```

I do not yet want to commit the above workaround officially to the particle repo because in my opinion this can be improved from the framework itself.
There should be something that can be done with [this code](https://github.com/gantry/gantry5/blob/267d72b4b899f8c234a95a84998c75f45b172394/src/platforms/wordpress/classes/Gantry/Framework/Document.php#L74) so the script URLs that contain parameters are rendered properly in WordPress.

**Comment by mahagr** [comment]
Looks like the workaround for WP doesn't work with external links.

**Comment by JoomFX** [comment]
Thanks Matias 😉
