### ISSUE TITLE
Chance stroke color on hover

### ISSUE THREAD

**Issue by karbal1** [gantry/gantry5#1976]
Hi,

Is it possible to make the blocks, I made in gantry, chance on hover? I would like to have the grey stroke chance in a green frame when hover...
How can I do that?
http://karinbaldemo.be/coachingatwork/index.php

Thanks!
Kind regards

**Comment by mahagr** [comment]
Yes. It is possible with some custom CSS code and some basic CSS coding skills. It is, though, not Gantry issue, so I'm closing the issue.

Please try asking the question in Gantry chat at https://gitter.im/gantry/gantry5
