### ISSUE TITLE
real life 404 page does not load any styling

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#198]
as discussed in hipchat with matias just now...

please see pic, when entering a wrong url such as in my example, the 404 error page actually loads, but it does not have any styling.

![gantry_404](https://cloud.githubusercontent.com/assets/5719486/7531598/ebfe635a-f521-11e4-8c9f-d8d89d5a9b95.jpg)

**Comment by mahagr** [comment]
Related to Joomla not loading any assets from $doc->addStyleSheet() in error page...
