### ISSUE TITLE
Dropdown Menu Level 2 Setting for Width Doesn't Work

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#1980]
In the G5 Menu Editor, when you change the dropdown width for a Level 2 item, it does not change anything. Changing the width for a Level 1 item does work. This is observed in the Interstellar template.

This is another bug, but Dropdown Direction will not Expand Left for any level.

**Comment by newkind** [comment]
Tried it on Helium and seems to be working fine. Interstellar doesn't modify the nucleus code of the menu so it should be the same.

!(Menu)[https://monosnap.com/file/JSLqi4LJUcjGR5V54SXnas6SegMVzA.png]
