### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by antonbw** [gantry/gantry5#1981]
Hi new clean install of latest  wordpress, gantry5 and Helium (5.4.12) theme loads but of main page is displays 'no menu selected' have tried latest CI as well and in Hydrogen but unable to do page settings or menu properties in layout ?
![wp helium menu prop](https://cloud.githubusercontent.com/assets/28346341/25657966/587117a4-2ff8-11e7-8375-dab628153082.PNG)

**Comment by mahagr** [comment]
```
JSON_UNESCAPED_SLASHES (integer)
    Don't escape /. Available since PHP 5.4.0. 
```

It should be available in PHP 5.4.0 and later... Which PHP version you're using?
