### ISSUE TITLE
Header changing format when displaying a single Joomla Article

### ISSUE THREAD

**Issue by Hammer315r** [gantry/gantry5#1982]
I'm displaying a link (Downloads) in the header of the hydrogen theme, I did this by creating a joomla article containing the link and used the "Joomla Article" particle to display it inside the header of the page.

As soon as I add content to the page (e.g. displaying a single joomla article in the main section), the formatting gets messed up in the header, and the link suddenly has a shadow and moves downwards.

Why does adding content in the main section affect the header at all?
![downloads after](https://cloud.githubusercontent.com/assets/28386724/25697208/63da46c0-30ba-11e7-99fb-14b23fc4321d.PNG)
![downloads before](https://cloud.githubusercontent.com/assets/28386724/25697210/6535c616-30ba-11e7-9d78-905775b201fe.PNG)

**Comment by mahagr** [comment]
Sorry for the late answer -- I missed your question.

When Joomla adds its content, extra CSS file gets loaded. Make sure you override those styles as well.

**Comment by Hammer315r** [comment]
I solved this problem a few days ago, but thank you for your help, I used firebug and went through the css files to find the error.
