### ISSUE TITLE
Unexpected mobile menu flashes

### ISSUE THREAD

**Issue by paulhibbitts** [gantry/gantry5#1983]
Hello,

I seem to be getting some unexpected mobile menu flashes for several Android devices as well as Chrome and Firefox Mac (when Browser window is small), when using either the Helium and Hydrogen theme. Is there something I can do on my end to prevent this?

Here are several videos of what I am seeing:
https://youtu.be/OTZK7pNU50o

https://youtu.be/37-BxBPQ9Ak

https://youtu.be/SSBVpLuEX8Y

The test site I am using is at http://test.hibbittsdesign.org/grav-skeleton-eportfolio-blog-site/

Thanks very much,
Paul

**Comment by JoomFX** [comment]
Hi Paul,

The reason for this behavior is that the JS responsible for collapsing/hiding the normal menu is loaded in the footer, in the `main.js` file and there is some delay until the full code is being loaded.

You can just add the following code in your `custom.scss` file and the issue will be gone (make sure you have `@import "dependencies";` at the top:

```
@include breakpoint(mobile-only) {
    .g-main-nav {
        display:none;
    }
}
```

**Comment by paulhibbitts** [comment]
Hello @JoomFX , thank you so much for your very helpful and prompt response!

I've added the following to the top of my custom.scss file as you describe:

```
@import "dependencies";

@include breakpoint(mobile-only) {
    .g-main-nav {
        display:none;
    }
}
```

The flash that I was seeing is now gone, THANK YOU! However, for some reason there is still a "bump" when viewing this page in particular: http://test.hibbittsdesign.org/grav-skeleton-eportfolio-blog-site/articles

Any ideas on that one?

Again, thanks for all your help,
Paul

**Comment by paulhibbitts** [comment]
Thanks again for your great help @JoomFX , I am on-track to tackle that last item I mentioned so I will close this issue. Cheers!
