### ISSUE TITLE
Checkboxes next to the options in Content tab get unchecked after refresh

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1986]
When you override a value in Content tab in WP in any of the outlines and you refresh the page the checkbox gets "unchecked". Toggle state is being kept.

**Comment by adi8i** [comment]
@newkind Do you extend the forms?

**Comment by newkind** [comment]
Where?

**Comment by adi8i** [comment]
I assume we are talking about Content tab as in `blueprints/content/archives/content.yaml` for example. The you can create `../blog/content.yaml` and extend the first one.

**Comment by newkind** [comment]
Yah, although I'm not extending anything. The bug is simply not representing what's being currently overriden in the admin.
