### ISSUE TITLE
Joomla Gantry 5 Cache bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1987]
It appears that Joomla Gantry 5 Cache is not showing right its always 0 see screenshot!
![2017-05-09 23 57 36](https://cloud.githubusercontent.com/assets/10489911/25874602/8ba406ca-3513-11e7-8be1-4d357e756f4b.jpg)

I checked and the cache is generated and its deleted it not just shown how many files and size of the cache!

**Comment by mahagr** [comment]
I don't think it's an issue as Joomla just doesn't find the cached files as we're using custom folder structure inside the cache.
