### ISSUE TITLE
Recompile CSS button

### ISSUE THREAD

**Issue by StefanvDelft** [gantry/gantry5#1990]
Hi all,
I have been working with the Gantry 5 framework for about a year now and I like it very much.
A suggestion I have, maybe for a future update...
I often have to Recompile CSS. There are the clicks to the template-Default, Styles tab over and over again.
It would be great if there were a Recompile CSS button in the main Joomla dashboard. Like clear cache, visible in every screen :)
Thanks very much for all the work and effort that the developers put in Gantry 5!

**Comment by newkind** [comment]
For the time that you make changes just switch from production to development mode and Gantry will re-compile detected SCSS changes on every front page refresh :)

**Comment by StefanvDelft** [comment]
Wow that is a great thing to know :)
Thank you very much for your quick reply!

**Comment by newkind** [comment]
No problem, closing!
