### ISSUE TITLE
Does the "Default Menu" auto-switch menu in multilingual sites?

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#1991]
Is it normal behavior with gantry 5 menu particle, when using the option for menu "Default Menu" to select automatically the default menu for each language in a Joomla multilingual website?

I am asking because the documentation http://docs.gantry.org/gantry5/tutorials/multilingual-site says that we need to create separate layouts for each language and select the desired menu for each layout - but in a website I am working on, using the default menu results to auto-switching among the languages menus when changing languages in the same layout.

**Comment by mahagr** [comment]
Both should work. The layouts are mostly needed to translate the particles inside the layout.
