### ISSUE TITLE
Add option to copy particle inside Layout manager

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1992]
The ability to go to the Layout manager and just hit some sort of 'Copy particle' button on each already existing and configured particle would be super helpful. :)

**Comment by mahagr** [comment]
It already exists, kind of... You can copy particles which have been saved by using the cloning/inheritance feature.

**Comment by mahagr** [comment]
The feature doesn't work for base outline, though.

**Comment by mahagr** [comment]
Duplicate of #1703 (as copying is already possible in other outlines),
