### ISSUE TITLE
Nested collection.list on container.tabs issue

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1995]
Hi Matias,

This issue https://github.com/gantry/gantry5/issues/1877 , is not fixed  100%

It seems that wrong modal is opening and I've sent to you the test particle on private (gitter).

Can you please take a look and find a fix for it?

Thank you

**Comment by mahagr** [comment]
Unfortunately, this one will not be easy to fix as multiple layers of non-fields are really not supported because of the deep lookups which need to be done.

I'm going to move this one to the future releases as it needs a bit more work than just a quick fix.

**Comment by nicutor** [comment]
Thank you Matias, I will remember you about this issue. 

Just to know for others who can have the same problem, the collection.list is not working on nested container.tabs and probably on nested container.sets too.

**Comment by nicutor** [comment]
Hi @mahagr , can you please put a lower milestone on this? 
Is there somebody else that has used nested container.tabs and have this issue?
Please let us know, so maybe this bug can be fixed sooner.

**Comment by mahagr** [comment]
@nicutor Please test -- also with other particles with any kind of collections as it may affect those too.
