### ISSUE TITLE
Add custom css class to g-grid row

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#1996]
Hello.
How i can add custom css class to g-grid row
![5b2862cc-20a0-11e5-9dbd-5ecdce5540cc 1](https://cloud.githubusercontent.com/assets/26233757/26120963/0f6546e0-3a8c-11e7-85f9-dd4b6cc48ebb.jpg)

**Comment by mahagr** [comment]
I don't think you can add it from admin for rows. You can do it from yaml, but the issue is that you can easily add/remove rows, so I would rather add a new section and add the class into there.

**Comment by mahagr** [comment]
I'm assuming that the question has been answered.
