### ISSUE TITLE
How to copy a filled particle to use in another website?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1997]
I probably have asked this before, but I couldn't find the post. Sorry if I did.

I have filled my custom cs/jss atom with many css and js that I almost use on every website. How do I backup this filled atom to use in another website so I don't have to go through the trouble of filling them again? I think filled particles' information is stored in some .yaml file, but I can't find where they are.
=============update==============
OK I found the file, it is templates/g5_helium/custom/config/default/page/head.yaml. If I copy this file over to new website at the same location, will it work and will it create any potential problem?

**Comment by mahagr** [comment]
Yes, it would work as it is. Just be wary if you use another template as the content may be different.

**Comment by mahagr** [comment]
Assuming that the question has been answered.
