### ISSUE TITLE
bootstrap wordpress particles

### ISSUE THREAD

**Issue by konradCEO** [gantry/gantry5#1998]
how load Bootstrap in Gantry5 Practicles?

http://www.thedruk.pl/ - sample bootstrap not works

**Comment by newkind** [comment]
How did you add it?

**Comment by konradCEO** [comment]
Im use  "ON  Bootstrap3" buton in Global Page Setting
http://thedruk.pl/bootstrapset.jpg - like that

and 

past CODE in CUSTOM HTML Practicles np this code:

`<div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect!</p> 
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Column 1</h3>
      <p>Lorem ipsum dolor..</p>
      <p>Ut enim ad..</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 2</h3>
      <p>Lorem ipsum dolor..</p>
      <p>Ut enim ad..</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 3</h3> 
      <p>Lorem ipsum dolor..</p>
      <p>Ut enim ad..</p>
    </div>
  </div>
</div>`

and grid don't work

**Comment by newkind** [comment]
Bootstrap toggle is under section Frameworks so it means that it loads only JS scripts that belong to the bootstrap, not css and styling.

If you want to use Bootstrap styling you have to include the Bootstrap CSS from these links :
https://getbootstrap.com/getting-started/#download-cdn

**Comment by konradCEO** [comment]
OKEY I must Bootstrapa from the link above.

Just how do i integrate a bootstrap with Gantry?

**Comment by newkind** [comment]
Just use Custom CSS/JS atom and as an url to CSS paste this: `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`

**Comment by konradCEO** [comment]
I checked before
when i use this link .... 

CSS/JS Atom - then the error pops up " 404" 
like that:  http://thedruk.pl/bos2.jpg

When i chose locations in this option [CSS/JS Atom] .../gantryTheme/custom/bootstrap.min.css
it still does't work

----

**Comment by newkind** [comment]
You're adding it wrong. How are you doing it? Here's the docs page: http://docs.gantry.org/gantry5/configure/page-settings#atoms

**Comment by konradCEO** [comment]
So I do just as it is described here
http://docs.gantry.org/gantry5/configure/page-settings#atoms

And as I paste the link, I click APPLY, then automatically pops up error 404 itself.
Then the selection window returns.
But it is not possible to approve this link.
`https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css`

**Comment by newkind** [comment]
Are you using latest Gantry? Do you have mod_security enabled? Try to disable mod_security and paste a screenshot of your Atom configuration.

**Comment by konradCEO** [comment]
yea last Gantry
and Lastest WP

![a](https://cloud.githubusercontent.com/assets/26788585/26162509/35e63e5a-3b27-11e7-80ae-440347693cc1.jpg)
![b](https://cloud.githubusercontent.com/assets/26788585/26162508/35e671c2-3b27-11e7-8cfd-6b5a60887a02.jpg)
![c](https://cloud.githubusercontent.com/assets/26788585/26162511/35ec0132-3b27-11e7-85d6-9a0f209dcdc6.jpg)
![d](https://cloud.githubusercontent.com/assets/26788585/26162510/35e97c78-3b27-11e7-9599-ee86932b1cca.jpg)
![e](https://cloud.githubusercontent.com/assets/26788585/26162506/35e4548c-3b27-11e7-9e27-f0f5699e413c.jpg)
![f](https://cloud.githubusercontent.com/assets/26788585/26162507/35e5a1ac-3b27-11e7-8163-e6c380efc86b.jpg)

**Comment by newkind** [comment]
@mahagr any ideas? can you try with http instead of https?

**Comment by newkind** [comment]
If you want to, please ping me on Gitter and if you'll provide me your admin login credentials, I'll investigate what can be wrong.

**Comment by mahagr** [comment]
The only reason it won't work is that mod_security blocks the POST request thinking it is an attack.

**Comment by konradCEO** [comment]
Thanks for Help Guys @newkind  and @mahagr 

hym...  I do not know if this is the case


i cant disable mod_security in my cPanel i dont have this option in SECURE tab
but
when i use in .hataccess:
`<IfModule mod_security.c> SecFilterEngine Off SecFilterScanPOST Off </IfModule>`
My web site is not working then

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator, webmaster@formwood.thedruk.webd.pl and inform them of the time the error occurred, and anything you might have done that may have caused the error.
> 
> More information about this error may be available in the server error log.
> 
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
> 

@newkind yea I can give you my admin passwords

**Comment by konradCEO** [comment]
Okey im back :) 

I changed the server to free 000web only for test
http://fwd.comeze.com/

![a1](https://cloud.githubusercontent.com/assets/26788585/26300107/74ede77e-3edd-11e7-953c-e6db3d54173e.jpg)
![a2](https://cloud.githubusercontent.com/assets/26788585/26300111/77cdbbb8-3edd-11e7-9e40-ebe084da91db.jpg)


CUSTOM CSS / JS ATOM works

However, the page is not displaying properly.

P.S.
Maybe I misunderstand. And the gantry can not be used with CUSTOM HTML in one section of the layout written in Bootstrap.

**Comment by newkind** [comment]
It should work just fine. I just checked your site and all is fine, besides that bootstrap is messing up with your styling.

What I can tell you for sure is that scaffolding.less file has set your default font size from `16px` to `14px` which is messing with all fonts because every piece of page is using `rem` as font unit size.

You can either play with it or ie. force the 16px of default font size by using `!important` in Helium SCSS.

Anyways your site is fine, bootstrap is fine, you just need to resolve conflicts.

**Comment by mahagr** [comment]
@konradCEO Have you been able to solve the issues you've had with Bootstrap? It would be a great addition to have precompiled bootstrap CSS files for Gantry. :)

**Comment by konradCEO** [comment]
@mahagr @newkind 
YES! Sorry i did not write if the solution works. Family probelms.

Back to the topic:

Font Resizing Solution - works great.

I have tested several bootstrap templates on Gantry

Works great.

---
When I finish the right side then I will praise the results.

**Comment by mahagr** [comment]
In the meantime, I'm going to close this issue.
