### ISSUE TITLE
Gantry 5 Grav offcanvas ID duplication 

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#1999]
GravCMS Helium template
![image](https://cloud.githubusercontent.com/assets/26233757/26268712/079dc4de-3d0a-11e7-8712-702413125a14.png)

**Comment by mahagr** [comment]
I'm not able to see this issue in my local installs.

**Comment by lexa45ru** [comment]
grid.html.twig
``` <div {% if segment.attributes.id %} id="{{ segment.attributes.id|e }}"{% endif %} ```
if ```segment.type``` equals ```offcanvas``` this code add ID ```g-offcanvas```, but parent div already contains ID ```g-offcanvas```

**Comment by mahagr** [comment]
Which template is this? Because of you cannot add id to the grid from Gantry admin.

**Comment by lexa45ru** [comment]
Template is Helium. GravCMS

**Comment by newkind** [comment]
Can't replicate it also - this is my source on Grav + Helium

![https://monosnap.com/file/WrOav3bj6CWy4g9Bez2DcVsXP5M5EI.png](Helium)

**Comment by mahagr** [comment]
Closing as we cannot reproduce the issue and there hasn't been any response from @lexa45ru
