### ISSUE TITLE
Hydrogen: Missing some css

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#20]
![untitled](https://cloud.githubusercontent.com/assets/876623/6886407/88597572-d63d-11e4-9da6-7d0e2a7daa43.png)

Issues
- Alert text color
- Color dropdown-toggle
- Color li items on hover (dropdown)
- .btn-link color

**Comment by w00fz** [comment]
1- Are you using [alerts links](http://getbootstrap.com/components/#alerts-links)? The green links are just the default link colors of the theme, bootstrap works the same way unless you use `.alert-link`

2, 3, 4. @kevlardev is going to look at it

Thanks.

**Comment by 810** [comment]
![untitled](https://cloud.githubusercontent.com/assets/876623/6907088/8d4d0aca-d733-11e4-9a8a-3bd93223f928.jpg)

**Comment by w00fz** [comment]
From the screenshot I can tell you are not using `.alert-link`. That's the way bootstrap works. If you click the link I pasted above it is explained (http://getbootstrap.com/components/#alerts-links).

What you want is something like:

```
<a class="alert-link" title="View Announcements" href="/forum/announcements/id-6" rel="follow" abp="156">...
```

**Comment by 810** [comment]
Thnx we will fix that

**Comment by w00fz** [comment]
:+1:

**Comment by 810** [comment]
but you haven't the alert-link  so it is the same

**Comment by w00fz** [comment]
Thought it was! I think it was stripped out for some reasons. I'm adding it back now and should be good. @kevlardev could you have a double check on it?

**Comment by 810** [comment]
i have also a issue with table: 
![untitled](https://cloud.githubusercontent.com/assets/876623/6910801/5a41b868-d758-11e4-9935-c1a6a6bd5db2.jpg)

when i delete:
table { table-layout: fixed; } 
/media/gantry5/engines/nucleus/scss/nucleus/mixins/_nav.scss

Then is fine again.

**Comment by mahagr** [comment]
Can you have single issue per real issue, please! Makes it really hard to close fixed bugs.
