### ISSUE TITLE
JS Pipeline

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#2001]
Hello.

JS Pipline work only with script added width
~~~
{% do gantry.document.addScript(url( scripturl ), 10, 'head') %}
~~~
Other JS in page not added to pipiline script (like system main.js).

Oher question: how moved piplined script to footer

**Comment by mahagr** [comment]
You're on Grav?

**Comment by lexa45ru** [comment]
Oh, i firgot write it. Yes GravCMS

**Comment by mahagr** [comment]
Fixed the pipelining for bottom js, though `main.js` breaks if `js_minify: true`, so you need to disable minifying. 

@w00fz Can you take a look why minifying the file breaks it?

**Comment by mahagr** [comment]
This is Grav bug IMHO. Closing.
