### ISSUE TITLE
JS Collection

### ISSUE THREAD

**Issue by lexa45ru** [gantry/gantry5#2002]
New scripts not added to page via collection in admin panel (Grav CMS)

**Comment by mahagr** [comment]
What do you mean?

**Comment by lexa45ru** [comment]
I add js scripts via admin panel to collections:
![image](https://cloud.githubusercontent.com/assets/26233757/26416365/0dcdc110-40cf-11e7-836f-406043a2e0bd.png)

But in output i see only first script (default) `system://assets/jquery/jquery-2.x.min.js`

**Comment by mahagr** [comment]
@rhukster Has this been added lately?

**Comment by rhukster** [comment]
Not new. However that is system level config that defines asset collections. You still have to add the collection to the page via twig or via php. Jquey collection is a good example.

**Comment by lexa45ru** [comment]
Also, imho, need add option to disable (without deleting) the script in the collection.
![image](https://cloud.githubusercontent.com/assets/26233757/26641946/842b324a-4645-11e7-9725-d6584cd349ff.png)

**Comment by rhukster** [comment]
Unfortunately this maps directly to the system.yaml config file.  There's no way of providing an enable/disable state for this.

**Comment by mahagr** [comment]
@lexa45ru You cannot just add collections, you also need to use them in your twig files.

```twig
{% do assets.addJs('main') %}
```

Also, don't put your own files into the system folder, but them into user and use `user://` stream.

Closing as non-Gantry question.

**Comment by lexa45ru** [comment]
That is, once I have to add this file to the collection, and the second time to call from my twig file?

**Comment by mahagr** [comment]
If you add it to the system configuration, it just makes it available to be used in your twig.

Gantry provides an easier way to add custom JS/CSS assets to your page from the `Page Settings`, you may want to use that instead.

**Comment by lexa45ru** [comment]
Maybe yes, but why then introduce this function? Or is it for other templates, not for gantry?

**Comment by mahagr** [comment]
It is for Grav and has nothing to do with Gantry.
