### ISSUE TITLE
Section Collapse bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2004]
When you click Collapse All the sections collapse, but if you want to expand particular section you will see that they still say collapse instead expand.

http://take.ms/xy7aa

**Comment by mahagr** [comment]
I was able to reproduce the issue.

**Comment by w00fz** [comment]
Try clearing your cookies. I can't seem to be able to reproduce this.

**Comment by kat05** [comment]
I can confirm this issue, please see pic.

![g5_expandsection](https://user-images.githubusercontent.com/5719486/30326097-a7b6f176-97c7-11e7-93b7-c6bae041d67f.jpg)
