### ISSUE TITLE
Blog display button incorrect

### ISSUE THREAD

**Issue by blackyzero** [gantry/gantry5#2005]
Dear everyone,

I found the issue when assignment a blog item page to use Outline which is inherited a base outline.
The button "Next Post" and "Previous Post" are swapped together.
![screen shot 2017-05-23 at 5 54 32 pm](https://cloud.githubusercontent.com/assets/4286063/26351273/2ded897e-3fe1-11e7-9ae7-62ef7d76f79a.png)

How could i fix it?
Thanks a lot.

**Comment by paulhibbitts** [comment]
I also prefer the buttons to be organized that way as well.

To achieve the same you will need to add a bit of custom Twig to the custom folder for your Helium folder (and create one if none exists).

1. In your Helium theme folder, create the following series of sub-folders:
/custom/templates/partials/
2. Add the following in a file called blog_item.html.twig and find the chunk of code starting with {% if show_prev_next %} and replace that chunk with the below:

```
{% if show_prev_next %}

        <p class="prev-next">
            {% if not page.isLast %}
                <a class="button" href="{{ page.prevSibling.url }}"><i class="fa fa-chevron-left" aria-hidden="true"></i> {{ 'GANTRY5_ENGINE_BLOG_ITEM_PREV_POST'|trans }}</a>
            {% endif %}

            {% if not page.isFirst %}
                <a class="button" href="{{ page.nextSibling.url }}">{{ 'GANTRY5_ENGINE_BLOG_ITEM_NEXT_POST'|trans }} <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
            {% endif %}
        </p>
    {% endif %}
```
I use this exact code in my ePortfolio Skeleton, and you can view that repo at https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog/blob/master/themes/g5_helium/custom/templates/partials/blog_item.html.twig

**Comment by blackyzero** [comment]
That's great!
i got it works. Thanks a lot @paulhibbitts .
