### ISSUE TITLE
Particle equal to get_post($post_id); Example

### ISSUE THREAD

**Issue by NoahjChampion** [gantry/gantry5#2007]
Hi. 

Gantry looks pretty awesome and I have been going through it now looking to create my own Particle because there doesn't seem to be this one or any one to start with relevant. 

Could you provide an example of creating a new particle that would be the equivalent of `get_post($post_id);` for Wordpress ?

I don't know anything about Twig, but looks doable. 

I've already created my theme but am seeing how Gantry could help leverage that, but I need this particle to go more about seeing that. 

Is a particle simple a file that calls the php file and the php file from there does everything, and that file does not have to include Twig syntax?

**Comment by rhukster** [comment]
```
{{ page.find('/your/page/route').content }}
```

Something like that?

**Comment by NoahjChampion** [comment]
Hi @rhukster !!! Thanks for responding. 

Hmm, I'm not sure what that would look like which is why I am asking. 

Though your response confuses and makes sense to me. 

It confuses because it looks nothing like what I thought and then makes me unclear of how to manipulate. 

It makes sense because I'm guessing that maybe `.content` is a predefined part of Twig? If so then my `/my/page/route` could be my PHP function?

I have a function that runs [get_post()](https://developer.wordpress.org/reference/functions/get_post/). 

What I would like is a select drop down (particle post type select drop down) in the Gantry Theme Admin where I could populate a specific post type from Wordpress and then select that post and save it into a section like the footer or sidebar. Then on the frontend of the site that would return my $var returned from my PHP function which would be the content from the specific post save in the Gantry Theme Admin. 

I can draw up a screenshot if that would help explain.

**Comment by rhukster** [comment]
Sorry I replied incorrectly. I saw this pop up in my email and thought it was a Grav CMS question. I see now it was Gantry5 specific.

**Comment by adi8i** [comment]
Hi, you can use this one as an example, it fetch wordpress posts. https://github.com/gantry/gantry5/blob/develop/engines/wordpress/nucleus/particles/contentarray.html.twig

**Comment by NoahjChampion** [comment]
@rhukster ok, sure no problem! 

@adi8i ok, thanks appreciate it! 

Thanks both again :D
