### ISSUE TITLE
Content Array (Artists, Posts, Content) spacing between columns.

### ISSUE THREAD

**Issue by RyanMPierson** [gantry/gantry5#2011]
Any chance we could add an option in the YAML to give space between columns of the WordPress Posts, Joomla Articles, Grav Content particles?

David came up with this CSS that adds it. Having the ability to toggle this on and off would be cool.

```.g-content-array .g-array-item {padding: 0 0.938rem;}```

**Comment by newkind** [comment]
But there is already space between the columns added by the `g-content` class. Take a look at the screenshot.

!(https://monosnap.com/file/3n6U09uJj4EgkVGC9qyaqbAlrcVzCV.png)[Screenie]

**Comment by RyanMPierson** [comment]
Might be an issue on Supra then, because we had to write that CSS and add it to separate the columns.

**Comment by newkind** [comment]
What section? Check if there is no classes that would remove the padding from `g-content` ie. `flush`

**Comment by mahagr** [comment]
Invalid: Not part of Gantry itself.
