### ISSUE TITLE
Apply outline in code

### ISSUE THREAD

**Issue by xpeH** [gantry/gantry5#2012]
Hi. Im use wordpress bbpress and hydrogen. And i have couple of outlines. The problem is when forum is opened default outline is applied to it. Please answer some one: is it possible to set outline in code by hooks or filters? Or is a way to set it according to slug? Thanks in advance.

**Comment by mahagr** [comment]
Yes. In fact, this is how Gantry itself sets an outline. There are a few ways to do this:

* Modify template file

Open `bbpress.php` in your theme and add `$theme->setLayout(my_layout', true);` after the variable has been set in line 20. Layout name is the name (folder) of the outline in the filesystem. This changes the template for all the pages unless you add some additional logic to figure out the outline to be used.

* Add an action

You can do something like this:
```
add_action('template_redirect', 'gantry_theme_set_template_layout', -9999);

function gantry_theme_set_template_layout() {
    $gantry = Gantry\Framework\Gantry::instance();
    $theme  = $gantry['theme'];

    $theme->setLayout('my_layout', true);
}
```

You need to do this earliest at this point and you need to do it before Gantry loads its configuration for the current outline.

* Create your own assignment type

Gantry has a couple of filters and actions for adding your own assignment types which can then used from the admin.

`apply_filters('g5_assignments_types', $types)` is run when Gantry asks for all the available types
`do_action('g5_assignments_page', $list)` is run after all rules have been built assignments set for the current page

Additionally, there are filters for each type if you need to customize any of the lists.

The logic is a bit more involved, though... So it might be best to look at the code.
