### ISSUE TITLE
Page content is autoformatted in Gantry 5 - Wordpress

### ISSUE THREAD

**Issue by renatocan** [gantry/gantry5#2013]
I have created an outline in Wordpress with a "Page Content" block. The problem is that the content is autoformatted and `<p>` tags are inserted, causing errors on the html.

Is there a way to disable autoformatting? I have found something about a "Disable Auto Paragraphs" option but it is available only for Gantry 4, right?

Thanks,

[]s,

Renato.

**Comment by newkind** [comment]
Disable Auto Paragraphs is also available in Gantry 5 in Theme Settings > Content tab.

**Comment by renatocan** [comment]
Thanks! I hadn't noticed.
