### ISSUE TITLE
"container-main" Inside a HTML tag "main"

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#2016]
Hello,
I am creating 3 columns in my design according to this tutorial:
Http://docs.gantry.org/gantry5/advanced/creating-layout-presets
I also know that I can change the SECTION tag that encloses each section using these lines for example:

```yaml
structure:
   header:
     subtype: header
```
--------------------------
But I want the container of my columns to have a MAIN tag and no SECTION.
I am creating sections using this:
```yaml
   /container-main/:
     -
       - content 60:
       - aside 20:

structure:
   container-main:
     subtype: main
```
---------------------
But the container always returns me a SECTION tag and not a MAIN.
How can i fix this?
![sin-titulo-1](https://user-images.githubusercontent.com/9434043/26842590-fb288f98-4ab2-11e7-942d-96254ca84bd4.png)

**Comment by adi8i** [comment]
Hi,

I haven't tested this, but my first though is that you don't re-load the preset, after each change you do in the yaml file you have to load the preset, it won't auto update. Go to `Layout manager -> load`, take care, everything applied to section level will be wiped out.

**Comment by mahagr** [comment]
I think that only sections (not containers) can be using different tags right now. You can use them by: `main-id`.

**Comment by mahagr** [comment]
I'm assuming that the question has been answered.
