### ISSUE TITLE
Does not detect new version

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2018]
Hi,
I have an installation of Joomla 3.7.2 with Gantry 5.4.12.
After clearing the Joomla cache, the new version of Gantry it doesn't detect.
Neither from Components > Gantry 5 Themes the new version is not detected. I must do the update manually.

**Comment by topwebs** [comment]
I have repeatedly raised this issue in gitter with no response. Something is wrong with the Gantry 5.4.13 update for Joomla. It is not showing up for the auto updates. The WP update is working correctly.

**Comment by mahagr** [comment]
Should be fixed already.
