### ISSUE TITLE
Gantry Dropdown Menu not remaining open on Windows Touch Screen

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2019]
From reports by Henning / David, and also the user here:

http://www.rockettheme.com/forum/general-discussion/270250-rt-salient-sub-menu-navigation-vs-windows-edge

When opening a dropdown menu on Windows Edge browser on Windows Touch Screen / tablet the sub-menu closes after a second or two. It will not remain open.

**Comment by w00fz** [comment]
Anyone with a window touch screen that can help looking into this?

**Comment by paulhibbitts** [comment]
Hey @w00z, I've got a Surface Pro with Windows 10 if I can help. I can also confirm I see this issue on MS Edge.

Google Chrome, Firefox, and Opera all seem to be a-ok with the menu display.

**Comment by mahagr** [comment]
MS Edge is dead now. I'm glad that MS replaced it with better product.
