### ISSUE TITLE
"Unsupported operand types" error when trying to expand the Dropdowns in the Menu Editor

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#202]
I got this error with all Menu Items when I try to expand their dropdowns.
It is with clean installation of Gantry5 RC1, not an update.

http://i.imgur.com/w1gEYDA.png

**Comment by kat05** [comment]
i can replicate this, fresh joomla 3.4.1 install with learn joomla sample data + gantry + hydrogen

then went to > components > gantry 5 themes > hydrogen...

in the menu editor i tried selecting the 'aboutjoomla' menu and got the error

![joomla 3 4 1 2 - administration](https://cloud.githubusercontent.com/assets/5719486/7547234/db4c5976-f5ae-11e4-9f4e-0a2cba2ef91f.jpg)
