### ISSUE TITLE
Share custom between theme

### ISSUE THREAD

**Issue by AmibeWebsites** [gantry/gantry5#2022]
Hi, is there a way to specify a location for the custom folder outside of a theme so that it can be shared between themes?

This is my use case: I select a template, make a whole bunch of outlines, setting up particle and assignments... and then I decide to change templates :-(

Option 1: move/copy the files of custom (primarily custom/config) from one template to the next - not ideal
Option 2: symlink custom directories between templates
Option 3: template config that specifies location of custom folder

One thing is that css-compiled would need to be regenerated after swapping templates - not such a big deal. Is there code I can auto-run when a template change is detected?

Is any of this feasible? Ideal option? Any other factors to consider?

Thanks...

**Comment by mahagr** [comment]
Well, there's actually a request of not sharing custom with child themes (in Grav and WP), which is conflicting with your request. Most of the time you don't want to share settings and customizations between themes, but yeah, there are many different use cases.

Right now the official stance on changing themes is to copy the settings manually from theme to another. It works great on Grav and WP but has some issues in Joomla, which keeps records about the template styles in the database. Usually, the main issue when changing the template is that the particles may not be in the new theme or they are incompatible with each other. So some manual tweaking may be required when changing themes.

**Comment by AmibeWebsites** [comment]
Hi, I've worked out that it appears to work between child and parent themes (WordPress) by modifying the child theme's include/theme.php as follows:
```
// Initialize theme stream.
$gantry['platform']->set(
    'streams.gantry-theme.prefixes',
    ['' => [
        "gantry-themes://{$gantry['theme.parent']}/custom",
        "gantry-themes://{$gantry['theme.name']}",
        "gantry-themes://{$gantry['theme.name']}/common",
        "gantry-themes://{$gantry['theme.parent']}",
        "gantry-themes://{$gantry['theme.parent']}/common",
    ]]
);
```
Would I have to adjust themes to all be children of one theme so I'm assuming then it could be achieved between all themes by modifying each theme's include/theme.php - this would be a problem though when a theme is updated, unless I make a child theme of each installed theme?

A WordPress hook or Gantry function where I can dynamically adjust streams.gantry-theme.prefixes?

And where can I find out more about the different streams available? The more I think this through the more I'd like to pull custom out of the gantry-themes stream and into the uploads folder (or similar). My rational is that then the theme files are kept clean and files that change are in a location that's being backed-up (of course I'm backing up themes at the moment but wouldn't need to if I can make this change).

I would love also the hear if there are any concerns with what I'm suggesting that should receive attention.

Thanks.

**Comment by AmibeWebsites** [comment]
Thanks @mahagr - hadn't realised there were conflicting requests... I'll see if I can find those tickets to understand that perspective.

I'm working with a user base that won't be able to copy files and, for usability, it makes sense (to me, in the setup I have) to regard layouts, assignments and menu settings as site configuration and not theme configuration.

The particles point is an issue - I'll also need to look at ways to share those across themes.

**Comment by AmibeWebsites** [comment]
@mahagr Can't find the request you refer to - perhaps you can point me in the right direction?

I appear to have it working between themes and child themes alike, where all have the first item in streams.gantry-theme.prefixes set to one joint location "gantry-themes://my_one_theme_to_rule_them_all/custom"

Being able to dynamically set this would save from from having to create a child theme for every theme that overrides this in include/theme.php

As for trying to move it to media, this causes a fatal error:
```
// Initialize theme stream.
$gantry['platform']->set(
    'streams.gantry-theme.prefixes',
    ['' => [
        "gantry-media://custom",
        "gantry-themes://{$gantry['theme.name']}",
        "gantry-themes://{$gantry['theme.name']}/common",
    ]]
);
```

**Comment by Empowermom** [comment]
A big DITTO to what AmibeWebsites said:
"it makes sense ... to regard layouts, assignments and menu settings as site configuration and not theme configuration."

... most especially in Joomla.   Is there a convenient, "NON delve into the code" way to do that?

**Comment by mahagr** [comment]
This is a part of the themes which has really not been solved yet, but @AmibeWebsites is on right track on how you can do it. You can share stuff between themes by changing how the logic works, but I'm not sure if it is fully supported by the logic as nobody has tried it before.

I'm not sure if there's request for the opposite issue, but a few people have complained in WP and Grav that child theme shouldn't share configuration with the base theme.

@Empowermom: In Joomla sharing layouts is much harder than in other platforms because of Joomla stores stuff into the database, which makes sharing impossible.

**Comment by AmibeWebsites** [comment]
Yes, I'm effectively sharing settings and particles across themes, with the ability for each theme to override. It does mean that for each theme I need to move particles to a central place (or symlink them if they're likely to get updated).

@mahagr Okay, I think I understand the need for config to reside in a child theme, rather than the parent - it actually makes sense to me (and I wonder if I was one of those that 'complained'). BUT, even if child config resides under the child folder structures by default, this can still be 'overridden' by changing the logic as I've indicated above, so nothing would be lost.

The more I think about this though the more I'm coming up against another issue, which is more a fundamental design concern around what a 'theme' is... but this is another topic for discussion I'll write up when I have my thoughts together.

**Comment by AmibeWebsites** [comment]
@mahagr Any thoughts on a steam that references the site's uploads folder? I'm working in a multisite environment so if I can get everything that is site specific under its own directory structure it makes it easier to setup backups for each site.

**Comment by mahagr** [comment]
Stream named `gantry-media://` already uses uploads folder and there's a setting to change its behavior to look into uploads first and only if the file doesn't exist -- into the theme.

**Comment by AmibeWebsites** [comment]
@mahagr using gantry-media:// like below causes a fatal error - have I done something wrong?
```
// Initialize theme stream.
$gantry['platform']->set(
    'streams.gantry-theme.prefixes',
    ['' => [
        "gantry-media://custom",
        "gantry-themes://{$gantry['theme.name']}",
        "gantry-themes://{$gantry['theme.name']}/common",
    ]]
);
```

**Comment by mahagr** [comment]
Might be because of the circular reference as the media points back to the theme, which now points to media. So yeah, that one would certainly not work.
