### ISSUE TITLE
Can't use new WordPress 4.8 Widgets as Widget particle in LM

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#2023]
Looks like new widgets introduced in WP 4.8 are causing some troubles in Layout Manager. When you try to place one of the new widgets as a widget particle - Video, Audio, Image or Text (has a rich editor now) - they don't load any input fields.

**Comment by omikron** [comment]
I am experiencing this as well.

**Comment by w00fz** [comment]
Looks like an issue in the way we load the widget form on our side. If you inspect the video widget for instance, you can see all the hidden fields for video extensions but not the button and drop outline.

I think this is just partially working and needs investigation.

@mahagr added you to this

**Comment by newkind** [comment]
We should solve this before next update.

**Comment by newkind** [comment]
Let's bump this up as it **REALLY** needs to get fixed.

**Comment by mahagr** [comment]
WP 5.8 has new Widget Blocks, which should be used instead of this. Closing as deprecated feature.
