### ISSUE TITLE
JS Issue with the Menu

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2025]
Hey @w00fz 

[The fix](https://github.com/gantry/gantry5/commit/8ec9dc61b556c34158dec4636211e94bc6fb3f1e) that you applied in 5.4.6 is causing a conflict when using the [UIkit's Sticky Component](https://getuikit.com/v2/docs/sticky.html) (`data-uk-sticky`) to achieve a "Fixed/Sticky Header" behavior.
By the way, the issue is also reproducible when using our "Fixed Header" and "Headroom.js" atoms.
Could you maybe make the JS code a bit more specific so the `height` is not applied to a parent element that is out of the Menu Container (`g-main-nav`)? 😃 

I'm not sure that I explained the issue properly, so I recorded [a short video](https://youtu.be/cKiKQ8uQ9ys) that shows everything.

Thank you 😉

**Comment by w00fz** [comment]
Please give it a try, should be good now.

**Comment by JoomFX** [comment]
Thanks Djamil!
Tested it and everything works perfectly fine 😉
