### ISSUE TITLE
How translate Gantry5 Helium WordPress theme ? 

### ISSUE THREAD

**Issue by alireza-nazari** [gantry/gantry5#2026]
Hello,

I have made new theme base on Helium WordPress theme in persian language (RTL), my language is like Arabic language, everything was good until some none persian words comes up like "Search..." word in the search text box or "Search" button and all comment area, etc.

How to add/override theme language, Gantry5 Plugin and particles in WordPress?

Any help, thanks. 
![download](https://user-images.githubusercontent.com/9654370/27256288-a1e1886a-53c5-11e7-88ff-8922edb5d5ab.png)
![download](https://user-images.githubusercontent.com/9654370/27256304-0c7ed61e-53c6-11e7-8247-fbd6c3bde881.png)

**Comment by newkind** [comment]
Hi,

Please translate it as any other WP theme. Edit the .po file in `wp-content/themes/g5_helium/languages/` using ie. POEdit and save the new translated file as <your-language-code>.po(.mo) ie. pl_PL.po(.mo)
