### ISSUE TITLE
G5 wordpress and Woocommerce

### ISSUE THREAD

**Issue by ToNamPhong** [gantry/gantry5#2027]
Hi there,

I tried to follow this tutorial http://timber.github.io/timber/#woocommerce to implement woo for G5 based theme(Helium).

Here the result I got http://imgur.com/a/cemxp

Both archive.twig and single-product.twig files already exist (views/woo). 

Could you please point me to the right direction?

**Comment by newkind** [comment]
Can you please post on pastebin or somewhere else your `woocommerce.php` contents?

**Comment by ToNamPhong** [comment]
Here you go https://anotepad.com/notes/3k9en6

I copied the code from this doc http://timber.github.io/timber/#point-of-entry-main-woocommerce-php-file

**Comment by newkind** [comment]
Ok so here's the thing. You copied the code directly from Timbers page which isn't going to work 100%. The code itself is good, it's just missing the bits that Gantry requires ie. Gantry initialisation and loading page header. You should check ie. archive.php of Helium to see how it's done there.

Also the file name of the TWIG file should be without `views/` part as that's being handled by Gantry.

Here is how the code of the `woocommerce.php` should look like : https://pastebin.com/raw/NLFMau3B

Please also note that I used the `single-product.html.twig` and `archive.html.twig` filenames. You can of course use the `single-product.twig` and `archive.twig` without the `.html` part, but this is what we're recommending in our themes.

Thanks,
Jakub
