### ISSUE TITLE
Cannot Delete New Configurations

### ISSUE THREAD

**Issue by gospelpowered** [gantry/gantry5#203]
Using RC1 i created a new configuration on the 'Configurations' page which worked fine, i can edit and work with it. However it can't be deleted. I press on the delete button and it asks me am i sure, i click yes and then i get an error 501 Not Implemented. A message below it says "The requested method is not implemented by the server.".

**Comment by mahagr** [comment]
That is odd as I've been deleting all the configurations just fine. I'll take a look on this when I've recovered from this week a bit. :)

**Comment by w00fz** [comment]
I also have had no issues so far nor I've seen any other one reporting this issue. Can you double check this was RC1? The 501 sounds like a Beta 5 known issue, because we have had no Configurations implemented at all.

**Comment by gospelpowered** [comment]
You are right, i didn't work probably because i just updated to RC1 from Beta5 within Joomla as opposed to re-installing. Once i re-installed using the RC1 package i could delete the configurations. Thanks
