### ISSUE TITLE
Set font family URLs to relative instead of hard-coded protocol in HTTPS

### ISSUE THREAD

**Issue by 27Bslash6** [gantry/gantry5#2030]
When compiling CSS, the default font family 'rockettheme-apps' uses a hard coded https:// protocol when the admin section is accessed over HTTPS, but the relative // protocol is generated when the admin is accessed over HTTP.

As there are use cases for having a secured wordpress admin section but insecure frontend, can we get either an option to specify generated URL protocols, or alternately just default to // for all generated elements?

Tested with
Wordpress: 4.8
Gantry: 5.4.13
Helium: 5.4.11

**Comment by mahagr** [comment]
Verified. Sometimes I really wish that WordPress used relative URLs instead of forcing them to always use full address... Yet another workaround needed...

**Comment by mahagr** [comment]
Looks like this one is already fixed.
