### ISSUE TITLE
scss compile error using slash

### ISSUE THREAD

**Issue by manuel-84** [gantry/gantry5#2033]
in a scss file of my theme i have this:

`border-radius: 0 65px 65px 0 / 0 73px 73px 0;`

the result is:

```
Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Array to string conversion").

50
Twig_Error_Runtime 
/var/www/html/wordpress/wp-content/plugins/gantry5/engines/nucleus/views/partials/page.html.twig12
49
Whoops\Exception\ErrorException 
…/vendor/leafo/scssphp/src/Compiler.php2285
48
Gantry\Component\Whoops\SystemFacade handleError
…/vendor/leafo/scssphp/src/Compiler.php2285
47
Leafo\ScssPhp\Compiler opDivNumberNumber
…/vendor/leafo/scssphp/src/Compiler.php2060
```

**Comment by w00fz** [comment]
Is that even a legal value for border-radius? Or are you trying to perform a SCSS math operation there?

**Comment by manuel-84** [comment]
it is a legal value for border-radius
to make it works i had to do a trick, splitting the values like this

```
      border-top-left-radius: 65px 73px;
      border-bottom-left-radius: 65px 73px;
```

**Comment by w00fz** [comment]
The things you learn!
Probably the compiler we use for the scss is not compatible. Glad you sorted though.

**Comment by manuel-84** [comment]
yes, it's probable
so you could look for a better compiler to use in next releases ;)
