### ISSUE TITLE
Block attributes in particle template

### ISSUE THREAD

**Issue by AmibeWebsites** [gantry/gantry5#2035]
Hi, in engine/templates/content/particle.html.twig is there a way to access the block attributes?

Thanks...

**Comment by AmibeWebsites** [comment]
Figured this out... for future reference, any variables set in the block template are available in the particle template.

**Comment by AmibeWebsites** [comment]
Seems particle HTML generated before the block HTML. What calls the particle template to generate the particle HTML if not the block template?

**Comment by w00fz** [comment]
If what you are trying to do is to add custom tags to a block, you can do this via admin in the Tag Attributes section of the block settings.

**Comment by AmibeWebsites** [comment]
Hi @w00fz, thanks for responding. It wasn't what I was trying to do. I was trying to influence the containing div of the particle (.g-particle) based on a setting for the block.

I have managed to achieve what I wanted by taking the particle's containing div into the block template. This assumes that all particles are rendered within a block.

The only thing now I'm unsure of is if the variable _inContent_ (from the particle content template) is available in the block layout template. I'm not sure where with variable is initially set.

**Comment by mahagr** [comment]
Yes, blocks are rendered after particle HTML has been generated. In general, Gantry renders from the leaves towards the root/bottom. This allows code to hide the nested structures if there's nothing to render (particle decides not to show up). Particles are also rendered very early before the layout gets rendered.

`inContent` gets added from module/widget.
