### ISSUE TITLE
Need instructions on how to install gantry via git

### ISSUE THREAD

**Issue by wfsaxton** [gantry/gantry5#2039]
Gantry has made it easy to download everything together via zip file, which is nice.  What I'm really looking for, though, is a way to download and install it all via git.

Normally, I would be able to find a skeleton project and theme project, download them both via git (or gpm) and away I go.  This skeleton, though, doesn't contain basic items like a "config" directory and child files so there doesn't appear to be a way to do this.

So either gantry does this in some different way or its not designed to be downloaded via git?

**Comment by mahagr** [comment]
Right now Gantry uses [hebe](https://github.com/rockettheme/hebe) to install. Just follow the instructions and you should be fine. Just a note, though, that there's no public skeleton -- you need to get the basic skeleton files from the helium skeleton package.

@w00fz You're more familiar with Grav GPM, maybe you have better ideas?
