### ISSUE TITLE
Rokbooster  PHP Notice:  Undefined index: HTTP_USER_AGENT 

### ISSUE THREAD

**Issue by gmng** [gantry/gantry5#2041]
@rockettheme-build 

My apache error log getting a lot of these error or notice messages. How can I avoid this?

[Sun Jul 02 07:48:04 2017] [error] [client 144.76.xxx] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/admin/web/domain/public_html/plugins/system/rokbooster/rokbooster.php on line 78
[Sun Jul 02 07:48:07 2017] [error] [client 144.76.xxx] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/admin/web/domain/public_html/plugins/system/rokbooster/rokbooster.php on line 78
[Sun Jul 02 07:48:07 2017] [error] [client 144.76.xxx] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/admin/web/domain/public_html/plugins/system/rokbooster/rokbooster.php on line 78
[Sun Jul 02 07:48:07 2017] [error] [client 144.76.xxx] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/admin/web/domain/public_html/plugins/system/rokbooster/rokbooster.php on line 78

**Comment by mahagr** [comment]
Not part of Gantry 5, but let's see if this is known issue or fixed.

@kat05 Have you seen this before?

**Comment by mahagr** [comment]
Try if changing the code in /home/admin/web/domain/public_html/plugins/system/rokbooster/rokbooster.php on line 78 to:

```php
        $userAgent       = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : 'unknown';
```
