### ISSUE TITLE
Bootstrap issue with Gantry 5 framework

### ISSUE THREAD

**Issue by SplendidDigital** [gantry/gantry5#2043]
0
down vote
favorite
Installed Gantry 5 Component (5.4.13) and Hydrogen Theme (5.4.13). Getting the message: 0 .transition is undefined: /home/ricky2015/public_html/libraries/fsj_core/assets/css/bootstrap/bootstrap_fsjonly.less on line 6 (http://www.tnssecurities.in)

Read at a place to enable bootstrap (http://freestyle-joomla.com/forum?view=post&post=6226), so did the same through Page Settings page (Hydrogen Theme Home template) by adding Atoms Java Script Framework and enabling Bootstrap framework (http://mylearningaidindia.blogspot.in/2017/07/bootstrap-issue-with-gantry-5-framework.html). However, did not help.

Through the GoDaddy C-Panel, opened the file bootstrap_fsjonly.less that has the following code:

.fsj { @import "bootstrap.less"; // import bootstrap into .fsj only! }

@import "modal-core.less";

Is there a code to define transition?

This happened after Joomla updated to the most recent version 3.7.3 in which Gantry template was working fine earlier. Uninstalled and re-installed but of no help.

**Comment by mahagr** [comment]
Looks like this issue has nothing to do with Gantry 5.
