### ISSUE TITLE
Adding a Custom Style Sheet

### ISSUE THREAD

**Issue by etom-project** [gantry/gantry5#2047]
Hello,

Im ruining wordpress + Gantry framework with  g5_hydrogen (Child theme)
I was able to run my custom CSS without the child theme but once I activate the Child and its working perfectly, the custom style sheet stop working.

Would you please advise?

Thank you,
Tariq

**Comment by paulzz3000** [comment]
I had problems with Hydrogen and a child theme. Switched to Helium and all works fine.
