### ISSUE TITLE
On Joomla / Gantry5 / Helium template, can you use a video as the background image?

### ISSUE THREAD

**Issue by LukeDouglas2** [gantry/gantry5#2052]
I know videos can be used for OwlCarousel HTML as I've reviewed their GitHub page, https://owlcarousel2.github.io/OwlCarousel2/demos/video.html.  However, I have done research and cannot see a way to do this inside the Gantry5 Helium template under Joomla.  Does anyone know if this can be done and, if so, how?

**Comment by N8Solutions** [comment]
I would be interested in this functionality as well!
Maybe @newkind can shed some light on how we can accomplish this.

**Comment by mahagr** [comment]
You can use plain HTML5 to display videos, just Google for it.

I'm closing the issue as being slightly out of the scope, you can easily create your own particle which supports videos.
