### ISSUE TITLE
Question: Passing Variable From Block to Block

### ISSUE THREAD

**Issue by reramjiawan** [gantry/gantry5#2054]
Hello,

I have a question regarding blocked scoped variables, i have a variable set in the particle block that i need available in the stylesheet block but this cannot be done since everything is scoped and putting the variables outside the block does not help either since it wont keep its mutated value.

How to go about this?

**Comment by reramjiawan** [comment]
I have changed my way of adding CSS and JS as described in the Gantry5 Docs. [Docs](http://docs.gantry.org/gantry5/advanced/css-js-twig)

**Comment by mahagr** [comment]
Glad that you were able to solve your issue.
