### ISSUE TITLE
Deprecated code in main.js

### ISSUE THREAD

**Issue by chasiv** [gantry/gantry5#2056]
I'm getting 2 warnings in Firefox from main.js. 

#1 is 'Use of getAttributeNode() is deprecated. Use getAttribute() instead (Line 1:18520). 

#2 is Use of Mutation Events is deprecated. Use of MutationObserver instead. (Line # 1:23392).

**Comment by mahagr** [comment]
You can safely ignore those warnings, they are used to support older versions of IE.

**Comment by dpalic** [comment]
wondering if there are any plans to get rid of this warning in the console?
Over a year passed and the browsers evolved so maybe some workaround could be added to avoid the warning in the console?

**Comment by mahagr** [comment]
Maybe at some point in the future.

**Comment by mizreqat** [comment]
It is simple!
by the way, Chrome will stop supporting:
[](https://developer.chrome.com/blog/mutation-events-deprecation/)

Use MutationObserver instead...
Replacement for your codebase depends on how these events are being used, but as an example:

`// Old mutation event usage:  
target.addEventListener(‘DOMNodeInserted',event => doSomething(event.target));

// Replacement mutation observer code:  
const observer = new MutationObserver(mutationList =>  
  mutationList.filter(m => m.type === 'childList').forEach(m => {  
    m.addedNodes.forEach(doSomething);  
  }));  
observer.observe(target,{childList: true, subtree: true});`
