### ISSUE TITLE
Save button and filed not blinking when changing image in styles.

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2059]
Save button and field not blinking when changing image in styles.
![2017-07-24 23 15 54](https://user-images.githubusercontent.com/10489911/28545486-6ba76188-70c7-11e7-8480-025bf2d5f6b4.jpg)

**Comment by kat05** [comment]
@DamirPecnik which template is that?

I am testing Hydrogen in Joomla and Subfeature only has 2 settings:
- Background
- Text
and both of them have the pulsating circle and the Save button is pulsating too when I apply any changes.

Did you add the 'Image' setting yourself?

**Comment by JoomFX** [comment]
Hey guys,

I've also seen this (seeing it quite often) with our templates.
I haven't noticed any specific pattern, for me it happens mostly in the "Base" outline when modifying an Image Picker field (as @DamirPecnik said above).
Just wanted to say that I can confirm this issue.
