### ISSUE TITLE
Offline page input area stuck at 19px in Hydrogen template

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#2063]
This issue is similar to #1973 
It only effects the Hydrogen template in Joomla and not the Helium template. I have not tested it in either WP or Grav.

Until this is corrected a temporary fix is to add the following code to the custom.scss file.

```css
input {height: auto !important;}
```

Thanks to @scorptech_twitter for bringing this up.

**Comment by newkind** [comment]
I removed the forced height on all inputs and haven't seen any issues so far. If there will be a regression let me know on which elements and I'll do the proper fix for it.
