### ISSUE TITLE
Font size on a custom outline

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2066]
Hello,
I'm new to Gantry 5 and I'm not much of a coder. I'm stuck at this point where I can't figure out how to change the font size on a custom outline. 
I found out how to change the font type (Styles->Core Styles->Body Font) but I can't find the property of the font size.
Can someone help me?
Thank you.

**Comment by sooryakalai** [comment]
Why don't you try changing the font size in CSS by using "font-size : " ?

**Comment by Emtree** [comment]
That way font-size is changed in all outlines and I need in only one custom made outline. Is there a way to target only that outline?

**Comment by marktaylor46** [comment]
There is a class on the body tag that tell you what outline is being used. So you can use that in your CSS selector to target a specific outline. There is also a class that tells you the menu item being used so you can also target just a specific menu item too.

**Comment by JoomFX** [comment]
And you can also add your own class from the "Page Settings" tab and use it in your CSS so the code is applied only to this particular outline.

**Comment by Emtree** [comment]
I found that class "section.entry-content" which I was looking for to change and I added a new class.  Thank you all!!
