### ISSUE TITLE
Outline assignment will not save Grav page language

### ISSUE THREAD

**Issue by hugoaf** [gantry/gantry5#2068]
If I have two pages like:
`/pages/01.home/default.en.md` . (with a title: "home")
`/pages/01.home/default.es.md` .  (with a title: "inicio")

I have two outlines:
First called "home" with english contents, assigned to "home" page
Second called "inicio" with spanish contents assigned to "inicio" page

In G5 administrator, the assignment seems to work, but on front page only the last saved outline assignment is always shown.

In `/data/gantry5/themes/****/config/outline*/assignments.yaml` only the page folder is saved ignoring language.

Probably multilingual works still on progress, but other than duplicate my website in a subdomain, is there a workarround?

**Comment by mahagr** [comment]
Assignments have now language support. Just set the language and the outline will only be used with the selected language.
