### ISSUE TITLE
Theme rt_citadel_child not found

### ISSUE THREAD

**Issue by sirmilord** [gantry/gantry5#2069]
Having issue trying to create a Citadel child theme... I'm following the guide http://docs.gantry.org/gantry5/theme-development/create-child-theme-wordpress, but when I'm activating the child theme I got the following Exception:

Theme rt_citadel_child not found

![child_theme_exception](https://user-images.githubusercontent.com/25770448/29080412-60307c66-7c68-11e7-89b7-38e25b65918b.jpg)

I found similar issue here: https://github.com/gantry/gantry5/issues/1169 and followed the guide, but still got this error. 
Can you please advice or give a link to a child example that works?

**Comment by mahagr** [comment]
You need to rename the Gantry theme class to match the theme name.

**Comment by mahagr** [comment]
@sirmilord Your child theme is missing `gantry/theme.yaml` file. Please copy it from the original theme and edit it afterward.

**Comment by sirmilord** [comment]
Thank you very much! I did the process from scratch step by step once again. 
It looks like the problem was solved after I copied custom folder from parent to a child theme and removed the content of functions.php in child theme.
