### ISSUE TITLE
Improve Outlines

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#207]
As discussed I would like to enhance the Configurations in a couple places:

- [x] `Duplicate` - Duplicating a Configuration should happen in 2 steps
       1. A modal opens with an input field where you can decide in advance what the Title is going to be for new configuration. It should also come prepopulated with the default title like happens now (ie, `Hydrogen - Home (2)`
       2. Once Confirmed the new title, it goes through the actual request of duplicating except now it will get the title in `POST`

- [x] `Create` - Creating a Configuration should be more fancy than it is now and happen in 2 steps
       1. A modal opens with 2 input fields. 1 for the title and 1 for the Preset. Title should be prepopulated and the Preset of Default or Base should be auto selected.
       2. Once Confirmed the title and preset, it goes through the actual request of creating a new Configuration except it will get the title and preset in `POST`

- [x] `List` - We should find a better way to load just the presets image representation instead of having to load the whole layout. This is kind of related to the issue we've been struggling with, where on Windows with XAMP/WAMP the loop in the twig would die due to the `ThreadStackSize` apache issue.

**Comment by mahagr** [comment]
Both ii. points have already been implemented. Variables are unsurprisingly title and preset.

**Comment by w00fz** [comment]
This is true only for 1.ii, in 2.ii we aren't passing any title nor preset, this is just `hardcoded` internally for now.

**Comment by DamirPecnik** [comment]
Add ability to post an image of the Outline in admin maybe?

**Comment by w00fz** [comment]
We have images for outlines already but because of the known thread stack issue we had to fallback to one image only last minute.
