### ISSUE TITLE
Grav duplicates pages and causes fatal errors when saving the mainmenu

### ISSUE THREAD

**Issue by withindale** [gantry/gantry5#2070]
Grav triplicates pages causing fatal errors when saving the mainmenu (see issue #2015). This bug needs to be fixed with haste to make Grav fit for purpose.

![image](https://user-images.githubusercontent.com/17011185/29156230-a6ee6dda-7d98-11e7-86c0-f075f6386251.png)

In the screenshot note the following pages have been duplicated twice:
01.technologies
02.control
03.standards
as
05.technologies
06.control
07.standards
and interspersed with other pages as
07.technologies
08.control
09.standards
Only the second group have default.md files.

Grav corrupted this directory yesterday when I was adding and reordering pages (in the advanced tab of the page editor) in another directory.

**Comment by mahagr** [comment]
I'm not able to reproduce the issue. Is there a reliable way to reproduce this issue?

**Comment by mahagr** [comment]
It looks like the issue happened if you had non-routable and/or non-visible pages in the menu (or having 01. prefix in the folder name).
