### ISSUE TITLE
Particles are not using selected timezone

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2072]
When trying to add Time Zone to date particle it is not working.

Trying this example:
`{{ "now"|date(particle.date.formats|default('l, F d, Y', 'Europe/Paris')) }}`

But its not working!

**Comment by mahagr** [comment]
@DamirPecnik I think you were testing on Joomla?

**Comment by MissTara33** [comment]
I'm also having this issue - Joomla 3.7.4.
Is the Date particle defaulting to UTC, instead of the server timezone set in Joomla's Global Config?

**Comment by mahagr** [comment]
I can confirm the issue -- it should use user setting and fall back to the system one, but it doesn't.
