### ISSUE TITLE
Error. No space between attributes.

### ISSUE THREAD

**Issue by paulzz3000** [gantry/gantry5#2074]
Adding attributes to a particle puts them before classes and without a space between the attributes and class="foo".
For example:
<div  data-continue="true"class="g-block emerge size-100">
There is an extra space before the first attribute though. Methinks it belongs at the end of any added attributes?
It causes validation problems but not sure it affects the rendering at all. It shouldn't, I think. It would be good to fix though.

**Comment by mahagr** [comment]
@paulzz3000 Can you send me a screenshot on what setting you were changing and in which particle?

**Comment by paulzz3000** [comment]
[attributes-error.pdf](https://github.com/gantry/gantry5/files/1223165/attributes-error.pdf)
[particle-screen.pdf](https://github.com/gantry/gantry5/files/1223177/particle-screen.pdf)

It's in a Custom HTML particle. There're a couple of them using different JS data-attributes—emerge.js and ScrollReveal.js.

**Comment by mahagr** [comment]
Should be fixed (in CI builds).
