### ISSUE TITLE
Grav (helium) buttons are always in English no matter the language or overrides

### ISSUE THREAD

**Issue by montagproject** [gantry/gantry5#2075]
Hello

I'm trying to use gantry/helium on GRAV for a site in Polish. It seems that some navigation buttons in blog posts (next post, previous post, read more) are hard-coded in English in Gantry. Even the option in Base Outline to change "read more" default text into something else does not work.

Moreover. The same problem is with dated (forced in English, even with other language set etc)

**Comment by mahagr** [comment]
Translate files in `user/plugins/gantry5/admin/translations/en` and put them into `pl` folder and you should be mostly fine.

**Comment by montagproject** [comment]
Thanks. I'll give it a try

**Comment by montagproject** [comment]
It worked great for blog buttons and form summary. Howeve does not seem to influence date format.

Thanks!

**Comment by mahagr** [comment]
I think that date format is right now locked to whatever you enter in the particle..?

**Comment by montagproject** [comment]
which one?

**Comment by mahagr** [comment]
I mean you can select the format from the particle, though it will always display in that format (it'll not change based on the locale).

**Comment by DominiqueVial** [comment]
If my understanding is correct by doing this, adding translation in plugin directory, all the works lost at plugs update?

**Comment by mahagr** [comment]
Plugin folder will be deleted in most CMS'es during installation. So generally yes, everything added/modified to the plugin folder will be deleted on update.
