### ISSUE TITLE
The gantry5 presets are not working properly...

### ISSUE THREAD

**Issue by p3core** [gantry/gantry5#2077]
Hello...
[WEBSITE](http://server5.nexia.net.in)
My website is using Gantry5 Helium template...
**When I go into configuration!, Preset 4 is appearing twice...**
Please check the screenshots and you will understand what I'm trying to say...
----->1.
[Helium Error 1](https://ibb.co/ncDGBa)
----->2.
[Helium Error 2](https://ibb.co/buTSHF)
The second issue is the presets are not working properly...
When I select Preset 2, it's not changing...
Preset 1 is loading for Preset 2, 3, 4, 5, 6...
Please check the screenshots...

Thank you

Regards,

Praveen Thomas

**Comment by mahagr** [comment]
It was just typo in preset 3. Presets are changing for me just fine. In Joomla you need to enable `Gantry 5 - Presets` plugin to make presets to change in your site.

**Comment by p3core** [comment]
@mahagr ,

There is no Typo in v5.4.16...
Now that the Typo is fixed, Please help me with this one...
**The presets are not changing...**
When I select preset 2, preset 1 gets loaded...
The same happens for preset 3, 4, 5, 6...
I've attached a screenshot for your reference...
Please do help me on this...

![gantrymanagepage](https://user-images.githubusercontent.com/12592119/29391589-0101dbc2-8316-11e7-9c4d-88614492ccb3.png)

Thank you

Regards,

Praveen Thomas

**Comment by mahagr** [comment]
This may be a new issue in latest Joomla as it changed how the extension locking works. Have you upgraded from some older Gantry/Joomla version or is this a new site?

**Comment by p3core** [comment]
@mahagr 
My website was using Gantry 4...  
Upgraded to Gantry 5...  
My Joomla version is 3.6.5...

**Comment by mahagr** [comment]
@p3core Go to plugins and find `Grantry 5 - Presets` plugin (should be under gantry5 type). Make sure it is enabled.

**Comment by p3core** [comment]
@mahagr 
Thanks a lot for the help...  
Don't know how I **missed** enabling Presets plugin!, it's working properly now...  
You're the man...
