### ISSUE TITLE
Grav - childtheme-feature

### ISSUE THREAD

**Issue by mgollmer** [gantry/gantry5#2078]
Hello there, 

I just wanted to try the new feature and created a child theme via cli based on the helium theme. I activated the child theme and got following error: 

![image](https://user-images.githubusercontent.com/26478647/29334761-d0c0f6ea-8208-11e7-8487-8027614b7e80.png)

Seems like he's not able to find the parent theme or something. Am I doing something wrong? Is there anything that need to be done to get this child theme to work ? 

Here is the yaml-code of my g5_helium_child.yaml

streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - themes://g5_helium_child
         - themes://g5_helium

Kind Regards, 
Michael

**Comment by mahagr** [comment]
The new feature requires Grav release (there was a bug on autoloader), which will hopefully be out in a short time.
