### ISSUE TITLE
Change default section id

### ISSUE THREAD

**Issue by paulzz3000** [gantry/gantry5#2079]
Is there any way to use a custom id for a section, instead of the default g-foo, just foo.
When adding JS libraries, such as FullPage.js it'd be a damn sight easier. When adding a section to the yaml file called 'fullpage' it automatically creates 'id="g-fullpage"'.
Apologies if this has been addressed before, couldn't find anything on it.
Thanks.

**Comment by mahagr** [comment]
You can set id manually from the layout yaml file. If there's no id set, it will default to `g-name`. See the docs on how to do it:

http://docs.gantry.org/gantry5/advanced/creating-layout-presets

You might want to try something like this:

```
structure:
  fullpage:
    attributes:
      id: fullpage
```

**Comment by paulzz3000** [comment]
Thank you.

**Comment by paulzz3000** [comment]
That did work. But, when I added a class to that section, via the Layout manager, the id changed to g-fullpage.
Also same when I changed Layout settings to anything other than Inherit from Page Settings.
I could add everything to the YAML file, I guess, but that'd negate the Layout manager.
Am I doing something irregular?

**Comment by paulzz3000** [comment]
Hi - any ideas on this?

**Comment by mahagr** [comment]
No, I need to test it out and take a look what is going on.

**Comment by paulzz3000** [comment]
Hey Mahagr - have you had chance to test this?

**Comment by mahagr** [comment]
Unfortunately, I've been rather busy with another project. I think the issue is that the section name is the same as the id, which makes the code to assume that id wasn't been set at all - which turns it to the default. Try using a different id to the section name and let me know how it goes.
