### ISSUE TITLE
Plugin info page style bug (hidden and overlayed labels)

### ISSUE THREAD

**Issue by drnasin** [gantry/gantry5#2081]
https://ibb.co/bBYrxF

problem comes from scss file which generates height: 43px;
for those elements. Tested in Chrome and FF.

I suggest putting height: inherit; (or removing it). In both cases every "info" label is shown right.
Even the one that was hidden all the time :) (showed on image as empty yellow outline under asset timestamp buttons)..

https://ibb.co/fru0Pv

**Comment by drnasin** [comment]
@mahagr if you're ok with the solution I gave (height: inherit) I can do a PR if you want...

**Comment by mahagr** [comment]
@drnasin Please do so. :) Though, this issue seems to be more of Grav admin issue, not Gantry.

**Comment by mahagr** [comment]
Seems to be fixed in Admin 1.10 or earlier.
