### ISSUE TITLE
Joomla Helium: jQuery conflict with JSN UniForm

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#2082]
I planned a website for a client of us with the Helium Template. Unfortunately the template load his own jquery.min.js from the folder /js/jui . A form of JSN Uniform will not load if this file is loaded. If i delete or rename this JS-File all is working correct.

But after an update this file remains and the error returns. Is there any way to solve this problem?

Greetz hacki65

**Comment by newkind** [comment]
You can disable the built-in jQuery in Page Settings tab -> JavaScript frameworks on the bottom. Please note that particle can still force loading built-in jQuery even if you have it disabled in the Atom, so if you still see it in the page, you might need to modify you particles code.

**Comment by mahagr** [comment]
The template doesn't load its own JQuery -- Joomla does. Gantry just tells Joomla that it needs JQuery if any of the particles use it. Joomla components/modules/plugins do the same, so this issue is not unique to Gantry.

I consider this to be a bug in JSN Uniform. If it wants to use its own version of JQuery, it has to deal with it.

**Comment by hacki65** [comment]
Sorry guys, this is bullshit. The jquery.min.js will load from gantry without any option to disable it. The particles "contenttabs" & "owlcarousel" seems need this but the particle works if i delete the jquery.min.js.
BTW: i dont use this particles !!! - but jquery will be load regardless.

With template hydrogen there is no issue. But i want use helium for the client.

Please see screenshots:

Here the form will not be loaded:
![screenshot 2017-08-24 14 57 52](https://user-images.githubusercontent.com/20481746/29668048-163cf016-88df-11e7-9d40-08bbd6d2d434.jpg)

Here is the page sourcecode:
![screenshot 2017-08-24 14 58 30](https://user-images.githubusercontent.com/20481746/29668086-37f1df14-88df-11e7-9f1f-5e6b9277f717.jpg)

**Comment by mahagr** [comment]
I just checked this and there's extra file in the template called `js/jui/jquery.min.js`. It looks like Joomla has added support for JS overrides in templates, so if the file exists, that is the one which gets used.

Looks like I need to add check if the file exists into the installer and delete the file during update.
