### ISSUE TITLE
Problem with "&#8217 " instead of apostrophe in WordPress Posts 

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2085]
The code "&#8217 " appears instead of apostrophe only in titles. How do I fix this? 
Screen shot is attached.
![apostrophe](https://user-images.githubusercontent.com/16117229/29493402-35967a74-8595-11e7-9117-b52eb9d77a5c.jpg)

**Comment by mahagr** [comment]
@newkind Looks like titles have already been escaped in WP.

**Comment by kat05** [comment]
I've just tried this on a Helium RocketLauncher on WP 4.8.1 with Gantry 5.4.17 and I can't replicate the issue, please see pic.

![g5_apostrophe](https://user-images.githubusercontent.com/5719486/30319998-a5cdcc7e-97b1-11e7-8699-50d0b9140647.jpg)

**Comment by Emtree** [comment]
I fixed the problem somehow. I just turned off some items in Assignments tab

**Comment by Emtree** [comment]
It is not fixed. I got the same error again. I don't know how, but it is irritating. Yesterday I was checking some Page Title to On/Off and I got the same problem, and I don't know how to fix it. Do you think that this might be happening because of a locally installed WordPress?

**Comment by Emtree** [comment]
![untitled](https://user-images.githubusercontent.com/16117229/30519827-05a1fa48-9ba0-11e7-9ee0-f055cb2b20ce.jpg)
But look at this, I have the problem in this one title, but not in the other oO

**Comment by mahagr** [comment]
Above two titles are using different unicode characters. You have likely used different character in each of the title.

Let me see if I can easily fix this...
