### ISSUE TITLE
Grav Gantry Child-Theme Doc?

### ISSUE THREAD

**Issue by mgollmer** [gantry/gantry5#2086]
Hi there, 

do you have any short explanation of how the new childtheme feature works? That would be awesome!

Kind regards, 
Michael

**Comment by mahagr** [comment]
Just run `bin/plugin gantry5 child-theme` command in CLI.

It will ask you two questions and creates the child theme for you. After that just change the theme for the site and you're good to go. :)

**Comment by mahagr** [comment]
@RyanMPierson can you add this to the docs?

**Comment by mgollmer** [comment]
Hello there, 

and then the child theme folder acts like the custom folder? Or do I got wrong ?

**Comment by mahagr** [comment]
It acts like any Grav child theme. But yes, it replaces the custom folder.

**Comment by drnasin** [comment]
Yeah docs would be nice on this. I am already working on a theme (photon) and wanted do to test the new feature but I saw that only base outline and system outlines are available in my child theme. None of my other layouts were copied. Is that per design?

**Comment by mgollmer** [comment]
Hey there, 

I guess you find your data in /user/data/gantry/themes/.... Maybe you just need to create a folder for your child theme in there. 

Regards, 
Michael

**Comment by mahagr** [comment]
@drnasin Yeah, you basically need to copy files from `/user/data/gantry/themes/parent` to `/user/data/gantry/themes/child` to keep all the settings from the parent theme. Might be something I could add to the CLI script...

**Comment by mgollmer** [comment]
@mahagr yeah, would be nice if there would be an option for keeping the previous made settings of the parent theme.

**Comment by mahagr** [comment]
Option has been added.

**Comment by mahagr** [comment]
```
> bin/plugin gantry5 child-theme --help
Usage:
  child-theme [options]
  child-theme
  childtheme

Options:
  -p, --parent=PARENT   Parent theme name
  -c, --child=CHILD     Child theme name
  -l, --clone           Clone outlines and configuration to the child theme
  -L, --no-clone        Do not clone outlines and configuration to the child theme

Help:
  The child-theme creates a new child theme from an existing Gantry theme
```

If you run it just by bin/plugin gantry5 child-theme it'll ask you some questions:

```
> bin/plugin gantry5 child-theme
Creating new child theme

Enter parent theme name: g5_helium
Enter child theme name: new_helium
Clone outlines and configuration to the child theme [Y/n]: 

Success! Child theme new_helium created.
```

**Comment by RyanMPierson** [comment]
done and done. http://docs.gantry.org/gantry5/theme-development/create-child-theme-grav
