### ISSUE TITLE
MD5 or SHA1 hash values for Template Files with Check Page?

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#209]
Make a check in Gantry5 Admin if any files have been altered in template/theme from the original ones. and list them, add a link to page with list in Extras Drop-down maybe?

This would be good for

**Comment by mahagr** [comment]
That would allow us to prevent upgrades or allow us to move overridden files into their proper locations on update.

**Comment by w00fz** [comment]
This is something we always have had. The build was taking care of it automatically. We are just a bit behind with the automated builds for G5 and the G5 templates, as soon as that's hooked up again, it will store md5 like it always did.
Then in the future we could add some mechanism to detect changes before updates and such.

**Comment by w00fz** [comment]
I just added checksums for Gantry 5 (`component` (admin / site), `library`, `plugins`, `module`, `nucleus`) and Hydrogen. Filename is `MD5SUM` at the root of each.

For now we'll keep generating these checksums with Gantry and the templates, in the future we'll see about actually using them, have a look at the CI Builds.
