### ISSUE TITLE
meta data 

### ISSUE THREAD

**Issue by MKTGExperts** [gantry/gantry5#2090]
Per http://ogp.me/ and https://developers.facebook.com/tools/debug/

The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: og:title, og:locale, og:image, og:description, og:url, fb:app_id, og:type
If I view source code of my site i see the following, name should   rokcomments has the word correctly on /www/plugins/content/rokcomments/rokcomments.php:293: <meta property="fb:admins" content="'.$fb_moderatorid.'"/>
line 294 is also correct.

<meta name="og:locale" property="og:locale" content="en_US" />

/media/gantry5/engines/nucleus/templates/page_head.html.twig   line 68 is where the issue is.

**Comment by mahagr** [comment]
I think we need to check the value and pick which attribute (name or property) should be used instead of just blindly adding both. It works though as the property attribute is there.
