### ISSUE TITLE
Change the order of particles into a gantry template

### ISSUE THREAD

**Issue by lucapada** [gantry/gantry5#2091]
Hi!
I'm working on a site based on Joomla 3.7.5.
I've got three particles (columns): one at left, one at center and another one at right into the same row. 
I want to see the content into the center particles first of the content of left and the one of right, only when I'm watching the website from mobile devices...
Simply, I wanna change the order of the columns when the user agend is a mobile device.
Could you help me?
Thanks a lot!

**Comment by N8Solutions** [comment]
Hello Lucapada,

I know you can change the collapse order so that it goes right-to-left instead of left-to-right. However, making a change so that it goes Center, then left, then right... not sure if it can be done.
Maybe @JoomFX can has an idea.

**Comment by mahagr** [comment]
As Gantry is using flex css3 extension, you can likely use it to change the ordering.

**Comment by lucapada** [comment]
Thank you so much! Thanks to yours hints I solved my problem!

**Comment by N8Solutions** [comment]
@lucapada Would you care to share your solution? This  way others can benefit from it as well.
