### ISSUE TITLE
404 error for media/gantry5/engines/nucleus/css-compiled/joomla.css.map

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2092]
Safari generates 404 errors in its console for these 2 files:

media/gantry5/engines/nucleus/css-compiled/joomla.css.map
media/gantry5/engines/nucleus/css-compiled/nucleus.css.map

after the latest gantry update

**Comment by mahagr** [comment]
@w00fz Looks like something is not working in our phing build script.

**Comment by mahagr** [comment]
@joomlabeat Gantry 5.4.17 should be fine.

There is still issue in our build scripts which needs to be solved.

**Comment by vincowl** [comment]
@mahagr Seems this bug reappeared in G5.4.19. Cf #2149 and #2151

**Comment by joomlabeat** [comment]
I confirm this is the case as I saw those 404 coming back with latest G5

**Comment by w00fz** [comment]
These are only errors when the developer panel and source maps are on.
Nothing to worry about. Until we solve the clamav false positive error in compressed js, source maps are not going away.

You can safely ignore the missing maps errors or if it really bothers you can edit those css files and remove the commented line that specifies the source maps file at the bottom.

**Comment by Marktwert** [comment]
issue is back with update to 5.4.28.

Safari generates 404 errors in its console for these 2 files:

media/gantry5/engines/nucleus/css-compiled/joomla.css.map
media/gantry5/engines/nucleus/css-compiled/nucleus.css.map

after the latest gantry update

**Comment by uuuguuur** [comment]
i `have` same problem 

[Error] Failed to load resource: the server responded with a status of 404 () (joomla.css.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (nucleus.css.map, line 0)

**Comment by TheMageKing** [comment]
I am having the problem again with nucleus.css
The requested URL /media/gantry5/engines/nucleus/css-compiled/nucleus.css.map was not found on this server.
