### ISSUE TITLE
Gantry does not work properly with joomla events

### ISSUE THREAD

**Issue by dpalic** [gantry/gantry5#2093]
In Joomla typically the plugins are using common joomla events to identify any important operation.
E.g. in Gantry if you do any modification of the style and you save (save is important) no events get fired.
This would be no issue, if we would not like to integrate well into gantry templating. E.g. on any change of gantry we want to trigger a different plugin to do a operation.
Am I missing something or is gantry really not using the events at all?
If no events case, what is the recommended way to integrate properly into gantry?

**Comment by mahagr** [comment]
Gantry fires Joomla events when styles are changed (duplicate, renaming etc) or generally always when the changes affect Joomla. It also fires its own events when any action is performed in Gantry admin, though these events are internal to Gantry, so you need to hook into those events instead of relying on Joomla ones.

What do you have in your mind?

**Comment by dpalic** [comment]
We want to do some processing in a custom plugin, so we need a notice from gantry as soon as the gantry was edited (anything changed)
can you point us to a documentation or even better to some example code?
Also is there any doc with the full list of gantry events?

**Comment by mahagr** [comment]
There are following events in Joomla:

Plugin group: gantry5
* `onGantry5ThemeInit($theme)`
* `onGantryGlobalConfig(&$global)`
* `onGantry5UpdateCss($theme)`
* `onGantry5AdminInit($theme)`
* `onGantry5SaveConfig($data)`

Additionally Gantry 5 callls these events directly:
* onRenderModule
* onContentBeforeSave
* onContentAfterSave
* onContentBeforeDelete
* onContentAfterDelete
* onExtensionBeforeSave
* onExtensionAfterSave
* onContentCleanCache

Rest of the events are called by Joomla when saving JTable for template styles, menus etc..

I see that there are some Joomla events missing, though you can still hook to Gantry's own event listener (symfony/event-dispatcher) which can be accessed by Gantry DI: 

```php
$gantry = \Gantry\Framework\Gantry::instance();
/** @var EventDispatcher $events */
$events = $gantry['events'];

$listener = new EventListener; // Your listener class.
$events->addSubscriber($listener);
```

Events are:
* `theme.init`
* `admin.init.theme`
* `admin.global.save`
* `admin.menus.save`
* `admin.styles.save`
* `admin.layout.save`
* `admin.assignments.save`
* `admin.page.save`
* `admin.settings.save`

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/faq/joomla-events

Added to docs. Improvements to come.
