### ISSUE TITLE
Using "bourbon" to apply CSS styles online.

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#2094]
I'm creating a particle for Gantry 5.
And I'm inserting styles online like this:

{% assets in 'head'  with { priority: 0 } %}
    <style>
    .g-video{ 
    display:flex;     
    }
    </style>
    {% endassets %}

**But I want to use the browser prefixes for the flex property usign "bourbon".** 
Try this:
{% assets in 'head'  with { priority: 0 } %}
    <style>
    .g-video{ 
    @include display(flex);   
    }
    </style>
    {% endassets %}

**But I print this in the code:**
![view-source localhost masterpets3 nosotros](https://user-images.githubusercontent.com/9434043/29594429-6b428d92-8776-11e7-92e5-74540419e8cd.png)

Some solution for this situation. Since I do not want to be manually creating the browser prefixes.

**Comment by newkind** [comment]
Bourbon code needs to be compiled from SCSS to CSS. When you add code via `{% assets %}` there is no compilation in between. Gantry just takes the code and renders it in the `<head>`. This means that it's not gonna work with Bourbon.

You can either add it to the regular `.scss` files and then it would compile or if you care about having it in the `<style>` tag simply use a website like https://autoprefixer.github.io/ to generate your code with all browser prefixes.

**Comment by mahagr** [comment]
In Gantry this is supported inside assets tag:

```html
<link rel="stylesheet" href="myfile.scss" type="text/css"/>
```

**Comment by Mineslu** [comment]
Hello,
I tell you my situation:
1) I have created a particle with several options. One of them is the possibility of defining the background color of a block. In this way:

name: Media Plyr
description: particular que muestra los datos de una persona.
type: particle
icon: fa-play-circle

configuration:
  caching:
    type: static

form:
  fields:
    enabled:
      type: input.checkbox
      label: Publicado
      description: Habilitar o deshabilitar esta partícula.
      default: true
    
    Color:
      type: input.colorpicker
      label: Color
      description: 'Define a color.'


2) Now, I will place the color that the user chooses as background color for the particle. So:

{% extends '@nucleus/partials/particle.html.twig' %}
 {% block particle %}
  {% assets in 'head'  with { priority: 0 } %}
     <style>
       .**fondovideo**{
     background:{{particle.Color}};
      }
     </style>  
    {% endassets %}
 <div class="**fondovideo**">TEXT</div>
{% endblock %}


This is where I want to use bourbon ... to create my online styles with browser prefixes. Try to place this because I want to use flexbox:
 <style>
      .fondovideo{
     @include display(flex);
   }
     </style>
____________________________
But no results.
Thank.

**Comment by newkind** [comment]
Just keep the dynamic color inline like you have, but move the flex part to the scss file where you can use bourbon.

**Comment by mahagr** [comment]
I agree. In this case, you can easily move flex rule into CSS file and just use an HTML class instead. Dynamic part can still be put inline. The issue why I'm not keen to allow inline SCSS compilation is that it is really slow. With caching it may work in some time in the future, but right now I wouldn't recommend it even if it was possible (likely you could somehow do it).

**Comment by Mineslu** [comment]
Hello,
The problem is that I try to retrieve a value created in a particle from my custom.scss file and I could not.
In my scss file put:

@import "dependencies";
 .fondovideo{
background:**{{particle.Color}}**;
} 
</style>

Does anyone know if I can get the value that a user defined in an option from a particle and use it from an .scss file?

**Comment by newkind** [comment]
Just what we wrote above. You keep the dynamic colors from particles inside of the {% assets %} and you just move the non-dynamic stuff like flex to the scss file.

**Comment by Mineslu** [comment]
Hello,
It would be great if we could use the value returned by the particles within the custom scss.
I have seen that within custom.scss variables are used, for example: "$content-padding" or "$content-margin"
Do you think I can do the same with the value of my particle's options?
Thank

**Comment by mahagr** [comment]
Variables set in particles cannot be used in SCSS, mostly because of there can be multiple instances of the particle with different values, making it technically impossible to use single CSS file as it would contradict itself. You should be using inline CSS instead. And yeah, as I said, inline CSS does not support SCSS.
