### ISSUE TITLE
Merge 2 menus in one only on for mobile devices.

### ISSUE THREAD

**Issue by lucapada** [gantry/gantry5#2095]
Hi, always me...! 
I'm developing a joomla site with Joomla 3.7.5 and Gantry 5.4.16 I have 2 menus in 2 different areas, one in the header and one in the navigation. They're both set to mobile target, but when I use a mobile device I only see one of them in the mobile menu, the one of header. The problem is I want to see both on mobile menu. How can I do it?

**Comment by mahagr** [comment]
Gantry only supports a single menu in mobile menu.
