### ISSUE TITLE
Joomla Helium: jQuery conflict with JSN UniForm (Second try)

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#2096]
**Sorry, it helps not if the original issue will be closed. I have answered in original post #2082 - here is the content:**

Sorry guys, this is bullshit. The jquery.min.js will load from gantry without any option to disable it. The particles "contenttabs" & "owlcarousel" seems need this but the particle works if i delete the jquery.min.js.
BTW: i dont use this particles !!! - but jquery will be load regardless. AND: In Page settings there is NO JavascriptFramework-Atom loaded.

With template hydrogen there is no issue. But i want use helium for the client.

Please see screenshots:

Here the form will not be loaded:
![screenshot 2017-08-24 14 57 52](https://user-images.githubusercontent.com/20481746/29668048-163cf016-88df-11e7-9d40-08bbd6d2d434.jpg)

Here is the page sourcecode:
![screenshot 2017-08-24 14 58 30](https://user-images.githubusercontent.com/20481746/29668086-37f1df14-88df-11e7-9f1f-5e6b9277f717.jpg)

I hope this can be solved... thanks.

hacki65

**Comment by mahagr** [comment]
Should be already fixed.

**Comment by mahagr** [comment]
@hacki65 Thanks for your detailed description of the issue and sorry that I didn't believe it; I was not aware of the file override. Thankfully the issue is now fixed and will be released soon.
