### ISSUE TITLE
The "Twig_Extension_Core" extension is not enabled

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2097]
Hi,
I need to use the the **PBBooking** component on a client site (with the latest Joomla & Gantry versions) but I receive the following error:

> Error displaying the error page: The "Twig_Extension_Core" extension is not enabled.: The "Twig_Extension_Core" extension is not enabled.

I repeat the test on a second site (only Joomla, without Gantry) and the error is gone.
Now, suppose that is a gantry issue, isn't ?

Thanks

**Comment by mariantanase** [comment]
It seems that the error message is caused by a conflict between the twig library used by Pbbooking and the twig library used by Gantry.
https://hotchillisoftware.com/kbarticle/front-end-wont-display-error-loading-error-page-message/

**Comment by mahagr** [comment]
Yeah, there can only be one version of the library -- you can delete the older one (from pbbooking).

There's really nothing else you can do.
