### ISSUE TITLE
Changing Base Configuration styles do not update look of the site

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#21]
I change from Preset1 (default) to Preset4 and then "Save Styles", OK.
After that when I want to revert back, and change from Preset4 to Preset1 > "Save Styles" - > nothing !
Still remain the Preset4. Even when cleared cache. It seems that is a file permission issue.

I think I found where is the glitch.
When access from:
Extensions > Template Manager > Hydrogen Home > Styles, the URL is:
http://localhost/joomla/administrator/index.php?option=com_gantry5&view=configurations/10/styles&style=10
This is OK, the changes are working fine.

When access from:
Components > Gantry 5 Themes > Configure > Styles, the URL is:
http://localhost/joomla/administrator/index.php?option=com_gantry5&view=configurations/default/styles&style=10
When make some changes nothings happent.

**Comment by mahagr** [comment]
If you stay at Hydrogen Home, you should be able to change styles however you want to.

There is known issue that default styles do not get applied unless you compile each configuration (joomla layout) separately. We will address this issue on beta2.
