### ISSUE TITLE
Character encoding on translation file

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2100]
Hi,
I started the translation of **it-IT.com_gantry5.ini** (administrator\components\com_gantry5\language\it-IT\). It seems that accented characters are not displaying correctly.

**Sample 1** (without encoding). `GANTRY5_PLATFORM_INHERITANCE="Ereditarietà"`
![character1](https://user-images.githubusercontent.com/3976174/29818182-6e7c2e38-8cbb-11e7-89c9-952841d41a4c.png)

**Sample 2** (with encoding).  `GANTRY5_PLATFORM_INHERITANCE="Ereditariet&agrave;`"
![character2](https://user-images.githubusercontent.com/3976174/29818221-8fe60e40-8cbb-11e7-95a8-a724c3bdb1cf.png)

How can I make accented characters appear correctly ?
Thanks

**Comment by mariantanase** [comment]
I notice another issues, the layout tab is not displaying correctly and some other functions from Gantry Admin has not working anymore (e.g. changing from one Outline to another from dropdown list has no effect).
If I delete the it-IT.com_gantry5.ini file, all turns back to normally.

**Comment by mahagr** [comment]
You are using wrong character encoding -- you should always save your files in UTF-8 / no BOM.

**Comment by mariantanase** [comment]
ok, thanks
