### ISSUE TITLE
TypeError: Cannot read property '0' of null - frontend article editing - HYDROGEN

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2102]
A member raised this in the RT forum but I have been able to reproduce the issue in a HYDROGEN Gantry 5.4.17 local installation.

How to reproduce:
1. install Joomla 3.7.5 with blog data
2. Install Gantry 5.4.17
3. Install Hydrogen with DEMO data
4. Add a new menu item "test", single article, pointing to any article.
5. In "content" in backend change options to show "image & links" in frontend
6. go to frontend, and login
7. Go to "test" menu item and click on "edit" to edit article
8. Click on "image & links".
9. Select any image - you will see two JS errors in the console.

![2017-08-30_15-41-18](https://user-images.githubusercontent.com/11683218/29878180-bc315aac-8d99-11e7-950c-938c1ca63d6b.png)

Forum link http://www.rockettheme.com/forum/gantry-framework/271824-typeerror-cannot-read-property-0-of-null

**Comment by kat05** [comment]
I am also able to replicate the .js error with Hydrogen. There is no error when using Beez3.

**Comment by gaelicwinter** [comment]
Thank you all!
