### ISSUE TITLE
Gantry template - removing module padding/white space

### ISSUE THREAD

**Issue by hitman2017** [gantry/gantry5#2104]
Hi Guys, I got my website made through Gantry G5_hydrogen. It looks nice but I find that there is a lot of space between the modules. I need to remove the padding/white space. Please advise how I can achieve this.
Thanks in advance.

**Comment by mariantanase** [comment]
On the layout tab, you should go to the settings of the sections and there you can add variations as you like : nomargin, nopadding

**Comment by mahagr** [comment]
Or you can alternatively create CSS overrides to make margins and paddings smaller. The extra space is part of the default design.

**Comment by mahagr** [comment]
Closed due to inactivity.

**Comment by Maundler** [comment]
I noticed you closed this, but I have the exact same question :)

I have already added a css code on the syle.css and on the theme editor as well and have done the following code
`.header-no-padding1{
	margin: 0;
	padding: 0;
	border-spacing: 0;
	border-collapse: collapse;
	
}`

And I have added this class to the navigation section on the particle of Gantry5 and it does nothing, the space remains... A bit of help here?

I have the header with the logo and menu, so far so good, after that, I have included a slider on the navigation particle and have added the css class on the navigation section, but it seems to do nothing.
