### ISSUE TITLE
'Particle Defaults' tab not showing right after Installation

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2105]
I've seen this in Joomla with both Hydrogen and also Helium 5.4.17, right after installing it.

Please see pic, after installing the Sample Data, at first only the tabs
- Styles
- Layout
- Page Settings
are showing.

The tab
- Particle Defaults
is missing until you select any of the other tabs.

No biggie but thought I'd mention it. :)

Not tested in WP or Grav yet.

**Comment by kat05** [comment]
![g5_particledefaults](https://user-images.githubusercontent.com/5719486/29971366-432bc4e0-8f28-11e7-8e28-c45f28b0fc16.jpg)

**Comment by mahagr** [comment]
Maybe the line shouldn't be shown at all, but this is such a small thing and happens only once, so it's really not worth of fixing.
