### ISSUE TITLE
Incorporate "responsive-font" mixin into Gantry 5 core

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2106]
A number of RT templates now use the "responsive-font" mixin. When members copy particle from one template to another they often forget to copy the responsive-font mixin from _utilities.scss. 

I believe we should now incorporate this mixin into core Gantry 5 because of the above and because it is now commonly in use in most RT template now (and the code is the same).

**Comment by mahagr** [comment]
@newkind Can you take a look on this?

**Comment by newkind** [comment]
Yep, will do.

**Comment by paulzz3000** [comment]
Hi @marktaylor46 
Could you tell me more about this mixin please? Can't find any docs anywhere. Did it make it into Nucleus?

**Comment by marktaylor46** [comment]
Yes it is now part of CORE G5. The mixin can be found in /media/gantry5/engines/nucleus/scss/theme/mixins/_typography.scss (in Joomla) and the variable for it is initialised in /media/gantry5/engines/nucleus/scss/configuration/nucleus/_typography.scss

It should be fairly obvious how to use the mixin if you look at the code, but you can find practical examples of usage in templates such as Aurora.

Regards, Mark.

**Comment by paulzz3000** [comment]
Thanks Mark! Much appreciated.
