### ISSUE TITLE
text in "to top" particle is hard coded

### ISSUE THREAD

**Issue by Bokelmann** [gantry/gantry5#211]
the text in "to top" particle is hard coded. Should be a textfield that one can change (like "nach oben" in german). Also would be nice that a "icon only" option with a button class would work right of the box ...

**Comment by w00fz** [comment]
Cheers, this is added now and also allows HTML so you could write stuff like: 
`<i class="fa fa-chevron-up"></i> To Up` or whatever is desired. By default it's going to be simply "To Top".

![totop](https://cloud.githubusercontent.com/assets/11734/7553234/6dcd8076-f6a0-11e4-81a3-0b7287fa4cfb.jpg)
