### ISSUE TITLE
Additional info for Menu Editor documentation

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2112]
Howdy Ryan,

I was just playing with a Grav Flux RocketLauncher.

In the Menu Editor, i added more dropdown columns to the 'Features' menu item and spread out the child items across 5 columns, then saved and expected the frontend to display the 'Features' dropdown in 5 columns. It still just displayed all items in 1 column though.

I just could not get it to work until Karol told me I would have to set 'Dropdown Style' to 'Extended' which I did, but on frontend I still only got 1 column.

With Karol's help I then figured out that I also had to change the setting for 'Dropdown Width' which was 220px by default. Once I made this larger or set to 'Auto', then I got the correct number of dropdown columns on frontend.

I think we need to note this somewhere in the docs, it was driving me crazy, lol.

So 
1) 'Dropdown Style' can't be 'Simple' and 
2) 'Dropdown Width' needs to be 'Auto' or you will keep seeing all child items in only 1 column or somehow scrambled across whatever width is available in the dropdown.

![g5_dropdown](https://user-images.githubusercontent.com/5719486/30324542-b94c86c2-97c1-11e7-89ab-8ee50c731d54.jpg)

**Comment by RyanMPierson** [comment]
In Progress

**Comment by RyanMPierson** [comment]
Completed here: http://docs.gantry.org/gantry5/configure/menu-editor#menu-item-settings
