### ISSUE TITLE
Add Info about Theme installation via 'Tools'

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2113]
Especially for our Grav RocketTheme club themes it's worth mentioning in the docs that they can be installed through 'Tools', please see pic.

![g5_tools_directinstall](https://user-images.githubusercontent.com/5719486/30325473-30a9b0c0-97c5-11e7-8879-8a4739b98274.jpg)

I have not found this info in the docs, if it's there already, let me know.

The club theme docs (Flux, etc) on rockettheme.com currently link to this page in the Gantry documentation:
http://docs.gantry.org/gantry5/basics/installation#installing-a-gantry-theme

**Comment by RyanMPierson** [comment]
In Progress

**Comment by RyanMPierson** [comment]
http://docs.gantry.org/gantry5/basics/installation#method-b-tools-panel

Complete
