### ISSUE TITLE
Inheritance position: static not working when multiple sections are in one block of container

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2114]
This is how inheritance displays currently with multiple sections in one block of a container:

![screen shot 2017-09-13 at 2 37 20 pm](https://user-images.githubusercontent.com/5002814/30397122-6581423c-9891-11e7-9a09-8e072260990a.jpg)

Need to consider adjusting "position: static" here:

![screen shot 2017-09-13 at 12 46 17 pm](https://user-images.githubusercontent.com/5002814/30397367-45a273a4-9892-11e7-9a84-19f72e5f456b.jpg)

**Comment by simmonsr** [comment]
I put in a fix that should work. Please check it out when you get a chance @mahagr

**Comment by marktaylor46** [comment]
Confirmed fix with CI build :)

**Comment by mahagr** [comment]
@w00fz Are you happy with this change? It will change the looks of inheritance but fixes issues.
