### ISSUE TITLE
Gantry 5 admin menu bar disappears in IE Edge

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2118]
See screenshot. This is easy to reproduce in IE Edge 40 and G5.4.17 - I use "Photon" template too.

![2017-09-16_12-36-16](https://user-images.githubusercontent.com/11683218/30511970-0f0535e2-9adc-11e7-9ae8-8eab29f7989d.png)

Go to Gantry 5 admin.
Select "menu" to go to Gantry 5 menu editor
then press the "back to setup" button.... menu bar disappears.

A refresh of the page will reinstate the menu bar again.

See Video https://www.screencast.com/t/tk9tNVblzPK5

Forum Topic http://www.rockettheme.com/forum/joomla-template-photon/272135-backend-theme-menue-issue-proton

**Comment by mahagr** [comment]
@w00fz @newkind @hexplor Can someone of you to take a look on this one? It looks like some kind of CSS issue.

**Comment by newkind** [comment]
@w00fz this is something for you - Edge is doing something quirky with JS which causes the top value of -50000px to be persistent.

https://monosnap.com/file/32EDcDS1HFBiINgJ0Ap9O9nqmb9OWv.png

**Comment by marktaylor46** [comment]
This is now broken in IE11 see screenshots.

![2017-09-20_13-37-05](https://user-images.githubusercontent.com/11683218/30644054-08619638-9e09-11e7-81ef-15271925e8be.png)

![2017-09-20_13-37-37](https://user-images.githubusercontent.com/11683218/30644062-0d38c550-9e09-11e7-8fac-e58b12326629.png)

**Comment by w00fz** [comment]
I am not sure why this was an issue in IE in the first place and my fix for IE edge was by writing the same code in a different format which doesn't make sense.
I wouldn't worry about IE11 too much since Microsoft declared end of life for it on January 12, 2016.

Microsoft Edge seems to work fine now with my fix.
