### ISSUE TITLE
Entry-title to H1

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2119]
How to change entry-title h2 tag to h1 for all posts?
![untitled](https://user-images.githubusercontent.com/16117229/30512286-2f6186aa-9aec-11e7-8758-d6d29c7a6080.jpg)

**Comment by mahagr** [comment]
Is this in WP?

**Comment by newkind** [comment]
Yes it is. You need to edit/override theme files and edit the `views/partials/content(-page, -single).html.twig` files.

**Comment by mahagr** [comment]
Sorry, bad reference above.

**Comment by Emtree** [comment]
Thank you!!
