### ISSUE TITLE
Module positions not showing up after installing/updating theme

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#212]
We forgot to add default module positions to Hydrogen / Callisto in manifest. The positions only appear after saving a layout.

**Comment by mahagr** [comment]
Also affects updates.

**Comment by w00fz** [comment]
So what is involved to fix this?

**Comment by mahagr** [comment]
Not much really. When you update theme, we just need to run a command.

The issue is that we haven't loaded Gantry when in installer, so some extra steps may be needed to properly initialize it.

**Comment by mahagr** [comment]
We have had this for too long time, needs to be fixed soon.
