### ISSUE TITLE
Earlier versions of Gantry and Helium required

### ISSUE THREAD

**Issue by sooryakalai** [gantry/gantry5#2123]
Dear developers,
I have been waiting a long time for "https://github.com/gantry/gantry5/issues/2065" this issue to get resolved. 
I respect and appreciate all your efforts , contributions and support but meanwhile I would like to run earlier versions of Gantry and Helium that works till the developers release an update.
To be specific, 
Helium ( v5.3.2 / g5_helium)
Gantry Version vdev-4933c8ba3
Timber Version 1.1.2

Can anyone guide me where to find these repositories ?

Regards,
Soorya

**Comment by JoomFX** [comment]
Hi Soorya,

You can download all Gantry version from [here](https://github.com/gantry/gantry5/releases).

**Comment by mahagr** [comment]
I don't think that going to earlier version helps you as the bug has been there all the time.

Best bet would be to delete/rename the `custom/config/menu` folder if it fixes the issue.

**Comment by sooryakalai** [comment]
@mahagr can you please elaborate on renaming the custom/ config/menu folder ?
Do I loose any data or styling by doing so ?

**Comment by mahagr** [comment]
You will loose the customized menu settings from Gantry itself, but at least it would "fix" your menu issues. Try it out, you can always restore the files back.
