### ISSUE TITLE
Particle that will show the name of the user who is logged in

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#2124]
Hello,
I'm messing with a problem.
I am creating a particle that will show the name of the user who is logged in.
How do I recover the name of the user who is logged in within a particle ?.
In such a way that it looks like this:
If you are a visitor (Not logged in):
Hello visitor.
If you are logged in:
Hello "User Name"...
![custom-login-04](https://user-images.githubusercontent.com/9434043/30769858-2f8c980e-9fe7-11e7-92c1-5b6a7028992e.gif)

**Comment by mariantanase** [comment]
Take a look on this topic: https://github.com/gantry/gantry5/issues/1189

**Comment by mahagr** [comment]
This depends on which CMS you're on. But basically, you just call the CMS to get the current user and display his name if he's logged in.

**Comment by Mineslu** [comment]
Great, it was what I needed.
Thank you all
