### ISSUE TITLE
add srcset to Thumbnail

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2125]
I want to make change to the thumbnail (featured image) like this sample and to serve them like scaled images instead of re-sized images
![thumbnail](https://user-images.githubusercontent.com/16117229/30775171-31d582da-a08f-11e7-9893-b126514b705d.jpg)
How can I do this?

**Comment by mahagr** [comment]
You're on WP? Gantry itself does not do any scaling or resizing, check at Timber documentation how it's doing this.
