### ISSUE TITLE
joomla Error displaying the error page

### ISSUE THREAD

**Issue by appukonrad** [gantry/gantry5#2126]
J! 3.7.5
Gantry 5.4.18
Helium 5.4.18

After update Gantry pkg and Helium from 5.4.17 to 5.4.18, site show only "joomla Error displaying the error page". 

Returning to version 5.4.17 is OK

**Comment by mahagr** [comment]
Just enable debug mode from Joomla, it should give more information about the issue.

**Comment by appukonrad** [comment]
I have already downgraded I can not test it anymore

I downloaded 5.4.18 from the gantry page and after the new update all OK

**Comment by mariantanase** [comment]
Is a bad idea to use on obsolete Joomla version

**Comment by mahagr** [comment]
It may have been caching issue of some kind. I'm glad everything is working now with the latest version.
