### ISSUE TITLE
W3C errors being reported as "role" is on wrong elements in html

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2127]
The role attribute is on the wrong elements in Gantry 5 core.

1. There should be no role on the <nav> html element (coming from menu.html.twig line 124
but
2.  there should be one on offcanvas toggle DIV line 91 of page.hml.twig

errors reported as follows:
![2017-09-25_15-05-38](https://user-images.githubusercontent.com/11683218/30812601-1a063e72-a203-11e7-9e1a-60bc13d0c9f6.png)

Also see this 3rd error too.

![2017-09-25_16-23-06](https://user-images.githubusercontent.com/11683218/30816463-eb96d866-a20d-11e7-96b0-e341693229ee.png)

**Comment by mahagr** [comment]
Which template are you using for the 3rd error?

**Comment by marktaylor46** [comment]
Supra template.

Here is original forum post:

 http://www.rockettheme.com/forum/joomla-template-supra-solved-threads/272308-solved-w3c-compliant-issue-with-navigation

**Comment by LukeDouglas2** [comment]
Marktaylor46,

I am logged into RocketTheme but get can't see that link.  

403 Forbidden
You do not have permissions to access this page.

**Comment by marktaylor46** [comment]
You won’t be able to if your RT subscription has expired or you don’t have a subscription to that template.

**Comment by thexmanxyz** [comment]
@marktaylor46 @mahagr can be closed see merge of fix #2365
