### ISSUE TITLE
How Would be the best way to override <script src=/media/jui/js/jquery.min.js

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#2129]
Hello. Would be the best way to override <script src="/media/jui/js/jquery.min.js"
Because I want to load the latest version of Jquery
PDT: I'm working with Joomla 3.8
Thank.

**Comment by mahagr** [comment]
Just copy the js file into your template and it should automatically be using the new one.

**Comment by mahagr** [comment]
Check Joomla documentation. :) If I recall it correctly, just use the above path inside your template.

**Comment by lipatovroman** [comment]
> Check Joomla documentation. :) If I recall it correctly, just use the above path inside your template.

OMG, I tried any combinations - not working...

**Comment by mahagr** [comment]
Try this then https://extensions.joomla.org/extension/jquery-easy/
