### ISSUE TITLE
Can't find the correct way of TWIG customization

### ISSUE THREAD

**Issue by TilenVonHarc** [gantry/gantry5#2130]
Hi guys,

before I dig in all the details about my problem (URL, version, particles, etc.) I would like to know if somebody could just point me in the right direction or even help me. 

I managed to create new YAML fields and they show up great in the particle in the Joomla! administration. Now I know that the next step is to integrate those YAML fields in the TWIG file. And here is the problem - nevertheless where I put the "correct" code my web page doesn't load the particle at all.

I am using a template from Rockettheme (called FLUX) and the template has a nice calendar, to present oncoming events. But I thought that it would be easier for the administrator if the calendar particle had some extended editing (input) options (such as: button1, button2, image, etc.).

[CODE REMOVED AS IT WAS FROM PAID PRODUCT]

As you can see I created a new set of YAML fields. Now I would just like to ask a kind person to tell me where in the code to use them and how (the syntax and all this (for me) messy symbols). I need to point out that all my custom fields should begin after the particle default description YAML field. Except the image field should be above the particle default description YAML field.

Thank you very much for your help and I am looking forward to finally make it right :)

**Comment by DamirPecnik** [comment]
We can close this, its being resolved on the RocketTheme forum.

**Comment by w00fz** [comment]
👍
