### ISSUE TITLE
Can you disable the load of native jquery from Joomla 3

### ISSUE THREAD

**Issue by Mineslu** [gantry/gantry5#2131]
Hello,
Can you disable the load of native jquery from Joomla 3, from gantry?
Thank
![sin titulo-1](https://user-images.githubusercontent.com/9434043/30929245-8b9d8744-a383-11e7-872d-8eb8e7cd8144.jpg)

**Comment by w00fz** [comment]
That is not coming from Gantry, it's Joomla auto-loading it because of the JCaption thing.
If you disable anything Joomla that requires jQuery, it won't load.

Gantry itself is JS agnostic and only cares about running its own JS payload.

**Comment by Mineslu** [comment]
OKAY.
I give it because I'm making an atom to load the Bootstrap 4 framework.
And this requires Jquery 3. But Joomla loads version 1.12, this will make many of the components of Bootstrap 4 not work.

**Comment by mahagr** [comment]
You can override jQuery js/css in your template, just use the same path for the file.
