### ISSUE TITLE
Optimize CSS Delivery

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2135]
Hello,
I tested my site on Google Insights and I got this "blocking css resources" along with other files which are not hydrogen related. Is there a way to fix these hydrogen related css files:

- /gantry5/assets/css/font-awesome.min.css
- engines/nucleus/css-compiled/nucleus.css
- custom/css-compiled/hydrogen_home.css
- nucleus/css-compiled/wordpress.css
- /wp-content/themes/g5_hydrogen/style.css
- css-compiled/hydrogen-wordpress_home.css
- /custom/css-compiled/custom_home.css

Is there a way to fix or merge these css scripts?
I'm using WordPress hydrogen theme.
Thank you!

**Comment by w00fz** [comment]
Gantry doesn’t provide a mechanism to unify JS or CSS files, however there are Wordpress plugins that do so. Try looking for “CSS unify”
