### ISSUE TITLE
Can't remove meta property

### ISSUE THREAD

**Issue by Emtree** [gantry/gantry5#2138]
Hello,

I used the meta name and property from the hydrogen theme (Page Settings > Head Properties > Meta Tags). I deleted them, but they are still here.
When I changed the theme (for ex. Twenty Fifteen) the meta property and name were not there, which was what I wanted. Now that I returned to hydrogen theme I saw that they were still there. How do I get rid of them?
Thank you

**Comment by mahagr** [comment]
Make sure you removed them from both base and the outline you're currently using.

**Comment by Emtree** [comment]
Hello mahagr, the meta tags are removed from all outlines including base outline.

**Comment by mahagr** [comment]
Is the property your own or added by Gantry? If it's yours, you have to have it somewhere.

**Comment by marktaylor46** [comment]
1. Make sure that you have Gantry in "development mode" in Gantry 5 admin > extras.
2. Make sure that you DO NOT have the system - page cache plugin enabled in Joomla > plugin manager
3. Make sure that you DO NOT have a compressor enabled such as rokbooster or JCH_optimize in plugin manager.
4. Clear cache in Joomla
5. Clear cache in your browser.

Regards, Mark.

**Comment by Emtree** [comment]
What do you mean by property of my own?
 I added the meta property through Gantry meta tags in head property. I added something like 
<meta property="og:title" 
<meta property="og:description"
....
Even after I deleted these form meta tags in gantry head property, they are still loading in my page.

**Comment by Emtree** [comment]
Hello marktaylor, I use WordPress and I have development mode ON. I cleared the cache (I use wp super cache) and cleared cache in browser.
Even when I fetch the data from Google, the meta tags are still there.

**Comment by marktaylor46** [comment]
Oh WP - that wasn't obvious to me from your original issue. 

1. Look with Firefox Inspector or one of the other browser developer tools to see if the METAs are in the rendered page. They should not be. so...
2. Use Google webmaster tools to request a recrawl of your site - chances are it's just Google has cached those metas.

Regards, Mark.

**Comment by Emtree** [comment]
Hi Mark,
The problem wasn't in gantry meta tags. The Yoast SEO plugin is taking the first wordpress post and making it the meta name description for the homepage. How do I fix this? Should I ask Yoast support?
Please note that I have written a meta description for the homepage too, but that meta doesn't show up.

**Comment by marktaylor46** [comment]
Yes ask Yoast for support.

**Comment by Emtree** [comment]
But why is the description meta okay when I change the theme?

**Comment by marktaylor46** [comment]
No idea without looking at your site admin.

**Comment by Emtree** [comment]
Will you check the problem if I give you access to the dashboard?

**Comment by mahagr** [comment]
Glad that you were able to figure it out.
