### ISSUE TITLE
Gantry 5 Save modification Feature

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#214]
In Gantry4 when I was changing settings in a template override I could SAVE and still be allowed to continue to change more settings. Save&Close would exit me with Save from the template override manager screen.

In Gantry5 we don't have this option as every SAVE returns you to the tmpName-Default Theme. If you're not paying attention to this then you start editing the wrong template.

I would suggest upon a SAVE your remain on a template Theme until such time you want to change to another.

**Comment by w00fz** [comment]
I'm not sure what you mean here. If I am in the Home configuration and I save I am still in the Home configuration, I am not getting redirected to default. Am I missing something?

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
I have tried and retried on OSX and Windows, I can't reproduce this. Feel free to reopen when you have more details on how to reproduce it.
