### ISSUE TITLE
Override the Gantry5 router in Joomla

### ISSUE THREAD

**Issue by Vanguger** [gantry/gantry5#2142]
Hello! I have a page in Joomla created in **Menu>test»Gantry 5 Themes»Custom Page** opens to: **site/test**

My problem is that I need an extensible address: **site/test/x1/x2** - going to this address opens the **404 error page**

Question:
How do I override the router in plugin to keep my new url: **site/test/x1/x2** ?
x1,x2 - I have a dynamically changeable IDs

**Comment by mahagr** [comment]
You need to write your own component and router in order to do something like that. All URLs need to be routed by some router, otherwise it'll be 404.

**Comment by mahagr** [comment]
Fixed routing paths with urlencoded spaces and non-latin letters (#1688)

**Comment by mahagr** [comment]
Not Gantry issue as said above.
