### ISSUE TITLE
css class and tag not loaded in menu modules

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#2143]
hi
when i add module picker in the menusystem of gantry , and when i add some css and tag to that,
it's not loaded in the menu frontend.
look at the screencast if you want see : 
https://www.screencast.com/t/VmKl0jyVkHRP

**Comment by JoomFX** [comment]
Hi there,

Make sure you clear Gantry Cache.
You can find the option under [Extras](http://docs.gantry.org/gantry5/configure/extras).
If you are using some optimization extensions or if you have enabled Joomla cache, you might also want to clear the Joomla Cache.

**Comment by mahagr** [comment]
I agree that those modules are likely cached.
