### ISSUE TITLE
IE11/Safari issues in Gantry admin

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#2144]
I'm using Joomla 3.8.1 (auto updated), PHP 7.0.98, MySQL 5.5.35-MariaDB, running on Apache on a large website hosting service.

Since updating to Joomla 3.8.1,  Gantry 5 templates Hydrogen and Hassium (by JVGtheme) have the problem that in the back end, the only theme page that displays properly is the Styles page. The Layout, Page Settings, and Particle Default pages show as blank pages.  (Note that the Joomla menu items still show at the top of the page, but the Gantry content is blank.) This is true on two of my websites even for Hydrogen Base Outline.

On the front end, everything seems to be working fine.

**Comment by pintobuck** [comment]
More info: I'm using Gantry 5.4.18 and Hydrogen 5.4.18, which were auto updated.

**Comment by JoomFX** [comment]
One of our users reported the same "issue".
It turned out to be a browser cache issue. Just clear your browser cache and then hard-refresh (CTRL+F5) the Admin page.
You might also want to try with a different browser.

That being said, no Joomla 3.8.1 does not break Gantry 5 backend.

**Comment by pintobuck** [comment]
Yes, clear cache worked.  Thank you.

**Comment by pintobuck** [comment]
Upon further analysis, I narrowed my issue down to the Internet Explorer 11 browser, which is the browser that manifests the problem for me.  When, I switched over Firefox or Chrome, then the problem went away. 

My previous post thought that clearing cache cured my issue, but my issue turned out to be IE 11.  Even clearing the IE 11 cache did not work for me.  .

Changing browsers worked for me. Thank you to JoomFX for pointing out browser problems, which helped me find a solution.

**Comment by JoomFX** [comment]
No problem mate.

Yeah, the user who reported this in our forum was also on IE11.
So the G5 developers might want to look at it.

**Comment by mahagr** [comment]
@pintobuck Was the issue fixed by clearing cache in IE11?

**Comment by pintobuck** [comment]
Question: mahagr asked "Was the issue fixed by clearing cache in IE11?"
Answer:  Clearing the cache in IE11 did not fix the problem for me.

**Comment by mahagr** [comment]
I'm going to keep this open for now.

**Comment by EddySn** [comment]
Dear all, unfortunately it is not only a IE11 issue. I have the same issue in Safari, running the backend iFolio template pro (v1.0.3). Clearing cache in Safari works, but I have to repeat this every time, when switching a theme outline. I am using Joomla 3.8.1 and Gantry5 (5.4.19).
