### ISSUE TITLE
Style editor page get broken after first save

### ISSUE THREAD

**Issue by metska** [gantry/gantry5#2146]
Gantry 5.4.18 and Joomla 3.8.1

![gantry-5 4 18-administrator](https://user-images.githubusercontent.com/2114176/31663126-a1f5fad2-b349-11e7-8a4b-89d652cec744.jpg)

New clean Gantry installation to site. First changes to template, saving and exit to some other page. When I go next time to the Gantry template administration there are dropdown missing and Layout-page empty. This happens with Hydrogen and Helium.

I have tried to remove plugin and template and reinstalled and same thing happens. Site is cloned of another site on same server and that another site is working fine.

**Comment by JoomFX** [comment]
Hi there,

Please have a look at this issue - https://github.com/gantry/gantry5/issues/2144

**Comment by metska** [comment]
Hi,
seem that that cache cleaning won't help in my case. I tried to log in with other browsers and page was already broken like picture shows. Tested with Chrome, Vivaldi, Firefox and Safari and with mobile Safari.

Even color picker, file browser, particle sliders and add tag fields/buttons do nothing.

"Extra" button in Template top menu isn't working.

Recompile CSS -button gives error: 
(/administrator/index.php?option=com_gantry5&view=configurations/default/styles/compile&theme=g5_hydrogen&159423c387adb1a80dfb7614bbb9b5ce=1)

404 Not Found
Oops, Page Not Found.

**Comment by JoomFX** [comment]
I'm surprised that the issue is not solved for you.
It is confirmed to be a Browser Cache issue (not Joomla or Gantry cache).

Please make sure that you clear the **browser** cache and cookies properly and try again.
You might also want to re-install the framework but I do not think it is necessary.

**Comment by adrianweb** [comment]
It might be an issue with Gantry V5.4.18, I've seen this issue on WordPress, I don't how to reproduce it or what could cause it, but downgrading to v5.4.17 helped.

**Comment by metska** [comment]
I tried to clean my browser cache, didn't help. I tried also to browse with the fresh installed Linux computer and Template page broken. I even installed Joomla 3.8.0 from backup the Installing the Gantry successfully without error messages and first save and page is broken.

If I try reinstall Gantry pkg without remove it first, I get message:

> Warning
> Install path does not exist.
> Package Update: There was an error installing an extension: com_gantry5_v5.4.18.zip
> ×
> Error
> Error installing package

And after that Tempate editor is totally broken and gives error:

![a7262560-677b-4161-8e0c-f871bdc51a7a](https://user-images.githubusercontent.com/2114176/31672155-6e855312-b364-11e7-8cbd-9f2e5c28bbd1.jpg)

**Comment by mahagr** [comment]
It looks like Gantry is only partially installed ^

**Comment by metska** [comment]
I have done more testing and I can repeat the problem with the Gantry at least versions 5.4.15 to 5.4.18. It may allow 1 to 10+ saves before the page gets broken and then you have to remove Gantry and reinstall it back before Style page works again, a while. 

If you try to reinstall or upgrade Gantry by uploading  a file it gives an error:

> Warning
> Install path does not exist.
> Package Update: There was an error installing an extension: com_gantry5_v5.4.18.zip

Sometimes this error comes when you have already uninstalled Gantry and try to make a clean installation. Even this error message comes Gantry is installed or upgraded in a system but most Gantry extensions are disabled. I have also tried to install and reinstall other components without any problems.

I have tried to make used Akeeba Admin tools fixes and reinstalled Joomla Core files. 

I have tested Joomla 3.7.5 site without problems. Also, another 3.8.1 site, which this problem site is originally cloned and with it this problem hasn't occurred. Both of these 3.8.1 sites are on the same server.

**Comment by yellowwebmonkey** [comment]
@metska , I was looking at @DKrreo_twitter's site yesterday who was having same problem.  I noticed that when installing older version of Gantry then going to manage extensions, that only the component itself was showing the downgrade to 5.4.17 and all the plugins, etc were still showing 5.4.18.  Not sure if that is helpful to anyone...

**Comment by pkortge** [comment]
I'm also now seeing this problem on a Joomla! v3.7.5/Gantry v5.4.18 website I'm working on - see screenshot attached.
[mtr Versla Theme.pdf](https://github.com/gantry/gantry5/files/1392644/mtr.Versla.Theme.pdf)

I've cleared cookies, re-installed the RocketTheme Versla v1.1.4 template, re-installed Gantry (had to delete it first and then re-install as it wouldn't install over the previous version) and problem remains.

Also tried multiple web browsers.

However, for me the problem didn't occur after the "first save" as the template backend has been working OK for weeks now and through multiple saves.

**Comment by dkrrero** [comment]
I have the same problem, I restore previous backup of my page and don't work... I don't know what happen.... If any have a solution please share it...

**Comment by yellowwebmonkey** [comment]
I am looking at dkrero's page and get this error in console: 

main.js?59e66306:1 Uncaught TypeError: Cannot read property '0' of null
    at constructor.top (main.js?59e66306:1)
    at new constructor (main.js?59e66306:1)
    at main.js?59e66306:1

**Comment by mahagr** [comment]
@metska The error `Install path does not exist.` comes when the installation fails on source path missing, meaning that the files were never unzipped to the temporary folder. Something is wrong on your site if that happens. Make sure that Joomla tmp and log folder settings are pointing to the correct location.

Regarding the issue itself, please try CI builds if it fixes the issue.

**Comment by metska** [comment]
Here are how a source is loaded between working and broken administrator page:

Problem site (after page gets broken)

![2017-10-18 11 51 37 am](https://user-images.githubusercontent.com/2114176/31709471-d4db8960-b3fa-11e7-91cc-151dd52cc147.jpg)

Working site

![2017-10-18 11 49 26 am](https://user-images.githubusercontent.com/2114176/31709481-d932bf60-b3fa-11e7-9c8b-dbad6176ecca.jpg)

**Comment by mahagr** [comment]
It looks like main.js doesn't get loaded -- make sure it exists in the filesystem. I don't think this is an issue in Gantry, but your hosting deleting the file because of it thinks there's a virus in the file.

**Comment by metska** [comment]
It looks that main.js is ok, this is view from Media > Gantry5 > assets > js

![2017-10-18 01 42 42 pm](https://user-images.githubusercontent.com/2114176/31714932-81c2d264-b40a-11e7-9ec8-a57199217e92.jpg)

Did you notice that there are also changes in components folder?

**Comment by mahagr** [comment]
I meant the main.js used by admin (`administrator/components/com_gantry5/js`), this one is used in frontend only.

**Comment by metska** [comment]
That's true, the file is missing from there. I will contact my hosting provider to find out why this happens on this site but not in sibling site on the same hosting account.

**Comment by adrianweb** [comment]
Hello,

@mahagr what's the state of this issue? It affects multiple websites on different hosting environments. 
Could it be related to ClamAV issue, it blocks the js file and we have to wait until it's whitelisted? 
Is there any temporary workaround?

It looks like a server issue, but it happens everywhere, users are reporting it. I use the same environment for a while and never had this kind of issue until yesterday. From time to time gantry is broken and I have to reinstall the plugin, it's the only way it will work again.

**Comment by w00fz** [comment]
I’m going to rebuild the packages with an uncompressed version of the js and do a release.
Unfortunately I am right now out of town at a conference and have limited time. I’ll make this happen as soon as possible.

I’m sorry about the issue, we actually contacted clamav and tried to get the file whitelisted but it’s faster to just release again.

**Comment by adrianweb** [comment]
Hey mate,

No worries, if that's the issue I can manually update the websites, it been a long discussion without a final conclusion that's why I asked.

**Comment by thexmanxyz** [comment]
@w00fz @adrianweb @mahagr Something is really strange with that main.js because even Gmail flags the compressed and even the uncompressed file for some reason. So I'm not sure if a repack will fix this issue if there is some false flagging going on. As already posted above ClamAV flags the file (even a totally outdated version of the main.js i tried, at least 5-6months old one).

**Comment by w00fz** [comment]
Can you guys try 5.4.19?

Try the packages from here: https://github.com/gantry/gantry5/releases/tag/5.4.19

**Comment by thexmanxyz** [comment]
@w00fz seems to work

**Comment by w00fz** [comment]
👍 

I literally fixed this on the road, off of my personal hotspot and while @rhukster was driving. Hope you guys appreciate the dedication. 😉

![img_6186](https://user-images.githubusercontent.com/11734/31733352-63eb7012-b409-11e7-8016-b72d5f86d2e3.jpeg)

**Comment by JoomFX** [comment]
LOL! Niiice 😄 
Thanks Djamil!

P.S. I miss your activity in the Gantry 5 chatroom on Gitter.
Hopefully, once Grav v2 is released, we'll have you back on G5 😉

**Comment by N8Solutions** [comment]
@w00fz Outstanding Dedication! This isn't a problem that was affecting me but it's very nice to know that you guys are on top of stuff getting things done when necessary. BRAVO! I'll also second what @JoomFX said, we miss having you around in the G5 chatroom.

**Comment by hugoaf** [comment]
@w00fz please tell @rhukster to drive safely, we are many people that relys on you guys. 
Actually there should be a universal rule to prohibit you two go in the same vehicle. :smile:
