### ISSUE TITLE
Successful SSL, Gantry 5.4.18, Hydrogen template, and Joomla 3.8.1 on Shared Hosting 

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#2147]
This post is more for information than it is an issue.  I could not get Joomla, SSL, and Gantry 5 to work together until now. See closed issue #1892.  My Gantry problem back then, but solved now, was that SSL broke Hydrogen Template's connection to the custom.scss page, and so the template fell apart on the front end.  But, now Joomla, Gantry 5, Hydrogen Template, and SSL are working together well after I added a line to .htaccess:
`### Upgrade internal requests to https, insert if your site layout breaks when visiting the site via https`
`Header set Content-Security-Policy "upgrade-insecure-requests"`

Addtional Info: 
(1) Currently, I'm using Joomla 3.8.1, PHP 7.0.98, Hosting Service's Apache server, Database 5.5.35-Maria, 
Database Collation utf8mb4_general_ci, Gantry 5.4.18, Hydrogen Template 5.4.18.
(2) For my current installation, Joomla 3.6.2 was installed using the hosting service auto install tool. Joomla was upgraded using Joomla's auto upgrade since then
(3) A year ago, I tried the SSL solution described above, and it did not work.  However, it is working now. Perhaps the interim upgrades to all components helped.
(3) An additional problem, which remains unsolved for me, is that Joomla Force HTTPS crashes my website which is run on a very large, website hosting service.  So, a year ago and now, I leave Joomla Force HTTPS turned off, and use the hosting service C-Panel to force HTTP > HTTPS.
.

**Comment by mahagr** [comment]
I need to check tha all requests (especially in CSS) are using `//` protocol (pick http/https).

**Comment by mahagr** [comment]
@simmonsr Can you check this out?
