### ISSUE TITLE
404 errors about nucleus.css.map have returned with G5.4.19 update

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2149]
Further to https://github.com/gantry/gantry5/issues/2092

It seems these messages have now returned to the browser console again.

![2017-10-19_11-27-30](https://user-images.githubusercontent.com/11683218/31769983-b4d043a8-b4cd-11e7-93f5-ec0c277546ce.png)

**Comment by mahagr** [comment]
I think this is a side effect of not using the minimizer (which causes false positives in virus detection)...?
