### ISSUE TITLE
How to remove border from module 

### ISSUE THREAD

**Issue by hitman2017** [gantry/gantry5#2150]
Hi, If anyone can please guide me in right direction here.
How to remove the border from the images. In backend I've put background to transparent. Also tried putting image module to another section of the template and it still comes up with borders on frontend.

See screenshot attached.
Using template/theme: Gantry Administration by RocketTheme
Version: 5.4.17 / Released: August 25, 2017

![2017-10-23 01_15_31-tyre world auto ltd - administration](https://user-images.githubusercontent.com/31493938/31861819-f1e41994-b78f-11e7-9371-c62a2ac3413f.png)
![2017-10-23 01_13_52-automotive car mechanic east tamaki east south auckland](https://user-images.githubusercontent.com/31493938/31861816-ed93dc94-b78f-11e7-82e8-d7004d3231f5.png)

**Comment by mariantanase** [comment]
Can you provide an URL ?

**Comment by hitman2017** [comment]
http://tyreworld.co.nz/homepage

**Comment by marktaylor46** [comment]
remove the "shadow" module class suffix that you added on the module.

Regards, Mark.

**Comment by hitman2017** [comment]
Thanks Mark, that has fixed the issue !!!
