### ISSUE TITLE
Grav Google Maps plugin not displayed

### ISSUE THREAD

**Issue by vincowl** [gantry/gantry5#2151]
While using grav 1.3.7 and helium theme (uses gantry 5 plugin), I can't see Google Maps plugin output anymore. Investigating further, here is the console's output :
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (nucleus.css.map, line 0) http://XXX/user/plugins/gantry5/engines/nucleus/css-compiled/nucleus.css.map
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (main.js.map, line 0) http://XXX/user/plugins/gantry5/assets/js/main.js.map
```
Indeed, these files do not exist.

**Comment by marktaylor46** [comment]
Those error messages pertain to https://github.com/gantry/gantry5/issues/2149

**Comment by w00fz** [comment]
I doubt this is related to the missing source maps

**Comment by mahagr** [comment]
I agree that the errors shown are not related the issue of Maps not showing up.

**Comment by vincowl** [comment]
Ok. So, console errors put aside, any idea to what causes Google maps plugin output not been displayed ?

**Comment by N8Solutions** [comment]
Are you using Cloudflare?
I recently had this issue and was using "rocket loader" from Cloudflare.
Once I turned it off the problem went away.

**Comment by vincowl** [comment]
No as far as I know. Maybe under the hood, but I only activated Google maps plugin, gantry 5 ans shortcode, using helium theme

**Comment by N8Solutions** [comment]
You should know if your website is using CloudFlare or not. It's not
something that is "under the hood". You have to login to CloudFlare & add
your site or do it through your webhosts control panel interface.

**Comment by vincowl** [comment]
So : I don't use CloudFlare.

**Comment by N8Solutions** [comment]
OK, then
Are you using any other CDN (Content Delivery Network) like CloudFlare?
Are you using anything that might minify, compress, or compile the javascripts, css, html?

**Comment by vincowl** [comment]
No. Just grav out if the box with gantry, helium theme and shortcode served by apache2. Nothing else. Using PHP 7.0

**Comment by vincowl** [comment]
I just tryied to test with latest grav version (1.3.8 instead of 1.3.8). Google maps is displayed correctly.... Strange ! Then, it works now with 1.3.8 but no idea where the problem was with 1.3.7...

**Comment by mahagr** [comment]
Might have been a bug in Grav 1.3.7. Closing the issue.
