### ISSUE TITLE
Hydrogen nor  g5_helium can be uploaded to wordpress 

### ISSUE THREAD

**Issue by AlienDezine** [gantry/gantry5#2156]
"Could not extract file from archive. g5_hydrogen/./
Could not extract file from archive. g5_helium/.

WordPress 4.8.2

Any solutions? 

Thanks

**Comment by whoey** [comment]
unzip and rezip the themes /./ directory causes issues.

**Comment by newkind** [comment]
Yes, we're aware of this. Closing as duplicate of #2154
