### ISSUE TITLE
Problem with zip file

### ISSUE THREAD

**Issue by vitorvfmf** [gantry/gantry5#2158]
Hi, I am using this software for a while I want to thank you for that.

I'm not sure what the problem is, but there is something about that zip file that WordPress doesn't like. I downloaded the wordpress-tpl_g5_hydrogen_v5.4.18.zip file to my local computer and examined it - it seems perfectly normal, but I get the same error you reported when I upload it into a new WordPress. I then extracted the g5_hydrogen directory from the zip file and compressed it into a new zip file. I was then able to upload the theme without error. The same happened with 5.4.19 version.

**Comment by vitorvfmf** [comment]
[g5_hydrogen.zip](https://github.com/gantry/gantry5/files/1419993/g5_hydrogen.zip)

Check my file, this one works.

**Comment by mahagr** [comment]
Fixed in CI build.
