### ISSUE TITLE
Appending ?Itemid=1 to the URL displays enqueued warning message

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#216]
See:

http://demo.rockettheme.com/live/joomla/callisto/index.php?Itemid=404-error

**Comment by mahagr** [comment]
Not seeing it in my local (anymore), but will keep the issue open as I'm not sure if another fix fixed also this one or not.

**Comment by mahagr** [comment]
Looks like error page should not have system message in the layout as Joomla attempts to hide the messages and remove them right after displaying error page. So the messages will never be shown.

**Comment by arifinrt** [comment]
System message has been removed from Error page. Will be applied to the packages on the next release
