### ISSUE TITLE
Possible jquery conflict

### ISSUE THREAD

**Issue by hitman2017** [gantry/gantry5#2162]
My drop down menu doesn't work on front page. I've got Vinaora Nivo Slider on front page and I suspect it could be conflicting with the jQuery. Any idea how I can make both work.

There's no option in backend for the slider to disable jQuery.
website: www.tyreworld.co.nz

![2017-11-02 23_45_54-auto electrical service car servicing deals manukau auckland](https://user-images.githubusercontent.com/31493938/32322110-3423908c-c028-11e7-919d-9dd2894c1ff5.png)

![2017-11-02 23_45_38-automotive car mechanic east tamaki east south auckland](https://user-images.githubusercontent.com/31493938/32322097-2d278018-c028-11e7-80de-c5191bd66228.png)

**Comment by JoomFX** [comment]
Hi there,

This is a simple `z-index` issue.
Try increasing the `z-index` for the "Navigation" section to something higher.
For more details, have a look at [this issue](https://github.com/gantry/gantry5/issues/1187).

**Comment by w00fz** [comment]
For the records, gantry5 does not use any jQuery, it is JS framework agnostic. So, if any conflict ever happens, most likely comes from the platform or a particle.

**Comment by mahagr** [comment]
@hitman2017 Were you able to fix your issue by changing z-index?

**Comment by mahagr** [comment]
Closing the issue due to inactivity.
