### ISSUE TITLE
Resize section on base-outline doesn't inherit its dimensions

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2163]
Hi,
The scenario: I made a layout with 2 sidebars. Default Outline is inheriting from Base Outline (see the screenshots). Now, on Base Outline I want to drag left/right to resize the sidebar.
As a result, the Default Outline width retain its initial dimensions, it doesn't change (see the pic).
![base-outline](https://user-images.githubusercontent.com/3976174/32324906-36fae1e4-bfcd-11e7-8e9c-3f77110d5ae0.png)

![default-outline](https://user-images.githubusercontent.com/3976174/32324808-e3e25b90-bfcc-11e7-838b-609888dcc4d1.png)
Is this behaviour normal?

**Comment by w00fz** [comment]
Yes we only support inheritance up to the section level. I don’t think we have inheritance for the container itself. The container being what holds those sizes information, means that sizes of sections can’t be inherited.

**Comment by mariantanase** [comment]
ok, understand. thanks
