### ISSUE TITLE
Can we assign different outlines for article list page and article page?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2169]
By default, Joomla's article page is inheriting article list page's itemid. This creates a lot of problem, the modules on article list pages will display on article pages no matter you want it or not; if the article list page uses an outline that has no "page content"(like when you use rokSprocket to list articles and don't want com_content to render another list), the article page will inherit it and display nothing; If you use "custom page" for listing articles, then the article pages will get homepage's itemid, which will also be unacceptable. Joomla's Doc suggest us creating hidden menu item for articles, I say this is bullshit, what if I have hundreds of articles? Creating a hidden menu item for the category is viable, but the breadcrumb on article page would be "home>hidden>article", when people click the "hidden", they will get to the page that is supposed to be hidden and also get the above issue. 

There are many workarounds I can think of, using CSS to block, using javascript to modify the breadcrumb's link, and even using some paid extensions. But I just want to ask, since Gantry5 framework is quite robust, is there any solution within its scope? One approach I can think of is letting the article page and article list page have different outlines, is this possible without modifying the PHP files?

**Comment by mahagr** [comment]
We are using Joomla's router to route all paths and yes, I do agree that this is one of the worst issues when using Joomla. The only working solution would be to let the user set the Itemid used for the articles, but I'm not sure if Joomla article router allows us to do that.

**Comment by mahagr** [comment]
I can confirm that there's really not a good way to do this other than assigning menu item for every article. There's no way for me to set the Itemid manually I'm afraid :(
