### ISSUE TITLE
Child theme functions.php not working

### ISSUE THREAD

**Issue by paulzz3000** [gantry/gantry5#2171]
[functions.txt](https://github.com/gantry/gantry5/files/1468255/functions.txt)

I've been using these functions for a few years with different themes. All fine but Gantry ignores them, even if I copy them into theme.php

For example, there's a function that adds a load of default image sizes:

function custom_image_sizes() {
  add_theme_support('post-thumbnails');
	add_image_size('bnm-1400', 1400, 9999, false);
	add_image_size('bnm-1280', 1280, 9999, false);
}
add_action('after_setup_theme', 'custom_image_sizes');

function add_custom_sizes( $imageSizes ) {
  $my_sizes = array(
		'bnmimages' => 'BNMImages'
	);
	return array_merge( $imageSizes, $my_sizes );
}
add_filter( 'image_size_names_choose', 'add_custom_sizes' );

Is there a problem with the hook? after_setup_theme?

There's also a default maintenance message (which I know Gantry has built in) which has no impact whether the user is logged in or out.
I must be missing something really obvious here but it's beyond me!
I'm using Wordpress and latest Gantry and Helium.

UPDATE,
Gantry is not ignoring all of the functions in there. Some are getting through, like a catch-all defer and add class as body slug. If only I knew why the others were failing...

**Comment by paulzz3000** [comment]
UPDATE,
Gantry is not ignoring all of the functions in there. Some are getting through, like a catch-all defer and add class as body slug. If only I knew why the others were failing...

**Comment by newkind** [comment]
All of them should work just fine. Try placing them in functions.php and playing with priorities ie. `add_action('after_setup_theme', 'custom_image_sizes', 11);`

**Comment by paulzz3000** [comment]
Thanks @newkind 
Cannot get the maintenance function to work at all. It's been my default for years. 
function wp_maintenance_mode(){
    if(!current_user_can('edit_themes') || !is_user_logged_in()){
        wp_die('<h1 style="color:#ffa800">Website Maintenance</h1>...');
    }
}
add_action('get_header', 'wp_maintenance_mode');

**Comment by paulzz3000** [comment]
I appreciate that but it's limited, I can't add any styling to it, nor links. Is the reason I can't use mine because Gantry has one too and there's a conflict? If so, no problem, I'll find another solution. If not, I'd still like to know why it doesn't work.

**Comment by newkind** [comment]
Actually it's quite opposite. Gantry 5 gives you all the freedom to configure your offline page. Simply edit the outline "Offline" and you can change everything there - styling, scripts, particles, atoms, layout - whatever you want.

**Comment by paulzz3000** [comment]
I had no idea, just the text box on the G5 setting page, thanks.
Still really interested to know why my function isn't being picked up though.

**Comment by newkind** [comment]
Maybe the hook is wrong or something else. To be honest `get_header` isn't the hook i'd use personally for this kind of task.

**Comment by paulzz3000** [comment]
OK, fair enough. As it's worked with at least a dozen other themes, for at least three years, I thought it might be curious to work it out. Thanks for all your help @newkind
