### ISSUE TITLE
Stipping Html-endtags in inlineJS

### ISSUE THREAD

**Issue by mgollmer** [gantry/gantry5#2175]
Hello there, 

I developed a particle that uses the "javascript_footer" block  in twig and inserts some inlineJS. In this inlineJS there are some Stringoperations that buildup htmlcode - for example: 

**TWIG-Content**
```js
test = "<td>" + value + "</td>";
```

The javascript code is hardcoded in the associated twig file.

After the twig component rendered and hab been send to the browser the sourcecode in the browser looks like this.

```js
test = "<td>" + value + "";
```

Everysingle endtag defined in a string is gone ... I can't find a solution. I'm using **grav** and **gantry**. 
thank you in advance.

Kind regards, 
Michael

**Comment by mahagr** [comment]
Do not use the block for this as it has to parse the javascript, which does cause a few issues.

Please use these instead:
http://docs.gantry.org/gantry5/advanced/css-js-twig#load-css-js-in-gantry-53

**Comment by mgollmer** [comment]
Thanks! Forgot to close this one ;).
