### ISSUE TITLE
The "none-responsive" menu appear when viewing on mobile/tablet devices

### ISSUE THREAD

**Issue by ToNamPhong** [gantry/gantry5#2176]
Hi Guys, 

I see the little "issue" with the menu on mobile and tablet devices.

When you browsing the site on mobile, the MAIN MENU appears for few seconds. Something was wrong here, Could you please check this issue?

Example the latest template from rocket: https://imgur.com/a/wXsEF => you can see the main menu appears for few seconds then offcanvas.

This issue happened with all gantry5 based themes.

Thank you

**Comment by mahagr** [comment]
This is how the menu works. We are using the desktop menu in mobile, just transforming it with javascript. You may want to hide the main menu in the phone until the js kicks in.
