### ISSUE TITLE
Particle twig changes not apply

### ISSUE THREAD

**Issue by furbyhaxx** [gantry/gantry5#2178]
when changing the twig file of an existing particle in "THEME_DIR/particles" the changes take no effect, changes in the yaml file apply normal. 
deleting cache and refreshing don't work. I even can delete the twig file an the page still renders normal

-- correction, deleting the twig file and clearing cache throws an error on the frontend. but after reinstalling the file including the changes and clearing cache again it uses the original file instead of the new one.

**Comment by furbyhaxx** [comment]
manually deleting "/cache/gantry5/THEME_DIR" forces gantry to reload all files

**Comment by mahagr** [comment]
Make sure you enable `Development mode` before changing the files. Otherwise the changes will not be detected as Gantry does not check the changes in the files in `Production mode` in order to speed up page loads.
