### ISSUE TITLE
Helium Theme not working on my wordpress.com site

### ISSUE THREAD

**Issue by ElixirMike** [gantry/gantry5#2179]
I installed the Gantry 5 Framework on my site, and then uploaded the Helium Theme. However, When I activate it, the site throws a "Server 500" error. The Wordpress support team said this is because there are errors in both the plug-in as well as the theme. They shared these error messages.

PHP Fatal error: Uncaught RuntimeException: UniformResourceLocator: Absolute stream path with relative lookup not allowed () in /wpcom-138889961/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php:430
Stack trace:
#0 /wpcom-138889961/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php(412): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->find('gantry-themes', 'g5_helium/custo...', false, false, false)

#1 /wpcom-138889961/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php(412): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->find('gantry-theme', 'engine/css-comp...', false, false, false)

#2 /wpcom-138889961/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php(372): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->find('gantry-engine', 'css-compiled/w

Is this something that can be resolved ?

**Comment by newkind** [comment]
I'm contacting the WP.com staff for the possibility of getting a dev account to debug this issue. I'll keep you updated.

**Comment by newkind** [comment]
Ok, this issue should be fixed now. We tested latest CI of Gantry5 and Helium and all seems to be working fine! :)

Big *THANK YOU* to the WordPress.com team for giving us access to the business plan so we were able to fix this.

**Comment by ElixirMike** [comment]
How would I get the latest version? I was in Wordpress and it has "autoupdates" enabled...but I don't see the framework has been updated. IS there a way for me to get latest and apply fixes?

**Comment by newkind** [comment]
You can download the CI build from the Gantry website, but I'd just wait till we release update today and just update your Gantry 5 Framework plugin. That's the safest way to do it.

**Comment by ElixirMike** [comment]
Thanks, I'll wait till end of day to update the plugin. Would I need to download latest Helium theme and update it manually?

**Comment by newkind** [comment]
No, the bugfix is in the framework plugin.
