### ISSUE TITLE
WordPress - Menu Particle - Start Level, Base Item

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2181]
In the Menu Particle the start level is not working as it should also the Base Item also dont work as it should. Can somebody confirm this?

![2017-11-30 13 53 45](https://user-images.githubusercontent.com/10489911/33431785-f27b7f50-d5d5-11e7-86c3-3be114ec430c.jpg)

**Comment by marktaylor46** [comment]
i can confirm that this is an issue in WP. It's impossible to create a "split menu" type of menu. E.g. if you add a second menu to the sidebar and set it to use "main-menu", "active" "start level 2" "end level 0" then you would expect child items of the active menu item to show but they do not. You either get some random particle content of absolutely nothing at all.

**Comment by infuseit** [comment]
Anyone have an update on this? I just checked and it is still an issue in WP.

**Comment by DamirPecnik** [comment]
Yes its still an issue waiting on the devs.
