### ISSUE TITLE
Request: change Lightcase size defaults

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#2182]
in lightcase.js the default video popup is so tiny which seems very unnecessary as lightcase is already responsive

lightcase.js
video: {
                    width: 400,
                    height: 225,
               ...
                }, 

it overrides any normal changes you might otherwise make with data-lc-options= to the maxWidth.... IMO  there shouldn't be *any* default size for *any* specific media type... just let the maxWidth and maxHeight default options be the only limiters

I'd argue too that the default maxWidth and maxHeight should be more like 1200x800 versus the current 800x500

**Comment by BjoernH01** [comment]
I totally agree with you, fixed sizes are really unnecessary. Right now I'm having the same problem with images which are shown in the popup way to small.

**Comment by blizam** [comment]
You can override them inline... for images, you can add

data-lc-options='{"maxWidth":1000, "maxHeight":800}'

or something similar in your <a> tag

for videos you have to go a bit deeper to override the defaults like:

data-lc-options='{"maxWidth":1280, "maxHeight":720, "video":{"width":1280, "height":720}}'

hopefully that helps in the short term... but I do think the defaults are much too small and media specific defaults, like video, shouldn't be defined at all IMO

**Comment by BjoernH01** [comment]
Yes, I've found that solution with "data-lc-options" already however that way you always have to get in the code view and edit it.

Normally I use JCE with the lightcase plugin, nice solution for uploading images and getting the right thumbnails for the popups.

It would be gread to have the lightcase options directly in the lightcase atom in the Gantry backend.

That way everyone could change them to their needs, nothing is hardcoded and can't be changed via Gantry 5 updates.

**Comment by newkind** [comment]
I just updated Lightcase to 2.4.4 and overwrote the default values for the maxWidth and maxHeight to 100%. This works nicely with images however not so great with videos, when I tried to use `auto` instead of `100%` for videos, the size was proper but the placement of the video was calculated badly. For now I have set the new video values to the suggested 1280x720 but we still should rework the atom in the future to support loading configuration from the YAML.
