### ISSUE TITLE
page settings: header already sent

### ISSUE THREAD

**Issue by Hg347** [gantry/gantry5#2184]
In Notio Theme, on every save in tab "Page Settings", an is exception thrown.
It does not matter if something has been changed or not. Just click "save page settings"
I'm not sure if this is template specific but I don't think so.

Cannot modify header information - headers already sent by (output started at /kunden/373755_52428/mientras-tanto/webseiten/wp-content/plugins/foogallery/freemius/includes/class-freemius.php:9203)

**Comment by mahagr** [comment]
Check the error logs if your WP instance has PHP warnings on the page. It looks like foogallery doesn't play nice and is causing these issues.
