### ISSUE TITLE
page settings: more detailed documentation required

### ISSUE THREAD

**Issue by Hg347** [gantry/gantry5#2185]
# page settings

Please refer to the discussion below. I think there is more clarification in the documentation required.

Wordpress 4.9.1
Gantry5 V5.4.19

## too many places / options to add JS
In the page settings tab are too many options to add javascript. 
Option 1 (custom content, refer to screenshots) does not output/add anything to the header section when entering <script>TEST</script>.
Option two and three seem to be interchangeable. I think you could remove CSS and JS from the assets section.
![screenshot_20171202_103738](https://user-images.githubusercontent.com/21147024/33514142-a048e586-d74e-11e7-9256-02784c550d87.png)

## add async tag, documentation
The documentation should state that the "async" attribute can easily be added. I assume that many people do not know that.
Also add a note that it is sufficient to add two slashes `//` instead of `http` or `https`. The correct protocol will be choosen automatically.
![screenshot_20171202_104108](https://user-images.githubusercontent.com/21147024/33514141-9f695d30-d74e-11e7-99ba-b92ab5814bc5.png)

## clarify where to drop Atoms
I took me a while to find out that I had to drag & drop the atoms to the lower area which is hardly visible on my screen. Intuitively I expected the drop area above the atoms and not below.
I think in other sections of gantry5 the drop area is always above or to the right. Possibly it would be sufficient to add a "drop-icon" to indicate the target area.

**Comment by paulzz3000** [comment]
@Hg347 Box 1 is for scripts or anything else that have to go in the head.
2 is for adding linked scripts and any required initialisations (in head or before </body>) plus load priority
3 is for scripts that can be applied to specific pages although if you have Base Outline chose these will be loaded on every page.
They all have their specific uses.
I agree about the async obfuscation. Could be a useful addition to the docs.

**Comment by Hg347** [comment]
@paulzz3000 Thanks for the clarification. The difference between 2 and 3 is clear to me now. Should be documented in my opinion. 

About option 1 I still don't get it. If I put a string like `<script>test</script>` in there it is not written in the html head section. I think it simply does not work. 
But I understand that this box is for special purposes which cannot be achieved by option 2, is it?

**Comment by newkind** [comment]
1 is not only for JavaScript. It's for everything that you might wish to add into <head> tag so you can use it for meta, css, comments or any other thing that should appear in the <head> tag.

**Comment by paulzz3000** [comment]
@Hg347 I'm not sure why your test <script>test</script> doesn't work. It does for me.

**Comment by Hg347** [comment]
Ok, I understand. But I keep this issue open for now since option 1 does not output anything. At least in my tests. Can anybody confirm this?

**Comment by newkind** [comment]
Works fine for me too :

![Image1](https://monosnap.com/file/4qx0hPF46iSAmnPsTulirbQGDZGSQq.png)

![Image2](https://monosnap.com/file/rTSHi8PklEcEKaUsAJ6cxqssLESefK.png)

**Comment by Hg347** [comment]
I assume now that it is related to the notio theme. I will perform some more tests locally and post the result here

**Comment by newkind** [comment]
I guarantee you that Notio has nothing to do here. Check if other outline isn't overriding this settings.

**Comment by Hg347** [comment]
That's it. Another outlined has been overriding. Thanks.
I change this subject to add more documentation on this and keep this issue open.
