### ISSUE TITLE
particles and atoms are global => dedicated git folder

### ISSUE THREAD

**Issue by Hg347** [gantry/gantry5#2186]
This is also a kind of code issue. When I try to lookup the "social"-particle I can find it via search in git only. And then I have matches in seemingly unrelated folders. E.g. there are theme folders where this is placed and overriden in other places.
Shouldn't there be a subfolder particles in folder assets? In my point of view are particles global and not  specific to a theme - at least most of them.
I expected to find all particles in a appropiate folder hierarchy, e.g.

- assets
  - common
    - particles
      - social
      - login form
      - To Top

**Comment by mahagr** [comment]
Hmm, not really, I think it is more like a design choice.

Particles can be both global and specific to a theme, also their content/instances can be either global or specific to the theme. Actually, they can be both at the same time as you can override their content.

**Comment by Hg347** [comment]
Well, when a particle is specific to a theme it means it has a kind of dependency on the theme. If it doesn't have a dependency on a theme, why should it be specific to it ?
Why should a particle ever depend on a theme? A particle is function or content, a theme is layout. I don't think they should be tight together for no reason.

**Comment by marktaylor46** [comment]
There's a very good reason... Templates are commercial products that RT sells in order to pay for the developers that build everything and the support staff that assist in the forums. So templates do contain unique template specific particles as that is one of the main differentiators between the templates that RT sells.

Regards, Mark.
