### ISSUE TITLE
When updating site from HTTP to HTTPS, not all links get changed

### ISSUE THREAD

**Issue by rbywater** [gantry/gantry5#2187]
I've been trying to get my Wordpress/Gantry5 site running with HTTPS but am having trouble with some links that are remaining with HTTP. The links that aren't changing are relating to the owlcarousel component. The image & href links for items in the carousel haven't updated (although I haven't tried going in and then saving them again) but the main issue is that the JS itself is pointing at http rather than https.
```
<script type='text/javascript' src='http://www.kapitiplayhouse.org.nz/wp-content/themes/g5_helium/js/owlcarousel.js?ver=7877a6d9ae07580db45d754057e83e2e'></script>
```

Is there a way to force this to HTTPS?

**Comment by DamirPecnik** [comment]
Please see the OWLCarousel Particle in Particle folder in theme and see if there is maybe an HTTP link in there.

**Comment by rbywater** [comment]
There didn't appear to be anything in there but it led me to 'gantrytheme://' which then led (via Google search) to me going into the Particle defaults screen and hitting Save again there which appears to have caused it to now show as HTTPS.

Long story short, all good now :)
