### ISSUE TITLE
Using child theme creates redundant stylesheet

### ISSUE THREAD

**Issue by paulzz3000** [gantry/gantry5#2189]
A child theme css requires Template info to properly load, say, Helium, but all the actual css is created and compiled from custom.scss.
This leaves the child theme's style.css simply declaring the author, template, version etc, no actual styles, but it is loaded anyway.
Any way around this, to save an additional http request?

**Comment by newkind** [comment]
Nope, this file will and should be always loaded. It's not only about easing the migration and compatibility for new users but also for respecting the guidlines and practises or the WP community.

**Comment by paulzz3000** [comment]
Fair enough! I can dequeue it afterwards. Thanks.
