### ISSUE TITLE
custom.scss not compiling

### ISSUE THREAD

**Issue by moley147** [gantry/gantry5#2193]
I have been using XAMPP to develop a new website using Joomla and Gantry 5 Helium.

Everything has been going great so I decided to transfer to a live site to finalise and debug the website before replacing/updating our existing website.

I backed up using AkeebaBackup.

I restored using Akeeba Kickstart on the live site and all the content, Helium template etc, etc seem to be there.

The only thing missing is the custom.scss is not compiled in the g5_helium/custom/css-compiled folder.

In development mode I get
________________________________________________________________________________________________
/* GANTRY5 DEVELOPMENT MODE ENABLED.

   WARNING: This file is automatically generated by Gantry5. Any modifications to this file will be lost!

   For more information on modifying CSS, please read:

   http://docs.gantry.org/gantry5/configure/styles
   http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
 */

/* @import "custom.scss" */
________________________________________________________________________________________________
and in Production mode I get.
________________________________________________________________________________________________

/*b0e19e7f9aa00410167bc869a3e0e166*/
/* @import "custom.scss" */
________________________________________________________________________________________________

It keeps creating css-compiled/custom_20.css and renaming the older custom_20.css as custom_21, _22 etc, etc. 

So it's not compiling the SCSS/custom.scss.  Its not an error in the file as I used an empty custom.scss with just "body {background-color:#ffffff;}" in it and it still wont compile.

Has anyone got any ideas?

Thank you 

Ian

**Comment by mahagr** [comment]
Remember that files are case sensitive in Linux: use `custom/scss` not `custom/SCSS` folder.

**Comment by moley147** [comment]
You solved it. I am such an idiot!  Thanks mahagr.
