### ISSUE TITLE
5.4.19 update to 5.4.21 issue in Wordpress

### ISSUE THREAD

**Issue by jamgit** [gantry/gantry5#2195]
#When updating from 5.4.19 to 5.4.21 I get the following errors. Any ideas on what this is?

1. Backend when trying to update an outline layout:
![screen shot 2017-12-12 at 3 12 24 pm](https://user-images.githubusercontent.com/7244493/33914067-3c248d16-df51-11e7-9075-e6c7f94d6faa.png)
2. Front of site error shows on top of website:
![screen shot 2017-12-12 at 3 12 53 pm](https://user-images.githubusercontent.com/7244493/33914084-547043f6-df51-11e7-95b7-a21d42607118.png)

**Comment by mahagr** [comment]
We already released update to fix the issue.
