### ISSUE TITLE
Menu format in Gantry 5

### ISSUE THREAD

**Issue by pykeiam** [gantry/gantry5#2199]
Greetings, I'm attempting to do a multi-column menu, that has the submenus pre expanded and indented, but am having no luck. Is this menu possible with Gantry 5, or do I need to switch over to a specific menu extension to get this formatting?  Here's a visual example of what we're trying to do:

![joomlamenu](https://user-images.githubusercontent.com/34690544/34173101-fbe5dffc-e4b9-11e7-8e04-5fa3cbe8e999.png)

Thanks in advance for any input/advice.

Pykeiam

**Comment by blizam** [comment]
Make them all the same level of menu items and use Custom HTML Particles to create your "parent" headers with custom CSS styling
