### ISSUE TITLE
Is there a way to override mobile breakpoint?

### ISSUE THREAD

**Issue by xbass540** [gantry/gantry5#2203]
i have a question: I have setup an outline with 2 particles per row. I need those particle to remain 2 even in mobile version. I don't want them one below the other. Is this possible?
I would be flexible using the grid system with nucleus code if necessary.

**Comment by thexmanxyz** [comment]
@xbass540 I already answered on gitter. However, the solution maybe to bind a selector on the `size-xx` class(es) which prevents on certain `@media` break points that the particles extend to 100%. I think there is no option, variation or default class which prevents this behaviour. So you have to override the default `width: 100%` with a value that fits your needs. But be careful that you use a correct selector which does not break all ´size-xx´ occurences

**Comment by thexmanxyz** [comment]
@xbass540 
Something like this works for the demo site and this is also what i would use.:
```
.g-home-particles #g-features .size-33-3 {
    max-width: 33.33333%;
    -webkit-flex-basis: 33.33333%;
    -moz-flex-basis: 33.33333%;
    flex-basis: 33.33333%;
    -ms-flex-preferred-size: 33.33333%;
}
```
Idk if you need three or two columns because you wrote different things on gitter and here however changing the values to 50% will fit both scenarios. Maybe there is a better solution however this works.

**Comment by xbass540** [comment]
hi, i will certainly have a look on your info, thanks grand!
I managed to figure a scenario that worked for me without messing with the gantry classes.
I created 2 grids with nucleus code one for desktop and one for telephones - using tables here that don's go responsive- and used the visible-phone and visible-desktop classes for each case.
So the mobile version displays a table of 2 columns.

Sorry for the inconsistency between the 2 threads i ended up that i need 2 columns on the mobile version.

**Comment by thexmanxyz** [comment]
@xbass540 interesting approach, out of curiosity, how you put the table in the layout / the second grid ? I think there must be an easier way with a custom layout however I'm not really sure how this can be achieved without modifying CSS or a trick like yours.

**Comment by xbass540** [comment]
hi,
the table is inside the g-grid row and i don't use particles at all. I have simulated the particles functionality with table columns. All this is wrapped inside a div that is visible only in phones.

`<div class="visible-phone">
<div class="g-grid">

        <table style="border:none;">
          <tr>
            <td>  .......some content.....</td>
            <td >  .......some content.....</td>
          </tr>
        </table>

      </div>
</div>`

**Comment by thexmanxyz** [comment]
@xbass540 Aah ok this makes more sense :). Thanks for you reply! I was just wondering how you got the html tags between the particles and the grid...because I do not know a way to do this. Maybe it's also possible to create a particle and load the particles there and wrap them in your own layout. 

However, I'm interested if there is a better / intended solution instead of modifying the core css rules. @mahagr @w00fz .

**Comment by xbass540** [comment]
@mahagr  @w00fz @thexmanxyz I would expect there are some classes of the style: phone-6 , desktop-3, laptop-4 that define the kind of grid relative to the screen. This would be very handy

**Comment by thexmanxyz** [comment]
@xbass540 check the corresponding bootstrap documentation which is used 2.x or http://docs.gantry.org/gantry5/tutorials/media-queries

**Comment by xbass540** [comment]
@thexmanxyz : Is the bootstrap framework used with Gantry? If yes are all the Bootstrap classes available?  I though Gantry was using its own classes.
I have finally implemented my project by using custom media queries but was hoping to have something like <div class="small-2 large-4 columns">...</div> available (like in Foundation framwork)

**Comment by thexmanxyz** [comment]
@xbass540 yes it is used, yes bootstrap 2.x.

**Comment by mahagr** [comment]
There's no boostrap enabled by default in Gantry, but Joomla does use an old version of it. It's not guaranteed to have Bootstrap available unless something loads it. In WP and Grav you need to load your own Bootstrap CSS files -- Gantry loads only js if asked to.
