### ISSUE TITLE
Unable to delete particles / menu disappears 

### ISSUE THREAD

**Issue by grimley** [gantry/gantry5#2206]
Theme / Layout
"Outlines - Position - Menu - About..." menu not visible / accessible.
Unable to delete particles (once one or more have been added to a section.
(Gantry 5.4.22 / Grav 1.4.0-BETA.3)

**Comment by kat05** [comment]
I can confirm the issue with the missing Gantry 5 theme toolbar, using Grav v1.4.0-beta.3 - Admin v1.7.0-beta.1  and Helium

Please see pic.

![grav_beta_missingtoolbar](https://user-images.githubusercontent.com/5719486/34937686-0036d1ec-f9e6-11e7-9496-f05ad8c336ba.jpg)

**Comment by kat05** [comment]
I am able to delete particles, but most of the "Drop to delete" area is hidden, please see pic.

![grav_beta3_droptodelete](https://user-images.githubusercontent.com/5719486/34938225-c48b3582-f9e7-11e7-9590-3ed680ea9fa3.jpg)

**Comment by mahagr** [comment]
@rhukster @w00fz Looks like new admin beta has issues with Gantry.

**Comment by ovresko** [comment]
waiting for a fix, you can access outlines / menu from url
<base>/admin/gantry/positions 
<base>/admin/gantry/menu/

**Comment by mahagr** [comment]
Should be already fixed.
