### ISSUE TITLE
Helium CSS using @import for Google Font

### ISSUE THREAD

**Issue by paulzz3000** [gantry/gantry5#2207]
The first line of compiled helium.css is an import of the Google Font I'm using which seems to be loaded elsewhere so I'm wondering why it's there in the helium stylesheet?

**Comment by mahagr** [comment]
Gantry uses Google fonts and by default, they are loaded from Google's CDN. There is a documented way to load fonts from the local server, but doing it requires manually adding and defining the fonts, which isn't something most people want to do.

**Comment by paulzz3000** [comment]
OK, thanks. It just looked like it was appearing/loading in two different places.
And I know we shouldn't fret about specific GTMetrix points but, loading fonts this way is a negative.

**Comment by paulzz3000** [comment]
Absolutely @mahagr It'd be a bit crazy to load a popular Google font locally unless chasing misleading stats from GTMetrix et al.
It just seemed that it was being loaded twice and one of the loads was via a less-than-optimal @import into a compiled stylesheet.

**Comment by mahagr** [comment]
Yes, the font could also be loaded from another CSS file in some cases, there's really not much that can be done to prevent that if you happen to use the same font which is already been loaded elsewhere.

**Comment by paulzz3000** [comment]
Thanks, it's not being loaded by anything else. I'll see if I can find another way to load it without relying on Gantry itself.
