### ISSUE TITLE
When error level set to maximum warning message about "displayItems"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2208]
Unknown: Calling "displayItems" on template "@particles/menu.html.twig" from template "@particles/menu.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0. in /home/murupump/public_html/libraries/gantry5/vendor/twig/twig/lib/Twig/Template.php on line

This error message is appearing in Salient with error level set to maximum.

Forum topic http://www.rockettheme.com/forum/joomla-template-salient/274109-i-can-t-edit-modules-in-front-end-anymore

**Comment by mahagr** [comment]
Might be a cached template, will need to investigate.

**Comment by mahagr** [comment]
I already fixed this one.
