### ISSUE TITLE
Joomla - Menu Particle in Module

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2209]
When you use Menu Particle in the Module the Display in Menu feature is not working i tried to set it to hidden but it still shows, if I add Menu particle directly to layout it works!

![2018-01-08 19 52 51](https://user-images.githubusercontent.com/10489911/34686968-9677ef62-f4ad-11e7-86b2-6b311fad7456.jpg)

**Comment by mahagr** [comment]
@DamirPecnik It works just fine for me. Make sure you didn't have caching turned on in the module.
