### ISSUE TITLE
Meta tags missing on my page

### ISSUE THREAD

**Issue by chseluv** [gantry/gantry5#2210]
Hello,

I'm using Joomla 3.8.3 and Gantry 5.4.22.

Apparently my website can only show meta tags that are generated by Gantry itself OR Joomla's language-assigned meta tags.

I need to tailor the meta-description and the meta-keywords to each page, at least to each menu item, and I don't want to use one setting for everything on my website for better SEO performance.

How can I enable Joomla's very own meta-data system while I use Gantry 5? Any idea or headsup?

**Comment by LukeDouglas2** [comment]
You can edit your articles under the 'Publishing' tab for the Meta Description and Meta Keywords (pretty useless). These will be used when the page is displayed

**Comment by chseluv** [comment]
Metadata for articles is displayed normally, you are right.

However, I have a set of menu items that are actually where a component outputs its content and the metadata for these items just doesn't work. If I write some meta tags in Gantry page settings they do get displayed but of course they are all the same for the whole website.

My website is a multilingual one with a lot of menu items, I don't know exactly how to enable Joomla's own metadata engine for menus

**Comment by LukeDouglas2** [comment]
Then I would have to agree with Alexis that there might be some type of conflict with other addons'

> Alexis Priddy @yellowwebmonkey Jan 12 13:15
> @chseluv , I just did a quick menu item set to Gantry5 page and the menu meta data worked. Do you have any SEO type components or plugins that might be affecting it?

**Comment by mahagr** [comment]
Please give an example of something that works in the default theme but not in a Gantry theme.

**Comment by jubacchi** [comment]
I´m having the problem witm my website. 
When i try to share my articles, the meta tags  are not sent to Facebook, for example:
My website: https://www.educatu.com.br/
An article with meta tags with problem (as any other of my website):  https://www.educatu.com.br/noticias/1732-atribuicao-de-aulas-da-rede-municipal-sera-no-dia-1-de-fevereiro.html

In facebook, metatags do not work, but ins whatsapp web, they are fine.

Any light?

**Comment by N8Solutions** [comment]
@jubacchi Facebook and Twitter use OpenGraph which is a different type of Meta tag.
You can do 2 things.
You can add some Open Graph meta tags using Gantry 5
http://docs.gantry.org/gantry5/configure/page-settings
These Open Graph meta tags added via page settings in Gantry 5 are site wide and not menu specific.

If you want to have menu item specific Open Graph tags added that will work for Facebook and Twitter then you should do a search for extensions that are available for your CMS.

**Comment by jubacchi** [comment]
Right.
But what I do not understand, is that this worked until a few days ago: as this facebook link: https://www.educatu.com.br/noticias/1733-teste-do-rogerio.html and stopped suddenly.

**Comment by N8Solutions** [comment]
@jubacchi when you say "this worked" what are you referring to?

**Comment by jubacchi** [comment]
I mean when I shared an article on facebook and all information (meta tags) was sent correctly.

**Comment by jubacchi** [comment]
for example: my "home" site even shows some information when it is shared, but when I try to share the articles, nothing happens.

**Comment by jubacchi** [comment]
the last link that worked you can see here: https://www.facebook.com/educatu/posts/1980474372244976?__xts__[0]=68.ARBdHeHFW406Aydw8okaiwxmWHqm0uYdStfCquRRcE8mtWwgfVIkjHpPaiahN-0LRwCUeDxbXT0dJC7yP6AICD5qwZ6o8Re9vKc7iZ24x2rZs0ps2TrUTaSHlwWuYkQoKdvc-8Gs-wZUUjmUb-u5ZtfqbSZTivYlDlbb6ey7HlrZWz3VvB_Kh2Z_-ZPKOl_1ouMV66F2i_NFhtHfO5WrVUNU8oQRZsTIlz6IdqXeiA7T2Oqbpgjltytu-7RGftqhNAqbYmks1P58vvgPAuh8LG8WFEAh7dyEtWWNHxs8oi7xFaVOlU2ueNmaR5PXIaHOwrO5Bp_HxxmHWIlEqb0Ai-fjWtZG&__tn__=-UC-R
after this,, my meta tags doent worked any more.
