### ISSUE TITLE
WordPress - Gantry Particle Widget - Save Button Inactive!

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2211]
After we select the Particle the Save button is still inactive see the video!

[Screencast 2019-03-05.zip](https://github.com/gantry/gantry5/files/2979469/Screencast.2019-03-05.zip)

**Comment by tbob18** [comment]
Any progress on this? Currently, the only way to save a particle to is enter something into the Class box to re-enable the Save button.

**Comment by Vanguger** [comment]
Not working yet :(

**Comment by Vanguger** [comment]
Here is a temporary patch to fix this problem. You can add to the plugin or functions.php
Tested on Wordpress v5.1.1
```
add_action('admin_enqueue_scripts', function($hook_suffix){
  if($hook_suffix != 'widgets.php') return;
  if(!wp_script_is('jquery', 'done')) wp_enqueue_script('jquery');
    $script = "
      jQuery(document).ready(function($) {
        $('.widgets-sortables').on('DOMSubtreeModified', function(){
          var g5 = $(this).find('#g5-container .g-instancepicker-title .changes-indicator');
          if (g5.length){
            var but = g5.closest('.widget-inside').find('.widget-control-save');
            if (but.length && but.attr('disabled')) but.removeAttr('disabled').attr('value', '".__('Save')."');
          }
        });
      });
    ";
  wp_add_inline_script( 'jquery-migrate', $script );
});
```

**Comment by mahagr** [comment]
Thank you. We will look into this fix.

**Comment by newkind** [comment]
Fixed in the latest CI. Please test and let me know if it works.

**Comment by cegascam** [comment]
Thanks for the help, it works perfectly.
