### ISSUE TITLE
Particles are going overlapped when going to 'responsive'

### ISSUE THREAD

**Issue by dimidino** [gantry/gantry5#2215]
Hello! 

In general, the site is not very good and mobile friendly and should be worked on, but for now I would be happy if someone help me with the solution of this problem here (see the title menu and logo at example) www.sgemsocial.org ! The parts overlap when is going to mobile version ... how I should solve this problem? ...how would you resolve it? Is exist also on other cases on this site! 

Thank you and greetings everyone!

**Comment by marktaylor46** [comment]
You should raise questions about Rockettheme Photon template in the Rockettheme forum rather than here.
