### ISSUE TITLE
Some of my RokSprocket Modules are not working when the web site is online ...

### ISSUE THREAD

**Issue by dimidino** [gantry/gantry5#2216]
Hello again!

And another case from me! ( our unattractive site - www.sgemsocial.org/index.php/event-location/hotels-boards/hotels-5-star/hotels-5-star-paradise-blue ) Lately, i have problems with RokSprocket Modules that simple are not working when the web site is online, and work very well on the local host! the parameters and options of the site are identical, I compared them many times!

Greetings to everyone here!

**Comment by marktaylor46** [comment]
404 on that link - but if you have questions about roksprocket then you should raise those on the rockettheme forum rather than the Gantry 5 project.

**Comment by dimidino** [comment]
Ok, SORRY! ... don't hate me! ;)
