### ISSUE TITLE
If Joomla session expires whil in gantry 5 admin screens - you get and error and loop

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#222]
I have noticed that if you leave Gantry 5 admin page open and your session expires in joomla, when you then click on anything in admin you can get a looping flashing popup message that you can't get out of unless you refresh the screen (then getting joomla admin login page).

Example page below:
![2015-05-11_08-55-26](https://cloud.githubusercontent.com/assets/11683218/7562102/8a261e52-f7c9-11e4-912e-a8e2aaa8fe36.png)

**Comment by mahagr** [comment]
Same as #188
