### ISSUE TITLE
Gantry 5 bug?

### ISSUE THREAD

**Issue by JimDee** [gantry/gantry5#2220]
If I go to Page Settings / Head Properties and save the following in the Custom Content box ...

`<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=PT%20Sans%20Caption:100,200,300,400,500,600,700,800,900">`

... and then save / refresh, the Custom Content box then shows:

`<l-ink rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=PT%20Sans%20Caption:100,200,300,400,500,600,700,800,900">`

In the first line, it changes "<link" to "<l-ink" thus disabling the HTML.  I'm pretty sure it does this in other boxes on the Page Settings area, such as in the "Before </body>" text box.

Seems like a bug, unless you're not allowing HTML in those boxes, for some reason.

This is on (v1.0.3 / rt_supra), Gantry 5.4.22

**Comment by w00fz** [comment]
I think it’s becauwb you have left it open. Try `<link />`

**Comment by JimDee** [comment]
Nope... the error persists when the tag is closed, as well.  

![image](https://user-images.githubusercontent.com/2186820/35354689-b2b4c1ba-00ff-11e8-8eca-4ed12c14a5f1.png)

**Comment by w00fz** [comment]
Ok looks like it's an issue we'll look into it. I think `<link>` is correct anyway, HTML5 has no closing tag.

**Comment by JimDee** [comment]
Thanks!  :-)

**Comment by w00fz** [comment]
BTW which platform is this? I just tried on Grav and seems to keep it correctly

**Comment by JimDee** [comment]
Sorry... Joomla 3.8.3, php 7.0.22, apache

**Comment by mahagr** [comment]
Doesn't happen to me in Joomla, I bet that this is some Apache/Joomla/server security module trying to prevent attacks to the site.

**Comment by kat05** [comment]
I just tried this on MAMP with Joomla 3.8.5, Helium and Gantry 5.4.22 and it keeps the code correct after saving and refreshing the page (link is still link and not l-ink).
Also tried Supra 1.0.5 without any issues.

**Comment by JimDee** [comment]
Glad to her it's not a Gantry issue, then.  I suppose maybe it's mod_sec on my shared host (Inmotion, in this case).  Strange, anyway.  But, thanks for looking into it.  (If anyone else has this issue & finds this thread, my current workaround is use Jumi & just use that box to call in some outside code like:   {jumi [path/to/mycode.php]}   ... and then put my HTML or whatever there. Works well in this case.)
