### ISSUE TITLE
favicon link is automaitcally created when favicon.ico is in the website root

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#2221]
This is a weired behaviour.

In the gantry admin you have the ability to set your favicon location etc.. in the default, base and {your template} layout. All of these in my template are disabled.

**My Template Outline**
![image](https://user-images.githubusercontent.com/319997/35390648-16a23bf6-01d4-11e8-8158-74c97e5ed05c.png)

If you upload a favicon.ico to the root of your website the following <link> code is automatically added (or a slight variation). If you then remove it the code is then removed.

````
<link href="/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
````

This should not happen. Gantry is detecting the favicon.ico file is present and then adds the code automatically.

https://realfavicongenerator.net/ recommends that you do not add this <link> as having the file is enough.  Also is an excellent resource for all things favicon.

Can you remove this automatic asset detection so i do not have the <link> code added.

The apple-touch-icon.png does not seem to do this.

Gantry 5.4.22
Joomla 3.8.3
Helium 5.4.22

**Thanks as ever**

**Comment by w00fz** [comment]
I believe what you are describing happening is actually Joomla doing.

https://docs.joomla.org/Special:MyLanguage/Changing_the_site_favicon

**Comment by shoulders** [comment]
I did not expect that. thanks for the heads up

I have verified that it is Joomla doing this and the new location of the code is /libraries/src/Document/HtmlDocument.php

I will go and post this on the Joomla github as it does need removing.

**Comment by shoulders** [comment]
Joomla bug report - https://github.com/joomla/joomla-cms/issues/19456
