### ISSUE TITLE
problem with calendar and categories

### ISSUE THREAD

**Issue by Pennailenia** [gantry/gantry5#2225]
calendar and categories widget don't work. If I click a category or a day in calendar I can't see all articles and I don't understand why. Can you help me?
I send link of my web site

[sjbeercockartwork.com/events/ ](sjbeercockartwork.com/events/)

[sjbeercockartwork.com/artgallery/](sjbeercockartwork.com/artgallery/)

**Comment by mahagr** [comment]
Looks like there's no JS errors.. Make sure that JS gets loaded for those 2, I think it's not.

**Comment by Pennailenia** [comment]
thank you for your answer, I found the issue, it was a conflict between
plugins

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mahagr** [comment]
@Pennailenia Were you able to work around it? And what was the another plugin?

**Comment by mahagr** [comment]
Closing the issue then as it was solved.
