### ISSUE TITLE
Ability to add class to a menu item and to change dropdown width for that menu item

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#223]
Suggested improvement for menu manager. 

1. Ability to add a class to a menu item (not menu)
2. Ability to set dropdown width for a menu item  (not just standard or fulllwidth) e.g. percentage or px value. (as you can in G4).

**Comment by adi8i** [comment]
1. Right now there's now way to do that in layout manager, but you can still add style the menu, each menu have an id and a class, you can see in the picture.
![1](https://cloud.githubusercontent.com/assets/9744973/7565012/faca2506-f7f4-11e4-8ea2-433c59155976.PNG)


2. you can set a dropdown width at `styles` - under `menu configuration styles` 
![capture](https://cloud.githubusercontent.com/assets/9744973/7564977/a96dc58c-f7f4-11e4-90e1-3614957b96bd.PNG)

**Comment by csbalazs** [comment]
2. That's true, but in G4 I can set different sizes each dropdown menu items.

**Comment by marktaylor46** [comment]
Thanks but that what I'm looking for. 
1. I want to be able to apply a class that I can use on several menu items (so ID class is no good)
2. I want different menu items to have different widths

The only way around at present is to use custom CSS.

Regards, Mark.

**Comment by adi8i** [comment]
i haven't tried and i am not sure if will work, but may be possible to override menu particle and add some code that will fit your need

**Comment by marktaylor46** [comment]
I can do it with CSS no problem. It's a feature suggestion to help others going forward.

Regards, Mark.

**Comment by csbalazs** [comment]
Further suggestion:
+ 3. Ability to set which menu is the default menu mobile.

**Comment by sural98** [comment]
+1 @marktaylor46.
If G5 is meant for the end-users many basic features should be in the core.

**Comment by marktaylor46** [comment]
Hence the suggestion (yes core) - the DEVS will look into it and reply.

Regards, Mark.

**Comment by adi8i** [comment]
Actually many feature requests here, are seen as basic from a coder view, a basic user will never think at, and g5 already have lot of configurations, a basic user will lose his head with all this configs anyway.

But of course there's all the time room for improvements.

**Comment by marktaylor46** [comment]
I disagree, this was available in G4, people have got used to it and are asking for it now. As an RT MOD I can tell you I have already been asked about it several times already.

Regards, Mark.

**Comment by csbalazs** [comment]
+1 marktaylor46

**Comment by w00fz** [comment]
1. I fail to see the benefit of having a way to add classnames to menu items when you can target them via css `:nth-child()` but I added the feature anyway, since it doesn't costs much extra code and since it's requested a lot

![hello-world](https://cloud.githubusercontent.com/assets/11734/7577591/d4515bba-f7fe-11e4-9128-880278bbc6cb.jpg)

2. @kevlardev is looking into this one

**Comment by sural98** [comment]
In this case some built-in classes would be helpful.
In G4 we were able to assign widths to each column for multi-column drop-downs and G4 was doing the rest.

**Comment by marktaylor46** [comment]
Because if you rearrange the menu items you would have to keep changing the CSS. It's much easier if the menu item itself has a class. Also, so you can affect many menu items with one CSS statement (if they all get given the same class), again cutting down on the CSS that you have to write.

Regards, Mark.

**Comment by sural98** [comment]
@marktaylor46 Then you will surely post a tutorial for us, the end-users :)

**Comment by marktaylor46** [comment]
@sural98 - I was answering @w00fz. At the moment you can only do what you want by adding custom CSS. That is why I am asking for the change. If you look in the Callisto forum on  RT site in solved topics you will see a topic where another member wanted the same thing and I answered with the CSS to achieve that.

Regards, Mark.

**Comment by sural98** [comment]
@marktaylor46 
I had seen your post.
Why I need to post here is that G5 needs more intuitive additions like https://github.com/gantry/gantry5/issues/228
so that we, the end-users will need less coding, css etc.
