### ISSUE TITLE
Owl Carousel disappears after gantry 5 update

### ISSUE THREAD

**Issue by giodocxman** [gantry/gantry5#2234]
Just updated to the latest Gantry 5 version, with an update to helium as well. Think its the Dec 17 update. My previously working Owl carousel has just disappeared.. Any ideas.. Shows up in the CSS, nothing rendered though..

**Comment by blizam** [comment]
disappeared how... is the Particle still present in the Layout Manager? Joomla, Grav, or WordPress? Have you flushed all CMS/server caches since upgrading?

**Comment by giodocxman** [comment]
Hi Matt, Apologies, Helium 5.4.22, on Joomla 3.8.4, disappears as in does not render anything in the browser. However, when I view the code with web developer on firefox, and chrome, you see the particle in the code.. 
![92bd tmp](https://user-images.githubusercontent.com/36161512/35818898-2436ac70-0a99-11e8-8e9c-35d8a22ca183.jpg)

**Comment by giodocxman** [comment]
and the Cache on Joomla is flushed..

**Comment by blizam** [comment]
looks like a CSS issue of some kind... does it work in a different Section? Anyway you can provide a link?

**Comment by giodocxman** [comment]
Running it on localhost atm.. It only works correctly in areas that don't have other modules.. (Modules from the helium UI).. Very strange. I've added very little custom CSS..

**Comment by giodocxman** [comment]
OK update, seems the owl carousel does not show only on the home page, assigned that layout to all pages, shows up on all pages except the home page.. Anyone got any ideas?

**Comment by giodocxman** [comment]
![3aa0 tmp](https://user-images.githubusercontent.com/36161512/35851329-a0b4e6c8-0b1f-11e8-84fe-666fdd287892.jpg)

**Comment by giodocxman** [comment]
ok further testing has revealed, that I've got a module that uses All Vids plugin, along with newsfalsh, to display latest videos, when this is disabled, the owl carousel appears again.. Worked fine before the gantry 5 update.. Perhaps the devs need to look into this. I've got other newsflash modules, that seem to be working fine with the owl carousel

**Comment by blizam** [comment]
So their is likely some CSS or JS in your other plugin that's conflicting with Owl... Owl uses jQuery and generally plays well with other plugins but it's best to always make sure you don't have multiple different jQuery libraries loading. You can check your browser Console for JS errors to see if that's the issue.... if it's free of errors then it's most likely a CSS issue that will have to be deconflicted

**Comment by giodocxman** [comment]
Yes I figured that.. But if its a JQuery conflict, then the devs at Helium/Gantry 5 will need to resolve it.. Any idea on how to get to get in touch with them?

**Comment by giodocxman** [comment]
OK problem solved, installed the free slideshow particle, 
http://demo.joomlead.com/particles/index.php/particles/slide-show

Everything is working ok.. Would be nice if the owl carousel that comes with gantry actually worked in this instance but oh well..

**Comment by mahagr** [comment]
As Gantry uses standard methods in Joomla to load jQuery, there cannot be any conflicts unless the other module/plugin breaks the Joomla standards. So the issue is likely not in Gantry, but in the other extension you installed.

**Comment by giodocxman** [comment]
Yes it was the AllVideos plugin, that clashed with gantry. So someone needs to fix their stuff..

**Comment by mahagr** [comment]
I found this by some Googling:

https://www.joomlaworks.net/forum/allvideos/48401-jquery-conflict-with-owlcarousel-js

**Comment by giodocxman** [comment]
Fantastic!.. Thx very much.. :)
