### ISSUE TITLE
How to migrate to a new domain?

### ISSUE THREAD

**Issue by renatocan** [gantry/gantry5#2235]
I've migrated a Wordpress website using Gantry to a new domain. After the migration, every image referenced by Gantry layout (using gantry-media://) pointed to the previous domain and were not shown. I've managed to correct some of the problems by manually setting the images (in the layout, by configuring the particle and setting the image) but for some particles this procedure does not work.

Is there a way to reset Gantry's domain settings or to use relative URLs?

Thanks,

Renato.

**Comment by DamirPecnik** [comment]
Is that located in Files or in Database? If in Files use search and replace for the URL. If in Database then you need to use this:  https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

**Comment by renatocan** [comment]
Thanks for the help. But isn't there a way to this within Gantry? Or even better, to configure Gantry to use relative URLs for the images?

[ ],
Renato.

**Comment by blizam** [comment]
gantry-media:// is relative... you probably just needed to flush the Gantry cache (extras menu) or any 3rd party caching you've installed after the migration.

**Comment by renatocan** [comment]
I did not notice Gantry had a cache. Clearing it solved the issue.

Thanks!

Renato.
