### ISSUE TITLE
gantry picker folder

### ISSUE THREAD

**Issue by waltersao** [gantry/gantry5#2238]
how can i select a folder in .yaml file?
example: filepicker exists for the file.
TIA
waltersao at email net it

**Comment by mahagr** [comment]
Filepicker accepts parameter named `root` which you can use to set the folder. Default is `root: gantry-media://`.

**Comment by waltersao** [comment]
Thank you.  I know this and use it.  But I only select files. I would like the name of the directory.
  image:
    type: input.imagepicker
    label: Image
    description: Select the main image.
    root:
    - test
    - gantry-theme://
    - gantry-media://

**Comment by mahagr** [comment]
I'm not sure what you mean. Do you need directory under webroot? I think it would work just like that.
