### ISSUE TITLE
can't update gantry 5 package

### ISSUE THREAD

**Issue by aana5i** [gantry/gantry5#2239]
Hello,

i am trying to update gantry 5 5.2.15 but i have a problem.

the gantry 5 package seem's missing

![update](https://user-images.githubusercontent.com/36354810/36070157-609c9c08-0f38-11e8-9ec4-1a909536fd8c.jpg)

![update2](https://user-images.githubusercontent.com/36354810/36070166-980a44ba-0f38-11e8-838b-c5b91d480844.jpg)

**Comment by w00fz** [comment]
Have you tried installing it manually by downloading it from the gantry.org site?

**Comment by aana5i** [comment]
it is risky ?

**Comment by w00fz** [comment]
No, just download the Joomla plugin and then install it via the installer in the joomla admin.
Do not uninstall anything, just install it again.

**Comment by aana5i** [comment]
thanks, the gantry component ?

**Comment by w00fz** [comment]
yes, https://github.com/gantry/gantry5/releases/download/5.4.22/joomla-pkg_gantry5_v5.4.22.zip

And also, you should make always a backup just in case :)

**Comment by aana5i** [comment]
yes thanks
