### ISSUE TITLE
Scss inks are broken

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2243]
There seems to be an issue with scss files

When i want to click in dev tools to open the file and go to that line

It loads wrong url

http://projects/http:/projects/xxxxx/wp-content/themes/g5_theme/scss/alamo/styles/_core.scss

**Comment by mahagr** [comment]
@DamirPecnik Should be fixed now.

**Comment by DamirPecnik** [comment]
Still not fixed ....

**Comment by mahagr** [comment]
Seems to be fixed in Gantry 5.5.
