### ISSUE TITLE
How can I use WooCommerce templates

### ISSUE THREAD

**Issue by aaloch** [gantry/gantry5#2244]
Hi,
I added the following file to Gantry's hydrogen child theme: 
/woocommerce/templates/cart/cart.php

this would normally change tha cart page, but it doesn't seem to take any effect at all, is there a way to get it working without of twig files.

**Comment by newkind** [comment]
The directory structure is wrong because of the `templates` directory. Please move it to `/woocommerce/cart/cart.php`
