### ISSUE TITLE
Question - Grav - Meta Tags of my Media

### ISSUE THREAD

**Issue by mgollmer** [gantry/gantry5#2247]
Hello there, 

I question myself, if adding metatags to images and other media works just like described here...

https://learn.getgrav.org/content/media#metafiles

If you re using gantry there is by default another image folder and it's just another way of adding the files to the system. 

Can anybody confirm the grav way or give a short describtion of how to add metag tags the images used in gantry.

Regards, 
Michael

**Comment by mahagr** [comment]
I cannot see why they wouldn't work.

**Comment by mgollmer** [comment]
Hello there, 

does it really work like in grav? So I only have to add a meta file and i will be found?

**Comment by mahagr** [comment]
Gantry doesn't have media support, so all the media comes from the Grav. That said, it can be that individual particles do not use media and just show the images as they are.
