### ISSUE TITLE
Problem with "&" character in Level 2 menu particle

### ISSUE THREAD

**Issue by mixahlos** [gantry/gantry5#2248]
Hi,
I have a really strange problem with the the Gantry menu and the "&" character in Hydrogen & Helium template.

Lets say I have the following Menu Structure : 
```
Home
Toplevel 1
-- Top 1 & Sublevel 1
-- Top 1 & Sublevel 2
Toplevel 2
-- Top 2 & Sublevel 1
-- Top 2 & Sublevel 2
```

When the **Toplevel 1** menu is active all the children items that contain the "&" character instead of "&" are displaying as "&amp;" but in the **Toplevel 2** submenu items is the "&" is fine.
This happens ONLY in MENU PARTICLE or MOBILE MENU PARTICLE and only In level 2 menu.
So I Am also displaying the menus as menu modules to see that there is no problem.

You can see the problem here : ```http://demo4.clickonlogic.com/media-gallery```
I have disabled any java or other external libraries just to be sure. I also disabled any custom css / scss.

**Comment by N8Solutions** [comment]
I had a look at your site and this is indeed a very strange issue. I hope that @w00fz & @mahagr will be able to help you figure it out.  Good Luck!

**Comment by mixahlos** [comment]
I also tried to display other special characters and this is happening only with "&" char.

**Comment by mahagr** [comment]
I'm not able to reproduce this issue. If you can, please walk me through on newly installed RL how to reproduce the issue.
