### ISSUE TITLE
Unable to overwrite existing configuration directories

### ISSUE THREAD

**Issue by wpompen** [gantry/gantry5#225]
I tried to duplicate a configuration before, folders were created then. I guess the overwriting was not allowed .
An exception has been thrown during the rendering of a template ("mkdir(): File exists") in "partials/configuration-selector.html.twig" at line 12.

**Comment by w00fz** [comment]
Did you check if the folder permissions are correct?

**Comment by mahagr** [comment]
It looks like real issue for me; mkdir should check if the directory/file is already there.

**Comment by wpompen** [comment]
Unless (by some mysterious way) the permissions were changed, they should be ok since they're created by "it"  self?

**Comment by mahagr** [comment]
Thought I found the issue, closing this for now. Let me know if it happens again.

**Comment by DanGthatRokGallery** [comment]
It happened again mahagr -> http://www.rockettheme.com/forum/joomla-template-ambrosia/244909-runtime-exception

**Comment by mahagr** [comment]
In the future I would prefer also having a new bug pointing to the old one once the version where it was fixed was released. :)
