### ISSUE TITLE
WordPress - Particles are disapearing on Widgets area.

### ISSUE THREAD

**Issue by mlyngraficzny** [gantry/gantry5#2252]
Hi. I create a website on WordPress with Gantry 5 framework.

I noticed that when I add "Widget Positon" someware, and I add some particle in WP widgest, they dissapear on backend, but you can see it on website. So I can't edit them on backend. :( 

After log out/ log in particles disapear on the website too.
--
I heard about problem like this on G Chorm. The same problem I have in Firefox.

What can I do to fix this problem?
----
Please, check the screen with GOOGLE MAP and SLIDESHOW particle.

![screen2](https://user-images.githubusercontent.com/37270276/37255443-c70a36ce-254c-11e8-8423-ff5b887dbf29.jpg)

**Comment by mahagr** [comment]
WP 5.8 replaced widgets area with Widget Blocks.
