### ISSUE TITLE
Remove "particle defaults" tab by default

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2253]
As per conversation with the RT team. Remove the "particle defaults" tab from Gantry 5 admin but also leave the options to have an "expert mode" to reinstate the tab for advanced users.

Now that we have "inheritance" there is really no need to use the "particle defaults" tab at all and it seems to greatly confuse novice users.

**Comment by kat05** [comment]
+100

**Comment by mahagr** [comment]
This has already been implemented (defaults only show up in base outline)
