### ISSUE TITLE
Errors reported in PHP 7.2.1 "The each() function is deprecated"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2254]
Please see this RT forum topic:

http://www.rockettheme.com/forum/joomla-template-supra/275441-solved-error-production-mode-exception-the-each-function-is-deprecated

Gantry 5 seems to break with PHP 7.2.1 (stack trace in topic). Regressing to PHP 7.1 resolves the issue.

**Comment by moraks** [comment]
> Please see this RT forum topic:
Need member Login for see this forum
But this error is reproduced from me too.
`[php7:notice] [pid 2772:tid 1912] [client ::1:59752] PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in ...\administrator\\components\\com_virtuemart\\helpers\\html.php on line 498, referer: ***/administrator/index.php?option=com_installer&view=install`

**Comment by marktaylor46** [comment]
That’s an issue in virtuemart not Gantry so you should contact them about that.
