### ISSUE TITLE
array_intersect_key(): Argument #1 is not an array

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2257]
When trying to clear the inheritance from the section i can clear it from 2 of the Replace sections:
 Section Attributes
 Particles within Section

But when i tried with clearing this section i get this error:
Block Attributes

![2018-03-20 01 34 42](https://user-images.githubusercontent.com/10489911/37629409-e6747130-2bde-11e8-8b01-808f7ea36db6.jpg)

![2018-03-20 01 27 51](https://user-images.githubusercontent.com/10489911/37629392-d3be0fba-2bde-11e8-81f0-9e9752132c51.jpg)

**Comment by mahagr** [comment]
@kat05 Are you able to reproduce this issue with Fluent?

**Comment by mahagr** [comment]
@DamirPecnik Can you check if the fix works for you?

**Comment by kat05** [comment]
I am not able to replicate the issue with Fluent, using new Gantry 5.4.24
