### ISSUE TITLE
WordPress: Image `resize` filter in particles

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#2258]
I am not able to resize the featured image in a particle, using [resize filter](https://timber.github.io/docs/guides/cookbook-images/#arbitrary-resizing-of-images). It works in theme views only.

Code example:

```
{% set posts = wordpress.call('Timber::get_posts') %}
{% for post in posts %}
    <img src="{{ post.thumbnail.src|resize(640) }}" />
{% endfor %}
```

**Comment by adi8i** [comment]
I am unsure about this one, might be related to server configuration or other things. I'll re-open if needed.

**Comment by mahagr** [comment]
Gantry is using it's own instance of twig, though the filters should be there unless Timber has changed something.

**Comment by adi8i** [comment]
The filter works on a live server, but it don't work on docker and c9.io, maybe I have to configure something..
