### ISSUE TITLE
#g-page-surround from _main.scss conflict with modal

### ISSUE THREAD

**Issue by anjoclaudio** [gantry/gantry5#226]
Modal popup was not working correctly. Traced the issue to this code in the file hydrogen/_main.scss
#g-page-surround {
    @include transform(translate3d(0, 0, 0));
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.4);
}

If i change the code to 
#g-page-surround {background:#fff;} 
modal works.

**Comment by w00fz** [comment]
The transform is required for the Offcanvas to work, what modal popup where you using that didn't work? It might not be a Gantry 5 issue.

**Comment by mahagr** [comment]
@kevlardev Does this relate to the issue: 

https://github.com/gantry/gantry5/commit/f4da2eccc35fb1bcc82f5eea92d4ba05d5d3bf57

Looks like the branch has one extra commit in it.

**Comment by adi8i** [comment]
i think is the same story for fixed nav, will not work fine inside g-page-surround.
