### ISSUE TITLE
Translate default strings in twig [joomla][help wanted]

### ISSUE THREAD

**Issue by PhocaCz** [gantry/gantry5#2264]
Hi, I am very new to Gantry5 (testing only), so sorry for lack of my G5 knowledge. I have read some "multi-language" issues but not sure if they are the same I want to ask.

Is there same way how to translate strings set in twig templates? I can add my own solution, but it requires overwriting of default language stings and I am not sure if this isn't too complicated.

Example:
_media\gantry5\engines\nucleus\particles\totop.html.twig_

changing FROM:
`{% if not particle.icon and not particle.content %}To Top{% endif %}`

TO:
`{% if not particle.icon and not particle.content %}{{gantry.G5Translate.translate('TPL_G5_HYDROGEN_TO_TOP')}}{% endif %}`

The following PHP class is included in template:
```
class G5Translate {
	public function translate($text) {
		return JText::_($text);
	}
}
$gantry['G5Translate'] = new G5Translate();
```
does the trick. So, if there is for example:
_language\de-DE\de-DE.tpl_g5_hydrogen.ini_

with:
`TPL_G5_HYDROGEN_TO_TOP="Nach Oben"`

it is translated well. 

![To Top](https://i.imgur.com/9zljawX.png)

But this solution requires overwriting of all twigs with language strings, so the question is if there is some better, faster and easier way?

Thank you, Jan
System: Gantry5, Joomla! 3.x, PHP7

**Comment by mahagr** [comment]
Gantry has `|trans` filter which you can already use to translate the strings. Just remember to add English versions of the translations as well.

You can make a pull request to fix translation issues you find (in Gantry itself). :) Github has pretty good instructions on how to do it and it should be simple enough. :)

**Comment by hjelperne** [comment]
Yes. Some doc/example for the |trans filter would be greatly appreciated!

**Comment by mahagr** [comment]
There's really not much to document, you just pass language key:

```twig
{{ 'GANTRY5_THIS_IS_MY_KEY'|trans }}
```

And then define it as you would in your platform of choice.

**Comment by PhocaCz** [comment]
Yes, very easy, thank you for sharing.

Jan
