### ISSUE TITLE
Adding menu items from another menu, or how to override Gantry Menu Class.

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2266]
Not sure, but I think I have seen somewhere about adding custom menu items on Gantry's menu. Is this possible? 
Actually, what I am after is to be able to include menu items from other menus as children items for a Gantry "Mega menu"  with columns, where the actual menu items of that menu would be at the top of the columns and the extra will be below.

Obviously, I can go and create alias menu items in my main menu for those additional items. 
However there are a few things that I don't like with this approach. 
First, in Joomla's menu manager this is going to be somewhat confusing, as all these menu items will have to be on the same level.
Then, it requires double manual work to create aliases and then to maintain the aliases in case the target menu item has changed.

So, it would be just perfect if I could just select and add those desired menu items from Gantry's Menu Administration - which I guess it's not possible currently - but it would be a nice to have feature.

Furthermore, I would like to know how I could go about overriding Gantry's Framework Menu Class. Is there any example or documentation somewhere on how we can override core classes?

**Comment by N8Solutions** [comment]
Hello @joomlabeat 

For the menu feature you are requesting @w00fz is the best person to ask.

As far as overriding the Gantry custom classes you can refer to this document:
http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet


regards,

Michael

**Comment by mahagr** [comment]
It's not really possible as we're using Joomla to handle most of the menu tasks. So you can do what you can do in Joomla and not much else except adding particles.
