### ISSUE TITLE
Page Not Found - can not save on wordpress

### ISSUE THREAD

**Issue by minhphong2311** [gantry/gantry5#2267]
I change the content but can not save ..with full debug on, the error I get is
![gantry](https://user-images.githubusercontent.com/37891754/38070928-ace8a8fc-3348-11e8-848d-d1c3ff540492.png)

**Comment by mahagr** [comment]
@minhphong2311 Looks like you have mod_security or some similar firewall action blocking response because of it thinks that HTML has SQL attack in it.

**Comment by minhphong2311** [comment]
thanks @mahagr

**Comment by mahagr** [comment]
@minhphong2311 Have you figured out what it was?
