### ISSUE TITLE
Wordpress Engine Override Has No Effect in Child Theme on Multisite 

### ISSUE THREAD

**Issue by jwwicks** [gantry/gantry5#2269]
As a Wordpress theme developer I would like to be able to override Nucleus engine files in my child theme on a multisite install. Currently placing the files in the directories outlined in the docs has no effect on child themes. Placing them in the blog specific directories also has no effect.

Given I have an active child theme in Wordpress Multisite based on a Gantry theme
When I override a Nucleus engine file such as /wp-content/plugins/gantry5/engines/nucleus/templates/page_head.html.twig by placing it in blog specific directory /wp-content/themes/Child-Theme/custom/Blog-Id/engine/
Then changes to it will override the base engine file

**Comment by jwwicks** [comment]
@newkind Has zero effect on a child theme in a multisite install.

![image](https://user-images.githubusercontent.com/702596/38293451-5da9bb66-379c-11e8-8772-cc19702e5271.png)

This should have killed the site. Didn't. Believe me I've tried just about every combination of folders including placing them in the parent theme folders with no luck.

**Comment by newkind** [comment]
Ok, I just checked my installation and although it isn't multisite, the directory structure you mentioned is wrong. The original file location in Nucleus is under `nucleus/views/partials/page_head.html.twig` and this is what you should use. It worked fine in my child theme under `custom/views/partials/page_head.html.twig`

**Comment by adi8i** [comment]
Sorry for jumping in, just for the records.

`engines/nucleus/templates/page_header.html.twig` is the base file and
`nucleus/views/partials/page_head.html.twig` extends it

As newkind said, you have to overwrite `nucleus/views/partials/page_head.html.twig`, this file is loaded by the theme:
```
$context['page_head'] = $theme->render('partials/page_head.html.twig', $context);
```

And here are two ways of doing it:
1. Extend the base file and overwrite certain blocks.

```
{% extends "@nucleus/page_head.html.twig" %}

{% block head_title -%}
    {# Code goes here #}
{%- endblock %}
```

2. Don't extend the base file and write the code from scratch. Hardly ever needed, you won't need to do this 99% of the time I guess.

**Comment by jwwicks** [comment]
@NewKind and @adi8i,

I'm just trying to follow the [docs](http://docs.gantry.org/gantry5/advanced/customizing-theme-files#engine-files) which makes it seem like we can override these templates files themselves.

Either we can't do it, override a base file, in which case the docs should say so. Or there's something I'm missing which I'd like to document. I've already started updating the docs with some multisite notes about the directory structure for other sections but would like to figure out this part as well.

I'll try and go through all the permutations from just Theme_Dir/custom to Multisite-Theme_Dir/custom/blog-id to Child-Theme_Dir/custom etc... 

@adi8i So if I'm understanding this correctly, the only way to override engines/nucleus/templates/page_head.html.twig completely is through the views/partials file and writing it from scratch in that file. If all you want to do is add say include an IE style sheet or something you extend the base and then just add to the existing block in the partials file.

`{% block head_ie_stylesheets -%}
        
{% endblock -%}`

And for a multisite, child theme the correct directory for this file is:
/wp-content/themes/ChildTheme_Dir/custom/blog-ID/views/partials/page_head.html.twig

![image](https://user-images.githubusercontent.com/702596/38334962-b3f576f2-3811-11e8-9707-838d384a8d00.png)

Thanks for the clarification.

**Comment by mahagr** [comment]
You can override almost every file by copying it into custom, but it's not always the proper way to do it as sometimes future version may be incompatible with your override. So while you can override everything, you should be careful what to override and make sure updates won't break with your changes.
