### ISSUE TITLE
Override of font-awesome.min.css in custom folder doesn't seem to be working

### ISSUE THREAD

**Issue by anjoclaudio** [gantry/gantry5#227]
Placed font-awesome.min.css in custom folder under folder 'css' . It loads in the header but icons fail to load both in admin template and frontend.  
bootstrap-gantry.css seems to be working fine.

**Comment by w00fz** [comment]
Why did you need to override `font-awesome`? We are already providing it to the latest version.

**Comment by anjoclaudio** [comment]
I don't have a need for this function. I was just testing the examples in the documentation and found override font-awesome was not working.

By the way congratulations on the amazing work done on gantry 5.

**Comment by w00fz** [comment]
Thank you!
Which documentation did you referenced to? It might be out of date and we might need to update it.
Also where did you download font-awesome from?

**Comment by mahagr** [comment]
@FrugalGeek Might be some issue in the doc?

**Comment by anjoclaudio** [comment]
Gantry 5 docs under Gantry 5 Framework (Library) examples
http://docs.gantry.org/gantry5/advanced/file-overrides

I used the same font-awesome file shipped with gantry 5 in media folder

**Comment by mahagr** [comment]
I just copied FontAwesome (both css and the font files) into templates/g5_nucleus/custom and it works just fine. 

Documentation seems to be correct as I just copied css/ and fonts/ folders as they were.
