### ISSUE TITLE
Hydrogen gantry5 theme empty styles.yaml

### ISSUE THREAD

**Issue by ghost** [gantry/gantry5#2270]
This issue for Theme: Hydrogen (v5.4.22 / g5_hydrogen)
after updating wordpress to version 4.9.5 each time open hydrogen theme on the styles; the styles preset reset to default ..... after investigation i found that file 
/wp-content/themes/g5_hydrogen/custom/config/default/styles.yaml 
automatically resetting it's value to { } and all the style settings are gone .
i fix this issue by change chmod for file styles.yaml to "444" to prevent file writing; but this is just a temporary fix.

**Comment by mahagr** [comment]
I cannot reproduce the issue. The file doesn't change unless I save the changes in the styles tab and even then it remembers the settings I've been using.

**Comment by hatem-badawi** [comment]
this issue happens when you leave the default style without any changes ;  just change the styles present from preset1 to preset2 or preset3 .
if you change any value in the default styles this problem doesn't appears ;and so you will not be able to reproduce the issue.

**Comment by mahagr** [comment]
@hatem-badawi 

Unfortunately no, it just asks me if I want to save/discard/stay and all of those options work just fine for me. Have you tried this with a clean WP installation?

**Comment by hatem-badawi** [comment]
get clean wordpress copy and install hydrogen theme the go change style preset1 to preset2 and save
then go to another link then come back to hydrogen theme page you will find preset2 as you saved it,
then go to another link then open again hydrogen theme ;this second time you will find style reset to preset1 .
 try this and tell me if you able to found the issue

**Comment by kat05** [comment]
I will give this a try now and report back.

**Comment by kat05** [comment]
Ok, I followed your steps and I am not able to replicate the issue.

I changed from Preset1 to Preset2 in Base outline, saved, then went to 'Comments', went back to Hydrogen and still saw Preset2. Then I went to 'Pages' and then back to Hydrogen and it's still on Preset2, then went to 'Plugins', then back to Hydrogen and it is still on Preset2.
Please let me know if you need me to try any other steps to replicate.

**Comment by mahagr** [comment]
Thanks @kat05, you confirmed my findings on the issue.

**Comment by newkind** [comment]
Is there a possiblity that you could upload us your whole theme directory to investigate?
