### ISSUE TITLE
Call to undefined method Compiler::setSourceMap

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2271]
Pleas see forum topic http://www.rockettheme.com/forum/joomla-template-supra/275886-call-to-undefined-method-gantry-component-stylesheet-scss-compiler-setsour?start=0#1381845

Members site fails with the above error on compile of CSS. If I change to "production" mode instead of "development" mode it works around the issue.
![2018-04-06_09-36-45](https://user-images.githubusercontent.com/11683218/38411322-bf17f2f8-397e-11e8-890e-7bf228904480.jpg)

**Comment by marktaylor46** [comment]
The extension "System - SunFw Framework" seems to be the cause of this issue.

**Comment by mahagr** [comment]
The extension is using old version of SCSS compiler -- Gantry needs the latest. Deleting the `vendor/leafo/phpscss` folder from the another plugin (or library) will help to fix this as long as Gantry is enabled on all pages.
