### ISSUE TITLE
Register to read more points to wrong URL

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2272]
Hi,
I have a strage problem. 
On my gantry site, the link "Register to read more" ("**Registrati per leggere il seguito...**" button) it points to the home page. The correct behaviour should be to point to the login page.
This is (one of) the page: (http://localhost/tanase/index.php/guide/creare-un-form-di-login-con-gantry-che-si-apre-in-una-popup)
I followed this guide: https://docs.joomla.org/Restricting_access_to_%22read_more%22
The template is Hydrogen.
Where is the problem ? And how to fix this ?

NOTE: I mention that with the protostar default joomla template, it points to the correct page (e.g. login page).

Thanks

**Comment by N8Solutions** [comment]
@mariantanase Do you have a live link where the site can be inspected? The link you posted is unavailable.
