### ISSUE TITLE
Particle tamplate(twig) do not work in child theme

### ISSUE THREAD

**Issue by GBitweb** [gantry/gantry5#2274]
Hello.
Im using Gantry with Grav.
I created new child theme with command: 
`bin/plugin gantry5 childtheme -p g5_helium -c helium_aroma`
particles from directory:
`grav/user/themes/g5_helium/particles/`
works well but when I want add new particle to
`grav/user/themes/helium_aroma/partilces/`
gantry don't see those files.

**Comment by drnasin** [comment]
could it be a typo? grav/user/themes/helium_aroma/partilces <- typo?

**Comment by mahagr** [comment]
I tested this locally and new particle appeared to the layout and works just fine.

Yes, I'm thinking it was a typo as well.
