### ISSUE TITLE
Blocks stylesheets and javascript do not work as mentioned.

### ISSUE THREAD

**Issue by GBitweb** [gantry/gantry5#2275]
I'm using Gantry with Grav.
When I created new particle with `{% extends '@nucleus/partials/particle.html.twig' %}` at the beginning
`{% block stylesheets %}` and `{% block javascript %}` intert code just before `{% block particle %}` in html and not as mentioned to `<head>`.

**Comment by adi8i** [comment]
I think there are better ways to load css / js, check this page: http://docs.gantry.org/gantry5/advanced/css-js-twig#load-css-js-in-gantry-53

**Comment by GBitweb** [comment]
OK. I can agree, but at first those blocks are mentioned in _Particle Template_ in [docs](http://docs.gantry.org/gantry5/tutorials/particle-blocks) and second i can't add for eg. hreflang link entries via `gantry.document.addSomething`
