### ISSUE TITLE
Menu Item Link Target - GUI not reflecting changes

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2277]
There seems to be an issue with the Gantry menu items and the assigned target. If I change the target for a menu item the setting is saved and reflected as long as I stay in the menu settings of Gantry. 

However as soon as I do a refresh on the site or navigate to e.g. the outline settings and then go back to the menu, the setting is resetted to the previous option (just in the GUI - in the background it has been saved correctly and also reflected on the frontend).

The wrong option seems to persist until the cache is cleaned.

**Comment by mahagr** [comment]
Looks indeed that there's caching issue.

**Comment by mahagr** [comment]
This should be fixed with my commit today.
