### ISSUE TITLE
Roboto font is loaded from google

### ISSUE THREAD

**Issue by nadjak77** [gantry/gantry5#2279]
Hi,
I added my fonts to the theme like descriped in the docs (http://docs.gantry.org/gantry5/tutorials/fonts).
That works fine.
But there is still the font "roboto" loaded from google.
I cannot find it in my files.
And the roboto font is still local in the font directory from the theme.
Can you help me, how to don't load the roboto ?
Thank you
Nadja

**Comment by mahagr** [comment]
It could be loaded from the theme itself, or you can have Styles setting pointing to the Roboto font.

Which theme are you using?

**Comment by nadjak77** [comment]
I use the hydrogen theme.
I think the theme loads the font. But I cannot find where. Has anyone an idea?
Thank you.

**Comment by N8Solutions** [comment]
Hello @nadjak77,
Have you changed the font in the Outlines, ie Base, Default, & Home Outlines? It's located under the Styles tab on the top left.
![image](https://user-images.githubusercontent.com/12389693/39491394-ef163dd2-4d94-11e8-96a1-1e52eab81608.png)

**Comment by nadjak77** [comment]
Yes, in every template the fonts are set to roboto lokal.
The site is: https://www.urlaubinbadsaarow.de/

**Comment by N8Solutions** [comment]
As I asked above @nadjak77,
Have you changed the font in the Outlines, ie Base, Default, & Home Outlines? It's located under the Styles tab on the top left.

Meaning you can change roboto to something else. I have removed roboto on several sites and replaced it with a different font and roboto does not load.

**Comment by nadjak77** [comment]
Yes, I changed it on every Template.
I removed it also in another site and there were no problems.
But in this site I cannot find the place whitch load the google fonts.
NAdja

**Comment by N8Solutions** [comment]
@nadjak77 can you post a link to your site?

**Comment by nadjak77** [comment]
You can see it in Post #4
> The site is: https://www.urlaubinbadsaarow.de/

**Comment by N8Solutions** [comment]
@nadjak77 I've inspected your site and I see that the Roboto font is loading. However, as I wrote [above](https://github.com/gantry/gantry5/issues/2279#issuecomment-385776081), you need to remove the Roboto font and select something else. If you do not do that it will not stop loading it. Not only that, you need to make sure that every outline is inheriting the font from the Base Outline. I just removed the font from a different site which is my testing site and if you inspect the site you'll see that the roboto font is no longer loading. I also added it to only one page and it is only loading the roboto font to that particular page.

[This page](https://g5test.te.n8solutions.org/box-test) has the Roboto font loading and all the others do not. Inspect that page first to see that it's there and then inspect the others, you won't find it.

Please double check your outlines and make sure they are all inheriting from the base outline and that you have properly entered in your new font in correctly.

regards,

Michael
