### ISSUE TITLE
HELIUM template : Error in _header.scss

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2281]
The HELIUM template _header.scss is incorrect in that it is generating two "background" attributes in the CSS when there is both a background color and a background image.
![2018-04-20_11-10-49](https://user-images.githubusercontent.com/11683218/39045855-15b9baca-448c-11e8-8810-197904313a36.jpg)

**Comment by mahagr** [comment]
@newkind Please take a look at this when you have a chance.
