### ISSUE TITLE
Atom / Particle - Language Detection

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2287]
I've come across an issue which I really can't solve and didn't find a solution for. Is there a cross CMS way to determine the current page language? Because I wan't to exchange some strings within an Atom depending on the current language.

I know if I use a particle within Joomla I would be able to create multiple particles for different languages which would then automatically be loaded correctly if configured so. However for Atoms I don't have that option. So it would be great if there is a way to determine the current language. I appreciate some help or suggestions on this topic.

**Comment by mahagr** [comment]
Try

```twig
{% set language = gantry.page.language %}
...
```

**Comment by thexmanxyz** [comment]
@mahagr Thanks you very much for the help that's great, didn't know about that attribute :). Exactly what I need.
