### ISSUE TITLE
System messages particle - hydrogen (!Joomla)

### ISSUE THREAD

**Issue by bomkallo** [gantry/gantry5#2294]
Since quite a time i'm wondering what's the idea behing system messages particle in g5-hydrogen.
It's description says: "Always include this particle to all of your layouts. Otherwise users will not see important system messages like login failures."

Well, I've found it a bit annoying while writting my own modules/coms in Joomla. As it comes out from native !J, the container for messages should be named #system-message-container as it is equivalent to !J <jdoc:include type="message" />. Hydrogen instead does the wrong thing, it does add #g-system-messages which is not compatible with core.js/validate.js and thus you will hit a nice red error in your console window when you play with ajax and custom validators.

I'm writting this issue because I don't know the real intention of this particle. Sure I can add my custom container in place of that particle, but then what's the reason to use particle then?
Looks like a bug to me as gantry always pass g- before if you won't force it to do the other way.
The last note: as i checked beez, #system-messages-container is always added - provided you want to see proper errors from validators. It looks like sometimes it works, but i doubt that #system-m... is injected via script into #g-system when it detects errors lol :P 

I'll be glad hearing some explainations because maybe i've missed something.

PS: media/system/js/core-uncompressed.js line 366:
	Joomla.removeMessages = function() {
		var messageContainer = document.getElementById( 'system-message-container' );

**Comment by thexmanxyz** [comment]
@bomkallo try overriding

`media\gantry5\engines\nucleus\templates\content\system.html.twig` replace the identifier with the one you want. In your case `g-system-messages` to `system-message-container`. Mind that you have to create a copy in the appropriate folder to create an override.

**Comment by bomkallo** [comment]
I know the idea of overrides, i don't get the default behavior which has no point in any situation.

**Comment by thexmanxyz** [comment]
@bomkallo Just wanted to provide a fix because you will need it anyway...

**Comment by bomkallo** [comment]
Just a small update. I was wondering why messages tend to work. It looks like gantry detects if there are any messages to be displayed and then #system-message-container is injected into #g-system...
Well it works at standard processing level, still, the absence of this container will break javascript validators I mentioned.

**Comment by mahagr** [comment]
System messages particle allows you to move Joomla alerts (login failed etc) to where-ever you want them to be.

The only thing the particle does in Joomla is to add `<jdoc:include type="message" />` into the document, so as long as Joomla puts any content into the include, it should work. 

For some reason, it looks like Joomla doesn't add the html if there aren't any messages.

**Comment by bomkallo** [comment]
Well, it used to be a long time it exists so you'd better put that container inside particle to be accessable all the tie and you're done & compatible :) As I've noted before, beez puts this container all the time, no harm then.

**Comment by mahagr** [comment]
@bomkallo Maybe Joomla has some kind of flag which changes the behaviour on latest versions? Because I know it used to show up all the time.

**Comment by mahagr** [comment]
@bomkallo Found out the reason why it is missing. Looks like our override for `html/layouts/joomla/system/message.php` doesn't include the container when there's nothing in there. If you delete it, you will get the original version, though it may cause some layout issues in some themes (which I believe is the reason why the container is missing).

CC @hexplor @newkind

**Comment by bomkallo** [comment]
Yea override is:
<?php if (is_array($msgList) && !empty($msgList)) : ?>
	<div id="system-message-container">
Original:
<div id="system-message-container">
	<?php if (is_array($msgList) && !empty($msgList)) : ?>

You're going to change this in any of future releases?

**Comment by mahagr** [comment]
Should be fixed now in Helium/Hydrogen
