### ISSUE TITLE
[BUG] [WordPress] Custom breakpoints not working

### ISSUE THREAD

**Issue by jrc2** [gantry/gantry5#2295]
When I add custom breakpoints in the backend (in pixels), the breakpoints in helium.css are not correct. This leaves (at least in my case) 5 pixels between phone and tablet, and 5 pixels between tablet and desktop that are not styled correctly. I am trying to get the breakpoints to match Elementor's breakpoints.

**Comment by newkind** [comment]
That's correct and it has been made on the purpose. The difference should be 1px and not 5px and it was made like that as breakpoints can't overlap themselves.

```
// Breakpoint Variables For Particles
$media: "all" !default;
$mobile-only: "#{$media} and (max-width:#{$breakpoints-tablet-container - 0.062})" !default;
$no-mobile: "#{$media} and (min-width:#{$breakpoints-tablet-container})" !default;
$small-mobile-range: "#{$media} and (max-width:#{$breakpoints-large-mobile-container})" !default;
$large-mobile-range: "#{$media} and (min-width:#{$breakpoints-large-mobile-container + 0.063}) and (max-width:#{$breakpoints-tablet-container - 0.062})" !default;
$tablet-range: "#{$media} and (min-width:#{$breakpoints-tablet-container}) and (max-width:#{$breakpoints-desktop-container - 0.062})" !default;
$desktop-range: "#{$media} and (min-width:#{$breakpoints-desktop-container}) and (max-width:#{$breakpoints-large-desktop-container - 0.062})" !default;
$large-desktop-range: "#{$media} and (min-width:#{$breakpoints-large-desktop-container})" !default;
```

**Comment by jrc2** [comment]
I understand a 1px difference, but there are 5px between each breakpoint that are streched out and don't fit in the screen right. For example, from 762px to 767px, the styling is messed up with the breakpoint set to 768px.

**Comment by jrc2** [comment]
@newkind ok, I'll try that. (sorry, I couldn't see your edit when I replied to the email notification)

**Comment by jrc2** [comment]
@newkind I switched to rem. Now I just have 1px between each breakpoint that is not styled correctly. Is there anything I can do so the site is usable at the in-between pixels?

**Comment by newkind** [comment]
Not really. Make your site look as best as possible when there is no breakpoint in the works. There's really no way around it. Besides - devices have their resolutions all set at certain points - you won't really find a device that would scale like browser window on desktop (pixel by pixel). If you think you'd "hit" a device breakpoint - modify your breakpoint sizes so that they would work with that device.

**Comment by jrc2** [comment]
Ok. I've just never run into an issue like this with my hand-written css files on static websites I've made. I always have had the max-width of one media query one pixel less that the min-width of the next. For example, if one has a max-width of 400px, the next media query would have min-width of 401px, so both 400 and 401 are styled correctly.
