### ISSUE TITLE
Changing Google Analytics Tracking code implementation

### ISSUE THREAD

**Issue by coolman01** [gantry/gantry5#2298]
Now that Google Analytics has changed the code to ensure anonymisation, is this likely to be included in the script behind the field where the analytics user ID is entered, or are we having to add the complete script in the header instead?
See the image I was sent.
![ga-tag](https://user-images.githubusercontent.com/6746747/40300748-714652ba-5cea-11e8-8686-0316922a6193.jpg)

**Comment by N8Solutions** [comment]
@coolman01 Thank you for bringing this up. GDPR compliance is very important for me. I look forward to hearing from the Gantry 5 team about this. In the interim a solution would be to disable the default Google Analytics Atom and simply add the code manually in order to be compliant.

**Comment by marktaylor46** [comment]
The existing analytics atom code already anonymizes IP???
![2018-05-21_10-47-36](https://user-images.githubusercontent.com/11683218/40301824-2a3bd69c-5ce5-11e8-83e9-2c36fa5620dd.jpg)

**Comment by N8Solutions** [comment]
Thank you for the reply @marktaylor46 !

**Comment by coolman01** [comment]
I just discovered that - thank you and sorry for wasting time.
Regards
David

**Comment by webmasterab** [comment]
@mahagr As I read in your reply, this is now included in the update of 5.4.24.
Is there a timeline to indicate when this update is coming?

**Comment by N8Solutions** [comment]
Webmasterab, According to [Mark Taylor's response](#issuecomment-390608342) above this is already included in Gantry 5. This begs the question now as to why Matias milestoned this?

@webmasterab @marktaylor46 @mahagr

**Comment by mahagr** [comment]
Milestone is always set to the latest version, eg. wehn the issue was closed.
