### ISSUE TITLE
Can I define a different outline from the defaut outline to show the articles in joomla...?

### ISSUE THREAD

**Issue by educastellini** [gantry/gantry5#2299]
I wanted to be able to define a different outline than I use in home to show the articles in joomla, I read about the methods to do this in joomla but apparently in Gantry a different method has to be used, please someone knows how to make this change.

**Comment by marktaylor46** [comment]
This is normal Joomla behaviour for "orphaned" or "menuless" articles. To get around this use the hidden-menu technique.

Create a MENU called "hidden" (no need to create a module to place it anywhere). In the hidden menu, create a MENU ITEM for each of the orphaned articles (single article type) and make sure these menu items are published. Now the hidden menu won't appear on any of your pages, but, the articles will now open in their own page. You can also use the same technique and create a hidden category blog menu item to pick up multiple articles too, thus saving having to create a hidden menu item for every article.

Once you have the menu items you can assign whatever outline you need to use to those.

**Comment by educastellini** [comment]
Yes it worked perfectly with both methods, or with "single article type" for a single file and with "category blog", worked with the whole category.

Thank you very much...!!!

**Comment by marktaylor46** [comment]
Great. Please close the ticket then. :)
