### ISSUE TITLE
Layout manager - cannot remove empty spaces

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#23]
Impredictible control when drag-n-drop "Sample Content" particles on layout. Cannot remove empty spaces.
![gantry-shot01](https://cloud.githubusercontent.com/assets/3976174/6895403/198d2776-d6e0-11e4-9d53-d534708c694a.png)

On frontend:
![gantry-shot02](https://cloud.githubusercontent.com/assets/3976174/6895406/22513e2e-d6e0-11e4-9a4c-e9ec847debf3.png)

**Comment by mahagr** [comment]
@w00fz Might be something for you?

**Comment by mariantanase** [comment]
What do you mean ? I cannot remove that empty space from backend who generate three empty spaces on frontend .

**Comment by w00fz** [comment]
We are having troubles reproducing it, we cannot in any way get the empty row to appear above particles. The way it's supposed to work is to automatically remove empty rows, even on Save this should happen.

Which browser and OS are you running on?
Also what I see on your screenshot is that it's missing the placeholder "Drop particles here..". Do you see it if you add a row in another section? Are you able to reproduce this in another section?

![gantry 5 - administration 2015-03-30 11-19-41](https://cloud.githubusercontent.com/assets/11734/6903369/b007f0da-d6ce-11e4-8174-76b452d8eb41.jpg)

**Comment by mariantanase** [comment]
Sorry, I cannot reproduce it again, now it seems to be working, after removed manually the code generated from layout.yaml

**Comment by mahagr** [comment]
I will close the issue for now. If you get it again, please make another comment into here and we will reopen it.
