### ISSUE TITLE
Particle Developer Access on <head> Injection

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2303]
I have a feature request to support the assignment of tags other the stylesheets and javascript to the `<head>`. Mabye the implementation of some sort of block would be great. Like it is currently handled with assets, stylesheets and scripts.

ATM we don't have an option to assign icon tags or open graph tags to the `<head>` other than doing it manually over the backend or overriding core files `assets.yaml` / `page_head.html.twig`. Within a Particle or Atom I don't see an option to inject tags there. But it's often useful and creates new option for further extensions.

Here is a link to the actual code where the injection of custom tags should happen: [page_head.html.twig](https://github.com/gantry/gantry5/blob/3f5c6a669b8cbe6972b95b5ab618706140a6b482/engines/common/nucleus/templates/page_head.html.twig#L37-L45).

Here is an core file override which shows what the support of the feature would allow to do within an e.g. Atom. [Favicon Tag Generator](https://github.com/thexmanxyz/Favicon-Tag-Generator-Gantry)

Ad.: Implementing of a Canoncial URL Atom like described here #2291 can't be done without this feature.

**Comment by thexmanxyz** [comment]
@mahagr I think I missed 

```
{% pageblock body_top %}
    -BODY TOP-
{% endpageblock %}
```
will check and report back. Thanks for pointing on.

**Comment by thexmanxyz** [comment]
@mahagr Ok I rechecked now and I missed that body attachment isn't enough for my purpose. Thought there is also the possibility to add something to `<head>` which isn't the case currently.

We would need something like

`{% pageblock head_top %}
    -BODY TOP-
{% endpageblock %}`

`{% pageblock head_bottom%}
    -BODY TOP-
{% endpageblock %}`

which currently does not exist. I would highly appreciate this feature to be added because it gives more freedom for Particle and Atom developers.

**Comment by mahagr** [comment]
```twig
{% do gantry.document.addStyle(url('gantry-assets://css/whoops.css'), 5) %}
{% do gantry.document.addStyle({ href: url('gantry-assets://css/whoops.css') }, type: 'text/css', media: 'screen'), 5) %}

{% do gantry.document.addInlineStyle('a { color: red; }', 0) %}
{% do gantry.document.addInlineStyle({ content: 'a { color: red; }', type: 'text/css' }, 0) %}

{% do gantry.document.addScript(url('https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js'), 10, 'head') %}
{% do gantry.document.addScript({ 
    src: url('https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js'), 
    type: 'text/javascript',
    defer: 'defer',
    async: 'async',
    handle: 'mootools-code.js' {# WordPress only #}
}, 10, 'head') %}

{% do gantry.document.addInlineScript('alert("test");', 0, 'footer') %}
{% do gantry.document.addInlineScript({ content: 'alert("test");', type: 'text/javascript' }, 0, 'footer') %}
```

**Comment by mahagr** [comment]
Yes, you're right, we have only ran into situation where people have wanted to add HTML into the body.

Right now you can add custom head tags only from the Page Settings tab.

For what you wanted to use this feature for?

**Comment by thexmanxyz** [comment]
@mahagr My first message of this issue states two examples were I would need this feature. So it would be greate to support this feature, what is holding back on integrating it?

**Comment by mahagr** [comment]
I just looked into this one and I think we could easily do this with a new `pageblock`.

Just add these to `page_head.html.twig` and your examples should work:

```twig
{{ gantry.document.getHtml('head_top')|join("\n    ")|raw }}
{{ gantry.document.getHtml('head_bottom')|join("\n    ")|raw }}
```

I can add those before the release (today), but I'd like to know if it works for you first.

**Comment by mahagr** [comment]
Actually, I'm going to add 3 positions: head_top, head_meta and head_bottom

**Comment by mahagr** [comment]
Implemented in CI build.

**Comment by newkind** [comment]
This needs to be documented @RyanMPierson ;)

**Comment by thexmanxyz** [comment]
@mahagr First and foremost, thanks for implementing the new functionality. I finally had the time to test it and it works as expected. I finally had the time to update my Atom and it works flawlessly.

**Comment by thexmanxyz** [comment]
@mahagr Here is a port of my old favicon [Extension](https://github.com/thexmanxyz/Favicon-Tag-Generator-Gantry) to an [Atom](https://github.com/thexmanxyz/Favicon-Tag-Generator-Atom-Gantry) based on the new functionality. Just to let you know that I already use it.

**Comment by joomlabeat** [comment]
WP 5.8, latest Gantry 5.4.x: 

`pageblock head_top` & `pageblock head_meta `, do not work in particles - they only work in atoms.
Only `pageblock head_bottom` works

From a quick debugging I tried to do - they seem to be sent the html to the Gantry Document Html -addHtml() method.
But when the getHtml method runs, the html returned is empty.

I have a similar implementation in Joomla 3.9.latest on a particle and those two work with no problem.

**Comment by mahagr** [comment]
@joomlabeat Can you open a new issue about this?
