### ISSUE TITLE
Menu crashes after changes names of menu

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#2304]
I have trouble with menu.
I renamed the first level menu item. After this - the order of the menu items has changed and the menu items of the second level of this menu item has ceased to work. And changes in menu not save
wordpress 4.9.6
v5.4.23 / g5_helium

I tryed to create new menu - same, also reinstall theme - nothing changed.

How possible to fix it?

Thanks

**Comment by mahagr** [comment]
@newkind Can you take a look?

**Comment by pobo3** [comment]
Do I have a chance to solve this problem?

**Comment by pobo3** [comment]
Thanks a lot
