### ISSUE TITLE
variable availability in particle twig

### ISSUE THREAD

**Issue by creative-resort** [gantry/gantry5#2306]
It seems that variables that 
are **set** in a **template's**
`templatename\custom\engine\templates\page.html.twig` file (not inside a block)
are **not available** within a **particle's**
`templatename\particles\mobile-toggle.html.twig` file (inside of the block "particle").

How do I make use of those template specific variables within a particle?

**Comment by mahagr** [comment]
Particles are rendered and cached individually without any context, though they do have access to Gantry configuration, which includes all the settings you have set in the admin.

Try looking what's inside of `gantry.config`.

**Comment by mahagr** [comment]
Sorry about the delay, I missed your reply.

You can add JS/CSS/HTML from the particle into the main document, though it is limited to few locations in the HTML document.

Please see the documentation on this:
http://docs.gantry.org/gantry5/advanced/css-js-twig
