### ISSUE TITLE
I can not place an image with transparency

### ISSUE THREAD

**Issue by Legolasindar** [gantry/gantry5#2308]
Im trying duplicate this effect.
http://postscriptumgame.com/
http://postscriptumgame.com/wp-content/themes/PostScriptum/img/edge1.png

One png image with transparency for separate sections. But in my Grav+Gantry5 web, not work.

I put a Custom HTML particle with TAG **style -> background-image: url("user/themes/g5_hydrogen/images/separadors/edge1.png")**
The image appear, but without transparency.
If i use inspector of the firefox for make g-grid transparent, not work.

Sorry i cant provide link of my web because it is not public.

Thanks

**Comment by mahagr** [comment]
You need to make background color transparent and for that you need to write some of your own custom CSS. Instructions to do that are in:

http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
