### ISSUE TITLE
Print CSS should be universal

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#231]
So I have callisto installed and the Template is darker in the base colors - thats fine but everytime a Template has dark base color the Print-Screen gets screwed up - in callisto you could spent a whole flood on black ink if you want to print anything.

I know print is not that common but its really annoying to edit the CSS every single time. 

Because Print is so outdated i think it would be wise to make an extra Print CSS that is used instead of other CSS in print screen.

This way we get black on white with normal minimal styling.

**Comment by arifinrt** [comment]
Added print css to Callisto. Will be available in the packages on next release

**Comment by Omegatcu** [comment]
Thank you @arifinrt - but the intention was to make a standard PrintCSS for G5 because other plattforms have the problem as well.

**Comment by arifinrt** [comment]
Yes, the same fix had been applied to Hydrogen and Nucleus core itself
