### ISSUE TITLE
Discrepancy in routing between Grav and Gantry

### ISSUE THREAD

**Issue by Blazeflack** [gantry/gantry5#2310]
Please refer to https://github.com/getgrav/grav/issues/2030 where I initially posted about this issue.

**The following is a re-post of my latest reply to the above ticket:**

I apologize, you are completely correct. It turns out it is an issue with Gantry apparently.

Please see my following test site: [http://krakengroup.org/debug/folder-1/one](http://krakengroup.org/debug/folder-1/one)

Setup:
Grav install folder: /debug/
Absolute URLs: no
Custom base URL: no

The links in the main content area is created through the Grav pages.
The links in the footer are created through Gantry.

The text of the links shows their href value (having a / at the beginning or not).

Results:
Links in Grav pages which start with a slash (/) will correctly use the Grav install folder as base URL.
Links in Gantry elements which start with a slash (/) will not use the Grav install folder as base URL, but rather the root domain (krakengroup.org in this case).

In order for links to work in Gantry you need to omit the beginning slash of a relative URL. I'm not sure if this is intended behaviour or a bug. But it seems weird that it doesn't behave the same way as Grav.

In any case I should probably post this in the Gantry repository just to make sure.

**Comment by mahagr** [comment]
See my comment in grav issue.

**Comment by mahagr** [comment]
See the discussion in the another issue, closing.
