### ISSUE TITLE
Random Image Module Issues

### ISSUE THREAD

**Issue by Viper66Oz** [gantry/gantry5#2314]
G'day to whom it may concern. I have recently been having an issue with the Random Image Module in the latest Joomla and Gantry. 

Ok so I have a module position defined in a Gantry Hydrogen Outline I have created. The module position is for where I want to add the Joomla module Random Image.

So I have then gone and created the Extension>Module>New>Random Image module. I have already uploaded my images (3) into Joomla via the Content>Media new folder called random. 

So when creating the Random image module it asks for image file type (png), the location (images/random) and some sizing details. I hide the title, and allocate the position to where I have previously created. 

The position name is visible in my theme so I select. I assign the menu item to the home page as this is the outline I want the random image module applied to. Click save and close. I preview the page and I get the following.
![image](https://user-images.githubusercontent.com/26629942/41305866-39bb51ce-6e42-11e8-8a5f-cd4a2dad7ebe.png)

So I go back to the Random Image Module and remove the allocated position. Save and Close and my homepage returns, displaying as it should be but minus the random image module. 

I can however just apply a single image particle to the outline and this works fine. ????

I have been fault finding and getting assistance via Gitter gantry/gantry5 discussion. After some discussion and similar errors I was advised to raise this issue. This random image module has previously been working fine until about 23rd May, not sure if that helps.

**Comment by N8Solutions** [comment]
@Viper66Oz It's possible, as we discussed in the chat, that this is a specific problem with either Joomla or this specific Joomla module. I also just read in your comments where you stated that the random image module was working up to about May 23rd. We also know that it has a problem with the standard Joomla templates. 

I would suggest that you try installing an older version of Joomla where you know it worked to see if you can find a version where it is working and install newer versions one by one until it breaks.

**Comment by mahagr** [comment]
Has this issue been resolved? I've not seen any further replies from @Viper66Oz
