### ISSUE TITLE
Shortcode toggle menu

### ISSUE THREAD

**Issue by xbass540** [gantry/gantry5#2316]
hi! is there a way i use some shortcode to place the mobile menu toggle (3 horizontal lines) inside a <div class="g-grid"> <div class="g-block size-100"> </div></div>block?
I would like to position the toggle menu horizontally aligned with my logo and cart icon.
Now i can only have the toggle menu icon on top left corner alone.
(sorry to post here but i can't find some proper space to post questions)

**Comment by mahagr** [comment]
Which platform are you in? Right now the offcanvas icon (drawer) is hardcoded in HTML output and you need to use some custom CSS to locate it properly.

**Comment by mahagr** [comment]
Closed due to inactivity.
