### ISSUE TITLE
Gantry 5 'Menu Item Id' in Grav not populating <a /> tags

### ISSUE THREAD

**Issue by paolavness** [gantry/gantry5#2317]
Hi there,
Grav 5.4.23 with Gantry 5.

In Grav, I have a page called "ABC" with the `Folder Name` set to `abcfolder`. In the Gantry menu settings for "ABC", the `Menu item Id` is set to `abcfolder`.  On the website, the html for "ABC" menu is to the effect of `<a href='https://example.com/abc'>ABC</a>` - IE, the Gantry `Menu item Id` is not being set - neither here nor in the `<li />`

Is this a bug in integration with Grav or a Gantry bug or something that has been overlooked? 

I need to be able to set the `id` values of `<a />` tags to initiate custom actions, such as opening of [Intercom](https://www.intercom.com) chat box.

I look forward to hearing from you.

**Comment by mahagr** [comment]
I believe it is just something we have missed.

**Comment by mahagr** [comment]
@paolavness Unfortunately `Menu Item Id` is really the folder name of the menu item, not CSS Id.

There is currently no possibility to add id tag, try matching the class instead (if you're doing the logic yourself). Another possibility is to create a custom particle which you can put into the menu.

**Comment by paolavness** [comment]
Thanks @mahagr. Perhaps this can be added as a feature request in the future. I'm sure there is a reason why `Menu Item Id` was named that and not `Menu Name` but if not, perhaps something to consider in future versions to align with `HTML` norms. 
Thanks again.

**Comment by mahagr** [comment]
The naming comes from Joomla and was kept the same over the platforms. It is the identification which Gantry uses internally to figure out to which page the menu item belongs to.

**Comment by mahagr** [comment]
Also, try using a custom html particle as the menu item, it should allow you to do what you want right now. Or you can make overrides to add the id attribute yourself and make a pull request. :)
