### ISSUE TITLE
Menu Editor - rawRoute Error - No duplicate pages - Grav

### ISSUE THREAD

**Issue by Tirjasdyn** [gantry/gantry5#2318]
Hello, when I try to edit the menu, I get Call to a member function rawRoute() on null error. I've read the other issues, but I don't have duplicate pages, and all my pages are routable & visable. 

This only happens when I use Helium. If I use Hydrogen this doesn't seem to be a problem, as Hydrogen picks up when I edit the page order. 

Thank you!

**Comment by Tirjasdyn** [comment]
It's happening on hydrogen too.

**Comment by mahagr** [comment]
@Tirjasdyn I believe this one has already been fixed in latest CI build here:

http://gantry.org/downloads#ci-builds

Can you test it out?

**Comment by Tirjasdyn** [comment]
Sorry I've been away. Let me try the latest build.

**Comment by Tirjasdyn** [comment]
Yeah! I updated the theme and the gantry framework. It let me save my menu. Thank you!
