### ISSUE TITLE
"The menu selected is empty" in Gantry 5 admin > MENU

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2320]
If there is no "default" menu item in any Joomla menu (yellow starred in joomla menu manager which then shows the little "house" icon next to the menu in the menu manager dropdown), then if you go into Gantry 5 admin > menu you will get "The menu selected is empty!" and it's impossible to show the contents of any menu in the Gantry 5 menu editor.

1. Gantry 5 should handle this with a better error message such as "There is no default menu item - please mark one of your menu items as the default for Joomla".
2. Even then, it should still be possible to chose any menu from the dropdown and be able to edit it as normal.

Normally in Joomla is should be impossible to have no "default menu item" but Gantry 5 menu editor does make this possible if you change/remove the "default all" or you delete the whole menu. So that's why this ciurcumstance is rare - but it is possible to reproduce it easily.

**Comment by mahagr** [comment]
Yes, this is a known issue and something that is more of a bug in Joomla itself -- in some cases it allows you to remove default menu item, though in most cases it prevents it by displaying an error.

I can take a look if I can detect this special case and deal with it somehow.

**Comment by mahagr** [comment]
@marktaylor46 Should be fixed now.

**Comment by marktaylor46** [comment]
confirmed fix :) yaaay!
