### ISSUE TITLE
Grantry 5 v. 5.4.24 - Owl Carousel and Content Tabs is unable to load properly in Grav

### ISSUE THREAD

**Issue by KewMannDev** [gantry/gantry5#2322]
After updating my plugin today, I noticed that my Owl Carousel is not loading and content tabs are deformed. I am getting an error from my Console states that owlCarousel not found. May I know what happen?

**Comment by mahagr** [comment]
Try to force-reload the page by hitting Ctrl-F5. JS has been updated, your browser may have cached version of the file.

**Comment by KewMannDev** [comment]
Nope. It still the same. I have tried empty cache and incognito mode but they are returning me the same error. 

On the console side i have capture this error, perhaps may help the situation.


> Uncaught TypeError: jQuery(...).owlCarousel is not a function
>     at (index):787
>     at dispatch (jquery-2.x.min.js:3)
>     at r.handle (jquery-2.x.min.js:3)

**Comment by mahagr** [comment]
Which theme do you use?

**Comment by KewMannDev** [comment]
I am using Helium v.5.4.24. The content tabs probably is being affected by the owl carousel as the content tabs is under the carousel. Basically i am creating a new default theme but the Owl Carousel is not loading.

**Comment by KewMannDev** [comment]
@mahagr any heads up on what is happening on this issue?

**Comment by newkind** [comment]
Do you have an url to your site? Can you check if there is owlcarousel js file in the page source? Can you check `owlcarousel.html.twig` and look for the `owl-item` class?

**Comment by KewMannDev** [comment]
Hold on.. I just get to resolve this issue after clicking on the clear cache button in Grav Admin. It seems the cache in Grav is affecting it. Probably this may help anyone who met this problem.

**Comment by newkind** [comment]
Great, glad to hear that it was only cache.
