### ISSUE TITLE
Joomla! Home page.

### ISSUE THREAD

**Issue by a113f** [gantry/gantry5#2325]
Hello, I would like to show a slide only on the home page, but when I enter the home - particles, it shows on all pages. How do I show only on the home page?

**Comment by simmonsr** [comment]
Is your Home - Particles outline the Default outline (one with star)? If so, you need to create an additional outline that is used for Default (all pages). And the Home outline should be assigned only to your Home menu via your Gantry Template  > Assignments.

![screen shot 2018-07-10 at 10 35 46 am](https://user-images.githubusercontent.com/5002814/42520931-2beecd54-842d-11e8-965f-b7df255126c3.jpg)

**Comment by simmonsr** [comment]
I'd have to take a direct look.

Is the article using a Menu? Create a Single Article menu for it (can be a hidden menu) and it should be separate from the Homepage.

https://www.joomlashack.com/blog/tutorials/hide-menu-items/

**Comment by mahagr** [comment]
I am assuming that the issue has been solved by above link.

**Comment by a113f** [comment]
Yes. Thanks.
