### ISSUE TITLE
Cannot display content; not in Gantry 5 template!

### ISSUE THREAD

**Issue by juanrojasm** [gantry/gantry5#2326]
Hi, When I try to change the template of my site joomla I get the message on the website that says
Warning
Gantry 5 Component: Cannot display content; not in Gantry 5 template!

**Comment by mahagr** [comment]
Just go to module manager and disable (or assign to menu items) all instances of Gantry 5 Particle module. It only works if you're using Gantry based template.

**Comment by juanrojasm** [comment]
See the website, goodmoo.es what appears

**Comment by JoomFX** [comment]
@juanrojasm Your Home menu item ("Good Moo") is of type "Gantry 5 Themes" -> "Custom Page" which is available in the Gantry 5 theme only.

Just change the type of your Home menu item to something else. for example "Featured Articles" or whatever... just something that is available in Joomla by default.
