### ISSUE TITLE
Grav Child Menu Items not appearing in 5.4.24

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2327]
Create a Grav Skeleton here:

http://gantry.org/downloads#grav

Create a new page as a Child menu (so use Home as parent).

Clear your cache. And see that the Child menu will not appear.

**Comment by simmonsr** [comment]
I would note that this issue is specific to a Menu item which does not currently have a child item(s).

**Comment by simmonsr** [comment]
Guess enabling `Folder Numeric Prefix` in Child Item that has no siblings is the fix. I will have to note that in the docs.

**Comment by simmonsr** [comment]
Per rhukster:

https://github.com/getgrav/grav/issues/2102#issuecomment-405897171

Folder Numeric Prefix set as **disabled** shouldn't mean **hidden**. So looks like this is a G5 issue that needs to be addressed if possible.

**Comment by mahagr** [comment]
@simmonsr Your fix displayed also hidden menu items, can you try again with the new fix?

**Comment by simmonsr** [comment]
Yes, perfect thank you @mahagr !!
