### ISSUE TITLE
Header containing carousel placed under navigation and not over it

### ISSUE THREAD

**Issue by fabio42170** [gantry/gantry5#2328]
Hi everyone !
I'm a total newbie concerning Gantry. I read the documentation but couldn't find any answer to my question. Same on Google. Here's my point : I customized the Base outline for my website, and the particles outline as well. I wanted to have a menu in the navigation position at the top and a carousel owl slideshow over it. This works perfectly in the Particles outline and strangely, in the basic outline, the slideshow is placed under the navigation and not over it. How come ? What am I missing ? Is there any option that I might have skipped using for that ? I've been trying to find in vain.
Thanks for your kind help !
Fabio

**Comment by thexmanxyz** [comment]
@fabio42170 @mahagr can be closed already answered on gitter.im

**Comment by fabio42170** [comment]
Thanks a lot for the answer ! I managed to overcome the problem by resorting to the layouts and presets and the function "load". Very useful indeed. Saved me a lot of time.

**Comment by thexmanxyz** [comment]
@fabio42170 

Glad to hear that you found an appropriate solution :)
