### ISSUE TITLE
After last update loose language file if site language is russian

### ISSUE THREAD

**Issue by HolodWP** [gantry/gantry5#2329]
On backend of guntry 5 (WP) I have varibles instead names s if site language is russian. Also image picker does not work, unable to click to any picture or link. 
![image1](https://user-images.githubusercontent.com/41109862/42624273-b0278c40-85cd-11e8-91db-a70131b96b5e.png)
![image](https://user-images.githubusercontent.com/41109862/42624274-b07cf540-85cd-11e8-9ddc-90fcbed7aec0.png)

**Comment by HolodWP** [comment]
Previous version wos working fine, for now i cannot roll it back.

Yes error is:
JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542
[Показать/скрыть детали сообщения.] Error: Invalid `clickable` option provided. Please provide a CSS selector, a plain HTML element or a list of those. main.js:1:363816
require<[107]</u.getElements
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:363816
e
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:329459
loaded
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:151570
require<[192]</e.exports/<
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:409150
open/<
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:213850
require<[192]</e.exports/<
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:409150
_send/l.onreadystatechange
https://sbs812.ru/wp-content/plugins/gantry5/admin/js/main.js:1:311758

**Comment by mahagr** [comment]
On translations: Did you have Russian translations manually installed in your plugin folder? I ask this because of WP deletes the plugin before re-installing it on an update.

**Comment by HolodWP** [comment]
No, it is russian version of WP, I even not switch the language.

**Comment by newkind** [comment]
I just tried my dev instance and I can't replicate any of your issues. Russian language works just fine, the same with image picker - no JS errors.

![helium theme gantry5 dev wordpress 2018-07-12 11-55-13](https://user-images.githubusercontent.com/1641534/42626440-9f48485e-85ca-11e8-99f1-edf1843ec55b.jpg)

If I were you, I'd reupload my whole gantry5 directory via FTP/SFTP and cleared all caches - Gantry5 cache, any other caches coming from other plugins. Also you can try disabling all plugins but Gantry5 to see if any of them could cause the issue.

**Comment by HolodWP** [comment]
Yes the problem is not on new installed WP, it is only on updated. I have several sites and problem shows after update on every site. Some people in russia have the same problem. I roll back all my sites, and leave 2 less impotant for testing. Disablin all plugin, reinstalling Gantry 5 and Timber, switch theme was not helping. Will try to reupload whole gantry directory...

**Comment by HolodWP** [comment]
newkind, I have a testing WP site having the same problem. I can give you login and pass for testing this issue. Woud it be helpful? Of course in privat message.

**Comment by newkind** [comment]
Not without FTP, WP admin login won't do as I'd have to try to reupload the G5 directory by myself, check the translation files and their paths etc. So either you'd provide us with FTP/SFTP or pack the whole WP directory into a zip and send us with the database.

**Comment by HolodWP** [comment]
Ok, where I can send thes ZIP file?

**Comment by newkind** [comment]
You can send them to jakub at rockettheme.com or place them somewhere safe on your FTP and just send me the links to the files.

**Comment by HolodWP** [comment]
ok, send it to you e-male.

**Comment by newkind** [comment]
Got the files. I'll check them out in a bit and let you know.

**Comment by HolodWP** [comment]
Thenks a lot!

**Comment by HolodWP** [comment]
Thenk you! Problem is solved. After deleting files JS also disappear. For me english is convenient, guntry on english is OK.

**Comment by thexmanxyz** [comment]
@newkind @HolodWP @mahagr Should this issue be closed? better keep it open until fixed?!

**Comment by HolodWP** [comment]
Reopen issue?

**Comment by thexmanxyz** [comment]
@HolodWP Simply reopen it, it would be closed if not needed anymore. Better to keep it open...because otherwise it might get lost. I don't know maybe @newkind already took notes IDK.

**Comment by HolodWP** [comment]
Ok

**Comment by mahagr** [comment]
CI builds added first step towards fixing this issue -- strings should no longer be broken in Russia or any other translated language.

**Comment by mahagr** [comment]
Split the missing translations issue into #2359
