### ISSUE TITLE
link a menu horizontal to particle Helium/Gantry 5 (Grav)

### ISSUE THREAD

**Issue by Ikkache27** [gantry/gantry5#2333]
Hi guys : 

How to link a menu horizontal to a particle in the home page, when i click in the menu horizontal it scrolls to a particle in the same page (like OnePage Menu Particle but i want it for the horizontal menu).

Thanks in advance

**Comment by Ikkache27** [comment]
@w00fz   @rhukster 
can anyone help me here please
thank you

**Comment by blizam** [comment]
This really isn't an issue with Gantry or a feature request or anything that probably belongs here. I'm not sure if Helium has a support forum or perhaps Gitter is better than raising an issue post: https://github.com/gantry/gantry5#where-to-get-help

The Helium horizontal menu particle just builds normal links... so give your Particle an ID and link to it...

http://mydomain.com/page#particleID

http://docs.gantry.org/gantry5/configure/layout-manager#settings-2
http://www.webweaver.nu/html-tips/link-within-a-page.shtml

**Comment by Ikkache27** [comment]
Thank you @blizam

**Comment by Ikkache27** [comment]
@blizam @w00fz @rhukster 

How about if i want to create my own menu, not the main menu from the created pages ... there is no menu manager ?

Thank you in advance

**Comment by Ikkache27** [comment]
@blizam @w00fz @rhukster 
Can anyone help me here please
Thank you

**Comment by blizam** [comment]
I don't understand... In the horizontal menu particle you just specify whatever link you want... it doesn't have to be a relative link to the same page you're on... you can specify any fully qualified URL that you want.

Check out the Docmentation and Download links that the RocketLauncher installs... those are custom links where a URL is specified that is not a Grav Page... those examples should show you how to make your own custom links in the Menu

**Comment by Ikkache27** [comment]
Thanks for your reply @blizam 

Sorry i mean the Menu particle, i can't edit the link of the menu item that was generated when i creat a page,
(for example : when i want to creat Contact menu item, i must a creat a page and this menu item takes the link of the page "mysite/contact", but i want to edit this link and asign it to the particle in the home page like this "mysite/#contact") 

and also i can't add another menu editable from the menu editor, it takes only the menu generated from the creation of the pages.

**Comment by blizam** [comment]
If you want the route to your home "mysite" page to always be "mysite#contact" then you can change the route on the Grav page in the Admin or via the route attribute:

https://learn.getgrav.org/content/headers#routes

When you use menu items from the Grav Menu system the route has to come from CMS/Grav, you can't edit in the G5 Menu Editor. 

If you look at the "Documentation" and "Download" links that I mentioned previously in Helium you'll see that they are doing the same basic thing as I just described except their using the ```external_url``` parameter.

The alternative is using a Custom HTML Particle in your Menu Editor to hand code your own menu item.

Drag a Particle into your Menu, select Custom, and stick this in it:

```
<a class="g-menu-item-container" href="#">
  <span class="g-menu-item-content">
    <span class="g-menu-item-title">Test</span>
  </span>
</a>
```

It probably won't be/look perfect but it'll be close...

**Comment by Ikkache27** [comment]
Thank you very much @blizam , i have used the second way and k you very much @blizam , i have used the second way and do some changing, it works perfectly
