### ISSUE TITLE
Kunena - "The page isn't redirecting properly Firefox has detected that the server is redirecting the request for this address in a way that will never complete. This problem can sometimes be caused by disabling or refusing to accept cookies."

### ISSUE THREAD

**Issue by fabio42170** [gantry/gantry5#2338]
Hello !
I've been goign crazy finding a solution to a problem that was already discussed on the net. Found plenty of topics related to this issue, but no solution for me alas. I installed Joomla 3.8, updated, then installed a clean brand new Kunena 5.1.2 with the sample data, then created a link to the forum in my Main Menu for users to access the forum on the front end. Unfortunately, whatever I do, whenever I click on a category, I get this very frustrating error message : "The page isn't redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
This problem can sometimes be caused by disabling or refusing to accept cookies."

From what I read, this could be due to:
- " It's when you have two different menu items for Kunena, both having the same [alias] name, that causes redirect loop problems." (found in a forum) . Personally, I checked that point and even renamed the two aliases so that there would be no problem. In vain.
- improper SEO settings in joomla. I read the post here https://www.kunena.org/docs/en/setup/configurations and everything is ok on my website

I'm at a loss. This is the website link : https://www.4u2learn.fr/joomla/4u2learn/index and if you click on "chatting" in the mainmenu, you will be able to test and tell me what's wrong. Hopefully.
Thanks for your help !!!!!
Fabio

**Comment by fabio42170** [comment]
Well, next episode.
Forced to note that I was in a dead end, I decided to uninstall this version of kunena. And I installed an older version which worked perfectly on my former Joomla 2.5 website : the Kunena 3.0.0 version. Well, you know what ? everything works plain-sailing. No need to know that there must be a kind of bug somewhere in this new version. Which bug ? I'm not smart and skilled enough to find out and pass this on to experienced developers and/or users.
If anyone has any clue, let me know !
Thanks in advance !

**Comment by fabio42170** [comment]
One thing i know for sure is that the categories which produce this error page have no topics inside. And there's also the "main forum" link which does not work. To be noted : apart from some small display bugs, Kunena Version 5.0.14 works like a charm.

**Comment by mahagr** [comment]
These issues are for Gantry, not Kunena. Please use their issues tracker.

**Comment by fabio42170** [comment]
Thanks but how did you come to that conclusion ???

**Comment by fabio42170** [comment]
Yep indeed. Thanks a lot !
