### ISSUE TITLE
Moving menu item in Joomla doesn't have any effect in Gantry

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#234]
I think was another issue for this but...

![1](https://cloud.githubusercontent.com/assets/9744973/7590291/6d3c3396-f8d0-11e4-8e51-206652482395.PNG)

![2](https://cloud.githubusercontent.com/assets/9744973/7590292/6f6a6e3a-f8d0-11e4-9575-a5528ab160db.PNG)

**Comment by DanGthatRokGallery** [comment]
Users here are having the same issue -> http://www.rockettheme.com/forum/gantry-framework/243528-menu-items-order-being-overridden-by-gantry-menu
