### ISSUE TITLE
Joomla Menu Ordering

### ISSUE THREAD

**Issue by Dave-Skye** [gantry/gantry5#2341]
Currently if my client changes the order of a Joomla main menu item it does not change on the frontend.
To make the frontend menu order change I need to edit the ordering within Gantry 5.

I don't want to give the client access to gantry 5 otherwise there is a good chance the client will start screwing up the design of the website.

How can we make the menu ordering in Joomla work when using Gantry 5??

**Comment by N8Solutions** [comment]
Hello @Dave-Skye This is a known issue. Please comment here on #552 and close this one.

regards

**Comment by mahagr** [comment]
Closing as duplicate.
