### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by PhilipHolmes** [gantry/gantry5#2343]
For mobile - Option to display sub-menu items directly under the menu,  as opposed to having an arrow to click to display sub-menu items
Thanks

**Comment by mahagr** [comment]
You can always create a custom particle which does whatever you want with the menu data.

**Comment by PhilipHolmes** [comment]
Thanks mahagr, I guess it's more of a particle request than Gantry 5. The accordion style menu on mobile is a standard feature of many templates now, and offering customers more choice and options with particles seems a sure fire way to get more customers to me.
