### ISSUE TITLE
WordPress - Yoast Premium 8 Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#2347]
When you install Yoast 8.0 there is a bug with Gantry 5 Framework.

Method Timber\FunctionWrapper::__toString() must not throw an exception, caught TypeError: Argument 1 passed to WPSEO_Admin_Bar_Menu::get_post_score() must be an instance of WP_Post, instance of Timber\Post given, called in /home/XXXX/public_html/wp-content/plugins/wordpress-seo-premium/inc/class-wpseo-admin-bar-menu.php on line 144

![2018-08-20 23 23 41](https://user-images.githubusercontent.com/10489911/44367489-3c806380-a4d0-11e8-9408-d671087fc3c4.jpg)

If you logged off from the site the Site Works, the issue is in Admin Bar at the top when you are logged user.

https://wordpress.org/support/topic/complete-website-broken-after-update-to-8-0/
https://rockettheme.com/forum/gantry-for-wordpress/277646-conflict-between-gantry-5-and-yoast-seo-8-0
https://rockettheme.com/forum/wordpress-theme-acronym/277672-acronym-conflict-with-yoast-premium

**Comment by newkind** [comment]
Not a Gantry bug. It's a YOAST bug and it's gonna be fixed in 8.1

https://github.com/Yoast/wordpress-seo/issues/10646

```
Thanks for reporting this issue! We've immediately created a PR to fix this.

It's scheduled to be included in 8.1.
```
