### ISSUE TITLE
Static Routine Calls - Joomla Particle

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2349]
I initially thought that this is a Joomla issue but I was wrong. The issue is probably caused by Gantry. See also the [Original Joomla Issue](https://github.com/joomla/joomla-cms/issues/21799). But after cross checking with plain PHP code within a Joomla Module it is most likely an issue with the static method calls. 

Additionally it has to be said that as soon as I call the `ContentHelperRoute::getArticleRoute()` method additionally via PHP it will also work via TWIG. If I remove the PHP code it also stops again working only for the `/` page.

### Steps to reproduce the issue

1.) For me it only occured on the root page e.g. HOME - On all sub paths everything is working fine
2.) `ContentHelperRoute::getArticleRoute(articleId, catId)` calls do not return the valid route. It is simply nothing returned for either all or some of the articles.

Here are some examples to demonstrate the issue within TWIG:

**Does not work on HOME '/' but on all other pages** 
`joomla.route(joomla.call('ContentHelperRoute::getArticleRoute', articleId, catId))`

`getArticleRoute` does not return anything (only on root path  `/`)

**Does always work because no ContentHelperRoute involved**
`joomla.route("index.php?option=com_content&view=article&id=" ~ articleId ~ "&catid=" ~ catId)`

### Expected result

On all pages the correct route should be returned if a valid `articleId` and `catId` pair is passed to `ContentHelperRoute::getArticleRoute(articleId, catId)`

### System information (as much as possible)
Joomla 3.8.11
Gantry 5.4.24

**Comment by mahagr** [comment]
@thexmanxyz It works just fine for me in both home page and other pages. It returns the same menu item everywhere. You should check the menu item in your home page if it allows articles to be routed through it.

**Comment by thexmanxyz** [comment]
@mahagr Thanks for looking into. Mhm @yellowwebmonkey and me discovered this issue within a particle I have written. Independently of each other. 

> You should check the menu item in your home page if it allows articles to be routed through it.

I'm don't really know where I do that, so that I can try reproducing the issue. What setting is this? Or is this on webserver level (htaccess).

**Comment by thexmanxyz** [comment]
@mahagr At least on my test site I have no articles on my home page (default menu item). Except the ones I fetch within the particle via the finder. It's not a plain Helium but it's based on Helium. However I can try to reproduce it in a plain install.

**Comment by thexmanxyz** [comment]
@mahagr I'm not able to reproduce it on Hydrogen but I will try on Helium as well again. Will keep you updated. Maybe it was already fixed with any other update of Joomla or Gantry.

**Comment by thexmanxyz** [comment]
@mahagr Can't even reproduce on Helium. IDK what triggered the original problem but it was there but obviously fixed or not triggered anymore.
