### ISSUE TITLE
Font-Picker doesn't work (Grav)

### ISSUE THREAD

**Issue by mgollmer** [gantry/gantry5#2354]
Hello there, 

I have an issue while using the font-picker (local dev machine). I tried to choose a new google-font for the title and everything seems to work. There are no errors while compiling the scss and the affected value seems also right: 

![image](https://user-images.githubusercontent.com/26478647/44955038-fe5e4900-aeac-11e8-8576-09a7dbff7345.png)

But the font is not displayed! So i checked if the font is loaded properly.  And there seems to be the error - there is no new request for loading the lato font. 

I'm using a rockettheme theme xenon. Can somebody tell me what could be wrong or where to look ?

Regards, 
Michael

**Comment by newkind** [comment]
Make sure that the font variable is passed through the `get-font-family` function in SCSS ie. `font-family: get-font-family($font-family-default);`

**Comment by mgollmer** [comment]
DUUUUUUUUUUUDDDDDDEEEEEEE! ...F***! Sorry, what a dump request. Thanks for helping me out. This wasn't even a valid css-value for font-family...
