### ISSUE TITLE
Question about Caching.

### ISSUE THREAD

**Issue by jobst** [gantry/gantry5#2356]
I have just upgraded a number of my sites to newer templates and thus to the latest version of gantry5 to get responsive layouts for all of those sides - all of those sites are fairly busy sides.

I noticed (Apache server) there is a directory "SITEDIRECTORY/htdocs/cache" with a number of sub directories gantry5, GantryLess and Gantry with sub-directories for the template, html, twig and compiled files - there are a LOT of php files dating back at least a week or longer.

Are these files cleared AUTOMATICALLY or do I need to setup a cron job to clear those files on a regular base?

I tried to find some documentation about this and couldn't find any (this off course depends on the search terms used).

Can anybody shed some light on the clearing mechanism for the GANTRY5 CACHING mechanism, please!

**Comment by mahagr** [comment]
Gantry 5 caches yaml and twig files into PHP code and most of them do not really change unless you make changes in your configuration or templates. It will also keep the filenames for the cache entries the same, so in principle, the number of files shouldn't grow too much. This said it might be a good idea to clean up the folder now and then to make sure that old files aren't kept forever.
