### ISSUE TITLE
Version 5.4.25 breaks site

### ISSUE THREAD

**Issue by coolman01** [gantry/gantry5#2360]
I just installed this and had a few sites with the following message:

> Gantry\Component\Twig\TwigNodePageblock' not found 

I'll leave [this site](https://w4umulti.imaufbau.ch/de/) up for you to see, if it helps.

**Comment by mahagr** [comment]
Install CI build. New release will be out in few hours.

**Comment by coolman01** [comment]
@mahagr 
Good news. Thanks a lot.
