### ISSUE TITLE
Safari (11.x +) Web Inspector Issue

### ISSUE THREAD

**Issue by pnutster** [gantry/gantry5#2362]
Hi all,

A long term user of the Gantry Framework (mainly Joomla).

Recently I have started to experience the Safari Web Inspector crashing/hanging. At first I was thinking that it was solely due to Safari 11.x version updates by Apple. However, other developers I spoke with had a hard time replicating the issue.

Until I gave them a Gantry (5) website to test this issue on. As a matter of fact it occurs on the Gantry Demo site too - http://demo.gantry.org .

It seems to be a combination of Safari 11.x and Gantry (The issue does not occur on Safari 10.x) - however, no errors are visible on the test sites.

I have created a video to showcase the issue and gove some more information: http://screenshots.blueoceanyyc.com/7aabef210e6f

My hope is that someone involved with Gantry development can pinpoint the exact issue and find or propose a solution to this issue. Wether that is a fix in Gantry or a fix in Safari 11.x that Apple needs to be informed about...

I have even been thinking that Safari uses DNS prefetchin.. could that be an issue...? But to no avail, I was able to turn off prefetching and same results. Web Inspector hanging...

**Comment by simmonsr** [comment]
Unfortunately, I can't replicate this issue. The inspector for Safari seems to be working fine http://demo.gantry.org.

Perhaps when macOS Mojave comes out at the end of the month it will be fixed.

**Comment by newkind** [comment]
You can try latest Safari Technology Preview to check if it is a Safari issue and if they fixed it already.

https://developer.apple.com/safari/download/

**Comment by pnutster** [comment]
Replication can sometimes be odd. Will do it in 2 or 3 clicks (usually it happens to me in a submenu item and then going back to home).

As for Safari Technology preview. Have already been using every latest preview version for the past 3 months.. No go :(

**Comment by simmonsr** [comment]
Have you tried selectively disabling any Safari extensions to see if they may be causing the issue?

**Comment by pnutster** [comment]
Yes  first thing months ago I did was run safe mode
Then actually installed brand new High Sierra with Safari 11.x on different hardware - 100% virgin install - issue persists on this virgin install - not a conflict of software - extensions.

Then installed Sierra with Safari 10.x - again, virgin installation - issue not there

Currently the status is that this issue was introduced with Safari 11.x - and occurs in combination with sites running Gantry framework - have filed Apple Bug report as well - not much activity from their end on that.

**Comment by simmonsr** [comment]
Safari 12 was just released today. Can you see if your issue is fixed with the update?

**Comment by pnutster** [comment]
Also in Safari 12 - issue of hanging inspector remains - [http://screenshots.blueoceanyyc.com/7dde76f85dd4](url)

Again, replicating can be done by keeping inspector open and visiting, back and forth -  on http://demo.gantry.org - between home and pages > blog page

Oftentimes it will take a few attempts... but currently the developer of Espresso - https://espressoapp.com - was able to replicate too:

> Hi Piet,

Well there we go! I saw the CPU spike and also got the same unresponsive dev tools you have been describing (tested in Safari 12.0). Thanks for sending along the link.

I haven’t peeked under the hood yet to see what is going on, but it definitely seems like this is related to something happening on the site, as I haven’t noticed this behavior on any of the websites I’m working on or inspecting. I will let you know when/if I can find out more.

Sincerely,
Pete

**Comment by simmonsr** [comment]
Here is Safari on my Mac with the inspector:

http://rockettheme.hopto.org:8888/images/mp4.mp4

**Comment by newkind** [comment]
I'm sorry but I can't replicate it and there's really nothing in code that could cause this. I think that it might be something with browser caching or something with your system rather than with site.

This is my Safari 12 and Gantry demo site : https://monosnap.com/file/vPSTnz4Hv6PyrFdHFKK1MJieIFZR1I

**Comment by pnutster** [comment]
To my knowledge I  have been able to eliminate extensions and my system by doing the following:

- Safe Boot on current High Sierra MacBook Pro > able to replicate issue
- Have installed fresh High Sierra (Safari 11.x) on separate MacMini hardware > able to replicate issue
- Have installed fresh Sierra (Safari 10.x) on separate MacMini hardware > not able to replicate issue
- Upgraded Safari 10.x to Safari 11.x on fresh Sierra > able to replicate issue
- Upgraded Safari 11.x to Safari 12.x on current High Sierra on MacBook Pro > able to replicate issue
- Safari Technology Preview on current High Sierra on MacBook Pro > able to replicate issue
- Developer of Espresso app is able to replicate issue on demo.gantry.org

Clearly issue was introduced with Safari 11.x

@newkind - your video is clear, no replication of issue... while going back and forth in menu system. 

I have had occasions it would work for me flawless like in your video. Then closing Safari and opening again and would hang in like 3 attempts... So frustrating it is so hard to replicate. Again, I did have the Espresso app dev email me that he was able to replicate... so not going completely wonkers here ;)

I'll keep plugging at it... at this point I am working on downgrading my full system to macOS Sierra 10.12 with Safari 10.x - this since my workflow so heavily relies on Safari Web Inspector and alternatives like Chrome or Firefox for multiple reasons are not possible for me.

Thanks all for trying!

**Comment by simmonsr** [comment]
macOS Mojave will be released early next week, perhaps the upgrade will help.

I also am on macOS Sierra 10.12. But am using Safari 12.

**Comment by pnutster** [comment]
Not a fan of being an early adopter of a new OS version as my machine is a production machine for 50-60 hours workweeks.

As well as the fact that Mojave will be using Safari 12.x and my tests have shown that the OS version is not the main factor in replicating the issue, rather the version of Safari is.

Safari 10.x > all good
Safari >=  11.x > Web Inspector issue

**Comment by simmonsr** [comment]
I understand. Just thought I'd throw it out there.

"Then actually installed brand new High Sierra with Safari 11.x on different hardware - 100% virgin install - issue persists on this virgin install - not a conflict of software - extensions."

So you have been able to replicate on two different computers also? One was completely new install?

**Comment by pnutster** [comment]
Correct - was able to replicate on complete new install on different mac

**Comment by pnutster** [comment]
Yup crash reports are there, but that's abracadabra to me. Would they be of any help to you?

**Comment by simmonsr** [comment]
Most likely not. But I thought I would also throw that out there to see if there were any hints regarding the issue.

So no other website other than Gantry related websites crash Safari when using the inspector? Not one?

**Comment by pnutster** [comment]
For the longest time it didn't dawn upon me... and thought, ah well, just a crash... happens to the best of sites... but they were actually always the websites built by our company... And all use Gantry 5.

Then I was like... OK - I must have messed up some jQuery continuous loop in our base files or something... and started to investigate more... finding out actually on the demo.gantry.org it crashed too.

Now our company builds 99.9 with Gantry and Joomla... the demo.gantry.org looks to be the WordPress version (or if I am complete missing it.. the Grav version). So that is interesting too...

But long story short, I crash on sites with Gantry 5... not 4 and not others :(

**Comment by simmonsr** [comment]
demo.gantry.org is using Grav. Well again, very strange. I'll try to keep an eye out for any issues / comments from other users regarding this. Hope at some point a solution can be found (sooner than later).

**Comment by pnutster** [comment]
Still trying to troubleshoot... both @simmonsr and @newkind are not able to replicate... I was wondering, what type is your HD formatted in? Is your HD formatted HFS+ or the new APFS? Would you be able to check Disk Utility and check? http://screenshots.blueoceanyyc.com/f6dc057e4534

**Comment by simmonsr** [comment]
my wife's Mac Book Pro is APFS. But the issue with Safari is not there on her laptop either.

**Comment by newkind** [comment]
I'm on HFS+

**Comment by pnutster** [comment]
Thanks @simmonsr and @newkind ! No go... was almost thinking it could be related, but relation is now debunked.

**Comment by pnutster** [comment]
FYI - even an upgrade to Mojave 10.14 has the same results - crashing Web Inspector - so Initial plan to revert to Sierra with Safari 10.x still the only viable solution. Darned....

**Comment by Bengejd** [comment]
This has been a consistent issue (for me anyway) since early April of 2018, but I can see the same issues being brought up as early as 2015... I can't believe 4 years later, this is still a **consistent** issue with Safari. It makes Safari Technology Preview unusable, Safari Web Inspector unusable, and makes debugging IOS apps such a pain. 

I haven't used Gantry5 personally, but I experience the same thing when running Ionic Cordova, so I have to assume it's a Safari WebView issue...

**Comment by pnutster** [comment]
Although this does not lead to any fix, this has turned out the be such a tough issue to replicate, that I am glad to hear you are experiencing similar issues.

It also makes me wonder if it is in someway (older) hardware related? Here are my specs: http://screenshots.blueoceanyyc.com/765f0fa5d675 - although I was also able to replicate the same on old 2011 mac mini: http://screenshots.blueoceanyyc.com/f5e1b8c5faeb

Would you care to share your hardware specs?

By the way, on the mac book, I actually downgraded from Mojave to macOS Sierra so that it runs Safari 10.x to avoid this Web Inspector crashing issue. Very painful... but the hanging inspector is completely unworkable

**Comment by Raensul** [comment]
Macbook pro 2018, Mojave, the same issue. The latest updates are installed.
Debugging in safari is very painful. I had to return to chrome. Unfortunately...

**Comment by pnutster** [comment]
As a follow up, using the Safari Technology Preview for the last 3 hours now. Not a single Inspector crash has occurred. Hoping the changes are pushed to the new Safari version sooner than later.

**Comment by simmonsr** [comment]
Also found an issue I am having with a template with stable Safari that is fixed in Safari Technology Preview. So hoping for the best for the next release!

**Comment by elvisgraho** [comment]
Same Issue when developing Ionic Apps
