### ISSUE TITLE
I get an error message when I click the link.

### ISSUE THREAD

**Issue by bellsmarket** [gantry/gantry5#2368]
I am building a website using Joomla.
The template I am using is Gantry 5. (Helium)
But I am suffering from the menu link problem.

I have created multiple menu items from the menu.
I specified a file right under the document root for all items.
ex.
/ plan
/ prices
/ flow
/ faq
/ contact

When you click the menu item, 
【Not Found	The requested URL /〇〇 was not found on this server.】
is displayed

Outline is not assigned to the created menu item.
On the Assignments page there is a ban on the right side of the menu item.

Why does this problem happen?

Thank you for your help.

**Comment by bellsmarket** [comment]
Thank you for your kind advice.

I tried to rename from htaccess.txt  to .htaccess.
This process alone did not solve it.
but, it is linked to the error page of Gantry 5.

I changed the menu item type to Gantry 5 Theme custom page in that state, it worked fine.

Thank you very much.

**Comment by simmonsr** [comment]
So is everything working now? Can we close this issue?
