### ISSUE TITLE
particle content not being picked up by joomla's search

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#237]
it appears that particle content won't yield any search results in joomla.
not sure if this is a joomla or gantry issue, making it work would be a great improvement.

**Comment by DamirPecnik** [comment]
Yes also issue in RokAjaxSearch Search issue ...

**Comment by mahagr** [comment]
Did we have the same issue with custom HTML modules? Because of I think they had the same issue.

**Comment by mahagr** [comment]
In Joomla modules, plugins and templates are not searchable as they do not belong into any particular page. Additionally, even if we added search support, which page should the particle belong if it is shared for the whole outline or module position. This is clearly something we cannot solve in Joomla.

**Comment by djaxutah** [comment]
I know this is closed, but there has to be some solution to not being able to search particle content.

**Comment by blizam** [comment]
I think the closing comment is pretty clear and Joomla's search has always been limited to articles... even if the Gantry team did come up with a method for searching particles A) that would not be able to be integrated into Joomla search and B) if the Particle appears on multiple pages then where would the search results even link to?

**Comment by siptec** [comment]
Could a search plugin be created to search menu items?
