### ISSUE TITLE
Twig Dump in particle gives error while rendering particle

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2372]
How to dump variables for debugging in particles? 
I use `{{ dump(post) }}` or `{{ dump(particle) }}` and it gives: Error while rendering particle.

**Comment by adiwebdev** [comment]
Hi,

You might need to enable `WP_DEBUG` in `wp-config.php`, and Debug Mode in Settings > Gantry 5 Settings.

**Comment by joomlabeat** [comment]
Sorry my bad forgot to mention that WP_DEBUG is already enabled.
dump works fine in other twig templates but not in the particle.
Could it be a bug?

**Comment by joomlabeat** [comment]
Ok - sorry! Gantry Debug Mode setting was disabled. 
That was it!
Cheers
