### ISSUE TITLE
Mega menu not working

### ISSUE THREAD

**Issue by srajca** [gantry/gantry5#2375]
Hello I have installed and am trying to work with Gantry on making a template. I have problems with the mega menu.

At First the second level is connected with arrows and I just want it to be under the first level as a sub level. I could not get this to work. Then I added all of the second level into first level and started editing it in the menu, but the result is not saving. I am sending the attached screenshot.
Can you please help?
Thank you,
![menu_not_working](https://user-images.githubusercontent.com/11521975/46110310-894c0e00-c1e3-11e8-8f61-18423ab6293d.png)

**Comment by mahagr** [comment]
Cloding due to inactivity.

**Comment by srajca** [comment]
Any luck or news? Will this be fixed?
