### ISSUE TITLE
[bug] Bug in TinyMCE Editor Integration v1.2.0 with Grav 1.5.1 + Gantry v5.4.26

### ISSUE THREAD

**Issue by Legolasindar** [gantry/gantry5#2376]
**GRAV:** 1.5.1
**GANTRY:** 5.4.26
**TinyMCE Editor Integration:** 1.2.0

My site works well, not problem. Today, i updated TinyMCE Editor Integration to 1.2.0 version, and after this, the Recompile CSS option of Gantry not works, say this:

```
500 Internal Server Error
Oops, UniformResourceLocator: Absolute stream path with relative lookup not allowed ().
```

I tried disabling the TinyMCE plugin, and works again. I tried in another site in another hosting, and the same situation. Before uptade, works well, after update, nots works.

**Comment by mahagr** [comment]
It almost looks like that the TinyMCE plugin creates its own streams which are being used, or you do in your configuration. Make sure that all the stream lookup paths are relative.

**Comment by mahagr** [comment]
I'm closing this issue as it looks like a bug in the TinyMCE plugin.
