### ISSUE TITLE
Menu Logo Trasparent Over it Carousel how can I do?

### ISSUE THREAD

**Issue by balamek** [gantry/gantry5#2377]
HI
How can I get this effect with gantry, I try with the helium theme base, and get the menu over it on carousel, but when I do a new preset for add the logo, the logo dont see, I only get the menu over it the carousel. 
![sample](https://user-images.githubusercontent.com/42281961/46353516-ffa4a200-c621-11e8-8521-7c1ac7a415b8.jpg)

Thanks for the help.

**Comment by DamirPecnik** [comment]
That depends, can i get URL to see this?

**Comment by balamek** [comment]
Hi
I dont have a link, I work in local from my project, but here is the link for I use for example, thats what I want to do.
https://www.templatemonster.com/demo/64088.html

I try with helium theme, but never I can get the logo top the menu, If I try with helium theme the logo top dont see,  I dont know how can I get this effect. I dont know how can I get this trasparent effect, If I use my own layouts.
Thanks again

**Comment by DamirPecnik** [comment]
Put it online and i can do it for you localhost doesn't work for me as I need to see the code and the layout.

**Comment by balamek** [comment]
HI
Again here is online 
http://bienestarroger.byethost32.com/guerreros/
When I try to put the logo on the top menu the logo is miss, dont see, only can see the menu.
When I try to use my own layaouts I lost the transparent menu, I dont know How can I do that.

Thanks for the help

**Comment by balamek** [comment]
I close this by error finger, please any can help me with this problem? or It cant be make in gantry?
