### ISSUE TITLE
Stop g-block size classes from becoming 100% on mobile

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2379]
Hi,

I am wondering if there is anything built-in that will stop g-block size-XX classes to turn to 100% width on mobiles.

I am thinking it would be flexible for me to use g-grid > g-block size-XX on a few "micro-layouts" (e.g. inside a particle that displays content in columns for spreading a few icons within each article box), and I want to keep their original desktop XX width in all screens.

Is there anything like that available?

**Comment by adiwebdev** [comment]
Hi,

As far as I know there aren't built-in classes to do that. I use to create additional classes, like the one below.

```
@include breakpoint(mobile-only) {
    .mobile-50 {
        flex: 0 50%;
    }
}
```

**Comment by joomlabeat** [comment]
@adiwebdev - hi!
I am just trying out this approach:
Adding an extra class to the g-grid, and then for g-block & size-* children of that class, I set all the "resizing" rules to inherit, so they will fall to their initial values. 
The first test was ok, but I' ll see if this is going to work well in the long run.

```
body .static-grid [class*="size-"], 
body .static-grid .g-block {
    -webkit-flex-grow: inherit;
    -moz-flex-grow: inherit;
    flex-grow: inherit;
    -ms-flex-positive: inherit;
    -webkit-flex-basis: inherit;
    -moz-flex-basis: inherit;
    flex-basis: inherit;
    -ms-flex-preferred-size: inherit;
    max-width: inherit;
}
```

**Comment by adiwebdev** [comment]
The `inherit` keyword will not reset the properties to their initial values, it takes the computed value of the property from its parent element.

In your example you didn't specify the `width` property, the default value is used, probably that's why it still works.
