### ISSUE TITLE
Joomla Articles Particle pagination buttons not working

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2381]
Live page: http://cry.nycweb.io/index.php?lang=en
As you can see, the "next" button has no effect when being clicked.
Joomla version is always the latest;
Gantry: 5.4.26

**Comment by DamirPecnik** [comment]
Update Gantry to latest version

**Comment by newjie** [comment]
I've upgraded Gantry to the latest version, but the problem is still there.

**Comment by DamirPecnik** [comment]
Can you send access here:
support@webthemer.com
