### ISSUE TITLE
future of Nucleus CSS framework

### ISSUE THREAD

**Issue by gour** [gantry/gantry5#2383]
Hello,

I want to settle on Grav CMS for all my web sites and Gantry seems very capable theme framework, but I wonder if Gantry will continue using nucleus css framework or something else (e.g. spectrecss is, iirc, used for default theme now in Grav ) is considered for the future?

Does it make any difference for Gantry's end-users or does Gantry abstract underlying CSS framework so it is not really important?

**Comment by blizam** [comment]
I'm not a dev but I would guess that Nucleus will be around for the foreseeable future. I find that it's classes are unique enough that they don't conflict with other CSS frameworks should you choose to implement one.

Nucleus is considered an 'Engine' within Gantry and Engines can be swapped out entirely should you want to build a theme that doesn't use Nucleus.

I'm not sure how to address your last question... in terms of how it affects frontend users the only thing of major importance is that it uses Flexbox for it's grid system which is the same set of CSS attributes that most modern grid systems use. The biggest difference from my standpoint is that the Nucleus grid system doesn't have a column concept nor a responsive column concept... it only has size-xx classes that you need to ensure add up to 100... I do wish it had like size-xx-sm, size-xx-md, etc.

When I build Gantry sites I generally use the built in nucleus grid system whenever I want to make custom rows and columns, understanding that there's really only 1 built in breakpoint at mobile when everything stacks

**Comment by blizam** [comment]
> OK. But, it seems you can achieve everything (layout-wise) that you require with Gantry?

Correct, which I see is perhaps more to your point now... when I build sites with Gantry I rarely need, and try to avoid, using actual Nucleus Grid code because that's what Sections, Grids, and Particles are for in the Layout Manager... when I do need to throw in a little Custom HTML in a Custom Particle or elsewhere I find it's easiest/simplest to use the Nucleus Grid code that's already present on the page anyways vs loading some other framework, if possible :)

**Comment by gour** [comment]
> when I build sites with Gantry I rarely need...

Thank you for clarification!

**Comment by mahagr** [comment]
Nucleus is going to stay (for backwards compatibility reasons), but something else may be considered as newer supported alternative later on. You can easily override almost every file in Nucleus from your own theme, though.
