### ISSUE TITLE
Hidden Menu Items Dropdown

### ISSUE THREAD

**Issue by JKusber** [gantry/gantry5#2386]
Hello,

i think I found a bug in Joomla.

If you have a menu item with a second level element which is hidden there is a wrong blank dropdown in gantry.

![image](https://user-images.githubusercontent.com/12516802/46680238-ee8efe80-cbe8-11e8-93fd-bc38bb4148f4.png)

Steps to reproduce:

1. Use gantry helium theme (found it also in some custom themes)
2. Create a first level menu item
3. Create a second level menu item under the one from step 2
4. Switch it to hidden so it looks like that:
![image](https://user-images.githubusercontent.com/12516802/46680343-2a29c880-cbe9-11e8-806d-cfa464966d4f.png)

Than you will get this result. Thats no problem if you use only first level elements than you can force the menu particle to only first level. But if you have some items with a second level than thats a problem!

Greetings!

**Comment by marktaylor46** [comment]
You should use the "disable dropdown" in the parent menu item settings in Gantry 5 menu editor. Then you won't get a blank dropdown and the dropdown "v" will be removed too.

Regards, Mark.

**Comment by JKusber** [comment]
Ah ok! I said nothing!

-close!

**Comment by marktaylor46** [comment]
:) - you can close the ticket yourself.
