### ISSUE TITLE
Console Error: Uncaught TypeError: this.setOptions is not a function

### ISSUE THREAD

**Issue by xbass540** [gantry/gantry5#2389]
I get this console error:

Uncaught TypeError: this.setOptions is not a function
    at new constructor (main.js?ver=5bbfab3d:1)
    at main.js?ver=5bbfab3d:1
    at HTMLDocument.t (main.js?ver=5bbfab3d:1)

**Comment by mahagr** [comment]
@xbass540 Where do you get that error? CMS? Theme? Url?

**Comment by sumanasingh2k** [comment]
[https://google.com](https://google.com)
