### ISSUE TITLE
Listen to SCSS files and compile them when updated (development mode)

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#239]
Right now Gantry 5 acts as its always in production mode and because of that it doesn't check if there are changes in the files.

**Comment by JoomFX** [comment]
This will save me a lot of time!
I always forget to "Recompile CSS" after editing the SCSS files :D

**Comment by w00fz** [comment]
We still need to re-enable our Dev / Prod toggle that we never finalized. One of the reasons for that toggle was exactly for this, as well as cache.

**Comment by mahagr** [comment]
Added own issue on Prod /dev modes here #341. Closing this issue.
