### ISSUE TITLE
Cache causes problem with dynamic content of modules

### ISSUE THREAD

**Issue by alve89** [gantry/gantry5#2392]
In Joomla I'm using Helium as template. I'm using a Tab particle I configured in the templates layout settings. This particle loads a module in every tab. Due to Gantrys cache the dynamic content of the modules is not updated.

Is it possible to disable caching the content of a specific module?

**Comment by mahagr** [comment]
You may want to disable caching from the particle YAML file if caching isn't configurable. Contact the developer of the particle unless it's your own ;)
