### ISSUE TITLE
Safari Issue (10.1.2)

### ISSUE THREAD

**Issue by pnutster** [gantry/gantry5#2394]
Been bumping into a js issue. First I thought it was my customization, but using 100% straight out-of-the-box Joomla- Gantry Helium installer; same issue: http://screenshots.blueoceanyyc.com/075c65849e1d

after refreshing page, error goes away: http://screenshots.blueoceanyyc.com/ce506ecc6bb4

I know it is an "older" Safari issue (10.1.2) on MacOs Sierra 10.12.6 - but hoping someone can try and replicate and look into this.

Any browser plugins or extensions have already been eliminated.

**Comment by Bokelmann** [comment]
Update Safari to the latest or use Chrome. Old Safari is pretty buggy (including bad flex rendering).
I guess the devs can't invest time on bugs in old Safari versions that apple already fixed in newer versions.

**Comment by pnutster** [comment]
Understandable, unfortunately, Web Inspector on Safari 11.x and up, including 12 have become far from reliable and actually hangs (there is another issue posted for that). I spent a good 2-3 weeks to downgrade from Mojave, to get back to Sierra and Safari 10.x. As for using Chrome, backend administrator use would work, however some dev apps I use WebKit engine, those remain buggy :(

Thanks for the response!
