### ISSUE TITLE
No Logo Size Settings and No Instructions for how to resize it (Helium)

### ISSUE THREAD

**Issue by greenlanegreb** [gantry/gantry5#2399]
It's a great shame, that, despite a plethora of options for particles and modules that there is no built in ability to either allow for the "real size" of a logo image to take precedence in terms of the size that an uploaded logo displays at or any meaningful settings to allow for setting the width and height. 

I've searched for straight forward instructions but there are none within the Gantry instructions. I'm reporting this as a bug as developing a website with a logo is a very basic requirement and, despite the ease with which other tasks can be accomplished, this has been well and truly overlooked and not even detailed in the instructions. 

I'd like to see size settings introduced into Gantry to allow for sizing and for some (decent) instructions to be added into the manuals. 

Thanks :)

**Comment by mahagr** [comment]
Just remember to keep the particle simple enough and backwards compatible: it should keep on working as it was without needing to save/change the particle. :)
