### ISSUE TITLE
Adding a "Module Position" particle to the Layout does not add the module position as a choice in the Module Manager.

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#24]
Adding a "Module Position" particle to the Layout does not add the module position as a choice in the Module Manager. I mean if you add a "Module Position" particle to the Layout, set the "Key" to "testgantryposition" and then go to the Module Manager, open a module, expand the "Position" dropdown menu and start typing "testgantryposition", there is nothing found.

I do understand that this is quite tricky, because the Module Manager takes the available module positions from the "templateDetails.xml" file and in Hydrogen you do not have any:

    <positions>
    </positions>

But there should be a way to add those dynamically created module positions as a choice in the Module Manager.

P.S.  Yes, typing the module position manually works and the particular module is loaded on the Frontend.

**Comment by mahagr** [comment]
This is an issue that I was going to fix just before beta launch, but after using a few hours on it I noticed that the clever idea I had on it was never going to work. It will be fixed, though, but unfortunately there's no other way than to hack this.

Long story short, Joomla thinks that module positions are something that are static and do not change. They are stored in manifest file. What I need to do it to rebuild that file (or positions part of it) every time someone changes module positions in our admin -- not to mention installation.

**Comment by JoomFX** [comment]
Thanks for the details @mahagr :)
I'm glad you are actually aware of this issue and it will be fixed.

**Comment by w00fz** [comment]
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!
