### ISSUE TITLE
Suggestion: add toggle to section settings "Breakout"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#240]
It would be useful if a section could "breakout" of the breakpoints set for the template as a whole and therefore utilise the full width of the browser. The equivalent of this would be the "fullwidth" positions in Gantry 4 templates.

You can easily make the whole template use the full browser width by changing the style settings for the breakpoints all to be 100% (instead of REM units). But it would also be nice to do this selectively for a single section (e.g. "showcase" section in Callisto).

I would suggest just adding a toggle to sections settings of "Breakout" - if this is enabled then the g-container for that section should just be set to 100% instead of using the units set in breakpoint settings. I tried this with CSS and it seems to work very well.

**Comment by JoomFX** [comment]
+1

This is actually a quite good idea!
You can currently define which sections to be "fullwidth" by just removing the `container` for it in the YAML Layout file, for example [this](https://github.com/gantry/gantry5/blob/develop/engines/joomla/nucleus/layouts/_joomla_-_gantry4.yaml) .

But it will be very handy to have this option in the Admin, so the user can do it in one click without touching the code.

**Comment by adi8i** [comment]
we've discussed something like this before, if i remember good, and i don't think is that easy to implement, because it use flex and la la.... @kevlardev know the best :d

**Comment by marktaylor46** [comment]
It's easy to implement - instead of setting g-container for that section to the breakout units defined in style settings you set it to 100% instead - then everything works as you would expect. Try it - just add one line of CSS to illustrate it works:

section#g-showcase > .g-container {
    width: 100%;
}

**Comment by sural98** [comment]
+1
Will be helpful for Chimera-like themes.

**Comment by kevlardev** [comment]
Yes, we had talked about this during initial development and had planned on working on a better and more intuitive system for handling the placement of g-container on a section by section basis. This along with some changes to the way layout is done in the yaml would make it much easier to modify and create designs. It's something we just have not had a chance to dig into yet, but its on the list.

**Comment by marktaylor46** [comment]
A simple toggle in section settings would make it really easy for non-programmers to be able to make sections fulwidth without having to go near any code.

**Comment by nicutor** [comment]
+1 here, we should be able to add how many browser full width positions on templates.
