### ISSUE TITLE
Drop Down Menu Item Width Cannot Be Set The Same As The Length of the Top Item (Hydrogen)

### ISSUE THREAD

**Issue by greenlanegreb** [gantry/gantry5#2400]
Despite there being lots of options for the menu display particle, there is not one that allows the drop down background to be the same width as the width of the top menu item. Many thanks :)

**Comment by greenlanegreb** [comment]
.g-main-nav .g-standard .g-dropdown in SCSS fixes this but it is something that users would have to ask more advanced users about. It seems to me that there should be a much easier way of doing this.

**Comment by newkind** [comment]
Well it's not there for a purpose - very often the dropdown menu items are wider than the parent menu items and this would contract them.

Please take a look at the screenshot :
![https://monosnap.com/direct/gDjDbCjsd3pJKcWV0QWDI9WOLx2vIK]

This is something that should be customized by the user according to their needs.

**Comment by mahagr** [comment]
Milestone just means that it was dealt/closed at that time, not that something was fixed.
