### ISSUE TITLE
Gantry particle with K2

### ISSUE THREAD

**Issue by exigo5** [gantry/gantry5#2404]
Hello!

Could you say to me the grantry particle when will K2 content managers be compatible?

Do you have such a plan?
I really miss it and I think it would be very useful!

Very thanks!

**Comment by mahagr** [comment]
There are no plans to add K2 support. 

If K2 provides good and documented PHP API to get the content from it (without hacks or needing to implement the whole K2 inside Gantry) I will reconsider this, but I am not aware that this exists.

**Comment by exigo5** [comment]
I spoke inspiretheme team they make more gantry particle, he said, I ask here.
I think this option will is very usefully.
I hope this it will be like this :)

Thanks for your answer!

**Comment by MelJ-H** [comment]
Hi. has there been any further decisions regarding K2 been integrated into gantry 5? Or is it a case if I want to use Gantry 5 I need to convert all K2 articles to Joomla articles?
Thanks

**Comment by mahagr** [comment]
You can still use K2, but you need to use its modules instead of our particles.

**Comment by exigo5** [comment]
> Hi. has there been any further decisions regarding K2 been integrated into gantry 5? Or is it a case if I want to use Gantry 5 I need to convert all K2 articles to Joomla articles?
> Thanks

I have think need it use convertion K2 to com_content, because the K2 components very old school this time.

He no longer better so much that it is worthwhile to devote energy to it. Unfortunately.

If someone knows the best solution for the conversion, I would be very interested!

**Comment by MelJ-H** [comment]
> You can still use K2, but you need to use its modules instead of our particles.

Thanks. Though shame as I would like to use some of the particles. 
cheers

**Comment by MelJ-H** [comment]
> > Hi. has there been any further decisions regarding K2 been integrated into gantry 5? Or is it a case if I want to use Gantry 5 I need to convert all K2 articles to Joomla articles?
> > Thanks
> 
> I have think need it use convertion K2 to com_content, because the K2 components very old school this time.
> 
> He no longer better so much that it is worthwhile to devote energy to it. Unfortunately.
> 
> If someone knows the best solution for the conversion, I would be very interested!

It would be useful if I could convert from K2 to com_content. Looking long term might there be a point K2 stops working 
cheers

**Comment by mahagr** [comment]
Unfortunately, I do not know K2 too well; I've tried it a couple of times and read its code. This is also the main reason why it's not supported -- it takes a while trying to reverse engineer another project (as in Joomla way they likely have no API).

**Comment by newjie** [comment]
rokSprocket can get k2 contents.
