### ISSUE TITLE
Gantry5 Particles Using PHP instead of TWIG/YAML

### ISSUE THREAD

**Issue by pau1a** [gantry/gantry5#2405]
Hi guys,
Im loving Gantry5 and starting to get in deep, trying to learn the heart of it. Im looking at how closely Symfony/Twig is woven through the whole framework and so consequently trying to understand Symfony. I have a straightforward question and I apologise if this isn't the place for it.

Is it possible to create Gantry particles that don't take advantage of the TWIG/YAML and instead only use PHP? Ive looked around the docs and can't see anything.

**Comment by mahagr** [comment]
It's all Twig, but of course, you can call PHP from the Twig (Gantry does that a lot). Twig is easier and cleaner than PHP, though and it allows really cool ways to extend your template files which is hard to do from PHP.

Documentation for Twig can be found from here: 
https://twig.symfony.com/

YAML will just be converted to a PHP array (literally to PHP file in cache), so there's really nothing special in it. Again, it is just easier to read than PHP syntax. You can easily google YAML to see how it works.

**Comment by pau1a** [comment]
Thanks Mathias for taking the time to answer. I appreciate it.

Thats good to know. If possible could you point me to an example of this being done within Gantry? 

Ill then hopefully pick this apart and follow the threads. Like I say Im trying to get my head around everything at the moment and whilst twig looks really cool, the option to use PHP for whatever reason will be a valuable one.

**Comment by marktaylor46** [comment]
http://docs.gantry.org/gantry5/advanced/php-functions

Regards, Mark.

**Comment by pau1a** [comment]
Hi Mark, 
Thanks for that. I could've sworn Id read that document before but I guess not. Ill step through the guide and check it all out. Interesting stuff... cheers
