### ISSUE TITLE
Error running Gantry5 on joomla 3.9 with PHP 7.1 and up.

### ISSUE THREAD

**Issue by ridejong** [gantry/gantry5#2406]
Hi all,
 I am running gantry5 (latest version) on Joomla 3.9 with PHP version 5.6 and 7.0 this works fine. After upgrading to PHP 7.1.19 gantry seems to be failing with error: 

Warning: require_once(/customers/c/8/2/stemband.com/httpd.www/joomn/libraries/joomla/document/html/renderer/head.php): failed to open stream: No such file or directory in /customers/c/8/2/stemband.com/httpd.www/joomn/templates/gantry/error.php on line 85 Fatal error: require_once(): Failed opening required '/customers/c/8/2/stemband.com/httpd.www/joomn/libraries/joomla/document/html/renderer/head.php' (include_path='.:/usr/share/php') in /customers/c/8/2/stemband.com/httpd.www/joomn/templates/gantry/error.php on line 85

Is there a fix for this as PHP 5.6 is not support anymore.

Found that Joomls 3.8.x no longer uses libraries/joomla/document/html/renderer/head.php and since the template is trying to open this file, that is what is throwing the error message.

 back to PHPv7.0 and it works again. It looks like "require_once(JPATH_LIBRARIES.'/joomla/document/html/renderer/head.php');" in the gantry/error.php is not beeing used with PHPv7.0 removing this line does not affect the website. From PHPV7.1 it does. suggest fixes dont seem to work. Removing the line and replacing with othet code result in a different error.(gantry5 Error: 0 - [] operator not supported for strings) Replace ment code: 

```php
$header_contents = '';
if(!class_exists('JDocumentRendererHead')) {
    $head = JPATH_LIBRARIES . '/joomla/document/html/renderer/head.php';
    if(file_exists($head)) {
        require_once($head);
    }
}
```

Any advice on this?

**Comment by mahagr** [comment]
Looks like you have an old installation of Gantry 4 in your site. If you're not using it anymore, I recommend removing it (including the default `gantry` template), if you are, you need to update it and the default template.

**Comment by mahagr** [comment]
Just a quick clarification: the error doesn't come from Gantry 5. :)

**Comment by ridejong** [comment]
Hi mahagr, I will have a look. As far I know of the old Gantry4 is removed upon installing 5. I will let you know.

**Comment by ridejong** [comment]
Wrong button.. Sry.

**Comment by mahagr** [comment]
The error comes from `templates/gantry`, which is an old Gantry 4 default template. :)

**Comment by ridejong** [comment]
I see what has happened. Gantry5 is installed but the template has never been transferred from G4 to G5.
As I toke over from someone and I am not really into Gantry, is there an easy way upgrade the G4 template to G5? I can remove G4 before moving the site.

**Comment by marktaylor46** [comment]
If you are not using Gantry 5 then uninstall it. Then update Gantry 4 to latest version and your template to latest version too. Gantry 4 templates do not work on Gantry 5 and vice-versa. There is no easy way to convert a g4 template to g5 - you have to choose a new template and effectively start over. There are only a couple of RT templates that have a G5 equivalent template and even then there is a lot of work involved (it's still like starting over).

Regards, Mark.

**Comment by ridejong** [comment]
Hello marktaylor46,
Thank you for you answer. Gantry 4 is on the latest version 4.1.37. As this version does not seem to work with PHP 7.1 and up, I think I have to do the work and create the site from scratch on Gantry 5.

**Comment by marktaylor46** [comment]
What template are you using? Gantry 4 and all RT templates and products work on PHP7.x

I think you're using the Gantry 4 TEMPLATE and well as the Gantry 4 FRAMEWORK - so did you update the Gantry TEMPLATE to 4.1.37 too?

**Comment by ridejong** [comment]
Yes, that is correct. It all works fine on PHP 7.0 previous versions. Yes using Gantry 4 Template. All parts are updated.
![image](https://user-images.githubusercontent.com/44643201/47804335-d1a3a200-dd34-11e8-9eae-44f566455fff.png)

**Comment by marktaylor46** [comment]
That screenshot shows that you are using Gantry 4 TEMPLATE 4.1.27 so you have not updated the TEMPLATE.

**Comment by ridejong** [comment]
Good call, really need glasses. Now to find the update. lets start there. Keep you posted.

**Comment by marktaylor46** [comment]
http://gantry.org/downloads

![2018-10-31_17-03-25](https://user-images.githubusercontent.com/11683218/47805308-f0069f00-dd2e-11e8-8eec-87e4ab924a9d.png)

**Comment by ridejong** [comment]
Thanks, its already installed:-) With PHP 7.0 it works fine. Now switching over to PHP 7.1.

**Comment by marktaylor46** [comment]
It'll all be ok now then. and if you can I would go to PHP7.2 as it's faster and more stable and more current.

Regards, Mark.

**Comment by ridejong** [comment]
PHP7.1 is working fine now changing 7.2. I dont think that it will give problems. I guess this one can be closed.

**Comment by ridejong** [comment]
Ok, running on PHP 7.2.7. I will close this issue now. Thank you all, marktaylor46 thanks for your sharp eye.
