### ISSUE TITLE
Enhancement suggestion for FA icons and infolists

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#241]
1. Search window can pop-up "search box clicked" when picking up an FA icon in particles.
2. We first create an infolist item then click this to define other parameters. Once "Add new item" is clicked infolist parameter window can pop-up. This will by-pass the first step and save 1-click.

**Comment by w00fz** [comment]
I'm not sure what you mean, you can manually type the icon in the input field and the preview automatically updates. Try typing `fa fa-rocket fa-spin`

**Comment by mahagr** [comment]
I agree that it would prevent you from manually typing the icon name. Maybe it could be option of the component, to either open popup or not?

**Comment by sural98** [comment]
Callisto example:
1. Open Icon Menu (iconmenu) particle
2. Click one of icon menu items
3. Click to change icon by searching
4. You need to click search box to start searching
We may be able to start searching without clicking the box. ie. Search box will come as "mouse-clicked"
