### ISSUE TITLE
<jdoc:include type="message"> doesn't get replaced in Error Outline

### ISSUE THREAD

**Issue by Chrissi2812** [gantry/gantry5#2414]
I try to build a custom error 404 page which includes the JS and CSS files of Joomla.

If you include the message particle in your Error Outline, Messages won't be displayed.
This is because the `<jdoc:include type="message">` doesn't get replaced, same to when you try `<jdoc:include type="head">` in error_head.html.twig.

```html
<section id="g-drawer">
    <div class="g-container">
        <div class="g-grid">                        
            <div class="g-block size-100">
                <div class="g-system-messages">
                    <jdoc:include type="message" />
                </div>
            </div>
        </div>
    </div>
</section>
```

**Comment by mahagr** [comment]
Joomla error page doesn't support anything. Joomla doesn't even consider it being HTML. You need to build it as such -- everything needs to be added manually as Joomla ignores all the CSS/JS and messages etc...
