### ISSUE TITLE
Suggestion: For all HTML based input fields (simple content, html content etc) attach editor

### ISSUE THREAD

**Issue by jobst** [gantry/gantry5#2416]
Hi.
There are many, many places where lots of different Particles of the different Layouts (base,home,...)  have HTML based input fields for various particle types (and sub content of particle types)
 - simple content
 - custom HTML
 - accordion
 - block content
 - content tabs
 - every particle that allows HTML, really

Now if you want to input a larger amount of HTML you are basically stuck with the following:
 - have a sample page for JUST for editing purpose
 - create the HTML you need for the particle in that sample page
 - check whether that's what you want
 - copy it
 - paste it into the particles HTML section
 - save it.
 - run it.

Why not having an editor link field for each of the editable (HTML) particle sections that simply allows you to open up an editor right there and save it stright into the particle input field and save it?

Just a thought!
Would make pulling up a website from scratch so much easier!

**Comment by marktaylor46** [comment]
There's already been a ticket about this for a long time - see https://github.com/gantry/gantry5/issues/236

It's also already on the development list https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel

So I don't think we need another ticket here - I think this one should be closed, the requirement is well understood already.

Regards, Mark.
