### ISSUE TITLE
Multiple plugins not loading on gantry pages 

### ISSUE THREAD

**Issue by Ayanami251379** [gantry/gantry5#2418]
I have an issue for loading other plugins and modules on pages using the inline loader.
Joomla documents notes I can use the following code to load modules or plugins:
`{loadmodule mod_type,the title,[style]}`

The plugin I am using is [vmproductimport](https://www.joomdev.com/products/extensions/vm-product-import). Its working very well on regular joomla articles but as soon as I load multiple instances of the module the gantry pages do not seem to load them correctly.

I have a joomla article page called empty to test multiple instances:
http://demo.desert-secrets.com/index.php/empty

And the gantry page that needs to have multiple instances of the module:
http://demo.desert-secrets.com/index.php/products/perfume/solid-perfume

The code needed to load the module is as follows:
`{vmimport [product id]}`

To loade multiple instances I use the following code on the joomla page
```
{vmimport 1}
{vmimport 2}
{vmimport 3}
```

I use a custom particle to generate the code as noted above in gantry but once the page is loaded only the first `{vmimport 1}` is loaded as a module and any other instances of the code is ignored.

**Comment by mahagr** [comment]
Gantry particles use a different call to process the content than articles as particles have no information about the page content and are considered as custom HTML module in that regard. I'm pretty sure that the above shortcodes do the same if you use Custom HTML module instance and put the code into there...?
