### ISSUE TITLE
Layout (Unknown)

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#242]
I am now playing with Callisto and don't know if this had been posted in Callisto forum.
I have loaded Callisto - Home configuration with Home layout.
Modified a particle and saved layout (custom/config/67/layout.yaml)
Now layout page title reads Layout (Unknown)
https://www.evernote.com/shard/s262/sh/1d311305-bd8a-4579-9461-6f39fc6a7baf/a765a975581841fcba2541e861427405

**Comment by kat05** [comment]
hi, i've not been able to replicate this issue yet, i keep playing with it though. 
are there maybe any other steps you might have taken before the issue appeared?

**Comment by sural98** [comment]
*Manually* modify "custom/config/67/layout.yaml" and *save*. For example change name in one of Icon Menu entries (Callisto)
```
                          icon: 'fa fa-pencil'
                          text: 'Media Inquiries'
                          link: 'index.php?option=com_contact&amp;view=contact&amp;id=17'
                          name: 'Media inquiries'
```
Now load the same layout again.

**Comment by mahagr** [comment]
Just FYI: Layout preset is a new feature in RC1, so having (Unknown) means that you have saved the layout before RC1. You can add the preset manually, just save another item and copy the first nested variable to set the layout name and image for you.
