### ISSUE TITLE
Gantry Hydrogen (v5.4.26 / g5_hydrogen) - Header background image full display

### ISSUE THREAD

**Issue by hitman2017** [gantry/gantry5#2421]
My website is www.tyreworld.co.nz and I'm using Hydrogen (v5.4.26 / g5_hydrogen) template on Joomla 3.9.0.
I've got a jpg image which I want to use in the header position. Currently when I place the image using module position, the image is only centered and doesn't fill the whole space in the header section.

In the template configuration, there is an option for fullwidth, boxed, removed container options but all these takes effects on the whole website instead of a particular section.

**How can I do it such that the image takes whole of the header section.**

Thanks in advance : )

![2018-11-22 00_20_59-window](https://user-images.githubusercontent.com/31493938/48838267-bafce200-edec-11e8-875d-e6b4fdb5c275.png)

**Comment by marktaylor46** [comment]
You can change that on the outline layout - just change the section setting and there you can alter the section setting to "fullwidth (flushed)".

**Comment by hitman2017** [comment]
Thanks Mark, I've just checked that setting and have made it as per the screenshot
I've cleared cache and recompiled CSS as well. It's still same :(
Anything else I can try please.

![2018-11-22 01_02_54-window](https://user-images.githubusercontent.com/31493938/48840145-aa4f6a80-edf2-11e8-903e-af04db3e359f.png)

**Comment by marktaylor46** [comment]
That's not what I said to do?

![2018-11-21_13-20-19](https://user-images.githubusercontent.com/11683218/48843863-43996500-ed90-11e8-8e02-2986410c6e04.png)

**Comment by hitman2017** [comment]
Thanks Mark, that sort of fixed the issue. However, the image is flushed only towards the left. I'm not sure why it not using the space on the right.

![2018-11-23 00_41_31-window](https://user-images.githubusercontent.com/31493938/48900946-b7cf2800-eeb8-11e8-90b0-0b6a5339e919.png)
![2018-11-23 00_43_19-window](https://user-images.githubusercontent.com/31493938/48900987-d9301400-eeb8-11e8-837e-ea9041b8e4f1.png)

**Comment by marktaylor46** [comment]
Because your image is not big enough at 1606px wide  - it needs to be at least 1950px wide.

**Comment by hitman2017** [comment]
Brilliant - thank you so much Mark. That has fixed the issue : )

**Comment by marktaylor46** [comment]
Great - please close topic now :)

Rather than posting an issue here on the github project for Gantry 5 you should raise general  questions on the Gantry 5 forum in RocketTheme.

https://rockettheme.com/forum/gantry5-for-joomla
https://rockettheme.com/forum/gantry-for-wordpress

Regards, Mark.
