### ISSUE TITLE
Particle id - or generate a hidden particle id field

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2422]
My WP particle is loading content from the database with a complex query. The particle will be loaded under Single pages content and will display content related to the current page.

Ideally I would like to cache the data of each particle on each page - using wp transients. 
For this I would need a unique key for the particles of each page. 
This can be achieved by using the post.ID.
Same time, the same particle is used in other type of pages with different settings to load different set of data. I would also like to cache the data - but this time I cannot use the post.ID. Although there are other options specific to each page to use to create a unique transient key, I am concerned about the case where the particle might appear twice on the same page. 

It would be nice if each particle instance could produce a unique ID. Similar to what happens on the layout level when inserting particles.
Dumping particle doesn't reveal anything like this, though.
So, I am wondering if this is something possible? 
Or if it would be possible to have a hidden field on particle that would auto-generate a unique ID on particle save - e.g. by date-time.

**Comment by joomlabeat** [comment]
Hi Adrian,
`{{ dump(ID) }}`  gives me `null`

 @adiwebdev

**Comment by marktaylor46** [comment]
lowercase... 
{{ dump(id) }}

Regards, Mark.

**Comment by joomlabeat** [comment]
@marktaylor46 
that works - thanks!
