### ISSUE TITLE
grav: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by mihahauke** [gantry/gantry5#2426]
![grav_gantry_memory_exhausted](https://user-images.githubusercontent.com/2771069/49585033-7d0bcc00-f95d-11e8-97fe-35adf9af795a.png)

Grav 1.5.5

I have  3 pages with barely anything there and it works ok.
When I try to go to Gantry 5 plugin it throws memory exhausted. Can I do anything with this except for increasing the memory (which I can't). I wonder if it is some issue with grav/gantry or gantry requires more than 128 mb?

**Comment by simmonsr** [comment]
Are you using the ShortCode Core plugin? If so, disable "Activate in Admin" in plugin settings or use "RegexParser" as Processor (also in plugin settings).

**Comment by mahagr** [comment]
See:

https://github.com/thunderer/Shortcode/issues/71

**Comment by thunderer** [comment]
@mihahauke I implemented necessary changes in https://github.com/thunderer/Shortcode/pull/72, once @rhukster verifies it on his side I will release new stable library version and you will be able to use `RegularParser` again. Long story short: I found over 100x performance gain so neither time nor memory will be a problem now. Thanks for using Shortcode and Grav! :smile:

**Comment by rhukster** [comment]
@thunderer that’s awesome news! Some huge improvements there. I’m going to test this shortly.

**Comment by mahagr** [comment]
Fixed in the project.
