### ISSUE TITLE
Module Position in menu instead of module particle?

### ISSUE THREAD

**Issue by uglyeoin** [gantry/gantry5#2427]
In the menu we can create a particle or a module instance in the menu dropdown (or menu).  But what I would prefer is a module-position in the menu dropdown.  

It provides so much more flexibility and allows us to easily add thing per page (in Joomla!) without having to create tonnes and tonnes of modules instances which may or may not be called.

**Comment by mahagr** [comment]
Initial version supported module positions in the menu, but it had/caused some major issues (which I cannot remember anymore) and we had to drop the feature, or basically disable the option of allowing the position to be used in the menu.
