### ISSUE TITLE
Need extra output block for atom-like particles

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#243]
1. Include the JavaScript SDK on your page once, ideally right after the opening <body> tag. 

```
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/fi_FI/sdk.js#xfbml=1&version=v2.3";
     fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
```
2. Place the code for your plugin wherever you want the plugin to appear on your page.

```
<div class="fb-page" data-href="https://www.facebook.com/facebook" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div></div>
```

**Comment by w00fz** [comment]
I dont think we need extra output block for Atoms, it would just be the same as using `Custom HTML`.
In fact, because FB requires the `<div id="fb-root"></div>`, this is de facto a `Custom HTML`.

Atoms should be only reserved for just JavaScript or CSS, we are still missing a way to position an Atom at the top or bottom of `<body>` but that's [another issue](#62) that we never implemented.

**Comment by mahagr** [comment]
Well, I think we might still want to do it atom-like as the <div> should only be appended once and you may have multiple instances of facebook plugins. Even in particle, we might need something that is common to all instances and then local output.

What comes to having only script content, I don't think it's going to work as there are a lot of invisible blocks that for example add <img> tag to add a page view; for example most ads systems use that just like most affiliate scripts. So we really need invisible atoms which have extra markup in them. And they have two preferred locations: either in the start or end of <body>.

**Comment by w00fz** [comment]
This is now possible with the implementation from #580.
