### ISSUE TITLE
Limited value in POST for sending JSON during saving Layout

### ISSUE THREAD

**Issue by Imarel** [gantry/gantry5#2432]
I have some problem... I created project on local and after sending to server, when I try save something il Layout I have error
Error while saving layout: Structure missing
When I debug
$layout = $this->request->post->get('layout')
in $layout is NULL
If value in JSON file (string) is not over 9400 works fine but above return NULL.
In Console I can see:
POST http://null:null@tiltkomp.pl/wp-admin/admin.php?page=layout-manager&view=configurations/home_-_particles/layout&_wpnonce=e4d61044d8&action=gantry5 500 ()
Problem contains Gantry5 for Wordpress and hosting home.pl

**Comment by mahagr** [comment]
Looks like there's an issue in the POST request as you said. I'm not sure what could cause it, though -- maybe there's JS warning/error when you're saving?
