### ISSUE TITLE
UPGRADE 5.4.27 ERROR

### ISSUE THREAD

**Issue by willouch** [gantry/gantry5#2434]
Hi, I have trying to upgrade from 5.4.26 to 5.4.27

but I receive error : 
Joomla\Filesystem\File::delete: Failed deleting inaccessible file EventListener.php
Installation d'un paquet : il y a eu une erreur en installant l'extension Mettre à jour

And impossible to reinstall 5.4.26 same issues

Thks

**Comment by willouch** [comment]
J'ai du modifier les lignes 124 à 127 et tout est OK:

if (!Path::canChmod($file))
{
	throw new FilesystemException(__METHOD__ . ': Failed deleting inaccessible file ' . $filename);
}

**Comment by mahagr** [comment]
Looks like file permission error and has nothing to do with Gantry itself (Joomla installer error).

**Comment by newjie** [comment]
@willouch @mahagr I've got the same issue. Please tell me which file I should edit.

**Comment by mahagr** [comment]
@newjie Make sure that all the files in Joomla install are writable by the web server.

**Comment by racingkars** [comment]
Same problem for me....

**Comment by racingkars** [comment]
> J'ai du modifier les lignes 124 à 127 et tout est OK:
> 
> if (!Path::canChmod($file))
> {
> throw new FilesystemException(**METHOD** . ': Failed deleting inaccessible file ' . $filename);
> }

Of which file did you change this?

**Comment by mahagr** [comment]
The only way I've found to really be able to fix this problem in the past, is to use ssh and change the file permissions (both chmod and chown) for all the files. To what.. depends on your server.

**Comment by racingkars** [comment]
I am doing some research as i have the same problem. I now installed a package with Joomla 3.8.1 and Gantry5 5.4.18. No problems at all. Updated Joomla to 3.8.13. No problems at all. Update Joomla to  3.9.2. No problems at all. As soon as i do an update of Gantry5 to 5.4.27 i am having the problems.   I will now start all over again and do a more slow Gantry5 update. So older versions first (5.2.26 or older) and then see when the problem starts.  To me it's strange to claim it's a permission problem. If that's so, shouldn't it be visible before?  Why on 5.4.27 and not on 5.4.18? Forgive me my ignorance.

**Comment by racingkars** [comment]
For your information. I did an install of Joomla 3.8.1. I then upgraded to 3.8.13. I then installed the Gantry5 5.4.27 update. Everything is working well. I then did an update to Joomla 3.9.2 and everything is working well.  So a different order of installing did the trick for now. Not saying it's all solved of course, but for now it is.   Maybe this info can be useful to you or someone else.

**Comment by racingkars** [comment]
I received this:  Joomla\Filesystem\File::delete: Failed deleting inaccessible file EventListener.php

If i did a manual delete of this file it gave me the same error on the next file in: Libraries/Gantry5/classes/Gantry/Admin and so on. 
If i deleted these manually it just went on with a next PHP-file in another directory.     
As stated, changing the order of installing did the trick for now. But maybe a next update will give troubles again.

**Comment by mahagr** [comment]
Gantry installer isn't specifically listing any of those files, which means that Joomla finds the file while trying to remove it and the call for `Path::canChmod($file)` fails for some reason.

Hmm:
https://github.com/joomla/joomla-cms/blob/3.9.2/libraries/src/Filesystem/Path.php#L40-L55

The method hasn't changed since Joomla 3.8.0 (but the class has been moved), so the issue must be in a change inside the installer.

**Comment by mahagr** [comment]
It looks like this is the issue you're seeing: 
https://github.com/joomla/joomla-cms/issues/23504

There seems to be some kind of change in Joomla itself which is causing this issue to happen.

**Comment by racingkars** [comment]
I am using Linux on a Homeserver (Qnap NAS TS-473).
Using Filezilla:
                                         Owner / Group
Libraries   flcdmpe  (0777)   0             0
Gantry5   flcdmpe   (0755)   99           0
classes     flcdmpe   (0755)   99           0
Gantry     flcdmpe   (0755)   99           0
Admin     flcdmpe   (0755)   99           0
all php files adfrw   (0644)   99           0

**Comment by mahagr** [comment]
@racingkars Do you have safe mode enabled in your PHP configuration? See my comment in the Joomla issue, maybe that is the cause of your issues?

**Comment by racingkars** [comment]
Setting | Value
-- | --
 
Safe Mode | Off

**Comment by mahagr** [comment]
Which filesystem are you using in your NAS?

**Comment by racingkars** [comment]
Now you are asking above my skills.... Where should i find this info?

**Comment by mahagr** [comment]
Docs are saying that preferred one is ext4, so I believe you've not changed that.

What I do see, though, is that the owner for the libraries differs from the other folders, is that true?

**Comment by racingkars** [comment]
Then it is ext4 for sure....

The owner of the Gantry5 is... 99 instead of 0
There is also RokCommon/phpQuery in Libaries that has 99
So, i do not know if this is normal.

But i also have an old website with Joomla 3.9.2 and Gantry4 
There all folders and subfolders have 99 as owner.

**Comment by mahagr** [comment]
I believe that the owner should always be 99 (nobody) and having it 0 (root) is wrong and prevents the files from being updated as www server never runs as root.

**Comment by racingkars** [comment]
Ok, i believe you!
Now how can i change it?

**Comment by mahagr** [comment]
You need to change the owner to 99 or delete those files and reinstall everything that got affected.

Some Googling:
https://www.qnap.com/en/how-to/tutorial/article/advanced-folder-permissions-on-qnap-nas/

But I recommend installing SSH and changing the permissions from there:
https://www.qnap.com/en/how-to/knowledge-base/article/how-to-access-qnap-nas-by-ssh/

**Comment by mahagr** [comment]
@newjie Did the discussion help you?

**Comment by racingkars** [comment]
Yes, it did. Thank you very much. I managed to change some owner settings. All is working fine now.  Thank you very much for your help!   Best regards.  Kars
