### ISSUE TITLE
Save page settings: A variable mismatch has been detected

### ISSUE THREAD

**Issue by manuel-84** [gantry/gantry5#2435]
I am using WordPress 5.0.2 and Gantry 5.4.27. When I press "save page settings" button for an outline I get this error: "A variable mismatch has been detected."

I can save styles, layout, content, particle defaults without problems.

I can't find a way to debug this and find the source of the error.

Can some1 help looking into the problem? Thanks

Update: probably related to WordPress 5.0.2. (https://wordpress.org/support/topic/variable-mismatch/)

**Comment by manuel-84** [comment]
I can confirm that rolling back to WP 5.0 will solve the problem (introduced since 5.0.1) :)

**Comment by mahagr** [comment]
Yes, it looks like a WP bug.

**Comment by manuel-84** [comment]
Note: not fixed yet in 5.0.3...

**Comment by manuel-84** [comment]
@mahagr Seems working in WP 5.1, but need more feedback if someone else can test

**Comment by SamVolvo** [comment]
It is still there in 2024 just got it
