### ISSUE TITLE
Joomla articles in category blog display - issue in Gantry 5

### ISSUE THREAD

**Issue by MaghSamana** [gantry/gantry5#2437]
The following display is configured in the menu item in Joomla, as "category blog", 1 leading article and 4 intro, in 2 columns. In every other template, and also Gantry 4, it displays normally.

![test1](https://user-images.githubusercontent.com/46110970/50404944-9c588500-07b6-11e9-8519-6fdb41d0975e.jpg)

In Gantry 5 (both Helium and Hydrogen) I get this: 

![test2](https://user-images.githubusercontent.com/46110970/50404947-9ebadf00-07b6-11e9-84f6-a7b7d3f62fdd.jpg)

Is this some issue with Gantry 5 and Joomla layouts?

PS: Gantry 5 issue on Joomla 3.9.1 with PHP 7.1.24.

**Comment by joomlabeat** [comment]
This looks like there are 1 or more missing closing tags - usually divs- in the html.

**Comment by marktaylor46** [comment]
Use this to find out... https://validator.w3.org/

Regards, Mark.

**Comment by MaghSamana** [comment]
Thanks, both of you. There was some divs not closing in the intro text of the articles, though this is not a problem in general, and all other templates render normally. 
Now it's been fixed. :-)
