### ISSUE TITLE
Joomla: Creating custom template output (tmpl=custom)

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2438]
Hi all, Merry Xmas and best wishes for the coming new year.

I am having some trouble to achieve or understand how to create a custom template (tmpl=custom) for outputting component's content in Joomla. 

What I want is to have a clone of the component.php with some modifications.
I created my `customtmpl.php` and also created my custom gantry layout `customtmpl.yaml`, which is a clone of the `_body_only.yaml` and set it to be used with my tmpl file.

If I access an article using my newly created template that loads the new layout (`/article/?tmpl=customtmpl`), page loads and in custom/config folder a new folder for my new layout is getting created. 

However, my `customtmpl.yaml` isn't appearing anywhere in the gantry's admin configuration outlines, so I cannot manage it, so to let's say add some custom js for that template. 

I can have a new such outline only If I go the other way, to create a new outline from within the Gantry's Admin either by duplicating the _body_only, or based on the presets layout (using my clone there), I end up with a new outline in gantry's admin. In this case though I have to use the numeric  ID of the new outline when setting the gantry layout to be used in my `customtmpl.php`.

Is this how supposed it should work?

**Comment by mahagr** [comment]
You just need to create a custom outline and give it a name. It's been a while, but I don't think that you can create custom php files in Joomla like that and the ?tmpl=xxx only allows you to load existing layouts (or outlines in Gantry).
