### ISSUE TITLE
In search of Grav Hydrogen Skeleton pages

### ISSUE THREAD

**Issue by cxfk** [gantry/gantry5#2442]
Hello,

i am in search of the skeleton pages for hydrogen (grav flavor) as shown here: http://cnwebdesign.altervista.org/hydrogen-home

It would be nice if I could get a hint where I get it in raw format.

Thank you very much!

**Comment by adiwebdev** [comment]
As far as I know there's not a skeleton for Hydrogen theme. Go to [download](http://gantry.org/downloads#grav) page, then:
1. Install Grav
2. Install Gantry
3. Install Helium
