### ISSUE TITLE
hydrogen and wordpress

### ISSUE THREAD

**Issue by sistaidan** [gantry/gantry5#2444]
Hy !'m just desperated about this issue. I'm not a native speaker and my english is a bit rusty. I did all my sites with hydrogen everything seemed perfect till I upgrade [WordPress) to version 5. now I have this error on front and back end. 

<img width="941" alt="error hydrogen" src="https://user-images.githubusercontent.com/17512446/50730862-a59f0580-1157-11e9-80c4-184d7dcd9c14.png">

Tryed to reinstall hydrogen. to unzip and recompress the folder. nothing worked.
I know nothing about PHP.
Can please someone help me fix this all my sites are down. So anxious.

**Comment by sistaidan** [comment]
Thanks for your answers... I'm gonna' try this and come back to both of you.
It seems to me I use PHP 7

**Comment by sistaidan** [comment]
back, thanks newkind for you solution, my site (front end) is back but still no menu selected.

<img width="934" alt="front_end" src="https://user-images.githubusercontent.com/17512446/50740816-c23d4b00-11f4-11e9-8c4d-3ec89d2f18a8.png">

Apparently I lost all my configuration, I tried so many things to make this work, I must have throwed my child-theme. Anyway  the problem now is that nothing works properly in hydrogen admin like you can see on photos. the admin vew is not the one I know. Most settings do not work. I can't even change the default layout. 

<img width="850" alt="admin_hydrogen_3" src="https://user-images.githubusercontent.com/17512446/50740828-fd3f7e80-11f4-11e9-91df-610c698bc42a.png">

**Comment by sistaidan** [comment]
forget for the menu, it is displayed but my site doesn't display normally and hydrogen uncontrollable

**Comment by sistaidan** [comment]
no more access as administrator. no access anywhere. I'm done ! ???

**Comment by sistaidan** [comment]
good morning guy's. okay I worked hard yesterday and here I am.
all plugins desactivated by FTP. I ununstalled gantry and hydrogen and did a new installation and this was the first time for a wile I had a normal hydrogen display. so I tried a new child theme to start working... back to a 500 error.
so that's a proof my pb comes from hydrogen. as soon I activate a child I have a 500 error. tryed 3 times with different plugins. of course I must have incompatibility with a plugin but this is a minor pb. I'll try them them one by one.
last solution, I will try to create a child by hand to see if a keep a stability. I really can't work on the parent theme.
I don't see what to do else ! really sorry to bother you with that but I'm going from problem to problem and no solution. I have two major sites down and lost most of my configurations...

**Comment by newkind** [comment]
500 error means that something on the server side is not right. Please check your php error logs. Maybe there are some file/directory permission issues? Please try to deactivate and reinstall Gantry 5 plugin.

**Comment by sistaidan** [comment]
sorry forgot to give you my site adress 
 https://cgl-med.fr

**Comment by sistaidan** [comment]
Every thing is in order, for le moment hydrogen is stale. so good to start working on design. thanks a lot for you help. good night
