### ISSUE TITLE
Particle: wordpress.call('Timber::get_post')

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2445]
Hi,

I am showing a google map with a particle, below the WP main page content. 
Inside my particle I use:
`{% set post = wordpress.call('Timber::get_post') %}`

to get the post and then get the map's lat,lng from custom fields in the post to show in the map.

However, I just noticed that when I switch to production mode with the compiler for the twig/yaml enabled, the above snippet will become static and will always return the post object of the first loaded page on the browser, so every next-loaded page will show the same map as the first one.

How should I go about getting each time the current post object of the page I am looking at, within the particle?

**Comment by joomlabeat** [comment]
Searching in issues I came across a similar one: #2388

**Comment by newkind** [comment]
Remove this code from you particles YAML:
```
configuration:
  caching:
    type: static
```

**Comment by joomlabeat** [comment]
This seems to do it... Thanks @newkind for the quick response - you saved my day.

**Comment by newkind** [comment]
Great!

**Comment by joomlabeat** [comment]
My memory was blurred about particle's caching...
I also just re-discovered the documentation page: http://docs.gantry.org/gantry5/particles/particles

The docs state that the only caching option is "static". However I have seen that the custom html particle uses "config_matches", which I guess will obey to what the settings are. 

Is this an option that can be used in other particles as well, does it take any extra coding/configuration or has other requirements to make it work? 

And are there today any other caching options beyond the 2 above?
