### ISSUE TITLE
Gantry 5 hydrogen, joomla, php 5.6 to 7.* problem

### ISSUE THREAD

**Issue by procc1** [gantry/gantry5#2447]
Hi,
I'm using Joomla (latest version) and gantry 5 hydrogen theme (latest version)
When I try to switch php 5.6 version to 7.3 (or 7.*) , site breaks by giving this error:
What could be the problem?
p.s. "Gantry 5 Framework" is installed.

> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 369
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Attempt to modify property 'Array' of non-object in /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php on line 363
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/vazija/domains/varpogimnazija.lt/public_html/libraries/rokcommon/RokCommon/Registry.php:363) in /home/vazija/domains/varpogimnazija.lt/public_html/templates/g5_hydrogen/includes/gantry.php on line 48
> Failed to load 'g5_hydrogen' template: Please install Gantry 5 Framework!

**Comment by N8Solutions** [comment]
@procc1 Have you specifically tried switching to PHP v7.1 or v7.2?

There is a known issue with PHP v7.3 at the moment. Until the PHP community presents a fix for the issue, it is recommended, until that time, to use PHP v7.1 or v7.2.

Also, I see the error messages pertain specifically to RokCommon.
You should make sure you have fully updated all the extensions on your site so they are using the latest versions.

Since you have RokCommon installed its a pretty safe bet that you are also using another extension that depends on it like RokSprocket. You should update RokCommon to the latest version as well as anything else that is using it like RokSprocket. You can download the latest version of RokCommon by clicking on the "Download" button for RokSprocket and downloading it there.
[https://rockettheme.com/joomla/extensions](https://rockettheme.com/joomla/extensions)

As mentioned, you should make sure you are using the latest version of any extensions that are dependent on RokCommon. If you are not using anything that depends on RokCommon then you should uninstall it.

**Comment by N8Solutions** [comment]
For reference, here are the PHP v7.3 bug reports I was referring to
[https://bugs.php.net/bug.php?id=77430](https://bugs.php.net/bug.php?id=77430)
[https://bugs.php.net/bug.php?id=77114](https://bugs.php.net/bug.php?id=77114)

**Comment by procc1** [comment]
Thank you ;)
I updated RokCommon from 3.2.0 to 3.2.6 and now all PHP 7.* versions works without a problem ;)

**Comment by N8Solutions** [comment]
@procc1 Glad I could help!

Please close the issue since your problem is solved. 😉
