### ISSUE TITLE
Gantry 5 / Joomla 4 Alpha Testing

### ISSUE THREAD

**Issue by plainhavoc** [gantry/gantry5#2448]
Hi all, I was hoping there would be a section just for those of us who love Gantry, and are testing out the Alpha of Joomla 4. 

As many of you know, Joomla will have several issues of its own at this stage, but if we all pull resources together, we may be able to help report our findings to the devs here.

### Context: 
Attempted installation of Gantry 5.4.27 on Joomla 4 - Alpha 1 using the 'file upload' method.

### Expected Result: 
Error upon installation of all.
### Actual Result: 
Successful installation of component; Unsuccessful installation of both Hydrogen and Helium Themes. 
After installation; Joomla receives "Class 'JEventDispatcher' not found" Error 0, and site locks up. In J4, that class has been removed. [Referenced](https://issues.joomla.org/tracker/joomla-cms/18922)

Hope everyone is having a great week so far!

**Comment by mahagr** [comment]
There's a branch for Gantry 5 which works in Joomla 3.8+ and Joomla 4 (with some known issues).

https://github.com/gantry/gantry5/tree/feature/v5.5.0-joomla4

**Comment by plainhavoc** [comment]
Hi @mahagr , do you know if the installer xml would be different between 5.5.0 and 5.4.27? 5.5 seems to be missing the installer on github.

**Comment by mahagr** [comment]
There's no existing build for 5.5 yet.
