### ISSUE TITLE
How does Category Finder include subcategories?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2453]
Is this possible at all? I couldn't find similar issues and am not sure if it is a Joomla feature or Gantry feature.
All I want to achieve is let particles like Joomla Article to display articles in a category AND its subcategories.

**Comment by newjie** [comment]
Can someone just tell me whether this is possible?

**Comment by mahagr** [comment]
It is supported. Documentation is your friend here: http://docs.gantry.org/gantry5/advanced/content-in-particles

**Comment by lambdaheart** [comment]
I've been looking and I can't find anything like that. In content finder there is `.category(ids, include = True)` but this include tells us if we want to include or exclude category `ids`. I can't find anything like `include_child_category_articles`.

**Comment by mahagr** [comment]
Sorry, I was on a vacation.

You can do it by using category finder first, using `.id(category_ids, 10)` where the second argument is max levels. When you have a collection of categories, you can give the collection as the first argument to the method you have above.
