### ISSUE TITLE
HELIUM Joomla - No inheritation of the Mainbar from Base Outline

### ISSUE THREAD

**Issue by hacki65** [gantry/gantry5#2456]
Hello.
I think i found a big in helium. The inheritation from Base Outline to the Standard Outline of the CONTAINER (wich has the mainbar inside) don't work.

If i set another layout for aside, mainbar and sidebar (like 10%, 70%, 30%) or change any other things in this container like a variation or an layout like "Boxed" - nothing of this changes will be inherit to the Standard Outline.

The only way at the moment is to setting up this CONTAINER is to don't set this in the Base Outline. It must be set  in the Standard Outline or any other own Outline.

Base Outline:
![screenshot_2019-02-01 krusius fussboden gmbh - administration](https://user-images.githubusercontent.com/20481746/52143899-f6255800-265c-11e9-881d-09f4ff80b2de.png)

Standard Outline inherit from Base Outline:
![screenshot_2019-02-01 krusius fussboden gmbh - administration 1](https://user-images.githubusercontent.com/20481746/52143948-1e14bb80-265d-11e9-96dd-2e27897a9729.png)

Can this be investigated please?

**Comment by hacki65** [comment]
Another thing of this behaviour: If this is a feature and not a bug, it is confusing because all other settings will be inherit. So if this behaviour is a feature a documentation or warning would be nice.

**Comment by mahagr** [comment]
There is no container inheritance, it is part of the layout which is not inherited. Inherit from Page Settings means the Page Settings tab, not the base outline.

This behaviour is actually by the design as it is even more confusing if the container would be inherited as it would change the layout from the current outline and cause all kinds of issues which would be impossible to track.
