### ISSUE TITLE
500 Internal Server Error when click on particle defaults and page setting

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#2460]
hi i get this on my site when click on particle defaults and page setting
```
500 Internal Server Error
Oops, An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable")..
```
and i see Updates Available: Gantry 5.4.27 and when push update says me no updates atm. im on v 5.4.27 / g5_hydrogen

Joomla! 3.9.2 Stable [ Amani ]
Versión de PHP | 7.2.14

anyone know how to resolve?

**Comment by mahagr** [comment]
If installer does not work, you can also install latest version manually from here:
http://gantry.org/downloads#joomla

If upgrading manually doesn't work, you likely have bad file permissions.
