### ISSUE TITLE
Custom twig filter in Wordpress Gantry 5

### ISSUE THREAD

**Issue by Vanguger** [gantry/gantry5#2472]
We have long discussed this topic for Joomla right here: https://github.com/gantry/gantry5/issues/1584
I now have a question, how to do the same on Wordpress, in my plugin? Show the code, please.

It does not work for me in the plugin:
```
        $theme = \Gantry\Framework\Gantry::instance()['theme'];
        $twig = $theme->renderer();
        $twig->addFilter(new \Twig_SimpleFilter('customfilter', 'myCustomFilter'));
```

**Comment by Vanguger** [comment]
I did it like this. This works in the frontend, but again does not work in the admin panel:
(error in backend: Oops, Unknown "testCustomFilter" filter ..)

```
add_filter('timber/twig', function($twig) {
	$twig->addExtension(new Twig_Extension_StringLoader());
	$twig->addFilter(new Twig_SimpleFilter('testCustomFilter', 'myCustomFilter'));
	return $twig;
});

function myCustomFilter(){
	return 'Ok Custom Twig Filter';
}
```

**Comment by mahagr** [comment]
Yes, that works, but I don't think there's currently an event to hook up a filter into admin.

Though, that said, you can use the same code as in Joomla as long as you find the right event to run it in. It should work also in admin.
