### ISSUE TITLE
The System Outline "Error" when copied for multilingual breaks the url system in Joomla

### ISSUE THREAD

**Issue by MaghSamana** [gantry/gantry5#2475]
I'm setting up a multilingual Joomla site, which also uses Falang. Made separate language-specific outlines in Gantry 5 and all worked well. 

I needed to make multilingual 404 pages. So I made a copy of the System Outline Error, and configured the new Outline for another language. When I returned to the Outlines panel, the new Outline was marked as "default" (blue coloured-label, at the bottom right) and could not be deleted. Nothing strange so far, all the language-specifice Default Outlines that were made from copying the Default outline, are also marked in that way, are used in the site without any problem, and cannot be deleted either.

But with the new Error Outline, suddenly all urls broke on the site and I could only access the home page. Any link on the menu gave me a 404 error. I configured it for the default language - nothing changed. Since I could not delete the new Error Outline and nothing could be done, I had to restore the site from a backup. 

I don't know if I did something wrong, or if this is a bug in Gantry 5. Site uses latest Joomla! with PHP 7.1.14, and latest Gantry 5, while its template is developed upon Helium.

Any help here is much appreciated.

**Comment by MaghSamana** [comment]
I got the same goes for Home - Particles. One copy of the generic Home - Particles, set to all languages works. But if separate such pages are created and configured for each language and set to the home page, everything is messed in the home page AND in the site.

I think this is a bug.

**Comment by mahagr** [comment]
I'm not sure if I understand you correctly, but default layout is the one Joomla feature that everyone gets wrong.

You shouldn't set any of the new outline/layout as default, never do that. Default means that it is going to be used for all the pages, every single one of them. Assigning outline of a language does the same, but only for that single language. You can only have a single outline assigned as a default (or to language) at any time. So basically it is a fallback if nothing else works.

That said, Joomla does not support multiple error pages for different languages. Use module positions with particles instead and assign modules to languages.
