### ISSUE TITLE
Error Timber filter Resize?

### ISSUE THREAD

**Issue by Vanguger** [gantry/gantry5#2476]
Hi, help me understand why two strings are returned in different ways. The first is correct, the second is wrong. I check on the local server:

**In particle twig file:**
1 `{{ 'http://mysite.ru/wp-content/uploads/2019/03/5219800.jpg'|resize(100,100) }}`
2 `{{ 'http://mysite.ru/wp-content/themes/g5_hydrogen/images/av-about.jpg'|resize(100,100) }}`

**Result**
**1 Ok:**
`http://mysite.ru/wp-content/uploads/2019/03/5219800-100x100-c-default.jpg `

**2 Bug:**
`http://mysite.ru/wp-contentD:\OSPanel\domains\mysite.ru\wp-content\themes\g5_hydrogen\images/av-about-100x100-c-default.jpg`

**Comment by Vanguger** [comment]
I temporarily did this like this:
```
{% set img_path = 'http://mysite.ru/wp-content/themes/g5_hydrogen/images/av-about.jpg' %}
{% set img_res = img_path|resize(100,100)|replace('\\','/') %}
{% set img_exp = preg_match('#(/wp-content/themes/.*)$#', img_res ) %}
{% set img = ( img_exp[0] is not defined) ? img_res : img_exp[0] %}
{{ img }}
```
**But the question remains open**

**Comment by mahagr** [comment]
Maybe it is a bug in Windows. I think you should try to update Timber library (install composer to your system and run `composer update --no-dev` in `src/`) and if it doesn't fix the issue, go to TImber issues.

**Comment by Vanguger** [comment]
It doesn't even work on a remote server. I will write in Timber

**Comment by adiwebdev** [comment]
What about `gantry-theme://images/foo.jpg` ? Give it a try, maybe it works that way.
http://docs.gantry.org/gantry5/advanced/twig-filters#imagesize

**Comment by Vanguger** [comment]
"**resize**" also does not work on path: gantry-theme://images/foo.jpg?12345
if there is sign ? that doesn't work

**Comment by mahagr** [comment]
Yes, you can only access files as they are, there's no filename with question marks.

**Comment by DamirPecnik** [comment]
The issue is that Gantry is adding Asset Timestamps on files and assets

If images have Asset Timestamps on it like this it will not work:
`'http://site.com/wp-content/uploads/2019/05/GoldenGateBridge.jpg?5ccc9a0c'|resize(480)`

This works!
`'http://site.com/wp-content/uploads/2019/05/GoldenGateBridge.jpg'|resize(480)`

**Comment by mahagr** [comment]
From above it does look like an issue in Gantry, though the code seems to be wrong in the first place.

What does this output for you:
```twig
{{ particle.image }}
```
It should not have any query param in it.
I also think that you meant to write:
```twig
{{ url(particle.image)|e|resize(480) }}
```

This should fix the issue:
```twig
{{ url(particle.image, true, -1)|e|resize(480) }}
```

**Comment by DamirPecnik** [comment]
This worked!
`{{ url(particle.image, true, -1)|e|resize(480) }}`

What does that true and -1 do?

**Comment by mahagr** [comment]
The second parameter is whether to include domain and the last parameter is the threshold when to stop displaying the timestamp on the file. You likely guessed that the value means never. :)
