### ISSUE TITLE
Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)

### ISSUE THREAD

**Issue by InGenuitie** [gantry/gantry5#2479]
Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
Declaration of Gantry\Component\Twig\TokenParser\TokenParserPageblock::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token)

u get this message now when trying to access the theme page in wordpress.   so one said it might be caused by 2 versions of twig, if so where is the other version?

**Comment by newkind** [comment]
Ok you really need to stop posting this issue everywhere - here in issues, wordpress.org forums, G5 gitter. I know it's important for you but posting this everywhere just makes tons of mess.

Try decativating all plugins besides Gantry5 and see if it fixes te issue.

**Comment by InGenuitie** [comment]
its funny cause i did this first thing with out any luck,  I did it again after your recommendation(sorry for posting everywhere.) and found twig in Mailpoet.  I did a search too for twig on the server and it didn't pick this up either.  just must be one of those days, i couldnt get anything to work.  so atleast i found the conflict.

**Comment by newkind** [comment]
Great! Closing it then!

**Comment by mahagr** [comment]
@InGenuitie You can make it to work by making sure that both run the same Twig library, the easiest way (works in most cases) is just to delete vendor/twig in one of them.
