### ISSUE TITLE
Wordpress - Content Array Particle - Pagination Buttons not showing in page

### ISSUE THREAD

**Issue by felixnr** [gantry/gantry5#2480]
Hello everyone, this is my first time posting an issue in Github. 

I have been using Gantry 5 for a while and recently noticed that pagination buttons (from the WordPress Posts/Content Array particle) are no longer available in the live page [http://copu.uprrp.edu/](url)

WordPress Version 5.1.1.
Gantry Version 5.4.28.
Running with Helium theme.

What could be the issue?
Greetings, 
-Félix

![Website Particle](https://user-images.githubusercontent.com/4528336/54874139-c9b7cd80-4dbb-11e9-98d4-128411e66e2d.png)
![Website](https://user-images.githubusercontent.com/4528336/54874140-c9b7cd80-4dbb-11e9-9341-39859c3bcfc0.png)

**Comment by adiwebdev** [comment]
It is not working because `query_posts` was replaced by `get_posts`, probably other changes are required too. You can see the change [here](https://github.com/gantry/gantry5/commit/262136c5093efb729124b9cd17e6a77919825bc9#diff-8b055ab101b025e7f2a47c1086d5a5ce).

You can override the particle in your theme until the issue get fixed.

**Comment by DamirPecnik** [comment]
If we use query_posts it messes with the main query on the site. Will see what the guys can do about pagination.

> query_posts( array|string $query )
> 
> This function will completely override the main query and isn’t intended for use by plugins or themes. Its overly-simplistic approach to modifying the main query can be problematic and should be avoided wherever possible. In most cases, there are better, more performant options for modifying the main query such as via the ‘pre_get_posts’ action within WP_Query.
> 
> https://developer.wordpress.org/reference/functions/query_posts/
>

**Comment by mahagr** [comment]
I'm hoping that the above fix works properly.

**Comment by DamirPecnik** [comment]
Will test and let you know

**Comment by newkind** [comment]
Just tested the particle and seems to be working fine. I can see the pagination and it works properly.
