### ISSUE TITLE
How to create multilingual wordpress site with gantry 5

### ISSUE THREAD

**Issue by chhinsras** [gantry/gantry5#2481]
Dear all,

I am developing a website WordPress with gantry 5.

I create Home Page and I installed qtranslate-xt. Working with posts and pages are okay I can manage the multilingual site.

I have tried two methods as follows:

1. I go to helium section for designing home particle. On the top, I saw two language option, they are clickable but nothing change below.

2. Another thing, I try to use custom HTML particle to create two language site (e.g. <?php echo ('[:en] English [:kh] Khmer [:]'); ?> . However, nothing is rendering.

Please let me know if there is a solution for this.

**Comment by chhinsras** [comment]
I created differently Outline for specific language; Home_Particle_EN and Home_Particle_KH.

**Comment by mahagr** [comment]
Multiple outlines (or widget positions) are the way to do the translations in Gantry 5. Did you manage to solve your issues?

**Comment by chhinsras** [comment]
> Multiple outlines (or widget positions) are the way to do the translations in Gantry 5. Did you manage to solve your issues?

I don't think my way is preferred way, but only just for sovling current problem.

I create outlines - HomePage_KH and HomePage_EN. Blog_KH and Blog_EN.

And, each of them provides Khmer and English wording.
