### ISSUE TITLE
[Joomla] Passing particle form data back to Symphony controller

### ISSUE THREAD

**Issue by pau1a** [gantry/gantry5#2482]
Hi guys,

I guess my question really boils down to looking for information about where the symfony controller is located in gantry.

Im trying to pass simple user generated form data back from a particle in Joomla and looking at my options in terms of how to go about this. Most of the advice seems to advise that this is done in the controller hence my question. Ive had a look about and can't seem to find anything definitive.

A nod in the right direction would be appreciated.

Thanks for a great framework.

**Comment by mahagr** [comment]
There are no controllers in Gantry. In short, Gantry just renders all the positions in the layout and then constructs the layout together. Particles also support AJAX, which basically renders just the particle with some given query parameters.

So basically you need to call your logic from Twig.

**Comment by pau1a** [comment]
Thanks Mathias
