### ISSUE TITLE
[Joomla] Lightcase init question

### ISSUE THREAD

**Issue by pau1a** [gantry/gantry5#2484]
Hi guys,

I'm working through some problems on submitting forms via ajax on a popup module particle.

I can see that the particle initialises lightcase as follows:
{% do gantry.load('lightcase.init') %}

However, I have been unable to work out where lightcase takes its init settings from in the absence of a lightcase.init.js file in the template. 

I'm beginning to wonder if its hardcoded in somewhere or am I missing something.

**Comment by newkind** [comment]
LightCase is part of the G5 core and it's being initialised in the G5 core. If you want to pass your own options or parameters you can use the `data-lc-*` and `data-rel` HTML attributes according to this guide: https://cornel.bopp-art.com/lightcase/documentation/

**Comment by pau1a** [comment]
Awesome! Thanks
