### ISSUE TITLE
div excerpt text cut after one line despite 55 words configuration

### ISSUE THREAD

**Issue by sistaidan** [gantry/gantry5#2489]
Hy guy's
All is in the title.
It's not my native language so excuse my mistakes
I use gantry/hydrogen (really great framework, love it)  to create a new version of an old site, for a friend.
My problem is about excerpt (but it seems to come from the div itself not the excerpt text).
I explain : what ever I do my generated excerpt is cut after one unique line of text.
The configuration is on 55 words on back-end.
And even in : 
/public_html/wp-content/themes/g5_hydrogen/blueprints/content/blog /...or  /archives
 /public_html/wp-includes/formatting.php

Anyway after 3 days on it, I'm lost, really don't understand where it comes from. Hydrogen, gantry or wordpress (that is correctly configured too).
I found no css in class="post-excerpt" but viewing the page it looks like the div itself is contrained in height.
Please can someone help me find the solution ?

<img width="559" alt="1" src="https://user-images.githubusercontent.com/17512446/56607151-1e8f7380-6608-11e9-92c2-0081a473bb3f.png">
<img width="413" alt="2" src="https://user-images.githubusercontent.com/17512446/56607512-f8b69e80-6608-11e9-948f-74cf55fcc1c2.png">
![Uploading 3.png…]()

**Comment by simmonsr** [comment]
I think the setting you have is 55 characters, not words. Can you verify that?

**Comment by sistaidan** [comment]
Sorry don't know how to check that but in that case I tried changing that to 150 and even 300 but nothing changed in front-end

**Comment by sistaidan** [comment]
in words

<img width="423" alt="4" src="https://user-images.githubusercontent.com/17512446/56608344-db82cf80-660a-11e9-8249-4aed622cc506.png">

**Comment by simmonsr** [comment]
Can you email us @ support@rockettheme.com with a link to your site and login details so we can take a direct look?

**Comment by simmonsr** [comment]
Resolved via CSS. Removed p { white-space: nowrap; } code.
