### ISSUE TITLE
Layout cloning

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#249]
I have opened a configuration with a layout.
Modified layout and saved it.
G5 created this layout under custom/config/CONFIG_ID/layout.yaml
Now I would like to load this layout for another configuration.
I can't do that using G5 backend unless this newly created layout be copied manually to G5template/custom/layouts or G5template/layouts

**Comment by mahagr** [comment]
Actually you can.

In layout manager you can click load and then select configurations tab. It will allow you to load another layout and all its particles.

**Comment by sural98** [comment]
I can't load "custom/config/CONFIG_ID/layout.yaml" again because it is a modified one and G5 loads only those under layouts.
Will you please look at the issue https://github.com/gantry/gantry5/issues/242#issuecomment-101965803?
I think those are related.

**Comment by sural98** [comment]
And more if you load another layout for a configuration the previously loaded and saved layout "custom/config/CONFIG_ID/layout.yaml" is overridden.

**Comment by sural98** [comment]
To be more precise:
Using Callisto
Select "Callisto - Home" config and load "Home"
Modify some and save layout
Now select "Callisto - Home" config and load "Layout (Features - Typography)"
Now w/o using undo-redo how would you call modified layout that is created by G5 under custom/config/CONFIG_ID/layout.yaml

**Comment by mahagr** [comment]
You forget that Gantry 5 supports template updates, which means that all files which are not in ```templates/G5_template/custom``` will reset to original file every single time you use automatic updates from Joomla.

There is only a single location where you can put your changes and that's the custom folder. It's the only place which is safe against template updates.

For layout presets you should use ```custom/layouts``` (or without custom if its your own theme) directory and give your preset a name.

**Comment by w00fz** [comment]
In RC2 we added preservation of Particles while switching Layout Preset so this should be no longer an issue.
