### ISSUE TITLE
Blog View Format Wrong On Mobile

### ISSUE THREAD

**Issue by paul-kelly** [gantry/gantry5#2490]
When a blog view is displayed on a small screen e.g. phone, the multicolumn view is condensed to single column.

The article title is pushed to the side of the article and does not stay above - see here:
https://www.yourbusinesscommunity.co.uk/why-i-joined

When you view on mobile or reduce the browser to show one column, the issue is visible

**Comment by N8Solutions** [comment]
@paul-kelly From what I can see, everything is working normally.

I'm assuming you are referring to the Titles that are above each of the pictures, correct?

This is an issue with how you have created the page. If you require a different behavior when the site is viewed on a mobile or a tablet then you need to use media queries to get the desired result.

**Comment by paul-kelly** [comment]
Thanks for the response.

The issue on mobile is that the title are not showing above the image (except for the first one), which they are meant to.  They are pushed to the side of the next image!

I am using Hydrogen without any mods (that I am aware of!!!)
