### ISSUE TITLE
Small bug with the Section paddings

### ISSUE THREAD

**Issue by impressionestudio** [gantry/gantry5#2494]
Hi, 

I noticed that the classes "Large Vertical Paddings" and "Large Horizontal Paddings" create some problems in the content width when the browser width is for desktop near to tablet.
I attach an image for better understanding.

![gantry5-section-large-paddings-error](https://user-images.githubusercontent.com/4274087/57787627-681e3a80-773e-11e9-9fa3-f46d54bbbd4f.jpg)

If I remove these two classes then the problem is solved.

(I have noticed in the past a couple of similar problems with the Section paddings and margins so I guessed that this is not just a coincidence.)

**Comment by simmonsr** [comment]
That container class is there regardless of the large section paddings class.

**Comment by impressionestudio** [comment]
If you are talking about g-container, then yes, it is always there, but I believe that the classes "Large Vertical Paddings" and "Large Horizontal Paddings" are responsible for the following CSS code:
@media only all and (max-width: 59.938rem) and (min-width:48rem) 
	.g-container {
		width: 48rem;
	}
}
which changes the width of the content and makes it to overflow.

**Comment by marktaylor46** [comment]
You site looks fine to me if I add those classes back in?

That CSS looks correct to me - the container should be constrained to that size.

![2019-05-15_17-27-42](https://user-images.githubusercontent.com/11683218/57792486-08706100-7737-11e9-8155-a597e3cfdd5c.png)


Regards, Mark.

**Comment by impressionestudio** [comment]
If you disable the line "padding: 5rem 0;" in "#ank #g-testimonials" then the problem will appear.

(I removed the classes "section-vertical-paddings-large" and "section-horizontal-paddings-large" and added the custom code "padding: 5rem 0;" to have more space around.)

Thanks for looking at it.

**Comment by marktaylor46** [comment]
The definitions of those two classes are coming from your own custom.scss file - they are not part of Gantry 5 - and it is these definitions that are incorrect because the padding should be added to the g-container within the section and not the section itself.

I.e. your custom.scss statements should not be:

~~~~
#ank .section-horizontal-paddings-large  {
    padding-left: 15%;
    padding-right: 15%;
}

#ank .section-vertical-paddings-large {
    padding-top: 6vw;
    padding-bottom: 6vw;
}
~~~~



But rather they should be:

~~~~
#ank .section-horizontal-paddings-large .g-container {
    padding-left: 15%;
    padding-right: 15%;
}'

#ank .section-vertical-paddings-large .g-container {
    padding-top: 6vw;
    padding-bottom: 6vw;
}
~~~~

Regards, Mark.

**Comment by impressionestudio** [comment]
Damn, I see these classes (g-container, g-block etc) so many times per week (if not day) and I was not able to see this. I should have noticed that g-container was needed...
Thank you very much. I will be more careful next time.
