### ISSUE TITLE
Submenus not working 

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#25]
problem with submenu: in "Main menu" I created a second item menu "About us" with two submenus "Our activity" and "Where we are" all linked to a single article item, then I assigned this menu to Default view, with Preset 3 as Style. I can reach the requested page "About us", but clicking on the submenus nothing happens, the page is greyed, but no redirection to the articles. Also in Layout - Hydrogen Default, it is not possible to save the changes to menu settings (Menu, start level, end levels etc): clicking Apply I received an ok message, but after saving the layout I reload the page and nothing has changed.
![grey](https://cloud.githubusercontent.com/assets/11693902/6900114/ae0e15a8-d704-11e4-88a4-c603bf4b9f38.jpg)
Example of what happens clicking on "Our activity" submenu item: page is grey and no redirection to the article

**Comment by kevlardev** [comment]
This was due to the header section not having the proper z-index so the menu overlay was covering up the menu making it not able to be interacted with (most of our testing had been with the menu in the navigation section. It has been fixed with 9b698be36533205826de07ab23573999ccdbd098.
