### ISSUE TITLE
Split n-level menu into multiple columnes

### ISSUE THREAD

**Issue by Flowman** [gantry/gantry5#250]
Right now there is only an option to split 1-level items into multiple columns. In Gantry 4 we could specify on each item to split up child items into columns.

It doesn't have to go to the extrema, but to split up 2-level into multiple columns would be nice.

**Comment by kevlardev** [comment]
Currently we are only going to provide multiple column support for the 1st level of dropdowns as the UI is designed pretty specifically for managing a single level of columns with manipulation of items within those columns for all levels for use in extended menu mode.

**Comment by jameswadsworth** [comment]
Just migrating a site to the Interstellar template using Gantry 5 and we have level-3 dropdown that requires multiple columns. Any plans to add multiple columns to more that the first level because it does limit the design somewhat.

**Comment by w00fz** [comment]
No plans for the moment but you could  try to implement your own, we don't force our menu model.

**Comment by jameswadsworth** [comment]
Hi Djamil, if I wanted to implement multiple column support for level-2 dropdown and greater which files should I be looking at?

**Comment by jameswadsworth** [comment]
Perhaps not so easy to implement after reading this thread :(

[https://github.com/gantry/gantry5/issues/985](url)
