### ISSUE TITLE
https:// owl-carousel fails to load in "production mode", but loads in "development mode"

### ISSUE THREAD

**Issue by onsombal** [gantry/gantry5#2502]
WordPress 5.2.1 running Gantry 5 version-5.4.28 and Helium theme-5.4.28.

owl-carousel in the Header-section fails to load when using https:// in "production mode", but loads successfully when using http:// in "production mode".

owl-carousel in the Header-section loads successfully when using https:// and http:// in "development mode".

**Comment by simmonsr** [comment]
did you clear cache in the Gantry 5 admin? top right menu -> Extras -> Clear cache? Also clear your browser cache.

**Comment by onsombal** [comment]
Palm to the forehead. Yes, clearing the cache fixed it right up!

Thank you, simmonsr...

**Comment by simmonsr** [comment]
You're welcome!
