### ISSUE TITLE
WordPress Posts (contentarray)

### ISSUE THREAD

**Issue by vadimportnoy** [gantry/gantry5#2506]
if I enter anything in the “Categories” field it just disappears (on the frontend) and nothing is shown at all.

**Comment by beaversolutions** [comment]
![image](https://user-images.githubusercontent.com/43948602/59928007-73077180-9446-11e9-8738-007d84a20b14.png)

**Comment by beaversolutions** [comment]
any updates?

**Comment by newkind** [comment]
Is this still relevant?

**Comment by vadimportnoy** [comment]
Yes please

**Comment by newkind** [comment]
What browser, OS? What are you typing into the category field? The field will only display existing categories and after selecting one you have to either click on it or press enter to add it. I just tested this on my end and it seems to be fine.

**Comment by vadimportnoy** [comment]
just check this after long time and it is working! thanks a lot :)

**Comment by vadimportnoy** [comment]
after updating to 5.4.33, broken again

**Comment by vadimportnoy** [comment]
only one post displayed

**Comment by mahagr** [comment]
Fixed
