### ISSUE TITLE
import specific fonts for every language

### ISSUE THREAD

**Issue by mikajaxxx** [gantry/gantry5#2524]
Hi
I think if there be some kind of option/feature to import specific fons for every language it may help page speed.
i done it by creating an outline for second language, but I think there should be a better solution to load different fonts for every language.

**Comment by mahagr** [comment]
Right now the only fully working way to support multi-language in particles is to create outline per language. This is kind of Joomla way, which can be improved, but it requires a lot of work and full-blown multi-language support from Gantry.
