### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by pau1a** [gantry/gantry5#2525]
Are there any plans to update G5 to Bootstrap 4?

**Comment by mahagr** [comment]
Yes, as Joomla 4 uses it and not Bootstrap 2.3.

**Comment by exigo5** [comment]
> 
> 
> Yes, as Joomla 4 uses it and not Bootstrap 2.3.

We know, J4 use it B4.
The question is G5 when use it B4?
I think paula was this is question, and my question is too.
Thanks!

**Comment by mahagr** [comment]
Please read my response again. It was "Yes" :)

**Comment by thexmanxyz** [comment]
@exigo5 The answer to the question when is: As soon as Gantry supports J4 and probably this will happen as soon as J4 is still stable which currently is not the case
.

**Comment by exigo5** [comment]
> 
> 
> @exigo5 The answer to the question when G5 supports BS4 is: As soon as Gantry fully supports J4 and probably this will happen as soon as J4 is stable which currently is not the case.

I understand.
I want to use it with Grav.
:)

**Comment by mahagr** [comment]
I believe it'll be supported in Grav, too, at least to some extend.
