### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by pau1a** [gantry/gantry5#2526]
Hi all,

Are there any instructions anywhere for running a build from gantry 5 source. Lets say I want to build an installable archive for Joomla from the repo and also modify Hydrogen & or Helium for Joomla then build from source. Ive cloned the repo to my machine and see gulp files but don't see any pointers as to build?

**Comment by mahagr** [comment]
There is a tool called [hebe](https://github.com/rockettheme/hebe), which we use to symlink everything in the right place.
