### ISSUE TITLE
5.5.0-dev - runaway recursive issue persists

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2527]
I accept this is not the correct thing to be doing but it is an issue that comes up in the forum from time to time and it's not alway obvious what the cause is. Therefore I think 5.5.0 should more gracefully handle this use case and issue an error message.

Basically, in G5 menu editor, if you have a menu called "mainmenu" and then you add a child particle to a menu item which itself is a menu particle that uses "mainmenu" then you are creating a recursive loop that eventually runs out of memory when rendering on the frontend. I'd like to see an error message on the front end where the menu would normally be rendered (along the line of our "error rendering particle" error message that now states "error rendering menu, recursive menu loop detected".

**Comment by marktaylor46** [comment]
Ok, well at least it doesn't break anymore although I would have expected the message to occur earlier than it does. as it doesn't appear until you get to level 4 at least.

Nevertheless the original recursive issue is fixed and it is now very obvious what a user has done wrong.

confirmed fix.

**Comment by mahagr** [comment]
There's really no way to know if the same particle is being called from another particle, so instead, I had to just add a limit to how many you can nest.

**Comment by marktaylor46** [comment]
Ok understand - it's much better than it was and at least doesn't break anymore.
