### ISSUE TITLE
5.5.0-dev Identifier "theme" is not defined

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2528]
Clean installation of Joomla 3.9.10 added Gantry 5.5.0 dev and added Helium 5.5.0 dev. Made Gantry default the default theme and assigned "home" outline to "home menu item. Every thing seems ok until you log out of backend and log back in again... then you get the above error
![2019-07-25_14-05-16](https://user-images.githubusercontent.com/11683218/61876809-9dd16380-aee5-11e9-8ab4-c1f71920a8bb.png)

**Comment by marktaylor46** [comment]
![2019-07-25_14-09-47](https://user-images.githubusercontent.com/11683218/61876968-f274de80-aee5-11e9-85e5-045c5950b5b6.png)

**Comment by kat05** [comment]
I can confirm this issue also on Joomla 4 Alpha 10.

**Comment by mahagr** [comment]
Fixed.
