### ISSUE TITLE
5.5.0-dev - JS error when trying to add module to menu item

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2529]
In the G5 menu editor on Joomla 4 Alpha 10, I tried to add a module to the Home menu item. I am able to pick a module but when I hit Apply, a JS error shows and nothing happens.

TypeError: element.parent(...) is null main.js:5283:51

![g5_element_paremt](https://user-images.githubusercontent.com/5719486/62121955-f11c2b00-b2c4-11e9-9a62-c0305f29fc22.jpg)

**Comment by mahagr** [comment]
@kat05 Seems to work for me now. :)

**Comment by mahagr** [comment]
I found a bug in JS loading (B/C break), should be fixed now.

**Comment by kat05** [comment]
Yes, fine now, can be closed. :)
