### ISSUE TITLE
disabling Quick Icon - Gantry 5 does not disable update messages

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#253]
i've got gantry/hydrogen hebe linked and i keep seeing the update message for hydrogen, for example in the callisto manager. i also keep seeing a notification about an available update in the joomla control panel.

disabling the Quick Icon - Gantry 5 plugin does not seem to remove the messages though. since hydrogen is part of gantry, i would think it would disable that message?

![g5_update](https://cloud.githubusercontent.com/assets/5719486/7637167/94c59a12-fa31-11e4-999d-418b68afe61f.jpg)

**Comment by mahagr** [comment]
Only affects symbolically linked installations; will likely fix it in another way.

**Comment by w00fz** [comment]
This is no longer an issue since we moved to Travis and all the versions show as `@version@`. No update bar (in G5 admin) will show anymore.
