### ISSUE TITLE
Timestamp Query in Development mode

### ISSUE THREAD

**Issue by pnutster** [gantry/gantry5#2531]
@thexmanxyz 

Requesting to have the timestamp setting to work in development mode: 

Currently in development it will allways show timestamp despite the timestamp setting - see: http://screenshots.blueoceanyyc.com/c674954135bb - Main reason for removal of timestamp: we have multiple people working on the site and custom (s)css files. There are different methods used of “live preview” - Using Espresso.app - Codekit etc. Some of those apps can work with files with a query parameter in the files, other can’t - therefor a solution without a query parameter / timestamp would be the best solution for us.

file in question: /plugins/system/gantry5/gantry5.php line 248 to 252

Suggested code:

`        if ($this->params->get('asset_timestamps', 1)) {
            $age = (int) ($this->params->get('asset_timestamps_period', 7) * 86400);
            Gantry\Framework\Document::$timestamp_age = $age > 0 ? $age : PHP_INT_MAX;
        } else {
            Gantry\Framework\Document::$timestamp_age = 0;
        }`

**Comment by thexmanxyz** [comment]
@mahagr We already talked briefly about the default behaviour (force `asset_timestamp` in development mode). However I will restate the question and also add the formatted code of @pnutster to this answer as well (to be easier readable).

Do we really need to force `asset_timestamp` in development mode without any possibility to disable the timestamp? I see no actual reason why to restrict this setting in development mode. We can just remove the mode check and the default behaviour should still be the same. Any reasons why to FORCE the `asset_timestamp` in development no matter what value `asset_timestamp` has?

```PHP
if ($this->params->get('asset_timestamps', 1)) {
  $age = (int) ($this->params->get('asset_timestamps_period', 7) * 86400);
  Gantry\Framework\Document::$timestamp_age = $age > 0 ? $age : PHP_INT_MAX;
} else {
  Gantry\Framework\Document::$timestamp_age = 0;
}
```

**Comment by mahagr** [comment]
Related to #2330

I think it would be better to fix both of these by adding 2 new configuration options.

**Comment by thexmanxyz** [comment]
@mahagr What would be the two new added configuration options? Because my suggestion above just changes the behaviour and would not require a new option! Just want to know for the case that I prepare a PR and that we have it written down here within the issue.

**Comment by mahagr** [comment]
I just think it would be more convenient to have two different configurations depending on if you're developing or not, kind of what Grav has built-in. But I guess you're right, we could just use the same configuration regardless of in which mode you are in and just force you to hit force reload if you do these kinds of changes. They aren't that common, anyway... And if you want not to do that, just change the setting, which isn't that hard.

**Comment by thexmanxyz** [comment]
@mahagr You out of curiosity so the solution you proposed would result in three asset timestamp configuration options?

`asset timestamp development`
`asset timestamp production`
`asset timestamp SCSS` - considering #2330 

Thanks for integrating this feature request!
@pnutster your requested feature is now available in the latest release!

**Comment by pnutster** [comment]
Thanks!

**Comment by mahagr** [comment]
@thexmanxyz Yes, basically have 3 options for the different use cases.

**Comment by thexmanxyz** [comment]
@thexmanxyz Thanks for clarification. I already checked how to implement the differentiation between `development` and `production`. I need to verify where the SCSS thing happens that is something that I did not look into in detail. I keep the notification EMail open and prepare a PR as soon as I get on it.

Do you have a reference where the SCSS thing is handled? So I wouldn't waste time searching. You probably know better where to look

**Comment by thexmanxyz** [comment]
@mahagr @thexmanxyz Thanks for clarification. I already checked how to implement the differentiation between `development` and `production`. I need to verify where the SCSS thing happens that is something that I did not look into in detail. I keep the notification EMail open and prepare a PR as soon as I get on it.

Do you have a reference where the SCSS thing is handled? So I wouldn't waste time searching. You probably know better where to look

**Comment by mahagr** [comment]
SCSS just uses the same `url()` method and is in:

https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Component/Stylesheet/Scss/Compiler.php#L118

Third parameter = 0 will disable the asset timestamps.

**Comment by thexmanxyz** [comment]
@mahagr Thanks for pointing in the right direction, that is indeed very useful. Keep you updated on the PR!
