### ISSUE TITLE
Question | TWIG: Joomla Finder and Tags 

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2534]
@yellowwebmonkey @mahagr @newkind 

Is there a way to filter Joomla articles with the `joomla.finder()` by tag or alternatively return the tags with the article object? By default the objects returned do not contain the tags as array / attribute, checked with `dump(...)`. However there is a field `["show_tags"]=> string(0) ""`. I tried messing with that field as an option parameter but that didn't work. Some hint would be highly appreciated. Thanks!

I added a screenshot to show what field within a Joomla article I mean / target.

![grafik](https://user-images.githubusercontent.com/17965908/64416233-1a379480-d097-11e9-834e-e53ad7063a7e.png)

**Comment by mahagr** [comment]
Unfortunately, tags are not supported by the finder.

**Comment by thexmanxyz** [comment]
@mahagr @yellowwebmonkey Are there any plans to implement this feature within the finder or possibility to see this coming at some point in the future? Because there is a demand to fetch articles by their tags.

It would be great to at least have the option to fetch them by a method like:
`finder.tags(['tag-a','tab-b','tag-c'], match_all = true)`.

`.tags([tag_array], 'match_all')` ... it would be useful to have a second parameter which defines whether all tags (`true`) should be matched or any of the passed tags (`false`).

**Comment by mahagr** [comment]
There is a feature request for this: #1631

I would love to implement this soon, but for me getting Joomla 4 support and menu fixes done are more important at this moment.

If someone likes to look into this (mostly if there's a way to use Joomla tags by some API), I would love to hear about it.

**Comment by thexmanxyz** [comment]
@mahagr I completely missed the #1631 feature request. In the meanwhile we have a working PR for this FR so I will close this issue because it is not needed any more and everything discussed / outlined here should be working with #2561.
