### ISSUE TITLE
Disable caching for a specific particle

### ISSUE THREAD

**Issue by egloffmark** [gantry/gantry5#2535]
Dear all I have the issue that when I enabled the production mode / cache for the Gantry 5 in the menu, my particle which has some random slideshow will no longer be random when I reload the page. I assume its twig will no longer be executed and is somewhere get cached? Exists therefore an option that I can disable the caching for a certain particle?

example the "gantry.myFunctions.shuffle()" is a custom function which will call the shuffle() function of PHP and shuffles an array.

` {% set items = (particle.randomize ? gantry.myFunctions.shuffle(particle.items) : particle.items) %} `

In theme.php
`class MyFunctions {
    public function shuffle($list) {
        shuffle($list);
        return $list;
    }
}`

**Comment by mahagr** [comment]
Remove these lines from your particle:

https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/particles/social.yaml#L6-L8

If you're using it as a module, you need to disable caching from the Joomla module.
