### ISSUE TITLE
Problem adding new sample items

### ISSUE THREAD

**Issue by estanis3000** [gantry/gantry5#2537]
Hello! I am using Gantry 5.4.29 in joomla, and working with particles, specially with sample content particles,
on settings(cogwheel) in the bottom I want to add new items on Sample Item button(+ button), but it does not work, I can not add nothing.
could you help me please?

![sample content problem](https://user-images.githubusercontent.com/54909344/64495680-94684480-d262-11e9-96eb-d7183f063641.jpg)

**Comment by mahagr** [comment]
@estanis3000 It looks like we do not have sample content particle, where did you get that from?
