### ISSUE TITLE
template/custom/html doesn't override template/html folder

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#2543]
Overrides in template/custom/html don't override overrides in the template/html folder. This is supposed to work according to http://docs.gantry.org/gantry5/advanced/customizing-theme-files

**Comment by marktaylor46** [comment]
The template html folder is for Joomla overrides of core Joomla (as designed by Joomla) - therefore this is the correct location for a Joomla override fil;e. I checked the documentation and I coulnd't find anywhere that implied /custom/html should work - so could you provide a screenshot of the part that you are referring to please?

Regards, Mark.

**Comment by topwebs** [comment]
![FireShot Capture 050 - Customizing Theme Files - Gantry Docu_ - http___docs gantry org_gantry5_adv](https://user-images.githubusercontent.com/1662945/65041217-d9a00c80-d91b-11e9-87eb-223d534933ca.jpg) from link above.

"Any files located in subdirectories of the directories listed below would also be added to the custom directory in order to override a file stored within. For example, scss/hydrogen/_core.scss would be copied and modified in the custom directory as custom/scss/hydrogen/_core.scss."

html is a listed subdirectory. If this is wrong, the documentation should be changed.

**Comment by marktaylor46** [comment]
Docs are misleading I agree - I've had this confirmed that it's not possible to override a Joomla html override by putting a html folder in the custom folder. I've now done a pull request and updated the docs.
![2019-09-17_15-35-39](https://user-images.githubusercontent.com/11683218/65051358-e561f200-d960-11e9-80e7-90d462168476.png)

**Comment by mahagr** [comment]
Docs updated
