### ISSUE TITLE
Problem after upgrade  5.4.30

### ISSUE THREAD

**Issue by MarcoGiuliani89** [gantry/gantry5#2547]
After upgrade I have problem with two Content Array.
In the first one I try to load all post of 1 cat. in the second one I load a single post.
After the upgrade I see: **Error** while rendering contentarray particle.
(Since upgrade was all right)

Thank you for help!

**Comment by mahagr** [comment]
In the live site, just install Gantry 5.4.29 back (you can find it from releases tab here ^).

In the test site try enabling debug mode to see what it is.

**Comment by MarcoGiuliani89** [comment]
I already have debug enabled but I only see this message in the two particles.
"**Error** while rendering contentarray particle"

**Comment by simmonsr** [comment]
Are you using WordPress?

**Comment by mahagr** [comment]
are you also using development mode in gantry?

**Comment by MarcoGiuliani89** [comment]
Yes WordPress, debug true and development mode

**Comment by simmonsr** [comment]
Ok, just pushed a fix for this. My fault, sorry.

**Comment by MarcoGiuliani89** [comment]
All right!
Thank you so much!
