### ISSUE TITLE
Gap between main menu items

### ISSUE THREAD

**Issue by essiele** [gantry/gantry5#255]
The gap between a main menu item with a `g-menu-parent-indicator` and the menu item to the right of it is wider than normal... by at least 2px.

**Comment by kevlardev** [comment]
Yes, this was due to the text align that was centering the icons which makes sense in most applications but for a horizontal menu (atleast in ltr direction) it makes more sense for them to be aligned right to the edge of the padding of the li. I'll get this fixed up for uniformity.

**Comment by essiele** [comment]
Cool! Thanks!
