### ISSUE TITLE
jQuery does not load in the correct place for G5 for Wordpress Helium theme, also it loads only on the homepage

### ISSUE THREAD

**Issue by Mohika** [gantry/gantry5#2552]
How do I load jQuery in the head instead of the above </body> tag in G5 for Wordpress ... Some plugins won't work as they load their scripts that use jQuery in the head tag and therefore load before it.

Also for some reason, the theme only loads jQuery on the homepage .... I am talking about default jQuery that is loaded by Wordpress '/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp' .. its Helium theme. 

Jquery needs to load first in the head in order for the plugin script to work.

**Comment by mahagr** [comment]
Loading jQuery is handled by WP (Gantry just asks it to load it), you likely need to override/set something in WordPress in order to make it load in the head.

**Comment by Mohika** [comment]
There is no such setting in Wordpress. Try to create any script that uses jQuery and load it in the atom. even if you save it to load before the </body> tag it will load just above the jQuery. This is very new issue, it wasnt like this before.

**Comment by mahagr** [comment]
Every site I have, jQuery is at the header. Something in your site must be messing up this, calling header hook too early.
