### ISSUE TITLE
some errors are not displayed even though development mode is enabled

### ISSUE THREAD

**Issue by kutoman** [gantry/gantry5#2556]
In cases of some type of errors blank pages are shown instead of a error report. As soon as I deactivate the gantry 5 framework plugin the error report gets displayed after a page refresh:

![grafik](https://user-images.githubusercontent.com/5825645/67483770-cabd2000-f666-11e9-8f5f-19263f9943b7.png)

This makes debugging a tough job. This issue is not about the error itself (as it is caused outside of the gantry files) but it is about the fact that the error displaying is blocked despite of an enabled development mode.

**Comment by mahagr** [comment]
I'm not sure why this would happen as while Gantry does have its own error handler, it should only be active when Gantry is active (either in frontend or Gantry admin). Also, it should be showing you full traceback in [Whoops](https://github.com/filp/whoops), not like this.

**Comment by kutoman** [comment]
@mahagr I'm not sure if I got misunderstood. The error gets displayed like you see in the screenshot only if the gantry plugin is deactivated. But as you stated, I would expect a Whoops based error displaying when the plugin is activated. Unfortunately on some errors it's just a blank page I can look at.

**Comment by kutoman** [comment]
as a side note, I'm not sure if this is relevant, but as you can guess from the stack trace, my code is in a wordpress mu-plugin. The error is caused there

**Comment by mahagr** [comment]
The error handler from Gantry is being activated quite late and the error handler is only set to catch errors which happen inside Gantry or the theme. I'm guessing that the error is not caught by Whoops because of the restriction and is forwarded to the next error handler. I'm not sure why the next error handler would not handle it, though.

**Comment by kutoman** [comment]
I noticed that the error gets displayed when I switch to the production mode (it is not in Whoops style though). But in development mode (like in the image below) I get the white screen. Shouldn't be this vice versa?

![grafik](https://user-images.githubusercontent.com/5825645/70352407-61d2e580-186b-11ea-9f2b-2c1a3989eed7.png)

**Comment by newkind** [comment]
In order to Debug work with G5 you need to have enabled Debug mode in Gantry5 settings and WP_Debug in the wp-config.php
