### ISSUE TITLE
[GRAV] Gantry 5 Not Showing Assignments for Pages in Grav Beta 1.7

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2557]
See screenshot. Page Types are shown, but not Pages themselves:

![EHogiKYX0AIivCo](https://user-images.githubusercontent.com/5002814/67498527-32627380-f645-11e9-8c94-6bb4405a8771.jpg)

**Comment by simmonsr** [comment]
fix confirmed

**Comment by simmonsr** [comment]
pages are showing, but not saving

**Comment by mahagr** [comment]
Ok, there seems to be a bug in Grav 1.7.

**Comment by mahagr** [comment]
Not a bug, but really a bad call in admin. Might fix some language assingment issues as well.

**Comment by mahagr** [comment]
@simmonsr Can you test?

**Comment by simmonsr** [comment]
confirm fixed

**Comment by lesar** [comment]
I'm learning Gantry 5 on Grav.

On Grav v1.6.25 - Admin v1.9.14 -  Gantry 5 Framework v5.4.34 - Theme: Hydrogen (v5.4.34 / g5_hydrogen)

Not Showing Assignments for Pages on settings 
![Schermata del 2020-05-22 14-32-56](https://user-images.githubusercontent.com/6347403/82668072-4c931d00-9c39-11ea-959e-b7ac09b657e9.png)

Have the post to be reopen or have I misunderstanding something?
regards,  
Leonardo

**Comment by mahagr** [comment]
Yes, base outline does not really exist, it just sets defaults for everything else.
