### ISSUE TITLE
Little issue in Hydrogen on Menu setting

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#256]
best explained with a pic, minor issue but wanted to mention it. :)

![g5_hydrogen_menu](https://cloud.githubusercontent.com/assets/5719486/7640224/89e96fe0-fa47-11e4-977d-99906e350441.jpg)

**Comment by essiele** [comment]
Maybe it's just a case of getting rid of the word "Standard"...

**Comment by w00fz** [comment]
Cheers

**Comment by JoomFX** [comment]
Yeah, that's why I asked a week ago if we can overwrite Admin CSS :)
The `settings-param-title` field has a "max-width" of 150px and the `settings-param-field` has a "margin-left" 150px. It would be great if we can overwrite Admin CSS, if needed :)

**Comment by mahagr** [comment]
Where was that issue? I think it was a side comment on something else, can you make it as own issue @JoomFX so I don't keep forgetting it.
