### ISSUE TITLE
5.5.0-dev - g-main tab in Joomla menu editor

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2563]
Please see pic.

On a Gantry 5 custom page menu item, there is an extra tab that should not be there.

<img width="1350" alt="g5_5_joomla4_menuitem" src="https://user-images.githubusercontent.com/5719486/68387614-feb43d00-015e-11ea-859c-81c0b1d1175f.png">

This is on a Joomla 4 NIghtly build from today.

**Comment by mahagr** [comment]
Looks like this is caused by the menu type xml file.
