### ISSUE TITLE
How to remove extra string added to the end of the ".css" file extension

### ISSUE THREAD

**Issue by Pan-E** [gantry/gantry5#2565]
Hello,

My site is built on a Gantry5 template developed by RCAThemes. I am trying to optimize the performance of my site by combining and minifying CSS. 
It's not possible, because the CSS files have the extension "?XXXXXXXX" added dynamically to the end of the .css file extensions (where XXXXXXXX is a string of 8 characters). Here are 3 examples:

link href="/media/gantry5/assets/css/lightcase.css?XXXXXXXX" rel="stylesheet"
link href="/media/gantry5/assets/css/font-awesome.min.css?XXXXXXXX" rel="stylesheet"
link href="/media/gantry5/engines/nucleus/css-compiled/nucleus.css?XXXXXXXX" rel="stylesheet"

The string of 8 characters is the same for every CSS file.

I turned to the template developer for assistance, who, in return, forwarded me to these boards.
How can I eliminate this string of characters "?XXXXXXXX" from being added to the end of the css filename?

Thank you.
Panos

**Comment by mahagr** [comment]
Sorry for the delay.

You can disable those from the Gantry plugin configuration (in all platforms), look for: `Asset Timestamps`.

**Comment by Pan-E** [comment]
Thank you very much Matias!
