### ISSUE TITLE
custom.scss not seen

### ISSUE THREAD

**Issue by volandku** [gantry/gantry5#2566]
Gantry Administration by RocketTheme
Version: 5.4.31 / Released: October 4, 2019
Theme: Fluent (v1.1.3 / rt_fluent)
Joomla! 3.9.13

I created "/custom/scss/custom.scss" file and inserted
```@import "dependencies";

// Base Sizes
$core-font-size:				0.80rem !default;
$responsive-font-size:			0.80vw !default;
$core-line-height:				1.35 !default;
 
// Heading Sizes
$h1-font-size:					$core-font-size + 0.80 !default;
$h2-font-size:					$core-font-size + 0.60 !default;
$h3-font-size:					$core-font-size + 0.40 !default;
$h4-font-size:					$core-font-size + 0.25 !default;
$h5-font-size:					$core-font-size !default;
$h6-font-size:					$core-font-size - 0.15 !default;
```

No reaction at all - development mode on\off, recompile

**Comment by simmonsr** [comment]
Do you have a active Joomla membership? If so please post for support via our forum:

https://rockettheme.com/forum/joomla-template-fluent
