### ISSUE TITLE
Is there any way to render a particle widget from inside a partial view after an AJAX call?

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2569]
Gantry WP
I am rendering a particle widget from inside a partial view, with the help of a 3rd party plugin, which allows to create WP sidebars, assign widgets and render them with a shortcode anywhere.

So, inside my partial view I do: 
`{{ function('do_shortcode','[do_widget id=particle_widget-id]') }}`

That works fine during a normal page load.

But, I am also using that same partial view to prepare HTML after an AJAX call. 
So, I am rendering that view to return html to my AJAX like:

`$html = Timber::compile($templates, array('posts' => $posts));`

The $templates includes my partial view above. The $html is getting created with all my desired content expect that in this case, the function call to the shortcode that is included in my partial view, stops rendering anything.

Is there any way to be able to force the rendering of a particle in a scenario like the above?
Overall, it doesn't have to count on the 3rd party plugin, if there is any other way that will allow me to render a widget particle in any of my views, including the rendering during the AJAX scenario.

Any ideas?

**Comment by joomlabeat** [comment]
For now I created a function that returns the widget output using the do_shortocode function and I am caching this output on a transient during the main page load. 
Then whenever I call this new function either from the main page load or through AJAX, it will return the cached output.

**Comment by mahagr** [comment]
Not sure if this answers to your question, but there's also AJAX support in Gantry itself.

For WP you can take a look at this example:
https://github.com/gantry/gantry5/blob/develop/engines/wordpress/nucleus/particles/contentarray.html.twig#L171-L187

PS: There's more code in the file to handle the parameters.
PPS: On your issue, I have no idea what could be going on... Maybe something isn't initialized?
