### ISSUE TITLE
Add ability to rename Outlines from any Panel

### ISSUE THREAD

**Issue by dalewj** [gantry/gantry5#257]
I find the changing of layout names to be a bit limiting. As in there is only 1 place you can change the theme name at all. This is in Configurations Tab. I would like to request feature that lets me change the name of the theme in the actual theme. While im building the theme i like to change its name (As i do in a regular Joomla article or module) on the same page i am making the changes on. It seems we are adding too many steps of work to get a simple thing done.
![screenshot 2015-05-14 12 51 34](https://cloud.githubusercontent.com/assets/12450902/7641394/7fe2f43e-fa57-11e4-9181-59ff5034a19f.png)

**Comment by w00fz** [comment]
You can change the template name by editing the `theme.yaml` file, that’s really all there is to it. Is this what you were looking for?

**Comment by dalewj** [comment]
I want to be able to changing it in this screen.  i dont want too many extra steps.  thats why a feature request

**Comment by w00fz** [comment]
You cannot change it in the screen and we have no plans on having the ability to change the template name from the admin, it's not that hard, just edit the `templates/rt_callisto/gantry/theme.yaml` file and change:

```
details:
  name: Callisto
```

to

```
details:
  name: Yours
```

That is it.

**Comment by w00fz** [comment]
Also if you want a different folder name just rename it, `rt_callisto` to `rt_yours`.

**Comment by dalewj** [comment]
I think your missing the idea.  I want to be able to change Calistro - Books - Officescan   to   Calisitro - Something else in this screen.  We have to have a separate layout for every different page and i need an easy way to make changes to those names.  I want to do them on the fly while i edit.  Not talking about changing the whole calistro name of the template

**Comment by w00fz** [comment]
Ok it wasn't very clear, you just posted a screenshot and left me with some imagination to do :)

**Comment by dalewj** [comment]
hmm i see plenty of words.  funky

**Comment by w00fz** [comment]
We'll implement the feature :wink:, until then you can just go in `Configurations` and rename them from there.

**Comment by w00fz** [comment]
This is now implemented.

https://cloudup.com/c9RSnzIPrCM
