### ISSUE TITLE
page.html.twig issue

### ISSUE THREAD

**Issue by rascasse83** [gantry/gantry5#2571]
Just downloaded the latest stable build from the website (grav-pkg_gantry5_v5.4.31.zip)

And there is a key file present in the nucleus/templates folder which is missing some statements which results in the content of the page not being displayed

The statement in bold is missing

   {% block content %}
    **{{ page.content|raw }}**
        {% endblock %}

**Comment by mahagr** [comment]
Nope, this is intentional. You need to add a particle into the layout in order to display the content.

**Comment by mahagr** [comment]
Also see https://github.com/gantry/gantry5/blob/develop/engines/grav/nucleus/templates/default.html.twig#L4
