### ISSUE TITLE
make layoutmanager a generic Grav core field

### ISSUE THREAD

**Issue by drzraf** [gantry/gantry5#2577]
I'd really like to reuse that [Drag&Drop](https://github.com/gantry/gantry5/blob/master/platforms/common/application/lm/layoutmanager.js) for purposes other than layout management.
Having such a field widget as part of Grav would be a really nice addition.

But maybe https://www.npmjs.com/package/muuri would be a better base upon which restarting.

**Comment by drzraf** [comment]
I implemented mine using gridstack. Closing but I still think it would be a nice addition to Grav.

**Comment by mahagr** [comment]
That's a nice one. I'll bookmark it. :)
