### ISSUE TITLE
array_key_exists() on objects is deprecated - PHP 7.4 Twig Incompatibility

### ISSUE THREAD

**Issue by elverado** [gantry/gantry5#2579]
I am experiencing the following error, preventing a template cache rebuild and site display breakdown on PHP 7.4:

**Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in xxxxxx/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php on line 580**

This let me to this Twig issue: https://github.com/twigphp/Twig/issues/3151 

While I could manually edit the twig files within Gantry 5 to comply, it would not be resilient to other updates. Is there any progress being made to fold this updated Twig into a formal Gantry 5 plugin / theme release?

**Comment by N8Solutions** [comment]
@elverado You need to revert back to PHP 7.3. Gantry 5 is not yet compatible with PHP 7.4

for reference, see @mahagr comment in the G5 Chat.
:point_right: [December 9, 2019 10:31 AM](https://gitter.im/gantry/gantry5?at=5dee06681e0b827cc8c9a693)

**Comment by elverado** [comment]
Understood, thanks for the context. We are fine with keeping this site at 7.3 for the time being.

**Comment by elverado** [comment]
For reference 7.4 is working across our dozen or so plugin heavy sites without issue (heavily monitoring logs; no errors). The few references to array_key_exists() in Twig, which has been patched by them, appears to be the only breaking change. But I understand there to be far more pieces of Gantry than those in use by our site that would need more extensive testing.

**Comment by N8Solutions** [comment]
👍  If you do not need to keep this issue open, please close it when you can.

**Comment by mahagr** [comment]
Basically the main issue is that I cannot just update Twig for PHP 7.4 as it will drop PHP 5.4 support. Same is true for scssphp, which raised the minimum required version (not to mention a few other libraries we use).

I'm currently working on Gantry 5.5 which will raise all the minimum requirements and will work in PHP 7.4 as well.
