### ISSUE TITLE
Menu with an alias of "items" breaks Gantry 5 menu editor

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2582]
Joomla (maybe other CMS too).

If you have a menu item called "items" (doesn't matter what type of menu item) the alias will be "items" too. If you then go to Gantry 5 menu editor you will see an error message "the selected menu is empty" (which it is not). If you then change the alias in Joomla menu editor to "aliasx" or anything else then Gantry 5 menu editor does then work again.

Original RT forum topic https://rockettheme.com/forum/gantry5-for-joomla/282919-cannot-name-menu-items

**Comment by iantrudell** [comment]
Any updates on this?

**Comment by mahagr** [comment]
This has been fixed in upcoming Gantry 5.5
