### ISSUE TITLE
Menu slide out

### ISSUE THREAD

**Issue by siptec** [gantry/gantry5#2583]
When having the menu set at Extended style with menu-item1 > menu-item2 > menu-item3 , the dropdown of the item2 to show item3 requires the user to click on the arrow to expand. How do you make it function on hover. 

I'm afraid users won't know to click on the arrow to expand the menu. Is there a way to use the extended styling and change the onclick function with hover or both?

Saw this javascript solution from Stackoverflow

```
var hoverOrClick = function () {
    // do something common
}
$('#target').click(hoverOrClick).hover(hoverOrClick);
```

Could this be applied to the main.js in Gantry5 ? If so, any help would be appreciated.

**Comment by siptec** [comment]
Never mind... looks like this has been an issue for a long time and will not be addressed. Anyone with long menus or sub-menus would find this function helpful, but I guess there will have to be another answer with a separate development.

**Comment by mahagr** [comment]
Hower won't work with touch devices, which is why most CSS frameworks have already dropped hover menus for good. The best solution would be to make all parent menu items as placeholders so there's only a single click per item.

**Comment by siptec** [comment]
> Hower won't work with touch devices, which is why most CSS frameworks have already dropped hover menus for good. The best solution would be to make all parent menu items as placeholders so there's only a single click per item.

Thanks for the reply mahagr. Wish both hover and click were available, but at least now, I understand why this works that way.
