### ISSUE TITLE
Feature Request - preg_split Twig Extension

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2586]
Today I stumbled over a use case within Twig which would've required to split a string with multiple delimiters. This would require a implementation of `preg_split` as simple function within the Twig Extensions. Is this something that might be useful or required? If so please tell me @mahagr I would do the implementation. I just want to know and clear up if this is something you would like to have within the framework or not before investing time in a PR that will not be accepted.

**Comment by mahagr** [comment]
@thexmanxyz I'm ok for adding this, just check if Grav has this already (you should just copy it).

**Comment by thexmanxyz** [comment]
@mahagr Are you sure Grav already has this functionality? Did not find it :-/. Here is [the link](https://github.com/getgrav/grav/blob/e5cedd074b3c004b4c4d634528e1571febfdf95d/system/src/Grav/Common/Twig/TwigExtension.php) to the respective file in the Grav repository!
