### ISSUE TITLE
Dynamic width for every display size(desktop, mobile..)

### ISSUE THREAD

**Issue by mikajaxxx** [gantry/gantry5#2587]
Hi 
I think there should be dynamic  & fixed width for column based on device display size1
for example i have a logo in my layout with 15% width this value is good on large desktop but in tablet it becomes too small. so i should choose bigger width like 25% but it cause the space between this column and other column become too much ,
 if there be an option to determine width of column based on viewport size it will be great.
this feature already included in many template framework like yootheme pro ...
I hope such option provided for gantry
Best regards

**Comment by mahagr** [comment]
This is not possible with the current grid system without writing some custom CSS by yourself, but it is doable with some SCSS of your own.

**Comment by mikajaxxx** [comment]
Yeah it is easy in SCSS , my point was to add such feature (maybe on next release) for better UX. 
As you know responsive design is priority for web designers and such options give more control .
also a fixed with will be ok for most cases. i mean if the other grid's child could adopt by fixed width of one child, it will do the job.
Best Regards
