### ISSUE TITLE
Assignments menu for posts loading very slow

### ISSUE THREAD

**Issue by JasonRaveling** [gantry/gantry5#2589]
In my test environment, I have disabled every WordPress plugin except for Gantry 5. This issue happened on Helium and Hydrogen. I am unable to load the menu at all with my current database which has thousands of posts. [This screenshot](https://i.imgur.com/uZEArdv.png) shows what loads when I click on the assignments tab. Once I deleted most of my custom fields the assignments menu would load but it takes forever. Even after it has loaded it takes forever for the toggles to be effected.

The option to apply a layout to individual posts seems like it would be a rare case. It would be great if there is a way to enable/disable individual posts from even being loaded on the assignments menu.

**Comment by marktaylor46** [comment]
Same as https://github.com/gantry/gantry5/issues/1279

**Comment by JasonRaveling** [comment]
Thanks @marktaylor46. Also, it looks like there is an option for this. Of course I find it right after posting here. In case anyone else finds this, the option to enable/disable assignments for posts is under wp-admin > Settings > Gantry 5 Settings
