### ISSUE TITLE
back-end **unusable** on  iPad 

### ISSUE THREAD

**Issue by Endehar** [gantry/gantry5#2591]
Hi, just tried Gantry5 for Joomla.

Very interesting framework. but on an iPad the back-end is TOTALLY unusable, especially the layout editor.
Any attempt to click or move an item in the layout editor ends with "duplicating" that item on screen.

Any hints?

**Comment by mahagr** [comment]
Gantry backend has not really been designed for tablets/phones. You're better off using a laptop or desktop to edit the layout.
