### ISSUE TITLE
PHP 7.2+ Error: Cannot use Gantry\Joomla\Object\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by netzgedacht** [gantry/gantry5#2593]
I want to migrate from PHP 7.1 to 7.3 with Joomla 3.9.14, but getting the following message, if I set the configuration of the server to 7.3.

Whoops\Exception\ErrorException thrown with message "Cannot use Gantry\Joomla\Object\Object as Object because 'Object' is a special class name"  

Stacktrace: #0 Whoops\Exception\ErrorException in /libraries/gantry5/classes/Gantry/Joomla/Category/Category.php:14

Any suggestions?

**Comment by N8Solutions** [comment]
Make sure you have updated both the gantry core and your template to the
latest version. Whether you are using gantry 4 or gantry 5, the latest
versions for both are compatible with PHP 7.3.

**Comment by mahagr** [comment]
Yup, this happens in badly outdated version of Gantry.

**Comment by mahagr** [comment]
> Yup, this happens in badly outdated version of Gantry.

**Comment by mahagr** [comment]
Possible reasons:

1) Joomla sometimes stops searching for updates -- if Joomla for some reason cannot get the updates from the server, it can turn off the updates lookup. This can be enabled by manually checking for updates.

2) Joomla installer has (or at least has had) a bug where it does not update files which have bad permissions. This can be fixed easiest by uninstalling the package, but then you will lose the settings. Another way is to try to fix permissions and re-install.

**Comment by netzgedacht** [comment]
Thank you for the answers! Joomla has updatet the theme, but not gantry core. This was badly outdated. I did it manually and now it works! Thanks guys!
