### ISSUE TITLE
Error: Trying to access array offset on value of type int (PHP 7.4.1)

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2596]
Hello,

Testing instructions:
Joomla 3.9.14 or later
PHP 7.4.1
Error reporting to max or dev

Actual result
Display a notice or site is unusable with high level of error reporting
Error: Trying to access array offset on value of type int
File: /classes/Gantry/Component/Assignments/AbstractAssignments.php, line 140

Thanks.

**Comment by N8Solutions** [comment]
@uGE70 Please close this ticket and review the following ticket https://github.com/gantry/gantry5/issues/2579 as this has already been referenced. You need to revert back to PHP 7.3 or lower as PHP 7.4 is not yet supported in Gantry 5.

**Comment by uGE70** [comment]
Ok, sorry, I reviewed the past issues but I missed this information.

**Comment by mahagr** [comment]
I'm actually going to keep this open to make sure I have fixed it.

**Comment by mahagr** [comment]
See #2618
