### ISSUE TITLE
[Helium Theme] Titles are tied to Body Font and not Title Font.

### ISSUE THREAD

**Issue by binaryglyph** [gantry/gantry5#2599]
This was an issue that was supposed to have been resolved awhile back. Curiously the same behavior exists in 5.4.32. Titles are still tied to "Body Font" instead of "Title Font" in the Helium Theme.

**Comment by blizam** [comment]
You adjust that in /scss/helium/styles/_typography.scss

Change:

h1, h2, h3, h4, h5 {
font-family: get-font-family($font-family-default);

to:

h1, h2, h3, h4, h5 {
font-family: get-font-family($font-family-title);

**Comment by mahagr** [comment]
Looks like Hydrogen is using title font, helium isn't.

**Comment by jbonlinea** [comment]
Drap,
same issue here
thank's for the fix
