### ISSUE TITLE
Not finding custom css/less editor

### ISSUE THREAD

**Issue by edgibson** [gantry/gantry5#26]
Where is the admin side editor for the default custom-template.css file?

**Comment by mahagr** [comment]
We haven't done it yet. And the file location and name has changed a bit, it's now /custom/scss/custom.scss

**Comment by FrugalGeek** [comment]
We have a document about the current process. http://docs.gantry.org/gantry5/tutorials/adding-a-custom-stylesheet It's pretty manual for now, but having a backend solution is in the list.

**Comment by mahagr** [comment]
Documentation will help for sure, but I'm keeping this one open for now to remind be to add our own editor to making modifications.

**Comment by gmng** [comment]
There is a typo in:  "/custom/css/"   "/custom/scss/"
"To do this, navigate in the directory structure to (site root)/templates/(template directory)/custom/scss and create a file called custom.scss if one doesn't already exist. If the -------->>>>>   /custom/css/ <<<<<-----------  directory doesn't exist, you will need to create that, too. If it already does, just open it and make your additions/changes directly to the file."

**Comment by w00fz** [comment]
Thanks! I assigned @FrugalGeek to this.

Just so you know, we have a [docs repository](https://github.com/gantry/docs) as well.

**Comment by FrugalGeek** [comment]
Documentation is corrected. Thanks for finding that!
