### ISSUE TITLE
Gantry Menu Save Fails on Grav: PageLegacyTrait::move(): Not Implemented Error

### ISSUE THREAD

**Issue by thekenshow** [gantry/gantry5#2601]
I've been developing a new site with Gantry latest on Grav 1.7-rc6. After relocating a few user/pages using the file system, and changing their `visible` status to `true`, I can't save the Gantry menu configuration. 

Instead, clicking Save throws the error `Grav\Framework\Flex\Pages\Traits\PageLegacyTrait::move(): Not Implemented`. 

![Screen Shot 2020-02-20 at 5 19 43 PM](https://user-images.githubusercontent.com/998832/74994014-d7863080-541a-11ea-9c54-e04145e7b468.png)

The menu was working in 1.6 for sure, and I believe in some earlier 1.7 rc versions.

**Comment by mahagr** [comment]
Fixed in Grav 1.7.0-rc.10.
