### ISSUE TITLE
joomla - g5 / hydrogen - can't access level 2 menu items from level 1

### ISSUE THREAD

**Issue by nzimas** [gantry/gantry5#2602]
I've got a menu 3 levels deep.
The dropdowns from level 0 work as expected.
Nonetheless, level 1 menu items with offspring do not show any arrow indicating the presence of level 2 children.
Moreover, when I click on the level 1 menu item, which is a mere separator, nothing happens.

I've revised the relevant settings on all menu items involved. 
In all cases, the "Disable Dropdown" option is not ticked.

<img width="884" alt="Screenshot 2020-02-24 21 23 11" src="https://user-images.githubusercontent.com/6955694/75184588-4cc07100-574d-11ea-946b-ff5df702867c.png">
<img width="616" alt="Screenshot 2020-02-24 21 22 25" src="https://user-images.githubusercontent.com/6955694/75184593-4fbb6180-574d-11ea-8743-2c0422ceb728.png">

Environment:

Gantry 5.4.32
Hydrogen 5.4.32
Jooma 3.9.13

**Comment by mahagr** [comment]
Make sure that your menu particle configuration is set to display more than 2 levels.

**Comment by nzimas** [comment]
Max Levels in the Menu particle settings is set to 10.

<img width="571" alt="Screenshot 2020-02-26 14 51 59" src="https://user-images.githubusercontent.com/6955694/75346615-c40a1800-58a7-11ea-9008-1ca0f88820d2.png">

**Comment by nzimas** [comment]
Please discard my previous message.
Max Values was in deed set to 2 in the particle settings,
The screenshot shown in the comment above is from the Particle Defaults.
