### ISSUE TITLE
Does Gantry 5 support Grav Modular template overrides?

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2603]
Hi there!
I'm facing strange problem.
I had a working website with Grav modular overriden templates.
As a next step I decided to rebuild it with a `Gantry 5` framework.
Well, the home page does work, but strange thing happen with other pages.

For instance, I have a `Main services` page. Page template is set to `Modular`.
And it have some of code:

    ---
    title: Test
    content:
        items: '@self.modular'
        order:
            by: default
            dir: asc
    body_classes: services
    menu: Test
    slug: test
    process:
        markdown: true
        twig: true
    onpage_menu: false
    background: test.jpg
    ---

    {% set image = theme_url ~ '/images/' ~ page.header.background %}
    <div class="static_header" style="background-image: url('{{ image }}'); background-position: 0% 40%" >                                           
    	<div class="overlay"> 
    	</div>
    </div>

This piece of code renders perfectly.

Next child modular page `_intro`:

    ---
    title: Services
    published: true
    menu: MenuName
    image_align: left
    ---

    <section class="service-container container-fluid">
        <div class="row no-gutters">
    	{% for image in page.media.images %}
            <div class="col-sm-12 col-md-12 col-lg-6 col-xl-3 py-2">		
                <div class="card card-body h-100">
    				<div class="service-feature-box">
    					<div class="service-media">
    						{{ image.cropResize(806,582).html }}						
    					</div>				
    				   <div class="service-body">
    					 <div class="custom-heading centered">
    					   <h4>{{ image.meta.heading[grav.language.getLanguage] }}</h4>            
    					 </div>	
    					<p class="text-justify">{{ image.meta.description[grav.language.getLanguage] }}</p>                  
    				   </div>
    				</div>
                </div>		
            </div>
    		{% endfor %}
        </div>
    </section>

and it features custom page template, called `services.html.twig`.
here is a code:

    <section class="container-fluid">
	   <div class="row no-gutters">
		   <div class="col-md-12"> 
			   <div id="content-slide">
			  <div class="slideme">
				
			 <div class="showcase-inner">
				  {{ content }}
			 </div>
			  
				</div>
			</div>
		</div>
	</div>
</section>

As a result the modular child page outputs plain `html`. Do I'm missing something?

A **update**:
in `services.html.twig` I’ve changed `{{ content }}` to `{{ page.content|raw }}`
Now it renders `html` except `<img>` but with tag's inside content.
I had a text with `<b></b>` tags, so the text doesn't change it's weight, it just renders the `<b></b>` tags inside...

**Comment by mahagr** [comment]
Yes, Gantry automatically turns on autoescaping meaning that you need to put `|raw` to everywhere you're going to render HTML content. This feature will be later forced on in Grav itself, but for now I recommend you to start without Gantry and fixing all your template files with twig autoescaping turned on. When you have all of it working, switch the template to use Gantry.

PS. you need to use the `|raw` filter also for your image HTML output :)

**Comment by 01Kuzma** [comment]
Thank you for you answer!
In `twig` I turn on the `raw` filter: with `{{ content|raw }}`
But data coming from `markdown` is also autoescaped...
How it could be solved in Makrdown?
If I display them in such way:
```
{% for image in page.media.images %}
    {{ image.cropResize(806,582).html }}							
{% endfor %}
```

Thank you!
