### ISSUE TITLE
Grav Content particle doesn't accept more than one category

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#2608]
Similar to  this issue:
GRAV : As soon as you add more than 1 category, particles break #2361
I used the "GRAV Content" particle coming preinstalled with Helium Theme, but it works ONLY with one category. It looks like GRAV/Gantry can be used only with one blog...
The bug is still there after nearly two years...any solution/updating about this issue?

**Comment by beamaria** [comment]
Any developer can help??

**Comment by beamaria** [comment]
Hello again! Can anyone propose a solution for this problem??  Because there is no point in releasing a particle which is working only with one category.... Moreover this is really an old issue!
If there isn't a solution, it could be probably fair warning users that Gantry 5 in GRAV works with noticeable restrictions....

**Comment by mahagr** [comment]
It is not a limitation of Gantry, it is a limitation of Grav. Collections in Grav do not support OR compare which makes it impossible to add support without implementing it in Grav.

Duplicate to existing issue.
