### ISSUE TITLE
page pushed down without raison. 

### ISSUE THREAD

**Issue by sistaidan** [gantry/gantry5#2609]
hi,
First I must say it'ts not my native language. Please try to use simple vocabulary in your answers, for my understanding.
On a fresh install hydrogen/gantry5 without any other plugin I face a problem with this css code : 
#g-page-surround {    min-height: 100vh;}
in gantry5/engines/nucleus/css-compiled/nucleus.css
The same on parent or child theme. Result : All my sites are pushed at the bottom of the screan, just like there were an invisible block at header. 

Version de WordPress : 5.3.2 multi-site
Version de PHP/MySQL : 7.1.33 / 10.2.31
Thème : hydrogen gantry
Host : Apache

**Comment by petergriffiti** [comment]
I also have this problem. 
Any help please., I like the idea of Gantry but fining it difficult to get working. I tried it with Grav and the kept crashing when I activated th theme on it.

**Comment by simmonsr** [comment]
What specific error are you receiving?

**Comment by sistaidan** [comment]
Thank you for your answer  and excuse my bad English in advance. It’s not my native language.

While waiting for you answer, I found this line of code is causing the big white space in header. (see attached img 1)

#g-page-surround {min-height: 100vh; } (it’s new css code for me never used it before.)
I fixed it by replacing it by :
#g-page-surround {min-height: 0; } (the only way I found to overwrite it)

If you have a better idea, it’s welcome ;

But the biggest problem I’m having now is that the main-menu  (called « base ») is not stable, impossible to keep it in place.

It appears for few minutes and without Reason it desappears from Particle Defaults panel.
So I can’t select it anymore.
As you can see in img 2, this main-menu exist but in gantry board I can’t see it to select it (img 3).

this seems to be the major problem preventing me from using Gantry.

It’s just like gantry doesn’t support a main menu. It keeps desappearing after few seconds.
All other menus are viewable but not the main one ???

How can I fix it ?

Thank you for your help. I stopped working on it for a month  ‘cause don’t want to use another Framework or theme.  Really love gantry ! best one according to me, didn’t find better.

Best regards
nadia






De : simmonsr<mailto:notifications@github.com>
Envoyé le :vendredi 17 avril 2020 18:17
À : gantry/gantry5<mailto:gantry5@noreply.github.com>
Cc : sistaidan<mailto:nedh@live.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [gantry/gantry5] page pushed down without raison. (#2609)


What specific error are you receiving?
