### ISSUE TITLE
Switching Layout from the Load popover should allow to preserve the Particles

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#261]
When switching between Presets / Outlines it needs to offer the possibility to not loose all the particles in the current Layout but rather just update the structure.

**Comment by w00fz** [comment]
The initial implementation is in place. Looks like this:

![preserve-particles](https://cloud.githubusercontent.com/assets/11734/7644277/8ab609aa-fa57-11e4-8fc9-d4f460696937.jpg)

**Comment by adi8i** [comment]
Good one !

**Comment by mahagr** [comment]
Oh, warning message isn't showing up yet, reopening... 

@w00fz We need to talk about that when you come back.
