### ISSUE TITLE
How can I build my own field type input.pathpicker for a particle?

### ISSUE THREAD

**Issue by derhelli** [gantry/gantry5#2611]
I wrote some particles that read file names and file contents from server directories (e.g. images/mainslider) and format them and display them in the frontend. Currently I use the input type input.imagepicker or input.filepicker. The disadvantage of both is that the user always has to click on a file. I would much rather have an "input.pathpicker" which only returns the path to the directory. Is it possible to write an own type input.pathpicker?

**Comment by blizam** [comment]
The user has to click on something either way... with either of those existing inputs you can pretty easily get the path that the file is in.

You'd have to create a new YAML field with it's own backend experience where a user clicked on a folder, then save that path.

You could look at the filepicker as an example... or possibly even extend it like the Image picker does... to make it a "path picker"

https://github.com/gantry/gantry5/blob/develop/platforms/common/templates/forms/fields/input/filepicker.html.twig
