### ISSUE TITLE
PHP 7.4.x - Wordpress - G5 admin styling broken and particle settings all broken

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2613]
If you attempt to use PHP 7.4.x with WP G5 then the styling of admin goes awry and the particle settings panels do not show. The reasons for this is the HTML tag and Classes on the tag are being run into each other in the html output rendering them invalid markup. For example:
```<li class="active">``` actually renders in the page as:
```<liclass="active">``` when using PHP 7.4.x

Here are example screenshots:
![2020-03-25_09-37-36](https://user-images.githubusercontent.com/11683218/77551268-070cda80-6eaa-11ea-9e84-58a367e8e6bc.png)
![2020-03-25_09-38-49](https://user-images.githubusercontent.com/11683218/77551282-0e33e880-6eaa-11ea-8ca8-ab4b3c326272.png)

**Comment by mahagr** [comment]
@marktaylor46 It was a bug in Twig.

I had to raise minimum requirements
* PHP 5.5.9 (Twig requirement)
* WordPress 4.9.8 (Timber requirement)

**Comment by marktaylor46** [comment]
Huh? the site that had this error was using PHP 7.4.x so it met that minimum anyway?

**Comment by mahagr** [comment]
I mean that from now on those are the minimum requirements. They used to be PHP 5.4 and WP 4.4.

**Comment by marktaylor46** [comment]
Ok so why did I have the error on PHP 7.4.x? You mean that there is some sort of test that uses different twig versions?

**Comment by mahagr** [comment]
Because of Gantry was stuck with old version of Twig and Timber because of minimum PHP requirements. The libraries could not be updated to versions which work in PHP 7.4.

**Comment by marktaylor46** [comment]
Ah ok, I get it - you've had to update the TWIG version in Gantry to one that is compatible with PHP 7.4.x and as a result of that the new version of TWIG has a minimum PHP requirement of PHP 5.5.9 which means that Gantry also must stipulate that minium PHP requirement too.

**Comment by mahagr** [comment]
Yes, my comment was more of FYI that Gantry will not work anymore on older versions of PHP and WP.

Twig requires 5.5.0, but those early versions are buggy and not much used, so I raised the requirement a bit more.

**Comment by marktaylor46** [comment]
Thanks @mahagr I get it now :)
