### ISSUE TITLE
ERROR: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by ipr-paolo** [gantry/gantry5#2618]
I have MAMP on Mac OS X Mojave and I have Joomla 3.9.16 and I install gantry 5 Helium RocketLauncher with joomla and Gantry 5 but as I try to save layout I got the error: "Trying to access array offset on value of type null"
I enclose the error I got that cause impossible to use gantry.
[test - Administration.pdf](https://github.com/gantry/gantry5/files/4409038/test.-.Administration.pdf)

Also in frontend setting developer mode I got the error: "Trying to access array offset on value of type int"
I enclose the error I got also in this case.
[frontend error.pdf](https://github.com/gantry/gantry5/files/4409048/frontend.error.pdf)

How I can avoid this errors?
I can't figure where is the problem and I need help.

THANK.

**Comment by marktaylor46** [comment]
You are using PHP 7.4.x - you can't with Gantry 5 yet so downgrade to PHP 7.3.x

Regards, Mark.

**Comment by mahagr** [comment]
@ipr-paolo Should be fixed in CI build.
