### ISSUE TITLE
Popupwidget particle broken in Wordpress.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2622]
In Wordpress, the popupwidget particle in all RT themes is broken and does not work. There is a ticket on the internal tracker (GFIVEALL-98) for this but it appears the root cause of the issue is the API that that particle uses in Core Gantry 5. Therefore that is why I have raised this ticket here as this need to be investigated by @mahagr

**Comment by N8Solutions** [comment]
Hello @marktaylor46 Could you please elaborate a little as to what exactly the issue is? I have ported the **popupmodule** particle in to another template and would like to know what exactly isn't working properly.

**Comment by marktaylor46** [comment]
Sure, it does not work at all. Create a poupwidget particle, choose "customhtml" widget and then try and find anywhere that you can edit the customhtml.

Regards, Mark.

**Comment by N8Solutions** [comment]
@marktaylor46 You are saying **"Widget"**. Is this only for WordPress?

**Comment by marktaylor46** [comment]
Yes only in WP. "popupmodule" in Joomla works fine - it's only popupwidget particle that is broken.

**Comment by N8Solutions** [comment]
Great, thanks for the clarification.
I thought it might have also applied to Joomla since above you wrote "in all RT themes".

regards,

Michael

**Comment by marktaylor46** [comment]
Yes I wrote "themes" (WP term) as opposed to "templates" (Joomla term) and wrote "widget" and not "module" - but I'll edit the title to make it clearer.

Regards, Mark.

**Comment by newkind** [comment]
Ok, so I just tested this again and it's working fine for widgets that don't use the JS in their forms. I don't think we'll be able to change that because of how the JS for the WP core widgets is implemented.

**Comment by marktaylor46** [comment]
So, if it can't be fixed then we should at least exclude all the WP core widget from showing as a possibility for selection in the popupwidget particle. To be honest though, I see nmo point in the particle at all if that is the case as what is left after that?

**Comment by newkind** [comment]
I'm also opting for removing this particle entirely and just fallback to loading a certain widget position in the layout.

**Comment by mahagr** [comment]
Or prevent creation of new instances.. Or have a big warning on it. Remember that we cannot break the existing instances.

**Comment by marktaylor46** [comment]
I'd be ok with that, I'd just like to know what will happen to existing sites that have used this (yes I know it doesn't work but it might be on the layout anyway).

**Comment by mahagr** [comment]
See also #677
