### ISSUE TITLE
Assignments panel CSS  problem (5.4.32)

### ISSUE THREAD

**Issue by brentkearney** [gantry/gantry5#2623]
When there's a large number of pages, they overflow the Pages container.

<img width="1172" alt="Grav-Gantry-Assignments" src="https://user-images.githubusercontent.com/1550934/79284709-ace3b180-7e78-11ea-9465-ef1b01c47068.png">

**Comment by blizam** [comment]
I can't reproduce... maybe you've got some other backend plugin introducing some admin-side CSS that's conflicting with it? Are you able to debug the offending CSS?

**Comment by blizam** [comment]
Aside from that, I personally use the IF statement noted here:

https://github.com/gantry/gantry5/issues/1279#issuecomment-287728694

in a Theme override for assignments.html.twig to filter out all the different post types and taxonomies I'm never going to assign anything too... some of my sites have plugins that add a TON of extra posts or types the Assignments screen would take forever to load and be very difficult to navigate, unless I used that additional code in that comment

**Comment by mahagr** [comment]
Are you using Safari? It IMHO had some bug that causes this.
