### ISSUE TITLE
Outline Breaks Upon Duplication

### ISSUE THREAD

**Issue by greenlanegreb** [gantry/gantry5#2624]
Upon duplication on an outline, the duplicate is placing items that should appear on the same row, below each other, i've tried clearing 1) Joomla's cache, 2) Gantry's Cache 3) Browser Cache, and this is an issue both on Chromium and in Firefox.

An example of this is on my friends' website, www.katherinehammond.uk - so we have the welcome outline for that, then we click on "stories" and that section is set to load the Stories outline that is an absolute duplicate of the welcome template (just a different menu allocated) - you will see how photo is appearing underneath text in the second section down within the stories outline, compared to the welcome outline.

I tried it with and without inheritance and had the same issue. 

If it is a known issue, please would you be kind enough to point me in a direction of at least a temporary fix! 

Thank you.

**Comment by blizam** [comment]
Those 2 pages are definitely using different Outlines... ID 12 and ID 15 respectively.

Can you take a screen shot of what the Layout Manager looks like for both, along with their assignments? (Hide assigned items)

**Comment by greenlanegreb** [comment]
Hi, thanks for your Email but I can't see how duplicating an outline should cause this issue. As you'll be aware, there are many reasons outlined are duplicated, not least for changes in the style of a subsection of a website and for different menus to be be displayed per the ability in Joomla. 

So much point is that an image should not be appearing below another module position simply because it is a duplicated outline. 

Thanks and Kind Regards

**Comment by mahagr** [comment]
Missing `</a>` in the page causes layout to break:

```
<p>Credit: <a href="http://thestorytelleragency.com">http://thestorytelleragency.com</p> 	</div>
```
