### ISSUE TITLE
Font-picker do not list some google fonts

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2627]
Hi everybody,

I guess the title is pretty straighforward, i looked for google font on google repo, then wanted to use it on my website, but it appears that the one I chossed isn't offered in gant'y's fontpicker ?!
here is the font url https://fonts.google.com/specimen/KoHo

any ideas ? 
Help would be greatyl appreaciated ! 
Regards

**Comment by mahagr** [comment]
Font picker needs a local list of all available fonts. I guess the font is rather new and has not been listed because of that.

**Comment by jbonlinea** [comment]
ok I've read that somehere indeed

so on shot term, is there a way to update the font list ? 
idealy in a way that override gantry's list so it remain on update ?

on longer term, can't the list be retrieve from a cdn thus is is up to date without need to update gantry  

regards

**Comment by mahagr** [comment]
Fixed, see also #2283
