### ISSUE TITLE
Gantry 5 Menu editor not working as expected

### ISSUE THREAD

**Issue by Mohika** [gantry/gantry5#2628]
Menu editor on WordPress not working again.

Well, let me share some snapshots.
The snapshot below shows a state after the save of the menu changes. It haven't made the 3 column list as it was supposed to.
https://prnt.sc/s3912w
And this is before the save and refresh
https://prnt.sc/s393l1
when I save, clear cache and refresh I get back all the items as they where in a first snapshot. And I tried all possible combinations. Is there a way for me to clear the menu and start all over?
No matter how I arrange the menu items I get back to snapshot 1 after the save.
Gantry 5 has a menu issue which is now for too long, really .. you need to fix this .. cheers!

**Comment by mahagr** [comment]
There's work done to fix this, but it has still some bugs which cause Gantry 5.5 release to be delayed further (and it didn't help that I had bad flu for 3 weeks thus falling behind on all my projects).

I'm closing this as a duplicate.
