### ISSUE TITLE
"Trying to access array offset on value of type int" (PHP7.4 only)

### ISSUE THREAD

**Issue by liz-z17** [gantry/gantry5#2629]
I have run a few different configurations trying to realize what the problem was but do not have the opportunity to investigate it in depth at the moment.

I'm using XAMPP, Joomla! and Hydrogen theme, since I found these to be an excellent starting point in creating a fresh webpage.

Steps to reproduce:
Fresh installation of XAMPP
Fresh installation of Joomla!
Install Gantry5
Install Hydrogen
Enable the default style for all pages
Check the front - it's broken with the message: "Trying to access array offset on value of type int"

The one difference I found was the PHP version: it's broken under 7.4 but works fine with 7.3

**Comment by mahagr** [comment]
@liz-z17 This has already been fixed, try if CI build fixes the issues and please report back so we can release it as soon as possible: http://gantry.org/downloads

PS: find `joomla-pkg_gantry5_develop.zip`
