### ISSUE TITLE
display content : WP_Query vs query_posts() vs get_posts()?

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2630]
Hi guys, 

I've been digging into the various way to display dynamic content and bumped into a question, that may be a concern.

### Get wordpress dynamic content

It seems that wordpress distinguish the `main query`, stemming form the current page url, and `secondary query.ies`, stemming from whatever we want, if one has been set in the page template. 

It also seems that it is not advised to use query_post() for secondary queries, because it may interfere with the main query (I'm not aware of the details, but it seems to be a general recommendation)

see theses two post for reference [here](https://wordpress.stackexchange.com/questions/50761/when-to-use-wp-query-query-posts-and-pre-get-posts/50762#50762) and [here](https://wordpress.stackexchange.com/questions/1753/when-should-you-use-wp-query-vs-query-posts-vs-get-posts)

### Uses in gantry

To my understanding, the particle page content should be used to display the main query while "wordpress post" is more appropriate to display secondary queries. 

After having a closer look into `contentarray.html.twig` (aka, wordpress post particle) I observed that it uses `query_post()`

### Question / concern

I thus wonder why it uses `query_post()` rather than` wp_query()`, and if there are any kwown issues, or best practices to avoid issues ? 

Regards

**Comment by newkind** [comment]
We don't use the `query_posts()` in the backend - this is just the name in our system and it's not a direct reference to the WP function `query_posts()`. In Gantry5 backend we have used `WP_Query`, but since next update we'll be using Timbers' `PostQuery`.
