### ISSUE TITLE
BUG: CI build - PHP v7.4 - Joomla, Modifying Particle Content or Settings throws an Error

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#2631]
# BUG: Modifying Particle Content or Settings throws an Error
* Joomla v3.9.18
* Gantry 5 CI build 2020-04-24 | Commit: (4755f3c94)
* PHP v7.4

If you modify the content or settings of a particle in the Layout it throws an error:

```
Whoops \ Exception \ ErrorException (E_NOTICE)

Trying to access array offset on value of type null
```
Here's a link to a full error stack when I tried to modify the **Key** for the **module position**:
https://www.evernote.com/shard/s202/sh/6c473444-9459-419e-ab23-58db296e15d0/2b892dd146194117829d08462a1846f1

If you simply drag & drop a particle to a position and save the layout without modifying anything, it will save just fine without throwing an error.

It doesn't have to be a new particle. Even if you take an existing particle, and modify something, and then try to save the layout, it will throw an error.

If you require any further information please ask.

**Comment by simmonsr** [comment]
I can confirm this issue @mahagr

**Comment by N8Solutions** [comment]
@simmonsr what is the exact version of PHP that you tested on? My server was running v7.4.4. 

@dmleeman did not have the problem and he is running v7.4.5. I'm upgrading my server now to PHP 7.4.5 and will report back as to if the problem still exists for me.

**Comment by simmonsr** [comment]
7.4.2

**Comment by N8Solutions** [comment]
Upgraded PHP on my server to v7.4.5 and it did not make a difference. I am still receiving the same error message.

@dmleeman

**Comment by dmleeman** [comment]
Can confirm error is repeatable on Joomla 3.9.18 PHP 7.4.5 using this package
 joomla-tpl_g5_hydrogen_develop.zip

Cannot repeat error in following packages (Joomla 3.9.18, PHP7.4.5)
joomla-pkg_gantry5_develop.zip
joomla-tpl_g5_helium_develop.zip

**Comment by mahagr** [comment]
@N8Solutions @dmleeman Can you test if my fix helps?

**Comment by N8Solutions** [comment]
@mahagr Tested, and it is working fine for me.

**Comment by simmonsr** [comment]
confirmed fix
