### ISSUE TITLE
Wordpress Post particle in 5.4.33 not working properly

### ISSUE THREAD

**Issue by saponidas** [gantry/gantry5#2633]
Just after upgrade, the particle not respect the categories marked to be shown and only shows 1 post even you select 2 or more. When selection other number the option ( Number of Posts ), the post shown changes (Not accoording order by date)

WP 5.4.
Gantry 5 Framework 5.4.33 
Theme Helium 5.4.33 
Php 7.3

Thanks in advance.

**Comment by N8Solutions** [comment]
@saponidas Please install the previous release over top of your current installation. This should resolve the issue until this is taken care of.

https://github.com/gantry/gantry5/releases/tag/5.4.32

**Comment by mahagr** [comment]
The issue is in Timber changing its default behaviour; sorry, we totally missed this one.

**Comment by mahagr** [comment]
That fixes the builtin `contentarray` particle, but it will not fix the other custom particles. We are looking if there's a better fix that allows the custom particles to keep on working as well.

**Comment by saulr9** [comment]
Hi! I have a problem with Wordpress posts particle too, it only shows 1 post, I want to show 3 or more posts. I had to rollback gantry to version 5.4.32.

**Comment by simmonsr** [comment]
Yes, we are hoping to fix this issue soon and release an update for Gantry 5.

**Comment by simmonsr** [comment]
fix confirmed
