### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2637]
Hi all,

Platform: Gantry 5 5.4.33, hydrogen latest (Joomla)

I see a lot of warning messages via Chrome Dev tool about the source map, like **nucleus.css.map**, **joomla.css.map**
Screenshot: https://imgur.com/IIVTKtL
Anyone notice about the same warning in console ?
Thanks

**Comment by mahagr** [comment]
Removed those. Thanks.

**Comment by simmonsr** [comment]
confirmed, no longer an issue on our demo after updating Gantry 5:

http://demo.gantry.org
https://demo.rockettheme.com/live/joomla/versla/
