### ISSUE TITLE
Particle in widget overflow

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2639]
Hi
A question or bug ui or css wise

when a particle is added in a line in the layout editor, it's content fit in the parent container, as one would expect

but when the same particle is added in a widget position, it's content overflow its parent container

![Capture du 2020-05-05 16-30-21](https://user-images.githubusercontent.com/23659411/81078100-14c46f80-8eee-11ea-9849-5901b43cdb5d.png)

**Comment by blizam** [comment]
The only thing different about a particle loading directly on an outline versus from a wordpress widget is that it'll have an extra <div> wrapper on it that WordPress adds around all of it's widgets.

So it's something in your theme's CSS that's causing your issue; styling it differently when it's the wordpress widget wrapper
