### ISSUE TITLE
Level3 menu order bug 

### ISSUE THREAD

**Issue by Tazzios** [gantry/gantry5#2644]
I have added a menu particle and if i choose Start Level 3 the order is incorrect, if i change it to level2 the level3 menu items are shown in the right order (but shows to much).

It looks like the Start Level 3 order the items by order of creation.

gantry v5.4.34
Joomla 3.9.18

**Comment by Tazzios** [comment]
Level 3 follows the default joomla menu ordering, so that`s an easy workaround.

**Comment by mahagr** [comment]
This has already been fixed for Gantry 5.5
