### ISSUE TITLE
Helium: Enable autoplayHoverPause on owl carousel

### ISSUE THREAD

**Issue by reineltJanis** [gantry/gantry5#2645]
Extend the properties of the owl carousel particle by allowing the **autoplayHoverPause** functionality.

**Comment by N8Solutions** [comment]
@thexmanxyz How difficult would this be to add to your version, the [Owl Carousel Neo](https://github.com/thexmanxyz/Owl-Carousel-Neo-Gantry#owl-carousel-neo---particle-for-gantry)?

**Comment by thexmanxyz** [comment]
@N8Solutions [already implemented](https://github.com/thexmanxyz/Owl-Carousel-Neo-Gantry/commit/b45e8d3a9402bda80b33e92bb5bf45eaf8884b34), will prepare a PR for Helium as well.

@reineltJanis Kindly please, this is an open source project. You can ask if something gets implemented but TBH I don't like that commanding tone.

**Comment by reineltJanis** [comment]
@thexmanxyz NP. I will ask more politly in the future :) Amazing project! Keeep on going!

**Comment by thexmanxyz** [comment]
@reineltJanis No need to apologize it was 100% my fault I completely missed the PR link in the issue :-D (you created afterwards). Thanks for contribution anyway.

@N8Solutions See [v1.2.2](https://github.com/thexmanxyz/Owl-Carousel-Neo-Gantry/releases/tag/v1.2.2) of Owl Carousel Neo.

/can be closed
