### ISSUE TITLE
Gantry5 won't add camelcase section classes entered through UI

### ISSUE THREAD

**Issue by Bodge-IT** [gantry/gantry5#2647]
Gantry: 5.4.34
Template Helium: 5.4.34
Joomla: 3.9.15

It accepts the entry, adds 'class=""' to the section but leaves it empty.
The ui will accept uppercase char after a '-'
so stickybutton and sticky-Button work
but stickyButton does not.

I cannot see any reason for this, camelcase is valid for css identifiers.

**Comment by blizam** [comment]
Tested on J! 3.9.14 and G 5.4.32; works as expected
updated and 
Tested on J! 3.9.18 and G 5.4.34; works as expected

![image](https://user-images.githubusercontent.com/8940155/82069445-8b046700-9690-11ea-8d88-24241977c61a.png)

![image](https://user-images.githubusercontent.com/8940155/82069518-a66f7200-9690-11ea-8cf2-4906bd55948c.png)

**Comment by Bodge-IT** [comment]
Yes and did you check to see that the class is rendered.

**Comment by blizam** [comment]
I'm fairly certain there are no reserved words, stickyButton worked for me:

![image](https://user-images.githubusercontent.com/8940155/82083845-9616c180-96a7-11ea-8cb6-9891114375e1.png)

**Comment by Bodge-IT** [comment]
OK, thanks for checking.  Must just be local, but not an issue that makes any  sense to me.
Thanks for checking.
