### ISSUE TITLE
TypeError: can't access property "getViewElement"

### ISSUE THREAD

**Issue by PsychoBitchy** [gantry/gantry5#2651]
```Grav.default.Scrollbar.Instance.instance is undefined```
I just updated GANTRY5 for GRAV, the "layout panel" drop zone went blank ( minus the LOAD/CLEAR/SAVE buttons and the components list ) and I get this error in the console.
Evrything is up to date, including the gantry site template
 Gantry 5 Framework v5.4.34
 Helium v5.4.34 
Grav v1.7.0-rc.11 + Admin v1.10.0-rc.11

EDIT: 
I had been able to reproduce the issue by updating the admin plugin from  v1.10.0-rc.9 to v1.10.0-rc.11

**Comment by simmonsr** [comment]
Put in a fix for this issue. Please test with CI Build:

http://gantry.org/downloads#ci-builds

**Comment by Umbyology** [comment]
I have same issue, tried the latest CI ... no change.

**Comment by marcodeluca** [comment]
Yep I have this same issue. I just updated Grav and all plugins (inluding admin and gantry) to the latest version. I am no longer able to navigate through gantry outlines. When selecting an outline from the dropdown, I get the following:

TypeError: Grav.default.Scrollbar.Instance.instance is undefined

Is this an admin plugin issue or a gantry issue?

Any update?

**Comment by marcodeluca** [comment]
Ok @simmonsr is correct the latest CI build does fix the issue. grav-pkg_gantry5_develop.zip and replace the gantry5 folder in user/plugins with that.
