### ISSUE TITLE
Wordpress Menu / Gantry Menu Manager - Conflicting Object IDs

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#2652]
My main Blog page has a Post ID of 24

I have a WooCommerce Category with a Tag ID of 24

taxonomy=product_cat&tag_ID=24

I cannot have these 2 items (Posts Page and Product Category) in the same menu because Gantry assigns them both the same Object ID in menu.yaml

As a workaround I can use Custom Link menu items which get a new Object ID

**Comment by blizam** [comment]
I'll also say I'm surprised the Woo category renders correctly at all... there must be additional logic that can tell it's supposed to be a Woo category instead of a WP Page and that logic gets interrupted when both types (WP Page and Woo Product Category) are present in the menu

**Comment by mahagr** [comment]
I think this has been already fixed in 5.5 branch as it doesn't really rely on ids anymore.
