### ISSUE TITLE
Gantry 5.5 Menu Level Issue

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2653]
View comments and video below. Basically enter Level 2 menu item via arrow icon in Menu Editor, then select Back icon, and you will see duplicate of Level 1 menu items. Refresh and it goes back to normal though.

**Comment by simmonsr** [comment]
Level issue mentioned on Slack:

http://rockettheme.hopto.org:8888/images/Jun-01-2020%2015-29-26.mp4

**Comment by mahagr** [comment]
@simmonsr We need to recompile js and check again.

**Comment by simmonsr** [comment]
If I enter second level menu item and then select Back icon, then for reason duplicate of items appear as shown in video ^^:

![Screen Shot 2020-09-22 at 11 36 49 AM](https://user-images.githubusercontent.com/5002814/93911414-f78b1480-fcc7-11ea-895c-f5df7db26426.jpg)

**Comment by mahagr** [comment]
I'm seeing even worse issues.

**Comment by mahagr** [comment]
I'm able to reproduce this in Joomla, too.

**Comment by simmonsr** [comment]
Yah this still seems to be an issue (just tested latest pkgs)

**Comment by simmonsr** [comment]
I cannot replicate this issue in GRAV. So seems specific to Joomla / WP.

**Comment by mahagr** [comment]
It looks like the menu items do not have `group` index in themselves as it was based on `ordering` which has been replaced by `column_counts` field.

**Comment by simmonsr** [comment]
fix confirmed
