### ISSUE TITLE
Override plugin template in child theme - Wordpress 

### ISSUE THREAD

**Issue by saulr9** [gantry/gantry5#2657]
Hi! I want to override a plugin template in my child theme, but it does not work. I want to override this wp-content\plugins\edwiser-bridge\edwiser-bridge\public\templates\content-single-eb_course.php 
I tried to copy it to my-theme\edwiser-bridge\content-single-eb_course.php, my-theme\edwiser-bridge\templates\content-single-eb_course.php, my-theme\custom\edwiser-bridge\templates\content-single-eb_course.php but none of those override it. 
Could you help me where to put the file?

**Comment by adrienionescu** [comment]
It depends where the plugin is looking for those templates, you should check their docs. Usually, the overrides follow the same path, you can try `your-theme/edwiser-bridge/public/templates/content-single-eb_course.php`. You can also create a single view for a [custom post type](https://developer.wordpress.org/themes/template-files-section/custom-post-type-template-files/#custom-post-type-template-hierarchy) like this: `single-{post_type}.php`
