### ISSUE TITLE
Upper Menu Items Missing in GRAV

### ISSUE THREAD

**Issue by Umbyology** [gantry/gantry5#2659]
See attachment ... the upper/top horizontal "menu" items are missing (Menu, Clear Cache etc ...). The menu items blink-in for a split second when I refresh the page, then disappear. Almost like a layering issue of some kind, perhaps a z-index needs adjusting ... hope I got that right :)

I tried install the latest CI, then wiped the cache folder ... no change.

<img width="1367" alt="Screen Shot 2020-06-11 at 7 14 34 PM" src="https://user-images.githubusercontent.com/22547499/84452246-edfb0680-ac1a-11ea-9513-2171000dee9b.png">

**Comment by Umbyology** [comment]
I restored GRAV RC10 and all is well for now. Thus, the issue is in RC12.

**Comment by andrewbernard** [comment]
I am getting the same thing in RC12.

**Comment by mahagr** [comment]
I'm on Gantry CI + Grav RC.16 and I can see the upper menu.

**Comment by simmonsr** [comment]
You need to use latest CI with Grav RC:

http://gantry.org/downloads#ci-builds
