### ISSUE TITLE
Get styles in php files

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#266]
I am not sure how to name this or if is supposed to work.
adding this line will returng gantry 500 error:

`<i class="<?php echo Gantry\Framework\Gantry::instance()['config']->get('styles.others.font'); ?>"></i>`

as we've talked in the chat, i'll let this open as a question.

**Comment by mahagr** [comment]
I think it would be great if it worked, but I'm not fully sure how it should be implemented as we do not fully know in that point which template style gets loaded.

Thanks for the report, though, I need to take a look into this at some point.

**Comment by adi8i** [comment]
can't be used a helper, like joomla dose with `Jhelper' ? so just add this where you need it, i am not that good at php :))

**Comment by mahagr** [comment]
Gantry already works in that point, but the issue is that template gets initialized after component gets rendered, so it doesn't know which template style to use at that point. No worries, I guess I just need to initialize it when needed.
