### ISSUE TITLE
Error with css - El tema no tiene la hoja de estilos style.css.

### ISSUE THREAD

**Issue by juanthe7** [gantry/gantry5#2662]
Im trying to install the theme HYDROGEN but i run with this error: 

No se ha podido descomprimir el paquete. El tema no tiene la hoja de estilos style.css.

I have already installed the plugin: Timber and Gantry 5 Framework but it doen't fix the bug. 

I have seenm a  video on youtube : https://www.youtube.com/watch?v=5o5GjHVX7AQ where you give some instructions to install but i did all and it doesn't work.

**Comment by adrienionescu** [comment]
Make sure you download the right package: http://gantry.org/downloads#wordpress

**Comment by juanthe7** [comment]
thanks @adrienionescu, i downloaded the wrong one. I already did with the correct one and I didn't have any issue.
