### ISSUE TITLE
Custom Taxonomy in "wordpress post" particle

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2664]
Hi guys, 

I would like to be able to filter post in wordpress post particle based on a custom taxonomy

according to wp documentation here is how to[ get post from a custom taxonomy with wp_query
](https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters)

To my understanding, we have to add the `tax_query` parameter to the "query_parameter" 

First let's do in manually ! (without ui)

I thus tried adding this to the query_parameter, but the result is blank screen
```
    'tax_query': '{
      'taxonomy': 'MyCustomTaxonomySlug',
      'field': 'slug',
      'terms': 'My',
     }'
```

then I tried to add this of code in the twig file, to complete the `query_parameter` but the post aren't filtered

```
{% set query_parameters = query_parameters|merge ({
  'tax_query': {
    'taxonomy': 'docbookcat',
    'field': 'slug',
    'terms': 'conservation-society',
  }
})
%}
```

This result it nots o surprising as wp codex says that tax_query is an array of array, while my piece of code in simply an array.

The fact is that if I try to nest the array in an other one I get a blank page :
```
{% set query_parameters = query_parameters|merge ({
  'tax_query': {{
    'taxonomy': 'docbookcat',
    'field': 'slug',
    'terms': 'conservation-society',
  }}
})
%}
```

```

{% set query_parameters = query_parameters|merge ({
  'tax_query': {'{
    'taxonomy': 'docbookcat',
    'field': 'slug',
    'terms': 'conservation-society',
  }'}
})
%}
```

The broad question is how to make a wordpress query of post being in a custom taxonomy from a twig file ? 

If you can help me with this I can finish to extent the particle with conditionals and UI for better integration !

Thank's in advance

ps : you may want to look at my first research and successfull result to dispolay custom post types in the particles #2616

**Comment by adrienionescu** [comment]
In twig you write arrays like this:
- Indexed Array: []
- Associative array: {}


Query posts under one taxonomy:
```
{% set args = {
    'post_type': ['event', 'course'],
    'tax_query': [{
        'taxonomy': 'event_category',
        'field': 'slug',
        'terms': 'category-one'
    }]
} %}
```

Query posts from several taxonomies:
```
{% set args = {
    'post_type': ['event', 'course'],
    'tax_query': {
        'relation': 'OR',
        0: {
            'taxonomy': 'event_category',
            'field': 'slug',
            'terms': 'category-one'
        },
        1: {
            'taxonomy': 'course_category',
            'field': 'slug',
            'terms': 'category-one'
        },
    }
} %}
```

**Comment by jbonlinea** [comment]
Oh, man this makes my day ! 

I wasn't aware of this array syntax difference in twig

Thank's
