### ISSUE TITLE
Nested menus - issues on desktop and mobile 

### ISSUE THREAD

**Issue by damyco** [gantry/gantry5#2666]
Hi, I've got issues with nested menus (drop downs). I'm on WordPress + Helium theme.

It seems like the expand on hover is happening on whole ul instead of the particular li as you can see below:

![alt](https://i.imgur.com/CbxDJes.png)

Then on mobile it's not covering the previous menu and instead it appears on top of the other one:

![alt](https://i.imgur.com/O68uIjZ.png)

**Comment by mahagr** [comment]
@simmonsr Can you take a quick look on this?

**Comment by simmonsr** [comment]
I can't replicate on my local version of Helium. Seems ok.
