### ISSUE TITLE
default icon is not picked. 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#267]
i've added icon picker for offcanvas-toggle, using this code `{{ gantry.config.get('styles.offcanvas.toggle-icon', false) }}` , i've also tried with `false` ` true` and none. In styles i have this: `default: 'fa fa-fw fa-bars'`, in preset i also have this `toggle-icon: 'fa fa-fw fa-bars'` . But the box under styles tab will be unchecked and will not add any icon till i will not check it, so no default icon is picked, do i miss anything or is a bug ? I remember there was one

**Comment by mahagr** [comment]
default value doesn't get picked right now; you need to use 

    {{ gantry.config.get('styles.offcanvas.toggle-icon')|default('fa fa-default') }}

I have plans to improve it, but it's not high priority right now.

**Comment by adi8i** [comment]
aaaah btw i've tried with `default` too, but missed last part, and i've seen this in twig docs :D , thanks

**Comment by w00fz** [comment]
All good here @adi8i ?

**Comment by adi8i** [comment]
yes @w00fz, forgot to close this one, sorry :). 

btw, i've troubles accessing gitter, don't know why. but is happen almost every day.

**Comment by w00fz** [comment]
Try emailing them, they have pretty good support
