### ISSUE TITLE
2 column menu dropdown ordering doesn't save.

### ISSUE THREAD

**Issue by jasonmac75** [gantry/gantry5#2671]
When I save the menu order into 2 columns and then go back and re-edit the menu it defaults back the original state of 1 column?

As per screen shot:

![gantry5-2-col-menu-not-saving](https://user-images.githubusercontent.com/40664353/87963077-1266c000-cab0-11ea-984f-7cbb528cf1cb.jpg)

Is this a read/write issue to a config file setting,? I've noticed this popping up over quite a few updates or versions.

**Comment by simmonsr** [comment]
Your Hydrogen theme appears out of date (5.2.0 => 5.4.34). Please update to see if that helps:

http://gantry.org/downloads

**Comment by jasonmac75** [comment]
Just updated, didn't realise the template didn't update automatically, thanks for this. 

Unfortunately still the same problem with Theme: Hydrogen (v5.4.34 / g5_hydrogen), I can see the main-menu.yaml is modified as the date on the server has changed when in date modified view.

Odd is some of the text wrong ie Section?
ordering:
  furniture:
    -
      ection/furniture/107-bookcase-shelving: ''
      ection/furniture/104-sideboard: ''

  decoration:
    -
      201-lamp: ''
      ction/decoration/210-textiles: ''
      ction/decoration/212-screens: ''

Thanks

**Comment by jasonmac75** [comment]
Maybe I could clear the main-menu.yaml file and then resave and see if it saves initial state.

**Comment by mahagr** [comment]
Removing the file helps. This has already been fixed for the upcoming Gantry 5.5
