### ISSUE TITLE
Grav - shortcode doesn't work

### ISSUE THREAD

**Issue by lazybadger** [gantry/gantry5#2675]
1. Shortcode used inside block not processed, but rendered "as is". The same shortcode inside plain Grav work as expected
2. Shortcode used inside "page content" does not work, because in generated JS `"` in sources replaced by `&#039;`:
Shortcode's `[a-markers markerColor="beige" iconColor="darkpurple"]` converted into
```
          markerColor: &#039;beige&#039;,
          iconColor: &#039;darkpurple&#039;
```
and these definitions are errors for JS

Original [Rocketheme topic](https://rockettheme.com/forum/grav-theme-hadron/284763-shortcode-support-is-broken-in-theme-gantry) for reference

**Comment by mahagr** [comment]
Try if the shortcode works if you turn on autoescape for twig?

**Comment by lazybadger** [comment]
With 
```
twig:
  ...
  autoescape: true
```
I got the same results:
1. Plain shortcode in block ("process shortcodes" enabled for block)
2. **Not escaped** JS in page-content
```
        icon: L.ExtraMarkers.icon({
          markerColor: &#039;beige&#039;,
          iconColor: &#039;darkpurple&#039;
                    , icon: &#039;fa fa-home&#039;
                    })
```

**Comment by mahagr** [comment]
I think the issue may be in the shortcode plugin that contains this shortcode.

**Comment by lazybadger** [comment]
> I think the issue may be in the shortcode plugin that contains this shortcode.
I think - no, because (again)
1. _the same_ plugin and _the same_ shortcode work in plain Grav
2. Only **in Gantry-theme** I get not processed, but "dirty" shortcode in block-content

**Comment by mahagr** [comment]
@lazybadger Did you try it with autoescape on?

**Comment by mahagr** [comment]
@lazybadger I tried to add the shortcode, but in which plugin it is defined in?

**Comment by lazybadger** [comment]
> @lazybadger Did you try it with autoescape on?

Yes, as I wrote [in 3 comment above](https://github.com/gantry/gantry5/issues/2675#issuecomment-671250377) - no changes

> in which plugin it is defined in?

[Map Marker Leaflet](https://github.com/finanalyst/grav-plugin-map-marker-leaflet) on top of just Shortcode Core

**Comment by mahagr** [comment]
I can reproduce the escape issue in Quark as well:

https://github.com/finanalyst/grav-plugin-map-marker-leaflet/issues/20

**Comment by mahagr** [comment]
Fixed missing shortcode parsing in the custom particle.

**Comment by lazybadger** [comment]
Gantry 5.4.35, issue is **still here**

**Comment by mahagr** [comment]
Umm, really? I am looking into my site and shortcode is working in both places.

I did have to fix the plugin as it was broken, see the issue I created above. It is really easy to fix though, you just need to edit two files: https://github.com/finanalyst/grav-plugin-map-marker-leaflet/tree/master/templates/partials with `|raw` on all variables.

**Comment by lazybadger** [comment]
@mahagr Yes, I *had* to add `|raw` in all output in templates (but it isn't Ganry's side error) and now I **got** maps working. Issue can be now closed finally, I hope
