### ISSUE TITLE
Not being able to override outline global page settings

### ISSUE THREAD

**Issue by mathewriver** [gantry/gantry5#2676]
BUG REPORT: I'm not being able to override outline from the Global Page Settings neither in the error page, nor in the home page. Using Gantry 5 with Wordpress.
Whenever I try to add a custom code before body in the **Body Attributes**, try to add it as an asset or I try to add it as an Atom, it simply doesn't work, despite what the content is. It is always loading the content from the base oultine, even if I delete the base outline content from it. I also tried deleting custom code from the base outline and I still could override the default content.
Screenshot [https://ibb.co/GWGK12Z](url)

**Comment by mahagr** [comment]
@simmonsr Can you test this one out?

**Comment by simmonsr** [comment]
I can't replicate on Home Page. Do you have your Assignments set up to use your home page?

The issue with error page here has been fixed by @mahagr and will be available in 5.4.36.

**Comment by mahagr** [comment]
See #2686.
