### ISSUE TITLE
Error when accessing template from template manager if NoNumber ATM installed

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#268]
If you have Advanced Template Manager installed from NoNumber and try to access one of the installed G5 templates you will get an error "Error Please install Gantry 5 Framework!" even though it is actually installed and you can access the template through "components > gantry 5 themes".

**Comment by mahagr** [comment]
There is also another related issue where ATM doesn't pick up the style specified in Joomla menu item.
