### ISSUE TITLE
Italic fonts included in templates are not rendered just simulated

### ISSUE THREAD

**Issue by jameswadsworth** [gantry/gantry5#2682]
We discovered an issued with the Sienna template that playfairdisplay italic font wasn't displaying correctly. 

[](https://rockettheme.com/forum/joomla-template-sienna/284741-playfairdisplay-italic-font-don-t-displaying?start=0#1429927)

Upon further investigation, not only with the Sienna template but all other gantry templates we investigated, we found that although the italic fonts webfonts are included in the template files 

![Selection_108](https://user-images.githubusercontent.com/9198869/89656950-402b7180-d8c4-11ea-8b21-ffa8748bb8af.png)

and defined the theme.yaml files,

`      fonts:
        muli:
          400: 'gantry-theme://fonts/muli/muli-regular/muli-regular-webfont'
          400italic: 'gantry-theme://fonts/muli/muli-italic/muli-italic-webfont'
          300: 'gantry-theme://fonts/muli/muli-light/muli-light-webfont'
          300italic: 'gantry-theme://fonts/muli/muli-lightitalic/muli-lightitalic-webfont'
        playfairdisplay:
          400: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont'
          400italic: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-italic/playfairdisplay-italic-webfont'
          700: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont'
          700italic: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-bolditalic/playfairdisplay-bolditalic-webfont'
          900: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont'
          900italic: 'gantry-theme://fonts/playfairdisplay/playfairdisplay-blackitalic/playfairdisplay-blackitalic-webfont'
        weather:
          400: 'gantry-theme://fonts/weather/artill_clean_icons-webfont'`

the font-face definitions are only generated for the font-style: normal, never for the font-style: italic. 

`    @font-face {
      font-family: "muli";
      font-style: normal;
      font-weight: 400;
      src: url('../fonts/muli/muli-regular/muli-regular-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/muli/muli-regular/muli-regular-webfont.woff2') format("woff2"), url('../../fonts/muli/muli-regular/muli-regular-webfont.woff') format("woff"), url('../../fonts/muli/muli-regular/muli-regular-webfont.ttf') format("truetype"), url('../../fonts/muli/muli-regular/muli-regular-webfont.svg#muli') format("svg");
    }
    @font-face {
      font-family: "muli";
      font-style: normal;
      font-weight: 300;
      src: url('../fonts/muli/muli-light/muli-light-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/muli/muli-light/muli-light-webfont.woff2') format("woff2"), url('../../fonts/muli/muli-light/muli-light-webfont.woff') format("woff"), url('../../fonts/muli/muli-light/muli-light-webfont.ttf') format("truetype"), url('../../fonts/muli/muli-light/muli-light-webfont.svg#muli') format("svg");
    }
    @font-face {
      font-family: "playfairdisplay";
      font-style: normal;
      font-weight: 400;
      src: url('../fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont.woff2') format("woff2"), url('../../fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont.woff') format("woff"), url('../../fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont.ttf') format("truetype"), url('../../fonts/playfairdisplay/playfairdisplay-regular/playfairdisplay-regular-webfont.svg#playfairdisplay') format("svg");
    }
    @font-face {
      font-family: "playfairdisplay";
      font-style: normal;
      font-weight: 700;
      src: url('../fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont.woff2') format("woff2"), url('../../fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont.woff') format("woff"), url('../../fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont.ttf') format("truetype"), url('../../fonts/playfairdisplay/playfairdisplay-bold/playfairdisplay-bold-webfont.svg#playfairdisplay') format("svg");
    }
    @font-face {
      font-family: "playfairdisplay";
      font-style: normal;
      font-weight: 900;
      src: url('../fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont.woff2') format("woff2"), url('../../fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont.woff') format("woff"), url('../../fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont.ttf') format("truetype"), url('../../fonts/playfairdisplay/playfairdisplay-black/playfairdisplay-black-webfont.svg#playfairdisplay') format("svg");
    }
    @font-face {
      font-family: "weather";
      font-style: normal;
      font-weight: 400;
      src: url('../../fonts/weather/artill_clean_icons-webfont.eot#iefix') format("embedded-opentype"), url('../../fonts/weather/artill_clean_icons-webfont.woff2') format("woff2"), url('../../fonts/weather/artill_clean_icons-webfont.woff') format("woff"), url('../../fonts/weather/artill_clean_icons-webfont.ttf') format("truetype"), url('../../fonts/weather/artill_clean_icons-webfont.svg#weather') format("svg");
    }`

Therefore when an italic font is displayed it is always simulated since no italic version of the font face is available. 

Expected behaviour:
Gantry5 generates the font-face with font-style italic as well as normal.

**Comment by simmonsr** [comment]
Please see:

https://github.com/gantry/gantry5/issues/2451

**Comment by simmonsr** [comment]
Specifically:

https://github.com/gantry/gantry5/issues/2451#issuecomment-463693754

**Comment by jameswadsworth** [comment]
Issue #2451 is exactly the same. You can close this thread if you want since the other issue is till open. Hopefully a solution in Gantry5 will be found rather than having to manually add the font-face for italic files in the custom.scss file.

**Comment by mahagr** [comment]
Closing as duplicate.
