### ISSUE TITLE
Preload web fonts

### ISSUE THREAD

**Issue by turystahobby** [gantry/gantry5#2684]
I looking for a way to preload web fonts but not sure when exactly i have to past this syntax:
<link rel="preload">
font-display: swap

**Comment by natecovington** [comment]
Like this in your CSS:

@font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2) format('woff2');
  font-display: swap;
}

**Comment by turystahobby** [comment]
oh yes :) its work but I have issue with this particular webfont
…fonts/fontawesome-webfont.woff2?v=4.4.0(netdna.bootstrapcdn.com)

when I try to 
put this syntax font-display: swap; its break the whole page code
