### ISSUE TITLE
System Outlines - Styles don't work [WORDPRESS]

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2686]
Tried editing background / colors in Error outline -> Styles tab in WordPress, but it does not update. Tried RocketTheme's Phoenix and Reiko themes. Grav / Joomla are fine. Just specific to:

WordPress
Error / Offline / Body Only outlines (System)

**Comment by mahagr** [comment]
@simmonsr This issue may affect Joomla and Grav, too. Should be fixed in all of them now.

**Comment by simmonsr** [comment]
So fixes have been confirmed in Joomla / WordPress. But I found this when putting Grav in Offline mode:

![Screen Shot 2020-10-05 at 11 37 28 AM](https://user-images.githubusercontent.com/5002814/95107241-4345b100-06ff-11eb-8b66-0b7dc7186433.jpg)

**Comment by simmonsr** [comment]
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

**Comment by simmonsr** [comment]
/Applications/MAMP/htdocs/grav/grav-admin/user/plugins/gantry5/engines/nucleus/templates/offline.html.twig
{% extends "partials/page.html.twig" %}

{% block content %}
{{ content|raw }}
{{ gantry.global.offline_message|markdown|raw }}

{% if (page.header.form) %}
{% set show_login_form = 1 %}
{% include 'partials/login-form.html.twig' %}
{% endif %}
{% endblock %}
Arguments
"An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null")."

**Comment by mahagr** [comment]
Offline mode issue was not related to this bug. Fixed nonetheless.

**Comment by simmonsr** [comment]
Offline is System Outline, so that is how I came across it. Checking the fix. :)

**Comment by simmonsr** [comment]
fix confirmed
