### ISSUE TITLE
Variations populated list doesnt allow to click on scrollbar (Chrome/Opera)

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#269]
![150515](https://cloud.githubusercontent.com/assets/1657924/7654394/14319f26-fb1d-11e4-952d-cd3fc93e6fd6.png)

Chrome: 42.0.2311.152
Opera: 29.0.1795.47

**Comment by adi8i** [comment]
Is working fine for me, are you using touch ?

**Comment by csbalazs** [comment]
Try it in Totop particle.

**Comment by adi8i** [comment]
Dropdown list works, use scroll button.  The issue is the following, if you click the scroll bar, variations window will close @kevlardev

**Comment by csbalazs** [comment]
https://www.youtube.com/watch?v=9fyvidZK8JA

**Comment by adi8i** [comment]
Yes, read my comment, the window will close when you click the scroll bar, is a bug. But till it will be solved. You can use the scroll wheel, on your mouse.
![mouse-scroll-wheel](https://cloud.githubusercontent.com/assets/9744973/7655109/2a8abad4-fb2a-11e4-95d3-6c941614adb2.jpg)

**Comment by csbalazs** [comment]
Allright, but I couldn't find this issue in the list.

**Comment by adi8i** [comment]
don't worrie, you can open an issue every time you find a bug :)

**Comment by w00fz** [comment]
Are you guys both on Windows? Seems to be fine on a Mac

**Comment by w00fz** [comment]
Actually I just tried with `Chrome 42.0.2311.152 m` on `Windows 8.1` and it seems to be working fine there also.

**Comment by adi8i** [comment]
Is not just totop, is the same for most of particles, and yes windows 8.1 . I will take a look one more time

**Comment by adi8i** [comment]
Take a look here: https://www.youtube.com/watch?v=tXkAIn2juAM

**Comment by csbalazs** [comment]
Unfortunately, the problem is still exist in RC2: https://www.youtube.com/watch?v=sELN7unG7Lw

Windows 8.1
Chrome: 42.0.2311.152
Opera: 29.0.1795.47

**Comment by csbalazs** [comment]
adi8i, your video is private.

**Comment by adi8i** [comment]
oh, did not seen

**Comment by w00fz** [comment]
Weird I cannot reproduce this issue. I will try again over the weekend.
Interesting your video @adi8i, the first time works and then after that it never does again?

**Comment by adi8i** [comment]
yes, that's right @w00fz

**Comment by csbalazs** [comment]
My clean install: https://www.youtube.com/watch?v=4RErmgtTZKM

**Comment by esedic** [comment]
I can confirm this issue.
Using Chrome 42.0.2311.152 m on Windows 7, XAMPP with Apache 2.4.9 and PHP 5.4.27 and Joomla 3.4.1.
