### ISSUE TITLE
Custom Content in Head 

### ISSUE THREAD

**Issue by pscharfg** [gantry/gantry5#2692]
Thanks for the great work on Gantry.   I discovered an issue today as I was optimizing a website.   It appears when custom text is added via Global Page Settings / Head Properties, a "-" is added after the first letter of each line.  Specifically I am trying to add:
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#805bd5">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
```

and I'm getting:
```
<l-ink rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<l-ink rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<l-ink rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<l-ink rel="manifest" href="/site.webmanifest">
<l-ink rel="mask-icon" href="/safari-pinned-tab.svg" color="#805bd5">
<m-eta name="msapplication-TileColor" content="#603cba">
<m-eta name="msapplication-TileImage" content="/mstile-144x144.png">
<m-eta name="theme-color" content="#ffffff">
```

I tried creating an atom and I am having the same issue,.

**Comment by simmonsr** [comment]
Which CMS are you using?

**Comment by pscharfg** [comment]
Joomla

> 
> 
> Which CMS are you using?

latest version of both Gantry and Joomla

**Comment by simmonsr** [comment]
Hmm, I can't seem to replicate on my local. Is your site available for a direct look?

**Comment by simmonsr** [comment]
Do you have RS Firewall installed?

https://github.com/t3framework/t3/issues/256

**Comment by pscharfg** [comment]
I do have RSFirwall installed - It didn't occur to me that could be the issue. And yes, I can make the site available to you.  This is my first time reporting an issue. Can I send you login credentials privately?

**Comment by simmonsr** [comment]
It looks like the issue is RS Firewall then, I'd contact them for support if you are not aware as to how to modify the component for JS injections.

**Comment by pscharfg** [comment]
Thanks for your help.  I will address and report back in a few minutes.

**Comment by pscharfg** [comment]
yup - RSFirewall Exception.  I disabled the protection for com_gantry5 but there may be a better way then excluding the whole component.  I'll need to check with the RS folks.  Thanks again for your quick replies and for pointing me in the right direction

**Comment by simmonsr** [comment]
You're welcome!
