### ISSUE TITLE
wordpress 5.5 update problem (helium theme)

### ISSUE THREAD

**Issue by puhapuru** [gantry/gantry5#2694]
hi, i'm using helium theme(5.4.10) on wordpress 5.4.2.

the problem is that after update wordpress 5.5, home layout got break. for example the top slider(header) disappeared, and overall layout got distort. 

so i had to roll back the old version of wordpress.
can i get help with it?
thanks

**Comment by simmonsr** [comment]
You Helium version is way out of date (latest is 5.4.34):

http://gantry.org/downloads#wordpress

Try copying the site onto a subdirectory and updating there.

**Comment by puhapuru** [comment]
> You Helium version is way out of date (latest is 5.4.34):
> 
> http://gantry.org/downloads#wordpress
> 
> Try copying the site onto a subdirectory and updating there.

Thank you
