### ISSUE TITLE
[Joomla 4] Helium Theme Error 

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2695]
Please see screenshot:

![2020-08-18_15-38-35](https://user-images.githubusercontent.com/5002814/91874732-333e3b80-ec40-11ea-89d6-8bd79b51c5e7.png)

**Comment by mahagr** [comment]
@simmonsr This is something that needs to be fixed in all of our themes.

**Comment by simmonsr** [comment]
Can it be used in both Joomla 3 / 4?

**Comment by mahagr** [comment]
Yes.. But it works only in J!3.9+. We likely need to raise minimum requirements for the theme when we update them.
