### ISSUE TITLE
[Grav 1.7] Grav Admin RC doesn't show Gantry icon

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2696]
Please see screenshot:

![Screen Shot 2020-09-02 at 12 04 35 PM](https://user-images.githubusercontent.com/5002814/92014365-bcbf3d80-ed14-11ea-98ad-e548e7ed14f9.jpg)

Using latest RC admin / grav + gantry CI. Icon shows when in Gantry admin but not outside of Gantry admin.

**Comment by mahagr** [comment]
Looks like the icon shows up only when you're inside Gantry.

**Comment by mahagr** [comment]
The icon is not defined in Fork Awesome, just in Font Awesome. Additionally there's no SVG file for the icon in Gantry itself.

CC @rhukster

**Comment by 01Kuzma** [comment]
Moreover it doesn't work on Grav 1.7. Outlines doesn't switch

**Comment by simmonsr** [comment]
@01Kuzma If you are using CI build Outlines work:

http://gantry.org/downloads#ci-builds

**Comment by simmonsr** [comment]
tested with latest ci build + latest RC seems ok now

**Comment by simmonsr** [comment]
i take that back, still broken...

**Comment by marktaylor46** [comment]
tested with Grav 1.7.3 and G5.4.36 and it is broken - gantry does not have an icon.

**Comment by mahagr** [comment]
@rhukster

This commit removes custom RocketTheme fonts from Grav and causes the issue:

https://github.com/getgrav/grav-plugin-admin/commit/d315aed0f0edb1278acabb6d038235f66d7f4542

**Comment by rhukster** [comment]
I've put the special fonts back into the css.  Can someone test from github repo in admin real quick?

**Comment by simmonsr** [comment]
looking

**Comment by simmonsr** [comment]
fix confirmed

**Comment by mahagr** [comment]
Fix will be in Grav Admin v1.10.3
