### ISSUE TITLE
Layout manager - drag and drop

### ISSUE THREAD

**Issue by mihha** [gantry/gantry5#27]
Drag and drop of particles works only if you drag and drop the particle on the right. You can't drag and drop particle on the left. This allows you to rearrange only to the left and not to the right

![](http://take.ms/65UWU)

**Comment by mariantanase** [comment]
For me is working fine. When you drag the "To Top" particle from right to the left, take care to cover the entire area of "Spacer". The "Spacer" will float to the right position and the "To Top" will take place to the left side.
![gantry5-totop](https://cloud.githubusercontent.com/assets/3976174/6914403/4f7035ea-d78a-11e4-918f-ed80651af9ae.png)

**Comment by mahagr** [comment]
It is indeed working, but maybe its not obvious enough?

**Comment by mihha** [comment]
Yes, it wasn't obvious enugh. It is working now when I realized that I have to move the mosue pointer almost to the end of the browser window to enable it
