### ISSUE TITLE
[Grav v1.6.27] Gantry v5.4.35 - gantry.platform.filter() throws error

### ISSUE THREAD

**Issue by MaksymJ** [gantry/gantry5#2700]
Hi,
after updating to gantry 5.4.35, my site throws an error:
`Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("Identifier "shortcode" is not defined.").
Previous exceptions
Identifier "shortcode" is not defined. (0)`
in my Gantry 5 particle, i have such a custom HTML field in YAML file (i use/run there twig codes in that field):
```
    menu_html:
      type: textarea.textarea
      label: Menu HTML (Twig)
```
and in my particle twig file i call it like this:
```
{% set html = gantry.theme.compile(particle.menu_html) %}
{{ gantry.platform.filter(html)|html|raw }}
```
also, for testing purposes, if i just run this code:
`{{ gantry.platform.filter('<p>testing</p>') }}`
it throws an error too...

before the gantry update, everything worked well, but after the update it throws an error, i guess something is changed, do not know what exactly ...

thank you,
Best Regards
Maksym

**Comment by simmonsr** [comment]
@mahagr

**Comment by mahagr** [comment]
@MaksymJ As a workaround, please install older version of Gantry, I will fix this soon in CI releases.

**Comment by mahagr** [comment]
Fixed in CI version.

**Comment by MaksymJ** [comment]
@mahagr thank you so much!
