### ISSUE TITLE
Accessing Grav page.media.images and .files by Array Index

### ISSUE THREAD

**Issue by thekenshow** [gantry/gantry5#2702]
Gantry does not support Grav's ability to accessing media by array index. For example, `grav.page.media.images[2].url` returns NULL. Gantry's Custom HTML particle would be greatly improved with support for these. As it stands, anything beyond `grav.page.media.images|first` has to be hard-coded. 

In general (and I've probably requested this before) it would make development a lot easier if Gantry5 documented the Twig functions it supports (or doesn't support).

**Comment by mahagr** [comment]
`grav` should be available in Gantry particles. There is no difference in how it works as it is not part of Gantry, but Grav container object itself.

I just checked the Grav code. Array does not support numbers but filenames and there's no image named `2`. Try using something like: `grav.page.media.images|slice(1,1)|first.url`

**Comment by mahagr** [comment]
Slice has third parameter to remove keys as well.. After that you should be able to use numbers.

**Comment by thekenshow** [comment]
Thanks for diving into this and pointing me to that slice approach, much appreciated. Took me a while to figure out what you meant about removing keys, but I get it now.
```
{% set mu = ['/user/moose', '/user/goose'] %}

{% for u in mu %}
  - {{ u }}<br>
{% endfor %}

# Returns
# - /user/moose<br>
# - /user/goose<br>
# - /user/loose<br>

{{ mu|slice(0,3)[2] }}

# Returns
# /user/loose
```

**Comment by mahagr** [comment]
I didn't mean that. Try: `{% set mu = {one: '/user/moose', two: '/user/goose'} %}`

**Comment by thekenshow** [comment]
OK, thanks for clarifying.
