### ISSUE TITLE
Grav: Positions are not working if folder is missing

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2703]
![Screen Shot 2020-09-21 at 3 33 09 PM](https://user-images.githubusercontent.com/5002814/93818553-22219280-fc20-11ea-8600-fd1a1c5054bf.jpg)

**Comment by mahagr** [comment]
The bug also exists in the released version.

**Comment by mahagr** [comment]
@simmonsr Should be fixed, please test as I was not able to reproduce the issue.

**Comment by simmonsr** [comment]
So seeing an issue on the initial load of the positions page with DEV version (positions that exist do not show up initially):

![Screen Shot 2020-09-22 at 10 52 43 AM](https://user-images.githubusercontent.com/5002814/93906723-27cfb480-fcc2-11ea-8ac1-f66eb84bba66.jpg)

![Screen Shot 2020-09-22 at 10 53 08 AM](https://user-images.githubusercontent.com/5002814/93906758-31f1b300-fcc2-11ea-9d38-c4bcd6215414.jpg)

**Comment by mahagr** [comment]
Oh, thanks, that helps to reproduce the issue. Do the positions appear when visiting the individual outlines or do you need to save them?

**Comment by simmonsr** [comment]
The positions are there in the individual outline -> Layout, yes (see base outline on Helium). And if I hit Save Positions on the Positions page they show up. Just not on the initial page load when I first open that page after installing Gantry / Theme.

**Comment by mahagr** [comment]
What happens if you hit save layout?

**Comment by simmonsr** [comment]
You mean Save Positions? It shows the positions correctly. It's just the initial page load when you first load the positions that is the problem.

**Comment by simmonsr** [comment]
/Applications/MAMP/htdocs/grav/grav-admin/user/plugins/gantry5/engines/nucleus/templates/offline.html.twig
{% extends "partials/page.html.twig" %}
 
{% block content %}
    {{ content|raw }}
    {{ gantry.global.offline_message|markdown|raw }}
 
    {% if (page.header.form) %}
    {% set show_login_form = 1 %}
    {% include 'partials/login-form.html.twig' %}
    {% endif %}
{% endblock %}
Arguments
"An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null")."

**Comment by simmonsr** [comment]
Actually getting JS errors:

![Screen Shot 2020-10-05 at 11 42 02 AM](https://user-images.githubusercontent.com/5002814/95108097-6b81df80-0700-11eb-8688-c81e19f89897.jpg)

**Comment by mahagr** [comment]
@simmonsr Try again?

**Comment by simmonsr** [comment]
fix confirmed and working great, thanks.
