### ISSUE TITLE
[Joomla 4] G5.5 - assignments don't work at all.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2704]
If you assign an outline to a menu item in G5 admin it will say it's worked and saved - but it hasn't. If you do that, move off the assignments tab and then back again, no assignment has been made at all.

**Comment by mahagr** [comment]
It looks like Joomla has changed checked_out behaviour to default to null instead of 0.

**Comment by marktaylor46** [comment]
Yeh it works now - confirmed fix - although I jhave not tested that it still work in J3
