### ISSUE TITLE
[Joomla 4] G5.5 - why is Gantry 5 still using Bootstrap 2.3.2?

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2705]
Joomla 4 now uses Bootstrap 4 and CSS Grid for the frontend. Shouldn't Gantry 5.5 also use these rather than a very out of date (and modified) version of Bootstrap 2?

**Comment by mahagr** [comment]
It is the next step. Gantry 5.5 does not yet fully support Joomla 4 as it has been a moving target before beta releases. 

Right now we are still looking into bugs in Joomla 4 implementation (code) and just preparing to add Bootstrap 4 and Font Awesome 5.

**Comment by Flowman** [comment]
Bootstrap 5 maybe? As it is release soon.

**Comment by mahagr** [comment]
I cannot see Joomla 4 updating to that, which means that using BS5 would result in a broken looking site in J4.

**Comment by sanek4life** [comment]
> 
> 
> I cannot see Joomla 4 updating to that, which means that using BS5 would result in a broken looking site in J4.

[https://github.com/joomla/joomla-cms/issues/30805](https://github.com/joomla/joomla-cms/issues/30805)

The stable version of Bootstrap 5 will be released this December. The stable version of Joomla 4 will be with Bootstrap 5, since the developers wrote that if the stable version of Bootstrap 5 is released before the stable version of Joomla 4, then it will be in the CMS.

**Comment by Flowman** [comment]
> I cannot see Joomla 4 updating to that, which means that using BS5 would result in a broken looking site in J4.

Can we make it easy switchable in front-end for templates?

**Comment by mahagr** [comment]
So Joomla 4 WILL NOT ship with BS5. That means that any BS5 template will not be compatible with the components. Great.

**Comment by N8Solutions** [comment]
> 
> 
> > I cannot see Joomla 4 updating to that, which means that using BS5 would result in a broken looking site in J4.
> 
> [joomla/joomla-cms#30805](https://github.com/joomla/joomla-cms/issues/30805)
> 
> The stable version of Bootstrap 5 will be released this December. The stable version of Joomla 4 will be with Bootstrap 5, since the developers wrote that if the stable version of Bootstrap 5 is released before the stable version of Joomla 4, then it will be in the CMS.

@sanek4life I think you misread the comments from the devs in those other threads. Nowhere did they say that J4 would definitely ship with BS5. In fact, in this thread https://github.com/joomla/joomla-cms/issues/29944#issuecomment-654227683 George Wilson said the following:

> Alpha doesn’t change much. Last time the alpha was 2 years before stable bs4 was released (and there were large differences between the versions). And we’re targeting j4 now for end of this year. If bs5 is in something like RC before we go stable we can investigate but right now it’s still not really an option for us

So this means that J4 WILL NOT ship with BS5.

**Comment by dmleeman** [comment]
So Joomla 4 apparently now is definitely shipping with Bootstrap5

This is a link to an J4 beta 7 site (by one of the dev team leaders) running with BS5: https://learnjoomla4.com/

Still in development, but the performance is very good (after all, that is the bottom line)

But, then, it should be when hosted on cloud managed VPS hosting :)

**Comment by mahagr** [comment]
Closing the issue as latest builds have added Bootstrap 5 support.
