### ISSUE TITLE
[Gantry 5.5] Selecting Edit in Array item prohibits me from entering it

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2707]
See screenshot. Create new array item and you will see you cannot open it. Just stays in Edit Mode when try to return to click.

![Screen Shot 2020-09-23 at 3 54 41 PM](https://user-images.githubusercontent.com/5002814/94068664-203d0800-fdb5-11ea-9202-1a0120b6a635.jpg)

**Comment by mahagr** [comment]
Confirmed. This looks to be JS issue. Also clicking on the "Windows" icon below doesn't include the new items you just added.

**Comment by mahagr** [comment]
Same issue is in Joomla 3.9 and WP.

**Comment by simmonsr** [comment]
fix confirmed
