### ISSUE TITLE
[Gantry 5.5] Atoms no longer allow for dragging after one move.

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2708]
Move an atom to the dock. Try moving it again, you should see error in console:

![Screen Shot 2020-09-23 at 4 18 27 PM](https://user-images.githubusercontent.com/5002814/94070842-84ad9680-fdb8-11ea-9120-1edb97390902.jpg)

**Comment by mahagr** [comment]
Confirmed.

**Comment by simmonsr** [comment]
fix confirmed
