### ISSUE TITLE
Gantry 5 not supporting Advance Module Manager

### ISSUE THREAD

**Issue by oxido21** [gantry/gantry5#2710]
Hi guys,
There is a problem with Gantry 5, does not support AMM (again).
I have set a module on a position and set that module to be visible only on 1 specific menu, but not in the childs of that menu, is not working, and i found this:
https://www.regularlabs.com/forum/advancedmodulemanager/43368-possible-issue-with-amm#67722
https://www.regularlabs.com/extensions/advancedtemplatemanager/tutorial#not-compatible-with

It is possible to fix this? or can we somehow to deacivate the Assignments in the template, to allow the AMM to take control over?

**Comment by mahagr** [comment]
Good idea. I will look if it is possible to do that.

**Comment by mahagr** [comment]
@oxido21 Please test CI build from Gantry site, it should have component setting to disable assignments from Gantry.

**Comment by oxido21** [comment]
@mahagr It seams to be working, but there is 1 more error.
When I set "Use Gantry 5 Assignments" to "NO", if I access the Hydrogen template from: Templates menu, I get this error:  Please install Gantry 5 Framework!
But I don't get the error if I access the template from: Components > Gantry 5 Themes > Available themes > (my theme)

**Comment by simmonsr** [comment]
Added to change to RT Themes (will be available in next themes update).

**Comment by mahagr** [comment]
@oxido21 If you go to Templates > Styles and pick up Gantry style, it should not have the warning, but display options to go to Gantry component instead: [ Styles ] [ Layout ] [ Page Settings ]. Are you using advanced template manager? Try disabling it temporarily to see if it works without.

**Comment by oxido21** [comment]
@mahagr I have tryed to use advanced template manger before I decided to report this problem, but in this moment, no I don't use Advanced template manager,  I have only the Advanced module manager, but I disabled this allso.
But if I set "Use Gantry 5 Assignments" to NO and I clear the cache from Joomla menu: System > Clear cache, I get that error [[img](https://i.imgur.com/q4UuoiA.jpg)] .

**Comment by mahagr** [comment]
@oxido21 Try again. If it doesn't work, Joomla may not be able to update plugin files as the overridden class is now forced to load in admin.

You should not see the warning, but instead buttons to go to Gantry admin.

**Comment by oxido21** [comment]
@mahagr is not working, there is the same error "Please install Gantry 5 Framework!"

**Comment by simmonsr** [comment]
I can confirm issue from user when I shut off assignments

![Screen Shot 2020-10-07 at 10 22 16 AM](https://user-images.githubusercontent.com/5002814/95351634-099fb200-0887-11eb-8114-4f648ad7f4fb.jpg)

**Comment by simmonsr** [comment]
Using Gantry DEV and Helium DEV

**Comment by oxido21** [comment]
This is gonna be ready for the next update?

**Comment by mahagr** [comment]
Latest CI should be good. Manifest file was just missing the new folder.

**Comment by simmonsr** [comment]
Confirmed

**Comment by oxido21** [comment]
Hi,
I think gantry is still trying to control how themes are assigned in joomla.
I use, Joomla 3.9.24, Gantry 5.4.37, Advanced Template Manager (ATM) and Hikashop 4.4.0.
"Use Gantry 5 Assignments" in gantry is set to NO.
In my templates, i have created 3 Outline/Templates: Home, Category and Product.
If I open the Product template, and I access Assignments, because I use Advance Template Manger Pro, i have the option to set this template to be active for a specific type o page on Hikashop. 

- For template Product, I select Hikashop Page types = Product page.
- For template Category I select Hikashop Page types = Products Listing.
- For template Home I use the "Assign to Menu Items" and select the Home menu.

I have installed 3 other template (not gantry) on a second website to test if Advanced Template Manager is working well, and it does (at least with those templates).
So it looks like there is still a conflict.

@mahagr if you want, I can give you access to my website to take a look
