### ISSUE TITLE
Add new Google Analytics tag gtag.js to analytics atom

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#2711]
By updating your current Google Analytics tag (analytics.js) to the latest tag (gtag.js), you will benefit.

**Comment by mahagr** [comment]
@simmonsr Could you check this one?

**Comment by simmonsr** [comment]
Ok, I updated the analytics atom to use gtag.js. Force SSL appears to be on by default, so I removed that option. Also Debug Mode is done via Chrome extension:

https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en
