### ISSUE TITLE
Beta 5.5.0 WordPress totally refreshes layout defaults

### ISSUE THREAD

**Issue by Wicko-Design** [gantry/gantry5#2712]
When I uploaded the gantry 5.5.0 and then Helium 5.5.0 to my existing WordPress I found that the default base ouline Header and Footer layouts were refreshed to the Helium defaults. Previous version was 5.4.34.

**Comment by mahagr** [comment]
@simmonsr Can you test this one?

**Comment by mahagr** [comment]
@Wicko-Design What did you have in there? Screenshot?

**Comment by Wicko-Design** [comment]
Footer layout before update
![Screenshot 2020-10-06 at 10 48 24](https://user-images.githubusercontent.com/11837048/95186186-9ed87300-07c1-11eb-82e9-5181aecaac61.png)

Footer layout after update restored to default. 
![Screenshot 2020-10-06 at 10 47 53](https://user-images.githubusercontent.com/11837048/95186202-a39d2700-07c1-11eb-9c6c-080c1793c57b.png)

**Comment by simmonsr** [comment]
Yah, good catch @Wicko-Design. @mahagr update is overriding custom folder. It didnt do this before.

**Comment by simmonsr** [comment]
Updating via Appearance -> Themes -> Add New.

**Comment by simmonsr** [comment]
Downgrading to 5.4.35 or updating from 5.4.35 -> dev keeps the custom folder. But going to 5.5.0 to either of those versions causes an override.

**Comment by simmonsr** [comment]
Ok, issue here is that 5.5.0 builds come with /custom/ folder ALREADY in package @mahagr .

**Comment by mahagr** [comment]
Yeah, it's my local install. Let me fix that.

**Comment by mahagr** [comment]
I'll send the fixed builds in a second.
