### ISSUE TITLE
Beta 5.0.0 layout columns scrolling

### ISSUE THREAD

**Issue by Wicko-Design** [gantry/gantry5#2714]

**Comment by Wicko-Design** [comment]
After updfating Gantry and Helium to 5.5.0 on WordPress that previously had 5.4.34. 
When I go to the layout page in Helium I see that the Particle and Layout columns scroll together. Previously in 3.4.34 these would scroll seperately making it easier to drag new positions and particles to lower locations in the layout.

Screen shot is 3.4.34
<img width="1352" alt="Screenshot 2020-10-03 at 11 32 07" src="https://user-images.githubusercontent.com/11837048/94989380-48262b80-056c-11eb-98bf-5bea6848b80e.png">

Screen shot in 5.5.0
<img width="1358" alt="Screenshot 2020-10-03 at 11 32 23" src="https://user-images.githubusercontent.com/11837048/94989388-5d02bf00-056c-11eb-868c-67dde0207219.png">

**Comment by simmonsr** [comment]
I can't replicate. Scroll bar shows fine. Tested in both Gantry 5.5 and Gantry 5.4.35

![Screen Shot 2020-10-05 at 11 20 22 AM](https://user-images.githubusercontent.com/5002814/95105444-cca7b400-06fc-11eb-8127-e2587a832a18.jpg)

**Comment by simmonsr** [comment]
Do you have browser extension that disables scroll bar?

**Comment by mahagr** [comment]
Works for me, too.

**Comment by Wicko-Design** [comment]
ok reviewing this issue again it appears to only effect FireFox on Mac 81.0
Tested ok in Chrome

**Comment by mahagr** [comment]
I'm using the same version of Firefox in Linux, no issues here.

**Comment by Wicko-Design** [comment]
On further investigation I have discovered that the issue with with JetPack plugin that is linked to Woocommerce. It was generating a js error visible in console inspector. 
If I deactivate that the the issue is resovled. 
So not a Gantry issue.
