### ISSUE TITLE
G5.5/J4 - missing icon in Gantry 5 admin on outline selection dropdown.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2715]
![2020-10-06_12-10-18](https://user-images.githubusercontent.com/11683218/95196581-2f1db480-07d0-11eb-96d7-cce414d77a7d.png)

**Comment by mahagr** [comment]
Like discussed in FA5 issue, we need to solve this in a way which either doesn't use the character code in CSS or makes it a variable, which can be changed based on the icon set we're using.
