### ISSUE TITLE
Gantry 5 / how to clone particles on the same page

### ISSUE THREAD

**Issue by marvays** [gantry/gantry5#2719]
Hi. I am newbie in G5.
I have any "Quotes" like references. I need clone one on the some page. 
I don't want to create new citations and edit styles, but clone an existing one and just change the text. How?
![screenshot-bigholding-cz svethostingu-tmp cz-2020 10 16-06_29_30](https://user-images.githubusercontent.com/72960077/96213654-d4c3e700-0f79-11eb-8395-f65df1ba0736.png)

**Comment by mahagr** [comment]
Currently Gantry doesn't support cloning particles within the same page. As a workaround create a dummy layout and use it as your template for particles.

**Comment by blizam** [comment]
You can also use the Particle Defaults to set up all your base settings/content if you're mostly using the particle in the same way everytime.

**Comment by chatman1974** [comment]
> Hi. I am newbie in G5.
> I have any "Quotes" like references. I need clone one on the some page.
> I don't want to create new citations and edit styles, but clone an existing one and just change the text. How?
> ![screenshot-bigholding-cz svethostingu-tmp cz-2020 10 16-06_29_30](https://user-images.githubusercontent.com/72960077/96213654-d4c3e700-0f79-11eb-8395-f65df1ba0736.png)

Open your Base Outline. First, add your needed particle to some section that where you want to add it in Base Outline. Then open to your desired Outline. Add same particles to same section that where you add it from Base Outline. Then click to your added particles gear icons and set up them as inherit included "Particle Attributes" and "Block Attributes" from Base Outline.
