### ISSUE TITLE
Error installing joomla-tpl_g5_hydrogen_v5.4.36.zip

### ISSUE THREAD

**Issue by Gerlof** [gantry/gantry5#2720]
It appears thar folder 'custom' is missing' in joomla-tpl_g5_hydrogen_v5.4.36.zip.
Therefore the update/install will not succeed.

Quick solution: 
1) unzip the file in the tmp folder
2) manually add an (empty) folder 'custom'
3) and install using the tab 'Install from Folder

**Comment by marktaylor46** [comment]
we're fixing right now - should be ok in a few minutes

Regards, Mark.

**Comment by marktaylor46** [comment]
Fixed now.

Regards, Mark.

**Comment by Tazzios** [comment]
Just did the update twice and in both cases the hole website goes down. Just a white page also the administrator backend

**Comment by marktaylor46** [comment]
Make sure that you downloaded the Hydrogen template again and used that - we had to update ther package.

Regards, Mark.

**Comment by Tazzios** [comment]
I think i have a conflict with other plugin/component. It occurs also on different websites at different hostings. 
Clean joomla install and installing gantry  5.4.36 no problem.
Now find out which one, with no error in the logfiles :(
