### ISSUE TITLE
Issues with Fabrik

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#2721]
After the update of the template in Joomla 3.9.22 to version 5.4.36 I got the following message.

Fatal error: Cannot declare class Joomla \ CMS \ Form \ FormField, because the name is already in use in administrator \ components \ com_fabrik \ classes \ 39 \ FormField.php on line 22

After investigation, it appeared that the system plugin from Fabrik with version 3.9.2 or the component is causing the problems.

**Comment by EdSantos754** [comment]
Same here.

If you are stuck and can't access the backend anymore (like I was), you can change the order of fabrik's system plugin:

> One thing you could try is making sure that the Fabrik system plugin loads first. We have to override the standard JForms file in order to provide the "repeat" settings on the backend. So if something else explicitly includes that J! file before our plugin gets to it, this can cause issues.
>
> Using a database client of your choice (like phpMyAdmin), in the #__extensions table, find the row with 'name' plg_fabrik_system, and set the 'order' to -1.

More info here: https://fabrikar.com/forums/index.php?threads/fatal-error-on-admin.51977/

**Comment by mahagr** [comment]
Should be fixed in latest CI!
