### ISSUE TITLE
white screan since last update

### ISSUE THREAD

**Issue by sistaidan** [gantry/gantry5#2722]
hi,
first, i apologise for my english, it's not my native language.
I have an issue, since last gantry update, i can't  fix. i have a white  screan instead of my site.
![error](https://user-images.githubusercontent.com/17512446/96924251-ab8fe300-14b2-11eb-9de8-dbe7c57c9ff0.jpg)
![error](https://user-images.githubusercontent.com/17512446/96924268-b2b6f100-14b2-11eb-941f-c34f5a62fefb.jpg)
Thanks for any help.
nadia

**Comment by mahagr** [comment]
Looks like caching issue.
