### ISSUE TITLE
Changing layouts on an iPad

### ISSUE THREAD

**Issue by PeterAG** [gantry/gantry5#2724]
Hi,
The iPad is apparently not taken seriously by many in the development community, (as I was told just don't make changes on an iPad), but I think many want to use it to do serious work.  My issue is this: when changing the layout, moving a particle from one location to another, the particle is duplicated and then seems to appear in two places —the original place in the layout and the new place where it was moved to.  I would place the screencast showing this, but I'm reluctant to advertise my development site url.

Another iPad issue, is that, when I'm in layout page, merely scrolling up or down can move a particle unintentionally.  When this happens I'm aware something was moved, but I can't tell what.  

Effectively, this does make the iPad unusable for making gantry 5 changes, but I can use most of the other components, except when I can't scroll drop-down [menus past what is visible](https://github.com/joomla/joomla-cms/issues/31083). 

I use the 1st Gen iPad Pro running ios14.  I always run the latest ios.  

I hope the community takes this seriously, as it will factor into my choice of what I use in the future.  

Stay happy and well.  

Peter

**Comment by mahagr** [comment]
As a workaround, you can use Chrome browser. Safari has been buggy for ages.

**Comment by PeterAG** [comment]
Thanks man.  But the same issues occur in Chome.  Seems to be an ios issue more than a browser one.

**Comment by mahagr** [comment]
Unfortunately, I don't own an iPad, I will need to pass this one to someone else to test.

**Comment by barayuda** [comment]
Sorry jump in, I think that bug from Joomla backend theme?
if you change to classic backend theme, it still happen?

**Comment by PeterAG** [comment]
> Sorry jump in, I think that bug from Joomla backend theme?
> if you change to classic backend theme, it still happen?

Thanks but I never changed the backend theme and don't know how.

**Comment by rafaellizarazu** [comment]
It's a pity that you can't use iPad (iOs 14) to design your web.
It does not work neither with Hathor or Isis the two Joomla Admin templates. Any other ideas how to make layouts work with your iPad?
