### ISSUE TITLE
Bug in frontend "select an image" for an article with Joomla CMS

### ISSUE THREAD

**Issue by Johann009** [gantry/gantry5#2725]
Hello,

I have a problem common to three of my sites.
version of joomla 3.9.22 with Gantry 5 Helium template 5.4.36 and JCE plugin 2.8.18

When I want to modify an article in frontend I can add an image in the article, it works.
If I want to add an introductory image or a full image the window opens and crashes (impossible to find the IP server address of index.php).
Same problem with other extensions such as DPCalendar for example...

In backend it works perfectly. The problem is in frontend.

I tried to reinstall versions 3.9.20 and 3.9.21 of joomla to test - same bug !
I reinstalled JCE pluggin 2.8.18, same bug !
I test it with protostar template and it works fine!
So I think it's a problem with Gantry or Helium template !?

What's going on please???

Thank you for your help

![im1](https://user-images.githubusercontent.com/67013945/97223213-c1154d80-17cf-11eb-8c2a-a0eb5e920521.jpg)

![im2](https://user-images.githubusercontent.com/67013945/97223232-c6729800-17cf-11eb-8236-17e0d99dd5fd.jpg)

**Comment by Johann009** [comment]
in any case it seems to be a conflict between JCE and the Template Gantry5 - Helium ...
Maybe there is a conflict between RocketTheme and JavaScripts? Is it possible to change settings in the template parameters to solve this conflict?

**Comment by mahagr** [comment]
I don't think it's JS issue, it looks like double // in the URL or something similar. @simmonsr can you take a look?

**Comment by Johann009** [comment]
I add that 
with the Non WYSIWYG editor it works fine.
with Protostar template it works well with JCE.

Sakri, the developer of JCE plugin thinks that the problem is related to the template... and that RocketTheme products are unfortunately known for their JavaScripts conflicts.... Maybe it's something else?....
Thanks for your help, it's very embarrassing for front-end users...

**Comment by marktaylor46** [comment]
I replicated this but the answer is your .htaccess file. Make sure that you rename htaccess.txt in your joomla root directory to .htaccess. Then ensure that the rewritebase is correct within that.

Regards, Mark.

**Comment by Johann009** [comment]
Yes, the .htaccess. file is correctly renamed.The rewrite base is 0644 inside this directory, even in 0777 it doesn't change anything, same problem.
It worked well before! Now it doesn't work anymore. I tried to update with old version of Gantry5, Joomla, it doesn't change anything !  I can't find the update that created this bug!? 

That's it, I found it !! I just downloaded an old version of JCE plugin : version JCE 2.7.20 and it works !

so where is the compatibility problem with Gantry and JCE 2.8.18 ????!...

**Comment by Johann009** [comment]
I use Helium template v.5.4.36

**Comment by marktaylor46** [comment]
No, the problem is with JCE - not Gantry in that it expects the rewrite base in htaccess to be set. rewritebase is "/" or "/xxxx/" it's nothing to do with file permissions (644 or 755). So, it's a bug in the new JCE version - report it to them.

Regards, Mark.

**Comment by Johann009** [comment]
ok, thanks for your answer, I'm writing to Sakri from JCE and give you his answer.

**Comment by Johann009** [comment]
JCE confirms a Javascript conflict with the latest script libraries of version 2.8.18
I go back to version 2.8.17 while waiting for the next update.
Thank you for your help and your listening.
Warm regards
