### ISSUE TITLE
Remove PHP compiler for LESS 

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#273]
As requested by Henning, I am adding links to the three active PHP compilers for LESS.

https://github.com/oyejorge/less.php 
https://github.com/mishal/iless 
https://github.com/php-less-compiler

**Comment by w00fz** [comment]
Thank you! I really like the first one, seems to be quite active.

**Comment by mahagr** [comment]
Just depends on how customizable those are; hoping the best!

Have anyone tried any of them?

**Comment by coder4life** [comment]
https://github.com/oyejorge/less.php

Is one that trailed closely after the leafo compiler, however I heard it is very slow to execute operations.  However that was a few months ago and things could have been improved since then.  The other two are news to me.

**Comment by alisamii** [comment]
If the process for compiling is triggered with gulp, it may simply be easiest to require-dev (or require, as the case may be) the gulp-less plugin.

https://github.com/plus3network/gulp-less

**Comment by mahagr** [comment]
We have some parts that are compiled beforehand and not meant to be changed (like Nucleus) and then parts we need to compile every time someone changes settings in admin.

For static CSS files we are not using PHP compiler at all.

**Comment by mahagr** [comment]
I'm actually thinking of removing LESS support from Gantry. @w00fz @newkind ?

**Comment by newkind** [comment]
I don't think we need it when we have SASS.

**Comment by w00fz** [comment]
I'd gladly have it, if it was a user-contribution. I don't think we should work on implementing it, it's not something we will ever need, we are pretty much set on SASS and it has been working much better than LESS.

If anyone is interested in LESS and wants to contribute to its implementation, we will welcome it.

**Comment by mahagr** [comment]
The issue is that the implementation was not being maintained and I don't think it has ever worked in the way it was supposed to (I never finished the implementation). The files can still be found from the older releases, but I think its better not to ship with unmaintained code.
