### ISSUE TITLE
Mega Menu - expanded sub-items?

### ISSUE THREAD

**Issue by TheSoulrester** [gantry/gantry5#2735]
Hey, how is it possible to auto-expand all sub-items of an parent element in a mega menu?

it should look like here:
![image](https://user-images.githubusercontent.com/7083599/102062310-d6345300-3df4-11eb-8d0a-a919d34b2f65.png)

but for now it looks like this: 
![image](https://user-images.githubusercontent.com/7083599/102062411-fb28c600-3df4-11eb-88f5-c238a257c8f5.png)

**Comment by mahagr** [comment]
I don't think the menu supports that out of the box. You can create your own menu particle and do the layout in there.

**Comment by TheSoulrester** [comment]
how? i'm new with gantry 5 :(
