### ISSUE TITLE
Add <canvas> block tag to Gantry5 as a Section

### ISSUE THREAD

**Issue by dmleeman** [gantry/gantry5#2736]
This is my very first pull request so, please, don't go geek ballistic if it's in the wrong place 👍 

Is there a way to add <canvas> block element as a section in Gantry5? I'm running 5.4.36 currently and currently learning vanilla javascript.

**Comment by marktaylor46** [comment]
This isn't a pull request? You've just raised an issue ticket? 

A canvas tag is not a section and a section is not a canvas? 

If you want a canvas tag then just add it in a customhtml particle (you can also add your script there too if you really need to but it's usually best to put that on the page settings tab of the base outline - unless your script is actually producing output inline dynamically).


Regards, Mark.

**Comment by dmleeman** [comment]
lol, I need to learn github. Sorry Mark

I did try <canvas> inside customhtml but the output code did not appear to be valid use of the tag.

I shall close the ticket and take another look at it because my approach may be altogether wrong.

**Comment by marktaylor46** [comment]
No problem :) 

A canvas tag is perfectly valid (just like any other html tag) to be used inside a customhtml particle or module.

Regards, Mark.
