### ISSUE TITLE
Joomla 3.x hydrogen "Styles / Navigation colors / Overlay" setting doesn't apply

### ISSUE THREAD

**Issue by 24images** [gantry/gantry5#2744]
Hi,

I try to set in "Styles / Navigation colors / Overlay" a different color. But whatever I am setting it doesn't apply...
Any clue ????

Thank you

**Comment by chatman1974** [comment]
> I try to set in "Styles / Navigation colors / Overlay" a different color. But whatever I am setting it doesn't apply...
> Any clue ????

What you done for it? And can you explain it more clearly to what you want to do exactly?
