### ISSUE TITLE
setTemplate() can not select gantry template styles 

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#2746]
hi.
when i want use settemplate() function to set specific Gantry template style for example with id =11. but always my page render with default gantry style.
i write a my own joomla component and i want load my page with other than default joomla template.i write the below code and it work for other template like beez or protostar and can select different styles but in gantry always return Default gantry template,(i use Jdump compnent for debug and use dump(); )

```
//$templateStyleId = trim($params->get('course_templatestyle'));
$templateStyleId = 11; //use this sample only for imagine when i say in above id=11.
		$app = JFactory::getApplication();
		JTable::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_templates/tables');
		$tmplStyle = JTable::getInstance('Style', 'TemplatesTable');
		$tmplStyle->load($templateStyleId);
    dump($tmplStyle,"tmplStyle");
		
		if (!empty($tmplStyle->template)){
		  $app->setTemplate($tmplStyle->template, (new JRegistry($tmplStyle->params)));
		}
		$t = $app->getTemplate(true);
    dump($app,"app");
    dump($t,"getTemplate");
```

**Comment by mahagr** [comment]
Gantry does not set the template style -- that part is handled by Joomla. In which event are you trying to set the style?

**Comment by saman222** [comment]
i write my own plugin to change for my component to override gantry work in this line:
https://github.com/gantry/gantry5/blob/4a557f9f42b1a20bd73b7adc38c4e6970e8d1650/platforms/joomla/plg_system_gantry5/gantry5.php#L246

also my plugin need to be after ordering in the plugin list of joomla to set custom selected gantry theme.
