### ISSUE TITLE
Question: does Gantry change the base_url parameter?

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2747]
Hello!
I'm running Grav 1.6.3.1 with a Helium template.
Does the Gantry 5 or Helium change the 
```
{{ base_url }}
{{ page.url }}
```
parameters somewhere?

The problem is that I'm having problems running a `simple-search-plugin`.  All settings are copied from skeleton to mine project and only the difference between demo skeleton and mine project is that I'm using `Gantry 5`.

So, the `{{ base_url }}` and `{{ page.url }}` have to return base URL, while it returns a base + slug.
As for example, no matter at which page I am the right `base_url` should return: "/grav-blog/" (folder's name)
But in my case it returns `/grav-blog/some-page/`

More info regarding it I've posted [on forum](https://discourse.getgrav.org/t/simple-search-plugin-getting-error-404-of-misconfigured-urls/14606/2)

**Comment by mahagr** [comment]
Were you able to figure out the issue?

**Comment by 01Kuzma** [comment]
It seems that issue which I have is more oriented to a template implementation rather that to Gantry.
So, probably it's not related to gantry. If I will find out more - I will post some information
