### ISSUE TITLE
A options of plugin placed as Short Code in Custom HTML are ignored

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2749]
I've found a issue: placing a [Grav Youtube Plugin](https://github.com/getgrav/grav-plugin-youtube) into Gantry 5 `Custom HTML particle`.

The Short Code processing is turned on (two checkboxes). 
So, the youtube frame is loaded but it's ignoring plugin's options. As for example it ignores lazy load, Modest branding...
While plugin perfectly works placed in markdown page

**Comment by 01Kuzma** [comment]
Also tested on fresh install of Grav 1.7.3, Gantry 5.4.36 and Helium 5.4.36.
Placed a short-code from grav youtube readme - `[youtube color=white autoplay=1]https://www.youtube.com/watch?v=BK8guP9ov2U[/youtube]` into custom html particle, lazy load enabled

**Comment by 01Kuzma** [comment]
@mahagr any thoughts regarding this?

**Comment by 01Kuzma** [comment]
In order to utilize all params plugin should be called in markdown style:
`[plugin:youtube](https://www.youtube.com/watch?v=BK8guP9ov2U)`
But this doesn't work in `Custom HTML` particle

**Comment by mahagr** [comment]
Looks like there's a bug in Youtube plugin shortcode. I got the iframe working, but it won't lazy load because the plugin doesn't support it. White and autoplay options are there, but autoplay needs to be enabled from the iframe itself.
