### ISSUE TITLE
Unable to Get New Fonts into Base Layout

### ISSUE THREAD

**Issue by ThunderVamp9** [gantry/gantry5#2750]
We are working on building a template, and need to add fonts that are not Google fonts. The fonts need to be able to be selected in Core Styles like any other font. We note that Roboto is listed in there as a local font. Nothing we do seems to add anything else as a local font though.

We thought we had followed directions properly, using Gaspar as an example, but nothing has worked.

Screenshots show:

#1: Code is added to our YAML file for the Gaspar font
#2: Code is added to custom.scss
#3: This is how we want the font to be able to be selected, just like any other font. We don't want to have to return to CSS for this, or have the client who is buying the new font have to get into CSS
#4: The new font is not an option to be chosen, not even as a local font. Roboto is, though.

Is something being missed? Not done right?

![screen1-yaml-code](https://user-images.githubusercontent.com/20704423/105730144-01ce5100-5efc-11eb-87d2-b3384b1031aa.jpg)
![screen2-custom-scss-code](https://user-images.githubusercontent.com/20704423/105730145-0266e780-5efc-11eb-8abc-64e67a880b65.jpg)
![screen3-area-fonts-needed](https://user-images.githubusercontent.com/20704423/105730146-0266e780-5efc-11eb-95dc-bf99b8f028fb.jpg)
![screen4-added-font-not-an-option](https://user-images.githubusercontent.com/20704423/105730141-0135ba80-5efc-11eb-8a82-2991496feb64.jpg)

**Comment by ThunderVamp9** [comment]
UPDATE: I found I was adding these into my custom YAML file and instead added them to theme.yaml, and now they show up as a local font. But they still don't actually work/load.

**Comment by ThunderVamp9** [comment]
UPDATE: Finally got it working. Closing.

**Comment by mahagr** [comment]
Make sure you don't update the theme without backing up and restoring the modified files. :)
