### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by sanek4life** [gantry/gantry5#2752]
Will Gantry 5 use Bootstrap 5 for Joomla 4?

Joomla! 4.0 will ship with Bootstrap 5: [https://developer.joomla.org/news/839-joomla-4-0-will-ship-with-bootstrap-5.html](https://developer.joomla.org/news/839-joomla-4-0-will-ship-with-bootstrap-5.html)

**Comment by simmonsr** [comment]
Yes, Gantry 5 will utilize BootStrap 5 on Joomla 4.
