### ISSUE TITLE
Gantry5 icon is not visible in Grav 1.7.3

### ISSUE THREAD

**Issue by giminni** [gantry/gantry5#2754]
Today I installed the gantry plugin into grav v1.7. The icon is nor visible in the grav plugin list nor in the grav admin sidebar.
Installed:
- Grav CMS v1.7.3
- Admin Panel v1.10.2
- Gantry 5 Framework v5.4.36

**Comment by w00fz** [comment]
This is fixed in the develop branch of admin plugin and will be available in v1.10.3
