### ISSUE TITLE
Conflict between BreezingForms PayPal button and Gantry5/Helium template

### ISSUE THREAD

**Issue by Johann009** [gantry/gantry5#2756]
Hello,

my site is under joomla 3.9.24, I use version 5.4.37 of Gantry with the Helium template, and BreezingForms Pro 1.9.1 Stable (build 941).

At the end of my BreezingForms form I propose a PayPal payment. When I use the Joomla Protostar template, the PayPal payment page opens and the online payment is processed correctly. The form is therefore correctly configured.
When the same form is published under the Helium template with Gantry 5 the execution of the PayPal button does not happen correctly, a blank page is displayed ... When I set the debugging parameters to system debugging "on" in the system configuration of Joomla it works!!! So there is a bug between Gantry5/Helium and the PayPal button of BreezinForms !

Have you ever seen this kind of conflict? What can I do to solve this problem !?

Link to the form under Protostar:
https://jazcompreparevotresite.com/test-2
Link to the form under Gantry5/Helium:
https://jazcompreparevotresite.com/test

Thank you for your help.
Johann

**Comment by Johann009** [comment]
Ok. 
I've just found a solution to this problem... but it's still interesting that I point it out to you:

* if the BreezingForms form is inserted in the Gantry5 page as an instance-module in the section of my choice, the PayPal button function does not work (blank page)
* if I create a BreezingForm page from the menu with the name of the form I want to display, then the PayPal button works correctly!

Why this difference?

**Comment by mahagr** [comment]
It's likely that the form needs database entry in the modules table in order to work. It's just a guess, though.
