### ISSUE TITLE
Changing the display order of list in every "Style Group" at Theme Admin / "Styles Tab"

### ISSUE THREAD

**Issue by chatman1974** [gantry/gantry5#2759]
Hi all.
What determining the display ordering of Styles Listing in Theme Admin/Styles tab? I want to change the display order of sections in styles tab???
I want to make custom display ordering for every Styles Group. I mean custom display ordering for "type: core" and type: Configuration" styles.
Thanks...
![ordering](https://user-images.githubusercontent.com/69113726/107769535-31c58300-6d49-11eb-8ea2-7961ff2fcc4c.JPG)

**Comment by mahagr** [comment]
Those are just ordered by the appearance in the YAML file they are defined in.
