### ISSUE TITLE
Menu Items - narrowing the gaps

### ISSUE THREAD

**Issue by essiele** [gantry/gantry5#276]
I'd like to see the gap between the parent and sub-menu items slightly decreased...
![g-main-active-drpdwn](https://cloud.githubusercontent.com/assets/2575283/7662607/53d4d1d2-fb56-11e4-896f-15691bf87a53.png)

In addition, the gap between each sub-menu items could also be narrowed...
![sub-level-items](https://cloud.githubusercontent.com/assets/2575283/7662625/9b7442c0-fb56-11e4-8479-7dbc2b10cfa9.png)

Thank you, awesome bunch!

**Comment by kevlardev** [comment]
This is really a cosmetic thing that can be adjusted for each persons specific design needs. Each theme will likely have very different spacings and gaps based on visual effects as well as offset needs and is best left to be adjusted on a theme by theme basis or user preference basis.
