### ISSUE TITLE
Adding the canvas block element to Gantry5 structure

### ISSUE THREAD

**Issue by dmleeman** [gantry/gantry5#2761]
Is there a way to add the canvas tag as a parent block level element?

I would rather not contain it within a module or class in certain instances.

**Comment by mahagr** [comment]
I think the allowed tags are currently 'div', 'section', 'aside', 'nav', 'article', 'header', 'footer' and 'main' for the grid element.

See `src/classes/Gantry/Component/Layout/Version/Format2.php` line 23.

**Comment by dmleeman** [comment]
Looks like core code - I will leave it unbroken!

**Comment by mahagr** [comment]
Why do you need to have a canvas in block level (instead of having it inside the module/particle)?

**Comment by dmleeman** [comment]
Like div, footer, section etc. canvas is a block level element, working with some tutorial scripts it was required that <canvas> was treated as a block for javascript (rather than embedded in div or class). It is not vital.
I shall close the issue
