### ISSUE TITLE
Error after updating to Grav 1.7.6

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#2763]
I've just updated Grav to version 1.7.6 and four related plugins (admin, flex objects, login and form)
I use also a Gantry 5 paid theme (and of course Gantry 5 plugin,latest version)
After the uptdate I have this "Critical error" message
0 - Argument 2 passed to Grav\Plugin\Admin\Admin::mergePost() must be of the type array, string given, called in /Applications/MAMP/htdocs/2febbraio/user/plugins/admin/classes/plugin/Admin.php on line 919

I'm working in local environment, but I need to go live ASAP

I also opened this new issue in Grav admin plugin:  https://github.com/getgrav/grav-plugin-admin/issues/2074

**Comment by mahagr** [comment]
Fixed in Grav. See the Grav Admin issue.

**Comment by beamaria** [comment]
@mahagr :Thanks Mathias!
