### ISSUE TITLE
edit php files of a plugin

### ISSUE THREAD

**Issue by andreascarfo** [gantry/gantry5#2764]
Hi all,
I would like to edit some files of some plugins. It says "This template can be overridden by copying it to yourtheme/... "
But it doesn't work.
I tried both in the root than in the "custom" folder of both my child-theme than of my g5_helium.

Wordpress 5.6.1 + Helium + Child theme.

Does anyone have any idea?

**Comment by mahagr** [comment]
Overriding PHP classes is generally not a good idea, but basically, you can do it by registering autoloader which loads your custom classes instead of the original ones.

**Comment by andreascarfo** [comment]
I don't want to override a class but some files of plugin and it is previded by the creator.
I will look forward how to create an autoloader.
Thanks.
