### ISSUE TITLE
Lightcase / Gantry5 for Wordpress: Want to change close button link

### ISSUE THREAD

**Issue by vindhaus** [gantry/gantry5#2765]
Hi,

I've been beating my head against the wall about this.

I'm trying to change the close button, so that when someone clicks it, it will close to another section on my website. I've tried all sorts of scripts in trying to call the element and change it with vanilla JS, attempting to use the hooks as laid out in the Lightcase docs, but nothing has helped so far. I have jQuery enabled and enqueued, but so far no jQuery scripts have helped either.

Does anyone have any tips, tricks, websites, StackOverflow threads they could point me to? I've been able to do this with other lightboxes (FancyBox, etc.) but Lightcase has been a no-go so far and I'd rather try figuring this out since it's packaged with Gantry 5.

Thanks.

**Comment by mahagr** [comment]
You likely need to hook an event to the click action of the button. I'm not a JS expert, though, so I'm not sure if I can help more.

**Comment by vindhaus** [comment]
Yeah, I tried the OnClose hook but the issue I kept running into was getting an error where it was undefined... even though I defined it in the script. What I read was that Wordpress acts weird with JQuery, so when I did the standard work-around, it ended up not throwing any error...but the action never took.

**Comment by mahagr** [comment]
Closing as this is not directly related to Gantry 5 Framework.
