### ISSUE TITLE
Acymailing Newsletter subscription form widget and gantry

### ISSUE THREAD

**Issue by jasonmac75** [gantry/gantry5#2767]
I have an issue with Acymailing Newsletter subscription form widget, the support team says it does not include the widget javascript file when they load the layout page. As we use the WordPress structure to build our widget with the accordion option if Gantry doesn't include all the dependencies it won't work.

But I'm afraid you'll have to contact the gantry team to resolve this issue.
We use the core javascript and CSS of WordPress, it's not from our side to insert the wore function of WordPress.
If they add a way to include WordPress widgets it's on their editor they should make sure users can edit all kinds of widgets.

For example, in the Elementor our widget is working fine.
Plugin found here: https://www.acymailing.com/

Screen shot of settings that need adjusted:
https://terabykes.co.uk/gantry-acy-mailing.PNG

**Comment by mahagr** [comment]
Try to add and edit the widget in the WP way by using the widget positions. Adding a widget directly to the layout has some limitations.
