### ISSUE TITLE
iPad can't select gear icons for particles or menu items

### ISSUE THREAD

**Issue by charleshowell** [gantry/gantry5#277]
Using iPad Air 2 with iOS 8.3 (12F69) and Safari/Chrome.

When editing particles or menu items in (in Gantry 5.0.0 rc2) using Callisto demo template, I can't select the gear icon next to any particle, or when editing a menu I can't a) select the gear icon next to the menu item (e.x. About Us or Out Team) or b) if I create a new column in one of the menu items (under Pages for instace) I can't click on the "x" button in the upper right-hand corner of the blank menu column to delete it.

**Comment by w00fz** [comment]
Thank you, I'll look into it.

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
Looks like a regression, I suspect I introduced the issue after fixing some ghosting issues with the particles in Beta 5. 

I'll keep digging.

**Comment by charleshowell** [comment]
Djamal,
Thanks for your help. 
I really appreciate all the hard work you guys do to make such an excellent product. 
You rock!


Cpt. Chas Howell
Owner, USCG Licensed Captain, ASA Certified Sailing Instructor
Chas Howell Adventure Sailing (CHAS, Inc.)
1934 South Leland St
San Pedro, CA 90731
(562) 728-3005 mobile
chas@charleshowell.com

Sent from iPhone 6+ using Outlook




On Sat, May 16, 2015 at 12:21 AM -0700, "Djamil Legato" <notifications@github.com> wrote:












Looks like a regression, I suspect I introduced the issue after fixing some ghosting issues with the particles in Beta 5. 



I'll keep digging.
