### ISSUE TITLE
Error in PHP8

### ISSUE THREAD

**Issue by SkylarAstarot** [gantry/gantry5#2773]
I have a Joomla website running on the server with PHP8 and it generates the following error:
Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

![Captura web_13-3-2021_21948_localhost](https://user-images.githubusercontent.com/17954115/111020259-4aa27200-83a3-11eb-8008-9e724f7b7354.jpeg)

All errors are in files inside gantry5/engines folders

In control Panel (Administrator) everything works fine, the problem is only in Front End.

When will Gantry Framework be updated to work with PHP 8?

**Comment by N8Solutions** [comment]
@SkylarAstarot There is already an open ticket regarding this here [https://github.com/gantry/gantry5/issues/2737](https://github.com/gantry/gantry5/issues/2737). Please close this ticket and follow the other post for updates.
