### ISSUE TITLE
Is it possible implement PR in gantry styles?

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#2774]
hi
I want add Permission Tab to each individual template style in gantry. is there anyone to help or advise me? i find this:
https://issues.joomla.org/tracker/joomla-cms/24560
i have many user and many joomla user groups in my joomla and i want have some admins of joomla and each admin has an own menu item and can only his template style only. 
At the moment, i can implement this scenario before template style section but after i want implement this but i have doubt is it possible write my own plugin integrated with gantry5 or no? 
i understand gantry has an option called "Use Gantry 5 Assignments" if set to No the template style page maybe ready for implement PR tab. have you any idea?

**Comment by oxido21** [comment]
Try to create a group of users for each admin you have
and add that group too to each user you want
and like that, you can set a template style for each group of user and admins

**Comment by saman222** [comment]
Thank you @oxido21 but it seems not work. can you implement your test for your own? i can not implement that for administrators of joomla , means i want have multi admin in my joomla backend and each admin can only edit his template style.

**Comment by oxido21** [comment]
I think it's a little more complicated what you want to do, and you're going to need an existing component that does what you want or you develop an extension for that.

**Comment by mahagr** [comment]
Well, basically Gantry doesn't really handle ACL; that task is left to the underlying CMS; in this case, Joomla (or a plugin within).

If you implement a plugin that changes the behavior of the style assignments in Joomla, sure, that will work in Gantry as well. The only issue I can see is that you probably need to either change the behavior of Gantry assignments or to turn it off and use Joomla admin to do that.
