### ISSUE TITLE
Cookie "g5-collapsed" and 10 years expire date issue. GDPR Compliance

### ISSUE THREAD

**Issue by morten44** [gantry/gantry5#2775]
Hi
First of all, thank you for a great product.
We have an issue with the office who oversee GDPR in Denmark about a cookie used on our page.
Its called "g5-collapsed"
It also says it expire in 10 years

The danish office asked us about this cookie, what it does and why something need to be stored on PC for 10 years before its deleted.

I have not been able to find an explanation on this.
Can anyone confirm what does cookie does?
Can anyone tell me if there is a way to lower it from 10years to maybe 1 year something that sounds a little bit more "reasonable" for the Authorities asking into this?

Thanks for your time
I have attached a screenshot as well
![Screen Shot 03-15-21 at 10 39 AM](https://user-images.githubusercontent.com/40831248/111195325-0c2fd180-85b4-11eb-96e4-c1f6cd2d2942.PNG)

**Comment by N8Solutions** [comment]
Hello @morten44,
I have never seen that cookie before and I have quite a number of sites using Gantry 5. I also inspected the site using the address seen in the pictures you provided and I still do not see the those cookies.

**Comment by morten44** [comment]
Hi. Thank you for your reply. I will continue to trace it down :)
Kind Regards
Morten

**Comment by mahagr** [comment]
The cookie just keeps the state of some UI element, not sure which one. It's not used outside of JS.

I'm not sure why it has so large timeout, maybe it's just some arbitrary value. @w00fz ?

**Comment by mahagr** [comment]
See platforms/grav/gantry5/admin/common/application/utils/cookie.js line 6

**Comment by w00fz** [comment]
The file that contains the logic  for the 10 years cookie is dated Jun 28, 2017 (https://github.com/gantry/gantry5/commits/develop/platforms/common/application/utils/cookie.js) which is pre GDPR enforcement or at the very least at its early stage if I am not mistaken.

There was no particular reason for picking up 10 years, just a random big time length.

Looking at it 4 years later today, this can totally be changed to 1 year or 6 months, as it doesn't buy anything for staying alive that long.

The cookie's only purpose is to remember the state of open/collapsed panels in the admin, in a collection of 1 and 0 depending on the state.

Please feel free to change the timeframe to a comfortable amount and recompile the js.

**Comment by morten44** [comment]
Cool, thank you for your input.
Very good. Yes i am sure the 10 years was more or less random as made in early days, just got a little panic when the office looking over the GDPR in Denmark asked the question about the length and what it does :)

Thanks agian

**Comment by w00fz** [comment]
No problem. Feel free to point them to my comment as “official” answer and reasoning behind it, if that helps.

**Comment by morten44** [comment]
Thank you :)

**Comment by mahagr** [comment]
Gantry 5.5 will have this fixed (1 year).
