### ISSUE TITLE
What file is used to display modules inside a menu?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2777]
For a position, we have /media/gantry5/engines/nucleus/particles/position.html.twig to display it, and we can override it.
Similarly, what is the file responsible for displaying modules inside a menu? Like the circled module in the screenshot below.

![image](https://user-images.githubusercontent.com/12814040/111895328-2caec000-89e8-11eb-8223-4289b926135e.png)

I am asking this because I want to add some control to this module like I've done to position.html.twig:
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
    {% if particle.chrome == 'desktop_only' and gantry.mobile_detect.isMobile() %}

    {% elseif particle.chrome == 'mobile_only' and not gantry.mobile_detect.isMobile() %}

    {% else %}
      {{ gantry.platform.displayModules(particle.key, {'style': particle.chrome|default('gantry')})|raw }}
    {% endif %}
{% endblock %}
```
I've used the almost useless property "chrome" to distinguish positions that I want to render on mobile or desktop only. Now I want to do the same thing to the module inside a menu, but it is not a "position" so above code has no effect on it. I've looked menu.html.twig, but it doesn't seem to be the file I am looking for.

**Comment by dmleeman** [comment]
Although a Twig based solution would be welcome, there is a way to render modules to specific devices that works with Joomla and Gantry5.
Use the extension here: https://kubik-rubik.de/downloads/dsc-device-specific-content

Then you can apply the modification to the modules.php in your ../templates/[TEMPLATE]/html folder

`We need to modify the modules.php file located here
templates/template-name/html/modules.php

Michael Koontz @N8Solutions 18:02
Here is the file after I was done modifying it.
modules.php
you add the dsc-mobile, etc... to the Module Class Suffix under the Advanced Tab of the Module.
You need to of course have the DSC extension installed.

$moduleParams = json_decode($module->params);

    if($moduleParams->moduleclass_sfx === 'dsc-notmobile' && PlgSystemDeviceSpecificContent::isMobile()) {
        return;
    }
    if($moduleParams->moduleclass_sfx === 'dsc-mobile' && PlgSystemDeviceSpecificContent::isNotMobile()) {
        return;
    }
    if($moduleParams->moduleclass_sfx === 'dsc-nottablet' && PlgSystemDeviceSpecificContent::isTablet()) {
        return;
    }
    if($moduleParams->moduleclass_sfx === 'dsc-tablet' && PlgSystemDeviceSpecificContent::isNotTablet()) {
        return;
    }
    if($moduleParams->moduleclass_sfx === 'dsc-notdesktop' && PlgSystemDeviceSpecificContent::isDesktop()) {
        return;
    }
    if($moduleParams->moduleclass_sfx === 'dsc-desktop' && PlgSystemDeviceSpecificContent::isNotDesktop()) {
        return;
    }
	
that is the actual added code
placed just below
function modChrome_gantry($module, &$params, &$attribs)`

This solution was provided by @N8Solutions

**Comment by dmleeman** [comment]
The icing on the cake is to run a javascript that detects screensize or resize and reloads the specific modules. I don't yet have a solution for this.

**Comment by mahagr** [comment]
File `engines/nucleus/particles/menu.html.twig` is the file you're looking for. There is a macro to display the particle.

Also check for `engines/nucleus/admin/blueprints/menu/block.yaml` file if you want to add chrome or something else into it.

Positions won't work in the menu, there was some issue in Joomla that prevented us from doing that.

**Comment by newjie** [comment]
I was able to retrieve what I wanna do by modifying this file, thank you!


> The icing on the cake is to run a javascript that detects screensize or resize and reloads the specific modules. I don't yet have a solution for this.

@dmleeman  Can you share how to reload modules using Javascript?

**Comment by dmleeman** [comment]
@newjie Sadly, I have no solution for this yet. I believe that some AJAX solution may work best but, I am a novice to AJX right now. Still learning javascript!

**Comment by mahagr** [comment]
Particles have AJAX support to reload their data (see paginating particles), but you need to write JS yourself.
