### ISSUE TITLE
To Top particle and rel attribute issue in SEO checking

### ISSUE THREAD

**Issue by marco-laurito** [gantry/gantry5#2779]
Hi Reggie,

in these days I make deep SEO checkings for our non-profit website. I some webpages i have to put attribute rel=”follow” but in those same pages I have **“To Top” particle with rel=”nofollow”**. This conflict generates **follow-nofollow warnings by SEO analyzers**.
Meanwhile I temporary disabled "To Top" particle.

Can you help me how to modify/delete “ToTop” rel attribute?
Or can you suggest alternative ways to overcome these warnings?
Thank you in advance!
Marco

**Comment by mahagr** [comment]
@simmonsr Can we just fix it on our end? :)

**Comment by simmonsr** [comment]
Yes, let me look into it. But just wondering why override is not working.

**Comment by simmonsr** [comment]
doh! had my own override in template files.

**Comment by simmonsr** [comment]
https://www.searchenginejournal.com/google-nofollow-link-attributes/325255/

"No need to change existing attributes
There is no need to change any existing nofollow links. Google will continue to honor nofollow attributes that are currently in place."

Not sure it should really be changed.

**Comment by marco-laurito** [comment]
> Marco,
> 
> Are you using Joomla?
> 
> If so, you can override the particle ~/media/gantry5/engines/nucleus/particles/totop.html.twig
> 
> By copying that file and creating two folders /engine and /particles as shown here:
> 
> ~/templates/YOUR_TEMPLATE/custom/engine/particles/
> 
> Place the totop.html.twig file in the particles folder
> 
> You can then modify that file there (where you will find the code you mentioned) and it will not be overwritten in the event of an update.

Hi Reggie,
thank you for your fast reply!

I read the very useful your instructions on template override and the link you posted (https://www.searchenginejournal.com/google-nofollow-link-attributes/325255/). 

Thanks that I can ignore SEO analyzer (i.e. https://sitechecker.pro/) about follow-nofollow warnings and re-enable your ToTop particle.

Thank you again!
