### ISSUE TITLE
Date format is hardcoded into blog_list template

### ISSUE THREAD

**Issue by svatas** [gantry/gantry5#2783]
When you choose to have visible dates of publishing of articles in blog view, the date format is always the same regardless what format you choose in Grav.

I found, that this it hardcoded in twig file.

There is file 

`/user/plugins/gantry5/engines/nucleus/templates/partials/blog_item.html.twig`

in line 38 you can find :

`{{ page.date|date('jS M Y') }}`

This should be changed to some variable from GUI to reflect date format in GRAV or in template (something like dateformat.default or dateformat.short or dateformat.long I guess)

`{{ page.date|date(config.system.pages.dateformat.default) }}`

Or maybe there is option to use variable Date format from Particle deafults?

**Comment by mahagr** [comment]
Fixed for the next version. And no, we cannot use particle settings as we're not inside a particle.
