### ISSUE TITLE
Create theme.php override solution

### ISSUE THREAD

**Issue by pnutster** [gantry/gantry5#2784]
In discussion with Matias Griese opening this issue for Gantry (5.5) for Joomla 4.

A solution was proposed to make some edits to /templates/[TEMPLATE-NAME]/includes/theme.php
For instance to override some current older bootstrap 2 html:

```
$gantry['platform']->setModuleWrapper('<div class="platform-content">%s</div>');
$gantry['platform']->setComponentWrapper('<div class="platform-content row-fluid"><div class="span12">%s</div></div>');
```

However, this method would be overwritten by a theme update. An override solution that does not get overwritten would be welcomed.

**Comment by mahagr** [comment]
To be honest, it won't be overridden if the theme was originally supporting alternative bootstrap and the files were in the released package of the theme. That said, I agree that the file should be overridable.
