### ISSUE TITLE
Class 'Gantry\Framework\Gantry' not found

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2786]
![Screen Shot 2021-04-12 at 4 24 24 PM](https://user-images.githubusercontent.com/5002814/114464588-910a0d00-9bab-11eb-8f28-37dbf4eb7457.jpg)

Getting this when installing Gantry dev package.

**Comment by simmonsr** [comment]
guessing this is because i need to be using 4.x. doh!

**Comment by mahagr** [comment]
Shouldn't be an issue. I will need to check this one out.
