### ISSUE TITLE
Possible off-topic Twig question: How do I debug a twig object? 

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2787]
Just want to see its keys and values like we do javascript objects in the console.
In a twig file that I am trying to modify, there is a variable `article`, {{ article }} will be Gantry\Joomla\Content\Content. In the code there are usages like `article.route` and `article.categories|last`. 
I actually want to access the article's custom fields but I don't know what property to call. So I tried to list `article`'s keys and values by doing
```
  <dl>
    {% for key,value in article %}
      <dt>
        {{key}}
      </dt>
      <dd>
        {{value}}
      </dd>
    {% endfor %}
  </dl>
```
But this only outputs `<dl></dl>`. What could be wrong here?

**Comment by mahagr** [comment]
The object doesn't have an iterator for the fields, but I think you can use `article.getProperties()` as it extends JObject.
