### ISSUE TITLE
Trash and Pencil Icons Look Incorrect [GRAV]

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2788]
See screenshot:

![Screen Shot 2021-04-12 at 4 36 09 PM](https://user-images.githubusercontent.com/5002814/114465828-44273600-9bad-11eb-8dd7-189ddaa7e971.jpg)

**Comment by mahagr** [comment]
Likely in Grav, right? It's using another library and not FA.

**Comment by simmonsr** [comment]
Yes it's Grav. So how do we resolve this?

**Comment by mahagr** [comment]
@w00fz Do you have an idea? Because I think you cannot really solve the issue due to conflicts..?

**Comment by rhukster** [comment]
Probably due to lineawesome. ?

**Comment by simmonsr** [comment]
Specifically a Gantry 5.5 issue. 5.4 is OK.

**Comment by simmonsr** [comment]
Also spacer is missing icon:

![Screen Shot 2021-04-21 at 12 47 17 PM](https://user-images.githubusercontent.com/5002814/115598180-bda2e080-a29f-11eb-9673-ced4b18423ec.jpg)

**Comment by simmonsr** [comment]
Messes up arrow icon next to grav logo too:

![Screen Shot 2021-04-21 at 12 50 10 PM](https://user-images.githubusercontent.com/5002814/115598599-343fde00-a2a0-11eb-8938-9cc4246bbd90.jpg)
![Screen Shot 2021-04-21 at 12 50 18 PM](https://user-images.githubusercontent.com/5002814/115598600-343fde00-a2a0-11eb-85ca-287080326c8c.jpg)

**Comment by simmonsr** [comment]
fix confirmed
