### ISSUE TITLE
Featured articles in home page

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#279]
Using Hydrogen
Added page content to home layout
Setted featured article
Article not visible on home

**Comment by adi8i** [comment]
Hydrogen has nothing to do with joomla component, you even have `featured articles` set to `hide`, or wrong `menu item type`, be more explicit

**Comment by adi8i** [comment]
btw home layout is assigned to `Hydrogen Menu`, and that menu is set to `gantry5 themes - custom page`, this menu item type will not display joomla articles, even if you place `page content`, so you will want to change menu item type to something else, like `category blog`

**Comment by prankyboy** [comment]
Thx Adrian
I couldnt understand that H has nothing to do with J component... now it's clear

**Comment by w00fz** [comment]
Feel free to close the issue if this is resolved. Thanks!
