### ISSUE TITLE
Page builder not working

### ISSUE THREAD

**Issue by mariojoan125** [gantry/gantry5#2791]
Hello, the page builder is not working: it is not possible to edit anything. Also it looks not as usual. Please see attachment. I have uploaded the latest WP version and all plugins are updated too. How can I resolve this problem? Thank you for your valuable help!

![1  page-builder](https://user-images.githubusercontent.com/82475762/114619709-833faf00-9cb3-11eb-8650-a6bda975af88.png)

**Comment by simmonsr** [comment]
What page builder are you using?

**Comment by mariojoan125** [comment]
Many thanks for your message.

I am using Gantry and this is my website: www.mjelia.com

the problem still exists, and I would be immensely helpful for your help

Best,
Marios

**Comment by simmonsr** [comment]
I'm not seeing Gantry being used in the page source. view-source:https://www.mjelia.com/

From the looks of it though, if you are, it is a very very old version of Gantry.

**Comment by mariojoan125** [comment]
Hello,

please find attached a screenshot from the page builder, maybe this can
help clarify what I use.

I am using this since 2013 - this is true. How can I update it, while
keeping all pages as they are?

Thank you so much for your valuable help and support!

Best,
Marios

**Comment by mahagr** [comment]
Gantry 5 didn't exist back in 2013. As such, this cannot really be Ganrty 5 issue and Gantry 5 has nothing in common with the older versions of Gantry.

**Comment by mahagr** [comment]
What comes to upgrading the site, you will likely need to rebuild it with a new theme.
