### ISSUE TITLE
Custom Content not being inserted

### ISSUE THREAD

**Issue by ppetree** [gantry/gantry5#2792]
Joomla ver: 3.9.26 (stable)
Gantry ver: v5.4.37
Theme: g5_hydrogen

I've created a custom outline called "map" and added the following code to the header under the **Custom Content** section (because we don't want to bury this code down in gantry and we can't access the code in the root/js via the Assets section).

```
<link href="/css/geofence.css" rel="stylesheet" />
<script src="/js/maps.js"></script>
<script async src="https://maps.googleapis.com/maps/api/js?key=x1x1x1x1x1x1x1x1&callback=initMap"></script>
```
We can't get the header to be rendered with our code in it. Been trying various things for two days. 

The Custom Content section is enabled (blue checkbox). We have not created nor modified any of the twigs but there is some custom-css that is working. There are no error_log files. 

Any suggestions?

**Comment by mahagr** [comment]
I just tried this and the links are there, in the end of the `<head>`.

Make sure that the outline is being used.

**Comment by ppetree** [comment]
I've had it working on one site for over a year but when I tried getting it to work on another, nothing... not even a hint of progress (and the proper outline is being used). I solved the problem with sourcer.
