### ISSUE TITLE
Gantry 5.5 - Saving module in menu is overwritten by saving the menu item again in joomla

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2794]
If you create a module in the menu using G5.5 menu editor then it all appears to work fine. But if you then go into Joomla menu manager and just save that menu item (shown as a menu heading menu item) then it wipes out all the module details and just turns it into a normal "menu heading" menu item.

**Comment by mahagr** [comment]
Shouldn't be an issue anymore. Note that module assignments (to menu items) apply to the modules inside a menu as well.

**Comment by marktaylor46** [comment]
Not fixed! If the menu item in question has had an icon added in G5 Menu manager then that icon is wiped out by saving the menu item in Joomla module manager.

**Comment by marktaylor46** [comment]
Also other things such as dropdown width are wiped out too.

**Comment by mahagr** [comment]
OK, folder was missing in manifest.

**Comment by marktaylor46** [comment]
Confirmed fix
