### ISSUE TITLE
Gantry 5.5 - creating a module or particle in menu makes it have a "hover" effect in the menu

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2795]
If you create a module or particle in the menu shen it is shown on the front end it is being interpreted as a menu heading and therefore gets a "hover" effect over the link - this should not be the case. a module should just be module content and particle should just be particle contents - it's not really a menu item at all.

It then gets worse still... There is nothing to stop you adding a menu item in joomla menu manager as a child of the menu item that is actually the "module" or "particle" - then you actually get a child dropdown menu appearing when you hover over the "module" or "particle" in the menu.

**Comment by dmleeman** [comment]
@marktaylor46

Yes, well spotted. I see that too

Joomla 3.9.26
PHP 8.0.3
Gantry 5.5.dev

http://webdev.sites.k-hosting.co.uk/shop/1-test-product

**Comment by marktaylor46** [comment]
IMHO these "fake" menu items should behave more like the "Gantry 5 custom" menu item type. In that you should be able to edit the particle within the menu item and perhaps just link to the "module" editor if it is a module.

I think that as of now the problems that have been created outweigh the original problems that we were trying to solve (which really only affected WP anyway - not Joomla).

Regards, Mark.

**Comment by dmleeman** [comment]
Ok Mark, yes, I should have specified that the hover effect is apparent. Until you mentioned this, I did not notice this on the test site I began to set up.

**Comment by marktaylor46** [comment]
@dmleeman my comment was a general one - just on my observations - not really intended for you specifically. I just think we're breaking more than we're fixing with this change.

**Comment by marktaylor46** [comment]
Two wrongs don't make a right IMHO. Saying it's not a bug because it's always been a bug seems odd to me when there's am opportunity to fix it and improve Gantry 5 here.

Your decision though....

I am more worried about the other bug #2794 I raised because that is going to wreak havoc .
