### ISSUE TITLE
Chrome issue: Access to font at gantry-assets has been blocked by CORS policy

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2796]
I'm getting this error running Gantry 5.4.37  on Grav CMS 1.7.14
I've placed `Font Awesome 5` css file in `user/data/gantry5/themes/g5_helium/custom-assets/css/all.min.css` dir.
In page settings, this file location is selected: `gantry-assets://custom-assets/css/all.min.css`

Once I clear cache in Grav CMS no error is showed on Chrome Console. But on a second refresh I've got these two errors:
```
Access to font at 'gantry-assets://custom-assets/css/all.min.css' from origin 'https://webpage.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
and
GET gantry-assets://custom-assets/css/all.min.css net::ERR_FAILED
```
I've added this line at the very beginning of `.htaccess`:
`Header add Access-Control-Allow-Origin "https://webpage.com" but this doesn't help

**Comment by mahagr** [comment]
That error tells that the file isn't found and it's not converted to a relative URL.

**Comment by 01Kuzma** [comment]
That's strange, as I mentioned before, I've placed files here:
`user/data/gantry5/themes/g5_helium/custom-assets/css/all.min.css`
and this file location is selected in page settings: `gantry-assets://custom-assets/css/all.min.css`
File `all.min.css` physically exists in provided dir...
Any thoughts or I've done a typo?

**Comment by mahagr** [comment]
Another possibility is that for some reason the asset isn't converted from gantry stream to URI, did you try using a real path/uri instead?

**Comment by 01Kuzma** [comment]
Accessing file `https://webpage.com/user/data/gantry5/themes/g5_helium/custom-assets/css/all.min.css` from a browser opens it. I've changed a path in Page Settings to `/user/data/gantry5/themes/g5_helium/custom-assets/css/all.min.css` but the error in the console is the same: 
`Access to font at 'gantry-assets://custom-assets/css/all.min.css' from origin 'https://webpage.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`

It seems that this error is only affected in Chrome. Firefox doesn't produce it.

**Comment by mahagr** [comment]
OK; do you know which file has this URL?

**Comment by 01Kuzma** [comment]
The file is selected in `page settings` and physically available from `user/data/gantry5/themes/g5_helium/custom-assets/css/all.min.css`:
![image](https://user-images.githubusercontent.com/569504/117342563-11224a80-aeac-11eb-8478-4b7007ecefd8.png)
![image](https://user-images.githubusercontent.com/569504/117342652-239c8400-aeac-11eb-8b90-da27b3931d4a.png)

**Comment by mahagr** [comment]
Thanks, I will take a look on this in a few days.

**Comment by mahagr** [comment]
I just tested this in my local site with helium and by using the identical file and it worked for me (even if the file didn't exist).

I don't know what is different in your setup, but it is hard to tell why the stream wasn't converted to relative url.

Can you confirm that html head has the "bad" link to the CSS file?

**Comment by 01Kuzma** [comment]
I've forgotten to take a look into the source, look here, seems, that somehow the `gantry-assets` is not converted into a relative URL.
In Firefox it's the same, it's just not throwing an error as Chrome does.
![image](https://user-images.githubusercontent.com/569504/117413925-37350280-af1f-11eb-9d86-a61ff2b1eb03.png)

**Comment by 01Kuzma** [comment]
Seems a bug in a Caching. Once I turn off a Caching in Grav Config the path is rendered correctly. Once I turn it on - the `gantry-assets://` slug appears

**Comment by mahagr** [comment]
Even after cache clear? I'm asking because of I've not been reproduce the issue, cache enabled.

**Comment by mahagr** [comment]
Gantry does some post-processing of the page, which likely does not happen with the plugin. I need to check it out.

**Comment by mahagr** [comment]
You can ping me in discord. :)
