### ISSUE TITLE
Tooltips ?

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#28]
Suggest to implement the tooltips on backend, because some icons are not quite relevant.
![gantry5-tooltip](https://cloud.githubusercontent.com/assets/3976174/6913898/ce52906a-d785-11e4-8a2f-8ac2c7da0fbc.png)

**Comment by w00fz** [comment]
I added the tooltips now for those icons. Just a note, the icon you pointed at in your screenshot is the  `equalizer`. What it does is to resize all the particles in a grid with same size. In case you only have 1 particle nothing happens, but consider the scenario where you have 4 particles in a grid:

```
[ 13 | 55 | 8 | 24 ]
```

Clicking the `equalize` will automatically resize them evenly for you resulting in 

```
[ 25 | 25 | 25 | 25 ]
```

It's just a shortcut for when you have more than a couple particles and you want to quickly reset them.
