### ISSUE TITLE
Outline dropdown should be wider or not wrap outline descriptions

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#280]
Only a really minor thing - but the outline dropdown would benefit from being a little wider to stop the wrap on the outline names. Also, if it can't be made wider, then just truncate instead of wrapping because otherwise the dropdown looks ugly and is longer than it really needs to be.
![2015-05-16_09-22-54](https://cloud.githubusercontent.com/assets/11683218/7665426/974ab556-fbad-11e4-9922-9225fb9945e8.png)

**Comment by w00fz** [comment]
I'm really not a huge fan of this `Theme - ` prefix, I think we should kill those :)
I think a list of just names would be more than enough.

 - Overview
 - Typography
 - Variations
 - Home

**Comment by marktaylor46** [comment]
My concern is that when multiple G5 templates are installed they will innevitably have a "default" and you won't be able to tell one from the other? Perhaps it could be like the Joomla "module positions" list  in module manager whereby it adds a template heading into the list (that you can't select). So you would have:

- Hydrogen -
 - default
 - home
- Callisto -
 - default
 - overview
 - typography
 - home

I think that will make it clear which template is being used and make the entries shorter too?

**Comment by adi8i** [comment]
If you are in Hydrogen Template Manager you will see only Hydrogen's Layouts. So even if there if another g5 template based installed will not show there. :)

**Comment by marktaylor46** [comment]
Yes you're right - I forgot that. Just drop the prefix.

**Comment by mahagr** [comment]
I would keep the prefixes in Joomla, but hide them with some regexp from our views.

**Comment by w00fz** [comment]
For the time being I made the words not truncating like that in the middle but rather to normally break in new line.
Next step would be to clean out a bit the extra repeating Template name, since serve no purposes in G5 admin itself.
