### ISSUE TITLE
Gantry 5 {loadposition} within TABS particle not working. 

### ISSUE THREAD

**Issue by thatonedudebob** [gantry/gantry5#2801]
I'm not even sure if this can be accomplished but does gantry allow for module positions to be setup in an actual particle for EXAMPLE, Have a module position load up inside the TABS particle as if I was adding one to a joomla article. Every time I try to achieve this all I get is the text {loadposition XXX} within the particle. Or whichever {LOAD} I try. Does gantry have it's own way of achieving this?

**Comment by mahagr** [comment]
Most particles do not support content preparation out of the box, mostly because it may cause side effects.

If you modify the particle and wrap its content with `gantry.platform.filter(content)|raw`, without knowing more about the particle in question.
