### ISSUE TITLE
Gantry 5 main.js Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by Mohika** [gantry/gantry5#2802]
This is the site speed related and receives penalty by Google speed test and is red-flagged. 

gantry5/assets/js/main.js is flagged as it **Does not use passive listeners to improve scrolling performance**.

by the Google Page Speed Insights https://developers.google.com/speed/pagespeed/insights

**Comment by dmleeman** [comment]
I think that this has been addressed in the upcoming 5.5 version. Having noticed the error in Joomla3 and G5, it appears to be absent in the G5.5-dev beta and Joomla 4 test site I have running

**Comment by Mohika** [comment]
OK, I noticed it on the latest version of Gantry 5 for WordPress.
