### ISSUE TITLE
Gantry 5.5-dev Joomla Modules Titles do not display - J4 beta 7

### ISSUE THREAD

**Issue by dmleeman** [gantry/gantry5#2804]
Joomla 4 beta 7
PHP 8.0.3
Helium 5.5-dev

When creating a Module, the title does not show in Gantry templates (when set to Show). The same or similar Module does show it's title in Cassiopeia

https://imgur.com/a/zlqHpCx

This bug is not present in Joomla 3.9.26, PHP 8.0.3, Gantry5.5-dev

**Comment by mahagr** [comment]
Confirmed
