### ISSUE TITLE
Gantry 5.5-dev Particles Image Picker bug

### ISSUE THREAD

**Issue by dmleeman** [gantry/gantry5#2805]
Joomla 4 beta 7 & J3.9.26
PHP 8.0.3
Helium 5.5-dev

Intermittent bug: when using image picker in Particles, the modal opens to allow navigation to the required folder, but the folder links themselves are inoperative.

https://imgur.com/a/5BwaNOv

**_This seems to be a bug introduced into the beta dev package on 14th May. The prior version of 5.5-dev this was not an issue_**

**Comment by mahagr** [comment]
Looks like the same issue is in WP and Grav, I'm also getting `Uncaught TypeError: dropzone is not a constructor` in the console.

**Comment by mahagr** [comment]
I was able to fix this by rebuilding the packages. I'll update the builds in a sec.

**Comment by mahagr** [comment]
Try with the new builds :)

**Comment by dmleeman** [comment]
Great, 17/05/21 builds solves image picker problem. Tested on J4 beta 7 PHP 8.0.3
