### ISSUE TITLE
Gantry Menu manager cannot select any Wordpress menu after being upgraded to 5.5-dev

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2806]
Platform (local MAMP):
Wordpress 5.7.2, Gantry 5.4.34, Helium theme, PHP 7.4, no cache, no SEO plugin

Steps to reproduce
- Upload Gantry 5.5-dev with extensions manager.
- Replace Helium Theme with Helium 5.5-dev
- Check Gantry 5.5 and Helium 5.5 versions are working
- Try to select the main Wordpress menu in the Gantry Menu manager
- Create a new Wordpress menu, populate it with items and save.
- Try to select any menus in the Gantry Menu manager

Results
- No Wordpress menu is displayed in the Gantry Menu manager
- On frontend: ("No menu selected") error.

<img width="1225" alt="screen" src="https://user-images.githubusercontent.com/3645531/118374834-4d495f80-b5be-11eb-9704-3750a2a09410.png">
<img width="1257" alt="screen2" src="https://user-images.githubusercontent.com/3645531/118374892-96011880-b5be-11eb-8255-d0c1b7ec9720.png">

**Comment by mahagr** [comment]
I'm not able to reproduce this in my local. Was this a new or an existing installation?

**Comment by uGE70** [comment]
It is an existing installation. I have the same issue with another installation using a licensed Elixir theme. The database prefix has been edited for both, but I didn't see any issue until now.

**Comment by mahagr** [comment]
Could you try a clean installation of either one and then upgrade it to see if you can reliably reproduce the issue?

Also if you're able to give me instructions on how you could reproduce the issue, it would be a great help. Thank you. :)

**Comment by uGE70** [comment]
- So far I have installed the Wordpress Gantry RocketLauncher and upgraded it without any trouble.
- Then I have upgraded a third existing installation using the Gemini theme in english and not in french like the first ones and it worked flawlessly.
- I tried to insert french accents to break the installation or remove items using accents to make the faulty ones to work without success until now. Maybe some weird characters are the culprit.
- That's the only lead I have found, but I will make further tests this afternoon.

**Comment by mahagr** [comment]
So in short:
* New installation: works
* Updating English site: works
* Two French sites: FATAL ERROR

Do you have some extra plugins in the French site? Menu/language related perhaps?

**Comment by uGE70** [comment]
- All sites share the same basic extensions: Yoast, ACF, W3Cache, Really Simple SSL, Contact form, I usually prefer working with particles. No language specific extensions, I am not using multi-language plugins like Polylang for the french sites.
- I am using a child theme, but it doesn't seem to make any difference with or without it.
- I can go back from 5.5 to 5.4.37 without any issues, so the WP database tables don't seem altered.
- The issue seems to be the way Gantry is populating the menu $items parameters, but I have only begun to look at the inner working of Gantry to try get any clues about what's wrong. Especially to know if I can fix it in a database table or the menu yaml file.
- I am on my local Mac, so I want to test it on my Cloud server on Linux to see if there's any differences with the character encoding, I hope today or tomorrow.

**Comment by mahagr** [comment]
Maybe you could send me a zip from the site that breaks so I can take a look at what is breaking it. I'm also following Gantry 5 chat in https://gitter.im/gantry/gantry5

**Comment by uGE70** [comment]
The upgrade is working like a charm on my Linux Cloud Hosting. When I am importing the upgraded files and database on my local MAMP server using Mac OS 10.14.16, the same issue does appear.
I can make the menu working to some extent on my local Mac, if I manually inject the menu name in the AbstractMenu.php file and edit the createMenuItems method on the /src/classes/Gantry/Framework/Menu.php file.
Thanks for your help. I will send you my upgraded files to your email address.

**Comment by mahagr** [comment]
For me the menu works just fine, but I improved the logic to tell what is going wrong. I'll be building the new packages later today.

**Comment by mahagr** [comment]
@uGE70 Can you try again with the new build?

**Comment by uGE70** [comment]
Thanks for your new build. There's some improvements: the menu is now selected, but it is not populated yet. To be sure, I saved the Wordpress menu again.

<img width="1195" alt="Capture d’écran 2021-05-25 à 14 00 20" src="https://user-images.githubusercontent.com/3645531/119495475-bd947580-bd62-11eb-8c64-78d2b898abb6.png">
<img width="1360" alt="Capture d’écran 2021-05-25 à 14 01 35" src="https://user-images.githubusercontent.com/3645531/119495545-cdac5500-bd62-11eb-80b4-4652be7f6b0a.png">

**Comment by mahagr** [comment]
Thanks, that helps!

**Comment by mahagr** [comment]
@uGE70 As the fix is so easy ^, can you try applying it to your site and report back to me if it fixed your issues?

**Comment by uGE70** [comment]
Yes, thanks a lot for your help Matias ! It's working like a charm now. I also tested on PHP 8 and it's working too except for a deprecated message from the Timber library that would of course go if errors are set to false.
