### ISSUE TITLE
Question: move sections in layout manager?

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2807]
Hi,
I haven't found information, how I could move sections (change their position) in layout manager?
For example I'd like to move the `Expanded` section beyond the `Testimonials`
![image](https://user-images.githubusercontent.com/569504/118546301-6be75c00-b760-11eb-970f-0c186cf33fd0.png)

**Comment by mahagr** [comment]
You need to edit the files directly to do that. I would edit/copy the presets instead of the layouts and just change the preset of the layout.

**Comment by 01Kuzma** [comment]
Thank you!
The `layout.yaml` file in `config` folder should be edited?

**Comment by mahagr** [comment]
Those are the actual outlines. Presets can be found from the `layouts` folder if you want to add your own custom presets.

**Comment by 01Kuzma** [comment]
But there is no way to replace the already configured layout with modificated?
I've created a new layout, which is exactly the `Base Outline` default copy but with reordered sections.
And I've already configured default `Home` layout pretending it with modules and data. So I just want to reorder sections in `Home` layout. Or I need to do it from scratch?

**Comment by mahagr** [comment]
No, if you change preset, you can choose to keep all the content. If you do that, only sections that do not exist in the new layout are lost.
