### ISSUE TITLE
SCSS error in GRAV (GANTRY 5.5)

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2809]
![Screen Shot 2021-05-19 at 2 33 08 PM](https://user-images.githubusercontent.com/5002814/118873403-559be600-b8af-11eb-99c0-291bfeff516c.jpg)

**Comment by mahagr** [comment]
Try again, it required Grav admin update.

That said, we have two options here: either to set the minimum Admin requirement to 1.10.15 or to support the older version of SCSS compiler.

**Comment by simmonsr** [comment]
fix confirmed when updating to latest Admin. I would just require latest Admin.
