### ISSUE TITLE
Gantry 5.5 - menu editor - link and list tag attributes are not being saved at all

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2810]
The link and list attributes for a menu items are not being saved at all by Gantry 5.5 menu editor. If you come out of menu editor and go back in after saving then the details are no longer recorded.

**Comment by mahagr** [comment]
Is this Joomla?

**Comment by marktaylor46** [comment]
yes

**Comment by mahagr** [comment]
They are saved, but not displayed in Gantry. Let me fix that.

**Comment by marktaylor46** [comment]
ok, but they weren't present in frontend either?

**Comment by mahagr** [comment]
Same reason, the conversion from Joomla DB had a bug in it.

**Comment by marktaylor46** [comment]
confirmed fix
