### ISSUE TITLE
Gantry 5.5 - Trashed menu items showing in G5 menu editor

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2811]
If you trash a menu item (was a module in menu) in Joomla menu manager then it is still showing in G5 menu editor
![2021-05-24_15-00-56](https://user-images.githubusercontent.com/11683218/119358935-fe2bba80-bca0-11eb-9cb1-e17126a811cd.png)
![2021-05-24_15-01-13](https://user-images.githubusercontent.com/11683218/119358943-fff57e00-bca0-11eb-935f-4f5ab617174c.png)

**Comment by mahagr** [comment]
Actually, this is by design as not having the trashed items caused issues. I will need to find a way to hide those items, but still list them.

**Comment by marktaylor46** [comment]
Not sure I understand? Anything trashed should not show in g5 menu editor or on frontend at all. There's no way that trashed items can be listed in g5 menu editor as there will be hundreds of them - first  thing users do is trash the menu items in the demo - we can't have them showing up at all anywhere.

**Comment by mahagr** [comment]
They aren't found in the frontend. I'll fix this in the admin next week.

**Comment by mahagr** [comment]
I'm now moving the trashed menu items into the end of the list.

**Comment by marktaylor46** [comment]
That it no good - trashed items shoul dnot show at all - some users will have hundreds of trashed menu items

**Comment by mahagr** [comment]
They will not show up and because of that they will be moved to the end of the list if you show all in Joomla menu manager.

**Comment by marktaylor46** [comment]
Ok, So I just checked latest build  and they are still showing in Gantry 5 menu editor - they should not be there at all (even on the end).

![2021-06-01_10-51-16](https://user-images.githubusercontent.com/11683218/120304135-67c24f00-c2c7-11eb-856c-7d2868293cf2.png)

**Comment by mahagr** [comment]
Try now, I forgot to update the builds.

**Comment by marktaylor46** [comment]
Yeah - looks good now - confirmed fix
