### ISSUE TITLE
Gantry 5.5 - "gantry menu" tab in joomla menu manager doesn't show "icon only" checkbox

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2813]
The "gantry menu" tab in joomla menu manager doesn't show "icon only" checkbox that is present in Gantry menu editor

**Comment by mahagr** [comment]
It's stored in `Link Type > Add Menu Title` (`menu_text`) in Joomla. Basically, Joomla already has this feature.

**Comment by marktaylor46** [comment]
Hmmm ok so the switch in Joomla is the opposite way around.

Thanks

**Comment by mahagr** [comment]
Yeah, though there's not much we can do about it. The setting is basically negated during save. :)
