### ISSUE TITLE
Saving Gantry 5.5-dev menu throwing an exception when WP debug mode is on

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2815]
Platform (local MAMP Pro):
Wordpress 5.7.2, Gantry 5.5-dev, Helium child-theme, PHP 7.4, no cache, no SEO plugin

### Steps to reproduce

1) Add WP debug mode on wp-config.php file:
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);

2) Go to Gantry menu manager, click on the save button and Gantry will display an exception (screenshot). 

Note: it's perfectly working when debug mode is Off.

<img width="1374" alt="Capture d’écran 2021-05-27 à 09 41 26" src="https://user-images.githubusercontent.com/3645531/119787340-652fb600-bed1-11eb-95e9-fc03df7943e5.png">

**Comment by mahagr** [comment]
Check the new build, this should be fixed in it (as is the other issue).

**Comment by uGE70** [comment]
Thanks Matias, Yes it's all fixed and working great now. I could add new icons, move and rename menu items without any issues even at the root level.

**Comment by mahagr** [comment]
Thank you for your feedback!
