### ISSUE TITLE
Gantry 5.5 All Gantry menus display the main menu items when progressive or conservative cache is on.

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2818]
Platform (local MAMP Pro and Linux hosting):
Joomla 3.9.27, Gantry 5.5-dev, Callisto template, PHP 7.4, conservative/progressive cache, no SEO plugin

### Steps to reproduce
Add different menus to your Joomla site
Edit configuration options to System cache > Conservative or Progressive
Go to Gantry Menu Manager and try to select any menus.

### Expected result
Menus should display their own menu items

### Actual result
Only the main menu items are displayed

<img width="1226" alt="Capture d’écran 2021-06-02 à 11 45 56" src="https://user-images.githubusercontent.com/3645531/120460361-59446800-c399-11eb-8f6d-972980c87cc9.png">
<img width="1226" alt="Capture d’écran 2021-06-02 à 11 46 17" src="https://user-images.githubusercontent.com/3645531/120460446-6c573800-c399-11eb-835e-d6255e101b5e.png">

**Comment by mahagr** [comment]
@uGE70 Confirmed and fixed. Thank you!

**Comment by uGE70** [comment]
Works great ! Thank you.
