### ISSUE TITLE
Gantry 5.5 Dropdown Direction value is different between Gantry Menu Manager and Joomla Menu Manager

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2821]
Platform (local MAMP Pro):
Joomla 3.9.27, Gantry 5.4.37/5.5-dev, PHP 7.4, no cache, no SEO plugin

### Steps to reproduce
- In Gantry 5.4.37, set any menu item at root level to Dropdown Direction => Expand right
- Upgrade to Gantry 5.5 dev
- Check Gantry menu manager, menu item is set to Expand Right, save or not
- Check Joomla menu manager, Gantry tab, menu item is set to Expand Left

### Expected result
Both Joomla Menu Manager and Gantry Menu manager should show the same value after Gantry 5.5 upgrade.

### Actual result
Joomla Menu Manager is reverting to the default value

<img width="1226" alt="Capture d’écran 2021-06-08 à 13 54 43" src="https://user-images.githubusercontent.com/3645531/121182819-bf326300-c863-11eb-80ec-3ad8c4c81f32.png">
<img width="883" alt="Capture d’écran 2021-06-08 à 13 57 29" src="https://user-images.githubusercontent.com/3645531/121182876-c9ecf800-c863-11eb-843d-9b998015ff8f.png">

**Comment by mahagr** [comment]
Looks like I need to pass the defaults to the Joomla form.
