### ISSUE TITLE
Gantry 5.5 - Template error page is not displayed

### ISSUE THREAD

**Issue by mikesmith500** [gantry/gantry5#2822]
Hi.

When an error occurs, for example article not found (404), the template error page does not appear. A plain generic phrase appears.

Joomla! 3.9.27 Stable [ Amani ] 25-May-2021 15:00 GMT
Gantry 5.5 + Hellium (build 06/07/2021) 

```
<html><head></head><body>Error</body></html>
<head></head>
<body>Error</body>
<html><head></head><body>Error</body></html>
```

**Comment by mahagr** [comment]
Issue should be fixed now, I'll make new builds later this week.

**Comment by mikesmith500** [comment]
I just updated to the latest build and the problem continues.
