### ISSUE TITLE
Joomla Gantry particle, I think I found an issue with imagesize

### ISSUE THREAD

**Issue by TheoKondak** [gantry/gantry5#2825]
I am working on a gantry particle, and stumbled upon this page: http://docs.gantry.org/gantry5/advanced/twig-filters 

I tried to use the imagesize property mentioned in this page, and it seems to work only that when it renders it has double double quotes.

The TWIG code looks like that:

`<img src="{{ item.defaultImage|url }}" alt="{{ item.imageAlt }}" {{ item.defaultImage|imagesize }}>`

The code rendered in the front end looks like that: 

`<img src="..." alt="..." width=""1920"" height=""810"">`

So if you notice, the width and height attribute, got two double quotes on each side, which is not valid HTML thus it doesn't work. Tried to play around a bit, but it seems that it's an issue on your end.

**Comment by mahagr** [comment]
@TheoKondak You need to write:

`<img src="{{ item.defaultImage|url }}" alt="{{ item.imageAlt }}" {{ item.defaultImage|imagesize|raw }}>`

I will fix the filter so it doesn't need the raw filter anymore.

**Comment by mahagr** [comment]
Fixed in https://github.com/gantry/gantry5/commit/c878c2396c8c8c39d7faac8d17ff1fbe65af0b5c
