### ISSUE TITLE
Gantry 5.5 testing - unable to access menu manager

### ISSUE THREAD

**Issue by MaghSamana** [gantry/gantry5#2826]
After the migration, I didn't notice any rendering issues in the front end. Some .css files that were loaded as assets in some outlines had to be reconfigured again (the link was gone). 
Compiler is improved - I used to get minor problems (from the template's own classes) after compiling Base outline, and I often had to recompile every other outline also, Now this problem is gone.

I got this error, so far, when clicking the Menu editor.

![FireShot Capture Administration](https://user-images.githubusercontent.com/46110970/123777656-18c50500-d8d9-11eb-85ec-f3a23b197226.png)

My test environment is a migrated site from Joomla3.9.27 to Joomla 4 RC2. 
PHP version is 7.4.20.

**Comment by mahagr** [comment]
This seems to be a bug in Joomla 4 mysqli engine. I worked it around for now.

**Comment by mahagr** [comment]
https://github.com/joomla/joomla-cms/issues/35452
