### ISSUE TITLE
Gantry 5.5 Customize Error Page Title and Content Message

### ISSUE THREAD

**Issue by 01Kuzma** [gantry/gantry5#2827]
Hi!
Two questions:
  1. is there a possibility to change this message: `Error 404Woops. Looks like this page doesn't exist.` ?
  2. Change/translate Page Header Title from `Page Not Found` into it's own?
Thank you!

**Comment by mahagr** [comment]
Which CMS?

**Comment by 01Kuzma** [comment]
Grav CMS

**Comment by mahagr** [comment]
That comes from the error plugin.

You can define your own error page in Grav or just change the translation string for `PLUGIN_ERROR.ERROR_MESSAGE`.

**Comment by 01Kuzma** [comment]
Great, thank you!

**Comment by 01Kuzma** [comment]
Thank you!
But I still can't translate the string in the browser's tab title.

I'm translating these strings:

```
  PLUGIN_ERROR:
    ERROR: "error"
    ERROR_MESSAGE: "page not found"
    ROUTE_404: "404 code" 
```

**Comment by mahagr** [comment]
Maybe take a look into error plugin? The error page and the title isn't handled by Gantry.

**Comment by 01Kuzma** [comment]
(y) there is extra .md page for that.
