### ISSUE TITLE
Gantry 5.5 Menu settings are not saved by Joomla Menu Manager

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2829]
Platform (local MAMP Pro):
Joomla 3.9.27, Gantry 5.4.37/5.5-dev, PHP 7.4, no cache, no SEO plugin

## Steps to reproduce
Upgrade an existing Joomla website to Gantry 5.5 dev
In Gantry menu manager, set any specific menu settings, for instance Dropdown Width or Icon, and Save.
Check Joomla menu manager, there's no Gantry tab, save previous menu item in Joomla Menu manager again.
## Expected result
Menu item in Gantry Menu manager should show Dropdown Width or icon after menu item is saved in Joomla Menu manager.
## Actual result
Gantry Menu manager settings are not saved after menu item is saved in Joomla Menu Manager again.

<img width="1029" alt="Capture d’écran 2021-07-02 à 17 11 49" src="https://user-images.githubusercontent.com/3645531/124295691-6cde1c80-db59-11eb-8e5c-67499b98a704.png">
<img width="1044" alt="Capture d’écran 2021-07-02 à 17 12 55" src="https://user-images.githubusercontent.com/3645531/124295708-72d3fd80-db59-11eb-939b-51652e8732af.png">
<img width="1044" alt="Capture d’écran 2021-07-02 à 17 13 22" src="https://user-images.githubusercontent.com/3645531/124295728-7798b180-db59-11eb-9a67-c134b63a2c6b.png">

**Comment by mahagr** [comment]
Should be fixed now.

**Comment by uGE70** [comment]
I tested with the same configuration and it's all good now. Thanks for your hard work.
