### ISSUE TITLE
Apply and Save button will not save configurations in particle

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#283]
Apply and Save button will not save the settings in particle, i've seen this while using Social particle but probably is the same for most of them.

Honestly i don't see why that button should be there, was not needed, but when you are too lazy to hit one more button... whatever.

**Comment by w00fz** [comment]
Seems to be working fine for me, what are your steps exactly?

**Comment by adi8i** [comment]
I will try again in few minutes

**Comment by adi8i** [comment]
That's odd, now is working.

**Comment by w00fz** [comment]
Phew! That would have been hard to track down :) Maybe was cached JS. Glad it's fine now!

**Comment by adi8i** [comment]
I'll reopen this one. The issue is on second level of settings, for example in social particle, if you add some items and hit `apply and save` . so the first page of settings , will work, now if you dig, so go to add icon to an item and hit `apply and save` will not save. I  think this will happen for all particles.

![capture](https://cloud.githubusercontent.com/assets/9744973/7669489/66287e5a-fc7e-11e4-8f7a-3ae5ed0b7fb2.PNG)

**Comment by w00fz** [comment]
I see. I think the second modal shouldn't have the `Apply and Save` and just `Apply`. 
I'll look into that, thanks!

**Comment by adi8i** [comment]
That's great ! One less button.

**Comment by w00fz** [comment]
Ehe, only on the double modals it's removed, in the regular ones it's still there :)
Good catch though!
