### ISSUE TITLE
Grav+Gantry5.5 testing:still the old issue with categories!

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#2830]
I'm testing Gantry5.5 in Grav (Helium Theme): using "Grav content" particle there is still the old issue of Grav not accepting more than one category.
If you use just "dogs" category  the particle is visible, but if you add a "cats" category the particle isn't rendered.
So the "Grav content"particle is virtually useless....
I wonder if this trouble will ever be solved...

<img width="661" alt="Schermata 2021-07-08 alle 14 07 10" src="https://user-images.githubusercontent.com/11693902/124926797-d779d700-dff5-11eb-9f45-aac61a9df7ed.png">

**Comment by mahagr** [comment]
It's not really an issue, but how Grav categories work. Its meaning is: page must be in BOTH Cats and Dogs. Grav doesn't support OR operation:

https://learn.getgrav.org/17/content/collections#taxonomy-collections

This is really a Grav issue, Gantry only uses features form the underlaying platform.

**Comment by beamaria** [comment]
Hi Matias, 
Thanks for your reply; I know that this is a Grav issue, but I wonder if there is any possibility to force GRAV using "or" option

Eilis

**Comment by mahagr** [comment]
No, there isn't. The collections just do not support it right now.

**Comment by beamaria** [comment]
Not even if I use this option "Collection::merge($collection2)"  to merge the two categories "dogs" and "cats" in one menu called "pets"?

**Comment by mahagr** [comment]
Hmm, it is possible to have a loop in the template to do that. It just doesn't work with the default ordering as the items need to be reordered anyway, but yeah...

**Comment by beamaria** [comment]
ok, this is something that goes well beyond my possibilities, especially using Gantry5.5+Grav...
I 'll wait till the Grav team solves this issue ;-)
Thanks!

Eilis

**Comment by mahagr** [comment]
Should be fixed for the next release!

**Comment by beamaria** [comment]
Looking forward to it!
