### ISSUE TITLE
Grav+Gantry5 testing: impossible to upload new particles

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#2832]
Hi all! i'm testing locally a site with Grav and Gantry5.5 (Helium theme).

It looks like it's impossible to import new particles from other templates using this path:
user/data/gantry5/themes/g5_helium/
and including the file yaml and html.twig in a custom folder "particles", creating the "js" folder (if needed) and including the related css in a custom folder "scss" (of course writing  @import  "name-of-the-particle";  in the custom.scss file).
I was trying to copy the "calendar" particle form Rockettheme (but the error still crops up with other particles from different developers)

I have this crickey error page:

```
/Applications/MAMP/htdocs/grav-g5/user/plugins/gantry5/engines/nucleus/templates/partials/page_head.html.twig
{% extends "@nucleus/page_head.html.twig" %}
 
{% block head_title %}
    <meta charset="utf-8" />
    <title>{% if header.title %}{{ header.title }} | {% endif %}{{ site.title }}</title>
    {% include 'partials/metadata.html.twig' %}
    <link rel="canonical" href="{{ page.url(true, true) }}" />
    {% if header.robots %}
        <meta name="robots" content="{{ header.robots }}">
    {% endif %}
{% endblock %}
 
{% block head_application %}
   {% do gantry.platform.finalize %}
 
    {% block assets deferred %}
        {{ assets.css()|raw }}
        {{ assets.js()|raw }}
    {% endblock %}
 
{% endblock %}
Arguments
"""
An exception has been thrown during the rendering of a template ("CSS Compilation on file 'custom.scss' failed on error: Undefined variable $grey: user/data/gan ▶
Call Stack:\n
#0 import user/data/gantry5/themes/g5_helium/scss/_calendar.scss user/data/gantry5/themes/g5_helium/scss/custom.scss on line 3\n
#1 import user/data/gantry5/themes/g5_helium/scss/custom.scss (unknown file) on line 1").
"""


```

**Comment by mahagr** [comment]
I would prefer adding all the files to the theme itself (user/data is meant for automatically generated files only), but it isn't your issue.

The issue you're having is that scss uses variable `$grey` which isn't defined in your theme. You need to define all variables needed in SCSS, either in styles YAML of your theme or by defining them inside your SCSS file before it's being used.

**Comment by beamaria** [comment]
Thanks Matias, 
now it's clear!

Eilis
