### ISSUE TITLE
Gantry 5.5 - Template error page is not displayed (related to #2822)

### ISSUE THREAD

**Issue by mikesmith500** [gantry/gantry5#2833]
Problem #2822 persists with latest build.

**Comment by mahagr** [comment]
@mikesmith500 I cannot reproduce your issue. Make sure that you have copied htaccess file (if using Apache):

```
cp htaccess.txt .htaccess
```

**Comment by mikesmith500** [comment]
I have activated debugging in joomla and the following error appears:

Error: Call to a member function getLanguage() on null: Page not found

The server gives an error 500. I can't find anything relevant in the apache / nginx logs.

**Comment by mahagr** [comment]
Yeah, it seems to come from Joomla. Can you find out where the error occurs by looking into the back trace?

**Comment by mikesmith500** [comment]
I do not know how to do that :)

With debug enabled this is de error:

Error: An exception has been thrown during the rendering of a template ("Trying to get property 'title' of non-object").: Página no encontrada

**Comment by mahagr** [comment]
@mikesmith500 Sorry for the delay. You can enable debugging in Joomla which enables the backtrace (long list of method calls telling the code path that failed).

**Comment by mahagr** [comment]
@mikesmith500 DId you try enable debugging in Joomla?

**Comment by marktaylor46** [comment]
Just adding that I tried this on J4 and G5.5 and it works fine (once you have renamed htaccess.txt to .htaccess in joomla root and have enabled "url rewriting" in global configuration.
