### ISSUE TITLE
Page not found (stdin) URL

### ISSUE THREAD

**Issue by Flowman** [gantry/gantry5#2836]
Don't know how to explain this issue. I noticed when I have xdebug enabled I get this page not found error all the time but I cannot see where it is reference from. The URL path is (stdin), so did a search through my project and found that leafo scss compile is the only place where this is referenced. 

![image](https://user-images.githubusercontent.com/212680/125384324-593d7c00-e3cb-11eb-9f29-64766547c12f.png)

![image](https://user-images.githubusercontent.com/212680/125384759-fa2c3700-e3cb-11eb-8500-8ba3d9f82055.png)

Using Joomla 3.9.28 with multilingual enabled and gantry 5.4.37.

**Comment by mahagr** [comment]
Do you get this issue if you disable `System - Gantry 5` plugin? If you do, this is not a Gantry issue (as the code isn't run).

I don't think it is as Gantry is activated only after routing and it looks like this error happens before.

**Comment by Flowman** [comment]
Something in the background is calling that path from inside Joomla as it doesn't kill the page load in xdebug. The only code in the whole project that has anything to do with (stdin) is part of gantry. 

Could it be when it is recompiling the scss or something?

**Comment by mahagr** [comment]
As I said, try disabling Gantry plugin to see what happens. If you disable the system plugin, Gantry will not be initialized at all. Or just switch the theme to Protostar as it also prevents Gantry from being used.
