### ISSUE TITLE
Gantry 5.5 - no lines and files are showing in developer mode

### ISSUE THREAD

**Issue by jameswadsworth** [gantry/gantry5#2837]
When developer mode is activated in Gantry 5.5 the lines and files are not show in the generated css files to help with debugging. I've downgraded to version 5.4.37 and the lines and files are shown again. 

![image](https://user-images.githubusercontent.com/9198869/125517814-936c6c46-b0d4-465f-ab84-20868cd01ac1.png)

**Comment by mahagr** [comment]
Yes, these are missing as Gantry 5.5 uses later version of SCSS compiler which has proper support for SCSS map file and has removed this old "workaround".

You should inspect CSS to see the original SCSS files.

**Comment by mahagr** [comment]
I just verified that SCSS source files show up when you inspect the CSS.
