### ISSUE TITLE
This is not really an issue but need advice

### ISSUE THREAD

**Issue by Bootfair** [gantry/gantry5#2838]
Hi, 
I was wondering if Gantry 5 would let me use dropUP menus instead of dropdown like seen in this example https://aquaspringsdental.com/ .I want to have a sricky menu at the footer like this but I could not figure out how to make the dropdown menu drop up instead like on this example? Any help will be much appreaciated.
Best regards

**Comment by mahagr** [comment]
It looks like those menus are mostly done by using CSS tricks. So you will most likely be able to do this by just using CSS.

If HTML changes are required here's the particle: https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/particles/menu.html.twig . Just make your own based on that.

I'm closing this issue as it's not Gantry issue.
