### ISSUE TITLE
post.categories in partials/meta.html.twig

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2839]
I want to display terms of custom taxonomy of a custom post type both in the archive and in the single post view.
For the posts, this works by default and through the settings of the content.

But for the custom post types this isn't working.
I guess I should fetch those terms and assign them to the posts etc.

However, while reviewing the default archives and the view files of the helium, I came to this question:

How does the post.categories are getting filled and existing when we reach at the partials/meta.html.twig?

I think I have followed the "posts" from the beginning of their archive.php and I didn't spot a categories property.
How that gets filled and is not empty when we reach in the meta partial view file?

**Comment by mahagr** [comment]
You probably already saw it, but post comes from `https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/wordpress/page.php#L38` (or from any of the php files). 

Check Timber docs how the classes/methods work. Categories should be filled by then, but I'm not quite sure how Timber does that. Unfortunately I'm not an expert in WP and I'm not quite sure how WP/Timber uses the categories.

**Comment by joomlabeat** [comment]
@mahagr 
It's some time since then, so I don't have a fresh and clear picture on all the details.

Well, how each post object gets its categories is still a mystery for me.

I researched in Timber but I didn't manage to spot where this is happening - therefore, I never figured out if what I wanted to do is something that is supported - e.g. by passing any special parameters to Timber::get_posts() or with any other way.

So - in order to achieve what I wanted, after getting my custom post type posts array, I am iterating to get the terms of the custom taxonomy for each post.

**Comment by mahagr** [comment]
To be honest, I'm not 100% sure either. The purpose for using Timber was to simplify our logic as with WordPress things get pretty involved pretty fast, especially with all the hooks it has.

**Comment by joomlabeat** [comment]
I Agree. 
Overall, Timber does its job in this context pretty well.
