### ISSUE TITLE
Troubleshooting PHP 7.4 / Gantry Error

### ISSUE THREAD

**Issue by natecovington** [gantry/gantry5#2841]
I'm having trouble with Hydrogen/Gantry5 to work with PHP 7.4, attached is a screenshot of the live site on PHP 7.3, no errors in the console. then i switch to PHP 7.4 and my layout goes haywire. i'm not seeing any errors in cPanel logs... and I turned on Display Errors = Maximum in Joomla Global Configuration, I'm not getting any hints. Where else should I check?
<img width="1392" alt="Screen Shot 2021-07-23 at 8 21 15 AM" src="https://user-images.githubusercontent.com/4930859/126781674-4aa338af-0e14-4b65-82d4-ca0c31cb7dbc.png">
<img width="1392" alt="Screen Shot 2021-07-23 at 7 58 48 AM" src="https://user-images.githubusercontent.com/4930859/126781679-b21a2a4c-0fe7-423c-9298-23fcc8fc2b31.png">

**Comment by natecovington** [comment]
Found Gantry plugin was out of date.  For some reason Hydrogen was updating automatically but Gantry was not.

**Comment by mahagr** [comment]
There have been some issues on Gantry updates, we're looking into those. Thanks!
