### ISSUE TITLE
Is this UX problem in gantry menu editor?

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#2844]
hi.
i work hard with ganty menu editor but i can't to create multi column menu in level 2 or higher. you can only create multi column menu in level 1. is it right? if yes how can i put level2 menu item aside each other? 
thank you.

**Comment by blizam** [comment]
Multi column is only supported at level 1, additional levels are single column only.

**Comment by saman222** [comment]
Is there any plan to implement this feature?

**Comment by blizam** [comment]
Not to my knowledge. There's several other issue posts regarding the unpredictability of coding for multiple columns beyond level 1 being the current reason it's not possible nor planned.

https://github.com/gantry/gantry5/issues/1256#issuecomment-214815606
https://github.com/gantry/gantry5/issues/1089#issuecomment-312507707

**Comment by mahagr** [comment]
I'm closing this as duplicate of #1089
