### ISSUE TITLE
New WP 5.8 blocks don't work

### ISSUE THREAD

**Issue by pplopx** [gantry/gantry5#2845]
Sorry to add more work knowing that Joomla 4 is complicated. 

But...  for some strange reason, almost all of the new blocks for the ['Full Site Editing](https://developer.wordpress.org/block-editor/handbook/full-site-editing/)' concept that are released with WordPress 5.8 do not display well with Gantry.

Only the 'Query Loop', 'Login/out' & 'Site Logo' blocks seems to work. Otherwise, nothing.

Other blocks, such as navigation blocks and widget blocks, remain to be tested.
You can see it graphically with the following screenshots. 

I guess we'll have to figure out a way to make this compatible. Although Gantry takes care of the site design, these blocks come in handy for what the framework doesn't cover. 

Maybe Timber is involved or it's just a matter of Gantry contemplating support for these new features.

I know there are big changes coming to WP; Gantry should be ready.

Tested with Gantry 5.5-dev 6/23/2021

WP 5.8 default theme:

![Wp 5 8+Twenty Twenty-One 1 4](https://user-images.githubusercontent.com/28963354/127904219-52d3bce1-bc56-405e-95ca-ec91c1ebe814.png)

WP 5.8+Gantry 5.5dev+Helium 5.5dev

![WP 5 8+Gantry 5 5+Helium](https://user-images.githubusercontent.com/28963354/127904212-09af3a60-0584-4544-b9c5-9136bc1c0013.png)

**Comment by mahagr** [comment]
@pplopx I just updated the latest builds. 

Is it possible to get the example sites so I can try them locally?

**Comment by pplopx** [comment]
Thanks for updates, @mahagr 

I have applied the new packages but it doesn't seem to fix it.

The site is actually a clean install hosted on a "disposable" sandbox server, poppy.life style, which you can [see here](https://gantry.server2.trinchera.dev/index.php/2021/08/02/lorem/).

I can pass you the keys if you provide me a private way.

**Comment by mahagr** [comment]
You can use matias at rockettheme dot com.

**Comment by pplopx** [comment]
You have an email!

**Comment by mahagr** [comment]
Looks like I didn't receive it.

PS: I'm also in https://gitter.im/gantry/gantry5

**Comment by pplopx** [comment]
You have a DM for Gitter -- I hadn't thought of that! -;

**Comment by mahagr** [comment]
Thank you for contacting me. I will take a look into this on Monday!

**Comment by mahagr** [comment]
The Widget Editor should be fixed in the latest Gantry 5.5 builds.
