### ISSUE TITLE
Documentation links to twig.sensiolabs.org

### ISSUE THREAD

**Issue by pludikar** [gantry/gantry5#2846]
Hi,

There are several links in the documentation around twig that are outdated.  It appears that sensiolabs has changed their twig documentation domain from http://twig.sensiolabs.org/ to http://twig.symfony.org/  You will probably need to do a global search/replace to find all the instances

Regards
Peter

**Comment by pplopx** [comment]
Upps, may I correct the url:  https://twig.symfony.com/doc/2.x/  → I believe Gantry uses Twig version 2.

**Comment by pludikar** [comment]
The current Gantry document links don't specify the version - changing http://twig.sensiolabs.org/doc/filters/index.html to http://twig.symfony.com/doc/filters/index.html will result in a redirect to https://twig.symfony.com/doc/3.x/filters/index.html.  So if Gantry uses version 2, then yes, it should reference the appropriate version (eg https://twig.symfony.com/doc/2.x/filters/index.html).  In that case, I would also suggest making it clear which Twig version Gantry uses at the top of the documentation.

Peter
