### ISSUE TITLE
fatal error Joomla

### ISSUE THREAD

**Issue by jkplacek222** [gantry/gantry5#2847]
Hello, I have fatal error in my website. I have Joomla 3.9.28 and PHP 7.4. I dont know why I have this

> Fatal error: Uncaught RuntimeException: Could not find resource 'whoops.css' in any resource paths.(searched: /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/../Resources) in /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php:636 Stack trace: #0 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php(193): Whoops\Handler\PrettyPageHandler->getResource('whoops.css') #1 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Run.php(321): Whoops\Handler\PrettyPageHandler->handle(Object(Whoops\Exception\ErrorException)) #2 /libraries/gantry5/classes/Gantry/Component/Whoops/SystemFacade.php(132): Whoops\Run->handleException(Object(Whoops\Exception\ErrorException)) #3 [internal function]: Gantry\Component\Whoops\SystemFacade->handleException(Object(Whoops\Exception\ErrorException)) #4 {main} thrown in /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php on line 636
> 
> Fatal error: Uncaught RuntimeException: Could not find resource 'whoops.css' in any resource paths.(searched: /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/../Resources) in /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php:636 Stack trace: #0 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php(193): Whoops\Handler\PrettyPageHandler->getResource('whoops.css') #1 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Run.php(321): Whoops\Handler\PrettyPageHandler->handle(Object(Whoops\Exception\ErrorException)) #2 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Run.php(403): Whoops\Run->handleException(Object(Whoops\Exception\ErrorException)) #3 /libraries/gantry5/vendor/filp/whoops/src/Whoops/Run.php(433): Whoops\Run->handleError(1, 'Uncaught Runtim...', '/libraries/gant...', 636) #4 /libraries/gantry5/classes/Gantry/Component/Whoops/SystemFacade.php(155): Whoops\Run->handleShutdown() #5 [internal function]: Gantry\Component\Whoops\SystemFacade->handleShutdown() in /libraries/gantry5/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php on line 636

**Comment by mahagr** [comment]
It should be looking at that file from `/libraries/gantry5/assets/css` folder. Do you have some other component that is also using Whoops?

You can likely work around the issue by copying the file from my location into `/libraries/gantry5/vendor/filp/whoops/src/Whoops/Resources`, but the fix needs to be applied every time you update Gantry.
