### ISSUE TITLE
Modules background appear, but it should not

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#285]
If I use the default Gantry classes then modules' background appear in all width, but it should not.

For example:
I add visible-desktop class to showcase section and I go to below 960px with then the modul disappear but the module's background appear.

![responsive-classes](https://cloud.githubusercontent.com/assets/1657924/7666066/499f8bba-fbd5-11e4-83c9-5a250da17d87.jpg)

![01](https://cloud.githubusercontent.com/assets/1657924/7666067/4b6a1f96-fbd5-11e4-8b36-26c0e7001b85.PNG)

![02](https://cloud.githubusercontent.com/assets/1657924/7666068/4f07d616-fbd5-11e4-8bb1-a5fe50dd4258.PNG)

![03](https://cloud.githubusercontent.com/assets/1657924/7666069/5066bb76-fbd5-11e4-867d-a50ac6eadd64.PNG)

**Comment by adi8i** [comment]
it's a kind of bug, this have been discussed. Add `hidden-phone` `hidden-tablet`

**Comment by adi8i** [comment]
Dose that worked for you? This one is related to #181 . Feel free to close it, if is ok now :)

**Comment by mahagr** [comment]
This one might be a hard one as we are using absolute sizes and hiding an object doesn't make the other containers to fill up the width or to collapse the container.

@kevlardev I think we need you on this one.

**Comment by adi8i** [comment]
You need to use `@media` and `display: none` . From my point is an issue here, must be a better way to handle this, but will require some changes.

**Comment by kevlardev** [comment]
In this particular case, the showcase section is still appearing as there is a separate top/bottom padding added to the #g-showcase (as well as the other sections) for additional spacing. When the modules are gone, the padding is still being rendered.

The easiest way would be to add the visible-desktop class to the showcase section via the config gear in the layout manager, as opposed to the block themselves. This will cause the entire section and its padding to collapse in smaller breakpoints. Alternatively you can override the css to force the padding of #g-showcase to be 0 in those smaller breakpoints but adding the class to the section would be the cleanest approach.
