### ISSUE TITLE
Inner page showing blank screen and home page is rendering => WordPress Helium Theme V5.4.11 with Gantry5

### ISSUE THREAD

**Issue by linishshatter** [gantry/gantry5#2850]
Hello,

I had encountered a weird issue with the grantry5 framework and helium theme in WordPress.
I am using InMotion hosting and all of a sudden the websites stopped working.
Home page of the website is loading but none of the inner pages are loading.

I had tried the same with my local and with another hosting and both worked fine.

The website is working perfectly under default theme.

https://thereisabusinessforyou.com/ [ Working ]
https://thereisabusinessforyou.com/our-team/ [ Not Working - Just Blank Screen ]

Plugins I Use

- AWSM Team Pro
- BackupBuddy
- CF7 Invisible reCAPTCHA
- Classic Editor
- Contact Form 7
- Gantry 5 Framework
- Google XML Sitemaps
- MetaSlider
- Really Simple SSL
- ShiftNav Pro - Responsive Mobile Menu

Gantry Theme Version: Helium V5.4.11

Any help will be appreciated.

**Comment by linishshatter** [comment]
Anybody ?

**Comment by marktaylor46** [comment]
Your page is working fine for me? Clear your browser cache and try again.

![2021-08-17_09-43-13](https://user-images.githubusercontent.com/11683218/129694108-06414661-a335-4ab1-9dc4-e7b460fae85d.png)


Regards, Mark.

**Comment by linishshatter** [comment]
@marktaylor46 
Thanks for the response. I had checked now and it looks fine to me.
So I believe the server guys might have fixed something.
Closing the issue as its all good

Thanks Again!

Linish
