### ISSUE TITLE
Gantry 5.5 - Joomla 4 - blog pagination icons missing

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2851]
Something seems to have gone awry with the blog pagination icons as they no longer show. Seems to be something to do with classes uses and fontawesome for joomla.

![2021-08-17_15-27-19](https://user-images.githubusercontent.com/11683218/129745857-782ce203-cad7-468a-9cdf-1bd8c289ec41.png)

**Comment by hexplor** [comment]
Noted, fixed in repo, icons added. Fix will be available in next build.
