### ISSUE TITLE
Potential Upgrade Issue on Pre-Update Check for Joomla 4.0.0

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2852]
When I check for joomla upgrade , a warning came up.

![gantry5-potential-issues](https://user-images.githubusercontent.com/3976174/129854754-ad670964-8596-48f0-961d-61d7e463a478.png)

**System Info**:
Joomla 3.10
PHP 7.4.13
Gantry 5.4.37

**Comment by marktaylor46** [comment]
Gantry 5 is not yet compatible with Joomla 4 - so do not update yet. We're actively working on this and, once ready, we will release Gantry 5.5 (together with Helium and Hydrrogen template updates). This will then be followed by updates to all RocketTheme Gantry 5 templates (this will take some time). In the meantime, you can carry on using J3.10.x

Regards, Mark.

**Comment by mariantanase** [comment]
ok, thanks
