### ISSUE TITLE
Gantry 5.5: Saving a Style - CSS issue

### ISSUE THREAD

**Issue by Raere** [gantry/gantry5#2854]
Joomla 4
Gantry 5.5
Template: Helium

While saving the style, a popup appeared and then disappeared quickly. This happens with each saving of the style. I was able to capture the popup content of warnings. See attached file.

[save-styles_css-issue.txt](https://github.com/gantry/gantry5/files/7024316/save-styles_css-issue.txt)

**Comment by mahagr** [comment]
@hexplor You were working on this, how did you silence those deprecated messages?

**Comment by hexplor** [comment]
```$output-bourbon-deprecation-warnings: false !default;``` should do the trick. Taken from there: https://github.com/lacroixdesign/node-bourbon/issues/37
Gonna take a look.

**Comment by hexplor** [comment]
I can't reproduce that. Can you tell me exact steps, what values did you modify to have that appeared?

**Comment by marktaylor46** [comment]
I get this too:

![2021-09-09_10-07-49](https://user-images.githubusercontent.com/11683218/132657542-cf9f46f1-4f2c-459e-a55d-6367a475af69.png)

To recreate this issue... Clean rocketlauncher installation of "horizon" 
Update to J3.10.1
Update to G5.5
Go to "home" outline > styles.
tick the override box next to "main styles > text" and press "SAVE" - then you get the boubon deprecated errors.

**Comment by mahagr** [comment]
It's because Bourbon removed a lot of legacy stuff, which we are using. The deprecation messages can be silenced, but I'd rather get the themes modernized at some point.

**Comment by marktaylor46** [comment]
Ok, something needs to be done because right now you can't compile the CSS for any RT template.

Could we perhaps added a toggle in "page setting" to silence deprecation messages for now - I know you want to fix things properly but that could take a long time if every theme needs to be updated?
