### ISSUE TITLE
Gantry5.5 and GRAV: no pagination in GRAV content particle

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#2855]
Please see attachment: there is no pagination in GRAV content particle, even if I enabled it in the settings.
I set the columns to 3 posts and I have 6 posts in the same category, so there should be the pagination dots under the first 3 posts. Instead they are displayed in two rows of three posts each.
Working locally with GRAV 1.7.18 and helium theme
<img width="1403" alt="shot" src="https://user-images.githubusercontent.com/11693902/130321325-62b694da-a270-4085-bb88-229dad490a05.png">

**Comment by linishshatter** [comment]
Can you share the settings screenshot?
Also did you try controlling the Pagination limit under Settings -> Reading

**Comment by beamaria** [comment]
Ok, I tried to set the default number to:
3 -->no pagination buttons or dots for the next three posts
4 --> one post in the second row with buttons prev-next, but clicking on "next" button i receive this error "AJAX FAILED ON ERROR"

What kind of settings you need the screenshot of?
Grav content particle or what else?

**Comment by mahagr** [comment]
See the above fix. I'll be making new builds later today, too.
