### ISSUE TITLE
Gantry 5.5 - Joomla 4 - Call to undefined method setOutputStyle() ScssPhp\Compiler

### ISSUE THREAD

**Issue by vkengo** [gantry/gantry5#2857]
Call to undefined method ScssPhp\ScssPhp\Compiler::setOutputStyle()

![image](https://user-images.githubusercontent.com/4046453/131336548-e1dd125e-5a5a-4fc1-9c0e-8d50185f5a4e.png)

Joomla Stable: 4.0.2
PHP 7.4.9
Local server: Laragon

I run other Joomla 3.10+ and Gantry 5.4.37 on the same server no issues with compiling.

**Comment by mahagr** [comment]
The above lines do not match with the latest builds. Maybe you should try to upload the latest Gantry build and try again?

**Comment by vkengo** [comment]
I've downloaded the latest packages and installed them and getting the same error.
![image](https://user-images.githubusercontent.com/4046453/131465972-d14ee255-5675-4a80-8c28-d190c3283a10.png)

I've updated Laragon to the latest as well, still with PHP 7.4 (downgraded to test 7.2, 7.3 has the same error). 

I've tried Helix 2.0.2 which users the same compiler and got the same error.

Somehow it's related to the server and compiler, as with Helix I had the same error on both J3 and J4, frontend only loads when SCSS compiler is off.
![image](https://user-images.githubusercontent.com/4046453/131467454-c6f5be4e-43e6-4b46-b486-f7c9b36aa999.png)

I've used a site with a back-up at 3.9.28 and installed all the 5.5 packages, I could compile the style - no errors and the template loaded on the frontend, only error with the menu:

![image](https://user-images.githubusercontent.com/4046453/131469378-c4f36560-1724-4423-960c-0a39cd66623c.png)
![image](https://user-images.githubusercontent.com/4046453/131469584-e1d25fe1-05e6-416e-b6f3-37eea9db9158.png)
![image](https://user-images.githubusercontent.com/4046453/131469680-cf440d3e-1fd6-4abd-a130-df47b39676f5.png)

I will try to repackage the sites on to a live server online later this evening and see if the issue is local (which I'm guessing) and hopefully we'll know why.

Thanks

**Comment by mahagr** [comment]
Maybe there's a conflict with the SCSS compilers in Helix vs Gantry. We are using the latest version, try to look for `vendor/scssphp` folder in Helix?

For the second error, I just updated the builds with some menu fixes.

**Comment by vkengo** [comment]
I've installed Helix after Gantry to test, as I don't use it, just wanted to isolate the issue if it's vendor specific. I'll uninstall Helix as I just want to get Gantry to work in my dev workflow for J4, will need to upgrade a few site later. I'll have a look in the vendor folder as well and see what version they have.

I'll update and test the menu.

Thanks

**Comment by mahagr** [comment]
It looks like nobody else can get the error with clean installations, at least. I am pretty sure that you have somewhere extension which has older version of phpscss library.

**Comment by vkengo** [comment]
An unfortunate situation kept me away for a couple of weeks. I'm back and tested with a clean install of the latest J 4.0.2 and Gantry 5.5(12/9/21) + Helium and all is working fine.

Must have been something conflicting as the other site I've been working on, has been updated from an early beta version.

**Comment by mahagr** [comment]
Thanks for your response. I think that it may have been a bug in early dev release, too.

**Comment by Taz-1999** [comment]
Hi, just updated to Gantry 5.5.5 and got the same error. 

After some experimentation with the clues in this thread the problem in my case was I also had JoomDev's JD Builder 1.11.3 and Astroid framework 2.5.4 and Astroid Template One 1.3.4 + Zero 2.5.4. Turned of all of it and the problem went away. 

JoomDev is shutting down it's Joomla! products development, so no more updates will be made to JoomDev/Astroid. A fix is therefore unlikely.

I hope this helps if someone else runs into the same problem.

**Comment by ConfidantCommunications** [comment]
That helped me, thanks! I disabled the Astroid plugin and then Helix stopped its error message.
