### ISSUE TITLE
Gantry 5.5 - Joomla 4 - renaming of a particle in the menu result in "400 bad request"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2858]
JOOMLA 4

If you add a particle into the menu in G5.5 menu editor and save that works ok. But if you then edit the particle again to rename the particle this gives a "400 bad request" error.

![2021-09-01_15-20-51](https://user-images.githubusercontent.com/11683218/131688556-8efe3f7d-c5c5-452d-b231-890bfe37171d.png)

Note that the same thing happens if you insert a module and rename that too.

**Comment by mahagr** [comment]
OK, there is definitely something going wrong in Joomla 4. If you reload the page, the particle becomes a regular menu item.

**Comment by mahagr** [comment]
Also in the Joomla menu editor, the custom fields for Gantry 5 menu are missing.

**Comment by mahagr** [comment]
This seems to be fixed, too.

**Comment by marktaylor46** [comment]
confirmed fix
