### ISSUE TITLE
Gantry 5.5: Bootstrap 5 scripts cannot be disabled by Javascript Frameworks atom

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#2859]
Platform (local MAMP Pro):
Joomla 4.02, Gantry 5.5-dev, PHP 7.4, no cache, no SEO plugin

**Steps to reproduce**
Add the Javascript Frameworks atom in your Joomla outline
Uncheck Bootstrap framework
Check your HTML header

**Expected result**
Bootstrap 5 scripts are not loaded

**Actual result**
All Bootstrap 5 scripts are loaded by default

<img width="592" alt="Capture d’écran 2021-09-02 à 22 02 29" src="https://user-images.githubusercontent.com/3645531/131910276-aa5cd103-6191-4b02-af2f-8f56f3f0c080.png">
<img width="903" alt="Capture d’écran 2021-09-02 à 22 03 33" src="https://user-images.githubusercontent.com/3645531/131910318-6a2ff981-7fe2-4d70-9b43-0a60bdde8a2e.png">

**Comment by mahagr** [comment]
Joomla may load the scripts regardless of Gantry; basically, the Frameworks Atom just forces the scripts to be always loaded.

**Comment by uGE70** [comment]
Thanks for your explanation. I just want to add that I can uncomment the HTMLHelper::_('bootstrap.framework'); method in /libraries/gantry5/src/classes/Gantry/Framework/Document.php line 311 and everything is apparently running fine if no Bootstrap component is used or individually loaded when needed (ref https://github.com/joomla/joomla-cms/discussions/32842).

**Comment by mahagr** [comment]
I think that the reason why that line exists was that most of the modules which need the JS were not loading it. I'll review the logic as J4 seems to have changed some things (I think that even that discussion is now deprecated as J4 added assets manager).

**Comment by uGE70** [comment]
Thanks for considering it. I have already written a plugin to unset all those Bootstrap JS files, but I guess it would be nice to have a built-in (Gantry) way to choose to load them all or not. On Cassiopeia, they are not loaded by default.

**Comment by uGE70** [comment]
Thanks for this fix. I can confirm it's working. By the way, I have been using 5.5 on a Joomla 4 site for the last 10 days and it's working beautifully. Thanks for this huge work.
