### ISSUE TITLE
Menu item name auto update

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#286]
The issue is still there, you need to navigate to `menu` and change the item name there.
![capture](https://cloud.githubusercontent.com/assets/9744973/7666856/3f719034-fbfd-11e4-95e4-8ff9e5d0a738.PNG)

**Comment by w00fz** [comment]
You mean renaming the menu item from Menu Editor is not reflected on frontend?

**Comment by adi8i** [comment]
Yes that is

**Comment by w00fz** [comment]
Ok weird I thought this was fixed already. Any thoughts @mahagr ?

**Comment by adi8i** [comment]
This one is working too now, but there should be a reason why it didn't worked yesterday for me, same for #283 . The may still be some conflicts with `custom/config` folder i think.
