### ISSUE TITLE
Undefined constant Gantry\Framework\Base\GANTRY_DEBUGGER

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [gantry/gantry5#2860]
Hi

In a fresh install of Grav 1.7.20, with the Gantry 5.5.5 development package, system show this issue:

**Undefined constant "Gantry\Framework\Base\GANTRY_DEBUGGER**

How can I configure Grav to support Gantry 5.5.5?

Thanks.

**Comment by mahagr** [comment]
`GANTRY_DEBUGGER` is a constant which should be always loaded. Where are you seeing this error (please enable debugger to see the traceback)?

**Comment by mahagr** [comment]
Now the error is at least better. That said I'm not able to reproduce this bug locally.

Can you enable debugger from `system.yaml` file so we can see where the error comes from?

**Comment by pmoreno-rodriguez** [comment]
> Now the error is at least better. That said I'm not able to reproduce this bug locally.
> 
> Can you enable debugger from `system.yaml` file so we can see where the error comes from?

**Comment by pmoreno-rodriguez** [comment]
Hi.

After install grav-pkg_gantry5_v5.5.0-dev.zip throug direct install, in Grav admin page, this is showed:

[Crikey! There was an error.._.pdf](https://github.com/gantry/gantry5/files/7167682/Crikey.There.was.an.error._.pdf)

**Comment by mahagr** [comment]
Thank you, I will try to track the issue down.

**Comment by mahagr** [comment]
Above commit should fix the issue, can you try it out?

**Comment by pmoreno-rodriguez** [comment]
Hi.

Now all works fine. Thanks for your help
