### ISSUE TITLE
preg_match twig filter not accepting escaped /

### ISSUE THREAD

**Issue by jmshey90** [gantry/gantry5#2862]
If I used:
`{% set test = preg_match('/[^\/]+$/', item.link) %}`

I get the following error:
> An exception has been thrown during the rendering of a template ("preg_match(): Unknown modifier ']'")

Seems its not recognising the escaped /

**Comment by mahagr** [comment]
What happens if you remove the backslash? It's odd, though, as the code works in my test environment... Which php version are you using?

**Comment by jmshey90** [comment]
Same error. I have debug mode enabled in Joomla btw. I'm on php 7.4.12.

**Comment by mahagr** [comment]
Try `{% set test = preg_match('|[^/]+$|', item.link) %}`

**Comment by jmshey90** [comment]
That works

**Comment by mahagr** [comment]
Where did you see the non-working code?

**Comment by jmshey90** [comment]
It was inside a custom particle I am creating

**Comment by mahagr** [comment]
OK. I'm closing the issue as 3rd party then.
