### ISSUE TITLE
Gantry 5.5 Joomla - media picker giving error in browser console "dropzone is not a constructor"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2865]
When the G5.5 media picker is used it is giving an error in the browser console:

"uncaught typeerror: dropzone is not a constructor"

![2021-09-07_11-44-57](https://user-images.githubusercontent.com/11683218/132332151-83cd4264-3926-4a38-88d5-664bc8c958a7.png)

**Comment by mahagr** [comment]
Happens also in J3.10..

**Comment by mahagr** [comment]
@hexplor can you take a look?

**Comment by marktaylor46** [comment]
It does happen in J3.10.1 as well as J4 but it is Gantry 5.5 that is the cause as G5 is fine

**Comment by hexplor** [comment]
Should be fixed in next build.
