### ISSUE TITLE
Gantry 5.5 - admin tab order has been changed

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2866]
In Gantry 5 the tab order is "styles" followed by  "layout"

![2021-09-07_11-49-16](https://user-images.githubusercontent.com/11683218/132332744-443feb85-e3e9-4011-a17b-00e4fe30fe3c.png)

In Gantry 5 the order has been changed and now defaults to "layout" rather than "syles" when opening G5 admin.

![2021-09-07_11-49-44](https://user-images.githubusercontent.com/11683218/132332820-8df985ae-0709-478a-b226-c42b849c3abf.png)

**Comment by mahagr** [comment]
This is what we agreed about a year ago.

**Comment by mahagr** [comment]
https://github.com/gantry/gantry5/issues/2638

**Comment by marktaylor46** [comment]
Ok well I don't remember agree to that - and it's not that way in G5.4 - but ok.
