### ISSUE TITLE
Gantry 5.5 - Joomla 3.10.1 "styles" dropdown customhtml particle now just shows title rather than content

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2868]
In RT templates we have a dropdown menu item called "styles" in the front end that uses a customhtml particle to show the various styles options. In Gantry 5.5 instead of displaying the html of the particle in the dropdown (showing the style presets) it now only shows "customhtml" title and not the particle contents.

![2021-09-09_09-39-54](https://user-images.githubusercontent.com/11683218/132653128-b271c3a5-5b5e-430f-a5db-e2f863d11454.png)

![2021-09-09_09-41-35](https://user-images.githubusercontent.com/11683218/132653304-30b4fac2-2032-4f3c-95ea-216b362871a0.png)

**Comment by mahagr** [comment]
This has also been fixed in the new build. Just make sure you have new installation, not broken one.

**Comment by marktaylor46** [comment]
confirmed fix
