### ISSUE TITLE
Gantry 5.5 - J3.10.1 - after installing G5.5 the previoulsy set menu columns are removed.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2870]
After installing Gantry 5.5 the columns that were previously set in Gantry 5 menu editor have been removed.

![2021-09-09_09-56-33](https://user-images.githubusercontent.com/11683218/132655932-9b1c8375-90bb-44db-aea6-a64d316afb49.png)

![2021-09-09_09-57-38](https://user-images.githubusercontent.com/11683218/132655945-dd028562-8476-4176-a950-ad9239b1ba77.png)

In fact it's worse than that... in fact, ALL Gantry 5 custom menu fields have been lost (e.g. downdown width, classes, icons, images, etc etc).

**Comment by mahagr** [comment]
This seems to be fixed, too.

**Comment by marktaylor46** [comment]
Confirmed fix
