### ISSUE TITLE
Gantry 5.5 - Joomla 4 - lack of moduletable class DIV in J4 causes layout to change

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2873]
In Joomla 4 it appears that you no longer get the "moduletable" DIV surrounding content of a module in a module position on the layout of your outline. As a result of this any CSS that acted upon this class no longer applies and therefore the layout changes

Example "Horizon" theme

![2021-09-10_13-35-05](https://user-images.githubusercontent.com/11683218/132854306-1c27ef13-16c3-4f0c-8061-5e9c10d75b5e.png)

![2021-09-10_13-36-57](https://user-images.githubusercontent.com/11683218/132854317-04c122ae-678e-4a65-8349-014ad98d8914.png)

Note the difference in margin as Horizon applies a negative margin to the "moduletable" class.

Also note that "moduletable" class is also used in Wordpress and GRAV themes too as Gantry 5 write them in (I think?)

If this cannot be fixed then users need to be made aware of this as it may affect their own custom.scss too and therefore need altering once an Upgrade to G5.5 is made.

**Comment by mahagr** [comment]
Yeah, I noticed the same. We need to check if we're able to add the class easily enough...

**Comment by marktaylor46** [comment]
Don't think it's as simple as that as it's html structure that changed too. I.e. the class was ona DIV that no longer exists in J4 - so the CSS would likely need to be changed anyhow to accommodate new structure.

**Comment by mahagr** [comment]
@hexplor This needs a fix for every theme. This is why I have update instructions for every theme that should support J4.

**Comment by marktaylor46** [comment]
Just adding here also that because the DIV with the class "moduletable" is now missing from the rendered HTML this also has the effect that module class suffixes are no longer rendered either and therefore are not working at all causing significant layout differences between J3.10.1 and J4.0.2.

**Comment by hexplor** [comment]
Good find. Will see what can i do.

**Comment by hexplor** [comment]
> Just adding here also that because the DIV with the class "moduletable" is now missing from the rendered HTML this also has the effect that module class suffixes are no longer rendered either and therefore are not working at all causing significant layout differences between J3.10.1 and J4.0.2.

What do you mean by "module class suffixes are no longer rendered"? Module suffixes are not connected with moduletable class. Quick example: 
![image](https://user-images.githubusercontent.com/1741273/133427585-aa9b0bf3-29fd-422f-a449-b03aee100f95.png)

**Comment by marktaylor46** [comment]
See Chimera for Gantry 5 "blog" page.

The module class suffix field for a module is rendered on the save DIV as "moduletable" class which is no longer rendered under Gantry 5.5

![2021-09-15_13-05-33](https://user-images.githubusercontent.com/11683218/133430536-04f64fa7-a4b2-4e56-adf8-31340fb56d18.png)

![2021-09-15_13-06-23](https://user-images.githubusercontent.com/11683218/133430559-ae57eead-003b-4d14-98dc-d9751409303b.png)

**Comment by hexplor** [comment]
So Mark,
New helium install. Assigned Module:Custom from joomla into slideshow-a position. Added box3 module suffix. All works. Custom suffix, and moduletable class is added as well. 
![image](https://user-images.githubusercontent.com/1741273/133439186-b6b059e5-56bd-4733-abe9-96a8147fc06c.png)

Can you provide more detailed steps?

**Comment by marktaylor46** [comment]
Sure is an example for Myriad for G5 rocketlauncher on the "pages > blog" page
Look at how the "join our newsletter" module has been rendered:

First on J3.10.2 with Gantry 5.5 DEV

![2021-09-15_14-20-30](https://user-images.githubusercontent.com/11683218/133442119-826fbfc9-b2aa-46ea-8273-38cadf59471e.png)

Then the same site updated then to Joomla 4:

![2021-09-15_14-22-35](https://user-images.githubusercontent.com/11683218/133442192-cc3b3e30-f5d8-4269-aa5b-4fb6d6c4fd28.png)


See how the "moduletable" DIV that also had the module class suffix is no longer rendered. Therefore the content is not centered.

Note also that the module title is also not rendered at all now.

**Comment by mahagr** [comment]
Should now be fixed.

**Comment by marktaylor46** [comment]
How is this fixed? Nothing has changed as far as I can tell?

**Comment by mahagr** [comment]
All themes require updates to properly support Joomla 4. This tracker is for Gantry 5 only and the issue has been fixed for Helium and Hydrogen.

**Comment by EvilSound** [comment]
Hello friends. Sorry to reopen an old thread, but the same thing happens to me. I have upgraded to Joomla! 4 and module class suffix has disappeared. Therefore, it no longer reads the changes that I had for the modules in the custom css. I use Helium (v5.5.14/g5_helium).

**Comment by sju10544** [comment]
Sorry too. But after migrating our large site https://www.developmentscout.com/ to Joomla 4.4 with Gantry 5.5.17 and the Notio template 1.5.0 same thing happens.
The moduletable DIV doesn't load either with a custom test module on different positions. Only on a fresh Helium template it works. But as far as you add a new position on the Helium template, the moduletable doesn't work and the g-title doesn't show up.
Every help would be great!

**Comment by N8Solutions** [comment]
@hexplor Is it possible for you to look into this for these individuals? What with Mark having passed away and Matias no longer being involved with the project due to his illness, you're the only other one on the ticket familiar with the issue. Maybe you can just comment and let us know if this was fixed internally and that the RT templates have been updated as the Helium and Hydrogen templates were according to @mahagr ??

**Comment by N8Solutions** [comment]
@sju10544 since you are using the latest version of the Notio template, you should open a ticket in the RT Forum for this referencing this issue for better context.
https://rockettheme.com/forum/joomla-template-notio

**Comment by sju10544** [comment]
@N8Solutions thanks a lot for the reply. Tried to open a ticket but after login to my account I got this: 403 Forbidden
"403 You do not have permissions to access this page."

**Comment by sju10544** [comment]
O.K. Thanls guy. Just posted it here: https://rockettheme.com/forum/the-marketplace/290806-moduletable-div-doesn-t-load-with-gantry-5-5-17-and-joomla-4
