### ISSUE TITLE
J!4: Gantry5 particle Joomla articles Edit Link

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2877]
Hi there,
We have an issue with **Show Edit link** feature (Joomla Articles particle -> Display tab -> Show Edit link)
The edit link button not working when clicking on it. The result returned  with a blank page. Could you please check ?
Note: The edit link text is not translated for Joomla 4 (COM_CONTENT_FORM_EDIT_ARTICLE), we should add the language string to translate it or replace with JGLOBAL_EDIT

Platform: Joomla 4.0.3, Gantry5 latest build at https://github.com/gantry/gantry5/issues/2789
Steps: Add Joomla articles particle via theme layout and enable show edit link feature, login to front-end and click edit link button.

**Comment by mahagr** [comment]
Should be fixed in above commit ^
