### ISSUE TITLE
J4!: Article front-end editing

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2881]
Hi there,

The **CMS Content** feature no longer working in article front-end editing mode. The modal popup returned with empty content (Article, Contact, Field, Media, Menu, Module, Page break, Read more and the **Versions** button caused the issue too).

![editing](https://user-images.githubusercontent.com/2299347/134802114-c53c40ae-137f-4813-a398-14ff7ababf9a.png)

One more, please help clean up the js source map for main.js (Notice: DevTools failed to load source map: Could not load content for root/media/gantry5/assets/js/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

I'm using the latest build Gantry 5 v5.5 and Hydrogen ( added a screenshot with default Cassiopeia theme)

![article-editing](https://user-images.githubusercontent.com/2299347/134801967-6bb992f0-bf48-4d61-a018-b6a9aeed4a4e.png
)

Thank you

**Comment by mahagr** [comment]
I just confirmed the issue. It looks like the content is being loaded by ajax call, but the modal content isn't being updated.

**Comment by mahagr** [comment]
For me, it's not working in Cassiopeia either. Hmm...

**Comment by tonamphong** [comment]
Hi Mahagr,
You can download the J4 package and create a clean installation for testing. I tested with Joomla 4.0.3 and Gantry5/Hydogren CI build at https://gantry.org/downloads#ci-builds
System info

![info](https://user-images.githubusercontent.com/2299347/135083517-7eb63df1-4655-4bd5-9afd-2010521e8b7a.png)

Clean installation then create only single article to test, result
Default Cassiopeia template (Article option)

![info1](https://user-images.githubusercontent.com/2299347/135083940-19543077-46c0-47fb-bd39-7c25105003d9.png)

Media option

![info3](https://user-images.githubusercontent.com/2299347/135084400-88aa6a4a-be3d-4943-81cf-4310adb276d1.png)

Hydrogen

![info2](https://user-images.githubusercontent.com/2299347/135083974-6750b9d8-7ac5-4132-9a89-45c467303d0a.png)

Media 

![info4](https://user-images.githubusercontent.com/2299347/135084500-ff1b36b2-cba8-450e-bc5f-ecad01658885.png)

Hope that helps.

**Comment by tonamphong** [comment]
Ok, it seems we have a duplicate **modal** class that's added  to the iframe body instead the parent DIV.
Default Cassiopeia

![info5](https://user-images.githubusercontent.com/2299347/135089396-0019f23e-bcab-48d9-819f-2333763e08eb.png)

Hydrogen (duplicate modal class)

![info6](https://user-images.githubusercontent.com/2299347/135089477-5102588a-5b8e-4f60-ac55-b93d3380b762.png)

here the result if we remove the extra modal class at iframe body
![info7](https://user-images.githubusercontent.com/2299347/135089888-26004a61-3ce6-42e1-bab5-dfc31ac97cec.png)

Note: We can import some scss files from cassiopeia to improve the UI.

**Comment by mahagr** [comment]
@hexplor Can you take a look?

**Comment by mahagr** [comment]
I removed `contentpane` and `modal` classes, but the modal looks just horrible.

**Comment by hexplor** [comment]
Can you please check with the latest build? I've made lots of adjustments and fixes.

**Comment by tonamphong** [comment]
@hexplor Its working now :). Thank you
We just need to style the table and the toolbar buttons a little bit, i.e: 

![a1](https://user-images.githubusercontent.com/2299347/135353531-6fba3b97-1a5c-4dca-a3a4-24e892cd5409.png)
![a2](https://user-images.githubusercontent.com/2299347/135353556-c3d47b06-c03c-4e7f-a451-7e8351dd4eae.png)

**Comment by hexplor** [comment]
New build should be ready soon.  Made lots of fixes. Please check when new build will be available. Thanks :)(

**Comment by tonamphong** [comment]
Hi @hexplor 
Yes, It looks better now
