### ISSUE TITLE
J4! Menu Dropdown

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2883]
Hi there,

Steps:
1. Add some menu items then assign to parent menu item.
2. Go to theme settings -> Menu -> click to parent menu item, i.e: Home
3. Add new column for the parent menu item, in this case, just add new 01 column for testing purpose. Save
4. Next, remove the column that we just added before.
5. Save and test the front-end.

![step](https://user-images.githubusercontent.com/2299347/135111947-7ae55ea8-0f89-494f-a15b-f15afd9a2e07.png)

Problem: Its working fine with **J3/Gantry/Hydrogen 5.4.37**, the parent menu item revert back to single dropdown column(class: )

Here the correct class for parent menu item (after removing the column via menu editor)

![correct](https://user-images.githubusercontent.com/2299347/135110190-9f5bd0c0-8338-4c40-995f-e8ba8bc6e359.png)

However, with **J4/Gantry/Hydrogen 5.5** latest CI build, the result like so

![incorrect](https://user-images.githubusercontent.com/2299347/135110524-446e6569-28cd-4515-90a8-89069259192f.png)

The parent menu item still remains the class **g-fullwidth** instead **g-standard** like the correct case event we removed the mega columns layout. It should be reset the parent menu class to g-standard for dropdown instead g-fullwidth of mega-menu.

I have noticed the small change for input group field alignment (particle settings), this caused by Atum css, please improve it if its correct, here the screenshot 

**J3**
![j3](https://user-images.githubusercontent.com/2299347/135113453-b23a61e6-a077-4e0e-bb1a-ed50e50f2195.png)

**J4**
![j4](https://user-images.githubusercontent.com/2299347/135113503-a69550c6-069c-451b-bb8c-d03baefc47b9.png)

Thank you

**Comment by tonamphong** [comment]
Update: This issue caused the back-end Menu editor too. You can add new columns but you cannot delete the empty columns :). The grid column layout reverted back with broken layout when you save and reload the page.

![issues](https://user-images.githubusercontent.com/2299347/135232664-be1e5f32-7781-4b20-855f-c49a08b7062a.png)

**Comment by mahagr** [comment]
I fixed the columns saving, though it now always removes empty columns.

On the other issue, please also check that the menu width is set to auto.

**Comment by tonamphong** [comment]
@mahagr Yes, I see the issue is fixed with latest commit. Dropdown width is Auto :), I think you meant the dropdown style ? By default, dropdown style is assigned to **Use Default**, I changed between **Simple** and **Extended** mode and it worked, not sure about the caches or something like that. Thanks

**Comment by mahagr** [comment]
Oh, I meant the style. I'm closing the issue as being fixed.
