### ISSUE TITLE
fadeout recompilation not working in Gantry 5.5.0-dev-c66ab5d7a

### ISSUE THREAD

**Issue by tramber91** [gantry/gantry5#2885]
Hi all
I test latest version of Gantry 5.5 (5.5.0-dev-c66ab5d7a) and I have SCSS recompilation issue (Gantry admin, template hydrogen latest version)

on fadout line, like
`color:  fadeout($navigation-text-color, 25%)`;

Or
`@include background-image(linear-gradient(top, transparentize($accent-color-1, 90%) 0%, $accent-color-1 100%));`

Same custom scss files are OK for compilation in Gantry 5.4.37 !!

Alone like that ?

take care

Bertrand

**Comment by tonamphong** [comment]
It seems the issue caused by scss syntax and new scss compiler. Try this
`color: fade-out($navigation-text-color, 0.25);`

**Comment by tramber91** [comment]
It works thanks
=> need scss review !!

**Comment by mahagr** [comment]
https://github.com/gantry/gantry5/blob/develop/Joomla4-support.md

SCSS applies to everyone. :)
