### ISSUE TITLE
What is the function of Particle-CSS_Classes field?

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#289]
In our Docs for the Social Particle -> [http://docs.gantry.org/gantry5/particles/social#settings](http://docs.gantry.org/gantry5/particles/social#settings "Settings")
reading this, I believe a user would assume that the Class field would allow you to enter a class that would help you style the Particle.

![docs-social](https://cloud.githubusercontent.com/assets/3792467/7667421/c1125af2-fbd4-11e4-901a-0d2ca42a116e.jpg)

This is not what happens.

Using Gantry framework `joomla-pkg_gantry5_v5.0.0-rc.2` and `callisto-1.1.0-template` I placed our Default Social Particle in the Navigation section.

![social-default-particle-block-settings](https://cloud.githubusercontent.com/assets/3792467/7667418/ac60ce40-fbd4-11e4-8349-dbede1784da4.jpg)

I entered the class name of `testclass` in the BLOCK CSS classes field.

Next I did the same for the Particle tab:

![social-default-particle-settings](https://cloud.githubusercontent.com/assets/3792467/7667417/ac606eaa-fbd4-11e4-8357-d243e20d462a.jpg)

After Saving everything and clearing the caches this is what shows up on the front end:

![social-default-particle-fp](https://cloud.githubusercontent.com/assets/3792467/7667416/ac60721a-fbd4-11e4-9e4e-12f9197425ca.jpg)

The BLOCK `testclass` is output in the HTML but **NOT** the PARTICLE `testclass` or the Default entry of `social-items`

Is this a bug or we don't understand what Particle CSS Class is supposed to do?

**Comment by marktaylor46** [comment]
I think this is wrong too - why would you want "CSS classes" on the "PARTICLE" tab as well as the "BLOCK" tab of the particle settings? Former doesn't render in frontend, but latter does.

Good spot Dan!

**Comment by adi8i** [comment]
It is doing exactly what is saying, i am not sure what you mean. But a particle have 2 tabs `particle` and `block` , at top . if you add a class under `block` field. that class will be placed at block level, as you have your `testclass` in the picture.

If you place it under particle tab will be placed where particle start.

**Comment by marktaylor46** [comment]
No it doesn't put a class on the "PARTICLE" tab and it does not render in frontend, it only renders if you put it on "BLOCK" tab. and you cas have different input on each of the two tabs and they're both called the same thing "CSS classes"?

**Comment by adi8i** [comment]
btw the one under block tab is usefull because you can style `g-content`

**Comment by marktaylor46** [comment]
yes - so what is the one on "PARTICLE" tab for if it doesn't render anywhere?

**Comment by adi8i** [comment]
it render...

**Comment by adi8i** [comment]
![capture](https://cloud.githubusercontent.com/assets/9744973/7667576/d4a33a8c-fc15-11e4-9998-97c33b52f6e0.PNG)

**Comment by marktaylor46** [comment]
We're talking about "social" particle?

**Comment by marktaylor46** [comment]
![2015-05-16_19-52-27](https://cloud.githubusercontent.com/assets/11683218/7667598/c015c798-fc05-11e4-90e7-62dfc7dc38d5.png)
![2015-05-16_19-55-51](https://cloud.githubusercontent.com/assets/11683218/7667599/c34c8f78-fc05-11e4-83e0-d78bba9dfa2e.png)
![2015-05-16_19-56-16](https://cloud.githubusercontent.com/assets/11683218/7667600/c6d019d0-fc05-11e4-835e-14ee861f2baf.png)

**Comment by DanGthatRokGallery** [comment]
adi8i You applied a Variation not a Particle CSS class name

**Comment by adi8i** [comment]
no @DanGthatRokGallery is not variation, that's a clean template, is not hydrogen, anyway is a little bug, the guys missed a line in social particle code, will be fixed :P

**Comment by DanGthatRokGallery** [comment]
@adi8i I know its a bug that's why I submitted the ticket ;)
My concern isn't for you but more the novice user who can't sync what the Documentation says to what REALLY happens. As Mods these things are very important to us, big or small.
I say it in the Forums all the time, I think Doc Ryan has done an AWESAMAZING job with our Documentation.

**Comment by w00fz** [comment]
@adi8i provided a PR with #291 that fixes this.
