### ISSUE TITLE
Gantry 5.5 - Particles in Menu are gone after update

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2892]
Hey Matias,

There seems to be an issue with the Gantry 5.5 update.
It seems to be related to the Menu Manager rework and the fact that now the Menus are stores in the DB.

Anyway, the issue is that when you update from an older Gantry 5 version to Gantry 5.5 you lose the particles that you have added in the Menu.
Here, have a look at [this video](https://youtu.be/PKQqSrxgF3w). It shows the issue in detail. This is a clean installation of the Helium RocketLauncher v5.4.37

Most of our templates come with particles in the Menu by default so I already feel how the support requests are flooding our forums :smiley: 

P.S. You've done an awesome job with v5.5! Thank you Matias!

**Comment by mahagr** [comment]
@JoomFX Can you test CI builds? The issue should be fixed in there.
