### ISSUE TITLE
Custom CSS classes won't display

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2898]
I have a Joomla! 4 clean installation.
I've installed the Gantry 5.5.0 package and then Hydrogen template. All fine.
On Default theme > Layout (tab) > Navigation (section) > Menu module instance > Click on wheel > Block (tab) > CSS classes.
Here I added my custom class.
Apply & Save

Result: on frontend, that class doesn't appear anywhere.

Joomla! 4.0.3
Gantry 5.5.0
PHP 7.4.13

**Comment by marktaylor46** [comment]
Did you install Hydrogen for G5.5?

**Comment by marktaylor46** [comment]
No problem, please can you close the ticket.
