### ISSUE TITLE
Classes are not added to the menu

### ISSUE THREAD

**Issue by mdoblas** [gantry/gantry5#2899]
I just upgraded to Gantry 5.5.0 and Helium 5.5.0, and the classes are not added to the menu. Classes are defined in: Menus: Edit Item -> Link Type -> Link Class.

Before the update it worked fine.

I have tried to add the classes from the Gantry Menu tab and from the Gantry Framework but it doesn't work in any case.

Joomla 3.10.2
PHP 7.3.27-9

**Comment by jmshey90** [comment]
Happens to me also

**Comment by mahagr** [comment]
The code had been improved since then, so I added the support.
