### ISSUE TITLE
Sidebar - how

### ISSUE THREAD

**Issue by mihha** [gantry/gantry5#29]
How can we create a sidebar in the main content area?

**Comment by JoomFX** [comment]
Hey mihha,

You need to select a Preset/Layout that has a Sidebar in it. Try with the "Test" or with the "Joomla - Protostar"

![alt](http://i.imgur.com/uWDQQOr.png)

**Comment by mahagr** [comment]
Did it help you @mihha? Can the issue be closed?

**Comment by mihha** [comment]
That explains how to do it if I already have sidebars defined

What I wanted to learn is hot to add my own sidebars? For example I would want this layout

Main | sidebar1 | sidebar2

How can I achieve something like that?

**Comment by JoomFX** [comment]
Hey mihha,

Not sure if this is the best way to do it, but try the following:

1. Create a new file in "..templates/g5_hydrogen/layouts". For example "mihha.yaml"

2. Paste the following code in it:

 ```
header:
  container:
    - particle-menu

container:
  1:
    - main 60:
      - position-breadcrumbs
      - position-global_messages
      - pagecontent

    - sidebar1 20:
      - particle-social
      - position-sidebar
      - position-right

    - sidebar2 20:
      - particle-social
      - position-sidebar
      - position-right

footer:
  container:
  - position-footer
  - [particle-copyright 40, spacer 30, particle-branding 30]
```

3. Select the "Mihha" preset in the Layout Manager:

 ![alt](http://i.imgur.com/UkKltuO.png)

**Comment by mihha** [comment]
Thank you for that.

I have to admit that I got an impression that adding sidebar positions would be available in the Layout manager in the same way as you can add new rows and that you won't need to fiddle around with the YAML config files

I guess that this could be added as an improvement suggestion

**Comment by JoomFX** [comment]
No problem at all :)

I also think that creating and modifying the Layout should be done from the Layout Manager.
Here's what Andy said in the Gitter Chat:

`http://docs.gantry.org/gantry5/beta/roadmap#beta-2 first item is this “Configurations Page"`

So I suppose we'll have this feature in Beta 2 ;)

**Comment by mahagr** [comment]
We had layout manager having all the power described above, but it was so confusing and hard to use it so we just decided it will not happen. There is also second reason why we do not want to do that -- if you allow people to create any custom layout, you would also need to have CSS styling for every possible combination that user may have.

By not allowing users to freely set their layouts we make sure that the user has to know how to style the section he adds.

@JoomFX You misread Andy, he meant that there will be similar page to Joomla "styles" page, where you can see all the different layouts you have set up.

**Comment by JoomFX** [comment]
I see now.
Thanks for clarifying this @mahagr :)
