### ISSUE TITLE
Gantry 5.5.0 with Joomla 3.10 - ERROR

### ISSUE THREAD

**Issue by WolfgangDomroese** [gantry/gantry5#2901]
Today my Gantry5_package was updated to 5.5.0. But it does not work with Joomla 3.10 templates. So, I think, Updating should be inhibited? Or it should work with old template as well - thats what I expected.

T get a quick help,  I wanted to install "Helium" now. But installation ends with an error: "Manifestdatei (german)" not found. Does Helium no longer work with 3.10

So, what can I do to get the site to work rather soon (www.domroese.berlin)? Can I downgrade to G5_5.4? 

My idea was, to do these steps:

1. Update Gantry to 5.5
2. Change template to Helium.
3. Upgrade the whole site to Joomla 4.

Does that not work?

Kind regards, Wolfgang

**Comment by WolfgangDomroese** [comment]
...or do you look for this directory?
![image](https://user-images.githubusercontent.com/15429256/137873645-da6fed34-a837-47e7-af5e-41f771a16559.png)

**Comment by mahagr** [comment]
It looks good. In fact, I'm able to reproduce the issue.

**Comment by WolfgangDomroese** [comment]
That sounds perfect for me - so, I only have to wait for healing :-)

**Comment by WolfgangDomroese** [comment]
Please forgive me - I never did update components on my own. What to do after download on my local system? I want to avoid any new mistake. In the backend, I do an update? Or must I delete and do a new installation of  joomla-pkg_gantry5_develop.zip?
Thanks for your support!

**Comment by mahagr** [comment]
Hmm, OK, so you're not running to the bug but the file is really missing. Can you download the theme package and check if the file is in there? Or look into `custom/` folder if it's in there.

**Comment by WolfgangDomroese** [comment]
Searching the complete Joomla-folder by FileZilla, I do not find any file named subfeature. I've asked szoupi for sending latest package.

**Comment by mahagr** [comment]
I'm also sorry that it took 7 days to fix the issues on your site.

Here's the upgrade guide:
https://github.com/gantry/gantry5/blob/develop/UPGRADE-5.5.md

We are constantly updating it to contain any issues you may run into when upgrading to Gantry 5.5

**Comment by ppetree** [comment]
Just to be clear, this problem still exists in helium 5.5.7 on Joomla 3.10.5 and Gantry 5.5.7.
