### ISSUE TITLE
Incompatible units in scss calculations

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2903]
Hey guys,

The new SCSS compiler seems to be activated by default in Gantry 5.5 for all themes, not only for the themes that require it.

Anyway, if the user uses a value in any unit different than `rem` in the Breakpoints section, they will get an error.
[This screenshot](https://i.imgur.com/XTqc2Ca.png) shows the issue in a clean Helium RocketLauncher installation.

This will need to be fixed in some of the templates that have such calculations. Here's [another issue](https://github.com/gantry/gantry5/issues/2900) for example.
We also have few templates that need to be fixed :smiley: 

Anyway, I will open a new PR that fixes the issue in Gantry (and Helium).

**Comment by mahagr** [comment]
Try first to install the CI build from https://gantry.org/downloads

If that doesn't work, the theme may have overrides for breakpoints. @hexplor is working on updating themes, so he may know if there's more to it.

**Comment by jpolecheck** [comment]
No go.  Recompiled the CSS and got this error message here: 

 

500 Internal Server Error

Oops, CSS Compilation on file 'notio.scss' failed on error: Incompatible units px and rem.: /home/v9nksvbg20o9/public_html/atvmn_2021/templates/rt_notio/scss/notio/sections/_sidebar.scss on line 50, at column 17 Call Stack: #0 mixin breakpoint /home/v9nksvbg20o9/public_html/atvmn_2021/templates/rt_notio/scss/notio/sections/_sidebar.scss on line 57 #1 import /home/v9nksvbg20o9/public_html/atvmn_2021/templates/rt_notio/scss/notio/sections/_sidebar.scss /home/v9nksvbg20o9/public_html/atvmn_2021/templates/rt_notio/scss/notio.scss on line 80 #2 import /home/v9nksvbg20o9/public_html/atvmn_2021/templates/rt_notio/scss/notio.scss (unknown file) on line 1.

**Comment by Avgrafica** [comment]
Same issue with Hydrogen 5.5.7
I tried to modify the _flex.scss file by forcing the calc (# but it didn't work
