### ISSUE TITLE
Gantry 5.5 - Duplicate default outline cause 500 Internal Server Error

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2915]
Hi,
When I want to duplicate an outline it shows me a 500 Internal Server Error, but creates the outline at the end.

These are the steps:
1. Gantry 5 Themes > Default Theme > Outlines > Default outline > Duplicate > "DEMO" title > Confirm
Result: 500 Internal Server Error
"**Oops, Failed to read index.yaml: file_get_contents(): read of 8192 bytes failed with errno=13 Permission denied.**"

![duplicate-outline-error-message](https://user-images.githubusercontent.com/3976174/138071013-17a61cdb-f273-4e31-8470-b41663380988.png)

2. CONFIRM button doesn't work. Then click to CANCEL
3. Turn back to Default Theme > Outlines
The "Hydrogen - DEMO" outline is already created!

**Comment by mahagr** [comment]
Let me try in Joomla 4...

**Comment by marktaylor46** [comment]
I confirm I get the same issu
![2021-10-20_18-47-40](https://user-images.githubusercontent.com/11683218/138290336-ecf1d84e-3e52-43e1-a231-843d8858c568.png)
e
