### ISSUE TITLE
Breakpoint in px not being applied

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2922]
Hi there,
I'm using latest CI build (J4/Hydrogen).  If you use the default unit(rem) from the presets, it works. However, if you change the breakpoint values in px, like: 
![breakpoint](https://user-images.githubusercontent.com/2299347/139088333-5f7a8285-927f-4291-9495-59bbd2e1698a.png)

The breakpoint not being applied via front-end. Screenshot:
![px](https://user-images.githubusercontent.com/2299347/139089223-cd7dde5d-2e0b-44ac-8b66-a07db44059cc.png)

**Comment by mahagr** [comment]
The new logic is converting breakpoints variables to rem before scss compilation. This should fix all issues as long as HTML base font size is 16.

**Comment by tonamphong** [comment]
Tested without problem. Thank you :) 
NOTE: I see that the Recompile css feature not really fast as 5.4.37.

**Comment by mahagr** [comment]
For me recompiling is super fast, but it slows down if the compiler has to revert to the old one (with the above error for example).
