### ISSUE TITLE
Gantry 5.5.3 error page 404 gives error Joomla 3.10.3

### ISSUE THREAD

**Issue by webmasterab** [gantry/gantry5#2924]
Joomla 3.10.3
If I now go to a page that does not exist on a website, I get a white screen with the word error.
No more.

**Comment by webmasterab** [comment]
Now in the changelog at version 5.5.0 I find the following.

Joomla
Updated minimum requirement to Joomla! 3.9 (include themes)
Update theme initialization to work in Joomla! 4.0 (please copy updated includes, fields and html folders to your theme!)
Update theme installation to work in Joomla! 4.0 (please copy or update install.php in your theme!)
Update page templates to work in Joomla! 4.0 (please copy or update component.php, error.php, index.php, offline.php in your theme!)
Implemented per menu ACL in Menu Manager (#1240)
Fixed dropdown menu of Menu Manager listing items by id instead of alphabetical order (#2816)
Fixed Sample Data error during installation (#2790)
Fixed clearing menu cache with the latest Joomla versions

But which file should I copy where after the update via the update system.
Is it not possible to build this into the installation script?

**Comment by webmasterab** [comment]
I transferred the files from the zip via ftp to the folder /templates/g5_hydrogen

The white screen with only it becomes error remains

**Comment by webmasterab** [comment]
After setting the error reporting to maximum I got this message

Error: Call to a member function getLanguage() on null: Pagina niet gevonden

**Comment by mahagr** [comment]
Can you see where that issue happens? This information can be seen by also enabling debug mode in Joomla.

Usually the cause for this is that the method gets called too early, but I cannot really tell as I cannot reproduce the issue locally. The issue may also happen outside of Gantry in a compinent, plugin or module.

**Comment by webmasterab** [comment]
It occurs when I install the update to 5.5.3 and then visit a page that does not exist.
![foutrapportage](https://user-images.githubusercontent.com/8011751/140088351-ac961661-3022-4b3c-85c9-70a0fa8afce1.PNG)
Error: Call to a member function getLanguage() on null: Pagina niet gevonden
![errorpage](https://user-images.githubusercontent.com/8011751/140088675-808c5227-9751-4c46-a811-293fb29ee3bf.PNG)
It doesn't matter if the custom HTML is there or not

**Comment by mahagr** [comment]
I'm getting the error page with the latest Helium theme. Can you enable the debug mode to see the full traceback and send me screenshot of what you see?

**Comment by webmasterab** [comment]
I've had the debug on in Joomla and I don't get more than the message I wrote before here.
I've had this on several websites.

Or is there a debug mode in the template?

**Comment by mahagr** [comment]
Can you contact me directly via gitter chat?

**Comment by mahagr** [comment]
The issue can be reproduced if you go to:

> Content > Articles > Options > Integration

And change the `URL Routing` setting to Modern.

**Comment by webmasterab** [comment]
I have found that in Joomla 3.10.3 the error message comes when you use the updated router.
If you use the old one, you have no problem.

The router is in the options of the article management

**Comment by mahagr** [comment]
Try the latest CI build, it should fix your issue.
