### ISSUE TITLE
Gantry 5.5.3 - custom.scss files not being picked up and compiled at all

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2926]
Custom.scss files are not being picked up and compiled in G5.5.3 at all.

**Comment by mahagr** [comment]
It does work, but not without clearing cache. This is due to changes in SCSS compiler making it impossible to detect added images.

**Comment by marktaylor46** [comment]
Hmm ok that's new - I wasn't aware of that one.

Yes, it now works.

**Comment by marktaylor46** [comment]
I'm wondering though is we can make the "recompile CSS" button clear cache first?

**Comment by mahagr** [comment]
I improved the logic to detect overrides over the existing files.

**Comment by marktaylor46** [comment]
confirmed fix :)

**Comment by asyasali** [comment]
After the update, I am getting the following error:

An exception has been thrown during the rendering of a template ("ERROR: CSS Compilation on file 'custom.scss' failed on error: $amount: Expected 20% to be within 0% and 1%: media/gantry5/engines/nucleus/scss/nucleus/theme/mixins/_typography.scss on line 140, at column 3 Call Stack: #0 import templates/g5_helium/custom/scss/_jlparticles.scss templates/g5_helium/custom/scss/custom.scss on line 2 #1 import templates/g5_helium/custom/scss/custom.scss (unknown file) on line 2").

It is impossible to recompile the CSS even after the cache was cleared.

**Comment by mahagr** [comment]
That's likely because your `custom.scss` has 20% somewhere where SCSS only takes a number between 0..1.

The error seems to be off, though, try looking `templates/g5_helium/custom/scss/_jlparticles.scss` line 140

**Comment by asyasali** [comment]
Thank you @mahagr 

I installed the latest version of jlparticles and managed to finally recompile the css.

**Comment by gaelicwinter** [comment]
I had to change some modified particles from 25% to .25 and that cleared
the issue.
=============================================
