### ISSUE TITLE
Gantry 5.5 - The second instance of a Menu particle is not rendered.

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2927]
Hey Matias,

There is a strange issue with the Menu particle and Gantry 5.5.x
When you try to use two Menu particles in order to simulate a Split menu for example, the second particle is not rendered at all.
The issue is not present in Gantry 5.4.37.

Here, have a look at [this video](https://youtu.be/F8Wg9dyR4mg). It shows everything in detail.

**Comment by marktaylor46** [comment]
Could your try further actions.
1. Go to Gantry 5 menu editor and just save the menu as this moves the data to the database instead of yaml file.
2.  Clear cache on the base outline > EXTRAS button.

**Comment by JoomFX** [comment]
Yep, it is fixed in the CI build :)
Thanks Mark!

![ci](https://user-images.githubusercontent.com/7753940/139695390-068d94bc-6ee8-472d-a8cb-3e642c2ca2a9.png)

**Comment by marktaylor46** [comment]
You're very welcome. :)
