### ISSUE TITLE
Gantry5 and Joomshoping

### ISSUE THREAD

**Issue by Alex-Indilex** [gantry/gantry5#2929]
How to output categories and products from Joomshoping?
I have read that you will need to use Gantry Content Finders to download the information directly from Joomla. You will then be able to display this data on the front end.

{% set options = {published: true, id: [14, 3]} %}
{% set finder = joomla.finder('category', options) %}

How to output categories and products from Joomshoping? 
Not through a module, but through a particle. For example, through a standard particle Joomla Articles  contentarray

**Comment by mahagr** [comment]
In Joomla everything is generally custom and not reusable outside of the component itself. I have not looked into Joomshoping, but you may want to look into their documentation if they provide public apis to access their data. Usually the answer is no, which means that the only way to implement something like this is to copy their code.

**Comment by Alex-Indilex** [comment]
This is where I need to look
https://www.webdesigner-profi.de/joomla-webdesign/example/addon_api_documentation.htm

**Comment by mahagr** [comment]
Above API can be used to fetch the data via AJAX, but it looks like it requires admin access. So I don't think it can be used.

Nevertheless, I don't think this is something that can be done easily as it requires coding skills and time to implement something like this. It's probably better just to use what Joomshoping already provides.
