### ISSUE TITLE
Gantry 5.5.x - "particle" and "module" menu items are being rendered by third-party menu modules

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2932]
Gantry 5.5.x now uses the joomla database to store particle and module placed in the menu (via g5 menu editor) as menu items.

Unfortunately this now means that third-party menu modules/particles are now also trying to render these "particle" and "module" menu items.

Perhaps consideration could be given to using the joomla menu item flag "do not show in menu" for these menu items? But of course G5 menu particle would still need to render particles and modules in the menu.

**Comment by mahagr** [comment]
Fixed in Joomla.

**Comment by mahagr** [comment]
Also fixed in WP.
