### ISSUE TITLE
Joomla 4 - Error page doesn't load jQuery

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2933]
Hi Matias,

This is somehow related to https://github.com/gantry/gantry5/issues/2743.

Here's my scenario so you can get a better understanding of what's happening...
I have an atom that loads jQuery via `{% do gantry.load('jquery') %}`.
On all pages, when I inspect the code, I see that jQuery is loaded from the correct location:

`/media/vendor/jquery/js/jquery.min.js`

But on the Error page it is loaded from the Jooma 3 location, which is wrong:

`/media/jui/js/jquery.min.js`

I thought that the issue comes from [here](https://github.com/gantry/gantry5/blob/3f922844fc37d5017e50764c75573d80ed298eb8/src/platforms/joomla/classes/Gantry/Framework/Document.php#L191), but even after changing the location there, jQuery was still loaded from the wrong (Joomla 3) location.

**Comment by mahagr** [comment]
For Joomla 3 there was some special logic for the error page as it didn't work like other pages. The error isn't coming from there as that code will not be run in Joomla 4 at all.

Maybe there's something else that tries to load jquery? Because I have the opposite issue: jquery isn't being loaded at all.

**Comment by JoomFX** [comment]
You are absolutely right, Matias!
I had loaded jQuery manually in the Assets section in the Error Outline.

And yes, I can confirm the "real issue" - jQuery is not loaded at all on the Error Page.

**Comment by mahagr** [comment]
The same issue seems to be in Joomla 3.10, too. Also it renders `<jdoc:include type="modules" name="debug" />` instead of the debugger.

**Comment by LLudas** [comment]
Hello, the same issue appeared and with newest wordpress version.
Menus, sliders what runs on Jquery or any scripts not working.

**Comment by mahagr** [comment]
@LLudas I just tested the development version and jQuery seems to be working fine in it. Can you try CI build from here: https://gantry.org/downloads#ci-builds

Just make sure you pick  `wordpress-pkg_gantry5_develop.zip`
