### ISSUE TITLE
0 Identifier "errors" is not defined

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2936]
Hey Matias,

Several of our users report this issue which I'm not able to reproduce on my end neither with Helium/Hydrogen templates nor with our commercial templates.
I understand that it is not really possible to troubleshoot an issue that you cannot reproduce but still, do you have any idea what might be causing the issue?

To give you some details - this issue is only related to the Error Page.
For example, when the visitor tries to open a missing page, instead of getting `404 Page not found` they get `0 Identifier "errors" is not defined`.
And the users who report the issue are on Joomla 3 - latest Joomla version and latest Gantry 5 version.

**Comment by mahagr** [comment]
I'm not seeing the error with Helium when going to an error page. The error comes from the Pimple DI container when `error` isn't defined in the DI container. It is only defined if you have development mode on and its purpose is to display the errors, so maybe the issue happens only in the production mode?

It shouldn't be called from anywhere, at least I didn't find any code accessing it.

**Comment by mahagr** [comment]
Actually, I did find it...
