### ISSUE TITLE
Helium template: CSS compile error after upgrading to 3.10.3 

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2941]
Live website: http://www.r.peaceevergospel.tv/

I cloned a working site to this URL and assign someone else as administrator. After a short while, this problem happened.
![image](https://user-images.githubusercontent.com/12814040/141682274-7cf44c48-efd8-4c9d-8d8b-6e68805920df.png)

I compared this site with the original one, the only major difference I could find is that this one has upgraded to Joomla 3.10.3. Could this be the cause of the error?

**Comment by mahagr** [comment]
No, the issue is caused by SCSS code which doesn't meet the standard. We updated to a new compiler that is specs compliant, meaning that the themes need to be updated to use proper SCSS.

**Comment by newjie** [comment]
I've upgraded Helium them to 5.5.4, gantry is also the latest version but the problem persists.

**Comment by plam13** [comment]
I have the same global error !?

I will not update my other gantry5 sites

**Comment by mahagr** [comment]
No update will fix the error; it's your custom SCSS overrides that don't follow the specs. 

The old SCSS compiler in Grav 5.4 was broken and it was replaced with a new version that follows the specs. Read the error and fix the file/line from the error message.

**Comment by newjie** [comment]
For this site I don't have any custom css codes!

The error shows it's some code in Helium template's scss file that caused the error.

I've tried commenting out the lines in questions, but more and more similar errors would pop up.

**Comment by plam13** [comment]
Yes, sorry... I update some old custom particles and that fixed the problem.

**Comment by newjie** [comment]
https://www.loom.com/share/997f4edf65cf42dbbc7b4d5d3374e11b
Please kindly watched this 2 mins video.
