### ISSUE TITLE
Gantry 5.5.5 Wordpress Menus and Plugin Errors

### ISSUE THREAD

**Issue by mtechoh** [gantry/gantry5#2946]
I've hit a couple issues, unrelated. On Wordpress 5.8.2. Everything up-to-date. PHP 7.4.21. WPML 4.4.12. Gantry 5.5.0

1) Updated to Gantry 5.5.5. It killed the menu on all subnav items. ie: All top-level nav items, the menu displayed properly. All menu items below those displayed an error about no such parent. Reverting back to 5.5.0 fixed that.

Any ideas on fixes?

**Comment by mahagr** [comment]
Regarding the first issue, have you tried in which version the menus break?

**Comment by mtechoh** [comment]
The menu breaks in 5.5.5. It worked in 5.5.0, both before updating to 5.5.5, and after restoring to 5.5.0.

**Comment by mahagr** [comment]
What happens if you incrementally upgrade to 5.5.1, 5.5.2, 5.5.3, and 5.5.4?

**Comment by mtechoh** [comment]
5.5.4 is the first time the issue appears. The exact error message is "Undefined variable: parent".

**Comment by mtechoh** [comment]
( And the #2 issue happens in 5.5.0 - 5.5.5. Only changing to a non-Gantry theme fixes it. )

**Comment by mtechoh** [comment]
Found the bug causing #1. 
File: /gantry5/src/classes/Gantry/Framework/Menu.php
Line: 255. In earlier versions you're using $parent. It 5.5.4 you changed it to $item, but missed a spot.

So changing: 
                    if (!$item || isset($this->active[$parent->id])) {
to:
                    if (!$item || isset($this->active[$item->id])) {
fixes it.

Any ideas on #2?

**Comment by mtechoh** [comment]
I found the bug in #2 -- or at least a way around it.

**Comment by mahagr** [comment]
The first issue has been fixed (like you did it).

I'm not sure about the second issue as I am not sure how to reproduce it. From what I can read from the code, though, there's a global variable that seems not to be set.

How did you work it around?

**Comment by mtechoh** [comment]
I commented out this check it the plugin:

if ( is_singular() && strpos( get_the_content(), '<!-- wp:' ) === false ) {
return;
}

After that it worked and I haven't seen other issues because of it...yet. No idea why it made a difference in Gantry, but not in stock twentytwentyone.

**Comment by mahagr** [comment]
Yeah, that will not work as a fix. Can you create a new issue from the second one as I want to close the first issue as being fixed, thanks!

**Comment by mtechoh** [comment]
Done: https://github.com/gantry/gantry5/issues/2955
