### ISSUE TITLE
Gantry 5.5.x - icon pickers shows wrong icons

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2952]
G5.5 introduced the ability to chose fontawesome 4 or 5. However if you have a legacy site and show to leave "fontawesome 4 (legacy)" enabled in the base outline > page settings then font picker only allows you to choose fontawesome 5 icons? You should be able to select the old legacy icons e.g. "fa fa-cog" and not be given the only choice of "fas fas-cog" as when you look on the front end this will not show as only fontawesome 4 has been loaded (correctly).

In my opinion the icon picker should show the old legacy icons too (or at least there should be a dropdown in the icon picker to allow you to choose the icon set shown).

**Comment by mahagr** [comment]
Right now admin always uses FA5 icons. This may be quite a hard thing to fix as it would need a mapping from FA5 -> FA4.

**Comment by marktaylor46** [comment]
This is the issue - we're getting people to select FA5 icons that then do not work if you have fontawesome version set to 4 - most users don't even realise this.

At the very least can we at least put a warning message in the icon picker that says "fontaweseome 4 (legacy) selected in page settings - so your icons may not work - change to fontawesome 5" or something to that effect.

**Comment by mahagr** [comment]
Gantry will now show the proper set of icons in admin.

**Comment by marktaylor46** [comment]
Not fixed. The icons shows in the icon picker on any particle in an outline should reflect the fontaweseom version shown on the page settings of that outline. At the moment it only seems to take account of the page settings for fontawesome in the BASE OUTLINE only.

**Comment by mahagr** [comment]
Second issue moved into https://github.com/gantry/gantry5/issues/2966

Consider this one as closed.
