### ISSUE TITLE
Gantry 5.5.5 - adding meta data to "parent" menu item in joomla deletes Gantry 5 column data

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2954]
If you have a menu item in Joomla menu manager that has several children. Then, you go into Gantry 5 menu editor and add a number of columns to that "parent" menu item and then move the children to those columns - everything is fine.

Now go to the "parent" menu item in Joomla menu manager and just save the menu item. All column data has then been lost in Gantry 5 menu editor for that menu item.

**Comment by mahagr** [comment]
CI builds are available for testing.

**Comment by impressionestudio** [comment]
I think the problem still remains but a little different. 
I move some menu times to the second column and when I save, it shows an empty modal error message.
So I don't know what is the problem.
Then I refresh the page and all the menu items are in the first column.
(I use the version 5.5.6.)

**Comment by mahagr** [comment]
Try to inspect the AJAX requests and see what the response it. Please create a new issue when you do that, thanks!

**Comment by mahagr** [comment]
@impressionestudio Any updates?

**Comment by impressionestudio** [comment]
Sorry for the delay. I created a new issue #2974.
