### ISSUE TITLE
Gantry and Blocks Animation plugin

### ISSUE THREAD

**Issue by mtechoh** [gantry/gantry5#2955]
Installed "Blocks Animation: CSS Animations for Gutenberg Blocks". Loaded it on one page and tried it. Worked as expected -- once. Came back to page later and started getting this error:

_Warning: count(): Parameter must be an array or an object that implements Countable in /wp-includes/post-template.php on line 319
Notice: Trying to access array offset on value of type null in /wp-includes/post-template.php on line 325_

Disabling the plugin removes the error, and switching the theme to stock WP twentytwentyone theme eliminated the error and makes everything work properly. Tried it with fresh Helium theme. Same error and failure, so it's something Gantry is doing.

As a workaround I commented out this check in the plugin:

if ( is_singular() && strpos( get_the_content(), '<!-- wp:' ) === false ) {
return;
}

After that it worked and I haven't seen other issues because of it...yet. No idea why it made a difference in Gantry, but not in stock twentytwentyone.

(Original at https://github.com/gantry/gantry5/issues/2946)

**Comment by mahagr** [comment]
It looks like that the `global $pages` is not defined. A better workaround for you is to set it to an empty array from the theme (if not set).

In which page type(s) does this happen?

**Comment by mtechoh** [comment]
The plugin author said he found the problem and the next release will include the fix. It only happened on pages, not on posts.

**Comment by mahagr** [comment]
Thanks for the update.
