### ISSUE TITLE
J4: menu item module rendering

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#2958]
Hi there,
I have two menu particles and assigned a Module into special menu item (Login).
The Joomla login module display on the first menu particle but no longer shows in the second.

![1](https://user-images.githubusercontent.com/2299347/144243564-fbe94346-460a-4be9-af34-e75a36c15d84.png)

![2](https://user-images.githubusercontent.com/2299347/144243594-e2758b54-4a1f-49c5-84d2-1ed9994bff73.png)

Could you please check ?

**Comment by Tazzios** [comment]
It is not specific for J4 , I also have it with J3.

info
Joomla 3.10.3
Gantry 5.5.5
PHP 7.4.25

Not sure if it is relevant, but I see this error in the console on every page.
DevTools failed to load source map: Could not load content for https://...../media/gantry5/assets/js/main.js.map: HTTP error: status code 404,

**Comment by mahagr** [comment]
I'm pretty sure you can render a single particle only once per page, which was a decision I made for some reason. Anyway, with forms, there's an issue of using the same form name twice on a single page as it's against HTML specs.

In Joomla, I would just create another menu to the bottom of the page with a different instance of login module if you need it there, too.

**Comment by Tazzios** [comment]
I'm rendering different particles.

menu1 main shows from level1 to level 2
menu2 submenu shows level 3

this so that the user can access level 3 easier if they are on the lever 2 page.

**Comment by mahagr** [comment]
Also, make sure you're rendering different modules from Joomla.

**Comment by Tazzios** [comment]
It is another module instance, else it would be exzactly the same. Or i just don`t understand. :)

I created an example here:
http://marijqg132.132.axc.nl/gantry/index.php/agenda

The admin password is not so hard to guess if you want to have a look.
