### ISSUE TITLE
Double menu partent indicators

### ISSUE THREAD

**Issue by Wicko-Design** [gantry/gantry5#2959]
After updating to Gantry 5.5.5 on Wordpress we are now seeing double parent indicators in the menu. 
These appear to be in the Span class and in the ::after clas
![Screenshot 2021-12-02 at 09 14 32](https://user-images.githubusercontent.com/11837048/144392592-048952e2-ba18-4401-96c0-f8c50e272892.png)
This site does use Fontawesome Pro.
This is a [mobile accessories getgofone.co.uk](https://getgofone.co.uk) site.

**Comment by Wicko-Design** [comment]
Ok made some changes to how the FontAwesome js was loaded which fixed the issue. 

Originally I have it in the Customer Content section with the Font Awesome Settings on the page partical page set to disabled. 

By settings this to enabled and deleting the script from the Customer Content and adding it to HTML JS Import then setting Version to Load Manually. Also V4 Compatibility to enabled and Content Compatibility to Enabled.

**Comment by mahagr** [comment]
@Wicko-Design BTW, I'd like to make it easier to use Pro font in Gantry if possible. As I do not own the set, it would be nice if you could help me to make it easier to add + create some documentation about it.

**Comment by Wicko-Design** [comment]
Hi Matias

Yes I would be more than happy to help you. 

I have the font installed on out site and I also have a staging site we can test on if that helps. Also FontAwesome Pro is licenses for several sites. So if you want I can set one of the licensed sites to your testing site while you check out the issue. 

regards

David

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Wicko
6 Craysleaze
Kidmore End
Reading
RG4 9BH
UK

Mob: +44 (0)771 756 756 0
***@***.***
www.wickodesign.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mahagr** [comment]
Maybe ping me in chats?
