### ISSUE TITLE
Joomla 4 - Modules not rendered in Menu

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#2962]
Hey Matias,

This is a tricky one so I'll do my best to explain it :)
The thing is that the issue is reproducible only when the Menu particle is published via the Gantry 5 Particle module in the Module Manager. 
When the Menu particle is added in the Layout directly, everything works as expected.

In short - the Modules that you add via the Menu Editor are not being rendered in the Menu.
Here, have a look at [this video](https://youtu.be/DJuoaWTxwa0) that I recorded for you.

In Joomla 3 the Module is rendered correctly no matter if the Menu particles is added in the Layout or via the Gantry 5 Menu module in the Module Manager.

P.S. This is tested with Gantry 5.5.6

**Comment by Tazzios** [comment]
Seems to be (kind of) the same as described in #2958 .

**Comment by JoomFX** [comment]
Yeah, at first look it looks similar but at the end these are two different issues.
Before I open this issue I read the other issue twice in order to figure out if we are talking about the same problem.

The other issue is reproducible in both J3 and J4 while this issue is related to J4 only.

**Comment by Tazzios** [comment]
I tried the module like you did mine is directly shown (without drop down).

What happens if you add and menu item under 'article' or 'G5 page'? Show or no show?

**Comment by JoomFX** [comment]
@Tazzios The issue I reported is not reproducible in J3. It is only reproducible in J4.
I recorded a short video that shows the issue in detail. If you want have a look at it.
