### ISSUE TITLE
Gantry WP Fatal Error :  Call to undefined method Gantry\Component\Stylesheet\Scss\Compiler::setOutputStyle()

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2964]
Hi there

after the last update of gantry to 5.5.6 I got this error "sometimes" on front end, and if I try to compile scss from backend I get what you'll see in capture below.

Is there any reason this may append ? 

Thank's

`Fatal error: Uncaught Error: Call to undefined method Gantry\Component\Stylesheet\Scss\Compiler::setOutputStyle() in /home/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php:555 Stack trace: #0 /home/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php(170): Gantry\Component\Stylesheet\ScssCompiler->getCompiler() #1 /home/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Theme/ThemeTrait.php(271): Gantry\Component\Stylesheet\ScssCompiler->compileFile('helium') #2 /home/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Content/Block/HtmlBlock.php(86): Gantry\Framework\Theme->css('helium') #3 /home/www/wp in /home/www/wp-content/plugins/gantry5/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php on line 555`

![gantryscssbug](https://user-images.githubusercontent.com/23659411/145372228-f61ae2e4-1046-49d7-834c-bbf2987cee05.PNG)

**Comment by jbonlinea** [comment]
as #2271 it is a conflict between scss compiler.

It's great to have a scss compiler bundled with gantry, but it may be awesome if we could also diactivate it. I've seen this requestet elsewhere on the web while debugging this for myself.

regards

**Comment by mahagr** [comment]
Deactivating the bundled SCSS library won't really work as it would still fail just like this because of the different versions of those libraries are incompatible with each other. We are extending the library which has changed it's internal methods -> you see the above error.

The issue is that even if I worked around the issue and detected the version of the library, SCSS compilation would still fail or cause unexpected issues as the library has evolved so quickly.

**Comment by jbonlinea** [comment]
Hi

Thank you for your reply.

To be honest, I haven't fully understant what you mean, but I know nothing about scss compiling...

My dumb mind would say, if two libraries are incompatible, and we desactivate one of them, and by desactivate I mean unload, then everything is as we had only one library ? no ? so there shouldn't be any incompatibility issue 
(maybe the difference between desactivating and unloading the library is were I haven't fully understood you)


Or do you mean that this crashing is because because the scss code itself crash with one library, but not the other ? (that's not what I assume you meant)


All togather, if scss library are evolving quickly, are prone to incompatiblilities, and are bundled with several "software", the risk of crash is pretty high, broadly speaking, and within gantry realm. 

I don't know but if that is the context I guess that there are still a couple of solutions like : 
- "expose" the scss library bundled with gantry, so we coule eventually use it to compile non-gantry scss ; maybe we just needd the path to the library and execution rights ? 
- be able to define an external library gantry will use to compile its own scss. Maybe it is also also just a matter of path and execution rights ? This would also unload gantry scss compiler as it is not needed anymore and thus eliminate a source of conflict
- be able to unload gantry scss library, full stop. once the theme is stabilised, there shouldn't be any need to maintain it loaded ? 

well that just naive thought, as said above I know nothing about scss compiling, and I may be naive, but I can't think of it as something so critical that it will let us with nothing more than "these two software are incompatible because the two scss library bundled within each of them are incompatible"

I'm not sure if I may help, but let me know if so, and how :)

Regards

**Comment by mahagr** [comment]
I mean that the old version of the SCSS compiler (loaded by another extension) isn't compatible with the new one and Gantry requires v1.6-1.9 to work. Gantry itself loads the library only if it needs to compile SCSS (and not loaded alrady) -- to act nicely with other extensions.

So it's the other extension which doesn't play nicely with Gantry and there's nothing I can do to fix that. Gantry cannot prevent the other extension from loading anything, someone else needs to fix that.

The issue here is that the new SCSS library version has new functions which didn't exist in the old one. Gantry already detects the version of the SCSS compiler and tries to compensate, but those old versions just won't cut it as they are too old.

**Comment by mahagr** [comment]
PHP only allows class to be loaded once. If I try to replace the class with another one, PHP stops with a fatal error.

So no, there's really nothing I can do except maybe show a better error message.

**Comment by mahagr** [comment]
Try to find the plugin that includes the SCSS library and just delete the vendor files for it. That should make the system to work.

**Comment by jbonlinea** [comment]
> Try to find the plugin that includes the SCSS library and just delete the vendor files for it. That should make the system to work.

yes this is done already :)

i'm just trying to see how this would be future proff.

I mean of both uses scssphp. 

your library is more recent than the other.

I'm fine if the orther plug-in can user your library ranther than their "old" one.

I just wonder how can I "force" it to use yours... (same could be in the other way round)

**Comment by mahagr** [comment]
Well, the plugin needs to either update its version or it needs to be fixed not to register autoloader for SCSS unless the plugin needs it.

I have done all of that -- they need to do it, too.

**Comment by jbonlinea** [comment]
yes ! 

thank's for your replies, it really helps understanding what's under the hood and what is the way forward
