### ISSUE TITLE
Gantry 5 Joomla page width weirdly depends on Joomla content type

### ISSUE THREAD

**Issue by DSist** [gantry/gantry5#2965]
Hello,

My own template is based upon the Hydrogen theme. I have stumbled upon a strange page width behaviour in Joomla 3 I couldn't resolve. I have just installed the pure Hydrogen theme v5.5.6 (Gantry 5.5.6) to check it in unbiased conditions and the problem has been confirmed. All that is described below is done with the pure Hydrogen theme. Now the Gantry is 5.5.6, but the problem had occured with Gantry 5, long before Gantry 5.5 was released.

Joomla 3.10.3, Gantry/Hydrogen 5.5.6, PHP 7.4.16.

I have added two Module Positions (left and right sidebars) to Page Content raw in the Main section of the layout, so that the Page Content raw consists of three fixed width blocks: content-left 25%, content 50%, content-right 25%. I use this layout for every page on the site. All I have to do is to assign or not to assign modules to the left and right sidebars, so I have any configuration I need for the particular page on the site.

The problem I have encountered is the volatile width of the site, that depends on the Joomla context of the page. Category blog pages differ in width from Joomla article pages with the Gantry 5 layout. It is not only visual but is confirmed by Google DevTools: 1356.670 page body width for Category blog pages and 1339.170 page body width for Joomla article.

Here are body classes for both pages:

Category blog
< body class="gantry site com_content view-category layout-blog no-task dir-ltr itemid-163 outline-11 g-offcanvas-left g-default g-style-" >

Joomla article
< body class="gantry site com_content view-article layout-blog no-task dir-ltr itemid-163 outline-11 g-offcanvas-left g-default g-style-" >

I am not sure which width value is correct of course, as well as I am not sure whether the problem depends on Joomla content type strictly. Anyway it is weird that page body width differs from page to page, causing all the outer elemenets: the logo, the main menu, the breadcrumbs etc visually move left and right changing their positions every time user jumps from one page to another.

I have not yet checked it with Joomla 4.

Could someone please advise me regarding the problem?

![gantry5_page_width_1](https://user-images.githubusercontent.com/95962014/145674283-9d94907c-04ff-4a3d-a1ae-39e57b0983b2.png)
![gantry5_page_width_2](https://user-images.githubusercontent.com/95962014/145674287-4122609e-47b6-4463-a5c5-a6de8f26291d.png)
![gantry5_page_width_3](https://user-images.githubusercontent.com/95962014/145674288-e4019791-f525-4fbe-9965-c52e920faa06.png)

**Comment by DSist** [comment]
I am not sure which width value is correct of course, as well as I am not sure whether the problem depends on Joomla material type. Anyway it is weird that page body width differs from page to page, causing all the outer elemenets: the logo, the main menu, the breadcrumbs etc visually move left and right changing their position every time user jumps from one page to another.

**Comment by marktaylor46** [comment]
If nothing is published to a position then it will collapse and the other positions in the same section will be allocated the space that it would have occupied in the same ratio that they are allocated space. 

If you want the module position to occupy the same percentage space (regardless of anything being published or not to that position) then you need to tick the "fixed size" checkbox on the "block" tab of the particle settings.

Of course, in mobile viewport these positions will still collapse to 100% width each.

**Comment by DSist** [comment]
Sorry, but the problem is with the whole page width, it is not about percentage space. It is about different width calculations for different Joomla pages with the same layout and with the both sidebars collapsed, for example. The Gantry engine calculates wrong site width for different pages with the same layout, and somehow it is connected to Joomla content type.

I have just checked it. I assigned the original Hydrogen base page with no sidebars to all the menu items on the site and the same different width problem has occured. So it is not about sidebars at all!

**Comment by marktaylor46** [comment]
Ok, well it's hard to see what is going on with your screenshots other than to say the panel in your developer is a different with (scroll bar vs non-scrollbar on left pane) and that accounts for the difference in the width of the body). 

If you can provide links to those pages I can take a look.

**Comment by DSist** [comment]
Argh!.. Thank you, Mark! You are correct about the width, it is wrong parameter I supposed to be the reason. And you have finally found the reason - it is a scrollbar. So... is it normal that the left side of the content moves left-right depending on the scrollbar? Is the only way to use screen width header and menu? I have many small glossary articles that will never have a scrollbar so it is very weird that the left side of the site visually jerks while the user jumps from page to page/

**Comment by marktaylor46** [comment]
The scrollbar only appears if the content is longer than the viewport area height. Obviously if you alter the width of the viewport then that is going to alter the height of the content (e.g. text will wrap to next line). If you have two monitors then that's the bes t way of using a developer tool (one screen for the actual site and the second for the developer tool itself). Or, of course, instead of making the developers tool on the right make it appear at the bottom instead. and you can also the split position between the content and the developer tool too.

You're using a responsive template so that's why content flows as it does.

**Comment by DSist** [comment]
Thank you very much! I have almost become mad about it, having not noticed it was a scrollbar causing this...
