### ISSUE TITLE
G5.5.x - Icon picker needs an info message

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2966]
With the introduction of the possibility to use Fontawesome 5 in G5.5.x we now need to an info box in the icon picker that states the following:
"The icons shown reflect the Fontawesome version selected on the base outline > page settings. The fontawesome version required should only be set in the base outline > page settings - this setting should not be overriden on a per outline basis."

For the base outline > page settings > fontawesome another note should be shown:
"The fontawesome version required should only be set in the base outline > page settings - this setting should not be overriden on a per outline basis."

**Comment by mahagr** [comment]
Note, the Page settings warning doesn't show up in the base outline.
