### ISSUE TITLE
G5.5.x - cannot remove Fontawesome version override 

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2969]
If you have an override for the fontawesome version in page settings of a non base outline then you cannot remove the override tick. It apparently works when you save the page but if you move off the page and return the override for the fontawesome version have been reinstated (i.e. the fontawesome version dropdown select box).

**Comment by mahagr** [comment]
Saving works -- it removes the override from the configuration. I'm now investigating why the option is ticked even if it's clearly not.

**Comment by marktaylor46** [comment]
Yaay! Confirmed fix 😃
