### ISSUE TITLE
G5.5.7 - Parent dropdown indicator font icons missing

### ISSUE THREAD

**Issue by binaryglyph** [gantry/gantry5#2971]
Parent dropdown indicator font icons not loading in main menu and off-canvas menu Helium theme.
<img width="423" alt="Screen Shot 2021-12-15 at 11 04 09 PM" src="https://user-images.githubusercontent.com/11894987/146602227-a77692e3-67ec-4fd3-a6fd-3e4ba8ebfe6b.png">
<img width="282" alt="Screen Shot 2021-12-15 at 11 04 29 PM" src="https://user-images.githubusercontent.com/11894987/146602233-c34d861e-7424-4b14-be80-233003bbc200.png">

**Comment by mahagr** [comment]
Which CMS you're on?

Also try to play with FA4/5 settings: go to base outline and Page Settings.

**Comment by binaryglyph** [comment]
Joomla 4.0.5

I have played with the FA4/5 settings in base outline. Every combination. I even loaded the full fontawesome pro natively. Then I removed everything and just used FA4. Then FA5 with F4 compatibility. Now I have all FA shut off in the base outline and am using the FA 5 Pro CDN. The parent menu dropdown icons still do not load.

For the time-being, I have had to use css to hide them completely.

**Comment by mahagr** [comment]
Those work for me -- have you upgraded the Helium theme, too? As there was a fix for this if I recall it correctly (and the icons show up just fine for me).

**Comment by binaryglyph** [comment]
I am on v5.5.7, but maybe I should just manually reinstall helium.

**Comment by binaryglyph** [comment]
I tracked down the issue. When the site css is optimized and minified for Google PageSpeed, the font breaks.

**Comment by mahagr** [comment]
@binaryglyph Yeah, minifying tends to sometimes break both JS and CSS. Those tools do not intepret the code and sometimes make wrong decisions and break things.

I'm closing the issue.
