### ISSUE TITLE
Wordpress theme update error v5.5.7

### ISSUE THREAD

**Issue by puhapuru** [gantry/gantry5#2973]
hi, im using worpress 5.8.2 and helium theme ver.5.4.37, but when I tried to upgrade helium 5.5.7 by uploading zip file, wordpress gives critical error. gantry5 plugin is 5.5.7 and works fine. how can I upgrade theme without error?

**Comment by mahagr** [comment]
What is the error? Also make sure you're installing WP package from the theme.
