### ISSUE TITLE
Touch and wheel event listeners

### ISSUE THREAD

**Issue by southwestfilm** [gantry/gantry5#2977]
Google Pagespeed is showing a warning for my website - [South West Film](https://www.southwestfilm.co.uk/)

Does not use passive listeners to improve scrolling performance
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.

Could you advise how to fix this issue?

**Comment by hexplor** [comment]
Hello,
This is related to YouTube embedded player (base.js). It does not have anything to do with gantry itself. I think you should wait for YouTube to update their code. 
Cheers,

**Comment by southwestfilm** [comment]
Thanks, I'll try updating the youtube embed code to see if that fixes it.
