### ISSUE TITLE
full width position

### ISSUE THREAD

**Issue by cvcg** [gantry/gantry5#298]
hi there im trying g5 and i want a full width position.
the full width variation from propertyes dosent work.
please help.....
thanks

**Comment by mahagr** [comment]
As positions can be set full width in Layout Manager, I wonder if you mean making the underlying section to be either filling the whole width of the browser vs it being fixed to boxed size in the themes CSS?

There was discussion in Gitter chat if we should make fullwidth / boxed toggle on sections to allow people to choose in which mode sections are in.

This is against our previous decision to use hard coded container to force sections to fit the design of the template, so @kevlardev might be the best person to reply on this one.

**Comment by kevlardev** [comment]
Yes, we have been discussing how best to implement a way to allow for setting full width and fixed containers on a section by section basis (full width being full width of the browser window). There have been several issues regarding a system like this, such as #240 and its definitely something we want to try to implement in some fashion via the UI.
