### ISSUE TITLE
Logo particle 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#299]
Text field from logo particle will be place in link ```<a href..... title = "text filed goes here " ... . ```Should not it be in a `<p>` ?

**Comment by mahagr** [comment]
I'm not sure what you mean. The text of the logo isn't shown unless you either hover on top of it or use text reader.

**Comment by adi8i** [comment]
Oh, i thought the text should be placed under the logo.

**Comment by mahagr** [comment]
We could have feature for that; also might improve the text..
