### ISSUE TITLE
Gantry 5.5.9 is incompatible with Joomla 4.1. RC1 ?

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#2991]
I have a test site with Joomla 4.1 RC1 and Gantry 5.5.8.
On backend I see that is available an update for Gantry 5.5.9
But when I click on "Update" I receive the message "Invalid extension update".
![gantry-update-invalid](https://user-images.githubusercontent.com/3976174/151198431-c7be8d59-c512-4d76-9b55-ba9d1480fe62.png)

**Comment by mahagr** [comment]
We just need to test it and allow installation in the latest release.

**Comment by mariantanase** [comment]
Tomorrow will be released a stable Joomla 4.1.
Are there any developments so that Gantry can be compatible ? Or we have to wait for Gantry 5.5.10 ? 
Currently 5.5.9 cannot be installed.

**Comment by marktaylor46** [comment]
Did you install the CI build of Gantry 5.5 that adds the support?

**Comment by mariantanase** [comment]
> Did you install the CI build of Gantry 5.5 that adds the support?

No

**Comment by mahagr** [comment]
I'll release an update today.

**Comment by mariantanase** [comment]
> Well, there you go then, so use the CI build and it should be ok - let us know if you have any issue then.

The problem is different.
Over existing Gantry 5.5.8 installation, I can update the existing version by using "**Upload & Install Joomla Extension**" to upload the 5.5.9 stable version. All fine! No CI build needed.
On the first post I mention that the "Update" button doesn't work.

**Comment by marktaylor46** [comment]
I can confirm same issue when on G5.5.7 with J4.1 installed "Invalid Extension Update". @mahagr is woeking on fix now.
