### ISSUE TITLE
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.1.3". You are running 7.0.33. in /home/parislux/www/com/libraries/gantry5/vendor/composer/platform_check.php on line 24

### ISSUE THREAD

**Issue by Irene007007** [gantry/gantry5#2998]
Hi I'm new and I tried to instal Gantry 5 (I had Gantry 4 on my website) on my website and I have now this message : 
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.1.3". You are running 7.0.33. in /home/parislux/www/com/libraries/gantry5/vendor/composer/platform_check.php on line 24

I can't anymore go to my admin. Also I can't go for a latest PHP version because otherwise my website will go offline. 

Is there anybody who can help me ? Thank you.

**Comment by mahagr** [comment]
This is actually a bug.

**Comment by mahagr** [comment]
@Irene007007 There's a new CI build here: https://gantry.org/downloads#ci-builds (Make sure you select Joomla package!) which fixes the issue.

PS. You should really find out a way to update to PHP 7.3/7.4 as most of the code should be running just fine in them. Gantry will stop supporting PHP < 7.2 in the next minor version.

**Comment by mahagr** [comment]
It looks like it takes some time for CI builds to update. Make sure you check that the date of the build is today and not a week ago.
