### ISSUE TITLE
Bug: Menu -> add module/particle -> apply and save = 404 Not Found

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#300]
Clean install, local host w7 XAMPP Version: 5.6.3, I try this but still the same: ThreadStackSize on Windows

going to:
Extensions - template manager - Hydrogen - menu - drag and drop a Module o Particle - chose somthing - "apply and save"
Go back to: Theme Hydrogen
"404 Not Found
Oops, Page Not Found."

This only happens when u push apply and save, works perfect if u use "apply" - "save menu".

Congrats, still working guys, this is going to perfection ;)

**Comment by w00fz** [comment]
Thanks, I believe this might be related to #283

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment]
This is not related to ThreadStackSize issue, so I agree with @w00fz on this. It looks like the another issue you fixed.

**Comment by mahagr** [comment]
Didn't mean to close the issue, though..
