### ISSUE TITLE
G5.5.x - sourcemaps missing

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#3005]
Gantry 5.5.x packages when installed report sourcemaps missing as 404 in console
![2022-02-15_12-25-56](https://user-images.githubusercontent.com/11683218/154061897-f3f11cbf-4ba6-468a-9fbe-ac89b67d3f18.jpg)
e

**Comment by mahagr** [comment]
Fixed in commit cd8d88ca7ac3c84675e4f19ca3ff40f40a97637f
