### ISSUE TITLE
After updating to 5.5.10, I can't access the site and the control panel

### ISSUE THREAD

**Issue by universewrld** [gantry/gantry5#3006]
After updating to 5.5.10, I can't access the site and the control panel.

I see the login form in the control panel. After logging in, I see a white screen.

on the frontend, I just see a white screen.

**Comment by universewrld** [comment]
@mahagr help me how can i fix this?

**Comment by universewrld** [comment]
solution: go to  https:// your site .com/administrator/index.php?option=com_installer&view=update

and update.

I had the `update page` displayed, but the main page of the `control panel` was not displayed.

**Comment by mahagr** [comment]
The release was broken due to an issue in the build script; you can likely get it to work by visiting `/administrator/index.php?option=com_installer`,checking the updates and installing the working package.
