### ISSUE TITLE
Bootstrap5 CSS is not loaded

### ISSUE THREAD

**Issue by gioras** [gantry/gantry5#3007]
Bootstrap5 CSS is not loaded in RTL (or Hebrew)  

English
https://www.awesomescreenshot.com/image/22279138?key=7172665290783f414152cfa0a444dba4
Hebrew
https://www.awesomescreenshot.com/image/22279231?key=0a0718ae2bd377e86702aabe5fbc9e11

dev site:
https://bit.ly/3sH4C1s

Thanks
Giora

**Comment by mahagr** [comment]
You should first disable CSS/JS minifier as it prevents me from seeing what's going on. Also, you may want to check if the same happens in Helium template as you're using a custom one unknown to me.

**Comment by gioras** [comment]
Changed to Helium .  is there a CSS/JS minifier now?
Problem still there.

**Comment by mahagr** [comment]
Can you also disable the plugin that compresses the css/js into a single file?

**Comment by gioras** [comment]
It was easyblog that compressed the css/js . It is now disabled.

**Comment by mahagr** [comment]
Compression is still turned on.

```
<link href="[/j4/A.media,,_gantry5,,_engines,,_nucleus,,_css-compiled,,_nucleus.css+templates,,_g5_helium,,_custom,,_css-compiled,,_helium_26.css,,q621f2634+media,,_gantry5,,_assets,,_css,,_font-awesome.min.css+templates,,_g5_helium,,_custom,,_css-compiled,,_helium-joomla_26.css,,q621f2634+templates,,_g5_helium,,_custom,,_css-compiled,,_custom_26.css,,q621f2634,Mcc.QWbeMZodcg.css.pagespeed.cf.NShuksgbha.css](view-source:https://livesites.co.il/j4/A.media,,_gantry5,,_engines,,_nucleus,,_css-compiled,,_nucleus.css+templates,,_g5_helium,,_custom,,_css-compiled,,_helium_26.css,,q621f2634+media,,_gantry5,,_assets,,_css,,_font-awesome.min.css+templates,,_g5_helium,,_custom,,_css-compiled,,_helium-joomla_26.css,,q621f2634+templates,,_g5_helium,,_custom,,_css-compiled,,_custom_26.css,,q621f2634,Mcc.QWbeMZodcg.css.pagespeed.cf.NShuksgbha.css)" rel="[stylesheet]()"/>
```

**Comment by gioras** [comment]
I could not find any other compiler, but I have created a front-end cash cleaner:
( https://bit.ly/35IcjMW)
will that help?

**Comment by mahagr** [comment]
Yes, now I can see the individual files.

**Comment by mahagr** [comment]
I think I found the issue.

**Comment by mahagr** [comment]
@gioras 

This one should be fixed now in CI builds: https://gantry.org/downloads#ci-builds

PS. I have installed it and it seems to work!

**Comment by gioras** [comment]
Amazing. Thank you so much Matias I really appreciate your help
Best Regards,

--Giora

**Comment by mahagr** [comment]
No worries, it was a bug afterall!
