### ISSUE TITLE
Gantry Crash website with PHP 8

### ISSUE THREAD

**Issue by SkylarAstarot** [gantry/gantry5#3008]
Hello, I have a website in Joomla and I have problems with Gantry when updating PHP, I have 3 versions and I have to change to see which one works.
Joomla 3.1.10
Gantry 5.1.11

### PHP Versions

**7.3.33**
Website working perfectly

**7.4 - Crash**
Twig\Error\RuntimeError thrown with message "An exception has been thrown during the rendering of a template ("fwrite(): write of 173 bytes failed with errno=9 Bad file descriptor")."

Stacktrace:
#62 Twig\Error\RuntimeError in E:\website\astarot\media\gantry5\engines\nucleus\templates\page.html.twig:73
#61 Whoops\Exception\ErrorException in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2449
#60 fwrite in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2449
#59 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1654
#58 Leafo\ScssPhp\Compiler:compileChildren in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2212
#57 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1654
#56 Leafo\ScssPhp\Compiler:compileChildren in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:4286
#55 Leafo\ScssPhp\Compiler:callScssFunction in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2751
#54 Leafo\ScssPhp\Compiler:fncall in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2728
#53 Leafo\ScssPhp\Compiler:reduce in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2127
#52 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1690
#51 Leafo\ScssPhp\Compiler:compileChildrenNoReturn in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\Scss\LegacyCompiler.php:432
#50 Gantry\Component\Stylesheet\Scss\LegacyCompiler:importFile in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2009
#49 Leafo\ScssPhp\Compiler:compileImport in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2080
#48 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1690
#47 Leafo\ScssPhp\Compiler:compileChildrenNoReturn in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\Scss\LegacyCompiler.php:432
#46 Gantry\Component\Stylesheet\Scss\LegacyCompiler:importFile in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2009
#45 Leafo\ScssPhp\Compiler:compileImport in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2080
#44 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1690
#43 Leafo\ScssPhp\Compiler:compileChildrenNoReturn in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\Scss\LegacyCompiler.php:432
#42 Gantry\Component\Stylesheet\Scss\LegacyCompiler:importFile in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2009
#41 Leafo\ScssPhp\Compiler:compileImport in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2080
#40 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1690
#39 Leafo\ScssPhp\Compiler:compileChildrenNoReturn in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\Scss\LegacyCompiler.php:432
#38 Gantry\Component\Stylesheet\Scss\LegacyCompiler:importFile in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2009
#37 Leafo\ScssPhp\Compiler:compileImport in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:2080
#36 Leafo\ScssPhp\Compiler:compileChild in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:1690
#35 Leafo\ScssPhp\Compiler:compileChildrenNoReturn in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:399
#34 Leafo\ScssPhp\Compiler:compileRoot in E:\website\astarot\libraries\gantry5\src\classes\Leafo\ScssPhp\Compiler.php:253
#33 Leafo\ScssPhp\Compiler:compile in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\ScssCompiler.php:310
#32 Gantry\Component\Stylesheet\ScssCompiler:compileLegacyFile in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Stylesheet\ScssCompiler.php:189
#31 Gantry\Component\Stylesheet\ScssCompiler:compileFile in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:271
#30 Gantry\Framework\Theme:css in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Content\Block\HtmlBlock.php:86
#29 Gantry\Component\Content\Block\HtmlBlock:getStyles in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Framework\Document.php:131
#28 Gantry\Framework\Document:registerStyles in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Framework\Document.php:76
#27 Gantry\Framework\Document:registerAssets in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Framework\Base\Platform.php:277
#26 Gantry\Framework\Base\Platform:finalize in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:700
#25 Twig\Template:getAttribute in E:\website\astarot\cache\gantry5\rt_koleti\twig\8a\8a317bbca1fcef45bc1adf46fe9ab1cdff5d161682a74bb0bf95ba67eaf2c481.php:256
#24 __TwigTemplate_4daef23be9bb545f8a8398cc12368f1dacafee0527f54902b8c74d42dcc0498e:block_page_footer in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:214
#23 Twig\Template:displayBlock in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:175
#22 Twig\Template:displayParentBlock in E:\website\astarot\cache\gantry5\rt_koleti\twig\6e\6ea5ea8e688385e316d925eeed843140d71e4a7b1dddf0ed87a66e8ca635efa9.php:43
#21 __TwigTemplate_22cf26c7fded63a472d48eb69c2096f2c4eb4093480af8f3ec554a9cda54a567:block_page_footer in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:214
#20 Twig\Template:displayBlock in E:\website\astarot\cache\gantry5\rt_koleti\twig\8a\8a317bbca1fcef45bc1adf46fe9ab1cdff5d161682a74bb0bf95ba67eaf2c481.php:150
#19 __TwigTemplate_4daef23be9bb545f8a8398cc12368f1dacafee0527f54902b8c74d42dcc0498e:doDisplay in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:453
#18 Twig\Template:displayWithErrorHandling in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:420
#17 Twig\Template:display in E:\website\astarot\cache\gantry5\rt_koleti\twig\6e\6ea5ea8e688385e316d925eeed843140d71e4a7b1dddf0ed87a66e8ca635efa9.php:35
#16 __TwigTemplate_22cf26c7fded63a472d48eb69c2096f2c4eb4093480af8f3ec554a9cda54a567:doDisplay in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:453
#15 Twig\Template:displayWithErrorHandling in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:420
#14 Twig\Template:display in E:\website\astarot\cache\gantry5\rt_koleti\twig\86\86c2d596e6f301f839a7f0237c219e790cc1217d2e8b35a2a76657b5e82ba83b.php:35
#13 __TwigTemplate_c6b39b2cb7679b9f7f41c7a37028ef7852cd28ca377f1a9aeb9d394cee025dcd:doDisplay in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:453
#12 Twig\Template:displayWithErrorHandling in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:420
#11 Twig\Template:display in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Template.php:432
#10 Twig\Template:render in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\TemplateWrapper.php:47
#9 Twig\TemplateWrapper:render in E:\website\astarot\libraries\gantry5\compat\vendor\twig\twig\src\Environment.php:384
#8 Twig\Environment:render in E:\website\astarot\libraries\gantry5\src\classes\Gantry\Component\Theme\AbstractTheme.php:176
#7 Gantry\Component\Theme\AbstractTheme:render in E:\website\astarot\templates\rt_koleti\index.php:23
#6 require in E:\website\astarot\libraries\src\Document\HtmlDocument.php:678
#5 Joomla\CMS\Document\HtmlDocument:_loadTemplate in E:\website\astarot\libraries\src\Document\HtmlDocument.php:740
#4 Joomla\CMS\Document\HtmlDocument:_fetchTemplate in E:\website\astarot\libraries\src\Document\HtmlDocument.php:555
#3 Joomla\CMS\Document\HtmlDocument:parse in E:\website\astarot\libraries\src\Application\CMSApplication.php:1126
#2 Joomla\CMS\Application\CMSApplication:render in E:\website\astarot\libraries\src\Application\SiteApplication.php:778
#1 Joomla\CMS\Application\SiteApplication:render in E:\website\astarot\libraries\src\Application\CMSApplication.php:231
#0 Joomla\CMS\Application\CMSApplication:execute in E:\website\astarot\index.php:49

**8.1.2 - Error 500**

**Comment by mahagr** [comment]
It looks like there's a badly written SCSS file (invalid syntax) in your site and Gantry tries to fall back to the old compiler, which then fails on writing the file.

Do you have the latest version of the theme?

**Comment by SkylarAstarot** [comment]
Yes, I have modified some parameters of the theme but I don't remember, it is an old template Rockettheme Koleti v1.1.7, I uploaded the original template again, not the edited template, and it works. I won't touch it again. :)
Thank you and greeting.
