### ISSUE TITLE
SVG code for the logo instead of ICO

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#3014]
I used the classic ico format in the past. Now I converted the ico file to svg but I don't know how to insert it (the svg file) into the logo particle. There is a field to insert only the svg code, not the file. 
What is the best solution and format to use for site icons ?

**Comment by pmoreno-rodriguez** [comment]
Open your svg file with a text editor and copy all the code, then paste it in the field corresponding to the particle logo svg code

**Comment by mariantanase** [comment]
Thanks!
