### ISSUE TITLE
Different behaviour of the ERROR template from J3 to J4 - UPDATED

### ISSUE THREAD

**Issue by morphinestyle** [gantry/gantry5#3017]
On every website websites i'm using Gantry, after turning to J4 the SYSTEM OUTLINES - ERROR page no more working as well.
Something is changed or it's a bug?

**Comment by morphinestyle** [comment]
UPDATE: different Gantry/Joomla behavior between J3 and J4

To reproduce different behaviour of the ERROR template:
J3 current behavior: www.mywebsite.com/%$£-wrong-or-inexistent-url => (recognize 404 error) it load the ERROR System Outline template
J4 new behavior:     www.mywebsite.com/%$£-wrong-or-inexistent-url => (doesn't recognize 404 error) it loads up to the "last slash" of THE VALID URL, in this case it loads homepage

i found a way to recognize a 404 error and load the ERROR page/template: i.e. is using a BLOG category:
www.mywebsite.com/blog/wrong-or-inexistent-url => Gantry recognize a 404 error and load finally the ERROR template page

Tested on Joomla 4.1 on both Apache+Nginx and OpenLitespeed.

**Comment by morphinestyle** [comment]
Seems to be a new J4 router related issue, also Cassiopeia has different behaviour.

**Comment by mahagr** [comment]
Yes, there's already an issue with this at https://github.com/gantry/gantry5/issues/2938

There's a change in the Joomla router on which layout to use and I think the new way is wrong.
