### ISSUE TITLE
Adding particle into menu and clicking "Apply & Save"

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#302]
When you add the 'logo' particle in the menu (multi-lingual setup) and click `Apply & Save` you get a `404 not found` error.

If you click `Apply` in the particle modal and then click `Save Menu` the particle addition is saved properly.

**Comment by mahagr** [comment]
I think we fixed something similar already, but lets wait reply from @w00fz if this is still an issue.

**Comment by w00fz** [comment]
Duplicate of #300 (related to #283)
