### ISSUE TITLE
Gantry error on update from 5.5.11 to 5.5.12

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#3020]
I tried to update the gantry component via automatic update. Th esite is broken and I got the following error (although it seems that it was installed but with errors).

![gantry-package-error](https://user-images.githubusercontent.com/3976174/160809756-e35e5bdf-bceb-45bd-b93b-bb00c664047c.png)

And then I tried to update the template Hydrogen to 5.5.12 as well but I still get more errors.
![hydrogen-error](https://user-images.githubusercontent.com/3976174/160810008-aabbd617-6157-4aa8-a839-da9d4e01ce7d.png)

Joomla 4.1.0
PHP 7.4.27

**Comment by mariantanase** [comment]
I solved it by **manually installing** both the component and the template.

**Comment by mahagr** [comment]
Nothing has changed on this, maybe some file was being written or read when you performed the update..?

**Comment by mariantanase** [comment]
I notice that on this site, where I receive th error, the System Cache is set to "**ON - Progressive Caching**".
On another test copy, where System Cache is **OFF**, the automatic update worked correctly.
This seems to be the only difference.

**Comment by mahagr** [comment]
Are you in Windows?

**Comment by mariantanase** [comment]
> Do you have server in Windows?

No, the live site is on Linux.
On the local machine (with Windows), where System Cache is OFF, the automatic update worked correctly.

**Comment by mahagr** [comment]
Is there a way to reliably reproduce the issue? Did people use the site while Gantry was being installed?

**Comment by mahagr** [comment]
@mariantanase Did you have the issue on the latest update?
