### ISSUE TITLE
no way to put specific grav page content into gantry particle blocks 

### ISSUE THREAD

**Issue by yehudaclinton** [gantry/gantry5#3021]
For example, I want to put have a 2nd column on the home page containing the contents of a subpage, or of any separate page that could be edited separately. So I try dragging different particles next to the page-content block. It just results in the page content doubled. I understand that I could use other particles to input custom HTML, but I want to use the regular markdown editor.
[this](https://libraries.io/github/hibbitts-design/grav-gantry-particle-inject-page) doesn't work anymore, or at least I don't know how

**Comment by mahagr** [comment]
I have pinged the author of the particle.

**Comment by paulhibbitts** [comment]
Indeed that repository is Archived and I have not looked at Gantry for about 5 years, so I do not have much to suggest @yehudaclinton .

**Comment by yehudaclinton** [comment]
Particle Positions should be the answer, but I am having no luck so far.
https://docs.gantry.org/gantry5/particles/position

**Comment by mahagr** [comment]
You need to add a position to the site. After that go to the positions and add a particle to it, assigned to all pages. See that it works. Then go and assign it to the page you want it in.

**Comment by yehudaclinton** [comment]
fseesink on gitter showed me how to do it.
1. Create a Grav page /license. Enter content "This is license content to add". In Options tab, set 'Category' to 'licenseinfo'. Save page.
2. Create another Grav page /test. Enter "This is main test page". Save page.
3. Create a Gantry 5 outline.
  3.1 Under Gantry 5 in Admin, click Outlines near top right.
  3.2 Click [+] in upper left.
  3.3. Set title to 'Test' and click [Confirm].
  3.4 Click [Back to Setup]
  3.5 Select 'Test' outline from drop-down in upper left.
  3.6 Modify outline by clicking gear on, say, 'Header', click lock symbol to unlock settings, click 'Inheritance' tab, set 'Outline' to 'No Inheritance', and click [Apply and Save]. Now drag [Grav Content] particle into Header and click gear on particle. Set 'Categories' to "licenseinfo" and click [Apply and Save]. Click [Save Layout].
4. Click 'Assignments'. With 'Test' outline set in drop-down list, under 'Pages' on left find 'test' Grav page and click switch green to assign 'Test' outline to 'test' page. Click [Save Assignments].
5. Load test page by visiting yoursiteFQDN/test in your browser. You should see the /license page content showing up.
