### ISSUE TITLE
contentarray particle should support mutli-lingual pagination

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#3023]
The "PREV" and "NEXT" pagination buttons are hardcoded literals in the contentarray.html.twig file. They should use language constants instead so that the particle can be used in a multi-lingual site.

![Snag_5a4c84](https://user-images.githubusercontent.com/11683218/162149854-34236961-2922-43e9-83ac-0fc6b3c62792.png)

**Comment by mahagr** [comment]
Agreed.

**Comment by mahagr** [comment]
@marktaylor46 Should be fixed in all 3 platforms. Can you test tho?

**Comment by marktaylor46** [comment]
1. Joomla works fine - just did the update and everything works as it should
2. Wordpress is NOT FINE - after doing the update you just get the language constants shown instead of "PREV" and "NEXT"
3. works fine - just did the update and everything works as it should.

Regards, Mark.

**Comment by mahagr** [comment]
Umgh, ok, so I wasn't able to properly compile the language files then. Will try again.

**Comment by mahagr** [comment]
Should be fixed now.
