### ISSUE TITLE
Fatal error: Attempt to assign property "group" on null

### ISSUE THREAD

**Issue by anibalsanchez** [gantry/gantry5#3025]
File: libraries/gantry5/src/classes/Gantry/Component/Menu/Item.php
Line: 452

Error: Attempt to assign property "group" on null

On PHP 8 and Joomla 3.10.8

**Comment by mahagr** [comment]
Can you try if the new CI build fixes the issue or if there are further side effects?

Do you have menu items with protected access? I'm trying to understand when the bug happens...

**Comment by anibalsanchez** [comment]
Hi,

The error is found in the latest **joomla-pkg_gantry5_v5.5.12.zip.**.

The site had been working fine with gantry v5.5.7.

About the menu structure, yes, it has menu items with protected access.

**Comment by davidascherG** [comment]
I'm seeing "Warning: Creating default object from empty value in ... libraries/gantry5/src/classes/Gantry/Component/Menu/Item.php on line 452"
with 
Joomla 3.10.3
PHP Version 7.4.28
gantry 5.5.12
Xenon Template (Standalone) 1.5.0

This started to appear when I updated to gantry 5.5.12

**Comment by davidascherG** [comment]
Changing line 452
From: 
                                $item->group = $i;
To:
                        if ($item) {
                                $item->group = $i;
                        }
Fixes the problem.

**Comment by mahagr** [comment]
It has already been fixed like that. Release should be out later today.
