### ISSUE TITLE
Persistence of Particle Settings

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#303]
When setting the default particle configuration through `Components > Gantry 5 > Available Themes > Hydrogen > Configure > Settings > Logo` I expected that the `Logo` setting would be persistent such that when I add the logo particle in a menu or elsewhere, the parameters defined in the `Settings` would be automatically populated in the particle modal.

It appears that is not how it functions. Is that intentional? Or is this a feature that is still under development?

If it is intentional, it is misleading. It would be nice to define "global" settings that are persistent down the line.

**Comment by mahagr** [comment]
They are persistent. If they aren't shown up, there may be bug on showing the defaults, though.

* Base Outline defines global settings that are used everywhere else if not overridden
* Xxx Outline defines defaults for any particle used inside the current layout
* Particle in layout manager allows you to override these defaults

**Comment by alisamii** [comment]
Is Gantry 5 built using Symfony2 or Laravel?
Is there a way to turn on a debugger or debug bar?

**Comment by mahagr** [comment]
We do not use either, but we do use composer and have some symfony components there.

Right now we do not have debug bar, but I'm thinking of adding one if I just find time to do it.

**Comment by alisamii** [comment]
OK. If a debugger is added, it would be nice to have a setting to enable it for devs.

**Comment by alisamii** [comment]
I would like to suggest adding an option to inherit settings of particles in the menu system.

As it stands now, there is a **Base** or **Default** setting and a **Theme** setting for particles, for example, the Logo particle.

For example, in a multi-lingual setup, there is a use-case where you would want to include the Logo within the menu system, and that logo would be used in all languages.

Currently, when you drag in the Logo particle into the menu, it is undefined (image, url, text, etc).

It would be good to be able to simply drag the particle and with a single click define its parameters.

Two options can be envisaged.
- You have a toggle switch to set the particle's parameters to "Custom" or "Current Theme".
- You have a toggle switch to set the particle's parameters to "Custom" or "Predefined".

In the latter case, selecting predefined would insert/enable a dropdown to select from a choice of options such as **Current Theme**, **Base**, **Other Theme 1**, **Other Theme 2** etc. where **Other Theme #** is populated from an array of existing themes.

**Comment by alisamii** [comment]
Any visibility on when this issue might get looked into, specifically re logo particle persistence as described in the use case in my last comment on this issue?

**Comment by w00fz** [comment]
I would love this and many other requests to be implemented asap but the honest truth is we need to focus on getting out the first release and then jump on finishing WordPress which is a tad behind.

When waters are calm again and things are more stable we can focus on adding new features as well as reworking those bits where we are lacking on.

I know there are a lot of good ideas and I truly would like to get them all implemented right away, but unfortunately there's only so much we can do

**Comment by w00fz** [comment]
After evaluation and internal discussion between @mahagr and I, we don't like the idea of implementing any sort of cloning/inheritance logic for the Menu at the moment. The Menu is an independent entity, that only takes a space in the Layout but doesn't share anything else with it.

What we are considering, however, is to let Particles load with defaults values from the Base and allowing the user to override those values, exactly like it happens in the Layout or in the Outlines. (#1367)
