### ISSUE TITLE
Hydrogen doesn't consent VARIATIONS on SECTION just like Helium

### ISSUE THREAD

**Issue by morphinestyle** [gantry/gantry5#3032]
Hydrogen doesn't accept Variations on sections just like Helium, here an example:

HELIUM --- correct
![image](https://user-images.githubusercontent.com/35969533/167293973-86a03418-47d3-41a3-9254-002a79afd7ea.png)

HYDROGEN --- wrong: doesn't recognize variations
![image](https://user-images.githubusercontent.com/35969533/167293961-e562c7a3-019f-4bf2-a6c1-9b272583ae35.png)

There's a way to add it manually?

**Comment by morphinestyle** [comment]
I copied this code from Helium, and i added it to **templates/g5_hydrogen/gantry/theme.yaml**:

![image](https://user-images.githubusercontent.com/35969533/167294358-1f923d38-8df5-43d1-b429-38b0b87c28f1.png)

Does it will be overwritten on next Gantry/Hydrogen update?

**Comment by morphinestyle** [comment]
**UPDATE 2:** After Hydrogen theme update the **override was lost, but the template retain the Variations previously set**.
Now: if i delete the variations, save and want to insert again "NO MARGIN" Hydrogen was unable to found it again.

Please can you add Section Variations also in Hydrogen?

**Comment by pmoreno-rodriguez** [comment]
Hi @morphinestyle 

You will have to create a **_utilities.scss** file in /user/data/gantry5/themes/your_theme/scss/hydrogen/styles folder. In it you will have to write this code:

`// Section Horizontal Paddings
.section-horizontal-paddings {
    padding-left: 10%;
    padding-right: 10%;

    @include breakpoint(tablet-range) {
        padding-left: 0;
        padding-right: 0;
    }

    @include breakpoint(mobile-only) {
        padding-left: 0;
        padding-right: 0;
    }
}

// Section Horizontal Paddings Small
.section-horizontal-paddings-small {
    padding-left: 5%;
    padding-right: 5%;

    @include breakpoint(tablet-range) {
        padding-left: 0;
        padding-right: 0;
    }

    @include breakpoint(mobile-only) {
        padding-left: 0;
        padding-right: 0;
    }
}

// Section Horizontal Paddings Large
.section-horizontal-paddings-large {
    padding-left: 15%;
    padding-right: 15%;

    @include breakpoint(tablet-range) {
        padding-left: 0;
        padding-right: 0;
    }

    @include breakpoint(mobile-only) {
        padding-left: 0;
        padding-right: 0;
    }
}

// Section Vertical Paddings
.section-vertical-paddings {
    padding-top: 4vw;
    padding-bottom: 4vw;
}

// Section Vertical Paddings Small
.section-vertical-paddings-small {
    padding-top: 2vw;
    padding-bottom: 2vw;
}

// Section Vertical Paddings Large
.section-vertical-paddings-large {
    padding-top: 6vw;
    padding-bottom: 6vw;
}
`

With this changes you will able to enjoy of variations styles like in Helium theme.

**Comment by morphinestyle** [comment]
Hello @pmoreno-rodriguez and thank you!
It's not the same like VARIATIONS...

At this point better put some classe to the SECTION and handle sections by custom CSS just like any other rule.
VARIATIONS are practical and better visible while editing SECTIONS than a raw CSS class.

**Comment by mahagr** [comment]
Hydrogen is meant to be a bare minimum theme that you override yourself and use to create your own theme. It is missing a lot of features that other themes have.

**Comment by morphinestyle** [comment]
Hi Matias!
It's true and i know it, but this is a very, very useful feature that does not weigh down the theme.
However: there's a way to put my custom VARIATIONS without losing it on every theme update? (i prefer use variations instead css classes)

**Comment by mahagr** [comment]
You can copy most of the files into `THEME/custom` folder (using the same path). If something doesn't work, please report it to me.

**Comment by morphinestyle** [comment]
No Matias, i put the a modified copy (from the original THEME/gantry/theme.yaml) into THEME/custom/gantry but it's not working: it doesn't load any of the added 8 VARIATIONS.

I also tried to put into: THEME/custom (without gantry), and also adding presets.yaml file, but it won't load these files...

**I can make it work only making an override of the original THEME/gantry/theme.yaml file** (and losing it on every update).

**Comment by mahagr** [comment]
You're right, I will implement that in the next version. The location will be: `THEME/custom/gantry/theme.yaml`

**Comment by morphinestyle** [comment]
Thank you Matias.
This override to Hydrogen will prevent critical improvements or bufixes on theme updates, or theme.yaml is usually a "static" file between Hydrogen theme updates?

**Comment by morphinestyle** [comment]
Helium CI build won't load the overrides in custom/gantry/theme.yaml

![image](https://user-images.githubusercontent.com/35969533/168632400-495bd2e8-7bd6-43c1-b5ed-d8cf861b7290.png)

![image](https://user-images.githubusercontent.com/35969533/168632767-55821657-fd08-4128-bdd0-c8bffa308347.png)

**Comment by mahagr** [comment]
The location looks good. OK. I need to test the build itself, I just tested my dev build quickly. Stay tuned...

**Comment by mahagr** [comment]
@morphinestyle It works for me in Joomla 4. Try changing the name of the theme, it should change the name used at the top of the page. Are you sure you got the CI build which is only ~30 minutes old (at my writing)?

**Comment by mahagr** [comment]
Glad it works now. I'm closing the issue. The new release should be out in about 2 weeks, be careful not to update Gantry before that! :)
