### ISSUE TITLE
How do I add a menu module to Custom HTML?

### ISSUE THREAD

**Issue by kosh2323** [gantry/gantry5#3033]
In Gantry 5, it is possible to add different modules both through the menu manager and through Module Instance. But for example, you need to add a menu module directly to Custom HTML, something like ShortCode{menu: id=120}. There are Process ShortCodes in the Custom HTML particle itself, but I haven't found exactly what it's for in the documentation. Is there such an opportunity to add or search for some other modules for output, and how will Gantry work with these third-party modules?

**Comment by mahagr** [comment]
I would use third party modules for this as long as you don't need Gantry specific features for your menus.

**Comment by kosh2323** [comment]
> I would use third party modules for this as long as you don't need Gantry specific features for your menus.

In principle, there are 2 ways (tested experimentally): 

1. It's simple to place the necessary code in the module position, creating for example an HTML module, inside the code to register the call of the desired menu {loadmoduleid 120}, while enabling processing by plugins. Gantry is not even involved here, only tools Joomla 4. 

2. Use the Custom HTML particle and in the code also call the necessary menu {loadmoduleid 120}, turn on and put daws on Process Shortcodes, and this also works, by the way, I don't understand why there are 2 ticks? Just wondered if there are any even simpler ways?

**Comment by marktaylor46** [comment]
I see no good use case that would require such a thing. Add a position in your layout and assign a menu particle module to that position or just put the menu particle on the layout anyway. But if you really want to do this and are using Joomla CMS you can use Joomla {loadposition xxxx} or {loadmodule xxxxx} in a customhtml module or particle (make sure you enable "process shortcodes").

Regards, Mark.

**Comment by kosh2323** [comment]
> 



> I see no good use case that would require such a thing. Add a position in your layout and assign a menu particle module to that position or just put the menu particle on the layout anyway. But if you really want to do this and are using Joomla CMS you can use Joomla {loadposition xxxx} or {loadmodule xxxxx} in a customhtml module or particle (make sure you enable "process shortcodes").
> 
> Regards, Mark.

Hi Mark. This idea came from this. There will be 2 menus on the site and both are collapsible in adaptivity mode. The first menu is the main one in the Navigation section, there are no problems with it. The second menu will be in the Header section, and this section will be above the Navigation. The menu will have one level of nesting and, if adaptable, will collapse into a hamburger icon. In this mode, there will be 2 hamburger icons, when clicked, the main menu will go to the left, and the one-level menu from top to bottom. To do it manually, you have to come up with different ways. For example, with or without a script, but, the hamburger button code has to be prescribed separately from the menu itself, as well as classes. Therefore, we have to make an HTML module, and register it in it:

`<nav class="navbar">
	<div class="container">
		<section class="wrapper">
			<a href="./index.html" class="brand">Brand</a>
			<button type="button" class="burger" id="burger">
				<span class="burger-line"></span>
				<span class="burger-line"></span>
				<span class="burger-line"></span>
				<span class="burger-line"></span>
			</button>
			<div class="menu" id="menu">

	<ul class="menu-inner">///Here instead I prescribe {loadmoduleid xxx}
</di>
........
</nav>`

**Comment by marktaylor46** [comment]
It's not going to work like that. 

1. A menu particle (even if in a module) still is controlled by Gantry and it's existence may well interfere with the normal working of the other menu.
2. There's no such thing as loadmoduleid - it's load module
3. it's a messy solution.

Honestly the easiest thing for you to is use a third-party menu  module that has all this built in out of the box. Look on JED there are plenty of them available.

**Comment by kosh2323** [comment]
> It's not going to work like that.
> 
> 1. A menu particle (even if in a module) still is controlled by Gantry and it's existence may well interfere with the normal working of the other menu.
> 2. There's no such thing as loadmoduleid - it's load module
> 3. it's a messy solution.
> 
> Honestly the easiest thing for you to is use a third-party menu module that has all this built in out of the box. Look on JED there are plenty of them available.

Thanks for the answer Mark. I understand that this is a bad decision, and I'm looking for bad ways, but I started looking after I tried several menu modules with JED.

**Comment by marktaylor46** [comment]
Ok, nothing more I can add then, sorry.

Regards, Mark.

**Comment by mahagr** [comment]
Maybe create your own particle? The menu data is pretty close to that of Joomla (and easy to understand), so if you have the skills you can create your own particle by copying the menu particle and just modifying it to your liking.

**Comment by kosh2323** [comment]
> Maybe create your own particle? The menu data is pretty close to that of Joomla (and easy to understand), so if you have the skills you can create your own particle by copying the menu particle and just modifying it to your liking.

You can try it, thanks for the idea. I thank everyone who took part in the discussion. The topic has exhausted itself, apparently it should be closed.
