### ISSUE TITLE
Off Canvas Side Menu Bar?

### ISSUE THREAD

**Issue by ginto202** [gantry/gantry5#3053]
This is probably embarrassing but I can't figure out why mobile post pages have this bar on the side and allow mobile users to horizontally scroll to it thus making google think it's not mobile-friendly.. site is juicing-for-health.com
![Screenshot 2022-06-21 205736](https://user-images.githubusercontent.com/43481726/174920926-55b02733-e5b7-4fb7-8fd9-05a4799e4e4f.jpg)

**Comment by abbyjarvis** [comment]
Hi let connect though a direct call and discuss the issue. contact me https://pankajsangwan.com/#footer
