### ISSUE TITLE
How to properly connect all your styles to custom?

### ISSUE THREAD

**Issue by kosh2323** [gantry/gantry5#3059]
The documentation says how to connect custom.css, and there are no problems with this, but how does the compiler work in gantry? 
Let's say we want to connect several more files, both scss and just css. Do I need to write the *.css extension when connecting? Or just rename it to *.scss?

Do I need underscores for all files or only for those that we don't want to compile, for example mixins, variables and the like?How is it more correct to get 1 custom file at the output, so that it is compiled later?

**Comment by kosh2323** [comment]
I understand that the questions may be banal and simple, and someone may be annoyed, but I ask you, friends, to answer who knows.

**Comment by PhocaCz** [comment]
Hi, all custom css should be .scss. Mostly files with underscores are files which should be imported into main .scss file

**Comment by kosh2323** [comment]
> Hi, all custom css should be .scss. Mostly files with underscores are files which should be imported into main .scss file

Hi Jan, I'm surprised that someone answered, I already understood that, thanks for the answer. I'm closing the topic.
