### ISSUE TITLE
Joomla 4.2 arrived

### ISSUE THREAD

**Issue by WolfgangDomroese** [gantry/gantry5#3069]
Hello,

is Gantry5 now working with Joomla 4.2?

Kind regards, Wolfgang

**Comment by mahagr** [comment]
They pulled it back. I will need to test it out, though, and allow upgrades for 4.2, though...

**Comment by kosh2323** [comment]
Hello, when upgrading to 4.2, writes that there are updates to overrides. I didn't write this in version 4.15.

![1](https://user-images.githubusercontent.com/82117170/185308221-b25793a1-b60e-415e-a5a4-0ad093a14990.jpg)

![2](https://user-images.githubusercontent.com/82117170/185308253-54947569-1cb8-4da2-8d9b-882806c68ae1.jpg)

![3](https://user-images.githubusercontent.com/82117170/185308272-bc73ebe0-3b76-4ea7-9e4d-32d8f0a7cad1.jpg)

**Comment by mahagr** [comment]
You can safely ignore the warning; In Joomla 4 the file is just loading the proper layout from Joomla itself (the file is there for backward compatibility for the older versions of Joomla 3).

**Comment by WolfgangDomroese** [comment]
I've updated - OK. The warning about Overrides ist still there - I ignored!

**Comment by mahagr** [comment]
The latest version should work with J4.2, though I'm seeing issues with their new MFA feature (someone just reported it).
