### ISSUE TITLE
Question: Fixed Nav - - - 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#307]
@kevlardev I've fixed the navigation and work is fine with a litle exception. After adding `position: fixed` to nav section ( that is outside g-page-surround), by default will cover `g-page-surround` so i've added `position: relative` and `top` value.  

The only problem is: if nothing is placed in nav section, it will not show, but the empty space will still be there at top, of course because page-surround have a top value.

How should we handle this? I don't really like that top value.

**Comment by kevlardev** [comment]
This is most likely a case where there would need to be some javascript to make it truly dynamic, something that could detect the height value of the nav section and apply the top value matching that size.
