### ISSUE TITLE
Joomla 4.2.2 update Causing Hydrogen Front-End to Crash

### ISSUE THREAD

**Issue by dgrimey** [gantry/gantry5#3076]
I updated a localhost site last night to 4.2.2. Everything appeared to be okay, but I didn't check the front end. When I looked at the front end I got the Joomla "Something went wrong" page.

I set my Error Reporting to maximum and the following line stood out. I have attached a screen shot of the full error. I hope this helps. 

Error Message pointing to this line [59] - siteurl/templates/g5_hydrogen/html/mod_login/default.php:59

![Screenshot 2022-09-09-joomla-4-2-update](https://user-images.githubusercontent.com/22226227/189396336-6433d3ba-d60f-4d6c-bb60-44f9054cc34d.png)

**Comment by dgrimey** [comment]
I found a fix. I had started an override with the login module through the gantry back-end. I put all the items I had in the "/Templates/Gantry/html"   folder into a new folder within that directory. This allowed me to access the site again. It was a override in the login module that I wasn't using. 

I love gantry and hope this helps in some way.

**Comment by N8Solutions** [comment]
@dgrimey since you have solved this, can you please mark this as solved to help out the Gantry 5 team?

**Comment by verysaltyHH** [comment]
Error Message pointing to this line [59] - siteurl/templates/g5_hydrogen/html/mod_login/default.php:59

Ich habe es gelöst, indem ich die delault.php aus dem Ordner /templates/g5_hydrogen/html/mod_login/default.php mit der aus  /modules/mod_login/tmpl/default.php ersetzt habe.

**Comment by verysaltyHH** [comment]
Error Message pointing to this line [59] - siteurl/templates/g5_hydrogen/html/mod_login/default.php:59
Ich habe es gelöst, indem ich die delault.php aus dem Ordner /templates/g5_hydrogen/html/mod_login/default.php mit der aus  /modules/mod_login/tmpl/default.php ersetzt habe.
