### ISSUE TITLE
Social Particle - one size fits all

### ISSUE THREAD

**Issue by essiele** [gantry/gantry5#308]
It would be handy (and time-saving) to be able to change the size of the `.fa` icons all at once, as opposed to having to do them individually.

**Comment by w00fz** [comment]
We have a magical button for that! :crystal_ball: 

![magic](https://cloud.githubusercontent.com/assets/11734/7689860/4b8e121c-fd64-11e4-8232-cb6570bc32c7.jpg)

Try clicking it :)

**Comment by essiele** [comment]
Yes, I know that magical button... however,  you still need to cast more than one spell, once you're in that magical chamber, to turn them all into giants... or dwarfs.

**Comment by essiele** [comment]
... then you realize "Oops! Wrong spell..."

**Comment by w00fz** [comment]
You can still manually type in there the size, `fa-2x` etc, without having to open the Icon Picker. The grid view just makes it easier to change all at once.

**Comment by essiele** [comment]
ok... hold the phone...

**Comment by essiele** [comment]
Ok... so I went into grid view (as I have been)
changed the size of **one** icon (I currently have 4)
apply > apply > save > refresh front-end

Only the **one** icon changes size. What I'm saying is, it would be great to be able to change them all in **one** click.

**Comment by w00fz** [comment]
But that would not be so easy because how are we supposed to know what portion of that field you want to apply to all the other fields? I am sure you have different icons for all of them and all you are changing is the size. I know it is manual work you have to do if you have to apply the size but there is no possible way for us to sync automatically portions of them.

I am not sure how many icons you have but it can't be that bad copy and pasting the value you want for all the fields. Through the grid you could handle all via keyboard between `tab` and `cmd+v`

**Comment by essiele** [comment]
I hear you... but it would be a "per particle" operation, anyway. I'm just trying to encourage the DRY philosophy... for users, too.
Yeah, I know we can always `tab` and `ctrl+v` (when I grow up, I'll buy a Big Mac) for however many icons there are... but then there's always the likelihood of the "Oops! Wrong spell..." syndrome creeping in at some point.

**Comment by essiele** [comment]
Also, it encourages uniformity, IMHO.

**Comment by w00fz** [comment]
So how would you solve this issue UX wise?

**Comment by essiele** [comment]
![select-size](https://cloud.githubusercontent.com/assets/2575283/7690818/f3eb8e86-fdae-11e4-9e90-84fe77f1e3c9.png)

**Comment by essiele** [comment]
Then if further icons are added, they inherit the previously selected size,

**Comment by w00fz** [comment]
Ok let me ask you this then. What if tomorrow someone else wants to have a synchronized `fa-spin` and a synchronize `fa-flip` and a synchronized `Link`, etc, etc. You see where I'm going right?

Basically now it is just the size that you are finding it needs to be typed only once but that applies to any possible field and setting of the field. Besides, not all Collections might actually have an Icon field so the Size, down there, would not make sense for those.

Don't get me wrong, I hear you, I just think that for something that once set rarely is going to be changed again, it is not worth it. It might take you that 1-2 seconds per item to adjust the size manually, but once you found the right one, I bet you aren't going to change that for a very long time, if ever.

**Comment by essiele** [comment]
I see exactly where you're going... and your point is valid.

I still think it would be a great asset for a framework of this caliber. You're already on your way to blowing all others out of the water with G5... why stop now?

Here's another thought... I remember seeing Matias type something like "I need to make some money (lol)" a while back... how about implementing that feature in the subscription-based templates? I'd pay to get a feature like that! I'm sure others would, too.

**Comment by essiele** [comment]
Here's an even better idea... it actually woke me up!
![select-all](https://cloud.githubusercontent.com/assets/2575283/7693264/c06242ea-fdc6-11e4-9626-5f48494b9a24.jpg)

See what I did, there?

Ok... back to bed. Na nite!

**Comment by mahagr** [comment]
Right now we do not have a way to bind those fields together and implementing feature like this may take up to half a working day if you need to do all the base work for it. I would rather use that time to something that really slows down people, like making CSS compilation automatic during the development so you wouldn't need to hit recompile and wait for a few seconds every time you change a line in SCSS.

I'm closing this issue for now as we have other issues that are far more important at this stage of the development. I also believe that after creating your first Gantry 5 site, you will be able to point out other issues that will annoy you much more than this one. We still have a lot of missing features and there are still bugs which will make you to curse more than once. Those are the ones we would like to fix first.

**Comment by essiele** [comment]
Cool. 
Just to clarify, it was more of an observation than an annoyance. One of my roles at work is future-proofing... maybe I just forgot to leave work at the office.
Gantry6, maybe?

**Comment by w00fz** [comment]
Hey it's no annoyance at all. Thank you for taking the time to bring this up and be constructive about it, it is really appreciated.
Sometimes we just have to make a decision on what we think works best for the project and unfortunately we didn't agree on this one. Perhaps in the future we will find a better and more magical way to handle what you brought up here so, please, don't take it personally!

Thank you.

**Comment by essiele** [comment]
Awww, c'mon! Take it personally? No way, dude! Heck no!
I'm actually ROOTING for this project! Been posting all over [LinkedIn] (https://www.linkedin.com/groupItem?view=&gid=52867&type=member&item=6005112286061092865&trk=groups-post-b-title) about it!

At this point, I've got just one thing to say... like, **CARRY ON!**

**Comment by mahagr** [comment]
The main reason why I closed the issue was that we are really flooded on issues and it makes me to feel better if the list didn't grow too much. We might reconsider usability improvement like this at some later version, but we really would need a few other use cases so we could have a generic approach that would cover all the similar cases as well. By itself and at this stage it just doesn't make sense to me to use the time needed to implement the feature for this single use case.

That said, if you find something that really affects your every day life, please report it as we really appreciate any help we can get.

As a side note on my quote, I may have been a bit tired when I wrote that one as it seems to have slightly different meaning than I meant for it. :)
