### ISSUE TITLE
Gantry / Hydrogen : no Wordpress upgrades via GUI/WPCLI 

### ISSUE THREAD

**Issue by designzwang** [gantry/gantry5#3097]
We run Gantry 5.5.14 on Wordpress. While tracking down  PHP8.1-related problems, I found out that there are some php8 fixes in 5.5.15,  however I  was not aware of an upgrade being available.

But the GUI and WP Cli report no available Upgrades
+-----------------------------------------------+----------+--------+----------+
| name                                          | status   | update | version  |
+-----------------------------------------------+----------+--------+----------+
  gantry5                                       | active   | none   | 5.5.14

Is this a problem/error in the relase process of new versions, or is it working as designed and users are reqired to check and install upgrades manually ? The same issue is with the hydrogen theme, which has updates available but they are not reported in the GUI or WP-CLI.

Regards, 
Ulrich

**Comment by N8Solutions** [comment]
@designzwang I commented on your other post #3106

Please refer to https://github.com/gantry/gantry5/issues/3100 for more information. All I can say is that we need to be patient while they get things handled.

Again, if this satisfies your inquiry, please close this issue.


regards,

Michael

**Comment by designzwang** [comment]
Alright, thanks @N8Solutions !
 To sum it up for others reading this: download the 5.1.15 packages of Hydrogen and Gantry from https://gantry.org/downloads and install them manually. I can confirm that they worked in my environment ( Wordpress & PHP 7.4/8 )
