### ISSUE TITLE
Offcanvas Position

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#31]
Hey guys,

It is not a bug but an enhancement request :)
Would you please create an Offcanvas position? T3 Framework and Helix 3 have it (just in case you want to have a look). I do not care about the other frameworks and I suppose you too, but it is a must-have feature in my opinion.

You can publish whatever you want in the Offcanvas position - you can have another menu there, yu can have your shopping cart there, etc.

Just a small icon in the header and when you click it it brings the offcanvas element :)

**Comment by mahagr** [comment]
We already have off-canvas for non-visible elements (css/js), but to be honest this never came into my mind. It is a good idea, though and should be easy to implement as well.

I'm just not sure how we should represent something like this in our layout manager...

There is actually "existing" way to do this, and it is by assigning a class to the section/column to hide its contents. But yes, its probably not something that general user thinks of.

**Comment by JoomFX** [comment]
Thanks @mahagr :)
Yeah, I'm also wondering how it should be presented in the Layout Manager.

Can it be made as a Particle - you have the "Offcanvas" particle so you can put it wherever you want. Then this "Offcanvas" particle will be rendered on the Frontpage as a "Hamburger" icon or something similar. And when you click on it, the Offcanvas element appears.

Hmm, if it is a Particle, as I wrote above, how would we be able to assign another Particle to it (the "Module Position" particle) :D I see that it is not that simple!
Maybe the "Offcanvas" particle can be a subtype of the "Module Position" particle, so once you put the "Offcanvas" particle in your Layout, the "offcanvas" module position appears in the Module Manager?

What do your think about it @mahagr :)

**Comment by mahagr** [comment]
Yet another idea could be something like this:

```
{% block particle %}
  <i>Hamburger goes here.</i>
{% endblock %}
{% block offcanvas %}
  <p>Real content goes to here.</p>
{% endblock %}
{% block javascript %}
  <script>And you can guess what goes to here...</script>
{% endblock %}
```

Of course you could also other particles to this one, but there is still some missing logic (how to handle forms / validation) to make it happen.

**Comment by JoomFX** [comment]
Thanks mate :)
Will play with it and will see if I can come up with another idea ;)

**Comment by rhukster** [comment]
We added this **offcanvas** position in our later Gantry4 RocketTheme templates, I think we will definitely do so again for G5 ones too.  Just not gotten to it yet.  Thanks for the reminder!

**Comment by JoomFX** [comment]
Great! Thanks Andy :)

**Comment by mahagr** [comment]
Feature is now implemented and hardcoded as display:none, we still need hamburger and associated javascript to make it to work.
