### ISSUE TITLE
Outline preset body class

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#310]

**Comment by w00fz** [comment]
@mahagr have a look at this one and see if you are ok with it, I kinda dislike having to use the Joomla API to retrieve the menu alias and outline preset but seems to be a frequent request for targeting the page via CSS.

**Comment by mahagr** [comment]
I agree by not using menu path in body; if you want to see the path, just look into url instead. With SEF it will be identical (and translated), so honestly why to bother? If you want to target the page, there are better ways to do it.
