### ISSUE TITLE
Gantry status labeled "version higher than expected" in WP-Cli

### ISSUE THREAD

**Issue by designzwang** [gantry/gantry5#3106]
Follow-up to https://github.com/gantry/gantry5/issues/3097 : 
after manually installing the latest update to 5.5.15 for php8 compatibility, WPCLI shows 

` wp plugin list
+--------------------------+----------+------------------------------+---------+
| name                     | status   | update                       | version |
+--------------------------+----------+------------------------------+---------+
...
| gantry5                  | active   | version higher than expected | 5.5.15  |`

Will this cause any problems? Is 5.5.15 actually recommended for production use?
Regards 
Ulrich

**Comment by N8Solutions** [comment]
@designzwang Yes, Gantry 5.5.15 is a stable release version. I do not know why, but for some reason it is not showing up in Joomla either as the latest release available. I know the folks at Rocket Theme are a little short handed these days so they have fallen behind in taking care of some issues.

However, rest assured, it does fix some PHP 8 issues. With that said, others have reported issues with PHP 8 & 8.1 that have not yet been addressed. You can search the issues for those easy enough to see what they are. It is my understanding though that those issues are not show stoppers in the functionality and usage of Gantry 5.

If this satisfies your inquiry, please close the issue.


regards,

Michael

**Comment by designzwang** [comment]
Well, with PHP 8.x   I had to disable WP_DEBUG in our dev site and override two error types in SystemFacade.php->handleError to avoid the Gantry Error Handler interfering with many backend pages. 
  	if ((strpos($message, 'Undefined array key') !== false) || (strpos($message, 'Undefined variable') !== false)) {
		return false;
	}

Hope we can make the switch to PHP 8 soon on the production site. But anyway, thanks for your feedback , will close the issue. 
Regards, 
Ulrich
