### ISSUE TITLE
Question - selectize

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#311]
I've tried to add a selectize for align. But the code will be added like this: `'center'` , and will not work if the code is placed inside `''` .  As you can see in second picture. Is there anything to do ?

![2](https://cloud.githubusercontent.com/assets/9744973/7697408/2d67af94-fe10-11e4-844f-6d6b05ad19b3.PNG)
![1](https://cloud.githubusercontent.com/assets/9744973/7697411/2f6440a0-fe10-11e4-978a-1651cf532010.PNG)

**Comment by adi8i** [comment]
That's odd, because i have something similar for animation, and is works fine. 
![capture](https://cloud.githubusercontent.com/assets/9744973/7697623/10531e6e-fe12-11e4-9e82-f6da292da403.PNG)
![2](https://cloud.githubusercontent.com/assets/9744973/7697624/116e945e-fe12-11e4-9001-6f96b6719fe9.png)

**Comment by mahagr** [comment]
You may use this inside of scss:

unquote($string)

All the strings are quoted because of we do not know how they are going to be used and compiler fails on illegal input.

@FrugalGeek This might be something worth to document.

**Comment by adi8i** [comment]
Yep. That was. Thanks @mahagr
