### ISSUE TITLE
How to unset CSS/JS in Gantry 5?

### ISSUE THREAD

**Issue by lipatovroman** [gantry/gantry5#3112]
Hello,
How to unset CSS and JS files in Gantry 5?
I mean: where I can use 
unset($this->_styleSheets[JURI::root(true).'/media/jui/js/bootstrap.min.js']);
and similar unsets.
Thanks.

**Comment by saman222** [comment]
Hi. You can not do that. Your syntax use php and must use in .php file.you must use other extension under Joomla framework

**Comment by lipatovroman** [comment]
> Hi. You can not do that. Your syntax use php and must use in .php file.you must use other extension under Joomla framework

I just tested this code
`use Joomla\CMS\Factory;
$document = Factory::getDocument();
$document->setGenerator('Testing');
$document->addStyleSheet('/234567/123.css');
unset($this->_styleSheets[JURI::root(true). '/components/com_flexicontent/templates/empty/css/category.css']);`

in file /templates/g5_helium/index.php
and it's working ok.

Now, the problem is that this code will be removed after Helium update.

**Comment by saman222** [comment]
> > Hi. You can not do that. Your syntax use php and must use in .php file.you must use other extension under Joomla framework
> 
> I just tested this code `use Joomla\CMS\Factory; $document = Factory::getDocument(); $document->setGenerator('Testing'); $document->addStyleSheet('/234567/123.css'); unset($this->_styleSheets[JURI::root(true). '/components/com_flexicontent/templates/empty/css/category.css']);`
> 
> in file /templates/g5_helium/index.php and it's working ok.
> 
> Now, the problem is that this code will be removed after Helium update.

why you don't use gantry custom css atom or use custom css under Page setting tab.

**Comment by lipatovroman** [comment]
> why you don't use gantry custom css atom or use custom css under Page setting tab.

Because I need to disable unused CSS and JS. I need to use unset () function.

**Comment by N8Solutions** [comment]
@lipatovroman I just read your issue and thought this extension might be able to help you.
https://kubik-rubik.de/jcc-js-css-control


regards,

Michael

P.S. since this isn't an actual bug, please mark this as closed to help keep things clean.
