### ISSUE TITLE
Help with Yaml, layout code

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#313]
Im trying to do my own layout, but i have 0 knowlage of yalm, i search yesterday few hours but still :s
I have this layout, and wana that container appers inside one secction like top.
How i can add class or id on the first element of layout (not only class="g-container"). 

Is this possible?
another question is if i can add custom id and class names directly on yaml layout? (for ex if wana only the first container with id:cont-main
```
layout:
  container:
    1:
      - main 60:
        - pagecontent
      - left 20:
        - position-left
      - right 20:
        - position-right

  top:
    container:
      - position-top
```

**Comment by w00fz** [comment]
You can but it's more complex than that. The file you are describing up above is the simplest layout representation, the real full layout that gets saved and rendered on frontend can be found in `custom/config/<id>/layout.yaml`. In there you will find all the elements that create the page, including attributes such as `id` and `class`.
Find the container you want to have the class in that file and then in the attributes add `class: your-class`.

**Comment by AbeAlpha** [comment]
Nice :D im happy to know now and not soo hard, soo much ours searching TT
This means every time i change the simplest layout representation i lose the changes on the real full layout?
There is no way for add the optional attributes on the simplest layout?

**Comment by w00fz** [comment]
You should try but if you change the `layout.yaml` next time it will be loaded like that and even though you dont see the attributes for container in the admin they should still be preserved.
