### ISSUE TITLE
Gantry 5.5.16-dev Image picker not working when error reporting is set to maximum

### ISSUE THREAD

**Issue by uGE70** [gantry/gantry5#3131]
Platform (Mac MAMP Pro):
Joomla 4.2.9, Gantry 5.5.16-dev, Studius template, PHP 8.1.1 +, no cache, no SEO plugin
Chromium browsers on Mac.

Steps to reproduce
Set error reporting to maximum in Joomla.
Use the image picker of any Gantry 5 Particle in the layout manager, for instance the logo particle.

Expected result
The image picker is working and you can select any file.

Actual result
500 Internal Server Error
Oops, An exception has been thrown during the rendering of a template ("html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated")...

Thanks for your work on Gantry 5.5.16-dev. I didn't see any other glitches.

**Comment by marktaylor46** [comment]
Yes, I can reproduce. We’re looking into it now. Thanks for reporting.

Regards, Mark.

**Comment by hexplor** [comment]
Should be fixed in dev :) Releasing soon :)

**Comment by uGE70** [comment]
Successfully tested. Thanks for your work !
