### ISSUE TITLE
Failed to install Gantry5 framework latest 5.5.16

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#3136]
Hi there,
I noticed the Gantry5 framework 5.5.16 released 1 hour ago, however, the pkg_gantry5.xml is not updated. 
Please check and change the version, creationDate and update the package version. All packages should be 5.5.16 instead 5.5.15
Thank you so much for this release.

**Comment by hexplor** [comment]
Hi, 
Thanks for pointing that out. Updating tokens right now :) 
Best,
