### ISSUE TITLE
Error extension "plg_system_gantry5_v5.5.15.zip" during installation of "Gantry 5.5.16".

### ISSUE THREAD

**Issue by jmgroud** [gantry/gantry5#3139]
Error on the extension "**plg_system_gantry5_v5.5.15.zip**" during the installation of "**Gantry 5.5.16**".
Where does this message come from and why this version difference between Gantry and the plugin? 

"Warning
The installation path does not exist
Update Pack: error while installing the extension plg_system_gantry5_v5.5.15.zip"

When I try to install Gantry in version 5.5.15, everything is OK!
Is it a bug? An operation to do on the server to remove this message? A folder to create ? etc...

I am under Joomla 4.2.9 and PHP 8.1.17
![20230404 - Err Inst Gantry 5 5 16](https://user-images.githubusercontent.com/1281543/229730687-fd96755a-7bb2-4ef8-bad0-7bfc49ae1de9.jpg)

**Comment by N8Solutions** [comment]
@jmgroud Please post this information over in the previously created issue here (https://github.com/gantry/gantry5/issues/3138) so we won't have duplicates of the same thing.

**Comment by jmgroud** [comment]
OK i have posted this in then #3138 but how to delete this post ?

**Comment by N8Solutions** [comment]
@jmgroud Thank you, and you can just mark it as closed and that will be fine.
