### ISSUE TITLE
No update offered

### ISSUE THREAD

**Issue by DMHas** [gantry/gantry5#3143]
Hello all,

Jooma does not show an update for Gantry to version 5.5.16. Installed is the Gantry 5.5.15 with Hydrogen (v5.5.15 / g5_hydrogen). Joomla version is Joomla! 3.10.11 Stable. Is there anything I can do to trigger the update? (The cache has already been cleared - no change).

Thanks in advance!
Greetings DMHas

**Comment by N8Solutions** [comment]
@DMHas If would, please close this ticket and comment over on the existing thread regarding v5.5.16. It would seem @hexplor has not yet enabled the autoupdate in the backend yet after doing some debugging after the release 2 weeks ago. You can check that thread out here https://github.com/gantry/gantry5/issues/3138#issuecomment-1495949572.

In the meantime, if you would like to, you can download the updated version and install it manually. You can find the files at this URL, https://gantry.org/downloads, just be sure to grab the correct one for your Joomla.

kind regards,

Michael

**Comment by DMHas** [comment]
> https://github.com/gantry/gantry5/issues/3138#issuecomment-1495949572

> In the meantime, if you would like to, you can download the updated version and install it manually. You can find the files at this URL, https://gantry.org/downloads, just be sure to grab the correct one for your Joomla.

@N8Solutions: Thanks for your reply! Thread closed.

**Comment by DMHas** [comment]
>https://github.com/gantry/gantry5/issues/3138#issuecomment-1495949572

>In the meantime, if you would like to, you can download the updated version and install it manually. You can find the files at this URL, https://gantry.org/downloads, just be sure to grab the correct one for your Joomla.

@N8Solutions: Thanks for your reply! Thread closed.
