### ISSUE TITLE
Don't get an update notification

### ISSUE THREAD

**Issue by webmasterab** [gantry/gantry5#3155]
I don't get an update notification in my Joomla 4 environment.

This is also not so strange when I look at the XML.
There is still 5.5.15 while there is already 2 months version 5.5.16.

https://updates.gantry.org/5.0/joomla/pkg_gantry5.xml

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<update>
<update>
<name>pkg_gantry5</name>
<description>Gantry Framework</description>
<element>pkg_gantry5</element>
<type>package</type>
<client>site</client>
<version>5.5.15</version>
<infourl title="Gantry 5.5.15">http://docs.gantry.org/gantry5</infourl>
        <sha512>937dd530553add1440ff6187bd7f7ebee58b75da52d3da801b599bb104d0d4efec720d0f944b42705db78ab9177216ab24060c2efe5a36aed4853bc51066ae2d</sha 512>
<downloads>
<downloadurl type="full" format="zip">http://updates.gantry.org/download/5.5.15/joomla-pkg_gantry5_v5.5.15.zip</downloadurl>
</downloads>
<tags>
<tag>stable</tag>
</tags>
<maintainer>RocketTheme, LLC</maintainer>
<maintainerurl>http://gantry.org</maintainerurl>
<section>Updates</section>
<targetplatform name="joomla" version="(3.9)|(3.10)|(4.0)|(4.1)|(4.2)"/>
<php_minimum>5.6.20</php_minimum>
</update>
</update>

**Comment by N8Solutions** [comment]
@webmasterab They are aware of this as there was an issue with the v5.5.15 update. You can read about it here: 👉  https://github.com/gantry/gantry5/issues/3138#issuecomment-1529046851 👈 

Please close this issue to help keep things cleaned up.

**Comment by webmasterab** [comment]
Please close this issue to help keep things cleaned up.
