### ISSUE TITLE
Failed to save entry: Grav\Framework\Flex\Pages\Traits\PageLegacyTrait::file(): Not Implemented

### ISSUE THREAD

**Issue by vparmeland** [gantry/gantry5#3157]
I encoutered this issue while saving a page on GRAV CMS (I use Gantry theme)

![image](https://github.com/getgrav/grav/assets/17825769/9b46fdea-8d2a-4cdc-be85-bc7a72c19b4a)

Config : 
- I'm using the latest Grav version + up to date plugins
![image](https://github.com/getgrav/grav/assets/17825769/c47295a0-4a63-45d1-843b-50eceb51a957)

I already mentionned an issue on our community forum : 
https://discourse.getgrav.org/t/error-when-saving-a-page-pagelegacytrait-file-not-implemented/23247

Same issue here : https://discourse.getgrav.org/t/1-7-and-flex-pages-pagelegacytrait-move-not-implemented-error/11678/2

**Comment by blizam** [comment]
I encountered this error in the past but it's cleared for me, I assume with an update made to Grav.

Are you still facing this issue? What theme (Gantry is a plugin/theme framework, not a theme itself) specifically are you using?

Can you turn on debugging and post the entries there when this occurs? https://learn.getgrav.org/17/advanced/debugging
