### ISSUE TITLE
lightcase.js and webp images compatibility

### ISSUE THREAD

**Issue by impressionestudio** [gantry/gantry5#3158]
Hi. 
This is an easy and small improvement for lightcase.js in order to display webp images correctly. Please go to file "media/gantry5/assets/js/lightcase.js" find the line containing 'jpg,jpeg,gif,png,bmp', and add webp. 
So simple. Please include this in the next version of Gantry.

Thank you

**Comment by N8Solutions** [comment]
Tagging @rhukster @hexplor @mahagr Is this something that can get added when v5.5.17 is released?
