### ISSUE TITLE
Fixed Background on chrome 

### ISSUE THREAD

**Issue by Hertak** [gantry/gantry5#316]
The problem is present on chrome when you put a fixed Background caused by transition on the g-page-surround element

**Comment by adi8i** [comment]
Can you be more explicit ?

**Comment by Hertak** [comment]
Sorry i forget the url http://coloniasycerros.com.ar/index.php?option=com_content&view=category&layout=blog&id=8&Itemid=118 
In firefox the fixed background works fine but not on Chrome on Gitter JoomFX  say that i need open the issue.

**Comment by adi8i** [comment]
First off all remove that `fixed` in your code.  It dose nothing , what are you trying to do?

**Comment by adi8i** [comment]
Oh i see now, yes g-page-surround block fixed-attachment

**Comment by JoomFX** [comment]
@adi8i I asked @Hertak to open this issue because the `transform` that me and you are fighting agains is causing the issue in Chrome.

I asked @Hertak to open this issue as a reminder for @w00fz and @kevlardev so they can try to come with another solution by removing the `transform` from `g-page-surround`. Of course, do it when you have time, we completely understand that there are more important things ;)

**Comment by kevlardev** [comment]
Yes, this is an issue in most browsers. Ive seen several reported issues about it with Chrome and Firefox in particular in that 'fixed' behavior of everything fails to be be fixed when a transform is in effect, even if the transform is 0. We're working on some different approaches to try to retain the same functionality of the current offcanvas system using a different method.

**Comment by JoomFX** [comment]
It's great to hear you are already working on a different approach, with the `transform`.
Thanks guys!

**Comment by JoomFX** [comment]
@kevlardev @w00fz have you guys found another solution without `transform`?
This is the only issue that is still open regarding this problem. You can also see https://github.com/gantry/gantry5/issues/307 and https://github.com/gantry/gantry5/issues/328 .

Sorry for asking for this every 3, 4 days but now when I started developing I see how limiting this `transion` actually is. You cannot have a fixed header, you cannot have fixed backgrounds, you cannot have a nice fixed "Scroll to top" button. Yeah, you cannot have anything fixed and at the same time all of the above are quite trendy design elements.

**Comment by kevlardev** [comment]
This has been reworked to use a different method and should no longer prevent fixed elements. 995609b1562bfa72de8e1b334e4a2536dee92189
