### ISSUE TITLE
Disabled particles vs particle widths

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#317]
Create 3 particles in a section (33.3% width)
Disable the most left particle
Adjust the width of the middle particle to 70% for example
Since disabled particle will still cover a 33.3% space the second will overlap the third.
Unless disabled particle will be trashed width adjustments won't output the desired view

**Comment by adi8i** [comment]
Is working fine, i am not sure what are you trying to do, but i don't see any issue :)

**Comment by adi8i** [comment]
Right now is working like this: 
I have 3 particles, first is disable, and take 5%, second take 70 %, the last one take 25%.
![1](https://cloud.githubusercontent.com/assets/9744973/7703536/481f1396-fe41-11e4-816f-3a79ecd70a03.PNG)

Now because the first one is set to disable, on front end, that 5% will be redistributed.
![2](https://cloud.githubusercontent.com/assets/9744973/7703548/6198f170-fe41-11e4-93be-ec05a38a64a7.PNG)

**Comment by sural98** [comment]
I have tried without adjusting the width of 1st

**Comment by adi8i** [comment]
Is working fine, i just tried it.

**Comment by w00fz** [comment]
This seems to be working fine for me as well.

**Comment by sural98** [comment]
Backend needs some cosmetic styling for such scenarios.
![joomla 341 administration](https://cloud.githubusercontent.com/assets/1849490/7725493/d29bd5a0-ff03-11e4-820c-05cbd32ac25a.png)

**Comment by adi8i** [comment]
1. Where would you like that block to be placed ?
2. Why would you keep it in if is disable ?

**Comment by sural98** [comment]
Also if a particle is disabled then the widths of the rest cannot be adjusted visually (ie. Using slider makes no sense) as the disabled one is perceived as enabled and covers a percentage of the row.

**Comment by sural98** [comment]
@adi8i 
1. Any place in the row.
2. Disabled ones contain ready data so that they can be used in the future.

**Comment by w00fz** [comment]
It is fine as is when disabled. We had these arguments before and decided it's not worth complicating things and giving the disabled states a specific treatment since chances are it will be temporary. 
When you disable a particle you either are temporary doing so or you'll later just delete it.
