### ISSUE TITLE
Uses deprecated APIs in main.js

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [gantry/gantry5#3174]
Hi.
Recently I've been testing with Lighthouse my site made with Grav and Gantry 5, and this shows the following result in main.js:

> 
 Uses deprecated APIs 1 warning found 

`DOM Mutation Events, including DOMSubtreeModified, DOMNodeInserted, DOMNodeRemoved, DOMNodeRemovedFromDocument, DOMNodeInsertedIntoDocument, and DOMCharacterDataModified are deprecated (https://w3c.github.io/uievents/#legacy-event-types) and will be removed. Please use MutationObserver instead.`

**Comment by LMKWeb** [comment]
This issue was also flagged in Chrome dev tools on a Joomla 4 website running Gantry 5.

**Comment by hexplor** [comment]
Looking. Thanks for reporting.

**Comment by hexplor** [comment]
Please check on nightly builds: https://gantry.org/downloads#ci-builds
I have fixed that issue.

**Comment by pmoreno-rodriguez** [comment]
Hi @hexplor 

Good job. I have re-run some tests on my page, updated with the latest changes you have made and there is no trace of any warnings about DOM Mutation Events.
Thanks so much.
