### ISSUE TITLE
FA Icons and menu item text

### ISSUE THREAD

**Issue by wpompen** [gantry/gantry5#318]
I've created two menu's in Joomla (English and Dutch), each assigned to an outline.
The first one (EN) has icons assigned to each item so I started to repeat this with the second menu.
All items went ok except for two, as soon as I added the icons the item's text disappears.

Before adding the icons:
![image](https://cloud.githubusercontent.com/assets/5398592/7703883/1e2d66f6-fe3b-11e4-9981-02078fc82490.png)
After adding the icons:
![image](https://cloud.githubusercontent.com/assets/5398592/7703903/34ce263e-fe3b-11e4-9daa-23f8a3cd225d.png)
All items were created exactly with the same method (as far as I know)
![image](https://cloud.githubusercontent.com/assets/5398592/7703941/85557e7c-fe3b-11e4-8c8b-bff7b094f8d4.png)

**Comment by w00fz** [comment]
Did you try editing the title (pencil icon at the top of the modal) to see if that change gets picked up?

**Comment by wpompen** [comment]
I did, without "effect" ...

What would you say about the option to show/hide text icon (for more "flexibility)?

**Comment by wpompen** [comment]
Update: 
I've deleted /custom/config/menu/mainmenu-nl in order to update it to a change in the Joomla menu. 
The exact same items still have the same problem.

**Comment by wpompen** [comment]
Update, the text also disappears after inserting an image...

**Comment by wpompen** [comment]
Okay, I've found it!
In the file "mainmenu-nl.yaml" (secundair/Dutch menu) I saw some lines with "icon_only: false"
I've added an icon in the yaml file and changed "false" to "true" and it's working now...
... or was, because after saving the menu in the admin page, the values were reset for these two items and I was back to square one.

Does the future foresee a graphical display of these values?
  home:
    id: '548'
    type: component
    link: 'index.php?option=com_content&view=article&id=182'
    target: _self
    dropdown: ''
    width: auto
    class: ''
    icon: 'fa fa-home'
    image: ''
    subtitle: ''
    title: Home
  chiptuning:
    id: '563'
    type: component
    link: 'index.php?option=com_joodb&view=catalog'
    target: _self
    dropdown: ''
    width: auto
    class: ''
    icon: 'fa fa-tachometer'
    image: ''
    subtitle: ''
    title: Chiptuning

Should be:
  home:
    id: '548'
    type: component
    link: 'index.php?option=com_content&view=article&id=182'
    target: _self
    dropdown: ''
    width: auto
    class: ''
    icon: 'fa fa-home'
    image: ''
    subtitle: ''
    title: Home
    **icon_only: false**
  chiptuning:
    id: '563'
    type: component
    link: 'index.php?option=com_joodb&view=catalog'
    target: _self
    dropdown: ''
    width: auto
    class: ''
    icon: 'fa fa-tachometer'
    image: ''
    subtitle: ''
    title: Chiptuning
    **icon_only: false**

**Comment by w00fz** [comment]
I'm wondering if this is a Joomla setting in the menu item? I'm not aware of us having any logic or settings for icon_only.

**Comment by wpompen** [comment]
mmm... It won't be:
![image](https://cloud.githubusercontent.com/assets/5398592/7729832/28b3a392-ff17-11e4-8555-5b00c2c7763c.png)

**Comment by wpompen** [comment]
It was... thank you for your patience and persuading me into investigating further!

**Comment by w00fz** [comment]
No problem at all! So where was it?

**Comment by wpompen** [comment]
"Add Menu Title" had to be "Yes" which is default by the way.
I had changed this earlier to style Joomla's menu...

**Comment by w00fz** [comment]
Ah  I see, well glad it's all sorted now!
