### ISSUE TITLE
Joomla 5.0: debug.css 404 not found

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#3190]
Hi @hexplor 

I noticed the issue with debug.css file error loading with Joomla 5.0

[Root]/media/system/css/debug.css net::ERR_ABORTED 404 (Not Found)

Joomla! 5 moved the debug.css file to media/plg_system_debug/css/debug.css (related to this pull request https://github.com/joomla/joomla-cms/pull/39652) 

For now, Gantry has only specified the debug.css for J3 and J4. https://github.com/gantry/gantry5/commit/eebd1aea2323ff97df8d5d631a90e34c2cbc4555

Could you make a new debug.css location for J5?

Thank you

**Comment by hexplor** [comment]
Unbelievable. It's like fourth time they are changing this file location. Of course I will fix that.

**Comment by hexplor** [comment]
Should be fixed with the commit above. Please check CI Builds in couple minutes: https://gantry.org/downloads#ci-builds
