### ISSUE TITLE
Auto update xml joomla not working

### ISSUE THREAD

**Issue by Tazzios** [gantry/gantry5#3197]
The auto update files do not contain a version but  @version@
http://updates.gantry.org/5.0/joomla/pkg_gantry5.xml 

I`m still at 5.5.15 for that reason.

**Comment by hexplor** [comment]
We were in the middle of the release. Should work now.

**Comment by Tazzios** [comment]
Sorry i thought that i maybe played longer as i never saw the 5.5.16 in the auto update.
I see indeed the 5.5.17 in the auto update from joomla.
