### ISSUE TITLE
Hydrogen-Home and Hydrogen-Default contains different header layout

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#32]
I want to add a logo on the top-left side over the navigation bar. Obviously the logo must be on the same position on every page. Now, I added the logo particle on the header place (on the same templates, *Home* and *Default*).
![logo-position1](https://cloud.githubusercontent.com/assets/3976174/6920229/8f963e70-d7bd-11e4-811c-66053b187154.png)
I notice that the margin-left from the left side of the window is different from **Home** to **Contact pages**.
![logo-position2](https://cloud.githubusercontent.com/assets/3976174/6920268/c10dca0e-d7bd-11e4-8a51-4e5da58c9204.png)
![logo-position3](https://cloud.githubusercontent.com/assets/3976174/6920274/c5069708-d7bd-11e4-8e03-e51aef2e963d.png)
The difference from these pages seems to be an extra div with **g-container** class as you can see on the next 2 screenshots.
![logo-position4](https://cloud.githubusercontent.com/assets/3976174/6920369/2e0cd8f2-d7be-11e4-9fb6-c0b6480e39d2.png)
![logo-position5](https://cloud.githubusercontent.com/assets/3976174/6920374/3386e41c-d7be-11e4-89fb-706e97098fc5.png)

I don't know if this issue cause the displaying problem.

*[Firefox 36.0.4 on Windows 7 x64]*

**Comment by kevlardev** [comment]
I found the issue, the 'home' layout yaml was missing the container reference, so the g-container div wasn't being rendered.
