### ISSUE TITLE
Admin: Upload images, transparent background on trumbs

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#322]
![sin titulo-1](https://cloud.githubusercontent.com/assets/8228538/7710297/32c9df54-fe63-11e4-9a0d-b684cef7f354.jpg)

**Comment by w00fz** [comment]
You can upload images by dragging them from the desktop. We still need to finalize the media picker and there will be an upload button.

**Comment by adi8i** [comment]
@w00fz  he mean the background of first picture i think, but that is a png file, probably a transparent one, and it shows the picture as it is, but i don't see where the problem is :P

**Comment by AbeAlpha** [comment]
yes, if u have a white png u see nothing, for solve: admin.css
```.g5-dialog.g5-dialog-theme-default.g5-modal-filepicker .g5-content .g-files.g-filemode-thumbnails li .g-thumb {
    background-color: transparent;}```

**Comment by AbeAlpha** [comment]
+ remember last dir path (can be awesome)
+ do more bigger the popup or rezizable and remember the state

**Comment by w00fz** [comment]
Yah like said above, the media picker still needs to be finalized, it's just meant to be functional for now but it's not completed, we have other things we want to add to it.

**Comment by w00fz** [comment]
Transparency is now implemented.

![transparency](https://cloud.githubusercontent.com/assets/11734/7741778/368d190e-ff39-11e4-8d30-94f919a1d92d.jpg)

**Comment by AbeAlpha** [comment]
:D op!

**Comment by stevepentler** [comment]
Filestack/Filepicker was converting a logo.png to a .jpg with a black background. 
There's probably a formal way to do it, but I used the following hack in the settings:
` extensions: ['.png', '.jpeg', '.jpg'], extension: ['png']`
This will import a png, jpeg, or jpg and export only a png. 
Note that extension is singular for the export
