### ISSUE TITLE
See off-canvas mobile menu in all @media

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#323]
I wana have the offcanvas in all @media.
I try to ```.hide, body .g-offcanvas-hide {
    display: block;
}``` but the buton do not work -.-'

**Comment by kevlardev** [comment]
Currently the offcanvas is available in all breakpoints if there is a module or particle assigned to it (not counting the mobile menu), its just the mobile menu that is tied to the mobile breakpoints. If the only thing present in the offcanvas position is the mobile menu, then it will be hidden at larger breakpoints.

**Comment by AbeAlpha** [comment]
om dndt try ty :)
And for see the stile of mobile menu in larger breackpoints?

**Comment by kevlardev** [comment]
We don't plan to have the mobile menu in all break points, as its designed specifically to be a target for the main menu to be moved there in mobile breakpoints (as opposed to being a separate menu). However we do plan to add a new side menu particle soon that will allow for having a mobile menu style side menu available in all breakpoints inside the offcanvas panel or within a side column or other location within the layout.

**Comment by AbeAlpha** [comment]
Maybe this can help http://mac81.github.io/pure-drawer/

**Comment by JoomFX** [comment]
Yeah, I really like the Codrops one. It might also give you some ideas for removing the `transform` on `g-page-surround` (which you are already working on ;) )
