### ISSUE TITLE
Markup/Twig Question

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#325]
hey @w00fz @mahagr ,

me and @alisamii are trying to create the following markup:

```
<div class="page-top-wrapper">
	<div class="header-nav-wrapper">
		<header id="g-header">...</header>
		<section id="g-navigation">...</section>
	</div>
	<section id="g-showcase">...</section>
</div>
```

The only way I could think of to achieve this, was to set the `header`, `navigation` and `showcase` in the `page.html.twig` file and wrap them with the DIVs, here's an example:

```
            <div class="page-top-wrapper">
                <div class="header-nav-wrapper">
                    {{ page_header|raw }}
                    {{ page_navigation|raw }}
                </div>
                {{ page_showcase|raw }}
            </div>
            {{ page_top|raw }}
            {{ page_layout|raw }}
            {{ page_bottom|raw }}
```

But the problem is with the code that says that these positions should not be rendered twice. It works just fine if you want to set only one section, for example `navigation`. So the following code works just fine:

```
{%- set page_layout %}
    {% block page_layout %}
        {% for segment in gantry.theme.segments if segment.type != 'offcanvas' and 'navigation' not in segment.title|lower %}
            {% include '@nucleus/layout/' ~ segment.type ~ '.html.twig' with { 'segments':segment.children } %}
        {% endfor %}
    {% endblock %}
{% endset %}
```

But how would I add the `header` and the `showcase` there? I tried with multiple `and` operands, I tried with brackets, I tried to combine then, I tried using [this](http://stackoverflow.com/questions/8388537/twig-if-with-multiple-conditions), but I really cannot figure it out.

So, the questions are:

1. How can we exclude multiple sections from being rendered twice? What is the correct code for `{%- set page_layout %}`?

2. Is there a better approach to generate the above markup?

Thank you in advance ;)

**Comment by JoomFX** [comment]
And just in case you need it, so you can do a quick test, here's the whole `page.html.twig`:


```
{%- do gantry.theme.setLayout() -%}

{%- set content %}
    {% block content %}
    {% endblock %}
{% endset -%}

{%- set offcanvas = null -%}
{%- for segment in gantry.theme.segments if segment.type == 'offcanvas' %}
    {%- set offcanvas = segment -%}
{% endfor -%}

{%- set page_offcanvas %}
    {% block page_offcanvas %}
        {% if offcanvas %}
            {% include '@nucleus/layout/' ~ offcanvas.type ~ '.html.twig' with { 'segment': offcanvas } -%}
        {% endif %}
    {% endblock %}
{% endset %}

{% set header = null %}
{%- for segment in gantry.theme.segments if 'header' in segment.title|lower %}
    {% set header = segment %}
{% endfor %}

{%- set page_header %}
    {% block page_header %}
        {% if header %}
            {% include '@nucleus/layout/' ~ header.type ~ '.html.twig' with { 'segment':header, 'segments': header.children } %}
        {% endif %}
    {% endblock %}
{% endset %}

{% set navigation = null %}
{%- for segment in gantry.theme.segments if 'navigation' in segment.title|lower %}
    {% set navigation = segment %}
{% endfor %}

{%- set page_navigation %}
    {% block page_navigation %}
        {% if navigation %}
            {% include '@nucleus/layout/' ~ navigation.type ~ '.html.twig' with { 'segment':navigation, 'segments': navigation.children } %}
        {% endif %}
    {% endblock %}
{% endset %}

{% set showcase = null %}
{%- for segment in gantry.theme.segments if 'showcase' in segment.title|lower %}
    {% set showcase = segment %}
{% endfor %}

{%- set page_showcase %}
    {% block page_showcase %}
        {% if showcase %}
            {% include '@nucleus/layout/' ~ showcase.type ~ '.html.twig' with { 'segment':showcase, 'segments': showcase.children } %}
        {% endif %}
    {% endblock %}
{% endset %}

{%- set page_offcanvas = page_offcanvas|trim ?: '' %}
{% set page_header = page_header|trim ?: '' %}
{% set page_navigation = page_navigation|trim ?: '' %}
{% set page_header = page_showcase|trim ?: '' %}
{%- set offcanvas_position = page_offcanvas ? offcanvas.attributes.position|default('g-offcanvas-left') : '' -%}

{%- set page_layout %}
    {% block page_layout %}
        {% for segment in gantry.theme.segments if segment.type != 'offcanvas' and 'header' not in segment.title|lower %}
            {% include '@nucleus/layout/' ~ segment.type ~ '.html.twig' with { 'segments':segment.children } %}
        {% endfor %}
    {% endblock %}
{% endset %}

{%- set page_top %}
    {% block page_top %}
    {% endblock %}
{% endset -%}

{%- set page_bottom %}
    {% block page_bottom %}
        {{ gantry.scripts('footer')|join("\n    ")|raw }}
    {% endblock %}
{% endset -%}

{%- block page -%}
<!DOCTYPE {{ gantry.page.doctype|default('html')|raw }}>
<html{{ gantry.page.htmlAttributes|raw }}>
    {% block page_head -%}
        {% include 'partials/page_head.html.twig' %}
    {%- endblock %}
    {% block page_body -%}
    <body{{ gantry.page.bodyAttributes({'class': [offcanvas_position, 'g-style-' ~ gantry.theme.preset]})|raw }}>
        {{ page_offcanvas|raw }}
        <div id="g-page-surround" class="{{ gantry.config.get('styles.base.layout')|default('g-fullwidth') }}">
            {% if page_offcanvas|trim %}
            <div class="g-offcanvas-hide g-offcanvas-toggle" data-offcanvas-toggle><i class="fa fa-fw fa-bars"></i></div>
            {% endif %}
            <div class="page-top-wrapper">
                <div class="header-nav-wrapper">
                    {{ page_header|raw }}
                    {{ page_navigation|raw }}
                </div>
                {{ page_showcase|raw }}
            </div>
            {{ page_top|raw }}
            {{ page_layout|raw }}
            {{ page_bottom|raw }}
        </div>
        <script type="text/javascript" src="{{ url('gantry-assets://js/main.js') }}"></script>
    </body>
    {%- endblock %}

</html>
{% endblock -%}
{% do gantry.platform.finalize() -%}

```

**Comment by alisamii** [comment]
I'll add to that, for me, the idea is to be able to create a layout where the showcase can be positioned such that it has a full-width background image and the header and navigation can float on top of the showcase as in this design:

**Home Theme**
![home-theme](https://cloud.githubusercontent.com/assets/1498512/7725219/c79ef37c-fef8-11e4-8cf3-bcd3cd7c0984.png)

**Default Theme**
![default-theme](https://cloud.githubusercontent.com/assets/1498512/7725227/eed31554-fef8-11e4-9758-ea2a24d62959.png)

As you can see, the same basic concept is applied in both the home layout and the default layout, where the language switcher is placed in the `g-header` and the navigation in the `g-navigation` and then the `g-showcase` contains the background image full-width and on the home page can be configured to contain a centred particle (the search box in the above screenshots, for example).

**Comment by adi8i** [comment]
In first picture you can use a section, lets say `showcase`. 

First you need `3 rows`, on the first row you have `language switch` on second row you have `menu particle` on third `row` you have `search box`. 

Now you add a background to `#g-showcase`, the background will be full width like in your picture. Or if it is not you can adjust `g-content` 

You will need to customize `menu particle` and `modules`, add a transparent background and so on...

Guys i don't see where the trouble is ... :)

**Comment by adi8i** [comment]
Nah, because you have a menu, you should use `header` section

**Comment by alisamii** [comment]
@adi8i You are suggesting not to use the `g-header` and `g-navigation` layout sections and create three rows within `g-showcase` to accomplish that.

Although that is a possible solution, I think the ability to *nest* sections is valuable.

![screen 20shot 20on 202015-05-20 20at 2014 3a31 3a03](https://cloud.githubusercontent.com/assets/1498512/7725761/c27780ee-fefd-11e4-8403-7c09bffd9936.png)

In the above screenshot, I think it would be good to be able to wrap the `header`, `navigation` and `showcase` in a parent.

**Comment by adi8i** [comment]
Yea i've tried that too few weeks ago, should be possible in `layout` file, but no idea how.

**Comment by alisamii** [comment]
Also, as G5 is currently set up, navigation is not inside the header. It is a separate section.

**Comment by JoomFX** [comment]
@adi8i as you know with websites and web developement one thing can be achieved in different ways.
yes, your suggestion is pretty good.

but my questions are still valid. they are regarding the Markup:

1. How can we exclude multiple sections from being rendered twice? What is the correct code for `{%- set page_layout %}`?
2. Is there a better approach to generate the above markup?

**Comment by alisamii** [comment]
@JoomFX well articulated...better than me :)

**Comment by gyvermac** [comment]
@JoomFX I hope you'll get an answer because I'll certainly have the same problem shortly.
Right now I managed to fix the menu putting the navigation section out of the ""g-page-surround" DIV in the page.html.twig. But it could be useful to fix the header too. And in this case I'll have to exclude 2 sections.

**Comment by w00fz** [comment]
This can be done entirely by creating a custom layout preset. Took me a couple minutes and I come up with this:

``` .yaml
preset:
  image: gantry-admin://images/layouts/default.png

layout:
  container:
    1:
     - top-wrapper 100:
        header:
          container:
            - spacer

        navigation:
          container:
            - [particle-logo 20, particle-menu 80]

  showcase:
    container:
      - spacer

  feature:
    container:
      - spacer

  main:
    container:
      - system-messages
      - pagecontent

  footer:
    container:
      - spacer

  debug:
    container:
      - spacer

  offcanvas:
    - particle-mobile-menu
```

which on frontend renders like this:

![nested](https://cloud.githubusercontent.com/assets/11734/7732048/befa050a-fed9-11e4-9c16-de05113dc0f3.jpg)

---

The above structure is the simplified, development mode, way of writing layouts but it's good just for starting point because it is very limited. Once you import this preset on the admin and you save it, I'd suggest copying the saved version and use that as a raference. It will make it easier to add attributes to that top level `g-container` (like `id` `class` etc).

**Comment by JoomFX** [comment]
@w00fz thanks for that :)

would you please give me some more details about what you wrote (development version vs full version). I'll explain what I mean... I do know that you use the "Full" Layout version (in the `layout` folder in the template folder) but I'm trying to understand the benefits of that. If I have to be honest, I was planning to use the "development" (simplified) version for my templates and the main reason is that the customer can easily add a new section, while this is not really doable in the "Full" layout.

Yes, the "Full" layout keeps much more details, for example custom CSS/JS, Tag Attributes, Sizes... even Particle Settings and content. It might (not really) be a replacement of the Quickstart Package. Why I say "not really" - because if the Template developer builds the Template using the [G5 Particle Module](https://github.com/gantry/gantry5/issues/163) all you would need to have in the Layout file is the Sections and the Module Positions that come by default (for which the development version is more than enough). And if you are looking for the efect of the Quickstart Package by just installing the Template from the Extension Manager, then the Templates will still need to be build with "a separate configuration for each page" leading to approx 20 Configurations/Outlines per Template (what about multilingual websites).

I hope you understand what I mean. So what is the benefit of using the "Full" layout?

And again, thanks in advance Djamil ;)

**Comment by w00fz** [comment]
The 'developer' version is a sandbox to get you on route with the base of a structure. It is impossible to rely on just that because it's missing all the attributes that customize a page (particles settings, block values, section classes, disabled particles). There's nothing but a mere basic structure that you can load.

You can use development version as much as you like but in the end it will always be stored in the full version, there is no other way around that, the LM is a very complex part of Gantry and there is a lot going on with it, we need a very detailed structure to be able to store all that data. 

Initially this was JSON (and it still gets converted to that for the JavaScript in admin), now we are storing it as YAML and you can still manually edit it. Yes it's not easy to the eye to read as it is the 'developer' version, but that's because the structure is actually complex.

**Comment by JoomFX** [comment]
Many thanks again for taking the time to explain :)

If you say that the developer must go with the "Full" version, well I guess I will go with the "Full" version :D

And just to confirm - once my template is "ready enough" I just need to copy the "Full" YAML file from `/template_name/custom/config/*layout*` to `/template_name/layouts`, right?

**Comment by w00fz** [comment]
Yes that is the best way to create presets.

**Comment by alisamii** [comment]
@w00fz 
I tried to nest the nested sections in another wrapper like this
Original layout
```
layout:
  1:
   - top-wrapper 100:
      header:
        container:
          - spacer

      navigation:
        container:
          - [particle-logo 20, particle-menu 80]

      showcase:
        container:
          - spacer
```
New layout
```
layout:
  1:
   - top-wrapper 100:
      2:
        - inner-wrapper 100:
          header:
            container:
              - spacer

          navigation:
            container:
              - [particle-logo 20, particle-menu 80]

      showcase:
        container:
          - spacer
```
The resulting structure would be something like this:
```
<div class="top-wrapper">
  <div class="inner-wrapper">
    <div class="g-header"></div>
    <div class="g-navigation"></div>
  </div>
  <div class="g-showcase"></div>
</div>
```
so, effectively, I need a wrapper that contains another wrapper and showcase
and the inner wrapper contains header and nav
but it borks with a 500 error

Is there a way to do this in yaml, and if not, how can it be done in twig?

**Comment by JoomFX** [comment]
I also tried with a bit different syntax which does not generate an error, but also does not work properly. 

```
layout:
  0:
   - top-wrapper 100:
   
      1:
        - inner-wrapper 100:
          header:
            container:
              - spacer

          navigation:
            container:
              - [particle-logo 20, particle-menu 80]

      showcase:
        container:
          - spacer

  feature:
    container:
      - spacer
```

It does not generate the desired markup and the Layout Manager does not really look good (duplicate "Showcase" section, duplicate particles squized half-size even though they are 100%, etc):

![alt](http://i.imgur.com/jWE4Skt.png)

@w00fz I would really like to ask you to answer the original question as well :)

"How can we exclude multiple sections from being rendered twice? What is the correct code for `{%- set page_layout %}` ?"
