### ISSUE TITLE
Arrows icons from helium menu aren't displayed with fontawesome 6

### ISSUE THREAD

**Issue by xillibit** [gantry/gantry5#3253]
I have a helium template but arrows icons in the menu on helium template aren't displayed anymore since update from Joomla! 4.4.4 to Joomla! 5.1

![image](https://github.com/gantry/gantry5/assets/876395/e057cc37-90f4-41de-839e-9e678a17500f)

- Gantry 5.5.18
- Helium 5.5.18
- Fontawesome 6.5.1
- Joomla! 5.1

How to fix that ?

**Comment by pablop76** [comment]
Gantry5 update
![g5-update](https://github.com/gantry/gantry5/assets/24696716/d1d6d706-07f4-4407-b088-3bc9fa9296c3)

**Comment by hexplor** [comment]
How did you add those icons? i'm going to check that.

**Comment by hexplor** [comment]
Hey @xillibit, can you please test CI build if it has been fixed for you? https://gantry.org/downloads

**Comment by xillibit** [comment]
> How did you add those icons? i'm going to check that.

I don't have added, it's in the menu when there are subitems 
![Capture d'écran 2024-05-24 231251](https://github.com/gantry/gantry5/assets/876395/38a598dc-94ee-44b1-85ba-07ab0a889e64)

**Comment by hexplor** [comment]
It should be fixed in 5.5.19.

**Comment by xillibit** [comment]
I have the same issue on another site which is on Joomla! 4.4.5 which use xenon template since i have made the update to gantry 5.5.19. So i have 2 sites where i have the same issue

**Comment by xillibit** [comment]
I have updated the site to Joomla! 5.2.1 and now with gantry 5.5.19 the arrows icons are right displayed

**Comment by suule19** [comment]
![20250106_081312](https://github.com/user-attachments/assets/b8ca9784-6f91-44c9-9c62-15551d444c7a)
Solve this
