### ISSUE TITLE
Fonts ending with unit (pt, px, em) don't get treated as strings but colors/unit

### ISSUE THREAD

**Issue by elanorpam** [gantry/gantry5#326]
The google webfont Aguafina Script won't load on the front-end unless you select both charsets-- Latin *and* Latin Extended. Took me a while to figure this out, and I assumed the font-picker itself was not working somehow. I'm not sure if other fonts suffer from this same issue.

**Comment by w00fz** [comment]
Hi @elanorpam,
I've seen this issue before and I've been trying to hunt it down for quite sometime. Finally I found where this was happening and managed to fix it.

Will be available in next release, thank you.
