### ISSUE TITLE
atoms are not loaded

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#329]
@alisamii tried to implement an atom, we've talked on chat. But for me seems that atoms are not loaded anywhere, can you check this please, i am not sure how should work. :)

@w00fz  @mahagr

**Comment by JoomFX** [comment]
yes, I also do not see the Google Analytics Atom being loaded anywhere.

**Comment by adi8i** [comment]
related to #330 i will close this one :)

**Comment by mahagr** [comment]
Google analytics only loads if it's added to your layouts AND if you have entered the key.
