### ISSUE TITLE
Root not recognised by Compiler

### ISSUE THREAD

**Issue by gospelpowered** [gantry/gantry5#338]
Hey guys, 

My web hosting root is 'home2' and i can't seem to save my Gantry settings or Recompile. I get the attached error. It seems the compiler is looking for its code in 'home' whereas the root is actually 'home2'. It's not recognising its 'home2' and is somehow assuming 'home'.

![root issue](https://cloud.githubusercontent.com/assets/12219933/7774550/ddaa314e-00de-11e5-9b39-d91bb90dc3af.jpeg)

**Comment by mahagr** [comment]
The bug wasn't about the home directory (which comes from Joomla btw).
