### ISSUE TITLE
Submenu Columns not work

### ISSUE THREAD

**Issue by dragethy** [gantry/gantry5#34]
Submenus in more than 1 Column is not working. See attached screenshots. Allso a problem with the z-index and the nextend smart slider.

![backend](https://cloud.githubusercontent.com/assets/11740679/6924004/c91f4642-d7d5-11e4-94c5-e87439f9d471.png)
![frontend](https://cloud.githubusercontent.com/assets/11740679/6924003/c91fe958-d7d5-11e4-8eb5-63b1a2440686.png)

**Comment by w00fz** [comment]
This was fixed in #9

**Comment by w00fz** [comment]
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!
