### ISSUE TITLE
Make layouts to override content from Base Outline

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#340]
Right now there is no way to share particles between the layouts. If you have n+1 layouts and you want to add a new particle to the header section in all of them, you need to modify every single layout to add the particle and set all the settings for it.

My proposal is to create an option to each section:

Inherit Section Content 
(Select how you would like to inherit the section particles and positions from Base Outline. You can either choose to insert all the rows from the Base Outline or to decide to ignore all of them.)

* Insert Before
* Insert After
* Ignore

**Comment by JoomFX** [comment]
Very nice :)

**Comment by hugoaf** [comment]
Really cool and time saving feature.
Do you know what can be an addition to this feature, is to show "where my override is" an icon or something in the Base Outline particle settings to identify if that particle is being overridden somewhere else. In that way you would quickly know if you are modifying the correct spot. Something like this..
![where-is-my-override](https://cloud.githubusercontent.com/assets/8611472/7785296/e5c6c27e-013e-11e5-8635-106f3be813c8.jpg)

**Comment by WebTread** [comment]
Yeah a very good idea @mahagr. And I agree with @hugoaf that there should be some way to get an eagle eye view to see what is attached where and even possibly be able to disconnect them. Like some kind of Mission Control Center in the Base Outline.

**Comment by mahagr** [comment]
I would have created a new issue on the idea, but yes, I do like it.

**Comment by federone** [comment]
i think, for example to have a new tab, named "Global Settings" where we can add atoms .... which will be loaded on all pages ... like it is on default joomla templates, when you enable some params, it will be enabled on all pages ...

**Comment by w00fz** [comment]
Have a look here guys https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel

Collection of G5 things we plan to do

**Comment by w00fz** [comment]
This is now implemented in the develop branch, by our Inheritance effort. What matias proposed has not been implemented in that way, the approach is very different but still tackles the Inheritance problem.

There isn't any insert before/after, there is just Inherit with the ability to fine tune what to inherit, like in the case of a section you can pick either/or children and attributes.
