### ISSUE TITLE
Add production / development toggle

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#341]
Add toggle to turn automatic recompile on and off, otherwise people won't find the option (from system plugin) and the new feature will slow down sites for everyone.

**Comment by w00fz** [comment]
This is all hooked up now, just need to adjust the controller to go through the platform data and store the value. I'm passing the ball to you @mahagr.

**Comment by mahagr** [comment]
@w00fz There's something wrong with the feature still. I'm not getting the success message to work and the title gets into default. See Json\Devprod controller for more info.
