### ISSUE TITLE
Error when clicking on Assignments

### ISSUE THREAD

**Issue by capeinfo** [gantry/gantry5#342]
I get the following whenever I click on the Assignments link:

 Whoops \ Exception \ ErrorException (E_WARNING)
str_repeat(): Second argument has to be greater than or equal to 0 

I have Gantry5 and Hydrogen v5.0.0-rc.2.  Joomla! 3.4.1 and PHP 5.4.39-0+deb7u2

**Comment by mahagr** [comment]
Already fixed for RC3. It's related to a small issue in your database; go to phpmyadmin and look at menu items with level=0, there should be only one and it shouldn't be in any menu.
