### ISSUE TITLE
Hydrogen Menu doesn't work with Falang translations

### ISSUE THREAD

**Issue by Designjunkie** [gantry/gantry5#343]
When I use the menu in the Hydrogen theme, it works fine, but now when I translate everything with Falang, the translations don't show up in the menu (when language changed) and the menu items switch position random?

**Comment by alisamii** [comment]
Falang does not follow standard joomla conventions on translations and so will not work with gantry as it is right now.

Although I'm not a fan of how joomla handles translations, I recommend that you not use falang. A more joomla-like translator is Rosetta, by  the makers of sh404sef. I suggest you try that as I don't believe that gantry will diverge from joomla conventions to accommodate a non-standard component such as falang.

**Comment by Designjunkie** [comment]
ok, I'll try this then :)

**Comment by Designjunkie** [comment]
When I search for this extension(Rosetta), I can't find it on the Joomla site?

**Comment by Designjunkie** [comment]
Already found it, it's called Josetta :p Thnx

**Comment by mahagr** [comment]
Gantry will support Joomla way of doing translations, others may work or not. We will also have our own internal translation mechanism for particles, but on everything else we will likely just follow Joomla way or let it to do it for us.

**Comment by bernhard1701** [comment]
Had (and still have) problem with Gantry 5 and FaLang on one site (only!) with random menues.
All other sites (about 10) are running fine

**Comment by mahagr** [comment]
Have you modified menus from that site from Gantry menu manager?

**Comment by bernhard1701** [comment]
Yes i did - and as you ask this now, I think this (problem-) site was the only one I did so ;)

**Comment by mahagr** [comment]
I believe that the issue might fix itself if you just save the menu. If that doesn't work, you may try to remove (with backup) all files in `custom/menu` inside your template. That will remove any custom menu settings, but may allow you to fix the issue and maybe even restore the original layout without messing up translations.

**Comment by bernhard1701** [comment]
@mahagr: you are the man! Thank you, worked perfect ;)
