### ISSUE TITLE
Add "module picker" to "module instance" particle

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#345]
When adding a module in the menu manager it utilises a nice "module picker" to present the possible joomla module that you can use. When you use a "module instance" particle in a layout it just has a field where you have to type in the Joomla module ID. It would be nice if this field could use the same "module picker" as the menu has.
![2015-05-23_14-54-56](https://cloud.githubusercontent.com/assets/11683218/7784383/f51dd6dc-015b-11e5-9a02-732a6e2079f3.png)
![2015-05-23_14-55-57](https://cloud.githubusercontent.com/assets/11683218/7784385/f868a39e-015b-11e5-88cd-6d3962a3050e.png)

**Comment by w00fz** [comment]
Ehe we already have this implemented in the `particle` branch.

![pick a module](https://cloud.githubusercontent.com/assets/11734/7785438/add977ca-0144-11e5-9416-53dfcef71016.jpg)

**Comment by marktaylor46** [comment]
Yes it's in RC3 now this issue can be closed.
