### ISSUE TITLE
Page class on a joomla menu item does not render on body tag

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#346]
If you add a "page class" on the "page display" tab of a menu item in joomla menu manager this is not rendered on the html body tag.

**Comment by Bokelmann** [comment]
on that topic ... I see a class "no-task" that does never change ... even if I edit articles. Is that something like $input->getCmd('task') in Joomla?

**Comment by mahagr** [comment]
In joomla pageclass_sfx is used for styling the main component output. It will not be applied to the rest of the page. As our component didn't have anything to output, the class was useless.

The situation has changed in RC3, as now we do have optional main component output.
