### ISSUE TITLE
Extend Menu Item URL

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#348]
hi,

In Gantry Menu can you please add text option after menu item url?
I mean, for example, there is item url "index.php?option=com_content&view=category", i want to add "#go_to_bottom" text after url. So on frontpage url becomes "domain.com/blog/category#go_to_bottom",
i'm sure it will be very easy to add that option in gantry menu.
here is screenshot what i mean:
![extend_url](https://cloud.githubusercontent.com/assets/1756964/7788531/25787faa-024f-11e5-8cdd-b184c5f11723.jpg)

i guess it can be easilly done in "root/media/gantry5/engines/nucleus/particles/menu.html.twig" and its YAML files

thank you very much

**Comment by w00fz** [comment]
This is actually a good point. We'll look into it.

Thank you.
