### ISSUE TITLE
Extend Documentation info about adding new PHP funcs

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#351]
Hi,

how we can add and use in particles own php funcs?

for example we want to add Mobile-Detect function - https://github.com/serbanghita/Mobile-Detect - please add info how we can achieve it.

as i understand in "templates/g5_hydrogen/includes/theme.php" at bottom we have to add it like this:
```
class Simple_Class {
	public $custom_variable = 'this is a test';
	public function displayVariable() {
		echo $this->custom_variable;
	}
}
$gantry['Simple_Class'] = new Simple_Class();

require_once dirname(__FILE__).'/Mobile_Detect.php';
$gantry['Mobile_Detect'] = new Mobile_Detect();
```

and in particle/atom twig files we must call them like this:
```
{{ gantry.Simple_Class.displayVariable() }}
{%- if not gantry.Mobile_Detect.isMobile() -%}
	THIS DEVICE IS NOT A MOBILE
{%- endif -%}
```

Please add such info in docs, about how we can do this
thank you very much :)

**Comment by fernandopro** [comment]
Please!!!
I'm also very interested.

**Comment by FrugalGeek** [comment]
Hello,

Great suggestion. Touching base with the team to see how best to approach this. Thanks!

**Comment by mahagr** [comment]
Right now your solution for themes is correct. You can add class into DI container and use it from twig.

Later we may want to implement a better solution for individual particles.

**Comment by FrugalGeek** [comment]
http://docs.gantry.org/gantry5/advanced/php-functions

We are working on a more permanent solution for users of existing themes. This document will be expanded on and fleshed out further soon. Thanks for the suggestion.
