### ISSUE TITLE
Create single SASS file that imports everything

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#352]
People have hard time figuring out which files they need to import in order to get all the variables and mixins defined in the theme.

We need to have a single file that can be imported instead of requiring them to find a list of files from the filesystem or documentation.

**Comment by JoomFX** [comment]
@mahagr my tests showed that we might already have such file :)
It is `g5_hydrogen/scss/hydrogen.scss`

So the following code in `custom.scss` seems to do the job:

```
@import "../scss/hydrogen";
```

**Comment by kevlardev** [comment]
Added a new dependencies scss file that includes all vendor, nucleus, and theme specific mixins and variables for easy import. d17ee574ca8eff39c4e2b019ca86b04a13839251

**Comment by alisamii** [comment]
Hi @kevlardev 

I noticed that at the end of `themes/hydrogen/common/scss/hydrogen.scss` in https://github.com/gantry/gantry5/commit/d17ee574ca8eff39c4e2b019ca86b04a13839251 the `BREAKPOINTS` are still there.

```
// BREAKPOINTS
@import "nucleus/theme/breakpoints/base";
````

Are the breakpoints theme-dependent? I would assume that they are part of the core `nucleus` and should be imported/available in all themes.

**Comment by mahagr** [comment]
They are core, but as they are configurable we have them in the main css file.
