### ISSUE TITLE
g-container render inside g-main

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#354]
As you can see in the picture when you use main + one or two sidebar will result in this:

![home](https://cloud.githubusercontent.com/assets/9744973/7789805/664064e4-0277-11e5-9f97-aa5f3df7ac36.png)

The problem is that `g-container` class will be rendered inside `g-main` .

![capture](https://cloud.githubusercontent.com/assets/9744973/7789813/adde973a-0277-11e5-82a2-555f93f01452.PNG)

So this code seems to be wrong interpreted: 
```
container:
    1:
      - sidebar 20:
         - position-sidebar
      - main 80:
          - position-breadcrumbs
          - system-messages
          - pagecontent
```

**Comment by JoomFX** [comment]
I also reproduced the above with this Layout

```

```

**Comment by beamaria** [comment]
![sidebar](https://cloud.githubusercontent.com/assets/11693902/7811307/b53ef604-03a9-11e5-964d-e0e3825c6199.jpg)
Same problem here with default layout set to "two columns, right sidebar"
See the attached image:

**Comment by adi8i** [comment]
This should solve this bug temporary 
```
#g-main {
    .g-container {
         width: 0;
}
}
```

**Comment by beamaria** [comment]
mmmmH, doesn't work; this is the result


![senza titolo](https://cloud.githubusercontent.com/assets/11693902/7813062/f77851f6-03b7-11e5-978c-716402f6307c.jpg)

**Comment by beamaria** [comment]
I copied it in my custom/scss/custom.scss...

**Comment by adi8i** [comment]
then is `width: 100%` :)

**Comment by beamaria** [comment]
Yeah, definitely 100%!! Now it works :-))

**Comment by mahagr** [comment]
Where is the bad layout? @kevlardev this might be something to you.

**Comment by adi8i** [comment]
@mahagr `.g-container` is rendered inside `g-main` that's the issue, i think this is for @w00fz :D .

**Comment by w00fz** [comment]
Kevin is looking into this

**Comment by kevlardev** [comment]
@mahagr it seems like this was introduced with the 'Keep the current particles while changing preset' option. The layout yaml's are all correct. However when you start changing from layout to layout and saving with that particles option checked, all of the layouts start having strange behaviors, including a .g-container being rendered inside of main (which is not present in any of the yaml files those layouts are based on). With that option unchecked and setting up the layouts traditionally the problem disappears. So it seems there is something strange going on with how thats being handled

**Comment by adi8i** [comment]
Main section with 2 sidebars, will render a bit different than before on back-end, for me is ok, i am just saying :). I've noticed this change today.

![1111](https://cloud.githubusercontent.com/assets/9744973/8024003/27b6d946-0d2c-11e5-87ac-53944feeeac0.PNG)

**Comment by w00fz** [comment]
Yah you can now set is, classes and tag attributes to the container that wraps main and sidebars. We are also finishing implementing boxed/full width. This should fix the issue, the PRs for boxed/full width and also add new options for that wrapper.
Stay tuned.

**Comment by mahagr** [comment]
Please test with latest CI build and reopen if it isn't fixed. Already broken layouts may still be broken, though..
