### ISSUE TITLE
Deleted positions not removed from Module Manager

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#357]
*Copy/Paste from Gitter*

I think there was an issue for this, but I cannot find it.
Anyway, just want to make sure you are aware of this issue - when you add a module position and save the layout, this module position appears in the Module Manager as a choice under the "Positions" dropdown. So far so good. But then if you go to to the LM and delete the position, it does not get removed from the Module Manager
I see that the templateDetails.xml file is automatically updated when you add a module position. So it needs to be removed from there if it is deleted in the LM.

**Comment by mahagr** [comment]
Positions in templateDetails.xml get build from scratch every time you save layout.

Basically Gantry goes through of every layout you have set in outlines and builds an array of positions based on that.

Not sure how it can result of extra items as leftovers, but will look into it.

**Comment by w00fz** [comment]
Oh, perhaps you have another position with the same key but in a different Outline?

**Comment by JoomFX** [comment]
Thanks guys. It actually works fine. If you create a module position in the LM and then delete it, it will get removed from `templateDetails.xml` :)

I will explain where my confusion came from and the scenarion when you see module positions not being removed (just to say, it is not a bug, it is as it should be).....

So, I was building a new YAML layout. I added a new section that contains 3 module positions:

```
last:
  container:
    - [position-last-a 33.3,position-last-b 33.3,position-last-c 33.3]
```

Then I did some things in the LM, saved the preset several times, etc.
Then I decided that I no longer want this section (`last`) so I removed it from the YAML files.
I refreshed the LM and the section together with the 3 module positions were gone. But they were still present in the `templateDetails.xml` file. So I deleted them manually from the file, saved the preset in LM but they appeared again :O

Then I realized that the old version of my YAML preset in cached in `g5_hydrogen/custom/config/20/layout.yaml`. Once I deleted this file and clicked on Save in the LM, the 3 module positions were no longer added to `templateDetails.xml` ;)

**Comment by mahagr** [comment]
Yup, presets aren't used to create the positions. You can have a hundred positions in your presets, but as long as you aren't using them as layouts, you will not see those in Joomla.

Which is great, as you don't want to get flooded on something you do not use. :)
