### ISSUE TITLE
Users should be able to add their own classes to the <body> tag

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#359]
There should be easy way to add custom classes to the `<body>` tag

**Comment by alisamii** [comment]
:+1:

And the classes should be able to be added in such a way that they can be associated with layouts and maybe also outlines.

![layouts](https://cloud.githubusercontent.com/assets/1498512/7816931/9fccaaf0-03d1-11e5-8f97-39516ebe4be7.png)

**Comment by axel-rank** [comment]
Yes, just like in Gantry 4 Admin . Wonder, why this feature is dropped in Gantry 5, though you can configure a lot.

**Comment by w00fz** [comment]
Yes this has been discussed and will happen. At the moment the only way to achieve this is through `page.html.twig` override which is not ideal, we know. 

That said, there are PLENTY of other classnames rendered in the body that you can use for targeting a page so there is a workaround here.

**Comment by newkind** [comment]
Yah, but this can be necessary for the WP releases. In Gantry4 you had a pagesuffix feature in Joomla which was adding `<body>` classes based on the assigned menu item. In WordPress I had a Page Suffix gizmo which basicaly was a text input where I could define extra body classes on a per override level. This was crucial for the consistent styling between WP and Joomla ie. to the Front Page I had to add `-home-dec15` and to the Contact Us page `menu-contact-us`. Not sure how you guys are doing styling in Callisto but I might need a possibility to add `<body>` classes on a per configuration basis for my WP releases.

**Comment by koteva** [comment]
I agree, this is a feature that has to be added to Gantry 5

**Comment by w00fz** [comment]
With Page Settings Feature (https://github.com/gantry/gantry5/tree/feature/page-settings) this is now possible.

**Comment by newkind** [comment]
It's still going to respect the platform body classes right ? :)

**Comment by adi8i** [comment]
But you can add classes to body in config folder.

**Comment by w00fz** [comment]
Page Settings classes for body are only additional. All class names collected from elsewhere, outline, platform, menu, etc, are still kept and will show with the custom ones.

// Djamil Legato // From iPhone //
