### ISSUE TITLE
Admin styling should adapt to the user admin color scheme

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#360]
Gantry5 admin should adjust it's colors to the color scheme of the current user

**Comment by w00fz** [comment]
We have customizable colors for admin. prime is different than joomla, there are variables for that I think you can hook that up easily 

// Djamil Legato // From iPhone //

**Comment by newkind** [comment]
The thing is that the admin css is now pre-compiled, it should compile on the fly to support this.

**Comment by w00fz** [comment]
Unfortunately we cannot have admin SCSS being recompiled via PHP, I guess you need to do it yourself in a `wordpress.css` specific file and use that color scheme to fix it, if you really want :)

**Comment by mahagr** [comment]
Compiling admin template is actually something we have already talked of. Looks like that a few others like @JoomFX would like to customize admin colors and styling for their template.

**Comment by w00fz** [comment]
Until the PHP compiler has support for SASS 3.3/3.4 we really can't.

**Comment by mahagr** [comment]
Which feature we are using in there? Maybe we could just do some subset, though...

**Comment by newkind** [comment]
Fixed in https://github.com/gantry/gantry5/commit/a744bdb00799bd1db35c66ff3d0cdaab61c2b711
