### ISSUE TITLE
Eagle eye view/manager for overrides

### ISSUE THREAD

**Issue by hugoaf** [gantry/gantry5#361]
This is a feature request extracted form #340 ...

to show "where my override is" an icon or something in the Base Outline particle settings to identify if that particle is being overridden somewhere else. In that way you would quickly know if you are modifying the correct spot. Something like this:

![where-is-my-override](https://cloud.githubusercontent.com/assets/8611472/7830060/7771d158-03fd-11e5-9ae8-9594f9d6a49e.jpg)

And as suggested by @WebTread:
>there should be some way to get an eagle eye view to see what is attached where and even possibly be able to disconnect them. Like some kind of Mission Control Center in the Base Outline.

**Comment by w00fz** [comment]
This implementation is now redundant with the Inheritance effort. When Inheriting a particle you will get details about what particle of what outline you are inheriting from.
