### ISSUE TITLE
"apply & save" on item popup not working.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#364]
This is best illustrated through example in callisto but it happens elsewhere do
1. callisto - home outline on layout tab
2. click settings on "FP Maincontent" contentlist particle
3. click on any of the items within to get their popup setting
4. change the details in the item and then click on "apply & save" in that popup
5. Now go back into the item and you will see that the settings have not been saved. If instead you just use "apply" in the item settings and then click "apply and save" on the particle settings then this does work,
![2015-05-27_10-56-35](https://cloud.githubusercontent.com/assets/11683218/7833629/13b9be7e-0460-11e5-9b4f-51b04f42d696.png)

**Comment by sural98** [comment]
Yes, it is mostly not working unless you "apply"

**Comment by w00fz** [comment]
This is fixed already in the CI Builds.

**Comment by marktaylor46** [comment]
ok thanks - "apply & save" button no longer appears on item popup, only the article popup - I guess that was the fix - which is fine - thanks.

**Comment by w00fz** [comment]
Yes it won't appear anymore on second+ level modals as it doesn't really make sense.

// Djamil Legato // From iPhone //
