### ISSUE TITLE
3 collumn layout - width of center column

### ISSUE THREAD

**Issue by japre** [gantry/gantry5#366]
If I use the 3 column layout in Hydrogen template, the main body doesnt fit between columns... you can see the problem here http://joomla3.gymnachod.cz/index.php/cz/o-skole/kde-nas-najdete.

**Comment by nicutor** [comment]
The resolution is here: #354

**Comment by JoomFX** [comment]
@nicutor it is a workaround, not a solution.

**Comment by nicutor** [comment]
@JoomFX , yes. agree.

**Comment by w00fz** [comment]
Duplicate of #354
