### ISSUE TITLE
Trash dropzone in Layout Manager should have top:30px in WP

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#367]
When dragging stuff in LM - the trash dropzone is partailly covered by WP admin bar. So when the `#g5-container #trash` appears it should be set at top: 30px; in WP instead of top: 0;

**Comment by w00fz** [comment]
Look how I did In Joomla, it's already different between  Joomla and Prime, you just need to do the same in WP. I think I have a data set on the element or a css override.

**Comment by newkind** [comment]
There is still some leftover in JS because when you go to the LM for the first time and drag the particle the `#trash` top is still 0. You need to refresh the LM and after that refresh it starts respecting `top: 30px` from the CSS.

**Comment by w00fz** [comment]
It's working fine for me, are you sure you cleared cached etc?

**Comment by newkind** [comment]
Yah, did a hard refresh couple times. We can do a hangout to show it to you.
