### ISSUE TITLE
Third-party shortcodes not processed in custom HTML particle

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#369]
If you use third-party shortcodes in a custom HTML particle these are not processed. E.g. use "simple image gallery" {gallery}galllerynamegoeshere{/gallery}.

If you use a joomla module (with prepare content set to yes) either in a "module instance" particle or "module position" particle then the shortcode is successfully processed.

**Comment by gospelpowered** [comment]
Ability to process shortcodes would be awesome!

**Comment by marktaylor46** [comment]
Note above #564 email cloaking plugin needs to scan particle output to cloak any email addresses.
