### ISSUE TITLE
menu edit from the layout page does get selected after save

### ISSUE THREAD

**Issue by esmitz** [gantry/gantry5#37]
I have selected everything such us base path, menu, start level, etc..
Click 'Apply", when you open again the previous selection is not selected.

I've tried 3 different install in my local and i have the same issue.
![menu](https://cloud.githubusercontent.com/assets/11740621/6933401/4750318a-d7fd-11e4-9565-61f0594956ca.png)

Also the Menu in the Setting page has same problem.

Select everything and Save... Leave the page like go to Layout page.. then come back, it is not selected anymore.
![menu-set](https://cloud.githubusercontent.com/assets/11740621/6933433/bac0a1a4-d7fd-11e4-8515-47364058a51f.png)

P.S - I realize i select anything in the Setting page, it does not get selected after save then leave the page and come back..

My environment:
-Latest Joomla 3
-mamp
-I duplicated Hydrogen Home and work on it.

**Comment by esmitz** [comment]
Turn on the firebug console and got this when doing above... Sorry i am not much a code so i don't understand much.

Empty string passed to getElementById(). jquery.min.js:2
mysite/media/jui/js/jquery.min.js

**Comment by w00fz** [comment]
When you click the checkbox you also need to make changes. If you don't the value will continue matching the default value and reset the checkbox. 
Also once you hit apply are you clicking the save button afterwards?

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment]
Like @w00fz said right now overrides only save values that were changed from the default values. We do have some plans on changing this behavior (maybe with configuration setting you can pick) to allow you to make overrides which happen to use the default values. It may be useful on some cases, where you want to be sure that changing defaults will not change the values you forced earlier.

I'm not sure when we will implement that feature, but it isn't very high on our current list.
