### ISSUE TITLE
Gantry 5 Particle Module 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#370]
You can pick only base particles, if you have a new particle, in `template-name/particles` will not be available.

**Comment by w00fz** [comment]
I'm not sure how this should be handled, once you are in the Module Manager you are outside of the template scope.
Perhaps it should list the active templates particles, if available?

/cc @mahagr

**Comment by mahagr** [comment]
Its a known bug which I'm going to look into asap.

**Comment by mahagr** [comment]
Already fixed.

**Comment by JoomFX** [comment]
Awesome!
Thanks @mahagr ;)

**Comment by sural98** [comment]
But I can't still see some of the particles residing under **template/custom/particles** and **template/particles**

**Comment by mahagr** [comment]
Not sure what is going on there; have you set the template to be the default one?

**Comment by sural98** [comment]
I noticed Ethereal Home was set as default.
This was the cause.
Sorry for inconvenience
