### ISSUE TITLE
Ability to define mobile menu trigger point.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#371]
In addition to the ability to set the breakpoint widths it would be great if we had the ability to define the trigger point at which the menu switches from normal to mobile hamburger/sidepanel. 

I would suggest that an additional field be added to the style tab "breakpoints" that says something like:
"mobile menu threshold point (rems)".

In this way you could still have all the switching of the layout widths but in addition (for example) have the mobile menu show at all viewports sizes, some or none.

It's currently a design fashion to have no "normal" menu at all and instead to just have a mobile menu hamburger and sidepanel to save on screen real estate.

**Comment by DanGthatRokGallery** [comment]
+1
Also it would be nice to implement this for Tablet mode as menu line wrap is a difficult issue to deal with.

**Comment by adi8i** [comment]
+1, right now you can do this, need to override mobile-menu particle. For me is ok like it is now too.

**Comment by adi8i** [comment]
@w00fz now you can close this one too. https://github.com/gantry/gantry5/pull/372 :)
