### ISSUE TITLE
Nucleus messes up the Joomla Styling in the G5 Particle module

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#376]
The following code from Nucleus is causing issues in the G5 Particle module:

```
*, *::before, *::after {
    box-sizing: border-box;
}
```

With the above code: http://i.imgur.com/sAX203k.png
Without the above code: http://i.imgur.com/jNxMLtK.png

**Comment by w00fz** [comment]
I think this is part of the admin cleanup we discussed, where we need to namespace our admin CSS
