### ISSUE TITLE
Admin: dropdown z-index

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#378]
`.card settings-block` cover dropdown list in admin panel.

![capture](https://cloud.githubusercontent.com/assets/9744973/7842686/7ac5ab62-04ad-11e5-9bde-9eb331c8afe1.PNG)

**Comment by newkind** [comment]
That is already fixed in the latest build - this was an issue with transform(translateZ(0) which was added when the collapsing sections were added. Right now we commented it out in latest builds.

**Comment by adi8i** [comment]
I just seen that's translate :) . Ok i will close this one.
