### ISSUE TITLE
Image picker should use streams

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#379]
When selecting an image through image picker, it should return absolute url instead of relative. This is a WordPress standard.
![gantry 5 options gantry5 wordpress wordpress 2015-05-27 19-25-22](https://cloud.githubusercontent.com/assets/1641534/7842876/554d9194-04a6-11e5-82cc-96923789d697.jpg)

**Comment by w00fz** [comment]
This is known already. We are missing media streams, can you assign @mahagr to it please.

// Djamil Legato // From iPhone //

**Comment by newkind** [comment]
Sure, re-assigned :)

**Comment by mahagr** [comment]
Image picker should do just this as the value is not supposed to be url, but relative path from the WP installation. In frontend it should be already using domain name in the url.

If I used real urls here, moving your site to another domain would break all the links.

**Comment by mahagr** [comment]
Let's use streams instead. :)
