### ISSUE TITLE
Long layout names break the "layout picker" styling

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#38]
If your layout has a long name and you hit the Load button in the Layout Manager the styling breaks

![gantry admin 2015-04-01 09-42-17](https://cloud.githubusercontent.com/assets/1641534/6936542/a4bceb50-d853-11e4-819a-277f1ee0c45c.jpg)

The odd thing is that this happens only in the "Presets" tab - the "Configuration" one is fine.

![gantry admin 2015-04-01 09-45-44](https://cloud.githubusercontent.com/assets/1641534/6936575/f8c0a1f6-d853-11e4-90f6-424350dfa914.jpg)

**Comment by mahagr** [comment]
This is known issue (to me) already, but thanks for reporting it as I had totally forgot to mention it to @kevlardev :)

**Comment by newkind** [comment]
I also think that maybe we could incrase the width of this popup so it would be able to fit longer names - what do you think @kevlardev ? :)

**Comment by w00fz** [comment]
It was like that because initially the Presets section didn't have two columns and was just listing the theme provided presets. Thanks for fixing @kevlardev.

I think in the presets tab the labels should be User / Theme rather than User / System like it is in configurations, what do you think guys think?

**Comment by mahagr** [comment]
Not sure about theme as it's the platform that is supposed to use those predefined layouts.

**Comment by newkind** [comment]
So maybe Theme / Core or Theme / Gantry Core ? :)

**Comment by mahagr** [comment]
Well, not even Gantry Core -- Joomla error page and offline page are two of those. Those are likely also in WP and others, though, but there are also layouts for existing Joomla templates etc.

**Comment by w00fz** [comment]
Maybe `User / Platform` then for Presets and `User / System` for Configurations

**Comment by mahagr** [comment]
Fine to me. :) Assigning it to you.
