### ISSUE TITLE
System Messages particle should be removed from common Nucleus as it's Joomla only

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#380]
System Messages particle should be removed from common Nucleus as it's Joomla only. Right now it's placed in the engines/common/nucleus/ so all platforms are getting it.

**Comment by w00fz** [comment]
WordPress doesn't have messages like invalid login/password etc?

// Djamil Legato // From iPhone //

**Comment by newkind** [comment]
Yes it has, but not on the front end.

**Comment by w00fz** [comment]
What happens when you have a contact form on frontend that has invalid fields?

// Djamil Legato // From iPhone //

**Comment by newkind** [comment]
It takes you to the admin login screen and there shows the error.

**Comment by kevlardev** [comment]
We had talked initially about having gantry based global message styling, which was why the styling was kept in there. Not sure if that is still the plan.

**Comment by w00fz** [comment]
I think he means the actual System Messages Particle that has no use whatsoever in WordPress which I'm finding odd.

**Comment by mahagr** [comment]
We do want to be using system messages by ourselves, so no, I'm not going to remove those. System messages are also used for things like "Thank you for sending email!" among other things. So this is core Gantry feature even if WP doesn't have it.
