### ISSUE TITLE
Synchronize Target Window Menu Manager - Menu Particle

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#381]
Target window in Menu Manager, will not be applied, you need to select this in `layout manager - menu`. Synchronize them if possible or add a note somewhere, in doc .

![1](https://cloud.githubusercontent.com/assets/9744973/7843952/d7f4feca-04b5-11e5-9c61-6d85602a5ba9.png)
![2](https://cloud.githubusercontent.com/assets/9744973/7843953/d8c0791a-04b5-11e5-82cd-454e67fbfa05.png)

**Comment by w00fz** [comment]
Is this with the CI Build? Pretty sure I fixed this already.

**Comment by adi8i** [comment]
Yes with CI, 30 mins ago :D

**Comment by w00fz** [comment]
I'm a bit confused. Are you talking about the Menu Items setting in Joomla that when changed is not reflected in Gantry 5 Menu Editor ?

That was fixed in 7b605ac975c85, perhaps the issue has been reintroduced?

/ref. #200.
/cc @mahagr

**Comment by adi8i** [comment]
Yep #200, Will always open in parent window, even if you select `new without navigation` or `new window with navigation` .
