### ISSUE TITLE
Modals content in LM appear after the animation is done

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#382]
When changing particle settings in LM in WordPress, the content of the modal appears after the animation is finished - not as fluid as in Prime. Can we enhance that ?

Video : https://cloudup.com/cbNBX7c7J2N

**Comment by w00fz** [comment]
It's Ajax so takes the time it takes to gather all the data to display, nothing we can do about it, it's the same in joomla. On a remote installation this will be more appreciated since you get feedback of loading while the Ajax is processing.

// Djamil Legato // From iPhone //
