### ISSUE TITLE
Module position not collapsing honouring joomla ACL.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#385]
If you publish a module to a position on the outline layout and set if to "registered users" only then the module still occupies space in the layout - it should not. Gantry 4 handles this ok.

Example, create a menu module and give it "registered users" access and assign it to any position in your outline layout. If you look at the frontend the position is there and utilising space when it should not.

Module position rendering needs to honour Joomla ACL setting.

**Comment by Bokelmann** [comment]
+1 because Mark is such a nice guy

**Comment by marktaylor46** [comment]
Testing on latest CI build this seems fine now - so i'm happy to close the issue.
