### ISSUE TITLE
Enable the debug bar in Joomla G5

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#386]
Is there a way to enable the debug bar in gantry5 a la grav as in this screenshot:

![screen 20shot 20on 202015-05-28 20at 2017 3a05 3a34](https://cloud.githubusercontent.com/assets/1498512/7863920/59b49d4a-055f-11e5-9dcb-4dac5c2c1bf6.png)

It would be a great help and provide useful and vital information we as users can provide you as developers when we encounter bugs and exceptions.

**Comment by w00fz** [comment]
This is now implemented.
