### ISSUE TITLE
Joomla Menu Item Link CSS Style

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#389]
Joomla Menu Item Link CSS Style class don't get parsed in. Only works if you put it in the Gantry 5 Menu item i think it should be connected!

![2015-05-29 00 48 35](https://cloud.githubusercontent.com/assets/10489911/7872923/77aac22e-059c-11e5-9c9d-790b56ae4821.jpg)

**Comment by w00fz** [comment]
This is the same issue as in #381 and #162

**Comment by mahagr** [comment]
In joomla pageclass_sfx is used for styling the main component output. It will not be applied to the rest of the page. As our component didn't have anything to output, the class was useless.

The situation has changed in RC3, as now we do have optional main component output.

**Comment by mahagr** [comment]
Actually this doesn't seem to be related to the above two issues. Variable menu-anchor_css doesn't seem to be used in our menu at all.
