### ISSUE TITLE
menu setting shows empty after install

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#391]
in joomla, i did a discover install of our upcoming june template and in the base outline as well as in the default and home outlines, the setting for menu is empty. please see pic.

![g5_menuempty](https://cloud.githubusercontent.com/assets/5719486/7887928/49f50016-05fa-11e5-9316-47efbcfb93f7.jpg)

**Comment by adi8i** [comment]
empty field should inherit default one, on front end is showing? :)
