### ISSUE TITLE
Installing the BT Social Connect Component disables assignment of layouts to menu items

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#392]
In you install the Bow Themes Social Connect Component (http://bowthemes.com/joomla-extensions/bt-social-connect.html) , which I need to use for the full functionality of the BT Property Component (http://bowthemes.com/joomla-extensions/bt-property-component.html) a System Plugin is installed called *** BT Social Connect - System***.

When this plugin is enabled, two javascript files are loaded:
- **punycode.js** (http://mths.be/punycode v1.2.4)
- **validate.js**

One of these two javascript (or perhaps something else that I cannot identify) disables the functionality in Gantry5 which allows assignment of layout outlines to a menu item. I believe the conflicting javascript is **punycode.js**.

Both these components are available for free, but require registration on Bow Themes. To simplify the process, I have uploaded the components which can be downloaded from the links below.

This bug is a blocking bug and renders Gantry's menu assignment of layouts unusable.

http://clips.ergonomiq.net/bt-social-connect-unzip-me-first.zip
http://clips.ergonomiq.net/bt-property-component-unzip-me-first.zip

**Comment by kat05** [comment]
i can confirm this issue after installing the social connect component linked above

**Comment by kat05** [comment]
after disabling the bt plugins, things are back in order again.

**Comment by alisamii** [comment]
@kat05 Thank you :)

**Comment by adi8i** [comment]
![capture](https://cloud.githubusercontent.com/assets/9744973/7889089/d95b7140-0645-11e5-8ef5-b0af3b6609ad.PNG)

Dunno if is Gantry

**Comment by w00fz** [comment]
Sorry for stating the obvious: this has been tested with latest CI Build and/or symlinked gantry, correct?

Thanks.

// Djamil Legato // From iPhone //

**Comment by kat05** [comment]
i tested this with symlinked gantry

**Comment by alisamii** [comment]
Hi Djamil

With the symlinked Gantry, but I haven't updated to the CI Build.

It is on commit https://github.com/gantry/gantry5/commit/4a18fd0928fc9afc28def464895fda3af4cb406f

**Comment by adi8i** [comment]
Tested with latest CI Build.

**Comment by adi8i** [comment]
Btw... BT will load lot of assets

**Comment by alisamii** [comment]
@adi8i yeah, but sadly, I have no choice in the matter.

Not going to build a complicated real-estate component from scratch for this project...not worth it

**Comment by w00fz** [comment]
I could replicate this issue with Callisto and I did see it happening as described, it's not JS related, seems to be failing down the road when it tries to load some helpers.

Anyway, while I was debugging it, I tried to change the `Home (default)` menu item from `Callisto Theme` Menu to `Mainmenu` and after I switched back again the `Home (default)` to `Callisto Theme`, everything on frontend worked as expected.

Are you using the Menu automatically installed by Gantry by any chance? If yes could you try doing as I did above, setting back and forth the default Home?

**Comment by alisamii** [comment]
I'm using a multi-lingual setup.

When I initially installed Joomla, I elected to also install French, German, Italian and Spanish language packs, and activated the multi-lingual setup of Joomla.

I then set up and associated multiple menu items in each language with a language home. Since I have 5 languages installed, I have 5 menu modules, plus the 6th menu module with just a home menu item set for All languages.

In the hydrogen theme, therefore, I actually have 7 menus available...the *all* menu, which has a disabled module associated with it, the 5 menus for the DE, EN, ES, FR and IT menu items, and the hydrogen menu (which also only has a home menu item but none of the other menu items that are set up in each language).

The *home* menu item for the *all* menu and for the hydrogen menu are not assigned to any layout. The *home* menu items for the language-specific menus is assigned to the hydrogen home layout, and the rest of the menu items in the language-specific menus use the default layout *are not assigned to a specific layout or outline I should say.

Therefore, I'm not sure what you're asking that I do.

**Comment by w00fz** [comment]
Ignore my previous message re the menu, this has nothing to do with that. The problems seems to be when the system plugin of BT Social reaches `JHtml::_('')`, that's where it fails with Gantry.

One thing I noticed is that in their plugin  `plugins/system/bt_socialconnect_system/bt_socialconnect_system.php` there are `require_once` outside methods. I tried to move them inside the `onAfterRender` and it seems to have fixed the issue, can you guys try this?

``` php
defined('_JEXEC') or die ('Restricted access');
jimport('joomla.application.component.helper');

$path = JPATH_ROOT . '/components/com_bt_socialconnect';
if (!is_dir($path))  return;
class plgSystemBt_socialconnect_system extends JPlugin
{

	public function onAfterRender()
	{
			require_once(JPATH_SITE . '/components/com_bt_socialconnect/helpers/html/social.php');
			require_once(JPATH_ADMINISTRATOR.'/components/com_bt_socialconnect/publishes/btpublishes.php');
			require_once(JPATH_ADMINISTRATOR.'/components/com_bt_socialconnect/widgets/btwidget.php');

			$app = JFactory::getApplication();
			if($app->isAdmin()) return;
			...
```

**Comment by mahagr** [comment]
I don't think it is Gantry issue; sounds like it's really an issue in BT social connect not working well if some Joomla classes have been loaded/used by another plug-in before BT. We do not override any Joomla classes in Gantry, but we do need to access some properties early to figure out which template style is being used in order to do make the right choices when component is being rendered.

PS. Changing order of plugins may help as well.

**Comment by alisamii** [comment]
Matias,

Would it be possible to implement a check of some sort to override or resolve the conflict caused by the plugin?

Perhaps the plugin is not well coded, and as such, there may be other plugins by this developer or other developers which will have our cause the same problems. Having gantry be able to detect the issue and work around it would be good.

In the meantime, it may also be a good idea to contact Bow Themes to alert them off the issue, and perhaps suggest the workaround that Djamil identified (I haven't had the opportunity to treat that myself) as a possible solution. However, I don't have access to the Bow Themes support, and I have no idea how quickly they respond.

Best regards,

Ali

**Comment by w00fz** [comment]
@DamirPecnik said he saw the same thing happening with a different System Plugin so it might be Gantry related. Hopefully he will be able to identify the plugin and report back.

**Comment by alisamii** [comment]
Well, it may also be related to poorly written plugins or plugins that don't strictly adhere to joomla standards. Nonetheless, it's highly likely there may be other plugins that have the same issue and thus finding a solution that detects and corrects for such circumstances is probably a good idea.

**Comment by alisamii** [comment]
Bow Themes replied to my issue posted on their forum with this:

> Please open file /components/com_bt_socialconnect/helpers/helper.php.
> Find these line
> JHtml::_('behavior.tooltip');
> JHtml::_('behavior.formvalidation');
> And remove them.

It appears this issue also affects other templates, such as Purity HI from JoomlArt.

A similar issue may be present in #407. You would probably need to disable all the plugins that are installed by  the other BT component and then enable them one by one and reload he front-end. Whichever plugin breaks the functionality. This is to make sure that the problem is caused by that component. If it is, then find the helper.php file and see if the two lines referenced above are in the file and comment them out.

And let's hope bow themes updates the plugins to resolve this issue.

**Comment by gyvermac** [comment]
In #407 BTlogin is only a module and it doesn't seem to break any Joomla functionality. Only not fully working on G5.

**Comment by DamirPecnik** [comment]
@w00fz there is also something with Sobi Pro that is doing this don't know exactly what but its something with caching in Sobi, one user reported that when he turned off caching for sobi the error where gone other one that don't make any difference.

Also the error is random it appears and then just goes away and then again it appears so cant pin point the problem ... 

Told the user to turn off the Sobi pro completely and to see if the error will happen again so i will report back ...

**Comment by mahagr** [comment]
As @w00fz said, the issue seems to be related to loading following file from system plugin:

   require_once(JPATH_SITE . '/components/com_bt_socialconnect/helpers/html/social.php');

Returning after that line causes Gantry5 to fail (even if plugin was never used anywhere).

**Comment by mahagr** [comment]
@alisamii 

You found the bug in BT extensions. It is calling JHtml functions that take care of rendering before Joomla has even initialized itself (from the require_once in the plugin). Those calls will cause Joomla to initialize template (possibly also document and a few other classes) before routing happens, which results of it defaulting to default template style instead of picking one from the menu item. 

There is absolutely no fix we can do from Gantry5 as Joomla itself is in a broken state and I do not think that that the template state is the only thing which is wrecked up.

No code should ever be run just by including a php file. If extension breaks that rule, there are some really hard to detect side effects like this one.

**Comment by w00fz** [comment]
Closing this since, in the end and gladly, it's not related to Gantry 5!

**Comment by mabdelaziz77** [comment]
I've found the same problem using BT Social Connect 1.2.3 with Gantry5 Hydrogen them on a multi-language website.
It is not a gantry5 issue, I fixed it with removing the 2 lines of JHtml as @alisamii suggested.
Just wanted to thank you all because this thread saved my life.
