### ISSUE TITLE
Mobile Menu - error 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#397]
@w00fz  If you have a nested menu, will not open in offcanvas. (Latest CI g5 and hydrogen)

Menu Structure:
![menu](https://cloud.githubusercontent.com/assets/9744973/7909510/60cc2dfc-0855-11e5-860e-652ebbeb8e72.PNG)

Mobile Menu, and button to click:
![2](https://cloud.githubusercontent.com/assets/9744973/7909519/70f65932-0855-11e5-8231-f2abe1957644.PNG)

Error:
![capture](https://cloud.githubusercontent.com/assets/9744973/7909523/76141918-0855-11e5-920c-74a49165a323.PNG)

Could be related to #396

**Comment by kevlardev** [comment]
Hmm i cant seem to reproduce this on my local, submenus seem to open and animate properly. @djamil any idea on this?

**Comment by w00fz** [comment]
No, I cannot reproduce this either.

**Comment by adi8i** [comment]
Create a new menu, and only that structure inside it, and you will see. If you have more menu items will work, but if you have only a parent menu with a sub-menu, will not @w00fz

**Comment by w00fz** [comment]
Gotcha and fixed.
