### ISSUE TITLE
Two spaces between classes

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#399]
I have inserted 3 particles in a section. G5 adds 2 spaces between classes
```<div class="g-block  size-33-3"><div class="spacer"></div></div>```

**Comment by w00fz** [comment]
That's probably because in the twig files we have checks for rendering or not rendering certain classes which might cause double spaces.
This is totally fine in HTML and the CSS parsers know how to ignore the extra spaces.
It doesn't affect anything, no needs to   worry.
