### ISSUE TITLE
Impossible to install Gantry 5

### ISSUE THREAD

**Issue by alainbadan** [gantry/gantry5#40]
Hello,
I have tried several times to install Gantry 5 on a fresh Joomla 3.4.1 installation on a fresh AMPPS installation, with PHP 5.6, fileinfo dll installed on PHP, but I always get the same error message:

Erreur
Required PHP extension 'fileinfo' is missing. Please install it into your system.
Paquet : erreur à l'installation

Alerte
Extension Installer: Échec de l'installation personnalisée
![php](https://cloud.githubusercontent.com/assets/11753084/6939811/6f66efba-d870-11e4-952b-4dfbbed999f7.png)

**Comment by JoomFX** [comment]
@alainbadan have a look at this issue:

https://github.com/gantry/gantry5/issues/11

**Comment by mahagr** [comment]
Beta2 no longer requires this PHP extension, but for now you just need to setup your PHP to have it enabled.

**Comment by w00fz** [comment]
This was fixed in #11
