### ISSUE TITLE
Image alignment won't work

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#403]
I have applied the class **align-left** to ```<img>``` in the following custom html particle but it didn't work.
```<img src="" alt="" /><a href=""><p>...</p></a>```
Am I missing something?

**Comment by w00fz** [comment]
Yes you are missing the actual class :smiley: 

``` html
<img src="[src]" alt="" class="align-left" /><a href="[href]"><p>...</p></a>
```

**Comment by sural98** [comment]
I did add the class for img.
I didn't add it for simplicity.

**Comment by sural98** [comment]
That is it has not been added in the question.

**Comment by w00fz** [comment]
I did try my code above and it did work just fine. Rendered with `align-left` and the image was left aligned as expected.
How does it look like on front-end the rendered code?

**Comment by sural98** [comment]
```<div id="czsimple" class="g-block box-orange  size-33-3">
	<div class="g-content ">
		<div class="simplecustom ">
			<div>
				<img src="http://placehold.it/150x100" class="align-left">
				<h2 class="g-title">...</h2><p>...</p>
				<a href="#" class="button"><i class="fa fa-fw fa-quote-left"></i> Czytaj więcej</a>
			</div>
		</div>
            
	</div>
                        
</div>```
![image](https://cloud.githubusercontent.com/assets/1849490/7959116/ee13f492-09fe-11e5-8260-fa833f8eebd7.png)

**Comment by sural98** [comment]
I noticed that <img> was misplaced. Sorry for the inconvenience.
