### ISSUE TITLE
Gradient colour picker

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#406]
Would be great to be able to have a gradient colour picker.

It could be triggered by having a toggle switch to select a background as a solid or a gradient where if the user chooses Solid the standard colour picker already implemented is displayed and if the user selects gradient the gradient colour picker is displayed.

Could use one of the following colour picker plugins:

https://github.com/tantaman/jquery-gradient-picker

http://www.virtuosoft.eu/tools/css-gradient-generator

**Comment by w00fz** [comment]
This was already discussed in another issue that I cannot find, the gist of it is we have no plans to implement this at this at the moment. 

I think this would make a good contribution from the community if someone is willing to implement it.
