### ISSUE TITLE
&nbsp; not encoded

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#408]
I have manually added 3 ```&nbsp;``` to DESCRIPTION of a particle in layout.yaml of a layout and saved it.
It is rendered as is in the frontend.
```description: 'Wat is de invloed van mensen die zich in een later stadium van hun leven bij de netwerken?&nbsp;&nbsp;&nbsp;'```

**Comment by w00fz** [comment]
I'm not sure what exactly you changed. Was it a Particle? Which Particle? I tested this and works fine.

**Comment by adi8i** [comment]
Is a `yaml` file @w00fz, as far as i know, `&nbsp` will be ignored.

**Comment by w00fz** [comment]
I have it in a `layout.yaml` and works for me.

**Comment by sural98** [comment]
I can't now replicate the issue. Manually added &nbsp; is now stripped out.
FYI. It was promoimage particle of Callisto.
