### ISSUE TITLE
Social icons not saving

### ISSUE THREAD

**Issue by webfoundry** [gantry/gantry5#409]
To recreate issue:
1. Drag social particle from left sidebar onto layout
2. click cog icon on social particle > select box next to social name, e.g. 'Facebook'
3. Add any icon from Font Awesome, choose any size, fill in text field and link ref, click apply & save
4. Save page  and view in front end.

Issue: doesn't show in front end, then check social particle fields and these have been cleared of data on apply/save.

**Comment by adi8i** [comment]
`Apply & Save` button will not save any settings on second modal. This is a known bug and is already fixed for RC3 (next release). Use `apply` button instead.

Or you can use CI build, that bug is already fixed here:
http://gantry.org/downloads#ci-builds

**Comment by webfoundry** [comment]
yup, that was the issue - thanks for that!
