### ISSUE TITLE
Submenu columns does not work in "Standard" menu

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#41]
This was submited and closed in https://github.com/gantry/gantry5/issues/34 but I just want to double check if the "columns" issue is fixed as well (not only the z-index issue).

Let me know if you need screenshots of something.

**Comment by w00fz** [comment]
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!
