### ISSUE TITLE
Menu item-Template Style doesn't sync with Outline-Assignments

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#410]
In your default Home menu item if you set the Template Style to Callisto-Home and then go to Template Manager-> Callisto-Home -> Assignments -> it's possible to disable the Callisto Theme as the Home menu page override.

This was not possible in Gantry 4 as these two fields were always synced.

**Comment by DanGthatRokGallery** [comment]
Just a note - this little bug also allows for a Callisto-Home Outline to have two Assignement overrides enabled, e.g. Callisto-Home and MainMenu Home can be enabled at the same time.

**Comment by mahagr** [comment]
To me it seems to work just like it was designed in Joomla -- you can assign assignments as you wish.

You can assign styles (outlines) into any number of pages, but each menu item has at most one assignment. So basically there is 1:n relationship with no mandatory assignments and no other rules.

**Comment by webmasterchris** [comment]
I've been testing the new site with a colleague, We found when a new article is added, it uses the home template not the "starred" or set default template. With pages not on a menu it seems impossible to change the template.

**Comment by mahagr** [comment]
Yes, that is what Joomla is lacking. The only way to change the template is to use another menu item.

We have some plans either to use some existing extension or to write our own to allow you to change template styles elsewhere as well, but I'm not yet sure when we will add the support.

**Comment by mahagr** [comment]
I'm closing this one as not being a bug. As I said, you can assign any template style to any menu item.
