### ISSUE TITLE
Style id in outlines

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#411]
We often refer to the template_style_id in Extensions/Template Manager/Styles
Can you reflect this id in the outline?
In the picture 72 refers to the style id in Joomla template manager.
![outline id](https://cloud.githubusercontent.com/assets/1849490/7982807/aec36a9c-0ac2-11e5-817c-4a0c1d5a567e.png)

**Comment by adi8i** [comment]
Could be useful if you try to edit `custom/config` :)

**Comment by w00fz** [comment]
Good call.
