### ISSUE TITLE
Once again: Layouts and multi-language Joomla

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#414]
I had sounded the problem before and I need to reiterate again:
A multi-language Joomla installation with G5 will need many layouts: For each language "at least" 1 for home and 1 for the rest because of the "pagecontent" issue.
It is a lot of work as it was in G4 and needs a simple approach.

**Comment by JoomFX** [comment]
@sural98 have a look at this issue https://github.com/gantry/gantry5/issues/213

You can have only the "Default" Outline, without "Home". Just use the "Gantry 5 Themes -> Custom Page" for your Homepage. That's how you will not have "Page Content".

**Comment by sural98** [comment]
Couldn't understand. As far as I know G5's approach to multi-language installation is no different than that of G4.
Assume I have 3 languages: en-GB, fr-FR and de-DE
Each will have different layouts with particles, modules etc.
Can you explain your solution using this scenario?

**Comment by JoomFX** [comment]
I don't have a solution... Gantry5 does not officially support multilingual websites yet. You might be able to configure a multilingual website with it, but there will be big improvements/changes in this direction in the future.

The purpose of my previous comment was to shed some light on the multiple Outlines stuff and to let you know that you do not need to have a separate Outline for the Homepage.

**Comment by mahagr** [comment]
Yes, right now there isn't any better solution; using module positions / component content may help a bit, but doesn't really solve the "Joomla multi-language issue". We have plans on how to fix the issue in #84, so please, lets continue discussion in there.

We do not have any dates when we would have this support, but I still hope we would be able to implement it soon. Unfortunately I don't know what soon means as my kids are at home the whole July and before that I have more things to do than I can do.
