### ISSUE TITLE
Improvement/modification to gulpfile.js

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#415]
In https://github.com/gantry/gantry5/blob/develop/gulpfile.js on lines 12-30 is a function to update the installation of a src installed Gantry.

```
// if we call `up` or `update`, we just need to run through projs and update all NPM deps
if (process.argv.slice(2).join(',').match(/(update|up|--update|-up)/)) {
    gulp.task('default', function() {
        paths = ['./', 'platforms/common', 'assets/common', 'engines/common/nucleus'];

        var exec = require('child_process').exec, child;
        paths.forEach(function(path) {
            console.log("Updating JS dependencies in: " + path);
            child = exec('cd ' + path + ' && npm update --save --save-dev',
                function(error, stdout, stderr) {
                    if (stdout) { console.log('Completed `' + path + '`:', "\n", stdout); }
                    if (stderr) { console.log('Error `' + path + '`:' + stderr); }
                    if (error !== null) { console.log('Exec error `' + path + '`:' + error); }
                });
        });
    });

    return;
}
```

However, if you are doing a git clone installation for the first time, this won't work as the initial dependencies have not been installed.

An additional function is needed to do a first-run installation. Something like `gulp --go` would be a good command (if it is not already used in gulp elsewhere.

Or the same function could be updated to first install then update.

Line 20 is where the change would need to be done replacing

`child = exec('cd ' + path + ' && npm update --save --save-dev',`

with

`child = exec('cd ' + path + ' && npm install --save --save-dev',`

**Comment by mahagr** [comment]
@w00fz Can you take a look on this? Looks like something that could be fixed easily.

**Comment by w00fz** [comment]
You can install or update NPM dependencies across the whole project via the supported commands:

>  `-update`, `--update`, `-up`, `--up`, `-install`, `--install`, `-inst`, `--inst`, 
> `-go`, `--go`, `-deps`, `--deps`

They all execute the same command and it will be smart enough to know whether to install or update the dependencies.
