### ISSUE TITLE
Menu Dropdown Position

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#417]
If Menu is right aligned and you have sub-menu item, as dropdown will always open to right, will go out of page.

There should be an option to adjust dropdown opening position, `left`, `right`, `center`.

![capture](https://cloud.githubusercontent.com/assets/9744973/8019198/78f8e20a-0c4a-11e5-8ef3-83f0c8e715dc.PNG)
![home](https://cloud.githubusercontent.com/assets/9744973/8019199/7ada09d2-0c4a-11e5-8094-1f6220af30e9.png)

Other related thing, `style` should be added only for `g-active` @w00fz 
![capture1](https://cloud.githubusercontent.com/assets/9744973/8019206/ebe1e1ae-0c4a-11e5-994e-bb3022f1af40.PNG)

**Comment by alisamii** [comment]
I agree, but I think it can be one-level better even.

I think that the dropdown menu should be able to detect whether it's current width plus its position relative to the container will have it overflow the container, and in that case, reverse directions.

**Comment by JoomFX** [comment]
+1 for this (actually +1000)

I've had many customers with my G4 Templates that asked me to do that for them (the dropdown menu of the last Main Menu element to float to the left/stay inside the container).

Helix3 is a good example of what I mean.

**Comment by w00fz** [comment]
We never had this in Gantry 4, we had it in Fusion menu I think with Gantry 3.
It is a lot of extra load on the client side to properly redirect the menu left or right based the viewport. A lot of calculations, repositions, etc.
Something we might consider on implementing later on but definitely very low in our priority list.

**Comment by JoomFX** [comment]
Yah, I was thinking again about this the other day...
And now when you are saying that it will add a lot of extra load it will be probably best to leave it as it is.

I will do this on case by case basis. Whenever I have a custom that want this I will just assign a custom class to the main menu element and just adjust the dropdowns with CSS.

**Comment by adi8i** [comment]
I will use scss to add an option, so you can switch from left to right.

**Comment by kat05** [comment]
This was actually part of RokNavMenu and made available for some Gantry 4 templates.

The documentation is here:
http://www.rockettheme.com/docs/joomla/extensions/roknavmenu/setup.md#dropdown-menu-options
http://www.rockettheme.com/assets/docs/joomla/extensions/roknavmenu/menu_1.jpg

It's those settings called:
Dropdown on Large: Left/Right
Dropdown on Desktop: Left/Right
Dropdown on Tablet: Left/Right

It worked well and I think if we can integrate it into Gantry 5's menu, that would be fantastic.
It was not a calculation, but rather just a setting where you could decide for each parent on which device you would want it to open to the right or left.

**Comment by mahagr** [comment]
I was about to close this one as we already have some simple logic on dropdown direction. Do we need more? @w00fz @kat05 @adi8i

**Comment by adi8i** [comment]
I think you can close it. Gantry menu works fine now :)
