### ISSUE TITLE
Template rendering problem.

### ISSUE THREAD

**Issue by xaypay** [gantry/gantry5#418]
I add a module instance in layout and . . .

Oops, An exception has been thrown during the rendering of a template ("Indentation problem at line 488 (near " attributes:").") in "@gantry-admin/pages/configurations/styles/styles.html.twig" at line 16..

![problem](https://cloud.githubusercontent.com/assets/12773322/8019251/db9edd5a-0c55-11e5-980b-3fcdcedd7d81.png)

How fix it ?

**Comment by mahagr** [comment]
Looks like there's broken yaml file somewhere or regular expression fails to compile because of some setting.. Can you check following PHP options in the System Information:

    pcre.backtrack_limit	100000
    pcre.recursion_limit	100000

**Comment by w00fz** [comment]
Did that help @xaypay ?

**Comment by xaypay** [comment]
No (((( Did that help. I had backup and restore project and continue developing.

**Comment by mahagr** [comment]
We really need to track issues like this down, so if you have any other information or you run into this again, we would appreciate to hear more about the issue in order to fix it for good.

**Comment by w00fz** [comment]
By the sound of it looked like a corrupted YAML as Matias said. Glad you are back on track now but yeah, please do provide more details next time so we can figure it out and not have this happening again.

Thanks!
