### ISSUE TITLE
In "Full width" menu some of the 3rd level menus cannot be expanded

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#42]
Most probably this issue is related to some already repored ones and probably re-working the JS for the Menu will fix it but I just wanted to open it so you have track of it.

When you set the "Full width" menu and have multiple columns, some of the Menu Items that are actually parant items, do not have the box with the arrow so they cannot be expanded.

![alt](http://i.imgur.com/nK1yLmK.png)

**Comment by mahagr** [comment]
@kevlardev for you?

**Comment by w00fz** [comment]
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!
