### ISSUE TITLE
CI Updater

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#420]
It would be really nice to have a way to trigger an update of G5 CI build from within the G5 component.

![ci-update](https://cloud.githubusercontent.com/assets/1498512/8019562/a7d7c414-0c55-11e5-84ae-83679ccccfd3.png)

**Comment by w00fz** [comment]
We are not planning to provide updates for `CI Builds`, they are just meant to be temporary packages and installed manually without shortcuts. An updater for CI Builds will also replace the ability to rollback to the current stable version which we really don't want to loose.
