### ISSUE TITLE
Question: Gradient

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#422]
Is this the right way a gradient should look like? I don't think so, but i am asking thought... :D
![capture](https://cloud.githubusercontent.com/assets/9744973/8019957/085162a4-0c70-11e5-952d-227e1e155bcc.PNG)

**Comment by w00fz** [comment]
I think this is an ok implementation by relying just on the tools you have at disposition. Obviously a single gradient field would work best but that is harder to implement and as discussed in other issues we have no plans for that as of yet. 

With your approach above, you can then just combine those 3 colors in a proper css gradient.

**Comment by adi8i** [comment]
I've tried to add 3 color selectors on the same window, so on one color picker, but is a bit over me, so i've added this, lol
