### ISSUE TITLE
Question - Compile CSS / JS on the go

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#424]
Was some discussions about this on chat, but i am not sure how this work so i am asking.

Would be possible to load css/js from template only when is needed? Right now if we add css or js in `template-name/scss` or `custom/scss` will be compiled.

For a joomla `menu item type` override i have some css, but would be great if this css will be compiled and loaded only for pages where this override is used, and so on for particles or modules. 

Because if i will create some overrides, and some particles the code will be loaded all the time and the weight is considerable.

**Comment by w00fz** [comment]
This is kind of related to #215, I would like to have `custom.scss` a bit smarter where you can have `custom_outline-id.scss` or `custom_menuitem-id.scss` to go along with it.
That way not only they will be only loaded when needed but they will also allow to write CSS that's only targeting certain pages and not all of them.

**Comment by mahagr** [comment]
Loading CSS is possible only when needed by particles and atoms, but SCSS compilation when needed isn't implemented yet. You can create new .scss files and include them to be built when styles update, but there's no way to hook the missing file recompile in particle, yet.

**Comment by mahagr** [comment]
This feature is now implemented, though not by fixed SCSS file, but by adding support to add SCSS files just like you would add CSS files into your pages:

* Allow custom SCSS files to be inserted from particles and atoms by <link rel="stylesheet" href="particle.scss" />
* Allow custom SCSS files to be inserted from both Page Settings / Assets / CSS and Assets Atom
