### ISSUE TITLE
Question: Fixed top navigation / hydrogen template

### ISSUE THREAD

**Issue by Attis35** [gantry/gantry5#425]
Hello,

how can I set the navigation fixed in the top in hydrogen template? I've put the navigation part to the top in the yaml file and I tried to modify _navi.scss but it doesn't work for me.
Could you please help me?

**Comment by adi8i** [comment]
```
#g-navigation {
position: fixed;
width: 100%;
top: 0;
}
```
Also you will want to set `padding-top` for `#g-page-surround` (the padding should be equal with navigation height)

This is the basis, if you want something more advanced, of course more advanced styling will re required. :)

**Comment by Attis35** [comment]
Hello Adrian,

thank you for your fast response. Unfortunetly it doesn't work for me (I've recompiled CSS after modifications). I've updated the following files:

templates/g5_hydrogen/scss/hydrogen/_main.scss and _nav.scss
Should I do anything else?

**Comment by adi8i** [comment]
Don't modify that files, because will be rewritten when you will do an update to Hydrogen. 

Place your code in:
`g5_hydrogen/custom/scss/custom.scss` if directory doesn't exist you should create it :)

**Comment by w00fz** [comment]
You also need the CI Build for this or RC3 when it's going to be out.
In RC2 it wasn't possible to use fixed elements.

**Comment by adi8i** [comment]
Ops, they are still on RC2, forgot about that

**Comment by Attis35** [comment]
Thank you for your answers guys!
