### ISSUE TITLE
Browser Compatibility Screen

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#426]
It would be nice to add Browser Compatibility Screen for users that have outdated browsers like we have in Gantry 4 for IE ...

**Comment by mahagr** [comment]
This could even be a particle in a screen that displays a small notification.

We discussed this in the past and decided that we do not need it at least in the first version.

**Comment by w00fz** [comment]
We have plans for this but theme specific and not built into Gantry 5.
