### ISSUE TITLE
Module Instance title

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#428]
"Apply" or "Apply and Save" doesn't work after changing the "Module Instance" title with my own.
I use the latest CI build dev-7b3757a2f
![module-instance-title](https://cloud.githubusercontent.com/assets/3976174/8032991/1b57ef78-0ddb-11e5-85e1-efde0f2d9390.png)

**Comment by adi8i** [comment]
Is the same for all particles, you can't rename them. :)

**Comment by mariantanase** [comment]
Well, I don't like this :) it would be useful to associate the Module Instance title with the name of the inserted module (like rokajaxsearch) to be visible on layout manager.

**Comment by adi8i** [comment]
@mariantanase i mean is a bug ;)

**Comment by w00fz** [comment]
Not sure If i'm missing the point here but I can rename `Module Instance` as well as any other `Particle`.

What am I missing here?

![rename](https://cloud.githubusercontent.com/assets/11734/8147166/3b68a238-1215-11e5-9617-05d49286e2f9.jpg)

**Comment by mariantanase** [comment]
This issue seems to be related to CI build dev-7b3757a2f, but with RC3 the renaming is working fine.

**Comment by w00fz** [comment]
Hey @mariantanase, good to see you again!

Would you mind trying the latest CI Build? There have been some changes till that other one, although none related to this. I have a feeling it was a glitch in that build.

In my development environment seems to be working as expected.

// Djamil Legato // From iPhone //

**Comment by mariantanase** [comment]
Hi @w00fz !
I'm here still watching this project everyday, unfortunately I'm not so active to shooting G5 bugs :)
With "the latest CI Build" I mean "the latest" at that date, e.g. 7 days ago :) As you said it seems that was a glitch with that build.

**Comment by w00fz** [comment]
Cool so this is all good now with the last CI Build from http://gantry.org/downloads#ci-builds ?
