### ISSUE TITLE
Some way to implement bootstrap ?

### ISSUE THREAD

**Issue by thasmog** [gantry/gantry5#429]
I tryed to add bootstrap with custom CSS/JS but my site gets striced out. How to remain same widh ?

**Comment by adi8i** [comment]
That should not happen, maybe are some classes that conflict. I will try to reproduce.

**Comment by thasmog** [comment]
watch it from my site http://thasmog.eu

My breakpoint for large desktop is 95rem

**Comment by adi8i** [comment]
Rem can be ok too, you have just wrong breakpoints ;)

**Comment by w00fz** [comment]
Glad to see you solved the issue! :+1:
