### ISSUE TITLE
"Full width" menu size (enhancement)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#43]
Currently the "Full width" menu fills up the whole window size:

![alt](http://i.imgur.com/nK1yLmK.png)

Wouldn't it be better to appear as most of the Mega Menus available on the Internet. I mean to be center and filling up just the container. Adding `position: relative;` to the Main Menu element is a good example of what I mean.

![alt](http://i.imgur.com/sStZRGj.png)

Or it will be left as it is and the theme developer will decide how to style it?

**Comment by kevlardev** [comment]
This is really meant to be left up to the theme developer to decide which type they prefer (relative to container or relative to browser window) based on the design and their preferences. However Im going to change this in the Hydrogen theme to stay relative to the container.

**Comment by JoomFX** [comment]
Thanks @kevlardev :)
