### ISSUE TITLE
@alisamii

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#431]
@alisamii i can't use the chat, i can read, but i can't write anything, is happen often, look like is something wrong with my ISP....

**Comment by adi8i** [comment]
btw there is a new block, in `page_head.html.twig` 
```
{% block head_overrides -%}
         {% for css in gantry.theme.configuration.css.overrides %}
             {%- set url = url(gantry.theme.css(css)) %}{% if url %}
             <link rel="stylesheet" href="{{ url(gantry.theme.css(css)) }}" type="text/css"/>
         {% endif %}
         {%- endfor %}
     {% endblock -%}
```

**Comment by alisamii** [comment]
@adi8i see #432

**Comment by adi8i** [comment]
custom folder will be added as `stylesheet`

**Comment by adi8i** [comment]
You can use `config` so the atom will load your js by default. The same for `<body>` classes.
```
body:
  class: custom-class custom-class-1 
```

**Comment by alisamii** [comment]
What do you mean? In the yaml?

Also, take a look at the question I posed to @bokelmann please.

**Comment by adi8i** [comment]
I've never used that script. 

And yes in a yaml file. This is a great tool, you can create a ready to use pages using `layout presets`. You can see in the picture, in `config` folder you will have a folder named the same as your `preset`

![reducerireview cloud9](https://cloud.githubusercontent.com/assets/9744973/8035186/05236df6-0df7-11e5-85bb-2dd16635dc2d.png)

**Comment by alisamii** [comment]
ok, but there isn't a global `yaml` file applies to all layouts, is there?

also, can you try experimenting with `Joomla Atomizer` to see if you can get it to work?
