### ISSUE TITLE
overrides to page_head.html.twig break code

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#432]
I had an override to `page_head.html.twig` located in `/templates/g5_hydrogen/custom/engine/templates` from an old attempt to insert the TypeKit code in the header without using an atom because I didn't want to have to drag the typekit atom into each layout (I wanted a global activation of that atom's content).

I later decided that for the moment, I would set up the atom and drag it into each layout outline. But, I left the override file in place.

When I updated the CI from `dev-fb2cb0f72` to the latest CI build, `custom_XX.css` files were no longer being loaded.

I removed the override to `page_head.html.twig` and `custom_XX.css` files are loaded again.

As a test, I copied the contents of `/media/gantry5/engines/common/nucleus/templates/page_head.html.twig` into a new empty file located at `/templates/g5_hydrogen/custom/engine/templates/page_head.html.twig` and loaded the front end again, and the `custom_XX.css` files are once again not loading.

Sometime between `dev-fb2cb0f72` and the latest CI build, the code regressed where `page_head.html.twig` overrides will break the code.

**Comment by mahagr** [comment]
You need to override your override; we had to change the logic a bit in order to fix the loading order of 2 files.

**Comment by alisamii** [comment]
Hi Matias, 

I did. I took the latest version of page_head.html.twig from the latest
CI build and just copied it's contents into a new copy in the
override...and the page broke, even with the new code and no
modifications to that code at all. 

On 2015.06.08 18:10, Matias Griese wrote: 

> You need to override your override; we had to change the logic a bit in order to fix the loading order of 2 files. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/gantry/gantry5/issues/432#issuecomment-110057011

**Comment by mahagr** [comment]
You may also want to check theme.yaml, it added ```overrides:``` to the css section.

**Comment by mahagr** [comment]
I tried to reproduce the issue by copying ```/media/gantry5/engines/common/nucleus/templates/page_head.html.twig``` to ```/templates/g5_hydrogen/custom/engine/templates/page_head.html.twig``` and by making minor change to the file.

My custom.scss file worked just fine.

**Comment by alisamii** [comment]
@mahagr suggested I manually replace the content of the core and the override with the content currently on github. Doing that solved the issue of the override breaking the site.

Seems that sometimes, joomla doesn't properly update files even though it does not error out. @mahagr said that when the md5 hash checking is implemented, this should be resolved.

I will close this issue, however, I still think there is an issue because the core file with the wrong code should have also broken the site, but it did not. Should be looked into further.
