### ISSUE TITLE
Joomla Classes are loaded before G5

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#433]
Right now if you want to adjust joomla classes, like `.span...`, using Media Queries will work only if `!important` is added.

http://docs.gantry.org/gantry5/tutorials/media-queries

**Comment by kevlardev** [comment]
This should be fixed for RC3 and should be available for testing in the latest CI builds.

**Comment by adi8i** [comment]
I had latest CI all the time, anyway i will try update again a bit later.

**Comment by w00fz** [comment]
There was an ordering issue with some CSS that was fixed a few days back. Can you confirm with the latest CI Build this is not a problem anymore?

**Comment by adi8i** [comment]
I've tried this and will work only if there is `!important`
```
@include breakpoint(no-desktop) {
    .span6, .span4 {
        width: 100% ;
    }
}
```

**Comment by kevlardev** [comment]
Where are you setting up this rule? The custom scss should be the last thing loaded now with the new ordering. Before the bootstrap stuff was loaded after our theme specific css and overrides, so none of hte bootstrap media queries as well as other customizations would work as bootstrap would just reset them to default. Now the ordering should be correct with theme specific joomla css and custom css coming at the very end to provide full override control (assuming youve not overridden page.html.twig which is where part of the changes were made)

**Comment by adi8i** [comment]
Is added in `template-name/scss/...` and i don't have overrides.

**Comment by kevlardev** [comment]
If you're not adding it to custom, it should be in the themename-joomla scss, as that is what is used to set joomla specific rules (and override them). Basically all the common stuff, theme and otherwise, gets loaded first, then the platform assets (bootstrap, hydrogen-joomla, etc) come next

**Comment by kevlardev** [comment]
However the bootstrap media query portions get loaded at the end of the themename-joomla.scss so really the best place would be the custom css for these adjustments, or create a new file include and put it at the end of the themename-joomla.scss after the breakpoint import

**Comment by adi8i** [comment]
Still not working for me, i'll assume that is something wrong in my configuration. I have a file called "flat-joomla.scss" here is imported another file that contain the code i've posted above. `flat-joomla.scss` is added in `gantry/theme.yaml` also, if this matter.
