### ISSUE TITLE
After update to Gantry 5 RC3 unable to access template admin

### ISSUE THREAD

**Issue by dickbronder** [gantry/gantry5#438]
After updating to Gantry 5 RC3 I'm not able to access the template anymore. Neither the Gantry 5 Themes Component. Anybody else?

**Comment by mahagr** [comment]
Ping me in Gitter chat for Gantry 5, as it would allow us to talk in real time to figure out what's going on.

Otherwise I need more information about the error you are getting.

**Comment by dickbronder** [comment]
I will, new here so I'm trying to figure out Github :-)

**Comment by dickbronder** [comment]
Solved it, had to reinstall the template once and the RC twice.
Thanks anyway :-).

**Comment by mahagr** [comment]
Likely some cached file.. Got the same in our production server where we had to restart the server in order to empty opcache for the modified php file.
