### ISSUE TITLE
Menu editor loads menus with en-GB-tagged items only

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#44]
- Menu editor loads those menus with menu items of languages set to All (*) or English (en-GB).
- On the other hand MainMenu with en-GB-labeled items is missing Home menu item (**index.php?option=com_content&view=featured**)

**Comment by mahagr** [comment]
I've not fully solved this issue in Joomla; if we load all the items for all languages, the menu would be too messy to show up. So I'm filtering by current language right now.

Multilanguage support isn't working yet (saving messes things up, too), though, need to think how it would work the best.. Maybe language selector next to the menu selector..?
