### ISSUE TITLE
custom css does not override the standard css files since RC3

### ISSUE THREAD

**Issue by felixo1234** [gantry/gantry5#440]
I use g5_hydrogen template rc3. In RC2 I set the flex-flow property of #g-navigation .g-main-nav .g-toplevel to row nowrap, because I do not want the menu items to wrap when I resize the window, I just wanted them to shrink. With RC2 it just worked fine, I just commented out the specific lines in hydrogen_16.css and the problem was solved. After updating to RC3 the same issue occured again, but it was not possible to solve it with deleting the right lines in the code.
So I tried to add a custom css in templates/g5_hydrogen/custom/scss/custom.css

            .g-toplevel {
                      flex-flow:row nowrap;
                }
But it does not manage to override the flex-flow property. Firefox Inspector still shows me flex-flow: row wrap in hydrogen_16.css
Any ideas on how to solve this problem?

Thanks!

**Comment by mariantanase** [comment]
Did you hit "Recompile CSS" ?

**Comment by mahagr** [comment]
You cannot change hydrogen_16.css because of the new version will detect the change and force recompile every time you touch the file. So your changes get overridden whenever you do them.

Correct way to do this is use ```templates/g5_hydrogen/custom/scss/custom.scss``` file (with scss as the extension).

**Comment by felixo1234** [comment]
I tried to use custom.scss file and located in the exact same path you told me. In the file I wrote:
           `.g-toplevel {
                  flex-flow:row nowrap;
               }`

In  `templates/g5_hydrogen/custom/css-compiled/custom_16.css` the import of custom.scss was commented out so I changed it to `@import "../scss/custom.scss"` but it had no effect either.
What am I doing wrong? 
Thanks!

**Comment by gyvermac** [comment]
Try this
```css
/*Test*/
#g-navigation .g-main-nav .g-toplevel { 
	flex-flow:row nowrap;
	-webkit-flex-flow: row nowrap;
	-moz-flex-flow: row nowrap;
	-ms-flex-flow: row nowrap;
	-o-flex-flow: row nowrap;
}
```

**Comment by w00fz** [comment]
If you use Chrome or Firefox and inspect the element, in the Style panel you can identify what is overriding your change.

I have a feeling this is just a selectivity issue, you just need to go more specific with it (https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**Comment by mahagr** [comment]
If there was commented out import, it means that the SCSS file could not be found. Are you sure the file was in the proper location?

**Comment by felixo1234** [comment]
thanks @gyvermac this worked!
