### ISSUE TITLE
Menu item page suffix is not being rendered on the body tag

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#442]
Further to #346 the page suffix on a menu item should be rendered on the body tag of the html. Gantry 4 rendered this fine. The reason it needs to be rendered on the body tag is so that anything within the page can be targeted with custom CSS. The page suffix field is often used by members to apply styling to a specific page(s) throughout the application of the page class suffix field.

**Comment by mahagr** [comment]
Menu item page suffix now works just like in Joomla itself (I just fixed a bug). I do agree that I see no point of doing it in Joomla way as the suffix can only be used to have custom styling and it doesn't make any sense to be able to restrict that customization into component only as it is easy to target that if needed.

I need feedback from @kevlardev @w00fz and @arifinrt before I'm going to make any changes on this one.

**Comment by marktaylor46** [comment]
Thanks :) I look forward to hearing conclusion.

**Comment by w00fz** [comment]
Fine by me to be on body, not entirely sure what would be its purpose otherwise. Since Joomla works around menu items, page suffix to me means body.

I trust Mark, so feel free to go ahead and change the behavior.

// Djamil Legato // From iPhone //

**Comment by marktaylor46** [comment]
thanks :)

**Comment by marktaylor46** [comment]
Great stuff - it works! thanks!
