### ISSUE TITLE
Session expires on the frontend

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#443]
Hmm, it happened twice today, with RC3.

I do not think it is caused by the modifications I have made (only in the layout YAML file).

My installation is on locahost. I loaded the website and then I just left it open in a tab for about 20-30mins. Then when I opened the tab again and clicked on a Menu Item, I got the following error:

```
Notice: A session had already been started - ignoring session_start() in C:\wamp\www\GANTRY5\libraries\joomla\session\session.php on line 665
```

Once I refresh the website, everything works as expected.
The session should not expire on the frontend :)

**Comment by w00fz** [comment]
Is that 20-30 minutes the setting you have on Joomla? Can you try to lower it to 1 minute and see if it still happens?
Also perhaps try with different pages and protostar, just to make sure it is a Gantry issue.

**Comment by JoomFX** [comment]
Yep, just did the tests you mentioned and it seems to be a G5 relate issue:

1. I set the Session to 1min. After 2mins I clicked on a Menu Item and I got the error.
2. I set Protostar as default template. After 2mins I clicked on a Menu Item and I didn't get the error

**Comment by mahagr** [comment]
I've never seen this issue in any of my test sites. Do you happen to have anything else installed, just to be sure there isn't anything else that could cause it?

Gantry 5 does nothing with sessions (as far as I know it), so the issue sounds odd to me.

**Comment by JoomFX** [comment]
Hmm, I did some tests and it does not really seem to be a G5 related issue.

Have a look at [this issue](http://issues.joomla.org/tracker/joomla-cms/5644) in the Joomla Issue Tracker - it is absolutely the same thing as the one I experience.

The issue is not reproducible with the Quickstart Installation of Ethereal, so it is another prove that it is not a G5 related issue.

@mahagr yes, I have some extensions installed. One of them is Kunena :))

The other extension, that I'm almost sure is responsible for this issue is PayPlans. It is a really nice membership extension, but it modifies quite some parts/logic of Joomla.

So feel free to close this issue. My conclusion is that this is caused by PayPlans and hopefully it will not be reproducible on a live server (somehow). Or, since it is just a Warning, I can just set "Error Reporting" to None, even though it is not a real solution :)

But it is still very strange.... I am building this website the last two weeks and I never had this issue before. I was building, or it is better to say configuring, the website on Protostar and I never experienced this issue until I installed G5 RC3 :)

**Comment by mahagr** [comment]
Read the comments in Joomla and it does sound like some plugin is initializing session by its own before Joomla gets into there. And doing that without using Joomla session class.

I just checked Kunena -- it's only using Joomla classes and even those not in system plugin.

Try disabling PayPlans if it fixes the issue. Starting session at wrong time may cause really bad issues as all the user data for the current session may be broken, so try to figure it out rather than just tuning the error reporting. If it only happens on session expire, it would most likely affect only remember me and some form submissions.

**Comment by JoomFX** [comment]
@mahagr Thanks for the explanation Matias, I'll try to figure it out :)
