### ISSUE TITLE
Gantry\Framework\Document::url returns url instead of null

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#444]
When using Gantry\Framework\Document::url with path that can't be found ie.
`Gantry\Framework\Document::url('gantry-assets://wordpress/images/g-icon.png')`
it returns your site ie. http://my-site.com instead of null

**Comment by mahagr** [comment]
Tagged as WP issue as it's the only one which appends domain name to all its urls.

Similar issue may be present also in Joomla, though, so need to check what it does in the same use case.
