### ISSUE TITLE
Template independent SCSS naming

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#445]
I mentioned that a while ago but I will try again :)

In `g5_hydrogen/scss` you have the following files and folders. Their names are Template dependent and should be changed in each Template:

`hydrogen`
`hydrogen-joomla`
`hydrogen.scss`
`hydrogen-joomla.scss`

In Calisto and Ethereal you have changed the above names so they reflect the Template Name.
I don't know how you start a new Template and if you have a tool that renames the files/folders properly but for us, that will start each and every Template with the default Hydrogen, here's what needs to be done in order to properly rename everything so it reflects the Template Name:

1. Rename the files and folders in `g5_hydrogen/scss`
2. Modify several lines in `hydrogen.scss`
3. Modify several lines in `hydrogen-joomla.scss`
4. Modify `theme.yaml`

Wouldn't it be better to have the names of these files and folders Template independent? For example:

`theme`
`theme-joomla`
`theme.scss`
`theme-joomla.scss`

Or another option:

`gantry`
`gantry-joomla`
`gantry.scss`
`gantry-joomla.scss`

If you do not have the one-click tool I mentioned above, I'm sure @arifinrt will be very happy with such change :D

**Comment by federone** [comment]
i agree, its better to have their names as indepedent

**Comment by mahagr** [comment]
@kevlardev @arifinrt @w00fz Your call.

**Comment by mahagr** [comment]
You can freely use template independent names in your own templates. As a developer I do agree that using the same name would be easier to me, too. But the decision was made on using more unique naming and I'm not sure if one time renaming makes it worth to change the current way.

Personally I need something more concrete example on why the decision was not optimal one. One of those could be file overrides, but even they aren't such a big issue with SCSS.

**Comment by JoomFX** [comment]
@mahagr Thanks Matias :)

Yep, it is definitely not a big issue, it is just a personal wish from which will benefit mostly the developers and not the normal user.

I can live with the way it is now I just tried to make you reconsider that, but it seems that there is actually a reason behind that template specific naming.

So yeah, it is up to you to decide how you want it to be. I will just stick with it ;)
