### ISSUE TITLE
Not responsive on android kitkat web browser

### ISSUE THREAD

**Issue by didacticien** [gantry/gantry5#446]
Hi, sorry for my english i'm french !
gantry 5 with hydrogen theme is not responsive in front end on web browser android kitkat! is there something i can do to make it work. For info i just install the latest joomla and gantry5 + hydrogen theme...
thank you

**Comment by JoomFX** [comment]
What is your Opera version?
Probably you are on an old Opera release that does not support Flexbox and other stuff.

Have a look at the [Gantr5 Browser Requiremnt](http://docs.gantry.org/gantry5/basics/system-requirements).

**Comment by didacticien** [comment]
sorry the problem is with the android browser himself not opera...

**Comment by JoomFX** [comment]
Strange...
For me it works just fine and is fully responsive on HTC One (Android 5.0.2, Software Number 7.19.401.2).

What is your Phone Model and Android version?
Also, can you share the link of your website?

**Comment by didacticien** [comment]
samsung S3 and android 4.4.4
website : entreprise-donica.fr

**Comment by alisamii** [comment]
Android browser 4.4 of materialists flexbox.

Android browser 4.2 and 4.3 only support the old specifications of flexbox and do not support wrapping.

http://caniuse.com/#search=Flexbox

Best regards,

Ali

**Comment by JoomFX** [comment]
I just tested your website (default G5 installation) and it is fully responsive.
You can test it on another phone as well.

@w00fz you might want to have a look at it (if you have S3/Android 4.4.4)

**Comment by didacticien** [comment]
yes it's fully responsive but not on my phone... strange and very not useful to developp my site :)

**Comment by alisamii** [comment]
What do you mean by "it isn't responsive". In my tests it also is guilt responsive.

What do you want it too do that it isn't doing?

Best regards,

Ali

**Comment by JoomFX** [comment]
Can you check the settings in your Android browser? 
There is a "Desktop View" setting, can you play with it and see if it is causing the issue.

**Comment by didacticien** [comment]
"Desktop View" setting is not active 
on firefox and other platforms it's working but not on android : i didn't have the mobile menu i still have the normal menu...

**Comment by JoomFX** [comment]
Ok. Go in the Template Manager -> Base Outline -> Styles tabs
Scroll down. What do you have in the "Breakpoints" for the "Mobile Menu"?
Can you change it to 60rem, click on the "Recompile CSS" button and try again?

**Comment by didacticien** [comment]
i put a screenshot on my site...

**Comment by w00fz** [comment]
By Android browser, do you mean Chrome?

**Comment by didacticien** [comment]
i don't think that the default web browser is chrome...

**Comment by w00fz** [comment]
We only support Chrome on Android.
The "Android Browser" is outdated, slow and unpredictable in all possible ways.

I think even Google dropped it and installs Chrome now by default, wonder how you don't have Chrome.

**Comment by JoomFX** [comment]
@w00fz hmm, the default browser on my recently updated HTC One is HTC Browser.
I don't know if this means Chrome or not 
I'm on Android 5.0.2

**Comment by didacticien** [comment]
I have it of course, but most of my visitors are using tablets and phones using this web browser...
on Android 5.0.2 the default web browser was effectively replace by chrome...

**Comment by didacticien** [comment]
@JoomFX : I just try your solution but still not working...

**Comment by w00fz** [comment]
You are also being very vague on what exactly are the issues you are experiencing. What exactly do you mean by "not responsive" and "not working"? Does the site load? Do you mean it's slow or do you mean it shows in desktop mode?

Care to expand?

**Comment by didacticien** [comment]
@w00fz : take a look :
![screenshot_2015-06-09-23-21-13](https://cloud.githubusercontent.com/assets/12820107/8070306/90c383a0-0f00-11e5-82f2-36d67bd26183.png)

**Comment by didacticien** [comment]
![screenshot_2015-06-09-23-21-13](https://cloud.githubusercontent.com/assets/12820107/8070333/ce9b3772-0f00-11e5-9b7c-bce1b5f24173.png)

**Comment by didacticien** [comment]
that's two different points of view with normal view and zoom out...

**Comment by w00fz** [comment]
What do you get here: http://whatsmyuseragent.com/

**Comment by didacticien** [comment]
![screenshot_2015-06-09-23-45-46](https://cloud.githubusercontent.com/assets/12820107/8070494/e0aad0c0-0f01-11e5-9e29-53787ce7fcdc.png)

**Comment by didacticien** [comment]
I'll come back later
Thank you
