### ISSUE TITLE
Change "configuration" to "outline"

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#447]
Using Hydrogen with Gantry 5 RC3. Please see pic when trying to delete "default outline". We need to change configuration to outline here in the popup:

![screen shot 2015-06-09 at 4 08 16 pm](https://cloud.githubusercontent.com/assets/5002814/8069691/e43eac42-0ec1-11e5-8a38-69508756452d.jpg)

**Comment by mahagr** [comment]
This is actually something I forgot to do -- we need to remove the button for deleting default style in Joomla.

**Comment by w00fz** [comment]
Fixed the error message to say `outline` rather than `configuration` and added the logic to determine if an Outline can be deleted or not, i.e., in Joomla it's set to Home.
