### ISSUE TITLE
"input.checkbox" field dont works in collection.list field

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#450]
hi,

"input.checkbox" field dont works in "collection.list" field - when i uncheck field, after saving settings dont saves that field as unchecked

Best Regards,
Federico

**Comment by mahagr** [comment]
Actually it may be more general issue with checkboxes as they only send value if they are true. You can use enable.enable instead, I know it works.

**Comment by w00fz** [comment]
Thanks for opening the issue @federone , it's fixed now and available in the next CI Build if you want to give it a shot.
