### ISSUE TITLE
Too many Atoms looks ugly in Layout

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#451]
hi,

i have a lot of atoms, so in my layout, in "atom" section they dont look good, here is what i mean:

maybe its better to have them full width, or 50% on each atom .... or to have new row option, as offcanvas has ...
![333](https://cloud.githubusercontent.com/assets/1756964/8070888/0a0c34ea-0f16-11e5-93fd-614cbbd7cff0.png)

Best Regards,
Federico

**Comment by alisamii** [comment]
I disagree with full width. It's a lot of wasted space. 50% is also too large. Plus it will make the layout manager far too long.

I think having it display up to five per row, and if there is a need for more than five, then it either automatically breaks/wraps, or you can dynamically add another row is a good idea.

I think five is a good number and very few users will need more than five. @federone being an exception that proves the rule.

Best regards,

Ali

**Comment by federone** [comment]
yes, maybe max-5 or max-4 is good, i just want that they looked readable ...

Best Regards,
Federico

**Comment by alisamii** [comment]
I also hope that we can have atoms that are definable as default, for example for Google analytics or global JavaScript, that we can place in the base outline and set a flag to have them active and placed on all pages by default.
Best regards,

Ali

**Comment by federone** [comment]
> I also hope that we can have atoms that are definable as default,

but its already possible to have them already defined in "Base Outline" in layouts ..... i dont understand what you mean :(

Best Regards,
Federico

**Comment by alisamii** [comment]
Yes, you can set them up with their perimeters, but you need to drag the atom into each layout for it to be active. A globally active Assoon would not need to be dragged into each layout.

Best regards,

Ali

**Comment by w00fz** [comment]
Like discussed before, we will have a Page Setup panel where global things such as Atoms, meta data, favicon and more, will be availble, allowing each outline to inherit directly from there.

It will be possible to have Atoms such as Custom CSS/JS or Analytics in this Page Setup panel and be defined only once.

**Comment by alisamii** [comment]
I think "Page Setup" is misleading. It should be called "Global settings" of "site settings"

Best regards,

Ali

**Comment by adi8i** [comment]
You don't have to place an atom for each script you want to load, you can create a new item instead
http://www.adriandev.com/images/Gantry/gantry5-atom-settings.jpg

**Comment by w00fz** [comment]
Ok now the Atoms section is behaving a bit differently than the others. A maximum of 5 Atoms are displayed per row and the 6th will go in a new row. This is different than a Grid, think of it as a floating, it is still as if it was 1 big row that wraps.

![atoms](https://cloud.githubusercontent.com/assets/11734/9187122/e1e7dc7a-3f81-11e5-889d-683d2cc85d06.jpg)

**Comment by federone** [comment]
thank you so much,

Best regards,
Federico
