### ISSUE TITLE
Enhancement of SCSS Compiler to Minified one

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#452]
hi,

please add in gantry admin global func, where we can compress scss to minified one.

i mean in "libraries/gantry5/classes/Gantry/Component/Stylesheet/ScssCompiler.php" on line 76 to have an alternative "scss_formatter_compressed" option ...

Warm Regards,
Federico

**Comment by mahagr** [comment]
Already planned for production mode. We also plan to add source maps for development mode as it allows you to easily find the file and line of the css rule.

**Comment by federone** [comment]
thank you very much

**Comment by w00fz** [comment]
Closing this since we now have a plan of attack in #535. We will also keep extending the Dev / Prod toggle as things come up
