### ISSUE TITLE
Bug: Mobile menu disappears when outline is duplicated

### ISSUE THREAD

**Issue by Attis35** [gantry/gantry5#453]
Hello Guys,

I've found a bug in the RC3. I've duplicated an outline where the mobile menu function has enabled, than I assigned the new outline(s) for different menu items. The Mobile menu works only with the original outline....
could you please check it?
Thank you!

**Comment by w00fz** [comment]
Does your duplicated Outline have anything in the Offcanvas Section?

**Comment by mahagr** [comment]
I fixed similar issue on loading preset or another outline, but I didn't check the duplicate. It is possible that it has similar bug in it. Also make sure if duplicate has all the other changes you made.

**Comment by Attis35** [comment]
Yes, I've compared the settings an everything is the same, I removed only a simple content in the header section. Offcanvas contains the menu...

**Comment by Attis35** [comment]
Ignore my previous comment. The menu is at the right place, only problem is that the background color changed to white and mobile menu icon is also white...

**Comment by w00fz** [comment]
Ohh! So it was just styling and not a bug per se?

**Comment by Attis35** [comment]
Exactly. Sorry for that! Anyway. Where can I change the color of the mobile menu icon (3 bold lines)?

**Comment by w00fz** [comment]
In Styles :arrow_right: Section Styles :arrow_right: Offcanvas Section :arrow_right:  Toggle Color

**Comment by Attis35** [comment]
Got it, thank you very much!!

**Comment by w00fz** [comment]
You are very welcome!

**Comment by nzimas** [comment]
I've toggled on the background colour in the off-canvas section and the icon is still displaying white on white.
Tested on Chrome 43 for Android.

![screenshot 2015-06-21 23 35 34](https://cloud.githubusercontent.com/assets/6955694/8274814/d5999bb4-186e-11e5-9b0e-eb67ac497c06.png)

**Comment by w00fz** [comment]
Are the front page you are looking at and the outline where you changed the setting matching?


// Djamil Legato // From iPhone //

**Comment by nzimas** [comment]
Yes.

I've edited the setting in the Hydrogen - Default outline, which is the
outline / template style associated with the home menu item.

**Comment by nzimas** [comment]
Solved.
Turns out I had forgotten to change the default fff value in the toggle
colour setting.

**Comment by w00fz** [comment]
Glad you solved it!
