### ISSUE TITLE
Sidebar-mainbody glitch (multi-column layouts)

### ISSUE THREAD

**Issue by bomkallo** [gantry/gantry5#454]
Hello,

I'm playing around with new Gantry and I've found weird behavior (hydrogen template). 
What I did:
1. I did load 2 column layout -> sidebar | mainbody
2. I put two module positions into sidebar section
3. I put page content into mainbody section.
4. Sidebar is set to 20%, the rest 80%.

When I check the test page I see that there are two blocks, size-20 and size-80 which are properly set. Then, inside .size-80 block the .g-container appears, it sets width to 75rem so it doesn't keep the grid anymore.

The screenshot from browser debugger shows the container (I've tried changing many options in blocks/containers but it fails anyway).

http://postimg.org/image/601il7pqr/

The gray area is .size-80 in gray, the blue container is failure I'm trying to solve.

PS: Temporary fix is a little css trick, but I don't think it's the way it should go.

Edit:
Now I'm a bit lost:) I started to switch layouts and dig libraries, then I went Joomla-Gantry4, fanatic saving and realoding took place and then I went back to 2-column to see it working properly...
Former container classed as .g-container changed name to .g-content. I took another override which was broken, loaded g4, loaded 2-col back, reset the mainbody and it works...

If anyone know internals enough then you could enlight me how it may happen:)

**Comment by kevlardev** [comment]
This should have been fixed with the latest RC3 release, were you using RC3 when this problem occurred?

**Comment by bomkallo** [comment]
I've downloaded rc3 on monday or early tuesday and it was my first issue after two reinstalls  I'll keep testing g5 and I'll put input if I find something. I'm a bit disappointed of the fact that gantry is going to be so easy for simple things, in the same time having more complicated layer over more advanced topics. G4 had more balance between, but will see.

**Comment by mahagr** [comment]
@bomkallo If you want to open up what you find as being easy and what you find is hard, we would really like to hear your feedback. The issue with Gantry 5 is that it's still a new product compared to mature G4. So there are also things which we didn't consider or isn't fully finished yet.

To me the most complicated thing in Gantry 5 is its ability to work in multiple platforms, which makes the code structure harder to follow. But I'm not using it to build themes or sites.
