### ISSUE TITLE
You need to import dependencies in custom.scss 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#455]
You need to import dependencies in `custom.scss`, otherwise `variables` can't be used.

**Comment by w00fz** [comment]
That is normal @adi8i, you don't have to import the `_dependencies.scss`, but if you need bourbon or mixins or variables, then yes, you do need to import it.

If you just want simple CSS or just independent SCSS, you can get away with no dependencies at all.

**Comment by adi8i** [comment]
Oh ok :D
