### ISSUE TITLE
Possible Sidebar/Mainbody Combination layout bug

### ISSUE THREAD

**Issue by TGoodrich** [gantry/gantry5#457]
I have a layout with 2 sidebars, one on the left and one on the right of the mainbody. I have not added anything to the right-side sidebar. I do have content added to the left-side sidebar and the mainbody.

I have found that the frontend is not using the widths I set in the layout manager. For example, I set the left sidebar to 25%, the mainbody to 65% and the right sidebar to 10%. When I check the frontend in developer tools the div for the left sidebar reads size-27 and css calculates it at 27%. The mainbody reads size-72 and css 72%. On top of that 27% + 72% only equals 99% so where did that 1% go. 

It seems no matter what width I set the left sidebar to it is always off by +2% of the actual setting. I have no content in the right sidebar so it is understandable there is no output for it on the frontend so the mainbody takes up that extra 10% originally set for the right sidebar. Given this it would appear the mainbody width is off by -3% of actual setting.

Sorry, almost forgot to mention I am testing with Joomla 3.4.1 and Gantry / Hydrogen v5.0.0-rc.3

**Comment by w00fz** [comment]
I see what you mean and I think it is indeed a bug. We aren't rounding up the new determined sizes to fill the gap left by the collapsed sidebar.

Could you try editing the file `libraries/gantry5/classes/Gantry/Framework/Base/ThemeTrait.php`, line 480 [[reference](https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Framework/Base/ThemeTrait.php#L480)]

```php
$child->attributes->size *= $multiplier;
```
to

```php
$child->attributes->size = round($child->attributes->size * $multiplier);
```

And see if that helps in your tests?

**Comment by mahagr** [comment]
Actually that might not fix the issue either. It still rounds down 33.3 - 33.3 - 33.3 = 99

**Comment by TGoodrich** [comment]
Still seems partially bugged, doing a 30% | 60% | 10% results in frontend output of 33% | 67% = 100%.

**Comment by mahagr** [comment]
There's an issue #115 which suggests of making some columns sticky, thus allowing 30% | 70% if another side collapses.

**Comment by mahagr** [comment]
@TGoodrich Please test this with latest CI build.

I'm now taking account cumulating rounding error.
