### ISSUE TITLE
Add Joomla Atomizer to Gantry5 templates

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#460]
Hi,

I am trying to implement Joomla Atomizer (http://joomlatomizr.joomlamino.com/getting-started/manage-your-layouts) which adds a series of classes to the `<body>` tag and also allows me to add a javascript for further customisation of the site and template.

I followed their documentation and modified the template's `index.php` file by adding the following line immediately after `defined('_JEXEC') or die;`:

`JLoader::register("Joomlatomizr", dirname(__FILE__).'/jizr.php');`

I also placed the `jizr.php` file in the root of the `g5_hydrogen` template.

This should have immediately injected a series of classes into the `<body>` tag. The classes are along the following lines:

```
<body class="jizr_lang_en-gb jizr_platform_mac jizr_browser_safari jizr_browserversion_8-0 jizr_joomla_3-2-0 jizr_option_com_content jizr_view_article jizr_menu_check-it-live jizr_menuid_110 jizr_itemid_110 jizr_guest jizr_module_mod_custom jizr_module_mod_custom_manage-your-layouts jizr_module_mod_custom_customize-your-styles jizr_module_mod_custom_add-some-javascript jizr_module_mod_menu jizr_module_mod_breadcrumbs jizr_module_mod_login jizr_article jizr_articleid_6 jizr_categoryid_2 loaded" data-twttr-rendered="true">
```

This is from their **Check it live!** page http://joomlatomizr.joomlamino.com/check-it-live

However, nothing gets added.

**Comment by w00fz** [comment]
You can't really just add it to the `index.php`. That is good for regular templates where the layout is fixed and defined in it. With Gantry 5, however, we do build all dynamically so the `index.php` is merely a Gantry 5 initializer.

What you want to do is to extend the theme by adding your own PHP functions ([follow this tutorial](http://docs.gantry.org/gantry5/advanced/php-functions)) which will allow you to get access to the `jizr`  methods.

To add those classes to the body you will probably also need to override the `page.html.twig` and use those `jizr` methods you have now available to inject them in the `<body>`.
