### ISSUE TITLE
Base Outline - Layout Manager

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#461]
This is somehow in relation to https://github.com/gantry/gantry5/issues/295

1. If you change the settings under the "Styles" tab in the Base Outline, they are applied on the Frontend
2. If you modify the settings/layouts under the "Layouts" tab in the Base Outline, the are not applied on the Frontend (because it "reads" the Default Outline)

Since there is no point in modifying the "Layouts" in the Base Outline, wouldn't it be better to remove the "Layouts" tab (similarly to the Assignments tab) or make the Layout Manager read-only/greyed out in order to prevent confusion?

It really isn't consistent at the moment:

1. Base Outline -> changes under "Styles" tab = changes on the frontend
2. Base Outline -> changes under "Layouts" tab = NO changes on the frontend

And if the user is supposed to edit the "Styles" only in the Default (or other) Outline, then the "Styles" tab might also be greyed-out in the Base Outline.

@mahagr Matias, mate... you explained everything very well in https://github.com/gantry/gantry5/issues/295 but believe me, this Base/Default stuff is confusing.

**Comment by adi8i** [comment]
I agree, base outline have not assignment tab and should not have layout tab too, because there's nothing you can do there. Or is anything that i miss? :)

**Comment by gyvermac** [comment]
I agree too. It took me some time to understand these behavior...

**Comment by mahagr** [comment]
We intend to add a feature soon, which allows users to inherit some sections from base outline layout.

While Layout tab has no use right now, it will not stay like that. I can remove the tab for now, but we need to put it back as soon as we implement layout inheritance.

**Comment by w00fz** [comment]
I think for now we are going to keep it, it will make sense later on when we extend its functionaly further.

**Comment by paulcu** [comment]
I like the concept of the 'base outline' for making global settings and having the features under 'settings' and 'layout' functional. It would also be nice to be able to override those 'base' settings in the 'default' or other theme outlines created. Still wrapping my head around the naming conventions though.

**Comment by UberGruber** [comment]
Sorry for posting on a closed issue, but I find myself a bit confused on this too. How can I add a particle to all existing Outlines, say a Header, a Breadcrumb or whatever Module. Is there a way to update all existing Outlines that are copy/child of "Default" theme? Is Default just a name like "Home" or it really serve as a sort of master/base outline?

**Comment by mahagr** [comment]
Default in Joomla is just a name; Base Outline is the master one.

**Comment by UberGruber** [comment]
I see thank you! But how can I then place in already existing Outlines (generated frome the Base outline) some Particles since the outline tab has been removed from the Basic outline? 

Let's say I want to add a Custom html particle in the footter of all Outlines already made, how can I do that?

**Comment by mahagr** [comment]
Outline tab has been removed until we figure out how to inherit stuff in there so that it's both flexible enough and easy to use. Right now you have to copy particle to all outlines and use default configuration from Settings tab of base. Not optimal, but we have already plans to make it better.

**Comment by UberGruber** [comment]
I see thank you for your clear statement, good work and thank you for answering back!
