### ISSUE TITLE
Menu item name not updating

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#463]

**Comment by mahagr** [comment]
Please provide more information on what you mean as it works in Gantry menu editor.

**Comment by adi8i** [comment]
If you rename menu title in `joomla -> Menus`, the name will not change in front end
![capture](https://cloud.githubusercontent.com/assets/9744973/8131375/92561b96-1122-11e5-92a6-5b7ec8be24ce.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9744973/8131378/9349e474-1122-11e5-9356-1a60829ec20c.PNG)

**Comment by mahagr** [comment]
I think this is the same but as #162
