### ISSUE TITLE
Custom HTML Particle strips the HTML (Module Manager)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#464]
1. Create a new G5 Particle Module and select "Custom HTML" particle
2. Paste the HTML in the field
3. Save the module
4. Click on "Edit Particle" - the HTML has been stripped out

If you do the same from the Layout Manager, the HTML is NOT stripped out.

**Comment by mahagr** [comment]
Doh, need to remove joomla filtering.

**Comment by w00fz** [comment]
Should be good now.

**Comment by bob-ludvigsen** [comment]
Hi
The problem still exists, I have an installation with Joomla! 3.4.3 and Gantry v5.0.1 / g5_hydrogen

The html is stripped on save..

**Comment by kat05** [comment]
reopening this for now, will do some testing in a bit to see if i can replicate

**Comment by w00fz** [comment]
I am not able to reproduce this one.

**Comment by w00fz** [comment]
Can you check the file `modules/mod_gantry5_particle/mod_gantry5_particle.xml` and see if you have the `filter="raw"` for the field:

```xml
<field
    name="particle"
    type="particle"
    filter="raw"
    label="MOD_GANTRY5_PARTICLE_FIELD_PARTICLE_LABEL"
                    description="MOD_GANTRY5_PARTICLE_FIELD_PARTICLE_DESC" />
```

The only reason that would not work is because perhaps the update didn't replace that file. Although this seems to be fine in a 5.0.1 package.

Another thing that comes to mind is that perhaps you have other content plugins interfering and stripping out HTML?

**Comment by bob-ludvigsen** [comment]
The filter="raw" is in that field.
I have a clean installation with only Akeeba and Gantry as extras..
There is no problem in the module manager..

**Comment by w00fz** [comment]
I am not entirely sure why this would be a problem. On my local I cannot reproduce it and being `filter="raw"` it means all the HTML should be preserved.

Would you mind trying out the CI Build? Perhaps is something we fixed after 5.0.1. http://gantry.org/downloads#ci-builds

**Comment by kat05** [comment]
Ok, so 
JoomFX said it's fine in the Layout Manager, so he had the problem in the Module Manager?
bob-ludvigsen says it's NO problem in the Module Manager.
Not sure both are talking about the same issue?

I'll do some testing to see what happens.

**Comment by w00fz** [comment]
This issue was specific to the G5 Particle Module, not the LM in G5 admin. If that's the case then we are talking about a different issue.

**Comment by kat05** [comment]
Ok, I can not replicate an issue with the G5 Particle Module, hebe linked. I guess this can be closed and if @bob-ludvigsen still has an issue maybe he can start a new ticket with more details.

**Comment by w00fz** [comment]
Cheers.

**Comment by huwhuww** [comment]
Hi guys,
I have the same problem right now with everything up to date.
I checked filter=raw is ok
no filter on editor

any idea ?

**Comment by mahagr** [comment]
Joomla shouldn't be filtering content for the field; so I have no idea what it could be. Does it happen with the menu item (Gantry 5 / Custom) as well?

**Comment by huwhuww** [comment]
this is where i got the problem. It only works in layout manager. otherwise html is stripped out when i save.

**Comment by kat05** [comment]
Hi, can you paste the HTML you're using? I am not able to replicate this issue.

**Comment by huwhuww** [comment]
I tried multiple things 
even just <img src="images/blabla.jpg"></img> vanish in outer space

**Comment by mahagr** [comment]
Do you have some plugin that does this clearing? As Joomla shouldn't touch above text.

**Comment by huwhuww** [comment]
So far I just have akeeba installed.

**Comment by mahagr** [comment]
Come and visit us in gitter chat; you can PM directly to me links etc for the site.
