### ISSUE TITLE
Joomla frontend module editor is showing untranslated strings in position dropdown

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#465]
using latest ci build, the position dropdown on the frontend module editor is showing untranslated strings, please see pic

![g5_positions](https://cloud.githubusercontent.com/assets/5719486/8136138/058f152c-10f1-11e5-82c8-23e9a112a94b.jpg)

**Comment by w00fz** [comment]
I'm not even sure where that string is coming from, cannot find it anywhere in the project?

**Comment by mahagr** [comment]
Joomla is automatically guessing those, so we need to add them manually to Joomla on init. Luckily there's a way to do it without modifying files.
