### ISSUE TITLE
Tooltip position is off on the second column of cards in admin

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#467]
Not sure if this happened after last changes in the admin styling but the second 
![hydrogen options gantry5 wordpress wordpress 2015-06-15 09-46-12](https://cloud.githubusercontent.com/assets/1641534/8155406/2ea7f1ea-1344-11e5-83f1-59a03f4b328f.jpg)

Video : https://cloudup.com/cep1-r7EyAF

**Comment by w00fz** [comment]
Yes this is a known issue in just Webkit, Firefox is fine. Webkit seems unable to properly handle pseudos when using the css3 columns. I have plans to rework the tooltips to use JS rather than CSS as they also caused other type of issues.

**Comment by w00fz** [comment]
Was able to fix this with `transform: translateX(0);` in the `.card` elements. Don't remove it. If there's flickering, we need to fix those but that transform is needed.

**Comment by newkind** [comment]
This reopens another ticket with dropdowns being overlapped by other cards.
![hydrogen theme gantry5 wordpress wordpress 2015-06-17 12-04-21](https://cloud.githubusercontent.com/assets/1641534/8204477/2f0c888e-14e9-11e5-87c0-a009ac947a1a.jpg)

**Comment by newkind** [comment]
And most likely this causes another issue with icons tooltip where the tooltip is behind the modal
![hydrogen theme gantry5 wordpress wordpress 2015-06-17 12-10-21](https://cloud.githubusercontent.com/assets/1641534/8204575/eaf69472-14e9-11e5-88c0-aba7b1e4880c.jpg)

**Comment by w00fz** [comment]
The tooltips behind the modal was a completely different issue. When you changed the zIndex of the modal you didn't include popovers and that's why it was behind.

Re the other problem, I know am restricting `translateZ(0)` to the h4 only so the ifx only applies to the tooltips. Should be all good now.

**Comment by newkind** [comment]
looks like it's fixed
