### ISSUE TITLE
Google fonts hardcoded as http://

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#469]
Google font references seem to be hardcoded as http:// instead of just //: (the place I checked was google-fonts.json in /administrator/components/com_gantry5/js

This is an issue since if you are using https you get mixed content warnings in console (particularly Chrome).

@mahagr also mentioned that //: doesn't work in wordpress so he will need to add support for this.

**Comment by mahagr** [comment]
Looks like Gantry already supports this, so we just need to change the URLs not to use scheme.

**Comment by w00fz** [comment]
FYI this is only an issue for the front-end. In admin the fonts are always loaded based on the protocol:

![font](https://cloud.githubusercontent.com/assets/11734/8338578/b3b8875e-1a66-11e5-8017-283b6695f3b0.jpg)

The `google-fonts.js` is a reference for the admin font picker but when it actually loads the file it uses the proper protocol so the reference to that file has nothing to do with the frontend.

Regarding the frontend, yes that was hardcoded and matias just fixed it.

For the admin try with the latest CI Build, there's been webfontsloader updates just recently.
