### ISSUE TITLE
Duplicating outlines does not copy everything

### ISSUE THREAD

**Issue by gospelpowered** [gantry/gantry5#470]
As per https://gitter.im/gantry/gantry5?at=557e0b51873bcf056fb509cb

When copying outlines, the colors, layouts etc don't seem to copy across, i have to re-create the styles, settings and layouts every time.

**Comment by mahagr** [comment]
@gospelpowered Can you test this out? I think it's now copying everything -- and also cleaning up the directories when you remove style.
