### ISSUE TITLE
Clicking on settings of spacer particle results in a 404 error

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#472]
![screen shot on 2015-06-15 at 12_57_52](https://cloud.githubusercontent.com/assets/1498512/8158559/7085dcc0-135e-11e5-8eaa-87c0dd9274d5.png)

**Comment by gyvermac** [comment]
Working for me on build dev-bf1226a10 (jun 14)

**Comment by mahagr** [comment]
Settings for '' <- tells me a lot, you do not have subtype set in your layout. I think it's backwards compatibility issue.

**Comment by w00fz** [comment]
If you edit your `layout.yaml` files, search for `type: spacer` and around there there should also be a `subtype` which you want to be `subtype: spacer`

**Comment by alisamii** [comment]
The `yaml` file that is causing this is:

```
preset:
  image: gantry-admin://images/layouts/default.png

layout:
  outer-wrapper 100:
    inner-wrapper 100:
      header-nav 100:
        header:
          container:
            - spacer
        navigation:
          container:
            - [particle-logo 20, particle-menu 80]

    showcase:
      container:
        - spacer

    feature:
      container:
        - spacer

    main:
      container:
        - system-messages
        - pagecontent

    footer:
      container:
        - spacer

  debug:
    container:
      - spacer

  offcanvas:
    - particle-mobile-menu
```

Where would I add the `subtype` in the shorthand version of the `yaml` file?

**Comment by w00fz** [comment]
You need to look into the compiled `yaml` not the simpler version of it. Look into `template/custom/config/<id>/layout.yaml`, that's what gets used anyway for admin and frontend
