### ISSUE TITLE
Use Custom.css without recompile

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#473]
Is there any way to use a custom.css without have to recompile in admin and without do any change on the soucre?

**Comment by gyvermac** [comment]
Was working on RC3 but no more on CI build (dev-bf1226a10)

**Comment by AbeAlpha** [comment]
How to work on rc3? i need to recompile on every change

**Comment by gyvermac** [comment]
I think : download it and install over your actual installation. Should work.

**Comment by AbeAlpha** [comment]
im using rc3

**Comment by mahagr** [comment]
If you need to recompile every time, check System - Gantry 5 plugin and make sure its on development mode.

Otherwise it should work automatically without need to recompile (as long as filesystem reports the modified time correctly).

**Comment by AbeAlpha** [comment]
ty
