### ISSUE TITLE
Controlling Height 

### ISSUE THREAD

**Issue by vachatterus** [gantry/gantry5#474]
Is there any way to control the height of a position?

**Comment by kevlardev** [comment]
If you mean from the layout manager UI, then no. We don't have any controls or interface for setting fixed heights on particular positions. You could, however, add a classname to the position, then assign fixed height values to those classes via the css.

**Comment by w00fz** [comment]
Alternatively, if you just need a quick and easy fix from the admin, you could use the `Tag Attributes` from the Position Block settings. 

http://docs.gantry.org/gantry5/tutorials/using-block-settings#tag-attributes

Where basically you can hardcode inline CSS with key `style` and value `height: 50px;`

Please note that this is not the best approach, I'd use Kevin's suggestion above and add a classname and style it from the CSS but it's still a valid approach.
