### ISSUE TITLE
We badly need a filter to hide/show only enabled items in Assignments

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#480]
This is really needed! With such amount of items, going through every list to find if something is checked almost wants me to sit and cry ;)

**Comment by mahagr** [comment]
@w00fz Something for you to tackle. :)

**Comment by newkind** [comment]
Awesome works! :) One more thing though - can we don't hide the assignments groups ie. in Post: Terms group parents be visible: Categories, Tags etc. ?
![Uploading Hydrogen Theme ‹ Gantry5 WordPress — WordPress 2015-06-19 09-46-33.jpg…]()

**Comment by w00fz** [comment]
We could but I don't know how. Right now there is no relationship between the "parent" group and its children. The list is just a flat list where groups and items are siblings. I have no way of telling what the corresponding group parent is for the active items.

**Comment by w00fz** [comment]
Ok I created the relationship and made the categories follow the filtered items
