### ISSUE TITLE
Joomla Blank Page Gantry Error (Fresh Install, PHP 5.3)

### ISSUE THREAD

**Issue by Spiderhip** [gantry/gantry5#484]
Hi,

I used rt template with gantry 5. I just get both blank pages on admin and site pages.

I used;

error_reporting(E_ALL | E_STRICT);
 ini_set("display_errors", 1);

codes in index.php to see error.

I get this error on both pages.

Parse error: syntax error, unexpected '[' in /var/www/vhosts/domainname.com/httpdocs/lilyumtip/plugins/system/gantry5/gantry5.php on line 78

Is there a possible solution for this ?

Thank you.

**Comment by w00fz** [comment]
What version of PHP are you using? For Gantry 5 at least PHP 5.4 is required (5.5/5.6 are recommended).

http://docs.gantry.org/gantry5/basics/system-requirements

**Comment by juanmanunez** [comment]
Gracias, de gran ayuda ;)
