### ISSUE TITLE
Can't add a module to submenu unless there are submenus already

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#486]
If you have a level 1 menu item and that item does not have any child items within joomla menu manager then within Gantry 5 menu manager it is not possible to add either a module or particle to that item as a child item. 

To get around this what you have to do is to create a temporary child item in joomla menu manager, then go back to gantry 5 menu manager, click on the level 1 parent, then drag on the module or particle onto that child item. Then go back to joomla menu manager to remove the temporary child item . Thus leaving yourself with a level 1 menu item with only a module/particle as the only child item.

I think it should be possible to drag a module/particle onto to the layout to create it as a child of a menu item somehow (perhaps a "+"? but this might imply you could add menu items too - which you can't).

Needs thinking about best way to resolve this.

![2015-06-20_19-13-01](https://cloud.githubusercontent.com/assets/11683218/8268517/757884c8-1780-11e5-9e73-c9ab7423e2d7.png)

**Comment by w00fz** [comment]
Did you try with the latest CI Build? I implemented this functionality after RC3  so I'm wondering if it's a bug in the new implementation.

// Djamil Legato // From iPhone //

**Comment by marktaylor46** [comment]
I just tried it with latest CI of G5 and hydrogen and it doesn't look any different? At least I don't know how it's supposed to work. I have a single menu item level 1 only called "home" I can't see how you would drag a module as a child of that menu item?

**Comment by adi8i** [comment]
Just click the menu item, is working fine for me :).
![capture](https://cloud.githubusercontent.com/assets/9744973/8269439/cd26a2c4-17b0-11e5-8c98-0257cb09901d.PNG)

**Comment by w00fz** [comment]
Yeah you have to click it to open the sublevel first, like you would do for parents. Then you can drag in there like @adi8i says.

So I think this is the functionality you were asking for and I implemented it but after RC3.

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
// ref #419

**Comment by marktaylor46** [comment]
Indeed it is there and working in CI build. Closing
