### ISSUE TITLE
Login re-direction doesn't work

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#487]
Using Hydrogen and Gantry 5 both RC3.
Using Joomla's Login module if you set "Login Redirection Page" to any menu item other than a blank field then on Login  your NOT redirected and get a 404 error page.

This failed in my Callisto also.

Also failed for this user -> http://www.rockettheme.com/forum/joomla-template-callisto/243677-login-landing-page

**Comment by w00fz** [comment]
This seems to be fine for me, I cannot reproduce with latest Gantry and Hydrogen (5.0.2).
Can you test if this is still an issue for you?

**Comment by DanGthatRokGallery** [comment]
user issue - need long form of URL

**Comment by JoomFX** [comment]
I'm not sure if these are related at all, but still... have a look at the issue I opened in the Joomla CMS repo - https://github.com/joomla/joomla-cms/issues/7204

**Comment by mahagr** [comment]
It's the same issue.
