### ISSUE TITLE
Particles Sidebar / Layout Manager column sizes

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#488]
Using the latest CI build (commit: 7fd7f7ede) the particles sidebar column takes 50% of the screen size. It's great that the sidebar now has a sticky capability, and that the height of the particle buttons has been reduced...but...the width of the sidebar is taking 50% of the page, thus rendering the layout manager's side of the page narrow.

![screen shot on 2015-06-22 at 10_30_15](https://cloud.githubusercontent.com/assets/1498512/8278293/89072526-18ca-11e5-9200-607d20edaef2.png)

The screenshot above is from a display set to 1262x1291.

**Comment by mahagr** [comment]
Unfortunately I'm not able to get the issue in my local environment.

**Comment by gyvermac** [comment]
I have the same issue.

**Comment by gyvermac** [comment]
Working on Chrome / Firefox not on Safari (Yosemite)
Webkit problem ?
