### ISSUE TITLE
Particle instance override not taking effect

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#489]
I have discussed this with @mahagr 

This example is from Ethereal template using RC3 latest CI build on an otherwise unchanged rocketlauncher copy. @mahagr think is more likely a G5 issue than the template

1. go into horizmenu particle setings on the home outline layout.
2. add a tick to add override of menu items and change title and link within an item and apply and save
3. clear cache
4. look at front end - details have not changed.

Observation: you can add classes/id to that same particle and they do show up on frontend - it's only the items within it that have this issue.

![2015-06-22_11-52-29](https://cloud.githubusercontent.com/assets/11683218/8280559/4be232ce-18d6-11e5-949f-69a942876710.png)
![2015-06-22_11-53-57](https://cloud.githubusercontent.com/assets/11683218/8280564/4ea1be58-18d6-11e5-9b99-4dd5c1e1f770.png)

**Comment by marktaylor46** [comment]
btw RT site reference http://www.rockettheme.com/forum/joomla-template-ethereal/243305-horizontal-menu?start=10#1211969

**Comment by marktaylor46** [comment]
Another topic with same issue here http://www.rockettheme.com/forum/joomla-template-ethereal/244350-login-error-template-layout?start=0#1217132

Despite horizmenu particle settings in base layout, default template layout and particle instance on layout all being empty it stills hows "features, gantry5 etc etc"

**Comment by kat05** [comment]
i tried this in ambrosia which is using the horizontal menu particle at the top right and even when i change from 'Features' to 'FeaturesXXXX' in AMBROSIA-DEMO override and 'BASE OUTLINE' and 'AMBROSIA-DEFAULT' it WONT SHOW the change on frontend for me.

i also tried adding a NEW ITEM to all 3 outlines (base, demo, default) and it wont show up.

**Comment by marktaylor46** [comment]
Please note the issue seems to be specific to the horizmenu particle - regardless of what template that is in. e.g. ethereal has same issue too.

**Comment by pdubois95** [comment]
I've just hit this exact bug.  Where are the menu items stored in this particle?

**Comment by mahagr** [comment]
I think the only way to currently work around this issue is to override all the settings (with different value than default) in the same level. Really need to fix this bug in the next version...

**Comment by pdubois95** [comment]
Editing the file './config/default/particles/horizontalmenu.yaml' directly appears to work.  These modifications do not appear in the control panel however.

**Comment by marktaylor46** [comment]
Another member with same issue here http://www.rockettheme.com/forum/joomla-template-ambrosia/244875-ambrosia-slideshow-and-logo?start=10#1219894

**Comment by pdubois95** [comment]
So, from the perspective of someone who is not familiar with Gantry specifically - It looks like the new configuration for this particle is not being replicated properly. 

The file that is being modified : 
./custom/config/10/layout.yaml

The file that apparently also needs to be modified : 
./config/default/particles/horizontalmenu.yaml

What mechanism should this particle be using to ensure both files have matching configurations?

**Comment by marktaylor46** [comment]
@maghr is aware what the issue is it is to do with "nested structures" - he will get to it in due course.

**Comment by pdubois95** [comment]
Indeed, but I need this patched soon and from what I see this ticket has been open for a month already.  If I can help out I'd like to.

**Comment by marktaylor46** [comment]
Another member with same issue [url]http://www.rockettheme.com/forum/joomla-template-ambrosia/244876-can-t-save-the-change-on-the-template?start=20#1220070[/url]

**Comment by pdubois95** [comment]
Any movement on this issue?

**Comment by marktaylor46** [comment]
Any movement would be shown here on the issue - so no not as yet sorry.

Regards, Mark.

**Comment by mahagr** [comment]
I've been on my vacation, so no progress here.

**Comment by DanGthatRokGallery** [comment]
I've actually tested this solution for Ethereal -> http://www.rockettheme.com/forum/joomla-template-ethereal/245374-horizontal-menu#1222275  and it seems to work. I also tried this on ambrosia and it worked there also

**Comment by mahagr** [comment]
@DanGthatRokGallery So the bug fix needs to be done to Ethereal template, not into Gantry?

**Comment by kevlardev** [comment]
Yes, this isnt a Gantry issue, but rather a typo in the custom particles created in those templates. Im updating each of the affected themes with the corrections.

**Comment by pdubois95** [comment]
I don't see a new changelog for ambrosia - will this fix be pushed soon ?
