### ISSUE TITLE
Section Fullwidth

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#493]
Section Full Width is not working as expected, it only puts the background to the full-width and particles and content in it are the same fix size, i also tried putting the particle to full-width in variations but that's not working either ...

**Comment by marktaylor46** [comment]
+1

"fullwidth" should behave the same as in Gantry 4 templates - i.e. a fullwidth position/section should have all the content occupying the fullwidth.

I also acknowledge that some people may only want the background to be fullwidth - therefore I sugest that the existing "fulliwidth" option be renamed to "fullwidth-background" and that a new "fullwidth" option be added that does just that.

**Comment by alisamii** [comment]
I second that, and would add that there are instances where you may need a full-width background image that sits behind 2 sections, in a nested section structure as in this screenshot:

![screen shot on 2015-06-24 at 13_07_40](https://cloud.githubusercontent.com/assets/1498512/8328595/622e405c-1a72-11e5-8058-2ba5bcf3924f.png)

**Comment by marktaylor46** [comment]
We've just has a very long internal debate about this and @kevlardev has come up with this proposal:

"add a third option to the toggle, that removes the g-container, so we have 1) Boxed 2) Fullwidth - Background 3) Fullwidth - Content"

Those options would then seem to meet the requirements  of most people.

Purely as an illustrative example - this site link (provided by Henning) illustrate what members are trying to achieve... https://www.forthebright.gr/index.html

**Comment by DanGthatRokGallery** [comment]
I second the 3-option toggle - a good compromise between a fast and functional template that behaves the same for everybody when installed but still allows user customization.
