### ISSUE TITLE
hydrogen theme - menu items and header section's height

### ISSUE THREAD

**Issue by nzimas** [gantry/gantry5#495]
Where can I control de height of the menu items background and also the height of the entire header section?
Does it require custom CSS rules? Of so, which classes must be overridden?

My aim is to make the whole header + navigation sections a lot shorter.

**Comment by adi8i** [comment]
1) You could try to add block variations `no margin` and/or `no padding`.
2) Target `#g-navigation .g-content` and add padding / margin top and bottom `0`.
3) From block setting add tag attributes.

**Comment by w00fz** [comment]
Best way to achieve that is via `custom.scss` ([more info](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet))

You can also get more informations regarding the `Tag Attributes` in #474
