### ISSUE TITLE
Gantry 5: Object returned by JApplicationSite::getTemplate(​true) is not compatible

### ISSUE THREAD

**Issue by charleyhankins** [gantry/gantry5#499]
I started receiving this error upon loggin in.

This began occurring after I upgraded to Gantry 5 with Callisto theme and upgraded to PHP 5.4.

The error was resolved after disabling and uninstalling NoNumber Advanced Template Module.

Thanks w00fz for all your help!

CH

**Comment by w00fz** [comment]
Thanks for opening the issue. Did you mean Joomla 3.4 instead of PHP?

**Comment by charleyhankins** [comment]
ACK!  Indeed I did.
PHP 5.4
Joomla 3.4
Thanks!
CH

**Comment by mahagr** [comment]
@nonumber This is the bug we talked about in JAB15. 

Function JApplicationSite::getTemplate(true) returns id and home parameters in J3.4, which are missing in ATM:

https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L477

Our code needs to know the current style that is being used in order to work properly; otherwise I've already implemented basic support for ATM.

**Comment by nonumber** [comment]
Advanced Template Manager doesn't override the getTemplate method.
I think you'll find the difference is bettween the JApplicationAdministrator::getTemplate(true) and JApplicationSite::getTemplate(true).
...

**Comment by mahagr** [comment]
@nonumber

Alright, I tracked down the issue a bit further and it looks that every extension using ```JFactory::getApplication()->setTemplate()``` will cause the two parameters ```id``` and ```home``` to be lost.

Thanks Peter, I think that I just need to stick on plan B then.

**Comment by nonumber** [comment]
Ok, great :)

Let me know if there is something I should fix from my side.

**Comment by marktaylor46** [comment]
Another RT member with same issue here:
http://www.rockettheme.com/forum/joomla-template-callisto/244306-gantry-5-compatibility-with-virtuemart-3-0-9?start=0#1215810

**Comment by canadaonline** [comment]
@mahagr Good day, I was wondering if you have had an opportunity to look at this bug?  Also I am about to launch on September 1st 
http://gamerforces.com 

I understand that you guys do your best and I appreciate that, if you could please be so kind to tell me how to disable errors from Gantry if the bug is not resolved soon.  Thank you in advance for your response and have a great day and weekend!

Cheers!
CanadaOnline

**Comment by mahagr** [comment]
I'll get this one fixed before that time. Promise!

**Comment by canadaonline** [comment]
Thank you, you rock! :)

**Comment by mahagr** [comment]
I've still not had change to fix this issue as we had some more serious issues just before the release, but now that I'm not busy anymore, I'll make sure we have a solution on Monday. Sorry that it didn't make it into the release, but we are planning another release next week and if you cannot work with CI builds, I can easily make 5.1.1-1 build just for you. :)

**Comment by canadaonline** [comment]
Good day,

Thank you and hope we are still on track for Monday.  When you have the fix ready if you could please be so kind to make 5.1.1-1 build would be awesome.  Once again thank you so much and have a great day!

Cheers!
CanadaOnline

**Comment by mahagr** [comment]
@canadaonline we ran into major bug in the last release so I've been on it the whole day. If you do not have any side effects in your site, you can hide the error message for now until I get all those other issues fixed (use 5.1.0).

Just comment out ```libraries/gantry5/classes/Gantry/Framework/Outlines.php``` line 78.

    // $app->enqueueMessage(sprintf('Gantry 5: Object returned by JApplicationSite::getTemplate(true) is not compatible with Joomla %s API, guessing style Id.', JVERSION), 'notice');

**Comment by canadaonline** [comment]
Thank you :-D

**Comment by canadaonline** [comment]
@mahagr I do not have and Outlines.php file located at 

libraries/gantry5/classes/Gantry/Framework

**Comment by w00fz** [comment]
It's `Configurations.php` the file, not `Outlines.php`, same path.

**Comment by canadaonline** [comment]
@w00fz Thank you, worked like a charm until you guys get the fix.  Keep up the great work guys!

Cheers!

CanadaOnline

**Comment by w00fz** [comment]
:arrow_up: wrong issue reference sorry.

**Comment by mahagr** [comment]
Actually I renamed the Class in 5.1.1, which is why it didn't match in older version.

I will update the issue when I get back to this.

**Comment by canadaonline** [comment]
Thank you for the resolution, you guys are awesome!

Cheers!

**Comment by mahagr** [comment]
Let me know if there are any side effects. I've tried to look if it breaks anything, but I think I got all the cases where it might.

**Comment by canadaonline** [comment]
@mahagr Could you please do the 5.1.2-1 as I don't do CI atm.  Thank you in advance!

Cheers!

**Comment by mahagr** [comment]
Ping me on gitter.
