### ISSUE TITLE
Copy properties from a particle to another in the Layout Manager

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#50]
Showcase (and others) has 1 Sample Content module.
I would like to have 2 more exact copies (for example) of this block on the same row instead of dragging 2 positions from left sidebar, then copying the content of the existing to the newly created ones.
By replicating If there exists 2 blocks they will share 50% of the space, 33% for 3 etc.
Can you have add a button on the block for this task?

**Comment by mahagr** [comment]
We already have internal task to do this. Yeah, it will make life a lot easier as often particles may share the same configuration / information.

There is also a task (and unfinished branch) for making adding particles to keep the portions in layout manager.

Thanks for noticing! Proves that someone is actually trying to test our betas. :) It makes me so happy!

**Comment by adi8i** [comment]
You can consider to add a Link for images too . I mean on sample content you can add : image; headline; description , link, link text, but you can't add a link to image.  So when i click the image i go to a specific location

**Comment by w00fz** [comment]
This is now possible with Inheritance. As it is now you need to Inherit attributes and then uncheck the attributes, in order to copy them. But we are working on adding a shortcut for that so you can open the particle settings and pick to `copy from...` directly.

See https://github.com/gantry/gantry5/issues/1312

**Comment by JoelAzaria** [comment]
@w00fz this is not currently possible.  Per @mahagr here https://github.com/gantry/gantry5/issues/1312#issuecomment-223020767 the logic was an issue and copying on the same layout is an issue.
Sooo...  was this done somewhere else?   Or is there a way to do it that I'm just not finding???
