### ISSUE TITLE
Gantry 5 To Top - Possible Bug

### ISSUE THREAD

**Issue by TGoodrich** [gantry/gantry5#500]
I am using the latest Gantry 5 and Hydrogen RC and found what might be a bug with the To Top particle.

On the home page the To Top works as expected. You click it and the page will scroll to the top of the page.

For all other pages, when you click the To Top it does not scroll up but instead redirects back to the homepage.

I could not find a way to fix this in the template manager as the only options for this particle are for the purpose of styling.

**Comment by w00fz** [comment]
Can you inspect in the subpages how the ToTop renders? The `href` of ToTop is `#`, that doesn't make the page redirect so there must be something else interfering.

**Comment by TGoodrich** [comment]
Here is the HTML for the tag as it appears in google chrome's inspector:

<a href="#" id="g-totop" rel="nofollow"><span><i class="fa fa-chevron-up"></i></span></a>

While on a subpage, when I mouse over the the chevron up symbol I see:

mydomain.com/# in the lower left of the browser window. It is the same for the homepage.

**Comment by TGoodrich** [comment]
Sorry my html was removed, not sure how to add that into the issue description propery

**Comment by w00fz** [comment]
See the Code section in https://guides.github.com/features/mastering-markdown/

**Comment by TGoodrich** [comment]
Great thanks, edited above and added the link code. Hope it helps

**Comment by w00fz** [comment]
This seems to be working fine for me. What are your SEO Settings? 
Also do you happen to have any plugin that rewrites the links?  Another thing you could do is to make sure the file `media/gantry5/engines/nucleus/particles/totop.html.twig` looks like the one in https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/particles/totop.html.twig

**Comment by TGoodrich** [comment]
Maybe it's a server issue? My twig file looks the same and I do have joomla SEF turned on. Other than that I am using arkeditor, jevents, modules anywhere, components anywhere, and roksprocket. Nothing in .htaccess.

**Comment by alisamii** [comment]
There are incompatibilities with the NoNumber suite of extensions. Perhaps your problems are related top that.

Until those issued are solved, I for one have refrained from installing those extensions.

Best regards,

Ali

**Comment by TGoodrich** [comment]
If it helps this problem occurred before installing the NoNumber Extensions. Looking back the only extension I had installed when I first noticed the problem was the Ark Editor.

**Comment by TGoodrich** [comment]
Update: Disabled the Ark Editor and it made no difference. I then re-enabled it and went into Joomla's Global Configuration > SEO Settings and turned off SEF Urls. I retested and the To Top started working properly. I then Turned Joomla's SEF URL's back on and now the problem has returned.

**Comment by w00fz** [comment]
This is now fixed @TGoodrich , I also enhanched it a little bit, it now smoothscrolls to the top.
