### ISSUE TITLE
Box-sizing CSS causes jomsocial content to overflow container

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#502]
Please see there two topcis on RT forum:

http://www.rockettheme.com/forum/joomla-template-callisto-solved-threads/243402-solved-gantry-5-and-jomsocial?start=0#1210566

http://www.rockettheme.com/forum/joomla-template-callisto/241714-jomsocial-layout-problem?start=0#1201743

It it cause by the use of "box-sizing: content-box;" whereas jomsocial needs "box-sizing: border-box;"

This is fix that I used:

.jomsocial *, .jomsocial *::before, .jomsocial *::after {
    box-sizing: border-box !important;
}

I also believe this affects other third-party extensions such as K2 too. 

![2015-06-26_09-29-44](https://cloud.githubusercontent.com/assets/11683218/8373608/33c6c20a-1be6-11e5-8e28-ec2ec0c98711.png)

**Comment by Bokelmann** [comment]
The CSS of Gantry 5 is designed for the future. So nucleus.css is forcing box-sizing: border-box;
this allows Gantry to use a very stripped down and simple html structure that can use paddings and borders in a flexible way.

*, *::before, *::after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

however most Joomla-components expect to use box-sizing: content-box;

so gantry needs to set box-sizing: border-box; back to box-sizing: content-box in joomla.css

.platform-content *, .platform-content *::before, .platform-content *::after {
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}

Now JomSocial is using Border-box
(/components/com_community/templates/jomsocial/assets/css/style.css)

.jomsocial *, .jomsocial *:before, .jomsocial *:after {
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

But that rule has a small css-specificity value. I really think JomSocial needs to increase that. They should have in mind that modern templates will use border-box; and extensions will use box-sizing: content-box;.

so I see two options: 
1. JomSocial should increase css-specificity.
2. we start to add a 3rd-party.scss with fixes for all kinds of issues for Joomla components
and add Mark's fix.
As we know over time this concept tends to produce issues with different versions etc.

**Comment by mahagr** [comment]
Well explained @Bokelmann, I've already given link of this bug to JomSocial team.

**Comment by marktaylor46** [comment]
excellent analysis @Bokelmann - thanks :)

**Comment by marktaylor46** [comment]
We've also has another third-party product have issues too "Joobi" - again to overcome this it was necessary to write this CSS:

.com_jmarket .platform-content *, 
.com_jmarket .platform-content *:before, 
.com_jmarket .platform-content *:after {
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
box-sizing: border-box;
}

Obviously it doesn't seem practical for us to expect all third-party developers to chang etheir products to be compatible with Gantry 5. On the other hand, we certainly don't want to be maintaining a list of third-party CSS patches either within Gantry 5.

Not sure what solution is. One for @kevlardev me thinks.

**Comment by Bokelmann** [comment]
just as an idea I want to throw in:
https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by harry-saputra** [comment]
Thanks for the suggestion @Bokelmann , JomSocial will add more specificity value (we still have one level wrapper up from .jomsocial ) to solve this issue.

**Comment by w00fz** [comment]
I know @kevlardev has been looking at many different ways to handle this and it's not an easy task to foresee how extensions are going to be handling the `box-sizing`, making the whole templating kind of hard.

Thank you guys for the suggestions in here, I assigned Kevin to this so he can take a look and provide with more details.

**Comment by kevlardev** [comment]
Ive retooled this a bit to combine a few approaches that should hopefully provide better fallbacks for all conditions as well as have better third party behaviors regardless of which box sizing they are reyling on. It's not a silver bullet, but im hoping this will be cleaner than the previous approach.

**Comment by mahagr** [comment]
@marktaylor46, @Bokelmann Please test this out. :)

I'm closing this issue as JomSocial team said that they have already fixed the issue in their end.
