### ISSUE TITLE
Menu editor does not show menu subtitle in preview

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#503]
when adding either a menu icon or menu image, they will both show in the menu editor preview.
when adding a menu subtitle, it will not be shown.

please see pic for a better explanation.

![g5_subtitlepreview](https://cloud.githubusercontent.com/assets/5719486/8381670/71fddb98-1c2d-11e5-8c4a-af4882f72c3d.jpg)

**Comment by mahagr** [comment]
Not really sure if its a bug as we aren't attempting to reproduce frontend menu, just to have approximation on it. Will keep this as improvement request.

**Comment by w00fz** [comment]
Implemented this.
