### ISSUE TITLE
Badges for G5 particle module in module manager

### ISSUE THREAD

**Issue by muffindcc** [gantry/gantry5#504]
With RokSprocket, we display the layout type in the module manager, I was curious as to whether we can/should do the same for G5 particles, so you can see what G5 particle corresponds to which module, directly in the module manager.

![screen shot 2015-06-26 at 19 06 16](https://cloud.githubusercontent.com/assets/5719481/8384115/acca4e10-1c36-11e5-9d9c-dc51446b0886.jpg)

**Comment by muffindcc** [comment]
Not sure if this is related, but with the new badges, I now get the following error in the Module Manager: Notice: Trying to get property of non-object in /../platforms/joomla/plg_system_gantry5/gantry5.php on line 103

**Comment by kat05** [comment]
i can confirm this one, also seeing that notice with error reporting set to development.

![g5_badgenotice](https://cloud.githubusercontent.com/assets/5719486/8412868/0611cb8a-1e8d-11e5-949c-d63d71b05615.jpg)

**Comment by w00fz** [comment]
I couldn't reproduce this but I applied a fix, please give it a try.
