### ISSUE TITLE
Module instance vs Enter and hovering

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#505]
I don't know if the following is intended.
1. Place a **Module Instance** particle. Edit it. Clicking in **Block/Variations** and accidentally pressing **Enter** the particle opens **Pick a module** window.
2. On the other hand if you click in **Block/Variations** and press **Enter** while hovering the mouse over any options drop-down elements will be placed in variations box.

**Comment by mahagr** [comment]
I'm not sure either. @w00fz may know better, but he's at his well deserved vacation.
