### ISSUE TITLE
Swipe to open offcanvas menu takes priority over other swipe functions

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#510]
i am not sure if this is a legit issue but thought it's worth mentioning as it got me confused after expecting a different behavior.

for example in our upcoming template, when viewing the frontpage roksprocket features module at the top on mobile and swiping from right to left, roksprocket will navigate to the next slide which is correct.

now, when swiping from left to right, i would expect to navigate to the previous image of the slideshow, however, the swipe will open the offcanvas menu.

not sure if this is considered an issue, for sure it's a little confusing. :)

**Comment by w00fz** [comment]
This is mostly RokSprocket. The main issue is that there isn't a `swipe` event per se, so each implementation can be different and they might conflict with each other.
This should be handled by the template/extension. I did so in the current template and should be fine.

**Comment by w00fz** [comment]
For future references, an option has been added as per #559 request and in case of an issue like the above, the G5 swipe gesture can be disabled to not mess with RokSprocket (in this case).
