### ISSUE TITLE
Need a way to identify "print" popup with CSS

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#511]
When you click on the "print" button of an article you get a popup that shows the article before it is printed. If you want to apply some CSS styling to this page then you need a way of identifying that page (say a class on the body tag).

With Gantry 4 we used to be able to do this using the ID of "component-body" but with Gantry 5 there is no such ID and all the other classes that do appear on the body tag also exist on other pages too -i.e. there is nothing "unique" on the body tag that you can use in CSS.

As an example, if you look at callsto demo on the blog page and click on the print button to get the popup you will see that the background is black - if you wanted to change the color of this to white (as member in RT forum did) then it's hard to see how you could write any CSS that would be unique to just that page.

**Comment by adi8i** [comment]
Print is defined like this: 
```
@media print {
	#g-feature {
		background: #fff !important;
		color: #000 !important;
	}
}
```

**Comment by marktaylor46** [comment]
Nope - not the actual print - but the popup box showing the article before you print it @media print will only apply to the printed output - not the popup.

**Comment by Bokelmann** [comment]
@w00fz adi8i  you are completly missing the point.
It's about integrating standard joomla behavior for gantry.
We need a a hook for tmpl=xy uses ... that may even not be a print usecase

**Comment by w00fz** [comment]
It now renders a class `print-mode` in that print preview mode.

**Comment by marktaylor46** [comment]
That's great! Thanks so much @w00fz
