### ISSUE TITLE
GANTRY5_EDIT_PLATFORM_PARTICLE

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#512]
please see pic, using latest CI

![g5_string](https://cloud.githubusercontent.com/assets/5719486/8413097/5edea336-1e8e-11e5-80ff-974d923084d0.jpg)

**Comment by mariantanase** [comment]
It seems that is a similar issue of #498, some single quotes are missplaced.

**Comment by kat05** [comment]
ah sweet, thanks for that!

**Comment by adi8i** [comment]
https://github.com/gantry/gantry5/blob/develop/platforms/common/templates/forms/fields/gantry/particle.html.twig 

This should be the file, but i don't see what's wrong here :)
