### ISSUE TITLE
REQUEST: Menu item font size

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#513]
We often need to set font size of menu items. This is necessary especially for RTL sites as they need bigger ones.
Without any custom styling can such a feature be added to **styles of base outline** so that we can easily adjust it per layout.

**Comment by JoomFX** [comment]
I'm including instructions how to do this as an example in the Blog Post I'm writing for the G5 Blog.

**Comment by sural98** [comment]
Thanks

**Comment by w00fz** [comment]
Why can't you use the Block tab for that? You can either add a custom `class name` or just use the `Tag Attributes`.
I don't think it's worth adding a new parameter for font size, it's so very specific to a theme context...

references:
 - [CSS Classes](http://docs.gantry.org/gantry5/tutorials/using-block-settings#css-classes)
 - [Tag Attributes](http://docs.gantry.org/gantry5/tutorials/using-block-settings#tag-attributes)
