### ISSUE TITLE
Yaml layout settings problem in 2 different containers what contain sidebars in both of containers.

### ISSUE THREAD

**Issue by GESign** [gantry/gantry5#514]
Ihave a problem with yaml layout settings in containers. It looks like I can not make 2 different containers where both of the container are containing sidebars. The second one is missing on the layout. I tried to use this setting in yaml file:

preset:
  image: gantry-admin://images/layouts/default.png

layout:

    container:
        1:
            - header 40:
                - particle-logo
            - sidebar 60:
                - particle-menu
                - [particle-social 50, position-lang 50]

    navigation:
        container:
            - position-navigation

    container:
        1:
            - main 80:
                - position-breadcrumbs
                - system-messages
                - pagecontent
            - sidebarmain 20:
                - position-sidebar

    footer:
        container:
            - position-footer
            - [particle-copyright 40, spacer 30, particle-branding 30]

    offcanvas:
        - particle-mobile-menu

Could You help me with this problem, please.

Best regards,
Andrew

**Comment by adi8i** [comment]
I am not either, this code will work,but don't thik is the best solution, should allow us to change the nr inside container, ex: 0,1 or use `-` @mahagr .
```
container-1:
    1:
      - sidebar 20:
         - position-sidebar
      - main 80:
          - position-breadcrumbs
          - system-messages
          - pagecontent
```

**Comment by GESign** [comment]
Dear adi8i,

It solved my problem perfectly!!! Thank You very much!

I use this code now and it works:
preset:
  image: gantry-admin://images/layouts/default.png

layout:

    container:
        1:
            - header 40:
                - particle-logo
            - sidebar 60:
                - particle-menu
                - [particle-social 50, position-lang 50]

    navigation:
        container:
            - position-navigation

    container-1:
        2:
            - main 80:
                - position-breadcrumbs
                - system-messages
                - pagecontent
            - sidebarmain 20:
                - position-sidebar

    footer:
        container:
            - position-footer
            - [particle-copyright 40, spacer 30, particle-branding 30]

    offcanvas:
        - particle-mobile-menu


I will move sidebars into new sidebar.
Case can be closed.
