### ISSUE TITLE
Cannot modify header information - headers already sent by ...

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#515]
Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/gantry5/callisto/wordpress/wp-admin/includes/template.php:1935)

both ryan and i are getting this error in the wp-admin when trying to access the g5 theme settings for either hydrogen or callisto.

![g5_wp_headerinfo](https://cloud.githubusercontent.com/assets/5719486/8451823/7583da26-1fe6-11e5-92d6-40ad157ac09c.jpg)

both ryan and i are running our installs on mamp pro as core wordpress installs with gantry 5 and callisto hebe linked. enabling or disabling xdebug does not make any difference.

**Comment by kat05** [comment]
during some earlier testing on jun-18 (see hipchat) i mentioned the following:

> in /git/gantry5/src/platforms/wordpress/Admin/Router.php i commented out line 102 and 103 and now the g5 admin loads fine... well not fine but at least i can see something.

it allowed me to see the first panel...

![g5_wp_onepanel](https://cloud.githubusercontent.com/assets/5719486/8452038/21971e8a-1fe8-11e5-9a7f-e9175464f8e9.jpg)

however, switching to another panel, caused a different error...

![g5_wp_nextpanel jpg](https://cloud.githubusercontent.com/assets/5719486/8452081/64b7f4be-1fe8-11e5-9f2b-2b5c197fb166.jpg)

**Comment by kat05** [comment]
so basically for both ryan and myself, the wp admin panel does not work at the moment.

**Comment by mahagr** [comment]
Should be fixed in aef6d9e

**Comment by kat05** [comment]
i can confirm that this header error is fixed, using php 5.6
as mentioned on hipchat there is a different error still happening with php 5.5.
anyways, this one is confirmed as fixed. :)

**Comment by mahagr** [comment]
I believe that we already solved twig caching issue which was your 5.5 issue?
