### ISSUE TITLE
intermittent/random "Obtaining write lock failed"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#516]
@mahagr requested I raise this issue in respect of:
http://www.rockettheme.com/forum/joomla-template-callisto/244073-twig-error-runtime?start=0#1214659

This site is experiencing intermittent and random occurrence of this error

![2015-07-01_11-41-50](https://cloud.githubusercontent.com/assets/11683218/8452879/9e1c6e8a-1fe6-11e5-9413-0f72abe536a7.png)

Sometimes you have to refresh of change page 20 times before it occurs but it happens often. After receiving the error you can then refresh the page and the error will go again.

**Comment by mahagr** [comment]
Try / Catch is missing on CompiledYamlFile class (or in the parent).

**Comment by marktaylor46** [comment]
link to members's site is http://www.eeco.it/NEW4/

Forum topic is http://www.rockettheme.com/forum/joomla-template-callisto/244073-twig-error-runtime?start=0#1219521

**Comment by mahagr** [comment]
The issue for the user went away by enabling production mode. This time the issue was obtaining write link for the SCSS cache file, which contains meta information from the files which were used to get the final CSS.

**Comment by mahagr** [comment]
Above should fix the issue as well as making first page loads faster.
