### ISSUE TITLE
Error trying to access a menu setting

### ISSUE THREAD

**Issue by gyvermac** [gantry/gantry5#52]
I wanted to see if it was possible to had a custom class to a menu (to make it fixed) but I get this error when I clic on the parameter button of a main menu (working on submenus).
![capture d ecran 2015-04-03 a 13 41 22](https://cloud.githubusercontent.com/assets/11781634/6981790/efb7d13c-da07-11e4-835f-2cc72edad39e.png)

With unofficial Beta 2 / joomla 3.4.1

**Comment by mariantanase** [comment]
Confirm, I receive the same error, on a fresh install.
Tested with unofficial beta 2 on j341 [Firefox Developer 38.0a2]

**Comment by w00fz** [comment]
Thanks!

**Comment by mariantanase** [comment]
yes, is working now
