### ISSUE TITLE
Flush class is not working with section class

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#522]
I think there should be this available as its in home layout ...

![2015-07-02 12 39 22](https://cloud.githubusercontent.com/assets/10489911/8475331/9b0fcb5c-20b7-11e5-935c-2a15793ef618.jpg)

**Comment by DamirPecnik** [comment]
ok i see this is applied like this:
```
.flush .g-container > .g-grid > .g-block > .g-content {
  margin: 0;
  padding: 0;
}
```
so flush is applied to all of the section inner content and particles but not the section it self? Is this the way it suppose to work or?

**Comment by kevlardev** [comment]
This was how it was designed to function, its a class to remove all the inner content paddings of blocks for a tighter arrangement of blocks when using this layout approach with particles (as the individual block items in particle output cant as easily be classed with variations like nomarginall/nopaddingall
