### ISSUE TITLE
Recompile css at Layout tab

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#523]
Can you please add the same button to the layout tab also as we do most of our work at this tab?
Better off it would be under Extras.

**Comment by mahagr** [comment]
Not sure why you would like to recompile CSS from layout tab as the only occasion where you need to recompile CSS is when you change the settings.

In development mode changes should be picked up automatically.. Though in the production mode it may be useful feature...

**Comment by w00fz** [comment]
I don't like this either, there is nothing in Layout that is ever going to be tied to the recompilation of SCSS and as mentioned by Matias, you can always switch to Dev mode (from any panel) and have SCSS recompile automatically.
