### ISSUE TITLE
#__update_sites lists gantry 5 twice

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#524]
for some reason, gantry 5 gets listed twice in the update sites screen.

![g5_updates](https://cloud.githubusercontent.com/assets/5719486/8481487/a176df90-20e3-11e5-82e5-a049b8b1b984.jpg)

**Comment by mahagr** [comment]
Does this happen after installing Gantry or just in RocketLaunchers?

**Comment by kat05** [comment]
i saw it with demo/launcher packages of our upcoming template and also with core joomla install and latest gantry ci build.

**Comment by mahagr** [comment]
I'm starting to think that this comes from the fact that we are using the same update stream in both Gantry5 and Hydrogen, which is totally ok.

Having it listed 2 times should not have any side effects, so I'm not sure if this is a bug.

**Comment by mahagr** [comment]
Not considering this a bug.
