### ISSUE TITLE
How to set  CSS classes parameters in Media Quiries? (Where is Gantry 4 mediaquiries.css in Gantry 5?)

### ISSUE THREAD

**Issue by GESign** [gantry/gantry5#526]
Hi Team,

Thank You for this great new template system!
I am looking for Media Quiries now.
I saw this: http://docs.gantry.org/gantry5/tutorials/media-queries and I was chceking GitHub issues and questions but I don't find the solution.

1., I created a custom CSS file for normal CSS (It works with normal CSS settings!)
2., I added this line in my custom CSS file on top: @import "nucleus/mixins/breakpoints";
Actually I dont have this url I think... I use Hydrogen template only.
3., I added this code below to the end of my custom CSS file (I would like to change this CSS class: .detached {visibility: hidden;} ):

/*   typically min 75rem   */
@include breakpoint(large-desktop-range) {

}
/*   typically range 60rem to 74.938rem   */
@include breakpoint(desktop-range) {
.detached {visibility: hidden;}
}

/*   typically 48rem to 59.938rem   */
@include breakpoint(tablet-range) {
.detached {visibility: hidden;}
}
/*   typically 30rem to 47.938rem   */
@include breakpoint(large-mobile-range) {
.detached {visibility: hidden;}
}
/*   typically max 30rem   */
@include breakpoint(small-mobile-range) {
.detached {visibility: hidden;}
}

/*   Less commonly used media queries   */

/*   typically min 60rem   */
@include breakpoint(desktop-only) {

}
/*   typically min 48rem   */
@include breakpoint(no-mobile) {

}
/*   typically max 47.938 rem   */
@include breakpoint(mobile-only) {

}
/*   typically max 59.938rem   */
@include breakpoint(no-desktop) {

}

This version is not working for me up. :(

Could You help in this situation please.

Best regards,
Andrew

**Comment by adi8i** [comment]
Your file should be scss. So add your code in `g5_hydrogen/custom/scss/custom.scss` , here you can add bot css or sass. 

I'll recommend to import all dependencies, so you can use variables, bourbon and mixins too, just add: `@import "dependencies"` 
Take a look at this pic: 
http://www.adriandev.com/images/Gantry/custom-css.jpg

**Comment by GESign** [comment]
Hi Adrian,
Thank You for your information!
I tried this but it has no effect on my website.
Should I add this custom.scss file in template in Atoms Section? I tried both cases but didn't help.

I created a css class in some module: .no-mobile

I created this custom.scss file (for testing I added this display none setting to every rem cases):
@import "dependencies";

/*   typically min 75rem   */
@include breakpoint(large-desktop-range) {
.no-mobile {display: none;}
}
/*   typically range 60rem to 74.938rem   */
@include breakpoint(desktop-range) {
.no-mobile {display: none;}
}

/*   typically 48rem to 59.938rem   */
@include breakpoint(tablet-range) {
.no-mobile {display: none;}
}
/*   typically 30rem to 47.938rem   */
@include breakpoint(large-mobile-range) {
.no-mobile {visibility: hidden;}
}
/*   typically max 30rem   */
@include breakpoint(small-mobile-range) {
.no-mobile {visibility: hidden;}
}

/*   Less commonly used media queries   */

/*   typically min 60rem   */
@include breakpoint(desktop-only) {

}
/*   typically min 48rem   */
@include breakpoint(no-mobile) {

}
/*   typically max 47.938 rem   */
@include breakpoint(mobile-only) {

}
/*   typically max 59.938rem   */
@include breakpoint(no-desktop) {

}

Is this file OK?

**Comment by adi8i** [comment]
`g5_hydrogen/custom/scss/custom.scss` here you need to add the code, you should have this file too: `g5_hydrogen/scss/dependencies.scss` .

http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
or look at my profile, i have a tut on my website too

**Comment by GESign** [comment]
Dear Adrian,

It is amazing, it works!
So my problem was I was thinking in CSS not SCSS. So I changed "//  typically min 75rem" to "/*   typically min 75rem   */". That was a mistake. So conclusion:

1., Create g5_hydrogen/custom/scss/custom.scss
2., Fill it with the content from here at bottom: http://docs.gantry.org/gantry5/tutorials/media-queries
3., Add css class or id what You use on your website to change. END
4., NO need to take this file into the layout "Atoms Section".

Thank You, Adrian for your help! You are amazing! Your website helped also! ;)
This case can be closed.

**Comment by mahagr** [comment]
Thanks @adi8i for your help.
