### ISSUE TITLE
COM_GANTRY5_PARTICLE_NOT_INITIALIZED

### ISSUE THREAD

**Issue by ErikBecht** [gantry/gantry5#527]
I installed Gantry5 including the Hydrogen template and doing some homework about the features of the framework. The website is still using a Gantry 4 template but now shows the error:
"COM_GANTRY5_PARTICLE_NOT_INITIALIZED"

After I click on the HOME button the website loads normally.

Website : www.mtc-tet.nl

When doing a google on "COM_GANTRY5_PARTICLE_NOT_INITIALIZED" you will find more website with the same problem.

Any idea how to solve this?

Br,
Erik Becht

**Comment by mahagr** [comment]
Did you already get the issue solved as I'm not getting any errors?

**Comment by ErikBecht** [comment]
Yes, solved by changing the default homepage/startpage to the Home menu-item of the Mainmenu.
The "Home" menu-item of the Hydrogen Theme was set to default.

**Comment by sarazimmo** [comment]
For others who want to know where to go, 

Go to Menus >> Menu Managers. You'll see Hydrogen Theme in the list, and when you click on it, you'll see that Home is being defaulted.

What you do, is go back, and look for Main Menu (this is still under Menus >> Menu Managers), click on it, and then click Home as default. 

That should solve the problem.

**Comment by mahagr** [comment]
FYI: translation for this is

"%s: Cannot display content; not in Gantry 5 template!"

It can happen either in menu item (geing Gantry 5 one) or if you are using Gantry 5 particle.

Not sure why it's not translated, though...
