### ISSUE TITLE
2 columns preset percent problem

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#528]
Hello,

If I get 2 columns preset and I set 20-80 percent (Sidebar-Main), then the component is sticking out.

![image](https://cloud.githubusercontent.com/assets/1657924/8502563/f340b66a-21b1-11e5-896f-d624dd7f460f.png)

![image](https://cloud.githubusercontent.com/assets/1657924/8502359/3454b26c-21af-11e5-958b-8f0bdb78e9ed.png)

If I add css correction with manual, then the issue has solved:

.g-block.size-80 .g-content {
    width: 80%;
}

![image](https://cloud.githubusercontent.com/assets/1657924/8502468/94931b54-21b0-11e5-9fdc-c95690cd58d9.png)

Joomla! 3.4.3
Gantry RC3/CI Builds (01.07.2015)

**Comment by adi8i** [comment]
Duplicate of #468

**Comment by csbalazs** [comment]
Sry, I didn't remember this issue.

**Comment by mahagr** [comment]
Did you upgrade Gantry5 from older version? If you did, which version were you using before?

**Comment by csbalazs** [comment]
I tested in clean Joomla! 3.4.3 + CI Build (07/07/2005) but the issue is still available.

![image](https://cloud.githubusercontent.com/assets/1657924/8554135/465d48de-24e8-11e5-8e99-8e07860561e7.png)

**Comment by kevlardev** [comment]
Consolidating these mainbody/sidebar issues to a single issue for a new container approach

**Comment by kevlardev** [comment]
In the meantime, ive added some css to nucleus to reset the width on these erroneous containers to stop the overflow issues from appearing.
