### ISSUE TITLE
Default Roboto font further character support

### ISSUE THREAD

**Issue by csbalazs** [gantry/gantry5#529]
It is possible to change default Roboto font to Latin extended version in G5 based Rockettheme's templates?
Unfortunately the current version doesn't support some Hungarian characters (ő,ű).
![image](https://cloud.githubusercontent.com/assets/1657924/8506728/b8c5805c-2223-11e5-92f3-42faf4b05f23.png)
If that does't exist the extended Robot fonts, then on demand I expand the current version with the missing characters, and I send it to Git.

**Comment by adi8i** [comment]
Personally i don't think that's needed, your request looks template specific, i mean not everybody will use Hungarian characters. 

You should be able to change the font from Styles panel.
![capture](https://cloud.githubusercontent.com/assets/9744973/8507513/50954f72-224f-11e5-8f53-2fe20583e66b.PNG)

**Comment by csbalazs** [comment]
That's true, but I think the extended version of the Roboto font is better, because this one contain missing characters and even further ones, but this is just an idea.
I tested here and it worked: http://www.fontsquirrel.com/fonts/roboto

**Comment by alisamii** [comment]
@csbalazs The extended font is much heavier and is not needed for 95% of sites. The difference between the extended and the standard latin font files in terms of impact on the site is that the extended will take 4 times as long to download, if not more.

**Comment by mahagr** [comment]
@kevlardev Your call.

**Comment by w00fz** [comment]
Note that `roboto` is the local version of the font that we provide with the template. You can always use the Google Font version instead, from the Font Picker.

 1. Open the Font Picker
 2. Search for `Roboto`
 3. Select a variation
 4. Hover over the selected charsets,
 5. Check any additional charset you want to be added.

I don't think we will provide the full extended version of roboto with the template, it's just too big and it's something that can be easily changed.

![fontpicker](https://cloud.githubusercontent.com/assets/11734/8530655/15e6adba-23d7-11e5-8c1c-08e5677b9b64.jpg)
