### ISSUE TITLE
Missing main.js.map

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#53]
#### Version
Nightly build (pre beta)
Joomla 3.4.2

#### How to reproduce
Open debugger, and load the index page.

#### Extra info
https://www.newf1.nl/media/gantry5/assets/js/main.js.map	GET	404	text/html	0 B	46.999808ms		XMLHttpRequest

**Comment by JoomFX** [comment]
This is the Source Map. Have a look at https://github.com/gantry/gantry5/issues/16

**Comment by w00fz** [comment]
We still need to strip that comment from the CSS and JS, we'll get there but you don't have to worry, the request to sourcemaps only happens if you have sourcemaps enabled in your browser AND if your browser's developer toolbar is open.
If it fails finding them it doesn't hurt anything.

**Comment by 810** [comment]
ah ok, then i will close it also. thnx
