### ISSUE TITLE
Issue 370 G5 particle module

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#530]
https://github.com/gantry/gantry5/issues/370
I am using Ethereal and for example the particles that are specific to this template Ethereal block, Number headline, Slideshow, Swiper won't appear in Gantry 5 Particle Module's list.

**Comment by sural98** [comment]
I couldn't replicate the issue with Ethereal and Ambrosia Rocket Launchers. That is template specific particles can be copied from one to another and G5 particle module can see them.
I don't know what is causing this issue if RL installation is not used as a base.

**Comment by mahagr** [comment]
Can you check if you have Ethereal set as your default template?

**Comment by sural98** [comment]
As stated in #370 it was my fault.
This can be closed.
