### ISSUE TITLE
W3C compliance - Accessibility - Responsive Menu

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#532]
please see:
http://www.rockettheme.com/forum/general-discussion/244330-w3c-compliance-accessibility-still?start=0#1215677

**Comment by 3cellhosting** [comment]
This also needs to be considered for RokSprocket and image title tags as they fall in the same category for 508 compliance.

**Comment by mahagr** [comment]
@kevlardev I think this one is for you?

**Comment by kevlardev** [comment]
Yes, we need to implement those title attributes for menu items. I'll work on getting those added.

**Comment by mahagr** [comment]
I believe that there's also requirement to have a way to skip menu and go to the content.

I'm thinking if we should for now add "Skip menu" and just jump over the menu.
