### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#533]
I have a Roksprocket tabs module with 3 simple items.
Each item in this module is having a description of {loadposition SOME_POSITION}
Positions are home to 3 different G5 particle modules.
There is module position in layout to load Roksprocket module's position.
The page outputs error.
```Open: C:\wamp\www\ethereal\libraries\gantry5\vendor\twig\twig\lib\Twig\Node.php
    public function getAttribute($name)
    {
        if (!array_key_exists($name, $this->attributes)) {
            throw new LogicException(sprintf('Attribute "%s" does not exist for Node "%s".', $name, get_class($this)));
        }```
What does that mean?

**Comment by mahagr** [comment]
Go into your php.ini configuration file and change the following line:

    xdebug.max_nesting_level=100

to something like:

    xdebug.max_nesting_level=200

By default XDebug settings are very conservative and do not work well with Twig or Yaml.

**Comment by sural98** [comment]
It worked. Thanks.

**Comment by w00fz** [comment]
For future reference: http://docs.gantry.org/gantry5/troubleshooting/max-nesting-level

// Djamil Legato // From iPhone //
