### ISSUE TITLE
Problem saving the colors in the styles tab in theme outlines

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#536]
Using the latest build and i am having problem saving the colors in the styles tab in theme outlines
i set one color in base outline and then i set the override in the say home outline, that works good
but when i want to uncheck the check box in the home outline it wont let me do that, after refresh it will stay checked and the color value will stay like that i set and not the color from base outline

See video:
http://take.ms/84gdm

**Comment by w00fz** [comment]
I cannot reproduce this issue. I tried following the exact same steps as in your video and it works fine.
Can you try with a different instance to see if you can reproduce? Maybe it's something related strictly to the one you are trying with.

**Comment by DamirPecnik** [comment]
The gantry is loading values from the blueprints/styles/subfeature.yaml and not from base ..

Watch the video and you will be more clear this is clean Joomla Install latest build i just added the image field to the Subfeature Colors ...

sorry for background music it was on when i recorded it :dancer: 
http://take.ms/VLHAL

**Comment by adi8i** [comment]
Have you tried to add a default value ? `$your-section-text-color: #fff !default;` ?

**Comment by DamirPecnik** [comment]
@adi8i the problem is in saving the values i think its a bug @w00fz confirmed it works really funny i am waiting for @mahagr to take a look ...

**Comment by mahagr** [comment]
I don't think that Gantry is loading the values from subfeature when you uncheck the values. Basically unchecking makes it to load the values from the base configuration (or if base is not saved, it uses default values from blueprints).

I think that JavaScript on the other hand is trying to match the settings to selected preset as it doesn't have information from the base values..?

**Comment by mahagr** [comment]
I'm not setting milestone just yet as we probably want to discuss what the option should really do. :)

**Comment by DamirPecnik** [comment]
Well i think it should inherit from base outline, because if i set my base values different from blueprints it should use base values trough out the site ....

**Comment by mahagr** [comment]
I can agree on that. So @w00fz, do I need to pass the current settings along with presets?

**Comment by w00fz** [comment]
I don't think this is related to JavaScript. When you uncheck a field in an Outline and Save, that field is not sent at all to the request.
The PHP is reverting it and saving it with the wrong value, I think from the `yaml` default value rather than the Base.

**Comment by mahagr** [comment]
Actually PHP doesn't save the value at all, meaning that it doesn't exist in the file. That allows the inheritance from the base configuration to work.

I think that to fix the issue we need to send base settings to JS and making reset to use base settings and not the current preset.

**Comment by w00fz** [comment]
Well then the problem is how the field renders that value. It looks like it's defaulting to the field default value rather than Base.
I don't think it would be very optimal to have the javascript handle this. It's a lot of work between reading the json and applying the value to each field. If there is no value and it doesn't match a preset it should use Base.

**Comment by mahagr** [comment]
I finally understood the issue and was able to reproduce it.

**Comment by mahagr** [comment]
The issue is that blueprints aren't properly built for the styles, so array merges use wrong strategy.
