### ISSUE TITLE
60/20 % layout

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#54]
On the beta2 the layout on the fresh install is 60/20 wide, and seems that not cover the whole 100% width. I have published content only on the mainbody and the on position-7.
A 20% white space is on the right site of the screen. I miss something ?
![gantry5b2-shot1](https://cloud.githubusercontent.com/assets/3976174/6982838/51e5da0c-da17-11e4-993c-52a67077378a.png)

**Comment by w00fz** [comment]
Which layout did you load? `Test` ?

**Comment by adi8i** [comment]
Is not there other issue open for this? :P empty positions don't collapse :P ?

**Comment by w00fz** [comment]
Oh I see what you mean. Do you have anything published in `position-8` ? This is obviously a bug but trying to figure out if it's the known one where sizes don't re-adjust or something new!

**Comment by mariantanase** [comment]
Hydrogen-Default.
I have nothing on position-8.

**Comment by w00fz** [comment]
This is a known issue, when a section or position collapse on frontend, all the other siblings should readjust size to accommodate the blank spot left. It's a tricky implementation that we still need to solve.

I also can't find the other ticket so good thing you created one.

Thank you!

**Comment by mariantanase** [comment]
I'm glad to help you !

**Comment by mahagr** [comment]
Yes, this is unimplemented feature. It'll be there, no worries, I've just been busy on fixing other bugs.

**Comment by mahagr** [comment]
Fixed other than issue described in #115
