### ISSUE TITLE
Two column submenu adds a big gap on mobile menu

### ISSUE THREAD

**Issue by pablotll** [gantry/gantry5#540]
Hi, I searched before posting and didn't find anything related, sorry if it's there somewhere.

I've setup a submenu to have 2 columns (50/50) on the navigation menu editor:
![captura de pantalla 2015-07-07 a la s 11 23 14](https://cloud.githubusercontent.com/assets/13223064/8551175/a21dc98a-249a-11e5-9044-823ac30e9cf6.png)

That looks fine in the desktop version of the site. But on the responsive version, the offcanvas menu adds a lot of space between the 2 submenu options:
![captura de pantalla 2015-07-07 a la s 11 14 17](https://cloud.githubusercontent.com/assets/13223064/8551196/c2af30b2-249a-11e5-8eb5-57ef120807b1.png)

With only two options, in an iphone5 I barely see the second menu, smaller screens won't show it and people won't know it's there.

Thank you.

**Comment by w00fz** [comment]
Hey there! Is this with RC3? I think this issue has been fixed already but the activity on G5 development has been so fast that I fail to remember if it was fixed before or after RC3.
Would you mind trying with the latest [CI Build](http://gantry.org/downloads#ci-builds) to see if that fixes the issue for you?

Thanks!

**Comment by pablotll** [comment]
No, it didn't fix it for me. Although I got some errors from the installation so maybe it's because of that:

![captura de pantalla 2015-07-07 a la s 19 35 21](https://cloud.githubusercontent.com/assets/13223064/8560751/dc88f95a-24e0-11e5-9a56-7420d7e3d3bd.png)

In the Extension Manager the version of Gantry appears as dev-43567c479 but I don't know is it's actually there and maybe that's why I still get the big space in the offcanvas menu.

Thank you.

**Comment by mahagr** [comment]
You can ignore warning during uninstall; it was harmless issue in our RocketLaunchers.

Can you inspect the html from the offcanvas as it may reveal something..?

**Comment by w00fz** [comment]
This should be now fixed in CI Build.
Good catch, thanks for reporting it!
