### ISSUE TITLE
Deleting Outline i get 500 Internal Server Error

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#542]
500 Internal Server Error

Oops, Cannot delete non-existing folder..

![image](https://cloud.githubusercontent.com/assets/10489911/8558887/f0e2549c-2507-11e5-90ef-02f42127dfe9.png)

**Comment by mahagr** [comment]
Should be easy bug to be fixed. Outlines do not always have saved configurations, so we might just test if the folder exists before attempting to remove it.
