### ISSUE TITLE
Google Analytics atom

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#544]
I notices that on the Google Analytics atom, every option contains 2 checkboxes. I don't know why.
In my particular case, the option **Anonym Statistics** will work only when both left-right checkboxes are checked.
![2checkboxes](https://cloud.githubusercontent.com/assets/3976174/8566401/3abb8a56-255e-11e5-8260-7f38802dac9a.png)
Only in this case the output will be:
<code>ga('set', 'anonymizeIp', true);</code>

**Comment by newkind** [comment]
One is to change the value, second is to check that this option should be overrided in current outline



Dnia 8 lip 2015 o godz. 10:47 Marian Tanase <notifications@github.com> napisał(a):

**Comment by mariantanase** [comment]
Sorry I don't understand.
I see that If only one checkbox from the same line is checked, has the same result when is unchecked.
To be more clear, if you check only one checkbox and then hit **Apply** following by **Save Layout** the check is not saved.

**Comment by adi8i** [comment]
In short the right one is to enable the field, then the second one, on left, near statistic is to enable Anonym Statistics, so you first need to enable the field the the option. 

Is the same as for any other field. Like it is for UA Code, first you hit the checkbox then fill the input.  Left checkbox is just an input, could be replaced with any other, like text, or selectize etc.

**Comment by alisamii** [comment]
I think that the interface is a bit clunky.

If you are in the base outline, and you set the parameters there, you don't see the right-most checkbox. That checkbox is only available in the other outlines and allows you to override the settings made in the base outline.

Let's say, for example, that you have a property id of UA-1234567 for your site and you set that in the base outline. You also want to use anonymous tanking for the entire site, so your enable anonymous starts in the base outline. But, you want to track your home page with a different property id than the rest of your siteand you don't want the stats for the home page to be anonymous. What you would then do is in the settings of Google analytics in the home outline, you would check the right checkbox on the property id and change that and you would then check the right checkbox for anonymous starts as well and then uncheck the left checkbox.

That would then set a new I'd for taking the home page and ensure that the tracking is not anonymous, but only for Pages associated with the home outline.

**Comment by alisamii** [comment]
I think the interface could potentially be improved, but at the moment I'm not at my computer to mock up a better interface to make it more clear.

**Comment by mariantanase** [comment]
@adi8i  What's the differents between enable the field (to doing what ?) and enable Anonym Statistic (which is the real feature)?
In my opinion if a user wants to enable anonym statistic will check a checkbox and only one checkbox not two, if no the checkbox will remain unchecked.

**Comment by w00fz** [comment]
The right checkbox applies to most of the fields and it only appears when you are in an Outline.
When you are in an outline you are able to override the values from the Base. If you notice when the right checkbox is unchecked, there is a semi-transparent overlay above the whole field that is there to indicate that it's going to use the value from the Base.

When you are in an outline and you want a field to behave differently than Base, you can check that right checkbox which will allow you to override the value of it. This is also what @adi8i means by 'enabling'. You have to either click the field or the checkbox before you can start changing the value.

This is particularly clear in the Styles panel. In Base you might have a background color set to red but in your Home outline you might want that color to be green. To do so you would go to the Home outline, check the right checkbox and then change the color to red (this is how the overriding system works).

The same applies for Settings. I can see the confusion of it being next to another checkbox, in the analytics particle, but this is consistent across the whole framework.

**Comment by mariantanase** [comment]
Thank you @w00fz ! loud and clear :+1:
