### ISSUE TITLE
RTL Joomla assets not loading when lang is RTL

### ISSUE THREAD

**Issue by kevlardev** [gantry/gantry5#547]
The bootstrap-rtl.css needs to be loaded when lang is detected as RTL along with the other joomla assets when joomla output is present.

**Comment by mahagr** [comment]
Good catch, I had totally forgotten this issue. Relates somewhat to #546.

**Comment by kevlardev** [comment]
There is an ordering issue currently, the bootstrap-rtl is loading before the bootstrap main css, it needs to load immediately after in order to provide the appropriate overrides.
