### ISSUE TITLE
Implement a better way to handle container placement

### ISSUE THREAD

**Issue by kevlardev** [gantry/gantry5#549]
Currently the containers are automatically generated either before or after section elements based on config setting (to allow for both boxed and fullwidth approaches to the background styling of those sections). Nested sections automatically do not receive containers (to prevent mainbody/sidebar overflow problems when containers are placed inside of side by side sections).

This approach has exposed some flaws that limit the options for layout and control. Nesting sections is nearly impossible as there is no container or width control once those sections are nested. We need to implement a more manual system to allow the developer to explicitly indicate when and if a container should be rendered. There are a couple of refinements i can see solving most of these issues.

1. Add a third option to the section/global container controls for 'fluid' or 'no container' which will simply cause the container to not be rendered at all on a section by section basis. This will allow for true fluid width implementations of individual content as well as full screen effects such as slideshows and sliders without needing to overcome the width restrictions of the container.

2. Allow for containers to render inside of nested sections with no limit, provided those nested sections are not 'side by side' implementations in which case the containers would be restricted from rendering inside of those side by side sections (mainbody/sidebar implementations and other custom side by side setups) This would require some check of whether the nested sections are in a side by side configuration (perhaps looking at the structure / block size and any nested section below 100% width dont get a container or something) or some sort of manually added flag in the yaml to indicate whether this nested layout gets internal containers or not. This will also help to prevent backward compatibility issues with the mainbody/sidebar containers being placed incorrectly that have been sporadically appearing since rc3.

**Comment by mahagr** [comment]
See also #521

**Comment by kevlardev** [comment]
Toggle third option previously discussed in #493

**Comment by nicutor** [comment]
+1 on this

**Comment by mahagr** [comment]
Mostly implemented. 

@w00fz What struck into my mind was that instead of rendering "flushed content" container, we should really have no container at all as @kevlardev suggested. That would make the section to render full width, but would also keep the padding and margin from the g-content.

We also do not have any restrictions in place on where containers can go in, but I don't think we need need those.
