### ISSUE TITLE
Facebook comment 

### ISSUE THREAD

**Issue by Hertak** [gantry/gantry5#55]
I install two facebook comment system one is phoca and the other Module - Facebook Comments By Internet Partner. 
If you have symten error on defoult the gantry have a lot of error but if you turn off every works fine.

**Comment by mahagr** [comment]
We have debugger turned on and it catches all potential issues in the code, including any broken 3rd party code. Right now it has been set to stop the code execution and display trace dump on where the issue happened to allow us to fix all the bugs in our code.

I bet that the developer of the module will be really happy to fix the issue, just provide him at least the error (h1) and the file and line where it happens (first item on the left).

I'm going to leave this issue open to remind myself to add option to disable debugging, in case of you are working locally and do not want to stop the page from loading on minor issues like this.
