### ISSUE TITLE
Particles in Menu Manager and Module cannot be reset / changed

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#550]
Particles under options tab in Menu manager can't be removed.
![capture](https://cloud.githubusercontent.com/assets/9744973/8589970/944eec0e-2624-11e5-8b82-193cf7f4b1a7.PNG)

**Comment by mahagr** [comment]
@w00fz I think this one is mainly for you, as we need to be able to reset particle state via JS.

**Comment by kat05** [comment]
works fine for me.
