### ISSUE TITLE
Intermittent delays in G5 particle module 

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#551]
Is anyone experiencing intermittent delays in G5 particle module when selecting text/clicking?
Unlike other modules G5 particle module response to keyboard /mouse is a strange.

**Comment by mahagr** [comment]
Not really, but I'm experiencing some odd slowdown when loading settings tab in admin. Might be related to that?

**Comment by w00fz** [comment]
Doubt that is related, he's describing the module while you are describing the admin.
I see no delays in the module at all.

**Comment by w00fz** [comment]
Did you figure it out @sural98 ? I don't see anything weird on my end. Perhaps restarting the browser / clearing cache? Also what browser are you trying with and did you try with a different one?

**Comment by sural98** [comment]
I have tested the issue with Ambrosia RL and were unable to reproduce.
On the other hand I suspected that it would be the cause if 2 RT G5 templates coexisted. I have installed Ethereal also. No. There were no issues with this installation too.
I have again tested the issue in Opera v.31.0.1889.50. Same problem.
Is it the number of modules, menus? No idea.
@w00fz Can we again arrange a TeamViewer session so that you can see the issue in my local installation.
FYI. I am using Chrome as my default.

**Comment by mahagr** [comment]
I think there's something else going on, may be related to number of menu items or something..

So you're able to reproduce this in a single Joomla instance? The issue must be in JavaScript, which means that you may able to benchmark JS and see which functions take the most time.

**Comment by sural98** [comment]
I can confirm that this issue is related to the no of menu items.
There was no problem with a fresh Ambrosia RT launcher but issue arised upon importing 1362 items and a no of menus via an sql.

**Comment by mahagr** [comment]
@w00fz Do we have some JS that goes through all the input fields?

**Comment by sural98** [comment]
Were you able to replicate the issue?
If so can we expect a fix soon?

**Comment by mahagr** [comment]
Unfortunately no. Concact me in gitter next week and I'll forward it to someone trying to replicate the issue.

**Comment by w00fz** [comment]
Nothing of our Particle Module custom stuff deals nor touches anything related to the Menu. Anything Menu in the module is purely Joomla and the only Menu elements I see in there are Assignments.

Are you sure you are only getting this with the Particle Module? Could you create a dump of your Joomla DB with all those items and let Matias or I have it in Gitter?

**Comment by w00fz** [comment]
Hey @sural98 just wanted to let you know that I was able to track this down (after a lot of debugging!!) and fix it.

As usual, THANK YOU for being so helpful with details and responsive in providing the SQL dump that helped me a lot. This has proven to be a very nice optimization for the whole admin.

:+1:

**Comment by sural98** [comment]
Hi @w00fz. It is crazy fast now with your latest fix.
I really appreciate your great efforts in the project.
Thanks.

**Comment by sural98** [comment]
However Global Filter (Assignments) box's response tab to clicking appears to be the same.

**Comment by sural98** [comment]
There is still an issue with Global Filter:
Delay is persisting while inputting characters or deleting (using backspace) them.

**Comment by mahagr** [comment]
As this issue deals only with Particle Module, it might be better if you just created a new issue for Global Filter. :)
