### ISSUE TITLE
Possible issue using Cyrillic font

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#558]
Please see http://www.rockettheme.com/forum/joomla-template-ambrosia/244537-solved-google-font-subsets-other-that-latin-where-and-how?start=0#1217106

Member reports having to add parameters to font strings to get cyrilic font to work.

Another member reports something similar here too - this time for latin-extended:
http://www.rockettheme.com/forum/joomla-template-callisto/244515-latin-extended-fonts-missed?start=0#1216912

**Comment by w00fz** [comment]
This is not a bug, it's already possible to add extra charsets from whithin the fontpicker.
See my comment and explanation in here: https://github.com/gantry/gantry5/issues/529#issuecomment-118962467

I'd like to extend the documentation for this at this point, since it came up more than once.

/cc @FrugalGeek

**Comment by FrugalGeek** [comment]
Will do!

**Comment by marktaylor46** [comment]
Thanks guys - that's very helpful... another thing I didn't know.

Would be useful if that "hover" could be more obvious though - some sort or icon or something.

But.. thanks again

**Comment by w00fz** [comment]
With @marktaylor46 suggestions it is now more obvious that there are other charsets available in the font picker and that can be selected.

![fontpicker-charset](https://cloud.githubusercontent.com/assets/11734/8628491/57776dbc-2708-11e5-9810-d27b5b9ebef1.jpg)

**Comment by marktaylor46** [comment]
Very good - happy :)

**Comment by FrugalGeek** [comment]
Added: http://docs.gantry.org/gantry5/tutorials/using-the-font-picker#selecting-your-font-weights-and-

**Comment by marktaylor46** [comment]
great - thanks!
