### ISSUE TITLE
Ability to disable offcanvas swipe gestures

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#559]
Member has a third-party slideshow module which uses swipe events to change slides (left and right). unfortunately the swipe event is opening the mobile menu rather than changing slide. So, it would be nice to have the facility to disable the swipe-open of the mobile menu (tick box setting).

member topic is:
http://www.rockettheme.com/forum/joomla-template-callisto/244566-off-canvas-mobile-menu-swipe-issue?start=0#1217036

**Comment by w00fz** [comment]
This is now implemented as a new option in the `Offcanvas Section`, like displayed in the screenshot below.

Please note that the swipe gesture, hamburger icon, offcanvas position.. that is all tied to the offcanvas section and not the menu (just a FYI).

![swipe-gesture](https://cloud.githubusercontent.com/assets/11734/8630810/8252c10a-271f-11e5-8593-aa167f571742.jpg)


/cc @felixo1234 (I remember someone asking about this sometime ago and I think it was you :smile:)
