### ISSUE TITLE
Core font size default value can't be changed.

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#562]
`$core-font-size` value can't be changed, even if i change the value in `scss/configuration/_typography.scss`, will still display `font-size: 1rem`. Basically all Base Sizes and Heading Sizes placed in `_typography.scss` are not readed.

Because you already defined `h1 { font-size: $h1-font-size } ` in nucleus, i should be able to change only core value, so i don't need to define h tags again.

I've tried to define font size in `hydrogen/typography.scss` but is the same.
![1](https://cloud.githubusercontent.com/assets/9744973/8645823/61d8e3ec-2953-11e5-9e70-f6c04833e80e.PNG)
![2](https://cloud.githubusercontent.com/assets/9744973/8645825/65ce9848-2953-11e5-8014-9c27eb61a196.PNG)

**Comment by mahagr** [comment]
This is because of the values are defaults and used only if configuration hasn't been saved or the value is missing from the configuration. So the values are just fallbacks and you need to update default value from yaml file, to be the same, to get any effect.

**Comment by adi8i** [comment]
I am bit dizzy, the default value is 1.5 rem, in yaml file also the default value is 1.5rem, i can go to styles enable the field and add any value, this will work.
I the field is disabled the default value will be 1rem.

![capture](https://cloud.githubusercontent.com/assets/9744973/8649168/21733aec-2970-11e5-9264-abc48a8ab92a.PNG)

**Comment by mahagr** [comment]
I think I know the issue here.

@kevlardev Can you make sure that template configuration gets loaded before nucleus configuration. The issue is that !default only sets the value once, so template overrides get skipped.
