### ISSUE TITLE
Joomla email cloaking plugin

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#564]
Joomla's email cloaking plugin does not work on any particle content so email addresses are not cloaked.

So I guess the real question is - can Gantry 5 do anything to cloak email addresses in particle output?

Typical code used:
 
    <a href="mailto:test@test.com">email test</a>

Regards, Mark.

**Comment by mahagr** [comment]
Same as #369

**Comment by marktaylor46** [comment]
How is is the same? it's not a shortcode being used at all? it's just ordinary html in the output from a particle?

**Comment by mahagr** [comment]
Both are fixed by enabling Joomla onDisplayContent event from the particle output.

**Comment by marktaylor46** [comment]
ok fair enough. But I'll add comment on other ticket too.

**Comment by mahagr** [comment]
Sure, saves some time from me. :)

**Comment by mahagr** [comment]
Doh, wrong reference..

**Comment by webcoast** [comment]
_mahagr commented on Jul 14, 2015
Both are fixed by **enabling Joomla onDisplayContent event from the particle output**._

How do we 'enable Joomla onDisplayContent event from the particle output'? I have looked everywhere and can't figure out how to do this. I'm using Gantry 5.3.2,
Thanks, Nicola

**Comment by mahagr** [comment]
It can only be done from selected particles, for example Custom HTML particle. Each particle needs to add support for this in order it to work. Which particle are you using?

**Comment by webcoast** [comment]
I am using "Simple Content" particle.
![gantry](https://cloud.githubusercontent.com/assets/1870107/17573576/ae9e84e8-5f9e-11e6-8024-10b3a7bd0320.jpg)

What do you mean 'each particle needs to add support for this in order for it to work'.  If it won't work for simple content, can you give me instructions for how to do it for Custom HTML particle please.
Thanks.

**Comment by mahagr** [comment]
Basically developer/modifier of the particle needs to add support for filtering content by plugins. It can be done by taking the `output` and passing it through `{{ gantry.platform.filter(output) }}` function in the twig file.
