### ISSUE TITLE
'Page heading' does not show on Gantry 5 custom page

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#565]
this has been mentioned in our forum:
http://www.rockettheme.com/forum/gantry-framework/244553-dropping-gantry-5?start=10#1217584

> Another thing I have noticed is Gantry 5 doesn't seem to work very well with SEF components unless you link to an single article. If you link to a custom gantry page it just thinks that there is no page there at all. 

> It also doesn't include the site name in the title unless you link to a Joomla page. eg if you link to a Gantry page it doesn't work.
Global config > SEO Settings > Include Site Name in Page Titles doesn't work so I would have to manually do this or change all of gantry pages to Joomla pages. 

i have not yet tested the seo issues, but can confirm that the 'Page Heading', set in the menu item > page display > page heading ... does not show on a gantry 5 custom page.

**Comment by mahagr** [comment]
Fixed in

https://github.com/gantry/gantry5/commit/ebc5f0d0fb201c9031109ca3519c416c1c7a00d9
