### ISSUE TITLE
Article not on a menu are recieving the wrong theme outline

### ISSUE THREAD

**Issue by webmasterchris** [gantry/gantry5#566]
Articles hyperlinked in content and not on a menu are receiving the theme outline of the home page not the default theme starred in the Joomla Template Manager:styles page. This is isolated to Ganty5 templates. Ive tested other like beez3. Links work properly in beez3. Is there a config change I need to make.

**Comment by mahagr** [comment]
You can find the logic which Joomla uses to find the menu item for articles from ```components/com_content/helpers/route.php``` file. It will just pick the first menu item that matches its requirements (of if nothing is found, it defaults on starred item). For some reason in your case it's the home page that gets picked up the first. You can end up the same situation with beez3, but in your case it is not picking up the menu item in beez3. Joomla also defaults on current menu item if it matches, so be careful not to use Joomla component on home pages; use modules instead.

To fix the issue, you may need to change home page to something else; maybe use Gantry5 custom page with module particle in it and set the module to display articles you want to show. You may also want to create (hidden) menu item for articles if you need have more control on how individual articles get displayed.

I've run into this issue before, too, and its annoying that you have no control on which menu item gets picked up.

**Comment by webmasterchris** [comment]
That's not really what is happening. It's only happening in Gantry 5 and in every instance in it, new Joomla install, upgrade, different themes. If it was not intentional, this is definitely a bug. The issue resolves itself if only one Gantry style is used. For example, If I use only the 	Callisto - Default style. This is not an isolated incident and definitely a bug.

**Comment by webmasterchris** [comment]
I'm not sure I'm communicating this effectively. Most of the sites I develop don't use the page content position on the home page. The way I tested this it to add the page content position to the home style. All content then rendered properly only with the home template style modules. When either I have the page content position on both template styles or I use only 1 template style the bug isn't an issue.That how I figured out Gantry is not using the default template style for articles linked and not on a menu. When I don't add the page content position to the Home template style and you click on a link that isn't on the main menu, the home page renders without the "page content". One example is http://www.webmasterchris.com/dpls/using-the-library/policies

**Comment by mahagr** [comment]
What you explained above still looks like normal Joomla behavior to me. Edit the menu item of your home page and tell me that you aren't using com_content component in it and I will agree this is a bug.

When I visit your site, Joomla is telling me that you indeed have Articles component as your home page. Logic in Joomla Articles router says that it should always use the first com_content menu item that it finds, so it ends up using your home page, which has been assigned to Home style. So Joomla uses correctly Home style and not Default. I cannot see any bugs in there, but I can agree that this is something that Joomla isn't doing well. You can replicate the issue in any other Joomla template simply by assigning a module to home page only. You will see that module not only in your front page, but also on all articles you write.

To fix the issue you need to change com_content from your front page into something else -- preferably to Ganty / Custom view. Then create another (hidden) menu item to catch up all the articles. In that way you can control which template style gets used as well as which modules you want to display in the page.

**Comment by webmasterchris** [comment]
![issue](https://cloud.githubusercontent.com/assets/11822535/8709032/9c5a47ca-2b0d-11e5-8004-678c6628c673.PNG)

I recreated the menu as you suggested. it was working until I deleted the old menu. The then showed the error above. Your suggestion did not work on another site I'm working on. I used a hidden menu which is not a long term solution due to the size of that specific site. I'm glad to give you any help you need, including admin access to the sites.

**Comment by webmasterchris** [comment]
I then recreated the in content links, went straight back to the home page and back to square one. It appears to be a bug. Thanks for you attention mahagr!

**Comment by mahagr** [comment]
Your error comes from Joomla articles component; for some reason routing isn't working in that example. I think it may be some kind of configuration or cache issue...

PM me in gitter chat and I can take a look.

**Comment by mahagr** [comment]
This was not Gantry bug, but issue in the editor plugin which assigned home menu item to all articles.

**Comment by cail** [comment]
Here is why this may happens actually and the acceptable solution:
https://joomla.stackexchange.com/questions/17896/home-page-layout-is-used-for-content-instead-of-the-default-layout
