### ISSUE TITLE
Gantry 5 and SEF components in Joomla

### ISSUE THREAD

**Issue by prototype2118** [gantry/gantry5#567]
Gantry 5 doesn't seem to work very well with SEF components unless you link to an single article. If you link to a custom gantry page it just thinks that there is no page there at all. 

It also doesn't include the site name in the title unless you link to a Joomla page. eg if you link to a Gantry page it doesn't work.

Global config > SEO Settings > Include Site Name in Page Titles doesn't work so I would have to manually do this or change all of gantry pages to Joomla pages.

**Comment by mahagr** [comment]
I believe that I've already fixed this just before the release in #565. :)

**Comment by w00fz** [comment]
This was fixed with #565
