### ISSUE TITLE
Not having to create a new outline for every joomla module manager instance of a Gantry 5 particle

### ISSUE THREAD

**Issue by prototype2118** [gantry/gantry5#568]
Can we have it so that way if we want to implement a Gantry 5 particle module that we don't need to also have a corresponding outline?  It would be nice just to have the straight up Joomla integration of creating a Gantry 5 particle module, assigning it a position in the template and then assigning it to a menu item of a legitimate Joomla CMS article.  It's very difficult to have to create an outline for everything when you just want to be able to work within the CMS.

And on top of that, when you do create a corresponding outline for a gantry 5 particle module it that is assigned to a menu item of a Joomla article, they don't seem to be apart of the same system and seem detached from one another.  It's not cohesive looking like it would be if it was just a plain joomla module.

**Comment by mahagr** [comment]
You can already do this.

Outlines are meant to contain all the static content like logo, menu and footer information that doesn't change between the pages. For the rest you should create module positions and assign modules -- including particle modules into those Joomla positions, just like you would do in any template.

**Comment by w00fz** [comment]
I'm assuming Matias answer helped you here since there hasn't been any reply and I'm closing this.
