### ISSUE TITLE
G5 latest release breaks something at backend

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#569]
The following is from Ambrosia's G5 particle module
![alignment issue](https://cloud.githubusercontent.com/assets/1849490/8671639/98d6a64a-2a2f-11e5-941b-58aa5d905144.png)

**Comment by kat05** [comment]
Good catch, I can confirm this issue in > Modules > FP Mainleft Headlines 1

**Comment by sural98** [comment]
Not only that one but all particles with sub-elements behave like this.

**Comment by mahagr** [comment]
@kevlardev can you take a look?

**Comment by sural98** [comment]
There is something more to be done I think. Some text need no wrapping.

![alignment issue](https://cloud.githubusercontent.com/assets/1849490/8693832/c3e343a8-2ae2-11e5-879a-1f1163f5d9da.png)

**Comment by mahagr** [comment]
Reopened to let @kevlardev to decide what to do with the another issue.
