### ISSUE TITLE
Module Gantry 5 Particle: reset upon -> edit -> save

### ISSUE THREAD

**Issue by hw225** [gantry/gantry5#570]
PHP Version 5.4.42
Curl
openssl
Multibyte string
Fresh Joomla Joomla! 3.4.3 install
Multi language setup correct
Latest Gantry 5 version joomla-pkg_gantry5_v5.0.0

---

Module Gantry 5 Particle set to get a particle (sample content) 
Pick the particle 
Enter content -> Apply
Set language of module
Set position (drawn from outline)
Set menu assignment
Set module advanced->headline to H2
Set Title module
Save & close

Everything is fine in backend and frontend

Enter module again edit anything
Then click Save or Save and close

Result:
---
The particle is lost in the module screen (pick particle shown again) 
Frontend loose particle
Joomla setting of advanced->headline is also lost
(If save the module with only advanced->headline set and no particle picked then the headline setting stays intact)
Menu assignment is kept intact

Save as a copy works, but if edit the module(the copy or the original)  later same result as above.

**Comment by hw225** [comment]
Hmm something weird is gong on...
After trying to save different info in different ways and making a new test module some of the particle modules shows more than one particle associated in the module manager. 

Also now some of the modules keep their settings and particle. So it is not consistence. 

 Maybe this is related to that I made all of these modules as "

![2015-07-14 13-55-56](https://cloud.githubusercontent.com/assets/13331654/8672743/91516368-2a31-11e5-9b7e-749b78ec38fc.png)
Save as a copy"

**Comment by hw225** [comment]
I got the modules sorted out by going into each and remove the particle and save & close. Then went back inside and added the particle again. 
Now it seems I can keep editing them without loose particle or get double-up on particles assigned.

Might be the "Save as a Copy" workflow I did the first time on creation of the modules...

**Comment by w00fz** [comment]
I'm not getting this issue with Save as Copy. Did you update to the latest 5.0.0 release version?

**Comment by hw225** [comment]
I tried to replicate today and first could not.
But then I tested with the content of the particle (sample content particle)
It looks to me as if one use æ ø å in the "Link text" field.of the particle 
then  APPLY
SAVE 
Make some other (or none) edit in the module interface
and then hit SAVE or Save & Close again
![particle-content](https://cloud.githubusercontent.com/assets/13331654/8696160/5a3b15c2-2aea-11e5-8c4c-5888f1f6ec1d.jpg)

Then the module reset the particle pick and some of the Joomla settings (advanced -> Header tag)

Maybe someone can see if they get same result if using æ ø å  in the Link text field and SAVE X2

**Comment by w00fz** [comment]
Ok that is bizarre. I can replicate with those characters.

**Comment by w00fz** [comment]
Ok this should be now fixed, you can give it a try in the latest [CI Build](http://gantry.org/downloads#ci-builds) if you like.

**Comment by mahagr** [comment]
Do we need the fix elsewhere or was this issue only with Joomla filtering the module input?

**Comment by hw225** [comment]
Confirm: now æøå works in latest CI Build on my site.
Thanks a lot.
