### ISSUE TITLE
Admin screen shot in release notes vs actual

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#571]
Admin screen shot at http://gantry.org/blog/gantry5-released is different from that of actual release.
![admin extra1](https://cloud.githubusercontent.com/assets/1849490/8672850/b8d21032-2a3a-11e5-834d-ecd902482034.png)
![admin extra](https://cloud.githubusercontent.com/assets/1849490/8672849/b8d1de46-2a3a-11e5-8fdb-2ceb0ee6e50a.png)

**Comment by FrugalGeek** [comment]
Fixed!
