### ISSUE TITLE
"Box-sizing: inherit" causes an issue with the RokSprocket Loader (at least with Strips)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#573]
The new "box-sizing" in G5.0.0 is in conflict with the RokSprocket Strips loader:

```
*, *::before, *::after {
    box-sizing: inherit;
}
```

I do not think it is a G5 issue as I personally think the new "box-sizing" is better than the old one. I just wanted to let you know as you will probably need to apply some fix directly in RokSprocket (or as a fix/override in G5) so the loader shows properly. I did it with the following code:

```
.sprocket-strips.loading .sprocket-strips-overlay {
	box-sizing: content-box;
}
```

**Comment by JoomFX** [comment]
And while we are on "box-sizing" I'd like to ask you for your opinion about one more thing...

You have the following code in Nucleus (`_forms.scss` in `media/gantry5/engines/nucleus/scss/joomla`):

```
// Box model Resets for Joomla / Bootstrap2
.platform-content input {
    @include box-sizing(content-box);
}
```

Wouldn't it be better to have it also set to `inherit` or just to delete it?
I currently have the following issue because of the above code:

![alt](http://i.imgur.com/em1w2q4.png)

In the above screenshots I have the `input` with `width:100%` but because of the padding and the box-sizing it gets bigger than it should.

**Comment by kevlardev** [comment]
The problem with the box sizing on inputs is that the whole bootstrap2 setup requires content-box on inputs for everything to appear properly. I can't identify every use case or third party extension from the theme css that may or may not be expecting bootstrap2 behavior so have to do a blanket setting in the joomla css to set those to content-box as they are in bootstrap2.

**Comment by JoomFX** [comment]
Thanks for the reply Kevin :)

Yah, it is not a big issue, not at all. I just wanted to see what you think about it. I will fix the stylings on case by case basis, not a problem.

What about the RokSprocket Loader issue? Did you notice that already with the commercial RT templates? And how do you plan to handle that - put some code in the extension or in G5 (I suppose in G5)?

**Comment by kevlardev** [comment]
Ya we will likely have to add an exception in g5, or atleast the themes themselves, for roksprocket box sizing override.

**Comment by JoomFX** [comment]
ok, thanks Kev ;)
