### ISSUE TITLE
Default Sections

### ISSUE THREAD

**Issue by Design-ADCD** [gantry/gantry5#575]
It would be quite useful if I could create default sections that would be applied to all outlines. Sometimes I got to recreate everything to a new Outline, or change every Outline just because of a single changing, like the Logo in the Header for example. This would be so helpful.

**Comment by w00fz** [comment]
We do have plans to implement a mechanism where you can inherit **Sections** from other **Outlines**, as well as inherit **Particles** settings from others of the same type.

**Comment by w00fz** [comment]
See also #340

**Comment by federone** [comment]
hi,

i think, for example to have a new tab, named "Global Settings" where we can add atoms .... which will be loaded on all pages ... like it is on default joomla templates, when you enable some params, it will be enabled on all pages ...

sometimes working on it, we get confused ... and i guess our customers will too ... and they will ask plenty questions ... and its a headache for us for giving support

Thank you very much

**Comment by w00fz** [comment]
Have a look here https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel, I outlined an Agenda for the future version of Gantry 5 which includes a description of what's been asked here.

**Comment by w00fz** [comment]
This is now implemented with our Inheritance effort.
