### ISSUE TITLE
Language implementation in Assignments

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#576]
I see a language implementation in Assignments and I am totally confused:
Will it make menu item assignments useless?
Are we pairing template style (outline) with a language?
How will that work?
Can @FrugalGeek prepare a doc regarding that issue?

**Comment by mahagr** [comment]
It's the same Joomla feature you see on the right side when editing beez or protostar styles. Basically it allows you to set template style as your home page for a single language only.

**Comment by sural98** [comment]
That means it is not a radical multi-language implementation and no worry for confusion.

**Comment by mahagr** [comment]
Yeah, it's just Joomla feature.

We are still missing inline translations for all the particles as I really do not like the Joomla way of copying everything over for every single language.

**Comment by w00fz** [comment]
Closing this as it sounds like you got your answer there.
