### ISSUE TITLE
Custom JS/CSS atom enhancement

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#577]
Currently, when you add a Custom JS atom, you can specify the file location and that is about it. However, JSs can be either placed in the `<head>` element or in the footer just before the `</body>` tag. There is even syntax within G5 to insert the script file reference in the head or footer. However, there is no interface within the particle to specify the target insertion point.

It would be very useful to be able to click a checkbox (as in the mockup below) that would insert the script in the footer. The default could be in the `<head>` element. *I'm not sure which option would be better as the default, but in this mockup I have selected default for head and if selected, then insertion would occur in the footer.*

![atom](https://cloud.githubusercontent.com/assets/1498512/8695970/fa5583aa-2ae8-11e5-92c4-045c26a90c17.png)

A further enhancement, which I have not mocked up, is to provide the option to inline the script. This would then inject the contents of the javascript file inside a `<script>` tag rather than link to the external script file.

**Comment by w00fz** [comment]
This was also mentioned in #62, not sure why it was closed.

**Comment by w00fz** [comment]
See @adi8i's contribution in #580, would be nice if you could give it a try. I'll review soon and merge it in later.

**Comment by w00fz** [comment]
This is now implemented, I merged #580.
