### ISSUE TITLE
"Hide unassigned items" not working

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#578]
"Hide unassigned items" option in  Assignments is not working in my local Ambrosia installation.
Can anybody reproduce the issue?

**Comment by mahagr** [comment]
It's not fully working for me either. Half of the menu items still show up even if they aren't assigned to the page. This is with my local install of Hydrogen.

**Comment by sural98** [comment]
None is hiding in my case.
Will you please take a look at this closed issue? 
https://github.com/gantry/gantry5/issues/398

**Comment by w00fz** [comment]
I don't see any problem here on my local on a fresh Ambrosia installation. When i click "Hide unassigned items" from the Demo Outline I get this:

![ambrosia - administration 2015-07-15 09-50-05](https://cloud.githubusercontent.com/assets/11734/8704285/e5032f32-2ad6-11e5-8432-ea74073eb378.jpg)

I tried on both Chrome and Firefox. Any other clue on how I can reproduce the issue?

**Comment by kevlardev** [comment]
I'm getting the same as djamil, it appears to be working properly in all my tests. Were there any conditions or special circumstances that might be causing this to fail (custom outlines, configuration changes, etc?).

![screen shot 2015-07-15 at 11 52 17 am](https://cloud.githubusercontent.com/assets/4529755/8704409/697be72a-2ae8-11e5-89ff-38d6bfff7c3e.png)

**Comment by w00fz** [comment]
Do you have an empty Menu @sural98 ?

**Comment by w00fz** [comment]
This should be fixed now.

**Comment by sural98** [comment]
It is fixed now with the latest update.
FYI. There was a menutype not defined in #__menu_types

**Comment by mahagr** [comment]
Which was the menu type?

**Comment by sural98** [comment]
It was a user-defined one: gallery
There were 5 menu items assigned to that.
