### ISSUE TITLE
Editing a subtitle in Menu Editor causes all of the subtitles to get lost after save.

### ISSUE THREAD

**Issue by titro** [gantry/gantry5#579]
Joomla 3.4.3 with latest Gantry 5.0.0

Subtitle functionality is broken.

If a add a Subtitle in Menu manager (Parent)it is shown in the preview and can be sucessfully saved (or looks so).

But:
- Subtitle is not added to the menu entry in Frontend
- If i go back to Setup and open Menu Manager again, the submenu entry does not exist

**Comment by marktaylor46** [comment]
I can confirm this too.

But also. in joomla menu manager. if you complete the link type > link title attribute field then that then does shows on frontend - but all the other subtitles have vanished from Gantry 5 menu manager.
![2015-07-15_15-37-25](https://cloud.githubusercontent.com/assets/11683218/8701094/b9c97f0c-2b07-11e5-8041-0ab35ba9597d.png)
![2015-07-15_15-37-13](https://cloud.githubusercontent.com/assets/11683218/8701098/bdd352b2-2b07-11e5-9735-e39c318b74b9.png)
![2015-07-15_15-38-12](https://cloud.githubusercontent.com/assets/11683218/8701103/c2f7fffe-2b07-11e5-8535-25643428d6b5.png)

**Comment by w00fz** [comment]
When you say submenu do you mean subtitle or a sublevel?

**Comment by marktaylor46** [comment]
my apologies - I mean the subtitle text when you open ambrosia they are all set, change one of them and they all vanish - only way to get them back is to add them in joomla menu manager.

**Comment by w00fz** [comment]
Maybe let's wait and see what @titro was referring too, it might be the same issue.

I'm suspecting that he created an empty sublevel, saved and the sublevel didn't show on frontend. This is expected, since it's empty there's nothing to show on frontend.
For instance, if Home is not a parent item and you click on it, you will get a sublevel (so that you can add Particles and Modules in it), although if it's empty it will just remain a simple menu item.

But I'd like it to be clarified as he might well be referring to subtext.

**Comment by titro** [comment]
Sry! I mean subtitle of course! Not submenu!
Am 15.07.2015 6:59 nachm. schrieb "Djamil Legato" <notifications@github.com

**Comment by mahagr** [comment]
@titro Could you try out the last CI build?

**Comment by marktaylor46** [comment]
@mahagr I just tried this and it does seems fixed to me - obviously it doesn't get back subtitles that you already lost though - you have to add them back yourself.

**Comment by mahagr** [comment]
Yeah, what is lost is lost... We need to get 5.0.1 out soon to avoid more user issues..

**Comment by kat05** [comment]
i can confirm the fix, i am now getting a proper notification:

400 Bad Request
Oops, Failed to save /ambrosia: Menu Item must have a title..

**Comment by mahagr** [comment]
Actually this one was not that bug. :) The fix for this is to save subtitle information, not to display error.

**Comment by kat05** [comment]
sorry, i commented on the wrong ticket. but the subtitles can now be edited without getting lost. :)

**Comment by titro** [comment]
Fixed, thanks!
