### ISSUE TITLE
There are not needed options in the Menu Selection Dropdown

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#581]
These two options from the screenshot aren't needed in WP as you cannot set menu as active or default.
![hydrogen theme gantry5 wordpress wordpress 2015-07-15 21-57-41](https://cloud.githubusercontent.com/assets/1641534/8708525/c956b018-2b3c-11e5-8d98-7113c8837bb2.jpg)

**Comment by newkind** [comment]
These 2 unnecessary options in the dropdown are still present for WP

http://monosnap.com/image/3TglxY3zq20dDdI5bMB3Iz3rPSV5XI.png

**Comment by w00fz** [comment]
You can see how i implemented it and fix it @newkind , at least you also get an idea on how this works.
