### ISSUE TITLE
Add Edit Button to open Module Edit

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#582]
Add a Edit Button on Module Instance Particle if the module is already linked to Module Instance so we open the module edit right away and not the module index page...

![2015-07-16 00 38 00](https://cloud.githubusercontent.com/assets/10489911/8711548/3a5d536e-2b53-11e5-95aa-6e6b9b2aa032.jpg)

**Comment by w00fz** [comment]
You can click on the link `Joomla's Module Manager` and it will take you automatically to the Module settings in Joomla, the links gets also automatically updated every time you pick a different module.

Although this brought up an issue with the link not getting properly updated on first load, which is now fixed.

Thank you!
