### ISSUE TITLE
Menu dropdowns on desktop don't work when Offcanvas is empty

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#583]
I don't see any issue open for this. The js is broken and will not change between `g-inactive` and `g-active` on dropdown. 

Ok, it will only if you add `mobile menu` particle in layout.

@w00fz

**Comment by mahagr** [comment]
I saw another issue on this, not sure where I saw it. I think it was on gitter chat..

**Comment by devilstars** [comment]
Confirmed. When i've upgraded gantry from RC3 to 5.0.0 dropdown items have stopped to show on mouse hover. Downgrading to RC3 fixed it.

**Comment by kat05** [comment]
i can confirm this issue. as long as the mobile menu particle gets loaded, the dropdown works fine.

**Comment by mahagr** [comment]
If I recall it right, there was JS error which caused state not changing.

**Comment by kat05** [comment]
Timestamp: 16/07/15 13:17:15
Error: TypeError: this.offcanvas is null
Source File: http://kat05.dev:8888/jo_ambrosia_demo/media/gantry5/assets/js/main.js?55a79268
Line: 425
