### ISSUE TITLE
Administrator gliches

### ISSUE THREAD

**Issue by ramon12** [gantry/gantry5#585]
There are some gliches, tested with joomla 3.4.3, gantry 5.0.0 and last CI, the gliches can be reproduce.

Resize browser or mobile view: Left padding should be as right, particles is going out of view (and the buttons should  have margin-buttom,is not good on touch)
![1](http://l3.picsurge.com/ZI8RpC/1.png)

Particle overlap layout
![2](http://l3.picsurge.com/ZI8RpC/2.png)
Broken particles view
![2.1](http://l3.picsurge.com/ZI8RpC/3.png)

Drop shows without selecting a menu
![3](http://l3.picsurge.com/ZI8RpC/4.png)

Pick a particle broke entire administrator, can't select or go back
![3](http://l3.picsurge.com/ZI8RpC/5.png)

**Comment by w00fz** [comment]
I cannot see any of that, it's like you are missing a lot of JavaScript and CSS.
I see you are using `localhost`, can you try on a remote server? Also try `127.0.0.1` instead of `localhost` or create a proper local domain (ie, `gantry.dev`)

**Comment by w00fz** [comment]
Also try to open the inspector, I am quite positive you are getting some errors reported in there.
This is definitely not how it looks like normally and also the first time I do see the admin broken like that.

**Comment by ramon12** [comment]
Tested even on host, the pics was taken on localhost, still have those

**Comment by w00fz** [comment]
Can you give me access to the remote host by any chance? You can PM me on Gitter.

**Comment by w00fz** [comment]
This is how I see the Menu for instance in both mobile and desktop:

## Mobile
![mobile](https://cloud.githubusercontent.com/assets/11734/8737048/219cd856-2bd3-11e5-9b99-409d963dd656.jpg)

## Desktop
![dekstop](https://cloud.githubusercontent.com/assets/11734/8737062/311c9816-2bd3-11e5-831e-f4331cfe31f7.jpg)

Same on different instances I have with both symbolically linked Gantry 5 and 5.0.0.

**Comment by ramon12** [comment]
Have you tried to resize browser window?

**Comment by w00fz** [comment]
Yes like this: https://cloudup.com/cW4s2dzEwBZ
That's what you meant right?

**Comment by w00fz** [comment]
Thanks for contacting me on Gitter @ramon12, all the issues you reported in here and on Gitter are now fixed!
