### ISSUE TITLE
Wordpress - 404 Not Found  Oops, Outline not found.

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#588]
Using a WP install with Gantry and Callisto hebe linked.

in the 'Outlines' screen i did the following:

1. Hit the 'Duplicate' icon on the 'Home' outline
2. Rename the Duplicate to 'My Home' by using the LITTLE pencil icon next the outline name.
3. Hit the BLUE pencil icon 'Edit' and the error shows.

404 Not Found
Oops, Outline not found.

When I do it the exact same way in Joomla, I do not get an error.

![g5_wp_outline_not_found](https://cloud.githubusercontent.com/assets/5719486/8744782/458d32fe-2c7a-11e5-8ae8-d00898aacf18.png)

**Comment by mahagr** [comment]
Thanks, I forgot to add issue on implementing missing bits on this page.

**Comment by mahagr** [comment]
@w00fz Some Javascript changes are needed; I'm now passing id and outline variables with the request. The first one is the div id to be replaced and the second contains html.

As id of the div changes, you need to target the parent tag in order to add the html.

**Comment by mahagr** [comment]
@w00fz Is there a change me to signal that full page reload on the content is needed? Or a way to tell that content in div id=xxx needs to be refreshed?

We need a quick workaround on this issue to get rid of the error and changing outlines to use ids would have some side effects which would push this fix into a few weeks into future.
