### ISSUE TITLE
Wordpress - Whoops \ Exception \ ErrorException (E_WARNING) in Menu editor when no menu is present

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#589]
Trying to open the G5 Menu editor will throw an error if there is no menu set up in WordPress.

Whoops \ Exception \ ErrorException (E_WARNING)
in_array() expects parameter 2 to be array, null given 
Open: /Applications/MAMP/htdocs/gantry5/git/gantry5/src/classes/Gantry/Component/Menu/AbstractMenu.php 

Please see pic.

![g5_wp_nomenu](https://cloud.githubusercontent.com/assets/5719486/8745543/40cf10d2-2c81-11e5-8ff3-0b9ffb0498b2.png)

**Comment by mahagr** [comment]
Same as #592.

**Comment by mahagr** [comment]
Fixed in #626
