### ISSUE TITLE
Layout allows multiple pagecontent

### ISSUE THREAD

**Issue by WebTread** [gantry/gantry5#59]
Not sure in what way this would ever make sense to allow the pagecontent Position to be added twice. Right now it does allow that and it simply adds your page content twice on the page. Anyhow thought it was worth mentioning. Maybe this was intentional.

**Comment by w00fz** [comment]
We initially thought of limiting the Pagecontent to only be dropped in once but then realized there is no reason for that. There might be situations where you actually want to show the content twice or more. It might not make much sense in Joomla but it might be useful in some other platforms.

I honestly don't think we would ever use it that way nor that it will be a common scenario but at least it's possible and not restricted.

**Comment by WebTread** [comment]
Yeah after submitting it I thought there may be a circumstance where you do something completely out of left field where a repeat may be desired.
