### ISSUE TITLE
WordPress - Developer/Production toggle broken

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#591]
At first I saw the word 'Development' and used the toggle. That changed it to 'Production'.

When I now keep using the toggle, it will always say 'Production' no matter which way the toggle is set.

Also, the purple message, will always say 'Production mode enabled', it will never mention 'Development'.

![g5_wp_production](https://cloud.githubusercontent.com/assets/5719486/8745993/54185eba-2c85-11e5-9f50-ecf66f5447bb.png)

**Comment by mahagr** [comment]
Same as #590.

**Comment by mahagr** [comment]
Fixed in ce2fa4f
