### ISSUE TITLE
Changing menu item alias results in order change in g5 menu manager

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#595]
When you change the alias of a menu item in joomla menu manager then when you return to G5 menu manager the menu item will have been moved (order) to the last in the menu

e.g menu/alias
1/a 2/b 3/c 4/d showing in joomla menu manager and g5 menu manager
change alias of menu item 2 from b to xxx and when you return to g5 menu manger you will see
1/a 3/c 4/d 2/xxx
Since the menu item ID's have not changed at all I wonder why the menu has changed order in g5 menu manager when it could have been preserved.

Also wondering if it's possible to keep order of items in sync between the two menu managers? E.g. Joomla has the ability to drag and drop order of menu items but this does not get reflected in g5 menu manager and vice-versa.

Regards, Mark.

**Comment by mahagr** [comment]
I thought that it's already working (as long as you do not change id); I need to check this out and look what's failing.

**Comment by bomkallo** [comment]
I've probably hit same issue while using falang translation plugin, so I have one menu for 'every language' and the rest is handled with that tool. 
At beginning I was getting weird menu links behavior, but after the end I found them in correct order because in most cases I kept original aliases. Today I started to put german aliases instead and the menu order was permanently stuck, so I got back to originals, saved everything few times and now it fits Joomla order again.

**Comment by jameswadsworth** [comment]
Gantry 5.2.13 and Requim 1.
Firstly if I change the order of menu items in the joomla menu manager these changes are NOT reflected in the Gantry template menu manager. And vice versa: you can change the order of the menu items in the template and then go to the joomla menu manager and the order is different. Gantry menu order is always implemented in the frontend not the order under Joomla menu manager. It is not very intuitive and I will love explaining this to my clients (plus I am not sure I want my client having access to the template to change the menu order. They have enough trouble understanding updating content and linking menus. Now they have to go the template menu to change the order!!!)

Secondly I have run in BomKollo's problem. We set the right order in both Joomla menu and manager and Gantry template menu. We then translated the menu's using Falang, and for the translated menus the order does not reflect the order in the original language in either the Joomla menu manager or the Gantry template manager. We will try restoring the original alias names in the translations to see if that restores the order.

**Comment by mahagr** [comment]
Newest Gantry should now be able to work properly with changing aliases, including (but not tested) with Falang.

Note that menu ordering is still not being synched with Joomla menu.

**Comment by mahagr** [comment]
See issue #552 for keeping menu item ordering in sync between Joomla and Gantry.

Closing this issue as it fixes the issue described in the title.

**Comment by jameswadsworth** [comment]
Great. Looking forwarding to testing this. And will send feedback in due course.
