### ISSUE TITLE
JQuery seems loaded correctly but when executing a script throws an error that jquery is not defined...

### ISSUE THREAD

**Issue by arivera12** [gantry/gantry5#596]
This is the script that doesn't work.... and its ok written I just want to hide the title for the home page
<script type="text/javascript">
   JQuery(document).ready(function() {
      JQuery(".page-header").hide();
});
</script>
Here is JQuery loaded correctly and there is no console error...
![screen shot 2015-07-18 at 8 03 07 am](https://cloud.githubusercontent.com/assets/5600102/8762370/3045e0b4-2d45-11e5-88ce-ddc8783009a3.png)

But on the console say that query is undefined... This is very weird...
![screen shot 2015-07-18 at 8 03 51 am](https://cloud.githubusercontent.com/assets/5600102/8762384/79f27ce0-2d45-11e5-9d13-98776d558024.png)

What could be wrong here?

**Comment by w00fz** [comment]
Your test should be `jQuery` not `JQuery`
```js
typeof jQuery === 'undefined'
```

**Comment by arivera12** [comment]
My bad... I always user the dollar sign why I can't use it here?

**Comment by w00fz** [comment]
It's never a good idea to use the `$` sign actually, when other js are loading they may be using `$` as well and your script would be referencing the wrong one. 
You can always write your script in an anonymous function to use `$`, ie:

```js
(function($) {
   // you can now safely use $ in here
})(jQuery));
```

// Djamil Legato // From iPhone //

**Comment by arivera12** [comment]
All my scripts uses the $ sign... But that's ok I will just search and replace them and thanks for that note I thought that jquery was the only framework that uses the $ sign...
