### ISSUE TITLE
'&' symbol in external menu item not outputting properly

### ISSUE THREAD

**Issue by gospelpowered** [gantry/gantry5#598]
Hey, i think this might be a bug but not sure if it's a gantry thing. 

When i put in an external URL on the frontend menu it renders it wrongly, i'm specifically referring to the & symbol. So a link like:

https://domain.com/cart.php?a=add&domain=register

Gets output as this on the menu:

https://domain.com/cart.php?a=add&amp;domain=register

So then the link doesn't work. 

Is this something you guys can address?

Thanks a lot.
Igor

**Comment by w00fz** [comment]
The link you put in is via Joomla Menu Manager or G5 Menu Editor?

**Comment by w00fz** [comment]
I tried creating an External URL Menu Item in Joomla with URL `index.php?hello&world=foobar` and on frontend it did render normally.
I know Joomla does convert to `&amp;` when the `&` is in content, although mine seems to be working fine.
What are your SEO settings? Also are you using the Joomla `.htaccess`?

**Comment by mahagr** [comment]
@gospelpowered Can you check the source code if menu item url is double escaped?

**Comment by gospelpowered** [comment]
I am using .htaccess. 

Looking at the source code i see this, which is strange:

https://domain.com/cart.php?a=add&amp;amp;domain=register

When i hover over the link i see:

https://domain.com/cart.php?a=add&amp;domain=register

Thanks

**Comment by mahagr** [comment]
We changed the escaping a bit, this might be result of that. Will check it out.
