### ISSUE TITLE
Operation timed out error accessing sites with Hydrogen & Gantry 5

### ISSUE THREAD

**Issue by nkorop** [gantry/gantry5#599]
Unfortunately the issue still exists after upgrade to last Hydrogen and Gantry 5.

The error message is "Operation timed out after 10162 milliseconds with 0 out of -1 bytes received" and the ms have different value.

Any idea how to solve it?

Example of site with this problem: www.elefsina.info

**Comment by w00fz** [comment]
If you go in G5 admin and select the Base Outline, do you get any error when you `Compile CSS` from the `Styles` tab?

**Comment by nkorop** [comment]
I did Compile CSS and there was no error...
I made a search on google and the error has connection to curl... but I have problem only on sites with Hydrogen template and Gantry 5. The other sites with different template never caused any problem.

**Comment by mahagr** [comment]
We aren't using curl anywhere, so it cannot be it. What I did last time as to extend PHP timeout every time a CSS file gets compiled. There are 3 options why it's not working:

* Function set_time_limit() has no effect when PHP is running in safe mode. There is no workaround other than turning off safe mode or changing the time limit in the php.ini.
* Apache is configured to stop execution after 10 seconds.
* It's not CSS recompilation that takes over 10 seconds.

Please contact me in Gitter and we can take a look what happens.

Do you know when this error occures?

**Comment by nkorop** [comment]
@mahagr ok. I am waiting to you on Gitter chat...

**Comment by nkorop** [comment]
Together with @mahagr we worked on this issue (Thank you!)
ok... so... the issue was a module {JB:Social Share}. I have disabled it and site is working faster and no errors for the moment...

So the case is closed and thank you for your time and help!
