### ISSUE TITLE
Exception error after installation

### ISSUE THREAD

**Issue by proweb** [gantry/gantry5#6]
Localhost Joomla installation:
## System Info:

![index.php?option=com_admin&view=sysinfo](https://dl.dropboxusercontent.com/u/9469830/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_336.png)
### Additional extensions:
- K2
- JCE
- Widgetkit 2
- NoNumber Advanced Module manager
- Switch Editor from Anything Digital
- Mootools Enabler/Disabler By Roberto Segura

 ### Errors after install:
*in template manager:*

![on Menu click](https://dl.dropboxusercontent.com/u/9469830/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_334.png)

*in front:*

![in front cache error](https://dl.dropboxusercontent.com/u/9469830/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_335.png)
![cache error details](https://dl.dropboxusercontent.com/u/9469830/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_337.png)

**Comment by mahagr** [comment]
I believe that this is bug and I'll look it after the weekend. :)

Nice and complete report! Really helped me to track it down. Though I'm getting a bit different variation of the issue (on unserialize only).
