### ISSUE TITLE
Home Page Notices & Error

### ISSUE THREAD

**Issue by WebTread** [gantry/gantry5#60]
Joomla 3.4.1 site updated from Joomla 2.5.28. Installed G5 and Hydrogen. Install went fine. All pages show except Home page which is blank with the following notices and fatal error...

Notice: Undefined index: in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 126

Notice: Trying to get property of non-object in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 207

Fatal error: Call to a member function get() on a non-object in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 267

**Comment by w00fz** [comment]
Can you try loading the Home configuration in admin and Save, see if it fixes the home page?

**Comment by WebTread** [comment]
Ok it seems the error occurred because the Home menu item type was set to Cerulean Blog. I was testing G5 on a dev site I'd done a little work on so didn't even think about that till after trying your suggestion.

So not sure if this will help you guys in any way by knowing this throws an error but maybe it will come in handy as maybe others will have a similar issue and you may have some work around or notice that can be given to them to let them be aware when their settings are such. Any way hope to help more if I find anything.

**Comment by w00fz** [comment]
Now I read again the error:

```
Notice: Undefined index: in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 126

Notice: Trying to get property of non-object in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 207

Fatal error: Call to a member function get() on a non-object in /home/webtread/public_html/sites/svm/libraries/gantry/gantry.php on line 267
```

Being `libraries/gantry` it means it is Gantry4 and that is where the error is coming from, in Gantry5 the location is `libraries/gantry5`.

We should probably have a look at this either way @mahagr.

Thanks @WebTread

**Comment by WebTread** [comment]
Yep anything I can do to help so we all can start using it and make the web a better place for us all :D

**Comment by mahagr** [comment]
Yes, I can confirm that this is an issue in Gantry 4, not in Gantry 5.

The issue is in gantry_getTemplateById($id), which for some reason returns null as if it doesn't find the template style which it is trying to access.

To me it was trying to fall back to Master style, which is likely null (or not set).

**Comment by mahagr** [comment]
This issue only exists with Cerulean and Fresco templates and is related on how those override blog page of articles. There's really no way to fix it as changing template will break the page.

There's really nothing I can do to fix the issue on those overrides -- you just need to change the menu type back to normal.

But I'm going to keep this open as it reminds me to create a new and faster home page. :)
