### ISSUE TITLE
Use more strict Template ACL from Joomla 3.4.2+

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#600]
See https://github.com/joomla/cms-security/issues/14 and https://github.com/joomla/cms-security/pull/15 for details.

**Comment by topwebs** [comment]
We normally set clients as Administrator and deny them access to the Template Manager. However, with G5, we would like them to be able to edit G5 particle modules. If we currently deny access to the Template Manager Administration, then they cannot edit the G5 particle modules. Not sure if this is a G5 or more likely Joomla issue.

**Comment by mahagr** [comment]
@topwebs I just implemented ACL that obeys the rules you have set for menu and template components. Gantry itself doesn't yet have finer ACL, but at least user cannot access anything he's not supposed to touch.
