### ISSUE TITLE
WordPress - duplicating system outlines does not work

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#601]
In Joomla, when going to Outlines and hitting the 'Duplicate' button for example on the system outline  'Body Only', will add a duplicate to the outline.

In WordPress, this does not work, it looks like nothing happens.

**Comment by mahagr** [comment]
None of the actions in that screen works yet.

**Comment by mahagr** [comment]
Duplicating should now work.

**Comment by kat05** [comment]
fix confirmed! :+1:
