### ISSUE TITLE
WordPress - Can't pick any widget in 'Widget Instance' particle

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#604]
I've dragged a 'Widget Instance' into my layout and then hit the Gear icon.

It correctly opened a popup with a button to 'Pick a Widget'.

I clicked on it, another popup opened which was titled 'Pick a Module' (Joomla?) and there was nothing there that I could select.

![g5_wp_widgetinstance](https://cloud.githubusercontent.com/assets/5719486/8775573/bd9a9432-2ee9-11e5-98e5-8953f7667561.png)

**Comment by mahagr** [comment]
I'm just implementing this feature in separate branch. :)

**Comment by mahagr** [comment]
Should be fixed now.

**Comment by kat05** [comment]
confirmed
