### ISSUE TITLE
WordPress - Duplicating Outlines does not load the used Layout

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#605]
In WordPress using Callisto for example, i duplicate the 'Callisto - Home' outline which is using the 'Home' layout. The Duplicate gets automatically named 'Callisto - Home (2)'. When I then check the Layout tab of this new outline, it says: Layout (Unknown) - No layout specified!

In Joomla, when I do the same thing, the 'Home' layout gets automatically added to the duplicated outline, there is no need for me to load it myself.

**Comment by mahagr** [comment]
Not implemented yet. Thanks for the reminder.

**Comment by kat05** [comment]
fix confirmed :+1:
