### ISSUE TITLE
Remove or comment jquery.noconflict()

### ISSUE THREAD

**Issue by arivera12** [gantry/gantry5#606]
I have tons on plugins that uses the $ sign. I went to the folder /media/jui/js/jquery-noconflict.js and commented the jQuery.noConflict(); and also deleted my browsing data, cache and everything, but jQuery.noConflict(); is not commented... What I am doing wrong?
Here I commented the jQuery.noConflict();
![screen shot 2015-07-20 at 8 10 15 am](https://cloud.githubusercontent.com/assets/5600102/8780633/3af97572-2ed8-11e5-93f5-fb88a80cd70f.png)

Here it shows that its isn't commented....
![screen shot 2015-07-20 at 8 10 26 am](https://cloud.githubusercontent.com/assets/5600102/8780659/5c21b0e8-2ed8-11e5-9c1a-91a595626b38.png)

**Comment by w00fz** [comment]
Maybe you have other plugins loading providing the same file? I would do a search in the whole Joomla instance. When you hover over the `jquery-noconflict.js` in the inspector, it should tell you the exact location.
Gantry5 and Hydrogen do not use nor provide jQuery so I doubt this has anything to do with Gantry5.

**Comment by mahagr** [comment]
I agree that it has nothing to do with Gantry 5 -- it's Joomla that loads that file. Check also that there's nothing loading Mootools, as it's the likely cause of enabling the feature.

**Comment by arivera12** [comment]
Ok I am still looking for removing that I will let you know when fixing this issue for me and come with the solution...

**Comment by w00fz** [comment]
I'm going to close this now for inactivity, feel free to add to the issue when you find a fix!

**Comment by mahagr** [comment]
And this is really not Gantry issue; it's issue of not using best practices while writing JS code. Using plain $ is really, really bad in Joomla and likely just breaks everything; see no-conflict in jQuery documentation.
