### ISSUE TITLE
WordPress - Assigning Outline B does not remove Assignments in Outline A

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#607]
When you create a new Outline and assign it to certain pages, any other Outlines that were assigned to those pages, should get unassigned automatically.

This is currently not yet happening in WordPress and you can actually have several different outlines using the same assignment settings.

**Comment by mahagr** [comment]
Good catch. Though I'm not sure if we should do that as WP assignments are different from Joomlas. Basically you can have multiple assignments and combinations of assignments with different priorities, which will then be calculated to get final score.

So basically you could have assigned outline A to all blog post in category X, but then you could have another higher priority outline for some pages that match certain additional condition. Scores are already implemented except in UI.

**Comment by newkind** [comment]
Yah, Matias is right. In WP you should be able to have multiple outlines assigned to the same items.

**Comment by mahagr** [comment]
I'm closing this issue as assignments aren't just menu items as in Joomla.
