### ISSUE TITLE
WordPress - Assignments don't seem to work at all

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#608]
I have a 'Home' outline which is NOT assigned anywhere and it's using Preset 4.
I also have a 'Testing' outline which is assigned to ALL pages and it's using Preset Preset 8.

For the life of me, on the frontend all I see is Preset 4. This is just an example, any other settings i have in the 'Testing' outline do not show on frontend either. Everything seems to come from 'Home' outline.

**Comment by newkind** [comment]
What front end page you're testing it ? Blog page isn't really considered a real page, so that might be an issue. Can you create a single page and load it in front end ?

**Comment by newkind** [comment]
The cause of the issue was hardcoded outline in theme files

**Comment by kat05** [comment]
confirmed :+1:
