### ISSUE TITLE
WordPress - Improve frontend message for when Timber is not activated

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#609]
When you don't have Timber running, all you see on frontend is:

> Theme cannot be used. For more information, please login to administration.

If possible, this message should be improved and actually mention Timber maybe?

**Comment by rhukster** [comment]
I agree we should definitely have information specifically about Timber

**Comment by newkind** [comment]
The thing is that this notice is not only for the Timber missing issue, but all other stuff also. If Timber is missing, we have a notice in the admin with click-to-install link.

**Comment by mahagr** [comment]
I have to disagree here, if you're on production site, you really do not want to give any extra information about the internal state of the site. As the error message suggests, logging into admin will tell you what is wrong -- actually you should already seen the message when you enabled the theme.

**Comment by mahagr** [comment]
I'm closing this one as invalid -- there is no reason to let all the users to know every single detail. The error message is already too detailed to my taste and should give admin enough information to figure out what is wrong -- just follow the instructions.

**Comment by RKPW** [comment]
mudah kok, masuk menu plugin kemudian aktifkan framework grav, kemudian refresh page awal selesai 🥇
