### ISSUE TITLE
Back-end compatibiliy with Chrome

### ISSUE THREAD

**Issue by Aesine** [gantry/gantry5#61]
Hi eveyone,
I'm having some problems with both the drag-and-drop layout manager and the color picker in Chrome (Version 41.0.2272.118 m on Windows 8.1)(gantry5 beta2).
I recorded two gifs, one with chrome, the other with firefox
Chrome : 
![chrome](https://cloud.githubusercontent.com/assets/11697476/6997527/d4f9593e-dbbe-11e4-8086-a1afcabb524d.gif)

Firefox : 
![firefox](https://cloud.githubusercontent.com/assets/11697476/6997541/2c9dfe74-dbbf-11e4-918f-6a235c0978e3.gif)

Do you know what causes the problem?

**Comment by adi8i** [comment]
I am not sure if is a bug or something wrong configured, because all this kind of problems i've seen till now was on a localhost .

Will be good if you can try on a hosting server :)

am i right #w00fz ?

**Comment by adi8i** [comment]
You can take a look here too : https://github.com/gantry/gantry5/issues/39

**Comment by w00fz** [comment]
Yes like @adi8i said it would be helpful if it was accessible for us to see what's going on there.
Also could you open the inspector and see if you are getting any JS error? If it's just a 404 regarding map files than that's not a problem, I'm wondering if there's something else conflicting perhaps.

**Comment by w00fz** [comment]
Was also thinking, could you go in the Menu Editor in Gantry 5 and see if you can drag-n-drop the items in there or if this is just an issue you are facing in the Layout Manager?

**Comment by Aesine** [comment]
I can't drag-n-drop the items in the Menu Editor. I'm getting main.js.map not found
![mainjsmap](https://cloud.githubusercontent.com/assets/11697476/7001918/9cb4221e-dc42-11e4-8cb0-5d05072dcfbb.png)
(I can't try a hosting server)

**Comment by Aesine** [comment]
I moved from MAMP to WAMP. Still getting the same issues.
This time both main.js.map and admin.css.map 404 not found.

**Comment by sural98** [comment]
The issue #39 is mine. You are experiencing the same. Is your computer a touch-screen one?

**Comment by sural98** [comment]
I have noticed today that I can drag-and-drop/resize using hand on my all-in-one touch screen while it won't work with a mouse.

**Comment by Aesine** [comment]
Yes it is a touch-screen computer, and layout manager works great with touch.

**Comment by w00fz** [comment]
I think @sural98 is onto something here. There might be an issue on the way `touch` vs `mouse` events are detected. This is going to be an interesting issue to resolve since I don't think anyone in RT as an all-in-one touch screen computer!

**Comment by Aesine** [comment]
When I disable touch events in Chrome settings, the mouse works fine!

**Comment by w00fz** [comment]
hey @Aesine I'm going to close this issue as there are more details in #39 and I am sure now it's the same problem
