### ISSUE TITLE
Layout Manager should display widget type (and title) instead of Widget Instance

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#612]
![hydrogen theme e2 80 b9 gantry5 wordpress e2 80 94 wordpress 2015-07-21 13-42-45](https://cloud.githubusercontent.com/assets/1641534/8799971/e52b90d0-2fae-11e5-8983-b8a4389ec18d.png)

Layout Manger should display widget type + widget title instead of the "Widget Instance" label. We need the widget title as if user will have multiple widgets of the same type (ie. Text Widget) next to each other, he will have to open modal to see which one is which.

**Comment by w00fz** [comment]
You can edit it yourself when you create a new widget. It's the pencil.
Works the same for Joomla Module Instance and particles, positions, etc.

**Comment by mahagr** [comment]
I think he meant to do it automatically. :) In Joomla module instance works just like that already (first time only).

**Comment by mahagr** [comment]
I'm removing important tag from this one as it's how it works in Joomla too. So this is actually not a Wordpress issue, but something we might want to fix in both.

**Comment by Boumy** [comment]
Aw, yes please add those titles, even for menu particles. Under joomla, some menu names are shown in the layout manager and some not. And its better in the default Outline than in the Home Outline. So according to me, its a bug.

**Comment by mahagr** [comment]
Widget is deprecated with WP 5.8 having the new Widget Blocks feature.
