### ISSUE TITLE
WordPress - resetting widget selection with x icon does not work

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#613]
I've added a new Widget to my layout and picked the calendar particle and saved.
It shows fine on frontend.

Now when I try to reset the Widget selection using the little round x icon that appears when i hover on the 'Edit Widget' button, nothing happens.

**Comment by mahagr** [comment]
If you noticed, also editing looses all data. Both are issues I was going to talk with @w00fz tonight. :)

**Comment by kat05** [comment]
resetting with x, so that's confirmed. got another ticket for the data loss which is still open.
