### ISSUE TITLE
WordPress - blog pagination displays vertically

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#614]
This is an Audacity RL using Hydrogen, the pagination displays vertically.

This probably is happening with the club themes, Callisto etc. too and needs a fix.

Please see pic.

![g5_wp_pagination](https://cloud.githubusercontent.com/assets/5719486/8804560/12deab34-2fcd-11e5-9306-60703f9ee1c7.png)

**Comment by newkind** [comment]
This is hydrogen, and it's like that because there's no styling for pagination yet ;)

**Comment by newkind** [comment]
Fixed in 0e8d266
