### ISSUE TITLE
WordPress - Changes in Base Outline not reflecting in other outlines

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#615]
using Hydrogen with
Base Outline
Hydrogen - Default and
Hydrogen - Home

In Joomla, when I change a setting in the Base Outline, for example i disable the Menu particle in the settings panel and save, then the change will also be applied automatically to the other 2 outlines.

In WordPress, when I disable the Menu particle in Base Outline in the settings panel and save, this does not disable it in the other 2 outlines.

**Comment by mahagr** [comment]
Actually this will happen also in Joomla if you first saved settings in that another outline and then changed base outline. This is because of there is no "Use Default" option in the toggle.

We need to implement 3-way toggle in order to support this.

**Comment by mahagr** [comment]
@w00fz How about adding third option to the toggle which will unset the value before sending form to the server?

**Comment by kat05** [comment]
@mahagr  not sure you understood me correctly, i did not say that i changed anything in the other outlines.

i only changed something in base outline, which was then not reflected in the other 2 outlines.

when i tested this, the behavior between joomla and wordpress was not the same.

**Comment by w00fz** [comment]
What @kat05 is describing sounds like inheritance issue specifically in Wordpress only.
Outlines are not inheriting from Base when needed, like Joomla does. Is this the issue you are describing @kat05 ?

**Comment by mahagr** [comment]
Inheritance bug has been fixed (was in Joomla too, but setup was different), but there's still another issue on not being able to inherit toggle state from base. So as long as you haven't saved settings in the current outline, you will get inherited values from base. But if you save settings, they will get locked to the values that were in base at the time of save action.

@w00fz Is there easy way to make toggle to have 3 stages: 1 / 0 / unset? Last stage would work just like our checkbox which disables the input.

**Comment by mahagr** [comment]
After talking in Hangout we decided that we are going to use the same checkbox approach for the enabled toggle (right side as for the other options). When checked off it would not send the field in POST request as well as it would grey out background of the whole card except of the enabled fields inside of the cards.

@w00fz Do you have time to implement this today?

**Comment by w00fz** [comment]
I am not entirely sure I understood what you meant there but I implemented it this way (see screenshot) which is what makes the most sense to me. I don't think 3 way toggles are good UI elements nor are easy to figure out. 

With this implementation I made I think it is all more consistent and more easy to understand for people.

![enabler-overrides](https://cloud.githubusercontent.com/assets/11734/9534871/d2f9221c-4cd0-11e5-9c8b-2083650bebb0.jpg)

If this is not what you meant at all just let me know and we can discuss it. Right now the enabler is just behaving like any other field in the form.

**Comment by mahagr** [comment]
Looks good to me. The only thing that bugs me though, is that if you click on the toggle while the item is disabled, you need to click again to get focus. Noticed the same thing in other fields too.

**Comment by w00fz** [comment]
That's expected behavior, it's a 2 steps process. Firstly you enable the override and then you chance value. Otherwise it would be too easy to accidentally chance overrides.
// Djamil Legato from Nexus 7
On Aug 27, 2015 23:33, Matias Griese <notifications@github.com> wrote:Looks good to me. The only thing that bugs me though, is that if you click on the toggle while the item is disabled, you need to click again to get focus. Noticed the same thing in other fields too.

**Comment by mahagr** [comment]
Thanks for the explanation. I think it works well, I'm just not sure how you can accidentally change value of input as I was assuming it was already active, just greyed out.
