### ISSUE TITLE
RuntimeException: Cannot override frozen service configuration executing a query...

### ISSUE THREAD

**Issue by arivera12** [gantry/gantry5#618]
A got a query that was already working, now the page throws an exception when executing that query...
What could be wrong?

This is the stack trace...
```
RuntimeException thrown with message "Cannot override frozen service "configuration"."
Stacktrace:
#9 RuntimeException in /home2/revocode/public_html/libraries/gantry5/vendor/pimple/pimple/src/Pimple/Container.php:76
#8 Pimple\Container:offsetSet in /home2/revocode/public_html/libraries/gantry5/classes/Gantry/Component/Theme/ThemeTrait.php:116
#7 Gantry\Framework\Base\Theme:setLayout in /home2/revocode/public_html/templates/g5_hydrogen/index.php:24
#6 require in /home2/revocode/public_html/libraries/joomla/document/html/html.php:578
#5 JDocumentHTML:_loadTemplate in /home2/revocode/public_html/libraries/joomla/document/html/html.php:635
#4 JDocumentHTML:_fetchTemplate in /home2/revocode/public_html/libraries/joomla/document/html/html.php:455
#3 JDocumentHTML:parse in /home2/revocode/public_html/libraries/cms/application/cms.php:1045
#2 JApplicationCms:render in /home2/revocode/public_html/libraries/cms/application/site.php:729
#1 JApplicationSite:render in /home2/revocode/public_html/libraries/cms/application/cms.php:258
#0 JApplicationCms:execute in /home2/revocode/public_html/index.php:45
```

This is the query

```
//Creamos el product key
$db = JFactory::getDbo();
$db->setQuery("SELECT REPLACE((SELECT UUID()), '-', '')"); 
$product_key = $db->loadResult();

//Preparamos el nuevo statement
$query = $db->getQuery(true);

//Definimos la columnas
$columns = array(
'user_application_id', 
'application_id', 
'user_id', 
'pc_changed',
'product_key',
'pc_username',
'platform',
'arch',
'pc_model',
'pc_cores',
'pc_mac_address',
'pc_ipv6_address',
'create_date'
);

//Definimos los valores
$values = array(
$db->quote(''), 
$jinput->getInt('application_id', 0), 
$jinput->getInt('user_id', 0),
1,
$db->quote($product_key),
$db->quote(''),
$db->quote(''),
$db->quote(''),
$db->quote(''),
0,
$db->quote(''),
$db->quote(''),
$db->quote(date("Y-m-d H:i:s"))
);

//Preparamos el query
$query ->insert($db->quoteName('zgq73_users_application'))
->columns($db->quoteName($columns))
->values(implode(',',$values));

//Ejecutamos el query
$result = $db->setQuery($query)->execute();
```

Here is the error throw ^

**Comment by mahagr** [comment]
Are you getting exception from the query? We had backwards incompatible change in error page (RC something) because of the old version didn't quite work. Check that you have the latest template and if you have created your custom one, compare the Joomla php entry files (index.php, error.php etc) against the latest ones.

**Comment by arivera12** [comment]
Yes the exception comes from the query I have Version: 5.0.1 / Released: July 16, 2015. I have the hydrogen theme installed and also updated with latest version...

**Comment by mahagr** [comment]
Can you try adding following code to index.php inside the theme, just after line 20:

    // Reset used outline configuration.
    unset($gantry['configuration']);

Let me know what happens. That is not the real fix as it may have some unwanted side effects.

Do you have some extension that allows you to change template styles?

**Comment by w00fz** [comment]
@arivera12 Any luck with the suggested fix from Matias?

**Comment by arivera12** [comment]
Nope, I just written my own class for accessing the db instead of using the joomla db class.

**Comment by w00fz** [comment]
Well I'm sorry about that, if you ever figure out what was the issue or you have additional informations to help us track it down, please let us know. 

In the meantime I'm going to mark the issue as closed, feel free to reopen if needed.

Thanks.
