### ISSUE TITLE
Error Gantry 5 Themes: Please enable 'System - Gantry 5 Framework' plugin!

### ISSUE THREAD

**Issue by Bullnados** [gantry/gantry5#620]
I got that message after the installation of Gantry 5.0.1 for joomla in Components-Gantry Themes
Also I go to Extensions-Plugins disabled and enabled "System - Gantry 5". And than no error shown in Components-Gantry Themes

Joomla! 3.4.3

**Comment by mahagr** [comment]
So all good then! Installer should enable this plugin by default, so I'm not sure why it wasn't doing that.

Did you just install the package?

**Comment by Bullnados** [comment]
Yes the one: joomla-pkg_gantry5_v5.0.1.zip. I tried it some times. I have Installed gantry 4 before. than Gantry 5. Removed gantry 4 and than Gantry5 but problem still exists

**Comment by mahagr** [comment]
Should not matter what you have been installing before or after. Did you get any error message during installation process?

**Comment by Bullnados** [comment]
Mmmh i think not otherwise i would have searched the install error message

**Comment by marktaylor46** [comment]
Please see these two posts from forum
http://www.rockettheme.com/forum/joomla-template-callisto/242021-please-install-gantry-5-framework-before-installing-callisto-template?start=0#1203414
http://www.rockettheme.com/forum/joomla-template-ambrosia-solved-threads/244217-solved-error-please-install-gantry-5-framework?start=0#1215061

I have not seen the issues myself though.

Regards, Mark.

**Comment by w00fz** [comment]
I think those are different errors than the one reported here.
Those are about installing the framework, I've seen that happening before and I think it was also fixed some time ago.

This one error from @Bullnados is about "Enabling Gantry 5 system plugin", which I never seen before happening since it should be automatic after ones install Gantry 5.

@Bullnados is this issue still happening for you or was it just a glitch?

**Comment by Bullnados** [comment]
Yes still happening. 
But issue is only after install.After dis/enable manual all is fine.

**Comment by mahagr** [comment]
@Bullnados Are you installing the package as it is or are you individually opening files inside?

I'm asking this because of the package installer should enable and lock most of the extensions just after all the packages have been installed. Go to installer and from there manage tab. Filter by Gantry and see if most of the Gantry 5 packages are locked..?

**Comment by Bullnados** [comment]
I think to 95% nothing was locked. But I start a try at weekend. I installed the packege which is linked in HP for joomla

**Comment by mahagr** [comment]
If nothing was locked, you have issue in your site. Either package installation was somehow aborted (which you would for sure have noticed) or your Joomla installation doesn't run post-install scripts for some reason.

There are two possible reasons for this:

1) When you update Joomla, there's post-installation check that removes all the extra files from /libraries folder. I've seen a lot of cases (common enough to notice) where this doesn't happen and Joomla keeps on using the wrong or old files.

2) You have some extension installed into your system, which messes up the installation -- likely from the same reasons.

Is your Joomla installation upgrade from 2.5 or even older version?

**Comment by Bullnados** [comment]
No. I think updated from 3.3. But surely not 2.5

**Comment by w00fz** [comment]
Would be really helpful to understand if this is an isolated issue on that setup only or if it is perhaps some server configuration preventing the post-installation to get triggered.

Is it possible for you to create a brand new and fresh Joomla setup and try to install a [CI Build](http://gantry.org/downloads#ci-builds) in it, to see if that automatically enables the system plugin as well as locking the packages as expected?

This is what you should get after installation, if you browse to `Extensions Manager -> Manage` and then filter by `gantry`:

![extension manager - manage](https://cloud.githubusercontent.com/assets/11734/9258170/c6eee420-41ae-11e5-87f8-3f4319cd3874.jpg)


Thank you!

**Comment by Bullnados** [comment]
Thanks for Screenshot. Here is my one directly after new installation:
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/9259768/e1a8af1c-4203-11e5-835d-1b6a70c8e9d0.PNG)
New Joomla installation need some time.

**Comment by w00fz** [comment]
So this one is the same installation where you don't get the System plugin automatically enabled after install?

**Comment by Bullnados** [comment]
yes

**Comment by w00fz** [comment]
Is this a production site? If not, have you tried to uninstall Gantry completely and then installing again?

**Comment by Bullnados** [comment]
At the moment its not production site. will be new website for our association.
Completely uninstall is: select all eight components seeing ins screenshot? If yes, than i had uninstalled complete.
MMh strange did nothing except clearing joomla cache and now it works

**Comment by w00fz** [comment]
I guess you had old files cached that were being used when installing, instead of properly using the new ones.

So you are getting the system plugin auto enabled all the times now?

**Comment by Bullnados** [comment]
Ok deleting cache had nothing to do. Empty cache and new installation. No problem.
I try to get gantry cached and start ne installation again :)
Open website with hydrogen theme to fill cache and installed Gantry again. No problem
So i would close the issue.

**Comment by Bullnados** [comment]
And sorry for my English

**Comment by w00fz** [comment]
No worries, thanks for taking the time helping us tracking this out and glad that at least you managed to get it working.
Let us know if the problem occurs again.

**Comment by Bullnados** [comment]
Will do that. I still have one idea. Containing crosstec themes and gantry 4. Wanna test that in the next days/weeks

**Comment by ppetree** [comment]
Just downloaded Gantry 5.2.10 and the same version of Hydrogen.

This is an error that should not be happening guys.  I had to go to extensions, plugins, disable the three plugins and reenable them before I could install hydrogen.

**Comment by mahagr** [comment]
Usually it isn't an issue as in most environments this is working out of the box. You said that the plugins were enabled but didn't work?
