### ISSUE TITLE
Widget Positions and Widget in Theme Settings should be hidden

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#621]
There's no point of having "Widget Poisitions" and "Widget" cards in Theme Settings, as they should be enabled at all times. Also the default values can or "Pick a Widget" button can be very confusing and misleading.
![hydrogen theme gantry5 wordpress wordpress 2015-07-22 14-02-40](https://cloud.githubusercontent.com/assets/1641534/8824899/75e45bcc-307a-11e5-8d28-19bbe1a5d905.jpg)

**Comment by mahagr** [comment]
I think we still need to have these two showing up as they allow you to set default chrome site-wide or for the current layout.

What if we just hide the first parameter, which needs to be overridden in layout?
