### ISSUE TITLE
In Ambrosia our RokSprocket attempts to open image files outside of the webroot as defined in open_basedir

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#622]
Our Ambrosia  theme is referencing a RokSprocket called image outside the webroot.

E.g.
/home/some-site/public_html/templates/rt_ambrosia/../../../images/rocketlauncher/home/slideshow/img-01-preset1.jpg

This causes an exception to be thrown if php.ini's open_basedir directive has been configured to prevent access outside webroot.

This is happening at:
http://www.rockettheme.com/forum/joomla-template-ambrosia-solved-threads/244542-solved-bug-exception-ambrosia-is-referencing-an-image-outside-webroot?start=0#1218950

http://www.rockettheme.com/forum/gantry5-for-joomla/245181-cannot-add-module-instances-positions-or-page-content?start=0#1220178

**Comment by mahagr** [comment]
I have already fixed ../ references in https://github.com/gantry/gantry5/commit/234bd898753cc7c94c6360a44159b61cbf8fdbce

**Comment by kat05** [comment]
people are still reporting issues with latest ci builds, so i asked for login details:
http://www.rockettheme.com/forum/joomla-template-ambrosia/245737-twig-runtime-error?start=0#1223981

**Comment by mahagr** [comment]
@kat Latest CI (from few hours back) will allow users to disable our error screen when they put Gantry into production mode and disable debug mode in Joomla. Installed latest Ci into the site and put it into production to avoid getting the error.

**Comment by mahagr** [comment]
Alright, the issue is still there in development mode, but production is all good.

**Comment by marktaylor46** [comment]
I have another member who has apparently got the same issue....
http://www.rockettheme.com/forum/joomla-template-ambrosia/246460-update-gandry-5?start=0#1227271

**Comment by mahagr** [comment]
I'm not able to reproduce this with latest public version (5.1.2). I tried ```open_basedir``` for both webroot and subdirectory and both of them were working just fine. I remember that I was able to reproduce this issue earlier, but I have no idea where users get this issue.
