### ISSUE TITLE
WordPress - data gets wiped out when editing Text Widget

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#623]
I've added a new Widget to my layout and selected the Text Widget.

I gave it a title and some text, then hit 'Apply' and then 'Apply and Save'

Refreshed the frontend and everything showed up fine.

Then I went back into the widget and decided to hit the 'Edit Widget' button. All of my data (title and text) i had previously entered was wiped out.

**Comment by mahagr** [comment]
For some reason checkbox isn't working yet; maybe the data I pass to the form is in wrong form? Right now it is true, maybe it should be a string?

**Comment by kat05** [comment]
confirmed!
