### ISSUE TITLE
Add PHP regex functions as Twig extensions - preg_match, preg_replace etc.

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#627]
Add PHP regex functions as Twig extensions - preg_match, preg_replace etc.

**Comment by rhukster** [comment]
What do you need these for?

**Comment by newkind** [comment]
In example detection of  and  tags in post content, when user sets custom Read More label. This would also help with other stuff as Timber isn't ideal in all cases.

**Comment by newkind** [comment]
Fixed
