### ISSUE TITLE
Remove layout tab from base outline

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#628]
As confirmed by @mahgr the layout for the base outline is not used anywhere (at the moment). 

I suggest removing the layout tab from base outline for now (as we do with the assignments tab) since it just leads to confusion when people change things on the layout and they have no effect anywhere on the site.

**Comment by JoomFX** [comment]
@mahagr just a reference so you can recall what we discussed a while ago - https://github.com/gantry/gantry5/issues/461

**Comment by marktaylor46** [comment]
Thanks - I didn't know about the other issue. Right now I really think the tab should be removed because it is creating a lot of confusion. I know we need it going forward so we can re-enable it when we get it working - but as it does nothing right now it should be removed.

**Comment by JoomFX** [comment]
@marktaylor46 yep, I agree with you :)

**Comment by mahagr** [comment]
I know, I've now changed my mind on this on heavy mental pressure. :)

I was hoping that we already had the feature that was missing (it's one of the most important missing features), but it may take a couple of weeks to get it in.
