### ISSUE TITLE
Stop using IDs on menu items for menu particle

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#629]
Menu items are having an ID of the menu item ID added to each LI. They also have a class of the same constant added. 

Why is this an issue? Well if you add a menu particle in (say) the footer for the same menu as in the header then you get markup error on W3C validator because of duplicate use of same ID.

I think it is sufficient to just use the class - I don't believe we need to add ID as well.

![2015-07-23_09-25-02](https://cloud.githubusercontent.com/assets/11683218/8846323/095f68b2-311e-11e5-94c2-d7813c933e10.png)

**Comment by mahagr** [comment]
@kevlardev @w00fz Is the id being used anywhere? I agree that it should go away if we have no use for it (targetting works with classes too).

**Comment by marktaylor46** [comment]
cheers :)
