### ISSUE TITLE
Template module positions not showing up in Joomla

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#63]
please see pic, the dropdown for 'position' on the frontend module editor is not working.
![g5_hydrogendropdown-1](https://cloud.githubusercontent.com/assets/5719486/7007593/125f15d8-dc51-11e4-9ef4-1996b1168689.png)

Same issue exists in backend, none of the Hydrogen module positions show up.

**Comment by mahagr** [comment]
Actually this is related to my bug where our manifest file doesn't have module positions specified.

**Comment by mahagr** [comment]
Same issue also exists in backend, but is not as visible.

**Comment by mahagr** [comment]
I still need to figure out how to do the translations without needing to touch the language files.

**Comment by mahagr** [comment]
@kat05 Can you make new issue from the translation thingie.. I'm going to postpone that part to beta4 which will have other language stuff as well.
