### ISSUE TITLE
Gantry update message showing when there is no update

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#631]
The Gantry 5 update message is showing on member site even when there is no update showing in Joomla updater. If you "purge cache" is Joomla updater then the message is removed from Gantry 5 theme. However, as soon as you log out and then log back in again the message has returned.

http://www.rockettheme.com/forum/gantry5-for-joomla/245167-update-message-still-displayed-after-the-update?start=0#1220107

![2015-07-23_10-55-38](https://cloud.githubusercontent.com/assets/11683218/8847759/c89b73a0-3129-11e5-98b8-c023e53dafbf.png)
![2015-07-23_10-56-06](https://cloud.githubusercontent.com/assets/11683218/8847761/cc05e6ba-3129-11e5-90d6-e14898d36607.png)

**Comment by kat05** [comment]
i am not seeing this on all of my test install, but can confirm on some.

**Comment by w00fz** [comment]
I can't seem to be able to replicate this at all.
I even tried adding an outdated version of another Library plugin, thinking perhaps that was causing some sort of confusion, but it works just fine.
You guys have any suggestion on how I can replicate this on my local?

**Comment by mahagr** [comment]
I'm also not able to replicate this; the issue only exists if using CI builds, which is how we intended it.

I just checked and we are using the same SQL query (just without extra filters) as Extension manager.

**Comment by marktaylor46** [comment]
@w00fz @mahagr Try the members site - login included in topic. That site is only using Gantry 5.0.1 (not a CI build) yet that message keeps returning - you can clear cache and it goes, log out and back in again though and it will be back again.

**Comment by w00fz** [comment]
I did see it on her site but unfortunately it's of no help if I can't reproduce it on my local.
The only thing I can think of is the DB being out of sync. 

Did you try installing a CI Build and then revert back to stable or also just install stable on top of the current one, to see if it goes away?

**Comment by marktaylor46** [comment]
yup tried that and it didn't.

**Comment by kat05** [comment]
can't we zip her install and get the database, so that you can try it on your local?

**Comment by marktaylor46** [comment]
There is no backup software on her site (e.g akeeba backup).

**Comment by w00fz** [comment]
So any of you guys able to reproduce this at all?

**Comment by marktaylor46** [comment]
I can't recreate it locally but I have seen this on other member sites too.

**Comment by kat05** [comment]
I did see it locally before, but I've not found that install again, I might have deleted it meanwhile.
Maybe this will resolve itself with the 5.0.2 release anyways. If not, I'll make sure to get you a copy if I see it again on one of my installs.

**Comment by mahagr** [comment]
The issue comes when for some reason Joomla updates table contains entry for up to date extensions. Normally those entries are not saved into the database. Maybe changing stability settings for updates may contribute to this?

**Comment by DanGthatRokGallery** [comment]
So the update to 5.1.0 I experienced this on my local and this user has the same issue:
http://www.rockettheme.com/forum/joomla-template-callisto/246431-navigation-menu-hover-boxes#1227345

**Comment by marktaylor46** [comment]
Original issue from member - member is now happy to close this as resolved.

**Comment by mahagr** [comment]
I'm going to keep this open as I don't think we have fixed it.

**Comment by marktaylor46** [comment]
Just making a note here in case anyone else get's this again. You can fix the issue by manually downloading the latest Gantry 5 version and then installing that in extensions manager - then do a purge in updates and a "find updates" and then the update message in Gantry 5 admin should have gone.
