### ISSUE TITLE
Trying to get property of non-object when accessing page without menu item

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#632]
Best explained through example (I reproduced this on callisto)

Assign a standard Joomla "search" module to a module position particle anywhere on the layout.,

The search module is rendered ok - but as soon as you key in a search value and press enter then you get an exception thrown.

![2015-07-23_11-38-16](https://cloud.githubusercontent.com/assets/11683218/8848454/5fe61e0e-312f-11e5-814a-fcb3d9fe8d55.png)

![2015-07-23_11-34-45](https://cloud.githubusercontent.com/assets/11683218/8848460/65b8d574-312f-11e5-9bbe-d82ee611df8a.png)

http://www.rockettheme.com/forum/joomla-template-ambrosia/245155-search-breaks-site-gives-error?start=0#1220492

**Comment by mahagr** [comment]
Was actually from accessing menu item without itemid, but fixed it nonetheless.
