### ISSUE TITLE
WordPress - little grammar thing for Layout note in Base outline

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#635]
It says:

> Base Outline does not yet have a layout.

the word 'yet' suggests, that there will be one later on. It should be changed to:

> Base Outline does not have a layout.

**Comment by mahagr** [comment]
@newkind Do you mind recompiling language files again?

**Comment by mahagr** [comment]
Actually we are going to change this. So no need to change the string..

**Comment by kat05** [comment]
confirmed, layout panel is back in base outline.
