### ISSUE TITLE
WordPress - Adding widget to the menu fails

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#638]
All I did was drag a 'widget' to the menu, please see pic.

![g5_wp_405](https://cloud.githubusercontent.com/assets/5719486/8853948/913cafbc-315d-11e5-9100-c2c3088ccd11.png)

**Comment by mahagr** [comment]
Yup, still working on widgets ;) Thanks for reminder, though.

**Comment by mahagr** [comment]
Adding widgets to the menu is a high priority task, but because of there are fatal errors in WP admin, I will look into those bugs first.

As Gantry 4 didn't have this feature, I'm disabling the feature for now to allow us to do the release rather sooner than later.

**Comment by kat05** [comment]
i can confirm that this is fixed (widget hidden in menu editor) on hebe linked installs.

in the ci builds, it says 'module' there, which is another reason to believe something is wrong with ci builds.

**Comment by mahagr** [comment]
@kat05 Did the latest build fix that module issue (new install)?

**Comment by kat05** [comment]
yes, latest ci build seems to not show 'modules' anymore

**Comment by newkind** [comment]
closing
