### ISSUE TITLE
Suggestion: have a debug mode that renders particle IDs and module IDs

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#639]
Just a suggestion. Members often ask where and what X is on the page. If we had a debug mode toggle in Gantry 5 we could use that to render classes in the front end such as "particle-type-id" and "module-type-ID" in the output to make is easier to understand the source of page content

**Comment by mahagr** [comment]
@marktaylor46 Debug mode now enabled comments for particles and positions.
