### ISSUE TITLE
WordPress - 500 Internal Server Error - Oops, Widget 'date' not found.

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#640]
In the menu editor, I dragged a 'widget' into my menu.

The popup to pick a widget opened, I selected 'date' but then got this error, please see pic.

![g5_wp_500](https://cloud.githubusercontent.com/assets/5719486/8854018/f5657f0a-315d-11e5-9b5a-ce2ce6b64ff8.png)

**Comment by mahagr** [comment]
Good to have issue on this -- I'm still working on widgets and I've not got that far yet. :)

**Comment by kat05** [comment]
fix confirmed :+1:
