### ISSUE TITLE
Suggestion: add outline ID in outline dropdown

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#641]
When debugging it's easier to determine which outline is being using in front-end as it is rendered on the body tag. However, when you want to figure out which ID that is you have to go out of Gantry 5 theme and to template manager (which is only place where template ID is shown). Therefore I suggest this ID be added to the outline drop-down so it's easier to identify the outline from within Gantry 5 theme without having to go to template manager.

**Comment by w00fz** [comment]
I think this can be easily accessible via the Outlines Page, I don't think we should add too much informations in the dropdown. See also #555
