### ISSUE TITLE
WordPress - CI build fontawesome issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#643]
I have a Chimera RocketLauncher and added Gantry 5 and Hydrogen CI builds to it. vdev-b905e62ff

The fontawesome icons don't load. I do not have this issue on my other installs which are hebe linked.

![g5_wp_fontawesome](https://cloud.githubusercontent.com/assets/5719486/8854641/2c7c0a42-3161-11e5-9487-e4ecf6abd67e.png)

**Comment by w00fz** [comment]
Not exactly sure what you guys mean here, I just installed latest CI package + hydrogen e i see the icons fine.

![fontawesome](https://cloud.githubusercontent.com/assets/11734/8896958/4edf3a8a-33c0-11e5-941c-3117ced56af3.jpg)

**Comment by kat05** [comment]
i had this issue for a couple of days with several ci builds, today i used vdev-11b57c6c8 and the fontawesome icons show now. :)
