### ISSUE TITLE
Checkbox styling in Widget settings in Layout Manager are broken

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#646]
Checkbox styling in Widget settings in Layout Manager are broken
![hydrogen theme gantry5 wordpress wordpress 2015-07-24 12-18-05](https://cloud.githubusercontent.com/assets/1641534/8872530/2458b87c-31fe-11e5-901f-069bedcadc44.jpg)

**Comment by mahagr** [comment]
Fixed in 310ec2e

**Comment by newkind** [comment]
and also in 83f7dcb ;)
