### ISSUE TITLE
WordPress - Checkbox coming from widget cannot be unchecked

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#647]
We have some code in layout manager to make checkboxes to work with overrides. In WP widgets we do not have overrides because of we do not have any control on the form, which makes the logic to be a bit different to ours.

We need to add workaround to our validate AJAX call for sending data from non-Gantry form so that unchecked checkbox isn't sent at all.

**Comment by w00fz** [comment]
This is actually not an interference from the overrides, it's just the way it works, for checkbox as for anything else (for instance, an empty text field).
I did add a special case for checkboxes now, if unchecked it won't be sent to the validation. I'm not entirely sure why this is needed.

Also note that even though now I'm not sending unchecked fields, the validator is still returning the value back.

Example:
```
// Sent from JS
widget-archives[0][title]:
widget-archives[0][dropdown]:1
title:Archives
```

```
// Response from validator
{"code":200,"success":true,"item":{"type":"widget","widget":"archives","title":"Archives","options":{"widget":{"title":"","count":0,"dropdown":1},"enabled":1}}}
```

> Note the `"count":0`. This was tested with Archives widget.

**Comment by mahagr** [comment]
@newkind can you check if WP checkboxes now work?

@w00fz This is just needed for WP as we have no control on their forms. So basically WP will internally interpret any set value as true and unset variable as false. In validation WP will then add the value, which is what gets sent back.
