### ISSUE TITLE
WordPress - Archives widget checkbox issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#648]
Please see pic, the checkboxes don't seem to be styled properly.

![g5_wp_archivescheckbox](https://cloud.githubusercontent.com/assets/5719486/8875606/b462c126-321a-11e5-9381-477fb64300ca.png)

**Comment by newkind** [comment]
Hmmm I fixed this like na hour ago ... Can you try hard refresh couple times so I would reload the css ?

**Comment by kat05** [comment]
pulled latest and they look good!
