### ISSUE TITLE
404 not triggered by this type of link

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#649]
Pertaining forum Topic -> http://www.rockettheme.com/forum/joomla-template-ethereal/245316-menu-errors-and-how-to-disable-crikey-exception-reporting

I can confirm this on my local Ethereal. If a user on a site inadvertently types the wrong URL, specifically one that includes a text-separator in the path, instead of the nice 404 page they get "Exception (404)
Component not found."

On my local I used this path -> http://localhost:8081/Ethereal34/index.php/features/crikey
Gantry 4 on the other responds with a proper 404 page for this type of URL.

I've attached an image of the error page. User is concerned that pathing is revealed for his site.
![component not found 404 error](https://cloud.githubusercontent.com/assets/3792467/8888293/a88b4b2e-3275-11e5-8dde-92d8d3799cb1.jpg)

**Comment by mahagr** [comment]
Above error should not happen. I'll look into it.

**Comment by JoomFX** [comment]
I'm also getting the above error. It really seems that it occurs only if some of the parent menu items are "Text Separator". At least I was not able to reproduce it otherwise.

I'm also getting a similar issue with pages that the user does not have access to:

![alt](http://i.imgur.com/KhCbbU8.png)

In might not be easy to reproduce and troubleshoot my issue as it is a bit specific:

1. I do not have "Text Separator" as a parent menu item
2. The Menu item I'm trying to access is not in the Main Menu, but in another menu
3. The page/component I'm trying to access is "Akeeba Release System"
4. The access to this page is restricted by "PayPlans"

If I just create a menu item and set its Access Level to "Super User" and the try to access it with a normal user I do NOT get the above error.

**Comment by mahagr** [comment]
Alright, so it looks like I just need to ignore exceptions with 401, 403 and 404 error codes somehow.

**Comment by titro** [comment]
additional

I try to do a request on a component which does not exists (com_impressum)  --> 404
![image](https://cloud.githubusercontent.com/assets/4005090/8958902/ee411942-3607-11e5-8f24-5639f36310b1.png)

**Comment by samsblues** [comment]
I am using the Wordpress plugin for Joomla, all working fine - until i click "Older posts" on the blogs home page: "http://localhost/joomla31/?option=com_wordpress".

Would really appreciate any help with this - doing my nut in :(

<img width="1213" alt="screen shot 2015-07-29 at 21 12 05" src="https://cloud.githubusercontent.com/assets/13561082/8968680/aeef2a66-3636-11e5-9084-15ba682e7e3c.png">

**Comment by kat05** [comment]
i can confirm this issue, still happening in today's ci build.

**Comment by castor01** [comment]
I can confirm this issue too. The error occurs only in the 2nd part of the URL. After the 2nd Shlash but not after a 3rd Slash. For example www.test.com/others/error/page.html or www.test.com/others/error/others/page.html or www.test.com/others/error.html

**Comment by DanGthatRokGallery** [comment]
I can confirm castor01's finding.
I tried this on a users site:

http://www.trexmag.com / reviews123 -> normal 404
http://www.trexmag.com / reviews / hotels123 -> Crikey 404
http://www.trexmag.com / reviews / hotels / 123-> normal 404

If the bad URL occurs after the 2nd slash then the Crikey occurs.

**Comment by mahagr** [comment]
I disabled Crikey messages altogether when you're in production mode (with some additional conditions, like not being in debug mode and user not being admin), so at least there will not be an error when the site is in production.

This one still needs to be fixed, though.

**Comment by castor01** [comment]
Hi mahagr,
the error still remains. Your settings described change nothing.

**Comment by mahagr** [comment]
@castor01 Did you remember to disable debug mode from Joomla as well as put the theme into production mode?

**Comment by castor01** [comment]
Hi mahagr,
I am sure to have everything set up correctly. I can give you an admin access, then you can test yourself.

**Comment by mahagr** [comment]
You can ping me in a private gitter chat.

For public chat go to https://gitter.im/gantry/gantry5 (you'll find my user from there).

**Comment by castor01** [comment]
@mahagr I have snd you a mail under 'matias@kunena.org'

**Comment by mahagr** [comment]
That works too, thanks!

**Comment by mahagr** [comment]
For some unknown reason I cannot reproduce the issue locally -- on the other hand I'm getting a blank page and not 404, so its different kind of issue.

Maybe there's something different in my installation; I would like to know how did you install joomla / gantry / template?

**Comment by mahagr** [comment]
Ok, I am able to get it in demo server...

**Comment by castor01** [comment]
1. Joomla is installed from a provider package
2. The entire Joomla installation on the server is replaced by a local version

**Comment by mahagr** [comment]
I was able to fix this; I think it was issue caused by a small change in the error handling library we are using.

**Comment by kat05** [comment]
this all seems to work fine for me now with joomla debug = off and g5 in production mode.

**Comment by mahagr** [comment]
Should also be fine with debug turned on.

**Comment by kat05** [comment]
Yea, works with debug enabled too, it's showing the Call stack, but so does Protostar, so all seems well.

**Comment by castor01** [comment]
online tested - now it works fine without errors
