### ISSUE TITLE
Custom HTML Particle and Atom

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#65]
We need two new particles, one for handling custom html in the layout, kind of like Custom HTML module does in Joomla.
The other needs to be an atom where you can type custom html as well and you could pick if it should render at the top or the bottom of body.

**Comment by JoomFX** [comment]
@w00fz will we be able to add code like this in the new atom. I'm asking because you said "*where you can type custom html*". we need to be able to add JS as well:

```
        <script>
            jQuery(document).ready(function($) {
                $('.counter').counterUp({
                    delay: 10,
                    time: 1200
                });
            });
        </script>
```

**Comment by w00fz** [comment]
Yes, the `Custom CSS / JS` atom that exists today, is going to be extended to allow to also include inline scripts/styles. That's where you would be able to add your custom jQuery script or perhaps some inline css tweaks that you want specific for a page etc.

The `Custom HTML` atom is going to be a whole different atom, dedicated mostly for rendering HTML, not just scripts. Technically you would be able to even write `<script>` or `<style>` blocks in it. They are similar but the `Custom CSS / JS` atom will wrap them between `<script>` and `<style>` already for you so you can just type js or css.

So here is an example. In the new `Custom CSS / JS` you will be able to add a new Inline Script and the following is what you would put in it:

```
jQuery(document).ready(function($) {
    $('.counter').counterUp({
        delay: 10,
        time: 1200
    });
});
```

In the `Custom HTML` atom, on the other hand, you could write the follwoing:

```
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('.counter').counterUp({
            delay: 10,
            time: 1200
        });
    });
</script>
<style type="text/css">
    #my-custom-div { display: none; }
</style>

<div id="my-custom-div">
    <h1>Hello world!</h1>
    <p>Lorem ipsum</p>
</div>
```

The reason we want to keep the two separated is because the `Custom CSS / JS` will be able to create 1 tag only for both `<script>` and `<style>` and put in it everything together. This way it's more optimized than generated many different tags of the same type in the page. Although the `Custom HTML` will allow you to do so if you actually need it, plus you could combine it with also JS and CSS.

Hope it makes sense!

**Comment by JoomFX** [comment]
Got it :)
Thanks a lot for the detailed explanation @w00fz !

**Comment by mahagr** [comment]
Implemented custom HTML particle in its simplest form. I could add own inputs for styling and javascript -- or I could automatically move those into <head> or end of the <body> (maybe based on checkboxes). 

What do you think?

**Comment by mahagr** [comment]
Added support for stream urls inside the text field.
