### ISSUE TITLE
WordPress - Error if menu does not exist

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#650]
When i click on the menu in Gantry 5 and there is no menu created i get : Whoops \ Exception \ ErrorException (E_WARNING)

**I think there should be notice for this**

![2015-07-26 23 35 30](https://cloud.githubusercontent.com/assets/10489911/8896024/0f56383a-33ef-11e5-8256-79bea887b4f4.jpg)

It appears this is fixed but i am using the latest ci build and it isnt.
https://github.com/gantry/gantry5/issues/589

**Comment by kat05** [comment]
fix confirmed
