### ISSUE TITLE
Drop-Down Menu Direction

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#652]
There should be drop-down menu direction for smaller viewport sizes when there is menu at the end it goes outside of the screen ... don't know if this is happening in Joomla but something like it was implemented in some latest themes in Gantry 4

![2015-07-26 23 55 30](https://cloud.githubusercontent.com/assets/10489911/8896119/02ad8c70-33f2-11e5-8772-72da2ad49cc7.jpg)

**Comment by w00fz** [comment]
See here: https://github.com/gantry/gantry5/issues/417#issuecomment-110114753
