### ISSUE TITLE
Assignments are blank

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#653]
Theme: Hydrogen (vdev-905842ca5 / g5_hydrogen) when i want to assign an assignment all are blank.

![image](https://cloud.githubusercontent.com/assets/10489911/8896148/4440b4a4-33f3-11e5-84a0-8d130e527527.png)

**Comment by mahagr** [comment]
Might be a bug in CI builds; @w00fz can you take a look if we are missing files from the builds?

**Comment by kat05** [comment]
i can confirm this issue with vdev-11b57c6c8.

however, everything works fine on hebe linked installs.

there is definitely something wrong with the ci builds, i am still missing the content tab as well, even in latest.

**Comment by mahagr** [comment]
@kat05 @newkind Is this issue fixed also?

**Comment by kat05** [comment]
it is fixed for me in latest ci builds.

**Comment by newkind** [comment]
fixed :)
