### ISSUE TITLE
No Gantry 5 Theme UI Bug Joomla

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#655]
When there is no Gantry 5 theme installed there is a notice but the layout is broken see screenshot!

![2015-07-27 13 00 21](https://cloud.githubusercontent.com/assets/10489911/8904434/9827c12c-345f-11e5-8370-88602935641d.png)

**Comment by mahagr** [comment]
@kevlardev Can you check this one out?

**Comment by kevlardev** [comment]
I cant seem to find a way to reproduce this, was there anything special or extra that you did? Or was it just a straight fresh joomla install / gantry install with no theme?
