### ISSUE TITLE
WordPress Menu - If Linked and Erased Error Appears

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#656]
When menu is created in WordPress and linked in G5 and then you erase that menu from WordPress and there are no more menus left you will get an error notice ...

Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("in_array() expects parameter 2 to be array, null given") in "@particles/menu.html.twig" at line 2."

Stacktrace:
#34 Twig_Error_Runtime in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:337
#33 Twig_Template:displayWithErrorHandling in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:296
#32 Twig_Template:display in F:\Websites\testing\wordpress-gantry\wp-content\cache\gantry5\g5_hydrogen\twig\6\a\6a88125ac9ccafd47a0b49af060a004a442273c25934dce3cc3f303eafa8b270.php:53
#31 __TwigTemplate_6a88125ac9ccafd47a0b49af060a004a442273c25934dce3cc3f303eafa8b270:doDisplay in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:322
#30 Twig_Template:displayWithErrorHandling in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:296
#29 Twig_Template:display in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:307
#28 Twig_Template:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Environment.php:293
#27 Twig_Environment:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Framework\Theme.php:80
#26 Gantry\Framework\Theme:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:539
#25 Gantry\Framework\Base\Theme:renderContent in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:489
#24 Gantry\Framework\Base\Theme:prepareLayout in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:477
#23 Gantry\Framework\Base\Theme:prepareLayout in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:477
#22 Gantry\Framework\Base\Theme:prepareLayout in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:477
#21 Gantry\Framework\Base\Theme:prepareLayout in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Theme\ThemeTrait.php:318
#20 Gantry\Framework\Base\Theme:segments in <#unknown>:0
#19 call_user_func_array in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:520
#18 Twig_Template:getAttribute in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Environment.php:332
#17 __TwigTemplate_ca5e45b26641d1e1f2e053617ac28923be63303b1486074174f755296905ab9c:doDisplay in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:322
#16 Twig_Template:displayWithErrorHandling in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:296
#15 Twig_Template:display in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Environment.php:332
#14 __TwigTemplate_3d30530860c2ec3b18247046ef456db708860d770739e254200bb1775617c389:doDisplay in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:322
#13 Twig_Template:displayWithErrorHandling in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:296
#12 Twig_Template:display in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Environment.php:332
#11 __TwigTemplate_5033404a50efeabb8d79dacf0b41c68ceb2ad7a87af627159856e69bc8e168aa:doDisplay in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:322
#10 Twig_Template:displayWithErrorHandling in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:296
#9 Twig_Template:display in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php:307
#8 Twig_Template:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Environment.php:293
#7 Twig_Environment:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\timber-library\lib\timber-loader.php:69
#6 TimberLoader:render in F:\Websites\testing\wordpress-gantry\wp-content\plugins\timber-library\timber.php:282
#5 Timber:compile in F:\Websites\testing\wordpress-gantry\wp-content\plugins\timber-library\timber.php:316
#4 Timber:render in F:\Websites\testing\wordpress-gantry\wp-content\themes\g5_hydrogen\index.php:42
#3 include in F:\Websites\testing\wordpress-gantry\wp-includes\template-loader.php:74
#2 require_once in F:\Websites\testing\wordpress-gantry\wp-blog-header.php:16
#1 require in F:\Websites\testing\wordpress-gantry\index.php:17
#0  in F:\Websites\testing\wordpress-gantry\wp-content\plugins\gantry5\src\classes\Gantry\Component\Menu\AbstractMenu.php:124

![image](https://cloud.githubusercontent.com/assets/10489911/8915961/8bec7ab2-34a8-11e5-8487-27087183053c.png)

**Comment by kat05** [comment]
seems fine for me now.
