### ISSUE TITLE
WordPress Dropdown UI Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#657]
There is a bug when i click on the dropdown the layout boxes get shifted see the video

http://take.ms/N4B2y

![2015-07-27 21 55 55](https://cloud.githubusercontent.com/assets/10489911/8916221/64dbf2d4-34aa-11e5-9c89-0209dd61455d.jpg)

**Comment by newkind** [comment]
I'm not sure if we can do anything about it - this is how cards are working in CSS and this happens because the container height changes. Any input here @kevlardev ?

**Comment by weredigi** [comment]
Wondering if we could separate wordpress from joomla update lot extra email
of unrelated to subject matter if using other cms

greg@weredigital.com

**Comment by w00fz** [comment]
Sorry that's not possible. Gantry as a whole is a project that includes different platforms that all reside in the same GitHub repository.
I would suggest creating a filter with your email to mark as read or delete any gantry email that contains specific keywords such as `wordpress`. That's your best bet.

**Comment by kevlardev** [comment]
fixed with c22c4823c79000c998b40a74929ca31ac0bcdc38
