### ISSUE TITLE
Uninstall of Gantry should remove cache files

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#659]
Seen this in WP, it's probably the same in Joomla.

After uninstalling both Gantry 5 and Hydrogen from my WP install, there are still tons of files under 
../wp-content/cache/gantry5/

I believe this should get removed during uninstall?

**Comment by kat05** [comment]
I've also searched my database for 'gantry' and 'hydrogen' and there seem to be some entries there. not sure if some of those would need removal too though.

**Comment by newkind** [comment]
I think that we can remove the cache on uninstallation, although I wouldn't remove the stuff from database as I think it might be nice to keep them if someone decides to get back to previous theme

**Comment by adi8i** [comment]
i think cache should be cleared in joomla/wp, because that's the place where cache is stored.

**Comment by mahagr** [comment]
Joomla should already clear cache on uninstall.
