### ISSUE TITLE
Different presets between Home and Default

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#66]
A little thing, I don't think it's a bug but a different setting.
On a fresh install **Hydrogen-Home** has *Preset 2* style assigned, and **Hydrogen-Default** has *Preset 1*. I think It's better to have the same preset for uniformity.
Another thing: On the **Styles** tab, is not obvious which is the default style. Suggest to make the default thumbnail with a different border (red as example).

**Comment by mahagr** [comment]
1) Home page has different style because of we needed to show up "front page" to showcase some of the features as well as pointing new users to our documentation to get started. It is only possible by fully customizing the page (with home preset).

2) Good idea.. I would maybe just use star to display it, just like in Joomla styles page.

**Comment by mariantanase** [comment]
@mahagr 
When I said different setting I intend different color palete not different layout position

**Comment by w00fz** [comment]
Maybe I'm missing something here but for me both Home and Subpages, on fresh install, are Preset 1?

**Comment by gyvermac** [comment]
Yes Preset 1 for both on install

**Comment by mariantanase** [comment]
No, for me Home has Preset 2 and the rest has Preset 1.

**Comment by w00fz** [comment]
Check your template custom folder perhaps you have overrides for that. By default it is all Presets 1

// Djamil Legato // From iPhone //

**Comment by mariantanase** [comment]
Is a fresh gantry5 beta2 install on a fresh joomla 3.4.1 installation on my localhost test environment (xampp).
Anyway, tomorrow morning I will repeat the procedure and I'll be back with results.

**Comment by mahagr** [comment]
@mariantanase I finally understood your issue. I bet you saved something in admin as:

On the new installation if you haven't saved the configuration, it doesn't use any of the presets, but !default values in scss files.

@kevlardev Did you update the default values to match preset1? I think this issue may be related on those.

**Comment by mariantanase** [comment]
Yes, I repeat the procedure and is fine, both home and the rest are preset 1.
Sorry

**Comment by w00fz** [comment]
No worries, glad it is sorted and wasn't a bug

// Djamil Legato // From iPhone //

**Comment by mariantanase** [comment]
Hi, I don't want to create another issue, but on the **Styles** tab, is not obvious which is the default style. Suggest to make the default thumbnail with a different border (red as example).

**Comment by mahagr** [comment]
There is no default style, really, but I think we could do the same as in LM and highlight the preset that was used to create that configuration. @kevlardev your thoughts?

**Comment by mariantanase** [comment]
With *default* style I mean *applied* or *actual* style, or how you want to call it.
