### ISSUE TITLE
Menu max levels seems to be short by 1

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#660]
Seen in WP, might be same in Joomla.

I am using the 'Testing menu' which is part of Jakub's test install.

There are 1st level items, one of them is called 'Depth' and it has a child Item called 'Level 1' which itself has a child item called 'Level 2' which itself has a child item called 'Level 3' etc.
(You can see it in the attachment)

Now in the Base outline > Settings > menu > Max levels i set 2 and i would expect to see 'Depth' and its child 'Level 1' but all i see is 'Depth' without any children. I think that's wrong? 

![g5_wp_maxlevels](https://cloud.githubusercontent.com/assets/5719486/8931353/f7af62cc-3535-11e5-9c14-47982d1728ea.png)

**Comment by mahagr** [comment]
@kat05 Can you check Joomla as well? It might be good, tho.

**Comment by kat05** [comment]
This seems to be working fine in Joomla, tested with latest CI build (commit: 1d7e39cfe)
