### ISSUE TITLE
Turn off Responsive Layout

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#663]
@kevlardev Is there a possibility to have just desktop layout turned on and no responsiveness some users where asking about this on RT Forums?

**Comment by kevlardev** [comment]
No, the entire layout and framework (like most these days) was built with touch and mobile devices in mind. It requires a lot of specific media queries and arrangements to make all that work and creating an override (such as the 960fixed and 1200fixed we had in gantry4) requires tons of css and overhead to reverse all those rules to provide both functionalities in parallel. Users have total control over the breakpoint and container sizes via the settings, but there is no way to completely disable all mediaqueries and flex reorganization.

**Comment by newkind** [comment]
In my opinion this would be like going couple years back ? Especially that the responsive layout is one of key things when we talk about SEO and Google position. We need to drop some legacy stuff so we could move on, otherwise it will always hold us back.

**Comment by mahagr** [comment]
I think it would be possible to disable media queries from CSS files by one variables, though. We could also set width on html body to restrict the size. But honestly I'm not sure why anyone would like to do either of them, unless they have separate template for mobile devices.

**Comment by DamirPecnik** [comment]
Me neither but users are requesting ....

**Comment by newjie** [comment]
I have been using gantry templates for years and I want to ask this question too. Sometimes I don't want to bother too much with mobile layout and some of my clients did ask me to present the webpage on mobile device "as is" on desktop devices. 

I don't know too much of the exact definition of "responsive" but I think all it takes is to change the meta tag
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
to 
`<meta name="viewport" content="width=content-width, initial-scale=1.0">`

This is a little hard to do with javascript. So why not just provide this option for some users? I don't see it creates any drawback.

**Comment by w00fz** [comment]
You can change this behavior by overriding the `page_head.html.twig`. Because Gantry 5 is built with responsiveness in mind, we enable this functionality by default (only at template level), however you can still customize it to never output that viewport meta tag.

See how the page_head.html.twig looks like by default here: https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/templates/page_head.html.twig

Also more informations on how to override can be found here: http://docs.gantry.org/gantry5/advanced/file-overrides
