### ISSUE TITLE
Hydrogen email popup input field alignment issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#665]
In the 'Email to friend' popup in Hydrogen, the inputs are misaligned, please see pic.

![g5_hydrogen_emailalign](https://cloud.githubusercontent.com/assets/5719486/8958542/bfd58144-3605-11e5-92fb-6837bb87a7bb.png)

**Comment by mariantanase** [comment]
You're right, I noticed too. I resolved with a few css lines on custom.scss : 

    div.formelm label {
        display: block;
        padding-right: .25rem;
        width: 5rem;
        float: left;
        line-height:1.8rem;
        text-align: right;}

    div.formelm input,
    div.formelm textarea {
        margin: .1rem;
        display: block;}

**Comment by kevlardev** [comment]
Was the pop up forms the only place you came across these label issues?

**Comment by kat05** [comment]
fix confirmed!
