### ISSUE TITLE
modules in template override not showing

### ISSUE THREAD

**Issue by nzimas** [gantry/gantry5#667]
In order to display a set of modules in the article view only, thus bypassing the menu item, assignment, I have created a template override.
So far I have tried unsuccessfully two modes injection methods.

1) Direct invocation of one specific module

<?php
jimport('joomla.application.module.helper');
   $module = JModuleHelper::getModule('mod_ijoomla_adagency_zone','Right Top Ad');
   echo JModuleHelper::renderModule($module);
?>

2) By loading a module position

<?php
  // get document
  $doc = JFactory::getDocument();
  $renderer = $doc->loadRenderer( 'modules' );
  $style = array( 'style' => 'standard' ); // you can change raw to other styles

  if ($doc->countModules('video') > 0) {
      echo $renderer->render('video', $style, null);
  }
?>

In the latter example, the position most certainly exists in the template details XML file.

At this point, I do not know if the issue is Gantry 5 specific or if Joomla 3.4.3 requires a different approach.

**Comment by mahagr** [comment]
Your code should certainly work. Just make sure that your template override for article is used. Can you echo anything else to be sure if this is the case?

**Comment by mahagr** [comment]
Any updates @nzimas on this issue?

**Comment by mahagr** [comment]
Assuming issue to be solved. Please reopen it if it isn't. :)
