### ISSUE TITLE
Particles issue

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#67]
I'm on **Hydrogen-Home** > **Layout**. From *Footer* I click on **Social** particle and **Drag Here to Delete**. Fine. Save Layout.
Now, I want to reinsert the same particle on the same place. 
From the left side I drag the **Social** particle and place it on the previous place on Footer section, then **Save Layout** and **Clear Cache**.
But none of the social icons are visible on frontend.
Many issues with click on particles can cause broken layout. Seems to be freezing or something like that.
Now I cannot return on the initial state. Should be usefull to be a kind of **Reset** button on the top to reset the layout positions with the particles.
![gantry5b2-shot1](https://cloud.githubusercontent.com/assets/3976174/7019230/0dc82d26-dd0e-11e4-9b4f-df05e04ee8db.png)

**Comment by mariantanase** [comment]
After logoff and login again, when return on the layout tab I see the following broken layout. Without touching anything.
![gantry5b2-shot2](https://cloud.githubusercontent.com/assets/3976174/7019303/e8124dfe-dd0e-11e4-8468-422e5d446bbe.png)

**Comment by mahagr** [comment]
@w00fz You might want to take a look on this.

**Comment by w00fz** [comment]
Are you still getting this issue? I was never able to reproduce it. I think we talked about this in Gitter if i recall correctly and you said it was an older version beta?

I'm going to close this, feel free to reopen if it is still an issue.
