### ISSUE TITLE
Please help with title

### ISSUE THREAD

**Issue by gustav-mahler** [gantry/gantry5#671]
Hi there, Can you please help me?

I run Joomla and Gantry 5 and got these tooltips (extra copy of the titles in white) over the Gantry menu as shown in the image example underneath. How to remove these? I think it started when I split the menu subitems into 2 columns.

http://www.gustav-mahler.eu

Joomla version 3.4.3
Joomla platform 13.1.0
Gantry Hydrogen 5.0.1

![image](https://cloud.githubusercontent.com/assets/13572225/9001631/1f650f8a-375a-11e5-8164-eff920bdc1f3.png)

Gustav from Holland

**Comment by adi8i** [comment]
Menu links have `title`

**Comment by JoomFX** [comment]
@gustav-mahler Have a look at https://github.com/gantry/gantry5/issues/532 . It explains why you see the title.

Then have a look at https://github.com/gantry/gantry5/issues/670 . I do believe that the title should be optional and I think the RT guys agree with this and will implement an ON/OFF switch for it.

Until then, you can just remove the following code from line 46 in `menu.html.twig` (root/media/gantry5/engines/nucleus/particles):

```
title="{{ item.title|e }}"
```

You can do it without a template override as I strongly believe that the ON/OFF switch will be available in the next release (5.0.2)

**Comment by gustav-mahler** [comment]
Thank you JoomFX and adi81!     It did the trick.
