### ISSUE TITLE
Layout manager does not load in chrome

### ISSUE THREAD

**Issue by ifeedmonsters** [gantry/gantry5#674]
I was working on a site when all of a sudden I am having an issue (only in chrome) where the layout manager would not load in any sections, the outline select box up top would not load any options, and the "Extras" dropdown does not work at all.

**Comment by adi8i** [comment]
I am using the latest version of Chrome on Windows 8.1 without any issue, can you specify your Operating System and Browser version? :)

**Comment by kat05** [comment]
I am not seeing any issues either, using Gantry 5.0.1 and also latest CI build on Chrome Version 44.0.2403.125 (64-bit) on Mac OS 10.10.3

**Comment by mahagr** [comment]
No issues on using Chrome here, either.

**Comment by ifeedmonsters** [comment]
Hmm, it might not have been a browser issue, but the layout manager definitely stopped loading after a while. I was working on MAMP. I restarted my project twice because of the problem.

**Comment by mahagr** [comment]
Try to figure out how to reproduce it; if it's a bug we really need a reliable way to test what's going on with it.
