### ISSUE TITLE
Disable Dropdown option (reopen)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#675]
As @mahagr suggested, I'm opening a new issue for this. The original issue is https://github.com/gantry/gantry5/pull/611
The thing is that with the current implementation the user is not able to disable second level dropdowns (3rd level menu items) because you are hiding the "Dropdown Style" option for non-first-level menu items.

It will be best if we take the option out of "Dropdown Style". Here's what @w00fz said in the chat:

```
will have to dig into that a bit further
probably decoupling the option is the best way to go
i just hate having to add yet another to the already long list :smile:
that modal is getting fat
```

**Comment by w00fz** [comment]
Alright I added this to its own setting, really no other way around it. Looks like this now for root levels and sublevels.

![disable dropdowns](https://cloud.githubusercontent.com/assets/11734/9182132/f3bd7352-3f5d-11e5-998a-ecaee6f9593d.jpg)

**Comment by JoomFX** [comment]
Great! 
Thanks @w00fz :)
