### ISSUE TITLE
Widget particle in Layout manager should load custom widget css/js

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#677]
Widget particle in Layout manager should load custom widget css/js that might be needed to support widget settings form.

**Comment by GiannisZ** [comment]
The problem is with js files because css files are loaded correctly!

**Comment by newkind** [comment]
@mahagr we need this for next big release ;)

**Comment by mahagr** [comment]
WordPress 5.8+ is moving towards a new system, which makes this feature less interesting and duplicate.

**Comment by mahagr** [comment]
Deprecated Widgets in Layout Manager.
