### ISSUE TITLE
Scripts/Styles with head (and footer) don't work

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#678]
`{% scripts with { priority: 9 } %}
        <script type="text/javascript" src="{{ url('wp-includes://js/comment-reply.js') }}"></script>
    {% endscripts -%}`

Scripts and styles placed in twig files - both content and particles - don't work when using head or footer position. If we call a custom one ie. `foo` they start to work.

**Comment by mahagr** [comment]
Works in Joomla, just not in WP.

**Comment by mahagr** [comment]
Footer still has some issues.
