### ISSUE TITLE
Strange behavior of menu indicator

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#68]
I'm working on my custom.scss, but I have a funny problem with the submenu indicator (little down-arrow beside a menu item): the arrow is perfectly centered in hydrogen-home, but in "default" is misaligned to left...any kind of css I write doesn't center it ....not even sure if this is a bug, but I fire-bugged it and can't see differences between the css for "home" style and that for default...
![cross](https://cloud.githubusercontent.com/assets/11693902/7026287/2a1ca12e-dd49-11e4-9643-6d96beaacc0a.jpg)

**Comment by w00fz** [comment]
Referencing #58

**Comment by JoomFX** [comment]
It is easily reproducible. Just move the Menu Particle in the Header section.
I noticed that a while ago but I though it is not really important.

**Comment by beamaria** [comment]
I agree with you...unless you've squeamish customers like mine ;-) 
Do you think there will be a patch for this in Beta3 ?

**Comment by kevlardev** [comment]
As djamil mentioned, the entire structural output and much of the styling of the menu is being reworked to take into account additional features and functionality. This alignment issue will be addressed in this rewrite for beta3.
