### ISSUE TITLE
Particle packaging

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#680]
I know we've had several discussion about this but I thought I'd raise a ticket and offer some comments.

We need to find a way to package particles so that they can easily be installed and uninstalled from templates. By "package" I mean the twig, yaml, and scss associated with a particle - in short everything that makes that particle function.

Why do we need this? Because members want to use and move particles between templates. Why else? Because we making a maintenance headache for ourselves by duplicating particle files across templates... when we find a bug we have to fix it in every template copy rather than just once (like we would for a module like roksprocket).

What do we need to consider to do this? This will necessitate particles having there own version number (like a joomla module would) and we will need an updater/installer within G5 admin. what else? Some particles have dependencies on the template and inheritance of colors etc etc.

We should we invest time in doing this? Because without it members are retreating back to using Joomla modules rather than particles, particles offer the potential to much improve the functionality of a site and means use don't have to delve into coding.

Where could this lead? it opens up the potential to have a member "particles" for g5 area (much like Grav does) and also paves the way for more sophisticated "paid" particles should RT wish to do that.

Just a few ideas I though might help :)

Regards, Mark.

**Comment by JoomFX** [comment]
+1

I'm not sure if this will and should be implemented but I somehow like the concept :)

**Comment by w00fz** [comment]
We have plans for this but not at the moment. In the future we'd like to have an export/import as well as a repository for Particles. It's just not up to in the priority list right now so this will have to wait.
It's not so hard at the moment to just copy the few files tied to a particles, over to another template.

**Comment by mahagr** [comment]
I agree; while I would love to have this feature yesterday, there's just too many things we still need to fix before I would take a look into this.

**Comment by marktaylor46** [comment]
Ok, I hadn't expected it would be any time soon. I was surprised that this ticket got tagged as "question" and "closed" though. I had expected it to be "future release" and "enhancement" and left "open" for now.

**Comment by mahagr** [comment]
We are trying to keep number of issues as low as possible. I think this feature will be implemented somewhere after we have implemented support for Grav as we can likely reuse code from there.

**Comment by w00fz** [comment]
Hey Mark, don't take it personally.
The reason I flagged it as a question is only because I gave you an answer rather than actual code. The reason I closed it is because this has been already mentioned in other tickets, was discussed in different blog posts and we have it in our list of things to work on for Gantry in the future.

I just didn't want to leave it open and occupy yet another spot in the already many issues since we already know about it as well as knowing it won't happen anytime soon. I'd rather keep the more pressing issues open so that we don't get sidetracked when we browse to issues.

**Comment by marktaylor46** [comment]
Not taken personally at all - I was just a little bemused by the process. If it's in other tickets that are already open then fair enough - can you let me know ticket numbers though as i couldn't find any? Is the "list" for future developments publicly available? For me I would have thought it made sense to keep "issues" flagged as "future projects" open so the whole community can see?

Just an idea of course...

**Comment by w00fz** [comment]
#218 and #339

I'm going to create a wiki, here on GitHub, with a list of things we discussed and plan of adding sooner or later, so that it's available for public.

**Comment by w00fz** [comment]
There you go @marktaylor46 https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel

**Comment by alisamii** [comment]
Djamil,

In any of those items listed on this great wiki page, is there an item that will allow adding menu page suffix classes to the body tag so that we have a CSS class for each menu item the way it was possible to do in Gantry 4.

These generated a css class on the body tag with the syntax `menu-menu_name`. For example, home would get a class `menu-home` and the about menu would get the class `menu-about`.

Best regards,

Ali

**Comment by marktaylor46** [comment]
@w00fz Thanks for that - that's very helpful for the whole community :)

**Comment by marktaylor46** [comment]
@alisamii Gantry 5 already adds itemid-999 (where 999 is menu item id) this is the equivalent of Gantry 4 and "menu-about" etc but better since it uses the menu id rather than the alias (so you can change alias without having to change CSS).

Also, page class on menu item is now rendered too (it wasn't in early releases of Gantry 5).

Regards, Mark.

**Comment by JoomFX** [comment]
@w00fz @mahagr @newkind Guys, an year ago I said:

> I'm not sure if this will and should be implemented but I somehow like the concept :)

Well, things changed a lot for the last year... I'm now dreaming of this "Particle Packaging" (and making them installable from the G5 Admin) every single day :smile: 

@marktaylor46 has described everything perfectly! this is exactly how I'm imagining it.

So, I was wondering if you want to reopen this issue and if your plans are still the same, meaning if you are still planning to look at it once the Grav support is implemented?

**Comment by w00fz** [comment]
I think we all still want a repository for particles which, when we get there we will look into a better packaging system for particles, since that will require some changes. I want a better organization for particles like have them distributed in folders so that assets can go with them.

For the moment this is not our priority so it will take some time. It's in our agenda already so you can rest assured we will remember it.

**Comment by JoomFX** [comment]
Thanks Djamil.

Organizing particles (with all their assets) in folders sounds awesome!

**Comment by hennysmafter** [comment]
Why is this ticket closed! It is like SUPER important...

**Comment by marktaylor46** [comment]
Because it's on  the future features list already - no need to track it twice.

https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel

**Comment by midsussexwebsites** [comment]
As a 'new' convert to Gantry 5 I've been amazed at what I've seen and I'm excited for the future to see how the framework develops even further. With regards to the packaging of particles...ASAP! :-) 

I can see it is in hand, but having gone through the motions of manually installing a bunch of particles today for just one site, it is painfully clear this can not come soon enough to ensure smooth update rollouts across multiple sites.

Good luck all involved, looking forward to seeing the fruits of your labour.

**Comment by mahagr** [comment]
Thanks. We are planning this feature to Gantry along with marketplace for particles. Right now our team is working towards getting market place (for Grav, and soon later for Gantry) up and running.

**Comment by brandonchance** [comment]
This is going to be awesome, I'm too excited for this! Thanks for all your hard work Gantry Team! :+1:

**Comment by gyvermac** [comment]
👍

**Comment by ethistle** [comment]
We are now heading into 2018 and this feature would be an excellent addition. I have been using Gantry5 now for about a year or so ( been building website for over 20 years) and it really is the best framework out there.
The addition of particle "modules" would not only assist people like me but also provide an opportunity for template developers to market them - like Yoo theme did with their widgetkit

**Comment by jasonmac75** [comment]
I agree with your comments, having a marketplace and update feature is a must. I love the option to load each particle on a specific template and not sitewide all per all Wordpress widgets. Great job by rockettheme and some amazing particles and atoms created by inspiretheme.com, hopefully coming soon in 2018?

**Comment by thexmanxyz** [comment]
@ethistle @jasonmac75 I refer back on my thought #218

**Comment by BjoernH01** [comment]
Will the feature come to Gantry5 anytime near in the future?
Would be great if it got implemented.
