### ISSUE TITLE
Disable whoops when Gantry is in production mode, debug mode has been disabled and user isn't admin

### ISSUE THREAD

**Issue by prototype2118** [gantry/gantry5#681]
https://prismli.com/information/forum/prism-welcome-forum/2-welcome-to-the-prismli-group 

Example of a 404 exception that I am getting with error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT in the php.ini and error reporting set to NONE in Joomla.

The 404 exception is far too revealing for a site in production.  Can this be addressed?

**Comment by w00fz** [comment]
Agreed we need to either tie the whoops to Prod/Dev or have it serving with less data, especially on frontend.

**Comment by prototype2118** [comment]
Awesome, thank you for addressing this.

**Comment by mahagr** [comment]
Alright, you will now get the error dump only if one of these conditions are true:

* Gantry is in development mode
* Debug mode has been enabled in Joomla
* User is logged in and has admin rights for managing the template
