### ISSUE TITLE
Frontend article editor, article popup issue 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#683]
On the frontend article editor's article popup, there are some layout issues, please see pics.
This has recently been fixed in Salient itself (during pre-release testing, tickets JTEMPSALIENT-36 and JTEMPSALIENT-55), but I now noticed it's also an issue in Hydrogen, Callisto, Ethereal and Ambrosia and should probably be addressed in Gantry itself.

![g5_frontendeditor_article3](https://cloud.githubusercontent.com/assets/5719486/9108659/fa0c1578-3c2f-11e5-9295-df45b255ceb9.png)

![g5_frontendeditor_article2](https://cloud.githubusercontent.com/assets/5719486/9108660/fa0cf664-3c2f-11e5-9a18-8a904190f1ad.png)

![g5_frontendeditor_articlepopup](https://cloud.githubusercontent.com/assets/5719486/9108658/fa0b5db8-3c2f-11e5-83fd-b8c9e6fbbf05.png)

**Comment by kat05** [comment]
In Hydrogen, I only see the issue in the first screenshot fixed. The other 2 are still showing.
Also try hovering on the 'Search' and 'Clear' buttons to see another issue.

Callisto has the same issues as Hydrogen + the 'Filter' input field takes full width across the popup.

**Comment by kat05** [comment]
Ethereal still has the same issues as Hydrogen still has.

**Comment by kat05** [comment]
Ambrosia has the same issues that Hydrogen has + when clicking on any of the filter dropdowns, the filter input field gets pushed up a bit and partly hidden.

**Comment by kevlardev** [comment]
There is definitely a larger issue here, all of this stuff was styled properly before. It seems that the rules from the nucleus joomla css are no longer being loaded in popups, which is causing all of this missing styling. However the theme specific (hydrogen-joomla.css, etc) platform css is loading, which is why theme side fixes will work.

**Comment by kat05** [comment]
ok double checking on SALIENT , it's not fully resolved either.

- the filter input field is taking full width
- when hovering on any of the headers such as 'access', 'category', 'language', the tooltips are misplaced to the left
- when hovering on the 'search' and 'clear' buttons, there are issues too.

however,
- the pagination is looking fine

**Comment by kat05** [comment]
The commit that Matias provided fixes almost all issues.

An issue that's left is with the pagination, please see pic.

![single_article](https://cloud.githubusercontent.com/assets/5719486/9134494/e3832780-3d04-11e5-8b67-ff65ae4383eb.png)

**Comment by kat05** [comment]
Protostar loads those icons correctly.

For the missing 'Forward' icon (2nd blue arrow) I see the class is the following in Hydrogen:
```<span class="icon-step-forward"></span>```

while it should be the same as Protostar:
```<span class="icon-next"></span>```

**Comment by kat05** [comment]
Ok, so for all 4 icons from left to right, Protostar uses the following:

```<span class="icon-first"></span>```

```<span class="icon-previous"></span>```

```<span class="icon-next"></span>```

```<span class="icon-last"></span>```

And Hydrogen etc. use these instead:

```<span class="icon-backward"></span>```

```<span class="icon-step-backward"></span>```

```<span class="icon-step-forward"></span>```

```<span class="icon-forward"></span>```

**Comment by kevlardev** [comment]
Thats really strange, we arent altering the classing of any joomla output in hydrogen. I have no idea why those class names for pagination would be different

**Comment by kevlardev** [comment]
![screen shot 2015-08-07 at 11 22 24 am](https://cloud.githubusercontent.com/assets/4529755/9140431/cd3e8cf2-3cf6-11e5-8848-e8010438b3fd.png)
This is reproducible in protostar if you remove protostar's custom pagination.php override. Its definitely a joomla core issue and seems they have fixed it for the 3.5 release: https://github.com/joomla/joomla-cms/pull/7175
