### ISSUE TITLE
Delete Home Outline - WordPress

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#688]
WordPress Hydrogen. If I try to delete Home Outline, it remains, even though it says Succesful "Configuration Deleted" in the bottom right.

**Comment by kat05** [comment]
Hey Reggie, is this using CI build or hebe linked?

It's been a week or so and I am almost certain I was able to delete the Home outline on both.
It's currently working fine for me hebe linked, but will retry with latest CI build too.

**Comment by kat05** [comment]
I can confirm this issue with latest CI build and also hebe linked.
