### ISSUE TITLE
[WORDPRESS] Content Settings Not Taking Effect for Menu Items

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#690]
Whether using Base Outline or Additional Outline, any menu item (other than Homepage) is not accepting, for instance, the unpublishing of detail text for author, title, date, comments for Posts via our Content Settings.

Unfortunately for a Page, when trying to hide the Title via Content Settings, it doesn't accept it either, even it was on the Home Page.

![screen shot 2015-08-06 at 4 20 45 pm](https://cloud.githubusercontent.com/assets/5002814/9123886/1f31cf32-3c58-11e5-949e-d50f00fefd62.jpg)

![screen shot 2015-08-06 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/5002814/9123911/5a04c4c0-3c58-11e5-81ad-4d24e6f993e3.jpg)

**Comment by mahagr** [comment]
@simmonsr Can you try again; not sure if it fixes your issue, but at least what you described works now for me.

**Comment by kat05** [comment]
@simmonsr Just wondering, in the Content tab there are for example 4 settings for Author, one each under Blog, Post, Page and Archive. I did some testing last week and had to disable for several of those to make sure the Author was really gone from all pages on frontend.

**Comment by simmonsr** [comment]
The "Home" Page Title isn't supposed to be showing I don't think:

![screen shot 2015-08-07 at 2 12 20 pm](https://cloud.githubusercontent.com/assets/5002814/9143848/66302c6a-3d0e-11e5-9668-94ea9184078a.jpg)
![screen shot 2015-08-07 at 2 12 44 pm](https://cloud.githubusercontent.com/assets/5002814/9143849/6634d620-3d0e-11e5-8ad0-64827641a19a.jpg)
