### ISSUE TITLE
WordPress: using characters from foreign alphabets like greek or hebrew is breaking front end

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#691]
Non-ASCII characters only menu items break frontend

**Comment by AK-101111** [comment]
If I use even one menu item with greek characters the front site becomes unrenderable.

**Comment by newkind** [comment]
Can you please post a link to your site or a screenshot ? Did you used any translation plugins or you just edited the menu in the WP ?

**Comment by AK-101111** [comment]
My site is on localhost for the time being. 
No translation plugins, this is a clean install with only gantry and twig plugins installed. 
I only edited the menu in WP. 
I have debug enabled but nothing renders, i get a blank screen. If I remove the greek menu item the site renders again.

**Comment by newkind** [comment]
Thanks for the info. Can you type me here exact name of the menu item and your menu setup so I could try to replicate it on my local ?

**Comment by AK-101111** [comment]
Thanks for the quick reply. 
It should be reprodusable by simply editing the Navigation Label of an existing menu item from latin to any Greek character. 
Here is on to copy paste Γ.

**Comment by newkind** [comment]
Yah, I can see the issue, front end goes blank.

@mahagr can you also try it ?

**Comment by mahagr** [comment]
I have no issues with menu having Greek characters in my menu items. I'm using Hydrogen and my character encoding in database is UTF-8.

**Comment by mahagr** [comment]
Edit: Alright, all Greek is issue, I had some latin characters there as well.

**Comment by newkind** [comment]
The same with Hebrew - a user just reported this in the Gitter.

**Comment by newkind** [comment]
Another word to test : Κεντρική

**Comment by ContrerasG** [comment]
Hello native Spanish speaker here, several characters are not allowed i.e:
-any of our Spanish punctuation marks to open  like ¿ ¡ or the " ñ "

I think the only ones allowed are English...

**Comment by DamirPecnik** [comment]
Another user on RT forums have problem with Russian Language in Menu, the site brakes when he uses Russian characters in menu ...
