### ISSUE TITLE
WordPress - changes to WP menu items do not show on frontend

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#692]
I have a 2nd level menu item called 'Alignment', which showed up fine on frontend.
Then I went to > Appearance > Menus and for that menu item I changed the Navigation label to 'Alignmentsssssss'.
Refreshing the frontend will keep showing 'Alignment'.
Then I went to the G5 Menu editor and changed the name to 'AlignmentSSS'.
This will then be shown on frontend.

Anyways, any changes inside the WP menu editor, do not seem to have any effect.

**Comment by kat05** [comment]
Just a note, I now deleted a menu item from the WP menu editor and that got correctly removed on frontend too.

**Comment by kat05** [comment]
Changing the order of menu items in WP menu manager, also does not have any effect on the frontend or the G5 menu editor.

**Comment by mahagr** [comment]
Should be fixed now.
