### ISSUE TITLE
Google Font issue when RokBooster is enabled

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#699]
The thing is that only one font gets imported:

![alt](http://i.imgur.com/aThEmZ6.png)

While two should be imported:

![alt](http://i.imgur.com/esWIVn3.png)

The font loaded first (Body Font) will be the only one that will work.

Steps to reproduce:

1. Install the default G5 + Hydrogen (CI build)
2. Select two different Google fonts for "Body Font" and "Heading Font". MUST be different!
3. Reload the page and notice that everything works as expected
4. Install and enable RokBooster
5. Refresh the page (if needed couple of times so the CSS gets combined in one PHP file) and notice that only one font is imported (the first one - Body Font) and the styling of the "Heading Font" goes back to the default browser font because the Google Font is not found.

**Comment by w00fz** [comment]
This is not really a Gantry 5 issue but RokBooster. Anyway I was able to fix this and it will be available with RokBooster v1.1.15.

Cheers!

For internal reference: ROKBOOSTER-73

**Comment by JoomFX** [comment]
Wow! Man, that was quick :D
Thanks a lot Djamil!
