### ISSUE TITLE
Menu Image is not visible!

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#70]
When selecting image for menu item its not appearing on front-end.
![2015-04-07 22 09 11](https://cloud.githubusercontent.com/assets/10489911/7032407/e46845e6-dd72-11e4-9d06-7692535e2fdd.jpg)

**Comment by w00fz** [comment]
@kevlardev @mahagr I know we discussed this and knew the images in the menu items weren't rendering. I just don't remember whether we were going to drop that field or not?

Referencing to #58

**Comment by newkind** [comment]
I don't think we should drop it

**Comment by mahagr** [comment]
Fixed in bff8212
