### ISSUE TITLE
Menu Whoops error when re-editing menu item

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#700]
Steps to reproduce :
1. Edit root level menu item
2. Add icon and subtitle
3. Hit "Save and Apply"
4. Try editing the menu item again

![callisto theme e2 80 b9 gantry5 wordpress e2 80 94 wordpress 2015-08-12 07-38-55](https://cloud.githubusercontent.com/assets/1641534/9217373/1c5167dc-40c7-11e5-86fe-b092d7edb8b0.png)

**Comment by mahagr** [comment]
I cannot reproduce this locally so I'll wait Jakub to get back in order to get more details on what goes wrong.

**Comment by kat05** [comment]
i can confirm this issue, it seems to be a new one, I remember doing this several times last week and did not run into the error. 

![g5_wp_whoops](https://cloud.githubusercontent.com/assets/5719486/9218498/576022d0-40d3-11e5-9e56-0aa6c97f7496.png)

**Comment by kat05** [comment]
I might be wrong of course, but then I previously tested the menu and did not have the above mentioned issue, this fix https://github.com/gantry/gantry5/issues/697 had not been implemented yet. Not sure though if this change could cause the error or not. Just wanted to add the info in case it might be helpful.

**Comment by kat05** [comment]
@mahagr  my install is a core wp install with callisto and gantry hebe linked. also, after i received the above error, i closed the menu editor, then reopened it again and reselected the menu that i previously edited. i now see this:
1. it tells me that the menu is empty which is not correct.
2. the dropdown has changed its layout and is no longer usable, please see pic

![g5_wp_menuwhoops](https://cloud.githubusercontent.com/assets/5719486/9218706/e7712fee-40d4-11e5-8fe1-9915207d5241.png)

**Comment by kat05** [comment]
I have now deleted the problematic menu item and now the menu will load correctly again in the g5 menu editor.

**Comment by mahagr** [comment]
Please try to find reliable way to reproduce it!

**Comment by kat05** [comment]
I just followed the exact steps that Jakub mentioned in his original post.

**Comment by kat05** [comment]
It seems that after it is broken, the only way to make it work again, is to go to the WordPress menu editor and resave the menu.

**Comment by kat05** [comment]
@newkind  i can no longer replicate this issue today. i deleted my previous install and started fresh and it's no longer happening for me on this new one.
