### ISSUE TITLE
Make logo particles image responsive

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#702]
Does gantry have a class similar to the bootstrap `.img-responsive` class which, according to Bootstrap  applies the following:

> Images in Bootstrap 3 can be made responsive-friendly via the addition of the .img-responsive class. This applies `max-width: 100%;`, `height: auto;` and `display: block;` to the image so that it scales nicely to the parent element.

It would be helpful if something like this would be available as one of the core variations available from the drop-down In a particles settings, especially in regards to things like the logo particle.

On my menu system, the logo is displayed using a logo particle dropped between the third and fourth items in the mail menu. If it doesn't scale properly, it well cause the menu to wrap. See this screen shot from an iPad:

![image](https://cloud.githubusercontent.com/assets/1498512/9218198/8a566c56-40d0-11e5-81f5-afde0c0d55fe.jpg)

Images in other areas appear to scale, but the logo doesn't.

**Comment by kevlardev** [comment]
All images by default include those values in gantry5 (max-width: 100%; height: auto) the logo particle img is inheriting those as well (so long as the logo element is an <img>). If you place the logo particle elsewhere you will see it scales appropriately. Perhaps there is an issue with it when placed inside a menu due to the way the menu items are structured.

**Comment by mahagr** [comment]
I changed this into question for now as we are not yet sure if this is a menu issue or something else.

**Comment by mahagr** [comment]
@alisamii I was thinking about this and I think you could just add some CSS to make the image in here responsive. Let us know if you find a good way to do it, I'd like to know it for myself, too.
