### ISSUE TITLE
Catch warnings from SCSS compiler

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#705]
After updating SCSS compiler, it added support for warnings and errors. Looks like we need to catch those, otherwise the errors get outputted to twig:

    <link rel="stylesheet" href="/wp-content/plugins/gantry5/engines/wordpress/nucleus/css-compiled/wordpress.css?55c8639b" type="text/css" /> 
    Line 1 WARN: "box-shadow is deprecated and will be removed in the next major version release" 
    <link rel="stylesheet" href="/wp-content/themes/callisto/custom/css-compiled/callisto-wordpress.css?55cc6e9b" type="text/css"/> 

First seen in #704.

**Comment by mahagr** [comment]
It looks like Save Styles ignores all messages and just returns success messages.

We need to change that to return also possible warnings from SCSS compiler.

To test this out:

* Edit custom.scss and put ```@warn "This is my warning";``` into it.
* Try what happens on Recompile vs Save

PS: Also error messages need a bit more styling, file is located in ```platforms/common/templates/layouts/css-warnings.html.twig```. We can take a look on those after this feature has been correctly implemented.

**Comment by w00fz** [comment]
I'm not getting any warning in the response of the ajax?

```
code: 200
html: "The CSS was successfully compiled"
success: true
title: "CSS Compiled"
```

**Comment by mahagr** [comment]
See my comment above on how to get warning. :)

**Comment by w00fz** [comment]
I did, my `custom.scss`

``` scss
@warn "This is my warning";
```

**Comment by w00fz** [comment]
I see it now
