### ISSUE TITLE
Unsupported CI Builds versions in Changelog

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#706]
I just tried latest CI build to try the new "change log" link and got a server500 error

Windows 10 PC.

nothing in apache error log
![2015-08-13_14-02-27](https://cloud.githubusercontent.com/assets/11683218/9250473/24f4b2aa-41c5-11e5-8f03-9cf77347db5e.png)

**Comment by kat05** [comment]
I am getting the same error to on Mac OS.

**Comment by kat05** [comment]
This works fine now.
