### ISSUE TITLE
WP theme preset switch requires to save twice to see changes

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#708]
Changing WP themes preset styles requires to twice hit "Save Styles" button to be able to see the changes on the frontend. After first save the hash changes but not the actual file content. This is most likely a Yosemite bug.

**Comment by kat05** [comment]
I am on Yosemite too but I can not replicate this issue.

In the Callisto Base outline, I select a different preset, hit 'Save Styles', wait till it's done, refresh frontend and I see the new style.

**Comment by kat05** [comment]
Works just fine for me with Hydrogen as well.

**Comment by kat05** [comment]
Ok, seems this issue happens in Production mode, then I can replicate it too.
Before I was using Development mode.

**Comment by mahagr** [comment]
Doh, I hope that latest version of SCSS haven't changed this again. I've fixed it already once for us.

**Comment by kat05** [comment]
ok, with matias rocketlauncher package from today, updated to latest ci i can now replicate this issue too.

**Comment by newkind** [comment]
Ryan reports that this is also issue in MAMP + El Capitan

**Comment by mahagr** [comment]
Seems to be fixed..
