### ISSUE TITLE
Clicking + button to add a new outline doesn't refresh the page

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#709]
When hitting the + button on the outlines page, you get the notice that outline has been created, but it doesn't appear until you manually refresh the page.

![callisto theme callisto wordpress sandbox wordpress 2015-08-14 13-29-20](https://cloud.githubusercontent.com/assets/1641534/9273042/91e308bc-4288-11e5-9b1c-e73c9d57147a.jpg)

**Comment by newkind** [comment]
There's another issue connected to this. If you create the outline and rename it, it doesn't update the ID of it until you refresh the page.

![callisto theme callisto wordpress sandbox wordpress 2015-08-14 13-29-20](https://cloud.githubusercontent.com/assets/1641534/9273515/be0ff008-428d-11e5-9882-8074dc7d84e6.jpg)

This means that when you try to edit it you'll get :

![callisto theme callisto wordpress sandbox wordpress 2015-08-14 14-03-54](https://cloud.githubusercontent.com/assets/1641534/9273521/c939aa96-428d-11e5-93e0-a481b75cb48b.jpg)

**Comment by mahagr** [comment]
Same as #588?

**Comment by newkind** [comment]
most likely
