### ISSUE TITLE
add 'toggle selection' functionality for menu assignments 

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#71]
please see pic taken in gantry4, it would be nice to have the same option in gantry5 too.
![g5_assigntoggle-1](https://cloud.githubusercontent.com/assets/5719486/7036010/8a596c60-dd54-11e4-86e1-82da4088cb82.png)

**Comment by w00fz** [comment]
Yup we have plans on improving the assignments section quite a bit. See also https://github.com/gantry/gantry5/issues/2#issuecomment-87098165

**Comment by kat05** [comment]
sweet!
