### ISSUE TITLE
We need something like custom variations to add custom css classes to widgets

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#711]
We need something like custom variations to add custom css classes to widgets - this is needed for sample content ie. in Callisto

**Comment by w00fz** [comment]
Maybe what it's needed is a replica of what Modules in Joomla do `moduleclass_sfx` where you can add space separated class names?
This would mean injecting a class suffix text field for all widgets.

**Comment by newkind** [comment]
Yah I was thinking about something like that as that's what we have currently in G4. @kevlardev suggested to ignore this and use block modules but i'm starting to think that even if it's a proper approach, we still might benefit from possibility of easy adding extra css classes to widget chrome.

**Comment by kevlardev** [comment]
It still is a handy feature as it makes it easier to add module/widget specific alterations and custom css when you need to tweak little things. I just meant that they shouldnt be used to control main style appearance and as anchors of functionality (as those should be platform independent and utilize block level variations and classes).

**Comment by w00fz** [comment]
Yah I agree, variations should be kept within the LM, additional classes for block wrappers that are case-by-case specific and not necessary theme related, we could inject in the widgets so that they can be accessed outside of the LM and from the Widgets page.
