### ISSUE TITLE
Placing a RokSprocket as a particle widget instance removes all RokSprockets widgets

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#712]
When you have widget postions placed in the Layout Manager and some RokSprocket widgets inside of them, and you will place the RokSprocket widgets directly in the Layout Manager, all of the instances of RokSprocket widget will disappear from widget positions.

**Comment by newkind** [comment]
Looks like this is a bigger issue than we thought, because widgets need to be saved as widgets into database so the code being executed in them would know where to load the instance from.

**Comment by DamirPecnik** [comment]
I noticed that when i placed the shortcode to the page it also didn't work!

**Comment by mahagr** [comment]
For now as workaround to the bug Sprocket and rokGallery cannot be picked up in Gantry admin.

**Comment by mahagr** [comment]
Widget instances have been deprecated with WP 5.8 Widget Blocks feature.
