### ISSUE TITLE
Bring back Joomla Debug module position - Feature

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#715]
Has there been any thought, pro or con, in bringing back the Debug module position that existed in Gantry 4 ?

**Comment by mahagr** [comment]
It is there, at least in my hydrogen (I'm using the position). But as it's not strictly required, it may be missing from some layouts.

**Comment by mahagr** [comment]
On this one -- should we have the debug position outside of the layout and only in Joomla?

**Comment by kevlardev** [comment]
There's really no need for a user facing position for debug any longer i don't think? Its really not helpful to display debug information anywhere else besides full width at the bottom of the page output. I think it should just be outside of the layout in Joomla platform only, and not visible or manipulated in the layout manager as a "position".

**Comment by mahagr** [comment]
I agree on that. After we have added the fixed position, we should go through all the layouts and remove the ones we have included.

**Comment by mahagr** [comment]
Alright, I made debug position to be fixed to the bottom of every single page.
