### ISSUE TITLE
ERROR:  Twig_TokenStream::nextIf()

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#717]
Hello @ all,

after I updated to Gantry5 I had a strange error.
I use Twig in some custom templates and Modules. All these custom sites throw the following error when i upgraded to Gantry 5.1.0.

```
Whoops\Exception\ErrorException thrown with message "Call to undefined method Twig_TokenStream::nextIf()"

Stacktrace:
#3 Whoops\Exception\ErrorException in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Twig/TokenParserAssets.php:55
#2 Whoops\Run:handleError in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php:119
#1 Gantry\Component\Whoops\Run:handleError in /var/www/domain.net/htdocs/libraries/gantry5/vendor/filp/whoops/src/Whoops/Run.php:357
#0 Whoops\Run:handleShutdown in <#unknown>:0
```

I don't really understand why this error is Thrown - I have my own version of Twig installed under a different path.

**Comment by mahagr** [comment]
I am betting that you have 2 different versions of twig; just make sure that you are using the latest version in your extensions.

BTW: If you have Gantry 5 enabled, you can just rely on Gantry 5 having Twig already loaded for you, so you do not need to include the libraries by yourself. Also make sure whenever you update Gantry, you will clean up the cached template files in your own stuff.

**Comment by w00fz** [comment]
Could it be your own version of Twig is older than what we are using with Gantry?

https://github.com/gantry/gantry5/blob/develop/src/composer.json#L11

**Comment by w00fz** [comment]
@Omegatcu were you able to solve this?

**Comment by Omegatcu** [comment]
didn't had time today - will try tomorrow.

**Comment by delixyr** [comment]
I am having the same issue.
I use p8pbb bridge to bridge between Joomla and phpbb on my site. When phpbb is set to un stand alone it works. When I try to embed phpbb within joomla I get this error.
Happened since updating Gantry to 5.1.0
I use Ambrosia template/style for joomla/phpbb

![ddggh](https://cloud.githubusercontent.com/assets/4602841/9404146/9f2cec18-480a-11e5-9b68-453581794940.png)

**Comment by mahagr** [comment]
As you are using Ambrosia for both Joomla and phpBB, I'm going to prioritize the issue.

**Comment by delixyr** [comment]
@mahagr yes.

**Comment by Omegatcu** [comment]
my problem was solved with the new twig version.

**Comment by mahagr** [comment]
As phpBB seems to be fixing this issue in the next release, I'm not going to work it around for Gantry.
