### ISSUE TITLE
WordPress: Updates available notification is missing

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#718]
When there is a new version of Gantry available, it's not been shown up in Gantry administration.

Joomla has this working, so I'm marking it as a bug.

**Comment by w00fz** [comment]
Purple bar?

**Comment by mahagr** [comment]
Yes, that bar doesn't have any content in WP yet. Part of the reason is that we haven't yet published Gantry5 in WP extension directory. So this issue is more of a reminder to deal with it when we prepare our next release in their directory.
