### ISSUE TITLE
Gantry 5.1.0 has borked ToTop particle

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#720]
Forum issue here -> http://www.rockettheme.com/forum/joomla-template-salient/246445-to-top-arrow-missing-after-gantry-update
Either the totop.yaml or totop.html.twig has changed as this is what the ToTop icon looks like now:
![totop](https://cloud.githubusercontent.com/assets/3792467/9324815/abb2aab0-455b-11e5-93f8-00c1fbbaced4.jpg)

**Comment by kat05** [comment]
I can confirm this issue with Salient and Gantry 5.1.0

**Comment by mahagr** [comment]
To me Gantry looks OK for this; the variables should be escaped.

We may need to have override in Salient on this, I will check it out in a bit.

**Comment by mahagr** [comment]
Yeah, what salient has is:

    content: '<span class="fa fa-2x fa-angle-up"></span>'

**Comment by arifinrt** [comment]
In totop.yaml, the description says it allows html. So, I think we need to "allow" that?

    content:
      type: input.text
      label: Text
      description: The text to be displayed for the link. HTML is allowed.
      default: To Top

**Comment by mahagr** [comment]
@w00fz @kevlardev Your input on this?

**Comment by adi8i** [comment]
That's an easy fix, i forgot about filter, sorry :) https://github.com/gantry/gantry5/pull/721

**Comment by w00fz** [comment]
Adrian's fix is good.

Salient content icon is redundant now, when that was set as span icon, we didn't have the separated fields for icon/text.

I think we need to merge the raw filter in and going forward use the icon field instead of html in the content field.

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
Fixed with #721
