### ISSUE TITLE
Can't drag-and-delete a particle

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#723]
Can't drag-and-delete a particle after installing CI build (Version: dev-3c81cc2c5)

**Comment by mariantanase** [comment]
I can conferm this. I wrote this on gitter too

**Comment by sural98** [comment]
@mariantanase Using "chrome://flags/" check if the option "Enable touch events" is disabled in Chrome.
I have enabled it and it now works in Chrome.
However it didn't work with Opera and Firefox.

**Comment by sural98** [comment]
No. I am sorry for the confusion but not working in Chrome either.

**Comment by sural98** [comment]
The option "Enable touch events" should remain disabled in Chrome.

**Comment by w00fz** [comment]
Hey guys, I am unable to reproduce this but @mahagr had the same issue and clearing the browser cache fixed it for him. Could you try that?

**Comment by mahagr** [comment]
Yes, I was able to reproduce this one time; then I reloaded the page and issue was gone.

**Comment by w00fz** [comment]
Sorry guys! I was able to reproduce this, it only happened when loading the `Layout` tab via Ajax and was an issue I introduced while fixing #551.

Should be good now! Good catch.
