### ISSUE TITLE
Error installing Gantry for wordpress

### ISSUE THREAD

**Issue by ckubs** [gantry/gantry5#725]
Installed the plugin, installed Hydrogen theme and I wasn't able to use it. I got a notice that I have to install a library called Timber, installed that too via plugins and then everything was screwed up. 

The frontend is blank and I can't acces the backend because I get a weird page with Gantry style,

"RuntimeException
Fatal error: Theme does not have default layout "

...full of error.

Now I'm puzzled. Any help would be much appreciated.

**Comment by newkind** [comment]
Any url to your site ?

**Comment by ckubs** [comment]
http://goo.gl/cZADYS

**Comment by newkind** [comment]
Ok, I can see that you don't have your Hydrogen set as your theme. The error you mentioned can happen when there's an issue with configuration and layout locations. Can you please try to reupload your Gantry 5 plugin and Hydrogen theme so we would be sure it's not a bad upload ?

**Comment by ckubs** [comment]
OK, take a look again. I was using Theme Test Drive so I only saw the error. Now the theme is active and the problems are there.

**Comment by newkind** [comment]
Still can't see the error but this doesn't matter now. Can you please tell me if you tried reuploading both plugin and theme ?

**Comment by newkind** [comment]
Can you also check the permissions for files and directories ?

@mahagr looks like we might need a better error message for this issue.

**Comment by ckubs** [comment]
For directories I have 755
This is the error page I get http://oi62.tinypic.com/nexsbc.jpg

**Comment by newkind** [comment]
Can you please check that in the wp-content/themes/rt_hydrogen/layouts you got there some yaml files ?

**Comment by ckubs** [comment]
It may sound odd but this time I uploaded the theme via ftp/Cpanel not via Wordpress theme installer and it works, with no error page. The yaml files are there. Don't know why this is happening.

**Comment by newkind** [comment]
Sometimes this happens ;) Maybe there was some issues with connectivity in your region etc. I'm glad that it works! Closing!
