### ISSUE TITLE
WordPress menu system enhancements

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#726]
This was postponed to be added after release, but I cannot find ticket for that so I'm going to make a list of items that Gantry 5 WP menus still needs to get done.
- [x] Ability to use Widgets in menu
- [x] Synchronize particle menu items with WP core menu
- [x] When renaming menu item title, that item get reordered to be the last one

**Comment by newkind** [comment]
There's also another issue that throws Whoops error when editing menu item name in the G5 menu editor.
![callisto theme e2 80 b9 gantry5 wordpress e2 80 94 wordpress 2015-08-24 13-34-56](https://cloud.githubusercontent.com/assets/1641534/9520458/cd3e5206-4cc7-11e5-9a75-6d8674ec5589.png)

**Comment by mahagr** [comment]
Needed by the next theme.

**Comment by ryanaddams** [comment]
There's a bug with the Gantry menu editor in WordPress. If you edit and save a menu, it looks fine on the first save but one of the dropdown items is duplicated (it overwrites/renames an existing item). If you save again, this is made permanent in the yaml file. Each reload of the Gantry menu editor seems to exhibit variations of this behavior and the item cannot be fixed. The only workaround is to not use the Gantry menu editor in these cases and to delete the yaml file for that menu if it exists.

None of the aforementioned issues seem to cover this specific case, but it's repeatable on my site using the latest production WordPress and Gantry.

**Comment by DamirPecnik** [comment]
@mahagr any idea when this will get implemented or resolved? WordPress users are suffering from it ... :)

**Comment by mahagr** [comment]
We talked about this with @newkind and it's something we're trying to focus on during the next bug fix phase. Let's hope we'll find the fix. :)

**Comment by marktaylor46** [comment]
Another RT member with the same issue here http://www.rockettheme.com/forum/wordpress-theme-fluent/274903-menu-issue

We really need to get this resolved IMHO

**Comment by blizam** [comment]
I'm sure it's related. When I try and create multi-columns or generally change the order of things nothing saves. I'll save my changes in the Menu Editor, browse away (to the Outlines tab or something) and when I come back everything, or 90% of my changes at least, have reverted. I'm sure I'll eventually get there by writing the menu.yaml file myself but I wanted to make sure this behavior was included in the fix. I did have child items that I made parents which may be part of my issues, as described by others here.

**Comment by blizam** [comment]
For what it's worth I notice pretty strange behavior in how things are saved in the [menu-name].yaml file:

--sometimes items don't save an Object ID
--If you have 2 menu items with the same name saving becomes erradict; the items get mixed up
--ampersands (and presumably other special characters) in the Menu Display Name 'cause  erradict behavior... sometimes it saves ok, othertimes not... I've run into instances where clicking the settings icon on an item returns a popup message of "404 not found - Oops, Menu item not found."
--I don't understand the Object_IDs at all really... probably some WP thing I just don't understand... but the Object IDs I see get saved on the items: list in the yaml file are not always the Object ID of the WP Menu Manager... sometimes they are... sometimes they're within a number or 2 and somehow still seem to work... other times I've had the number be the exact Object ID as I see in the WP Menu Manager and I still get the 404 not found - Oops, Menu item not found when trying to change a menu item's settings

**Comment by mkdev-de** [comment]
3 years later: Any idea if that gets fixed?

**Comment by mahagr** [comment]
I took yet another deep look into this issue and I have found a fix for the issue. It will take some time to get it fully fixed and tested, but I'm hopeful that it will finally be fixed to the next version (5.4.26) which should be out within 2 months.

You can see the progress in https://github.com/gantry/gantry5/tree/feature/wp_menu branch.

Right now the branch has the logic to save all our extra data into the menu items, but only menu item specific data is loaded from the database. This means that ordering, columns and particles are not yet loaded from the new DB storage.

**Comment by mahagr** [comment]
UPDATE: Make that **Gantry 5.4.27*' as there was a regression bug in 5.4.25 which needed a quick patch.

**Comment by blizam** [comment]
Will the new DB storage for the Menu address this issue?

https://github.com/gantry/gantry5/issues/1194

**Comment by Safeworld4women** [comment]
Re @blizam comment - Likewise - would be good to know if #1194 will be fixed in update.

**Comment by mahagr** [comment]
Regarding to WPML menu issue, I don't think that synching menu particles to the database fixes the issue, but I have not tested it yet.

As an update, I've made great progress on fully utilizing WP menu items in the database inside Gantry menu and its manager. There are still some minor issues that I need to fix as well as a decent amount of testing needed, but the implementation looks to be working great in most parts.

**Comment by careercoder** [comment]
I highly recommend doing the following... 

Whenever a person is modifying the menu - create a temporary menu with what is being created. 

Erase the core menu - and replace with the new menu once saved. 

The only way I resolved this was by erasing the YAML file.

**Comment by mahagr** [comment]
Closing in favour of #2473

**Comment by LMKWeb** [comment]
I was having the same issue reported with menu items in a Joomla site - were the improvements made just to the WP branch? Should I open a new issue for Joomla?

**Comment by mahagr** [comment]
I'm going to look into Joomla and Grav next.
