### ISSUE TITLE
Make 5+ Available on Wordpress Plugin Repository and WPackagist

### ISSUE THREAD

**Issue by JesusisFreedom** [gantry/gantry5#729]
It would be great to be able to have gantry 5 up on wppackagist. I use a WP stack that makes it easy to require plugins through composer. 
I noticed 4.*.* is available on wppackagist.

If you publish 5.0 to the Word Press plugins site wppackagist will pick it up automagically.

**Comment by w00fz** [comment]
We are certainly going to add Gantry 5 to the Wordpress plugins repository. As soon as they approve the plugin it's going to be there available.

I'll keep the issue open so we can update on the status of it.

**Comment by newkind** [comment]
We want to wait till the next G5 update to fix the biggest issues and after that we'll submit the G5 to wordpress.org

**Comment by newkind** [comment]
Officially requested Gantry 5.1.1 to be added to the WP.org plugins directory! Now all we need to do is wait :)
