### ISSUE TITLE
Change module variation doesn't change the color of the content text.

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#73]
Sorry to bother with these issues. I found another one :bug:  :)
Try this scenario:
On the **Layout** tab, go to **Aside** section, then go to **Position-7** module and click on the wheel (settings module), finally click on **Block** tab.
On **Variation** field add **Box3** style (Parenthesis: is not obvious how to cancel the label *Box3*  when you don't want it. I'll select and then press Delete but suggest to add some kind a "close" icon to be more obvious.)
Now turn back to base issue.
When apply **Box3** (or someone else) and save, on frontend it changed only the background, but not the text-color ! The color of the text is the same as the background-color.
.box3 .g-content{
background:none repeat scroll 0% 0% #439A86;
color:#fff:}

Supposed that should be added something like:
.box3 .g-content a{
color:#fff;}
![gantry5b2shot01](https://cloud.githubusercontent.com/assets/3976174/7040712/534c9db8-ddd2-11e4-94a7-ed9b3ecaef22.png)

**Comment by mahagr** [comment]
Related to #58
