### ISSUE TITLE
Namespacing Issues When Used with a WP Composer stack

### ISSUE THREAD

**Issue by JesusisFreedom** [gantry/gantry5#730]
When using Bedrock from roots.io I get the following error when I have all the plugins and one Gantry5 theme enabled.

See image for error.
http://imgbin.org/images/25572.png

**Comment by mahagr** [comment]
I've already fixed the bug in https://github.com/rockettheme/toolbox/commit/c0b7c2f70d3f7a4ab6bfcc6f9117d006502a8133 and you can easily apply the fix manually to test it out.

It will not get rid of the issue, though, but may get us into the issue.

**Comment by JesusisFreedom** [comment]
Wow, so simple. I should have caught that!

Thanks.

**Comment by w00fz** [comment]
Oops I missed that too! :smile: 
Now I am curious, were you able to get Gantry working with bedrock after applying the fix?

**Comment by JesusisFreedom** [comment]
No,

It kept erroring out in Uri locator looking for css files that didn't exist
in the hydrogen theme???

On Fri, Aug 21, 2015 at 9:50 AM, Djamil Legato <notifications@github.com>
wrote:

> Oops I missed that too! [image: :smile:]
> Now I am curious, were you able to get Gantry working with bedrock after
> applying the fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantry/gantry5/issues/730#issuecomment-133491572>.
>



-- 
-Austin with FWD

**Comment by mahagr** [comment]
I would report a new bug on it if you haven't already done so or solved the issue.
