### ISSUE TITLE
Error : Call to undefined method Twig_TokenStream::nextIf() 

### ISSUE THREAD

**Issue by delixyr** [gantry/gantry5#731]
I use p8pbb bridge to bridge between Joomla and phpbb on my site. When phpbb is set to un stand alone it works. When I try to embed phpbb within joomla I get this error.
Happened since updating Gantry to 5.1.0
![ddggh](https://cloud.githubusercontent.com/assets/4602841/9403629/64c29c34-4806-11e5-9c6a-aef90244de01.png)

**Comment by mahagr** [comment]
Same as #717, closing as duplicate.
