### ISSUE TITLE
Cannot drag menu items anymore since yesterdays updates

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#732]
Since yesterday I'm unable to drag & drop menu items in G5 menu manager. When I try to drag them they act like a regular <a> elements.

Also after updating the sandbox to the latest CI build, i lost all my menu columns and custom html particle in the under Styles menu item for Callisto. But not sure if that's related.

**Comment by w00fz** [comment]
This works fine for me. Maybe try clearing the browser cache and try latest CI Build or `git pull`. There was a few CI Builds where this was broken and then fixed.

**Comment by w00fz** [comment]
Ok this should be good now.

**Comment by newkind** [comment]
Fix confirmed.
