### ISSUE TITLE
Issue regarding admin language

### ISSUE THREAD

**Issue by ckubs** [gantry/gantry5#733]
I'm testing and hopefully use gantry 5 for my website. Opened the admin for the first time and there's something strange. I don't see some translatable words( I guess that they are) but instead:
GANTRY5_PLATFORM_STYLES
GANTRY5_PLATFORM_RECOMPILE_CSS
GANTRY5_PLATFORM_THEME
...etc
My wordpress install is not in English but my native language. Could this be an issue?

**Comment by newkind** [comment]
Yes, this was a bug in the 5.1.0, it's already fixed in the latest CI builds if you want to try it.

**Comment by ckubs** [comment]
Oh, thank you :)

**Comment by newkind** [comment]
We're here to help ;)
