### ISSUE TITLE
Skip to main content button should be hidden by default

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#735]
After recent accessibility changes when you load the theme settings page in WP admin you can see the "Skip to main content" button that doesn't go away until you click somewhere on the page. Shouldn't this be hidden by default ?

![screen shot 2015-08-21 at 15 49 21](https://cloud.githubusercontent.com/assets/1641534/9409640/376870d6-481c-11e5-919f-adb88ee47681.png)

**Comment by w00fz** [comment]
This is not ours but Wordpress. It shows up automatically when you tab from URL bar. It's foraccessibility and we have no control over it.

**Comment by w00fz** [comment]
Sorry I see what you mean now. You have to click on Ajax pages and it will show up again. Should be fixed now.
