### ISSUE TITLE
Drag & Drop broken in Layout Manager in latest CI

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#736]
The drag & drop of particles and atoms is broken in the latest CI build for WP (possibly a same issue as in the menus #732 

Steps to reproduce -
1. Go to the theme settings page in the WP admin ie. Hydrogen Theme
2. Try dragging particles - it should work just fine
3. Switch to a different outline from the dropdown in the left top corner
4. Try dragging again - it won't work anymore

**Comment by w00fz** [comment]
This works fine for me. Maybe try clearing the browser cache and try latest CI Build or `git pull`. There was a few CI Builds where this was broken and then fixed.

**Comment by w00fz** [comment]
Give it a try now please.

**Comment by newkind** [comment]
Confirmed fix.
