### ISSUE TITLE
Intro and Full Article Images on Joomla are not responsive 

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#737]
The images set on Article > Images and Links > Intro Image and Full Article Image seems to not be responsive.

The images added on the Article > Content are responsive.

How can I fix this?

**Comment by adi8i** [comment]
Both images are responsive, i've just tested it.

**Comment by nicutor** [comment]
After some help from @hennysmafter and @adi8i I found that this is responsive on Chrome but not on Firefox and IE. The solution can be found here http://forum.joomla.org/viewtopic.php?f=713&t=820231

You need to add this on custom.scss

.pull-left {
float: left;
width: auto;
height: auto;
max-width: 100%;
}
