### ISSUE TITLE
Time to first byte too long in WP

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#738]
I'm not sure why but time to first byte on WP installation with all plugins disabled besides Gantry 5 and Timber are between 1.2s - 1.5s and the difference is big compared to Joomla. Can you investigate that ?

**Comment by mahagr** [comment]
For some reason the page loads really slow compared to default WP themes; 500ms vs 70ms for me. I think that the slowdown is caused by Timber or how we use it; I'm not sure yet.
