### ISSUE TITLE
WP language file not loading properly

### ISSUE THREAD

**Issue by adadeacon** [gantry/gantry5#739]
I've just installed the Gantry 5 plugin and Hydrogen theme on a new WP installation on Wamp for a new site I'm developing.

It seems like the plugin's language file doesn't load properly when working on the theme admin area.
I see text like this all over the place: 'GANTRY5_PLATFORM_STYLES', 'Section GANTRY5_PLATFORM_STYLES', 'Core GANTRY5_PLATFORM_STYLES', 'GANTRY5_PLATFORM_RECOMPILE_CSS'.

I've refreshed the page a few times and cleared my browser cache, but it stays the same.
![dfinanz_theme_ _dfinanz_ _wordpress_-_2015-08-22_23 39 04](https://cloud.githubusercontent.com/assets/13922544/9425978/0b0195fc-4927-11e5-8a6b-5a958a8266e5.png)

I have changed the Hydrogen theme's name to Dfinanz, which you can see on the screenshot, but this language issue also came up before when I installed the theme with modified name. It seems the language issue is limited to the plugin itself and not the theme.

***UPDATE***
I've installed a fresh copy of WP on my online development server, installed the Gantry plugin and Hydrogen theme. Getting the same language file issue.
Online site: http://dfinanz.owlmedia.co 
![hydrogen_theme_ _dfinanz_ _wordpress_-_2015-08-23_00 12 50](https://cloud.githubusercontent.com/assets/13922544/9426107/c86a60b6-492b-11e5-91c4-b90611b72e72.png)

**Comment by newkind** [comment]
You're using English UK, Australia, New Zeland - any but US right ? This was a bug in Gantry 5.1 and is fixed in the CI builds, so if you want to have it fixed please use the latest CI build from the gantry.org site and not the stable 5.1 release.

**Comment by adadeacon** [comment]
Yes, using English UK. Thank you, I'll use the latest CI build.
