### ISSUE TITLE
Navigation menu placed on Sidebar

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#74]
I created a new layout preset based of the *How to Create a Sidebar Section* guide.
on the left sidebar I put a menu particle.
On frontend, the **Login** item is floated to the right.

**Admin** Screenshot
![gantry5b2-menuleft1](https://cloud.githubusercontent.com/assets/3976174/7043953/d0cd1eb8-ddee-11e4-857c-aa3f3f1befbd.png)

**Frontend** Screenshot
![gantry5b2-menuleft2](https://cloud.githubusercontent.com/assets/3976174/7043960/db0a748e-ddee-11e4-8f9e-2be32c3d1da5.png)

Suggest to create an option on **Menu** particle to choose what kind of menu to use ( **Vertical** or **Horizontal** menu).

**Comment by adi8i** [comment]
if I remember correctly @kevlardev explained somewhere that menu particle is designed to be placed in header or navigation section, aesthetic reasons. Therefore , does not support any other section. You can do it at your own risk, and will require customization.

**Comment by mariantanase** [comment]
I saw there are many websites who place the menu on the sidebar (left or right). I don't like this limitation, it makes me forced to use third party menu modules.

**Comment by adi8i** [comment]
You don't need third party, you can use Joomla menu module, is good enough and also you can simple customize with bootstrap classes just add them, at advanced tab. Or as i said, you may add custom css to g5 menu, but some changes will come in beta 3 so you can wait

**Comment by JoomFX** [comment]
What @adi8i says is correct. You can read @kevlardev reply in https://github.com/gantry/gantry5/issues/49

This is not a limitation. You can achieve whatever you want, you just need to do it on your own. Rockettheme will surely have a Template that will have the Main Menu in the sidebar, but they will do quite some modifications to the default Gantry5 template in order to achieve that.

**Comment by mariantanase** [comment]
ok, thanks. Now I see the @kevlardev reply in #49

**Comment by beamaria** [comment]
By the way, you can see that placing the menu in a different section from Navigation enhances the problem or misaligned arrow indicator - same problem for which I opened  #68 issue -

**Comment by w00fz** [comment]
@adi8i I REALLY like the screenshot tool app you used for adding notes on that image :laughing: 

And also referencing #58 :+1:

**Comment by adi8i** [comment]
Thank you @w00fz :laughing: Yeah is Snipping Tool from win 8.1

**Comment by w00fz** [comment]
Alignments are fixed in #58 and for the rest Kevin answered in #49!

**Comment by joomapp** [comment]
Hi Guys,

For anyone bumping into the same question. After some CSS tweaks it's quite easy to set a normal menu in vertical position. Add a "normal" menu particle to the sidebar.

Give the sidebar -> section -> block the #ID: sidebar
Name the menu particle CSS ID: g-mobilemenu-container

Now add the following to your custom.scss

`/* Sidebar main menu styling */
#sidebar {background:#2f576f;color:#ffffff;}
#sidebar a {color: #fff;}
#sidebar #g-mobilemenu-container ul {
  background: #2f576f;
  z-index:999;
  transition: ease-in;
  width:19vw;
}
#sidebar #g-mobilemenu-container ul > li > .g-menu-item-container {
  color: #fff;
}
#sidebar #g-mobilemenu-container ul > li:not(.g-menu-item-type-particle):not(.g-menu-item-type-module):hover, #sidebar #g-mobilemenu-container ul > li:not(.g-menu-item-type-particle):not(.g-menu-item-type-module).active {
  background: #2f576f;
}
#sidebar #g-mobilemenu-container ul .g-dropdown-column {
  width:19vw;
  height:350px;
}

`
