### ISSUE TITLE
Hydrogen activated; site not rendering (+ admin)

### ISSUE THREAD

**Issue by jasonday** [gantry/gantry5#744]
I installed the latest gantry framework and hydrogen theme (5.1) from the gantry website. Additionally, I installed timber (https://wordpress.org/plugins/timber-library/) for the twig templates as outlined in the Gantry documentation.

When I activate the Hydrogen theme, the site does not render' it is completely blank including the admin interface (no errors, including the console).

Please advise.

**Comment by newkind** [comment]
Can you check if you have installed a WP plugin called "Twig" ?

**Comment by jasonday** [comment]
@newkind - I do have the twig plugin installed (I misrepresented by calling it timber above).

When I activate the theme, the site is blank.

Removing the theme, I get an error message in the theme admin panel:

Error: Twig Autoloader not found!

**Comment by newkind** [comment]
Twig plugin is not needed and causes the conflicts with Timber as Timber itself contains Twig implementation. Timber library is the plugin you need for Gantry 5.

Can you also please make sure that you're running PHP 5.4+ ?

**Comment by jasonday** [comment]
@newkind - I have tried with both plugins - same result.

However, the php version is the issue. 

Thanks.

**Comment by newkind** [comment]
Yah, so you need Twig plugin deactivated and PHP 5.4+ and you should be fine :) Please let me know if that fixed the issue.

**Comment by jasonday** [comment]
@newkind - that fixed it. I had to manually set php 5.6 within .htaccess. Thanks.
