### ISSUE TITLE
Gantry 5 display of DPcalendar not as nice as Protostar

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#746]
Topic at http://www.rockettheme.com/forum/joomla-template-metropolis/246719-pop-up-not-working
This is the DPcalendar modal window in Protostar:
![gantry5-protostar-dpcalendar](https://cloud.githubusercontent.com/assets/3792467/9430110/1c3e1806-49b6-11e5-8655-58f0e205de92.jpg)

This is the DPcalendar modal window in Salient:
![gantry5-salient-dpcalendar](https://cloud.githubusercontent.com/assets/3792467/9430111/1c3ee830-49b6-11e5-8830-1713ea4986dc.jpg)

**Comment by mahagr** [comment]
https://github.com/gantry/gantry5/commit/e9be92df949b5a8328e5c054edc8cfca650ef102

**Comment by mahagr** [comment]
@DanGthatRokGallery Can you check if the issue is fixed for you?

**Comment by DanGthatRokGallery** [comment]
Awesome job guys!
Close this one off.
