### ISSUE TITLE
The menu selected is empty!

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#748]
I have modified/changed/unpublished some menu items via Joomla menu manager.
Now G5 menu editor says ALL menus are empty.
What is the problem?

**Comment by mahagr** [comment]
I'm not sure of what happened, but it surely sounds like a bug. Is there a way to reproduce the issue?

**Comment by sural98** [comment]
I can provide you with the login of site. How can I do that?

**Comment by mahagr** [comment]
Gitter chat. :)

**Comment by mahagr** [comment]
This may be language assignment issue, still investigating if there's an easy fix for this one.

**Comment by mahagr** [comment]
@sural98 Did you fix your issue as all the menus seem to be working just fine in your site..?

**Comment by sural98** [comment]
Applying the latest builds it is fixed now.
Thanks.

**Comment by TEUCG** [comment]
This issue has resurfaced in 5.2.10 - language assignment issue, and all altered menus are now claimed to be to be empty in the "menu pane".
Also an error 500 appears when attempting to access the "Settings Pane":

> Oops, An exception has been thrown during the rendering of a template ("Trying to get property of non-object") in "forms/fields/menu/list.html.twig" at line 5..

**Comment by mahagr** [comment]
Can you make a new issue about this. It would also be helpful if you had any idea how to reproduce the issue reliably, so that I could test it in my development environment.
