### ISSUE TITLE
Not possible to remove module/particle from RocketLaunchers

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#749]
Please see screenshot.
![2015-08-26_08-39-18](https://cloud.githubusercontent.com/assets/11683218/9488972/86475fca-4bd5-11e5-816d-8272e86ca9d0.png)

Currently it is not possible to remove a module/particle from the G5 menu editor - there is not "drop to delete" function. I't also not possible to remove the module.particle from the joomla menu manager.

So, currently the only way seem to be to delete the parent menu item and then recreate it.

**Comment by mahagr** [comment]
@w00fz Can you check this one out?

**Comment by marktaylor46** [comment]
btw it's just the last remaining particle/module you can't delete. If you add another your can delete that.

**Comment by marktaylor46** [comment]
confirmed fix
