### ISSUE TITLE
Add HTML body class for used layout preset

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#750]
I added a body class in config/home/page.yaml like the following:

	doctype: html
	body:
	  class: gantry g-home

but neither 'gantry' nor 'g-home' is rendered in the body class

**Comment by mahagr** [comment]
We decided to fix this in a better and more compatible way.
	
"It feels to me that body class should be really something that belongs to the layout so if you create a new outline from scratch and just assign home layout preset it should have all the CSS classes set that home layout requires.."
