### ISSUE TITLE
Whoops error when editing menu item name in the editor

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#752]
Whoops error appears when you edit the menu item name in the G5 menu editor and hit save.

![callisto theme e2 80 b9 gantry5 wordpress e2 80 94 wordpress 2015-08-24 13-34-56](https://cloud.githubusercontent.com/assets/1641534/9520476/0686c37c-4cc8-11e5-8282-dadcecff63fe.png)

**Comment by mahagr** [comment]
There is still issue with ordering renamed item.

**Comment by mahagr** [comment]
See #758
