### ISSUE TITLE
Joomla 404 throws exception

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#755]
Hello @ all,

i believe we have a problem with soft 404 errors.

On a Joomla website I get some errors when i try to open a non existing url:

```
[Fri Aug 28 10:17:42 2015] [error] [client xx.xx.xx.85] PHP Fatal error:  Uncaught exception 'Whoops\\Exception\\ErrorException' with message 'Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given' in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php:89

Stack trace:
#0 /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php(119): Whoops\\Run->handleError(2, 'Parameter 1 to ...', '/var/www/it-dai...', 89)
#1 [internal function]: Gantry\\Component\\Whoops\\Run->handleError(2, 'Parameter 1 to ...', '/var/www/domain.net...', 89, Array)
#2 /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php(89): call_user_func(Array, Object(Exception))
#3 [internal function]: Gantry\\Component\\Whoops\\Run->handleException(Object(Exception))
#4 {main}\n  thrown in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php on line 89
```

the normal Response should be a 404 error

**Comment by mahagr** [comment]
Try latest CI build, I believe we already fixed it.

**Comment by Omegatcu** [comment]
just the exception changed slightly - CI build from 2 minutes ago

```
Whoops\Exception\ErrorException thrown with message "Uncaught exception 'Whoops\Exception\ErrorException' with message 'Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given' in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php:89
Stack trace:
#0 /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php(119): Whoops\Run->handleError(2, 'Parameter 1 to ...', '/var/www/domain...', 89)
#1 [internal function]: Gantry\Component\Whoops\Run->handleError(2, 'Parameter 1 to ...', '/var/www/domain...', 89, Array)
#2 /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php(89): call_user_func(Array, Object(Exception))
#3 [internal function]: Gantry\Component\Whoops\Run->handleException(Object(Exception))
#4 {main}
  thrown"

Stacktrace:
#0  in /var/www/domain.net/htdocs/libraries/gantry5/classes/Gantry/Component/Whoops/Run.php:89
```

**Comment by mahagr** [comment]
Nice, you found a bug in Joomla.

Alright, now I need to figure out how not to handle the error in this case...

**Comment by mahagr** [comment]
In the mean time, go to ```plugins/system/redirect/redirect.php``` in your Joomla install and change line 55 from:

    public static function handleError(&$error)

to:

    public static function handleError($error)

**Comment by Omegatcu** [comment]
is this quick fix in 5.1.1?

**Comment by w00fz** [comment]
It's not a Gantry issue but Joomla so until we find a workaround for it (or Joomla fixes it), you need to apply that patch on your Joomla install yourself.

**Comment by mahagr** [comment]
It's quick fix in Joomla. We may need to wait some time before Joomla gets the fix, but I'm keeping this issue as reminder so I can do there 2 things:

1) Submit a pull request to Joomla.
2) Figure out how to avoid the message in Gantry.

To be honest, I already thought that exceptions from outside Gantry were passed forward. I need to take a look why it doesn't happen in this case.

**Comment by DanGthatRokGallery** [comment]
running 5.1.2 on Salient I get
http://localhost:8081/Salient/index.php/features/overview?format=raw:
blank page - Chrome console shows a 200 Status Code

http://localhost:8081/Salient/index.php/dang.html:
this non-existent page 404's properly

**Comment by mahagr** [comment]
@DanGthatRokGallery That is a different issue; could you create a new bug out of it?

**Comment by mahagr** [comment]
@Omegatcu 

Which PHP version you're running on as I'm unable to get this error in PHP 5.6

**Comment by Omegatcu** [comment]
Debian with PHP 5.4.41

**Comment by mahagr** [comment]
Found a way to work around the issue without needing Joomla fix.

**Comment by Omegatcu** [comment]
you are the man :D
