### ISSUE TITLE
Different custom styles for different layouts

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#76]
I am not sure how this thing works, is more a question.

I have a custom scss file in Template -> Custom -> scss -> custom.scss

I also have menu "Home" with Template Style "Hydrogen - Default" assigned. This template style will auto load styles from "custom.scss".

Now i will create a second menu named "Page 1" and another Template Style "Hydrogen - Default (2) " assigned.
For this one i don't need any css style placed in "custom.scss" and i want to create a different scss files.

1. Will both "Hydrogen - Default" and "Hydrogen - Default(2)" auto load custom.scss file?

2. If i will create "custom-2.scss" and i will load this file into "Hydrogen Default (2)" with "custom css/js" atom, will take effect only this template style or both template styles will use it ? 

So i would like to have:
        " Hydrogen - Default"   with "custom.scss"
        " Hydrogen - Default (2)" with "custom-2.scss"

I've asked this because i have some "@media" and i need this for "Hydrogen - Default" only. 
Wondering if i can write "@media" like this (so i can use custom.css for all template styles):

.my-custom-style {
       @media (mix-width: 0001px) and (max-width: 99999px) {
               .span6 {
                bla : bla bla;
                }
        }
}

**Comment by JoomFX** [comment]
@adi8i The custom.scss file will always load, no matter on which page you are.

1. Yes, both will load the code from custom.scss file

2. If you create a "Custom JS/CSS" atom and place it only in "Hydrogen Default (2)" it will be fine but the code from your custom.scss will still be loaded

What you can do is:

1. Assign a custom CSS class to the Menu Particle (or to the section where you have the Menu Particle) on " Hydrogen - Default". For example "adrian".

2. In your custom.scss file write your code using the "adrian" class, for example:

```
.adrian .g-main-nav {
    ...
    ...
    ...
}
```

That's how the changes from the custom.scss file will be applied only to the Menu Particle in "Hydrogen - Default" because the other one does not have the "adrian" class ;)

**Comment by adi8i** [comment]
This is what i do @JoomFX , i always create my own classes and assign them to section or modules. 

I've asked this because i have some "@media" and i need this for "Hydrogen - Default" only. 
Wondering if i can write "@media" like this (so i can use custom.css for all template styles):

.my-custom-style {
@media (mix-width: 0001px) and (max-width: 99999px) {
bla: bla bla;
}
}

**Comment by JoomFX** [comment]
So you should be perfectly fine :)

Just your code should be like this:

```
@media (mix-width: 0001px) and (max-width: 99999px) {
    .my-custom-style {
        bla bla bla;
    }
}
```

I bit different from what you wrote :)

**Comment by adi8i** [comment]
Yes and no :)) . For example if i will edit span6 class, should be something like this: (but i dont know if sass will allow is to branched 

.my-custom-style {
         @media ( etc) {
                      .span6{
                       }
          }
 }

or i can write something like this:

@media (..) {
      .my-custom-style {
          width: 100% !important;
        }
  }

dunno... anyway i will try and see what works better

**Comment by JoomFX** [comment]
Basically both of the above examples will work :)

It is probably a matter of "personal taste".

Back to your original question - as you are already doing (having a custom CSS class only on "Hydrogen - Default"), then just write your code as follows:

```
@media (...) {
    .adrian {
        .span6 {
            ...
            ...
        }
    } 
```

or

```
.adrian {
    @media (...) {
        .span6 {
            ...
            ...
        }
    }
}
```

**Comment by adi8i** [comment]
Yes, i've tried now the second one and it's works :D , i will close this now . Thanks for help @JoomFX
