### ISSUE TITLE
Cant change website logo after version 5.1.1

### ISSUE THREAD

**Issue by Sanderluc5** [gantry/gantry5#763]
Everytime when i change my website logo to another image my website is still displaying the old image. On joomla 3.4.3

**Comment by mahagr** [comment]
Which template are you using? Can you try latest CI build if it fixes the issue as I'm not able to reproduce it with latest build.

**Comment by Sanderluc5** [comment]
Same problem on latest Ci build (dev-33a3601d4)

Im using hydrogen as template.

**Comment by w00fz** [comment]
I cannot reproduce this either.
Could you try to explain in steps what you did so we can try to reproduce the issue?

**Comment by kat05** [comment]
it's working fine for me too, using 5.1.1.

**Comment by adi8i** [comment]
Try to clear cache, probably you have server cache enabled, or joomla too, thought joomla cache is not that aggresive.

**Comment by Sanderluc5** [comment]
I will try to reinstall gantry. Cache is not the problem. Maybe the checkboxes are the problem everytime when i check a checkbox after save settings the checkboxes are blank.

**Comment by w00fz** [comment]
If the checkboxes reset it means the value is the same as Base Outline so it's not considered an outline.
You need to click the checkbox to enable the override but also change the value (in your case the image). Then you save.

**Comment by Sanderluc5** [comment]
Reinstall worked :) this thread can be closed.

**Comment by w00fz** [comment]
Sweet! Thanks for checking
