### ISSUE TITLE
Callisto RokSprocket Tabs module - Infolist is borked by G5 5.1.1

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#764]
Updated Callisto to 5.1.1 and the panel content for the RokSprocket Tabs module has disappeared.
![borked-sprocket-tabs-panel](https://cloud.githubusercontent.com/assets/3792467/9565902/9ba1b3c0-4eb9-11e5-8fb4-021aaa45c57b.jpg)

**Comment by DanGthatRokGallery** [comment]
Uninstalled G5 5.1.1 and re-installed 5.1.0
then reinstalled 5.1.1 and then it worked
I don't know???

**Comment by mahagr** [comment]
I'm going to keep this open..

**Comment by kat05** [comment]
i am not seeing any issue with callisto sprocket tabs using 5.1.1 and also not using latest Version: dev-290dcf45c.

i think it's invalid?

**Comment by adi8i** [comment]
The issue should be fixed in the latest CI Build, please read: #773

**Comment by mahagr** [comment]
We are not able to reproduce this anymore. Closing unless proved wrong.
