### ISSUE TITLE
Adding ToTop particle to row in Copyright Section

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#765]
For every Outline I do this to on Save I get this message:
500 Internal Server Error

Oops, A YAML file cannot contain tabs as indentation at line 10 (near "	class: box2")..

However it does save and on the Frontend ToTop works fine.

**Comment by DanGthatRokGallery** [comment]
This message also appears when adding an Atom then saving the layout.

**Comment by mahagr** [comment]
Which template is this in?

**Comment by w00fz** [comment]
Did you manually edit the yaml file?
I remember you had this issue before and was your editor using tabs rather than spaces. In YAML only spaces are allowed for indentation.

**Comment by DanGthatRokGallery** [comment]
No only does it in Callisto, 90% of the time any Save Layout brings up the message. No this is a clean install running a v1.2 on edited YAML files

**Comment by mahagr** [comment]
There was an update on twig for this version; not sure how it could be broken, though.

**Comment by DanGthatRokGallery** [comment]
okay my bad-when I first setup Callisto 1.0 I managed to set a Box2 variation for the "Header Section Settings" thats what Gantry was complaining about.
As soon as I removed "class: box2;" from pages_-_offline.yaml - the message was gone
Sorry guys
