### ISSUE TITLE
Block sizes min, max values incorrect on SECTION settings

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#766]
Further to #539 implemented in Gantry 5.1.1 There seems to be two issues:
![2015-08-30_11-27-16](https://cloud.githubusercontent.com/assets/11683218/9566793/69f3256a-4f0a-11e5-9980-2ceb393f6023.png)

1. The values are wrong
2. Should the "block" tab be present at all on SECTION settings

**Comment by marktaylor46** [comment]
Another member with this issue:
http://www.rockettheme.com/forum/member-submissions/247091-update-of-gantry?start=0#1231139

**Comment by w00fz** [comment]
The Block is supposed to show up for sections ONLY when they are side-by-side and not regular sections (ie, YES for SideLeft / SideRight, NO for Navigation / Header). 

I know this was working before 5.1.1 release and the Block was only showing where expected so something must have changed before that.

**Comment by marktaylor46** [comment]
Great, at least my understanding was correct then, block tab should not appear on navigation section.

Good luck hunting that down... :)
