### ISSUE TITLE
Atom JS not working at all

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#769]
In Callisto v1.2 G5 5.1.1 I was following Mark's guide http://www.rockettheme.com/forum/joomla-template-callisto/241487-adding-animate-css-and-wow-js-to-callisto

I entered Base Outline and clicked on CSS/JS to create my Atom. First thing I noticed my Chrome Console was showing these errors:
![main js-error-applying-file_location_path-for-atom](https://cloud.githubusercontent.com/assets/3792467/9568840/c1b006dc-4f24-11e5-816b-4882cbd02c91.jpg)

I created my WOW Atom:
![atom-setup-for-wow-base_outline](https://cloud.githubusercontent.com/assets/3792467/9568842/dac82a28-4f24-11e5-93d5-0ee2d56c6346.jpg)

When clicking Apply or Apply/Save you get an infinite-spinner and have to click OFF the modal and then click SAVE Layout to save your entires. Entered Atom to confirm they were still there - OK

Left BO and went to Callisto-Home and dragged in my WOW atom only to see this:
![atom-setup-for-wow-new-atom-dragged-into-callisto_home](https://cloud.githubusercontent.com/assets/3792467/9568858/536ce662-4f25-11e5-8309-4491e14afcdf.jpg)

Went back to BO to double check and it had changed to:
![atom-setup-for-wow-base_outline-after-leaving-and-coming_back](https://cloud.githubusercontent.com/assets/3792467/9568863/6517740e-4f25-11e5-970a-e5a2b9e29b37.jpg)

So instead I thought I would customize the Atom in the Layout Manager. Again I could create the entires and click Save Layout and get the Success message but going back in all the JS entries had disappeared again.
From adding the entries in BO and then here it accumulated quite a few blank rows:
![atom-setup-for-wow-callisto_home-cant-delete-created-entries](https://cloud.githubusercontent.com/assets/3792467/9568882/d2903994-4f25-11e5-985f-d468e13282ad.jpg)

However there was no way I could delete these. Trashed the Atom and created this ticket :(

Another user has this issue -> http://www.rockettheme.com/forum/gantry-framework/247061-unable-to-make-changes-to-custom-css-js-atom-settings-since-5-1-1

**Comment by adi8i** [comment]
The issue should be fixed in the latest CI Build, please read: #773

**Comment by kat05** [comment]
this seems to work ok now in latest ci (commit: 33a3601d4)

i followed mark's tutorial, but in salient instead of callisto
