### ISSUE TITLE
Hydrogen: Header Modulpositions typo with CSS Classes

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#77]
Hello - found a minor problem with the CSS classes in the module positions in the header (i think only there)

```html
<div class="g-block size-58">           
	<div class="g-content">
		<div class="platform-content">
			<div class="moduletablemycssclass nopaddingall">				
				<div class="custommycssclass nopaddingall">
				<p><img src="http://placehold.it/468x60&amp;text=Banner" alt=""></p></div>
				</div>
			</div>
		</div>
	</div>
</div>
```
`moduletablemycssclass` and `custommycssclass` need a space :D
We can do it in the module but please insert the space ;)

**Comment by mahagr** [comment]
That class comes from Joomla and is "feature" in it.
