### ISSUE TITLE
Deleting outline may cause 500 errors in the backend

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#774]
on a salient rocketlauncher with latest ci, i went to the outlines panel and deleted the 'typography' outline. this worked fine.

right after without doing anything else first, i tried to delete the 'coming soon' outine.

i get a popup with the following error:
```
500 Internal Server Error
Oops, An exception has been thrown during the rendering of a template ("Preset not found") in "@gantry-admin/layouts/outline.html.twig" at line 1..
```

this will then lead to more 500 errors after closing that popup and clicking the 'back to setup' button:
```
500 Internal Server Error
Oops, Identifier "theme" is not defined..
```
closing that popup and then trying to go to 'settings' panel will cause the following:
```
500 Internal Server Error
Oops, Cache path not defined for compiled file (/Applications/MAMP/htdocs/jo_salient_ci/media/gantry5/engines/nucleus/particles/analytics.yaml)!.
```

**Comment by kat05** [comment]
i just replicated this same issue in gantry 5.1.0, so not a new bug.

**Comment by DanGthatRokGallery** [comment]
Just tried this with G5 5.1.2 and it worked fine

**Comment by mahagr** [comment]
I was able to reproduce this in 5.1.2, so I guess the bug is still there.

**Comment by coolman01** [comment]
I cleared the default outline and everything worked fine (latests gantry 5 with isotope) but tried to use Gantry Particle and when I clicked the select particle button got the 500 error with "Oops, Cache path not defined for compiled file " --path/analytics.yaml. So clearing an outline also affects the defined atoms

**Comment by coolman01** [comment]
As an addendum - i turned off the analytics atom everywhere and deleted my settings so that it's not being used, and I still get the same error. Can't move forward now....

**Comment by mahagr** [comment]
Could you please specify the exact steps to get the error?
