### ISSUE TITLE
WordPress - Akeeba backup fatal error when Gantry 5 plugin is activated

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#775]
With Gantry 5 plugin activated in Admin, Akeeba has a fatal error:

```
[31-Aug-2015 21:17:04 UTC] PHP Fatal error:  Cannot redeclare PasswordCompat\binary\_strlen() (previously declared in ../wp-content/plugins/gantry5/src/vendor/ircmaxell/password-compat/lib/password.php:267) in /Applications/MAMP/htdocs/wp_callisto130_demo/wp-content/plugins/akeebabackupwp-core/app/Awf/User/password.php on line 258
```

![g5_wp_akeeba](https://cloud.githubusercontent.com/assets/5719486/9590760/fd9ce968-5036-11e5-8d11-3d0a34d25510.png)

**Comment by kat05** [comment]
Akeeba download link:
https://www.akeebabackup.com/download/backup-wordpress/1-4-2/akeebabackupwp-core-zip-3.raw

**Comment by newkind** [comment]
We have the proper checks in our code but Akeeba doesn't and since our code is running before Akeeba we can't do anything about it. I have sent them an email and asked to add this to their code :
```
if (!function_exists('PasswordCompat\\binary\\_strlen')) {
```

**Comment by newkind** [comment]
Just got a message from Akeeba guys that they fixed it 2 days ago and fix will be released with next update :) YAY!

**Comment by kat05** [comment]
cool!

**Comment by n8115** [comment]
Thanks for the update newkind.

Just ran into this same issue and I thought it was a different plugin causing a conflict.  Great to hear they're fixing this :)
