### ISSUE TITLE
Layout Manager -> Block -> Equalize Width issue

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#776]
with Salient and G5 5.1.2 I set up a Showcase row with 3 Particles and then pressed the equalize width button
![info_list-particle](https://cloud.githubusercontent.com/assets/3792467/9595528/a1081c32-5035-11e5-8034-76ba454729a7.jpg)
 None of the particles can be saved as the Block widths are too large:
![info_list-block](https://cloud.githubusercontent.com/assets/3792467/9595545/bd1cec68-5035-11e5-84d4-273344c0ae4e.jpg)

I get a Red message box warning I have an invalid field. Once I manually changed the value to 33.333% the particle would save.

**Comment by w00fz** [comment]
Can you try with Chrome if it's the same?

**Comment by mahagr** [comment]
Yup, seems to be identical in both.

Should we round the displayed/stored sizes to 0.1 just like in Gantry itself?

**Comment by w00fz** [comment]
Give it a try with the latest CI Build Dan, should be good now.

**Comment by mahagr** [comment]
Adding new particles into layout stopped working, reopening.

**Comment by w00fz** [comment]
?

Isn't this for equalize and block sizes? What new particles?

// Djamil Legato // From iPhone //

**Comment by adi8i** [comment]
Was about this: http://screencast.com/t/fpkVFzBbk

**Comment by mahagr** [comment]
Basically the new code broke inserting new particles into layout.

**Comment by w00fz** [comment]
I'm not entirely sure how, in order to test this change I was dropping in many particles and I haven't seen any issue with it. Also all the code does is rounding the decimal to 1 digit, nor sure how that could break stuff. 
Maybe your js is cached?

// Djamil Legato // From iPhone //
