### ISSUE TITLE
G5 5.1.2 Layout Manager -> Block readability

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#777]
Still hard to read text for small
![block-readability](https://cloud.githubusercontent.com/assets/3792467/9595650/f7e807dc-5036-11e5-9667-be1f3c323893.jpg)
 width blocks:

**Comment by mahagr** [comment]
I proposed earlier to display a popup showing all the info when hovering over the item, but there may be some technical difficulties on doing that.

**Comment by w00fz** [comment]
This was already ticketed, discussed and optimized a little, there's only so much room we can deal with.
