### ISSUE TITLE
drop-down arrow on menu is not centered

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#78]
When add variation **Align Left** to **Menu** particle, the drop-down arrow is align to the left, not centered inside that square as I expect. I don't remember if someone else has the same problem.
![gantry5b2-shot1](https://cloud.githubusercontent.com/assets/3976174/7068503/2de5ad06-ded3-11e4-8b23-3494fc4dd71b.png)

**Comment by mariantanase** [comment]
I see something similar on issue #68

**Comment by beamaria** [comment]
Yes, same problem for me...it depends on the fact the menu particle is not in "navigation" section - in my case it was in "header" section

**Comment by mariantanase** [comment]
In my case the menu particle is in *navigation* section.

**Comment by beamaria** [comment]
Ah, ok, anyway w00fz reminded us that the best part of menus problems will be fixed in beta3...maybe this issue will be ok in 3
