### ISSUE TITLE
Not all menu item children showing when starting at level 2

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#780]
This may be related to #666 but I think it is different. This is on 5.1.2 Gantry with Hydrogen

Please see screenshots below. Level 1 menu item has two children at level 2. You can see this works fine as a dropdown normal menu. But if you have a second menu starting at level 2 then only the first child at level 2 is being shown?

![2015-09-01_16-17-51](https://cloud.githubusercontent.com/assets/11683218/9608433/37680fbc-50c6-11e5-9393-7927b797038b.png)

![2015-09-01_16-16-59](https://cloud.githubusercontent.com/assets/11683218/9608329/c9e12424-50c5-11e5-8852-c9bf69185a62.png)

![2015-09-01_16-23-57](https://cloud.githubusercontent.com/assets/11683218/9608378/fb991fbc-50c5-11e5-9bfa-4391d779d881.png)

Link to forum http://www.rockettheme.com/forum/gantry5-for-joomla/247150-separate-submenu?start=0#1231601

**Comment by mahagr** [comment]
Fixed in 05d5eab
