### ISSUE TITLE
Custom Variations

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#782]
It would be good to have a way to add new custom variations that would be displayed in particle settings.

Right now, there are several variations that are built in, such as `box1`, `nomargin`, etc.

In order to add new variations, you need to edit the file `/templates/g5_hydrogen/gantry/theme.yaml`.

This file is currently cannot be overridden. Personally, I think that this setting is correct, as any changes made to the base template by divs will automatically be updated when a new update is installed.

However, I think a method should be implemented that would allow developers to add custom variations which would extend `theme.yaml`. This would ensure updates to `theme.yaml` are always taken into consideration while maintaining the ability to add new variations.

Perhaps, the custom variations could be added to a new file which could be placed here: `/templates/g5_hydrogen/custom/gantry/custom_theme.yaml`

The way I see this working is that when Gantry parses the core theme file `theme.yaml` at the end of the file, there is some code that looks to see if `custom_theme.yaml` exists, and if it does, it appends the contents to the core `theme.yaml`.

This same principle could be used to allow template developers to create new presets with a file `/templates/g5_hydrogen/custom/gantry/custom_presets.yaml`

**Comment by mahagr** [comment]
Simiar issue to #306

**Comment by w00fz** [comment]
Whatever logic we come up with, should also be applied to anything in `theme.yaml` really. Would be nice to be also able to easily add new local fonts without having to jump through hoops.

Somehow related to this is also #751

**Comment by nicutor** [comment]
+1 on this

**Comment by mahagr** [comment]
I've started the feature, but its not going to make it into 5.3

**Comment by shoulders** [comment]
As a noobie this was an issue I came across.  There should be both options:

1. I would like an option to add styles only - reason is that then i can keep track of the addtion options I have addeded easily

2. A full override - could be useful if you want to fully rework the names and variations available.

thanks

**Comment by saman222** [comment]
+1 on this
is it possible now or not?what do i do for create custom variation?

**Comment by N8Solutions** [comment]
@mariantanase & @w00fz This issue came up again for me. How's the progress coming along with being able to override and/or extend the `theme.yaml` file

**Comment by chatman1974** [comment]
> It would be good to have a way to add new custom variations that would be displayed in particle settings.
> 
> Right now, there are several variations that are built in, such as `box1`, `nomargin`, etc.
> 
> In order to add new variations, you need to edit the file `/templates/g5_hydrogen/gantry/theme.yaml`.
> 
> This file is currently cannot be overridden. Personally, I think that this setting is correct, as any changes made to the base template by divs will automatically be updated when a new update is installed.
> 
> However, I think a method should be implemented that would allow developers to add custom variations which would extend `theme.yaml`. This would ensure updates to `theme.yaml` are always taken into consideration while maintaining the ability to add new variations.
> 
> Perhaps, the custom variations could be added to a new file which could be placed here: `/templates/g5_hydrogen/custom/gantry/custom_theme.yaml`
> 
> The way I see this working is that when Gantry parses the core theme file `theme.yaml` at the end of the file, there is some code that looks to see if `custom_theme.yaml` exists, and if it does, it appends the contents to the core `theme.yaml`.
> 
> This same principle could be used to allow template developers to create new presets with a file `/templates/g5_hydrogen/custom/gantry/custom_presets.yaml`

Adding customized theme.taml file in  `/templates/template-name/custom/gantry/` folder is not working. You should add your customized theme.yaml file to `/templates/template-name/gantry/` folder. Customized theme.yaml file that placed in custom folder is not overriding to orginal theme.yaml file in  `/templates/template-name/gantry/theme.yaml`

Note: Sorry for bad English.

**Comment by mahagr** [comment]
I've finally implemented a way to use your own `custom/gantry/theme.yaml` file. I chose to go for a simple solution: if the file exists, it will be used instead of the default file. So if you override the file (or any other file), it is a good idea to check now and then if it has changed. Generally, themes have been very stable and most changes are between larger versions: 5.4 -> 5.5 -> 5.6...

Please check if it now works for you in CI build: https://gantry.org/downloads#ci-builds

PS. make sure you pick the correct file for your CMS.
