### ISSUE TITLE
&#65279; in HTML code

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#784]
I have noticed the following just after <body> tag in html code 
```<body class="site com_gantry5 view-custom no-layout no-task dir-ltr itemid-103 outline-10 g-offcanvas-left g-homepositions g-style-preset1">&#65279;```
Why is it (ZERO WIDTH NO-BREAK SPACE) outputted?

**Comment by adi8i** [comment]
Where's that, because i can't see it :)
```
<body class="site com_content view-article no-layout no-task dir-ltr itemid-105 outline-28 g-offcanvas-left g-default g-style-preset1">
```

**Comment by sural98** [comment]
In my local Salient launcher

**Comment by sural98** [comment]
I had overriden 
```SITE_ROOT/media/gantry5/engines/nucleus/templates/page.html.twig``` as 
```SITE_ROOT/templates/rt_salient/custom/engine/templates/page.html.twig```
It was the cause breaking the site styling entirely and outputting this entity.

**Comment by mahagr** [comment]
Maybe your override has some UTF-8 character in it?

**Comment by w00fz** [comment]
Did you mean you have overridden `page.html.twig`? The body tag is not rendered at all in `page_head.html.twig`, perhaps you have something else going on?

I also checked https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/templates/page.html.twig and I don't see any extraneous characters there.

// Djamil Legato // From iPhone //

**Comment by sural98** [comment]
It was page_head.html.twig but I can't reproduce the issue again.
It is normal now.
Sorry for any inconvenience!

**Comment by w00fz** [comment]
No problem, we were just confused, glad it's sorted.
