### ISSUE TITLE
[Question] What did i do wrong here

### ISSUE THREAD

**Issue by Legoman99573** [gantry/gantry5#785]
I tried doing this in the editor and i keep getting error messages. Is there something i need to fix the code in this, this has become quite annoying when the WYSIWYG editor has it looking perfect.

**Comment by w00fz** [comment]
Definitely need more informations here :)
Perhaps you forgot to attach a screenshot?

// Djamil Legato // From iPhone //

**Comment by mahagr** [comment]
@Legoman99573 More information is needed to solve your issue.

**Comment by mahagr** [comment]
Closing issue after 2 weeks of inactivity. Please be free to open it again.
