### ISSUE TITLE
Blank custom pages when format is not html

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#786]
Running G5-v 5.1.2 on Salient with Box setup:
 OS Windows-7
 PHP 5.6.8
 MySQLi 5.5.41-log

I get for these two URLS:
http://localhost:8081/Salient/index.php/features/overview?format=raw:
blank page - Chrome console shows a 200 Status Code

http://localhost:8081/Salient/index.php/dang.html:
this non-existent page 404's properly

**Comment by mahagr** [comment]
Thanks Dan from splitting the issue. :)
