### ISSUE TITLE
Duplicate template style cannot be distinguished

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#79]
Navigate to
**Extensions/template manager/templates (side panel)**
to see the list of templates.
Click
**G5_hydrogen Details and Files**
then
**Copy template**
to duplicate and name the new style.
Now go to 
**Components/Gantry 5 Themes**
Available G5 themes are listed with the same title and theme screen-shot.
There can be a distinguishing sign that one or more of the listed is/are duplicate(s)
The same is true for Layouts.
If any available layout is LOADED layout screen can tell that "this preset" is loaded.

**Comment by mahagr** [comment]
Yes, I did notice the same on copying template. And to be honest I really would like to replace the whole template manager as it is buggy on adding new files.

Presets we already discussed internally, although once you have created the layout, it will not change unless you will pick up the same preset again. Presets loading will change to keep all your items intact and not replacing them. Picking up existing configuration will replace all what you have. At least when that part gets implemented.

**Comment by sural98** [comment]
We will need multiple instances of  a layout in a multi-language Joomla installation (or you have something different in your mind?). 
Therefore we should be able to "save as" and name the copy of a layout in order to assign to language-based menu items.
In this case the name of the new layout should appear in the screen as follows for the sake of usability.
![layout_name](https://cloud.githubusercontent.com/assets/1849490/7105640/def7737c-e12b-11e4-9788-fcaf40813976.JPG)

**Comment by mahagr** [comment]
Layout doesn't have name, configuration does. And layout always lives inside a configuration, which you also need to change for multi-language. You can see the name of the configuration just above your screenshot. There will also be extra screen for configurations where you can manage the existing configurations from a single location. So I'm going to ignore the second message for now and just make sure that you can recognize copied templates.
