### ISSUE TITLE
iPad submenu roll down problem

### ISSUE THREAD

**Issue by GESign** [gantry/gantry5#790]
Dear Team,

I have a problem with Hydrogene template's submenu's arrow.
First of all: this problem is already fixed in Hydrogene template. But I don't know how I can reproducate it on my several webpages. It looks like it is not a css problem. Maybe a yaml problem?
You can see my problem on iPad, newer iPhone only:
http://www.missq.es/
http://hmgy.xi.hu/
http://elektroserv.hu/

Bud it works well here:
http://decorwine.com/ (I use the same yaml file as above)
http://segitokez2010.hu/

It looks like it is no yaml, no scss problem. But what can cause this problem?

I tried several things, I don't have any other idea. Help me, please.

**Comment by adi8i** [comment]
I will take a look. YAML has nothing to do with this. Submenu arrow is present in `html.twig` file, of course it's styled using scss.

**Comment by GESign** [comment]
I found this now: https://github.com/gantry/gantry5/issues/25
It works here: http://hmgy.xi.hu/
I tried before z-index, but maybe not on the right place.
I check this on my other sites. Thanks for your fast response!

**Comment by GESign** [comment]
Based on this comment: https://github.com/gantry/gantry5/commit/9b698be36533205826de07ab23573999ccdbd098 actually this is a z-index issue, but where should I take z-index: 2; line? Should I give this to ul or container div? 
Do you have built in vertical menu, please.

**Comment by GESign** [comment]
Container div. It looks like this is solved. Let me do it on other sites Tomorrow, please.

**Comment by mahagr** [comment]
As it looks like this issue has been solved, I'm going to close it. Just go into gitter chat if you have issues with your other sites; this is more like customization issue than a bug and people in there are usually very helpful. :)
