### ISSUE TITLE
How to MVC override in gantry5 + hydrogen?

### ISSUE THREAD

**Issue by laszlokosa** [gantry/gantry5#791]
Hello,
In gantry4 a 3rd party modules could be override with templates/[your_template]/html/ dir, but now it is not working.
Is there any possibility to use MVC for example for mod_k2_content module templates? And ofc how/where?
I tried to find an answer here about that but seems modules.php override thread didn't solution for me.
Best regards, L

**Comment by adi8i** [comment]
Should work as usually, gantry have nothing to do with this, as far as i know. I override some joomla files and modules and it works good.

**Comment by w00fz** [comment]
Yeah the regular Joomla way of overriding templates should just work, make sure your files are named correctly.

**Comment by laszlokosa** [comment]
Hello,
Hm. I am trying this a several hours and now try to prove you with screens that not working. After I switch to protostar template (for a short test) and switch back Hydrogen its works perfect. Don't understand what was wrong but you are right. :)
The mistake was in my system. Sorry for the unnecessary ticket.
Regards, L
