### ISSUE TITLE
Remove white borders on mobile in Hydrogen template

### ISSUE THREAD

**Issue by Sanderluc5** [gantry/gantry5#792]
Is it possible to remove the white borders in the template Hydrogen when surfing on a mobile? Im using joomla

**Comment by w00fz** [comment]
Can you take a screenshot to show which borders are you referring to?
Most likely you will need some custom css, you can follow the guide here: http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

// Djamil Legato // From iPhone //

**Comment by Sanderluc5** [comment]
Heres a picture of the borders
![screenshot_2015-09-04-01-36-55 1](https://cloud.githubusercontent.com/assets/9827642/9673792/4ed57c14-52a8-11e5-8cea-7246c371477e.png)

**Comment by kevlardev** [comment]
The Hydrogen theme shouldnt have any margin or paddings on the body or page container in mobile view. Have you added any additional custom css? Would you happen to have a link to your development site so I can take a closer look at whats going on?

**Comment by Sanderluc5** [comment]
I have only css overrides not custom css.
You can visit my site at: http://www.sdc-sneek.nl
The borders are only visible on small view size

**Comment by hennysmafter** [comment]
Your problem is in the bootstrap-responsive.css that is included in your template.

```css
@media (max-width: 767px)
body {
    padding-right: 20px;
    padding-left: 20px;
}
```

That is the code that is giving you the headache.

**Comment by kevlardev** [comment]
I'm going to go ahead and add a reset for that rule in Hydrogen to provide a bit better third party compatibility with extensions that are loading that rule.
