### ISSUE TITLE
Enhance Gantry 5 support in WordPress Customizer

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#793]
In the future releases we should extend the Gantry 5 with part of the settings to be added to the WP customizer. This would allow the editing of theme with live preview. We could use this : https://github.com/aristath/kirki

**Comment by mahagr** [comment]
I'm actually already playing with it by using particle widgets.. :)

**Comment by newkind** [comment]
Nice! We need MOOOOOORE! :D

**Comment by w00fz** [comment]
I looked at this and it is A LOT of work. Not only that, but the problem is this has to be implemented for each theme individually by providing functions and twig and js all to make it work in a fine-tuned way for each individual field. I don't think this is really of Gantry scope.

**Comment by mahagr** [comment]
This has been replaced with Widget Blocks in WP 5.8.
