### ISSUE TITLE
Base outline for readmore class

### ISSUE THREAD

**Issue by Boumy** [gantry/gantry5#794]
Hello.
I needed to replace Joomla's Bootstrap-like readmore button by a simple flat rectangle. I felt it was not so easy to clear the .btn  appearance with my cusom.scss 
adi8i gave me the advice to edit layouts/joomla/content/readmore.php to set a class of my own for
```<a class="myClass" href="<?php echo $displayData['link']; ?> ```
Wouldn't it be a good idea to integrate such a style "override" in Gantry ? As far as I have understood things, Gantry already acts on .btn-primary style to its color with Base Outline, so it would be great for .btn too… amho. Thank you.

**Comment by adi8i** [comment]
I think this one was solved in chat
:point_up: [September 4, 2015 5:11 PM](https://gitter.im/gantry/gantry5?at=55e9a6aac473234d41df686d)

**Comment by mahagr** [comment]
@Boumy Was this one solved already?

**Comment by Boumy** [comment]
Actually, this post wasn't about an issue. Sorry for my poor English. This was rather a feature request in case you think that people might want this ability to customize read more directly within Gantry UI. Especially because the hack adi8i gave me won't last in case of a Gantry update.

**Comment by adi8i** [comment]
@Boumy Read more has nothing to do with Gantry 5, it is in joomla core. Also that's not a hack, is an override, also has nothing to do with Gantry 5. That file will still be there after update, so no worries. That's the way joomla works, and honestly there are already lot of customization options in Joomla. You could try a language override, not sure if will work in this case, if you search a bit, you can override lot of things using language, from joomla admin, without writing any code.

**Comment by Boumy** [comment]
You are totally right. I am too tired and I make mistakes. layouts/joomla/content/readmore.php is of course a Joomla core file. And it won't be modified by a Gantry update. I was ridiculous. This confusion went because while I had the impression that Gantry leave us free to style everything like we want, suddenly I faced those "rebel" typed button.

**Comment by mahagr** [comment]
The issue with Joomla core overrides is that Joomla tends to change its code so often that we ended up having overrides on overrides in Gantry 4. It becomes fast a big issue as we cannot just drop support on some older version of Joomla and working around issues on older overrides in every template became a huge task. Changing Joomla styling is usually possible by just some CSS as you can target buttons etc pretty easily.

**Comment by kevlardev** [comment]
Yes, with Gantry 5 we wanted to avoid intensive overrides of Joomla output to keep the core code as close to native as possible. This ensures the best third party compatibility as well as less issues with future updates and maintenance. As stated above, CSS is the best approach for restyling those core joomla and bootstrap elements.
