### ISSUE TITLE
Module make using Gantry will not renter correctly if embedded in a article 

### ISSUE THREAD

**Issue by weredigi** [gantry/gantry5#795]
Using Joomla 3.43 with gantry 5.12 has anyone been able to get a module to render properly in an article using gantry.
What i'm trying to do is embed 3 modules on a page. They do come up "text only" but are not in a box as they should be. YET if i display the module using the layout manager it does work. Problem is the modules are needed in the middle of article . Second part to that you now have to use gantry to made the article position you can no longer type in a custom module position as Joomla use to allow that make several extra steps to make a module that embeds in a article .

**Comment by mahagr** [comment]
Gantry doesn't have any effect on how modules get rendered inside articles. Nor does Gantry has any effect on admin which modules you are able to pick up. Both of those are handled solely by Joomla and yes -- Joomla did remove ability to manually enter module position name without giving any way to add them.

PS. if you want to set chrome for the modules, you need to do it by using the shortcode syntax. We only provide a single type "gantry" in Hydrogen so maybe there should be some more.

**Comment by weredigi** [comment]
Well I'm afraid and I respectfully say "you're wrong"  
I have installed joomla with and with our gantry tried both tested on multiple computers (chromebook desktop and mobile) .
The module does not render "correctly" with gantry does without it!
If its the chrome doing it I have no idea but it plain and simple not rendering correctly or as intended YES does render just not correctly "no box .
Example not rendering here using module calls in Article> http://hiringhands.ca/test/test-mod
Example rendered as desired using layout !> http://hiringhands.ca/test/employers
Example using a "extra outline" and multiple sample content place holders to have it displayed as desired. A whole lot more work. and client will likely never be able to adjust! 
the extra layout has it working as we want but it was only done because it could not be done simple with inserting in article ....

**Comment by Bokelmann** [comment]
did you try something like  {loadposition xy,gantry} or {loadposition xy,standard}?

**Comment by hennysmafter** [comment]
What is happening while editing a Joomla article and including it on save it breaks the p tags. So the p tag will still say align right but the loadposition is no longer within that paragraph but outside of it. This is a bug in Joomla 3.4+ and hasn't been fixed yet. There is a temp. solution though.

Create module positions in G5 admin around the page content. It is a bit more work but will get the job done.
![2015-09-10 16 09 07](https://cloud.githubusercontent.com/assets/4426337/9790505/b6629ec4-57d6-11e5-9f61-d83ff6f2fa41.png)

**Comment by mahagr** [comment]
Has the issue been solved @weredigi with the above (two) suggestions?

**Comment by weredigi** [comment]
We used a work around but no its not fixed yet
