### ISSUE TITLE
Hydrogen layout manager; syntax error

### ISSUE THREAD

**Issue by jasonday** [gantry/gantry5#796]
Syntax error when accessing Hydrogen settings in WP admin.

>Whoops\Exception\ErrorException thrown with message "syntax error, unexpected end of file, expecting ']'"

>Stacktrace:
#0  in /home/movemain/public_html/wp-content/cache/gantry5/g5_hydrogen/compiled/config/eb9a57caf827da1a706a2a6a29f6c03d.php:176

Hydrogen & Gantry 5.1.2

**Comment by mahagr** [comment]
PHP 5.4 is required.

**Comment by jasonday** [comment]
5.4 as a minimum, correct? I'm setting 5.6 through .htaccess. I had a
similar issue prior and setting 5.6 resolved it.

**Comment by newkind** [comment]
Sometimes the .htaccess doesn't work. The best way to verify that is to create a new info.php file in the root of your WP installation and paste this code in the file :
```
<?php phpinfo();
```
After that just call the file url ie. http://mysite.com/wordpress/info.php and it will tell you which PHP version it's using.

**Comment by jasonday** [comment]
>PHP Version	5.6.12

Please let me know what additional information you need.

**Comment by newkind** [comment]
Try deleting cache directory in wp-content/ It's going to get regenerated automatically.

**Comment by jasonday** [comment]
Deleting the gantry directory under cache seemed to have done it. Thanks.
