### ISSUE TITLE
zoo 3.3.x have problem with gantry 5

### ISSUE THREAD

**Issue by mikajaxxx** [gantry/gantry5#797]
Hello my friends.
There is some problem on using zoo as CCK.
the zoo 3.2.4  works well with gantry 5. but zoo 3.3.x ( i checked the zoo 3.3.4 and 3.3.7) have no style on article page. in fact no template at all when i click on an article.
all versions of zoo works perfectly with gantry 4!

joomla 3.4.3
gantry 5.1.2
zoo 3.2.4 works fine but zoo 3.3.x doesn't works at all!

Best regards

**Comment by mahagr** [comment]
Try out going to admin and recompiling all CSS. You get unstyled page sometimes when memory runs out during CSS recompile (if it happens in frontend).

**Comment by mikajaxxx** [comment]
Hello 
tnx it solved my problem!

**Comment by VitoPalumboPodcast** [comment]
Hello. When I try to ask recompiling the CSS appears to me a white stripe on the Gantry component (on Joomla 3.6.0) and the recompiling fails. I already switched to php 7, or I have to increase the memory limit? https://drive.google.com/file/d/0B2GV_C16H1MtVUN3eHg5eml4VzA/view?usp=sharing

**Comment by mahagr** [comment]
@VitoPalumboPodcast Your issue is not related to this one. Besides the issue is already closed.
