### ISSUE TITLE
Gantry 5 > Custom Menu item type throw 404 error

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#798]
Version: dev-4ac9f726f / Released: September 4, 2015

![capture](https://cloud.githubusercontent.com/assets/9744973/9698788/9b583e38-53ce-11e5-9315-e0b096886517.PNG)

**Comment by mahagr** [comment]
Can you describe the issue a bit better -- how did you set up the page?

**Comment by adi8i** [comment]
Nothing fancy.
![capture](https://cloud.githubusercontent.com/assets/9744973/9710429/0cc1239e-5543-11e5-881b-1f832f94ca0e.PNG)
