### ISSUE TITLE
Applied Assignments/Overrides Particle

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#80]
I think that we should have an "Applied Overrides" or "Used Assignments" particle that whould show all of the assignments used on the particular page in order. The order is important here as it would show up which one has higher priority and that could ease up tracking on what's overriding what.

**Comment by mahagr** [comment]
Nice idea!

**Comment by newkind** [comment]
What would be even more awesome is a toggle in the admin that would allow you to turn on "Overrides Debug" mode which upon enabling would display borders and labels with override names around modules/particles showing the construction of page and what is being loaded and from where :)

Sample mockup :

![override_debug](https://cloud.githubusercontent.com/assets/1641534/7087040/6d7d25b6-df87-11e4-8cb2-17b3ac1d49e7.jpg)

**Comment by mahagr** [comment]
No frontend editing, though! I really dislike it, not sure why.

**Comment by newkind** [comment]
Yah, without editing - just for presentation :)



Dnia 10 kwi 2015 o godz. 14:42 Matias Griese <notifications@github.com> napisał(a):

**Comment by mahagr** [comment]
This feature doesn't really exist anymore as assignments were simplified for Gantry 5. Only single outline can be assigned to a given page and page specific particle assignments are dealt by positions (except in WP where its still missing).
