### ISSUE TITLE
Menu items missing from assignments in Chrome

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#800]
Please see two screenshots of the same Salient site in Chrome and Firefox. Gantry 5.1.2

The menu items are missing in Chrome. (if you have more menus they're missing from those too).

![2015-09-05_16-38-26](https://cloud.githubusercontent.com/assets/11683218/9700017/16580d7a-53ed-11e5-8580-17a3f8d2abea.png)

![2015-09-05_16-37-20](https://cloud.githubusercontent.com/assets/11683218/9700018/1bfac3da-53ed-11e5-859d-f9b6c99b7c53.png)

**Comment by adi8i** [comment]
Hey Mark, i seen this issue on my end too, few days ago, was another user having the same issue, i think @w00fz already fixed this, have you tried CI ?

**Comment by marktaylor46** [comment]
That was from member site. But yes CI does fix it so I'll close this issue. 

Thanks for pointing that out :)

**Comment by adi8i** [comment]
The issue is still there: http://screencast.com/t/cebjYhNS0

**Comment by marktaylor46** [comment]
Actually you're right now I checked again - it is better in CI, and looks fine until you start scrolling then it goes awry again ...
![2015-09-05_17-04-09](https://cloud.githubusercontent.com/assets/11683218/9700133/4d11a95e-53f0-11e5-8b38-326f575b0db5.png)
... so it does need another looksee by @w00fz

**Comment by adi8i** [comment]
Yes, sorry for confusion :).

**Comment by marktaylor46** [comment]
no worries - caught me out too since it looks ok with CI after first glance - it's only when you scroll it goes awry again.

Regards, Mark.

**Comment by mahagr** [comment]
Looks like rendering issue (or a bug) in Chrome.

**Comment by w00fz** [comment]
This is related to #781, you can read more about the Chrome issue in my comment (https://github.com/gantry/gantry5/issues/781#issuecomment-137544785).

I was able to workaround to yet this other scrollbar issue which unfortunately makes it a bit less optimized than I would like to, but until Chrome fixes it there isn't much else that I can do.
