### ISSUE TITLE
Arabic fonts don't take effect on front end

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#801]
Could you guys try this, looks like arabic fonts are loaded but are not displayed on front end.

**Comment by kat05** [comment]
Works fine for me, please see screenshot.
Do you have a detailed example of what is not working for you 
![g5_arabic](https://cloud.githubusercontent.com/assets/5719486/9716433/c1db5580-5569-11e5-8346-e4f84c8ee64a.png)
that I could try?

**Comment by w00fz** [comment]
This seems to be working fine for me as well. Have you sorted it out @adi8i ?
It could be a charset setting in your browser.

**Comment by adi8i** [comment]
I'll check the browser is still the same for me. Was another user reporting this one, that's why i've opened it.
![untitled](https://cloud.githubusercontent.com/assets/9744973/9722147/a297fc7c-55b0-11e5-8548-09964cef2868.png)

**Comment by w00fz** [comment]
Amiri is by default a `latin` charset font, you need to enable the arabic subset for that.

![amiri arabic subset](https://cloud.githubusercontent.com/assets/11734/9722187/5d9be168-555d-11e5-8c97-954137e81bd0.jpg)

Also there need to be arabic characters, it won't convert latin characters to arabic. 

This seems to be working fine for me:

![latin arabic](https://cloud.githubusercontent.com/assets/11734/9722196/84bfd8a8-555d-11e5-8518-52c0013d7f4b.jpg)

**Comment by adi8i** [comment]
Nop, is not that, i've also tried Noto, the arabic one, anyway, you can close it, if it's on my end.
