### ISSUE TITLE
Can't disable swipe gesture for offcanvas section

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#802]
I checked this out on latest CI build with Salient template (but it applies to all templates).

On the offcanvas section if you uncheck the "swipe gesture" field and save, then go to another outline, then return to the original outline and open offcanvas section settings again you will see that the "swipe gesture" field has been checked again, thereby making it impossible to disable the swipe gesture.

**Comment by mahagr** [comment]
I was able to reproduce this one. Checkbox doesn't send any data in POST if its inactive causing default value to be used.

**Comment by David2376** [comment]
Where is this setting stored at? I would like to manually turn off swipe gesture by hard coding the setting until this bug is fixed.

**Comment by w00fz** [comment]
This is fixed now, you can install the latest `CI Build` to get the patch. Otherwise you will have to manually edit the `YAML` files that are stored in your `custom/` folder and force the swipe gesture option to `0` in there.
