### ISSUE TITLE
SCSS Compiler issue: White page if compiler gets interrupted

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#805]
Hey guys,

As the title says, there seems to be an issue with the SCSS compiler in G 5.1.2.
I just reproduced it with the following setup:

- default Joomla 3.4.3 installation
- default G 5.1.2 
- default Hydrogen 5.1.2

Steps to reproduce:

1. Open any of the SCSS files in ../g5_hydrogen/scss/hydrogen folder and modify something so the recompilation will be triggered. For example, open the `_nav.scss` and add the `background: #000000 !important;` code.

2. Now, hard refresh the website by holding the CTRL key and hitting the F5 button 3-4 times in a row. If you just hold the the CTRL key and hit F5 once the issue will not be reproduced.

3. Notice that the recompilation is interrupted and the website is loaded without any styling.

4. If you now hit F5 once (or just refresh the page no matter how) the SCSS will be recompiled successfully.

Here, have a look at this video, it explains everything.

http://youtu.be/3U2bZsOvXGk

This issue is not reproducible G 5.1.0.

**Comment by mahagr** [comment]
It was supposed to be an optimization, but looks like I didn't consider interruptions.

**Comment by mahagr** [comment]
Also Later versions of SCSS compiler seems to run out of memory sometimes.

**Comment by mahagr** [comment]
The bug was actually worse than just CSS affecting all our configuration files as well.

**Comment by JoomFX** [comment]
Thanks @mahagr :)
