### ISSUE TITLE
title for Spacer .yaml

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#81]
I have added a Spacer to a section. It is "encoded" in the related .yaml file as follows:
```
title: "\n                                Spacer\n                            "
```
Please notice the \ns and spaces.

**Comment by w00fz** [comment]
Not sure what you mean?

**Comment by w00fz** [comment]
Wow, i realized what you meant now. Great find! That was actually causing another issue that I struggled figure out and now is solved!

Thank you.
