### ISSUE TITLE
Collapsed cards on the right are missing the chevron

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#811]
Not sure why but all collapsed cards on the right are missing chevrons - the ones on the left are fine. Might be position of icon.
![ethereal theme gantry5 wordpress wordpress 2015-09-09 09-51-54](https://cloud.githubusercontent.com/assets/1641534/9756200/8eaf8cb0-56d8-11e5-80c0-a5cc7f2cb62d.jpg)

**Comment by newkind** [comment]
Looks like this is a Chrome issue only ;/ Freaking Chrome!

Also this - when you collapse card, refresh and uncollapse the input fields are invisible until clicked on.

![ethereal theme gantry5 wordpress wordpress 2015-09-09 09-59-40](https://cloud.githubusercontent.com/assets/1641534/9756320/8fd19e52-56d9-11e5-8285-06f45a025045.jpg)

**Comment by kevlardev** [comment]
Ya this is more Chrome rendering issues that seem to be the result of chrome's extremely buggy css column implementation. Its been getting worse with each release

**Comment by mahagr** [comment]
It's a bug in Chrome, likely to be fixed soon.
