### ISSUE TITLE
Popups for first items are being cut at the top

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#812]
![ethereal theme gantry5 wordpress wordpress 2015-09-09 09-52-07](https://cloud.githubusercontent.com/assets/1641534/9756248/f9e9d0da-56d8-11e5-897f-afe952cde772.jpg)

**Comment by kevlardev** [comment]
Ya this is a rendering issue in Chrome that is the result of the css column implementation, i've been trying to find a way to fix it but not had any luck.

**Comment by mahagr** [comment]
It's a bug in Chrome, likely to be fixed soon.
