### ISSUE TITLE
WordPress - add Gantry 4 layouts

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#815]
In Joomla we have added some layouts for Gantry 4, I think these might be very useful to have in WordPress too. Possibly also core WordPress themes layouts, such as the Beez and Protostar layouts we have for Joomla.

![g5_wp_gantry4](https://cloud.githubusercontent.com/assets/5719486/9765323/fa4734e2-5713-11e5-8abe-b225e46bf6cb.png)

**Comment by newkind** [comment]
There's really no point to it because in G4 we used the machanism of overrides which isn't present in the G5. This means that even if we would recreate the layouts from G4 only the widgets from the default override would get moved, and that's not the point in this case.

**Comment by w00fz** [comment]
I think another reason is that in Joomla, at its essence, there are module positions. With those presets you are able to restore a G4 setup into G5 easily, although this is not the case with Wordpress, so aside from having a shortcut to a previous template layout, nothing else really gets added by those.

We can see how the Wordpress users react to it, if it's something they really want or feel like they are missing, we can always add them.

**Comment by newkind** [comment]
Yah, although this would really mean some major workaround especially that when you go in the Widgets pages and WordPress detects that there are some positions missing, it's going to move all of the widgets from missing positions to the "Inactive Widgets" section and users would have to place them again manually. Anyways we might think later about some kind of import later.
