### ISSUE TITLE
Suggestions for Assignments

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#82]
I have 134 menus and 533 Level 1 menu items in my multi-language site. It counts to 1500+ with sub-menu items.
**First off** Assignments page took a few minutes to load.
**Secondly** if the loaded layout is for English language, for example, you have to select en-GB tagged menu items one-by-one from those 533. Therefore there should be a select/unselect toggle near to every menu title as it is in Joomla's module menu assignment tab.
**Third**, current **menu item** select/unselect toggle might be practical for mobile devices but it is not for mouse/touchpad enabled desktops. Checkbox would be appropriate for desktop views.
**Fourth**, Assignments page cover too much desktop space. I understand it is for the sake of mobile view but it would be in the format of Joomla's core module menu assignment page.

**Comment by w00fz** [comment]
Thanks for the suggestions. Like said in #71 and https://github.com/gantry/gantry5/issues/2#issuecomment-87098165, the assignments is something we have planned to rework and make much more intuitive and fast. We know that right now is just simply listing the menu items for Joomla but it's really all we needed for getting the beta up and running, so you could assign configurations to menu items.

There is a huge room for improvements there and I guarantee you that it's our plan to make that happen.

I'll keep this open as reminder. Thanks!

**Comment by w00fz** [comment]
Portion of this has been enhanced with 4c526eb. We still have some work to do with it but it's going to come up later on.

**Comment by w00fz** [comment]
I think for now this is all we are going to have for Assignments. In the future, probably when we are going to approach Wordpress, we will revisit Assignments.
