### ISSUE TITLE
ID at the end of the file (?55f15f04) causing an issue with lightbox plugin (and probably others)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#821]
Hey guys, me again :))

I have a lightbox plugin that opens an image in a popup window.
Here's my code:

```
<a href="{{ url(item.image) }}" lightbox-attr title=""><img alt="{{ item.alt }}" src="{{ url(item.image) }}"></a>
```

This code works fine - the image is loaded on the frontend and when I click on it the popup window opens but the image in the popup cannot be loaded.

I hunted down the issue and it turned out that the image in the popup (lightbox) cannot be loaded because of the custom ID number G5 appends to the end of the filename, here's what I mean:

```
/templates/g5_hydrogen/custom/images/project1.jpg?55f15f04
```

I'm talking about the `?55f15f04` part.
So, I was wondering what can be done about it? In Chrome Inspect Element, as soon as I deleted this ID from the end of the filename, the image loaded perfectly fine in the popup/lightbox window.

You add this ID so you know if/when the file has been modified. But do we really need to add this to image files as well? Isn't it better to add this ID to the code files only (SCSS, YAML, Twig...)?

Or maybe you can give me another solution/workaround so I can tell G5 not to put the ID on this particular file. Is there something like:

```
<a href="{{ url(item.image.NO_ID) }}" lightbox-attr title=""><img alt="{{ item.alt }}" src="{{ url(item.image) }}"></a>
```

Thanks, as usual ;)

**Comment by mahagr** [comment]
Use third parameter of the function in latest CI build:

    {{ url(item.image, false, 0) }}

It disables the timestamps in the file URLs. Second parameter is for appending domain name, btw.

**Comment by JoomFX** [comment]
You rock Matias!
Thanks a million :+1: ;)
