### ISSUE TITLE
WordPress - login particle added to menu not fully working

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#823]
I've added a login particle via the menu editor.

It shows fine on frontend but when logging it, it does not change it's 'state' to show that you're actually logged in.

A login added via the Layout Manager works fine.

![g5_wp_logininmenu](https://cloud.githubusercontent.com/assets/5719486/9815905/c4e5f90a-5899-11e5-8271-f024e00978b8.png)

**Comment by newkind** [comment]
Confirmed. @mahagr we added support for the Context and Timber to particles, but not for particles in the Menu. The issue above appears because the Login Form particle doesn't have access to Timber and Context
