### ISSUE TITLE
WordPress - Widget Position Particle List Widget Positions DropDown

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#826]
We should have a DropDown in Widget Position Particle that Will List us all of the current Widget positions that are available in Widgets! This would be good so users don't misspell the position or so they don't have to go to widgets to see what is there etc ...

![2015-09-14 01 26 57](https://cloud.githubusercontent.com/assets/10489911/9839608/dc221f44-5a7f-11e5-935b-44c701069da4.jpg)

**Comment by newkind** [comment]
Well widget position particle creates a position so i think that misspelling argument here doesn't matter, although I agree that we should check if widget position with the same key already exists - @mahagr

**Comment by mahagr** [comment]
As @newkind suggested, the field is for creating a position, not assigning existing one.
