### ISSUE TITLE
Favicon management

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#83]
There are intentions to implement the favicon management in backend ? To give users posibility to upload their own and to replace the default joomla favicon.

**Comment by mahagr** [comment]
There hasn't been any plans to add this feature, but its a good idea.

**Comment by gospelpowered** [comment]
This can probably be merged with #264 and #265 or removed as those implement the favicon.

**Comment by w00fz** [comment]
Merged in @gospelpowered , thank you!

**Comment by gospelpowered** [comment]
Awesome, thanks guys

**Comment by essiele** [comment]
That would be **very** cool!
