### ISSUE TITLE
META atom required

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#830]
Many members in forum are asking how to add meta tags to the HEAD section in Gantry 5 templates. So I think it would be beneficial if we created a "META" atom that would give people the ability to add meta tag lines to the head section. Why? because they need to add things like:

    <meta name="apple-itunes-app" content="app-id=999999999">

I believe this should be in Gantry 5 core as it is a very common requirement.

**Comment by w00fz** [comment]
This is part of the Page Settings new features we are planning. 

https://github.com/gantry/gantry5/wiki/Gantry-5-Agenda,-Exploration-and-Time-Travel

**Comment by mahagr** [comment]
Which is why I added it to the milestone. :)

**Comment by mariantanase** [comment]
To change from HTML 4.01 to HTML5, I use this code :

`$doc = JFactory::getDocument();`
`$doc->setHtml5(true);`

I don't know if it's better to use a particle or to inject the code directly into the template.
Sorry if this is not related with the issue.

**Comment by marktaylor46** [comment]
@mariantanase it's not related to this issue that I can see. This is about how to add additional meta tags and other content to the HEAD section in the rendered html produced by Gantry 5 via Gantry 5 admin pages without having to touch code. But thanks for trying to help.

**Comment by w00fz** [comment]
FYI development process has started for this one. More details and code can be found in the [page-settings](https://github.com/gantry/gantry5/tree/feature/page-settings) feature I started.
