### ISSUE TITLE
Gantry 5.1.2 Won't Install on Clean Wordpress 4.3

### ISSUE THREAD

**Issue by bluestyler** [gantry/gantry5#833]
Hi, I've followed the installation instructions properly (from gantry.org for Wordpress) but when I tried to activate the Hydrogen theme, I get a blank screen! I've installed it on a clean and freshly installed Wordpress site. I'm quite surprised by this issue.

The wait icon spins for a while and then disappears. Essentially it crashes Wordpress because I cannot get to the pages with the browser. I have to change the theme directory name to get Wordpress back again. 

Does anyone know how to resolve this matter? Thank you all in advance :-)

**Comment by mahagr** [comment]
Do you have PHP 5.2 or 5.3 in your server?

**Comment by bluestyler** [comment]
Yes, v5.3. This should not be happening. I've tried many other Themes and Framework on my clean test platform with no problems, except two: Gantry and Motopress. Any other suggestions would be appreciated. Cheers all :-)

**Comment by mahagr** [comment]
Not sure why it fails still, as it should just display error that PHP 5.3 isn't supported. Minimum required PHP version is 5.4 (which is also unsupported now), so you're better to upgrade to PHP 5.5 or later.

Nevertheless, I will look if there's still some PHP 5.4 code in main files that need to be removed.

**Comment by w00fz** [comment]
Thank you.
The fatal errors are now fixed, short syntax for arrays were used before the actual PHP incompatibility error would display, for both Gantry and Hydrogen.

This is what you will get now when you try to activate Hydrogen:

![g5_wp_errors](https://cloud.githubusercontent.com/assets/11734/10011953/09a73232-60b7-11e5-8e8f-df02a4828b63.jpg)

Bottom line is you still need to upgrade your PHP, I highly suggest to upgrade to 5.6, aside from the incompatibility of 5.3 with Gantry 5, PHP 5.3 has reached the end of life over a year ago.

Thanks for opening the issue and reporting the bug!
