### ISSUE TITLE
Modules/Widgets/Particles in menu can throw 400 Bad Request

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#837]
This happens in both Joomla and Wordpress alike.

Jakub's way to replicate:

1. take root menu item that has no children
2. place widget and select Meta
3. hit save changes
4. refresh front end
5. refresh backend
6. try to enter the Meta widget like you'd like to add some children to it
so basicaly the same thing
with extra reloading and saving

My way:
I added a text widget to the first level, gave it a title and hit apply. then clicked on it to give it a 2nd level and got the error
looks like it disappeared too, the 1st level widget i had added

![sh1zs6ef3jpsac9xmkw73ei53fkkkt](https://cloud.githubusercontent.com/assets/5719486/9878200/cab0559e-5bc1-11e5-82fa-295878ddd61c.png)

**Comment by mahagr** [comment]
This issue is caused by implementing #832

**Comment by mahagr** [comment]
It looks like that particles / widgets / modules that were just added do not have path defined.

**Comment by mahagr** [comment]
@w00fz I need to know the location of the particle in order to return correct link.

**Comment by mahagr** [comment]
I added test to prevent broken link from appearing, so I can at least remove important tag.

@w00fz Inside JS we need to avoid highlighting these new items which do not have link in them.

Feature now works only when menu is saved, otherwise clicking to menu item opens its settings.
