### ISSUE TITLE
Menu items missing after upgrading to Gantry 5.1.3

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#843]
After upgrading to 5.1.3 many users have reported of missing menu items.

**Comment by mahagr** [comment]
It looks like that deleting menu yaml file fixes the issue.

**Comment by DanGthatRokGallery** [comment]
There is some info on this issue here ->http://www.rockettheme.com/forum/joomla-template-ambrosia/247896-gantry-5-1-3-update-killed-main-menu-items

**Comment by marktaylor46** [comment]
This is another member with same issue 
http://www.rockettheme.com/forum/joomla-template-callisto/247899-menu-items-disappear-after-upgrading-to-gantry-5-1-3?start=0#1235523

I will suggest your fix...

**Comment by marktaylor46** [comment]
Another member with same issue - I've suggested workaround 
http://www.rockettheme.com/forum/joomla-template-ethereal/247932-menu-disappearing?start=0#1235566

**Comment by marktaylor46** [comment]
Just adding link to forum members with this issue so I can track and inform them when fixed
http://www.rockettheme.com/forum/joomla-template-salient/247906-main-menu-misbehaving-please-help?start=0#1235693

**Comment by marktaylor46** [comment]
Another forum link that may help with diagnosis - I have asked for zip of existing file
http://www.rockettheme.com/forum/joomla-template-requiem/247955-it-does-not-work-a-portion-of-the-main-menu?start=0#1235706

**Comment by marktaylor46** [comment]
I'm making it clearer for the benefit of other people reading this issue that the file to delete is
/template/rt_templatename/custom/config/menu/mainmenu.yaml

where "templatename" is the name of your template

**Comment by rgblogs** [comment]
I also have similar problem and I know why it is happening.

https://github.com/gantry/gantry5/issues/850

**Comment by marktaylor46** [comment]
Another member asking about this here:
http://www.rockettheme.com/forum/gantry5-for-joomla/247979-menus-menu-items-gantry-5-1-3-menu-editor?start=0#1235828
