### ISSUE TITLE
WordPress - Ability to Duplicate Base in Outlines

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#846]
It would be good if we could have a button to duplicate base layout... for example someone sets all the layout in the base and would like to use it on other outlines this currently isn't possible ...

**Comment by mahagr** [comment]
Duplicating base in general isn't good idea, but this one does make sense as we base layout breaks the rule.

**Comment by newkind** [comment]
First of all I think that we should solve this case #848

**Comment by mahagr** [comment]
Looks like #848 is closed already.
