### ISSUE TITLE
Wordpress:  How do I set a site-wide html module/widget ??

### ISSUE THREAD

**Issue by n8115** [gantry/gantry5#848]
Hi!

I'm setting up a website using Gantry5 on wordpress, and can't  figure out how to set 2 - 50% width (particles I guess they're called? widget?) with HTML code in them, in the header position on all pages.

I first created a layout called "Homepage" attached to the homepage and have filled out the normal content areas, but now that I'm trying to set up sub-pages, I can't find a way to set up global header "modules" that will auto display on every page...

I remember with G4 I was able to set those on the "default" layout, which would then fill those used positions on all new pages, but adding particles to the "Base Outline" only seems to display those particles on pages that don't have another layout attached to them.  

Couldn't find anything in the documentation that outlines how to do this, am I missing something?

**Comment by mahagr** [comment]
Unfortunately right now it's not possible to reuse parts of the base layout.

We have plans to implement this feature for Gantry 5.2. Please look at issue #340. 

There is also another related issue #160, which would allow you to assign widgets more freely to different pages without needing to use another outline.

Please be free to continue discussion and your ideas on how to implement these features in the above issues; I'm closing this one as duplicate.
