### ISSUE TITLE
Adding dropdown width in Menu breaks the menu

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#850]
Hi

If I add dropdown width (like 350px) in menu item, then all menu items after that disappears from the front end.

**Comment by marktaylor46** [comment]
I don't think that's the issue here - it's the 5.1.3 Gantry update that has cause the issue and the ticket for that is #843 . There is a workaround documented in that ticket and you can also regress to Gantry 5.1.2 for now too.

**Comment by adi8i** [comment]
I can confirm this issue. If the width is anything else than `auto` the upcoming items will not show. In a way it is related to #843. I am not too sure why this happen, i've tried to track the bug, but need to wait for devs.

**Comment by rgblogs** [comment]
I have not upgraded Gantry. i am developing new website on 5.1.3 with Joomla 3.4.4.

**Comment by marktaylor46** [comment]
Gantry 5.1.3 is the latest version - that is the version that has the issue within it.
