### ISSUE TITLE
Outline Menu Dropdown widths ignored with Gantry 5 CI-a8c370d38

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#852]
Set the Simple Dropdown width in an Outlines menu editor and the width is ignored on page output.
Place the defined width in Base Outline and it works.

See http://www.rockettheme.com/forum/joomla-template-ambrosia/247896-gantry-5-1-3-update-killed-main-menu-items?start=10#1235952

**Comment by mahagr** [comment]
Looks like that the code was already broken and when I tried to fix it, it caused multiple other issues.

This is the code before my attempts to fix it:

```twig
    {%- if (item.width|default('auto') != 'auto') and not (root.getDropdown() == 'fullwidth' and item.level > 1) -%}
```
As `root` is always null, it became:

```twig
    {%- if (item.width|default('auto') != 'auto') and not (null == 'fullwidth' and item.level > 1) -%}
```

I need some help on what was the original idea here, as the code is still broken after my "fix" from above.

**Comment by mahagr** [comment]
Restored the intended functionality.
