### ISSUE TITLE
Offcanvas Menu in Mobile Devices

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#858]
In Hydrogen theme, I have Menu in Navigation section, and nothing else. Mobile menu is in offcanvas section. Header section is also empty. In this scenario, menu doesn't appear in mobile devices at offcanvas.

Now, if I publish anything in header or navigation section (other than menu), then it works. But I do not want to keep anything there and still want mobile menu.

**Comment by w00fz** [comment]
I am not able to reproduce this issue with latest 5.1.4 of both Gantry and Hydrogen.
This is what I have..

Admin:
![8 2015-09-21 11-01-48](https://cloud.githubusercontent.com/assets/11734/10000317/3b67f3ae-6050-11e5-9e86-75ef2c2c8474.jpg)


Frontend:
![home 2015-09-21 11-02-50](https://cloud.githubusercontent.com/assets/11734/10000332/5210d9ea-6050-11e5-927e-e325c61721c7.jpg)

Anything else I'm missing here? Also I assume you are talking about Joomla platform?

**Comment by w00fz** [comment]
@rgblogs do you have anything in Showcase or does your Home start with all white background? Like this:

![home 2015-09-21 12-03-15](https://cloud.githubusercontent.com/assets/11734/10001874/c8eb7a72-6058-11e5-9fd0-762da65931a5.jpg)

If that's the case, this is not an issue, the offcanvas toggle is there but it's white on white so you need to adjust the colors of it. You can do so by going into `Home Outline -> Styles Tab -> Offcanvas Section -> Toggle Color` and change white to something more contrasty :smile:

**Comment by rgblogs** [comment]
Yes, it is white with white background, so gets invisible. 

Issue resolved by changing toggle color :)
Thanks

**Comment by w00fz** [comment]
Glad it's all sorted!

**Comment by maplemoxie** [comment]
I swear I am running into the same white fa-bars on a white background... but changing the toggle color does nothing for me?  I've tried changing the background color - (temporarily) deleting my logo - custom CSS to change the color of the icon... to no avail.  Any other creative ideas? :)

**Comment by maplemoxie** [comment]
Nothing quite like confessing your struggles in public to get the creative juices flowing... z-Index!!! All better now...
