### ISSUE TITLE
Issue With Adding and Deleting Particles

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#86]
- Try to add a custom html particle, then without changing anything, drag to delete it. 
- The deleted particle still appears
- Click "Save Layout"
- The custom html particle duplicates itself now

Please see screencast here:
https://s3.amazonaws.com/uploads.hipchat.com/6986/14295/eVp1Ek5f89kxI57/screencast%202015-04-14%2019-24-57.mp4

**Comment by adi8i** [comment]
Ehe, you have the latest beta :dancers:

**Comment by w00fz** [comment]
This was a non-issue. Was already fixed in the merged branch
