### ISSUE TITLE
Custom font in navigation

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#860]
Hi, I've added a custom font to be used for navigation items. I followed [this guide](http://docs.gantry.org/gantry5/tutorials/fonts) to add the `bebas` font. But it seems that the menu items that contained the child items are different
![menu](https://cloud.githubusercontent.com/assets/3976174/10013276/43fb6f94-6110-11e5-99db-61f9a84af829.png)

**Comment by w00fz** [comment]
Did you customize the CSS to target the whole Menu?

**Comment by mariantanase** [comment]
A little
    #g-navigation{
        font-size:1.2rem;}

**Comment by w00fz** [comment]
So can you explain the steps you followed? I know you said you followed the tutorial but I'm just trying to understand if anything is missing.

I see the top level menu items inherit the font, so I assume you have added a class of the type:

```
#g-navigation .g-toplevel { font-family: Yourfont; }
``` 

Is that correct?

**Comment by mariantanase** [comment]
Not properly, maybe I miss something. Let me explain what I've done:
1. Upload my font on `custom\fonts\bebas_neue_regular` (all 4 extensions .eot .svg .ttf and .woff)
2. On my `custom.scss` I've added:
```
@import "vendor/bourbon/bourbon";
@include font-face('bebas_neue_regular', 'gantry-theme://fonts/bebas_neue_regular');
```
P.S. At this step I don't understand why import bourbon.
3. At the same `custom.scss` I've created a class:
    `.font-family-bebas {font-family: 'bebas_neue_regular', helvetica, sans-serif;}`

4.Now, turn back on layout manager, on navigation section > Menu particle options > Block tab > On CSS classes I added `font-family-bebas` class
Recompile and that's it.

**Comment by w00fz** [comment]
Hey Marian,
this seems to be working fine for me, I followed your exact same steps with a different font and it loaded fine on frontend. I'm going to write down my steps here, perhaps you can see something different that you did or did not do.

This is what I have (I used a font called 1942-report).

Firstly I downloaded the [Webfont Kit](http://www.fontsquirrel.com/fonts/1942-report).

Then I unzipped and copied the 4 font files in `custom/fonts/1942/`.

![folder_structure](https://cloud.githubusercontent.com/assets/11734/10079180/7cbd6c90-629d-11e5-9295-0f3fa20f1b8c.jpg)


I then edited the `custom/scss/custom.scss` and added this:
```sass
@import "vendor/bourbon/bourbon";
@include font-face('1942', 'gantry-theme://fonts/1942/1942-webfont');

.font-family-1942 {
    font-family: '1942', helvetica, sans-serif;
}
```

Went in Layout of Home and added `font-family-1942` in the class field for the Menu particle.

Finally in the Styles tab I recompiled the CSS and on frontend I got this:

![frontend](https://cloud.githubusercontent.com/assets/11734/10079167/67fa4e36-629d-11e5-8c6b-2c07ed1943a2.jpg)

---
Can you see anything different than what you did? If not, perhaps there is some CSS rule that is overriding yours, have you tried with `!important` ?

```sass
.font-family-bebas { font-family: 'bebas_neue_regular', helvetica, sans-serif !important; }
```

I don't see anything wrong on what you did.

**Comment by mariantanase** [comment]
Hi Djamil,
It seems that is a problem with the font `bebas` used. I've changed with another one `opensans condensed bold` and it looks fine.
So, I decide to use this new one, which is similar to `bebas` font.
Thanks

**Comment by w00fz** [comment]
Well that is strange. Glad you managed to sort it out.
