### ISSUE TITLE
Image picker gives "NS_ERROR_ILLEGAL_VALUE"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#865]
@w00fz Please see http://www.rockettheme.com/forum/joomla-template-salient/248185-gantry-5-image-select-dialog-box-issue?start=0#1237088 - all admin details therein.

When using the image picker from any outline on any folder you get "NS_ERROR_ILLEGAL_VALUE" thrown in console. Seems to be something to do with ajax calls and callbacks.

Gantry 5.1.4, Salient 1.0.2 Joomla 3.4.4

I have been unable to reproduce this error locally. But it's easily reproducible on member site.

**Comment by mahagr** [comment]
@w00fz Encoding issue again?

**Comment by w00fz** [comment]
No this is different and seems to be happening only on that site.
