### ISSUE TITLE
Newly cloned Outline should not have any assignments

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#866]
If you clone outline, new outline will currently get all the assignments from the old one. This should not happen.

**Comment by SHGraphics** [comment]
Although, I could see instances where this may be useful. Perhaps add a switch to allow user the choice of inheriting assignments?

**Comment by mahagr** [comment]
Maybe in the future. For now I still prefer new Outline being not used until you assign it.

**Comment by kat05** [comment]
I can confirm that this works fine in both Joomla and WP with latest CI.
There are no assignments on duplicated outlines.
