### ISSUE TITLE
Block Size 66.6 

### ISSUE THREAD

**Issue by Chrissi2812** [gantry/gantry5#868]
I want to have the sidebar the same width as the blocks in the mainbottom section. 
![image](https://cloud.githubusercontent.com/assets/6141652/10049907/fe10c000-6219-11e5-8971-ec7dc9b3a7cf.png)

But there is no class 66-7 or 66-6, so i gave the content block a class with this name but then i can't save the block because of the 66.7% size.
And when i change it to 66 the sidebar changes it's size too.
![image](https://cloud.githubusercontent.com/assets/6141652/10050151/33cd4ea6-621b-11e5-9eed-cccec03f76a3.png)

it works when i first give the content section the class and a width of 66% or whatever and then give the sidebar a width of 33.3%. But that feels quite complicated.

**Comment by adi8i** [comment]
Maybe Devs have other approach or a better idea, but for now, the easiest way i can think at, is to assign a class on `container`. Set mainbody to 67% and sidebar to 33% (you can chose any other values, but target them in css too).

![1](https://cloud.githubusercontent.com/assets/9744973/10052774/3aac8e2e-6231-11e5-926e-2eb19ce66206.PNG)

Then you can add the following code in `custom/scss/custom.scss`

```
@import "dependencies";

@include breakpoint(desktop-only) {
    .custom-size {
        .size-67 {
            flex: 66.7%;
            width: 66.7%;
        }
    
        .size-33 {
            flex: 33.3%;
            width: 33.3%;
        }
    }
}
```

**Comment by w00fz** [comment]
We don't technically support decimals on sizes, the only cases where you get decimals is when a grid is equalized. So if you drop 3 particles in an empty row, you will get `33.3 | 33.3 | 33.3`, if you remove one, you will get `66.7 | 33.3` and so on.

The moment you start dragging to resize, you will loose the decimal, you can always equalize through the equalize button that you get on the far right when hovering a grid:

![equalizer](https://cloud.githubusercontent.com/assets/11734/10056380/b26d5a02-61ef-11e5-8e44-12a70204a90a.jpg)

With all that said, what you want to do is to simply start dragging the blocks so they loose the decimals, making it easier to control the same size aspect, and you will end up with something like this:

![same](https://cloud.githubusercontent.com/assets/11734/10056472/3846e076-61f0-11e5-802a-6e8c08a71e41.jpg)

**Comment by Chrissi2812** [comment]
I think i will go with the approach of adi8i, it really seems the easiest way.

**Comment by adi8i** [comment]
Booth approaches can be easily achieved. Anyway @w00fz 's idea is a clean one, because you can have it done in layout manager, without any code. I meant strictly 33.3 size, but 1% is not a big deal, will not be visible on front end, so you can have 34 - 33 -33 with no problems.

**Comment by Chrissi2812** [comment]
The problem with @w00fz 's approach is that my images on the main-bottom-blocks use a 50% padding-top for their height. 
![image](https://cloud.githubusercontent.com/assets/6141652/10068321/d61841e2-62a3-11e5-870d-da9051b8e0cf.png)
But this "problem" is solved for me :+1:

**Comment by w00fz** [comment]
Glad to hear!

**Comment by mahagr** [comment]
The reason why we do not support decimals in grid is the amount of CSS required to support it. The biggest issue really is IE9/Android support as if we could easily make the grid better if we could get rid of those two browsers.

**Comment by uglyeoin** [comment]
I came here with the same problem.  I noticed that you support 

```
.size-33-3 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 33.3333333333%; -moz-flex: 0 33.3333333333%; -ms-flex: 0 33.3333333333%; flex: 0 33.3333333333%; width: 33.3333333333%; max-width: 33.3333333333%; }
.size-16-7 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 16.6666666667%; -moz-flex: 0 16.6666666667%; -ms-flex: 0 16.6666666667%; flex: 0 16.6666666667%; width: 16.6666666667%; max-width: 16.6666666667%; }
.size-14-3 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 14.2857142857%; -moz-flex: 0 14.2857142857%; -ms-flex: 0 14.2857142857%; flex: 0 14.2857142857%; width: 14.2857142857%; max-width: 14.2857142857%; }
.size-12-5 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 12.5%; -moz-flex: 0 12.5%; -ms-flex: 0 12.5%; flex: 0 12.5%; width: 12.5%; max-width: 12.5%; }
.size-11-1 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 11.1111111111%; -moz-flex: 0 11.1111111111%; -ms-flex: 0 11.1111111111%; flex: 0 11.1111111111%; width: 11.1111111111%; max-width: 11.1111111111%; }
.size-9-1 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 9.0909090909%; -moz-flex: 0 9.0909090909%; -ms-flex: 0 9.0909090909%; flex: 0 9.0909090909%; width: 9.0909090909%; max-width: 9.0909090909%; }
.size-8-3 { -webkit-box-flex: 0; -moz-box-flex: 0; box-flex: 0; -webkit-flex: 0 8.3333333333%; -moz-flex: 0 8.3333333333%; -ms-flex: 0 8.3333333333%; flex: 0 8.3333333333%; width: 8.3333333333%; max-width: 8.3333333333%; }
```
In nucleus but not 66.6 for some reason.  Any reason you supported some but not all?  If we're converting from a Bootstrap grid we need at least 12 of these classes.

**Comment by mahagr** [comment]
@uglyeoin Can you create a new issue out of this, maybe even pull request to add those sizes?

**Comment by uglyeoin** [comment]
@mahagr sure, I'd be happy to
