### ISSUE TITLE
Caching Mechanism

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#87]
Cache folder of a fresh Joomla installation (w/o any content) currently contains 110 files under 108 folders.
They are all G5-related php files with php blocks inside, exposing a lot of things. 
  - Will caching work this way?
  - Will you offer Rokbooster-like compression?

**Comment by Omegatcu** [comment]
Caching is not really done yet - @rhukster mentioned it will be implemented at a later point which makes sense.

The files you see now are also good for debug and to see how things can be improved. 
Let them built in all features and enhancements and then I'm sure they will have a solution for the cache as well.

**Comment by w00fz** [comment]
Right now the only cache happening is for the twig templates and yaml files. We aren't hooking up, as of yet, to the platform cache but it's something that is certainly on our todo list. 
We haven't discussed yet any plan for integrating RokBooster into Gantry, but you can still use RokBooster along side with Gantry 5, the two are compatible.

**Comment by mahagr** [comment]
Regarding to the amount of cached files, we are compiling both template files and configuration files into PHP classes / arrays to speed up things considerably. So basically each of those files has source file somewhere.

I'm not sure what exposing means. And yes, this is how caching is going to work at least for the template files as the template files are always compiled to PHP code.

**Comment by mahagr** [comment]
Rokbooster is verified to fully work with G5. :)

**Comment by w00fz** [comment]
All questions were answered here so I'm going to close this now. :)
