### ISSUE TITLE
G5 Particle Module does not have a "Module Class Suffix" field

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#871]
@mahagr @w00fz Hi guys,

First of all, sorry if this has already been reported. I searched but couldn't find anything.

The "Gantry5 Particle Module" does not have a "Module Class Suffix" field which is crucial for any Joomla module. 

I build my G5 templates mostly with the "G5 Particle Module" and I do rely heavily on the "Module Class Suffix" in order to be able to apply different styles/variation of a particular module/particle.

Also, if you just want to `text-align:center;` the title of a G5 Particle Module you are stuck.

I do believe that you just forgot about it :) Have a look at the screenshot below... the first one is from a "Custom HTML Module" and the second one from "G5 Particle Module":

![alt](http://i.imgur.com/vI3nRbn.png)

![alt](http://i.imgur.com/3VWr1TY.png)

P.S. You can build your particles so you can add a custom class there but this is not the point here.

**Comment by w00fz** [comment]
There's been a discussion regarding module suffixes in #857 which might give you a few answers as well as letting you know where we stand with it right now.

**Comment by JoomFX** [comment]
Hi @w00fz ,

I read https://github.com/gantry/gantry5/issues/857 couple of days ago but I read it again now carefully so I make sure I understand everything and do not miss something important (as I did last time :) ).

Well, the other issue is about variations (mostly). Here I'm talking about module class suffix that the user can add to the "G5 Particle Module" and then apply custom styling only to this particular instance.

I really hope that you just didn't understand me the first time, because removing the "Module Class Suffix" field from the "G5 Particle **Module**" intentionally, sounds like a madness to me. Honestly...

I'm talking about the Module Class Suffix that each and every module in Joomla has. The default Joomla modules, RokSprocket and any 3rd party module.

I'm talking about the module class suffix (the class) that renders next to the `moduletable` class:

```
<div class="moduletable ">
```

It is just the "**Module** Class Suffix" fields that is missing in the G5 Particle **Module**, I believe that the rest of the functionality is already there, meaning if you add the field where the user can add the suffix it will be rendered on the frontend.

Djamil, the G5 Particle module is a "**module**" and therefore it must have a **module** class suffix.

I will stop for now and see what your reply will be.

Mate, honestly I cannot build my templates without having the "Module Class Suffix" functionality in the G5 Particle modules.

**Comment by JoomFX** [comment]
Please don't make me assign classes to blocks and/or module positions or instances from the Layout Manager. And assigning a class from the Layout Manager is not the same as assigning a class from the module.

No, no... I really hope that you just missed my point. It just cannot be true that you have removed the module class suffix intentionally from the G5 Particle Module.

**Comment by w00fz** [comment]
Sorry, I red:
> I build my G5 templates mostly with the "G5 Particle Module" and I do rely heavily on the "Module Class Suffix" in order to be able to apply different styles/variation of a particular module/particle.

and put together **Module Class Suffix** with **styles/variation** and automatically made the connection with that other issue. I didn't realize from your screenshots that the field is actually missing. 

It should be there, I'm investigating.

**Comment by JoomFX** [comment]
Pfff, I was really worried about this Djamil :)
Thanks a lot! Now I can "breathе" again ;)

**Comment by w00fz** [comment]
I can tell you were worried! :smile: 
I am asking to the rest of the team if there was any particular reason for that not to be there or if we just completely missed it.

**Comment by JoomFX** [comment]
Hehehe :smile: 

But now I'm starting to worry again. What if the rest of the team say that there is a reason for it to be missing :scream:

**Comment by w00fz** [comment]
Sorry @JoomFX, we cannot add it back :sob: 






... Just kidding, I just pushed it.

**Comment by JoomFX** [comment]
You'll give me a heart attack with this jokes :smile: 

Thanks Djamil ;)
