### ISSUE TITLE
Front-end modals

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#872]
This is an issue I think should be considered.

I think it would be very useful to have native gantry support for simple modals. Nothing fancy or complicated, no fancy effects or extra bells and whistles.

This will come in very handy for such things as the login particle https://github.com/gantry/gantry5/issues/841

Right now, implementing the particle will be somewhat limited in functionality in that it will depend on a 3rd party modal implementation (for example, Bootstrap Modals, NoNumber's Modals, or RokBox). If the user does not have (or doesn't know how to use) these, they will generate a lot of potential support tickets.

Having a native modal capability in Gantry would allow adding a simple checkbox "Open in modal" to a particle such as this to open the target content in a modal. Not checking that would open the content in a page.

**Comment by w00fz** [comment]
I think this is something that should be coming from the particle itself. A modal implementation, no matter how simple it is, requires quite some JavaScript and CSS, which if provided built-in with Gantry will also impose that every template guarantees it's proper display and functionality. Coming with Gantry will also force people to use that modal even though someone else might prefer a different one.

This also seems like a very specific case scenario and it is totally possible to achieve via custom particles, I would hate to add the overhead in Gantry for a functionality that would quite probably be used very little.

**Comment by alisamii** [comment]
I disagree with closing this issue or labelling this as a question.

Modal support is already available in the backend of Gantry, and this is a request to extend that support to the front-end.

As regards your comment:

> Coming with Gantry will also force people to use that modal even though someone else might prefer a different one.

By defining a way to set "render content in a modal" from within a particle, it can be implemented in a no-conflict manner by adding some form of specificity such as

```
<button type="button" class="btn btn-primary btn-lg" data-toggle="g-modal" data-target="#myModal">
  Launch demo modal
</button>
```

This would then call a `g-modal` script.

As regards your other comment:

> A modal implementation, no matter how simple it is, requires quite some JavaScript and CSS

I would say it should be possible to create an atom that is available on install but by default is not enabled. The atom could then load the necessary JS and CSS.

This could be accomplished best when there is a global configuration such that you can set default atoms in the base layout (which is currently no longer available pending further progress on the roadmap). The idea would be the same as a global google analytics atom or any other custom atom one could enable to set to load on all layouts.

Please reconsider opening this issue...as I believe it has been closed with prejudice.

**Comment by mahagr** [comment]
Our modal was designed to use only in admin and requires huge amount of JS in order to work. It wouldn't even work as it is in frontend and for example in Joomla has already a lot more integrated modal in Bootstrap, which you can easily call from a particle. Actually we just added support for `{{ joomla.html(...) }}` allowing you to easily load any boostrap element.

If I was doing the theme for Joomla, I would use Bootstrap modal without any second thought just not to force the page to load yet another framework just for a modal.
