### ISSUE TITLE
TWIG - Request Current Url

### ISSUE THREAD

**Issue by Design-ADCD** [gantry/gantry5#875]
Hello! I would like to have a Twig code that could retrieve the current Url. This would enable me to create a particle that could add &blabla after ?filter. It would be very useful. Thank you!

**Comment by w00fz** [comment]
Thanks for opening the ticket. I tried to look if we had something already and I couldn't. There is `base_url_relative` but only points to the root. We might probably want to extend `site.` or add a `base_url_current` or something like that.

Unless we already have it and I completely missed it :smile: 

/cc @mahagr

**Comment by mahagr** [comment]
In Joomla by using latest CI build you can do something like this:

```twig
{% set current_url = joomla.call('JURI::current') %}
```

**Comment by Design-ADCD** [comment]
Interesting! Thank you very much! Unfortunately I can't use the Cl build, so I'll wait for the next release! But, may I ask, if I would want to make a link take me to the complete current url "{% set current_url = joomla.call('JUri::current') %}" plus a certain sting attached to the end, lets say: "&bla", how would I do it?

Thank you!

**Comment by mahagr** [comment]
I think it returns JUri instance, so you can just do the normal function calls to modify it.

**Comment by w00fz** [comment]
Shouldn't we just provide a `base_url_current` so that it's easily available from any platform via twig?

**Comment by mahagr** [comment]
I would rather avoid using hardcoded variables in context as they get copied to every twig file, which may have some effect on performance and memory usage. But we could provide simple call, like `{{ gantry.platform.currentUrl() }}` or maybe like `{{ gantry.page.current() }}` for this and other most common usages.
