### ISSUE TITLE
IE 9 Problem

### ISSUE THREAD

**Issue by innitek** [gantry/gantry5#877]
in IE8/9/10 admin panel is not showing properly and when I open my project on IE9 the rows and columns I hide with the class of hidden.large not working even when I use the class in my scss to display none. I don't have this problem with other browers and sometimes font-size looks good in all browers but It looks defferent in IE11 it's bigger size a bit.

**Comment by adi8i** [comment]
Please read http://docs.gantry.org/gantry5/basics/system-requirements#browser-requirements
Gantry 5 have higher requirements, and i see this a good point. Things needs to go forward, we can't stick to IE 8/9/10, that are outdated.

**Comment by mahagr** [comment]
IE9 is only partially supported and it cannot look the same as IE10+ because of missing CSS support. Nobody should be using IE9 in admin anyway, not to even mention IE8.

IE10 should be fully supported, though.
