### ISSUE TITLE
WordPress - Atom Head Section

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#878]
I tested this on the latest build dev-54e8fd0cf and Atoms seems to not be working in the head section, css and js dont work in there ...., if i thick Before ```</body>``` the javascript works in there ...

this is working fine in Version: 5.1.4 so its the latest build that is broken

**Comment by mahagr** [comment]
I have troubles of understanding what is broken here.

Also not sure what you mean by inserting before; you can already prioritize CSS and JS, which will determine its order.
