### ISSUE TITLE
Fixed menu (or section)

### ISSUE THREAD

**Issue by gyvermac** [gantry/gantry5#88]
I know it's not really a Gantry5 fonction but I think it'll be a good idea to easily have a fixed menu (header/section) may be on a new version of Hydrogen template...

**Comment by sural98** [comment]
As far as menu, logo and search resides on the same row all G5 templates can be designed as fixed-menu built-in regardless of the template features.
+1 for this option.

**Comment by mariantanase** [comment]
Good idea, and a +1 for usability !

**Comment by gyvermac** [comment]
the idea could be to be able to "fixe" at least one section (now, all the sections are in a page_layout include in  <div id="g-page-surround"> witch make it difficult to fixe easily

**Comment by Omegatcu** [comment]
+1 as well from me - it doesn't harm the framework to have this out of the box.

**Comment by w00fz** [comment]
We'll discuss this for a later beta or eventually for after release. There are several implications that come with it, performance and usability wise.  Thanks for the feedbacks.

**Comment by kevlardev** [comment]
This is something that will be added on a theme by theme basis, as its very dependent on the overall design and functionality of a particular theme. Gantry doesnt really include visual features like this "by default" as all the major visual items and functionality are driven by the theme (in this case Hydrogen). Having a fixed menu bar/section is something we will include in coming themes, and something that can be added by developers as needed. But for the sake of simplicity, we aren't planning to add it in the Hydrogen theme.
