### ISSUE TITLE
Gantry 5 Particle widget callback causes issues with other plugins that modify widget callback

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#880]
Gantry 5 Particle widget callback causes issues with other plugins that modify widget callback ie. RokBox : 

https://monosnap.com/file/9ZAkvYhlyILtfU70998d4ch4ySsijW.png

also I was getting this error :
```
Whoops\Exception\ErrorException thrown with message "Unsupported operand types"

Stacktrace:
#0  in /Gantry5/Framework/src/platforms/wordpress/WordPress/Widget/Particle.php:72
```
and when I debuged that line the `$instance = null` which also shouldn't happen.

**Comment by mahagr** [comment]
I guess that call without instance is possible. So I am now just handling `$instance = null` by displaying no content.
