### ISSUE TITLE
how to adjust the same height of product in woocommerce shop page?

### ISSUE THREAD

**Issue by queenstar** [gantry/gantry5#882]
Hi i have a problem that the shop page product images and height could not be the same height as in http://www.queenstarhair.com/index.php/shop

I have modified the functions.php but could not work well. All I need is to let the each product in my shop page lines in the same height despite of the titles. Hope you could help me, thanks!

**Comment by queenstar** [comment]
Here is the sample image of my problem.
![sample-1](https://cloud.githubusercontent.com/assets/14246570/10153519/a3a83fc4-668f-11e5-84bf-9a4fc8571be0.png)

**Comment by newkind** [comment]
Hi,

Can you please swithc the theme to Gantry 5 one so I could see the issue ?

Thanks

**Comment by queenstar** [comment]
Hi,

I have solved this problem through a professional staff.
Thanks a lot!

2015-09-29 16:02 GMT+08:00 NewKind <notifications@github.com>:

**Comment by newkind** [comment]
Ok :) Glad that it's solved!
