### ISSUE TITLE
WordPress - Content Override in Duplicate Outline

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#883]
I am trying to disable the overrides in content tab in my duplicate outline, i chose those overrides in the first outline and then i duplicated it now i want to disable them in duplicate one but they are not responding they are always on... tested with latest Build

![2015-09-30 00 43 31](https://cloud.githubusercontent.com/assets/10489911/10180354/9d988bde-670c-11e5-930d-acbbe0ad3557.jpg)

**Comment by mahagr** [comment]
I believe this is duplicate to issue #929?

**Comment by w00fz** [comment]
Oh yah sorry @mahagr I told you I didn't fix this but I misinterpreted the issue with another. Yes this is the same issue I believe.
