### ISSUE TITLE
`gantry.theme.joomla` not returning true in Joomla

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#885]
The `gantry.theme.joomla` is not returning true anymore within the Joomla environment causing issues with the load of head assets such as `bootstrap-gantry.css` and other assets.

https://github.com/gantry/gantry5/blob/develop/engines/joomla/nucleus/twig/partials/page_head.html.twig#L12

**Comment by mahagr** [comment]
Main content was rendered only after the header, which caused this issue. Fortunately we do not need that anymore for WP as we changed the implementation.

**Comment by w00fz** [comment]
Looks like this is still an issue.
@under24 reported that with a G5 custom menu item (Home), in 5.1.4 the `bootstrap-gantry.css`, now with the latest CI Build and after this fix, it doesn't anymore.
