### ISSUE TITLE
Tag attributes aren't rendered in CSS/JS Atom, even though they're there

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#888]
Tag attributes aren't rendered in CSS/JS Atom, even though they're there. Somethings stripping them on render, because they're there before rendering happens.

![ambrosia theme gantry5 wordpress wordpress 2015-10-01 17-03-46](https://cloud.githubusercontent.com/assets/1641534/10224499/91979aac-685e-11e5-8aa6-2fbac7561de7.jpg)

**Comment by w00fz** [comment]
The problem is WP doesn't allow to pass attributes via `wp_enqueue_script`. So they aren't stripped out, they are just never rendered.

**Comment by mahagr** [comment]
Joomla and Grav do support this, so should we just hide the options in WP?

**Comment by newkind** [comment]
I don't think we should hide this at all, but we should make it work like it should ie. using this method http://matthewhorne.me/add-defer-async-attributes-to-wordpress-scripts/

**Comment by mahagr** [comment]
That method should work, but it is really a hack and ugly way to do it. Will look into it when I find some time.

**Comment by newkind** [comment]
Yah, str_replace is not a very good way to do this, but until recently (before WP 4.1) there was even no such filter to make this happen, so in my opinion we should take what we have and make best out of it, until a better solution appears.

**Comment by w00fz** [comment]
Also we aren't limiting to async/defer. We have key/value that can be anything, so we need to be able to pass those as well, ie `id => my-custom-js`

**Comment by newkind** [comment]
yah, async and defer was just an example - we should allow everything that's possible to use

**Comment by joomlabeat** [comment]
I am just having this issue on Joomla:

i m in base outline -> global page settings and want to call google responsive ads script as a custom js atom <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> - but I cant seem to be successful with the async attr.

**Comment by w00fz** [comment]
You probably want to add that in the head section at the top rather than using an atom. Although it should work.

Can you attach a screenshot of it?

**Comment by joomlabeat** [comment]
![screen shot 2017-02-17 at 21 06 35](https://cloud.githubusercontent.com/assets/6756053/23079352/3e8abb34-f555-11e6-8d7c-bdf8de3fc4ed.jpg)
![screen shot 2017-02-17 at 21 07 09](https://cloud.githubusercontent.com/assets/6756053/23079351/3e87ebca-f555-11e6-8e42-30a8b56e8932.jpg)

**Comment by impressionestudio** [comment]
I have the same problem with the tag attributes in Joomla.
