### ISSUE TITLE
Configuration Selector Changes Height after Particle Menu Item Placed

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#89]
![screen shot 2015-04-17 at 1 48 13 pm](https://cloud.githubusercontent.com/assets/4026828/7208759/9f1f205c-e508-11e4-9da7-9a60e65255b7.png)

**Comment by w00fz** [comment]
Thanks, this is sorted now.

![tweaked-selectize](https://cloud.githubusercontent.com/assets/11734/7244541/e257c280-e791-11e4-84ec-373d50fae03d.jpg)
