### ISSUE TITLE
WordPress - Yoast SEO Plugin Description Meta Bug

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#892]
When Yoast SEO is installed the site has 2 meta name descriptions one from the theme and other from Yoast ...

![2015-10-03 23 42 07](https://cloud.githubusercontent.com/assets/10489911/10265237/7b18ee22-6a28-11e5-9196-45db878e54e1.jpg)

**Comment by newkind** [comment]
Fixed in 6eb079b
