### ISSUE TITLE
Compatibility issue with updateCSS function

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#893]
Fatal error: Declaration of Gantry\Component\Theme\ThemeTrait::updateCss(array $configurations = NULL) must be compatible with Gantry\Component\Theme\ThemeInterface::updateCss() in ../wordpress/wp-content/plugins/gantry5/src/classes/Gantry/Framework/Base/Theme.php on line 47

**Comment by mahagr** [comment]
User has old version, we already fixed this for 5.1.5...
