### ISSUE TITLE
WordPress - Hydrogen Home outline is gone in Gantry 5.1.5

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#895]
First mentioned by Alessandrowp on Gitter.

In Wordpress, the Hydrogen - Home outline is no longer available in version 5.1.5.

**Comment by newkind** [comment]
There is no Home outline in Hydrogen, there's a Home layout preset, that can be loaded into a created outline.

**Comment by kat05** [comment]
There is a Hydrogen - Home outline in Joomla, please see pic

![g5_hydrogen-home](https://cloud.githubusercontent.com/assets/5719486/10279736/50aafa04-6b68-11e5-9148-7b352651ecf3.png)

**Comment by mahagr** [comment]
I don't think that WP ever had Home outline..?

**Comment by mahagr** [comment]
For those who installed Hydrogen theme, you can create home outline yourself:

* Go to Outlines tab (on top row)
* Create new outline and rename it to Home
* Edit outline
* In Layout tab Load preset named Home, but first uncheck the checkbox on the modal. Then Save
* In Assigments tab check Page Context > Front Page and hit Save

After this your home page will be using the Home outline.

**Comment by joshmans** [comment]
I'm looking for this to have pre-defined content to help learn how everything works... setting up the home outline as described above doesn't give that pre-defined content in WP.

**Comment by newkind** [comment]
@joshmans I'm not sure if i'll follow you - the steps that @mahagr gave you are exactly the steps i'll be making to include home outline in the next version of Hydrogen (WP) and this is how it's done in Joomla too. What exactly are you looking for ?

**Comment by joshmans** [comment]
@newkind well in the install video there's a bunch of pre-loaded content on the 'home' outline.. that does not exist when i just created it on my WP installation.

**Comment by newkind** [comment]
@joshmans you mean particles that have been in place and configured ? If you'll follow @mahagr steps you'll get exactly what's in the video.

**Comment by joshmans** [comment]
@newkind I did.. and I don't.

**Comment by newkind** [comment]
@joshmans I have added default configuration for Home outline to latest CI build of Hydrogen - can you try it ? :)

**Comment by joshmans** [comment]
![image](https://cloud.githubusercontent.com/assets/16343132/11901442/488851d0-a571-11e5-898e-09174dcd1acf.png)

**Comment by newkind** [comment]
Ok, now that's very weird! Can you confirm that under hydrogen/layouts/ you have default.yaml file ?

https://monosnap.com/file/wF2P1AX2w32HNY1nUPmyxqI8b74jgP.png

**Comment by joshmans** [comment]
Is layouts in it's own directory within hydrogen or is it a sub-directory of one of the others? I don't have any layout directory.

**Comment by newkind** [comment]
Inside of the Hydrogen you should have a "layouts" directory and inside of that directory couple yaml files ie. default.yaml, home.yaml

In example full path : wp-content/themes/hydrogen/layouts/default.yaml

If you don't have such directory or it's empty, then it means that the package is either wrongly linked or wrongly uploaded. I'd suggest to download it as a zip from the url below and re-upload it.

Hydrogen CI build : https://gantry5.s3.amazonaws.com/nightly/wordpress-tpl_g5_hydrogen_develop.zip

**Comment by joshmans** [comment]
that worked perfectly. thank you! Not sure what was wrong that caused the layouts to not be there at all.

**Comment by newkind** [comment]
I assume that maybe it was a direct github link which required additional "common" directory to be linked. Anyways, I'm glad that it's working fine :)
