### ISSUE TITLE
Inputs and Textarea fields color are white when in the Menu

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#896]
I am adding login module in navigation bar. Everything is working fine.

But since text color of menu is white, when user enters username or password, it is not visible since this text also becomes white on white background input.

**Comment by mahagr** [comment]
@kevlardev It looks like this is very common issue for people. I believe its Hydrogen again.

**Comment by rgblogs** [comment]
yes H2

**Comment by rgblogs** [comment]
but what is solution?

**Comment by w00fz** [comment]
This is resolved now. You can easily fix it yourself by just adding the following simple rule in the `custom.scss` file:

```sass
.g-menu-item-container input, .g-menu-item-container textarea {
    color: #666;
}
```
