### ISSUE TITLE
Issue with a layout with both left and right sidebars

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#899]
Hey @w00fz ,

This is probably for you :smile: 
And sorry if it has been discussed already.

I have a quite annoying issue with my layout. It might be normal for you, but in my opinion this should not be like that.

So, I have a layout with both left and right sidebars. Here it is:

```
  container:
    1:
      - sidebar 30:
        - position-sidebar-left
      - mainbody 40:
        - [position-content-top-a 50,position-content-top-b 50]
        - pagecontent
        - [position-content-bottom-a 50,position-content-bottom-b 50]
      - aside 30:
        - position-sidebar-right
```

So, I would expect that:

1. If there is only one sidebar active (modules published in `sidebar-right` only), the right sidebar would be 30% and the "MainBody" would become 70.
2. If both sidebars (left and right) are active, the layout would be as in the YAML code above - both sidebars 30% and the "MainBody" 40%.

With the current behavior, if only one sidebar is active, it is 43% and "MainBody" is 57%. 

Could you please discuss this with the rest of the team and probably put a higher priority/more weight on the sidebars in the LM so they always take their percentage and the MainBody adjust according them?

Please, please Djamil, can you discuss it with the others?

And yes, the current issue can be worked around if the user has a Layout with one sidebar only, but having a "universal" layout is just priceless.

Thank you in advance :smile:

**Comment by JoomFX** [comment]
Or probably you can add an option that will force the percentage for particular element?

For example, add an option in Left Sidebar, MainBody and Right Sidebar that will say something like "Force Percentage" or "Force Width" so it will take the width/percentage that is shown in the LM.

**Comment by mariantanase** [comment]
Hi @JoomFX ,
On section settings from the active sidebar, on **Block** tab, did you checked **Fixed Size** ?

**Comment by JoomFX** [comment]
Hey @mariantanase 

Yep, this is exactly what I needed :smile: 
Thanks a lot mate ;)

@w00fz I feel a bit ashamed :relaxed: 
The "Fixed Size" option is exactly what I wanted to be added :smile:

**Comment by w00fz** [comment]
Aha no problem at all. Glad to see we had you covered already!
Thanks @mariantanase for the help.
