### ISSUE TITLE
Menu Particle not in the Navigation sections - Overlay z-index issue

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#9]
I don't know if it is a bug or it is by design, but if you move the Menu Particle in another section (not in the default Navigation section) the Overlay that appears when you click on the button to expand the dropdown menu has a higher z-index and the Menu Items become not clickable.

The `.g-nav-overlay` class have a z-index=1.
If the Menu Particle is in the Navigation section (as it is by default) the issue is not present because the `#g-navigation` id has a z-inder=2.

![menuoverlay](https://cloud.githubusercontent.com/assets/7753940/6881584/92f3a12c-d56d-11e4-96c1-4aeef3d7d9e4.png)

**Comment by kevlardev** [comment]
The menu with overlay effect is intended to be used at the top of the page in the navigation and/or header section (navigation section is optimal) but the header was missing the appropriate z-index. I've expanded the higher zindex to include the header section in addition to the navigation section.
