### ISSUE TITLE
Font awesome icons do not appear properly in the mobile/tablet menu.

### ISSUE THREAD

**Issue by Divaksh** [gantry/gantry5#900]
Font awesome icons works fine in normal big menu but on responsive menu they do not appear properly the vertical alignment is not proper. 
![20151006234440](https://cloud.githubusercontent.com/assets/3404831/10337178/a20012fe-6d1b-11e5-8c22-9bbfd870d632.jpg)

**Comment by w00fz** [comment]
Is this happening only on Android or can you reproduce it on desktop as well?

**Comment by adi8i** [comment]
That's vertical align, this will happen in a simple custom html too, that's font awesome ;)

**Comment by Divaksh** [comment]
If you notice they are not even aligned on desktop too. Same issue can be seen in iOS too.

![screenshot_20151010164036](https://cloud.githubusercontent.com/assets/3404831/10410871/af2ee24e-6f6d-11e5-887b-ea4e0a4866fb.png)

**Comment by adi8i** [comment]
One of the problems is the icon height, you can keep the same width by adding `fa-fw` but you can't control the height, different icons have different heights, you will see what i mean, if you try to create a round button.

**Comment by mahagr** [comment]
Not sure if this is an issue or just feature on Font awesome..?

**Comment by w00fz** [comment]
I think they are actually aligned, just some icons are taller than others. Fontawesome fixes this for width with `fa-fw` but doesn't have, afaik, anything for height.

I would add some custom.css to take care of them individually, it looks like just a few pixels misalignment for some of them.

Unfortunately this is not something we can control from within Gantry.
