### ISSUE TITLE
Utility class .equal-height breaks width settings when applied to modules.

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#902]
Create at least 2 different modules in Joomla with varying content.  At least one of them should have only a few words per line or a very small image that is not very wide.

Create module instances, one for each module and pick the modules you just created in Joomla.

In order to see the issue you should add either `box1` `box2` `box3` `box4` to the module otherwise the problem won't be visible.

Now add the new Utility Variation `equal-height` to the modules.  You will be able to see that the width of the module is reduced to meet the widest point created by the content.

![equal height 01](https://cloud.githubusercontent.com/assets/12389693/10370926/acca930c-6de9-11e5-80e0-6a474c0e420f.png)
![equal height 02](https://cloud.githubusercontent.com/assets/12389693/10370931/b3c8505e-6de9-11e5-9d9c-88536158f35c.png)

**Comment by hennysmafter** [comment]
Alright a solution for this is to add the following css to your custom.scss file:

```css
.equal-height .g-content {
    display: block;
    width: 100%;
}
```

Please everyone feel free to test this code and if you know a better one or see problems let us know. Meanwhile @kevlardev could you check if it is possible to add this to the standard scss files from Gantry.

**Comment by w00fz** [comment]
Good catch, thanks.

**Comment by N8Solutions** [comment]
Great!  Thank you Djamil!
