### ISSUE TITLE
Menu items disappearing from menu editor - but reinstated after menu rebuild

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#903]
Please see this topic in RT forum which has admin details.
http://www.rockettheme.com/forum/joomla-template-ambrosia/246851-main-menu-woes?start=10#1241146

Please follow the instruction therein.
1. go into menu editor and just save menu.
2. then go to any other G5 admin page and then return to menu editor
3. menu items will have disappeared?
4. to reinstate them go to joomla menu manager and click "rebuild"
5. now return to menu editor and then menu items will have returned.

**Comment by mahagr** [comment]
Has been fixed, yay!

**Comment by marktaylor46** [comment]
Yes, I can't reproduce any longer.
