### ISSUE TITLE
Embed shortcode doesn't work in Custom HTML particle

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#905]
Embed shortcode doesn't work in Custom HTML particle

```
[embed width="123" height="456"]http://www.youtube.com/watch?v=dQw4w9WgXcQ[/embed]
```

**Comment by Matt-Yorkley** [comment]
I've successfully used other (non-youtube) embedded shortcodes in the custom HTML particle on Wordpress and they worked fine...

**Comment by mahagr** [comment]
It looks like that [embed] is not handled as a shortcode (shortcode just gets removed), but its a filter in `the_content`.

See https://core.trac.wordpress.org/browser/tags/4.4/src/wp-includes/class-wp-embed.php

**Comment by mahagr** [comment]
It looks like the feature isn't supported in widgets either, so I cannot see any reason why we should add support for `[embed]` in particles. Its only meant to work with main content (posts).
