### ISSUE TITLE
Modify Copyright particle to allow links

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#906]
Links are very standard in the copyright line of websites. For example: © 2015 Cable News Network. Turner Broadcasting System, Inc. All Rights Reserved. contains a link.

Change Copyright particle to allow links, presumably by not escaping html (easiest). I don't really see how  adding link fields will work, as people could use links in a multitude of ways in this particle.

**Comment by JoomFX** [comment]
Just use the "Branding" particle instead of "Copyright" and add your HTML there. For example:

```
© 2015 Cable News Network. <a href="http://companywebsite.com">Turner Broadcasting System, Inc</a>. All Rights Reserved.
```

**Comment by topwebs** [comment]
The Copyright particle has some nice coding for the copyright years which isn't in the Branding particle.

**Comment by JoomFX** [comment]
Here's what you need to do:

1. Create a file called `copyright.html.twig` in `root/templates/g5_hydrogen/custom/engine/particles`. Yes, you need to create the `engine` directory and then create `particles` in it.
2. Paste the following code there:

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% set start_date = particle.date.start|trim in ['now', ''] ? 'now'|date('Y') : particle.date.start|e %}
{% set end_date = particle.date.end|trim in ['now', ''] ? 'now'|date('Y') : particle.date.end|e %}

{% block particle %}
Copyright &copy;
{% if (start_date != end_date) %}{{ start_date|e }} - {% endif %}
{{ end_date|e }}
{{ gantry.platform.filter(particle.owner)|html|raw }}
{% endblock %}

```

3. Use as much HTML in the "Copyright owner" field as you want.

I just tested the above and it works just fine.

I suppose the next thing you will say is that you do not want to override the default particle file - my answer is that this file will never change.

**Comment by JoomFX** [comment]
Or if @adi8i wants he can submit a PR for this.
Just replacing:

```
{{ particle.owner|e }}
```

With this:

```
{{ gantry.platform.filter(particle.owner)|html|raw }}
```

So the HTML will be processed in the "Copyright owner" field.

**Comment by adi8i** [comment]
I think copyright particle is fine like it is now, if everyone will come and ask to modify the files for their own needs, will result in a mess.

We add that and tomorrow will come another user that will ask to remove `html` filter, and so on.

You explained in detail how to create the override, it's a 2 mins job.

**Comment by JoomFX** [comment]
I agree with you @adi8i

**Comment by topwebs** [comment]
The standard particles should work for how most people build websites and in this case format copyright lines. You code the particles for the most common usage and overrides are for the lesser common usage. In fact, in this case, with my pull request, people can use or not choose to use html in the particle, so all bases are covered. 

I've spent a couple of hours now arguing this case and generated the pull request to save some people, including myself, having to do an override for every website we build. and to save many more who do not know how to do an override from being frustrated. Just merge the request.

**Comment by adi8i** [comment]
Overrides are overrides, particles are particles. You can create your own particles, in `custom/particles`  folder. The only thing you have to do is to rename the files to something else.

**Comment by mahagr** [comment]
Actually users cannot choose to use HTML after the change, they can only choose if shortcodes (plugins) are allowed to see the content. I think we need also option to disable HTML itself `|html|raw` regardless of if user wants to process short codes.

**Comment by mahagr** [comment]
There is pull request #908 for this one.

**Comment by w00fz** [comment]
PR #908 merged in. Thank you!
