### ISSUE TITLE
Not possible to apply box1 - box4 classes to modules published to module positions

### ISSUE THREAD

**Issue by gruz** [gantry/gantry5#911]
It is not  possible to use box1, box2 etc. classes per module when it's published to a module position.
I can see this is applied only per module position. But I want different modules in the same position to have different appearance. 

The module output in Hydrogen doesn't have needed classes g-content in it's HTML structure.

Here is what I mean using a screenshot
http://view.xscreenshot.com/834446fc637477898346407a24f522e1

I think it's a step backward that it's not possible to apply predefined styles to modules.

**Comment by rgblogs** [comment]
Read here: #857 ... A long story!
