### ISSUE TITLE
Language special character not rendered correctly

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#914]
I found this in requiem but believe it might be a g5 issue.

In the promo content particle (that use jquery to give typewriter effect) if you use special character then those characters are not rendered correctly for example if you put this word: "ønsker" in the description test it renders as "Ã¸nsker". If you put exactly the same text as the button text then that does render correctly. I check database colation and font and they both support the character. In fact you can change the string in firebug and it will render correctly.

Seems to be some issue with the jquery/Gantry 5

![2015-10-16_11-23-58](https://cloud.githubusercontent.com/assets/11683218/10539718/8b565506-73f9-11e5-926b-6920eccc4af7.png)

Forum issues are:
http://www.rockettheme.com/forum/joomla-template-requiem/249224-wrong-font-after-upgrade?start=0#1242939
http://www.rockettheme.com/forum/joomla-template-requiem/249313-problem-with-promo-content-charset

**Comment by mahagr** [comment]
This is likely template issue, but I'm not 100% sure, so I'll leave this open for now.

The issue is that something is parsing/filtering the above text and is not obeying UTF8 encoding while doing that. Its likely that issue might be coming from search and replace or regular expression.

**Comment by marktaylor46** [comment]
Ok let me know if I need to raise a JIRA instead.

**Comment by mahagr** [comment]
It looks like JavaScript typing the messages doesn't support UTF8 characters at all. It adds single characters which basically breaks those, which use more than once character, like öä. Not Gantry issue.

**Comment by mahagr** [comment]
@marktaylor46 Can you make another issue to JIRA?

**Comment by kat05** [comment]
just a note, it seems that non-latin characters are not supported.
https://github.com/mattboldt/typed.js/issues/80

**Comment by kat05** [comment]
Actually, it has worked just fine with the original requiem 1.0.0 release, see screenshot. 
There were changes to typewriter after that which have probably broken it.

Anyways, not a gantry issue, just wanted to leave the info here anyways. We'll look into those Requiem changes.

![requ_typewriterspanish](https://cloud.githubusercontent.com/assets/5719486/10963379/4f109096-83a0-11e5-8595-f586e312679d.png)
