### ISSUE TITLE
To Top allignment right

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#915]
How to set this

Im not clever editing css etc. files

Is there a simple way to do this in layout manager in the menue of the ToTop?

THX FOR HELP

**Comment by mariantanase** [comment]
Go to the settings of the **To Top** particle > **Block** tab > On the **Variations** field you need to add **Align Right** class.

**Comment by witzker** [comment]
GREAT THX

By the way wher can I get a list wit all classes and their function that can be used in that way for other serrings in gantry 5

**Comment by mariantanase** [comment]
When you click on the **Variation** field you will see a kind of drop-down with a list of all variation classes

**Comment by witzker** [comment]
OK Got it
in this menu there is a css class ToTop.
i meant a list with all CSS classes and their function that can be used in that way for other settings in gantry 5

**Comment by w00fz** [comment]
We have an issue open for that, see https://github.com/gantry/docs/issues/54 .
Until then, you can follow the link in that issue to see what is available.
