### ISSUE TITLE
Call to undefined method ...extendTwig()

### ISSUE THREAD

**Issue by tiptronic** [gantry/gantry5#916]
I just found grav and gantry5 and tried to install it. Everything seems to work fine (tried a couple of grav-themes), but I can't activate the Hydrogen theme. It immediately throws an error:

Whoops \ Exception \ ErrorException (E_ERROR)
HELP
Call to undefined method Grav\Theme\Hydrogen::extendTwig()

 /**
     * Initialize nucleus layout engine.
     */
    public function onTwigInitialized()
    {
        $env = $this->grav['twig'];
        $this->extendTwig($env->twig(), $env->loader());
    }

Since I guess this is not intended ;), what am I missing?

**Comment by newkind** [comment]
Everything :D Gantry 5 doesn't support Grav yet, although we have it in our plans. This should happen in the near future, but we cannot provide any ETA.

**Comment by tiptronic** [comment]
Hehe.... thanks for the hint...
So you're documentation is future-proof already :):
<pre>
'The new responsive Gantry 5 framework is developed for Joomla 3.4+, WordPress 4.2.2++, and Grav 1.0+.'
</pre>
;)

**Comment by newkind** [comment]
Exactly :D
