### ISSUE TITLE
Changing Colors in Menu

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#917]
As You can see in the picture the menu entry home has blue background when selected.

![gantry menue blau](https://cloud.githubusercontent.com/assets/4120266/10543246/a237c93e-741d-11e5-8504-8fece3767b25.png)

I want to change this to white, Home Font should be in Grey then.

I am not clever in editing CSS, etc. files, so I ask for a simple way to do this in template manager.

Many thanks for your help.

Regards
Witzker

**Comment by w00fz** [comment]
You can change that color from the `Styles` panel in Gantry Admin.

http://docs.gantry.org/gantry5/configure/styles
