### ISSUE TITLE
jQuery not loaded in the "Error" system outline

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#918]
Hey @mahagr ,

I believe this is for you :smile: 

So, G5/Hydrogen does not come with jQuery, it does not load it by default, but I've added `{{ joomla.html('jquery.framework') }}` in my `page_head.html.twig`:

```
    {% block head_platform %}
        {{ joomla.html('jquery.framework') }}
    {% endblock %}
```

But jQuery is not loaded on the Error Page. It is loaded just fine everywhere else, but not on the Error Page and I need it there because I have some things on the Error Pages that need jQuery.

I suppose that the Error Page doesn't call parent() - I've no idea what I'm talking about, just trying to look smart :smile: 

But it is strange, because in `{% block head_platform %}` I'm loading another asset and it loads fine on the Error Page, it is just jQuery (`{{ joomla.html('jquery.framework') }}`) that doesn't load.

**Comment by mahagr** [comment]
Joomla doesn't load JQuery in error pages. In fact it doesn't load any CSS or JavaScript -- those just get dropped out by Joomla itself. Also no content, plugin output or modules will work from error page.

Only thing that works from error page are the particles and atoms you use.

**Comment by JoomFX** [comment]
@mahagr Thanks for the explanation Matias.

But since G5 controls the whole layout or the Error Page, can't you enhance it somehow so `{{ joomla.html('jquery.framework') }}` actually loads jQuery on the Error Page?

I see the `wontfix` tag you added, but it really should be like that with G5 and I will try to explain why... With the default Joomla you cannot add anything to the Error Page, but with G5 you can add everything to the Error Page. That's why it makes perfect sense to be able to load jQuery on there. With the default Joomla, there is no Menu, no Modules, there is nothing on the Error Page, but with G5.... have a look at the commercial RT templates, at the Error Page - you have a menu there, what if the user adds a Particle or a module to the Menu, that requires jQuery? You also have a footer there, what if the user publishes a module that requires jQuery.

Please, can you reconsider this and probably enhance G5 so it loads jQuery on the error page - since G5 gives you the possibility to add Menu, Modules, Particles and other things on the Error Page, it should also give you the option to load jQuery there.

**Comment by mahagr** [comment]
None of the Joomla HTML functions adding JS or styles works from error page. Like I said, they are disabled by Joomla itself. You just cannot use JHtml class in error pages; the only way to load scripts is to load them manually (like you would have to do in any Joomla template).

I don't think its feasible to make `{{ joomla.html('jquery.framework') }}` to work as then people would ask the same question for every other Joomla HTML function because of someone may want to use tab, modal or even mootools (to name few) in their error page.

If you need to have any scripts or styles in error page, you would just need to do it manually. Remember that its unsafe to use any Joomla modules in error page anyway.. In fact I may want to disable them. :)

**Comment by JoomFX** [comment]
Ok, I see Matias. 
I just tried to load jQuery using an Atom, but it doesn't work.
I then, for test purpose, tried to load the Bootstrap JS from an Atom on the Error Page and it was also not loaded:

```
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
```

So, what do you mean by "load it manually"? I suppose using an Atom.

**Comment by JoomFX** [comment]
> Remember that its unsafe to use any Joomla modules in error page anyway.. In fact I may want to disable them. :)

Yep, but have a look at [Kraken's Error Page](http://demo.rockettheme.com/live/joomla/kraken/pages/error). The template provides the module positions, they are loaded on the Error Page, so if a user publishes a J! module in his Footer, and set it to be loaded on all pages, which is a normal practice for modules published in the Footer, they will also be loaded on the Error Page :)

**Comment by mahagr** [comment]
Yeah, might be that not even our JS loads in error pages. I've never really tried it out as I ran into this issue early in the development and just saw that error pages were handled in a different way to every other page.

**Comment by JoomFX** [comment]
Yeah, neither JS nor CSS loads on the Error Page when using an Atom.

But Matias, looking at the Error Page in the commercial RT templates, don't you agree that this is somehow incomplete? G5 allows the user to publish modules on the Error Page, actually depending on the configuration and with the current configuration (layouts) of the commercial RT templates, everything that is published on "On All Pages" will appear on the Error Page as well. So, it is quite possible that there will be some modules on the Error Page that require jQuery to function properly. As in my case, I have Social Icons, published on all pages, that have Tooltips, and the tooltips does not appear on the Error Page because they require jQuery.

I do, I really do understand everything you are saying, that this is how Joomla's Error Page works, but since G5 creates some new possibilities and scenarios, can't G5 be enhanced so `{{ joomla.html('jquery.framework') }}` loads jQuery on the Error Page as well. Or if this is 100% not possible because of the way Joomla works, can G5 loads Atoms on the Error Page at least?

**Comment by JoomFX** [comment]
Some enhancements should be possible since `{% block head_platform %}` loads my other JS asset on the Error Page.

**Comment by JoomFX** [comment]
Just to add something that might be helpful - in [Gantry 4](http://demo.gantry-framework.org/joomla/category-blogggg), Mootools is loaded on the Error Page, and in my [SativaFX](http://www.joomfx.com/demo/templates/sativafx/index.php/k2componentttt), jQuery is loaded on the Error Page.

**Comment by JoomFX** [comment]
Alright Matias, I spent good few hours on this :)
I completely understand you now :smile: 

But finally I managed to load jQuery (`JHtml::_('jquery.framework');`) in the default Joomla Error Page, not in the G5 override (`error.php`).

So here's what I did, I've not idea if my code is good or a total disaster and a security hole... I did it with trial and error and by looking the code in the G4 `error.php`. This is the code I added to `root/templates/system/error.php` (I renamed the `error.php` in Hydrogen):

```
JHtml::_('jquery.framework');

require_once(JPATH_LIBRARIES.'/joomla/document/html/renderer/head.php');
$header_renderer = new JDocumentRendererHead($doc);
$header_contents = $header_renderer->render(null);
```

Then I added the following in the `<head>` section:

```
<?php echo $header_contents; ?>
```

And voala... jQuery was loaded :smile: 

Now, the question is, how can I do the same with the Hydrogen's `error.php` where the `<head>` section is not being defined. And to be more precise - do you want to do it and merge it in G5/Hydrogen or you are totally pissed of by me and you find this request as ridiculous and it makes no sense to you ? :)

**Comment by JoomFX** [comment]
Alright Matias, I did it :)
But I did it in the ugliest possible way.

So, can you please have a look at the code below, and let me know how can we do it in a better way and if you want to implement this in Hydrogen officially. 

Basically, I defined `header_contents` in your `$context = array()` and then I load it as a Twig variable directly in `error.html.twig`, even though it should be loaded in `error_head.html.twig`.

And my dirty workaround has another side effect - it loads `<meta content...>` a second time because of `JDocumentRendererHead`.

So here is my `error.php`:

```
<?php
/**
 * @package   Gantry 5 Theme
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2015 RocketTheme, LLC
 * @license   GNU/GPLv2 and later
 *
 * http://www.gnu.org/licenses/gpl-2.0.html
 */

defined('_JEXEC') or die;

// Bootstrap Gantry framework or fail gracefully (inside included file).
$gantry = include __DIR__ . '/includes/gantry.php';

/** @var \Gantry\Framework\Theme $theme */
$theme = $gantry['theme'];

// Get language and direction
$doc             = JFactory::getDocument();
$app             = JFactory::getApplication();
$this->language  = $doc->language;
$this->direction = $doc->direction;

// Load jQuery
JHtml::_('jquery.framework');

require_once(JPATH_LIBRARIES.'/joomla/document/html/renderer/head.php');
$header_renderer = new JDocumentRendererHead($doc);

$context = array(
    'errorcode' => isset($this->error) ? $this->error->getCode() : null,
    'error' => isset($this->error) ? $this->error->getMessage() : null,
    'debug' => $app->get('debug_lang', '0') == '1' || $app->get('debug', '0') == '1',
    'backtrace' => $this->debug ? $this->renderBacktrace() : null,
    'header_contents' => $header_renderer->render(null)
);

// Reset used outline configuration.
unset($gantry['configuration']);

// Render the page.
echo $theme
    ->setLayout('_error')
    ->render('error.html.twig', $context);
```

And here is `error.html.twig`:

```
{% extends "partials/page.html.twig" %}

{% block page_head -%}
	{{ header_contents|raw }}
    {% include 'partials/error_head.html.twig' %}
{%- endblock %}

{% block content %}
    <h1>{{ errorcode|default(500) }} {{ error|default('Unknown Error') }}</h1>
    {{ backtrace|raw }}
{% endblock %}
```

Thanks ;)

**Comment by JoomFX** [comment]
And of course, my dirty workaround is absolutely unacceptable, but this is the maximum with my limited PHP knowledge, so I need your help here :)

The purpose of my *mess* is just to show that it is totally doable and in my opinion it should be done ;)

**Comment by mahagr** [comment]
Probably easier way would just to use the normal document instead of error one, but the main issue with both approaches is that Joomla may have been rendering all kinds of JS/CSS before the error occurs. The reason why head isn't rendered on error document is to "reset" everything into a known state.

To be honest, I'm still afraid to make this change as we do not know the original reason why Joomla does it. Remember that error page is not only used for 404 pages, it's also run after fatal errors in the code.

**Comment by JoomFX** [comment]
Ok, thanks Matias.

Well, I'm leaving this one for you and Djamil to decide how this should work and what implementation should and could be made. It will be really good if we can at least load Atoms on the Error Page, but I suppose this will require almost the same changes.

In the meantime I will just forward my customers to this issue so they can see why some things do not work properly on the Error Page :)

**Comment by mahagr** [comment]
Atoms should be showing up already, at least according to the code in https://github.com/gantry/gantry5/blob/develop/engines/joomla/nucleus/twig/partials/error_head.html.twig#L6-L7

**Comment by JoomFX** [comment]
Pfff....
Sorry Matias, you are right :)

I was on 5.1.5 and the Atoms were not loading on the Error Page.
On 5.1.6 they load perfectly fine!

Sorry once again :)
I believe nothing else should be done here, so feel free to close the issue ;)
