### ISSUE TITLE
Particle for vertical menue

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#919]
I have a particle menu and use it in a left modul position.
![vertical menue closed](https://cloud.githubusercontent.com/assets/4120266/10554203/da694f32-7461-11e5-86cc-beffda159c59.png)

the menu should look similar to joomla vertical menue
all submenues should be open and structured like this

Here is ITEM 1
     - Subitem1
      - Subitem2
Here is ITEM 2

Now it looks so when i open second item
![vertical menue open](https://cloud.githubusercontent.com/assets/4120266/10554282/5d772980-7462-11e5-86d8-9aba6ea2a392.png)

I have no Idea How to
PLEASE Help me

is there a particle for vertical Menu anywhere?

THX in advance
regards
Witzker

**Comment by w00fz** [comment]
We don't have a particle for vertical menu. From the look of it, it looks like you just need to fix some CSS. You can customize CSS via `custom.scss`, more details in [our documentation site](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet)
