### ISSUE TITLE
Particles that are turned "off" are rendering on the frontend.

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#92]
![dateparticle](https://cloud.githubusercontent.com/assets/4026828/7239077/b8d11d50-e76c-11e4-8a20-67d72de4ccb6.png)

When placing a particle in the Menu Editor, they appear on the frontend even when the little on/off switch is in the off position (saved)

**Comment by mahagr** [comment]
Should be fixed, reopen if you still see issue.
