### ISSUE TITLE
Ad icons from gantry in joomla menue

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#920]
Is this possible?
By the way can icons also be added in content title?
Or better where can ganty icons be added?
Lookin forward to description
Regards
Witzker

**Comment by w00fz** [comment]
You can add Icons from the Menu section in Gantry Admin. Once there you click on the gear icon of the Menu Item you want the icon added to and you select it.

![menu](https://cloud.githubusercontent.com/assets/11734/10562168/27c863f8-7502-11e5-9281-5db9a7b09072.jpg)

**Comment by witzker** [comment]
OK THX

Now it looks like this not very nice

![icon position](https://cloud.githubusercontent.com/assets/4120266/10564543/a1fded30-75b8-11e5-8402-768d9e74c33f.png)

icon Text
longicon Text

it should be like
ICON SPACE Text
mayby there is a position with where the icon is inside that fits the longest available icon and icon is centred inside this position
Then test stats in the same column
iconposition Text
iconposition Text

Im not clever editing CSS or other files
is there a simple way to do this or other solution with sane effect in backed.
can something be inserted in Menu CSS ect.
regards
Witzker

**Comment by JoomFX** [comment]
Try making your icons "Fixed Width". 
Make each icon, for each menu item, to be "Fixed Width".
When you click on the "Icon" field, and the window with all icons appear, you will see the "Fixed Width" checkbox.

**Comment by witzker** [comment]
WORKS GREAT THX !
Maybe you could help me also to lower the distance of the sections as in Picture

![webseite](https://github-cloud.s3.amazonaws.com/assets/4120266/10565615/34b2fc1c-75d5-11e5-99f4-98c457ac58dc.png)
All positions should be a shorter
I don't know where to put what to change distance
Red Yellow Green Blue
Could you be so nice to teach me how to lower the 4 distances hopefully as simple as before without editing CSS or other files only in in backed.
can something be inserted in Menu CSS ect.

UPS Do I have to start a new item with this?
Pls let me know and I will do immediately
Regards
Witzker

**Comment by w00fz** [comment]
That really requires some customized CSS which is hard to help you with without an URL to look at.
I suggest you have a look at how browsers inspector works (ie, https://developer.chrome.com/devtools).

That really is the best way for you to customize the template as you wish

**Comment by witzker** [comment]
can i send you URL to look not public

**Comment by w00fz** [comment]
You should probably hop in our [Gitter Chat](https://gitter.im/gantry/gantry5), the community is always willing to help in there. I'm there as well, so you can share your link and ask for CSS customizations help.

GitHub doesn't allow private messages and we like to dedicate this more to bugs report than personalized custom work.

Get in Gitter and I'm sure we can help you there :)

**Comment by witzker** [comment]
Great i will do tomorrow evening
THX
