### ISSUE TITLE
WPbakery Visual Composer not working on Gantry 5 

### ISSUE THREAD

**Issue by Mohika** [gantry/gantry5#923]
WPbakery Visual Composer not working on Gantry 5 from front end on pages. Works on posts. I have checked that Visual Composer works fine with any other template.

To explain the issue further: Once you try to edit a page with visual composer it will only load a frame of VC but you will not get the ability to do actual edits. You will not see  edit options on your rows or elements on a page

I tried then to switch the template from Hydrogen to Twenty Fifteen and I got edit options for VC elements on the front end for pages..    Same is happening on all of my 3 G5 sites, one being on a different hosting. But the fact that VC front edit works on posts even on Hydrogen but it doesn't on Pages tells me that it must be due of some bug with G5

**Comment by newkind** [comment]
I really don't see a reason why it would work on posts but not pages - that's odd. We don't have the access to the plugin but if you want to, we can have a chat on Gitter and I can try to solve your issue.

**Comment by Mohika** [comment]
OK... I will buzz you there :-) ..

**Comment by newkind** [comment]
Looks like Visual Composer doesn't like our call in the `page.php` :
```
$post = new TimberPost();
```
Changing it to the code below fixes the issue :
```
$post = Timber::query_post();
```
