### ISSUE TITLE
Nested loop in particle collection.list

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#924]
Hi,

I've tried to add a collection.list under another collection.list item and it seems the nested loop is not working.

I have here some references of what I will like to do:

http://stackoverflow.com/questions/19183877/twig-nested-loop
http://twig.sensiolabs.org/doc/recipes.html#accessing-the-parent-context-in-nested-loops
http://twig.sensiolabs.org/doc/tags/for.html

If this cannot be done already in some way, can you please add this to the new features?

Thank you

**Comment by mahagr** [comment]
Its not currently supported, but we have some plans on adding support for this.

**Comment by nicutor** [comment]
Great. This is a must need for writing robust particles.

**Comment by nicutor** [comment]
Hi @mahagr , can you please assign this to a milestone?

**Comment by nicutor** [comment]
Thank you @mahagr

**Comment by mahagr** [comment]
@nicutor I was feeling like this:

https://www.youtube.com/watch?v=GwU6fbwrWN0

when I was testing it out. LOL

**Comment by nicutor** [comment]
:)) I can understand you. I can't wait for the next release to come out to test it.

And I can't wait this to be solved too: #1026

Thank you again.

**Comment by JoomFX** [comment]
@mahagr Awesome !!
Thanks Matias :wink:

**Comment by DamirPecnik** [comment]
Thanks!
