### ISSUE TITLE
active menu item problem!

### ISSUE THREAD

**Issue by mikajaxxx** [gantry/gantry5#925]
Hello
when i create a Gantry particle module as Menu.. the menu works correctly but it can't determine which item is active! i mean in other pages still home is active! 
i cleared cache for joomla and gantry also recompiled theme
rt-salient 1.0.2  
joomla 3.4.4
gantry 5.1.6
best regards
Edited: ok i found the problem! i disabled cache for module and the problem have been solved. but you should take a look at this issue and find a better solution.. somebody doesn't know should to do this!

**Comment by mahagr** [comment]
Particles do not have caching so I'm not sure what did you disable..?

**Comment by w00fz** [comment]
Could you elaborate what steps exactly did you follow? What cache did you disable etc?
We do not any type of cache for Particles and Gantry 5 Menu is a Particle.

**Comment by mikajaxxx** [comment]
Hello
yeah particles doesn't have cache..but there is a module named gantry particle ! and it have cache option in advanced tab! so if i use menu as particle in this module it take the default cache and doesnt' updated when changing active menu! 
Best

**Comment by w00fz** [comment]
I cannot reproduce this issue. I tried with both Conservative and Progressive Cache, changed several Menus and saved. On front-end it always refreshed as expected.
Perhaps your server has more aggressive cache, if that's not the case we need more details to be able to replicate the issue, like what are your cache settings, what steps are you following and so on.

**Comment by mahagr** [comment]
Actually by looking at the code, @mikajaxxx seems to be right. If you create a new particle, it is by default cached by Joomla for 15 minutes. I'm going to change the default value not to use cache.
