### ISSUE TITLE
Images in Roketspocket should open in Rokbox 

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#927]
I have installed
Roketspocket 
Rokbox
RokGallery

When i klick on a image in RokGallery it is opened in popup i think this is Rokbox
When i klick on a image in Roketspocket nothin happens.

Is there som configuration to do that this is working.

In dokumentation of rockbox
http://www.rockettheme.com/docs/joomla/extensions/rokbox
is witten on bottom
If everything worked properly you will get a success message notification. You can customize both plugins accessing from: Extensions -> Plugin Manager, where they are listed as Content - RokBox and System - RokBox.
I have them there
What has to be set to open images from roketspocket as rockbox popups with a click on image

**Comment by w00fz** [comment]
You should direct the questions regarding Extensions to the proper RocketTheme forum. Dan created a tutorial for doing so.

Have a look: http://www.rockettheme.com/forum/joomla-extension-roksprocket/199429-rokbox-in-a-roksprocket-layout

**Comment by witzker** [comment]
I am no member there 
Could you please advice another free forum with people haveing  knowledge about this
Many thanks
Witzker
