### ISSUE TITLE
Outline assignment improvements for Custom Post Types

### ISSUE THREAD

**Issue by Matt-Yorkley** [gantry/gantry5#928]
Currently on the assignments page for an outline, the options are a bit limited for assigning to Custom Post Type pages in Wordpress.

Specifically, if I have a CPT with a number of categories, I can assign an outline to individual category archives for that post type, but I can't assign an outline to all category archives. So if I currently have 3 categories of a given CPT, I can assign an outline to those 3 specific categories, but if I later add some content with a new category, I have to go back and manually change the outline assignments every time. 

When this is multiplied out across many outlines and many custom post types with dynamically changing content, it makes it impossible to manage.

**Comment by Matt-Yorkley** [comment]
In fact, the ability to assign to single posts per CPT is exactly the same. 

So for instance for the CPT "products", I can't assign an outline to all product category pages, or to all product pages.

**Comment by w00fz** [comment]
I believe this is the same request as #771

**Comment by dudewithamood** [comment]
I second this. Although, the way I imagine it is to have under the Page Context section options for each CPT e.g. Single Product, where Product is a CPT.

**Comment by newkind** [comment]
This is most likely the same as #1298 so closing it too.
