### ISSUE TITLE
menu editor - pick a module publish/unpublish info display issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#93]
when using the menu editor and adding a module, the published/unpublished info popup is not being displayed correctly on the modules listed at the very top.

please see pic for better explanation.
![g5_pick a module](https://cloud.githubusercontent.com/assets/5719486/7240636/29313638-e778-11e4-96f8-f3d549934642.jpg)

**Comment by w00fz** [comment]
Ok this is sorted. Showing the tooltip below and within the block now

![bottom tooltips](https://cloud.githubusercontent.com/assets/11734/7244217/15676e0a-e78d-11e4-9795-46ef2f71a812.jpg)
