### ISSUE TITLE
Gantry 5 website slow

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#931]
I am using hydrogen template.

Just figured out website is very slow.

Are there any tools (like compression or deleting something) to make website fast.
I am not sure if I am missing something from settings.

**Comment by hennysmafter** [comment]
Please let us know if you are using Joomla / Wordpress and on which version you are! I cannot give appropriate support before knowing that.

**Comment by rgblogs** [comment]
I am using Joomla. Everything latest versions and updated.

Thanks for the links, i will check them.

**Comment by w00fz** [comment]
What is your server specs? Are you running Apache? What PHP version?
Also, do you have a link for us to look at?

**Comment by hennysmafter** [comment]
Did you get it sorted? Please let us know then the devs. can close the issue. If it ain't solved then I will be happy to go through your site to see whats what. You can PM me with the details.

**Comment by rgblogs** [comment]
Yes, I migrated to VPS, then slowed down.

But now it is solved, I enabled caching and optimized some more things.

**Comment by w00fz** [comment]
Yeah when sharing hosting resources it's always a possibility to get sites going slow. Gantry 5 is very fast, few milliseconds slower than the platform it's used with, so I'm quite sure you would have had the same issues with regular platform as well.

Glad you sorted.
