### ISSUE TITLE
Vertical slider like a filmstrip

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#932]
Hi
Could you please recomand a modul or plugin to run images like a filmstrip vertical from bottom to top in low speed.
Which has no conflicts with ganty 5 hydrogen

THX for suggestions
Witzker

**Comment by NeonTigerWeb** [comment]
you can do it in RokSproket free from RocketTheme

**Comment by witzker** [comment]
Thx
Maybe my discription was meey
I ment somethin like this
http://www.joomlahill.com/demos/1-images-crawler
But vertical.
Would be great to do this in rokspoket.
I tried many different options but could not get that result
Pls.help me on to get this best with rokspocket
THX
Best wit

**Comment by weredigi** [comment]
Why would you not go back to the site you mention and download it

**Comment by witzker** [comment]
Äh
I meant something like this
http://www.joomlahill.com/demos/1-images-crawler
this modul in the link is - HORIZONTAL - (Left to Right or Right to Left)
i need it to do the same thing but - VERTICAL - (bottom to TOP)
I hope I have expressed myself clear now.
Would be great to do this in RokSpoket!
I tried many different options but could not get that result!
Pls.help me on to get this best with RokSpocket.
THX

**Comment by hennysmafter** [comment]
Sometimes I am really wondering if people look at the JED:

I searched for 2 mins and come up with this: http://www.gopiplus.com/extensions/2011/07/vertical-scrolling-images-joomla-module/#.Vipw5LcrKHs

**Comment by witzker** [comment]
Thx
Gopiplus is ok as example but i would need to put text under the pichture.
RokSpochet in demo looks like there are all available pictures visible in the modul hight.
I have more pictures as suite in the high of the modul like in example gopiplus.
But i will try in RokSpoket.
The idea is to have an article on the left side and the running pictures with discription on the right side in smal column.
My hope is to find someone who already done this to advice me.
Thx for your patience

**Comment by witzker** [comment]
Pity!

**Comment by w00fz** [comment]
Sorry, I closed it for inactivity, but feel free to reopen if you don't want to keep it closed!

However, I would suggest you to join the Gitter chat and bring the discussion over there, mainly because we like to keep GitHub Issues limited to actual issues or quick questions, but also because any other type of support such as discussions on how to implement things, benefit more from a chat rather than comments. In Gitter Chat you will have a bigger audience and an immediate interaction.
