### ISSUE TITLE
help me remove the read more

### ISSUE THREAD

**Issue by akacha** [gantry/gantry5#933]
how do I remove the read more articles with the gantry 5?

**Comment by hennysmafter** [comment]
Please leave some more information like, current version of Joomla/Wordpress and Gantry. Without those basic items I can't help!

**Comment by mahagr** [comment]
In Joomla, "read more" comes from Joomla itself. So looking into Joomla documentation may help.

**Comment by akacha** [comment]
hello is WordPress 4.3.1 gantry 5

**Comment by newkind** [comment]
You can just go to the Content tab and set the Read More Display Mode to Never and they'll be gone. Just be sure to do this for the proper page type ie. Blog or Archive or both.
