### ISSUE TITLE
Adding Icons to the Particles in Layout manager from G5 Admin

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#935]
I guess the title is already saying it. I spoken about this on the chat and received the information that I should create a issue for this so that it wouldn't be forgotten. So here I go. 

Let's add icons to the Particles situated inside the Layout Manager from the Gantry Administrator.

![layout](https://cloud.githubusercontent.com/assets/4426337/10665091/f5c49636-78c8-11e5-8db9-a40fd6e58677.png)

**Comment by w00fz** [comment]
The only problem I have with this is finding the right Icons. We rely on FontAwesome and even though it's a big collections, it is kind of hard to find one that fit every Particle.

Some are easy, like Logo / Image could be the picture icon, Menu the hamburger icon, Date a watch, Social the chat cloud icons.
Others tho, like To Top or Module Instance or Module Position, tough to find one :)

I can try putting some together and post an image here, maybe we can discuss then if all icons make sense

**Comment by hennysmafter** [comment]
If you want to focus on more pressing matters then I can do that picture with icons also? Let me know so that we are not doing both the same thing!

**Comment by w00fz** [comment]
Nice job! I like them. I would just change a few:

1. System Messages -> `fa-exclamation-circle `
2. Logo -> `fa-file-image-o`

    This is because in CI Build (and so next version), "Logo" has been relabeled to "Logo / Image". Reason being that many people just thought that particle was reserved for Logos, which is not the case at all, can be used for any image of any kind!
3. Social -> `fa-share-alt`

Thank you for taking care of it.

**Comment by hennysmafter** [comment]
Alright 1,2,3 are all now in the new fiddle. And I like it I add a picture as well.
http://jsfiddle.net/dvktc6jp/7/

Do you need anything from me to integrate it?

![edit fiddle - jsfiddle - google chrome 2015-10-24 01 11 42](https://cloud.githubusercontent.com/assets/4426337/10706954/7e01164a-79ec-11e5-95a8-fe82ed47ec28.png)

**Comment by w00fz** [comment]
No this is all I needed, I like it and in the next days I'll look at integrating it.

Thank you!

**Comment by rhukster** [comment]
With icons, it might look even nicer left-aligned (with some prodigious left padding though)

**Comment by hennysmafter** [comment]
@rhukster That is a good idea. Makes it look even better. I changed it in a updated fiddle.
http://jsfiddle.net/dvktc6jp/8/

It looks then like this:

![edit fiddle - jsfiddle - google chrome 2015-10-24 02 00 31](https://cloud.githubusercontent.com/assets/4426337/10707463/084f61d4-79f3-11e5-854a-59bc262050ce.png)

**Comment by rhukster** [comment]
How about text left aligned too?

**Comment by hennysmafter** [comment]
Ow was changing my comment. To add some more suggestions. Will check the left alignment now. Will update soon!

**Comment by mahagr** [comment]
Yes, I like the last one the most, too. Icons really help to find the correct particle; lets get this done for Gantry 5.2. :)

**Comment by w00fz** [comment]
What do you guys think?

![particles-picker](https://cloud.githubusercontent.com/assets/11734/10745271/65d3e576-7bfd-11e5-9623-0f4237dba478.jpg)

**Comment by alisamii** [comment]
I  think that's great.

Two questions, would it be possible to make the particles pane collapsible (like how you can collapse the toolbars in Adobe applications to just show the icon with hover text)?

I think it would be great if it could collapse to icons only, with default display showing the icons with the text.

Also, how would we end able to add our own icons to custom particles we build that are not core gantry?

**Comment by w00fz** [comment]
You define the icon in the yaml file:

``` yaml
name: To Top
description: Scroll back to top.
type: particle
icon: fa-chevron-up
```

And yes we will at some point make it collapsible, but for that we need to rework the UI quite a bit and it takes time. At the moment we are wrapping up for 5.2 with the Page Settings and Layout Yaml syntax new features.

**Comment by w00fz** [comment]
Ok this is now implemented. All Particles that don't have an icon defined, will fallback to the `cube` icon, as you can see from my screenshot above, i didn't have an icon set for Module Position and Module Instance (they are using a proper icon now).

**Comment by hennysmafter** [comment]
I am not following this. Could you upload a pic as how it is now. Are there now cubes for both module types? Was there something wrong with the icons in my last fiddle? I got them from Fontawesome!

**Comment by w00fz** [comment]
It is with the two group icons, I was just saying that the default icon, for custom particles or particles that don't have this new icon field, will default to cube.

// Djamil Legato // From iPhone //

**Comment by hennysmafter** [comment]
Yeah, I understand that now. As I said in my previous comment it was my mistake! Regarding the last 3 navigation pictures should I create a new issue as this one is closed?

**Comment by w00fz** [comment]
These are now added in the LM as well.

**Comment by hennysmafter** [comment]
Looks brilliant! Thank you this will make it so much easier. I do see however that some of the already set items inside LM don't get the right icon but fall back to the default. I attach a picture. I upgraded from CI built to CI build.

![gantry52ci - administration - google chrome 2015-10-27 21 46 31](https://cloud.githubusercontent.com/assets/4426337/10772052/532e98a6-7cf4-11e5-87fd-0fc9e21576c0.png)

When you add new items it shows the right one. But can't save:

![gantry52ci - administration - google chrome 2015-10-27 21 49 28](https://cloud.githubusercontent.com/assets/4426337/10772110/a36411e8-7cf4-11e5-8915-d7360cf95625.png)

I believe this error is however already mentioned in the chat!
