### ISSUE TITLE
feature Request in Styles

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#939]
I am using Joomla. it will be nice to have following in Styles:

- Color picker to change background color of sidebar sections
- Color picker for background color, text color and hover in menu
- Different font for menu with option to all caps

Under menu, ability to have different colors for different menu.

**Comment by mahagr** [comment]
The available styling options come from the theme and different themes may have different options. Are you talking about Hydrogen here?

**Comment by rgblogs** [comment]
Yes. Hydrogen in Joomla

**Comment by w00fz** [comment]
I agree, it might be something we could expand in the future if/when we decide to refresh Hydrogen, but as it is now it serves as blank canvas to build your own template and it's not meant to do everything and anything everyone wants.
Each template will always be designed in a certain way and provide more and different features than another, Gantry 5 is the framework that allows to do so and Hydrogen is the starting point.

Our goal with Hydrogen is to still keep it fast and clean and although your suggestions would make a great set of options for a template, they are very specific uses that I don't think they will fit Hydrogen.
