### ISSUE TITLE
Menu editor - Particle settings will return 404 error 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#94]
If you go to Menu Editor -> add a particle -> then select social particle -> click config button ->  at social items -> add a new item, then if you click the new item, instead config page you will get a 404 error. 
Is the same for sample content .  Take a look at pictures so you will understand what i mean. 

![menu editor particle](https://cloud.githubusercontent.com/assets/9744973/7241132/62ab47ae-e7bf-11e4-949e-c00d1108603b.PNG)

![menu editor](https://cloud.githubusercontent.com/assets/9744973/7241139/696be7a6-e7bf-11e4-9eff-3cca780b868c.PNG)

@mahagr @w00fz

**Comment by w00fz** [comment]
The URL for the collections in the menu editor seems to be wrong.
