### ISSUE TITLE
Implementing Fixed Navigation/Header on Scroll

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#940]
I found This
http://gantry.org/blog/fixed-navigation
I'm not clever in editing CSS and other Files
Is there  a more easy way to do only some entries in the Backend in the meantime?
in other templates i found the option Fix header
is there a similar simple thing in Gantry 5 Hydrogena
 I have this set in Options

![header options](https://cloud.githubusercontent.com/assets/4120266/10710298/f154bcf2-7a53-11e5-9e44-3e0e1f47fea3.png)
can I do it from here?

THX for help

**Comment by mahagr** [comment]
Hydrogen doesn't have fixed header option.

Some people have already done fixed header for Hydrogen, so you may want to ask this in Gitter chat: https://gitter.im/gantry/gantry5
