### ISSUE TITLE
'Gantry: Please set current configuration before using $gantry["config"]'

### ISSUE THREAD

**Issue by achataing** [gantry/gantry5#942]
When I install and activate any social login plugin (I Have tested several ones) I receive this error when a new registration (sign up) is being made:
"Fatal error: Uncaught exception 'LogicException' with message 'Gantry: Please set current configuration before using $gantry["config"]' in C:\Users\TraductorACA\Documents\MEGAsync\MEGAsync\revistacastings.com Localhost\wp-content\plugins\gantry5\src\classes\Gantry\Framework\Services\ConfigServiceProvider.php:35 Stack trace: #0 C:\Users\TraductorACA\Documents\MEGAsync\MEGAsync\revistacastings.com Localhost\wp-content\plugins\gantry5\src\vendor\pimple\pimple\src\Pimple\Container.php(113): Gantry\Framework\Services\ConfigServiceProvider->Gantry\Framework\Services{closure}(Object(Gantry\Framework\Gantry)) #1 C:\Users\TraductorACA\Documents\MEGAsync\MEGAsync\revistacastings.com Localhost\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php(469): Pimple\Container->offsetGet('config') #2 C:\Users\TraductorACA\Documents\MEGAsync\MEGAsync\revistacastings.com Localhost\wp-content\cache\gantry5\g5_hydrogen\twig\8\7\877e7a54a485e2403254543d191c54acf6443699c920aadc2bff8fe1859a5365.php(143): Twig_Template->getAttribut in C:\Users\TraductorACA\Documents\MEGAsync\MEGAsync\revistacastings.com Localhost\wp-content\plugins\gantry5\src\vendor\twig\twig\lib\Twig\Template.php on line 182"

I do not really know how to fix this... It appears that the way things are handled within gantry 5 makes it incompatible with social plugins that add a registration using social buttons
Thanks in advance for any help on this matter

**Comment by mahagr** [comment]
Can you send a link to some free plug-in with this issue so we can test this out?

**Comment by NlGhT** [comment]
Apperently I was wrong regarding this issue being related to social plugins... It is an issue that happens regardless of the activated plugins... I deactivated all plugins on the site and it still appears... 

I do not know why this is happening... But the "register" button in the wp-login screen (which redirects to wp-signup.php) displays this error... I do not know how things are handle whithin gantry, and I have not yet used anything similar to this before

I must say I love gantry, it looks and feels as a premium (or even better) theme... But the way things are done scape my current wordpress knowledge...

If a person does a fresh wp install and sets a multisite and allows registration, does gantry work?, thanks in advance

**Comment by NlGhT** [comment]
Let me add the following... After deactivating the gantry framework and trying to register a new account, this is what happens: http://prntscr.com/8voxj6

Since I haven't setup registrations before, I am not familiar of the ways things are handled... Which means that I was expecting some sort of backend registration... This is not true in my site (is it a normal wordpress way to register?)
PD: No other plugins or themes are active
PD2: Is there a way I can get some guidelines of how to implement this into Gantry Hydrogen Theme so that it is also compatible?
Thanks in advanced

**Comment by mahagr** [comment]
I'm learing more about WP every day as well, mostly because of I've never worked with WP before this summer. Because of that we have made some mistakes based on the assumptions we had on WP, but as we see new issues, we are fixing remaining issues.

I'm letting our WP expert to reply on your questions.

**Comment by newkind** [comment]
Ok, so let me clear this one a little bit - so the issue (error) appears only on the registration page when wordpress is set to be a multi site environment right?

**Comment by NlGhT** [comment]
To answer your question I did the following tests Tests:
1) Single install (not multisite, it woks fine): http://prntscr.com/8vwy1q | http://prntscr.com/8vwyme | http://prntscr.com/8vwz5c
2) Multisite install (only gantry framework, hydrogen and timber): http://prntscr.com/8vwzwm | http://prntscr.com/8vx0ej | http://prntscr.com/8vx15z

The screenshots explain it themselves... 
To add to the pictures: http://prntscr.com/8vx2v6 | http://prntscr.com/8vx375 | http://prntscr.com/8vx4lp

**Comment by newkind** [comment]
Ok, looks like there are some fixes needed for the Multisite. I won't be able to make them for the 5.2 but they should be here with the next update after 5.2

**Comment by blizam** [comment]
More details on this issue can be found here: http://www.rockettheme.com/forum/gantry-for-wordpress/261904-gantry-throwing-error-on-account-activation

-----------------

An exception has been thrown during the rendering of a template ("Gantry: Please set current configuration before using $gantry["config"]") in "@nucleus/page_head.html.twig" at line 8.


Fatal error: Uncaught Error: Class 'Gantry\Framework\Gantry' not found in /.../public/wp-content/themes/rt_interstellar/header.php:18 Stack trace: #0 /.../public/wp-includes/template.php(572): require_once() #1 /.../public/wp-includes/template.php(531): load_template('/.../users/dev1...', true) #2 /.../public/wp-includes/general-template.php(45): locate_template(Array, true) #3 /.../public/wp-activate.php(67): get_header('wp-activate') #4 {main} thrown in /.../public/wp-content/themes/rt_interstellar/header.php on line 18


This prevents Gantry themes from being able to be used in a WordPress Multisite environment where any site needs to have user accounts created/activated

**Comment by dudewithamood** [comment]
Hi, what's the status on this one? Is there any workaround? Thanks...

**Comment by dudewithamood** [comment]
I'm getting the same error for wp-activate.php in Wordpress multisite install.

**Comment by achataing** [comment]
May this comment serve as a guide of a workaround to this issue. For those who love Gantry and Multisite:

1. Make sure you install wordpress using any Other domain name than the one you are planning to use Gantry. It could be a free domain, and the name may suggest it's used for registering. Something like: http://mydomainaccess.gq you may do this clicking this link: http://freenom.com

- What is the purpose of this?... 

After you have installed Wordpress on this domain, you will be able to create new sites with your Original domain using a couple of plugins: _This assumes now that you have 2 domains with correctly configured DNS Nameservers pointing to your hosting account one being mydomainaccess.gq and mydomain.com _

- Download, install and Network activate https://wordpress.org/plugins/wordpress-mu-domain-mapping/ _**Note:**_ to properly install this plugin you must **copy** **_sunrise.php_** that comes inside this plugin and move sunrise.php into **_wp-content/_**. If there is a sunrise.php there already, you'll just have to merge them as best you can. Edit **_wp-config.php_** and uncomment or add the SUNRISE definition line. If it does not exist please ensure it's on the line above the last "require_once" command. **_define( 'SUNRISE', 'on');_**

The last lines of your wp-config would probably look like this:

 ```
/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'mydomainaccess.gq');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

/* Domain Mapping */
define( 'SUNRISE', 'on' );


/* That's all, stop editing! Happy blogging. */
```
(My install is on subdomain install thats why it says "SUBDOMAIN_INSTALL")

- Login to your hosting account and **add** the alias or parked domain "mydomain.com" with no redirection and pointing to the installation of your wordpress "public_html/" or "public_html/wordpress" or "www/" or whatever your hosting has for you.

-Now go to network dashboard to add a new site within the backend... 

Under **Site Address (URL)**, put a subdomain (my case, needs a wildcard subdomain *.mydomainaccess.gq) or put your new site URL like: mydomainaccess.gq/mydomain

Fill in all the info: Site Title, Site Language, Admin Email (I suggest having a super admin, which is putting the same email here of the session you are now), then click Add site.

Now, your new site is: **mydomain.mydomainaccess.gq** or **mydomainaccess.gq/mydomain**

-Go to Network Dashboard and then to the plugin Domain Mapper under: Domain Options
check Remote Login, Permanent redirect (better for your blogger's pagerank), User domain mapping page, Redirect administration pages to site's original domain (remote login disabled if this redirect is disabled)... Leave this unchecked:
 Disable primary domain check. Sites will not redirect to one domain name. May cause duplicate content issues.

-Now, go to Domains under Network Settings and Add the domain for the new site there like this:
New Domain: http://mydomain.com
Site ID (you must check your site ID by going to "all sites"--- and when you put the mouse over "edit" button, the link has ID=""... get the ID there)
Primary (Check only for one)

Do the same for http://www.mydomain.com this will help your google

In order for this to work you must have a non-gantry theme activated in http://mydomainaccess.gq and Gantry theme active in http://mydomain.com

Since http://mydomain.com is actually a mapped http://mydomain.mydomainaccess.gq or http://mydomainaccess.gq/mydomain, when you click on "Register" you will be redirected to: http://mydomainaccess.gq/wp-signup.php and the Theme that will appear will be the one chosen for this site... So the look and appereance of this place where people register new Sites can be modified via Theme/Plugin... Since its Theme dependent, you must choose a theme that looks well for registering sites...

So in conclusion: You have Theme Twenty Sixteen on http://mydomainaccess.gq (free) and a Gantry theme on http://mydomain.com

It is possible to replicate the same behavior on mutiple networks:
- Download, install and Network Activate https://wordpress.org/plugins/wp-multi-network/
**Comment out the DOMAIN_CURRENT_SITE line in your wp-config.php file. If you don't have this line, you probably need to enable multisite. >> https://codex.wordpress.org/Create_A_Network **


-What is the purpose of this again?
Provided you need this, you can create new networks directly adding new domains and this new network will have all the features you need to replicate this steps again, you just need 1 free Domain for the new Network, and 1 new site with a new Domain. Sunrise.php from Domain mapping pluging works well with multi-network, and it helps when a new domain is registered for the other plugin wp-multi-network

-Now go to network settings and "Allow new registrations"

- Dowload Install Gantry5 & Gantry Theme

- Download and install Gantry Framework
- Download and install Gantry Theme and Network Activate it (You now have 2 themes to choose for your sites) but remember to activate the gantry theme only on your secondary site... not your first

PS: Final note

When adding Domains please remember that:
1- When you add a new "Network" you want to use a freenom.com Domain like (.gq .tk .ga .ml) using the input field they have there
2- When you add a new "Site" you want to just either a subdomain to create it, or a subfolder structure... and then, you go to network, and assign a paid Domain like .com .org etc, with its www. and setting up the primary one... (usually mydomain.com over www.mydomain.com)

**Comment by dudewithamood** [comment]
@achataing Thank you for this comprehensive reply. It's taken me a while to respond - I think the first time I read it I panicked and stuck my head down a hole.

I've come back to myself now and have reread your instructions carefully. My multisite is already set up and functioning (with the exception of registration) so I'm very cautious about making any fundamental changes.

If I were to distill this to its essence, would I be correct in saying that the crux of making this work is to use a non-Gantry theme for the registration component?

**Comment by achataing** [comment]
That is correct. The crux to making this work is to use a different theme for the registration on Multisite, however, when one decides to go all in for a project with gantry, it is best to do as the guide says for several reasons:

1) When you organize your website you want to allow registration with gantry and gantry cannot do it
2) When your main domain is www.mydomain.com and this IS the main site and THIS site has Gantry, it won't work
3) after Setting the MAIN SITE of the Multisite, it would have a theme other than Gantry and it would not be www.mydomain.com BUT www.registermydomain.com 
4) after having the MAIN SITE be www.registermydomain.com you can create another site with you www.mydomain.com and activate gantry and everything.... So you will achieve the following:

1- a user would go www.mydomain.com, then he would fall in love with ur site and create a newone for himself/herself and click "register"
2- the user would be automatically redirected to www.registermydomain.com and successfully register a site

**Comment by mahagr** [comment]
I think I know what's going wrong here, but I really need a multisite to test it with.

**Comment by achataing** [comment]
I suggest using Ampps + fiddler to emulate subdomains using the HOST attribute

**Comment by dudewithamood** [comment]
I'll see how quickly I can set something up for you - bare basics though, won't be a replication of what I already have.

**Comment by dudewithamood** [comment]
@mahagr Have sent details in PM on Gitter. @achataing (or anyone else) Let me know if you'd also like access... it's network enabled with sub-domains and the only two things installed are Gantry5 (network enabled) with the Hydrogen theme enabled on main site.

**Comment by mahagr** [comment]
@dudewithamood Should be working in the latest CI build (loading default outline).

**Comment by dudewithamood** [comment]
Ok, tested on my temp environment and on my live environment :-o - have been able to perform a complete end-to-end new site registration.

Very, very, very pleased. Thank you @mahagr and @achataing 

Just some points from mahagr (which I haven't tried yet):

> it uses hardcoded header and footer files, so if you want to change outline, you need to do it manually
> if you want to change the outline you need to create new file into theme
> copy the normal header.php and add $theme->setLayout('xxx'); after line 21 where xxx is the outline name
> i think the file is header-wp-signup.php
