### ISSUE TITLE
Admin Pages doesn't render correctly 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#943]
Version: dev-28d58c9c4 / Released: October 26, 2015

Gantry Admin pages doesn't render sometimes, you have to refresh the page and try again.

```
XMLHttpRequest cannot load https://c9.io/_user_content/authorize?redirect=http%3A%2F%2Fworkspace-adi8i…%26theme%3Dgp_bless%260759d0ddc03cad483116aceddb80e491%3D1%26format%3Djson. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://workspace-adi8i.c9.io' is therefore not allowed access.
```

![capture](https://cloud.githubusercontent.com/assets/9744973/10729187/67cf9ac6-7bf0-11e5-9793-b221803be143.PNG)

**Comment by hennysmafter** [comment]
I can confirm this behavior. I have tested this on a test environment and I got a equal message when server experiences heavy load. Or as other say is being stressed.

**Comment by w00fz** [comment]
I think the JS hasn't been recompiled properly after the merge. Should be good now.

**Comment by adi8i** [comment]
I still have this issue, could be something wrong on my end?

**Comment by mahagr** [comment]
You cannot go back to G5.1.6 after using latest CI (5.2) build.

**Comment by w00fz** [comment]
@adi8i that is not an error, it's output on purpose. Shows the flat list representation of the layout. I had it on for debugging and it's off in the latest CI, nothing to worry about.

**Comment by adi8i** [comment]
Yeah, anyway i see my issue is related to c9, if the workspce is set as private will pop-up that modal... Probably they changed something.
