### ISSUE TITLE
Admin css conflict

### ISSUE THREAD

**Issue by Matt-Yorkley** [gantry/gantry5#944]
I tried to use Gantry5 with the Piklist framework plugin, the Gantry5 theme editor breaks and becomes unusable, as for some reason it fails to load it’s CSS properly. Deactivating the Piklist framework solved the issue.

After a lot of testing, I found the conflict was caused when Piklist loaded and enqeued it's “admin.css” file. I also discovered that renaming the file to “piklist_admin.css” and updating the path fixed the issue.

Seems like both frameworks were loading an “admin.css” file at the same time, which normally shouldn’t be an issue, but the id tag on the script was also being set as id=”admin.css” on both. It seems Gantry5's admin.css file lost out, as Piklist loaded it's file with an explicitly higher priority (100 instead of the default 10). I found it strange that WP doesn’t resolve that issue automatically while enqueueing…

I image you might get the same conflict in the future with other frameworks and plugins, though. Renaming the file to "gantry-admin.css" and updating the links in the twig templates fixes the conflict.

**Comment by w00fz** [comment]
I think it only makes sense to prefix the `admin.css` with `g-` or. `gantry-`. Will take care of it, thank you for reporting this.

**Comment by newkind** [comment]
I haven't replied to this as I'm not sure if the issue is not the Piklist loading it's styling on all admin pages rather than only the required ones. Anyways, prefixing things can make it only better ;)
