### ISSUE TITLE
Particle Module edit issues when accessed through menu item manager

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#945]
I went to > Menu > Mainmenu > Home and checked the Module Assignment tab.
From there I am trying to access a Gantry 5 Particle module and edit it. It first opens fine in the popup, but when I then click on the 'Edit Particle' option, not all settings are accessible. Please see pic.

![g5_particlemoduleedit](https://cloud.githubusercontent.com/assets/5719486/10730517/b9f65010-7bf0-11e5-8a84-9c5056569818.png)

**Comment by hennysmafter** [comment]
Which particle did you select first? I am trying to recreate!


![gantry52ci - administration - menus_ edit item - google chrome 2015-10-26 17 58 53](https://cloud.githubusercontent.com/assets/4426337/10736041/3ce4bd8a-7c0b-11e5-9d60-8c7d0b62910f.png)

**Comment by w00fz** [comment]
We discussed this internally and has been solved.
