### ISSUE TITLE
Particle names being randomized after save/close/load

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#946]
`dev-28d58c9c4`
Particles are assigned random names. Not at first but after reloading the administrator.

Recreate:
1. Open template > Layout
2. Add particle
3. Save (after save still correct)
4. Close G5 Admin go to anywhere
5. Return to template manager
6. Open template > Layout
7. Random number showing. 

![gantry52ci - administration - google chrome 2015-10-26 18 05 20](https://cloud.githubusercontent.com/assets/4426337/10736528/c2ed4c6a-7c0d-11e5-983f-cb406459ee24.png)

**Comment by mahagr** [comment]
This should already have been fixed except for the saved layouts, which will remain broken.
