### ISSUE TITLE
Append Class to Body by Param in URL

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#949]
Kat gives this idea. In our G4 template, we can choose to demo our Menu options by appending some params in the URL:
For example: 
http://demo.rockettheme.com/live/joomla/acacia/features/menu-options?menu-type=dropdownmenu
and then the menu-type-dropdown menu will be appended to the body class.
Screenshot: http://pleaselook.at/Menu_Options_2015-10-26_17-57-55.jpg
Could you please help to add this in G5?

**Comment by w00fz** [comment]
I don't think has come up anymore and that kind of feature has always been something we needed only internally for showcasing our demos.

I don't believe this would add anything beneficial to the Gantry framework itself and we could probably handle this via a custom plugin that we use for ourselves only. So, for the time being, I'm going to go ahead and close the issue.

@mahagr, if you think this is still something worth of keeping open for the future, feel free to reopen.
