### ISSUE TITLE
Menu Editor does not keep the changes

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#95]
The video below explains it all :)

https://youtu.be/uKDq6hfwtLI

**Comment by w00fz** [comment]
This was discussed in the Gitter chat. 
The confusion resides in the fact that in the Menu Editor it's always the default menu set in joomla to load, changing from the dropdown and saving will not change that.

To use a different menu on frontend, it has to be changed from the Settings or Layout in the Menu Particle.
