### ISSUE TITLE
Copyright particle in Gantry 5 core contains fixed literal "Copyright"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#950]
The copyright particle in Gantry 5 core contains a fixed literal "Copyright" instead of a language constant (or a setting in the particle). This should be change to provide support for multi-lingual sites.

![2015-10-27_11-50-48](https://cloud.githubusercontent.com/assets/11683218/10757182/0e8c4eee-7ca1-11e5-850d-63e7e7c8ea90.png)

**Comment by w00fz** [comment]
I tried to implement this for both Copyright and To Top Particles but it looks like we aren't loading any translation language on front-end, so they don't get picked up.

**Comment by marktaylor46** [comment]
I don't know whether it's the same thing or not but I know in some of the other particles we have added our own literals as part of the module settings (e.g. simplecounter, newsletter). Maybe we need to do the same here - but personally I would prefer a proper language constant be used.

**Comment by ramon12** [comment]
Why do you need translation for this? Why do you use Copyright text and copyright symbol on same row? Use only symbol or text.
Sounds like this: SiteName Copyright Copyright 2015
Better this: Sitename © 2015 , another accepted way is: Sitename (C) 2015
<?php echo $sitename; ?> &copy <?php echo date('Y'); ?>

**Comment by w00fz** [comment]
I like that *ghost*'s suggestion, so even though it's been a while, I have now changed how the particle renders.

Before: `Copyright © 2016 SiteOwner`
After: `SiteOwner © 2016`

Looks much cleaner and it's not redundant with the double Copyright meaning, as ghost pointed out.

Thanks!

**Comment by mahagr** [comment]
Yeah, it looks much better like this. No need to translate anything and much cleaner, too. Nice!
