### ISSUE TITLE
problems with timber

### ISSUE THREAD

**Issue by akacha** [gantry/gantry5#951]
I have a version of PHP 5.4 gantry and the timber is giving me problems, how to fix?

Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in /home8/estetic8/public_html/wordpress/wp-content/plugins/timber-library/timber.php on line 17

Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /home8/estetic8/public_html/wordpress/wp-content/plugins/timber-library/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/usr/php/54/usr/lib64:/usr/php/54/usr/share/pear') in /home8/estetic8/public_html/wordpress/wp-content/plugins/timber-library/vendor/autoload.php on line 5

**Comment by akacha** [comment]
sorry the site is hosted in Bluehost and the server appears to be configured with PHP 5.6, but is actually running is with the php 5.2, the force by the .httacces but also can not view the site properly with the gantry

**Comment by akacha** [comment]
I resolved by forcing the version .httacces:
AddHandler application / x-httpd-php .php5 php56 .php4 .php3

Now what happens to me is that in the header is a lot of information that I did not put or at least not conscientemete.

Site: http://www.esteticaysalud.com.ve/wordpress/

**Comment by w00fz** [comment]
Which informations are you referring to in particular?

**Comment by akacha** [comment]
a widget that is placed at the time of migration, although I resolved! thank you very much anyway
