### ISSUE TITLE
Old "Page Content" YAML syntax not converted automatically

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#952]
@mahagr It seems you have changed the "Page Content" particle with the new layout syntax.
Previously it was called with `- pagecontent` and now it is called with `- system-content`.

Old Syntax:
```
  main:
    container:
      - position-breadcrumbs
      - system-messages
      - pagecontent
```

New Syntax:
```
  main:
    - position-breadcrumbs
    - system-messages
    - system-content
```

@w00fz said that the old syntax should be converted automatically but it isn't. Just install the latest CI build of Hydrogen, go in the LM for the "Default" outline and you will see what I mean.

**Comment by w00fz** [comment]
Thanks for opening the issue @JoomFX
