### ISSUE TITLE
WordPress - Content Features Suggestion

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#953]
1. Define a "Leading Post" and number of "Intro Posts" and number of columns that the intro posts would use
2. Control the number of post shown per page in an Archive/Category

RocketTheme Users are asking about this, also would be good if we can have some sort of switch so if the post count is not set to use the WordPress one in Settings!

**Comment by newkind** [comment]
1. When we created the Hydrogen we decided to not do this and go with simple blog layout - if someone want's it, he can just add it ;)
2. To be honest I like it the way it is, where it's controlled by WP core. Again if someone wants it - he can just add this to their site - 2 lines of code : https://github.com/jarednova/timber/wiki/Timber-docs#get_posts

Closing
