### ISSUE TITLE
Question about module class suffixs

### ISSUE THREAD

**Issue by Sanderluc5** [gantry/gantry5#954]
Does gantry have module class suffixs to use?
I saw this page but these suffixs dont work:
http://demo.gantry-framework.org/features/module-variations
Are there any other available?

**Comment by w00fz** [comment]
Hello @Sanderluc5,
first of all, let me just tell you the demo you are looking at is for Gantry 4 and not Gantry 5 so none of those variations or that documentation will work with our current and latest Gantry 5 version.

That said, suffixes are called variations in Gantry and they do work. Gantry implements a core functionality to enable templates to add their variations, for this reason it is each template to decide if and what variations to provide.

Hydrogen comes with a few different variations, `Box X` for colored boxes and effects such as **shadow**, **rounded** etc.
When you are in the Layout Manager you can click the cog wheel of a Particle (ie, Position) and in the Block tab you will see the Variations field that lists all the variations a themes comes with.

You can also look at the supported Variations from `templates/<template name>/gantry/theme.yaml` in which you will see a section for `block-variations`. For instance, these are the variations for hydrogen: https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/joomla/gantry/theme.yaml#L59-L78

Hope it answers your question.

**Comment by Sanderluc5** [comment]
Got it thanks :)
