### ISSUE TITLE
Continue Shopping button pops up every time a purchase is made

### ISSUE THREAD

**Issue by nextstepsyep** [gantry/gantry5#955]
Thanks for such a great plugin!!!  You guys did a great job explaining how to get the Continue Shopping button to appear on the page without any products in the cart that I was able to pop that puppy on there in one swoop.  Unfortunately, my newness to coding made me add the code prematurely as the Continue Shopping button actually showed up on the next screen during the checkout process so it wasn't necessary to add it. Secondly I have no idea how to find where I added the extra code to remove it without disrupting my store.  Outside of the extra Continue Shopping buttons, everything else is working perfectly! Can you help me remove the code that adds the Continue Shopping button to the top of the screen every time a product is added to the cart?
![stem exchange screen capture](https://cloud.githubusercontent.com/assets/15329521/10817292/3b6c8360-7e0f-11e5-8599-14ff1b2d8eea.png)

http://nextstepsyep.org/outreach/stem-exchange-2/

**Comment by nextstepsyep** [comment]
Greetings Gantry,

My apologies!  I meant to add this issue to the WooCommerce team.

**Comment by newkind** [comment]
So this is invalid ? :) Should we close it ?
