### ISSUE TITLE
Upgrading Gantry may cause g-container to disappear

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#957]
There have been many user reports where site has suddenly become full width after upgrading from 5.1.x. The issue is caused by missing g-container.

It looks like clearing Gantry cache fixes the issue. So somehow cache wasn't cleared during upgrade..?

**Comment by newjie** [comment]
I did have this problem. After purging cache g-container comes back

**Comment by mahagr** [comment]
Looks like the cache isn't being cleared on upgrade...

**Comment by Hertak** [comment]
i have the issue when i upgrade gantry, then i upgrade the template and the problem was fixed. 
I use a renamed templated.

**Comment by w00fz** [comment]
This has been fixed and will be in 5.2.1
