### ISSUE TITLE
Twig_Filter_Function

### ISSUE THREAD

**Issue by ccwebdesign** [gantry/gantry5#961]
With strict error checking, using Twig_Filter_Function causes:
Fatal error: Using an instance of "Twig_Filter_Function" for filter "toGrid" is deprecated. Use Twig_SimpleFilter instead.

in:  gantry5/src/classes/Gantry/Component/Theme/AbstractTheme.php : 101
$twig->addFilter('toGrid', new \Twig_Filter_Function([$this, 'toGrid']));

Fix is:
$twig->addFilter( new \Twig_SimpleFilter( 'toGrid', array( $this, 'toGrid' ) ) );

**Comment by w00fz** [comment]
Thank you!
