### ISSUE TITLE
WordPress - Assignments Bug

### ISSUE THREAD

**Issue by Webthemer** [gantry/gantry5#962]
There is a bug in Gantry 5.2.0 WordPress where ONE Menu item or page etc... can be assigned to multiple Assignments .... This don't have much sense ...

In Joomla the item in previous assignment gets unassigned from it when we assign the same item in current one...

**Comment by kat05** [comment]
looks like the same thing that had been reported here and is actually not considered to be a bug:
https://github.com/gantry/gantry5/issues/607

**Comment by newkind** [comment]
Exactly. This needs to be addressed still. We'll also want to have a particle that would show the applied outlines just like we have in G4. Closing.
