### ISSUE TITLE
5.2.1 breaks the "Gantry 5 Particle" module

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#964]
Hey @mahagr 

It seems that 5.2.1 breaks the "Gantry 5 Particle" module, the particle name is not shown and all particles have the same, default icon. The following screenshot explains it all:

![alt](http://i.imgur.com/f1z8BPP.png)

The functionality works, it is just the representation that is broken.

**Comment by JoomFX** [comment]
The issue seems to come from the changes made in `particle-picker.html.twig` - https://github.com/gantry/gantry5/commit/be77e82cb29fcbf4a6dd8ae139e02f15d1449ea5

**Comment by w00fz** [comment]
That was on purpose, yes, to have icons show up in the Particles Picker. It worked in the Menu when you were dropping a new Particle and Wordpress Widget, but I actually missed the Joomla module.

I hot-fixed the Joomla Package now, which was the only one affected, if you redownload the package manually from the site and install it again on top of your current one, this should be now fixed.

Sorry about that.

**Comment by JoomFX** [comment]
Thanks @w00fz :)
