### ISSUE TITLE
Gantry doesn't recalculate the block widths properly

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#965]
Found this in Requiem : 
https://monosnap.com/file/xbeQ8RdAmHha1A2wHmS2TUVi2MxqFC.png

the issue was in the layout YAML files :
```
 container:
    1:
      - mainbody 60:
        - [position-mainbar-a 33.3,position-mainbar-b 33.3,position-mainbar-c 33.3]
        - pagecontent
      - sidebar 20:
        - position-sidebar
```
Gantry should recalculate those to be 100%

**Comment by mahagr** [comment]
This issue doesn't affect layouts saved in the new format. Old format didn't have proper size calculation, which is OK as everyone was supposed to have columns up to 100% or it didn't work.

**Comment by w00fz** [comment]
So this one is not an issue?

**Comment by mahagr** [comment]
I'm not 100% sure, which is why I kept the issue open. But after my tests it only happened with the old layout files, so at least its restricted to old files, which IMHO had the issue even with older releases as width recalculation in LM was introduced in G5.2.

**Comment by mahagr** [comment]
@newkind I'm not able to reproduce the bug in latest CI (using custom layout in Hydrogen). The above container gets resized to 75% - 25% in both old and new format.

**Comment by mahagr** [comment]
Cannot reproduce anymore.
