### ISSUE TITLE
Newly created outlines won't appear instantly

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#968]
Joomla 3.4.5, Isotope with G 5.2.1 on Chrome
When creating/duplicating an outline it won't appear instantly unless the page is refreshed.

**Comment by sural98** [comment]
I had duplicated outline id=14 using id=13, for example. Now page loads outline id=13 when editing id=14

**Comment by sural98** [comment]
This appears to be a Chrome-only issue.
MS Edge is doing just fine.

**Comment by sural98** [comment]
Nope. MS Edge also needs page refresh.

**Comment by mahagr** [comment]
I am not able to reproduce issue in Linux FF/Chrome. Creating and duplicating stuff works just fine.

**Comment by sural98** [comment]
In Chrome or MS Edge
I am
- loading a layout, say id=13, normally.
- Making changes and saving.
- then going to page settings, for example, or loading another layout
but this time id=13 loads unsaved version.
I need to refresh (F5) to load the saved version.
That is every time I am going back to id=13 layout I need a page refresh.

**Comment by sural98** [comment]
I had experienced a similar one before
Please refer to https://github.com/gantry/gantry5/issues/741

**Comment by mahagr** [comment]
Are you in WP or in Joomla?

**Comment by sural98** [comment]
It is Joomla 3.4.5, Isotope, G 5.2.1

**Comment by sural98** [comment]
FYI. It started after 5.1.5 to 5.2.1 upgrade

**Comment by sural98** [comment]
While experimenting I see that not only layout tab but other tabs are also having this problem.
G5 remembers the first instance of the tab unless the whole page is refreshed. ie F5

**Comment by mahagr** [comment]
@sural98 Do we still have this issue in latest version?

**Comment by sural98** [comment]
This can be closed.
