### ISSUE TITLE
Best Translation Tool for gantry 5 Hydrogen

### ISSUE THREAD

**Issue by witzker** [gantry/gantry5#969]
Hello
need to build multilingual page.
before I was working with falang.

Will this work on Gantry 5 with Hydrogen or is there a better tool without problems?

THX for your advice
Witzker

**Comment by mahagr** [comment]
I don't think that any translation tools work with Gantry 5 particles, which is why we have been thinking of creating our own translation tools for those. Right now you need to create own Joomla styles and assign them to each language, just like you would do with Joomla modules.

**Comment by w00fz** [comment]
ref, #84
