### ISSUE TITLE
Gantry5 Beta 3 wouldn't install on Cygnet RocketLauncher

### ISSUE THREAD

**Issue by WebTread** [gantry/gantry5#97]
hmmm installing G5 beta 3 on a fresh Cygnet RocketLauncher install came up with the following Warning...

JInstaller: :Install: Failed to copy file /home/webtread/public_html/sites/gantry5/tmp/install_553570e92b593/pkg_gantry5.xml to /home/webtread/public_html/sites/gantry5/administrator/manifests/packages/pkg_gantry5.xml

Package Install: Could not copy setup file.

I had tried clearing caches, expired cache and did check in but no dice. It does however install fine on a fresh J3.4.1 install by itself. Which I did after not being able to install it on the RocketLauncher install.

**Comment by kat05** [comment]
hi,

can you manually create the administrator\manifests\packages directory? it seems to be missing from the cygnet launcher and will cause some installations to fail. with the directory added, the gantry5 installation should work fine.

**Comment by WebTread** [comment]
Hi... I'm sure I could but I already deleted that install and went with a fresh Joomla 3.4.1 install. Only installed the Cygnet RocketLauncher to play with Gantry5 any way. But I felt if there was an issue that others were going to have it was best that you are aware of this so it can be addressed in any way needed. Perhaps adding that directory to the Cygnet RL.

Best and thanks for the quick reply.

**Comment by mahagr** [comment]
This looks like a bug in Cygnet launcher, not in Gantry 5. Also the issue doesn't only affect Gantry 5, but a few other extensions as well.

There is not much I can do to fix this issue as the installation fails in Joomla installer, not in our code. That said I can add workaround and create the directory if it doesn't exist.

**Comment by mahagr** [comment]
Update: The issue seems to have been fixed on 6th April, so using a new Cygnet RocketLauncher should result a working site.

**Comment by mahagr** [comment]
Looks like Cygnet fix was never released (until now). Closing this issue here as it is not Gantry5 bug.
