### ISSUE TITLE
Suggestion: Front-end Overlay for Easy Section / Particle Identification

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#973]
During site development, having an overlay that identifies Gantry sections and particles at a glance would be really useful, especially while users are rearranging their layouts and switching back-and-forth, or using a template with pre-configured particles/modules.

Joomla and WordPress have this for modules/widgets, but its usefulness fades with particles and sections in Gantry 5.

**Comment by w00fz** [comment]
I think this is the same as #80 and #423

**Comment by mahagr** [comment]
I agree that this is duplicate for those two issues.
