### ISSUE TITLE
Trap PHP version not meeting requirements

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#976]
This error manifests itself when PHP does not meet Gantry 5 minimum requirements of php 5.4.x +

"Parse error: syntax error, unexpected '[' in /home/viljafra/public_html/adventure/plugins/system/gantry5/gantry5.php on line 97"

I am wondering if there is some way we can trap this and provide a more helpful:
"Your PHP does not meet the Gantry 5 Minimum requirements of PHP 5.4.x"

It keeps coming up in the RT forums over and over.

**Comment by mahagr** [comment]
Djamil seems to have committed fix already in https://github.com/gantry/gantry5/commit/19c1e7940fc3f1dd472421c2697f58bb5973c2e1
