### ISSUE TITLE
Particle module does not cache javascript / css

### ISSUE THREAD

**Issue by muffindcc** [gantry/gantry5#977]
Any javascript files loaded via {% block javascript %} have intermittent behaviour when Joomla APC conservative caching is activated. It will work on first load, then upon refresh, it will not load the requisite javascript files. Can be seen in the Isotope/Kraken/Requien RT templates.

**Comment by mahagr** [comment]
Gantry 5.2 has already module caching disabled for particles by default, which fixes the issue for new modules. I agree that this needs to be improved, but it may not be that easy to implement...

**Comment by marktaylor46** [comment]
I can confirm this issue and it's easy to replicate in Topaz template:

1. Create a "bookblock" particle and publish to a fictitious position called "xxxx"
2. Create a new article and put {loadpotion xxxx} in the article
3. Create a new menu item of type "single article" and choose the article created in step 2.
4. Go to that menu item and you should see the bookblock particle showing up ok
5. now enable "conversative" cache in Joomla Global config .
6. go back to front end and refresh page - you should still see bookblock (whilst cache is being built)
7. now refresh the page again - the bookblock will vanish completely until you clear joomla cache in backend.

I hope that help to track this issue down.

**Comment by mahagr** [comment]
@muffindcc I'm not able to reproduce your issue with a new module, it automatically turns off caching and loads dynamically.

That said, I'm changing the implementation to allow proper caching to speed up the page load.

**Comment by marktaylor46** [comment]
I just test this and it fails for me...

![2016-06-30_13-19-19](https://cloud.githubusercontent.com/assets/11683218/16487877/5395e9be-3ec5-11e6-9f0c-10156dd6cfe7.png)

**Comment by mahagr** [comment]
@marktaylor46 yeah, oops, I didn't test it with multiple modules. Try again.

**Comment by marktaylor46** [comment]
Yaay :) great it works now and does fix the issue I described too :)

**Comment by mahagr** [comment]
Just disable caching with menu particle as its not going to work. I have a branch which adds better caching options for dynamic particles, but its not ready yet.
