### ISSUE TITLE
Missing files after gantry 5.2 upgrade?

### ISSUE THREAD

**Issue by Sanderluc5** [gantry/gantry5#978]
Seems to be a ci build. Update to 5.2.1 solved the problems. Thanks

**Comment by w00fz** [comment]
Those source map files are not intended to be in stable released packages, for both Gantry and Hydrogen, they are only available in the CI Builds, perhaps you installed a CI Build at some point?

I would try redownloading the template and reinstalling manually.

Also note that those 404 are not such a big deal, you can well ignore them. They only show when you have the developer toolbar opened and if you have Sourcemaps for CSS/JS enabled (click on the cog gear in the inspector and you will see options to disable Sourcemaps)
