### ISSUE TITLE
error 500 on saving style changes

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#979]
This is the error I have when I save style changes on Hydrogen

500 Internal Server Error
Oops, Obtaining write lock failed on file: /web/htdocs/www.mysite.com/home/joomla30/templates/g5_hydrogen/custom/config/10/styles.yaml.

**Comment by mahagr** [comment]
Check that Apache is allowed to write to the given file or generally all files in `templates/g5_hydrogen/custom/config` folder.

**Comment by prankyboy** [comment]
ok Thx now it works
