### ISSUE TITLE
saving empty menu column causing issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#98]
please see pic, this happened after i added a 3rd column, then added a module to it and then deleted the module. djamil can replicate the issue too.
![g5_emptymenucolumn](https://cloud.githubusercontent.com/assets/5719486/7243024/4a9d0552-e78e-11e4-8b24-2c592ab815a3.jpg)

**Comment by w00fz** [comment]
Can easily replicate by clicking the `[+]` and hitting Save Menu. After save finishes reload the page and it's blank.
Looks like the columns are saved right but while rendering the group of an empty column is not set and fails to show.
