### ISSUE TITLE
Gantry logo interfering with assignments tab in WordPress

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#981]
Doesn't affect clicking, just looks kinda silly.

![screen shot 2015-11-05 at 8 28 47 pm](https://cloud.githubusercontent.com/assets/4026828/10987753/f572e6d6-83fb-11e5-9659-0763cf5fcad2.png)

Chrome for OS X, window width is roughly 1280 pixels.

**Comment by mahagr** [comment]
Same issue exists in Joomla, too, though with a bit narrower window.
