### ISSUE TITLE
Fatal Error function isCompatible()

### ISSUE THREAD

**Issue by Molly1961** [gantry/gantry5#983]
When installing the Hydrogen theme I am getting the following error:

Fatal error: Call to a member function isCompatible() on a non-object in C:\wamp\www\test1\wordpress\wp-content\themes\g5_hydrogen\functions.php on line 21

On Wampserver
PHP 5.5.12
Curl, OpenSSL Libraries and Multibyte String Support enabled.
WordPress v. 4.3.1

**Comment by alenb** [comment]
Having the same problem here

**Comment by newkind** [comment]
Hi,

This should be fixed with commit 19c1e79. You can apply it manually to g5_hydrogen/functions.php by changing this :
```
if (!$gantry->isCompatible($requiredGantryVersion)) {
```
to this :
```
if ($gantry && !$gantry->isCompatible($requiredGantryVersion)) {
```

Please let us know if it works for you :)

**Comment by alenb** [comment]
Works a charm! Thanks :)

**Comment by mahagr** [comment]
https://github.com/gantry/gantry5/commit/eb325b5102efd27a3d68623df85252d8e96e2419

**Comment by Molly1961** [comment]
Thank you for the quick reply, the fix worked.
