### ISSUE TITLE
Outline Assignments Improvement

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#984]
When you add new pages in the Joomla menu, they are not assigned to an outline unless you go into the G5 outline editor and activate all the new pages, which is tedious.

This issue is basically solved in the Joomla module manager by having the options: On all pages, No pages, Only on the pages selected and On all pages except those selected.

I propose that these same options be added to G5 for the outline assignments. This would greatly reduce the tedium in adding new pages to default outlines.

**Comment by mahagr** [comment]
Joomla does not have such a feature. And it really cannot have one as layouts (outlines) work in very different way from modules, which can be assigned multiple times.

Besides in Joomla when you create a new menu item, you should be able to set outline directly from menu editor page.
