### ISSUE TITLE
Menu editor : grouping of level 3 alters level 2 items

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#985]
A member reported this issue here http://www.rockettheme.com/forum/joomla-template-salient/250034-creating-3rd-level-multi-col-menu-without-affecting-2nd-level-item?start=0#1248695

But I can also reproduced this in a clean Salient rocketlauncher with G5.2.1 with the following steps:
1. Add a new menu item in joomla menu manager of type single article and make the parent for this menu item "overview".
2. Add another new menu item in joomla menu manager of type single article and make the parent for this menu item "overview" too.
3. Go to Gantry 5 Menu editor
4. Click on "features" menu item
5. Click on "overview" menu item
6. Add another column to this third level and drag your second menu item to the second column and save.

If you now go up a level (from level 3 to 2) you will see that an additional column has been added to level 2 (that should not be there) and that it contains the level 3 menu item?
Now if you go back down to level three you will see that thesecond level 3 menu item appears in both column 1 and column 2? Needless to say the frontend is equally broken.

![2015-11-08_10-32-23](https://cloud.githubusercontent.com/assets/11683218/11019849/85fa90aa-8604-11e5-9cbd-24032dc1ad42.png)
![2015-11-08_10-32-46](https://cloud.githubusercontent.com/assets/11683218/11019851/8aef2f8a-8604-11e5-9a70-36fb8165a51a.png)

**Comment by w00fz** [comment]
You are not supposed to be able to drag items between different levels, I'm fixing that now.
Columns always and only refer to the level1, you cannot create level2+ columns, so when you click the + you are actually creating a new column at level1

**Comment by staffiery** [comment]
Are you saying that was not the intended functionality (to have multiple columns at level2+) or that it will not be included in 5.2.2?

**Comment by newkind** [comment]
No, you can have multiple columns on different levels - you just shouldn't be able to directly drag item from one level to another. You should go to a desired level and create a new item there.

**Comment by marktaylor46** [comment]
I will check but I don't believe I did drag any items between levels. I thought I was just dragging items between columns at level 3. For some reason the item ended up appearing at level 3 and level 2.

**Comment by staffiery** [comment]
I was only dragging items to different columns on the same level. The creation of multiple columns on level 3 is being replicated on level 2

**Comment by w00fz** [comment]
Right now it's bugged, you can drag items between different levels, which is not intended to be possible.
And also, you actually cannot have columns at level 2+, columns can only be added at the first level which is always been like this, until 5.2 introduced the issue reported here.

**Comment by staffiery** [comment]
I understand the bug concerning dragging items between levels and that the intended functionality was to only have multiple columns on the first level. My question is will you make the change to allow multiple columns on level 2+ in 5.2.2 or is that not possible?

**Comment by w00fz** [comment]
No that is not possible. Even right now with this bug, the frontend only renders columns at frontend.
The menu as it is, threats 2+ levels as sliding in subitems and we can only support 1 column for that, otherwise it becomes too unpredictable.

Perhaps in the future we will change this but when we implemented it, we thought it through and end up with the conclusion that multi columns should only be allowed at the very first level.

**Comment by w00fz** [comment]
I fixed the bug and made this more clear now, by displaying a badge with the current level one is in. This should make things more easy to see at a glance. Sorry for any confusion with this.

![level badge](https://cloud.githubusercontent.com/assets/11734/11044870/3e2c8ffa-86d9-11e5-8502-a31065d63e9c.jpg)

**Comment by staffiery** [comment]
Thank you!
I will use a multi-column module in that level 2 to create the desired effect.

**Comment by staffiery** [comment]
How do I go about making a feature request for this functionality? (multi-columns on level 2+)

**Comment by mahagr** [comment]
I'm not sure if its worth to make feature request on this as it was an intended decision not to support this feature, mostly because of the logic in the menu is already too complicated because of all the features it has.

In my opinion something like this would be easier to support with separate menu particle designed to support this kind of a set of features. Not sure how menu manager could be adapted to multiple use cases, though..
