### ISSUE TITLE
Custom JS atoms are not working on 5.2.1.

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#993]
I had SmoothScroll.js installed on a 5.1.5 website. Updated to 5.2.1. now suddenly this one atom has become two atoms. But the js was no longer loading on the frontend. So tried removing both of them the settings did not want to save. Then after endless trying I closed my browser and reopened now they are gone.

So now I needed to re add the .js file. So I add it to the page settings tab and press save and guess what. Again it is not saving. So please have a look at this. The only way I could add this smoothscroll.js to the website now is by using a Joomla Module.

**Comment by w00fz** [comment]
There aren't any known issues of this kind, in fact I've seen people successfully using both atoms and assets.
Perhaps you can try the CI Build? Also how are you setting up the atom? If you place it in base outline then make sure the other outlines are not overriding it, like you would do for settings.

**Comment by hennysmafter** [comment]
@w00fz It is almost like you are saying that I am lying. Now I don't think you are but it looks that way. CI build is off course not a good idea on a live website. I have also used atoms and assets successful I was there testing for 520! Remember. This is the first time it happened to me and it happened after going from 515 to 521. During this upgrade it duplicated the one atom I had installed into two that is where the first issue came. This is solved now I think at least it is not showing up anymore. I also figured out that it is saving but I have to restart my browser for seeing any changes. Also only on this website??? So the deleting and saving is solved but now showing at frontend.

So here is what I do:

1. Login to Joomla
2. Go to G5 Admin > Page Settings
3. Assets click on + type in `SmoothScroll Plugin`
4. Open this asset then at file location:
5. I select the smoothscroll.js located at custom/js/smoothscroll.js
6. Apply and Save.
7. Go to frontend and open inspector
8. Search for smoothscroll.js and nothing.

9. I go back to joomla admin.
10. Create a custom html module with no editor selected
11. Add manually smoothscroll.js link inside 
12. Set `on all pages` location `debug`
13. Save and redo step 7
14. Search and immediately found.

As I already said the website is live but I made a duplicate on our production server so if you want I can sent login details by PM. Please let me know as I have to disable some security systems.

**Comment by w00fz** [comment]
I wasn't implying you were lying, why would I think so? I'm just trying to understand the context, since it is a new issue to me.
It must of been a synchronization of files gone wrong, it shouldn't  have created two of those  for starting, and also should have just been saved and starting working. Perhaps just a glitch,.
Was your site set to Production? If yes I take you tried clearing the cache?
Also are you able to reproduce this anymore?

**Comment by hennysmafter** [comment]
Yes this is still happening. The site was on production mode before updating. But this is what I do before updating anything in Joomla Sites.

Backup
Production > Development
Disable GZIP
Clear Joomla Cache with NoNumber Cache Cleaner
Disable Joomla Cache & Plugin
Clear Gantry Cache (just to be sure I do that again)
Update
Test
Enable Joomla Cache & Plugin
Enable GZIP
Development > Production
Rebuild (if necessary)
Clear Joomla & Gantry Cache

On our production site it is still not working on the live website we used a Joomla Module to do it because we can't say to our customer too bad your website goes offline until we figured this one out. While a solution like this keeps the site online only a little bit slower. So it might be a glitch as this only happened on this website but still I want to know how I can fix it off course.

**Comment by w00fz** [comment]
Why don't you PM me on Gitter and provide me with the details of the site, if you can. I can take a closer look.

**Comment by hennysmafter** [comment]
Just sended it to you via PM. I hope I just done something wrong would be a easy fix then :-)

**Comment by hennysmafter** [comment]
So this was my stupid mistake. Because of a overwrite inside `page_head.html.twig`. Once removed (Thank you @w00fz for finding this out!) it was working like it should.
