### ISSUE TITLE
Change box variation colors in G5 Admin Styling Tab

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#994]
Basically the title is already saying it. This might be a nice function. So in the G5 Admin Styling Tab we've got accent colors it would be nice to have here the background colors of the `variation` boxes.

![google chrome 2015-11-10 17 38 48](https://cloud.githubusercontent.com/assets/4426337/11068546/1ea10e82-87d2-11e5-8e2b-7afc6b6d4b35.png)

**Comment by w00fz** [comment]
I personally think this should still be something arbitrary decided by the template developer, whether to expose or not the variations. It is certainly doable but I am not quite sure it is something we want to do for Hydrogen.

Although, I'm going to pass it to @arifinrt and @muffindcc, perhaps even @kat05 in case they have anything else to add to it.

Thanks for the suggestion!

**Comment by hennysmafter** [comment]
Yeah it is something I get a lot of questions from inhouse and customers from to do this also in the template. The same goes with active menu item. So I just thought to let you guys know. I am doing it with custom.scss all the time so not a big deal but for my customers they hate custom.scss it is for them just strange symbols :-)

**Comment by mahagr** [comment]
I agree with @w00fz that this is really a decision that is made by the theme designer/developer as the feature is fully controlled from the theme itself.

**Comment by nicutor** [comment]
@hennysmafter I've fixed this by adding a new section with these colors. 

I must agree with @w00fz and @mahagr that this is something that designer should do. For example, the default number of boxes is 4 and I've added 9 on my templates. Nobody can guess what is in designer mind and what number boxes and colors he will add.

**Comment by hennysmafter** [comment]
@nicutor I also fully agree with @w00fz and @mahagr but I also find that whatever is standard in Hydrogen needs to be easily adaptable by the biggest ...... on the planet. Custom.scss is not as easy as selecting a color picker. 

So really appreciate it that it is been build in. Thank you very much. My customers will love it I am sure.

**Comment by mahagr** [comment]
After some discussion, our new default theme doesn't need the feature either.
