### ISSUE TITLE
Timber caching might be to heavy and "Clear Cache" doesn't affect it

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#995]
I just noticed that after enabling Timber cache the twig files are very heavily cached and I had to actually disable it in core to see any changes in my twig files. Also looks like our "Clear Cache" button is not conneted to Timber cache and it wasn't clearing it.

**Comment by mahagr** [comment]
More information is found from https://github.com/jarednova/timber/issues/399#issuecomment-65052831

**Comment by newkind** [comment]
Partially fixed. When in development mode and you modify twig files in the views/ directory, you still need to manually clear cache.
