### ISSUE TITLE
Gantry 5 Clear Cache fires during every plugin installation/update

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#996]
Gantry 5 Clear Cache fires during every plugin installation/update and not only during the Gantry 5 update.

**Comment by mahagr** [comment]
Thanks for adding this one.

I haven't figured out a way to detect what is being installed as WP doesn't know it itself. When WP is upgrading existing plugin/theme, the information is available, though, but as I would really want to make manual upgrades to work as soon as I can figure them out, I decided not to rely on that information.

**Comment by mahagr** [comment]
Should now happen only with Gantry5 plugin or Gantry template installation/update.
