### ISSUE TITLE
Dropdown menu issue

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#998]
Hy
An item has 3 sub.
Sub1 has other 2 sub

If dropdown style is set on simple I can see all the items on hover.
If dropdown style is set on default or extended  the items under sub1 doesn't appears on hover.
Is it normal or I'm doing something wrong?
![schermata-2015-11-11-a-10 56 32](https://cloud.githubusercontent.com/assets/12469577/11088617/ff120e26-8863-11e5-9271-b87932f15714.jpg)
![schermata-2015-11-11-a-10 56 53](https://cloud.githubusercontent.com/assets/12469577/11088624/01c442c4-8864-11e5-9f3f-903e49a993e7.jpg)

**Comment by mahagr** [comment]
There are two possibilities why the second level doesn't show up.

1. Menu particle is set to display only 2 levels of menu
2. You have CSS issue, likely bad zindex that makes the sub-menu to display in background

Looking into html should reveal which case is true; whether the items are there in the document or not.

**Comment by prankyboy** [comment]
Right. Was a css issue but I'd like to delete the dropdown symbol cos I have too many menu items.
