### ISSUE TITLE
Update package/template: error in Joomla 3.5 Beta1

### ISSUE THREAD

**Issue by Gerlof** [gantry/gantry5#999]
Testing Gantry in Joomla 3.5 Beta1.
Updating Gantry package and Hydrogen template results in error message 'Error Invalid extension update'.

![gantry-update-error](https://cloud.githubusercontent.com/assets/3882884/11088934/441294c6-8866-11e5-8cfd-b7aa0ea210ae.jpg)

**Comment by mahagr** [comment]
Added support for the next version
